### ISSUE TITLE
fail to load tensorflow 1.1.0 inside docker container - libcuda.so.1 missing

### ISSUE THREAD

**Issue by KashiErez** [tensorflow/tensorflow#10073]
Hi,

I ran into this bug while trying to upgrade tensorflow version to 1.1.0
Using 'nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04' docker image (I also tried other docker images as well).

Note that same code runs fine with tensorflow 1.0.0

Attached is python script that prints tensorflow version (see README.txt for instruction of how to build & run the docker image). 
[fail-to-load-tf-bug.zip](https://github.com/tensorflow/tensorflow/files/1016737/fail-to-load-tf-bug.zip)

Here is the stack trace for tensorflow 1.1.0:

```
Traceback (most recent call last):
  File "/run.py", line 3, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Here is the logs for tensorflow 1.0.0: (Here it works fine)
Please pay attention message 'Couldn't open CUDA library libcuda.so.1'
```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 522f0c0e9705
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
tensorflow version 1.0.0
tensorflow git version v1.0.0-rc2-15-g47bba63-dirty
```

Thanks :)
Erez

P.S:
I built and ran the docker image on 2 machines:
* MAC 
    - Docker version 17.03.1-ce, build c6d412e
    - no GPU
* Ubuntu 14.04.5 LTS 
   - Docker version 1.13.0, build 49bf474 
   - GPU info:

```
$nvidia-smi
Sun May 21 11:11:31 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:05:00.0     Off |                  N/A |
| 22%   57C    P8    31W / 250W |      0MiB / 12206MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:06:00.0     Off |                  N/A |
| 22%   54C    P8    21W / 250W |      0MiB / 12206MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:09:00.0     Off |                  N/A |
| 22%   45C    P8    15W / 250W |      0MiB / 12206MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:0A:00.0     Off |                  N/A |
| 22%   36C    P8    16W / 250W |      0MiB / 12206MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+  

```

**Comment by gunan** [comment]
To use GPU docker images, you have to use `nvidia-docker`
Did you start your docker containers using `nvidia-docker`?

**Comment by KashiErez** [comment]
Hi, 
Thanks for the response. 

You are right, running with nvidia-docker works.

But it used to work also with docker (just not using the GPU).
Is there any way to support using docker command line?

I want to explain the motivation:

We use CPU for:
* inference (serving) in production
* train & inference unit tests
* train & inference sanity tests
* developer machines

We use GPU for:
* training in production

Enabling one docker to run both GPU and CPU makes our development cycle simple.
Otherwise for each one of our services we will need to maintain 2 docker images - one of CPU and one for GPU.

Thanks :)
Erez

**Comment by gunan** [comment]
If you want to run the tensorflow-gpu docker image, you have to use nvidia-docker.
Unfortunately, the way the library is built right now, when TF starts running, it will try to load GPU libraries, and on non-gpu machines I am guessing this is failing.

I am not aware if our gpu docker images ever worked without nvidia-docker, could you point me to a version that you can get working? If it used to work, maybe we can get it to work the same way. But I cannot promise anything.

**Comment by KashiErez** [comment]
Hi,

It used to work in version 1.0.0.

Please look in the attachment 'fail-to-load-tf-bug.zip':

In the 'Dockerfile':
- comment the line installing tensorflow 1.1.0
- uncomment the line installing tensorflow 1.0.0

The Readme.txt file for the docker command to build & run.

The 'docker run' command works on 1.0.0 and fails on 1.1.0

Thanks for the help :)
Erez

**Comment by gunan** [comment]
I just tried on my machine, and with 1.0, this is what I see if I use `docker`:

```
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 80869fa6cca4
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  370.28  Thu Sep  1 19:45:04 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 370.28.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
>>> tf.__version__
'1.0.0'
>>> 
```

It does complain about libcuda.so.1, but I do not see an explicit crash. However, when I try to start a session, I see errors:
```
>>> sess = tf.Session()
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:152] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
>>> 
```

So I think the failure was more silent in 1.0, but with 1.1 we crash to avoid further errors.

adding @martinwicke @vrv to see if they have more input.

**Comment by martinwicke** [comment]
I think your diagnosis is correct, this never really worked, it just failed silently. 

However, I think the 1.0 failure mode is a little more subtle: it is possible that TF worked fine assuming you never placed an op on the GPU. 

That means that you could always use a GPU build of tensorflow, independent of whether a GPU (or libraries) were actually available. Now, with a GPU build, you actually need CUDA installed.

I don't think we want to support running GPU tensorflow on non-GPU machines (or rather, non-CUDA machines). I don't see a particularly compelling reason why you would want to do that.

**Comment by KashiErez** [comment]
Hi,

It does work for us. 

Let me explain to you our use case.

I work at Taboola, an Ad Tech company  (I just logged in to github using my private account).

In this specific project I am working on:
Currently We use tensorflow version 12.0.1 in production.
We A/B test RNNs, CNNs and other deep architectures.
 
We have daily training of models, and a fully automated continues delivery pipeline (both of models and code changes). 
At inference We predict scores for 600K items a second.

Our team contains 6 members (Data Scientists & Engineers) working full time on this project.

The main motivation to use **one image**, in order to keep development & CD cycle simple (see earlier post that explain what runs CPU vs GPU ).

So I hope I convinced you this is a real & interesting use case  :)

I appreciate your effort, and I do understand if you do not want to support it any more.

Thanks,
Erez

**Comment by martinwicke** [comment]
I'm very sympathetic to keeping CD simple. :)

Can you install CUDA on all your machines, even if they don't have a GPU? That ought to solve the problem. The issue is that the library cannot be loaded. It doesn't complain about not finding a GPU. 

Fundamentally, we link against this library, so it's expected to be there -- you can run the same tensorflow installation on all your servers as long as the environment is also the same. But apparently (unless I'm missing something), you have two different environments, one of which lacks a working CUDA installation.

**Comment by KashiErez** [comment]
Thanks for the response:

I think that there are 3 options here:

1. Install Cuda on machines (the downside is that it is painful on developer machines)
2. build GPU and CPU docker images
3. build one docker image, and install both GPU and CPU tensorflow versions with virtual env

I will have to think about what suits us best...

Thanks guys for your time.
Keep up the good work :)

**Comment by gunan** [comment]
Looks like @KashiErez is going to work around this problem on their end.
I will close this issue.

**Comment by ophiry** [comment]
@KashiErez Do you have a recommendation which of these solutions works best?

**Comment by KashiErez** [comment]
Hi Ophiry,

I found the 3rd solution the best.

This post contains a code snippet of the Dockerfile:
http://engineering.taboola.com/deep-learning-from-prototype-to-production

When you want to run on CPU, you have to:
   *  override the docker cmd, and use the CPU venv

When you want to run on GPU, you have to do 2 things:
   * override the docker cmd, and use the GPU venv
   * use nvidia-docker command line tool

**Comment by KashiErez** [comment]
Hi @gunan & @martinwicke,

My advice is to add GPU & CPU support at one tensorflow installation, for 2 reasons:
   1. The work around is very tedious
   2. Almost anyone going to production with Tensorflow will face this issue (regardless of using docker)

@ophiry, do you agree?

Thanks,
Erez

**Comment by ophiry** [comment]
Agree - the simplest thing would be to have tf use GPU if it's avaiable, and CPU if not.
of possibly have a configuration variable that can force GPU, force CPU, or do automatic selection

**Comment by ophiry** [comment]
A related issue - what is a good way to detect whether a GPU is present?

lspci is an option, but it requires installing extra packages,

**Comment by oolekk** [comment]
check that docker-nvidia-plugin is running, wasn't runnig for me and libcuda.so missing was the result
sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log

**Comment by cdeepakroy** [comment]
We are facing the same issue. 

We are building an open-source toolkit called HistomicsTK for analyzing histopathology images. We are currently trying to integrate some keras/tensorflow code into our toolkit. We would like our toolkit to work on all machines (with or without a GPU) and take advantage of the GPU if it is available or default to the CPU.

We also have some command-line programs/pipelines based on our toolkit that are packaged into a docker image derived from nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04. We want these to run with both plain `docker run` and `nvidia-docker run`.

The solution proposed by @KashiErez of creating two virtual environments -- one with tensforflow installed and another with tensorflow-gpu installed -- works but is very cumbersome.

Are there any plans of merging tensorflow and tensorflow-gpu into a single package?

**Comment by gunan** [comment]
In the longer term we have some projects that may merge the two packages, but the short term answer is no.

**Comment by thaynewalker** [comment]
FWIW I tried option #1 from @KashiErez  - Installing cuda on non-gpu machines as well. It turns out that while I can in fact install cuda on a machine with no GPUs, nvidia-docker dies with "unknown error". My guess is that cuda relies on an actual GPU being present in order to work correctly. Looks like virtualenv is the way to go.

**Comment by MadeInChina** [comment]
Try this way
```
version: '2'
services:
  tensorflow:
    image: tensorflow/tensorflow:latest-gpu-py3
    devices:
    - /dev/nvidia0:/dev/nvidia0:rwm
    - /dev/nvidiactl:/dev/nvidiactl:rwm
    - /dev/nvidia-uvm:/dev/nvidia-uvm:rwm
    volumes:
    - /usr/lib/x86_64-linux-gnu/libcuda.so:/usr/lib/x86_64-linux-gnu/libcuda.so
    - /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1
    - /usr/lib/x86_64-linux-gnu/libcuda.so.384.130:/usr/lib/x86_64-linux-gnu/libcuda.so.384.130
    - /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.130:/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.384.130
    ports:
    - 8889:8888/tcp
```
