### ISSUE TITLE
[Bug] CUDA_ERROR_INVALID_PTX on new RTX 5080 GPU with Driver 581.29

### ISSUE THREAD

**Issue by tgshen** [tensorflow/tensorflow#101746]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

TensorFlow 2.20.0 and 2.16.2

### Custom code

Yes

### OS platform and distribution

 Ubuntu 24.04.3 LTS

### Python version

3.11

### Bazel version

N/A

### GCC/compiler version

N/A

### CUDA/cuDNN version

- CUDA Version (from nvidia-smi): 13.0 - cuDNN Version (installed via pip): 8.9.7 (from package nvidia-cudnn-cu12==8.9.7.29) - CUDA Libraries (installed via pip): Compatible with CUDA 12.x

### GPU model and memory

NVIDIA GeForce RTX 5080 Laptop GPU, 16GB

### Current behavior?

Current Behavior
When attempting to run any TensorFlow operation on the GPU that requires JIT compilation (e.g., tf.matmul), the execution fails with an InternalError.
The detailed log output reveals that the root cause is a CUDA_ERROR_INVALID_PTX error, which occurs during the cuModuleLoadData step. This initial failure prevents the creation of a valid CUDA function handle, leading to the subsequent and final CUDA_ERROR_INVALID_HANDLE error when TensorFlow tries to launch the kernel.
This behavior is consistently reproducible on a new NVIDIA RTX 5080 Laptop GPU with the latest drivers, and occurs with both TensorFlow versions 2.20.0 and 2.16.2 installed from pip.
Key log line:
Expected Behavior
The expected behavior is that the tf.matmul operation should execute successfully on the GPU.
Specifically:
TensorFlow should correctly generate a valid PTX kernel for the new GPU architecture.
The NVIDIA driver should accept this PTX code and successfully JIT-compile it into native SASS.
The operation should complete without any InternalError, CUDA_ERROR_INVALID_PTX, or CUDA_ERROR_INVALID_HANDLE exceptions.
After the initial (and expected) JIT compilation delay, subsequent calls to the same operation should be fast.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import sys
import traceback

# Suppress oneDNN INFO messages to keep the log clean
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

def run_gpu_check():
    """
    Checks TensorFlow GPU availability and performs a simple computation.
    """
    print("--- System Info ---")
    print("TensorFlow Version:", tf.__version__)
    print("Python Version:", ".".join(map(str, sys.version_info[:3])))
    
    physical_gpus = tf.config.list_physical_devices('GPU')
    print("Physical GPUs Found:", physical_gpus)
    
    if not physical_gpus:
        print("\nERROR: No GPU detected by TensorFlow.")
        return
    
    print("-------------------")

    try:
        print("\nAttempting a simple GPU computation (tf.matmul)...")
        # Use a smaller tensor to ensure the test runs quickly once fixed
        with tf.device('/GPU:0'):
            a = tf.random.normal((100, 100))
            b = tf.random.normal((100, 100))
            c = tf.matmul(a, b)
            # Ensure the computation is actually executed
            _ = c.numpy()
        
        print("\n✅ GPU computation check PASSED.")
        print("Result tensor was successfully computed on device:", c.device)

    except Exception as e:
        print("\n❌ GPU computation check FAILED.")
        print("   Error Type:", type(e).__name__)
        print("\n   Full Error Traceback:")
        traceback.print_exc()

if __name__ == "__main__":
    run_gpu_check()
```

### Relevant log output

```shell

```

**Comment by Venkat6871** [comment]
Hi @tgshen ,
Thank you for raising this issue.
The root cause appears to be that the current TensorFlow pip binaries do not include precompiled CUDA kernels for the NVIDIA Blackwell architecture (Compute Capability 12.0, used in the RTX 50 series).
As a result, when TensorFlow falls back to JIT compilation from PTX, the generated PTX code is rejected by the CUDA 13.x driver, leading to `CUDA_ERROR_INVALID_PTX` and `CUDA_ERROR_INVALID_HANDLE` errors.

This is a known and ongoing issue. Please refer to the following tracking [issue](https://github.com/tensorflow/tensorflow/issues/89272) for further updates and technical discussions. Some of the comments there may also be helpful for your setup.

Thank you!

**Comment by YoranWandelsStudentHowest** [comment]
I can confirm encountering this exact issue on an NVIDIA GeForce RTX 5080 GPU using TensorFlow 2.16+. The issue seems indeed related to the lack of precompiled kernels for Compute Capability 12.0 (Blackwell) and XLA compilation failures with the new drivers.

However, I managed to get a stable training loop and inference running by explicitly disabling XLA devices and JIT compilation.

**Workaround that worked for me:**

1. **Disable XLA Devices** (Must be done before importing TensorFlow):
   ```python
   import os
   os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices=false'
   os.environ['TF_JIT_PROFILING'] = 'false'
   
   import tensorflow as tf

```

2. **Disable JIT in Keras models:**
When compiling your model, explicitly set `jit_compile=False`:
```python
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'],
    jit_compile=False  # Crucial for RTX 5080 stability currently
)

```



With these settings, I am able to utilize the GPU for training without the `CUDA_ERROR_INVALID_PTX` crash.

**Comment by MichaeLaudrup** [comment]
Hi, I think that this could help: https://github.com/MichaeLaudrup/Artificial_Intelligence_Msc/blob/main/TFM_education_ai_analytics/docs/BLACKWELL_GPU.md
