### ISSUE TITLE
Tensorboard 'Site cannot be reached' error

### ISSUE THREAD

**Issue by czarina** [tensorflow/tensorflow#10515]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Installed with Docker as per https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#1
- **TensorFlow version (use command below)**: ('v1.1.0-rc0-61-g1ec6ed5', '1.1.0')
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: not being used
- **GPU model and memory**: GPU not being used
- **Exact command to reproduce**: 

		:/tf_files# tensorboard --logdir training_summaries --debug
		Starting TensorBoard 47 at http://0.0.0.0:6006
		(Press CTRL+C to quit)

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

Hi. I'm following this tutorial for image classification: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#4 but with my own image dataset. I let the retraining run overnight, and it successfully completed. Now I am trying to visualize the results with Tensorboard. 

I ran tensorboard and this is the only terminal output:

    	:/tf_files# tensorboard --logdir training_summaries --debug
		Starting TensorBoard 47 at http://0.0.0.0:6006
		(Press CTRL+C to quit)

When I visit http://0.0.0.0:6006 the page does not load and it says 'Site cannot be reached.'

My retraining command was: 

    python retrain.py \
	  --bottleneck_dir=bottlenecks \
	  --model_dir=inception \
	  --summaries_dir=training_summaries/long \
	  --output_graph=retrained_graph.pb \
	  --output_labels=retrained_labels.txt \
	  --image_dir=data
	  
Can anyone help? I'm new to TF so I appreciate the advice.

**Comment by jubjamie** [comment]
I don't think this is a Tensorflow/Tensorboard bug but I think it is the way you have docker set up. It's been some time since I played with docker but I think that you might have to forward the docker port to one on your local host. The tutorial you followed did include this but it might be worth making sure that your ports are forwarding correctly. The key line in this code is the publish argument
```
docker run -it \
  --publish 6006:6006 \
  --volume ${HOME}/tf_files:/tf_files \
  --workdir /tf_files \
  tensorflow/tensorflow:1.1.0 bash
```
That should be enough but if you're ports aren't forwarding properly may I suggest that you try some of these commands to expose the Docker ports: 
[Docker - Exposing Ports](https://github.com/wsargent/docker-cheat-sheet#exposing-ports)

Stack Overflow has some good questions about it but some of them are over complicated for your needs.

If you have tried that and are convinced it's a problem with Tensorflow then keep this open and hopefully someone else can help troubleshoot! Hope this helps in the mean time.

**Comment by michaelisard** [comment]
Closing for now, but please reopen if you can't get help on stackoverflow, or this seems to be a real TensorFlow bug.

**Comment by czarina** [comment]
@jubjamie Hi, thanks for the tip! You were right, the issue is port forwarding related.

To clarify, I am running tensorboard inside docker, and docker is on my AWS EC2 instance.

I've managed to port forward from TB to docker, so I can do `curl http://localhost:6006/` on my EC2 and get the HTML for TB.

However, I've tried to visit http://<IP OF MY EC2>:6006 from my local browser (outside EC2) to see TB, and this does not work. Do you have any suggestions?

Thanks!!

**Comment by kulkarnivishal** [comment]
```tensorboard --logdir=<$MODEL_DIR> --host localhost ```
this would solve it.

**Comment by 13ecd1** [comment]
> `tensorboard --logdir=<$MODEL_DIR> --host localhost `
> this would solve it.

When I try this, I get "Access is denied". Do you happen to know why?

**Comment by pranathichunduru** [comment]
I am getting a similar error.I am running my jupyter notebook that trains a tensorflow model(ResNet) and when I call tensorboard in command line using 
`tensorboard` --logdir="path/to/logs/" ` It direct to a port and when I access the link it says

> This site can’t be reached... took too long to respond.
Thanks !

**Comment by rupa1118** [comment]
> `tensorboard --logdir=<$MODEL_DIR> --host localhost `
> this would solve it.

Thanks this worked for me 👍 ☺️ 
I have one question can't we download the structure graph and view on the system instead of viewing it on tensorboard? Thanks in advance

**Comment by Azkarehman** [comment]
> I am getting a similar error.I am running my jupyter notebook that trains a tensorflow model(ResNet) and when I call tensorboard in command line using
> `tensorboard` --logdir="path/to/logs/"`
> It direct to a port and when I access the link it says
> 
> > This site can’t be reached... took too long to respond.
> > Thanks !

were you able to solve it?
