### ISSUE TITLE
failed on build from source

### ISSUE THREAD

**Issue by andyyuan78** [tensorflow/tensorflow#1052]
envy@ub1404envy:~/os_prj/github/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
INFO: Found 1 target...
ERROR: /home/envy/os_prj/github/tensorflow/third_party/gpus/cuda/BUILD:126:1: declared output 'third_party/gpus/cuda/lib64/libcublas.so.7.0' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /home/envy/os_prj/github/tensorflow/third_party/gpus/cuda/BUILD:126:1: declared output 'third_party/gpus/cuda/lib64/libcudart.so.7.0' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /home/envy/os_prj/github/tensorflow/third_party/gpus/cuda/BUILD:126:1: declared output 'third_party/gpus/cuda/lib64/libcufft.so.7.0' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /home/envy/os_prj/github/tensorflow/third_party/gpus/cuda/BUILD:126:1: not all outputs were created.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 31.876s, Critical Path: 1.20s
envy@ub1404envy:~/os_prj/github/tensorflow$

**Comment by vrv** [comment]
Need more info:

- What git commit did you try to build at
- What version of bazel are you running
- Did you run ./configure before building (what other steps did you run) ?

**Comment by andyyuan78** [comment]
the latest tensorflow:
envy@ub1404envy:~/os_prj/github/tensorflow$ git status
On branch master
Your branch is up-to-date with 'origin/master'.


try both bazel 1.4 and 1.5

envy@ub1404envy:~/os_prj/github/tensorflow$ ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the location where cuDNN 6.5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Setting up Cuda include
Setting up Cuda lib64
Setting up Cuda bin
Setting up Cuda nvvm
Configuration finished
envy@ub1404envy:~/os_prj/github/tensorflow$

**Comment by imcomking** [comment]
Build a bleeding edge version.
The original sources comes from tensorflow dockerfile and I revised that.
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu]

git clone --recursive https://github.com/tensorflow/tensorflow.git
cd tensorflow

export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

sudo ./configure && \
    bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package && \
    bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip
sudo pip install --upgrade /tmp/pip/tensorflow-*.whl

**Comment by aabobakr** [comment]
make sure you run the ./configure script.. double check the paths for cuda and cudnn.. if not sure try system defaults

**Comment by andyyuan78** [comment]
it should be some PATH issue

I had the 2nd try and it passed. thanks all

**Comment by mhauskn** [comment]
I am having the same errors: ERROR: /v/filer4b/v20q001/mhauskn/projects/tensorflow/third_party/gpus/cuda/BUILD:126:1: declared output 'third_party/gpus/cuda/lib64/libcublas.so' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).

Could you give any more insight into how you solved the problem?

**Comment by kbrems** [comment]
It seems that the configure script ONLY works with the defaults. The error occurs if you change anything. As of release r0.7, the configure script SAYS the default is cuda 7.0, even though the release notes say it uses cuda 7.5. When I tried to tell configure I wanted 7.5, I got the error above. If I let it use the default, it worked and I verified that the libraries in the bazel genfiles cache were actually 7.5 and cudnn 4.0.7.

**Comment by mhauskn** [comment]
Thanks! As you suggested I had to not specify the Cuda/CuDNN versions (use system default) and then provide the paths to cuda/cudnn:

./configure 
Please specify the location of python. [Default is /lusr/bin/python]: 
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /opt/cuda-7.0
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /opt/cuda-7.0]: /u/mhauskn/cudnn-7.0-linux-x64-v4.0-prod
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
Setting up Cuda include
Setting up Cuda lib64
Setting up Cuda bin
Setting up Cuda nvvm
Configuration finished

**Comment by po0ya** [comment]
I confirm @kbrems, I had the same problem and didn't provided the versions and it worked.

**Comment by mondatu** [comment]
@kbrems Thanks a lot for your solution. I had the same problem fixed now. Hopefully, someone with knowledge of bazel will fix this minor bug soon

**Comment by vrv** [comment]
1) We need to figure out why the bazel genrules aren't producing the right outputs.  I wonder if the ./configure script is not modifying the CUDA_VERSION string in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/build_config.bzl#L7 ?  

2) @kbrems: where does the ./configure script say 7.0 is the default?

**Comment by kbrems** [comment]
$./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]:

**Comment by vrv** [comment]
@kbrems: that says 'e.g.,', which means 'for example', not the default.

**Comment by kbrems** [comment]
I guess it does not explicitly say Cuda SDK 7.0 IS the default, but that is what the text implies and what many people who run it are assuming, which it why they run into the issue.

**Comment by vrv** [comment]
I disagree that 'e.g.' means 'default is', but we can certainly change that to be 7.5 :)

I can also reproduce the problem above, it's a dumb error, will fix.

**Comment by vrv** [comment]
Fixed in 97f6b6fb66cd8e52af4750bd183dfc555d08ef4d

**Comment by panmari** [comment]
I recently had a very similar issue, because I still had a stale configuration file (`tensorflow/core/platform/default/build_config.bzl`) lying around. Checking it out again from master (essentially reverting all custom changes) fixed the problem.
