### ISSUE TITLE
The issue of compling from source code: undeclared inclusion(s) in rule '@nccl_archive//:nccl'

### ISSUE THREAD

**Issue by lxwgcool** [tensorflow/tensorflow#10665]
Hey guys,

I can compile the cpu version of tensorflow 1.2.0-rc2 without any problem, however, i am blocked when i try to compile the gpu version. I spend almost the whole day to install tensorflow 1.2.0-rc2 gpu version in our cluster, however there is no lucky.

### Here is the error from the terminal: 

ERROR: /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/BUILD:33:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':
  '/gpfs/gpfs1/apps2/gcc/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include-fixed/limits.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include-fixed/syslimits.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include/stddef.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/new'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/x86_64-unknown-linux-gnu/bits/c++config.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/x86_64-unknown-linux-gnu/bits/os_defines.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/x86_64-unknown-linux-gnu/bits/cpu_defines.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/exception'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/bits/atomic_lockfree_defines.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/bits/exception_ptr.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/bits/exception_defines.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/bits/nested_exception.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include/stdarg.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/cmath'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/bits/cpp_type_traits.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/ext/type_traits.h'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/cstdlib'
  '/gpfs/gpfs1/apps2/gcc/5.4.0/include/c++/5.4.0/cstdio'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 22.226s, Critical Path: 5.20s

### OS Information 
Red Hat Enterprise Linux Workstation release 6.7 (Santiago)

### Modules I loaded
gcc/5.4.0, cuda/8.0.61, cudnn/6.0, java/1.8.0_31, sqlite/3.18.0, tcl/8.6.6.8606, python/3.6.1

### Here is how i make the configuration
gcc (v5.4.0): /apps2/gcc/5.4.0 (customized path）
enabled cuda (v8.0): /apps2/cuda/8.0.61 (customized path）
enabled cudnn: /apps2/cudnn/6.0 (customized path）
python (v3.6.1, which is compiled with gcc 5.4.0): /apps2/python/3.6.1 (customized path)
Other options are disabled (such as hadoop, google cloud). 

### Here are some files i modified manually before compiling
(1) /tensorflow-1.2.0-rc2/third_party/gpus/crosstool/CROSSTOOL_clang.tpl
     /tensorflow-1.2.0-rc2/third_party/gpus/crosstool/CROSSTOOL_nvcc.tpl
    Add the following contents in all of "toolchain": 
    cxx_builtin_include_directory: "/apps2/gcc/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include"
    cxx_builtin_include_directory: "/apps2/gcc/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include-fixed"
    cxx_builtin_include_directory: "/apps2/gcc/5.4.0/include/c++/5.4.0"
    cxx_builtin_include_directory: "/apps2/gcc/5.4.0/include"
    cxx_builtin_include_directory: "/apps2/cuda/8.0.61/include"
    cxx_builtin_include_directory: "/apps2/cudnn/6.0/include"

(2) /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/protobuf/protobuf.bzl
     Add the following content in "ctx.action"
     env=ctx.configuration.default_shell_env

(3) /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/Makefile
     Some modification as below:
     CUDA_HOME ?= /usr/local/cuda --> CUDA_HOME ?= /apps2/cuda/8.0.61

I noticed that some of people said this issue could be bypassed by delete the nccl dependence in "/tensorflow-1.2.0-rc2/tensorflow/contrib/BUILD". However, i do not think this is the correct way to solve this issue. I wanna keep this dependence.

Thanks so much for your help. Any comments are appreciated.
Best Regards
Xin

**Comment by aselle** [comment]
Could you try to solve it like others have just to make sure you have everything working otherwise. Then put it back. Basically, it looks like you need to change the build file used for building nccl. @gunan, do you have any ideas?

**Comment by lxwgcool** [comment]
Dear Andrew:

Thanks so much for your kindly reply. I think the build file used for
building nccl you mentioned should be this one:
"/home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/BUILD".


Actually, i spend sometime to checked this file yesterday, however, i have
no idea about how to change it. Could you help me figure out how to change
it?

BTW, the compiling error shows that "this rule is missing dependency
declarations for the following files included by 'external/nccl_archive/src/
libwrap.cu.cc':" and all of related files are listed afterwards. However, i
check all of those files one by one, and all of them are exactly existed.

Thanks so much for your help.
Best regards
Xin

2017-06-13 4:27 GMT-04:00 Andrew Selle <notifications@github.com>:

**Comment by lxwgcool** [comment]
@aselle Dear Andrew:

Thanks so much for your kindly reply. I think the build file used for building nccl you mentioned should be this one:  "/home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/BUILD".

Actually, i spend sometime to checked this file yesterday, however, i have no idea about how to change it. Could you help me figure out how to change it?

BTW, the compiling error shows that "this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':" and all of related files are listed afterwards. However, i check all of those files one by one, and all of them are exactly existed.

Thanks so much for your help.
Best regards
Xin

**Comment by gunan** [comment]
I too have sees this when building for CentOS. For me when I reinstalled gcc/g++ this was resolved.

**Comment by lxwgcool** [comment]
Hi Gunan,

Thanks so much for your reply. May i know which version of gcc was used
when you compile the gpu version of tensorflow v1.2.0-rc2?

Actually, for my case, the cpu version of tensorflow v1.2.0-rc2 could be
compiled without  any problem. Do you think this issue in gpu version is
really caused by my gcc compiler? Is there any way that just change some
minor parts of certain *.bzl or BUILD file rather than re-compile the whole
source code of gcc?

Thanks again for your help.
Best regards
Xin


2017-06-13 14:00 GMT-04:00 gunan <notifications@github.com>:

**Comment by gunan** [comment]
I did not build with 1.2, last time I experimented with centOS it was version 1.0.
Here is the gcc version on my docker container:
```
# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
```

**Comment by lxwgcool** [comment]
Thanks gunan, we already have the module gcc v4.8.5 in our cluster, i will try it right now. 
However, i still has a question: since the cpu version of tensorflow v1.2.0-rc2 could be compiled by my current gcc v5.4.0 successfully without any problem, i think my current gcc v5.4.0 should works fine. I am really confused why the gpu version failed to be compiled (it seems that the compiling stopped before compile the source code of cuda/cudnn)? Any comments are appreciated. I will let you know if gcc v4.8.5 works fine. 

Thanks for your help
Best 
Xin

**Comment by gunan** [comment]
I am not sure, our primary environment is ubuntu so I can only speculate.
It can be missing headers, or some confusion on bazel side when you have different gcc versions installed.
It may be as simple as setting some environment variables, or there may be bugs in Bazel itself.

As I mentioned before, our primary development environment is ubuntu, and we only provide official support on ubuntu. You may be able to get more information from the community on this issue.

**Comment by lxwgcool** [comment]
Thanks gunan,
I tried gcc/4.8.5 with bazel 0.4.5, however, i still get the similar error as below: 
---------------
ERROR: /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/BUILD:33:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':
  '/gpfs/gpfs1/apps2/gcc/4.8.5/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include-fixed/limits.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include-fixed/syslimits.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include/stddef.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/new'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/x86_64-unknown-linux-gnu/bits/c++config.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/x86_64-unknown-linux-gnu/bits/os_defines.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/x86_64-unknown-linux-gnu/bits/cpu_defines.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/exception'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/bits/atomic_lockfree_defines.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/bits/exception_ptr.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/bits/exception_defines.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/bits/nested_exception.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include/stdarg.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/cmath'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/bits/cpp_type_traits.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/ext/type_traits.h'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/cstdlib'
  '/gpfs/gpfs1/apps2/gcc/4.8.5/include/c++/4.8.5/cstdio'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
---------------

I find there is a makefile in nccl_archive folder "/home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive". Then, i try to make the nccl_archive source code manually by simply typing "make". What is surprise for me is that I did the "make" successfully ( libwrap.o be compiled successfully as well), please check below:
---------------
hpc-xin@cn02:~/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive$ make
Compiling src/libwrap.cu                      > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/obj/libwrap.o
Compiling src/core.cu                         > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/obj/core.o
Compiling src/all_gather.cu                   > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/obj/all_gather.o
Compiling src/all_reduce.cu                   > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/obj/all_reduce.o
Compiling src/broadcast.cu                    > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/obj/broadcast.o
Compiling src/reduce.cu                       > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/obj/reduce.o
Compiling src/reduce_scatter.cu               > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/obj/reduce_scatter.o
Linking   libnccl.so.1.3.4                    > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/lib/libnccl.so.1.3.4
Archiving libnccl_static.a                    > /home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive/build/lib/libnccl_static.a
hpc-xin@cn02:~/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive$ 
---------------
It seems that gcc works for nccl. I really have no idea why nccl-archive be failed while compiling by bazel. 
I will spend more time for investigation on Friday afternoon. Any additional comments of this issue is really appreciated. 

Thanks again for your help
Best regards
Xin

**Comment by gunan** [comment]
Again, neither us nor bazel does not have official support for RedHat. So we do not have extensive experience with different error modes that you can see. Not sure why this is happening, so Ill mark this as Community support to see if anyone from the community has any information on building on RedHat.

You can also look through our previous issues. there seems to be a handful of people who ran into similar issues before:
https://github.com/tensorflow/tensorflow/issues/3841
https://github.com/tensorflow/tensorflow/issues/3431
https://github.com/tensorflow/tensorflow/issues/4851
https://github.com/tensorflow/tensorflow/issues/5182
https://github.com/bazelbuild/bazel/issues/1317
https://github.com/tensorflow/tensorflow/issues/1157

**Comment by RustingSword** [comment]
I had this exact problem on CentOS 7.1, with gcc 4.8.3, bazel 0.4.5, CUDA 8.0, cuDNN 5.1. CUDA and cuDNN are installed in the default path (`/usr/local/cuda`).

The error messages are as follows:
```
ERROR: /home/user/.cache/bazel/_bazel_sankuai/a124f28b2f66957c03d4d409b9638361/external/nccl_archive/BUILD:33:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/limits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/syslimits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/stddef.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdarg.h'.
[...]
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 38.362s, Critical Path: 28.04s
```

Adding
```
cxx_builtin_include_directory: "/usr/lib/gcc/x86_64-redhat-linux/4.8.3/include"
```
to
```
third_party/gpus/crosstool/CROSSTOOL_nvcc.tpl
```
seems fixed the problem.

@lxwgcool I noticed that the file path in your errors starts with `/gpfs/gpfs1/`, while your added path in `CROSSTOOL_nvcc.tpl` starts with `/apps2`, could this be the problem?

**Comment by lxwgcool** [comment]
@RustingSword Thank you RustingSword . "apps2" is auto-mounted in our cluster, therefore, in most of the time, i just use "/apps2" rather than "/gpfs/gpfs1/apps2". I will try to replace it at afternnon today and let you know if it works fine. Thanks so much for your suggestion.

Best regards
Xin

**Comment by lxwgcool** [comment]
@aselle @gunan @RustingSword 
Hi All, 
Good news: I just compiled gpu version of tensorflow 1.2.0-rc2 successfully. I did several additional things as below:
1: Thanks @RustingSword , I replaced all of "/apps2" by "/gpfs/gpfs1/apps2" to avoid the potential problem of auto-mount in our parallel file system. 
2: For the file: tensorflow/third_party/gpus/crosstool/CROSSTOOL_nvcc.tpl, replace: 
   "tool_path { name: "cpp" path: "/usr/bin//cpp" }" to "tool_path { name: "cpp" path: "/gpfs/gpfs1/apps2/gcc/5.4.0/bin/cpp" }"
3: Go to "/home/hpc-xin/.cache/bazel/_bazel_hpc-xin/c5e302e32d7acb9c3e4fce8142d1cd66/external/nccl_archive". For the file "MakeFile", change "CUDA_HOME ?= /usr/local/cuda" to "CUDA_HOME ?= /apps2/cuda/8.0.61", then type “make” to make the source code manually.
4: Back to the main folder of tensorflow and type "bazel clean"
5: bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
6: bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

I wrote some simple testing codes to test the gpu features of tensorflow 1.2.0-rc2  and all of those codes works fine now. The corresponding compiler and software I used as below: bazel v0.5.1, gcc v5.4.0, python v3.6.1, cuda v8.0, cudnn v6.0.

I am really appreciated for you guys help. Thank you so much :)

Best
Xin

**Comment by gunan** [comment]
Looks like the issue was resolved.
Thanks for the update!

**Comment by jimdowling** [comment]
I have this problem  with Centos 7.2. It is a pity as it is very close to working!
The corresponding compiler and software I used as below: bazel v0.5.2, gcc v4.8.5, python v2.7x, cuda v8.0, cudnn v6.0. The problem occurs when building the python package:

___[1,783 / 4,162] Compiling external/protobuf/src/google/protobuf/descriptor_database.cc
ERROR: /root/.cache/bazel/_bazel_root/2608380002b7e82b3d07fef59e49e485/external/nccl_archive/BUILD:33:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'.
In file included from /usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/host_config.h:173:0,
                 from /usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78,
                 from <command-line>:0:

**Comment by sea-man** [comment]
you have to run bazel with this option: **-cxxopt="-I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/*.h"**

**Comment by paulraines68** [comment]
Doesn't help me at all. I am running on CentOS7.2

`bazel build --cxxopt="-I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/*.h" -c opt --copt=-mavx --copt=-mavx2 --copt=-msse4.2 --copt=-msse4.1 --copt=-msse3 --copt=-mfma //tensorflow/tools/pip_package:build_pip_package
`

but it still fails with

```
ERROR: /autofs/cluster/pubsw/1/pubsw/.cache/bazel/_bazel_pubsw/0afd619d2e7b272bb659b23ca414b60f/external/nccl_archive/BUILD:33:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'.

```

**Comment by jiayiliu** [comment]
Yes, I shared the same problem with @paulraines68 and have tried both
1. edit the third_party/gpus/crosstool/CROSSTOOL_nvcc.tpl (@RustingSword )
2. add --cxxopt="-I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/*.h" (@sea-man )

PS I am using bazel (0.5.4), gcc (4.8.5) and compiling tf r1.4.
Any helps are welcome!

**Comment by gunan** [comment]
I think the problem is in the default crosstool bazel defines in version 0.5.4
Please try again with bazel version 0.8

**Comment by lvpengdlut** [comment]
I have tried bazel version 0.8 and all the solutions above, but the "nccl" problem is still not fixed.

System information:
    redhat 7.2
    gcc 4.8.5
    bazel 0.5.4 or 0.8.0
    tensorflow 1.4.1 
    cuda 8.0
    cudnn 6.0

**Comment by jiayiliu** [comment]
Thank you @gunan for checking - 
I  also got the same error with bazel 0.8.1 and tf r1.4.

**Comment by beanliao** [comment]
I have the same problem, can anyone help to check " undeclared inclusion(s) in rule '@nccl_archive//:nccl' " issue? 
it will be really appreciated. :)
 
**System information:**
CentOS 7.3
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Build label: 0.8.1- (@non-git)
tensorflow 1.4.1
cuda 9.0.176
cudnn 7.0.5
tensorflow 1.4.0

**Build command:**
 bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Error message:**
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/nccl_archive/BUILD:33:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.973s, Critical Path: 4.56s
FAILED: Build did NOT complete successfully
