### ISSUE TITLE
TF binary incompatible to protobuf?

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#10950]
I tried with TensorFlow 1.1.0 and 1.2.0, on Python 2.7 (and 3.5).
Note that I also asked about this [on StackOverflow](https://stackoverflow.com/questions/44455722/create-my-own-resource-types-tf-resource) but I think this might actually be a bug (either in the pip packaging of TF or protobuf or sth else), so I post it here.

Summary:

I think the protobuf pip package is binary incompatible with the TF pip package but I'm not exactly sure on this.

I try to write some own operator which creates some own `tf.resource`. I use the C++ header files from the TF pip install, and I link it to the `_message.so` file from the protobuf 3.3.0 pip package, because anything `tf.resource` related will need linking to protobuf.

My current code:

    // For Eigen::ThreadPoolDevice.
    #define EIGEN_USE_THREADS 1

    #include "tensorflow/core/framework/op.h"
    #include "tensorflow/core/framework/shape_inference.h"
    #include "tensorflow/core/framework/op_kernel.h"
    #include "tensorflow/core/framework/resource_mgr.h"
    #include "tensorflow/core/framework/resource_op_kernel.h"
    #include "tensorflow/core/framework/tensor.h"
    #include "tensorflow/core/framework/tensor_shape.h"
    #include "tensorflow/core/framework/types.h"
    #include "tensorflow/core/platform/macros.h"
    #include "tensorflow/core/platform/mutex.h"
    #include "tensorflow/core/platform/types.h"

    using namespace tensorflow;

    REGISTER_OP("ArrayContainerCreate")
    .Attr("T: type")
    .Attr("container: string = ''")
    .Attr("shared_name: string = ''")
    .Output("resource: resource")
    .SetIsStateful()
    .SetShapeFn(shape_inference::ScalarShape)
    .Doc(R"doc(Array container, random index access)doc");

    REGISTER_OP("ArrayContainerGetSize")
    .Input("handle: resource")
    .Output("out: int32")
    .SetShapeFn(shape_inference::ScalarShape)
    ;

    // https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/resource_mgr.h
    struct ArrayContainer : public ResourceBase {
      ArrayContainer(const DataType& dtype) : dtype_(dtype) {}

      string DebugString() override { return "ArrayContainer"; }
      int64 MemoryUsed() const override { return 0; };

      mutex mu_;
      const DataType dtype_;

      int32 get_size() {
        mutex_lock l(mu_);
        return (int32) 42;
      }

    };

    // https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/resource_op_kernel.h
    class ArrayContainerCreateOp : public ResourceOpKernel<ArrayContainer> {
    public:
      explicit ArrayContainerCreateOp(OpKernelConstruction* context) : ResourceOpKernel(context) {
        OP_REQUIRES_OK(context, context->GetAttr("T", &dtype_));
      }

    private:
      virtual bool IsCancellable() const { return false; }
      virtual void Cancel() {}

      Status CreateResource(ArrayContainer** ret) override EXCLUSIVE_LOCKS_REQUIRED(mu_) {
        *ret = new ArrayContainer(dtype_);
        if(*ret == nullptr)
          return errors::ResourceExhausted("Failed to allocate");
        return Status::OK();
      }

      Status VerifyResource(ArrayContainer* ar) override {
        if(ar->dtype_ != dtype_)
          return errors::InvalidArgument("Data type mismatch: expected ", DataTypeString(dtype_),
                                         " but got ", DataTypeString(ar->dtype_), ".");
        return Status::OK();
      }
  
      DataType dtype_;
    };
    REGISTER_KERNEL_BUILDER(Name("ArrayContainerCreate").Device(DEVICE_CPU), ArrayContainerCreateOp);

    class ArrayContainerGetSizeOp : public OpKernel {
    public:
      using OpKernel::OpKernel;

      void Compute(OpKernelContext* context) override {
        ArrayContainer* ar;
        OP_REQUIRES_OK(context, GetResourceFromContext(context, "handle", &ar));
        core::ScopedUnref unref(ar);

        int32 size = ar->get_size();
        Tensor* tensor_size = nullptr;
        OP_REQUIRES_OK(context, context->allocate_output(0, TensorShape({}), &tensor_size));
        tensor_size->flat<int32>().setConstant(size);
      }
    };
    REGISTER_KERNEL_BUILDER(Name("ArrayContainerGetSize").Device(DEVICE_CPU), ArrayContainerGetSizeOp);

I compile that. Note that I first got some `undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE` error but I resolved that by adding these additional compiler flags:

    from google.protobuf.pyext import _message as msg
    lib = msg.__file__
    
    extra_compiler_flags = [
        "-Xlinker", "-rpath", "-Xlinker", os.path.dirname(lib),
        "-L", os.path.dirname(lib), "-l", ":" + os.path.basename(lib)]

I read about that [here](https://github.com/tensorflow/tensorflow/issues/1419).

I end up with flags like these:

`-shared -O2 -std=c++11 -I /u/zeyer/.local/lib/python2.7/site-packages/tensorflow/include -I /usr/local/cuda-8.0/include -L /usr/local/cuda-8.0/lib64 -x cu -DGOOGLE_CUDA=1 -Xcompiler -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 TFArrayContainer.cc -o TFArrayContainer.so -Xlinker -rpath -Xlinker /u/zeyer/.local/lib/python2.7/site-packages/google/protobuf/pyext -L /u/zeyer/.local/lib/python2.7/site-packages/google/protobuf/pyext -l :_message.so`

Then I load that as a module via `tf.load_op_library`.

Then, I have this Python code:

    handle = mod.array_container_create(T=tf.int32)
    size = mod.array_container_get_size(handle=handle)

When I try to evaluate `size`, I get the error:

    InvalidArgumentError (see above for traceback): Trying to access resource located in device 14ArrayContainer from device /job:localhost/replica:0/task:0/cpu:0
             [[Node: ArrayContainerGetSize = ArrayContainerGetSize[_device="/job:localhost/replica:0/task:0/cpu:0"](array_container)]]

The device name (`14ArrayContainer`) somehow seem to be messed up. Why is that? What is the problem with the code?

For some more testing, I added this additional code in the `ArrayContainerCreateOp`:

        ResourceHandle rhandle = MakeResourceHandle<ArrayContainer>(context, cinfo_.container(), cinfo_.name());
        printf("created. device: %s\n", rhandle.device().c_str());
        printf("container: %s\n", rhandle.container().c_str());
        printf("name: %s\n", rhandle.name().c_str());
        printf("actual device: %s\n", context->device()->attributes().name().c_str());
        printf("actual name: %s\n", cinfo_.name().c_str());

This gives me the output:

    created. device: 14ArrayContainer
    container: 14ArrayContainer
    name: 14ArrayContainer
    actual device: /job:localhost/replica:0/task:0/cpu:0
    actual name: _2_array_container

So clearly, there is some of the problem.

This looks like something is messed up with the protobuf? Maybe I am linking the wrong lib? But I have not found which lib to link instead.

**Comment by ali01** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by albertz** [comment]
@ali01  Well, I wrote already the TF versions, and I wrote that I used the pip package, and this should be independent of the platform, but if it matters, I tried both Linux and MacOSX. I also posted all the code already, both the C++ part and the TF part. You can use `g++` for compiling, e.g. with the flags which I wrote. Maybe here how to load the module, if that is unclear:
```
mod = tf.load_op_library("TFArrayContainer.so")
```
Then, as I already wrote, the computation graph:
```
handle = mod.array_container_create(T=tf.int32)
size = mod.array_container_get_size(handle=handle)
```
Then, this is how you evaluate it (given that you have a default session):
```
size.eval()
```
I'm not exactly sure what information is missing.

**Comment by cy89** [comment]
@albertz could you please fill in the exact version numbers that you're using, perhaps just copy/pasting the form from ali01's response?

Also, it's not clear to me whether you can construct a smaller exhibitor code sample, but that would help a bunch. Thanks!

**Comment by albertz** [comment]
Ok, I reduced the test case a bit.

`demo.cpp`:
```
// Demo for: https://github.com/tensorflow/tensorflow/issues/10950
// See demo.py.

#include <vector>

// For Eigen::ThreadPoolDevice.
#define EIGEN_USE_THREADS 1

#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/framework/resource_mgr.h"
#include "tensorflow/core/framework/resource_op_kernel.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/framework/tensor_shape.h"
#include "tensorflow/core/framework/types.h"
#include "tensorflow/core/platform/macros.h"
#include "tensorflow/core/platform/mutex.h"
#include "tensorflow/core/platform/types.h"

using namespace tensorflow;

REGISTER_OP("ResourceBugDemo")
.Attr("container: string = ''")
.Attr("shared_name: string = ''")
.Output("resource: resource")
.SetIsStateful()
.SetShapeFn(shape_inference::ScalarShape)
.Doc("demo");

// https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/resource_mgr.h
struct ArrayContainer : public ResourceBase {
    ArrayContainer() {}

    string DebugString() override { return "ArrayContainer"; }
    int64 MemoryUsed() const override { return 0; };
};

// https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/resource_op_kernel.h
class ResourceBugDemoOp : public ResourceOpKernel<ArrayContainer> {
public:
    explicit ResourceBugDemoOp(OpKernelConstruction* context) : ResourceOpKernel(context) {}

    void Compute(OpKernelContext* context) override {
        ResourceOpKernel<ArrayContainer>::Compute(context);
        mutex_lock l(mu_);
        ResourceHandle rhandle = MakeResourceHandle<ArrayContainer>(context, cinfo_.container(), cinfo_.name());
        printf("rhandle.device: %s\n", rhandle.device().c_str());
        printf("rhandle.container: %s\n", rhandle.container().c_str());
        printf("rhandle.name: %s\n", rhandle.name().c_str());
        printf("rhandle.device should be: %s\n", context->device()->attributes().name().c_str());
        printf("rhandle.name should be: %s\n", cinfo_.name().c_str());
    }
    
private:
    virtual bool IsCancellable() const { return false; }
    virtual void Cancel() {}

    Status CreateResource(ArrayContainer** ret) override EXCLUSIVE_LOCKS_REQUIRED(mu_) {
        *ret = new ArrayContainer();
        if(*ret == nullptr)
            return errors::ResourceExhausted("Failed to allocate");
        return Status::OK();
    }

    Status VerifyResource(ArrayContainer* ar) override {
        return Status::OK();
    }
};
REGISTER_KERNEL_BUILDER(Name("ResourceBugDemo").Device(DEVICE_CPU), ResourceBugDemoOp);
```

`demo.py`:
```
#!/usr/bin/env python

# Demo for: https://github.com/tensorflow/tensorflow/issues/10950

from __future__ import print_function
import os
import sys
import tensorflow as tf


my_dir = os.path.dirname(os.path.abspath(__file__))
so_filename = "demo.so"
cc_filename = "demo.cpp"


def compile():
    # Fix for undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE.
    # https://github.com/tensorflow/tensorflow/issues/1419
    from google.protobuf.pyext import _message as msg
    lib = msg.__file__
    ld_flags = [
        "-Xlinker", "-rpath", "-Xlinker", os.path.dirname(lib),
        "-L", os.path.dirname(lib), "-l", ":" + os.path.basename(lib)]
    common_opts = ["-shared", "-O2", "-std=c++11"]
    if sys.platform == "darwin":
        common_opts += ["-undefined", "dynamic_lookup"]
    common_opts += ["-I", tf.sysconfig.get_include()]
    common_opts += ["-fPIC"]
    common_opts += ["-D_GLIBCXX_USE_CXX11_ABI=0"]  # might be obsolete in the future
    opts = common_opts + [cc_filename, "-o", so_filename]
    opts += ld_flags
    cmd_bin = "g++"
    cmd_args = [cmd_bin] + opts
    from subprocess import Popen, PIPE, STDOUT, CalledProcessError
    print("compile call: %s" % " ".join(cmd_args))
    proc = Popen(cmd_args, stdout=PIPE, stderr=STDOUT)
    stdout, stderr = proc.communicate()
    assert stderr is None  # should only have stdout
    if proc.returncode != 0:
      print("compile failed: %s" % cmd_bin)
      print("Original stdout/stderr:")
      print(stdout)
      raise CalledProcessError(returncode=proc.returncode, cmd=cmd_args)
    assert os.path.exists(so_filename)


def main():
    print("TensorFlow version:", tf.GIT_VERSION, tf.VERSION)
    os.chdir(my_dir)
    compile()
    mod = tf.load_op_library("%s/%s" % (my_dir, so_filename))
    handle = mod.resource_bug_demo()
    with tf.Session() as session:
        session.run(handle)


if __name__ == "__main__":
    main()
```

If you call `demo.py`, with Python 2.7.12, on Ubuntu 16.04, I get this output:
```
TensorFlow version: v1.2.0-5-g435cdfc 1.2.1
compile call: g++ -shared -O2 -std=c++11 -I /u/zeyer/.local/lib/python2.7/site-packages/tensorflow/include -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 demo.cpp -o demo.so -Xlinker -rpath -Xlinker /u/zeyer/.local/lib/python2.7/site-packages/google/protobuf/pyext -L /u/zeyer/.local/lib/python2.7/site-packages/google/protobuf/pyext -l :_message.so
...
rhandle.device: 14ArrayContainer
rhandle.container: 14ArrayContainer
rhandle.name: 14ArrayContainer
rhandle.device should be: /job:localhost/replica:0/task:0/cpu:0
rhandle.name should be: _0_ResourceBugDemo
```

But as I already guessed in the title, the problem is probably that the TF binary from the pip package is binary-incompatible to the protobuf pip package (3.3.0).
And the solution, as written maybe indirectly in #1419, is to just export the protobuf symbols by TF itself (in `_pywrap_tensorflow_internal.so`).

**Comment by martinwicke** [comment]
@jart @jhseu Could this be related (or fixed by) to the protobuf version change we had recently?

**Comment by jhseu** [comment]
Someone also encountered this bug internally (b/62536806), and it was fixed by syncing. Pinged to see if they know what the original issue was.

Possibly fixed by a newer protobuf version?

**Comment by jhseu** [comment]
This issue is fixed by https://github.com/tensorflow/tensorflow/pull/9994, which didn't make it into the TF 1.2 release.
