### ISSUE TITLE
Build TF 1.2 error: no such package '@nccl_archive//' OR undeclared inclusion(s) in rule '@nccl_archive//:nccl': this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':

### ISSUE THREAD

**Issue by jacob1017** [tensorflow/tensorflow#11404]
Hi，I compiled tensorflow r1.0 successfully with Centos 7.0，cuda 8.0 and CUDNN 6.5，gcc 4.8.5.  Recently，We want follow the latest version of Tensorflow，error below are always occur:

`ERROR: /home/jiangbo/tensorflow/tensorflow/tools/pip_package/BUILD:76:1: no such package '@nccl_archive//': /home/jiangbo/.cache/bazel/_bazel_jiangbo/0c80707bb0528f07a36b6bc1e1bf9b14/external/nccl_archive/build (Operation not permitted) and referenced by '//tensorflow/tools/pip_package:licenses'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
`
My bazel version have tried 0.4.5 and 0.5.2, but compile error.  Some method to solve this problem I have tried but no one helps , any body knows this problem, please tell me or let me know you thought.

After I compiled TF r1.2 error, I have checkout to r1.0. it is weird, the same error info again.

**Comment by martinwicke** [comment]
Can you please post the entire build log up to the error?

**Comment by sea-man** [comment]
I faced same issue, the full log is bellow:
ERROR: /root/.cache/bazel/_bazel_root/6093305914d4a581ed00c0f6c06f975b/external/nccl_archive/BUILD:39:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'.
In file included from /opt/cuda-8.0/bin/..//include/host_config.h:173:0,
                 from /opt/cuda-8.0/bin/..//include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/features.h:330:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
In file included from /opt/cuda-8.0/bin/..//include/host_config.h:173:0,
                 from /opt/cuda-8.0/bin/..//include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/features.h:330:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
In file included from /opt/cuda-8.0/bin/..//include/host_config.h:173:0,
                 from /opt/cuda-8.0/bin/..//include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/features.h:330:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!

**Comment by martinwicke** [comment]
@av8ramit this seems overzealous by our bot -- to do this, we would first have to make sure we have the labels correct.

Can you disable this behavior until we have the label state machine figured out?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by av8ramit** [comment]
@martinwicke disabling the close plugin and state machine changes are in flight

**Comment by gunan** [comment]
Using latest TF version, and bazel version 0.8.1 or later, this problem seems to be gone. For more information see #14380
