### ISSUE TITLE
Distributed training with synchronized SGD using 'grpc+verbs' sometimes hangs indefinitely

### ISSUE THREAD

**Issue by on-the-run** [tensorflow/tensorflow#11416]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.2 LTS
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: v1.2.0-1755-gee4259a 1.2.1
- **Python version**: Python 3.5.2
- **Bazel version (if compiling from source)**: 0.5.1
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: GeForce GTX 1080 Ti
- **Exact command to reproduce**: Sorry, the command is not available since this is custom code
- **RDMA driver version**: libibverbs-dev (1.2.1mlnx1-OFED.4.0.1.5.3.40200)

### Describe the problem
I am training a seq2seq model with synchronized SGD (using `tf.train.SyncReplicasOptimizer` and `tf.train.Supervisor`), over RDMA (using `grpc+verbs` protocol), on 2 workers and 1 parameter server. Each worker has 8 GPUs, and the model on each GPU is the same.

I can train this model fine with the default `grpc` protocol using the same setting. When I switched to `grpc+verbs`, the behavior becomes unpredictable. Most of the times both workers hang (for at least 12 hours, so not because I didn't wait long enough). Sometimes the chief worker (worker 0) starts training, but worker 1 hangs. (This should not happen since I am programming with synchronized SGD. Worker 0 should be blocked if worker 1 is not ready.) In rare case it can go through and start training. I believe the RDMA driver is correctly installed.

When worker hangs, the CPU utilization stays low but not zero, and the GPU utilization is 0.

### Source code / logs
I attached below the log from worker 1 [worker1.txt](https://github.com/tensorflow/tensorflow/files/1136607/worker1.txt). In this case, worker 1 hangs, and worker 0 starts training. (There are some custom logs printed.) In the log you can find that worker 1 sent a `RDMA_MESSAGE_TENSOR_REQUEST` to the parameter server, but never got an ACK, and I have checked the log from the parameter server, which showed that it never received a `RDMA_MESSAGE_TENSOR_REQUEST` from worker 1.

I also attached the full trace [gdb_worker1.txt](https://github.com/tensorflow/tensorflow/files/1136672/gdb_worker1.txt) collected on worker 1 in gdb with `thread apply all bt`, during worker 1 hanging.

Thanks.

**Comment by on-the-run** [comment]
@junshi15 Could you shed some light on this? Thanks!

**Comment by byronyi** [comment]
Have you tried your code in loopback mode? It helps to make sure that the problem doesn't lie in your network fabrics configuration.

**Comment by on-the-run** [comment]
@byronyi Thanks for the quick reply. I have tried my code over Ethernet, and it worked fine. I think that should indicate the network fabrics is fine. Also, one experiment I tried over RDMA did go through as I described in the issue. So RDMA fabric seems fine. The loopback mode won't traverse the network stack, right?

**Comment by byronyi** [comment]
Note that RoCE requires a lossless fabric, while gRPC does not. If you could reproduce the error in loopback mode, it would be easier for us to identify the possible issue.

**Comment by shamoya** [comment]
@on-the-run, can u verify the RoCE configuration with ib_write_bw between the 2 nodes ?
As @byronyi said, you may need to configure lossless (PFC) or ECN to prevent the packet loss.
ib_write_bw is a good stress test to see if RoCE is configured good.
Can u attach the full logs of the PS and worker ? I'm missing a lot of events here in the logs.

**Comment by on-the-run** [comment]
@shamoya, the RDMA I am using is Infiniband, instead of RoCE. `ib_write_bw` runs fine. The workers and the parameter sever can talk to each other via RDMA. Posting the output from running `ib_write_bw` between one worker and one parameter server below. 
```
---------------------------------------------------------------------------------------
                    RDMA_Write BW Test
 Dual-port       : OFF          Device         : mlx4_0
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 CQ Moderation   : 100
 Mtu             : 2048[B]
 Link type       : IB
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0x15 QPN 0x32da PSN 0xebb028 RKey 0xa0010194 VAddr 0x007f11bbfc2000
 remote address: LID 0x12 QPN 0x0337 PSN 0x198251 RKey 0xd001018f VAddr 0x007f728f89f000
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
 65536      5000             6071.23            6071.03            0.097136
---------------------------------------------------------------------------------------
```

**Comment by on-the-run** [comment]
@shamoya, about the logs of PS and worker, I didn't turn on VLOG for the log file I posted earlier. will a log with VLOG(2) enabled useful?

**Comment by shamoya** [comment]
If it's IB then we shouldn't have any packet loss.
VLOG(2) is maybe too much verbose, maybe just change all VLOG in rdma.cc to 0, so we can just see the Rendezvous protocol messages.
How many model parameters are there ?

**Comment by junshi15** [comment]
@on-the-run Did you even run an example successfully, say InceptionV3 training on ImageNet dataset?

**Comment by on-the-run** [comment]
@junshi15, Yes. The same code did go through once on RDMA, and it worked well at that time. I didn't try InceptionV3, though.

**Comment by junshi15** [comment]
that's strange. I have not seen issues like that, Your problem probably depends on the ordering of events, which is random. I am wondering if there is memory corruption somewhere.

**Comment by on-the-run** [comment]
@junshi15, one thing that I observed to happen repeatedly was that after the RDMA channels have been built, worker 1 sent a `RDMA_MESSAGE_TENSOR_REQUEST ` to PS, and never got an ACK. Then worker 1 was blocked there. And, PS never received that `RDMA_MESSAGE_TENSOR_REQUEST `. Does this ring a bell?

**Comment by on-the-run** [comment]
@shamoya, there are about 70 million parameters. Here are full logs:
[ps.txt](https://github.com/tensorflow/tensorflow/files/1137272/ps.txt), 
[worker0.txt](https://github.com/tensorflow/tensorflow/files/1137274/worker0.txt), 
[worker1.txt](https://github.com/tensorflow/tensorflow/files/1137275/worker1.txt)
In this case, worker 1 hanged, but worker 0 didn't. Not sure if the log of worker 1 gives enough information. Let me know if you need me to turn on other logs. Thanks.

**Comment by suiyuan2009** [comment]
does distributed tensorflow using 'grpc+verbs' have unit tests? I didn't find any. I meet `2017-07-11 09:46:46.591411: F tensorflow/contrib/verbs/rdma.cc:95] Check failed: cq_ Failed to create completion queue
` when using 'grpc+verbs' in an ib network.

**Comment by junshi15** [comment]
@on-the-run RDMA_MESSAGE_TENSOR_REQUEST is a fairly simple message. Here are some possibilities why PS did not receive it.
1) the message was not sent by worker. Note we only enqueue the message. The actual RDMA write happens [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L640-L656), by logging more in that function, we will know if the message is indeed written.

2) the message was not received at PS. [Here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L121-L127) is how we get notification of events. I do not expect and missed events, but maybe there are corner cases...
My focus would be on (1) since it is easier to verify. If in doubt, You can also check if the worker's tx_message_buf and PS' rx_message_buf addresses are paired, so that messages go to the right buffer.

**Comment by junshi15** [comment]
@suiyuan2009 It's a good idea to add unit tests. right now there is none. Your error is likely due to hardware config. For example, the IB adapter is down. One situation I have seen is some people have multiple IB adapters, let's say the first one is down, the second is up. The current code opens the first [device](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L74), which is down, hence the failure.

**Comment by suiyuan2009** [comment]
@junshi15 , it's seems user and root have different limit in my vm, I use root to run tf then it works.

**Comment by on-the-run** [comment]
@junshi15, Thanks for the suggestion. For 1, I am pretty sure that the RDMA write from worker succeeded, or at least didn't return non-zero value. The evidence is that this [line](url) went through, and I did see the code in `ibv_post_send()` (defined in `infiniband/verbs.h`) was executed. I will try to look at 2 and 3.

**Comment by suiyuan2009** [comment]
I meet stuck problem twice today when using `grpc` not `grpc+verbs`.

**Comment by on-the-run** [comment]
@junshi15, some updates about (2) and (3). I am attaching new logs, which give more information on RDMA related events, but fewer lines. In this case, both workers hang.
[ps.txt](https://github.com/tensorflow/tensorflow/files/1142795/ps.txt)
[worker0.txt](https://github.com/tensorflow/tensorflow/files/1142797/worker0.txt)
[worker1.txt](https://github.com/tensorflow/tensorflow/files/1142798/worker1.txt)

For (2), I believe the message is not received by PS, but don't know why. In the logs you can find the buffers are correctly paired.

For (3), I don't think there is a hashing collision, since not even one tensor had been successfully sent yet in the logs attached.

Could you shed some light on the following questions? 
(1) Which part of the code send the `RDMA_MESSAGE_ACK`? Why did I see `RDMA_MESSAGE_ACK` received in `rx_message_buffer`? 
(2) What will happen if all the outstanding `SendNextItem()` end up with doing nothing (which seems to be the case shown in the logs)?  
(3) At line 87 and 88 of [ps.txt](https://github.com/tensorflow/tensorflow/files/1142795/ps.txt), PS received a `RDMA_MESSAGE_ACK` from worker 1. This doesn't make sense since PS had never sent any message to worker 1, nor worker 1 had received any message from PS.

**Comment by shamoya** [comment]
@on-the-run, Looking at the ps log, something doesn't make sense to me.
The second call of RecvFromRemoteAsync is for Tensor 140513923548928.
The thread (coming from RecvFromRemoteAsync) then calls EnqueItem (with a lock) and then SendNextItem which doesn't do Write since local and remove are busy.
But this tensor should stay at the top of the queue, and the next SendNextItem should send it, but that doesn't happen (same for the third tensor - 140514712069888)

After the RDMA_MESSAGE_ACK is received (which set remote = idle and calls SendNextItem) the SendNextItem takes Tensor 140513093064448, and I don't understand why ? 

Is it possible your print change the locking scheme of the queue ?

**Comment by on-the-run** [comment]
@shamoya, My `tid` actually means thread id. Sorry for the confusion. I think PS finally sent three `RDMA_MESSAGE_TENSOR_REQUEST`, which matches the number of calls of `RecvFromRemoteAsync `. But I did added some VLOG inside lock surrounded code. Will that break something?

**Comment by on-the-run** [comment]
@shamoya, I just noticed this odd behavior, too. It seems that somehow the code got a `RDMA_MESSAGE_TENSOR_REQUEST ` but thought it got a `RDMA_MESSAGE_ACK `. Note that in the log PS also received a `RDMA_MESSAGE_ACK ` from worker 1, but worker 1 only sent a `RDMA_MESSAGE_TENSOR_REQUEST `.

I am running it on x86_64. How can I check the endian issue? Is endian handled by the Infiniband driver?

**Comment by byronyi** [comment]
I don't have an idea of the acutal issue, but as far as I know the immediate data is in network byte-order. You should use `wr.imm_data = htonl(val)` and `imm_data = ntohl(wc.imm_data)` to store and load the immediate data.

**Comment by on-the-run** [comment]
@byronyi @shamoya, Does that mean the code [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L597-L612) should be converted with `htonl()`, before sending to the RDMA hardware?

**Comment by byronyi** [comment]
See [here](https://github.com/linux-rdma/rdma-core/blob/dceee9494bfbadf0cf16b8fef81f3c2cb5355243/librdmacm/examples/udaddy.c#L213) and [there](https://github.com/linux-rdma/rdma-core/blob/dceee9494bfbadf0cf16b8fef81f3c2cb5355243/librdmacm/examples/udaddy.c#L459) for an example.

And yes, but you need to change save/load together.

**Comment by on-the-run** [comment]
@shamoya @byronyi, Yes. It sounds like we found something! Let me try the change and get back. Thanks!

**Comment by junshi15** [comment]
@on-the-run 
some high-level stuff:
there are three types of buffers, message/tensor/ack, each of them has tx and rx version. "tx" is for sending and rx is for receiving. tensorbuf is for tensor exchange, messagebuf is for message and all acks are on ackbuf. Since there is one one pair of message buffer and one pair of ack buffer, all the messages needs to be sent one by one. So are all the packs.

When a message is sent from A to B, in most cases, B needs to send an [ack](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L199), hence if you look at A's log, you have "sent RDMA_MESSAGE_XXXX", then "received RDMA_MESSAGE_ACK". In B's log, you should have "received RDMA_MESSAGE_XXX", then "sent RDMA_MESSAGE_ACK"

it seems all nodes sent "RDMA_MESSAGE_TENSOR_REQUEST" and received "RDMA_MESSAGE_ACK". I don't see any log from B's perspective. this is odd. A logging issue?

To answer your questions:
1) Mostly in Process_CQ(), e.g. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L154

2) buffers are busy. Remember all the messages has to be sent sequentially. A message can be sent only if both local tx-buf and remote rx-buf are idle. I think worker1 was stalled there.

3) I don't see any "sent RDMA_MESSAGE_ACK". logging issue?

**Comment by shamoya** [comment]
Actually I'm not sure this is the cause, the imm_data is the same one sent from the PS and received by worker0 (986591585). Nothing would have it this was the case.

Maybe the NameHash function acts different between the 2 nodes ? 
in PS this hash is for "rx_message_buffer" (RdmaMessageBuffer::SendNextItem) but somehow it worker0 the FindBuffer acts differently ?

**Comment by shamoya** [comment]
Thanks @junshi15 
In (1) he meant if the type is recv RDMA_MESSAGE_ACK, then rb (derived from imm_data) must rx_ack_buffer (which isn't the case here for some reason).

**Comment by shamoya** [comment]
@on-the-run - same TF version / dependent python packages on all sides ?
Important to mention I don't see this issue.

**Comment by on-the-run** [comment]
@shamoya, Yes, everything is the same on PS and workers: TF version, CUDA drivers, IB drivers, etc. I launch them with the same docker image.

**Comment by on-the-run** [comment]
@shamoya, I have checked that behaviors of `NameHash()` and `FindBuffer()` are consistent across PS and workers.

**Comment by shamoya** [comment]
I see.
Then what's happening here is very strange.
I see also my previous claim is wrong since the imm_data is correct and also the RDMABuffer (rx_message_buffer). so the only think I can think of is the buffer of rx_message_buffer is corrupted/not read well by ParseMessage.

**Comment by junshi15** [comment]
@on-the-run, It is strange I don't see any log about "RDMA_MESSAGE_ACK sent" and "RDMA_MESSAGE_TENSOR_REQUEST received".
Did you log anything inside [RdmaAckBuffer::SendNextItem()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L628-L637)? 

Also, I see many occurrence of `recv RDMA message: RDMA_MESSAGE_ACK, imm_data recevied = 986591585`. I assume 986591585 is NameHash('rx_ack_buffer'), can you confirm?

**Comment by on-the-run** [comment]
@junshi15, I did log inside `RdmaAckBuffer::SendNextItem()`. It was jut not triggered. 986591585 is the hash of "rx_message_buffer" instead of "rx_ack_buffer". That's why I can't understand why the `RDMA_MESSAGE_ACK` was sent to rx_message_buffer. Is it possible that somehow the code misunderstands `RDMA_MESSAGE_TENSOR_REQUEST ` to be `RDMA_MESSAGE_ACK`? Since that assumption can explain the strange log events.

**Comment by on-the-run** [comment]
@shamoya, RDMA driver version: libibverbs-dev (1.2.1mlnx1-OFED.4.0.1.5.3.40200).

**Comment by shamoya** [comment]
@on-the-run - it's just the version VERBS library, I would like to know also the kernel drivers of the HCA and also the FW version. please attach the output of:
- ofed_info -s
- ibv_devinfo

Also what do u think of my guess (all received buffer is actually 0 - and then it's parsed as RDMA_MESSAGE_ACK) ?

**Comment by on-the-run** [comment]
@shamoya, sorry, I am not so familiar with these stuff.
Output of `ofed_info -s`:
```
MLNX_OFED_LINUX-4.0-2.0.0.1:
```
Output of `ibv_devinfo`:
```
hca_id: mlx4_0
        transport:                      InfiniBand (0)
        fw_ver:                         2.40.7000
        node_guid:                      248a:0703:00bd:5740
        sys_image_guid:                 248a:0703:00bd:5743
        vendor_id:                      0x02c9
        vendor_part_id:                 4099
        hw_ver:                         0x1
        board_id:                       MT_1100120019
        phys_port_cnt:                  1
        Device ports:
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5)
                        sm_lid:                 1
                        port_lid:               18
                        port_lmc:               0x00
                        link_layer:             InfiniBand
```

I think your guess makes sense. I am trying to log all the values of each work completion event. Will get back.

**Comment by junshi15** [comment]
We are using mlx5_0, if it matters.

hca_id:	mlx5_0
	transport:			InfiniBand (0)
	fw_ver:				12.1100.6630
	node_guid:			e41d:2d03:0067:c9fc
	sys_image_guid:			e41d:2d03:0067:c9fc
	vendor_id:			0x02c9
	vendor_part_id:			4115
	hw_ver:				0x0
	board_id:			MT_2180110032
	phys_port_cnt:			1
	Device ports:
		port:	1
			state:			PORT_ACTIVE (4)
			max_mtu:		4096 (5)
			active_mtu:		4096 (5)
			sm_lid:			2
			port_lid:		3
			port_lmc:		0x00
			link_layer:		InfiniBand

**Comment by junshi15** [comment]
@byronyi Thanks for raising the endian-ness issue. It will probably improve the portability. 

If one of the nodes in the cluster is linux (little endian) and another is hp-ux (big endian), for example, then there may be problems. If the cluster is homogeneous, then there should be no issue.

**Comment by on-the-run** [comment]
@junshi15, when parsing a `RdmaMessage` with `ParseMessage()`, does it need to be protected by lock?

**Comment by junshi15** [comment]
The message and tensor rx_buffers are read-only locally and protected  at the remote end by "[remote_status_](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L644-L645)". I don't see same protection on [the ack rx_buffer](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L628-L637).
I need to think about the reason why ack buffers are treated differently.

**Comment by on-the-run** [comment]
@shamoya, I have checked the work completion events. It looks fine to me. Most importantly, the `imm_data` is correctly sent. So it is not an endian issue. But the endian should be considered as it suggests here in `infiniband/verbs.h`:
```
 struct ibv_wc {
     uint64_t        wr_id;
     enum ibv_wc_status  status;
     enum ibv_wc_opcode  opcode;
     uint32_t        vendor_err;
     uint32_t        byte_len;
     /* When (wc_flags & IBV_WC_WITH_IMM): Immediate data in network byte order.
      * When (wc_flags & IBV_WC_WITH_INV): Stores the invalidated rkey.
      */
     uint32_t        imm_data;
     uint32_t        qp_num;
     uint32_t        src_qp;
     int         wc_flags;
     uint16_t        pkey_index;
     uint16_t        slid;
     uint8_t         sl;
     uint8_t         dlid_path_bits;
};
```
It looks to me now a memory corruption issue.

**Comment by junshi15** [comment]
@on-the-run 
I refreshed my memory. Here is how the buffers are protected. I will focus on rx buffer which is protected by its remote side (tx side).

Rx_TensorBuffer:
When we send a tensor via TensorBuffer, we need to make sure both the Tx_TensorBuffer (at the sender) and the Rx_TensorBuffer (at the receiver) are idle. This is achieved by checking [local_status_ and remote_status_] (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L778) at the sender under a lock. When the tensor is received, the receiver send a [RDMA_MESSAGE_BUFFER_IDLE message](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma_rendezvous_mgr.cc#L142) to release remote_status_, while local_status_ is released at the [sender](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L222).

Rx_MessageBuffer:
Similar to Rx_TensorBuffer, both local_status_ and remote_status_ flags are [checked](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L643). They are turned to [busy](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L644-L645) once transmission starts. When the receiver reads the buffer, it sends an ACK to notify the sender to release [remote_status_](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L153).

Rx_AckBuffer:
No protection at all. The sender does not check AckBuffer before sending an Ack. This is OK because (1) all the acks are sent (`ab->SendNextItem()`) by one thread inside Process_CQ().
(2) messages and acks are interleaved. Let's say A wants to send multiple messages to B. After the first message is sent, A has to wait for the ack before sending the next message, i.e. [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L148) is the only place tx_message_buffer_.remote_status_ becomes idle. Since A can not send multiple messages consecutively, B can not ack consecutively. No risk of multiple ACKs stepping on each other.

But I afraid I may have missed corner cases. This messaging system is very fragile. If one message, even an ACK, is missing, you will likely get a hang.

To further debug, I suggest [the following change]:(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.h#L55-L60). Switch `RDMA_MESSAGE_ACK`  with `RDMA_MESSAGE_TENSOR_WRITE`. If indeed all message types are zero due to memory corruption, you should see all `RDMA_MESSAGE_TENSOR_WRITE` in your log.

**Comment by on-the-run** [comment]
@junshi15, Thanks for the explanation. I think memory corruption is confirmed. I switched the order of `RDMA_MESSAGE_ACK ` and `RDMA_MESSAGE_TENSOR_WRITE`. Now the first message received by worker 0 is indeed `RDMA_MESSAGE_TENSOR_WRITE`, which should be the `RDMA_MESSAGE_TENSOR_REQUEST` sent by PS. Worker 0 later failed at the CHECK [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L455). Need to figure out why memory is corrupted.

**Comment by junshi15** [comment]
@on-the-run Thanks for the info. I did not see any obvious reason. it may require a serious debug.

**Comment by shamoya** [comment]
Hi @on-the-run - can u print the buffer (not the completion buffer) ? 
I want to see if it's all 0's.
I'm not sure why we don't see the issues u r seeing .. looks like something severe in your case.

**Comment by bobzhuyb** [comment]
Hello @shamoya, I am working with @on-the-run on this issue. One important fact we observed is that with only one GPU per server, it will run without a problem. However, with increasing number of GPUs per server, the more likely it will get stuck. With eight GPU, it rarely runs.

Since our logs show that 1. the (virtual) memory addresses are correctly mapped and exchanged, 2. the NIC reports RDMA WRITE is successful, 3. userspace sees the target buffer remains unchanged (we try initializing rx_message_buffer with 0 or different values, any values remain unchanged), we suspect that the problem is because the mapping from virtual addr to physical addr has changed.

We suspect that this is related to we are using CUDA 8 and Pascal GPU, with which Nvidia has a new memory management feature (https://devblogs.nvidia.com/parallelforall/cuda-8-features-revealed/)

This is what may have happened (our speculation):
1. ibv_reg_mr --> NIC remembers the physical addr
2. CUDA maps the eight GPUs' memory to virtual addr, somehow changed the userspace virtual addr to physical addr mapping. 
3. RDMA transmission starts, NIC thinks it has written to the physical addr, but when the tensorflow process checks the memory contents, the process is actually looking at a different physical addr.

Our current workaround is to call mlock() right after malloc in rdma.cc. It tells the OS to pin the physical memory. We have run our program successfully for a few times since the change. We'll continue checking whether it really solves the problem.

I am not sure which is the right side to blame -- we don't expect CUDA to change the virtual addr mapping, however it seems that it does, especially when it works aggressively (with eight GPU). We expect ibv_reg_mr to pin the memory, however we searched through the ibv_reg_mr implementation in OFED and didn't see it did that.

**Comment by byronyi** [comment]
Maybe I have some fundamentally wrong assumptions about how memory registration works in verbs, but shouldn't the IB driver pin the memory pages in kernel space, as verbs user space library will send a command in ibv_cmd_reg_mr?

The user space library is not supposed to pin the user pages in user space API, like mlock(2).

**Comment by on-the-run** [comment]
@byronyi, If I am looking at the correct place, I didn't find any memory pinning done inside [`ibv_cmd_reg_mr()`](https://github.com/linux-rdma/rdma-core/blob/master/libibverbs/cmd.c#L358).

**Comment by byronyi** [comment]
It's inside the providers directory, e.g. mlx4_reg_mr

**Comment by on-the-run** [comment]
@byronyi, I believe both `mlx5_reg_mr()` and `mlx4_reg_mr()` call `ibv_cmd_reg_mr()`, but there seems no memory pinning done.

**Comment by bobzhuyb** [comment]
@byronyi, Personally, I used to believe that too. However, @on-the-run and I both searched in the code and didn't see the memory pinning. In the past, I have done very heavy hacking in the verbs libs, as heavy as rewriting most of the verbs code. Still, I cannot find it. 

However, I am not sure what happens after ibv_cmd_reg_mr (I believe this is the last step in userspace. mlx4_* calls ibv_cmd_*) passes the cmd to underlying driver. Mellanox @shamoya should be able to tell us more about this.

**Comment by junshi15** [comment]
All the buffers are allocated in [system memory](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/rdma.cc#L296-L299), so CUDA8 should not play a role here. My impression is that `ibv_reg_mr` does pin the memory, although I am not familiar the source code. @shamoya may be able to explain it.

**Comment by bobzhuyb** [comment]
@junshi15 I understand that you only allocate main memory. Nevertheless, CUDA starts after your code, and with Pascal GPUs, it maps GPU memory to the same virtual memory address space as the process (see Unified Memory in https://devblogs.nvidia.com/parallelforall/cuda-8-features-revealed/). We do not know what it does with the existing virtual addr and physical addr mapping.

Otherwise, I don't know how to explain why it works with one GPU, while starts to break with more GPUs..

**Comment by byronyi** [comment]
Maybe I didn't make it clear, I mean the verbs library is not doing nor supposed to do memory pinning in user space: that job is solely done by the in kernel part of your IB driver. Thus you should search it in the kernel source tree and kernel memory pinning API, something like `get_user_pages`, not the syscall nor user space API like `mlock`.

**Comment by byronyi** [comment]
@bobzhuyb And I think I have checked with TF people before, and they have made it pretty clear that TF is not designed to utilize UVM nor support this feature. See relevant discussion in [here](https://github.com/tensorflow/tensorflow/issues/3678#issuecomment-238064949). I also tend to believe neither IB driver or CUDA driver should alter memory mappings managed by the other one, as we are not doing peer memory access for NIC and GPU.

On the other hand I have worked with TF memory allocation subsystem and they are doing a pretty good job on keeping track of CUDA host/device memory allocation. See relevant details for [host](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/process_state.cc#L241) and [device](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/process_state.cc#L113) memory. And if you adjust those parameters (like the initial memory allocation or `allow_growth=False`), you could force it to allocate all CUDA memory at very early stage (before the whole distributed runtime is even initialized). After that, the virtual memory mappings of these memory regions should not be altered. If you do that, the step 2 of your speculation is rather unlikely to happen.

Being said that, the is a possibility that something is wrong in either CUDA or IB driver, but our chances are small. cc @zheng-xq @poxvoculi any comments on this?

**Comment by shamoya** [comment]
@on-the-run @bobzhuyb, the assumption doesn't make sense to me.
The memory is being pinned in https://github.com/torvalds/linux/blob/master/drivers/infiniband/core/umem.c#L83 , which is executed in the ibv_reg_mr flow, so mlcok shouldn't have any effect.
Also as @byronyi (this is what I know as well) said, TF doesn't support UVM.
Are u sure this is the only thing u changed that fixed the bug ? 

I'm having a similar issue with 8 P100 per node (4 nodes), happens with only certain conditions (tf_cnn_script benchmark with "real" data) and the pinning issue is not the case.
I think maybe found the issue (checking now and will report soon).

**Comment by bobzhuyb** [comment]
@byronyi @shamoya Thanks for the clarification. Yes, mlock() was the thing that made it stable in our environment. Good to know that you can reproduce the issue. Please keep us posted.

**Comment by shamoya** [comment]
Hi @bobzhuyb, 
The mlock solution still doesn't make sense to me.
it shouldn't have any effect, unless you a severe driver issues.
Can u involve RDMA community in this issue in https://github.com/linux-rdma/rdma-core ? 

Anyway my issue still not solved, I opened an issue in https://github.com/tensorflow/tensorflow/issues/11725.

Any help is appreciated, if u can take a look.
@junshi15 @byronyi if u have time I would be delighted as well.

**Comment by shamoya** [comment]
Hi @on-the-run,
Is there any way to know if the CUDA remaps the memory mapping of the process ?
As said, I feel we see a similar issue, but the mlock workaround doesn't help in our case.
We also feel it's something to do with Pascal memory management (can't say exactly what).
Any clues to what we can check ? 
Thanks !

**Comment by junshi15** [comment]
I was using K80 and CUDA-7.5, and was able to reproduce the other issue (#11725). So at least that issue is not only limited to Pascal.

**Comment by bobzhuyb** [comment]
We don't have a concrete evidence. However, we did a basic test -- when we malloc the receiver buffer, we init the buffer with a special value as a signature (say every byte initialized as 0xab). After the successful receive event triggered by WRITE_WITH_IMM, we immediate check the receiver buffer value. It remains unchanged in TF process. 

If you use ibdump at the receiver side, you should see the special signature in the packets. So the data must have arrived. Would you do the same as above to confirm that we are seeing the same (or similar) problem?

There are only two potential explanations, 

1. Receiver NIC didn't DMA the data into the receiver buffer -- we don't see why this may happen
2. NIC did write the data to physical memory, but the vaddr mapping has changed

Getting a concrete evidence requires some kernel hacking to get the vaddr to physical addr mapping at different stages.

**Comment by on-the-run** [comment]
@shamoya, unfortunately I am not an expert on CUDA. Also, my colleague @bobzhuyb has taken this issue over. @bobzhuyb, could you give some input when you have time? Thanks!

**Comment by byronyi** [comment]
Hi @bobzhuyb, I made a separate RDMA patch #11392 that supports checksum with VLOG=2. Maybe you could give it a try and see wether the problem persists.
