### ISSUE TITLE
Kernel version vs DSO version mismatch when running example after bazel build

### ISSUE THREAD

**Issue by hemanthdv** [tensorflow/tensorflow#1158]
After successful bazel build, running into error when executing example with gpu. Please suggest on how to resolve. The GPU has been used with MathConvNet (another deep learning package) without this error.
## Log:
`bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:481] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:114] retrieving CUDA diagnostic information for host: en4113750l
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: en4113750l
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported version is: 352.63
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.55  Thu Oct  8 15:18:00 PDT 2015
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported version is: 352.55
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:229] kernel version 352.55 does not match DSO version 352.63 -- cannot find working devices in this configuration
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 
F tensorflow/cc/tutorials/example_trainer.cc:116] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Const/_2': Could not satisfy explicit device specification '/gpu:0'
	 [[Node: Const/_2 = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 0>, _device="/gpu:0"]()]])
F tensorflow/cc/tutorials/example_trainer.cc:116] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Const/_2': Could not satisfy explicit device specification '/gpu:0'
	 [[Node: Const/_2 = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 0>, _device="/gpu:0"]()]])
F tensorflow/cc/tutorials/example_trainer.cc:116] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Const/_2': Could not satisfy explicit device specification '/gpu:0'
	 [[Node: Const/_2 = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 0>, _device="/gpu:0"]()]])
Aborted (core dumped)`

## Specifications:
Ubuntu LTS 14.04
Titan X GPU
CUDA 7.5

**Comment by vrv** [comment]
```
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported version is: 352.63
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module 352.55 Thu Oct 8 15:18:00 PDT 2015
GCC version: gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported version is: 352.55
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:229] kernel version 352.55 does not match DSO version 352.63 -- cannot find working devices in this configuration
```

My guess is that you have to update your cuda driver to 352.63, is that right @zheng-xq  ?

**Comment by hemanthdv** [comment]
Thats right @vrv, but Titan X has had trouble with CUDA 7.5 with the login-loop issue. That's the reason I had installed 352.55. I got it resolved using the tips on http://olivernina.blogspot.com/2015/11/installing-titan-x-drivers-and-cuda-75.html

Get rid of nvidia residuals
`sudo apt-get remove --purge nvidia*`
Reboot and switch to terminal login with Ctrl+Alt+F1. Then download the required version of the nvidia driver (in my case 352.63)
`cd ~/Downloads 
wget us.download.nvidia.com/XFree86/Linux-x86­_64/352.63/NVIDIA-Linux-x86_64-352.63.ru­n`
Then run
`sudo service lightdm stop`
Go to Downloads directory and change permissions to execute and run
`chmod +x NVIDIA*.run`
`sudo ./NVIDIA*.run`

**Comment by viksit** [comment]
Incidentally, one fix for this is to install the right nvidia driver. 

http://www.nvidia.com/download/driverresults.aspx/95159/en-us

**Comment by clockzhong** [comment]
But what's the right version mean? anc can we make them be syncronized automatically? 
I found this issue keep happening after my ubuntu upgrade its components, everytime I need debug this issue mannually. Now my current error logs are:
2018-01-22 10:12:52.860623: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-01-22 10:12:52.860688: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: clockAsusDesktop
2018-01-22 10:12:52.860714: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: clockAsusDesktop
2018-01-22 10:12:52.860790: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.111.0
2018-01-22 10:12:52.860851: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.90  Tue Sep 19 19:17:35 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
"""
2018-01-22 10:12:52.860907: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.90.0
2018-01-22 10:12:52.860934: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 384.90.0 does not match DSO version 384.111.0 -- cannot find working devices in this

**Comment by clockzhong** [comment]
Ok, It's my mistake. My problem is fixed after I upgrade my system with the following commands:

> sudo add-apt-repository ppa:graphics-drivers/ppa
> sudo apt-get update 
> 

and then:

 reboo

**Comment by xiaoyongzhu** [comment]
@clockzhong  I suspect you also executed `sudo apt-get upgrade` after `sudo apt-get update` - which will install the latest driver.

**Comment by clockzhong** [comment]
@xiaoyongzhu  yes, right! It's my typo. And it's corrected now. Thanks.
