### ISSUE TITLE
Documentation for windows install is wrong/misleading

### ISSUE THREAD

**Issue by areel** [tensorflow/tensorflow#12366]
https://www.tensorflow.org/install/install_windows states

Requirements to run TensorFlow with GPU support
cuDNN v5.

This is now incorrect.
TensorFlow 1.3 or later requires cuDNN 6. ('cudnn64_6.dll')

I also suggest you add a comment and link to this gist

https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c

He just saved me hours.

Regards

Aidan

**Comment by Scaws** [comment]
Thank you for posting this! Solved my issue

**Comment by gunan** [comment]
@av8ramit Cam we also mention the helpful script @mrry prepared in our windows installation documentation?
https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c

**Comment by av8ramit** [comment]
https://github.com/tensorflow/tensorflow/pull/12981

**Comment by av8ramit** [comment]
Merged!
