### ISSUE TITLE
Outdated Documentation (ImportError: libcudnn.so.6)

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tensorflow#12416]
### Problem Description
The binary version for GPU provided [here](https://www.tensorflow.org/install/install_linux#python_36) on installation page of Ubuntu expects cuDNN v6. However, the documentation mentions the version of cuDNN required as 5.1.

Kindly rectify the error in documentation.

### System information
- Linux Ubuntu 16.04
- TensorFlow installed from binary (GPU Version)
- Tensorflow version v1.3.0-rc2-20-g0787eee 1.3.0

**Comment by hitvoice** [comment]
I was misled by the documentation as well. Hope it'll be fixed soon.

**Comment by sumitbinnani** [comment]
Even I spent quite a time to resolve the issue when I received the error that:
```
ImportError: libcudnn.so.6 cannot open shared object file: No such file or directory
```

Later I found a Github thread which was in relation to porting to cuDNN 6 (#8828) and realized that the binary is based on version 6 of cuDNN.

Raised the issue so that others don't face the same issue.

**Comment by yongtang** [comment]
I can confirm the same issue. My Linux is Amazon's `Deep Learning AMI Ubuntu Version` which only have cuDNN v5.1 installed. When trying to install with python 3.5 and 
`https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.3.0-cp35-cp35m-linux_x86_64.whl`

The same error happens:

```$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> exit()

```

**Comment by yongtang** [comment]
Added a PR #12463 for the docs change.

**Comment by PeterSansan** [comment]
Today I got the same problem. Thanks for solving the issue.

**Comment by akihirom2017** [comment]
I have got the same problem when installing tensorflow into python3.5.
I am quite new to use this site, I may not follow what's going on.
was this issue solved? if so, how can I fix the issue?
Any helps would be appreciated.
Thank you for your help in advance.

**Comment by Omarkaab** [comment]
I had the same problem. 
Is there a way to go around the issue?

**Comment by coreyhahn** [comment]
I have cuDNN v6.0 and still have this problem.  Is there another fix?

**Comment by sumitbinnani** [comment]
@coreyhahn: Check if the symlink for the `libcudnn.so.6` is at appropriate location (usually `usr/local/cuda/lib64/` and `usr/local/cuda/include`). Also, ensure that the `LD_LIBRARY_PATH` is set.

**Comment by wei-yuan** [comment]
Check this out 
[After building TensorFlow from source, seeing libcudart.so and libcudnn errors
](https://stackoverflow.com/a/45787225/1115215)

**Comment by zrcahyx** [comment]
I don't have the permission to install the cudnn v6 on the server, i only have the cudnn v5. Does anyone have a solution for this problem? This is troubling me, i'll appreciate any help.

**Comment by yongtang** [comment]
@zrcahyx If you could build TensorFlow from source and link against v5 then the binary might be used in your server.

**Comment by zrcahyx** [comment]
@yongtang Thanks for your advice. But i can't even link against v5. I am contacting with my colleague and trying to get cudnn v6 installed on the server.

**Comment by Omarkaab** [comment]
@zrcahyx what version of tensorflow-gpu are you using ?

**Comment by shivajid** [comment]
Install CUDNN6.0. Older version used 5.0. Both 5.0 and 6.0 can co exists. Just download and copy the files to /usr/local/cuda/include and /usr/local/cuda/lib64 the corresponding file. I had this issue upgrading tensorflow to 1.3.

**Comment by RaskaFR** [comment]
Hi all,

About `ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory`. In order to solve this problem, you have to download from cuda [https://developer.nvidia.com/cuda-downloads](url) the appropriate package for your system and write in your `~/.bashrc` : `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/path/to/your/new/cuda/lib64"`. 
`usr/local/cuda/lib64` is the native path for cuda files and you want add the new files you downloaded. That's why you write `:` followed by the new path.
Be careful about having the lastest version for tensorflow (1.3.0).
Hope it helps.

**Comment by jacohend** [comment]
We're still getting this error with libcudnn 6 on ubuntu 16.04.2. . We also tried v5 and v7 symlinked to 6. I tried @RaskaFR 's advice above and still no dice.

**Comment by luizhenriquesoares** [comment]
this is not working on ubuntu 17.04.

**Comment by devill** [comment]
I just ran into the same issue with my keras docker image... did anyone find the solution yet?

**Comment by nazib** [comment]
In my case this command solved the problem
sudo apt-get install libcupti-dev

**Comment by mehrdadscomputer** [comment]
updating to cuDNN v6 for cuda 8 solved my problem

**Comment by evilkjoker** [comment]
same problem, i only have <code>libcudnn.so.7</code>.  I edit binary file <code>python2.7/site-packages/tensorflow/libtensorflow_framework.so</code> , change <strong>libcudnn.so.6</strong> 
  to <strong>libcudnn.so.7</strong> . surprised, it work.

System information
* Linux OpenSUSE 42.3
* Tensorflow version 1.5.0-dev20171103
* cuDNN v6

**Comment by JekaMas** [comment]
Or just `ln -s YOURS_PATH_TO_cuDNN/libcudnn.so.7.0.3 YOURS_PATH_TO_cuDNN/libcudnn.so.6`

**Comment by luizcalaca** [comment]
@wei-yuan Your post works for me! Thanks!

**Comment by AFIDclan** [comment]
Nothing is working for me. I have tried all of the above and the command:
$LD_LIBRARY_PATH/libcudnn.so.6
Finds the file. What can I try next?
Yes, I added export to my bashrc file
Yes, I installed Cudnn (both 6 and 5)

**Comment by guoxiaolu** [comment]
I have import error: ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory
1. download cudnn6.0 version (not latest 7.0)
2.sudo rm -rf /usr/local/cuda/include/cudnn.h
sudo rm -rf /usr/local/cuda/lib64/libcudnn*
3. to cudnn untar folders
sudo cp include/cudnn.h /usr/local/cuda/include/
sudo cp lib64/lib* /usr/local/cuda/lib64/
4. cd  /usr/local/cuda/lib64/
sudo chmod +r libcudnn.so.6.0.21  
sudo ln -sf libcudnn.so.6.0.21 libcudnn.so.6  
sudo ln -sf libcudnn.so.6 libcudnn.so  
sudo ldconfig  
It works for me.
I think @evilkjoker may be useful, @JekaMas It's unsuccessful for me

**Comment by WolfNiu** [comment]
Solution by @guoxiaolu worked for me!! Thank you!!

**Comment by yanxiangyi** [comment]
In my case, the failure only occurs when I start Python3 with `sudo`. Remove `sudo` everything is just fine.

**Comment by umarKarim** [comment]
One thing that worked for me was that rather than using 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64" ' I used 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:~/cuda/lib64" ' and it worked. I have to do it everytime the computer starts. Dont know what is cuda doing in my home folder and don't know why I need to do it everytime.

**Comment by Inchini** [comment]
@guoxiaolu it worked for me thanks

**Comment by pkufergus** [comment]
add into env 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/cudnn/c
udnn_v6/cuda/lib64
