### ISSUE TITLE
Install instructions should ask for libcudnn 6.0

### ISSUE THREAD

**Issue by frehoy** [tensorflow/tensorflow#12521]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 17.04
- **TensorFlow installed from (source or binary)**:
binary (pip3)
- **TensorFlow version (use command below)**:
v1.3.0-rc2-20-g0787eee 1.3.0
- **Python version**: 
Python 3.5.3
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
6.0
- **GPU model and memory**:
GTX 1080 8GB
- **Exact command to reproduce**:
NA

### Describe the problem
The install instructions at https://www.tensorflow.org/install/install_linux tell users to install libcudnn 5.1. 
I followed these and ended up with the error on 

    import tensorflow

    ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

So I installed libcudnn 6.0 instead and tensorflow is now working. 
My request is for the install instructions to be updated to reflect the move to cudnn 6.0

### Source code / logs
NA

**Comment by yongtang** [comment]
See #12416 and  PR #12463.

**Comment by jubjamie** [comment]
Similar issue for Windows users here #11784

**Comment by jubjamie** [comment]
@frehoy I believe this got fixed alongside #11784

**Comment by dr4b** [comment]
Yeah, this is definitely fixed and you can even see it in the docs_src directory here on Github:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_linux.md

But it sometimes takes a while for these things to propagate to the root directory on tensorflow.org as we usually only update that with version releases.

**Comment by sdlmw** [comment]
@frehoy  hello, i have a question. thank help me fix it. 
![qq 20170830183806](https://user-images.githubusercontent.com/13164077/29868736-b82eafae-8db2-11e7-976f-2e6247b351b6.png)
 i have installed  cuDNN v6.0. CUDA Version:8.0, Nvidia driver is newest.
thank you before

**Comment by mehrdadscomputer** [comment]
updating to cuDNN v6 for cuda 8 solved my problem
