### ISSUE TITLE
cuDNN 6 incompatible with Tensorflow 1.3 error

### ISSUE THREAD

**Issue by BogdanPugach** [tensorflow/tensorflow#13068]
Any help is greatly appreciated! I've spent way too much time on this. 

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
In tensorflow/stream_executor/cuda/cuda_gpu_executor.cc in function "static int TryToReadNumaNode(conststring &pci_bus_id,intdevice_ordinal)" added the following lines at the beginning of the function:
LOG(INFO) << "ARM has no NUMA node, hardcoding to return zero";
return 0;
modified workspace.bzl: set eigen_archive to use http://mirror.bazel.build/bitbucket.org/eigen/eigen/get/d781c1de9834.tar.gz because of an error that kept coming up related to the current version of eigen.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
 Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
source

- **TensorFlow version (use command below)**:
1.3.0
command used: git checkout v1.3.0

- **Python version**: 
2.7

- **Bazel version (if compiling from source)**:
0.4.5

- **CUDA/cuDNN version**:
CUDA version 8.0, CUDNN version 6.0.21
cudnn was downloaded from the NVIDIA website using the cuDNN v6.0 Library for Linux version

- **GPU model and memory**:
NVIDIA Pascal GPU on the TX2

- **Exact command to reproduce**:
sudo bazel build -c opt --local_resources 3072,4.0,1.0 --verbose_failures --config=cuda //tensorflow/tools/pip_package:build_pip_package

- **Other*:
Using an 8GB swapfile
CUDA install path: usr/local/cuda/
CUDNN install paths:
     include: /usr/include/
     libs: /usr/lib/aarch64-linux-gnu/
     I used the following command on the libs: sudo chmod a+r /usr/lib/aarch64-linux-gnu/libcudnn*

### Describe the problem
When I try to install tensorflow 1.3.0 I get the error listed below. It goes through pretty much the entire build and fails at the very end. Tensorflow 1.0 installs just fine on the TX2 using cuda 8 and cudnn 5.1(these lib are no longer on my machine so its not an issue with having 5.1 installed). I would use Tensoflow 1.0, but the network I am working with has a reliance on 1.3. 

### Source code / logs
IERROR: /home/nvidia/tensorflow/tensorflow/python/BUILD:2762:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed: link_dynamic_library.sh failed: error executing command 
  (cd /home/nvidia/.cache/bazel/_bazel_root/d2751a49dacf4cb14a513ec663770624/execroot/tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.2 \
    TF_CUDA_VERSION=8.0 \
    TF_CUDNN_VERSION=6.0.21 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \
  external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o bazel-out/local_linux-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so -Lbazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccusolver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccublas___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccuda_Udriver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccufft___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccurand___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccusolver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccublas___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccuda_Udriver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccufft___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccurand___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' -Wl,--version-script tensorflow/tf_version_script.lds -Wl,-z,muldefs -Wl,-rpath,../local_config_cuda/cuda/lib64 -Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64 -pthread -Wl,-no-as-needed -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections -Wl,@bazel-out/local_linux-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld: skipping incompatible bazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible bazel-out/local_linux-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible /usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible /usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible //usr/lib/aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible //usr/lib/aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: cannot find -l:libcudnn.so.6
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 5.977s, Critical Path: 4.15s

**Comment by aselle** [comment]
@gunan, have you ever seen this? I would basically suggest reinstalling cuda and cudnn in the more standard locations of /usr/local/cuda/..., but it appears it is finding them but you are getting these errors:
```
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible //usr/lib/aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible //usr/lib/aarch64-linux-gnu/libcudnn.so.6 when searching for -l:libcudnn.so.6
```

**Comment by gunan** [comment]
I think that means the libraries you installed are either incompatible with your system, or the TF libraries incompatible with what you have. I dont have much insight, as we never tested on TX2.

@petewarden in case he know something about TX* systems.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
I feel like this is due to some bazel/compiler options used. But I cannot be sure.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by gunan** [comment]
could you try adding `--action_env=LD_LIBRARY=${LD_LIBRARY_PATH}` to your bazel command?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by Jason08** [comment]
same issue on my TX2...  the version of TF is 1.4



ERROR: /home/nvidia/tensorflow/tensorflow/BUILD:573:1: Linking of rule '//tensorflow:libtensorflow_framework.so' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/nvidia/.cache/bazel/_bazel_nvidia/d2751a49dacf4cb14a513ec663770624/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/home/nvidia/cuda/lib64:/usr/local/cuda-8.0/lib64: \
    PATH=/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o bazel-out/host/bin/tensorflow/libtensorflow_framework.so '-Wl,-rpath,$ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccublas___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccuda_Udriver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccufft___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccurand___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' '-Wl,-rpath,$ORIGIN/../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' -Lbazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccublas___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccuda_Udriver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccufft___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccurand___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib -Lbazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib '-Wl,-rpath,$ORIGIN/' -pthread -Wl,-rpath,../local_config_cuda/cuda/lib64 -Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64 -Wl,-no-as-needed -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/tensorflow/libtensorflow_framework.so-2.params)
/usr/bin/ld: skipping incompatible bazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: skipping incompatible bazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudnn.so.6 when searching for -l:libcudnn.so.6
/usr/bin/ld: cannot find -l:libcudnn.so.6
collect2: error: ld returned 1 exit status


For help

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
I think we are missing a CPU arg here, we may need to tell bazel that it needs to build for arm CPUs.
Could you try adding flags:
```
--cpu=armeabi
--crosstool_top=@local_config_arm_compiler//:toolchain
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by oscarriddle** [comment]
I encountered a similar issue.
OS: CentOS
TF source: r1.7
gcc: 4.9.3
CUDA: 9.0
cudnn: 7.0.5

```
Error:
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded).
INFO: Found 1 target...
ERROR: /media/disk1/fordata/web_server/project/xiaolun/workshop/tensorflow.gpu.1.7/tensorflow/BUILD:744:1: Linking of rule '//tensorflow:libtensorflow_framework.so' failed (Exit 1)
/usr/bin/ld: skipping incompatible bazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudnn.so.7 when searching for -l:libcudnn.so.7
/usr/bin/ld: skipping incompatible bazel-out/host/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudnn.so.7 when searching for -l:libcudnn.so.7
/usr/bin/ld: skipping incompatible /usr/local/lib/libcudnn.so.7 when searching for -l:libcudnn.so.7
/usr/bin/ld: skipping incompatible /usr/local/lib/libcudnn.so.7 when searching for -l:libcudnn.so.7
/usr/bin/ld: skipping incompatible /lib/libcudnn.so.7 when searching for -l:libcudnn.so.7
/usr/bin/ld: skipping incompatible /lib/libcudnn.so.7 when searching for -l:libcudnn.so.7
/usr/bin/ld: skipping incompatible /usr/lib/libcudnn.so.7 when searching for -l:libcudnn.so.7
/usr/bin/ld: skipping incompatible /usr/lib/libcudnn.so.7 when searching for -l:libcudnn.so.7
/usr/bin/ld: cannot find -l:libcudnn.so.7
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.800s, Critical Path: 0.28s
FAILED: Build did NOT complete successfully
```
Seems the bazel has found the libcudnn.so.7, but it thinks it's incompatible.

**Comment by oscarriddle** [comment]
I solved this problem.
It's because I used cuDNN 7.1.2, which is incompatible, after changing to 7.0.5, the compilation successfully done.
So next time, if anyone encountered this problem, confirm your lib.so version.
