### ISSUE TITLE
Resource exhausted

### ISSUE THREAD

**Issue by omarcr** [tensorflow/tensorflow#1355]
This error happens when training several models in a for loop:

`W tensorflow/core/common_runtime/executor.cc:1076] 0x18ef02bb0 W tensorflow/core/common_runtime/executor.cc:1076] 0x18ef02bb0 Compute status: Resource exhausted: OOM when allocating tensor with shape
	 [[Node: sub_2518 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](sub_2518/x, Variable_1955/read)]]
Traceback (most recent call last):
  File "/media/konet/01D15611945D72C0/Pycharm_ubuntu/deep_neural_network_binary/dnn_127_models_binary.py", line 398, in <module>
    fited = model.fit(Xtrain, ytrain, nb_epoch=n_epochs, batch_size=batch_size, show_accuracy=True, shuffle=True, validation_split=0.35)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 581, in fit
    shuffle=shuffle, metrics=metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 239, in _fit
    outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 336, in __call__
    updated = session.run(self.outputs + self.updates, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 3200 } dim { size: 2000 }
	 [[Node: mul_4305 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Variable_1954/read, Variable_1956/read)]]
	 [[Node: add_3103/_9711 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_423_add_3103", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'mul_4305', defined at:
  File "/media/konet/01D15611945D72C0/Pycharm_ubuntu/deep_neural_network_binary/dnn_127_models_binary.py", line 387, in <module>
    model.compile(loss='binary_crossentropy', optimizer='adam', class_mode='binary')
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 440, in compile
    train_loss)
  File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 262, in get_updates
    m_t = (self.beta_1 * m) + (1 - self.beta_1) * g
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 452, in <lambda>
    setattr(Variable, operator, lambda a, b: Variable._RunOp(operator, a, b))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 467, in _RunOp
    return getattr(ops.Tensor, operator)(a._AsTensor(), b)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 426, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 728, in mul
    return _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()
: OOM when allocating tensor with shape
	 [[Node: sub_2518 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](sub_2518/x, Variable_1955/read)]]
Traceback (most recent call last):
  File "/media/konet/01D15611945D72C0/Pycharm_ubuntu/deep_neural_network_binary/dnn_127_models_binary.py", line 398, in <module>
    fited = model.fit(Xtrain, ytrain, nb_epoch=n_epochs, batch_size=batch_size, show_accuracy=True, shuffle=True, validation_split=0.35)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 581, in fit
    shuffle=shuffle, metrics=metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 239, in _fit
    outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 336, in __call__
    updated = session.run(self.outputs + self.updates, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 3200 } dim { size: 2000 }
	 [[Node: mul_4305 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Variable_1954/read, Variable_1956/read)]]
	 [[Node: add_3103/_9711 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_423_add_3103", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'mul_4305', defined at:
  File "/media/konet/01D15611945D72C0/Pycharm_ubuntu/deep_neural_network_binary/dnn_127_models_binary.py", line 387, in <module>
    model.compile(loss='binary_crossentropy', optimizer='adam', class_mode='binary')
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 440, in compile
    train_loss)
  File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 262, in get_updates
    m_t = (self.beta_1 * m) + (1 - self.beta_1) * g
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 452, in <lambda>
    setattr(Variable, operator, lambda a, b: Variable._RunOp(operator, a, b))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 467, in _RunOp
    return getattr(ops.Tensor, operator)(a._AsTensor(), b)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 426, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 728, in mul
    return _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()
`

Any advice on how to solve this?

Thank you

**Comment by yaroslavvb** [comment]
It sounds like you are running out of memory

**Comment by vrv** [comment]
Yes, this sounds like an out-of-memory issue.  Try reducing your model size / number of concurrent active models.  Note that we will continue to try to improve our GPU memory utilization, so the situation may get better over time.

**Comment by omarcr** [comment]
Hi, there is no number of concurrent models. 
What I do is right after training/testing one model, I start training/testing other in a for loop.
There is a limited number of models I can try consecutively due to this error.

**Comment by mtamburrano** [comment]
I've the same issue.
I'm using Keras with Tensorflow as backend, if I do KFold cross validation I run out of memor. Same model and same number of KFolds runs with no issues on Theano backend.
It seems like the GPU memory utilization needs to be improved

**Comment by bhack** [comment]
@vrv It seems that calling multiple fit inside a loop has some comulative alloc without reosuing or freeing GPU memory resources.

**Comment by vrv** [comment]
I think we need a small representative example to reproduce the problem -- we shouldn't have any cumulative allocations since we reference count everything.

**Comment by bhack** [comment]
We have tested again with TF master but we got the same issue. 
@vrv Do you think that make sense to leak check with cuda tools?
If not we need to deep investigate how keras pilot tensorflow in the backend with this cycles.

**Comment by vrv** [comment]
Maybe worth trying cuda tools but:

1) We should dump out of memory information to LOG(INFO) when we OOM: https://github.com/tensorflow/tensorflow/blob/cc9bfbf8ef4a3dea6514ad939d238f7442188247/tensorflow/core/common_runtime/bfc_allocator.cc#L639

2) Try setting https://github.com/tensorflow/tensorflow/blob/16d395e5dea687ab3aece0a462e631de25c8d77d/tensorflow/core/framework/log_memory.cc#L25 to true and see if you get more information ?

I haven't looked at Keras code, perhaps it is using a single session and adding/initializing new variables to the session for each new model?  Variables are persisted through the lifetime of a session, so it would be wise to use a session for each "model".

**Comment by bhack** [comment]
@vrv Mhhh.. Quite sure that we are incurring in https://github.com/fchollet/keras/issues/2102

**Comment by yochananscharf** [comment]
Drastically reducing batch-size to 5-10 solved the problem in my case.

**Comment by Huarong** [comment]
Yes, reducing batch size works.

**Comment by BlankWind** [comment]
reducing batch-size from13 to 10 solved the problem in my case

**Comment by lishen** [comment]
Reducing batch size of course reduces the memory usage but that is not the key issue here. The key is why running multiple models consecutively caused GPU blow-up. 

I had a similar problem. When run model training using single GPU worked fine. But when I duplicated the model onto multiple GPUs (with same batch size per GPU) blew up. I was using Keras' new multi_gpu_model API call.

**Comment by omarcr** [comment]
I think the solution is to clean  the session after training a model

**Comment by VETURISRIRAM** [comment]
I came across the same problem. I shut down all the anaconda prompt windows and cleared all the python tasks. Reopened an Anaconda prompt window and executed the train.py file. It worked for me the next time. The Anaconda and Python terminals were taking up the memory which doesn't leave space for the training process. Hope this helps 👍

**Comment by spcp001** [comment]
Try clear_session() if you running the model consecutively.

`from keras import backend as K`
`K.clear_session()`
you can find more in the following link:
[https://forums.fast.ai/t/how-could-i-release-gpu-memory-of-keras/2023/8](url)
