### ISSUE TITLE
ResourceExhaustedError in CNN/MNIST example (with GPU)

### ISSUE THREAD

**Issue by ywatanabex** [tensorflow/tensorflow#136]
(I'm using GPU(GTX 980) with CUDA-7.0&cuDNNv2, on Ubuntu 14.04)
I have gone through MNIST tutorial: http://tensorflow.org/tutorials/mnist/pros/index.md

Everything was going well except for the last two lines:

```python
print "test accuracy %g"%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0})
```

Executing these lines, I got an error: 

```python
ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 18 } dim { size: 18 } dim { size: 32 }
```

I think basic reason for this error is that test data can not be allocated to GPU device.
Is this a bug or not? Are there good way to avoid this issue?

**Comment by avitale** [comment]
I am having the same issue on OS X Yosemite with Docker container.
In my case it should be using the CPU, I tried bumping Docker memory limit to 8GB but still getting OOM  .
Looking at Docker Stats, during the final accuracy.eval() memory goes from 300MB to 900MB then it crashes.

**Comment by vincentvanhoucke** [comment]
If you don't have enough memory on your GPU to fit the whole test data, you could feed it in small batches to the eval graph using feed_dict like the example does with the training data.

**Comment by avitale** [comment]
I solved my case. Being on OS X, I use Docker via the docker-machine VM.
Both Docker and docker-machine VM have a default memory limit of 1GB, increasing both memory limits I was able to get the results without OOM errors. 
@ywatanabex ,  if it may help you, using Docker stats I saw memory peak around 1.9GB

**Comment by EigenFace** [comment]
I have this same problem on this same example with Ubuntu 14.04 with Nvidia GTX 970. Hits 3.35 GB usage and then crashes.

**Comment by VedAustin** [comment]
Same problem when running from a Dockers terminal on a Windows machine. I ran the example convolutional.py as suggested in their tutorials and for six hours it was still running chugging out the gradually decreasing error rates before crashing out!
Anything unusual about it taking 6 hours or is it normal since I am using CPU and not the recommended GPU for DNNs?

**Comment by mtourne** [comment]
Submitted a PR to that effect : https://github.com/tensorflow/tensorflow/pull/157

Did just as @vincentvanhoucke suggested and transform the test set to use batches.

**Comment by gyoshi** [comment]
I had the same issue with Ubuntu 14.04LTS & GTX970, but now solved with the code by @mtourne (#157). Thanks!

**Comment by mondatu** [comment]
@mtourne Thanks a lot for the fix. It works for my GPU (previously I also had Resource Exhausted error).

Another way following @vrv 's advice from [this discussion] (https://github.com/soumith/convnet-benchmarks/issues/66) is to install tensorflow from the latest source and configure your session to use BFC allocator before running it like this:

config = tf.ConfigProto()
config.gpu_options.allocator_type = 'BFC'
with tf.Session(config = config) as s:

The original example from @vrv  is [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/alexnet/alexnet_benchmark.py#L201). My GPU has 6 GB though. This allocator seems to dynamically allocate memory according to GPU's memory so it will probably work with cards having less memory as well.

**Comment by vrv** [comment]
@mondatu: just to be clear, you're saying that just using BFC alone is enough to solve the mnist tutorial out-of-memory?  No need to do the batching in mnist?

(The default allocator and the BFC allocator do dynamic memory allocation but the default one is more prone to unrecoverable fragmentation -- BFC behaves better for more models).

**Comment by mondatu** [comment]
@vrv yes, I didn't use the batch version of @mtourne. I updated tensorflow source code, compiled and reinstalled. Then I modified the original file convolutional.py with the above code I mentioned, thanks to your advice. It worked with my card (Titan Z) with 6 GB (obviously it runs only on one single GPU inside that duo card).

I also run the original file convolutional.py (with no modification) with the updated tensorflow source code and I got the same old Resource Exhaustion error

**Comment by vrv** [comment]
Cool, glad to know it worked!  We made the BFC allocator the default yesterday, so if you sync to head you probably don't need your additional modifications.  This will make it into the next binary release.  Thanks again!

**Comment by mtourne** [comment]
Has anyone tried BFC allocator with "only" 4GB of gpu memory ?

**Comment by mondatu** [comment]
You're welcome. Yeah, I updated and now I can run the original file without modification.
Thanks a lot to you guys for developing and releasing this wonderful framework.

**Comment by ebrevdo** [comment]
Sounds like this has been resolved.  Let us know if this issue comes back.

**Comment by skimmmer** [comment]
I'm using the BFC allocator on a GTX 750 (1GB memory). I see a bunch of lines for the `bfc_allocator` creating bins (from chunk 1KB to 1GB), like "Creating bin of max chunk size 1.00GiB". The BFC allocator also says it's "Allocating 741.23MiB bytes", which should be in the range. Also I run `nvidia-smi` during the run to monitor the memory, and I see it stabilize at 871MiB before crashing.

It crashes with (during the first epoch):
```
Bin for 19.53MiB was 32.00MiB, Chunk State:
Ran out of memory trying to allocate 19.53MiB.  See logs for memory state
```
Any ideas? Anyone else run with around the same GPU memory? I can supply more trace info if needed, thanks!

**Comment by sthomp** [comment]
Incase anyone else is having this issue running on docker I solved it by creating a docker machine as follows: `docker-machine create --driver virtualbox --virtualbox-memory 4096 --virtualbox-cpu-count 4 default`

**Comment by almostimplemented** [comment]
@skimmer: see PR : #157 from @mtourne, I needed to apply that patch for the script to run properly on my machine. FWIW, my graphics card is the [NVIDIA GeForce GTX 780 Ti](http://www.nvidia.com/gtx-700-graphics-cards/gtx-780ti).

**Comment by rhinesj** [comment]
I as well am unable to run the samples referenced in the getting started document without pull request #157. Perhaps the document should make it more clear how much hardware TensorFlow expects a user to have in order to run examples.

**Comment by orodbhen** [comment]
Same issue with the latest stable release of Tensorflow, Quadro 970M with 2GB mem. 

According the logging output, BFC allocator was being used. 

    W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:211] Ran out of memory trying to allocate 29.91MiB.  See logs for memory state

29.9 MB doesn't seem like an awful lot, but I'm assuming it has to be allocated contiguously.

**Comment by lookfwd** [comment]
Me too, exactly the same as @orodbhen with 2GB GeForce GTX 960M

**Comment by orionr** [comment]
As an additional data point, I'm getting the same as @lookfwd and @orodbhen with a GeForce GTX 750 (1 GB). I'll see if the more manual batching from @mtourne fixes it.

**Comment by orian** [comment]
FYI: I had the same error (Ram 32GB, Titan X 12GB). **Restarting iPython notebook helped**.

**Comment by Morpheus3000** [comment]
I was trying the Deep MNIST from the tutorial on the site. Using the entire test set throws the ran out of memory trying to allocate 78.1KiB (So close!)
Changing the batches of the test images works, But pushing it to batches of 5000, just so I could see where exactly the program breaks, gave me a warning that it ran out of memory. The strange thing is that, while the previous attempt, without batching, completely broke the program, this didn't. I still got the result, but with a lot of warning that says:

> W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.92GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.

I am using a 2GB 960M and I can confirm that the BFC option is enabled, since there were related errors with chunks when it completely crashed the first time.

**Comment by BKJackson** [comment]
Would running this in a terminal console avoid memory problems compared to the Python notebook?

**Comment by yaroslavvb** [comment]
The problem is that one of the layers needs 2GB of RAM for the activations if you use batch size 10k. So running in terminal would not avoid memory problems.

See https://github.com/tensorflow/tensorflow/issues/6019#issuecomment-267881864 for memory analysis

**Comment by Shuto050505** [comment]
I'm using a 2GB 860M.
mnist.test.image.shape is (10000,784).
Restricting shape to 7000, I could do it.

batch size
`batch_tx, batch_ty = mnist.test.next_batch(7000)
print("test accuracy %g"%accuracy.eval(feed_dict={x:batch_tx, y_: batch_ty, keep_prob: 1.0}))`
-> test accuracy 0.992

or

slice
`test_image = mnist.test.images[0:7000, :]
test_label = mnist.test.labels[0:7000, :]
print("test accuracy %g"%accuracy.eval(feed_dict={x: test_image, y_: test_label, keep_prob: 1.0}))`
->test accuracy 0.992

**Comment by ChinChangYang** [comment]
I am doing similar things as @Shuto050505 did here, but I compute the mean of accuracy for each batch in all test data. Replace the following line:

```
print("test accuracy %g"%accuracy.eval(feed_dict={ 
      x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))
```

by this:

```
batch_size = 50
batch_num = int(mnist.test.num_examples / batch_size)
test_accuracy = 0
    
for i in range(batch_num):
    batch = mnist.test.next_batch(batch_size)
    test_accuracy += accuracy.eval(feed_dict={x: batch[0],
                                              y_: batch[1],
                                              keep_prob: 1.0})

test_accuracy /= batch_num
print("test accuracy %g"%test_accuracy)
````

I will get the mean of test accuracy `test accuracy 0.9915`.

**Comment by thisHemit** [comment]
Encountered the same problem with a 2GB GeForce GT 710(btw it worked well the first time) on Linux Mint KDE 18(Sarah). @ChinChangYang 's solution works flawlessly and finally saved me after two days of failing to fix this.

**Comment by Phantomb** [comment]
Encountered the same issue on my Windows 10, 2GB GTX1050. Using @ChinChangYang 's solution fixed it for me. (Make sure to place the other code at the right indentation, so it falls within the `with` block

**Comment by ssm9462** [comment]
Just restarting Pycharm resolved this problem for me as well

**Comment by sbmaruf** [comment]
I am new to tensorflow and Machine Learning. Recently I am working on a model. My model is like below,

Character level Embedding Vector -> Embedding lookup -> LSTM1

Word level Embedding Vector->Embedding lookup -> LSTM2

[LSTM1+LSTM2] -> single layer MLP-> softmax layer

[LSTM1+LSTM2] -> Single layer MLP-> WGAN discriminator

while I'm working on this model I got the following error. I thought My batch is too big. Thus I tried to reduce the batch size from 20 to 10 but it doesn't work.

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[24760,100] [[Node: chars/bidirectional_rnn/bw/bw/while/bw/lstm_cell/split = Split[T=DT_FLOAT, num_split=4, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients_2/Add_3/y, chars/bidirectional_rnn/bw/bw/while/bw/lstm_cell/BiasAdd)]] [[Node: bi-lstm/bidirectional_rnn/bw/bw/stack/_167 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_636_bi-lstm/bidirectional_rnn/bw/bw/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]

tensor with shape[24760,100] means 2476000*32/1024*1024 = 75.*** MB memory. I am running the code on a titan X(11 GB) gpu. What could go wrong. Why this type of error occured?

**Comment by artie88** [comment]
I was faced with the same "ResourceExhaustedError" issue, so I changed the code as follows. I have 2GB of GPU memory, but I failed to run this simple code. I don't know how much memory should my video card has. Anyway, I changed the code to do not use the GPU and fix the issue.

...
config = tf.ConfigProto(
	device_count = {'GPU':0}
)
sess = tf.Session(config=config)
...

**Comment by SubashMourougayane** [comment]
Just reduce the batch size while feeding the test data to GPU

**Comment by shaunstoltz** [comment]
"Just reduce the batch size while feeding the test data to GPU"
batch_size=1

Now what? 0.5, 0?

Have 2 1080ti's, and sill running out of memory.

**Comment by sndre** [comment]
@shaunstoltz, what displays `nvidia-smi` before and after `ResourceExhaustedError`?

**Comment by lvjiujin** [comment]
I met the same problem in GPU, but when i change it to the cpu, it works well. the gpu is too samll!

**Comment by VETURISRIRAM** [comment]
I came across the same problem. I shut down all the anaconda prompt windows and cleared all the python tasks. Reopened an Anaconda prompt window and executed the train.py file with GPU. It worked for me the next time. The Anaconda and Python terminals were taking up the memory which doesn't leave space for the training process. Hope this helps 👍

**Comment by ykp1992** [comment]
> I was trying the Deep MNIST from the tutorial on the site. Using the entire test set throws the ran out of memory trying to allocate 78.1KiB (So close!)
> Changing the batches of the test images works, But pushing it to batches of 5000, just so I could see where exactly the program breaks, gave me a warning that it ran out of memory. The strange thing is that, while the previous attempt, without batching, completely broke the program, this didn't. I still got the result, but with a lot of warning that says:
> 
> > W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.92GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
> 
> I am using a 2GB 960M and I can confirm that the BFC option is enabled, since there were related errors with chunks when it completely crashed the first time.

Do you know what happens when this message occurs now? I am confused and have no idea why we can get a result when we run out of memory.

**Comment by phoenix1992** [comment]
> I am new to tensorflow and Machine Learning. Recently I am working on a model. My model is like below,
> 
> 1. Character level Embedding Vector -> Embedding lookup -> LSTM1
> 2. Word level Embedding Vector->Embedding lookup -> LSTM2
> 3. [LSTM1+LSTM2] -> single layer MLP-> softmax layer
> 4. [LSTM1+LSTM2] -> Single layer MLP-> WGAN discriminator
> 
> while I'm working on this model I got the following error. I thought My batch is too big. Thus I tried to reduce the batch size from 20 to 10 but it doesn't work.
> 
> > ResourceExhaustedError (see above for traceback): OOM when allocating
> > tensor with shape[24760,100] 	 [[Node:
> > chars/bidirectional_rnn/bw/bw/while/bw/lstm_cell/split =
> > Split[T=DT_FLOAT, num_split=4,
> > _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients_2/Add_3/y,
> > chars/bidirectional_rnn/bw/bw/while/bw/lstm_cell/BiasAdd)]] 	 [[Node:
> > bi-lstm/bidirectional_rnn/bw/bw/stack/_167 =
> > _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0",
> > send_device="/job:localhost/replica:0/task:0/device:GPU:0",
> > send_device_incarnation=1,
> > tensor_name="edge_636_bi-lstm/bidirectional_rnn/bw/bw/stack",
> > tensor_type=DT_INT32,
> > _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
> 
> tensor with _**shape[24760,100]**_ means 2476000_32/1024_1024 = 75.*** MB memory. I am running the code on a titan X(11 GB) gpu. What could go wrong. Why this type of error occured?
> 
> Extra info: the size of the LSTM1 is 100. for bidirectional LSTM it becomes 200.
> The size of the LSTM2 is 300. For Bidirectional LSTM it becomes 600.
> 
> _**Note**_ : The error occurred after 32 epoch. My question is why after 32 epoch there is an error. Why not at the initial epoch.

Hello, have you solved it? I have also encountered the same problem as you.

**Comment by anonym24** [comment]
@vaibhavsood 6GB 1080GTX is not enough?

**Comment by WrathofBhuvan11** [comment]
Guys anybody knows how to flush nvidia gpu cache memory (tell how to both in windows and in ubuntu).... ! sometimes even that might work

**Comment by Anurag27031994** [comment]
> 
> 
> Guys anybody knows how to flush nvidia gpu cache memory (tell how to both in windows and in ubuntu).... ! sometimes even that might work

import gc;    gc.collect()

**Comment by omsalah0** [comment]
use small patches, this the solution for this issue.

**Comment by iseegr8tfuldeadppl** [comment]
For the people stuck with this in models other than mnist.

A good method to drastically lower these parameters is to add:
`subsample=(2, 2)` (careful it lowers the resolution of images/data) in all the Convolutional layers above that Flatten layer,
if subsample doesn't work then it is `stride=(2, 2)`.

**Comment by yuejie89** [comment]
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[128,3,8,128,8,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node GPU0/D_loss/G/G_synthesis/cond/cond_1/Upscale2D_2/Tile (defined at D:\jiateng\project\stylegan\stylegan\training\networks_stylegan.py:66) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

这个怎么解决啊
配置信息：
{   'ask_confirmation': False,
    'host_name': 'localhost',
    'num_gpus': 1,
    'print_info': False,
    'run_desc': 'sgan-pictrue-1gpu',
    'run_dir': 'results\\00000-sgan-pictrue-1gpu',
    'run_dir_extra_files': None,
    'run_dir_ignore': ['__pycache__', '*.pyproj', '*.sln', '*.suo', '.cache', '.idea', '.vs', '.vscode', 'results', 'datasets', 'cache'],
    'run_dir_root': 'results',
    'run_func_kwargs': {   'D_args': {'func_name': 'training.networks_stylegan.D_basic'},
                           'D_loss_args': {'func_name': 'training.loss.D_logistic_simplegp', 'r1_gamma': 10.0},
                           'D_opt_args': {'beta1': 0.0, 'beta2': 0.99, 'epsilon': 1e-08},
                           'G_args': {'func_name': 'training.networks_stylegan.G_style'},
                           'G_loss_args': {'func_name': 'training.loss.G_logistic_nonsaturating'},
                           'G_opt_args': {'beta1': 0.0, 'beta2': 0.99, 'epsilon': 1e-08},
                           'dataset_args': {'tfrecord_dir': 'pictrue'},
                           'grid_args': {'layout': 'random', 'size': '4k'},
                           'metric_arg_list': [{'func_name': 'metrics.frechet_inception_distance.FID', 'minibatch_per_gpu': 1, 'name': 'fid50k', 'num_images': 50000}],
                           'mirror_augment': True,
                           'sched_args': {   'D_lrate_dict': {128: 0.0015, 256: 0.002, 512: 0.003, 1024: 0.003},
                                             'G_lrate_dict': {128: 0.0015, 256: 0.002, 512: 0.003, 1024: 0.003},
                                             'lod_initial_resolution': 8,
                                             'minibatch_base': 4,
                                             'minibatch_dict': {4: 128, 8: 128, 16: 128, 32: 64, 64: 32, 128: 16, 256: 8, 512: 4}},
                           'tf_config': {'rnd.np_random_seed': 1000},
                           'total_kimg': 25000},
    'run_func_name': 'training.training_loop.training_loop',
    'run_id': 0,
    'run_name': '00000-sgan-pictrue-1gpu',
    'submit_target': <SubmitTarget.LOCAL: 1>,
    'task_name': 'Administrator-00000-sgan-pictrue-1gpu',
    'user_name': 'Administrator'}
