### ISSUE TITLE
Import Error on Windows 10: No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by BotLivesMatter** [tensorflow/tensorflow#13675]
**System information**
OS: Windows 10 64
Tensorflow version 1.3 GPU version
Python 3.5.4
CUDA 8.0 -> cudart64_80.dll
CUDNN 6.0 -> cudnn64_6.dll
GPU: GeForce GTX 1070

**Installation Process & Issue:**
I followed the guide provided on https://www.tensorflow.org/install/install_windows for the installation via Anaconda. The installation seems to be successful, but upon running the following command in the console:

>>> import tensorflow as tf

I am getting the following error:

#BEGIN ERROR MESSAGE

Traceback (most recent call last):
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 938, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 23, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 938, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 23, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

#END ERROR MESSAGE

**Attempted Fixes:**
Ensuring that cudart64_80.dll and cudnn64_6.dll locations are appended into %PATH%.
Appending .DLL to %PATHEXT%.
Ensuring that the following dependencies are available and their location in %PATH%. This list is sourced from user mrry's reply in https://github.com/tensorflow/tensorflow/issues/5949.
KERNEL32.dll
WSOCK32.dll
WS2_32.dll
SHLWAPI.dll
python35.dll
MSVCP140.dll
VCRUNTIME140.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll

Any help would be greatly appreciated!

**Comment by reedwm** [comment]
Try following the advice given in https://github.com/tensorflow/tensorflow/issues/9469 and https://stackoverflow.com/questions/43577923/cannot-import-tensorflow-for-gpu-on-windows-10 and https://github.com/tensorflow/tensorflow/issues/11571.

**Comment by BotLivesMatter** [comment]
Below are my results from reviewing/following the advice of the links:

https://stackoverflow.com/questions/43577923/cannot-import-tensorflow-for-gpu-on-windows-10
Recommended changing CUDNN filename from cudnn64_6.dll to cudnn64_5.dll. Same error occurs.

https://github.com/tensorflow/tensorflow/issues/9469 OP said the issue was caused by his visual studio and he disabled his intel graphics card. My MSVCP140.dll location is in %PATH% so I doubt it is the first cause. I also have intel integrated graphics, but I am not sure how this will impact my issue. It would seem to me that the issue is regarding dependency and I am not sure how disabling it on boot will resolve the issue. If anyone has knowledge otherwise please let me know!

https://github.com/tensorflow/tensorflow/issues/11571 OP resolved issue by adding location of Visual Studio directories into %PATH% and reinstalling tensorflow. All the dll files that I have listed above already have their location in %PATH%. Unless there is a dependency that is not provided on download and not listed above, then their locations are all in my %PATH%. Not too sure about the reinstalling part. Would that be necessary? I am not sure how logically it will resolve the issue.

I have also downloaded and ran mrry's debugger. It seems to be able to find all my DLLs. Output below: 

ERROR: Failed to import the TensorFlow module.

- Python version is 3.5.

- TensorFlow is installed at: C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow

- All required DLLs appear to be present. Please open an issue on the
  TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues

**Comment by msatyan** [comment]
Look like the TensorFlow has stated using cuDNN 6.x in the past couple of days (from 5.1).
(cuDNN=NVIDIA CUDA Deep Neural Network library )
https://www.tensorflow.org/install/install_windows#CommonInstallationProblems
The problem on my computer got solved after I upgrading cuDNN 6.x (TF will not work with cuDNN 7 yet)
https://developer.nvidia.com/cudnn

My configuration is
Windows 10 x64, with GPU GTX 1080 ti
Anaconda 5.0.0 (with Python 3.6)
CUDA Toolkit 8.0
cuDNN v6.0

**Comment by Saltu5** [comment]
I have somewhat the same issue
I also run win 10 64-bit
python 3.6.2
most recent tensorflow (so I assume 1.3?)
but in the cpu-only version

my Stacktrace:

`Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <mo
dule>
    from tensorflow.python import *
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49,
 in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>
`

**Comment by Saltzmann** [comment]
I have somewhat the same issue
I also run win 10 64-bit
python 3.6.2
most recent tensorflow (so I assume 1.3?)
but in the cpu-only version

I installed tensorflow using pip, not anaconda though

#My Console Output#

Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <mo
dule>
    from tensorflow.python import *
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49,
 in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
\>\>\>

**Comment by mrry** [comment]
@BotLivesMatter Can you please try running Dependency Walker on `C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd` and let us know if it detects any missing DLLs?

@Saltzmann Since you are running the CPU version, the most likely problem is a missing `MSVCP140.DLL`. You can install it from https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by BotLivesMatter** [comment]
Running Dependency Walker outputs the following list of files with the message "Error opening file. The system cannot find the file specified(2)."

API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
API-MS-WIN-CORE-APPCOMPAT-L1-1-1.DLL
API-MS-WIN-CORE-APPINIT-L1-1-0.DLL
API-MS-WIN-CORE-ATOMS-L1-1-0.DLL
API-MS-WIN-CORE-COMM-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L3-1-0.DLL
API-MS-WIN-CORE-CRT-L1-1-0.DLL
API-MS-WIN-CORE-CRT-L2-1-0.DLL
API-MS-WIN-CORE-DATETIME-L1-1-1.DLL
API-MS-WIN-CORE-DATETIME-L1-1-2.DLL
API-MS-WIN-CORE-DEBUG-L1-1-1.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL
API-MS-WIN-CORE-ENCLAVE-L1-1-0.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-1.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-3.DLL
API-MS-WIN-CORE-FIBERS-L1-1-1.DLL
API-MS-WIN-CORE-FIBERS-L2-1-1.DLL
API-MS-WIN-CORE-FILE-L1-2-1.DLL
API-MS-WIN-CORE-FILE-L1-2-2.DLL
API-MS-WIN-CORE-FILE-L2-1-1.DLL
API-MS-WIN-CORE-FILE-L2-1-2.DLL
API-MS-WIN-CORE-HANDLE-L1-1-0.DLL
API-MS-WIN-CORE-HEAP-L1-2-0.DLL
API-MS-WIN-CORE-HEAP-L2-1-0.DLL
API-MS-WIN-CORE-HEAP-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-2-0.DLL
API-MS-WIN-CORE-IO-L1-1-1.DLL
API-MS-WIN-CORE-JOB-L1-1-0.DLL
API-MS-WIN-CORE-JOB-L2-1-0.DLL
API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-1.DLL
API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-5.DLL
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-2.DLL
API-MS-WIN-CORE-LARGEINTEGER-L1-1-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-2.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-1.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-2.DLL
API-MS-WIN-CORE-LOCALIZATION-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-3-0.DLL
API-MS-WIN-CORE-LOCALIZATION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-2.DLL
API-MS-WIN-CORE-MEMORY-L1-1-5.DLL
API-MS-WIN-CORE-MISC-L1-1-0.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-0.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-2.DLL
API-MS-WIN-CORE-NAMESPACE-L1-1-0.DLL
API-MS-WIN-CORE-NORMALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-PATH-L1-1-0.DLL
API-MS-WIN-CORE-PERFCOUNTERS-L1-1-0.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-2-0.DLL
API-MS-WIN-CORE-PROCESSSNAPSHOT-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-2.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-3.DLL
API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-2-0.DLL
API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-ANSI-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-L1-1-0.DLL
API-MS-WIN-CORE-QUIRKS-L1-1-0.DLL
API-MS-WIN-CORE-REALTIME-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-1.DLL
API-MS-WIN-CORE-REGISTRYUSERSPECIFIC-L1-1-0.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-2-0.DLL
API-MS-WIN-CORE-SHLWAPI-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-SHLWAPI-OBSOLETE-L1-2-0.DLL
API-MS-WIN-CORE-SIDEBYSIDE-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L2-1-0.DLL
API-MS-WIN-CORE-STRING-L2-1-1.DLL
API-MS-WIN-CORE-STRING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-STRINGANSI-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-3.DLL
API-MS-WIN-CORE-SYSTEMTOPOLOGY-L1-1-0.DLL
API-MS-WIN-CORE-SYSTEMTOPOLOGY-L1-1-1.DLL
API-MS-WIN-CORE-THREADPOOL-L1-2-0.DLL
API-MS-WIN-CORE-THREADPOOL-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-TIMEZONE-L1-1-0.DLL
API-MS-WIN-CORE-URL-L1-1-0.DLL
API-MS-WIN-CORE-UTIL-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-L1-1-1.DLL
API-MS-WIN-CORE-VERSION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-VERSIONANSI-L1-1-0.DLL
API-MS-WIN-CORE-VERSIONANSI-L1-1-1.DLL
API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-0.DLL
API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-1.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-1.DLL
API-MS-WIN-CORE-WOW64-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-1.DLL
API-MS-WIN-CORE-XSTATE-L2-1-0.DLL
API-MS-WIN-CRT-CONVERT-L1-1-0.DLL
API-MS-WIN-CRT-ENVIRONMENT-L1-1-0.DLL
API-MS-WIN-CRT-FILESYSTEM-L1-1-0.DLL
API-MS-WIN-CRT-HEAP-L1-1-0.DLL
API-MS-WIN-CRT-LOCALE-L1-1-0.DLL
API-MS-WIN-CRT-MATH-L1-1-0.DLL
API-MS-WIN-CRT-MULTIBYTE-L1-1-0.DLL
API-MS-WIN-CRT-PRIVATE-L1-1-0.DLL
API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL
API-MS-WIN-CRT-STDIO-L1-1-0.DLL
API-MS-WIN-CRT-STRING-L1-1-0.DLL
API-MS-WIN-CRT-TIME-L1-1-0.DLL
API-MS-WIN-CRT-UTILITY-L1-1-0.DLL
API-MS-WIN-DEVICES-CONFIG-L1-1-1.DLL
API-MS-WIN-EVENTING-CLASSICPROVIDER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONSUMER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONTROLLER-L1-1-0.DLL
API-MS-WIN-EVENTING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
API-MS-WIN-GDI-INTERNAL-UAP-L1-1-0.DLL
API-MS-WIN-SECURITY-APPCONTAINER-L1-1-0.DLL
API-MS-WIN-SECURITY-AUDIT-L1-1-1.DLL
API-MS-WIN-SECURITY-BASE-L1-2-0.DLL
API-MS-WIN-SECURITY-BASE-PRIVATE-L1-1-1.DLL
API-MS-WIN-SECURITY-CAPABILITY-L1-1-0.DLL
API-MS-WIN-SERVICE-CORE-L1-1-1.DLL
API-MS-WIN-SERVICE-CORE-L1-1-2.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L1-1-0.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L2-1-0.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-0
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-3.DLL
API-MS-WIN-SERVICE-WINSVC-L1-2-0.DLL
API-MS-WIN-SHCORE-PATH-L1-1-0.DLL
API-MS-WIN-SHELL-SHELLCOM-L1-1-0.DLL
API-MS-WIN-SHELL-SHELLFOLDERS-L1-1-0.DLL
API-MS-WIN-STORAGE-EXPORTS-EXTERNAL-L1-1-0.DLL
API-MS-WIN-STORAGE-EXPORTS-INTERNAL-L1-1-0.DLL
CUBLAS64_80.DLL
CUDNN64_6.DLL
CUFFT64_80.DLL
CURAND64_80.DLL
CUSOLVER64_80.DLL
PYTHON35.DLL
API-MS-ONECOREUAP-SETTINGSYNC-STATUS-L1-1-0.DLL
API-MS-WIN-APPMODEL-IDENTITY-L1-2-0.DLL
API-MS-WIN-APPMODEL-RUNTIME-INTERNAL-L1-1-0.DLL
API-MS-WIN-APPMODEL-RUNTIME-INTERNAL-L1-1-4.DLL
API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-APPMODEL-RUNTIME-L1-1-1.DLL
API-MS-WIN-APPMODEL-RUNTIME-L1-1-2.DLL
API-MS-WIN-APPMODEL-STATE-L1-2-0.DLL
API-MS-WIN-APPMODEL-UNLOCK-L1-1-0.DLL
API-MS-WIN-BASE-UTIL-L1-1-0.DLL
API-MS-WIN-CORE-CALENDAR-L1-1-0.DLL
API-MS-WIN-CORE-COM-L1-1-0
API-MS-WIN-CORE-COM-L1-1-0.DLL
API-MS-WIN-CORE-COM-L1-1-1.DLL
API-MS-WIN-CORE-COM-L1-1-2.DLL
API-MS-WIN-CORE-COM-L2-1-1.DLL
API-MS-WIN-CORE-COM-MIDLPROXYSTUB-L1-1-0.DLL
API-MS-WIN-CORE-COM-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-COM-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-DATETIME-L1-1-0.DLL
API-MS-WIN-CORE-DEBUG-L1-1-0.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-0.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-0.DLL
API-MS-WIN-CORE-FILE-L1-1-0.DLL
API-MS-WIN-CORE-FILE-L1-2-0.DLL
API-MS-WIN-CORE-FILE-L2-1-0.DLL
API-MS-WIN-CORE-FIRMWARE-L1-1-0.DLL
API-MS-WIN-CORE-HEAP-L1-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-1-0.DLL
API-MS-WIN-CORE-IO-L1-1-0.DLL
API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-0.DLL
API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-2-0.DLL
API-MS-WIN-CORE-LOCALREGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-MARSHAL-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-1.DLL
API-MS-WIN-CORE-PROCESSTOPOLOGY-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-PSM-APP-L1-1-0.DLL
API-MS-WIN-CORE-PSM-APPNOTIFY-L1-1-0.DLL
API-MS-WIN-CORE-PSM-KEY-L1-1-0.DLL
API-MS-WIN-CORE-REALTIME-L1-1-2.DLL
API-MS-WIN-CORE-REGISTRY-L2-2-0.DLL
API-MS-WIN-CORE-REGISTRY-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-1-0.DLL
API-MS-WIN-CORE-SHLWAPI-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-1-0.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-0.DLL
API-MS-WIN-CORE-TOOLHELP-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERRORPRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-PROPERTYSETPRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-PROPERTYSETPRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-WINRT-REGISTRATION-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-1.DLL
API-MS-WIN-COREUI-SECRUNTIME-L1-1-0.DLL
API-MS-WIN-CRT-PROCESS-L1-1-0.DLL
API-MS-WIN-DEVICES-QUERY-L1-1-1.DLL
API-MS-WIN-DOWNLEVEL-ADVAPI32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-ADVAPI32-L2-1-0.DLL
API-MS-WIN-DOWNLEVEL-KERNEL32-L2-1-0.DLL
API-MS-WIN-DOWNLEVEL-NORMALIZ-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-OLE32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHELL32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHLWAPI-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHLWAPI-L2-1-0.DLL
API-MS-WIN-DOWNLEVEL-USER32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-VERSION-L1-1-0.DLL
API-MS-WIN-DWMAPI-L1-1-0.DLL
API-MS-WIN-DX-D3DKMT-L1-1-0.DLL
API-MS-WIN-DX-D3DKMT-L1-1-3.DLL
API-MS-WIN-EVENTING-LEGACY-L1-1-0.DLL
API-MS-WIN-EVENTING-TDH-L1-1-0.DLL
API-MS-WIN-EVENTLOG-LEGACY-L1-1-0.DLL
API-MS-WIN-GDI-DPIINFO-L1-1-0.DLL
API-MS-WIN-HTTP-TIME-L1-1-0.DLL
API-MS-WIN-MM-JOYSTICK-L1-1-0.DLL
API-MS-WIN-MM-MISC-L1-1-1.DLL
API-MS-WIN-MM-MISC-L2-1-0.DLL
API-MS-WIN-MM-MME-L1-1-0.DLL
API-MS-WIN-MM-TIME-L1-1-0.DLL
API-MS-WIN-NETWORKING-INTERFACECONTEXTS-L1-1-0.DLL
API-MS-WIN-NTUSER-RECTANGLE-L1-1-0.DLL
API-MS-WIN-NTUSER-SYSPARAMS-L1-1-0.DLL
API-MS-WIN-OLE32-IE-L1-1-0.DLL
API-MS-WIN-OOBE-NOTIFICATION-L1-1-0.DLL
API-MS-WIN-POWER-BASE-L1-1-0.DLL
API-MS-WIN-POWER-SETTING-L1-1-0.DLL
API-MS-WIN-RO-TYPERESOLUTION-L1-1-0.DLL
API-MS-WIN-RTCORE-NTUSER-CLIPBOARD-L1-1-0.DLL
API-MS-WIN-RTCORE-NTUSER-PRIVATE-L1-1-0.DLL
API-MS-WIN-RTCORE-NTUSER-PRIVATE-L1-1-5.DLL
API-MS-WIN-RTCORE-NTUSER-SHELL-L1-1-0.DLL
API-MS-WIN-RTCORE-NTUSER-SYNCH-L1-1-0.DLL
API-MS-WIN-RTCORE-NTUSER-WINDOW-L1-1-0.DLL
API-MS-WIN-RTCORE-NTUSER-WINEVENT-L1-1-0.DLL
API-MS-WIN-SECURITY-ACCESSHLPR-L1-1-0.DLL
API-MS-WIN-SECURITY-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
API-MS-WIN-SECURITY-ACTIVEDIRECTORYCLIENT-L1-1-1.DLL
API-MS-WIN-SECURITY-BASE-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L2-1-0.DLL
API-MS-WIN-SECURITY-CRYPTOAPI-L1-1-0.DLL
API-MS-WIN-SECURITY-GROUPPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-LSALOOKUP-ANSI-L2-1-0.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L1-1-1.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L1-1-2.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L2-1-1.DLL
API-MS-WIN-SECURITY-LSAPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-PROVIDER-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDL-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDLPARSECOND-L1-1-0.DLL
API-MS-WIN-SECURITY-SYSTEMFUNCTIONS-L1-1-0.DLL
API-MS-WIN-SERVICE-WINSVC-L1-1-0.DLL
API-MS-WIN-SHCORE-COMHELPERS-L1-1-0.DLL
API-MS-WIN-SHCORE-OBSOLETE-L1-1-0.DLL
API-MS-WIN-SHCORE-REGISTRY-L1-1-1.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
API-MS-WIN-SHCORE-STREAM-L1-1-0.DLL
API-MS-WIN-SHCORE-STREAM-WINRT-L1-1-0.DLL
API-MS-WIN-SHCORE-SYSINFO-L1-1-0.DLL
API-MS-WIN-SHCORE-THREAD-L1-1-0.DLL
API-MS-WIN-SHCORE-UNICODEANSI-L1-1-0.DLL
API-MS-WIN-SHELL-CHANGENOTIFY-L1-1-0.DLL
API-MS-WIN-SHELL-NAMESPACE-L1-1-0.DLL
API-MS-WIN-SHELL-SHDIRECTORY-L1-1-0.DLL
API-MS-WIN-SHLWAPI-IE-L1-1-0.DLL
API-MS-WIN-SHLWAPI-WINRT-STORAGE-L1-1-1.DLL
DEVICELOCKHELPERS.DLL
EMCLIENT.DLL
EXT-MS-MF-PAL-L2-1-0.DLL
EXT-MS-ONECORE-APPCHROMEAPI-L1-1-0.DLL
EXT-MS-ONECORE-APPDEFAULTS-L1-1-0.DLL
EXT-MS-ONECORE-APPMODEL-EMCLIENT-L1-1-0.DLL
EXT-MS-ONECORE-APPMODEL-STATEREPOSITORY-INTERNAL-L1-1-1.DLL
EXT-MS-ONECORE-DCOMP-L1-1-0.DLL
EXT-MS-ONECORE-HLINK-L1-1-0.DLL
EXT-MS-ONECORE-ORIENTATION-L1-1-0.DLL
EXT-MS-ONECORE-PHONEINFO-L1-1-0.DLL
EXT-MS-ONECORE-SHELLCHROMEAPI-L1-1-2.DLL
EXT-MS-WIN-ADVAPI32-MSI-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NPUSERNAME-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NTMARTA-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-PSM-APP-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-SAFER-L1-1-0.DLL
EXT-MS-WIN-APPCOMPAT-AEPIC-L1-1-0.DLL
EXT-MS-WIN-APPCOMPAT-APPHELP-L1-1-0.DLL
EXT-MS-WIN-APPMODEL-DAXCORE-L1-1-1.DLL
EXT-MS-WIN-APPMODEL-DEPLOYMENT-L1-1-1.DLL
EXT-MS-WIN-APPMODEL-RESTRICTEDAPPCONTAINER-INTERNAL-L1-1-0.DLL
EXT-MS-WIN-APPMODEL-STATE-EXT-L1-2-0.DLL
EXT-MS-WIN-APPMODEL-USERCONTEXT-L1-1-0.DLL
EXT-MS-WIN-APPMODEL-VIEWSCALEFACTOR-L1-1-0.DLL
EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOY-L1-1-0.DLL
EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOYONECORE-L1-1-0.DLL
EXT-MS-WIN-AUDIOCORE-PAL-L1-2-0.DLL
EXT-MS-WIN-AUTHZ-CONTEXT-L1-1-0.DLL
EXT-MS-WIN-AUTHZ-REMOTE-L1-1-0.DLL
EXT-MS-WIN-COM-CLBCATQ-L1-1-0.DLL
EXT-MS-WIN-COM-COML2-L1-1-1.DLL
EXT-MS-WIN-COM-OLE32-L1-1-1.DLL
EXT-MS-WIN-COM-OLE32-L1-1-5.DLL
EXT-MS-WIN-COM-PSMREGISTER-L1-2-2.DLL
EXT-MS-WIN-COM-SUSPENDRESILIENCY-L1-1-0.DLL
EXT-MS-WIN-CORE-IURI-L1-1-0.DLL
EXT-MS-WIN-CORE-WINRT-REMOTE-L1-1-0.DLL
EXT-MS-WIN-DESKTOPAPPX-L1-1-1.DLL
EXT-MS-WIN-DEVMGMT-DM-L1-1-1.DLL
EXT-MS-WIN-DEVMGMT-POLICY-L1-1-1.DLL
EXT-MS-WIN-DIRECT2D-DESKTOP-L1-1-0.DLL
EXT-MS-WIN-DOMAINJOIN-NETJOIN-L1-1-0.DLL
EXT-MS-WIN-DWMAPI-EXT-L1-1-0.DLL
EXT-MS-WIN-DWMAPIDXGI-EXT-L1-1-0.DLL
EXT-MS-WIN-EDPUTIL-POLICY-L1-1-1.DLL
EXT-MS-WIN-ELS-ELSCORE-L1-1-0.DLL
EXT-MS-WIN-EVENTING-RUNDOWN-L1-1-0.DLL
EXT-MS-WIN-FAMILYSAFETY-CHILDACCOUNT-L1-1-0.DLL
EXT-MS-WIN-FECLIENT-ENCRYPTEDFILE-L1-1-0.DLL
EXT-MS-WIN-FECLIENT-ENCRYPTEDFILE-L1-1-1.DLL
EXT-MS-WIN-FIREWALLAPI-WEBPROXY-L1-1-0.DLL
EXT-MS-WIN-GDI-CLIPPING-L1-1-0.DLL
EXT-MS-WIN-GDI-DC-CREATE-L1-1-1.DLL
EXT-MS-WIN-GDI-DC-L1-2-0.DLL
EXT-MS-WIN-GDI-DC-L1-2-1.DLL
EXT-MS-WIN-GDI-DEVCAPS-L1-1-0.DLL
EXT-MS-WIN-GDI-DRAW-L1-1-1.DLL
EXT-MS-WIN-GDI-DRAW-L1-1-3.DLL
EXT-MS-WIN-GDI-FONT-L1-1-1.DLL
EXT-MS-WIN-GDI-FONT-L1-1-3.DLL
EXT-MS-WIN-GDI-GDIPLUS-L1-1-0.DLL
EXT-MS-WIN-GDI-INTERNAL-DESKTOP-L1-1-1.DLL
EXT-MS-WIN-GDI-METAFILE-L1-1-1.DLL
EXT-MS-WIN-GDI-METAFILE-L1-1-2.DLL
EXT-MS-WIN-GDI-PATH-L1-1-0.DLL
EXT-MS-WIN-GDI-PRINT-L1-1-0.DLL
EXT-MS-WIN-GDI-PRIVATE-L1-1-0.DLL
EXT-MS-WIN-GDI-RENDER-L1-1-0.DLL
EXT-MS-WIN-GDI-WCS-L1-1-0.DLL
EXT-MS-WIN-GPAPI-GROUPPOLICY-L1-1-0.DLL
EXT-MS-WIN-GUI-DUI70-L1-1-0.DLL
EXT-MS-WIN-IMM-L1-1-1.DLL
EXT-MS-WIN-KERNEL32-APPCOMPAT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-DATETIME-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-ERRORHANDLING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-FILE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-LOCALIZATION-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-PACKAGE-CURRENT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-PACKAGE-L1-1-1.DLL
EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-1.DLL
EXT-MS-WIN-KERNEL32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-SIDEBYSIDE-L1-1-0.DLL
EXT-MS-WIN-KERNELBASE-PROCESSTHREAD-L1-1-0.DLL
EXT-MS-WIN-MININPUT-INPUTHOST-L1-1-0.DLL
EXT-MS-WIN-MPR-MULTIPLEPROVIDERROUTER-L1-1-0.DLL
EXT-MS-WIN-MRMCORER-ENVIRONMENT-L1-1-0.DLL
EXT-MS-WIN-MRMCORER-RESMANAGER-L1-1-0.DLL
EXT-MS-WIN-NETWORKING-WLANSTORAGE-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-1.DLL
EXT-MS-WIN-NTUSER-DC-ACCESS-EXT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-DIALOGBOX-L1-1-1.DLL
EXT-MS-WIN-NTUSER-DRAW-L1-1-1.DLL
EXT-MS-WIN-NTUSER-DRAW-L1-1-2.DLL
EXT-MS-WIN-NTUSER-GUI-L1-3-1.DLL
EXT-MS-WIN-NTUSER-KEYBOARD-L1-3-0.DLL
EXT-MS-WIN-NTUSER-MENU-L1-1-3.DLL
EXT-MS-WIN-NTUSER-MESSAGE-L1-1-1.DLL
EXT-MS-WIN-NTUSER-MESSAGE-L1-1-3.DLL
EXT-MS-WIN-NTUSER-MISC-L1-5-1.DLL
EXT-MS-WIN-NTUSER-MIT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-MOUSE-L1-1-0.DLL
EXT-MS-WIN-NTUSER-PRIVATE-L1-3-2.DLL
EXT-MS-WIN-NTUSER-RECTANGLE-EXT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-ROTATIONMANAGER-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SERVER-L1-1-0.DLL
EXT-MS-WIN-NTUSER-STRING-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SYNCH-L1-1-0.DLL
EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOW-L1-1-1.DLL
EXT-MS-WIN-NTUSER-WINDOW-L1-1-4.DLL
EXT-MS-WIN-NTUSER-WINDOWCLASS-L1-1-1.DLL
EXT-MS-WIN-NTUSER-WINDOWSTATION-L1-1-1.DLL
EXT-MS-WIN-ODBC-ODBC32-L1-1-0.DLL
EXT-MS-WIN-OLE32-BINDCTX-L1-1-0.DLL
EXT-MS-WIN-OLE32-IE-EXT-L1-1-0.DLL
EXT-MS-WIN-OLE32-OLEAUTOMATION-L1-1-0.DLL
EXT-MS-WIN-OLEACC-L1-1-2.DLL
EXT-MS-WIN-PRINTER-PRNTVPT-L1-1-1.DLL
EXT-MS-WIN-PROFILE-EXTENDER-L1-1-0.DLL
EXT-MS-WIN-PROFILE-LOAD-L1-1-0.DLL
EXT-MS-WIN-PROFILE-USERENV-L1-1-0.DLL
EXT-MS-WIN-PROFILE-USERENV-L1-1-1.DLL
EXT-MS-WIN-RAS-RASAPI32-L1-1-0.DLL
EXT-MS-WIN-RAS-TAPI32-L1-1-1.DLL
EXT-MS-WIN-RDR-DAVHLPR-L1-1-0.DLL
EXT-MS-WIN-RESOURCES-DEPLOYMENT-L1-1-0.DLL
EXT-MS-WIN-RO-TYPERESOLUTION-L1-1-0.DLL
EXT-MS-WIN-RPC-SSL-L1-1-0.DLL
EXT-MS-WIN-RTCORE-GDI-DEVCAPS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-GDI-OBJECT-L1-1-0.DLL
EXT-MS-WIN-RTCORE-GDI-RGN-L1-1-0.DLL
EXT-MS-WIN-RTCORE-GDI-RGN-L1-1-1.DLL
EXT-MS-WIN-RTCORE-MINUSER-INPUT-L1-1-2.DLL
EXT-MS-WIN-RTCORE-MINUSER-PRIVATE-EXT-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-CURSOR-L1-1-1.DLL
EXT-MS-WIN-RTCORE-NTUSER-DC-ACCESS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-DPI-L1-2-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-IAM-L1-1-1.DLL
EXT-MS-WIN-RTCORE-NTUSER-INTEGRATION-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYNCH-EXT-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYSCOLORS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYSPARAMS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-WINDOW-EXT-L1-1-0.DLL
EXT-MS-WIN-SECUR32-TRANSLATENAME-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CAPAUTHZ-L1-1-1.DLL
EXT-MS-WIN-SECURITY-CHAMBERS-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CHAMBERS-L1-1-1.DLL
EXT-MS-WIN-SECURITY-CREDUI-INTERNAL-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CREDUI-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CRYPTUI-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CRYPTUI-L1-1-1.DLL
EXT-MS-WIN-SECURITY-EFS-L1-1-1.DLL
EXT-MS-WIN-SECURITY-EFSWRT-L1-1-1.DLL
EXT-MS-WIN-SECURITY-WINSCARD-L1-1-0.DLL
EXT-MS-WIN-SESSION-USERMGR-L1-1-0.DLL
EXT-MS-WIN-SESSION-USERMGR-L1-2-0.DLL
EXT-MS-WIN-SESSION-USERTOKEN-L1-1-0.DLL
EXT-MS-WIN-SESSION-WINSTA-L1-1-0.DLL
EXT-MS-WIN-SESSION-WTSAPI32-L1-1-0.DLL
EXT-MS-WIN-SETUPAPI-INF-L1-1-0.DLL
EXT-MS-WIN-SETUPAPI-INF-L1-1-1.DLL
EXT-MS-WIN-SHELL-DIRECTORY-L1-1-0.DLL
EXT-MS-WIN-SHELL-EMBEDDEDMODE-L1-1-0.DLL
EXT-MS-WIN-SHELL-SHELL32-L1-2-0.DLL
EXT-MS-WIN-SHELL-SHLWAPI-L1-2-0.DLL
EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL
EXT-MS-WIN-SHELL32-SHELLFOLDERS-L1-2-0.DLL
EXT-MS-WIN-SMBSHARE-BROWSERCLIENT-L1-1-0.DLL
EXT-MS-WIN-STORAGE-SENSE-L1-2-0.DLL
EXT-MS-WIN-SXS-OLEAUTOMATION-L1-1-0.DLL
EXT-MS-WIN-TSF-MSCTF-L1-1-2.DLL
EXT-MS-WIN-UI-VIEWMANAGEMENT-L1-1-0.DLL
EXT-MS-WIN-USP10-L1-1-0.DLL
EXT-MS-WIN-WER-UI-L1-1-0.DLL
EXT-MS-WIN-WER-XBOX-L1-1-0.DLL
EXT-MS-WIN-WINRT-STORAGE-L1-1-0.DLL
EXT-MS-WIN-WLAN-ONEXUI-L1-1-0.DLL
EXT-MS-WIN-WLAN-SCARD-L1-1-0.DLL
IESHIMS.DLL

Strangely enough, some files I know for sure I have such as PYTHON35.DLL, CUDNN64_6.DLL and their locations are in %PATH% that I defined in the tensorflow environment that I activated using the conda console. Perhaps it is using the default %PATH% when running? I know the default value will not have the location of those files.

That being said, some of these files I do not see when querying them such as API-MS-WIN-CORE-ATOMS-L1-1-0.DLL. Are these files required? If so is there a package to cover these?

**Comment by mrry** [comment]
The `API-MS-WIN-*.DLL` messages are false negatives. (This is apparently a [known issue](https://stackoverflow.com/q/36240215/3574081) in Dependency Walker, but unfortunately it's the best tool we have!) I believe the same is true for the `EXT-MS-WIN-*.DLL` ones as well. 

Are you running Dependency Walker from a command prompt in the same Conda environment in which you installed TensorFlow?

**Comment by BotLivesMatter** [comment]
In my first comment I ran it when it was just in the C drive not via cmd prompt. Literally just via file explorer.

I have tried running it again but this time I placed the exe file into the tensorflow environment and ran it via cmd(Please let me know if I am running it wrong):
Tensorflow is located at(this displays when launching the python console): C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow
I moved depends.exe into C:\Users\Eric\AppData\Local\conda\conda\envs\tensorflow\

I am getting the following errors(unfortunately they do not seem to specify where they are all occurring):
Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.
Error: A circular dependency was detected.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

Files with the error "Error opening file. The system cannot find file specified(2)". I removed all files from this list that started with API-MS or EXT-MS, let me know if you want me to post the whole thing:
CUBLAS64_80.DLL
CUFFT64_80.DLL
CURAND64_80.DLL
CUSOLVER64_80.DLL
DEVICELOCKHELPERS.DLL
EMCLIENT.DLL
IESHIMS.DLL

I guess the good news is that it is finding CUDNN and Python now. So the results seems to be much more accurate. I ran a query and none of the files above are installed except for IESHIMS.DLL, but that one's location is not in %PATH%.

Please advise on how to proceed.

**Comment by mrry** [comment]
The following DLLs are typically part of a CUDA Toolkit installation:

* `CUBLAS64_80.DLL`
* `CUFFT64_80.DLL`
* `CURAND64_80.DLL`
* `CUSOLVER64_80.DLL`

Perhaps you need to reinstall CUDA 8.0 to get these DLLs? (I believe the other three are false negatives.)

**Comment by BotLivesMatter** [comment]
Good news! After reinstalling CUDA 8, I am no longer getting the error. It seems that I was missing some of the files. Thank you for your help.

I do notice that I am getting the following messages, should I be concerned about them? They do not seem critical:
2017-10-13 18:23:28.501415: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-13 18:23:28.502420: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.

**Comment by mrry** [comment]
Great! It's safe to ignore those warnings.

**Comment by Saltzmann** [comment]
@mrry thanks downloading the file worked for me as well.

**Comment by renatocesargarcia** [comment]
The TensorFlow GPU worked after uninstalling Tensowflow CPU
![image](https://user-images.githubusercontent.com/22581263/34695875-a83ed278-f4b3-11e7-9f7d-fb784126a6a8.png)
