### ISSUE TITLE
Tensorflow not detecting GPU even when CUDA is installed

### ISSUE THREAD

**Issue by chans1239** [tensorflow/tensorflow#13793]
Hi there,
I am running the following on Ubuntu 16.04 LTS and I have GPU 1070 and tensorflow version 1.0.1 (installed and checked through conda -list

I am trying to run a simple piece of code in tf
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)

with tf.Session() as sess:
    print (sess.run(c))

And I am getting the following error:
InvalidArgumentError (see above for traceback): Cannot assign a device to node 'MatMul_1': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0

Regarding the CUDA installed, I have the following information obtained by running nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

Theano is able to detect and use GPU
Using gpu device 0: GeForce GTX 1070 (CNMeM is disabled, cuDNN 5110)

How to get TF to use the GPU. Or what CUDA version should I install to make it work with GPU.
I understand this is not the platform to ask questions related to CUDA but if someone can point me in the right direction then it will be helpful.

Thank You.

**Comment by drpngx** [comment]
Please paste the logs, and please, please, fill out as much as you can from the template.

**Comment by phansel** [comment]
@chans1239 
What does nvidia-smi return? Did you install tensorflow-gpu? Do you have cuDNN installed, and is it the CUDA 8.0 version?

**Comment by chans1239** [comment]
nvidia-smi returned the following:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.82                 Driver Version: 375.82                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0      On |                  N/A |
| N/A   38C    P8     8W /  N/A |    282MiB /  8111MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1034    G   /usr/lib/xorg/Xorg                             171MiB |
|    0      1764    G   compiz                                          40MiB |
|    0      2679    G   ...el-token=77106A4CB88D22FD5BF26E235E3576CE    68MiB |
+-----------------------------------------------------------------------------+

It turns out it had tensorflow - CPU version only. Installing tensorflow-gpu and correcting few errors solved the problem. This issue can be closed.

Thank you for the help.

**Comment by danijames** [comment]
@chans1239 Can you please tell what all errors you solved and which version of tensorflow you installed?

**Comment by chans1239** [comment]
I installed the tensorflow-gpu version and the solved the issue!
