### ISSUE TITLE
tensorflow/tensorflow:1.4.0-devel-gpu uses libcuda.so stub at runtime

### ISSUE THREAD

**Issue by flx42** [tensorflow/tensorflow#14224]
```
$ nvidia-docker run -ti tensorflow/tensorflow:1.4.0-devel-gpu /bin/bash
root@2ad65cce2269:~# ldd /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
[...]
        libcuda.so.1 => /usr/local/cuda/lib64/stubs/libcuda.so.1 (0x00007f9de7215000)
```
As a result, you can't use CUDA in this image:
```
2017-11-03 17:57:11.181620: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUresult(-1)
2017-11-03 17:57:11.181660: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 939b58c94187
2017-11-03 17:57:11.181677: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 939b58c94187
2017-11-03 17:57:11.181848: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
```

Issue was caused by: https://github.com/tensorflow/tensorflow/pull/13399
Please backport https://github.com/tensorflow/tensorflow/pull/13456 into `r1.4`

**Comment by flx42** [comment]
@gunan

**Comment by gunan** [comment]
@case540 can we patch #13456 into the release branch and rebuild our docker images?

**Comment by case540** [comment]
Ok, will get started on this. #14225

**Comment by flx42** [comment]
@gunan this seems to be fixed, right?

**Comment by case540** [comment]
Patch was cherry-picked to 1.4. In process of rebuilding/uploading docker images for 1.4

**Comment by case540** [comment]
New dockers built and uploaded. Unsure how to verify issue is fixed.

**Comment by gunan** [comment]
```
gunan@dragonite:~$ nvidia-docker run -ti tensorflow/tensorflow:1.4.0-devel-gpu /bin/bash
1.4.0-devel-gpu: Pulling from tensorflow/tensorflow
...
Status: Downloaded newer image for tensorflow/tensorflow:1.4.0-devel-gpu
root@d39ef3933d75:~# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.test.iss_gpu_available()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'iss_gpu_available'
>>> tf.test.is_gpu_available()
.....
True
>>> 
```
Looks like GPU is now accessible on 1.4 devel docker images.
