### ISSUE TITLE
Can Tensorflow 1.4 use CUDA 9?

### ISSUE THREAD

**Issue by bardenthenry** [tensorflow/tensorflow#14244]
I upgraded to tensorflow 1.4. I found that this version can not load "cudart64_90.dll" when i import tensorflow in python.

It can work when i use  tensorflow 1.4 rc-0. But now it goes error:   Could not find 'cudart64_80.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 8.0 from this URL: https://developer.nvidia.com/cuda-toolkit.

**Comment by dc297** [comment]
No, Tensorflow 1.4 doesn't support cuda 9.0. You may check the release docs here https://github.com/tensorflow/tensorflow/releases. They plan to release tensoflow 1.5 with cuda 9.0 and cuDNN 7.

**Comment by DollarAkshay** [comment]
Yeah, just got this error

`mportError: Could not find 'cudart64_80.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 8.0 from this URL: https://developer.nvidia.com/cuda-toolkit`

**Comment by asimshankar** [comment]
Correct, the release builds of TensorFlow use CUDA 8 right now.
The next release will support CUDA 9.

**Comment by danqing** [comment]
We've added CUDA 9 wheels here: https://github.com/mind/wheels/releases/tag/tf1.4-gpu-cuda9

**Comment by mroodschild** [comment]
if you install it from anaconda:

pip install --ignore-installed --upgrade \ https://github.com/mind/wheels/releases/download/tf1.4-gpu-cuda9/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl

danqing, Thanks a lot!!

**Comment by wangsen1312** [comment]
danqing, Great work！

**Comment by Fulvioo** [comment]
@Danquing . Any plans for developing  the same  patch for windows 10? Thanks

**Comment by danqing** [comment]
@Fulvioo unfortunately not :( we don't have any windows machines.

**Comment by rceballos98** [comment]
I'm working on Ubuntu 17.10, with cuda-9.0 and cuDNN 7.0 for cuda 9. I followed the instruction above but get the following error when trying to import:
```
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rodrigo/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/rodrigo/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/rodrigo/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/rodrigo/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rodrigo/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rodrigo/miniconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory
```
Running
```
pip install --ignore-installed --upgrade \ https://github.com/mind/wheels/releases/download/tf1.4-gpu-cuda9/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl
```
Succesfully installed TF:
```
Successfully installed backports.weakref-1.0.post1 bleach-1.5.0 enum34-1.1.6 funcsigs-1.0.2 futures-3.1.1 html5lib-0.9999999 markdown-2.6.9 mock-2.0.0 numpy-1.13.3 pbr-3.1.1 protobuf-3.4.0 setuptools-36.7.2 six-1.11.0 tensorflow-1.4.0 tensorflow-tensorboard-0.4.0rc2 werkzeug-0.12.2 wheel-0.30.0
```

**Comment by danqing** [comment]
You want to follow the **NOTE** section in my url above: https://github.com/mind/wheels/releases/tag/tf1.4-gpu-cuda9

**Comment by quarkleptonboson** [comment]
Thanks for the cuda wheels!

Btw I have Ubuntu 16.04 with anaconda and python 3.6, cuda 9, cudnn 7 and a GPU with compute capability 5.0. I also finished installing the additional MKL-dnn library. However I tried to install the cp36-cp36mu wheel yet it says my platform does not support that wheel. What might be lacking in my system? Thanks in advance!

**Comment by danqing** [comment]
How are you installing it? Can you paste the command you run? Also to make sure, do you have a reasonably new Intel CPU (past 3 years)?

Please feel free to open an issue in our repo and I can further assist you. Replying to this thread will email 10 people and don't want to create too much spam.

**Comment by colmantse** [comment]
so i take for window 10, tf 1.4 cuda 9 cudnn 7 is not an option yet?

**Comment by vickylance** [comment]
@colmantse yes you have to build it from source

**Comment by colmantse** [comment]
thanks

**Comment by DominikLorenz** [comment]
@quarkleptonboson you need to write cp36-cp36m instead of cp36-cp36mu . I just had the same problem ;)

**Comment by quarkleptonboson** [comment]
It worked! Thanks!

**Comment by rcmf123** [comment]
Can someone help me? I pretty new to this.
I already installed cuda9.0 and cudnn7.0 then found out that cuda 9 isn't supported by tensorflow 1.4 then I came across to this thread.
I've downloaded the whl and installed it using:
`pip3 install tensorflow-1.4.0-cp35-cp35m-linux_x86_64.whl`
it says that it was successful but when I try to import tensorflow I get the following error:
`ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`

I can't just download the cuda 8 since it will take me 1/4 of my day because of slow internet connection :|

**Comment by danqing** [comment]
I would assume that you installed the wheel I provided above.

If so, follow the debug guide in our readme (https://github.com/mind/wheels#cuda) and make sure cuda 9 is in your path. It looks like your cuda 9 isn't correctly installed.

If you need further assistance, open an issue in our repo and I can help you there. 10+ people are subscribed to this thread and let's not do multiple back-and-forth's to spam them.

**Comment by IanMin1022** [comment]
it works fine on the terminal but if I import tensorflow on Pycharm, it doesn't work with ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory.
Can I get any advice?

**Comment by IanMin1022** [comment]
After I added this at Environmental variables, it worked.
Name: LD_LIBRARY_PATH
Value: /usr/local/cuda-9.0/lib64:${LD_LIBRARY_PATH}:/usr/local/lib
Thanks a lot @danqing by the way.

**Comment by helloiamsourav** [comment]
hey how do I install tensorflow for Cuda 9 in Windows? Awesome work for Linux...

**Comment by wangsen1312** [comment]
@helloiamsourav  maybe you should build it from source~

**Comment by PaulWang1905** [comment]
If you build form source , it does supprot CUDA 6
I have built tensorflow binary wheels both for python2.x and python3.x , check out my repo or my blog
`https://repo.puyuwang.me/pub/`

**Comment by alexattia** [comment]
Hello,  
I have installed tensorflow with `pip install --ignore-installed --upgrade \ https://github.com/mind/wheels/releases/download/tf1.4-gpu-cuda9/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl` and MKL.   
However, I have this error when I import tensorflow
`[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.4.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "external/protobuf_archive/src/google/protobuf/any.pb.cc".)`.
It seems that Protocol Buffer is not updated although it was installed during the tensorflow installation : `Successfully installed (...) protobuf-3.5.0.post1  (...)`.
Thank you in advance

**Comment by PaulWang1905** [comment]
@alexattia 
the C++ version of google protobuff is 2.6.1 with this command:

`sudo apt-get install libprotobuf-dev`

**Comment by kirk86** [comment]
Hi everyone I'm just having the same issue as @rcmf123. My cuda-9.1 installation is located in `/usr/local/cuda-9.1` next to `/usr/local/cuda-8.0` and I have updated the path accordingly in my `bashrc` but I still keep getting the same error when trying to import tensorflow.

**Comment by PaulWang1905** [comment]
@kirk86 
Hi,I dont know if renaming the file could resovle the issue.However I am going build a tensorflow binary working with cuda 9.1 to reslove this. (my repo is [repo.puyuwang.me](url))
If you have CUDA 8.0 installed , you could just use the CUDA 8.0. Google`s official build only support CUDA 8.0 now.(1.4 version)

**Comment by kirk86** [comment]
@PaulWang1905 hi, I presume you have already builded `tensorflow-1.4.1-cp36-cp36m-linux_x86_64.whl`? Is this one with support for cuda 9.1?

**Comment by PaulWang1905** [comment]
@kirk86  I am still working on the bugs. The one you mentioned is for CUDA 9.0 . 
Sorry. Give me one more day.

**Comment by helloiamsourav** [comment]
I could not build with cuda-9

**Comment by PaulWang1905** [comment]
@helloiamsourav @kirk86 
Hi. Good news. I have built the tensorflow working with CUDA9.1
just go to my repo: https://repo.puyuwang.me/ to download it. 
Make sure you download the right version  (I built for both python2.x and 3.6 environments)
And if you want to build the binary on your own , you probably would encounter some errors with CUDA9.1.(most likely a header files error) It could be resovle by a quick hack:simply link the header files to the cuda/include directory.

**Comment by kirk86** [comment]
@PaulWang1905 that's awesome ;). Good job 👍

**Comment by conduit242** [comment]
@PaulWang1905 Thank you for doing this! Unfortunately, I am getting:
`tensorflow-1.4.1-cp27-cp27mu-linux_x86_64_cuda9.1.whl is not a supported wheel on this platform.
`
Any ideas?

**Comment by alexattia** [comment]
@conduit242 Are you using python 2.7 ? If you are using python 3.6 (check with `pip --version`) you need  `tensorflow-1.4.1-cp36-cp36m-linux_x86_64.whl`

**Comment by conduit242** [comment]
I am using Python 2.7, I was trying to use the Cuda 9.1 wheel that was mentioned above.

**Comment by PaulWang1905** [comment]
@conduit242  What is your CPU type?

**Comment by conduit242** [comment]
It's an AMD Ryzen 1600, so x86_64

**Comment by PaulWang1905** [comment]
@ conduit242 
I am done. This time it should work on both AMD and intel CPU. Do not forget to check the sha256sum.:-)

**Comment by conduit242** [comment]
@PaulWang1905 Thanks Paul, unfortunately I am still getting:
`tensorflow-1.4.1-cp27-cp27mu-linux-generic-x86_64-cuda9.1.whl is not a supported wheel on this platform.`

**Comment by PaulWang1905** [comment]
@conduit242 see if their build works ?  https://github.com/mind/wheels/releases/download/tf1.4.1-gpu-cuda91-generic/tensorflow-1.4.1-cp27-cp27mu-linux_x86_64.whl

**Comment by conduit242** [comment]
That worked! Thanks Paul.

**Comment by rolla12** [comment]
i work on this for three days ..cant found supported wheel for my platform..
  tensorflow-1.4.1-cp36-cp36m-linux_x86_64.whlthis one doesn't worked too

**Comment by rolla12** [comment]
got this error 
 File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by PaulWang1905** [comment]
Consider to update the python version. The build you mean is for python 3.6 
Or using virtualenv ,conda,or docker.
Or use  this whl.: https://github.com/mind/wheels/releases/download/tf1.4.1-gpu-cuda91-generic/tensorflow-1.4.1-cp35-cp35m-linux_x86_64.whl

**Comment by raffam** [comment]
I am on Windows 10 and have VS 2017 Community Edition. I tried to compile TensorFlow 1.4 with CUDA 9 but the compilation failed.
In particular, I have configured and generated the project files with the CMake build system. Then, as suggested in the guide, I tried to compile the project `tf_tutorials_example_trainer`.
The first linked project that fails to compile seems to be `tf_core_kernels`. I attach the compilation logs.
[tf_core_kernels.log](https://github.com/tensorflow/tensorflow/files/1594891/tf_core_kernels.log)

In particular, there are the following errors:

> D:\Programs\VS2017Community\VC\Tools\MSVC\14.12.25827\include\algorithm(2417): error C2678: binary '*': no operator found which takes a left-hand operand of type 'const tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator' (or there is no acceptable conversion) (compiling source file D:\data\programmi\tensorflow\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc)
>   D:\data\programmi\tensorflow\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc(54): note: could be 'const __int64 &tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator::operator *(void)'
>   d:\Programs\VS2017Community\VC\Tools\MSVC\14.12.25827\include\algorithm(2417): note: while trying to match the argument list '(const tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator)' (compiling source file D:\data\programmi\tensorflow\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc)
>   d:\Programs\VS2017Community\VC\Tools\MSVC\14.12.25827\include\algorithm(2439): note: see reference to function template instantiation '_FwdIt std::_Lower_bound_unchecked<_Iter,_Ty,_Fn>(_FwdIt,_FwdIt,const _Ty &,_Pr)' being compiled
>           with
>           [
>               _FwdIt=tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,
>               _Iter=tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,
>               _Ty=tensorflow::int64,
>               _Fn=std::less<void>,
>               _Pr=std::less<void>
>           ] (compiling source file D:\data\programmi\tensorflow\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc)
>   d:\Programs\VS2017Community\VC\Tools\MSVC\14.12.25827\include\algorithm(2447): note: see reference to function template instantiation '_FwdIt std::lower_bound<_FwdIt,_Ty,std::less<void>>(_FwdIt,_FwdIt,const _Ty &,_Pr)' being compiled
>           with
>           [
>               _FwdIt=tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,
>               _Ty=tensorflow::int64,
>               _Pr=std::less<void>
>           ] (compiling source file D:\data\programmi\tensorflow\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc)
>   D:\data\programmi\tensorflow\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc(115): note: see reference to function template instantiation '_FwdIt std::lower_bound<tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,tensorflow::int64>(_FwdIt,_FwdIt,const _Ty &)' being compiled
>           with
>           [
>               _FwdIt=tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator,
>               _Ty=tensorflow::int64
>           ]
> d:\Programs\VS2017Community\VC\Tools\MSVC\14.12.25827\include\algorithm(2417): error C2100: illegal indirection (compiling source file D:\data\programmi\tensorflow\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc)
> 

Moreover, various buffer overflows warnings are generated, which doesn't look good at all.

**Comment by rolla12** [comment]
PaulWang1905 , I had both python 3.5 and 3.6 ,,thanks for ( https://github.com/mind/wheels/releases/download/tf1.4.1-gpu-cuda91-generic/tensorflow-1.4.1-cp35-cp35m-linux_x86_64.whl
) but it is not optimized

**Comment by raffam** [comment]
The guide provided in TinyMind's [link](https://github.com/mind/wheels#cuda) installs CUDA 9.1, which seems to be not compatible with this wheel. You need to run

`sudo apt-get install cuda-9.0`

and not

`sudo apt-get install cuda`

**Comment by rolla12** [comment]
i got it installed but had the same  issues as https://github.com/tensorflow/tensorflow/issues/13711 ,,

**Comment by arunmandal53** [comment]
Go to http://www.python36.com/install-tensorflow141-gpu/ for step by step installation of tensorflow with cuda 9.1 and cudnn7.05 on ubuntu.

**Comment by PaulWang1905** [comment]
@arunmandal53  Hi, thanks for your link, did this guide work on your machine?  
 BTW, to all people having troubles with CUDA9.1, if you have to use CUDA9.1, consider to use the master branch or r1.5 branch. Some bugs has been fixed on the master branch.

**Comment by arunmandal53** [comment]
I have not checked master or r1.5 branch. But i build tensorflow 1.4 on my ubuntu16.04 with gpu 840m geforce and conformed myself it worked. I have written all the required details step by step to build tensorflow from source with cuda 9.1 and cudnn 7.05.

**Comment by rolla12** [comment]
arunmandal53 thanks it works

**Comment by neilpanchal** [comment]
Windows 10 wheels please! Eagerly waiting for windows Cuda 9 support.

**Comment by wangsen1312** [comment]
@neilpanchal   The newest 1.5 support the CUDA 9 and CUDNN 7

**Comment by Yagun** [comment]
Please build it for Windows (Win 7, Win 8 and Win 10 if the OS version is important) with CUDA 9.1 support.

**Comment by arunmandal53** [comment]
@Yagun I have successfully built Tensorflow 1.5.0 on Windows 10 with CUDA 9.1 and CUDNN 7.0.5 using cmake and Visual Studio 2015 Update 3. Tested. Goto http://www.python36.com/install-tensorflow-gpu-windows for step by step tutorial on "How to install Tensorflow 1.5.0 GPU with CUDA Toolkit 9.1 and cuDNN 7.0.5 for Python 3 on Windows OS". Let me know if it worked for you.

**Comment by raffam** [comment]
@arunmandal53 Thanks. I will try to build the 1.5 version on Windows 10.
But in your webiste there is written that "Currently, SSE or other are not supported by cl (C/CPP compiler came with visual studio 2015) only AVX and AVX2 supported.". Where did you take this information from?
For example, [here](https://stackoverflow.com/questions/1480916/how-do-i-enable-the-sse-sse2-instruction-set-in-visual-studio-2008-using-cmake) it says that it is supported at least since VS2005. Are you referring to TS Windows implementation in particular?

**Comment by arunmandal53** [comment]
@raffam actually i have used x64 based native cl compiler which does not have /arch:sse flags and it will throw ignoring warning. Though x86 build tools have sse enabled by default. But i have choosed x64 build tool due to out of memory errors.

**Comment by abhigoku10** [comment]
Hi could some one help me out , i have installed cuda 9.1 with cuddn 7.1 and all the dlls are present in the folder yet when i try to use tensorflow gpu it give me "ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit" but when i download the cuda 9.0 it again gives the same error saying cudart64_80.dll is not available . 

I have tired installing all the version of the tensorflow and cuda yet i get error i have checked the path variable to not sure why i am getting this error on Windows 10 1060q gpu

**Comment by rosefun** [comment]
YES，just download the correct version of cuda(as tf1.7.0_gpu need cuda9.0 and cudnn7).
Don't forget to log out your computer after add the variables of cuda.

**Comment by Baschdl** [comment]
@alexattia Do you have an import of any package using some ui components (matplotlib...) before your tensorflow import? That was the problem in my case, see #2903

**Comment by baregawi** [comment]
Anyone want to point me to the code that compiles models? Just ran into the slowness myself. It seems worse on CUDA 9.
