### ISSUE TITLE
Failed to synchronize the stop event

### ISSUE THREAD

**Issue by ljanyst** [tensorflow/tensorflow#14363]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
source

- **TensorFlow version (use command below)**:
b'v1.4.0-0-gd752244' 1.4.0

- **Python version**: 
3.5.2

- **Bazel version (if compiling from source)**:
0.7.0

- **GCC/Compiler version (if compiling from source)**:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

- **CUDA/cuDNN version**:
9.0/7.0

- **GPU model and memory**:
Tesla V100-SXM2-16GB

- **Exact command to reproduce**:
```
git clone https://github.com/ljanyst/image-segmentation-fcn.git
cd image-segmentation-fcn                                       
wget http://www.cvlibs.net/download.php?file=data_road.zip
unzip data_road.zip                                     
./train.py  --data-dir data_road
````
### Describe the problem
It seems like I am hitting some sort of a CUDA/cuDNN synchronization/race issue. Please see the snippet in the next section for the exact error message. The problem only happens with the KITTI dataset. The exact same TensorFlow code works fine for the Cityscapes dataset. Also, the problem only happens on Tesla V100. I tested the same exact software configuration on Tesla K80 and GeForce GTX1080 Ti as well, and things work fine.

### Source code / logs
```
2017-11-08 12:24:52.838039: E tensorflow/stream_executor/cuda/cuda_driver.cc:1080] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS
2017-11-08 12:24:52.838090: E tensorflow/stream_executor/cuda/cuda_timer.cc:54] Internal: error destroying CUDA event in context 0x51f18f0: CUDA_ERROR_ILLEGAL_ADDRESS
2017-11-08 12:24:52.838106: E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0x51f18f0: CUDA_ERROR_ILLEGAL_ADDRESS
2017-11-08 12:24:52.838137: F tensorflow/stream_executor/cuda/cuda_dnn.cc:3218] failed to set stream for cudnn handle: CUDNN_STATUS_MAPPING_ERROR
zsh: abort (core dumped)  ./train.py --data-dir data_road
```

**Comment by angersson** [comment]
@zheng-xq, can you take a look at this?

**Comment by zheng-xq** [comment]
The synchronization error is only what finds out the issue. The root cause is some GPU kernels had an illegal address access.

If someone wants to root cause this, first it is needed to find the offending kernel. In our past experience, it could be either a kernel bug, or a degenerate data entry.

**Comment by ljanyst** [comment]
Thanks for the hint @zheng-xq ! I have had a closer look, and the offending kernel seems to be:

```
CUDA Exception: Warp Out-of-range Address

Thread 28 "python" received signal CUDA_EXCEPTION_5, Warp Out-of-range Address.
[Switching focus to CUDA kernel 1994, grid 1995, block (0,0,0), thread (128,0,0), device 0, sm 0, warp 6, lane 0]
0x00007ffe7ac23a50 in volta_scudnn_128x128_stridedB_splitK_xregs_large_nn_v1_LOOP<<<(5,1,160),(256,1,1)>>> ()
(cuda-gdb) info cuda kernels
  Kernel Parent Dev Grid Status   SMs Mask   GridDim  BlockDim Invocation 
*   1994      -   0 1995 Active 0xffffffff (5,1,160) (256,1,1) .text.volta_scudnn_128x128_stridedB_splitK_xregs_large_nn_v1() 
```

I was unable to get any useful host-side stack trace because there appears to by something wrong with the DWARF symbols: `Unable to access DWARF register number 83886081`. I am not sure whether it's about the symbols in CUDA/cuDDN or in TensorFlow. Do you think that recompiling TensorFlow in debug mode will help? If so, how do I pass extra parameters to nvcc with Bazel?

**Comment by zheng-xq** [comment]
That seems to be a Cudnn bug. Adding NVIDIA folks. 

@benbarsdell, @nluehr, any insight to debug this Cudnn kernel exception?

**Comment by juliebernauer** [comment]
@ljanyst Let's talk offline so that I can have a look at this with debug info. Thanks.

**Comment by juliebernauer** [comment]
@zheng-xq @ljanyst We have a repro and a fix. Roll out is planned in cuDNN 7.0.5 mid-December.

**Comment by ManuelaPa** [comment]
Hello
I installed tensorflow 1.4 cudnn 6 and cuda 8.0
I have the same problem "cuda_event.cc:49 Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS" when I try yo train with tensoflow
I have tried to install anothers versions but I have the same issue always and in some computers, not only mine. Do you know what I have to do? Thanks

**Comment by mholt** [comment]
Came here to report the exact same thing with our Volta, using the Tensorflow container on NVIDIA GPU Cloud. We will be happy to test the fix with cuDNN 7.0.5 and follow-up. Please let us know if there are any other updates on this issue.

**Comment by RerRayne** [comment]
Same problem with WaveNet on V100:
```
2017-12-05 14:08:26.119341: E tensorflow/stream_executor/cuda/cuda_driver.cc:1080] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS
2017-12-05 14:08:26.119423: E tensorflow/stream_executor/cuda/cuda_timer.cc:54] Internal: error destroying CUDA event in context 0xbab66e0: CUDA_ERROR_ILLEGAL_ADDRESS
2017-12-05 14:08:26.119435: E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0xbab66e0: CUDA_ERROR_ILLEGAL_ADDRESS
2017-12-05 14:08:26.119470: F tensorflow/stream_executor/cuda/cuda_dnn.cc:3218] failed to set stream for cudnn handle: CUDNN_STATUS_MAPPING_ERROR
```
Is there a more precise timeline info on the fix? We would gladly try a beta version of cuDNN, if any exists.
Thank you!

**Comment by tukushan** [comment]
Confirmed that cuDNN 7.0.5 from https://developer.nvidia.com/rdp/cudnn-download fixes this on the AWS p3.8xlarge (Volta 4 GPU)

**Comment by juliebernauer** [comment]
@tukushan Glad to hear you can confirm the fix. @ManuelaPa @mholt @RerRayne @ljanyst Should be fixed by using cuDNN 7.0.5.

**Comment by mholt** [comment]
After installing cuDNN 7.0.5, I am still seeing this error. :( I'm using the TensorFlow container from NVIDIA GPU cloud. Anyone know if there's any extra steps I need to take? I extracted the library files and moved them into place according to the installation instructions...

**Comment by cliffwoolley** [comment]
@mholt - If you're using the NGC image for TensorFlow, you don't actually need to install cuDNN directly, as it's installed in the container for you already.  The NGC frameworks release 17.12 includes cuDNN 7.0.5 and should fix this issue.  Or are you saying you tried 17.12 and still see an issue?

**Comment by mholt** [comment]
Ah, sorry, I mistakenly thought cuDNN was installed outside the container (but maybe that is CUDA actually) -- pulling and using the latest container fixed it. Looks like that patch did it. Thank you!

**Comment by RerRayne** [comment]
@juliebernauer it works after updating. Thank you a lot!

**Comment by ljanyst** [comment]
Things work for me too now. Thanks @juliebernauer !

**Comment by ManuelaPa** [comment]
@juliebernauer Thanks for the answer! I installed cudnn 7.0.5 but it's not compatible with tensorflow 1.4, it needs cudnn64_6.dll, do you know that I should do? 
Thank you

**Comment by juliebernauer** [comment]
@ManuelaPa The developer website lists Win7 and Win10 versions for both CUDA9.0 and CUDA9.1. So one has to make sure to download and install the one needed - after removing previous versions on Windows (this is not the case on Linux). Can you please try this? This should work. If not, may I suggest you send a ticket or report a bug on the NVIDIA developer website?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by shivaniag** [comment]
Update seems to fix the issue, closing this.

**Comment by badreddine1758** [comment]
I am trying to build my own Tensorflow Op on a AWS P3 instance (using NVIDIA's GPU Cloud and nvidia-docker) and I get the following error message:

```
2018-05-29 10:47:38.377439: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
2018-05-29 10:47:38.377513: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
```

To build the Op, I had to create a coda_config.h, under /usr/local/cuda/, with the following content

```
#ifndef CUDA_CUDA_CONFIG_H_
#define CUDA_CUDA_CONFIG_H_

#define TF_CUDA_CAPABILITIES CudaVersion("3.0")

#define TF_CUDA_VERSION "9.0"
#define TF_CUDNN_VERSION "7.0.5"

#define TF_CUDA_TOOLKIT_PATH "/usr/local/cuda-9.0"

#endif  // CUDA_CUDA_CONFIG_H_
```

I also had to make these changes to /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h

```
#include "/usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public/nsync_cv.h" // <- "nsync_cv.h"
#include "/usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public/nsync_mu.h" // <- "nsync_mu.h"
```
I compile my source code files as follows
nvcc -std=c++11 -c -o my_op_gpu.cu.o my_op_gpu.cu.cc -I $TF_INC -I /usr/local/ -I /usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public -I /usr/local/cuda/include/ -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC --expt-relaxed-constexpr 
 
g++ -std=c++11 -shared -D_GLIBCXX_USE_CXX_ABI=0 -o my_op.so my_op.cc my_op_gpu.cu.o -I $TF_INC -I /usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public -D GOOGLE_CUDA=1 -L$TF_LIB -ltensorflow_framework -fPIC 

where
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')

Please help.

**Comment by weiliu620** [comment]
@juliebernauer so my understanding is v9.1 has the fix. but I'm having the same error 
```
2018-06-01 09:49:37.379160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties:
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:06:00.0
totalMemory: 22.38GiB freeMemory: 22.21GiB
2018-06-01 09:49:37.379206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-06-01 09:49:37.673924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-01 09:49:37.673988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0
2018-06-01 09:49:37.673996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N
2018-06-01 09:49:37.674543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21559 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:06:00.0, compute capability: 6.1)
2018-06-01 09:49:44.636341: E tensorflow/stream_executor/cuda/cuda_driver.cc:1080] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS
2018-06-01 09:49:44.636422: E tensorflow/stream_executor/cuda/cuda_timer.cc:54] Internal: error destroying CUDA event in context 0x6ab0fb0: CUDA_ERROR_ILLEGAL_ADDRESS
2018-06-01 09:49:44.636433: E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0x6ab0fb0: CUDA_ERROR_ILLEGAL_ADDRESS
2018-06-01 09:49:44.636483: F tensorflow/stream_executor/cuda/cuda_dnn.cc:2328] failed to set stream for cudnn handle: CUDNN_STATUS_MAPPING_ERROR
Aborted
```

I'm on Red hat EL 7, CUDA V9.1.85 (as seen from `nvcc --version` and TF 1.7. 

Do I need to upgrade to CUDA 9.2?

**Comment by juliebernauer** [comment]
@weiliu620 you want to make sure you are indeed using the cudnn version mentioned above. Upgrading CUDA won't change that by default (but might get you to use a different dir). Cleaning your LD_LIBRARY_PATH might help.

**Comment by majthehero** [comment]
I have this problem on CUDA 10.0. I'm using TF 1.10.0, keras 2.2.2, Window 10, GPU Nvidia mx150.

**Comment by christopher5106** [comment]
I confirm it solves the issue

**Comment by aimzieslol** [comment]
```
2019-03-19 13:31:35.622328: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
2019-03-19 13:31:35.642103: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4336885000 Hz
2019-03-19 13:31:35.642675: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55a2ee4e12b0 executing computations on platform Host. Devices:
2019-03-19 13:31:35.642712: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-19 13:31:35.860957: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55a2ee4be0b0 executing computations on platform CUDA. Devices:
2019-03-19 13:31:35.861029: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
2019-03-19 13:31:35.862019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.11GiB
2019-03-19 13:31:35.862059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-03-19 13:31:35.864736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-19 13:31:35.864767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-03-19 13:31:35.864792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-03-19 13:31:35.865597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6915 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
[I 13:32:16.864 LabApp] Saving file at /mobilenet-v2.ipynb
2019-03-19 13:33:04.306841: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-03-19 13:33:05.855707: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-03-19 13:33:05.855752: E tensorflow/stream_executor/cuda/cuda_timer.cc:55] Internal: error destroying CUDA event in context 0x7f5e1c700f30: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-03-19 13:33:05.855766: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 0x7f5e1c700f30: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-03-19 13:33:05.855786: F tensorflow/stream_executor/cuda/cuda_dnn.cc:194] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.
[I 13:33:17.075 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel 7b15ebfd-d35b-4c14-a383-59f53ea73a89 restarted
```

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

Getting this same error also. I've dropped the batch size to 50. 

Specs:
```
Manjaro Linux 4.19.28-1-MANJARO #1 SMP PREEMPT Sun Mar 10 08:32:42 UTC 2019 x86_64 GNU/Linux
```

```
Keras                2.2.4      
Keras-Applications   1.0.7      
Keras-Preprocessing  1.0.9
Python 3.7.1
tensorboard          1.13.1     
tensorflow           1.13.1     
tensorflow-estimator 1.13.0     
tensorflow-gpu       1.13.1
pycuda               2018.1.1

cuda 10.0.130-2
pycuda-headers 2018.1.1-4
python-pycuda 2018.1.1-4
python-tensorflow-cuda 1.13.1-2
tensorflow-cuda 1.13.1-2
```

**Comment by wumeng2** [comment]
@zheng-xq   hello, I also met this error using RTX2070. but after replacing a new gpu, I have never seen this error so far. I agree with you on the fact that  the synchronization error is only what finds out the issue. The root cause is some GPU kernels had an illegal address access. Hope to get  some insight from @benbarsdell , @nluehr . Thank you!

**Comment by henbucuoshanghai** [comment]
> Same problem with WaveNet on V100:
> 
> ```
> 2017-12-05 14:08:26.119341: E tensorflow/stream_executor/cuda/cuda_driver.cc:1080] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS
> 2017-12-05 14:08:26.119423: E tensorflow/stream_executor/cuda/cuda_timer.cc:54] Internal: error destroying CUDA event in context 0xbab66e0: CUDA_ERROR_ILLEGAL_ADDRESS
> 2017-12-05 14:08:26.119435: E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0xbab66e0: CUDA_ERROR_ILLEGAL_ADDRESS
> 2017-12-05 14:08:26.119470: F tensorflow/stream_executor/cuda/cuda_dnn.cc:3218] failed to set stream for cudnn handle: CUDNN_STATUS_MAPPING_ERROR
> ```
> 
> Is there a more precise timeline info on the fix? We would gladly try a beta version of cuDNN, if any exists.
> Thank you!

how you fix it    mine is 2080ti    ,same question    how to fix it

**Comment by henbucuoshanghai** [comment]
> @tukushan Glad to hear you can confirm the fix. @ManuelaPa @mholt @RerRayne @ljanyst Should be fixed by using cuDNN 7.0.5.
cudnn version is 7.0.5   and  I have to change the CUDA and tensorflow version    too???????

**Comment by henbucuoshanghai** [comment]
> > @tukushan Glad to hear you can confirm the fix. @ManuelaPa @mholt @RerRayne @ljanyst Should be fixed by using cuDNN 7.0.5.
> > cudnn version is 7.0.5   and  I have to change the CUDA and tensorflow version    too???????



> dropped the batch size to 50.

and teh error is solveed???

**Comment by henbucuoshanghai** [comment]
> Internal: error destroying CUDA event in context 0x7f5e1c700f30: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
> 2019-03-19 13:33:05.855766: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 0x7f5e1c700f30: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
> 2019-03-19 13:33:05.855786: F tensorflow/stream_executor/cuda/cuda_dnn.cc:194] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.
> [I 13:33:17.075 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports

my versions and errors are same as yours : cuda 10.0 ,tf
13.1     the error is same: tensorflow/stream_executor/cuda/cuda_dnn.cc:194] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream



how to slover them ??????

**Comment by henbucuoshanghai** [comment]
> I confirm it solves the issue

how to slover it

**Comment by yiyayamaya** [comment]
> > I confirm it solves the issue
> 
> how to slover it

Have you solved it?

**Comment by ysyyork** [comment]
mine is 2080ti and it only happens when it happens once. the first several train will be fine but if by accident it happens. i have no way to reset from rebooting. 
I'm using tf 1.4, cuda 10.1 and cudnn7
