### ISSUE TITLE
Bazel Build Fails with "undeclared inclusion(s) in rule '@nccl_archive//:nccl'"

### ISSUE THREAD

**Issue by johnsrude** [tensorflow/tensorflow#14380]
### System information
The environment used is:
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/1455194/tf_env.txt)

The branch downloaded is tensorflow-master branch

When I run the configure script the configuration is
[.tf_configure.bazelrc](https://github.com/tensorflow/tensorflow/files/1455688/tf_configure.bazelrc.txt)
 

### Describe the problem
When I run
```
bazel build --config=opt --config=cuda --config=mkl //tensorflow/tools/pip_package:build_pip_package
```
The build fails with the error
``` "/home/kevin/.cache/bazel/_bazel_kevin/1bfc1cc47be0eab35fef533f37af7359/external/nccl_archive/BUILD:33:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/core.cu.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed/syslimits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdarg.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
FAILED: Build did NOT complete successfully
```
but the files are present:
```
ls /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed/limits.h
/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed/limits.h
```
There appears to be a problem with bazel build with MKL enabled.  I have been able to compile this with MKL disabled. MKL for Ubuntu should be supported, yes?

**Comment by bignamehyp** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by johnsrude** [comment]
All the info is provided but I guess I was too concise.  I'll add verbiage to the OP.

**Comment by johnsrude** [comment]
I have fixed my problem on my side by running 
```
bazel clean --expunge
```
then hand-editing the configure file to
[.tf_configure.bazelrc](https://github.com/tensorflow/tensorflow/files/1455717/tf_configure.bazelrc.txt)
 then running
```
bazel build --config=opt --config=cuda --config=mkl //tensorflow/tools/pip_package:build_pip_package
```

**Comment by bignamehyp** [comment]
MKL was added as of TensorFlow 1.2 and currently only works on Linux. It also does not work when also using --config=cuda.

**Comment by bignamehyp** [comment]
@zheng-xq

**Comment by tfboyd** [comment]
It does not work with the --config=cuda.  Assigning to Gunhan there is work in this area with no ETA.  Also if you are using GPU I would go with AVX2 or AVX it should get most of the benefits you need for work mostly done on the GPU.  AVX2 does help for GPU work in my testing.  The input pipeline (image processing) benefits from it but I did not see a big difference until 8x K80s and did not have time to test o P100s or other situations.  Nor do I know the exact calls that benefit.  Not super informational but a little.  :-)

**Comment by johnsrude** [comment]
In the meantime how about a better error message, either in configure.py or in bazel?

**Comment by tfboyd** [comment]
I know this may seem confrontational but it is not.  You could add a message to configure.py.  It would not stop people from adding --config=cuda but you could give a warning based on the options they pick.  On the flip side, I am not sure how many people run into this problem.  If they see MKL on the performance page it says --config=cuda does not work.  If they see it in the config.py then a message would help them and you could be a hero.  (not sarcasm, the internet is a hard place to read intent)  

I would not expect people to see everything on the website as that is crazy.  I did [document the --config=cuda does not work](https://www.tensorflow.org/performance/performance_guide#tensorflow_with_intel_mkl_dnn).  And if you are interested in some gains with various config options on CPU.

**Comment by KevinLucidyne** [comment]
@tfboyd no offense taken.  We both want the same thing, to make TensorFlow better.

**Comment by jiayiliu** [comment]
I got the same problem, and found a unsuccessful (to me) solution at #10665 

Hope this helps @johnsrude

**Comment by gunan** [comment]
Could you try with bazel 0.8 and report what you see?
I think on ubuntu 16, we may have a problem with older bazel versions.

**Comment by jiayiliu** [comment]
@gunan  I am using redhat, unfortunately and still failed with bazel 0.8.1.  I will discuss the problem in #10665 since there is another person on that issue.  Thanks!

**Comment by beanliao** [comment]
I have the same problem, can anyone help to check " undeclared inclusion(s) in rule '@nccl_archive//:nccl' " issue?
it will be really appreciated. :)

**System information:**
CentOS 7.3
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Build label: 0.8.1- (@non-git)
cuda 9.0.176
cudnn 7.0.5
tensorflow 1.4.0

**Build command:**
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

Error message:
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/nccl_archive/BUILD:33:1: undeclared inclusion(s) in rule '@nccl_archive//:nccl':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/libwrap.cu.cc':
'/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
'/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
'/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
'/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.973s, Critical Path: 4.56s
FAILED: Build did NOT complete successfully

**Comment by gunan** [comment]
I think this is a problem with the default toolchain in bazel.
Will wait for a response from bazel team.

**Comment by beanliao** [comment]
@gunan Thanks for commenting. Is there any approach to install Tensorflow 1.4 on a system with Cuda9.0/Cudnn7.0/NCCL 2.0 ?

**Comment by jiayiliu** [comment]
@gunan Thanks!  Could you point out the problem that I can follow up with?  I am not familiar with bazel but I would like to understand better about it.

**Comment by gunan** [comment]
Github auto-referenced the issue above. I filed the issue in bazel repository here: https://github.com/bazelbuild/bazel/issues/4365

**Comment by gunan** [comment]
Can someone with a redhat or centos system try running this command and share its output?
```
gcc -E  -xc++ - -v
```

**Comment by beanliao** [comment]
@gunan 
I run with CentOS.
[root@localhost ~]# gcc -E -xc++ - -v
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/cc1plus -E -quiet -v -D_GNU_SOURCE - -mtune=generic -march=x86-64
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/x86_64-redhat-linux
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/backward
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include
 /usr/local/include
 /usr/include
End of search list.

**Comment by gunan** [comment]
Thank you very much!
the output does show the header folders you are missing. I am curious why you see the failure you reported. I will continue pushing from the bazel side.

**Comment by gunan** [comment]
On CentOS I was able to successfully build cuda and non-cuda TF,  at head using bazel.
I was not able to reproduce the problem later reported in this issue.

I will now test building with MKL.

**Comment by gunan** [comment]
using docker, I was able to successfully build pip package with the following parameters:
base image: `nvidia/cuda:9.0-cudnn7-devel-centos7`
TF revision: `master`
bazel version: `0.8.1`
gcc/g++ version: `4.8.5`

Commands tried:
```
bazel build --config=cuda --config opt --config=mkl tensorflow/tools/pip_package:build_pip_package
bazel build --config=cuda --config opt tensorflow/tools/pip_package:build_pip_package
bazel build --config=cuda -c opt tensorflow/tools/pip_package:build_pip_package
```

Maybe there was a problem before, but it seems to be resolved at head. I will close this issue now, but if you still see this problem at the master branch, please file a new issue with detailed instructions to reproduce the problem, preferably using docker.

**Comment by ilya-biryukov** [comment]
If the issue pops up again, looking at the generated crosstool, e.g. by
```
cat $(bazel info output_base)/external/local_config_cuda/crosstool/CROSSTOOL
```
Should shed some light on the problem.

It usually boils down to crosstool referencing files via symlink, while compilers resolve the symlinks when outputting the .d files and vice versa.

**Comment by jiayiliu** [comment]
@gunan Thanks for the extensive checks.  But I still got the problem no matter with master or r1.4 branches.  Also I shared the same output as @beanliao that the missing paths are in the search path.

I took a look as suggested by @ilya-biryukov - I found the following lines look suspicious:

  cxx_builtin_include_directory: "/include/c++/4.8.5"
  cxx_builtin_include_directory: "/include/c++/4.8.5/x86_64-redhat-linux"
  cxx_builtin_include_directory: "/include/c++/4.8.5/backward"
  cxx_builtin_include_directory: "/lib/gcc/x86_64-redhat-linux/4.8.5/include"

These paths missed the `/usr/` part.  But adding it won't solve the problem.

**Comment by jiayiliu** [comment]
Also I successfully built the CPU version. And then I got the error below with "--config=cuda":

ERROR: /path_to_tensorflow/tensorflow/contrib/resampler/BUILD:51:1: undeclared inclusion(s) in rule '//tensorflow/contrib/resampler:python/ops/_resampler_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/contrib/resampler/kernels/resampler_ops_gpu.cu.cc':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/x86intrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/ia32intrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/mmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/xmmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/mm_malloc.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/emmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/immintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/fxsrintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/adxintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/float.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdbool.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 12.777s, Critical Path: 12.35s
FAILED: Build did NOT complete successfully

I believe that this is the same error as nccl one and it related more to the configuration of the CROSSTOOL.

**Comment by gunan** [comment]
@jiayiliu Could you file a new issue with all the information asked by the issue template for me to be able to reproduce the problem? Please do not skip anything in the template, as I will need all the information to have a chance to reproduce the issue. As I mentioned in https://github.com/tensorflow/tensorflow/issues/14380#issuecomment-355214575 it may be your bazel version, your OS version, GCC version, or a combination but unless I can reproduce your problem, there is nothing I can do for you.

Also, please add the output of `gcc -E -xc++ - -v` to the issue you file. Thanks.

**Comment by ilya-biryukov** [comment]
@jiayiliu, you could try applying the following patch locally via `git apply <patch-name>`:
[0001-Don-t-use-no-canonical-prefixes-when-getting-include.txt](https://github.com/tensorflow/tensorflow/files/1607470/0001-Don-t-use-no-canonical-prefixes-when-getting-include.txt). There's a good chance your issue will be fixed by it (see the explanation below).
Also, have you considered using a recently added downloadable clang toolchain for cuda_clang configuration? Just configure with `TF_NEED_CUDA=1 TF_CUDA_CLANG=1 TF_DOWNLOAD_CLANG=1` (or choose the appropriate options when running `configure.py`)?

@gunan, @jiayiliu I bet the difference is that bazel's [autoconf](https://github.com/bazelbuild/bazel/blob/39a23a0e3d63c538b8aa9f6f94a3a3916998e973/tools/cpp/unix_cc_configure.bzl#L151) (in CPU build) does not pass `-no-canonical-prefixes`, while tensorflow's [GPU crosstool](https://github.com/tensorflow/tensorflow/blob/a1b155b6f51c539974e1bf73d0e0d15b388b9219/third_party/gpus/cuda_configure.bzl#L116) passes `-no-canonical-prefixes`.

I've checked it locally and it does not seem to break anything for me in gpu builds, so I guess we should just follow what bazel does and don't set `-no-canonical-prefixes` when getting the list of includes in `cuda_configure.bzl`. I'll send a patch for review with that change.

**Comment by argman** [comment]
my system version: centos7+gcc4.8.5+bazel 0.8.1
I find its tricky to fix this , just change the default gcc path when running configure from /bin/gcc to /usr/bin/gcc

**Comment by gunan** [comment]
@mhlopko @lberki is it possible the default toolchains do not work if the compiler is under `/bin/gcc`.

**Comment by argman** [comment]
@gunan I check that in configure.py it use which('gcc') to find gcc, when i run this it returns /bin/gcc, but when i run it manualy use shutil.which('gcc') it returns /usr/bin/gcc

**Comment by bidai541** [comment]
Met the similar problem too.  I removed the path of bazel cache files in "/root/.cache/bazel"(change root to your user path) and rebuild, build completed successfully.

**Comment by forest1990** [comment]
@argman  
Thanks.  It does work by " just change the default gcc path when running configure from /bin/gcc to /usr/bin/gcc"

**Comment by albenoit** [comment]
Hi all,
I am facing the same issues on undeclared inclusions on REHL Scientific Linux 6 ONLY when compiling with cuda (CPU mode works), according to the discussion above and other threads such as [#4365](https://github.com/bazelbuild/bazel/issues/4365), I did the following additional changes to my previous issue on an older Tensorflow version [#8529](https://github.com/tensorflow/tensorflow/issues/8529). I finally worked but i cannot say which factor actually solved the issue...(adding --cxxopt and/or removing the "-no-canonical-prefixes" option):

With Config : REHL SL6, bazel 0.8.0, tensorflow r1.5, CUDA 8.0, cudnn7.0.4, using gcc and compilation stuff from the devtoolset-4 module

1. delete the bazel cache folder
2. applied the fix proposed by ilya-biryukov removing the "-no-canonical-prefixes" option in third_party/gpus/cuda_configure.bzl file
 ```
-  result = repository_ctx.execute([cc, "-no-canonical-prefixes",
-                                   "-E", "-x" + lang, "-", "-v"])

+  result = repository_ctx.execute([cc, "-E", "-x" + lang, "-", "-v"])
   index1 = result.stderr.find(_INC_DIR_MARKER_BEGIN)
   if index1 == -1:
 
```
3. added --cxxopts in the bazel build command:
bazel build --cxxopt="-I/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/include/" --cxxopt="-I/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include" --linkopt='-lrt' -c opt --copt=-mavx --copt=-mavx2 --copt=-msse4.2 --copt=-msse4.1 --copt=-mfma --copt=-msse3 --config=cuda --genrule_strategy=standalone --spawn_strategy=standalone //tensorflow/tools/pip_package:build_pip_package

It finally worked... waiting for this for sooooo long, thanks to all with your hints and discussions !

**Comment by hlopko** [comment]
We've had discussions with the Bazel's external repositories team, and they're delivering `bazel sync --configure` in Bazel 0.29 command that will only refetch configure-like external repositories (which nccl_archive is). Good news is that we won't have to throw everything out with `clean --expunge`, only artifacts affected by the update will be recomplited. Bad news is that you still have to manually call `sync --reconfigure` when you update your system dependencies.

**Comment by hlopko** [comment]
Relevant Bazel commit - https://github.com/bazelbuild/bazel/commit/4a1380fed159f09b29df461b85e0469f8cd81d34
