### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

### ISSUE THREAD

**Issue by HudsonHuang** [tensorflow/tensorflow#14433]
**I am running some preparation code with tf, it seems it doesn't to much memory for it. But:**

(tensorflow) lab-huang.zhongyi@gpu-2:~/workspace/vae-npvc$ python build.py
452 files found
Processing Tensor("ReaderReadV2:0", shape=(), dtype=string)
2017-11-10 12:24:55.938368: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-10 12:24:55.938398: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-10 12:24:55.938408: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-11-10 12:24:55.938427: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-10 12:24:55.938435: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.

2017-11-10 12:24:57.272601: E tensorflow/core/common_runtime/direct_session.cc:138] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 8508145664
Traceback (most recent call last):
  File "build.py", line 100, in <module>
    main()
  File "build.py", line 24, in main
    with sv.managed_session() as sess:
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/lab-huang.zhongyi/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 953, in managed_session
    start_standard_services=start_standard_services)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 708, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 273, in prepare_session
    config=config)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 178, in _restore_checkpoint
    sess = session.Session(self._target, graph=self._graph, config=config)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 562, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/lab-huang.zhongyi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

**and when I checkout "nvidia-smi", some GPUs still have many memory:**

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    On   | 0000:04:00.0     Off |                  N/A |
| 49%   69C    P2    57W / 180W |   8046MiB /  8114MiB |     45%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    On   | 0000:05:00.0     Off |                  N/A |
| 48%   69C    P2    53W / 180W |   7393MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    On   | 0000:08:00.0     Off |                  N/A |
| 53%   72C    P2    54W / 180W |   7917MiB /  8114MiB |     19%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    On   | 0000:09:00.0     Off |                  N/A |
| 60%   76C    P2    54W / 180W |   7413MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 1080    On   | 0000:84:00.0     Off |                  N/A |
| 24%   41C    P8    12W / 180W |   2684MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 1080    On   | 0000:85:00.0     Off |                  N/A |
| 24%   35C    P8    12W / 180W |   1895MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 1080    On   | 0000:88:00.0     Off |                  N/A |
| 67%   82C    P2   163W / 180W |   6105MiB /  8114MiB |     88%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 1080    On   | 0000:89:00.0     Off |                  N/A |
| 67%   82C    P2   144W / 180W |   6097MiB /  8114MiB |     89%      Default |
+-------------------------------+----------------------+----------------------+

**and here is the code:**
 https://github.com/JeremyCCHsu/vae-npvc/blob/master/build.py

**Thank you all so much, I am really just a beginner.**

**Comment by HudsonHuang** [comment]
Oh it it really don‘t  enought memories.
I solved it by allocating memories dynamically:

import tensorflow as tf  
import os  
os.environ["CUDA_VISIBLE_DEVICES"] = '0'   #use GPU with ID=0 
config = tf.ConfigProto()  
config.gpu_options.per_process_gpu_memory_fraction = 0.5  # maximun alloc gpu50% of MEM
config.gpu_options.allow_growth = True      #allocate dynamically
sess = tf.Session(config = config)

**Comment by codewanghust** [comment]
mark

**Comment by nateGeorge** [comment]
In my case, it was installing:

`sudo apt install nvidia-cuda-toolkit`

which seemed to do the trick.  It updated the drivers to a newer version (looked like 410).  First, the ppa was added:
`sudo add-apt-repository ppa:graphics-drivers/ppa`
`sudo apt update`
