### ISSUE TITLE
Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain

### ISSUE THREAD

**Issue by hookover** [tensorflow/tensorflow#14475]
### SYSTEM Infomation
ubuntu16.04
cuda7.5
cudnn5
gtx1060
tensorflow1.0.1
python3.5
memory 15.6G ,used 5.3GB

$ nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
| 33%   38C    P2    27W / 120W |   6012MiB /  6071MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1536      G   /usr/lib/xorg/Xorg                           273MiB |
|    0      3210      G   compiz                                       115MiB |
|    0      3811      G   ...-token=C6D7A354DD6B35830E1B2860115A47BF    82MiB |
+-----------------------------------------------------------------------------+
```
### run train script get this error:

```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Called with args:
Namespace(cfg_file='./lstm/lstm.yml', gpu_id=0, max_iters=700000, network_name='LSTM_train', pre_train=None, randomize=False, restore=0, set_cfgs=None)
Using config:
{'CHARSET': '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
 'EXP_DIR': 'lstm_ctc',
 'FONT': 'fonts/Ubuntu-M.ttf',
 'GPU_ID': 0,
 'IMG_SHAPE': [180, 60],
 'LOG_DIR': 'lstm_ctc',
 'MAX_CHAR_LEN': 6,
 'MAX_LEN': 6,
 'MIN_LEN': 4,
 'NCHANNELS': 1,
 'NCLASSES': 64,
 'NET_NAME': 'LSTM',
 'NUM_FEATURES': 60,
 'POOL_SCALE': 2,
 'RNG_SEED': 3,
 'ROOT_DIR': '/srv/python/lstm_ctc_ocr_with_tf_1.0.1',
 'SPACE_INDEX': 0,
 'SPACE_TOKEN': '',
 'TEST': {},
 'TIME_STEP': 90,
 'TRAIN': {'BATCH_SIZE': 32,
           'DISPLAY': 100,
           'GAMMA': 1.0,
           'LEARNING_RATE': 0.001,
           'LOG_IMAGE_ITERS': 100,
           'MOMENTUM': 0.9,
           'NUM_EPOCHS': 2000,
           'NUM_HID': 128,
           'NUM_LAYERS': 2,
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 2000,
           'SNAPSHOT_PREFIX': 'lstm',
           'SOLVER': 'RMS',
           'STEPSIZE': 2000,
           'WEIGHT_DECAY': 1e-05},
 'VAL': {'BATCH_SIZE': 128,
         'NUM_EPOCHS': 1000,
         'PRINT_NUM': 5,
         'VAL_STEP': 500}}
Output will be saved to `/srv/python/lstm_ctc_ocr_with_tf_1.0.1/output/lstm_ctc`
Logs will be saved to `/srv/python/lstm_ctc_ocr_with_tf_1.0.1/logs/lstm_ctc/lstm_train/2017-11-11-11-13-49`
/gpu:0
Tensor("data:0", shape=(?, ?, 60), dtype=float32)
Tensor("conv4/BiasAdd:0", shape=(?, ?, 30, 1), dtype=float32)
Tensor("time_step_len:0", shape=(?,), dtype=int32)
Use network `LSTM_train` in training
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
E tensorflow/core/common_runtime/direct_session.cc:137] 
Internal: failed initializing StreamExecutor 
for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: 
CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615
Traceback (most recent call last):
  File "./lstm/train_net.py", line 89, in <module>
    restore=bool(int(args.restore)))
  File "./lstm/../lib/lstm/train.py", line 187, in train_net
    with tf.Session(config=config) as sess:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1176, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 552, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

```

I will be grateful to anyone for helping me
Thanks everyone

**Comment by drpngx** [comment]
It looks like there is a problem with this:
```
for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: 
CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615
```

Can you try with:
```
gpu_fraction = 0.1
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=gpu_fraction)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
Closing since the issue is stalled. Feel free to reopen if you have more information.

**Comment by wuwuwuwuwu55555** [comment]
It seems that there is no space in GPU, you would like to kill one process and re-run you code, or if you have  more than one gpu, set the gup number you want to use .

**Comment by NekuSakuraba** [comment]
I had an issue similar to this...
I was trying to execute the tensorflow in a jupyter lab notebook.

The issue stopped after I ran jupyter with `sudo jupyter lab --allow-root`

**Comment by anonymone** [comment]
I had an issue similar to this when I used docker to run two tensorflow program using GPU.

**Comment by EasonTong** [comment]
> It looks like there is a problem with this:
> 
> ```
> for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: 
> CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615
> ```
> Can you try with:
> 
> ```
> gpu_fraction = 0.1
> gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=gpu_fraction)
> sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
> ```

I tried, but it still doesn' t work.

**Comment by ThejanW** [comment]
`jupyter lab --allow-root` worked for me.

**Comment by Harry-KIT** [comment]
Hi brothers
i have 4 gpus on my PC. But i could utilize only one gpu. Others can not be used. Can you help me in this case. Actually i tried to use all gpus for dirrerent git repos.

error:

Attempting to fetch value instead of handling error Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 12652838912

**Comment by KishoreKonakanti** [comment]
@Harry-KIT ,

please set the gpu numbers to the process... you can do this in multiple ways as per the context:

- dlib: 
```
  from dlib import cuda
  cuda.set_device(<gpu number>
```
- OPENCV
`   cv2.cuda.setDevice(<gpu number>
`- More generic method
   ```
install numactl (sudo apt install numactl)
   export CUDA_VISIBLE_DEVICES=<gpu_number>;numactl --cpunodebind=<gpu number> ./executable
```

Hope this helps :+1: 

Thank you.
