### ISSUE TITLE
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hernandezurbina** [tensorflow/tensorflow#14622]
I'm trying to run Tensorflow-gpu through virtualenv via pip3 in Ubuntu 16.04. I have installed Cuda-9.0 and cuDNN v7.0.3, then tested both and they are working fine. However, when attempting to import Tensorflow in Python I get the following error:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

I located libcublas.so in /usr/local/cuda/lib64. However, I see that it references a new version of the library (9.0.176), My question is whether something simple can be done (like creating a symbolic link to the library with the name of libcublas.so.8.0) or I have to wait for an update in TF that can run with Cuda9/cuDNN 7

Cheers!

**Comment by layssi** [comment]
+1

**Comment by pangzhan27** [comment]
i have met the same problem. it seems that cuda 9.0 is not supported for Tensorflow-gpu through virtualenv for now. You may try to install through source code.

**Comment by jclune** [comment]
+1

**Comment by manchengfenxu** [comment]
+1

**Comment by tc64** [comment]
+1

**Comment by napolar** [comment]
+1

**Comment by usernameoliver** [comment]
+1

**Comment by Servot** [comment]
+1

**Comment by mystbrent** [comment]
+1

**Comment by mamrehn** [comment]
You might want to try this [tensorflow-gpu-v1.4-cuda-v9-cudnn-v7.whl](https://github.com/mind/wheels/releases/tag/tf1.4-gpu-cuda9) wheel as well as
```bash
sudo echo "/usr/local/cuda-9.0/lib64" >> /etc/ld.so.conf.d/cuda.conf
sudo ldconfig
```
as pointed out in the [nvidia forums](https://devtalk.nvidia.com/default/topic/845363/libcublas-so-7-0-cannot-open-shared-object-file/). Seems to work on an Ubuntu 16.04 machine.

**Comment by YoungGer** [comment]
+1

**Comment by stiebels** [comment]
+1

**Comment by mvrozanti** [comment]
+1

**Comment by drpngx** [comment]
@gunan FYI. Closing since @mamrehn appears to have posted a working resolution. We should fix this if possible.

**Comment by bfan1256** [comment]
Does this work with the new nightly builds? It doesn't seem to work with the `tf-nightly-gpu`

**Comment by mamrehn** [comment]
@bfan1256 At least it works with the latest tensorflow v1.4.1 ([tensorflow-gpu-v1.4.1-cuda-v9-cudnn-v7.whl](https://github.com/mind/wheels/releases/tag/tf1.4.1-gpu-cuda9)). I'm afraid you'd have to look into their compilation process and adopt it to the nightly version yourself to test it.

**Comment by arifoyong** [comment]
Tensorflow doesn't support Cuda 9.0 yet. 

Try to use Cuda-8.0 by updating the LD_LIBRARY_PATH with the following
sudo ldconfig /usr/local/cuda-8.0/lib64

**Comment by arifflexter** [comment]
+1 waiting for Cuda 9.0 support

**Comment by gunan** [comment]
Our nightlies are all built against cuda 9 now.
We do not have windows GPU nightlies yet, but if you build from master you can build and run TF with CUDA 9 on windows, too.

**Comment by amirse** [comment]
@gunan thanks! Works like a charm with nightly on cuda-9.1

**Comment by tremblerz** [comment]
Does supporting CUDA 9 also means removing support for CUDA 8? I am getting this error with the latest build
```
ImportError: Traceback (most recent call last):
  File "/home/abhishs8/Research/AdversarialAttacks/.env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/abhishs8/Research/AdversarialAttacks/.env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/abhishs8/Research/AdversarialAttacks/.env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/abhishs8/Research/AdversarialAttacks/.env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/abhishs8/Research/AdversarialAttacks/.env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```

**Comment by gunan** [comment]
For prebuilt binaries, yes. The latest prebuilt binaries only support cuda
9.0. If you need to use with cuda 8.0, you either need to use an old
version or build from source.

**Comment by sliute** [comment]
Had the exact same problem. But building from source with bazel as per [the official instructions](https://www.tensorflow.org/install/install_sources) works well. I now run TensorFlow 1.5 with CUDA 9.0 and cuDNN 7.0 on Ubuntu 17.10.

**Comment by urayoru113** [comment]
+1
I have same problem no matter what i install cuda-8.0 or cuda-9.1

**Comment by etasnadi** [comment]
With tensoflow-gpu (1.5.0) + cuda 9.0 + ubuntu 16.04 in virtualenv: the same error when importing tensorflow in the virtualenv's python3 interpreter. I think it is because it is not enough to set the LD_LIBRARY_PATH properly; You should run the `ldconfig` after installing the cuda toolkit. So I put the cuda lib path `/usr/local/cuda-9.0/lib64` (in my config) into the newly created file `/etc/ld.so.conf.d/cuda.conf` issued an `ldconfig` and now it works finally.

**Comment by estelleaf** [comment]
Hi there,
On my computer I had : 
- cudnn5.1
- cuda8.0
When importing tensorflow, I had the same error ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
To overcome this issue I installed tensorflow 1.4 instead of 1.6
But then I had another issue : libcudnn.so.6: cannot open shared object file: No such file or directory
This was because I had cudnn5.1 as required but actually it needs cudnn6
Here are the steps to uninstall cudnn5.1 and install cudnn6:

1- Uninstall cudnn 5.1
rm -f /usr/include/cudnn.h
rm -f /usr/lib/x86_64-linux-gnu/*libcudnn*
rm -f /usr/local/cuda-*/lib64/*libcudnn*
2- Install cudnn6
After having subscribed to nvdia, go to here https://developer.nvidia.com/rdp/cudnn-download and download cudnn6 for cuda8 and then go to the folder where you downloaded the cudnn and do : 
$ tar xvzf cudnn-8.0-linux-x64-v5.1-ga.tgz
$ sudo cp -P cuda/include/cudnn.h /usr/local/cuda/include
$ sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda/lib64
$ sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*

Now you should have tensorflow
Try it on typing in the console: 
$python
> import tensorflow


If you want to work in anaconda and the error persists , try :  
$jupyter notebook --generate-config

then you can find the name of the directory where you have your config file (Ill call it <dir>) and open <dir>/jupyter_notebook_config.py and add at the top : 

import os
c = get_config()
os.environ['LD_LIBRARY_PATH'] = '/usr/local/cuda-8.0/lib64:usr/local/cuda-8.0/lib64/libcudart.so.8.0'
c.Spawner.env.update('LD_LIBRARY_PATH')

Now it should work...


Here are the websites that helped me:

https://askubuntu.com/questions/952075/how-to-upgrade-tensorflow-to-v1-3-cudnn-cuda-upgrade
https://developer.nvidia.com/rdp/cudnn-download
https://medium.com/@ikekramer/installing-cuda-8-0-and-cudnn-5-1-on-ubuntu-16-04-6b9f284f6e77
https://stackoverflow.com/questions/43984135/tensorflow-gpu-can-not-be-called-from-jupyterhub-jupyter-notebook-why
