### ISSUE TITLE
TensorFlow Lite Android example doesn't compile with Bazel

### ISSUE THREAD

**Issue by bryant1410** [tensorflow/tensorflow#14664]
TensorFlow Lite Android example doesn't compile with Bazel, as explained in its README.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.10
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master (c0662f1620c2b97abb79b8ae6a8a30f7c7719475)
- **Python version**: 2.7.14
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: 7.2.0
- **CUDA/cuDNN version**: (not using cuda)
- **GPU model and memory**: (not using GPU)
- **Exact command to reproduce**: `bazel build --cxxopt='--std=c++11'   //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo`

### Describe the problem
When trying to compile the TF Lite Android demo with Bazel, it doesn't work, yielding:

```
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 16. The major revisions supported by Bazel are [10, 11, 12, 13, 14]. Defaulting to revision 14.
INFO: Analysed target //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/santiago/repos/tensorflow/tensorflow/contrib/lite/kernels/internal/BUILD:273:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels/internal:tensor_utils' failed (Exit 1)
In file included from tensorflow/contrib/lite/kernels/internal/tensor_utils.cc:24:
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/neon_tensor_utils.h:21:
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/cpu_check.h:21:
external/androidndk/ndk/sources/android/cpufeatures/cpu-features.h:31:10: fatal error: 'sys/cdefs.h' file not found
#include <sys/cdefs.h>
         ^~~~~~~~~~~~~
1 error generated.
Target //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 14.636s, Critical Path: 7.92s
FAILED: Build did NOT complete successfully
```

I have already tried installing all APT packages that contain a file named `sys/cdefs.h`, including `g{cc,++}-{5,6,7}-multilib`. NDK 16 is installed, along with LLDB 3.0 and cmake.

### Source code / logs
tf_env.txt:

```
== cat /etc/issue ===============================================
Linux s.local 4.13.0-16-lowlatency #19-Ubuntu SMP PREEMPT Wed Oct 11 19:51:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="17.10 (Artful Aardvark)"
VERSION_ID="17.10"
VERSION_CODENAME=artful

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 7.2.0-8ubuntu3) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== uname -a =====================================================
Linux s.local 4.13.0-16-lowlatency #19-Ubuntu SMP PREEMPT Wed Oct 11 19:51:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.13.3)

== check for virtualenv =========================================
True

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform

== env ==========================================================
LD_LIBRARY_PATH /home/santiago/torch/install/lib:/home/santiago/torch/install/lib:
DYLD_LIBRARY_PATH /home/santiago/torch/install/lib:/home/santiago/torch/install/lib:

== nvidia-smi ===================================================
/dev/fd/63: línea 105: nvidia-smi: orden no encontrada

== cuda libs  ===================================================
```

**Comment by rogerlzp** [comment]
I have met this error also.
Try different with NDK version,  get fatal error complaining different head file not found. 
#include <sys/xxx.h>
Any one have a look at this?

**Comment by lingbao00** [comment]
i am now trying to compile the demo by Android Studio,but i want to know how you get the libtensorflow_lite.so,the new source recompiled  just get libtensorflow_inference.so,but in this so file no model named org.tensorflow.lite.Interpreter,can anyone help me.

**Comment by angersson** [comment]
I'm running into this problem too on Docker (I'm the one who wrote the build instructions). @bryant1410, could you also post the contents of your `WORKSPACE` file?

The build has been working in our internal Bazel tests, so my initial assumption is that this is an environmental configuration issue of some kind.

**Comment by angersson** [comment]
I cloned HEAD on my work machine and successfully built the app:

```shell
git clone http://github.com/tensorflow/tensorflow /tmp/tf
cd /tmp/tf
vim WORKSPACE
./configure
bazel build //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --cxxopt='--std=c++11' --config=android_arm
```

Here's what WORKSPACE looks like:

```python
android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    build_tools_version = "26.0.1",
    path = "<my sdk path>",
)

android_ndk_repository(
    name = "androidndk",
    api_level = 14,
    path = "<my ndk path>",
)
```

And the output of `bazel version`:

```
Build label: 0.8.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Nov 27 13:19:39 2017 (1511788779)
Build timestamp: 1511788779
Build timestamp as int: 1511788779
```

So there's... some critical environmental difference going on.

**Comment by angersson** [comment]
This is ultimately caused by https://github.com/bazelbuild/bazel/issues/4068. NDK version 16 rearranged important includes, and Bazel doesn't support it yet.

You should be able to work around this by manually downloading NDK version 15, which you'll have to search around online for (the sdk manager doesn't let you download older versions). You can also try messing with [the NDK developer recommendations for build toolchain changes](https://android.googlesource.com/platform/ndk/+/ndk-release-r16/docs/UnifiedHeaders.md), which I haven't had time to experiment with.

**Comment by angersson** [comment]
Our official workaround at the moment is to download an older NDK and point to that instead. @bryant1410 , can you verify that works for you?

**Comment by bryant1410** [comment]
@angersson yes, that works. Thanks!

**Comment by vickey20** [comment]
Thanks @angersson, reverting to NDK v14 worked for me!
