### ISSUE TITLE
ImportError: libcudart.so.7.5: cannot open shared object file

### ISSUE THREAD

**Issue by chemelnucfin** [tensorflow/tensorflow#1501]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Fedora 23

If installed from sources, provide the commit hash:
b44a68232087284eccd55c6031e7fc3ebe5663ab

### Steps to reproduce
1.  ./configure with GPU support in /usr/local/cuda 
2.  build tests with --config=cuda option
3.

### What have you tried?
1.  building tests without --config=cuda has no problem
2.  made sure libcudart.so.7.5 exists in /usr/local/cuda/lib64 (as a soft link to libcudart.so.7.5.18)
3.  ./configure with /usr/local/cuda/lib64 (says file not found)

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
http://pastebin.com/xKrvzawQ

**Comment by moonboots** [comment]
You might be missing the [shell environment variables](https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#test-the-tensorflow-installation):
```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
export CUDA_HOME=/usr/local/cuda
```
These are used during runtime (versus compile time) cuda shared library lookup.

**Comment by chemelnucfin** [comment]
Thanks, I missed the CUDA_HOME variable, but I'm now getting this error.

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
\--------------------------------------------------------------
tensorflow/core/common_runtime_gpu_gpu_stream_util_test: error while loading shared libraries: libcudart.so.7.5: cannot open shared object file: No such file or directory

**Comment by chemelnucfin** [comment]
I also have /usr/local/cuda/lib64 in PYTHONPATH

**Comment by chemelnucfin** [comment]
New issue came up while trying to fix this.  Will open a new issue and close this.

**Comment by shkr** [comment]
Where is the new issue posted ?

**Comment by fpopic** [comment]
I was getting similar error: "ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory")

I just did @moonboots answer and restared my ubuntu 16.04 and everything has been working well.

http://www.deviantpics.com/images/2016/10/24/cuda%20radi.png

**Comment by cjfpainter** [comment]
I ran into it on Ubuntu14.04 trying to install Pycuda and I think Moonboots answer is correct; it worked for me, and I realise that the crucial point is about environment variables ( I mainly make executables ), 
These are used during runtime (versus compile time)

**Comment by chemelnucfin** [comment]
Just noticed this.  The new issue is #1701 and #2053 solved it.

**Comment by cjfpainter** [comment]
Hi there,Had similar trying to get PyCuda going, and took a suggestion from elsewhere to be careful about paths; I use Ubuntu, and this sort of did the trickexport LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"export CUDA_HOME=/usr/local/cudain bashrcI was using Nsight to compile, and forgot that it uses internal paths Hope that helps!-----chemelnucfin <notifications@github.com> wrote: -----To: tensorflow/tensorflow <tensorflow@noreply.github.com>From: chemelnucfin <notifications@github.com>Date: 02/07/2017 01:06AMCc: cjfpainter <chris.painter@zigzag.co.uk>, Comment <comment@noreply.github.com>Subject: Re: [tensorflow/tensorflow] ImportError: libcudart.so.7.5: cannot open shared object file (#1501)Just noticed this.  The new issue is #1701 and #2053 solved it.

**Comment by augustkx** [comment]
Hi, I am using Ubuntu14.04 with pycharm , but the  environment variables setting didn't work for me.

Weird is that I can run it in a terminal, but not in pycharm.

**Comment by eyildiz-ugoe** [comment]
Still experiencing the same on Ubuntu 16.04. Frustrating.

**Comment by liangliannie** [comment]
> Hi, I am using Ubuntu14.04 with pycharm , but the environment variables setting didn't work for me.
> 
> Weird is that I can run it in a terminal, but not in pycharm.

In pycharm, I tried to revise the path variable in run configuration. And it works.

**Comment by augustkx** [comment]
> > Hi, I am using Ubuntu14.04 with pycharm , but the environment variables setting didn't work for me.
> > Weird is that I can run it in a terminal, but not in pycharm.
> 
> In pycharm, I tried to revise the path variable in run configuration. And it works.
That's true. Thank you. I should also update earlier here. Sorry.
