### ISSUE TITLE
Error while using cuda-9.0, libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DrSajid** [tensorflow/tensorflow#15236]
Hi,

I just installed cuda-9.0
and done all the requirements for cuda to run tensorflow like libcudnn7_7.0.5.15-1+cuda9.0_amd64.deb, libcudnn7-dev_7.0.5.15-1+cuda9.0_amd64.deb.
The test example of libcudnn are working fine.

I installed tensorflow-gpu, it finished normally while using "$ sudo pip3 install tensorflow-gpu" but at the time of import, it gives me  error " 
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory"
Look like tensorflow doesn't support Cuda-9.0?

Error is as follows:

$ ipython
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow as tf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/usr/lib/python3.5/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

/usr/lib/python3.5/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-64156d691fe5> in <module>()
----> 1 import tensorflow as tf

/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     73 
     74 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug or a feature request.
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: No use pip install tensorflow
- **TensorFlow version (use command below)**: tensorflow_gpu-1.4.1-cp35-cp35m-manylinux1_x86_64.whl 
- **Python version**:  Python 3.5.2 (default, Nov 23 2017, 16:37:01)
- **Bazel version (if compiling from source)**:No
- **GCC/Compiler version (if compiling from source)**: No
- **CUDA/cuDNN version**:  cuda-9.0
- **GPU model and memory**: GeForce GT 750M
- **Exact command to reproduce**: No just import tensorflow as tf
                                                         
You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by drpngx** [comment]
You are missing that shared library. Can you run `ldconfig -v` to see which one you have? I have seen another report where the cublas `9.0` was installed.

**Comment by DrSajid** [comment]
Hi,
It look like its there,

ldconfig -v 
/sbin/ldconfig.real: Can't stat /lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Path `/usr/lib/nvidia-384' given more than once
/sbin/ldconfig.real: Path `/usr/lib32/nvidia-384' given more than once
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/usr/local/cuda-8.0/targets/x86_64-linux/lib:
/sbin/ldconfig.real: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5 is not a symbolic link

	libcudnn.so.5 -> libcudnn.so.5.0.5
/usr/local/cuda-9.0/targets/x86_64-linux/lib:
	libnppitc.so.9.0 -> libnppitc.so.9.0.176
	libcublas.so.9.0 -> libcublas.so.9.0.176
	libOpenCL.so.1 -> libOpenCL.so.1.0.0
	libcufftw.so.9.0 -> libcufftw.so.9.0.176
	libnppicom.so.9.0 -> libnppicom.so.9.0.176
	libcusolver.so.9.0 -> libcusolver.so.9.0.176
	libnppicc.so.9.0 -> libnppicc.so.9.0.176
	libnppial.so.9.0 -> libnppial.so.9.0.176
	libnppidei.so.9.0 -> libnppidei.so.9.0.176
	libnppig.so.9.0 -> libnppig.so.9.0.176
	libnvblas.so.9.0 -> libnvblas.so.9.0.176
	libnvrtc.so.9.0 -> libnvrtc.so.9.0.176
	libnvrtc-builtins.so.9.0 -> libnvrtc-builtins.so.9.0.176
	libnppist.so.9.0 -> libnppist.so.9.0.176
	libnppisu.so.9.0 -> libnppisu.so.9.0.176
	libcurand.so.9.0 -> libcurand.so.9.0.176
	libnvgraph.so.9.0 -> libnvgraph.so.9.0.176
	libnpps.so.9.0 -> libnpps.so.9.0.176
	libnppc.so.9.0 -> libnppc.so.9.0.176
	libcudart.so.9.0 -> libcudart.so.9.0.176
...
...

**Comment by drpngx** [comment]
Yeah, it looks like you have `9.0`, not `8.0` that the software is looking for. Please install `8.0` for now.

**Comment by DrSajid** [comment]
Well i found a solution by installation through source code.
in git log file(b43d0f3) " git log --oneline --decorate"

(HEAD -> master, origin/master, origin/HEAD) Merge pull request #15233 from ManHyuk/typo
70644fc fix typo
688bc53 Merge pull request #15225 from Androbin/patch-1
8267844 Enable GCS filesystem for Windows (#14856)
d3e35f9 Also install libssl-dev to make pip/py3.6 work properly. (#15226)
c470142 Update .gitignore
3a05c11 Merge pull request #15195 from rongjiecomputer/wav
0e49c54 Merge pull request #15021 from freedomtan/bmp-doc
774f4d3 Merge pull request #15205 from tensorflow/gunan-patch-1
cae2e56 Delete Dockerfile.devel-gpu-cuda9-cudnn7
b43d0f3 **Upgrade cuda to 9 and cudnn version to 7. (#14773)**
f7d392d Merge pull request #15197 from caisq/nomac-tag
28b92cd Fix tag in source_remote_test: no_mac --> nomac

Than I fallowed the instructions mentioned at 
https://gist.github.com/Brainiarc7/6d6c3f23ea057775b72c52817759b25c

And done (for python2.7!)

$ ipython2
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tensorflow as tf

In [2]: sess = tf.Session()
2017-12-10 13:28:46.568828: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-10 13:28:46.569233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1062] Found device 0 with properties: 
name: GeForce GT 750M major: 3 minor: 0 memoryClockRate(GHz): 0.967
pciBusID: 0000:04:00.0
totalMemory: 1.95GiB freeMemory: 1.72GiB
2017-12-10 13:28:46.569263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1152] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GT 750M, pci bus id: 0000:04:00.0, compute capability: 3.0)

**Comment by drpngx** [comment]
Great!

**Comment by Prajwal1997** [comment]
Hi,
I am also having the similar problem. I installed cuda 9.1 and set the path as suggested https://stackoverflow.com/questions/36159194/tensorflow-libcudart-so-7-5-cannot-open-shared-object-file-no-such-file-or-di
Should i install cuda 8.0 for resolving this problem?
The error is:

>>> import tensorflow
Traceback (most recent call last):
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/honeypot/tensorflow/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/honeypot/tensorflow/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/honeypot/tensorflow/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/honeypot/tensorflow/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by muthukumaranR** [comment]
Hi, had the same issue. fixed it by verifying if libcublas.so.8.0 is present is $LD_LIBRARY_PATH. in my case, it was in /usr/local/cuda/lib64 instead of /usr/local/cuda/lib.

**Comment by Connor323** [comment]
Hi all, I had the same issue as @Prajwal1997. My setting is cuda-9.1 with cudnn 7.0. I wonder if there is a way to set TF looking for the right version of cuda, instead of installing cuda 8.0? Thanks!

**Comment by VeLKerr** [comment]
Hi all, 
I have the similar problem. I have CUDA 8.0.61 with CudNN 5.1.10 but Tensorflow is searching CUDA 9:
```ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory```
How I can make Tensorflow understand that I'm using CUDA 8?

**Comment by drpngx** [comment]
@VeLKerr this is not a configurable setting. You have to use a different version of tensorflow.

**Comment by VeLKerr** [comment]
Ok, what version is compatible with CUDA 8.0.61? I'm using the last Tensorflow version (1.5.0).

**Comment by VeLKerr** [comment]
Ok, I've installed Tensorflow 1.0.1 and it is working correctly!

**Comment by drpngx** [comment]
Woohoo!

**Comment by bringtree** [comment]
i meet the same question
 .libcublas.so.9.0: cannot open shared object file: No such file or directory

i use cuda9.0

**Comment by VeLKerr** [comment]
Looks like you have an incorrect `LD_LIBRARY_PATH`. Try to set the following values:
```
export PATH=/usr/local/cuda-8.0/bin:${PATH}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

**Comment by lechatthecat** [comment]
Try this:
$ sudo ldconfig /usr/local/cuda/lib64

**Comment by arch-rh1** [comment]
I have **Cuda 9.0 , cudnn 7.0** on Ubuntu 16.04.
I built **Tensorflow 1.6** since the release notes states it has pre-compiled binaries for cuda 9.0 and cudnn 7.0.

ldconfig -v: **libcublas.so.9.0**

upon running: 
import tensorflow as tf
I still get the error: 
`ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory`

My Questions:
1. Shouldn't Tensorflow 1.6 work with cuda 9.0/ cudnn 7.0 ? 
2. Is there any way I can **continue using cuda 9.0** ?? I really cannot use 8.0


**Complete Error:** 
> 
> >>> import tensorflow
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/archana/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "/home/archana/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/home/archana/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/home/archana/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/home/archana/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/home/archana/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
> 
> 
> Failed to load the native TensorFlow runtime.
>

**Comment by shrikant10** [comment]
I am using CUDA 9.2 and cudnn 7.1

the error on importing tensorflow says:

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

What should I do?

**Comment by lechatthecat** [comment]
@shrikant10
The error message seems like it is trying to use Cuda 9.0. 
Check what version of Cuda is needed for your tensorflow version.
According to the error message, you need Cuda9.0, so use Cuda 9.0. (Not 9.2).

**Comment by PanagiotisPtr** [comment]
@DrSajid I know this is a closed issue but here is what worked for me:
I was using zsh(oh-my-zsh specifically) instead of bash for my temrinal and, although the lib64 path was set for bash, it wouldn't work for zsh.

Try ``exec bash`` on terminal to switch to bash and try again.
