### ISSUE TITLE
Cannot import tensorflow after installing tensorflow-gpu - Windows

### ISSUE THREAD

**Issue by PeskyWabbit** [tensorflow/tensorflow#15319]
I am running windows 10 64bit. 
Tensorflow-gpu version - 1.4.0
CUDA version - 8.0
cuDNN - v6.0

I installed it using the cmd command: `pip install tensorflow-gpu ` and do not have any other version of tensorflow installed. now when I try to execute 

```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```
I get the error `ModuleNotFoundError: No module named 'tensorflow'`

I am hoping getting this working will solve my bigger issue of tensorflow not recognizing my gpu for gpu processing.

**Comment by Carmezim** [comment]
Are you able to run this simple example?
```
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
```

**Comment by PeskyWabbit** [comment]
I was able to get it to work now by installing tensorflow-gpu through pycharms package installer rather than via pip. Closing!

**Comment by harzival** [comment]
This isn't a fix it's a bodge workaround, can we get this fixed?
