### ISSUE TITLE
tensorflow-gpu not working with pycharm

### ISSUE THREAD

**Issue by Omegasad** [tensorflow/tensorflow#15435]
I am trying to get the tensorflow-gpu working on pycharm but it doesn't compile. When I compile it, it gives me the following compile error

> ImportError: Could not find 'cudart64_80.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 8.0 from this URL:

I am using Pycharm with the Python 3.6 venv and I am pretty sure I have CUDA 8.0 installed. When I check the directory of CUDA\v8.0\bin, it shows the cudart64_80.dll 

It works perfectly on the CPU version but I want it working on the GPU side

**Comment by snnn** [comment]
Is it in your PATH?
Please run
```bat
echo %PATH%
```

**Comment by Omegasad** [comment]
Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Tori>echo %PATH%
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_25\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\Git\cmd;D:\Python27;D:\Python27\Scripts;D:\protobuf;C:\Program Files (x86)\nodejs\;F:\Python\Python36\Scripts\;F:\Python\Python36\;C:\Users\Tori\AppData\Local\Microsoft\WindowsApps;C:\Users\Tori\AppData\Roaming\npm;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;

Is this what you're looking for?

**Comment by snnn** [comment]
You have 2 Python here. How does it work?

**Comment by Omegasad** [comment]
One of it is python 2.7 and the other one is 3.6
I deleted the python 2.7 though and only have the 3.6 at the moment

**Comment by snnn** [comment]
Can you run your code directly on command line, without PyCharm?  Is your problem specific to PyCharm or not?

**Comment by Omegasad** [comment]
It is specific to pycharm. I don't think I have tensorflow working on command line but I am planning on working with pycharm only

**Comment by bignamehyp** [comment]
This is a pycharm specific issue, it's not a tensorflow library bug. This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). There is also a larger community that reads questions there. Thanks!

**Comment by amir-zeldes** [comment]
I can confirm the same observation: command line usage works fine, but in PyCharm I get:

```
 File "C:\Python35\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_80.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 8.0 from this URL: https://developer.nvidia.com/cuda-toolkit
```

PATH includes CUDA directories bin, lib/x64 and extras/CUPTI/libx64. I noticed the file cudart64_80.dll does in fact exist in <CUDA>/bin, not sure what is causing this.

**Comment by amir-zeldes** [comment]
OK, it took two restarts and now I can't reproduce the bug... Not sure what happened. I should point out that I had attempted to upgrade to cuda 9 before this happened, discovered that it wasn't supported under Windows, downgraded to TF1.4, and after uninstalling cuda and reinstalling v8, this bug happened, and persisted after one restart, despite everything being in path. I also restarted PyCharm a bunch of times, so it seems that's not enough.

Now I rebooted again and everything is just working in PyCharm and CLI... Sorry for the confusion!

**Comment by derluke** [comment]
Had the same issue here - adding LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64/ to the pycharm environment did the trick

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
Closing since it appears to be resolved.
