### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yangfengKAUST** [tensorflow/tensorflow#15817]
I met the same problem as ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory , https://github.com/tensorflow/tensorflow/issues/15604 , but non of their methods work.

**Comment by IronWolve** [comment]
Same issue, but its because I have 9.1 installed and 9.0 is the version supported in tf-nightly.   Was hoping tf-nightly would include 9.1 support.

**Comment by gunan** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by JSANJ** [comment]
@KeithAymar I have tried to use that command but I get the following error:

>Reading package lists... Done
>Building dependency tree       
>Reading state information... Done
>E: Unable to locate package cuda-9-0

Could you please advise what to do? Thanks in advance!

**Comment by KeithAymar** [comment]
I don’t know for sure.  I’m an a noob with this.  Took me a few days to get things working.  Anytime something doesn’t work quite right I make sure to do before running any install commands.  

sudo apt-get update 

Sounds like you don’t have the packages set up for install. 

These are the instructions I followed when I installed 9.1.  Be sure all the prerequisites are complete.  I am using a minimal install of Lubuntu.   But there are instructions for other flavors.  

http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation

**Comment by ricoms** [comment]
I use Ubuntu 1604, I installed cuda 9.1 following the instructions here: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation

When importing tensorflow happened the same problem as OP.

I used the command:
```sh
sudo apt-get install cuda-9-0
```
And it solved my issue, I now finally have tensorflow-gpu running

Thanks @KeithAymar
