### ISSUE TITLE
Numerous ::`anonymous namespace':: Linking errors in Tensorflow 1.3.1 Windows build with GPU

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#15840]
Building with VS 2015 64bit and CUDA 8 and Cudnn v7 (cudnn64_7.dll).

All other projects in the solution got built. Even the project pywrap_tensorflow_internal_static got built. But, when building the project pywrap_tensorflow_internal for the dll one, it compiles successfully but gives numerous linking errors as below:

I also see that (probably) all of them contain the anonymous namespace - ``class tensorflow::`anonymous namespace'::``.

```
1>pywrap_tensorflow_internal.exp : warning LNK4070: /OUT:_pywrap_tensorflow_internal.pyd directive in .EXP differs from output filename 'D:\rough\tensorflow-1.3.1\tensorflow\contrib\cmake\build\Release\pywrap_tensorflow_internal.dll'; ignoring directive
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: void __cdecl tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16>::Initialize<1>(class Eigen::TensorMap<class Eigen::Tensor<struct tensorflow::bfloat16 const ,2,1,__int64>,16,struct Eigen::MakePointer> const &,int)'::`2'::$TSS0" (?$TSS0@?1???$Initialize@$00@?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@QEAAXAEBV?$TensorMap@V?$Tensor@$$CBUbfloat16@tensorflow@@$01$00_J@Eigen@@$0BA@UMakePointer@2@@Eigen@@H@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: void __cdecl tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16>::Initialize<0>(class Eigen::TensorMap<class Eigen::Tensor<struct tensorflow::bfloat16 const ,2,1,__int64>,16,struct Eigen::MakePointer> const &,int)'::`2'::$TSS0" (?$TSS0@?1???$Initialize@$0A@@?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@QEAAXAEBV?$TensorMap@V?$Tensor@$$CBUbfloat16@tensorflow@@$01$00_J@Eigen@@$0BA@UMakePointer@2@@Eigen@@H@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "TSS0<`template-parameter-2',tensorflow::`anonymous namespace'::M::cale_independent_strtonum,cointerface ?? :: ?? ::HA::tensorflow::Z::AMPEBDPEAPEBD>" (?$TSS0@?1???$locale_independent_strtonum@M@?A0x77a2fbcf@tensorflow@@YAMPEBDPEAPEBD@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "TSS0<`template-parameter-2',tensorflow::`anonymous namespace'::N::cale_independent_strtonum,cointerface ?? :: ?? ::HA::tensorflow::Z::ANPEBDPEAPEBD>" (?$TSS0@?1???$locale_independent_strtonum@N@?A0x77a2fbcf@tensorflow@@YANPEBDPEAPEBD@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `private: static void __cdecl tensorflow::SparseMatMul<float,float>::ComputeOutputBlock(class std::vector<struct tensorflow::`anonymous namespace'::SparseSlice<float> *,class std::allocator<struct tensorflow::`anonymous namespace'::SparseSlice<float> *> > const &,class Eigen::TensorMap<class Eigen::Tensor<float const ,2,1,__int64>,16,struct Eigen::MakePointer> const &,int,int,int,bool,bool,class Eigen::TensorMap<class Eigen::Tensor<float,2,1,__int64>,16,struct Eigen::MakePointer> *)'::`2'::$TSS0" (?$TSS0@?1??ComputeOutputBlock@?$SparseMatMul@MM@tensorflow@@CAXAEBV?$vector@PEAU?$SparseSlice@M@?A0x20ed32c2@tensorflow@@V?$allocator@PEAU?$SparseSlice@M@?A0x20ed32c2@tensorflow@@@std@@@std@@AEBV?$TensorMap@V?$Tensor@$$CBM$01$00_J@Eigen@@$0BA@UMakePointer@2@@Eigen@@HHH_N2PEAV?$TensorMap@V?$Tensor@M$01$00_J@Eigen@@$0BA@UMakePointer@2@@7@@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `private: static void __cdecl tensorflow::SparseMatMul<float,struct tensorflow::bfloat16>::ComputeOutputBlock(class std::vector<struct tensorflow::`anonymous namespace'::SparseSlice<float> *,class std::allocator<struct tensorflow::`anonymous namespace'::SparseSlice<float> *> > const &,class Eigen::TensorMap<class Eigen::Tensor<struct tensorflow::bfloat16 const ,2,1,__int64>,16,struct Eigen::MakePointer> const &,int,int,int,bool,bool,class Eigen::TensorMap<class Eigen::Tensor<float,2,1,__int64>,16,struct Eigen::MakePointer> *)'::`2'::$TSS0" (?$TSS0@?1??ComputeOutputBlock@?$SparseMatMul@MUbfloat16@tensorflow@@@tensorflow@@CAXAEBV?$vector@PEAU?$SparseSlice@M@?A0x20ed32c2@tensorflow@@V?$allocator@PEAU?$SparseSlice@M@?A0x20ed32c2@tensorflow@@@std@@@std@@AEBV?$TensorMap@V?$Tensor@$$CBUbfloat16@tensorflow@@$01$00_J@Eigen@@$0BA@UMakePointer@2@@Eigen@@HHH_N2PEAV?$TensorMap@V?$Tensor@M$01$00_J@Eigen@@$0BA@UMakePointer@2@@7@@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `private: static void __cdecl tensorflow::SparseMatMul<struct tensorflow::bfloat16,float>::ComputeOutputBlock(class std::vector<struct tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16> *,class std::allocator<struct tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16> *> > const &,class Eigen::TensorMap<class Eigen::Tensor<float const ,2,1,__int64>,16,struct Eigen::MakePointer> const &,int,int,int,bool,bool,class Eigen::TensorMap<class Eigen::Tensor<float,2,1,__int64>,16,struct Eigen::MakePointer> *)'::`2'::$TSS0" (?$TSS0@?1??ComputeOutputBlock@?$SparseMatMul@Ubfloat16@tensorflow@@M@tensorflow@@CAXAEBV?$vector@PEAU?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@V?$allocator@PEAU?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@@std@@@std@@AEBV?$TensorMap@V?$Tensor@$$CBM$01$00_J@Eigen@@$0BA@UMakePointer@2@@Eigen@@HHH_N2PEAV?$TensorMap@V?$Tensor@M$01$00_J@Eigen@@$0BA@UMakePointer@2@@7@@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `private: static void __cdecl tensorflow::SparseMatMul<struct tensorflow::bfloat16,struct tensorflow::bfloat16>::ComputeOutputBlock(class std::vector<struct tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16> *,class std::allocator<struct tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16> *> > const &,class Eigen::TensorMap<class Eigen::Tensor<struct tensorflow::bfloat16 const ,2,1,__int64>,16,struct Eigen::MakePointer> const &,int,int,int,bool,bool,class Eigen::TensorMap<class Eigen::Tensor<float,2,1,__int64>,16,struct Eigen::MakePointer> *)'::`2'::$TSS0" (?$TSS0@?1??ComputeOutputBlock@?$SparseMatMul@Ubfloat16@tensorflow@@U12@@tensorflow@@CAXAEBV?$vector@PEAU?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@V?$allocator@PEAU?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@@std@@@std@@AEBV?$TensorMap@V?$Tensor@$$CBUbfloat16@tensorflow@@$01$00_J@Eigen@@$0BA@UMakePointer@2@@Eigen@@HHH_N2PEAV?$TensorMap@V?$Tensor@M$01$00_J@Eigen@@$0BA@UMakePointer@2@@7@@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `bool __cdecl tensorflow::`anonymous namespace'::IsGradientNode(class tensorflow::Graph const *,class tensorflow::Node const *)'::`2'::$TSS0" (?$TSS0@?1??IsGradientNode@?A0xd76da148@tensorflow@@YA_NPEBVGraph@3@PEBVNode@3@@Z@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<signed char>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@C@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<unsigned char>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@E@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<short>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@F@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<int>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@H@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<float>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@M@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<double>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@N@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<struct Eigen::QInt16>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@UQInt16@Eigen@@@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<struct Eigen::QInt32>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@UQInt32@Eigen@@@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<struct Eigen::QInt8>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@UQInt8@Eigen@@@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<struct Eigen::QUInt16>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@UQUInt16@Eigen@@@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<struct Eigen::QUInt8>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@UQUInt8@Eigen@@@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<struct Eigen::half>::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@Uhalf@Eigen@@@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "int `public: virtual class tensorflow::gtl::InlinedVector<enum tensorflow::DataType,4> const & __cdecl tensorflow::`anonymous namespace'::DenseToSparseBatchDatasetOp::Dataset<class std::complex<float> >::output_dtypes(void)const '::`2'::$TSS0" (?$TSS0@?1??output_dtypes@?$Dataset@V?$complex@M@std@@@DenseToSparseBatchDatasetOp@?A0x0fde61d7@tensorflow@@UEBAAEBV?$InlinedVector@W4DataType@tensorflow@@$03@gtl@5@XZ@4HA)
...
...
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "class Eigen::array<int,2> const `private: static void __cdecl tensorflow::SparseMatMul<struct tensorflow::bfloat16,float>::ComputeOutputBlock(class std::vector<struct tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16> *,class std::allocator<struct tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16> *> > const &,class Eigen::TensorMap<class Eigen::Tensor<float const ,2,1,__int64>,16,struct Eigen::MakePointer> const &,int,int,int,bool,bool,class Eigen::TensorMap<class Eigen::Tensor<float,2,1,__int64>,16,struct Eigen::MakePointer> *)'::`26'::zero" (?zero@?BK@??ComputeOutputBlock@?$SparseMatMul@Ubfloat16@tensorflow@@M@tensorflow@@CAXAEBV?$vector@PEAU?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@V?$allocator@PEAU?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@@std@@@std@@AEBV?$TensorMap@V?$Tensor@$$CBM$01$00_J@Eigen@@$0BA@UMakePointer@2@@Eigen@@HHH_N2PEAV?$TensorMap@V?$Tensor@M$01$00_J@Eigen@@$0BA@UMakePointer@2@@7@@Z@4V?$array@H$01@7@B)
1>pywrap_tensorflow_internal.exp : error LNK2001: unresolved external symbol "class Eigen::array<int,2> const `private: static void __cdecl tensorflow::SparseMatMul<struct tensorflow::bfloat16,struct tensorflow::bfloat16>::ComputeOutputBlock(class std::vector<struct tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16> *,class std::allocator<struct tensorflow::`anonymous namespace'::SparseSlice<struct tensorflow::bfloat16> *> > const &,class Eigen::TensorMap<class Eigen::Tensor<struct tensorflow::bfloat16 const ,2,1,__int64>,16,struct Eigen::MakePointer> const &,int,int,int,bool,bool,class Eigen::TensorMap<class Eigen::Tensor<float,2,1,__int64>,16,struct Eigen::MakePointer> *)'::`26'::zero" (?zero@?BK@??ComputeOutputBlock@?$SparseMatMul@Ubfloat16@tensorflow@@U12@@tensorflow@@CAXAEBV?$vector@PEAU?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@V?$allocator@PEAU?$SparseSlice@Ubfloat16@tensorflow@@@?A0x20ed32c2@tensorflow@@@std@@@std@@AEBV?$TensorMap@V?$Tensor@$$CBUbfloat16@tensorflow@@$01$00_J@Eigen@@$0BA@UMakePointer@2@@Eigen@@HHH_N2PEAV?$TensorMap@V?$Tensor@M$01$00_J@Eigen@@$0BA@UMakePointer@2@@7@@Z@4V?$array@H$01@7@B)
1>D:\rough\tensorflow-1.3.1\tensorflow\contrib\cmake\build\Release\pywrap_tensorflow_internal.dll : fatal error LNK1120: 1937 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```
By any chance, does anyone know what these errors are hinting towards?

Thanks in advance.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rumanQu** [comment]
@tensorflowbutler: This is regarding the build process from sources only. I was building Tensorflow version 1.3.1 on Win 7 64bit with CUDA 8.0 and CuDNN 7 using Visual Studio 2015. 

I used Cmake-gui with GPU enabled and all other default-set e.g. gRPC enabled, etc.
 
I found that the problem was in the VS project "**pywrap_tensorflow_internal**".  When I was building this particular project, there was a "**pywrap_tensorflow_internal.def**" definition file (which I didn't notice from where it was created) in the 'cmake-build' folder that was being used to generate the DLL file "**pywrap_tensorflow_internal.dll**".  However, it seemed to me that there were these extra (maybe erroneous) function names in the .def file that were actually not present in the intermediate ".lib" file generated by this project. And thus the above unresolved linking errors.

What I later went on doing is the following:
-  I simply deleted this definition file "**pywrap_tensorflow_internal.def**"  and also remjoved from the VS project configuration that was originally present as 
<Link>
<ModuleDefinitionFile>path/tensorflow-1.3.1/tensorflow/contrib/cmake/build/pywrap_tensorflow.def</ModuleDefinitionFile>
</Link>.
(Had I known how this  .def was generated, I would have regenerated it and tested without this manual modification of the project configuration.)

However, after this only, it successfully exported the functions into the final DLL file "**pywrap_tensorflow_internal.dll**".

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by mrry** [comment]
I'm guessing this occurred when you tried to build that library in a directory that contained artifacts from a previous build, perhaps based on a different version of the source.

We only maintain the CMake build in a state where it can build from a clean repository (as part of the CI and release processes), and this is intended to be a temporary state of affairs until we can switch to using Bazel. I'd recommend cleaning out your build directory before each build, to avoid this kind of issue.

We'd welcome contributions to improve the CMake build so that it doesn't fail in other scenarios, which I expect would involve changes to this part of the build script:

https://github.com/tensorflow/tensorflow/blob/926fc13f7378d14fa7980963c4fe774e5922e336/tensorflow/contrib/cmake/tf_python.cmake#L544-L557

/cc @guschmue in case you have an idea about how to regenerate the `.def` file at the appropriate time, or know another workaround for this problem.
/cc @ewilderj FYI, another CMake issue that might be relevant to the tf-distribute SIG.

**Comment by rthadur** [comment]
Contrib has been deprecated please refer to tensorflow/addons for latest updates.
