### ISSUE TITLE
Error while using cuda-9.1, libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Prajwal1997** [tensorflow/tensorflow#16136]
Hi,
I am having the import problem. I installed cuda 9.1 and set the path as suggested https://stackoverflow.com/questions/36159194/tensorflow-libcudart-so-7-5-cannot-open-shared-object-file-no-such-file-or-di
Should i install cuda 8.0 for resolving this problem?
Issue :tensorflow not supporting cuda version greater than 8.

The error is:

            import tensorflow
            Traceback (most recent call last):
            File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in
            from tensorflow.python.pywrap_tensorflow_internal import *
            File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in
            _pywrap_tensorflow_internal = swig_import_helper()
            File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
            _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
            File "/home/honeypot/tensorflow/lib/python3.5/imp.py", line 242, in load_module
            return load_dynamic(name, filename, file)
            File "/home/honeypot/tensorflow/lib/python3.5/imp.py", line 342, in load_dynamic
            return _load(spec)
            ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in
File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/init.py", line 24, in
from tensorflow.python import *
File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/init.py", line 49, in
from tensorflow.python import pywrap_tensorflow
File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in
from tensorflow.python.pywrap_tensorflow_internal import *
File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in
_pywrap_tensorflow_internal = swig_import_helper()
File "/home/honeypot/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "/home/honeypot/tensorflow/lib/python3.5/imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "/home/honeypot/tensorflow/lib/python3.5/imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Prajwal1997** [comment]
Where is the issue template?I have updated the comment and written the issue.

**Comment by junyanwu** [comment]
@Prajwal1997 
He means
> Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

To solve this problem(ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory), you can try
```
sudo vim /etc/profile
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
source /etc/profile
```
If you haven't install cuda8, install it

**Comment by Prajwal1997** [comment]
I have already added the relevant path as you mentioned and installed cuda 9. Does tensorflow support cuda 9? It looks like tensorflow doesn't support cuda 9!

**Comment by l0o0** [comment]
I have the same problems. I have added `/usr/local/cuda/lib64` to `$LD_LIBRARY_PATH`. The same import error message pops up when I `import tensorflow`.   
After I make a soft link`sudo ln -s libcublas.so.9.0 libcublas.so.8.0`, Another ImportError message:
>ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory   

So I try to make a softlink for all `*.9.0`
```bash
for i in $(ls *9.0)
do
echo $i
sudo ln -s $PWD/$i $PWD/${i/9.0/8.0}
done
```
After that , ImportError comes again
>ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

I solved the problem by the same way`sudo ln -s libcudnn.so.7 libcudnn.so.6`.  At last, I can import tensorflow without any error message. 

But when I try to run the code below in hello.py:
```python
import tensorflow as tf

hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)
```
It collapsed with the following message:
```
2018-01-17 17:01:19.184972: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-17 17:01:19.256650: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-17 17:01:19.256927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 750 Ti major: 5 minor: 0 memoryClockRate(GHz): 1.0845
pciBusID: 0000:01:00.0
totalMemory: 1.95GiB freeMemory: 1.45GiB
2018-01-17 17:01:19.256955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0, compute capability: 5.0)
*** stack smashing detected ***: <unknown> terminated
[1]    31692 abort (core dumped)  python hello.py
```

I think tensorflow is not compatible with CUDA 9.

Some helpful info:
Ubuntu 17.10, Python 2.7.14, conda 4.3.29, gcc (Ubuntu 6.4.0-8ubuntu1) 6.4.0 20171010, tensorflow-gpu==1.4.0
```
(tf) ➜  ~ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
Install cudnn by downloading cudnn-9.0-linux-x64-v7.tgz.

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by bringtree** [comment]
```
>>> import tensorflow
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by drpngx** [comment]
Yes, we have upgraded to `cuda9` at version `1.5.0` if memory serves. It looks like you have an issue with your CUDA installation. Please try to re-install.

**Comment by bringtree** [comment]
@drpngx 
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
```
it can be solved .

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
@bringtree yes, that works if it's there. Closing since it's an issue with the so location in most cases.

**Comment by Prajwal1997** [comment]
yes the path was an issue and it was solved.Thanks anyways @drpngx

**Comment by GhostEV** [comment]
> @Prajwal1997
> He means
> 
> > Have I written custom code
> > OS Platform and Distribution
> > TensorFlow installed from
> > TensorFlow version
> > Bazel version
> > CUDA/cuDNN version
> > GPU model and memory
> > Exact command to reproduce
> 
> To solve this problem(ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory), you can try
> 
> ```
> sudo vim /etc/profile
> export PATH=/usr/local/cuda/bin:$PATH
> export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
> source /etc/profile
> ```
> If you haven't install cuda8, install it

oh,it works~lol
