### ISSUE TITLE
Failed to Create Session: CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by b1ueshad0w** [tensorflow/tensorflow#16174]
Failed to create session:
```
import tensorflow as tf
tf.Session()
```
Error info:
E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_UNKNOWN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/envs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1482, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/ubuntu/envs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 622, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/ubuntu/envs/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: tensorflow-gpu ('v1.4.0-19-ga52c8d9', '1.4.1')
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8.0, cuDNN 6.0
- **GPU model and memory**: Tesla M40 24GB
- **Exact command to reproduce**: N/A

**Comment by qmick** [comment]
Seems like the issue https://github.com/NVIDIA/nvidia-docker/issues/262. Take a look if that can help.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by b1ueshad0w** [comment]
Turns out to be the driver's issue. I have sent it to NVIDIA and they are solving it.

**Comment by rhdong** [comment]
Hi ，@b1ueshad0w ， Has NVIDIA solved this issue？Thanks.
