### ISSUE TITLE
Does 1.5.0 not suppurt CUDA 9.1? It worked with CUDA 9.0 but not 9.1

### ISSUE THREAD

**Issue by tutan0558** [tensorflow/tensorflow#16479]
I installed 1.5.0, and tying to import tensorflow, but it said that 'cannot find cudart64_90.dll'. 
Then I installed the CUDA 9.0, and then everything works fine. 
So I want to make sure than does 1.5.0 not support CUDA 9.1 or I have something installed wrong?

**Comment by ppwwyyxx** [comment]
See the release notes: https://github.com/tensorflow/tensorflow/releases/tag/v1.5.0

TF 1.5.0 supports CUDA 9.1.
TF 1.5.0 prebuilt binaries only supports CUDA 9.0.

**Comment by zhiruiwang** [comment]
@ppwwyyxx Is installation from PyPI prebuilt binaries? I installed TF from PyPI and it shows the 'cannot find cudart64_90.dll' error. How to install TF 1.5.0 that is not prebuilt binaries? Thanks!

**Comment by ChandlerrLi** [comment]
Same problem, hope meaningful answers

**Comment by MikulasZelinka** [comment]
@zhiruiwang Yes, PyPI contains prebuilt binaries, meaning as of now there's only the version with CUDA 9.0 support.

You can build tensorflow by yourself: https://www.tensorflow.org/install/install_sources.

However, if you're on Windows, it's not officially supported and it's not straightforward. For tensorflow 1.4.0, I found these [binaries with CUDA 9.1](https://github.com/fo40225/tensorflow-windows-wheel) but it hasn't been updated for 1.5.0 yet.

**Comment by richardmark** [comment]
Easier just to go to https://developer.nvidia.com/cuda-90-download-archive and install CUDA 9.0 instead of current default install of CUDA 9.1

**Comment by yongtang** [comment]
From the Dockerfile that TensorFlow builds against:
https://github.com/tensorflow/tensorflow/blob/v1.5.0/tensorflow/tools/ci_build/Dockerfile.gpu

and by tracing to the related docker images, it looks like Tensorflow 1.5.0 is built with:
```
CUDA_VERSION 9.0.176
CUDNN_VERSION 7.0.5.15
```

I think it makes sense to update the docs for CUDA/CUDNN install version.

Created a PR #16495 for version update.

**Comment by joelandplus** [comment]
@richardmark Following instructions to install Cuda 9.0 on Ubuntu (apt-get) doesn't work, it will still install 9.1.

**Comment by rubenlg** [comment]
It works for me, but you have to specify the version so that it won't pick 9.1 automatically. Steps:
1. `apt-cache show cuda | grep Version`
2. Write down the full 9.0.? version
3. `apt-get install cuda=FULL-VERSION-CODE`

Also, make sure to run `apt-get update` before any of this, after you download the installer for 9.0.

**Comment by joelandplus** [comment]
@rubenlg i followed the instructions on NVIDIA website:

wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.0.176-1_amd64.deb
dpkg -i cuda-repo-ubuntu1604_9.0.176-1_amd64.deb
apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
apt-get update
apt-get install -y cuda

The above doesn't work. I will try your suggestion, thanks.

**Comment by kaismax** [comment]
i'm using _cuda 9.1_ and _cudnn 7.1.13_ with _tensorflow 1.5.0_ building from the source ,my laptop configuration i5 4200h 8go ram and gtx950m , and it work for me,
to build use Bazel and gcc 4.8 g++ 4.8
