### ISSUE TITLE
Tensorflow with GPU-support crashes when opening many CPU-only sessions in parallel

### ISSUE THREAD

**Issue by tcwalther** [tensorflow/tensorflow#1658]
The following code works fine in a CPU-only Tensorflow, but crashes on a GPU-enabled Tensorflow installation (0.7.1, with a Titan X, NVidia driver 352.79) when run many times in parallel:

```python
# test_tensorflow_session.py
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = ''
sess = tf.Session()
```

Bash command to run it in parallel:
```bash
for i in {1..48}; do ((python ./test_tensorflow_session.py 2> output$i.err 1> output$i.out ) &) ; done
```

If you then look into the `output*.err` files, you will see that most of the processes crashed. The output will look like this:

```
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:481] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:114] retrieving CUDA diagnostic information for host: gpu1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: gpu1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported version is: 352.79
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.79  Wed Jan 13 16:17:53 PST 2016
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported version is: 352.79
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:226] kernel version seems to match DSO: 352.79
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

For the sake of completeness, here is the use case: applying a Tensorflow model is just a small part in processing large amounts of data; processing is parallelised simply by using multiple processes.

I also tried wrapping the `tf.Session()` call in `with tf.device('/cpu:0'):`, but that didn't change anything. I assume that it is trying to get exclusive access to the GPU, and if it can't do that, it crashes. This is a bit annoying, since by setting `os.environ['CUDA_VISIBLE_DEVICES'] = ''`, I am actively trying to disable the GPU.

Ideas?

**Comment by vrv** [comment]
Hm, that is indeed weird.  Not sure why CUDA_VISIBLE_DEVICES isn't helping you.

Can you try the following in the meantime?

    config=tf.ConfigProto(device_count={"GPU": 0, "CPU": 1})
    tf.Session(config=config)

**Comment by tcwalther** [comment]
Thanks for the amazingly quick reply! Unfortunately, explicitly setting the `device_count` doesn't change the situation.

I would love to gather more debug information. Right now, all I can see is that a `std::system_error` is thrown somewhere, although it looks like it is thrown somewhere in the CUDA code, not in Tensorflow (I couldn't find any matching line in Tensorflow's codebase). Do you have any advice on how I could get a more meaningful stack trace?

**Comment by vrv** [comment]
I think it would be nice to figure out what's causing the actual failure at the cuda level, but it's surprising to me that this code is being reached at all -- I think that's the bug.  Basically, we need to figure out why "GPUMachineManager()" is ever being called when no GPU devices are requested -- that's the entry point that tries to do GPU initilization.  I'll try to find time to debug this.

**Comment by vrv** [comment]
Okay I partially take this back.  It is weird that the stream executor code is called at all, but I don't think that's the cause of the problem.  I tried reproducing your problem at HEAD, spawning 48 processes with CUDA_VISIBLE_DEVICES="" and I didn't get any std::system_error.

My guess from looking up the error is that each session is creating a number of std::threads, and at some point one of them blows up.

Another thing to try for debugging is to set the intra_op_parallelism_threads and intra_op_parallelism_threads in the ConfigProto to smaller values (they default to the number of cores on the machine).

As for why this causes problems only with the GPU pip, I'm not entirely sure yet :)

**Comment by tcwalther** [comment]
Oh gosh, turns out the problem was somewhere else completely. I hit the user process limit. Just to recap, I have two servers, one with a GPU and one without, otherwise nearly identical. However, on the CPU-only server, I increased the number of maximum processes per user in `/etc/security/limits.conf` a while ago, and when setting up the GPU server, I forgot to do that. It simply crashed because it wasn't allowed to spawn a thread anymore.

I think I simply got mislead by Tensorflow's `stderr` output. For the future, it would be great if there was an easier way to see when exactly Tensorflow crashes - that way I would have seen it had nothing to do with CUDA.

@vrv, thank you so much for your really fast replies!

**Comment by creativesh** [comment]
Hi 
I have exactly the same issue, I am training resNet50 and always after 3 epochs,i get this error
 i use ubuntu 16.04,tensorflow 1.3,and gtx 1080 gpu on a shared server with 3 gpus 
and also i have used new dataset tensorflow api,i suspect something is write aboute feeding data to network 
this is my training code :+1: 
[github.txt](https://github.com/tensorflow/tensorflow/files/1503372/github.txt)
