### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory (when trying to run object detection)

### ISSUE THREAD

**Issue by JSANJ** [tensorflow/tensorflow#16750]
Hello, I am trying to install the object-detection module of tensorflow but when running the following command: 
python3 object_detection/builders/model_builder_test.py

I get the following error. I have install CUDA 8.0,9.0,9.1, and cuDNN 6 and 7 but still have the following error. I appreciate your advice, thank you! 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 18, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

**Comment by adekunleba** [comment]
Had same issue

sudo apt-get install cuda-9-0 

worked for me even after I had Cuda-9-0 installed.

**Comment by JSANJ** [comment]
@adekunleba When I run that command, I get the following:
`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cuda-9-0
`
Could you please advise what to do? Thank you in advance!

**Comment by calper-ql** [comment]
@JSANJ do you have this in your rc file ? `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/extras/CUPTI/lib64`

**Comment by adekunleba** [comment]
@JSANJ you should add `cuda/lib64` to your `LD_LIBRARY_PATH`, in addition to @calper-ql suggestion, I also did ```export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64```

**Comment by gunan** [comment]
if you have multiple versions of CUDA installed, you probably need this instead:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64
```
This is because `/usr/local/cuda` is usually just a symlink to one of the versions. if you have multiple versions, it may be a symlink to another version.

**Comment by JSANJ** [comment]
@calper-ql @adekunleba @gunan Thank you all, your suggestions worked for installation on Windows using Ubuntu Bash

As a side note:
I also tried installing it on a Linux version (Ubuntu 16.04) and found that I wasn't actually installing CUDA due to the Ubuntu Software Center malfunctioning, but using commands instead worked as in: https://askubuntu.com/questions/760034/waiting-to-install-for-ever-ubuntu-software-16-04.

**Comment by ophyx** [comment]
@JSANJ `sudo apt-get install cuda-9.0` instead of `sudo apt-get install cuda-9-0` worked for me

**Comment by mmawada** [comment]
Hi , I tried all of the above but still getting the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/na/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/na/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/na/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/na/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/na/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/na/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
*************************************************************************
Not only that if i run import tensorflow as tf using spider in anaconda2 I get the same error as above but with libculas.so.8.0 : ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory.
I checked and i do have this file in lib in anaconda2, so I am puzzled .  I tried every thing in the tensorflow link but no success.  I am working with Ubuntu latest version 16.04.3.
Help please!

**Comment by gunan** [comment]
That is a CUDA library, anaconda2 should not, and would not have that library.
Also, one of your error messages complain about  cuda 9.0, and the 2nd complain about cuda 8.0
you will need to pick which version of TF you want to work with, then install the corresponding CUDA version.

**Comment by mmawada** [comment]
Gunan, thank you .  I decided to work with anaconda3 , do I need to install Cuda 9.2 as an update ?  in anaconda3 I did the following commands: 
sudo -H apt-get install git
	sudo -H apt-get install python3
	sudo -H apt-get install python3-matplotlib
	sudo -H apt-get install python3-pip
	sudo -H pip3 install --upgrade tensorflow
and it seems everything was updated fine , then I tried to import tensorflow as tf and got the error again

**Comment by gunan** [comment]
Anaconda is just a python distribution.
CUDA and cuDNN aare independent of Anaconda. You install anaconda separately, then you install CUDA separately.

**Comment by mmawada** [comment]
Gunan, thank you .  I decided to work with anaconda3 , do I need to install Cuda 9.2 as an update ?  in anaconda3 I did the following commands: 
sudo -H apt-get install git
	sudo -H apt-get install python3
	sudo -H apt-get install python3-matplotlib
	sudo -H apt-get install python3-pip
	sudo -H pip3 install --upgrade tensorflow
and it seems everything was updated fine , then I tried to import tensorflow as tf and got the error again

**Comment by mmawada** [comment]
well I did a full installation of cuda9.2 , with the latest version of tensorflow v 1.8 which is compatible . I used the following link :http://www.python36.com/how-to-install-tensorflow-gpu-with-cuda-9-2-for-python-on-ubuntu/ .  \After 3+ hours all went successfully and when it came to import tensorflow as tf , frustratingly enough i got the same error as before :    Any Ideas ?  Thank you 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/na/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/na/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/na/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/na/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/na/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/na/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/na/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/na/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by gunan** [comment]
https://www.tensorflow.org/install/install_linux#nvidia_requirements_to_run_tensorflow_with_gpu_support
As stated in the web page above, TF 1.8 is compatible with CUDA 9.0
We have no prebuilt binaries that are compatible with cuda 9.2. for cuda 9.2, you need to build from sources.

**Comment by mmawada** [comment]
Thank you .  I seem to have resolved the issue as on the command line i tested the tensoflow with Hello world and worked so happy until i realsied that tensoflow 1.8 was running on cpu and no gpu .  then i did the following :from tensorflow.python.client import device_lib followed by print(device_lib.list_local_devices()): "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 14605564845436371737
How do I get GPU working and how come it is not ?  Am I missing some installation ?

**Comment by crazysal** [comment]
After banging my head around a couple of days, installing cuda 9.2 but failing tf builds from scratch  uninstalling then downgrading to 9.0 to use pre compiled binaries : 

Dirty hack till tf updates cuda support 

**GCC :** (Ubuntu 7.3.0-16ubuntu3) 7.3.0
**OS :** 
linux -4.15.0-20-generic
x86_64
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
**GPU :**  
00:07.0 3D controller: NVIDIA Corporation GV100 [Tesla V100 SXM2] (rev a1)

**CUDA :**  
Driver version : 396.26 
Toolkit : 9.2 and 9.0 both installed by sudo sh cuda_9.*****-run  (download from nvidia ) but for installing 9.0 say N when asks to install display driver.


then do as said above : #issuecomment-365089833 

 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64 >> ~/.bashrc

**Comment by mmawada** [comment]
thank you for the suggestion as i am stuck not be able to get tf gpu working on tf 1.8 on cuda 9.2.  could you guide from where did you install cuda 9.0 as the nvidia download points immedaitely to 9.2 version.

**Comment by mmawada** [comment]
I did re-install cuda 9.0 after I uninstalled 9.2 and then reinstalled tf v.1.8 .  the validation on terminal of tf was successful but again it was running on cpu and not gpu!! .  I am absolutely puzzled why i cannot get tf gpu working tried every thing under the sun -very frustrating
