### ISSUE TITLE
TF 1.3 unable to create Session in the first time

### ISSUE THREAD

**Issue by tkc285** [tensorflow/tensorflow#16807]
I have install TF 1.3 GPU using anaconda. It is failed to create session as run TF in script file.

As run TF interactively or using spyder, same error messages were shown and it fail to create session in the first time. However, it able to create session if run "sess = tf.Session()" again. The TF will run either by input line by line script or using "exec(compile(open(filename, "rb").read(), filename, 'exec'))" 

The error message as create session:

$ source activiate tf13py36
(tf13py36)$ python
>>> import tensorflow as tf
>>> sess = tf.Session()
2018-02-05 17:44:25.343373: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-05 17:44:25.343398: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-05 17:44:25.540883: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-05 17:44:25.541399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX 980 Ti
major: 5 minor: 2 memoryClockRate (GHz) 1.228
pciBusID 0000:03:00.0
Total memory: 5.94GiB
Free memory: 5.83GiB
2018-02-05 17:44:25.600695: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x225e110 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2018-02-05 17:44:25.600988: E tensorflow/core/common_runtime/direct_session.cc:171] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tchen/anaconda3/envs/tf13py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1486, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/tchen/anaconda3/envs/tf13py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 621, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/tchen/anaconda3/envs/tf13py36/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/tchen/anaconda3/envs/tf13py36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
>>> sess = tf.Session()
2018-02-05 17:45:19.371509: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x225e110 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2018-02-05 17:45:19.371738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:03:00.0)
2018-02-05 17:45:19.430913: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x225e110 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
>>> x1 = tf.constant([1,2,3,4])
>>> x2 = tf.constant([5,6,7,8])
>>> result = tf.multiply(x1, x2)
>>> print(sess.run(result))
[ 5 12 21 32]

SYSTEM Infomation
ubuntu16.04
cuda V8.061
cudnn 6021
gtx1060
tensorflow1.3.0
python3.6.1
memory 30G ,used 5.5GB

$ nvidia-smi
Tue Feb  6 10:21:38 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 00000000:03:00.0 Off |                  N/A |
| 22%   31C    P8    19W / 250W |    110MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro 600          Off  | 00000000:04:00.0  On |                  N/A |
| 36%   53C    P0    N/A /  N/A |    524MiB /   959MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     19564      C   python                                        98MiB |
+-----------------------------------------------------------------------------+

I am grateful to anyone for helping me
Thank you very much!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tkc285** [comment]
Problem solved.
Add the CUDA_VISIBLE_DEVICES in the python file:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"

Thanks for the help.
