### ISSUE TITLE
Tensorflow-gpu 1.6 : failed call to cuInit: CUDA_ERROR_NO_DEVICE

### ISSUE THREAD

**Issue by vincent-roye** [tensorflow/tensorflow#16860]
- CUDA 9.0
- Cudnn 7.0
- Tensorflow-gpu 1.6

nvida-smi is good
![nvidia-smi](https://user-images.githubusercontent.com/2728049/35970141-d827bac6-0cfb-11e8-886f-92b068c62c4e.png)

Error 
2018-02-08 18:14:24.768537: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
**2018-02-08 18:14:25.438352: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE**
2018-02-08 18:14:25.441350: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: Vincent
2018-02-08 18:14:25.441633: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_diagnostics.cc:165] hostname: Vincent
2018-02-08 18:14:25.443152: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\direct_session.cc:297] Device mapping:

Device mapping: no known devices.
MatMul: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0
b: (Const): /job:localhost/replica:0/task:0/device:CPU:0
a: (Const): /job:localhost/replica:0/task:0/device:CPU:0

Code : 
`import os
import tensorflow as tf

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="1"

from tensorflow.python.client import device_lib
#print (device_lib.list_local_devices())

# Creates a graph.
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))`

**Comment by qmick** [comment]
Try set `CUDA_VISIBLE_DEVICES=0`

**Comment by vincent-roye** [comment]
Perfect, it's working. thanks!

**Comment by maiminh1996** [comment]
Thanks you very much @vincent-roye :+1:

**Comment by libichong** [comment]
- Windows 10

My case is a bit different. I updated the display card driver and it shows '!'  in device manager. I chose to roll it back and it become normal. Then the error is gone.

**Comment by kajal15003** [comment]
export CUDA_VISIBLE_DEVICES=0,1
works for me

**Comment by zzj0402** [comment]
adding `--runtime=nvidia` to the docker exec/run command
