### ISSUE TITLE
Failed to call cudnnRNNBackwardData: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by burglarhobbit** [tensorflow/tensorflow#17009]
### System information
- **Have I written custom code**: Yes
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from**: binary
- **TensorFlow version**: 1.4.1
- **Python version**: 3.5.2
- **Bazel version:** Not compiled from source
- **GCC/Compiler version**: Not compiled from source
- **CUDA/cuDNN version**: 8.0/v6
- **GPU model and memory**: GeForce GTX 1080 (8GB x 4)
- **Exact command to reproduce**: Code as per below

The code starts training and after an arbitrary number of iterations on batches, it gives the following error:

```
2018-02-14 23:51:31.591963: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
2018-02-14 23:51:31.592000: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
2018-02-14 23:51:31.592023: E tensorflow/stream_executor/cuda/cuda_dnn.cc:1679] Failed to call cudnnRNNBackwardData: CUDNN_STATUS_INTERNAL_ERROR
Aborted (core dumped)
```

I'm using `cudnn_gru` in a `tf.while_loop` control flow operation and using initializers from outside the `tf.while` scope since variables aren't allowed to be instantiated within the `tf.while` scope:

```
import tensorflow as tf

gru_fw = tf.contrib.cudnn_rnn.CudnnGRU(num_layers=1, num_units=150, input_size=500)
gru_fw_1 = tf.contrib.cudnn_rnn.CudnnGRU(num_layers=1, num_units=150, input_size=1800)
e = tf.random_uniform([gru_fw.params_size()], -0.1, 0.1)
f = tf.random_uniform([gru_fw.params_size()], -0.1, 0.1)
g = tf.zeros([1, 4, 150])
h = tf.zeros([1, 4, 150])
zeros_i = tf.zeros([4, 150])

class cudnn_gru:
	def __init__(self, num_layers, num_units, batch_size, input_size, keep_prob=1.0, is_train=None, scope=None):
		self.num_layers = num_layers
		self.grus = []
		self.params = []
		self.inits = []
		self.dropout_mask = []
		for layer in range(num_layers):
			input_size_ = input_size if layer == 0 else 2 * num_units
			gru_fw = tf.contrib.cudnn_rnn.CudnnGRU(
				num_layers=1, num_units=num_units, input_size=input_size_)
			gru_bw = tf.contrib.cudnn_rnn.CudnnGRU(
				num_layers=1, num_units=num_units, input_size=input_size_)
			with tf.variable_scope('CUDNN_GRU', reuse=tf.AUTO_REUSE):
				param_fw = tf.get_variable("param_fw",initializer=e,validate_shape=False)
				param_bw = tf.get_variable("param_bw",initializer=f,validate_shape=False)
				init_fw = tf.get_variable("init_fw", initializer=g)
				init_bw = tf.get_variable("init_bw", initializer=h)
	def __call__(self, inputs, seq_len, keep_prob=1.0, is_train=None, concat_layers=True):
		outputs = [tf.transpose(inputs, [1, 0, 2])]
		for layer in range(self.num_layers):
			gru_fw, gru_bw = self.grus[layer]
			param_fw, param_bw = self.params[layer]
			init_fw, init_bw = self.inits[layer]
			mask_fw, mask_bw = self.dropout_mask[layer]
			with tf.variable_scope("fw"):
				out_fw, _ = gru_fw(outputs[-1] * mask_fw, init_fw, param_fw)
			with tf.variable_scope("bw"):
				inputs_bw = tf.reverse_sequence(
					outputs[-1] * mask_bw, seq_lengths=seq_len, seq_dim=0, batch_dim=1)
				out_bw, _ = gru_bw(inputs_bw, init_bw, param_bw)
				out_bw = tf.reverse_sequence(
					out_bw, seq_lengths=seq_len, seq_dim=0, batch_dim=1)
			outputs.append(tf.concat([out_fw, out_bw], axis=2))
		if concat_layers:
			res = tf.concat(outputs[1:], axis=2)
		else:
			res = outputs[-1]
		res = tf.transpose(res, [1, 0, 2])
		return res

class native_gru:
	def __init__(self, num_layers, num_units, batch_size, input_size, keep_prob=1.0, is_train=None, scope="native_gru"):
		self.num_layers = num_layers
		self.grus = []
		self.inits = []
		self.dropout_mask = []
		self.scope = scope
		for layer in range(num_layers):
			input_size_ = input_size if layer == 0 else 2 * num_units
			gru_fw = tf.contrib.rnn.GRUCell(num_units)
			gru_bw = tf.contrib.rnn.GRUCell(num_units)
			with tf.variable_scope('native_GRU', reuse=tf.AUTO_REUSE):

				init_fw = tf.get_variable("init_fw", initializer=zeros_i)
				init_bw = tf.get_variable("init_bw", initializer=zeros_i)
				
			#init_fw = tf.Variable(tf.zeros([batch_size, num_units]))
			#init_bw = tf.Variable(tf.zeros([batch_size, num_units]))
			mask_fw = dropout(tf.ones([batch_size, 1, input_size_], dtype=tf.float32),
							  keep_prob=keep_prob, is_train=is_train, mode=None)
			mask_bw = dropout(tf.ones([batch_size, 1, input_size_], dtype=tf.float32),
							  keep_prob=keep_prob, is_train=is_train, mode=None)
			self.grus.append((gru_fw, gru_bw, ))
			self.inits.append((init_fw, init_bw, ))
			self.dropout_mask.append((mask_fw, mask_bw, ))

	def __call__(self, inputs, seq_len, keep_prob=1.0, is_train=None, concat_layers=True):
		outputs = [inputs]
		with tf.variable_scope(self.scope):
			for layer in range(self.num_layers):
				gru_fw, gru_bw = self.grus[layer]
				init_fw, init_bw = self.inits[layer]
				mask_fw, mask_bw = self.dropout_mask[layer]
				with tf.variable_scope("fw_{}".format(layer)):
					out_fw, _ = tf.nn.dynamic_rnn(
						gru_fw, outputs[-1] * mask_fw, seq_len, initial_state=init_fw, dtype=tf.float32)
				with tf.variable_scope("bw_{}".format(layer)):
					inputs_bw = tf.reverse_sequence(
						outputs[-1] * mask_bw, seq_lengths=seq_len, seq_dim=1, batch_dim=0)
					out_bw, _ = tf.nn.dynamic_rnn(
						gru_fw, inputs_bw, seq_len, initial_state=init_bw, dtype=tf.float32)
					out_bw = tf.reverse_sequence(
						out_bw, seq_lengths=seq_len, seq_dim=1, batch_dim=0)
				outputs.append(tf.concat([out_fw, out_bw], axis=2))
		if concat_layers:
			res = tf.concat(outputs[1:], axis=2)
		else:
			res = outputs[-1]
		return res
```
This has not happened before, when the project structure was sequential and not within a control flow mechanism. Also, if I change the implementation to use native GRU instead of cudnn_gru, it works perfectly fine.

**Comment by burglarhobbit** [comment]
@facaiy Can you help me in this error? Thanks.

**Comment by dpedley** [comment]
Hey, I had a crash, maybe related? Also on Ubuntu 16.04 
In my case the crash happens running a tutorial, `not` custom code.

```
From models/tutorials/rnn/ptb:
python ptb_word_lm.py --data_path=simple-examples/data/ --model=small --save_path=build
```
Crashing [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc#L203) while polling [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_event.cc#L49)

Note in the output below it runs through a few iterations in the first epoch before crashing. Also of note, this is a really low mem GPU machine, before I found this issue, I assumed memory limits had been reached.

```
2018-02-15 13:42:07.302928: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX FMA
2018-02-15 13:42:07.435901: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-15 13:42:07.436403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: GeForce GT 730 major: 3 minor: 5 memoryClockRate(GHz): 1.006
pciBusID: 0000:01:00.0
totalMemory: 1.95GiB freeMemory: 1.82GiB
2018-02-15 13:42:07.436453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GT 730, pci bus id: 0000:01:00.0, compute capability: 3.5)
WARNING:tensorflow:From ptb_word_lm.py:504: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-02-15 13:42:17.089765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GT 730, pci bus id: 0000:01:00.0, compute capability: 3.5)
Epoch: 1 Learning rate: 1.000
0.004 perplexity: 5095.013 speed: 3685 wps
0.104 perplexity: 846.368 speed: 5772 wps
0.204 perplexity: 627.641 speed: 5847 wps
0.304 perplexity: 505.304 speed: 5854 wps
0.404 perplexity: 435.348 speed: 5852 wps
0.504 perplexity: 389.893 speed: 5815 wps
2018-02-15 13:43:50.493081: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
2018-02-15 13:43:50.493151: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
```

System information
 - **Have I written custom code:** No
 - **OS Platform and Distribution:** Ubuntu 16.04
 - **TensorFlow installed from:** binary
 - **TensorFlow version:** tensorflow-gpu (1.5.0)
 - **Python version:** 3.5.2
 - **Bazel version:** Not compiled from source
 - **GCC/Compiler version:** Not compiled from source
 - **CUDA/cuDNN version:** 9.0/v7
 - **GPU model and memory:** GeForce GT 730 (2GB x 1)

**Comment by burglarhobbit** [comment]
Have you tried reducing (to half) the batch size?

**Comment by dpedley** [comment]
@burglarhobbit yeah even at batch_size=1, but as you said, might be a different cause.

**Comment by bignamehyp** [comment]
@ebrevdo can you please take a look?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by peterwilliams97** [comment]
I get the same error with Keras on Ubuntu 16.04

**Comment by burglarhobbit** [comment]
@peterwilliams97 It would mean that the graph gets disconnected somewhere in between which is why it is not able to perform backprop.

**Comment by peterwilliams97** [comment]
@burglarhobbit Thanks
What can I do to prevent this? It happens over a day into my modelling in a late epoch of a late CV round of the fourth or fifth model in the test run. It is caused by some sort of resource leak somewhere?

**Comment by peterwilliams97** [comment]
I saw this again today under similar circumstances to my last comment
```
 File "/home/pcadmin/code/Butt-Head-Astronomer/toxic/mod_rec_word_char.py", line 89, in get_model2
    x = Bidirectional(Rec(n_hidden, return_sequences=True), name='c_bidi')(x)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 324, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 385, in call
    y_rev = self.backward_layer.call(inputs, **kwargs)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py", line 90, in call
    output, states = self._process_batch(inputs, initial_state)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py", line 297, in _process_batch
    is_training=True)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 1555, in __call__
    seed=self._seed)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 944, in _cudnn_rnn_no_input_c
    direction, dropout, seed, name)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 858, in _cudnn_rnn
    name=name)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/ops/gen_cudnn_rnn_ops.py", line 107, in cudnn_rnn
    is_training=is_training, name=name)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/pcadmin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Failed to call ThenRnnForward
         [[Node: c_bidi_24/CudnnRNN_1 = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="gru", seed=234, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](c_bidi_24/transpose_2, c_bidi_24/ExpandDims_1, w_bidi_24/Const, c_bidi_24/concat_1)]]
         [[Node: output_24/Sigmoid/_5943 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_571_output_24/Sigmoid", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

The model being executed is 
```
def get_model2(embedding_matrix, char_embedding_matrix,
    max_features, maxlen, char_maxlen, Rec,
    dropout=0.2, rnn_layers=1, n_hidden=80, trainable=True):

    inp1 = Input(shape=(maxlen, ), name='w_inp')
    x = Embedding(embedding_matrix.shape[0],
                  embedding_matrix.shape[1],
                  weights=[embedding_matrix],
                  trainable=trainable, name='w_emb')(inp1)
    x = SpatialDropout1D(dropout, name='w_drop')(x)

    for i in range(rnn_layers):
        x = Bidirectional(Rec(n_hidden, return_sequences=True), name='w_bidi%d' % i)(x)
    avg_pool = GlobalAveragePooling1D(name='w_ave')(x)
    max_pool = GlobalMaxPooling1D(name='w_max')(x)
    conc1 = concatenate([avg_pool, max_pool], name='w_conc')

    inp2 = Input(shape=(char_maxlen, ), name='c_inp')
    x = Embedding(char_embedding_matrix.shape[0],
                  char_embedding_matrix.shape[1],
                  weights=[char_embedding_matrix], name='c_emb')(inp2)
    x = SpatialDropout1D(dropout, name='c_drop')(x)

    for i in range(rnn_layers):
        x = Bidirectional(Rec(n_hidden, return_sequences=True), name='c_bidi%d' % i)(x)
    avg_pool = GlobalAveragePooling1D(name='c_ave')(x)
    max_pool = GlobalMaxPooling1D(name='c_max')(x)
    conc2 = concatenate([avg_pool, max_pool], name='c_conc')

    conc = concatenate([conc1, conc2], name='w_c_conc')

    outp = Dense(6, activation="sigmoid", name='output')(conc)

    model = Model(inputs=[inp1, inp2], outputs=outp)
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

    return model
```
with `batch_size=200, dropout=0.5, n_hidden=128, rec=CuDNNGRU, trainable=False`
The Keras description of the model is
```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
w_inp (InputLayer)              (None, 150)          0                                            
__________________________________________________________________________________________________
c_inp (InputLayer)              (None, 600)          0                                            
__________________________________________________________________________________________________
w_emb (Embedding)               (None, 150, 300)     45000000    w_inp[0][0]                      
__________________________________________________________________________________________________
c_emb (Embedding)               (None, 600, 25)      25000       c_inp[0][0]                      
__________________________________________________________________________________________________
w_drop (SpatialDropout1D)       (None, 150, 300)     0           w_emb[0][0]                      
__________________________________________________________________________________________________
c_drop (SpatialDropout1D)       (None, 600, 25)      0           c_emb[0][0]                      
__________________________________________________________________________________________________
w_bidi (Bidirectional)          (None, 150, 256)     330240      w_drop[0][0]                     
__________________________________________________________________________________________________
c_bidi (Bidirectional)          (None, 600, 256)     119040      c_drop[0][0]                     
__________________________________________________________________________________________________
w_ave (GlobalAveragePooling1D)  (None, 256)          0           w_bidi[0][0]                     
__________________________________________________________________________________________________
w_max (GlobalMaxPooling1D)      (None, 256)          0           w_bidi[0][0]                     
__________________________________________________________________________________________________
c_ave (GlobalAveragePooling1D)  (None, 256)          0           c_bidi[0][0]                     
__________________________________________________________________________________________________
c_max (GlobalMaxPooling1D)      (None, 256)          0           c_bidi[0][0]                     
__________________________________________________________________________________________________
w_conc (Concatenate)            (None, 512)          0           w_ave[0][0]                      
                                                                 w_max[0][0]                      
__________________________________________________________________________________________________
c_conc (Concatenate)            (None, 512)          0           c_ave[0][0]                      
                                                                 c_max[0][0]                      
__________________________________________________________________________________________________
w_c_conc (Concatenate)          (None, 1024)         0           w_conc[0][0]                     
                                                                 c_conc[0][0]                     
__________________________________________________________________________________________________
output (Dense)                  (None, 6)            6150        w_c_conc[0][0]                   
==================================================================================================
Total params: 45,480,430
Trainable params: 480,430
Non-trainable params: 45,000,000
__________________________________________________________________________________________________
```

**Comment by burglarhobbit** [comment]
@peterwilliams97 Did you try asking in the keras github repo? I do not have much experience in keras to comment on it but have you tried running it on a cpu? Sometimes CUDA acts weird which has caused me to choose native GRU rather than cudnn_gru when using while loops in tensorflow

**Comment by protoget** [comment]
Could you provide a minimum reproducible example? Also, why not using the CudnnGRU comes with TF?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by burglarhobbit** [comment]
@protoget Here it is:

```
import tensorflow as tf
max_para = tf.placeholder(tf.int32)
num_units = 150
inputs = tf.placeholder(tf.float32,shape=[15,8,num_units])
class cudnn_gru:
    def __init__(self):
        self.gru_fw = tf.contrib.cudnn_rnn.CudnnGRU(1, num_units, 
            kernel_initializer=tf.random_normal_initializer(stddev=0.1))
        with tf.variable_scope('CUDNN_GRU', reuse=tf.AUTO_REUSE):
            self.init_fw = tf.get_variable("init_fw",shape=[1, 8, num_units],initializer=
                tf.zeros_initializer())
            self.init_bw = tf.get_variable("init_bw",shape=[1, 8, num_units],initializer=
                tf.zeros_initializer())
    def __call__(self,inputs):
        out_fw, _ = self.gru_fw(inputs, initial_state=(self.init_fw,))

class cudnn_gru2:
    def __init__(self):
        self.gru_fw = tf.contrib.cudnn_rnn.CudnnGRU(1, num_units-1, 
            kernel_initializer=tf.random_normal_initializer(stddev=0.1))
        with tf.variable_scope('CUDNN_GRU', reuse=tf.AUTO_REUSE):
            self.init_fw = tf.get_variable("init_fw",shape=[1, 8, num_units],initializer=
                tf.zeros_initializer())
            self.init_bw = tf.get_variable("init_bw",shape=[1, 8, num_units],initializer=
                tf.zeros_initializer())
    def __call__(self,inputs):
        out_fw, _ = self.gru_fw(inputs, initial_state=(self.init_fw,))

def get_output():
    gru = cudnn_gru()
    out = gru(inputs)
    return tf.constant(1)

def get_output2():
    gru = cudnn_gru2()
    out = gru(inputs)
    return tf.constant(2)

for i in range(3):
    i_ = tf.constant(i)
    out = tf.cond(i_<max_para,get_output,get_output2)
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 93 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 109 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 125 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 139 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 154 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 169 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 185 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @protoget: It has been 200 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jalilasadi** [comment]
I had the same problem. I had both cuda 10.0 and 10.1 installed. I removed the 10.1 and then downgraded the graphic card's driver and the problem was gone.

**Comment by sushreebarsa** [comment]
@burglarhobbit Is this still an issue ?
We see that you are using old version of tensorflow 1.x which is not actively supported, We recommend that you upgrade to 2.4 or later version.Please have a look at the [migration](https://www.tensorflow.org/guide/migrate) guide for reference to migrate from TensorFlow 1.x to TensorFlow 2.Thank you!
