### ISSUE TITLE
ImportError: Could not find 'cudart64_90.dll'.

### ISSUE THREAD

**Issue by JoanRessing** [tensorflow/tensorflow#17101]
Installed tensorflow 1.5.0 on windows 10 education (version 1709) using "C:\> pip3 install --upgrade tensorflow-gpu"

Installed CUDA 9.0 from https://developer.nvidia.com/cuda-90-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exenetwork

Installed cuDNN 7.0.5 for CUDA 9.0 from https://developer.nvidia.com/rdp/cudnn-download

I have python 3.6.3 and nvidia gtx 1060 6GB

Exact command to reproduce: python neural.py

Bazel version: N/A

### Describe the problem
Tried creating a simple network but running into the error described in title. I checked the directory where the CUDA_PATH refers to and the file is there.

### Source code / logs
    from keras.models import Sequential
    from keras.layers import Dense
    import pandas as pd
    
    def load_mnist(path):
    	train = pd.read_csv(path + 'train.csv')
    	y = train.ix[:,0]
    	train = train.drop('label',1)
    	test = pd.read_csv(path + 'test.csv')
    	return [train, y, test]
    
    [train, y, test] = load_mnist('data/')
    model = Sequential()
    model.add(Dense(12, input_dim=8, activation='relu'))
    model.add(Dense(8, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    
    model.fit(train, y, epochs=150, batch_size=10)
    
    predictions = model.predict(test)

![importerror](https://user-images.githubusercontent.com/25662411/36347024-c66f8fea-144c-11e8-905e-b519759c8def.PNG)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by JoanRessing** [comment]
@tensorflowbutler updated the post, the code fragment is the content of neural.py

**Comment by bignamehyp** [comment]
Can you please try to install tensorflow gpu nightly build?

**Comment by Chunde** [comment]
I have the same problem, I used CUDA Toolkit 9.1, I am not sure if this is the problem, going to try 9.0

**Comment by JoanRessing** [comment]
Figured it out, had forgotten to set the cuDNN path variable.

**Comment by gohugo** [comment]
what cuDNN path variable ?

**Comment by YopSolo** [comment]
same message for me Could not find 'cudart64_90.dll

my config 
win 10
CUDA 9.0
cuDNN 7.0.5 
python 3.6.4 and nvidia gtx 1060 6GB

my error with : import tensorflow
![error](https://user-images.githubusercontent.com/1012515/37651861-da3f6338-2c39-11e8-9ef9-63148e28e0be.PNG)

my /bin
![bin](https://user-images.githubusercontent.com/1012515/37651860-da24499a-2c39-11e8-89ea-961d7402c8ec.PNG)

my /include
![include](https://user-images.githubusercontent.com/1012515/37651862-da5afa4e-2c39-11e8-80fa-09c85afc8057.PNG)

my /lib/x64
![lib-64](https://user-images.githubusercontent.com/1012515/37651864-da74110a-2c39-11e8-83b4-7154453f269a.PNG)

my environment variables
![path](https://user-images.githubusercontent.com/1012515/37651967-35cd6e84-2c3a-11e8-93a1-5677526a470c.PNG)

**Comment by Luther0507** [comment]
I'm having the same issue with CUDA 9.0, CUDNN 7.1.1, Python 3.6.4 (AMD-64) and tensorflow-gpu. I also tried it with tf-nightly-gpu. 
The cudart64_90.dll is in the bin folder but the import fails
Error
![image](https://user-images.githubusercontent.com/32106185/37685138-a39be4d8-2c92-11e8-844a-9742da1d9759.png)


My Vars
![image](https://user-images.githubusercontent.com/32106185/37685169-c0b2a020-2c92-11e8-8302-be6c21ebf3e5.png)

**Comment by hk2283** [comment]
I had same error. The "bin" directory contains "cudart64_91.dll" instead of "cudart64_90.dll". 
I found "build_info.py" file contains DLL file name to use import tensorflow on python. 
And I fixed DLL file name in "build_info.py". 
After that it cause a punch of error that I can not try to handle.

**Comment by leobenkel** [comment]
I am having similar issues.

Versions:
* ```>pip --version
pip 9.0.3 from c:\users\leopc\appdata\local\programs\python\python35\lib\site-packages (python 3.5)```
* `CUDA 9.1` 
* `tensorflow-gpu (1.7.0)`

Content of folders:
* `C:\Program Files\NVIDIA GPU Computing Toolkit\cudnn\bin`
    * `cudnn64_7.dll`
* `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin`
    * `cudart64_91.dll`
    * and a bunch other dll

Error:
```
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit
```

Any idea what I should do ?

**Comment by 21011996** [comment]
@leobenkel Use CUDA 9.0, found out that the hard way, but now it works.

**Comment by leobenkel** [comment]
@21011996 , how do I get CUDA 9.0 ? I tried and I could not find it anywhere on the nvidia website.

**Comment by 21011996** [comment]
@leobenkel here you go [https://developer.nvidia.com/cuda-90-download-archive](CUDA 9.0)

**Comment by leobenkel** [comment]
@21011996 , is there any trick to uninstall cuda 9.1 and reinstall cuda 9.0 ? I went in the uninstaller control pannel window on windows 10 to uninstall all cuda 9.1 components. but now the cuda 9.0 installation keep failing even after reboot.

**Comment by kevindjf66** [comment]
I have the same problem.. Is there any solution now?

**Comment by 21011996** [comment]
I suggest Google :) Installed 9.1 by mistake, but successfully installed
9.0 after, GL m8

**Comment by leobenkel** [comment]
@kevindjf66 , to pass the installation, I disabled the visual studio support. I dont know what downstream error that will create but it succeed so far.

**Comment by angersson** [comment]
This looks like it has been solved, so I'm closing the issue to keep the tracker focused. Thanks!

**Comment by vedantja** [comment]
Switching to CUDA 9.0 and CUDNN7.1 worked for me

**Comment by JoWoWi** [comment]
same issue and solved by using CUDA 9.0 as described above

**Comment by Ap1075** [comment]
Also keep in mind to download the base package of CUDA 9.0. Other packages (Patch1, patch2) didn't seem to include cudart64_90.dll.

**Comment by Yoshud** [comment]
installing tf-nightly (pip install tf-nightly) helped

**Comment by paulkarpenko** [comment]
I'm seeing this error as well, unfortunately. 

```ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit```

I'm using `tensorflow-gpu-1.8.0`, but I've tried `tf-nightly-gpu` as well with no luck. I have CUDA v9.0, cuDNN 7.1, and the DLL is definitely where it's supposed to be (C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin)

My PATH is set correctly (I think!) as well.

![image](https://user-images.githubusercontent.com/2983780/40287407-fe8a4fe8-5c61-11e8-8725-57b8e4f12a94.png)

I'm not sure what else to try.

**Comment by lh47383** [comment]
Is there a simple solution.  I've tried everything to no avail.

**Comment by lh47383** [comment]
Well, I can now instantiate a TensorFlow!

I get an error that says my cpu supports instructions that the TF was not compiled to use : AVX2.

I’ll ignore like the internet says.

Thanks for your help.

Luke Hamm
806-535-4741

On May 24, 2018, at 12:13 PM, Armaan Puri <notifications@github.com<mailto:notifications@github.com>> wrote:


Just download the base package, check if cudart64_90.dll is in the directory (should be in CUDA/v9.0/bin), once you see it there, ensure the directory is added to your PATH. Done. That's about as simple as it gets.

**Comment by crapthings** [comment]
@lh47383 
https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u

**Comment by anonym24** [comment]
well still doesn't work with CUDA 9.0 and cudnn 7, I have this file 100% (cudart64_90.dll) and all needed environment variables (paths) 

details: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/57

**Comment by jackhhchan** [comment]
Hi,
I am having the same problem when trying to run tensorflow-gpu that returns
ImportError: Could not find 'cudart64_90.dll'

I have installed CUDA 9.0 onto my computer.
Also, copied cuDNN files into my path /NVIDIA GPU Computing Toolkit/CUDA/v9.0/

It still isn't working.

Any idea how this can be fixed?

Thanks

**Comment by robinekenheim** [comment]
There is a 
`cudart64_92.dll` file in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin
But when trying to load TensorFlow the error is that TF is trying to make use of 
'cudart64_90.dll'
Tried renaming the file but then I get other errors 😭

**Comment by Makhaon** [comment]
if you'll create the new issue, please give us a number, I have same issue, tensorflow doesn't works with cuda 9.2:
> ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL
I'm have searching for this dll and found only cudart64_92.dll

**Comment by foreverdeveloper** [comment]
i installed cuda 9.2 but tensorflow is finding cudart64_92.dll ,
should i reinstall cuda 9.0 ?  are there any answers ?

**Comment by Makhaon** [comment]
Yes, you shoud, it helps.

**Comment by Leminhbinh0209** [comment]
try it:
set PATH=%PATH%;C:\tools\cuda\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin

**Comment by cquark7** [comment]
I was going to comment "why can't they clearly specify which CUDA version is supported in the installation docs", but then I re-checked the installation docs just to be sure and this is what I found:
![install tensorflow on windows tensorflow](https://user-images.githubusercontent.com/29166153/43369202-63f41704-9387-11e8-81f1-cf133babb048.png)

Lesson learned: **Read the docs carefully if you don't want to waste your valuable time.**

**Comment by UmeanNever** [comment]
I also had this problem with __cuda 9.0__ installed and the __cudart64_90.dll__ file exactly in path. 

After I had a look at the PATH in my terminal, I realized that it's because I'm using conda virtual environment and I just add PATH in system environment variable setting after installing cuda and cudnn, but **the path in virtual environment is not updated.** I solved this by deactivate-activate the environment and restart python.

For those who have similar issues in conda virtual environment, you may try [deactivate and activate the virtual environment](https://conda.io/docs/user-guide/tasks/manage-environments.html) and restart python.

**Comment by CHIKKIZZY** [comment]
@UmeanNever was spot on. If you are using a conda environment a simple restart may be all you need to do.

**Comment by antropit** [comment]
I have GTX1060 wich not compotable with CUDO 9.0. Only with CUDO 9.2. What I must do? O.o

**Comment by Vegoo89** [comment]
Found a solution, in my case it was related to Windows 10 and Pycharm.
Somehow Pycharm doesn't have access to Program Files in Windows 10 if you don't run it as admin and this is default location of CUDA folder and all dlls .
I closed all my projects and opened Pycharm as admin and suddenly everything works.

**Comment by ibraheemalkilanny** [comment]
Don't forget to restart cmd/terminal after applying changes in path !!

**Comment by SatyamThakur30** [comment]
Always check the cuda version in this case you have to install cuda version 9.0 this will create the cudart64_90.dll file in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin folder. 

This will surely work.

**Comment by zhushichuan** [comment]
> 找到了一个解决方案，就我而言，它与Windows 10和Pycharm有关。
> 不知何故，如果不以管理员身份运行，Pycharm无法访问Windows 10中的Program Files，这是CUDA文件夹和所有dll的默认位置。
> 我关闭了所有项目并以管理员身份打开了Pycharm，突然一切正常。
> 
> 我还编辑了两行tensorflow模块的build_info.py：
> 
> cudart_dll_name ='C：\ Program Files \ NVIDIA GPU Computing Toolkit \ CUDA \ v9.0 \ bin \ 
> cudart64_90.dll'cudnn_dll_name ='C：\ Program Files \ NVIDIA GPU Computing Toolkit \ CUDA \ v9.0 \ bin \ cudnn64_7。 DLL”
> 
> 希望能帮助到你！

Thank you. This is very useful.

**Comment by regression-gerry** [comment]
I had a similar issue except mine was:
ImportError: Could not find 'cudart64_100.dll'.

My initial tensorflow installation was tensorflow-gpu 2.0 beta which requires CUDA 10.0.

What I did:
- uninstall tensorflow via 'pip uninstall tensorflow-gpu==2.0.0-beta1'
- uninstall CUDA 9.0
- install CUDA 10.0
- 'pip install tensorflow-gpu' (This will install tensorflow-gpu 1.14)
- download the latest cuDNN from
https://developer.nvidia.com/rdp/cudnn-download
- copy out cudnn64_7.dll, cudnn.h, cudnn.lib to the relevant folders
further instructions: https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html
- set the environment variable lastly to:
Variable Name: CUDA_PATH 
Variable Value: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0

I am able to get tensorflow running again through these steps.

**Comment by SatyamThakur30** [comment]
Download cudnn version 10.0 not latest one  10.1.
 This will work.

**Comment by Starscream9559** [comment]
> 
> 
> PLEASE DO NOT INSTALL CUDA 9.2 FOR TENSORFLOW USAGE. ONLY 9.0 WORKS

What about CUDA 10/10.1/10.1 Update 1/10.1 Update 2 ?
For CUDA 10.1, it now says cudart64_100.dll that is missing.

**Comment by lukeoverride** [comment]
> PLEASE DO NOT INSTALL CUDA 9.2 FOR TENSORFLOW USAGE. ONLY 9.0 WORKS
> 
> What about CUDA 10/10.1/10.1 Update 1/10.1 Update 2 ?
> For CUDA 10.1, it now says cudart64_100.dll that is missing.

I tried with Cuda 10.1, it looks for cudart64_100.dll, even if I changed the entry in build_info. So I downgrade to Cuda 10.0 and it worked. Actually from the other way round cuda 10.0 is not detecting visual studio

**Comment by sephethus** [comment]
Having a catch 22 situation here, I have CUDA 10.1 which means I have cudart64_101.dll not 100.dll. It's looking for 100. I cannot downgrade to CUDA 10.0 because I'll have to just wipe out my whole computer to redo the whole NVidia driver situation. NVidia is not friendly towards simply uninstalling drivers in Windows 10. The install will definitely fail as it was doing all weekend till I finally gave up and did a full format reload of Windows 10 which is a pain.  I have tensorflow 1.13.1 installed because 1.14 gets errors when trying to use it with imageai. So that's out and besides, I tested it, 1.14.0 still wants the older version of CUDA, 10.0

**Comment by sephethus** [comment]
So naturally I ended up having to blow away my whole Windows 10 installation and start with a clean install, just to go back a version to 10.0. Unfortunately 10.0 doesn't support Visual Studio 2019 like 10.1 does. So go figure. This is an impossible situation and I might as well give up on Machine Learning altogether.

**Comment by biswadipmitra** [comment]
GETTING ERROR..
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 
![ERROR](https://user-images.githubusercontent.com/6049201/64925507-1df1b680-d80f-11e9-89c0-053a8f3abd04.JPG)
from this URL: https://developer.nvidia.com/cuda-90-download-archive

**Comment by Starscream9559** [comment]
I don't wanna spoil you guys but, recently I've installed Pop OS and the team already compiled all the necessary needs into single cmd line. Either make it dual-boot or, different disk. Both are good.
Once in Linux, open terminal and run, 

> sudo apt install tensorflow-cuda-latest

which is a package of CUDA Toolkit, cuDNN, and Tensorflow itself. CUDA, TF and cuDNN version is determined by the current stable version, and your GPU version. Still using it up until now.

**Comment by rakesh4real** [comment]
> So naturally I ended up having to blow away my whole Windows 10 installation and start with a clean install, just to go back a version to 10.0. Unfortunately 10.0 doesn't support Visual Studio 2019 like 10.1 does. So go figure. This is an impossible situation and I might as well give up on Machine Learning altogether.

Hi, fortunately 0NE-LINE of code solves this issue. Refer [this article](https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc)

**Comment by rakesh4real** [comment]
fortunately 0NE-LINE of code solves this issue. Refer [this article](https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc).

**Comment by YumiAlmero03** [comment]
> fortunately 0NE-LINE of code solves this issue. Refer [this article](https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc).

this works thank you!

**Comment by anandtestenv** [comment]
just rename the file cudart64_XXX.dll to cudart_100.dll.
This is because command is still searching for version 10.0 but u have installed 10.1 or something else.

**Comment by Abdullah211w** [comment]
im having the same problem "Could not find 'cudart64_90.dll'"
my card is GTX 1050Ti 4GB
Can Anyone Help please

**Comment by Cibi075** [comment]
Fix for the issue!!!
https://stackoverflow.com/a/59703666/9203336

**Comment by JunghunJwa** [comment]
In my case,the problem solved by deleting tf-nightly and reinstalling tensorflow

**Comment by dreamer-sakshi** [comment]
https://www.youtube.com/watch?v=O8yye2AHCOk
