### ISSUE TITLE
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by akkefa** [tensorflow/tensorflow#17147]
I installed cuda 9.1 and set the path as suggested.
Should i install cuda 8.0 for resolving this problem?
Error:

ImportError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

**Comment by dieka13** [comment]
from my experience, yes you'll need cuda 8.0 hence the libcublas.so.8.0 error

**Comment by akkefa** [comment]
Issued is fixed by installing tensorflow 1.5 with Cuda 9.0 version.
