### ISSUE TITLE
Get cudnn version 7005 while 7101 installed only

### ISSUE THREAD

**Issue by HorsonLiu** [tensorflow/tensorflow#17422]
ubuntu 16.04
GTX 1080ti
cuda 9.1
cudnn 7.1.1 ( libcudnn7_7.1.1.5-1+cuda9.1_amd64.deb & libcudnn7-dev_7.1.1.5-1+cuda9.1_amd64.deb )
tensorflow 1.4.1 compiled from source with cuda 9.1 and cudnn 7.1.1

I have never downloaded or installed cudnn 7.0.5. "locate libcudnn.so.7.0" show nothing.

2018-03-05 11:06:53.859047: E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7005 (compatibility version 7000) but source was compiled with 7101 (compatibility version 7100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2018-03-05 11:06:53.859249: F tensorflow/core/kernels/conv_ops.cc:667] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
Aborted (core dumped)

**Comment by HorsonLiu** [comment]
Failed trying tensorflow-1.6.0.

**Comment by HorsonLiu** [comment]
I solved this problem by installing libcudnn 7.0.5 and compiling tensorflow with libcudnn 7.0.5.

**Comment by msis** [comment]
For people with similar issue issue in the future, I recommend installing the version that `tensorflow` was compiled with:
```shell
sudo apt install libcudnn7-dev=7.0.5.15-1+cuda9.1 libcudnn7=7.0.5.15-1+cuda9.1
```
And then freezing this version in apt so it will not automatically upgrade them:
```shell
sudo apt-mark hold libcudnn7 libcudnn7-dev
```

**Comment by unnir** [comment]
@msis 

I got this:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcudnn7-dev
E: Unable to locate package libcudnn7
```

**Comment by msis** [comment]
@unnir, how did you install `libcudnn*`? 
If you didn't add the nvidia repos to your apt sources, `apt` will not be able to locate them (they are not distributed by default)

**Comment by HorsonLiu** [comment]
@msis
![tf-compile-with-cudnn71](https://user-images.githubusercontent.com/4844122/38712332-7a2eb67a-3efd-11e8-93ce-7217721b813f.png)

It seems that tensorflow code cannot detect runtime CuDNN version correctly. Or maybe it is a bug of libcudnn 7.1 ?

**Comment by msis** [comment]
@HorsonLiu this error: 
> 2018-03-05 11:06:53.859047: E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7005 (compatibility version 7000) but source was compiled with 7101 (compatibility version 7100). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration. 

clearly says that you're tf is trying to load CuDNN 7.0.5, but it found 7.1.1 . 
Therefore, I suppose that you might have 2 versions of CuDNN installed when you were compiling it, and the earlier was automatically selected.

**Comment by cpoptic** [comment]
As of April 2018, and to save a lot of googling and investigating, TF 1.7 and 1.8 are not compatible with CUDA 9.1.  So you have to use 9.0 unfort.
Furthermore, you have to use cuDNN 7.0 NOT 7.1 (at least on a Windows 10 machine)
Don't make the mistake of installing cuDNN 7.1, as that is not yet supported.

If you've installed cuDNN 7.1, found it not to be compatible, and downloaded cuDNN 7.0, the CUDA 9.0 probably still has the old cuDNN 7.1 files installed in your CUDA\v9.0 folder.  There are 3 files in particular you must copy from your cuDNN 7.0 folder into the CUDA\v9.0 folder to replace the incorrect cuDNN 7.1 versions. cudnn64_7.dll, cudnn.h, & cudnn.lib

This is detailed in nVidia's pdf here (pages 6-7):  https://docs.nvidia.com/deeplearning/sdk/pdf/cuDNN-Installation-Guide.pdf

After that, follow the next step to set the CUDA_PATH environment variable.
Click OK, close, restart your machine, and should be good to go.

Downgrading those 3 files from the cuDNN 7.1 back to the 7.0 was what solved the issue for me.

**Comment by javacjh** [comment]
In my case,` ubuntu 16.04, py3.6`, I have to use `tf1.7`, but my conda package is `cudatoolkit  9.0` and `cudnn     7.3.1`. at first I get error as follows:
`2019-03-18 13:18:32.718709: E tensorflow/stream_executor/cuda/cuda_dnn.cc:396] Loaded runtime CuDNN library: 7301 (compatibility version 7300) but source was compiled with 7102 (compatibility version 7100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.`

if I simply use:
`conda install cudnn=7.1`

this may happen:
```
    cudatoolkit:         9.0-h13b8566_0       --> 8.0-3               
    cudnn:               7.3.1-cuda9.0_0      --> 7.1.3-cuda8.0_0
```

which is not compatible. 

So I changed the update into:
`**conda install tensorflow-gpu=1.7 cudatoolkit=9.0 cudnn=7.1**`

then it work. Hope this may help

**Comment by MukundaM** [comment]
> In my case,` ubuntu 16.04, py3.6`, I have to use `tf1.7`, but my conda package is `cudatoolkit 9.0` and `cudnn 7.3.1`. at first I get error as follows:
> `2019-03-18 13:18:32.718709: E tensorflow/stream_executor/cuda/cuda_dnn.cc:396] Loaded runtime CuDNN library: 7301 (compatibility version 7300) but source was compiled with 7102 (compatibility version 7100). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.`
> 
> if I simply use:
> `conda install cudnn=7.1`
> 
> this may happen:
> 
> ```
>     cudatoolkit:         9.0-h13b8566_0       --> 8.0-3               
>     cudnn:               7.3.1-cuda9.0_0      --> 7.1.3-cuda8.0_0
> ```
> which is not compatible.
> 
> So I changed the update into:
> `conda install tensorflow-gpu=1.7 cudatoolkit=9.0 cudnn=7.1`
> 
> then it work. Hope this may help

The last specified command solved the problem for me. Thanks @javacjh

**Comment by gsp2014** [comment]
> In my case,` ubuntu 16.04, py3.6`, I have to use `tf1.7`, but my conda package is `cudatoolkit 9.0` and `cudnn 7.3.1`. at first I get error as follows:
> `2019-03-18 13:18:32.718709: E tensorflow/stream_executor/cuda/cuda_dnn.cc:396] Loaded runtime CuDNN library: 7301 (compatibility version 7300) but source was compiled with 7102 (compatibility version 7100). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.`
> 
> if I simply use:
> `conda install cudnn=7.1`
> 
> this may happen:
> 
> ```
>     cudatoolkit:         9.0-h13b8566_0       --> 8.0-3               
>     cudnn:               7.3.1-cuda9.0_0      --> 7.1.3-cuda8.0_0
> ```
> 
> which is not compatible.
> 
> So I changed the update into:
> `conda install tensorflow-gpu=1.7 cudatoolkit=9.0 cudnn=7.1`
> 
> then it work. Hope this may help

This also solved my problem. Thanks!

**Comment by macqueen09** [comment]
I make cudnn from 730 to 704 ; 
still same problem
and then I change tensorflow from 1.5 to 1.9
It solved every problem
(I use CUDA 9)
