### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cubetastic33** [tensorflow/tensorflow#17629]
OS Platform and Distribution:
Linux Ubuntu 17.10

TensorFlow installed using pip
TensorFlow version: 1.6, with GPU support
Python Version: 3.6.4
CUDA version: 9.1
GPU model and memory: NVidia GEForce 940MX 2GB
command to reproduce:
~$ python3
>>> import tensorflow as tf
(basically run any tensorflow program to reproduce)

Problem:
Whenever you run a tensorflow program, you get a huge error log, but the main problem is this:
`ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`
So, the reason this is happening is because TensorFlow wants Cuda 9.0, but I have Cuda 9.1. This problem can be fixed by installing Cuda 9.0, but I have a few requests. Seeing that a couple of people have this problem (see https://github.com/tensorflow/tensorflow/issues/15604, https://github.com/tensorflow/tensorflow/issues/15817, https://github.com/tensorflow/tensorflow/issues/15817), I think that TensorFlow could be updated so that it works with Cuda 9.1 (but I think this issue is only with Ubuntu), or the following could be done:
Update the TensorFlow documentation, saying that you specifically need Cuda 9.0 for TensorFlow 1.6, and Cuda 8.0 for TensorFlow 1.4, and so on
And also, include this in the errors list at https://www.tensorflow.org/install/install_linux#common_installation_problems.

Edit: If a Pull Request is required to update the documentation, I am fine with doing that.

**Comment by mldm4** [comment]
I proposed a solution that worked for me in #15604

**Comment by cubetastic33** [comment]
@mldm4 I have also replied to you at 15604, the issue is not really that _I_ couldn't get it to work, I know what the problem is. I just need this to be fixed, or mentioned more specifically (it already is, just not that clearly) in the TensorFlow docs, and included in the common installation problems.

**Comment by gyanendro** [comment]
I also face the same problem with same configuration. But when I install cuda-9.0 version the issue got solved. I feel tensorflow-gpu version is using the cuda-9.0 version specifically.

**Comment by jamesredwards** [comment]
this has been a persistent problem since i first installed tensorflow. it seems totally unable to reference the latest cuda library and instead insists on a specific x.version.

i last managed to correct this with CUDA v8.0 by renaming than file libXXX.so.N to the version it was looking for.

**Comment by sebma** [comment]
@mldm4 Hi, do you mean to downgrade coda to v9-0 ?

Can you please be more specific and point your hyperlink to the comment with the proposed solution to gain people more time ?

**Comment by mikewlange** [comment]
I'm on my phone so have to be brief.. However when installing cuda 9.1 the folder created is labeled cuda9.1. All the instructions say to set your $PATH to yadda/yadda/cuda/yadda/bin. Changing the path to $yadda/yadda/cuda9.1 shits the bed and you get this error. If you've installed 9.1, leave it alone and follow the installation instructions step 2 here https://github.com/mikewlange/tensorflow-gpu-install-ubuntu-16.04

**Comment by sebma** [comment]
@mikewlange Thanks 😃

**Comment by mikewlange** [comment]
My pleasure. Hope you got it going!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by davidblumntcgeo** [comment]
jamesredwards said: "this has been a persistent problem since i first installed tensorflow. it seems totally unable to reference the latest cuda library and instead insists on a specific x.version.

i last managed to correct this with CUDA v8.0 by renaming than file libXXX.so.N to the version it was looking for."

@jamesredwards , or anyone else who is circumventing this error by renaming files, could you clarify how I'd do this for libcublas.so.9.0? I'm running cuda v8.0 on ubuntu 16.0.4, and tensorflow-gpu is erroring out with "ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory" . 

In the /usr/local/cuda/lib64/ directory I see libcublas.so , libcublas.so.8.0, libcublas.8.0.61 and libcublas.so.8.0.88. I can use sudo mv to rename these files. Just renaming libcublas.so.8.0 to libcublas.so.9.0 does not fix this error. Do I have to do something to the other files as well?

Is tensorflow looking for licublas.so.9.0 in a different location than /usr/local/cuda/lib64/ ?

Thanks for any help!

**Comment by dashsd** [comment]
This issue is related to Google's protobuf-compiler due to which tensorflow fails to find the shared object file, in this instance, libcublas.so.9.0. Even switching from CUDA 9.1 to 9.0 didn't help as tensorflow was still unable to locate the file.

Building the latest version of protobuf (3.5.0) from source didn't help either. What worked for me was to install the system-wide protobuf compiler through apt install protobuf-compiler on Ubuntu 16.04. And, install the python version through pip3 install protobuf. I am using CUDA 9.0 as 9.1 is not yet compatible with tensorflow's pre-built binary.

You can check the system-wide protobuf version using protoc --version which is 2.6.1 on 16.04. The protoc python version is 3.5.2.post1. Hope this helps. I had a similar issue using earlier versions of tensorflow and CUDA 8, and had documented this troubleshooting procedure. Using the same procedure, I am able to use tensorflow 1.8.0 too.

**Comment by sliute** [comment]
What worked for me was the process described at https://medium.com/@taylordenouden/installing-tensorflow-gpu-on-ubuntu-18-04-89a142325138 plus the protobuf bit @dashsd provided above. $PATH and $LD_LIBRARY_PATH all use '/usr/local/cuda-9.0'. The latter contains two separate entries, as described in https://github.com/tensorflow/tensorflow/issues/16750: one for /usr/local/cuda-9.0/extras/CUPTI/lib64 and another for /usr/local/cuda-9.0/lib64.

I use Ubuntu 18.04 on a Dell XPS 15" with NVIDIA GeForce GTX 1050 (GP107M), driver version 390.48. Tensorflow now runs on CUDA 9.0 and CUDNN 7.0.5.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by agilebean** [comment]
Hi @shivaniag > it would be great if you can reassign this issue if you have other priorities at the moment. 
This issue affects many users and is therefore critical. 
Thank you for your caring consideration!

**Comment by fay111101** [comment]
I have the same bug cuda9.2 cuDNN7.14

**Comment by agilebean** [comment]
Hi @shivaniag you would really help the community if you re-assign this issue...
To All:
Who would be willing to solve this issue?

**Comment by dashsd** [comment]
TF 1.9 is also built against cuda 9.0. So, it's not going to work with cuda 9.2 unless it is built from source. I had a hard time trying to do it. With all unsuccessful attempts, I switched back to 9.0 for now. However, on Antergos, it's available pre-built with 9.2. It was more convenient to me rather than building it from source. Sorry, there's not much help I can provide regarding this. Some poor souls have successfully built  it. Here's one of the links: https://github.com/fo40225/tensorflow-windows-wheel
Hope this helps!!!

**Comment by Parnia** [comment]
I have the same problem. CUDA 9.2, cuDNN7.1

**Comment by angeload** [comment]
Same problem here. CUDA 9.2, cudNN 7.1.4

**Comment by T0T4R4** [comment]
You have to re-compile tensorflow. The builds are not compatible with this combination yet.

**Comment by T0T4R4** [comment]
Yeah but what a pain.. I mean cuda 9.2 and cudnn 7.1 have been there for quite a while already...
Would be nice to have a ready package...

**Comment by dashsd** [comment]
Tensorflow 1.10 released and it still requires cuda 9.0!!!!!! Can someone confirm this?

<b>ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive</b>

**Comment by dhruvhacks** [comment]
Please refer [combinations of CUDA, CuDNN and Tensorflow](https://www.tensorflow.org/install/install_sources#tested_source_configurations).

This error happens majorly due to incorrect version combinations of Nvidia-driver, CUDA, CuDNN and Tensorflow-gpu
![image](https://user-images.githubusercontent.com/15031475/44293189-4d9a5c00-a2a7-11e8-9e5f-13463cb4f60c.png)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by VictorGallagher** [comment]
Yesterday I received this message.
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
This install is about 2 months old and had been under daily use. I had just completed a training run and ran the script again and received the message. Could someone point me in the right direction, to resolve this issue ? Also I am running this in a virtual environment.  
Ubuntu 18.04
Python 3.6.5
tensorflow-gpu==1.10.0
protobuf [required: >=3.4.0, installed: 3.6.0]
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)
nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 9.0, V9.0.176
 NVIDIA-SMI 396.51    Driver Version: 396.51

**Comment by mikewlange** [comment]
This this 

Snagged most of these words from stack overflow. I’ve run into similar. 

1. dir is wonky in your vm 
First check this:
LD_LIBRARY_PATH and make sure it’s  pointing to the correct location.

2. Check the permission of the folder /usr/local/cuda-9.0 it’s prob  wrong. Kinda common. 

This how #2 above handled it upon discovery.. 

I could not even cd to the folder. I changed the owner of the cuda-9.0from root to my-user-name and after that python was able to find the missing library.

3. If you still can’t jump to hyperspace,  try these things. 

This is almost always a missing path in your LD_LIBRARY_PATH. We know..   check it again and proceed. 

Find libcublas.so.9.0on your system (start looking under /usr/local). 


If you don't find it, then install the CUDA 9.0 Toolkit https://developer.nvidia.com/cuda-90-download-archive after you read the rest.. 

 NOTE:::::::  

with TF 1.5 you want 9.0 toolkit and not 9.1 as anyone who has installed this does that, don’t.  

If you have it, then update your LD_LIBRARY_PATH to point to the appropriate lib directory.

If you've done either of those and are now getting a similar looking error for a cudnn related library, then repeat that process for the CUDNN library.

https://developer.nvidia.com/cudnn

I think the latest version works. Tensorflow depends on both CUDA toolkit and the CuDNN library extension.

Note that you can install all of this in userspace too (sudo is typical, but not required).

**Comment by trananhdung17** [comment]
I got same error message when import tensorflow. And now, I solve this problem already.
Try apt-get install cuda-cublas-<cuda-version>
with cuda-version: 9-0, 9-1, etc...

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by VictorGallagher** [comment]
mikewlange, Thanks for pointing me in the right direction. Your resources worked. It seems that ''wonky'' is the right term to describe this problem with the pip virtual environment.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mechanicalAI** [comment]
We'll, if you don't want me help. @elithrar please some with a better solution?

**Comment by mechanicalAI** [comment]
I'm done helping people with this. I'm out --- cheers

**Comment by mechanicalAI** [comment]
> mikewlange, Thanks for pointing me in the right direction. Your resources worked. It seems that ''wonky'' is the right term to describe this problem with the pip virtual environment.



Thanks. I'm longer going to contribute to this. If you need help: https://github.com/mikewlange/tensorflow-gpu-install-ubuntu-16.04 otherwise, contact Nvidia and they'll tall you to figure it out!!!

**Comment by mechanicalAI** [comment]
And for the love of god. If you don't know why you need TF, stop using it!!! https://medium.com/@julsimon/apache-mxnet-support-in-keras-83de7dec46e5  convert you TF model to MXnet: https://github.com/Microsoft/MMdnn and them get to work!!!!

**Comment by mechanicalAI** [comment]
ALL READ: -

https://github.com/awslabs/keras-apache-mxnet is your TF replacement. you look back.... trust me. Been at this for 24 years (software engineering in general) and have built anything you've seen on the net. And guess what, without TF. Worked at hedge funds to build prop trading, search and rescue 100% autonomous drones, ios slot machines, er surgical tools, ect... 

All without TF. you are correct no CUDA needed either.

Honesty, anything you need to do, can do it PyTorch. Or, 
1. Python for data munging
2. https://pytorch.org/docs/stable/index.html to build your model

OR - easier...

3. Convert your TF models to **MXNet** -  
4. Find your converter: https://github.com/mechanicalAI/deep-learning-model-convertor https://github.com/Microsoft/MMdnn#conversion

OR, here is what sane people do who have to do this for a living....

1. Data pro? Munge that data like no-ones business?
2. Keras!!! OR https://github.com/mechanicalAI/autokeras or toss the GPU and learn 

1.. FInd the model yourself - example:
![image](https://user-images.githubusercontent.com/38701254/48317350-915ae400-e5be-11e8-847f-1a3fb708122a.png)

OR -

or https://github.com/mikewlange/KETTLE
or https://github.com/mechanicalAI/tpot OR you're best bet
https://github.com/mechanicalAI/h2o4gpu <- drop in replacement for ScikitLearn with with GPU support - https://github.com/mechanicalAI/h2o4gpu#requirements

Good luck and don't let your self get stuck for more than 1:30 min. Draw a line..

**Comment by cbasavaraj** [comment]
Hi all, 
I use PyTorch as much as possible, but for a particular project where i need to export a (Keras) model to tensorflowjs, I'm forced to use tf. The only solution which has worked well for me has been to build from source, after installing CUDA from the Ubuntu multiverse, as described here:

https://medium.com/@asmello/how-to-install-tensorflow-cuda-9-1-into-ubuntu-18-04-b645e769f01d

Bonne chance!

**Comment by KostasBitsakos** [comment]
February 2019, stil no concrete solution.

**Comment by Emile0205** [comment]
This issue seems to not be given enough attention. Why is tensorflow searching for libcublas.so.9.0 when CUDA 10.0 is installed. I installed tensorflow and ran some programs but it seemed most of the GPU memory wasn't being allocated to tensorflow so I rebooted my pc and then I received this error. This needs more attention.

**Comment by pauldadzie** [comment]
@Emile0205 I agree!
I tried using TF 1.12.0 with cuda 10.0, seemed to work fine. Then I change to TF-gpu 1.12.0 and I get this error. Like why is this still an issue almost a year later from the thread was created?
I read in another thread that this problem has been around since TF 1.5!

**Comment by jgmeyerucsd** [comment]
I had this problem trying to use tensor flow within a conda environment. tensorflow worked fine with the standard install in my base python 3.6, but not in my conda environment that I use for python. 
`import tensorflow as tf`
I got the same error. 

Here is what worked for me. I checked that the file did actually exist at /usr/local/cuda-9.0/lib64 and found that I have libcublas.so.9.0
Then I added the LD_LIBRARY_PATH to my ~/.bashrc:
`echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64/" >> ~/.bashrc`
Restarted my terminal, built conda environment:
'conda create -n tf-gpu python=3.6 tensorflow-gpu
source activate tf-gpu
conda install ipykernel
python -m ipykernel install --user --name --display-name "tf-gpu"
source deactivate
jupyter notebook'

and then made a new notebook that uses the tf-gpu kernel, and:
'import tensorflow as tf
h = tf.constant('hellow')
sess = tf.Session()
print(sess.run(h))'

Worked

**Comment by Evarin** [comment]
I had the same problem (with CUDA 9.2), and somehow got it solved ~magically using `conda install tensorflow-gpu` (after uninstalling it with pip), rather than `pip install tensorflow-gpu`. It does not sound like a read fix, but it may help :)

**Comment by chankim** [comment]
**Hi, folks! Why all this fuss? Read below!
If you just downgrade from cuda 9.2 to cuda 9.0 (and the driver too), you will have other problems when installing a new software packages. The solution is just to add the cuda 9.0 toolkit leaving the cuda 9.2 intact.**
After you have cuda 9.2 and the corresponding newest driver, you can just add cuda 9.0 toolkit using .run file install. While you additively install cuda 9.0 using .run file, say 'no' whey you are asked 'do you want to install the driver?' and the driver will remain intact and just cuda 9.0 will be installed. Cuda 9.0 works ok with the driver for cuda 9.2 (drivers are backward compatible). When you want to use tensorflow, just change the symbolic liink /usr/local/cuda to /usr/local/cuda-9.0 instead of /usr/local/cuda-9.2. 
If you are in utubn 16.04 or higher, you don't have to worry about the nouveau driver and nomodeset, nvidia-xconfig things. just run the .run file and it is installed cleanly. (install all the patches too).

See https://devtalk.nvidia.com/default/topic/493290/multiple-cuda-versions-can-they-coexist-/

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
