### ISSUE TITLE
Running tensorflow on GPU encountered ERROR: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ritaxiaotian** [tensorflow/tensorflow#18221]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I'm using the tensorflow object detection API
- **OS Platform and Distribution : Linux Ubuntu 16.04
- **TensorFlow installed from : pip install
- **TensorFlow version (use command below)**: 1.6
- **Python version**: python3
- **CUDA/cuDNN version**: Cuda 9.0
- **GPU model and memory**: GTX 1060
- **Exact command to reproduce**: import tensorflow

ERROR:
import tensorflow
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help

**Comment by JonnoFTW** [comment]
Have you done this:

```bash
export LD_LIBRARY_PATH=/usr/local/cuda/lib64
```
Or set it to the location where lubcublas.so actually is?

**Comment by dinhvankiet124** [comment]
Still error

```
export PATH="/usr/local/cuda/bin:$PATH"
export CUDA_HOME="/usr/local/cuda"
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="/usr/local/cuda/extras/CUPTI/lib64:LD_LIBRARY_PATH"
```

**Comment by ritaxiaotian** [comment]
Hi all, thanks for your answers. I've searched for solutions before I posted the issue. So I've tried installing Cuda 9.0, I actually have file "libcublas.so.9.0" and I tried "export LD_LIBRARY_PATH=/usr/local/cuda/lib64"


In the end, I solved the problem by reinstalling Cuda 9.0, installing both tf 1.4,1.5 and 1.6 on the computer and 
in the terminal, type:
$ sudo gedit /etc/profile

Then, add these instructions at the end of the file:
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64\
                                                   ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

I followed instructions in this article: https://askubuntu.com/questions/563764/usb-devices-showing-as-read-only

Then, I rebooted the machine. Problem solved. I'm not sure which step worked in this process though.

Thanks.
