### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by OlofNiko** [tensorflow/tensorflow#18237]
I had installed CUDA toolkit version 9.1.85, cuDNN v7.1.2  for CUDA 9.1 and tensorflow 1.6 from [this link](https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.6.0-cp36-cp36m-linux_x86_64.whl
)

When i try import tensorflow i get the following error.

(tensorflow) akshith@Akshith:~$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/akshith/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/akshith/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/akshith/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/akshith/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/akshith/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> 

how to solve this?
TIA

**Comment by jameschartouni** [comment]
I have the same issue with tensorflow 1.7

**Comment by jwfromm** [comment]
The prebuilt tensorflow binaries only support CUDA 9.0. If you want to use 9.1, you'll have to build tensorflow from source. I'd recommend just using CUDA 9.0 though, since it's easier and you won't notice any functional differences :).

**Comment by Herlderlord** [comment]
Will TF support CUDA 9.1 "natively" ? It could be great to just have to do pip install and get TF compatible with CUDA 9.1.

**Comment by rohan100jain** [comment]
@chsigg might be able to answer that question.

**Comment by strelec** [comment]
Could you not simply depend on the major version of the library, that is, libcublas.so.9 instead of libcublas.so.9.0? The api should stay compatible, as far as I know.

**Comment by OlofNiko** [comment]
I had uninstalled cuda 9.1 and trying to install cuda 9.0 and i got this error

akshith@Akshith:~/Downloads$ sudo apt-get install cuda-9-0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  cuda-cublas-9-0 cuda-cublas-dev-9-0 cuda-cufft-9-0 cuda-cufft-dev-9-0
  cuda-curand-9-0 cuda-curand-dev-9-0 cuda-cusolver-9-0 cuda-cusolver-dev-9-0
  cuda-cusparse-9-0 cuda-cusparse-dev-9-0 cuda-demo-suite-9-0
  cuda-documentation-9-0 cuda-drivers cuda-libraries-9-0
  cuda-libraries-dev-9-0 cuda-npp-9-0 cuda-npp-dev-9-0 cuda-nvgraph-9-0
  cuda-nvgraph-dev-9-0 cuda-nvml-dev-9-0 cuda-nvrtc-9-0 cuda-nvrtc-dev-9-0
  cuda-runtime-9-0 cuda-samples-9-0 cuda-toolkit-9-0 cuda-visual-tools-9-0
  freeglut3 freeglut3-dev libcuda1-387 libdrm-dev libgl1-mesa-dev
  libglu1-mesa-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev
  libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev libxcb-shape0-dev
  libxcb-sync-dev libxcb-xfixes0-dev libxmu-dev libxmu-headers
  libxshmfence-dev libxt-dev libxxf86vm-dev mesa-common-dev nvidia-387
  nvidia-387-dev nvidia-390-dev nvidia-modprobe nvidia-opencl-icd-387
  x11proto-dri2-dev x11proto-gl-dev x11proto-xf86vidmode-dev
Suggested packages:
  libxt-doc
The following NEW packages will be installed:
  cuda-9-0 cuda-cublas-9-0 cuda-cublas-dev-9-0 cuda-cufft-9-0
  cuda-cufft-dev-9-0 cuda-curand-9-0 cuda-curand-dev-9-0 cuda-cusolver-9-0
  cuda-cusolver-dev-9-0 cuda-cusparse-9-0 cuda-cusparse-dev-9-0
  cuda-demo-suite-9-0 cuda-documentation-9-0 cuda-drivers cuda-libraries-9-0
  cuda-libraries-dev-9-0 cuda-npp-9-0 cuda-npp-dev-9-0 cuda-nvgraph-9-0
  cuda-nvgraph-dev-9-0 cuda-nvml-dev-9-0 cuda-nvrtc-9-0 cuda-nvrtc-dev-9-0
  cuda-runtime-9-0 cuda-samples-9-0 cuda-toolkit-9-0 cuda-visual-tools-9-0
  freeglut3 freeglut3-dev libcuda1-387 libdrm-dev libgl1-mesa-dev
  libglu1-mesa-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev
  libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev libxcb-shape0-dev
  libxcb-sync-dev libxcb-xfixes0-dev libxmu-dev libxmu-headers
  libxshmfence-dev libxt-dev libxxf86vm-dev mesa-common-dev nvidia-387
  nvidia-387-dev nvidia-390-dev nvidia-modprobe nvidia-opencl-icd-387
  x11proto-dri2-dev x11proto-gl-dev x11proto-xf86vidmode-dev
0 upgraded, 56 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1,055 MB of archives.
After this operation, 2,192 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 file:/var/cuda-repo-9-0-local  cuda-nvrtc-9-0 9.0.176-1 [6,348 kB]
Get:2 file:/var/cuda-repo-9-0-local  cuda-nvrtc-dev-9-0 9.0.176-1 [9,334 B]
Get:3 file:/var/cuda-repo-9-0-local  cuda-cusolver-9-0 9.0.176-1 [26.2 MB]
Get:4 file:/var/cuda-repo-9-0-local  cuda-cusolver-dev-9-0 9.0.176-1 [5,317 kB]
Get:5 file:/var/cuda-repo-9-0-local  cuda-cublas-9-0 9.0.176-1 [25.0 MB]
Get:6 file:/var/cuda-repo-9-0-local  cuda-cublas-dev-9-0 9.0.176-1 [49.4 MB]
Get:7 file:/var/cuda-repo-9-0-local  cuda-cufft-9-0 9.0.176-1 [84.1 MB]
Get:8 file:/var/cuda-repo-9-0-local  cuda-cufft-dev-9-0 9.0.176-1 [73.7 MB]
Get:9 file:/var/cuda-repo-9-0-local  cuda-curand-9-0 9.0.176-1 [38.8 MB]
Get:10 file:/var/cuda-repo-9-0-local  cuda-curand-dev-9-0 9.0.176-1 [57.9 MB]
Get:11 file:/var/cuda-repo-9-0-local  cuda-cusparse-9-0 9.0.176-1 [25.2 MB]
Get:12 file:/var/cuda-repo-9-0-local  cuda-cusparse-dev-9-0 9.0.176-1 [25.3 MB]
Get:13 file:/var/cuda-repo-9-0-local  cuda-npp-9-0 9.0.176-1 [46.6 MB]         
Get:14 file:/var/cuda-repo-9-0-local  cuda-npp-dev-9-0 9.0.176-1 [46.6 MB]     
Get:15 file:/var/cuda-repo-9-0-local  cuda-nvgraph-9-0 9.0.176-1 [6,081 kB]    
Get:16 file:/var/cuda-repo-9-0-local  cuda-nvgraph-dev-9-0 9.0.176-1 [5,658 kB]
Get:17 file:/var/cuda-repo-9-0-local  cuda-samples-9-0 9.0.176-1 [75.9 MB]     
Get:18 file:/var/cuda-repo-9-0-local  cuda-documentation-9-0 9.0.176-1 [53.1 MB]
Get:19 file:/var/cuda-repo-9-0-local  cuda-libraries-dev-9-0 9.0.176-1 [2,596 B]
Get:20 file:/var/cuda-repo-9-0-local  cuda-nvml-dev-9-0 9.0.176-1 [47.6 kB]    
Get:21 file:/var/cuda-repo-9-0-local  cuda-visual-tools-9-0 9.0.176-1 [398 MB] 
Get:22 file:/var/cuda-repo-9-0-local  cuda-toolkit-9-0 9.0.176-1 [2,836 B]     
Get:23 file:/var/cuda-repo-9-1-local  nvidia-modprobe 387.26-0ubuntu1 [17.2 kB]
Err:23 file:/var/cuda-repo-9-1-local  nvidia-modprobe 387.26-0ubuntu1          
  File not found - /var/cuda-repo-9-1-local/./nvidia-modprobe_387.26-0ubuntu1_amd64.deb (2: No such file or directory)
Get:24 file:/var/cuda-repo-9-1-local  cuda-drivers 387.26-1 [2,390 B]          
Err:24 file:/var/cuda-repo-9-1-local  cuda-drivers 387.26-1                    
  File not found - /var/cuda-repo-9-1-local/./cuda-drivers_387.26-1_amd64.deb (2: No such file or directory)
Get:25 file:/var/cuda-repo-9-0-local  cuda-libraries-9-0 9.0.176-1 [2,566 B]   
Get:26 file:/var/cuda-repo-9-0-local  cuda-runtime-9-0 9.0.176-1 [2,526 B]     
Get:27 file:/var/cuda-repo-9-0-local  cuda-demo-suite-9-0 9.0.176-1 [3,880 kB] 
Get:28 file:/var/cuda-repo-9-0-local  cuda-9-0 9.0.176-1 [2,552 B]             
E: Failed to fetch file:/var/cuda-repo-9-1-local/./nvidia-modprobe_387.26-0ubuntu1_amd64.deb  File not found - /var/cuda-repo-9-1-local/./nvidia-modprobe_387.26-0ubuntu1_amd64.deb (2: No such file or directory)
E: Failed to fetch file:/var/cuda-repo-9-1-local/./cuda-drivers_387.26-1_amd64.deb  File not found - /var/cuda-repo-9-1-local/./cuda-drivers_387.26-1_amd64.deb (2: No such file or directory)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

How to resolve this error?

**Comment by jianqin123** [comment]
I am facing the same problem。This problem is encountered when executing a python script using ssh to connect to a server.Running python script locally works well.

**Comment by strelec** [comment]
You can just compile tensorflow from source. It is not rocket science.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 108 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 124 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 140 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MingyaoLiu** [comment]
I had this issue when trying to build from source on ubuntu 18.10, tf r1.12, cuda 10 (error just say .so.10.0 not .sp.9.0.
I got it working at last, thw whl file i attached in the other thread. Way i fixed it is to install cuda 10 with apt and also with the run file, then reboot... may not apply to your issue tho.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Honghe** [comment]
I am facing the same problem. Running python script locally works well. but when:
- execute a python script using ssh to connect to a server.
- execute a python script in `tmux`.

**Comment by tilakrayal** [comment]
@OlofNiko ,
We see that you are using older version of tensorflow (1.x) which is not actively supported. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!
