### ISSUE TITLE
TF hangs with distributed mode

### ISSUE THREAD

**Issue by sj6077** [tensorflow/tensorflow#18737]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.5
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.5.4
- **GCC/Compiler version (if compiling from source)**:
5.4.0
- **CUDA/cuDNN version**:
9.0/7
- **GPU model and memory**:
TitanXP, 12G
- **Exact command to reproduce**:

### Describe the problem
When I run skip_thoughts model with distributed mode(2 workers in a machine, 2 GPUs per worker), tf hangs with linux condition variable error.

### Source code / logs
Below is the gdb log.
`Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fd44d2e891c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007fd45b021ecb in nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec) ()
   from /home/soojeong/expdir_parallax/venv/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x00007fd45b0217a1 in nsync::nsync_sem_wait_with_cancel_(nsync::waiter*, timespec, nsync::nsync_note_s_*) ()
   from /home/soojeong/expdir_parallax/venv/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x00007fd45b01ec12 in nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) ()
   from /home/soojeong/expdir_parallax/venv/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#5  0x00007fd45b01f0f3 in nsync::nsync_cv_wait_with_deadline(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*, timespec, nsync::nsync_note_s_*) ()
   from /home/soojeong/expdir_parallax/venv/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007fd45879da1b in tensorflow::(anonymous namespace)::WaitForNotification(tensorflow::CallOptions*, long long, tensorflow::Notification*) ()
   from /home/soojeong/expdir_parallax/venv/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x00007fd45879e313 in tensorflow::LocalMaster::RunStep(tensorflow::CallOptions*, tensorflow::RunStepRequestWrapper*, tensorflow::MutableRunStepResponseWrapper*) ()
   from /home/soojeong/expdir_parallax/venv/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so`

**Comment by sj6077** [comment]
I found master sessions are created more than # workers + #ps, is it okay?
`2018-04-21 00:34:14.953222: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session b6a0c9c95637b2bf with config: allow_soft_placement: true operation_timeout_in_ms: 600000
2018-04-21 00:34:16.310345: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x427e8e0
2018-04-21 00:34:44.031831: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session 76c3e3934cf937ae with config: allow_soft_placement: true operation_timeout_in_ms: 600000
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: encoder/gru_cell/gates/w_h, encoder/gru_cell/candidate/u, decoder_pre/gru_cell/gates/w_h, decoder_pre/gru_cell/candidate/u, decoder_post/gru_cell/gates/w_h, decoder_post/gru_cell/candidate/u, ready: None
2018-04-21 00:35:15.087387: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session c4f0640d9b337f3b with config: allow_soft_placement: true operation_timeout_in_ms: 600000
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: encoder/gru_cell/gates/w_h, encoder/gru_cell/candidate/u, decoder_pre/gru_cell/gates/w_h, decoder_pre/gru_cell/candidate/u, decoder_post/gru_cell/gates/w_h, decoder_post/gru_cell/candidate/u, ready: None
2018-04-21 00:35:46.098996: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session 9369768b7b043c22 with config: allow_soft_placement: true operation_timeout_in_ms: 600000
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: encoder/gru_cell/gates/w_h, encoder/gru_cell/candidate/u, decoder_pre/gru_cell/gates/w_h, decoder_pre/gru_cell/candidate/u, ready: None
2018-04-21 00:36:17.038228: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session 7efeddd92fe6182f with config: allow_soft_placement: true operation_timeout_in_ms: 600000
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: encoder/gru_cell/gates/w_h, encoder/gru_cell/candidate/u, decoder_pre/gru_cell/gates/w_h, ready: None
2018-04-21 00:36:48.031089: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session 6969f6e188a265b0 with config: allow_soft_placement: true operation_timeout_in_ms: 600000
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: encoder/gru_cell/gates/w_h, encoder/gru_cell/candidate/u, decoder_pre/gru_cell/gates/w_h, ready: None
2018-04-21 00:37:19.015507: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session ac9ea7dbf55378a3 with config: allow_soft_placement: true operation_timeout_in_ms: 600000
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: encoder/gru_cell/gates/w_h, ready: None
2018-04-21 00:37:50.067835: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session 22291f96c1f27e60 with config: allow_soft_placement: true operation_timeout_in_ms: 600000
2018-04-21 00:37:50.692820: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x4ead290
INFO:140062530406144:RDAG:RunOp: Created MonitoredTrainingSession on grpc://localhost:55501
INFO:140062530406144:RDAG:iteration 0 start`

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 80 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 95 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rohan100jain** [comment]
Please provide a pointer to the code you're running so that I can try and reproduce it.

**Comment by sj6077** [comment]
I think this issue is gone. I'll close it.

**Comment by lxn179208** [comment]
how do you solve it?

**Comment by lxn179208** [comment]
@sj6077 how do you solve it?

**Comment by sj6077** [comment]
@lxn179208 I don't remember the issue exactly, but if you suffer similar problems you can check device of your variables by `log_device_placement` option in SessionConfig. Sometimes, some variables are assigned to each worker, then global init is not working.
