### ISSUE TITLE
Difference in output between CPU and GPU 

### ISSUE THREAD

**Issue by annemenini** [tensorflow/tensorflow#19200]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: TF 1.7 and TF 1.8 (v1.8.0-0-g93bc2e2072 1.8.0)
- **Python version**: Python 3.5.4
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: CUDA 9.0, cudnn 7.0.5
- **GPU model and memory**: GPU GTX1080
- **Exact command to reproduce**: n/a

**Problem**
I see a very different output when executing a training on CPU vs. GPU. The problem does not seem to be related to initialization or numerical precision (see investigation): same code, same data, same machine, just switching between GPU and CPU execution by adding `os.environ["CUDA_VISIBLE_DEVICES"]=""` gives fundamentally different results (the loss function differs by several orders of magnitude at the end of the first run of the first epoch).

**Investigation**
I gave names to all the variables and operations in order to track what was the first operation in the graph where the results differ between CPU and GPU execution. I could actually identify it. In my case, it is a `tf.multiply` (pixel-wise multiplication of complex64 Tensors). I can see that the inputs of that operation are identical (+/- numerical precision), while the outputs are really different: the magnitude of the complex output is consistent but the phase is very different (the real and imaginary parts are both very different). I can tell that the CPU output is the right one.

Unfortunately, I am not able to reproduce the problem in a unit test (but am still working on it). If I feed the same inputs to `tf.multiply` in a unit test, the CPU and GPU outputs are consistent. I am wondering if the CPU/GPU execution may be affecting the order in which the graph is build/executed, and if there may be interferences somehow.

**Seeding and reproducibility**
Regarding the seeds, they are all set (graph wise and operation wise), but anyway, the diverging operation does not depend on a seed in this case.

The problem is reproducible from one run to the other.

**Environment dependency**
The problem occurs with both TF 1.7 and TF 1.8. However, if I switch the environment (same machine, same OS, same code, same data, but python 2.7, TF 1.4), the problem disappears, i.e. the CPU and GPU outputs are consistent.

Any idea or debugging experiment suggestion is very welcome.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by annemenini** [comment]
I updated the original post (info were there but not in the right format)

**Comment by annemenini** [comment]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: TF 1.7 and TF 1.8 (v1.8.0-0-g93bc2e2072 1.8.0)
- **Python version**: Python 3.5.4
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: CUDA 9.0, cudnn 7.0.5
- **GPU model and memory**: GPU GTX1080
- **Exact command to reproduce**: n/a

**Comment by angersson** [comment]
@zheng-xq Can you take a look at this?

**Comment by zheng-xq** [comment]
It will be very helpful to have a small repro case.

CPU and GPU are known to produce slightly different results. For each operation, if the inputs are identical, the output should only have lsb difference. So if you observe large difference from a single operation, not a sequence of operations, it might be a bug somewhere. Otherwise, this is somewhat expected.

**Comment by angersson** [comment]
@annemenini Can you provide code + data to reproduce this?

**Comment by annemenini** [comment]
I unfortunately cannot share the full code and do not manage to reproduce to problem in a simple unit test so far.

To clarify, the difference I observe out of a single operation (tf.multiply) is significant: with the notation A .* B = C, here are the values I observe on one randomly picked element of the tensor:

On CPU:
A = -0.2314 + 0.2525i
B = -0.0212 - 0.3013i
**C = 0.0810 + 0.0644i**

On GPU:
A = -0.2314 + 0.2525i
B = -0.0212 - 0.3013i
**C = -0.0712 + 0.0751i**

The mismatch disappear if I execute the same operation on it own in a simpler graph (hence why I don't manage to reproduce the problem in a unit test).

**Comment by tensorflowbutler** [comment]
Nagging Assignees @zheng-xq, @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bdenoun** [comment]
Hi guys, I have exactly the same issue when running the same code on CPU and on GPU ... my guess is that computation on some operations are numerically instable on GPU (but I am not a pro in numerical computation ....). 
Here is first my setup :    
**I am on Ubuntu 16.04.4 LTS with Tensorflow built from source (I have both 1.7 and 1.8). I have both python version (2.7 and 3.5), bazel version is 0.14, the GCC compiler is 5.4, CUDA is 9.2 and cudnn 7.1.4. I have 2 GPUs, both are NVIDIA GTX 1080Ti.**
I created a snippet that easily reproduce my issue.

_**ON CPU**_

```
import os
os.environ["CUDA_VISIBLE_DEVICES"]=""
import numpy as np
import tensorflow as tf
data = np.array(
    [np.array([np.arange(1, 13 * 8 + 1).reshape(13, 8, 1) * i / 12.0 for i in range(1, 13)]) * j / 32.0 for j in
     range(1, 33)]).astype(np.float32)

input_placeholder = tf.placeholder("float32", shape=(None, 12, 13, 8, 1))

res = tf.transpose(input_placeholder, [1, 0, 2, 3, 4])

weights = tf.ones([8, 8, 16, 1])
biases = tf.ones([16])

deconv = tf.map_fn(lambda x: tf.nn.bias_add(tf.nn.conv2d_transpose(x, weights, strides=[1, 1, 1, 1], padding='VALID', output_shape=[32, 20, 15, 16]), biases), res)

sess = tf.Session()

with sess.as_default():
   output = sess.run(deconv, feed_dict={input_placeholder: data})

transposed = np.transpose(fin, [1, 0, 2, 3, 4])
print(transposed)
```
Just for some clarity issue, I print the end of what the snippet outputs **each time**: 
```
[[[  2.          2.          2.        ...   2.          2.
       2.       ]
    [  4.          4.          4.        ...   4.          4.
       4.       ]
    [  7.          7.          7.        ...   7.          7.
       7.       ]
    ...
    [ 22.         22.         22.        ...  22.         22.
      22.       ]
    [ 16.         16.         16.        ...  16.         16.
      16.       ]
    [  9.          9.          9.        ...   9.          9.
       9.       ]]

   [[ 11.         11.         11.        ...  11.         11.
      11.       ]
    [ 23.         23.         23.        ...  23.         23.
      23.       ]
    [ 37.         37.         37.        ...  37.         37.
      37.       ]
    ...
    [ 67.         67.         67.        ...  67.         67.
      67.       ]
    [ 47.         47.         47.        ...  47.         47.
      47.       ]
    [ 25.         25.         25.        ...  25.         25.
      25.       ]]

   [[ 28.         28.         28.        ...  28.         28.
      28.       ]
    [ 58.         58.         58.        ...  58.         58.
      58.       ]
    [ 91.         91.         91.        ...  91.         91.
      91.       ]
    ...
    [136.        136.        136.        ... 136.        136.
     136.       ]
    [ 94.         94.         94.        ...  94.         94.
      94.       ]
    [ 49.         49.         49.        ...  49.         49.
      49.       ]]

   ...

   [[268.        268.        268.        ... 268.        268.
     268.       ]
    [538.        538.        538.        ... 538.        538.
     538.       ]
    [811.        811.        811.        ... 811.        811.
     811.       ]
    ...
    [856.        856.        856.        ... 856.        856.
     856.       ]
    [574.        574.        574.        ... 574.        574.
     574.       ]
    [289.        289.        289.        ... 289.        289.
     289.       ]]

   [[187.        187.        187.        ... 187.        187.
     187.       ]
    [375.        375.        375.        ... 375.        375.
     375.       ]
    [565.        565.        565.        ... 565.        565.
     565.       ]
    ...
    [595.        595.        595.        ... 595.        595.
     595.       ]
    [399.        399.        399.        ... 399.        399.
     399.       ]
    [201.        201.        201.        ... 201.        201.
     201.       ]]

   [[ 98.         98.         98.        ...  98.         98.
      98.       ]
    [196.        196.        196.        ... 196.        196.
     196.       ]
    [295.        295.        295.        ... 295.        295.
     295.       ]
    ...
    [310.        310.        310.        ... 310.        310.
     310.       ]
    [208.        208.        208.        ... 208.        208.
     208.       ]
    [105.        105.        105.        ... 105.        105.
     105.       ]]]]]
```


**_ON GPU_**

```
import numpy as np
import tensorflow as tf
data = np.array(
    [np.array([np.arange(1, 13 * 8 + 1).reshape(13, 8, 1) * i / 12.0 for i in range(1, 13)]) * j / 32.0 for j in
     range(1, 33)]).astype(np.float32)

input_placeholder = tf.placeholder("float32", shape=(None, 12, 13, 8, 1))

res = tf.transpose(input_placeholder, [1, 0, 2, 3, 4])

weights = tf.ones([8, 8, 16, 1])
biases = tf.ones([16])

deconv = tf.map_fn(lambda x: tf.nn.bias_add(tf.nn.conv2d_transpose(x, weights, strides=[1, 1, 1, 1], padding='VALID', output_shape=[32, 20, 15, 16]), biases), res)

sess = tf.Session()

with sess.as_default():
   output = sess.run(deconv, feed_dict={input_placeholder: data})

transposed = np.transpose(fin, [1, 0, 2, 3, 4])
print(transposed)
```
It is exactly the same code (except the cuda visible command), and **sometimes** I have exactly the same aforementioned output, **but I also have these** outputs:

```
[[[  1.9999084   1.9999084   1.9999084 ...   1.9999084   1.9999084
       1.9999084]
    [  4.          4.          4.        ...   4.          4.
       4.       ]
    [  7.          7.          7.        ...   7.          7.
       7.       ]
    ...
    [ 22.         22.         22.        ...  22.         22.
      22.       ]
    [ 15.9999695  15.9999695  15.9999695 ...  15.9999695  15.9999695
      15.9999695]
    [  8.999954    8.999954    8.999954  ...   8.999954    8.999954
       8.999954 ]]

   [[ 10.999954   10.999954   10.999954  ...  10.999954   10.999954
      10.999954 ]
    [ 22.99997    22.99997    22.99997   ...  22.99997    22.99997
      22.99997  ]
    [ 37.00006    37.00006    37.00006   ...  37.00006    37.00006
      37.00006  ]
    ...
    [ 67.00003    67.00003    67.00003   ...  67.00003    67.00003
      67.00003  ]
    [ 46.99997    46.99997    46.99997   ...  46.99997    46.99997
      46.99997  ]
    [ 25.         25.         25.        ...  25.         25.
      25.       ]]

   [[ 27.999954   27.999954   27.999954  ...  27.999954   27.999954
      27.999954 ]
    [ 57.99997    57.99997    57.99997   ...  57.99997    57.99997
      57.99997  ]
    [ 90.999985   90.999985   90.999985  ...  90.999985   90.999985
      90.999985 ]
    ...
    [136.        136.        136.        ... 136.        136.
     136.       ]
    [ 93.999985   93.999985   93.999985  ...  93.999985   93.999985
      93.999985 ]
    [ 48.999954   48.999954   48.999954  ...  48.999954   48.999954
      48.999954 ]]

   ...

   [[268.        268.        268.        ... 268.        268.
     268.       ]
    [538.        538.        538.        ... 538.        538.
     538.       ]
    [810.99994   810.99994   810.99994   ... 810.99994   810.99994
     810.99994  ]
    ...
    [856.        856.        856.        ... 856.        856.
     856.       ]
    [574.        574.        574.        ... 574.        574.
     574.       ]
    [289.0001    289.0001    289.0001    ... 289.0001    289.0001
     289.0001   ]]

   [[186.99992   186.99992   186.99992   ... 186.99992   186.99992
     186.99992  ]
    [374.99997   374.99997   374.99997   ... 374.99997   374.99997
     374.99997  ]
    [565.        565.        565.        ... 565.        565.
     565.       ]
    ...
    [595.        595.        595.        ... 595.        595.
     595.       ]
    [399.00006   399.00006   399.00006   ... 399.00006   399.00006
     399.00006  ]
    [201.00008   201.00008   201.00008   ... 201.00008   201.00008
     201.00008  ]]

   [[ 97.99998    97.99998    97.99998   ...  97.99998    97.99998
      97.99998  ]
    [195.99997   195.99997   195.99997   ... 195.99997   195.99997
     195.99997  ]
    [295.        295.        295.        ... 295.        295.
     295.       ]
    ...
    [310.00003   310.00003   310.00003   ... 310.00003   310.00003
     310.00003  ]
    [208.00012   208.00012   208.00012   ... 208.00012   208.00012
     208.00012  ]
    [105.00009   105.00009   105.00009   ... 105.00009   105.00009
     105.00009  ]]]]]
```
or 
```
  [[[  1.9999237   1.9999237   1.9999237 ...   1.9999237   1.9999237
       1.9999237]
    [  4.          4.          4.        ...   4.          4.
       4.       ]
    [  7.          7.          7.        ...   7.          7.
       7.       ]
    ...
    [ 22.         22.         22.        ...  22.         22.
      22.       ]
    [ 16.         16.         16.        ...  16.         16.
      16.       ]
    [  9.000046    9.000046    9.000046  ...   9.000046    9.000046
       9.000046 ]]

   [[ 11.000015   11.000015   11.000015  ...  11.000015   11.000015
      11.000015 ]
    [ 22.99997    22.99997    22.99997   ...  22.99997    22.99997
      22.99997  ]
    [ 37.00006    37.00006    37.00006   ...  37.00006    37.00006
      37.00006  ]
    ...
    [ 67.         67.         67.        ...  67.         67.
      67.       ]
    [ 47.00006    47.00006    47.00006   ...  47.00006    47.00006
      47.00006  ]
    [ 25.000076   25.000076   25.000076  ...  25.000076   25.000076
      25.000076 ]]

   [[ 27.999962   27.999962   27.999962  ...  27.999962   27.999962
      27.999962 ]
    [ 57.99997    57.99997    57.99997   ...  57.99997    57.99997
      57.99997  ]
    [ 91.00003    91.00003    91.00003   ...  91.00003    91.00003
      91.00003  ]
    ...
    [136.00002   136.00002   136.00002   ... 136.00002   136.00002
     136.00002  ]
    [ 94.000046   94.000046   94.000046  ...  94.000046   94.000046
      94.000046 ]
    [ 49.00006    49.00006    49.00006   ...  49.00006    49.00006
      49.00006  ]]

   ...

   [[268.00006   268.00006   268.00006   ... 268.00006   268.00006
     268.00006  ]
    [538.        538.        538.        ... 538.        538.
     538.       ]
    [810.9999    810.9999    810.9999    ... 810.9999    810.9999
     810.9999   ]
    ...
    [856.        856.        856.        ... 856.        856.
     856.       ]
    [573.99994   573.99994   573.99994   ... 573.99994   573.99994
     573.99994  ]
    [289.        289.        289.        ... 289.        289.
     289.       ]]

   [[186.99997   186.99997   186.99997   ... 186.99997   186.99997
     186.99997  ]
    [374.99997   374.99997   374.99997   ... 374.99997   374.99997
     374.99997  ]
    [565.        565.        565.        ... 565.        565.
     565.       ]
    ...
    [595.        595.        595.        ... 595.        595.
     595.       ]
    [398.99994   398.99994   398.99994   ... 398.99994   398.99994
     398.99994  ]
    [200.99997   200.99997   200.99997   ... 200.99997   200.99997
     200.99997  ]]

   [[ 98.00005    98.00005    98.00005   ...  98.00005    98.00005
      98.00005  ]
    [195.99998   195.99998   195.99998   ... 195.99998   195.99998
     195.99998  ]
    [294.99994   294.99994   294.99994   ... 294.99994   294.99994
     294.99994  ]
    ...
    [309.99997   309.99997   309.99997   ... 309.99997   309.99997
     309.99997  ]
    [207.99997   207.99997   207.99997   ... 207.99997   207.99997
     207.99997  ]
    [104.99999   104.99999   104.99999   ... 104.99999   104.99999
     104.99999  ]]]]]
```

I also tried to run the command inside a ```tf.device('/cpu:0')``` but I still got the same behavior ...

**Comment by tensorflowbutler** [comment]
Nagging Assignees @zheng-xq, @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by trungpx** [comment]
Hello everyone,

I got the same issue. When I tried to train and test a simple CNN model (code below) with keras. Then when I run model on CPU it got the validation accuracy max: 78%, while GPU gave the result: 75% only. I run it with 25 epochs.
Source code as following:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

# Part 1 - Creating the model
# Initialising the CNN
classifier = Sequential()
# Step 1 - Convolution
classifier.add(Conv2D(32,(3,3),input_shape=(64,64,3),activation='relu'))
# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size=(2,2)))
# Adding a second convolutional layer
classifier.add(Conv2D(32,(3,3),activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))
# Step 3 - Flattening
classifier.add(Flatten())
# Step 4 - Full connection
classifier.add(Dense(units=128,activation='relu'))
classifier.add(Dense(units=1,activation='sigmoid'))
# Compiling the CNN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# Part 2 - Fitting the CNN to the images
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)
training_set = train_datagen.flow_from_directory('dataset/training_set',target_size=(64,64),batch_size=32,class_mode='binary')
test_set = test_datagen.flow_from_directory('dataset/test_set',target_size=(64,64),batch_size=32,class_mode='binary')

# Let's fit the data to our model
classifier.fit_generator(training_set,steps_per_epoch=8000,epochs=25,validation_data=test_set,validation_steps=2000)

# Part 3 - Making new predictions from our trained model
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('dataset/single_prediction/cat_or_dog_1.jpg',target_size=(64,64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image,axis=0)
result = classifier.predict(test_image)
training_set.class_indices
if result[0][0]==1:
    prediction = 'dog'
    print('This is a dog!')
else:
    prediction = 'cat'
    print('This is a cat')

# End CNN example

The difference is about 3-4%.  I have tried serveral times but the behaviour is unchanged. 
So, If you want to try an image classification model (cats vs dogs), then I invite you to use code and try run on your CPU, GPU to verify. The data for model [here ](https://drive.google.com/drive/folders/1XaFM8BJFligrqeQdE-_5Id0V_SubJAZe?usp=sharing)and the origional source code [here](https://becominghuman.ai/building-an-image-classifier-using-deep-learning-in-python-totally-from-a-beginners-perspective-be8dbaf22dd8).

**Comment by arogozhnikov** [comment]
I believe, this issue drives to divergence in https://github.com/Kyubyong/dc_tts/issues/21

**Comment by bdenoun** [comment]
So what would be the solution ? @arogozhnikov

**Comment by bdenoun** [comment]
I have read the mentioned thread so if I understand well, your advise is to upgrade my tf version to 1.9?

**Comment by annemenini** [comment]
I believe the issue from @bdenoun may be different from the original issue since the difference between the CPU and GPU outputs looks like a numerical precision difference. In the post from @trungpx, the difference (few % of accuracy) also appears after several epochs. I believe this instability behavior may be expected. In the original post, the discrepancy between the CPU and GPU outputs is several order of magnitude bigger than that and after a single operation. 

Nonetheless, it is interesting to note that @bdenoun got this numerical instability in a very simple graph involving a transpose. Although I have never managed to replicate the original issue in a very simple graph, my problem also started to appear after adding some transpose operations in my graph. Maybe the 2 issues are linked.

I would like to add that I have recently updated my Tensorflow version to 1.9 and I still observe the exact same issue as in the original post. I will give it one more try to replicate the problem in a simple test with TF 1.9

**Comment by annemenini** [comment]
### Issue with tf.transpose & tf.conj on GPU:
I have finally managed to reproduce a problem very similar from the initial post into a simple test case below. The problem seems to be linked to the `tf.transpose` and `tf.conj` in my case. Indeed, in the test case below, the `conjugate` argument of the `tf.transpose` is ignored when executed on GPU.

### Source:
```
import os

import numpy as np
import tensorflow as tf

#os.environ["CUDA_VISIBLE_DEVICES"]=""

input1 = tf.placeholder(tf.complex64, shape=[None, None, None, None], name="input1")
input2 = tf.placeholder(tf.complex64, shape=[None, None, None, None], name="input2")
input3 = tf.placeholder(tf.complex64, shape=[None, None, None, None], name="input3")

input1 = tf.transpose(input1, perm=[0, 3, 1, 2], conjugate=False)
input2 = tf.transpose(input2, perm=[0, 3, 1, 2], conjugate=True)
input3 = tf.transpose(input3, perm=[0, 3, 1, 2])
input3 = tf.conj(input3)

output1 = tf.Print(input1, [tf.real(input1), tf.imag(input1)], "output1: ", name="output1")
output2 = tf.Print(input2, [tf.real(input2), tf.imag(input2)], "output2: ", name="output2")
output3 = tf.Print(input3, [tf.real(input3), tf.imag(input3)], "output3: ", name="output3")

np.random.seed(seed=0)
a = np.random.rand(1, 16, 32, 8) + 1j * np.random.rand(1, 16, 32, 8)

sess = tf.InteractiveSession()

b, c, d = sess.run(["output1:0", "output2:0", "output3:0"], {"input1:0": a, "input2:0": a, "input3:0": a})
```
### Console output with GPU execution:
```
output2: [[[[0.548813522 0.963662744 0.0202183966]]]...][[[[0.318294257 0.612427294 0.152561143]]]...]
output3: [[[[0.548813522 0.963662744 0.0202183966]]]...][[[[-0.318294257 -0.612427294 -0.152561143]]]...]
output1: [[[[0.548813522 0.963662744 0.0202183966]]]...][[[[0.318294257 0.612427294 0.152561143]]]...]
```
Note the signs of the imaginary part of output2, it should be the opposite of output1, and the same as output3 (the imaginary part is the second half of each printed line).
### Console output with CPU execution (i.e. uncommenting `os.environ["CUDA_VISIBLE_DEVICES"]=""`):
```
output2: [[[[0.548813522 0.963662744 0.0202183966]]]...][[[[-0.318294257 -0.612427294 -0.152561143]]]...]
output3: [[[[0.548813522 0.963662744 0.0202183966]]]...][[[[-0.318294257 -0.612427294 -0.152561143]]]...]
output1: [[[[0.548813522 0.963662744 0.0202183966]]]...][[[[0.318294257 0.612427294 0.152561143]]]...]
```
In this case, the signs are correct.
### Additional notes:

- I could reproduce the problem in another machine with the following config: tensorflow-gpu 1.7.0 (previsouly tensorflow-gpu 1.9.0), device: Tesla V100-SXM2-32GB (previously GeForce GTX 1080 Ti)

- In the original source code where the issue was discovered, even the graph corresponding to `ouput3` in the test case above is failing to properly process the conjugate operation, I don't manage to reproduce that problem in the test case.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment]
@zheng-xq Hi, could you please look into this ?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @harshini-gadige: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by azaks2** [comment]
There seems to be a bug in SwapDimension1And2InTensor3WithNarrowMatrices from
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/conv_ops_gpu_3.cu.cc.
The method ignores the template parameter bool conjugate.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @azaks2: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yousefessam** [comment]
Hello,
I have the same problem. I trained a CNN model using keras over Tensorflow and GPU shows higher accuracy than CPU regarding that the same source code is used, and I also repeated the experiment nearly 10 times to make sure of the results. Any suggestions.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @azaks2: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harsh306** [comment]
I also face the similar issue with my Custom TF code. Is it solved?

**Comment by Path17** [comment]
Had the same issue by having different results when training with cpu and gpu. The problem went away when I upgraded to 2.0.0-alpha.

**Comment by nicochidt** [comment]
I have the same problem with Keras using the tensorflow/tensorflow-gpu backend. I'm able to train the model and inference in GPU (with tensorflow-gpu-1.12.0 installed) but when I use the same codebase to run inference in another system that is using tensorflow-1.13.0, I get NaNs as output regardless of the inputs.

**Comment by mkranzlein** [comment]
Still experiencing this with a custom Keras model using `tensorflow-gpu==2.0.0-beta1`. If I train on the CPU via `os.environ["CUDA_VISIBLE_DEVICES"]="-1"`, my model starts to learn immediately, and the loss goes down as expected. If I change that line to `os.environ["CUDA_VISIBLE_DEVICES"]="0"` to train on the GPU and make no other changes, the model gets stuck in a local minimum, and the loss is stagnant even after many epochs of training. However, if I call `model.fit()` a second time with a smaller batch size, it will eventually escape the local minimum and the loss will start decreasing. This is occurring with multiple training datasets of varying size. The model does include a `tf.transpose()` call, which others have mentioned, but it doesn't involve any convolution.

**Comment by mimbres** [comment]
I had same issue while using tf-cpu and gpu with 2.0.0. 
It seems solved in **tf-nightly-cpu==2.1.0-dev20200102**

**Comment by BaoshengHeTR** [comment]
Just want to add that I have the same issue. In addition, I have the same issue on using other libraries like Spacy. I have a feeling that if the training load is not very intensive (can be done on AWS sagemaker M4 or C5 instances by 1-3 hours), using gpu is NOT a good option.

**Comment by vigliensoni** [comment]
I am experiencing the same issue using Magenta 1.2.2 on TF 1.15.2: when using GPU, the loss doesn't decrease and the model doesn't learn. Running the same code on the same machine with CPU starts learning immediately. I have tried learning rates of different orders of magnitude and there is no difference.

This behavior was also reported [here](https://groups.google.com/a/tensorflow.org/forum/#!topic/magenta-discuss/6r6IFBpP4n8)

**Comment by BaoshengHeTR** [comment]
a guess is that this might not be the problem of tf but a glitch in CUDA.

**Comment by vigliensoni** [comment]
I have tried the code with same results on Google Colab w/CUDA 10.0 and a P100 on a HPC cluster with CUDA 10.1. 

@BaoshengHeTR do you have any suggestions?

**Comment by BaoshengHeTR** [comment]
> I have tried the code with same results on Google Colab w/CUDA 10.0 and a P100 on a HPC cluster with CUDA 10.1.
> 
> @BaoshengHeTR do you have any suggestions?

two possible suggestions is to tweak your shuffle before each epoch and try to change your batchsize, and change your weight initilization. One guess is: probably training a model from scratch could have some problem because some digit precision issue, but fine-tuning work should not be affected.

Please share your following attempts.

**Comment by BaoshengHeTR** [comment]
> I have tried the code with same results on Google Colab w/CUDA 10.0 and a P100 on a HPC cluster with CUDA 10.1.
> 
> @BaoshengHeTR do you have any suggestions?

two possible suggestions is to tweak your shuffle before each epoch and try to change your batchsize, and change your weight initilization. One guess is: probably training a model from scratch could have some problem because some digit precision issue, but fine-tuning work should not be affected.

Please share your following attempts.

**Comment by vigliensoni** [comment]
> > I have tried the code with same results on Google Colab w/CUDA 10.0 and a P100 on a HPC cluster with CUDA 10.1.
> > @BaoshengHeTR do you have any suggestions?
> 
> two possible suggestions is to tweak your shuffle before each epoch and try to change your batchsize, and change your weight initilization. One guess is: probably training a model from scratch could have some problem because some digit precision issue, but fine-tuning work should not be affected.
> 
> Please share your following attempts.

Hi @BaoshengHeTR,

I tried your suggestions: 

- the tensors are shuffled when loaded for training. 
- I tried different batch sizes and the learning wasn't affected, the loss remained constant. 
- Since training w/CPU actually decreases the loss, I used CPU training-based checkpoints as starting point to GPU training. The loss started at the same point left by the CPU, but then, instead of diminish, it went up, and then it was stabilized at a certain value without significant changes for a number of epochs.

**Comment by BaoshengHeTR** [comment]
> > > I have tried the code with same results on Google Colab w/CUDA 10.0 and a P100 on a HPC cluster with CUDA 10.1.
> > > @BaoshengHeTR do you have any suggestions?
> > 
> > 
> > two possible suggestions is to tweak your shuffle before each epoch and try to change your batchsize, and change your weight initilization. One guess is: probably training a model from scratch could have some problem because some digit precision issue, but fine-tuning work should not be affected.
> > Please share your following attempts.
> 
> Hi @BaoshengHeTR,
> 
> I tried your suggestions:
> 
> * the tensors are shuffled when loaded for training.
> * I tried different batch sizes and the learning wasn't affected, the loss remained constant.
> * Since training w/CPU actually decreases the loss, I used CPU training-based checkpoints as starting point to GPU training. The loss started at the same point left by the CPU, but then, instead of diminish, it went up, and then it was stabilized at a certain value without significant changes for a number of epochs.

Very strange. Is that possible to share your repo so we can repeat your test? I am working on some Bert projects, and haven't done much test, but will give my updates.

**Comment by vigliensoni** [comment]
Hi @BaoshengHeTR,

Here is a Colab repository with a minimal working example so that you can repeat my test. The code downloads and installs Magenta from the TensorFlow Github organization, and a small dataset for testing the training.

https://colab.research.google.com/drive/1ZVMYB-UPJIu7ooNYboEKotC6qatHWgBy

You will see that training with GPU lead to s stagnant loss (no learning at all), but using the same code and dataset with CPU lead to a decrease in the loss. 

Any insights would be very much appreciated.

**Comment by amanasj** [comment]
I know this thread is old but was there any resolution to this, I'm having the same problems.

**Comment by ziegenbalg** [comment]
@OmriSteiner, are you planning on submitting a PR for the commit above? I plan on testing this in the so let me know if you need a second verification to get it merged. Cheers for the work!

**Comment by OmriSteiner** [comment]
@ziegenbalg Yes, I am planning on submitting a PR once my employer signs the legal documents required.
I believe my branch fixes the conjugate transpose issue. You're welcome to test it.

**Comment by victoriapoghosian** [comment]
Had the same issue, after upgrading to tf 2.3.0 results are the same for cpu and gpu.

**Comment by jvishnuvardhan** [comment]
I think this was resolved. I couldn't reproduce the issue with recent `TF1.15.5`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/3ff8b088cafe1213d19255410afd3486/untitled.ipynb) is a gist with CPU code as mentioned [here](https://github.com/tensorflow/tensorflow/issues/19200#issuecomment-398448108).

[Here](https://colab.research.google.com/gist/jvishnuvardhan/b72c95c734f217820f4564688950f1e7/untitled1069.ipynb) is a gist with GPU code. Both the results are same.

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!
