### ISSUE TITLE
tensorflow-gpu-1.8: failed call to cuInit: CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by FlonTaut** [tensorflow/tensorflow#19266]
### System information
- **No custom code, Validate you installation test from tensorflow website**: Validate your installation test code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.4
- **TensorFlow installed from (source or binary)**: with `pip install --upgrade tensorflow-gpu`
- **TensorFlow version (use command below)**: 1.8 gpu
- **Python version**: 2.7
- **CUDA/cuDNN version**: 9.0 / 7
- **GPU model and memory**: Nvidia GeForce GTX 1080 Ti 11GB
- **Exact command to reproduce**:
`# Python
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))
`
### Describe the problem
I installed tensorflow and then tried to run the "validate your installation" program from the website.
`# Python
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))
`
After `sess = tf.Session()` im recieving the following error:
`2018-05-14 13:19:32.098811: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-05-14 13:19:32.098874: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: censored
2018-05-14 13:19:32.098889: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: censored
2018-05-14 13:19:32.098935: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 390.48.0
2018-05-14 13:19:32.098992: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 390.48.0
2018-05-14 13:19:32.099006: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 390.48.0`

This Issue https://github.com/tensorflow/tensorflow/issues/16860 did not resolve my problem.

Hopefully you can help me with this issue.

**Comment by achalshah20** [comment]
Can you post the output of nvidia-smi ? Did you try https://github.com/tensorflow/tensorflow/issues/7653 ?

**Comment by lxhner** [comment]
@achalshah20 yes i tried everything. cold reboot. hard reboot, updates ...
Output of nvidia-smi:
![unbenannt](https://user-images.githubusercontent.com/18403881/40040579-1a11e3a2-581b-11e8-94f0-972d5b98a6a7.PNG)

I found a website where they told to install `nvidia-modprobe`. Didnt fix my problem.
I Found another website where they said the set the gpu with `os.environ`, didnt work either.

**Comment by zheng-xq** [comment]
Could you post the entire log somewhere and point us to the link?

**Comment by FlonTaut** [comment]
@zheng-xq sorry, which logs do you need?

The links for `nvidia-modprobe`:
https://deeptalk.lambdal.com/t/failed-call-to-cuinit-cuda-error-unknown/57
http://kawahara.ca/tensorflow-failed-call-to-cuinit-cuda_error_unknown/

The link for `os.environ`:
https://github.com/tensorflow/tensorflow/issues/16860
But thats not relevant for my issue because i dont specify the gpu, because only 1 is installed at 0

**Comment by achalshah20** [comment]
From your nvidia-smi, I see "volatile uncorrectable Ecc error". Some discussion is already going on for this issue. Refer #19347

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by FlonTaut** [comment]
Im sorry guys i will take a look at it and will try to test the memory.
But the graphics card is only one month old and should not be damaged somehow.

I'll keep you guys up to date.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by hanalice** [comment]
i add cuda infos to PATH, and add a new env variable LD_LIBRARY_PATH. it works for me sometimes, but would filed throwing the same error few times~

**Comment by FlonTaut** [comment]
I was able to solve the problem now too.
But the solution for me was to complete reinstall my ubuntu and only install tensorflow on the blank system.

@1Mr-Styler nvidia-modprobe didnt solve it for me.
Im not sure why nvidia-smi has shown an ECC error because now its working perfectly without any nvidia-smi error

**Comment by Enverex** [comment]
Just to clarify, your card wasn't showing ECC errors, people just appear to be reading the table wrong:

There are four headings in that table: Volatile, Uncorrectable ECC Errors, GPU Utilisation and Compute Mode. They correspond to the table below it in the following order - top left, top right, bottom left, bottom right: (blank), N/A, Default, 0%.

I assume the card doesn't have ECC RAM which is why the ECC readout is N/A. But in short, nvidia-smi wasn't showing any errors.

**Comment by qysnn** [comment]
For me install `nvidia-modprobe` solved this problem. The command is `sudo apt install nvidia-modprobe`.

**Comment by gzhcv** [comment]
### System information

- **OS Platform and Distribution** : Ubuntu 14.04

- **TensorFlow version** : 1.10 gpu

- **Python version**: 2.7

- **CUDA/cuDNN version**: 9.0 / 7

- **GPU model and memory**: Nvidia GeForce GTX TITAN X 

- **`nvidia-smi`**:

+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 384.130        |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:02:00.0     Off |                  N/A |
| 22%   61C    P0    75W / 250W |      0MiB / 12206MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:03:00.0     Off |                  N/A |
| 23%   63C    P0    78W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:83:00.0     Off |                  N/A |
| 22%   60C    P0    77W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:84:00.0     Off |                  N/A |
| 22%   61C    P0    72W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+-----------------

- **`find /lib/modules/ | grep -i nvidia `**

/lib/modules/4.2.0-27-generic/kernel/drivers/net/ethernet/nvidia
/lib/modules/4.2.0-27-generic/kernel/drivers/net/ethernet/nvidia/forcedeth.ko
/lib/modules/4.2.0-27-generic/kernel/drivers/video/fbdev/nvidia
/lib/modules/4.2.0-27-generic/kernel/drivers/video/fbdev/nvidia/nvidiafb.ko
/lib/modules/4.2.0-27-generic/updates/dkms/nvidia_384_uvm.ko
/lib/modules/4.2.0-27-generic/updates/dkms/nvidia_384.ko
/lib/modules/4.2.0-27-generic/updates/dkms/nvidia_384_modeset.ko
/lib/modules/4.2.0-27-generic/updates/dkms/nvidia_384_drm.ko

### Describe the problem

I upgrade the nvidia driver througth command: **`sudo apt-get install nvidia-384`**.  Then i found there are serveal nvidia driver installed througth command: **`sudo dpkg --list | grep nvidia-*`**，so i uninstalled these driver except nvidia-384 use commadn: **`sudo apt-get remove xxx`**.  After that, the info as follows:

ii  nvidia-384                                            384.130-0ubuntu0.14.04.1                            amd64        NVIDIA binary driver - version 384.130
ii  nvidia-opencl-icd-384                                 384.130-0ubuntu0.14.04.1                            amd64        NVIDIA OpenCL ICD
ii  nvidia-prime                                          0.6.2.1                                             amd64        Tools to enable NVIDIA's Prime
ii  nvidia-settings                                       352.39-0ubuntu1                                     amd64        Tool for configuring the NVIDIA graphics driver

**Error occured when i run tensorflow code as follows:**
`2018-10-03 23:13:51.656015: E tensorflow/stream_executor/cuda/cuda_driver.cc:397   ] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-10-03 23:13:51.656131: I tensorflow/stream_executor/cuda/cuda_diagnostics.c   c:163] retrieving CUDA diagnostic information for host: root0-SCW4350-16
2018-10-03 23:13:51.656166: I tensorflow/stream_executor/cuda/cuda_diagnostics.c   c:170] hostname: root0-SCW4350-16
2018-10-03 23:13:51.656299: I tensorflow/stream_executor/cuda/cuda_diagnostics.c   c:194] libcuda reported version is: 384.130.0
2018-10-03 23:13:51.656428: I tensorflow/stream_executor/cuda/cuda_diagnostics.c   c:198] kernel reported version is: 384.130.0
2018-10-03 23:13:51.656465: I tensorflow/stream_executor/cuda/cuda_diagnostics.c   c:305] kernel version seems to match DSO: 384.130.0
<tensorflow.python.client.session.Session object at 0x7f30a08ae5d0>`

i have tried many solutions such as install `nvidia-modprobe` , `nvidia-cuda-mps-server` , `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/extras/CUPTI/lib64:/usr/local/cuda-9.0/targets/x86_64-linux/lib/"` all of these don't work. 

Maybe  It is noteworthy that **`nvidia-smi`** shows that `NVIDIA-SMI 352.63     Driver Version: 384.130` and **`sudo dpkg --list | grep nvidia-*`** shows that **`nvidia-settings   352.39-0ubuntu1 `**. It seems that some moulde of nvidia-352 are not uninstalled. And i tried to installed nvidia driver througth **`nvidia_xxxx.run`** file，but the error remain while running tensorflow code.

Hopefully you can help me with this issue.

**Comment by dtlam26** [comment]
For tf2.4, install nvidia-modprobe also solved this problem. `sudo apt install nvidia-modprobe`. It seems like besides Cuda and Cudnn now, we also need this to verify the installation of Cuda
