### ISSUE TITLE
AttributeError: NewBase is_abstract, ImportError: libcudart.so.7.5

### ISSUE THREAD

**Issue by karesh** [tensorflow/tensorflow#1965]
Hi,

I have tried to install tensorflow as in https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html
I have cuda 7.0 installed under /usr/local/cuda
 After I install gpu version using pip it gives the error-  ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory. 
But I have  libcudart.so.7.0 file. Why this is referring 7.5 by default ? 
(issues for version 0.7 and 0.8)

Then I tried to install cpu only version and giving me the error
AttributeError: type object 'NewBase' has no attribute 'is_abstract' (only to version 0.8)

How can I solve those issues ?
Thanks

**Comment by ilblackdragon** [comment]
FYI, saw similar issue when installing 0.8rc0 in the Travis: https://travis-ci.org/tensorflow/skflow/jobs/123599570

**Comment by vrv** [comment]
cuda issue: our pip installs require libcuda 7.5  I've updated the documentation and the website to clear this up.  If you want to use a lower libcuda version, you need to install from sources.

**Comment by vrv** [comment]
the NewBase one looks related to benchmark.py, assigning to @ebrevdo

**Comment by xuxy09** [comment]
I have the exactly same problem. Could you tell me what you did to solve it?

**Comment by hukla** [comment]
I had the same problem and solved by upgrading a library named 'Six'

**Comment by aabramovrepo** [comment]
Hi guys,

I have the same problem after the tensorflow installation via pip and updating the Six library didn't help:

>>> import tensorflow as tf I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module> from tensorflow.python import * File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 94, in <module> from tensorflow.python.platform import test File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/test.py", line 62, in <module> from tensorflow.python.framework import test_util File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 41, in <module> from tensorflow.python.platform import googletest File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 32, in <module> from tensorflow.python.platform import benchmark # pylint: disable=unused-import File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/benchmark.py", line 112, in <module> class Benchmark(six.with_metaclass(_BenchmarkRegistrar, object)): File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass return meta("NewBase", bases, {}) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/benchmark.py", line 107, in __new__ if not newclass.is_abstract(): AttributeError: type object 'NewBase' has no attribute 'is_abstract'

I'm using Nvidia GTX Titan X (comp. capability 5.2) and CUDA 7.5. Does anybody have an idea?

Many thanks in advance for your help!

Cheers,
A

**Comment by ebrevdo** [comment]
Looking specifically at the NewBase issue: please tell me the exact version of python and six that you are using.

**Comment by ebrevdo** [comment]
specifically, run:

import six
print(six.__version__)

**Comment by aabramovrepo** [comment]
python 2.7.6
six 1.5.2

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L41

We require > 1.10  for six.  I'm wondering why setup.py didn't require upgrading your 'six' :(  Can you try updating?

**Comment by xuxy09** [comment]
I can import six, but when I want to print six.version, it says " 'module' object has no attribute 'version' "

**Comment by xuxy09** [comment]
Here is the thing: I have installed "six-v1.10.0" by pip upgrading, but when I open the python and print the version of six, it still says "1.5.2".

**Comment by xuxy09** [comment]
I have figured out how to upgrade the package "six" properly. 
The default location of "pip install" in my computer is "/usr/local/lib/python2.7/dist-packages". So when I upgrade "six", it is the file in "/usr/local/lib/python2.7/dist-packages" that is upgraded. 
However, when we import some package in Python, another location "/usr/lib/python2.7/dist-packages" is searched first, while the file "six.py" in this location has never been upgraded.
So what we need to do is to modify the default location of "pip install" from "/usr/local/lib/python2.7/dist-packages" to "/usr/lib/python2.7/dist-packages"; then we can upgrade the right "six.py".
To modify the default location, we can make a new file "/etc/pip.conf", and type the following into this file:
"
[global]
target=/usr/lib/python2.7/dist-packages
".
Now you can upgrade the package "six" properly.
To avoid some unknown error, you may want to change the default location back to "/usr/local/lib/python2.7/dist-packages" after upgrading "six".

**Comment by xuxy09** [comment]
I only installed the CPU-version tensorflow. Now everything works well for me. Hope this could be helpful for you.

**Comment by LiberiFatali** [comment]
**xuxy09**'s solution also works for GPU version

**Comment by aabramovrepo** [comment]
Thanks a lot for the help! Updating Six library to 1.10 helped!

**Comment by karesh** [comment]
Yes Thank you. I have uninstalled apt-get numpy and reinstalled pip numpy v11 and upgraded the six 1.10 package and working fine on CPU.

**Comment by yselivonchyk** [comment]
CUDA 7.5 and cuDNN 5.0. the above mentioned error no longer appears after doing what xuxy09 suggested. I would only like to make it a little easier for you with the next line:

sudo pip install six --upgrade --target="/usr/lib/python2.7/dist-packages"

**Comment by yhlleo** [comment]
It's strange that it works well in my PC--which the path is `/usr/local/lib/python2.7/dist-packages`--but occurs errors in my workshop computer with the same path. After I set the target path as `/usr/lib/python2.7/dist-packages`, this problem is gone. Now my tensorflow works well, thank you very much! @yselivonchyk

**Comment by yhlleo** [comment]
The most popular method of get the version one package is as follows.
`$ python`
`>>>import six`
`>>>print six.\__version\__`
`...`
`>>>import protobuf`
`>>>print protubuf.\__version\__`

Recently, I have learnt a simple method to get the version of the packages, such as numpy, six and protobuf, like this:
`pip show numpy six protobuf`

With this method, both the verison and orther detailed information of the package will be presented, so I want to share with you.

**Comment by wangzhangup** [comment]
Aha
I have another solution:
$ cd /usr/lib/python2.7/dist-packages
$ sudo rm six*

**Comment by ebrevdo** [comment]
That won't work in the long run if your package manager / os manages six in
that directory.

**Comment by xuxy09** [comment]
I agree. It's quite dangerous to delete some package directly.



xuxiangyu2014@qq.com
 
From: ebrevdo
Date: 2016-05-10 14:30
To: tensorflow/tensorflow
CC: XiangyuXu; Comment
Subject: Re: [tensorflow/tensorflow] AttributeError: NewBase is_abstract, ImportError: libcudart.so.7.5 (#1965)
That won't work in the long run if your package manager / os manages six in
that directory.

**Comment by ailurus1991** [comment]
$home/.pip/pip.conf is better and also worked.

**Comment by TimZaman** [comment]
I had a similar error:
`AttributeError: type object 'NewBase' has no attribute 'is_abstract'`
This fixed my issue:
`sudo pip install six --upgrade --target="/usr/lib/python2.7/dist-packages"`
Shouldn't TF test for a particular six version, or at least help the user on his way.

**Comment by ebrevdo** [comment]
Seems like the issue is fixed by updating six correctly. Closing.

**Comment by shubhamchaudhary** [comment]
If you get error `Not uninstalling six at /path/to/six, owned by OS`, run `sudo easy_install six`

**Comment by rachelwarren** [comment]
for the record as pr this thread a really simple solution was just to install python with brew, which aligns all the paths for you.

**Comment by AlienceGG** [comment]
mac os : 10.11
before run the command in the following line , we must uninstall the `six` by running `sudo pip uninstall six`
I met this erro and fix it by run `sudo easy_install six`

**Comment by brianlan** [comment]
My problem is exactly the same as @xuxy09, and I used the solution provided by @yselivonchyk. It solved my issue. Thanks a lot.

**Comment by bashimao** [comment]
I can confirm either methods ( @xuxy09 / @yselivonchyk ) solve this particular issue on `Ubunutu Trusty`.

**Comment by j2kun** [comment]
I needed to add a `-U` to the command to get it to work: `sudo easy_install3 -U six`

**Comment by sheunaluko** [comment]
For me, I had the CPU version running on ubuntu 64bit. I had the same error "AttributeError: type object 'NewBase' has no attribute 'is_abstract' " 

I fixed it simply by running `easy_install3 -U six` while inside the activated virtualenv. Hope that helps
