### ISSUE TITLE
Resource Exhausted  Error

### ISSUE THREAD

**Issue by jaiaravind4u** [tensorflow/tensorflow#20213]
```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[98384,15003]
         [[Node: dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dynamic_seq2seq/decoder/output_projection/Tensordot/Reshape, dynamic_seq2seq/decoder/output_projection/Tensordot/Reshape_1)]]
         [[Node: dynamic_seq2seq/truediv/_217 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_783_dynamic_seq2seq/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

i get the above error when i try to train my model using the tensorflow gpu

**Comment by riless** [comment]
@jaiaravind4u this error means that you do not have enough memory to create a tensor with this  shape: _[98384,15003]_ it's a very huge tensor though.

**Comment by jaiaravind4u** [comment]
Thanks i solved the isuues on my side its working now
