### ISSUE TITLE
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shivank01** [tensorflow/tensorflow#20271]
I have recently installed tensorflow-gpu using pip. But when I am importing it it is giving the following error:

    ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory

I have gone through all the answers of stackoverflow related to this issue but none of them worked for me.

libcudnn.so.7 is present in both the following directories /usr/local/cuda/lib64 and /usr/local/cuda-9.0/lib64 .

Also, I have added the following path in my .bashrc file:

    export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
    export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64\${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    
    export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
    export LD_LIBRARY_PATH=/usr/local/cuda/lib64\${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

Please help me in resolving this

**Comment by tedyu** [comment]
After installing cuda, there is no libcudnn.so under /usr/local/cuda/lib64

Can you tell me how you installed cuda ?

Thanks

**Comment by mysticaltech** [comment]
Yes exactly, it's not in there!

**Comment by mysticaltech** [comment]
Turns out it's not included, you have to download and copy them to/usr/local/cuda/lib64 separately:
[https://developer.nvidia.com/rdp/cudnn-download](url)

**Comment by Keiku** [comment]
@tedyu @mysticaltech I found libcudnn.so.7 in `/usr/lib/x86_64-linux-gnu`. Do you know why it will be installed there?

```
╭─keiichi.kuroyanagi@instance-1 /usr/lib/x86_64-linux-gnu  ‹system›
╰─$ pwd                                                                                                                                                              02:32:15
/usr/lib/x86_64-linux-gnu
╭─keiichi.kuroyanagi@instance-1 /usr/lib/x86_64-linux-gnu  ‹system›
╰─$ ls libcudnn.so.7                                                                                                                                                 02:32:26
libcudnn.so.7@
```

**Comment by tedyu** [comment]
I think it is the default location for libcudnn.so.7

**Comment by soerendip** [comment]
Hm, the links seem to be outdated and the install commands don't work. How to resolve this now??

**Comment by thatrobotguy** [comment]
If you go to the generic linux download (Not for PowerX), which should be the 3rd one down for CUda 9.0, the tar.gz file has everything you need. The instructions are right there towards the middle of the webpage to extract it and copy the files to the correct location. Do make sure your path is set as stated by @shivank01 for libcudnn.so.7.
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html
![installationlink](https://user-images.githubusercontent.com/24778586/46674403-04310380-cbaa-11e8-88da-2e1e7716d5b6.png)

**Comment by jowagner** [comment]
Or if you use /etc/ld.co.conf/ to manage the library locations, you may have forgotten to run `ldconfig` after installing cuddnn.

**Comment by xiadeye** [comment]
just:
sudo ldconfig /usr/local/cuda/lib64

**Comment by miladfa7** [comment]
you  add the following path in your .bashrc file:

```
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH


export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```

**Comment by oktemer** [comment]
At first you should download cuda driver from the link https://developer.nvidia.com/rdp/cudnn-download. After you extracted tar file  you will have cuda directory , In this directory copy the contents of the include/cudnn.h to /usr/local/cuda-9.0/include/  and 
lib64/libcudnn* files to /usr/local/cuda-9.0/lib64 . 
After that , to make tensorflow to recognize these libraries you should edit path variable named LD_LIBRARY_PATH as the following;

export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/extras/CUPTI/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH

**Comment by pavlexander** [comment]
none of the above solutions worked. The issue was with the symbolic links that got corrupted after following the official `nvidia` guide. The fix I applied is explained on this page: https://stackoverflow.com/a/61563579/1215913

**Comment by BramVanroy** [comment]
Here is what worked for me:

- Install CuDNN manually from https://developer.nvidia.com/rdp/cudnn-download. It will be installed in `/usr/lib/x86_64-linux-gnu`
- Create symlinks from your CUDA installation to that initial location:

```
cd /usr/local/cuda-10.1/lib64
sudo ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5 libcudnn.so.7
sudo ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5 libcudnn.so
```

**Comment by xxxrokxxx** [comment]
@BramVanroy you are a $life saver! :) (.format{} and a few sleepless nights ;))
#I had to link the libcudnn.so.8 to libcudnn.so.7 but still.

**Comment by Nicholas-Mitchell** [comment]
In case it helps, here is how I set up a new conda environment from scratch to get:

* Tensorflow version 2.2 (supports CPU and GPU)
* Python 3.8
* CUDA 10.1.243
* CUDNN 7.6.5

## Installation Steps

```bash
$ conda create -n tf python=3.8     # create new env, with name "tf"
$ pip install -U pip             # ensure new version available
$ conda activate tf 
$ pip install -U tensorflow
$ conda install -c anaconda cudatoolkit=10.1.243 cudnn=7.6.5   # the important part - versions must match
$ pip install ipython
```

## Confirming success

Import tensorflow, check it finds a GPU and also confirm the version:

```python
$ ipython
Python 3.8.3 (default, May 19 2020, 18:47:26)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow as tf

In [2]: tf.config.list_physical_devices()

2020-06-22 00:49:40.954473: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-22 00:49:40.969881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: TITAN X (Pascal) computeCapability: 6.1
coreClock: 1.531GHz coreCount: 28 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 447.48GiB/s
2020-06-22 00:49:40.970047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-22 00:49:40.971409: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-22 00:49:40.972694: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-22 00:49:40.972945: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-22 00:49:40.974394: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-22 00:49:40.975205: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-22 00:49:40.979167: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 00:49:40.980315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0

Out[2]: 
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]     # GPU!

In [3]: tf.__version__
Out[3]: '2.2.0'
```

This was done on Ubuntu 18.04, but should work just as well for Windows. From what I could see, the same `cudatoolkit` and `cudnn` versions are available:

* https://anaconda.org/anaconda/cudatoolkit/files?version=10.1.243
* https://anaconda.org/anaconda/cudnn/files?version=7.6.5

**Comment by arnabanerji** [comment]
For what it's worth, I just followed @Nicholas-Mitchell 's instructions to get things working on WSL with python 3.7 on miniconda using the NVIDIA preview drivers to allow WSL to use GPU hardware.

**Comment by flavienbwk** [comment]
From a CUDA 10.2 install on Ubuntu 18.04, I had to :

1. Create symlinks for CUDA 10.1 and export the links

```console
ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart.so.10.2 /usr/lib/x86_64-linux-gnu/libcudart.so.10.1
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```

2. Install libcudnn for CUDA 10.1 : https://developer.nvidia.com/rdp/cudnn-archive

Test with

```python3.7
import tensorflow as tf
tf.config.experimental.list_physical_devices('GPU')
```

**Comment by engrmz** [comment]
Hello everyone,
I solved the error by installing cuDNN 7.6. I followed these steps;

Remove cuda tool kit from anaconda environment using command `conda remove cudatoolkit`

1. Download **cuDNN v7.6.4** (September 27, 2019), for **CUDA 10.1** ([https://developer.nvidia.com/rdp/cudnn-archive](https://developer.nvidia.com/rdp/cudnn-archive))
                        cuDNN _Runtime_ Library for Ubuntu18.04 (Deb)
                        cuDNN _Developer_ Library for Ubuntu18.04 (Deb)
                        cuDNN _Code Samples_ and User Guide for Ubuntu18.04 (Deb)

Installed the above 3 files _in the same sequence_.

**Comment by rohitdavas** [comment]
`conda install -c anaconda cudnn ` can fix the issue. [from here](https://anaconda.org/anaconda/cudnn)

**Comment by sqiprasanna** [comment]
> @BramVanroy you are a $life saver! :) (.format{} and a few sleepless nights ;))
> #I had to link the libcudnn.so.8 to libcudnn.so.7 but still.

Hey @BramVanroy can you tell me how you linked libcudnn.so.8 to libcudnn.so.7

**Comment by BramVanroy** [comment]
> > @BramVanroy you are a $life saver! :) (.format{} and a few sleepless nights ;))
> > #I had to link the libcudnn.so.8 to libcudnn.so.7 but still.
> 
> Hey @xxxrokxxx @BramVanroy can you tell me how you linked libcudnn.so.8 to libcudnn.so.7

It's called symlinking or soft linking: https://askubuntu.com/questions/56339/how-to-create-a-soft-or-symbolic-link

**Comment by FazalAAli** [comment]
I tried almost all the solutions here and none of them  seemed to work. Eventually, I tried to `cat` the contents of my libcudnn.so files and turns out they were empty. Downloaded them again, copied them to the right place again, and it all worked. (It's confusing enough as is I don't need the confusion from bad downloads :( )

**Comment by Uzair-Khattak** [comment]
> sudo ldconfig /usr/local/cuda/lib64

Yes Sir, it worked, Thank so much,,,can you just tell the reason for it?

**Comment by windowsair** [comment]
> > sudo ldconfig /usr/local/cuda/lib64
> 
> Yes Sir, it worked, Thank so much,,,can you just tell the reason for it?

Yes, you need to inform the system to change these *.so files

**Comment by 83521166** [comment]
> In case it helps, here is how I set up a new conda environment from scratch to get:
> 
> * Tensorflow version 2.2 (supports CPU and GPU)
> * Python 3.8
> * CUDA 10.1.243
> * CUDNN 7.6.5
> 
> ## Installation Steps
> ```shell
> $ conda create -n tf python=3.8     # create new env, with name "tf"
> $ pip install -U pip             # ensure new version available
> $ conda activate tf 
> $ pip install -U tensorflow
> $ conda install -c anaconda cudatoolkit=10.1.243 cudnn=7.6.5   # the important part - versions must match
> $ pip install ipython
> ```
> 
> ## Confirming success
> Import tensorflow, check it finds a GPU and also confirm the version:
> 
> ```python
> $ ipython
> Python 3.8.3 (default, May 19 2020, 18:47:26)
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import tensorflow as tf
> 
> In [2]: tf.config.list_physical_devices()
> 
> 2020-06-22 00:49:40.954473: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2020-06-22 00:49:40.969881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
> pciBusID: 0000:01:00.0 name: TITAN X (Pascal) computeCapability: 6.1
> coreClock: 1.531GHz coreCount: 28 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 447.48GiB/s
> 2020-06-22 00:49:40.970047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> 2020-06-22 00:49:40.971409: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2020-06-22 00:49:40.972694: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
> 2020-06-22 00:49:40.972945: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
> 2020-06-22 00:49:40.974394: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
> 2020-06-22 00:49:40.975205: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
> 2020-06-22 00:49:40.979167: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-06-22 00:49:40.980315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
> 
> Out[2]: 
> [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
>  PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
>  PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'),
>  PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]     # GPU!
> 
> In [3]: tf.__version__
> Out[3]: '2.2.0'
> ```
> 
> This was done on Ubuntu 18.04, but should work just as well for Windows. From what I could see, the same `cudatoolkit` and `cudnn` versions are available:
> 
> * https://anaconda.org/anaconda/cudatoolkit/files?version=10.1.243
> * https://anaconda.org/anaconda/cudnn/files?version=7.6.5

thanks a lot, it solve my problem
wish you best

**Comment by tisbuet** [comment]
> Or if you use /etc/ld.co.conf/ to manage the library locations, you may have forgotten to run `ldconfig` after installing cuddnn.

This one solves my issue! Thanks.

**Comment by ankit-attri** [comment]
Anyone facing the issue in the docker container, fastest solution I found for this was to use  [https://hub.docker.com/layers/nvidia/cuda/12.0.1-cudnn8-runtime-ubuntu20.04/images/sha256-e09a47362de8314c1b60a25b3fc1f85ca048d2972bfb1299f0da02542796470a](url) base image with python 3.11. Worked on the first run. 
You might have to export the LD_LIBRARY_PATH. Here is the bash script:
`EXPORT_COMMAND='export LD_LIBRARY_PATH=`python3 -c "import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + \":\" + os.path.dirname(nvidia.cudnn.lib.__file__))"`'

if ! grep -Fxq "$EXPORT_COMMAND" /root/.bashrc; then
    echo "$EXPORT_COMMAND" >> /root/.bashrc
    echo "Added LD_LIBRARY_PATH update to /root/.bashrc."
else
    echo "LD_LIBRARY_PATH update is already present in /root/.bashrc."
fi
`
