### ISSUE TITLE
CudNN error running TensorFlow: Could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by hephaex** [tensorflow/tensorflow#2033]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
$ ls -l /usr/local/cuda-7.5/lib64/libcud*
-rw-r--r-- 1 root root   322936 Aug 16  2015 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 16  2015 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 16  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 16  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 16  2015 /usr/local/cuda-7.5/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 59823168 Apr 19 15:15 /usr/local/cuda-7.5/lib64/libcudnn.so
-rwxr-xr-x 1 root root 59823168 Apr 19 15:15 /usr/local/cuda-7.5/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 59823168 Apr 19 15:15 /usr/local/cuda-7.5/lib64/libcudnn.so.5.0.4
-rw-r--r-- 1 root root 58734618 Apr 19 15:15 /usr/local/cuda-7.5/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

```
$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.8.0rc0
```

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1. When I run the deep convolutional nn tutorial from TensorFlow's website, I get the following error:

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow dev\
ice (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0)
Successfully loaded: saved_networks/dqn-2920000
F tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not set cudnn filter d\
escriptor: CUDNN_STATUS_BAD_PARAM
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by vrv** [comment]
To use cudnn 5 you have to build from sources -- cudnn5 is not binary compatible with cudnn4, and our binaries use the latest official cudnn release (which is 4).

**Comment by jamlong** [comment]
May I rephrase his bug then?

**Comment by jamlong** [comment]
Download and install cuDNN

https://developer.nvidia.com/cudnn

Uncompress and copy the cuDNN files into the toolkit directory. Assuming the toolkit is installed in /usr/local/cuda, run the following commands (edited to reflect the cuDNN version you downloaded):

tar xvzf cudnn-6.5-linux-x64-v2.tgz
sudo cp cudnn-6.5-linux-x64-v2/cudnn.h /usr/local/cuda/include
sudo cp cudnn-6.5-linux-x64-v2/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/lib64/libcudnn*

**Comment by jamlong** [comment]
Short form: 
@vrv I'd argue that the tensorflow.org should be update to reflect that, here: 
https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#optional-install-cuda-gpus-on-linux

The following section is misleading, as it makes it sound like it should "just work" with other versions: 

> Download and install cuDNN
>
> https://developer.nvidia.com/cudnn
> 
> Uncompress and copy the cuDNN files into the toolkit directory. Assuming the toolkit is installed in /usr/local/cuda, run the following commands (**edited to reflect the cuDNN version you downloaded**):
> 
> tar xvzf cudnn-6.5-linux-x64-v2.tgz
> sudo cp cudnn-6.5-linux-x64-v2/cudnn.h /usr/local/cuda/include
> sudo cp cudnn-6.5-linux-x64-v2/libcudnn* /usr/local/cuda/lib64
> sudo chmod a+r /usr/local/cuda/lib64/libcudnn*

Bolding mine.   No indication that you need to specifically download cudnn4 for that. The rest of the page merely says cudnn > 2.0.  Also the versioning makes that more confusing than it needs to be (cudnn4 -> 6.5  cudnn5 -> 7.x, and the only way I know is by looking at the actual filenames in the download links) 

On https://developer.nvidia.com/cudnn

cudnn5 is now the first thing you're presented,  so you actually have to scroll down to get to cudnn4 (which you don't know you have to do anyway), so I expect more tensorflow beginners will wind up doing the same (Download cudnn5, follow install instructions, get obscure error message)

Seems like something the documentation could be more clear.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/pull/2065 ?

**Comment by jamlong** [comment]
Excellent!

**Comment by achaiah** [comment]
I ran into this issue as well. Very confusing, please update documentation.

**Comment by fancyerii** [comment]
I have the same problem.

**Comment by jiapei100** [comment]
Me too...

Ubuntu: 16.04
Cuda: 8.0.27 RC
cudnn: 5.0.5
tensorflow: 0.9.0

the error message is like:

>  tensorflow/stream_executor/cuda/cuda_dnn.cc:422] could not set cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM

Any solutions ?

Thank you very much....
Pei

**Comment by tongda** [comment]
I have similar problem.

OS: Ubuntu 14.04
Cuda: 7.5
cudnn: v4 for 7.0
tensorflow: 0.10

error message: F tensorflow/stream_executor/cuda/cuda_dnn.cc:423] could not set cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM

It seems like every time 1 epoch training finishes, tensorflow will fail with this message.

Any thought about this?

Thanks.

**Comment by vguizilini** [comment]
I am having the same issue, however as far as I can tell it only shows up when I am using conv3d (conv2d works fine), after one epoch.

OS: Ubuntu 16.04
CUDA: 7.5
CUDNN: Tried 4.0, 5.0 and 5.1 (and the corresponding tensorflow binaries)

Any thoughts? I really would like to get this sorted out as quickly as possible.

Thanks.

**Comment by oakkas** [comment]
Same thing here:
With Ubuntu 14.04
Cuda: 7.5
CUDNN: 5.0
Train on 16064 samples, validate on 1785 samples
Epoch 1/10
F tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not set cudnn filter descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped

**Comment by mpkuse** [comment]
Similar for me.
Cuda 8.0, CUDNN 5, Tensorflow 0.12

Multi-gpu version of my project has issues.
Single GPU version works fine.

E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F tensorflow/core/kernels/conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)

**Comment by philipperemy** [comment]
If you have the error `CUDNN_STATUS_BAD_PARAM`, make sure that the problem does not come from your code. For example, it happened to me because I gave an empty array as an input to the tensorflow session after the SECOND epoch. My `next_batch()` function had a bug. This was the reason. I'm running v5 with TF 0.9 built from the sources and it works nicely now.
@tongda @vguizilini @mpkuse @oakkas @achaiah @fancyerii

**Comment by brando90** [comment]
is this error still relevant for tensorflow 1.0.0?

**Comment by dovanchan** [comment]
E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F tensorflow/core/kernels/conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)

MAC Tensorflow1.0 GTX650m  cudnn5.0 cuda8.0 . 
How to slove this problem?>>

**Comment by sujoyp** [comment]
Has anyone solved this problem ?

**Comment by philipperemy** [comment]
Guys make sure your code is bug free. In most of the cases, we suspect this error to come from your code, rather than TF itself. I had this error because I was given an empty array to TF.

**Comment by philipperemy** [comment]
```
To use cudnn 5 you have to build from sources -- cudnn5 is not binary compatible with cudnn4, and our binaries use the latest official cudnn release (which is 4).
```

**Comment by liufsd** [comment]
why not update to cudnn 5?
I mean all of us will install new version cudnn when first install  tensorflow

**Comment by cro888888** [comment]
I have the same problem too, can't someone really answer the question?

**Comment by syed-ahmed** [comment]
Hi, I'm getting the same error.
```
tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not set cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM
```
I'm using 3D convolutions as well like @vguizilini . Also, the current documentation says cudnn 5.1 is supported.

**Comment by cro888888** [comment]
I tried, still getting it.

2017-05-03 14:45 GMT+08:00 Syed Tousif Ahmed <notifications@github.com>:

**Comment by supamonkey2000** [comment]
still happening on Windows 10 64 bit. GPU is GTX 1060 3Gb

**Comment by philipperemy** [comment]
@supamonkey2000 run a very tensorflow script like MNIST CNN and check if you have this error.

**Comment by supamonkey2000** [comment]
@philipperemy I ran the MNIST tutorial with no errors.

**Comment by philipperemy** [comment]
@supamonkey2000 so the problem comes from your code. Check every line carefully.

I had this error because I was given an empty array to the TF session.

**Comment by post2web** [comment]
I had same error because of accidentally doing:
`tf.layers.conv2d(net, filters=0)`

**Comment by nicolefinnie** [comment]
@philipperemy  was right, we didn't hit this issue when we just had one GPU, but when we trained our model with multiple GPUs, the error kicked in. You need to calculate your batch size for each GPU carefully. For example, if each batch size is 64 and you have 4 GPUs with 47 training samples, it will be split to 16, 16, 15, 0, the last batch will get zero sample. It's not obvious when there are many samples like our case.

**Comment by yushuinanrong** [comment]
@nicolefinnie 
Nicole is absolutely right. A safe strategy is to make your batch size dividable by the number of GPUs.

**Comment by cro888888** [comment]
The ultimate solution i found was to reboot. It saves the fire. (2018 film Skyscraper)

**Comment by philipperemy** [comment]
@cro888888 lol that's great!

**Comment by taninaim** [comment]
I was having this problem earlier trying to fit inception_v3 on cifar10. As noted in Keras' documentation, there is a minimum image size for each model. Make sure you're not fitting images that are too small for your selected model.
