### ISSUE TITLE
non-chief workers hang in training distributed seq2seq model when time-major is true

### ISSUE THREAD

**Issue by junshi15** [tensorflow/tensorflow#20585]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOs High Sierra version 10.13.3 (also found in Linux RHEL 6.5)
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7.0 (also found in 1.8.0)
- **Python version**: 2.7.10
- **Bazel version (if compiling from source)**:N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A CPU version
- **GPU model and memory**:N/A
- **Exact command to reproduce**:
python nonchief_hang.py --out_dir=/tmp/rnn/work0 --ps_hosts=localhost:2222  --worker_hosts=localhost:1111,localhost:3333 --task_index=0 --job_name=worker --time_major
python nonchief_hang.py --out_dir=/tmp/rnn/work1 --ps_hosts=localhost:2222  --worker_hosts=localhost:1111,localhost:3333 --task_index=1 --job_name=worker --time_major
python nonchief_hang.py --out_dir=/tmp/rnn/ps0 --ps_hosts=localhost:2222  --worker_hosts=localhost:1111,localhost:3333 --task_index=0 --job_name=ps --time_major

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
In a distributed seq2seq model (see a short example below), when time-major is set to true, the non-chief workers hang, further debugging showed that the non-chief workers were waiting for embedding matrices to be initialized. The chief worker trains without issues.

If we remove ("--time_major") from the command line, then non-chief workers run fine.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
This is a simple seq2seq model following the implementation of [tensorflow/nmt](https://github.com/tensorflow/nmt), with optimizer removed.

```python
import argparse
import sys

import tensorflow as tf
import numpy as np
import time
FLAGS = None


def main(_):
  ps_hosts = FLAGS.ps_hosts.split(",")
  worker_hosts = FLAGS.worker_hosts.split(",")

  # Create a cluster from the parameter server and worker hosts.
  cluster = tf.train.ClusterSpec({"ps": ps_hosts, "worker": worker_hosts})

  # Create and start a server for the local task.
  server = tf.train.Server(cluster,
                           job_name=FLAGS.job_name,
                           task_index=FLAGS.task_index)
  if FLAGS.job_name == "ps":
    server.join()
  elif FLAGS.job_name == "worker":

    # Assigns ops to the local worker by default.
    with tf.device(tf.train.replica_device_setter(
        worker_device="/job:worker/task:%d" % FLAGS.task_index,
        cluster=cluster)):

      # Build model...
      batch_size = 24
      src_len = 25
      source = np.ones((batch_size, src_len), dtype=int)

      embedding_encoder = tf.get_variable(
          "embedding_encoder", (99, 128), tf.float32)

      embedding_decoder = tf.get_variable(
          "embedding_decoder", (99, 128), tf.float32)

      with tf.variable_scope("encoder") as decoder_scope:
        encoder_emb_inp = tf.nn.embedding_lookup(
           embedding_encoder, source)

        encoder_cell = tf.contrib.rnn.BasicLSTMCell(
          num_units=256,
          forget_bias=1.0)

        if FLAGS.time_major:
            sequence_length=np.ones(src_len, dtype=int)*batch_size
        else:
            sequence_length=np.ones(batch_size, dtype=int)*src_len
 
        encoder_outputs, encoder_state = tf.nn.dynamic_rnn(
            encoder_cell,
            encoder_emb_inp,
            dtype=tf.float32,
            sequence_length=sequence_length,
            time_major=FLAGS.time_major,
            swap_memory=True)

      with tf.variable_scope("decoder") as decoder_scope:
        target_input = np.ones((batch_size, src_len), dtype=int)
        decoder_emb_inp = tf.nn.embedding_lookup(
            embedding_decoder, target_input) 

        # Helper
        if FLAGS.time_major:
           dummy = tf.fill([src_len], batch_size)
        else:
           dummy = tf.fill([batch_size], src_len)

        helper = tf.contrib.seq2seq.TrainingHelper(
            decoder_emb_inp, dummy,
            time_major=FLAGS.time_major)

        decoder_cell = tf.contrib.rnn.BasicLSTMCell(
            num_units=256,
            forget_bias=1.0)
        decoder_initial_state = encoder_state

        # Decoder
        my_decoder = tf.contrib.seq2seq.BasicDecoder(
            decoder_cell,
            helper,
            decoder_initial_state)

        # Dynamic decoding
        decoder_outputs, final_context_state, _ = tf.contrib.seq2seq.dynamic_decode(
            my_decoder,
            output_time_major=FLAGS.time_major,
            swap_memory=True,
            scope=decoder_scope)

      global_step = tf.train.get_or_create_global_step()
      
      train_op = decoder_outputs

    # The StopAtStepHook handles stopping after running given steps.
    hooks=[tf.train.StopAtStepHook(last_step=100)]

    # The MonitoredTrainingSession takes care of session initialization,
    # restoring from a checkpoint, saving to a checkpoint, and closing when done
    # or an error occurs.
    with tf.train.MonitoredTrainingSession(master=server.target,
                                           is_chief=(FLAGS.task_index == 0),
                                           checkpoint_dir=FLAGS.out_dir,
                                           hooks=hooks) as mon_sess:
      # This is an infinite while loop since global_step does not increment at all.
      # In a real training, global_step is passed to an optimizer, then increments
      # after each step.
      while not mon_sess.should_stop():
        x = mon_sess.run(train_op)
        global_step_val = global_step.eval(session=mon_sess)
        print('global_step = {0}, time_major is {1}'.format(global_step_val, FLAGS.time_major))

if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.register("type", "bool", lambda v: v.lower() == "true")
  # Flags for defining the tf.train.ClusterSpec
  parser.add_argument(
      "--ps_hosts",
      type=str,
      default="",
      help="Comma-separated list of hostname:port pairs"
  )
  parser.add_argument(
      "--worker_hosts",
      type=str,
      default="",
      help="Comma-separated list of hostname:port pairs"
  )
  parser.add_argument(
      "--job_name",
      type=str,
      default="",
      help="One of 'ps', 'worker'"
  )
  # Flags for defining the tf.train.Server
  parser.add_argument(
      "--task_index",
      type=int,
      default=0,
      help="Index of task within the job"
  )
  parser.add_argument(
      "--out_dir",
      type=str,
      default="",
      help="output dir"
  )

  parser.add_argument(
      "--time_major",
      action='store_true',
      help="time major"
  )
  FLAGS, unparsed = parser.parse_known_args()
  tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
```

**Comment by michaelisard** [comment]
@lukaszkaiser would you assign to someone who can look into this if you don't have time?

**Comment by lukaszkaiser** [comment]
@ebrevdo : I'm really not sure what the problem is here and who can debug it properly, can you find a person who'd know? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment]
I think there's an error you're not seeing in the logs.

  if FLAGS.time_major:
            sequence_length=np.ones(src_len, dtype=int)*batch_size
        else:
            sequence_length=np.ones(batch_size, dtype=int)*src_len

This is problematic. You should always have a vector of size batch_size, regardless of time_major or not.  In your case you may even be able to just skip passing in this argument.

**Comment by ebrevdo** [comment]
The reason I think there's an error is that passing the wrong size sequence_length should cause either a ValueError or tf runtime error to be raised.

**Comment by junshi15** [comment]
@ebrevdo Thanks for looking into issue. I really appreciate it.
What you said was correct, sequence_length should always be 1-D vector of batch_size length. "time_major" dictates the dimension of the input tensor, whether time should be on the first or second axis. I have fixed the code. It works with both case. For future reference, the modified code is pasted below.

```python
import argparse
import sys

import tensorflow as tf
import numpy as np
import time
FLAGS = None


def main(_):
  ps_hosts = FLAGS.ps_hosts.split(",")
  worker_hosts = FLAGS.worker_hosts.split(",")

  # Create a cluster from the parameter server and worker hosts.
  cluster = tf.train.ClusterSpec({"ps": ps_hosts, "worker": worker_hosts})

  # Create and start a server for the local task.
  server = tf.train.Server(cluster,
                           job_name=FLAGS.job_name,
                           task_index=FLAGS.task_index)
  if FLAGS.job_name == "ps":
    server.join()
  elif FLAGS.job_name == "worker":

    # Assigns ops to the local worker by default.
    with tf.device(tf.train.replica_device_setter(
        worker_device="/job:worker/task:%d" % FLAGS.task_index,
        cluster=cluster)):

      # Build model...

      batch_size = 24
      src_len = 25
      source = np.ones((batch_size, src_len), dtype=int)

      embedding_encoder = tf.get_variable(
          "embedding_encoder", (99, 128), tf.float32)

      embedding_decoder = tf.get_variable(
          "embedding_decoder", (99, 128), tf.float32)

      with tf.variable_scope("encoder") as decoder_scope:
        encoder_emb_inp = tf.nn.embedding_lookup(
           embedding_encoder, source)

        encoder_cell = tf.contrib.rnn.BasicLSTMCell(
          num_units=256,
          forget_bias=1.0)
        sequence_length=tf.fill([batch_size], src_len)

        if FLAGS.time_major:
            # swap (batch, time) axes if time_major
            encoder_emb_inp=tf.transpose(encoder_emb_inp, [1, 0, 2])

        encoder_outputs, encoder_state = tf.nn.dynamic_rnn(
            encoder_cell,
            encoder_emb_inp,
            dtype=tf.float32,
            sequence_length=sequence_length,
            time_major=FLAGS.time_major,
            swap_memory=True)

      with tf.variable_scope("decoder") as decoder_scope:
        target_input = np.ones((batch_size, src_len), dtype=int)
        decoder_emb_inp = tf.nn.embedding_lookup(
            embedding_decoder, target_input) 

        # Helper
        if FLAGS.time_major:
           # swap (batch, time) axes if time_major
           decoder_emb_inp = tf.transpose(decoder_emb_inp, [1, 0, 2])

        helper = tf.contrib.seq2seq.TrainingHelper(
            decoder_emb_inp, sequence_length,
            time_major=FLAGS.time_major)

        decoder_cell = tf.contrib.rnn.BasicLSTMCell(
            num_units=256,
            forget_bias=1.0)
        decoder_initial_state = encoder_state

        # Decoder
        my_decoder = tf.contrib.seq2seq.BasicDecoder(
            decoder_cell,
            helper,
            decoder_initial_state)

        # Dynamic decoding
        decoder_outputs, final_context_state, _ = tf.contrib.seq2seq.dynamic_decode(
            my_decoder,
            output_time_major=FLAGS.time_major,
            swap_memory=True,
            scope=decoder_scope)

      global_step = tf.train.get_or_create_global_step()
      
      train_op = decoder_outputs

    # The StopAtStepHook handles stopping after running given steps.
    hooks=[tf.train.StopAtStepHook(last_step=100)]

    # The MonitoredTrainingSession takes care of session initialization,
    # restoring from a checkpoint, saving to a checkpoint, and closing when done
    # or an error occurs.
    with tf.train.MonitoredTrainingSession(master=server.target,
                                           is_chief=(FLAGS.task_index == 0),
                                           checkpoint_dir=FLAGS.out_dir,
                                           hooks=hooks) as mon_sess:
      # This is an infinite while loop since global_step does not increment at all.
      # In a real training, global_step is passed to an optimizer, then increments
      # after each step.
      while not mon_sess.should_stop():
        x = mon_sess.run(train_op)
        global_step_val = global_step.eval(session=mon_sess)
        print('global_step = {0}, time_major is {1}'.format(global_step_val, FLAGS.time_major))


if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.register("type", "bool", lambda v: v.lower() == "true")
  # Flags for defining the tf.train.ClusterSpec
  parser.add_argument(
      "--ps_hosts",
      type=str,
      default="",
      help="Comma-separated list of hostname:port pairs"
  )
  parser.add_argument(
      "--worker_hosts",
      type=str,
      default="",
      help="Comma-separated list of hostname:port pairs"
  )
  parser.add_argument(
      "--job_name",
      type=str,
      default="",
      help="One of 'ps', 'worker'"
  )
  # Flags for defining the tf.train.Server
  parser.add_argument(
      "--task_index",
      type=int,
      default=0,
      help="Index of task within the job"
  )
  parser.add_argument(
      "--out_dir",
      type=str,
      default="",
      help="output dir"
  )

  parser.add_argument(
      "--time_major",
      action='store_true',
      help="time major"
  )
  FLAGS, unparsed = parser.parse_known_args()
  tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
```

**Comment by junshi15** [comment]
@ebrevdo I just realized there could still be a bug in tensorflow. 
Indeed, the code above works perfectly. Note I used the following "lookup-then-transpose" to handle time_major:
```python
        encoder_emb_inp = tf.nn.embedding_lookup(
           embedding_encoder, source)
        if FLAGS.time_major:
            # swap (batch, time) axes if time_major
            encoder_emb_inp=tf.transpose(encoder_emb_inp, [1, 0, 2])
```
Another approach could be "transpose-then-lookup":
```python
      source = np.ones((batch_size, src_len), dtype=int)
      if FLAGS.time_major:
          source = tf.transpose(source)
      ...
      with tf.variable_scope("encoder") as decoder_scope:
        encoder_emb_inp = tf.nn.embedding_lookup(
           embedding_encoder, source)
```
the latter causes non-chief worker to hang. There is no error message, the worker just keeps starting master sessions. I found the latter hung because it is the approach taken by tensorflow/nmt, which you co-authored (thanks for the great contribution, I benefit enormously from the nmt code). When I try to extended nmt to distributed setting, I found the issue.

Do you know why "transpose-then-lookup" causes the non-chief worker to hang? I attached the "transpose-then-lookup" code for your reference.

```python
import argparse
import sys

import tensorflow as tf
import numpy as np
import time
FLAGS = None

def main(_):
  ps_hosts = FLAGS.ps_hosts.split(",")
  worker_hosts = FLAGS.worker_hosts.split(",")

  # Create a cluster from the parameter server and worker hosts.
  cluster = tf.train.ClusterSpec({"ps": ps_hosts, "worker": worker_hosts})

  # Create and start a server for the local task.
  server = tf.train.Server(cluster,
                           job_name=FLAGS.job_name,
                           task_index=FLAGS.task_index)
  if FLAGS.job_name == "ps":
    server.join()
  elif FLAGS.job_name == "worker":

    # Assigns ops to the local worker by default.
    with tf.device(tf.train.replica_device_setter(
        worker_device="/job:worker/task:%d" % FLAGS.task_index,
        cluster=cluster)):

      # Build model...

      batch_size = 24
      src_len = 25
      source = np.ones((batch_size, src_len), dtype=int)

      if FLAGS.time_major:
          source = tf.transpose(source)

      embedding_encoder = tf.get_variable(
          "embedding_encoder", (99, 128), tf.float32)

      embedding_decoder = tf.get_variable(
          "embedding_decoder", (99, 128), tf.float32)

      with tf.variable_scope("encoder") as decoder_scope:
        encoder_emb_inp = tf.nn.embedding_lookup(
           embedding_encoder, source)

        encoder_cell = tf.contrib.rnn.BasicLSTMCell(
          num_units=256,
          forget_bias=1.0)
        sequence_length=tf.fill([batch_size], src_len)

        encoder_outputs, encoder_state = tf.nn.dynamic_rnn(
            encoder_cell,
            encoder_emb_inp,
            dtype=tf.float32,
            sequence_length=sequence_length,
            time_major=FLAGS.time_major,
            swap_memory=True)

      with tf.variable_scope("decoder") as decoder_scope:
        target_input = np.ones((batch_size, src_len), dtype=int)

        if FLAGS.time_major:
            target_input = tf.transpose(target_input)

        decoder_emb_inp = tf.nn.embedding_lookup(
            embedding_decoder, target_input) 

        # Helper
        helper = tf.contrib.seq2seq.TrainingHelper(
            decoder_emb_inp, sequence_length,
            time_major=FLAGS.time_major)

        decoder_cell = tf.contrib.rnn.BasicLSTMCell(
            num_units=256,
            forget_bias=1.0)
        decoder_initial_state = encoder_state

        # Decoder
        my_decoder = tf.contrib.seq2seq.BasicDecoder(
            decoder_cell,
            helper,
            decoder_initial_state)

        # Dynamic decoding
        decoder_outputs, final_context_state, _ = tf.contrib.seq2seq.dynamic_decode(
            my_decoder,
            output_time_major=FLAGS.time_major,
            swap_memory=True,
            scope=decoder_scope)

      global_step = tf.train.get_or_create_global_step()
      
      train_op = decoder_outputs

    # The StopAtStepHook handles stopping after running given steps.
    hooks=[tf.train.StopAtStepHook(last_step=100)]

    # The MonitoredTrainingSession takes care of session initialization,
    # restoring from a checkpoint, saving to a checkpoint, and closing when done
    # or an error occurs.
    with tf.train.MonitoredTrainingSession(master=server.target,
                                           is_chief=(FLAGS.task_index == 0),
                                           checkpoint_dir=FLAGS.out_dir,
                                           hooks=hooks) as mon_sess:
      # This is an infinite while loop since global_step does not increment at all.
      # In a real training, global_step is passed to an optimizer, then increments
      # after each step.
      while not mon_sess.should_stop():
        x = mon_sess.run(train_op)
        global_step_val = global_step.eval(session=mon_sess)
        print('global_step = {0}, time_major is {1}'.format(global_step_val, FLAGS.time_major))


if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.register("type", "bool", lambda v: v.lower() == "true")
  # Flags for defining the tf.train.ClusterSpec
  parser.add_argument(
      "--ps_hosts",
      type=str,
      default="",
      help="Comma-separated list of hostname:port pairs"
  )
  parser.add_argument(
      "--worker_hosts",
      type=str,
      default="",
      help="Comma-separated list of hostname:port pairs"
  )
  parser.add_argument(
      "--job_name",
      type=str,
      default="",
      help="One of 'ps', 'worker'"
  )
  # Flags for defining the tf.train.Server
  parser.add_argument(
      "--task_index",
      type=int,
      default=0,
      help="Index of task within the job"
  )
  parser.add_argument(
      "--out_dir",
      type=str,
      default="",
      help="output dir"
  )

  parser.add_argument(
      "--time_major",
      action='store_true',
      help="time major"
  )
  FLAGS, unparsed = parser.parse_known_args()
  tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
```

**Comment by ebrevdo** [comment]
It still looks like you've got an error in either creating or running the
graph that you're just not catching. See if you're accidentally piping or
throwing out your stderr, or maybe it's in another log file?

**Comment by junshi15** [comment]
For "transpose-then-lookup" code, the chief worker ran fine, but non-chief worker hung. After I set `tf.logging.set_verbosity(tf.logging.DEBUG)`, I saw the following on the non-chief worker. It seems embedding_encoder and embedding_decoder were not ready on the non-chief worker. No other error messages were seen.

```python
junshi15$ python nonchief_hang_v3.py --time_major --out_dir=/tmp/rnn/work1 --ps_hosts=localhost:2222  --worker_hosts=localhost:1111,localhost:3333 --task_index=1 --job_name=worker

2018-08-06 07:27:35.223313: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-06 07:27:35.224656: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> localhost:2222}
2018-08-06 07:27:35.224674: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> localhost:1111, 1 -> localhost:3333}
2018-08-06 07:27:35.225027: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:332] Started server with target: grpc://localhost:3333
INFO:tensorflow:Graph was finalized.
2018-08-06 07:27:42.742037: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session 6f967f601337d97c with config:
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: embedding_encoder, embedding_decoder, encoder/rnn/basic_lstm_cell/kernel, encoder/rnn/basic_lstm_cell/bias, decoder/basic_lstm_cell/kernel, decoder/basic_lstm_cell/bias, global_step, ready: None
2018-08-06 07:28:12.781871: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session 3139c55b7e2bdbef with config:
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: embedding_encoder, embedding_decoder, ready: None
2018-08-06 07:28:42.816610: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session 7d5684fbb32ca03b with config:
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: embedding_encoder, embedding_decoder, ready: None
2018-08-06 07:29:12.848483: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session 34122298c96817e7 with config:
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: embedding_encoder, embedding_decoder, ready: None
2018-08-06 07:29:42.877087: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session 0e9164b2458e92cf with config:
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: embedding_encoder, embedding_decoder, ready: None
2018-08-06 07:30:12.905306: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session fb3c939889939c88 with config: 
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: embedding_encoder, embedding_decoder, ready: None
2018-08-06 07:30:42.936056: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session c3e8a41826633f8a with config:
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: embedding_encoder, embedding_decoder, ready: None
2018-08-06 07:31:12.966590: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session 284b8fd3e8c8772e with config:
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: embedding_encoder, embedding_decoder, ready: None
```

**Comment by ebrevdo** [comment]
Do you have logs for the non chief worker?

**Comment by junshi15** [comment]
Yes, the logs for non-chief worker is posted above. I was wondering if you meant chief worker. I posted the logs for chief worker below:
```
junshi15$ python nonchief_hang_v3.py --time_major  --out_dir=/tmp/rnn/work0 --ps_hosts=localhost:2222  --worker_hosts=localhost:1111,localhost:3333 --task_index=0 --job_name=worker
2018-08-06 09:31:55.765383: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-06 09:31:55.766691: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> localhost:2222}
2018-08-06 09:31:55.766719: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> localhost:1111, 1 -> localhost:3333}
2018-08-06 09:31:55.767065: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:332] Started server with target: grpc://localhost:1111
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-08-06 09:31:57.797718: I tensorflow/core/distributed_runtime/master_session.cc:1136] Start master session 6e427cebcbefcb54 with config:
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/rnn/work0/model.ckpt.
global_step = 0, time_major is True
global_step = 0, time_major is True
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 120 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sushreebarsa** [comment]
@junshi15 
We see that you are using old version of tensorflow  1.x which is not actively supported, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .To migrate your code please see [this](https://www.tensorflow.org/guide/migrate#1_replace_v1sessionrun_calls) guide . Thanks!
