### ISSUE TITLE
Failed to memcpy from device to host: CUDA_ERROR_LAUNCH_TIMEOUT when running CIFAR10 after 113K steps

### ISSUE THREAD

**Issue by hamidb** [tensorflow/tensorflow#2117]
I tried to run the cifar10 model provided from TF with GPU support. I was able to successfully install Tensorflow from source (with GPU) and also was able to run the `cifar10_train.py` with utilizing my GPU. However, after step=113330, I encountered the following error which is probably related to async memcpy from device to host. As my graphic card compute capability is 5.2, I thought it should not be due to compute capability conflicts. 

### Similar issues
#1477
#1060
But my error is slightly different

### Environment info
Operating System: Ubuntu 14.04
GPU:  GM200 - GeForce GTX TITAN X (rev a1)
Tensorflow 0.8 (installed from source)
Installed version of CUDA and cuDNN: 
cuda 7.5
cudnn 7.0 (v4)
using Anaconda virtual env

### Logs
```
2016-04-25 22:10:14.937118: step 113330, loss = 0.74 (1276.4 examples/sec; 0.100 sec/batch)

E tensorflow/stream_executor/cuda/cuda_driver.cc:1197] failed to enqueue async memcpy from device to host: CUDA_ERROR_LAUNCH_TIMEOUT; host dst: 0x7fbdd0001680; GPU src: 0xb06c84600; size: 3=0x3
E tensorflow/stream_executor/cuda/cuda_driver.cc:1099] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_TIMEOUT :: No stack trace available
E tensorflow/stream_executor/stream.cc:272] Error recording event in stream: error recording CUDA event on stream 0x1efe980: CUDA_ERROR_LAUNCH_TIMEOUT; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_TIMEOUT
F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:198] Unexpected Event status: 1
F tensorflow/core/common_runtime/gpu/gpu_util.cc:370] GPU sync failed
E tensorflow/stream_executor/cuda/cuda_driver.cc:1099] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_TIMEOUT :: No stack trace available
E tensorflow/stream_executor/cuda/cuda_driver.cc:1099] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_TIMEOUT :: No stack trace available
E tensorflow/stream_executor/cuda/cuda_driver.cc:1099] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_TIMEOUT :: No stack trace available
I tensorflow/stream_executor/stream.cc:826] stream 0x1efe860 did not wait for stream: 0x1efd340
Aborted (core dumped)

```

**Comment by poxvoculi** [comment]
Is this error reproducible, i.e. does it occur repeatedly at roughly that number of steps?  Are there any other indications of unusual behavior before this error, e.g. signs of memory exhaustion?

**Comment by hamidb** [comment]
@poxvoculi 
It is hard to reproduce it as it takes really long to reach 113K steps. I had it running overnight several times and sometimes my system reboots after core dumps. So I lost the step at which it failed.
I am trying to keep track of it in a log file to see if there is a random failure or not.
I did not notice any sign of memory exhaustion. Indeed, it was my initial guess. But what is the best way to ensure there is no memory bandwidth limit?
My current GPU memory usage at step=70K is 11501MiB with GPU utilization around %30-%45

**Comment by poxvoculi** [comment]
I have not personally seen this CUDA error previously.  The error likely is not directly related to the memcpy, but rather the memcpy is failing because the GPU is in a bad state.  Many CUDA driver commands are asynchronous: the error from a prior action is only fielded when trying to launch a subsequent action.  If it's a bad error (e.g. one we never expect to see), then a bad status will propagate back up to the top of TensorFlow. That's what's happening here.  NVIDIA documentation indicates that this error can result when a kernel takes too long to execute.  If you're not using any modified kernels and  are just running the provided model with the usual data, then no kernel should take an excessive amount of time unless something causes the GPU to not be able to make progress.  It's hard to guess what that might be.  TensorFlow uses its own external memory manager for GPU memory, so memory exhaustion *should* trigger a TF bad status exception on the CPU side, and never trigger a GPU error.  Since this error only showed up after a long period, I don't think it's impossible that it could be a hardware issue, e.g. an un-corrected memory error (IIRC, most consumer NVIDIA GPUs don't use ECC memory).

**Comment by hamidb** [comment]
Yes it takes a long time. And I figured out that it is not happened at the exact step. I re-ran the training this time with TF built using the whl file. And so far 238K step is reached without core dump.
Could it be according to building from source?
I did not change anything with respect the code, though.

**Comment by girving** [comment]
@hamidb: Building from source is fine.  Unfortunately, it sounds like this will be impossible to debug since it can't be reproduced, so I'll close for now.  Please reopen if reproduction becomes possible!

**Comment by nyartsgnaw** [comment]
I get the same bug. 
2017-07-13 22:05:28.022704: I tensorflow/stream_executor/stream.cc:1500] stream 0x5da97e0 did not wait for stream: 0x5da95b0
2017-07-13 22:05:28.022741: I tensorflow/stream_executor/stream.cc:4087] stream 0x5da97e0 did not memcpy host-to-device; source: 0x203861300
2017-07-13 22:05:28.022808: F tensorflow/core/common_runtime/gpu/gpu_util.cc:343] CPU->GPU Memcpy failed

**Comment by shiyongde** [comment]
the same 
2018-12-11 00:31:09.918511: E tensorflow/stream_executor/cuda/cuda_driver.cc:1130] failed to enqueue async memcpy from host to device: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure; GPU dst: 0x4232ce0b00; host src: 0x7f1f10244780; size: 1597440=0x186000
2018-12-11 00:31:09.918525: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2018-12-11 00:31:09.918534: E tensorflow/stream_executor/cuda/cuda_driver.cc:1000] could not wait stream on event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2018-12-11 00:31:09.918534: E tensorflow/stream_executor/cuda/cuda_driver.cc:1000] could not wait stream on event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2018-12-11 00:31:09.918568: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1

**Comment by JSchwerdtner** [comment]
the same
 E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:81]
2018-12-14 21:42:32.399322: I T:\src\github\tensorflow\tensorflow\stream_executor\stream.cc:1960] stream 000001C988E79E00 did not wait for stream: 000001C988E79680
2018-12-14 21:42:32.401562: I T:\src\github\tensorflow\tensorflow\stream_executor\stream.cc:1960] stream 000001C988E7A100 did not wait for stream: 000001C988E79680
2018-12-14 21:42:32.422902: I T:\src\github\tensorflow\tensorflow\stream_executor\stream.cc:4793] stream 000001C988E7A100 did not memcpy host-to-device; source: 000000021028F500
2018-12-14 21:42:32.409988: I T:\src\github\tensorflow\tensorflow\stream_executor\stream.cc:4780] stream 000001C988E79E00 did not memcpy device-to-host; source: 000000073AA53800
2018-12-14 21:42:32.401944: I T:\src\github\tensorflow\tensorflow\stream_executor\stream.cc:1960] stream 000001C988E79E00 did not wait for stream: 000001C988E79680
2018-12-14 21:42:32.435799: F T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_util.cc:339] CPU->GPU Memcpy failed

**Comment by JSchwerdtner** [comment]
got a solution

cudnn64_6.dll is missing in the Toolkit - bin folder.

**Comment by nicholasg97** [comment]
My solution related to the fact I was using 
`from numba import cuda
cuda.select_device(0)`

You have to use the latter line before interacting with tensorflow or keras at all.

**Comment by Terkea** [comment]
Has anyone found a fix to this yet? I'm encountering just the same problem
```
2020-04-04 07:32:27.274747: I tensorflow/stream_executor/stream.cc:1990] [stream=000002027C991AE0,impl=000002027F822190] did not wait for [stream=000002027C9908E0,impl=000002027F822160]
2020-04-04 07:32:27.278532: I tensorflow/stream_executor/stream.cc:4938] [stream=000002027C991AE0,impl=000002027F822190] did not memcpy host-to-device; source: 000002026F97A000
2020-04-04 07:32:27.282116: F tensorflow/core/common_runtime/gpu/gpu_util.cc:340] CPU->GPU Memcpy failed
```

**Comment by rokokorn** [comment]
@Terkea 
I have strange problem - identical dockerfile, on one machine it works (GTX1050TI), on laptop with MX250 i get the same error as you.

I found here #35029 that it could be linked with nvidia drivers - 430 with GTX and 440 with MX250.

**Comment by Terkea** [comment]
```python
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.compat.v1.Session(config=config)
```
adding those lines on top of my file right below the imports fixed this in my case.

**Comment by riteshahlawat** [comment]
@Terkea That worked for me, thanks so much!!!

**Comment by Terkea** [comment]
> @Terkea That worked for me, thanks so much!!!

glad I could help

**Comment by ronadlisko** [comment]
@Terkea Thank you so much. Your solution works in my case as well.
