### ISSUE TITLE
failed to enqueue CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by waTeim** [tensorflow/tensorflow#2190]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 15

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

The following were installed

cuda-repo-ubuntu1504_7.5-18_amd64.deb
cudnn-7.0-linux-x64-v4.0-prod.tgz

    jeffw@chill:~/src/tensorflow/tensorflow/examples/skflow$ ls -l /usr/local/cuda/lib64/libcud*
    -rw-r--r-- 1 root root 322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
    lrwxrwxrwx 1 root root     16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
    lrwxrwxrwx 1 root root     19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
    -rwxr-xr-x 1 root root 383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
    -rw-r--r-- 1 root root 720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
    lrwxrwxrwx 1 root root     34 Apr 30 16:31 /usr/local/cuda/lib64/libcudnn.so -> /usr/local/cudnn/lib64/libcudnn.so
    lrwxrwxrwx 1 root root     36 Apr 30 16:32 /usr/local/cuda/lib64/libcudnn.so.4 -> /usr/local/cudnn/lib64/libcudnn.so.4
    lrwxrwxrwx 1 root root     40 Apr 30 16:32 /usr/local/cuda/lib64/libcudnn.so.4.0.7 -> /usr/local/cudnn/lib64/libcudnn.so.4.0.7
    lrwxrwxrwx 1 root root     40 Apr 30 16:31 /usr/local/cuda/lib64/libcudnn_static.a -> /usr/local/cudnn/lib64/libcudnn_static.a

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

the above command fails, with `AttributeError: 'module' object has no attribute 'version'`however, the version is 0.8.0

* pip freeze:
    tensorflow==0.8.0

If installed from sources, provide the commit hash:

### Steps to reproduce
1. start with  the example `tensorflow/tensorflow/examples/skflow/text_classification_cnn.py`
2. use GTX 980 
3. modify example steps fairly large number (e.g. 2400)
4. modify **EMBEDDING_SIZE** to 16
5. modify **N_FILTERS** to 16
6. modify **WINDOW_SIZE** to 32.
7. run until crash 

### What have you tried?
1. various step numbers.  The default (100) does not crash, various other step crash eventually with larger number crashing sooner.  Perhaps this is a memory leak or other general failure to maintain datastructures. 
2. various values for the above variables some combinations work some don't.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

Can be found in [this gist](https://gist.github.com/waTeim/f243b94ff52f0bc1d9584991cd3cad8d)

**Comment by mrphoenix13** [comment]
can you copy the first lines when tensorflow tries to load libcudnn?

I think maybe it's because your are using cuDNN v5.

**Comment by waTeim** [comment]
Hmm well I just obtained cudnn on Saturday and specifically avoided v5, however cuda itself might be older; they're dated Aug 2015 (see below).  Also, previously i had cudnn v3 installed for caffe and deep dreams.  Maybe I need to reinstall (recompile) all the support packages obtained via pip?  

Nevertheless, here's the output (note I've modified/renamed the example) 

    jeffw@chill:~/src/tensorflow/tensorflow/examples/skflow$ CUDA_VISIBLE_DEVICES=0 python text_classification_mkp2b.py
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
    using saved form
    Total words: 26744
    I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
    name: GeForce GTX 980
    major: 5 minor: 2 memoryClockRate (GHz) 1.2785
    pciBusID 0000:03:00.0
    Total memory: 4.00GiB
    Free memory: 3.91GiB
    I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
    I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
    I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:03:00.0)


    lrwxrwxrwx  1 root  root       8 Nov 15 20:27 cuda -> cuda-7.5
    drwxr-xr-x 13 root  root    4096 Nov 15 20:26 cuda-7.5
    lrwxrwxrwx  1 root  root      24 Apr 30 16:22 cudnn -> cudnn-7.0-linux-x64-v4.0
    drwxr-xr-x  4 root  root    4096 Nov 15 21:00 cudnn-7.0-linux-x64-v3.0
    drwxr-xr-x  4 root  root    4096 Apr 30 16:22 cudnn-7.0-linux-x64-v4.0

I've already cut-pasted the cudnn libs (above) here are the others

     ls -l /usr/local/cuda/lib64/libcublas*
    -rw-r--r-- 1 root root 28585480 Aug 15  2015 /usr/local/cuda/lib64/libcublas_device.a
    lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcublas.so -> libcublas.so.7.5
    lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcublas.so.7.5 -> libcublas.so.7.5.18
    -rwxr-xr-x 1 root root 23938736 Aug 15  2015 /usr/local/cuda/lib64/libcublas.so.7.5.18
    -rw-r--r-- 1 root root 28220076 Aug 15  2015 /usr/local/cuda/lib64/libcublas_static.a
    ls -l /usr/local/cuda/lib64/libcufft*
    lrwxrwxrwx 1 root root        15 Aug 15  2015 /usr/local/cuda/lib64/libcufft.so -> libcufft.so.7.5
    lrwxrwxrwx 1 root root        18 Aug 15  2015 /usr/local/cuda/lib64/libcufft.so.7.5 -> libcufft.so.7.5.18
    -rwxr-xr-x 1 root root 111231960 Aug 15  2015 /usr/local/cuda/lib64/libcufft.so.7.5.18
    -rw-r--r-- 1 root root 115104400 Aug 15  2015 /usr/local/cuda/lib64/libcufft_static.a
    lrwxrwxrwx 1 root root        16 Aug 15  2015 /usr/local/cuda/lib64/libcufftw.so -> libcufftw.so.7.5
    lrwxrwxrwx 1 root root        19 Aug 15  2015 /usr/local/cuda/lib64/libcufftw.so.7.5 -> libcufftw.so.7.5.18
    -rwxr-xr-x 1 root root    447664 Aug 15  2015 /usr/local/cuda/lib64/libcufftw.so.7.5.18
    -rw-r--r-- 1 root root     42206 Aug 15  2015 /usr/local/cuda/lib64/libcufftw_static.a
    ls -l /usr/local/cuda/lib64/libcuda*
    -rw-r--r-- 1 root root 322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
    lrwxrwxrwx 1 root root     16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
    lrwxrwxrwx 1 root root     19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
    -rwxr-xr-x 1 root root 383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
    -rw-r--r-- 1 root root 720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
    ls -l /usr/local/cuda/lib64/libcurand*
    lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcurand.so -> libcurand.so.7.5
    lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcurand.so.7.5 -> libcurand.so.7.5.18
    -rwxr-xr-x 1 root root 51765952 Aug 15  2015 /usr/local/cuda/lib64/libcurand.so.7.5.18
    -rw-r--r-- 1 root root 51992564 Aug 15  2015 /usr/local/cuda/lib64/libcurand_static.a

**Comment by zheng-xq** [comment]
As a step to debug this problem, could you try to run without modify the classifier? 

In Cudnn documentation about this particular error: 

CUDNN_STATUS_MAPPING_ERROR
An access to GPU memory space failed, which is usually caused by a failure to bind a texture.
To correct: prior to the function call, unbind any previously bound textures.
Otherwise, this may indicate an internal error/bug in the library.

TensorFlow doesn't bind any texture with its Cudnn calls. So the last part indicated that it could be a problem in the library itself.

**Comment by waTeim** [comment]
After some experimentation, I found that to be able to reproduce the error, the dataset does not need to be changed, but changes to need to be made to one or more of the parameters **EMBEDDING_SIZE**,  **N_FILTERS**, and **WINDOW_SIZE**.  For example, setting these parameters to the following causes the error.

    EMBEDDING_SIZE = 16
    N_FILTERS = 16
    WINDOW_SIZE = 29

various values of **WINDOW_SIZE** were tried and some cause the error and some don't.  Larger values tend to cause the error (29,30,31,32) while smaller values don't (20,21,22). 

I'll update the original report to indicate this.

**Comment by agupta83** [comment]
Hi,
I am having similar problem on the project I am working. I am implementing [Convolutional Neural Networks for Sentence Classification](http://emnlp2014.org/papers/pdf/EMNLP2014181.pdf). I am getting this error irrespective of the parameter I choose. I have tried window size of 3, 4, 5 and various number of filters (32, 64, 128). It crashes at step **8100** step is all the parameter settings.

Below is small snippet from log. I have attached the log file [here](https://gist.github.com/agupta83/ecb3b4a7ba5e948216aa94cba755d26f). I am using TF 0.80 (2296dd8060ce77c71fc820c77442835f050399dd) and cuDNN v4. 

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:0a:00.0
Total memory: 12.00GiB
Free memory: 11.76GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:09:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 2 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:06:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 3 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:05:00.0
Total memory: 12.00GiB
Free memory: 11.33GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1 2 3 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 2:   Y Y Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 3:   Y Y Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:756] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:0a:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:756] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:756] Creating TensorFlow device (/gpu:2) -> (device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:756] Creating TensorFlow device (/gpu:3) -> (device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0)
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:0a:00.0
/job:localhost/replica:0/task:0/gpu:1 -> device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0
/job:localhost/replica:0/task:0/gpu:2 -> device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0
/job:localhost/replica:0/task:0/gpu:3 -> device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0
I tensorflow/core/common_runtime/direct_session.cc:151] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:0a:00.0
/job:localhost/replica:0/task:0/gpu:1 -> device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0
/job:localhost/replica:0/task:0/gpu:2 -> device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0
/job:localhost/replica:0/task:0/gpu:3 -> device: 3, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0

...
...
...
I tensorflow/core/common_runtime/simple_placer.cc:667] save/control_dependency: /job:localhost/replica:0/task:0/cpu:0
2016-05-09 18:27:25.888013: step 10, loss = 3.76 (281.4 examples/sec; 0.227 sec/batch)
2016-05-09 18:27:28.206509: step 20, loss = 3.71 (282.3 examples/sec; 0.227 sec/batch)
...
...
2016-05-09 18:34:27.086410: step 1700, loss = 1.23 (295.2 examples/sec; 0.217 sec/batch)
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 176886 get requests, put_count=175848 evicted_count=1000 eviction_rate=0.00568673 and unsatisfied allocation rate=0.0120869
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 100 to 110
2016-05-09 18:34:31.962832: step 1710, loss = 1.16 (291.8 examples/sec; 0.219 sec/batch)
2016-05-09 18:34:34.287784: step 1720, loss = 0.99 (270.6 examples/sec; 0.237 sec/batch)
...
...
2016-05-09 19:01:22.861471: step 8100, loss = 1.08 (262.5 examples/sec; 0.244 sec/batch)
F tensorflow/stream_executor/cuda/cuda_dnn.cc:917] failed to enqueue convolution on stream: CUDNN_STATUS_MAPPING_ERROR
Aborted (core dumped)
```

**Comment by waTeim** [comment]
I'm updating this now as a placeholder with additional verification to follow; though this bug appears to be completely reproducible, it also appears to be tied to some subtle component of the install for the error appears to have ceased after upgrading to Ubuntu 16 from Ubuntu 15.  It appears that neither cuda nor cudnn libraries were changed, so possibly this is due to a change of libraries (sklearn?) reinstalled by a global upgrade of pip, or other support libraries or possibly this is a change to the kernel.

**Comment by girving** [comment]
@zheng-xq: Any thoughts as to how to better diagnose?

@agupta83: What platform are you on?  I'd like to know if it's Ubuntu version specific, since @waTeim says it goes away at a later version.

**Comment by agupta83** [comment]
I have Ubuntu 14.04 LTS (3.16.0-71-generic kernel) on my system.

**Comment by girving** [comment]
Since the bug is fixed by upgrading Ubuntu and thus is likely to be a bug outside TensorFlow, I'm going to close this issue.  If upgrading is not an option and more information is available we can reopen, and of course we're happy to accept PRs fixing TensorFlow for older systems.

**Comment by chenxi116** [comment]
It seems that this problem still exists for Tensorflow 0.9 and 0.10. @agupta83  Have you solved the problem without upgrading Ubuntu system?

**Comment by agupta83** [comment]
@chenxi116 Nope. I couldn't figure out the issue.

**Comment by ritchieng** [comment]
@chenxi116 I'm facing this exact same issue and stuck at iteration 3000 or so.

- Ubuntu 14.04.4 LTS
- TensorFlow 0.8.0
- Keras 1.0.4
- Python 2.7
- CUDA 7.5
- CuDNN 5

I'm attempting to upgrade to Ubuntu 16 and the latest TensorFlow version.
