### ISSUE TITLE
Issue with Tensorflow softmax on gpus

### ISSUE THREAD

**Issue by TGithubbr** [tensorflow/tensorflow#22099]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
none
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.10.0 gpu
- **Python version**:
3.5.5
- **Bazel version (if compiling from source)**:
n/a
- **GCC/Compiler version (if compiling from source)**:
n/a
- **CUDA/cuDNN version**:
CUDA 9.0/cuDNN v7.2.1.38 for CUDA 9.0 
- **GPU model and memory**:
GTX 980 4GB
- **Exact command to reproduce**:
n/a

### Describe the problem
There is still a huge issue with not included GPU kernels in the latest tensorflow python version. When you try to run 

> import tensorflow as tf
> with tf.device('/{}:{}'.format('gpu','0')):
>     x = [0., -1., 2., 3.]
>     softmax_x = tf.nn.softmax(x)
>     session = tf.Session()
>     print(session.run(softmax_x))

it's exiting with the following error:

```
Traceback (most recent call last):
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1261, in _run_fn
    self._extend_graph()
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1295, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'Softmax': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]

         [[Node: Softmax = Softmax[T=DT_FLOAT, _device="/device:GPU:0"](Reshape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools\check_tensorflow.py", line 7, in <module>
    print(session.run(softmax_x))
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'Softmax': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]

         [[Node: Softmax = Softmax[T=DT_FLOAT, _device="/device:GPU:0"](Reshape)]]

Caused by op 'Softmax', defined at:
  File "tools\check_tensorflow.py", line 5, in <module>
    softmax_x = tf.nn.softmax(x)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1738, in softmax
    return _softmax(logits, gen_nn_ops.softmax, axis, name)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1680, in _softmax
    output = compute_op(logits)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 7672, in softmax
    "Softmax", logits=logits, name=name)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\Users\xxx\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'Softmax': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]

         [[Node: Softmax = Softmax[T=DT_FLOAT, _device="/device:GPU:0"](Reshape)]]
```

The softmax cuda kernel seems not to be included in the package. This means that when you don't specify explicitly to use the gpu, it will just run softmax on cpu, which leads to cpu usages of 100% and very low gpu usage from 10 to 20%, and if you do it crashes.
Especially for beginners this can be very confusing and hard to find. Also it has a huge impact on overall performance.

So are there any solutions for this problem?

**Comment by yongtang** [comment]
I don't have Windows access though I tried on Linux the Softmax is available on GPU:
```
$ python2
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> with tf.device('/{}:{}'.format('gpu','0')):
...   x = [0., -1., 2., 3.]
...   softmax_x = tf.nn.softmax(x)
...   session = tf.Session()
...   print(session.run(softmax_x))
... 
2018-09-05 22:09:50.785901: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-05 22:09:52.634968: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-05 22:09:52.635365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-09-05 22:09:52.635392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-05 22:09:52.940328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-05 22:09:52.940375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-09-05 22:09:52.940384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-09-05 22:09:52.940659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
[0.03467109 0.01275478 0.25618663 0.69638747]
>>> 
```

I think that might be a Windows specific issue?

**Comment by TGithubbr** [comment]
This is the strange thing: there is also another issue, where someone used complicated building instructions to build the windows version with softmax gpu support: https://github.com/tensorflow/tensorflow/issues/15254
This one led to nothing.
I'm working on replicating his instructions, but still I think this should be correctly implementet into the official version

**Comment by TGithubbr** [comment]
So are you working on this?

**Comment by yongtang** [comment]
@TGithubbr I don't have access to Windows so I may not be able to provide much help for Windows-related issues. Would be happy to take a further look if the issue could be reproduced on Linux.

**Comment by TGithubbr** [comment]
I just tested it on linux and it works perfectly allright. So if you at any time get the chance to test the windows build for yourself please check this bug out. I have not enough experience in this field to find the issue for myself

**Comment by reedwm** [comment]
/CC @gunan, do you know why this is occurring?

**Comment by gunan** [comment]
@meteorcloudy @mrry to help
I cannot see any problems.
Only potential is, is it possible when we override EIGEN_STRONG_INLINE on windows something weird happens here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/softmax_op_gpu.cu.cc#L38

**Comment by meteorcloudy** [comment]
@TGithubbr I notice you were using v1.10, which is still built by CMake.

I think this problem no longer exists when building TensorFlow on Windows with Bazel, which will be default from v1.11.

Here's my result with a tensorflow nightly build:
```
pcloudy@TENSORLOW-JENKI C:\tools\msys64\home\pcloudy\workspace\tf_gpu_test
# type test.py
import tensorflow as tf
with tf.device('/{}:{}'.format('gpu','0')):
    x = [0., -1., 2., 3.]
    softmax_x = tf.nn.softmax(x)
    session = tf.Session()
    print(session.run(softmax_x))

pcloudy@TENSORLOW-JENKI C:\tools\msys64\home\pcloudy\workspace\tf_gpu_test
# C:\python36\python test.py
2018-09-26 15:23:05.448428: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-09-26 15:23:07.100434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.18GiB freeMemory: 10.87GiB
2018-09-26 15:23:07.208930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:05.0
totalMemory: 11.18GiB freeMemory: 10.87GiB
2018-09-26 15:23:07.318715: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 2 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:06.0
totalMemory: 11.18GiB freeMemory: 10.87GiB
2018-09-26 15:23:07.435113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 3 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:07.0
totalMemory: 11.18GiB freeMemory: 10.87GiB
2018-09-26 15:23:07.563203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 4 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:08.0
totalMemory: 11.18GiB freeMemory: 10.87GiB
2018-09-26 15:23:07.677694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 5 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:09.0
totalMemory: 11.18GiB freeMemory: 10.87GiB
2018-09-26 15:23:07.797429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 6 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:0a.0
totalMemory: 11.18GiB freeMemory: 10.87GiB
2018-09-26 15:23:07.911700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 7 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:0b.0
totalMemory: 11.18GiB freeMemory: 10.87GiB
2018-09-26 15:23:07.940870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7
2018-09-26 15:23:12.710532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-26 15:23:12.723927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 2 3 4 5 6 7
2018-09-26 15:23:12.732976: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y Y Y N N N N
2018-09-26 15:23:12.745232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N Y Y N N N N
2018-09-26 15:23:12.756203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 2:   Y Y N Y N N N N
2018-09-26 15:23:12.766825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 3:   Y Y Y N N N N N
2018-09-26 15:23:12.777259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 4:   N N N N N Y Y Y
2018-09-26 15:23:12.788947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 5:   N N N N Y N Y Y
2018-09-26 15:23:12.801252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 6:   N N N N Y Y N Y
2018-09-26 15:23:12.812655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 7:   N N N N Y Y Y N
2018-09-26 15:23:12.827793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10534 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2018-09-26 15:23:12.861306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10534 MB memory) -> physical GPU (device: 1, name: Tesla K80, pci bus id: 0000:00:05.0, compute capability: 3.7)
2018-09-26 15:23:12.898461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10534 MB memory) -> physical GPU (device: 2, name: Tesla K80, pci bus id: 0000:00:06.0, compute capability: 3.7)
2018-09-26 15:23:12.927800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10534 MB memory) -> physical GPU (device: 3, name: Tesla K80, pci bus id: 0000:00:07.0, compute capability: 3.7)
2018-09-26 15:23:12.956151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 10534 MB memory) -> physical GPU (device: 4, name: Tesla K80, pci bus id: 0000:00:08.0, compute capability: 3.7)
2018-09-26 15:23:12.986229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 10534 MB memory) -> physical GPU (device: 5, name: Tesla K80, pci bus id: 0000:00:09.0, compute capability: 3.7)
2018-09-26 15:23:13.015754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 10534 MB memory) -> physical GPU (device: 6, name: Tesla K80, pci bus id: 0000:00:0a.0, compute capability: 3.7)
2018-09-26 15:23:13.047423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 10534 MB memory) -> physical GPU (device: 7, name: Tesla K80, pci bus id: 0000:00:0b.0, compute capability: 3.7)
[0.03467109 0.01275478 0.25618663 0.69638747]
```

**Comment by TGithubbr** [comment]
I tested 1,11,0rc2 and it really works! Thanks!

**Comment by karkirowle** [comment]
I would not bother to reopen this issue, but for Cuda Compute Capability 3.0 this is actually the last build which is supported from the pre-built packages on Windows (i.e. when you query tensorflow for the devices, it won't promptly say that you have a Cuda too low).
While I understand that officially TF is not supporting this Cuda version, I would still be interested in what is the problem, or if there is a workaround for this (apart from training on CPU).

**Comment by TGithubbr** [comment]
Yes don't bother. They don't know what they are doing because they apparently don't have Windows.  If the build passes they apparently just put it up

**Comment by TGithubbr** [comment]
You could try to build it with bazel which I tried but was never able to get to work. They won't be able to do anything because they don't have Windows (google to cheap for that) and don't test their builds
