### ISSUE TITLE
doc bug on gpu installation page

### ISSUE THREAD

**Issue by chahld** [tensorflow/tensorflow#22651]
Your install website (https://www.tensorflow.org/install/gpu) has the wrong cuda version number referenced. It says that tensorflow wants cuda 9.0 and cuda 7.2, but cuda 7.2.1 seems to work only with cuda 9.2. If you don't upgrade cuda you get this obscure error: 
 
"Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED"

I have written custom code, but not relevant for this problem.
os: ubuntu 16.04
tensorflow-gpu installed with pip
tensorflow version: v1.11.0-0-gc19e29306c 1.11.0
python 3.5.2

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by av8ramit** [comment]
@chahld you can ignore @tensorflowbutler . @tfboyd any ideas on what exactly it should be?

**Comment by chahld** [comment]
cuda 9.2 and cudnn 7.2.1 with tensorflow 1.11 worked for me.

**Comment by tfboyd** [comment]
It all depends on where you install from.  The instructions assume you install from the tensorflow official pip by pypi or our website, e.g.  `pip install tensorflow-gpu`

The official pip requires CUDA 9.0 and cuDNN greater than or equal to 7.2.  You can use newer cuDNN's but CUDA does not have the same backward compatibility agreement.  

I have been told the Anaconda install is compiled with CUDA 9.2 by the Conda team and that would require CUDA 9.2.  

Finally, there have been changes to the license with NVIDIA that would allow us to include CUDA/cuDNN/TensorRT/NCCL (now open source) in the builds, but that will bring the package size to almost 500MB well above current pypi limits, which are normally maybe 50MB, if my memory is correct, that we have had increased to well over 200MB.

**Comment by tfboyd** [comment]
@chahld   To help other people please update your comment to say where your install came from.  My concern is people will think they should use CUDA 9.2 and that is not going to work with 1.11 from the official pip.  Thank you for helping.

**Comment by chahld** [comment]
My original comment does say that: "tensorflow-gpu installed with pip", but I added a summary to try to make it clearer. 

If you choose cudnn 7.2.1 you have to use cuda 9.2. Based on nvidia's website: 
https://developer.nvidia.com/rdp/cudnn-archive. This is the only 7.2.xxx version that is available and it says that it requires cuda 9.2. 

Note I chose to install cudnn 7.2.1 instead of latest 7.3.1 because of tensorflow docs. 7.3.1 has a version that works with cuda 9.0. So the 9.0+7.3.1 combination might work also (I haven't tried it).

**Comment by tfboyd** [comment]
@chahld  NVIDIA had been slow to move the items to the archive.  If you install with apt-get you can still get 7.2.x with CUDA 9.2.  I would suggest just moving 7.3.  I am surprised CUDA 9.2 is working for you but I am glad you got it working.  Sorry about the request, for some reason I looked at your comment and though you were a different person from the original poster.  I thought you were just a random person adding a data point.

**Comment by tfboyd** [comment]
@chahld 

Went an extra mile here is what I tried:
- `nvidia-docker run -it nvidia/cuda:9.2-devel-ubuntu16.04 bash`
- `apt-get install python3`
- `apt-get install python3-pip`
- `pip3 install tensorflow-gpu`
- `python3`  and then `import tensorflow as tf`

Error is what I expected below, but it is possible that you CUDA 9.0 is still in a path and I have used cuDNN that says it is for a different version of CUDA that I installed a few times.  No idea how often that should work but it likely works more often than not I would guess as I do not think it does any kind of check the API just has to match up. 

```bash
File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```
