### ISSUE TITLE
Tensorflow C++ 1.9.0 ~1.11.0 failed call to cuInit: CUresult(-1)  but libcuda.so is ok, where is the problem?

### ISSUE THREAD

**Issue by TsinghuaTop** [tensorflow/tensorflow#22863]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution Linux kernel 3.10.104:
- **TensorFlow installed from source 1.9.0 build with gpu
       configure with open cuda support and build with command as 
      "bazel build -c opt --config=mkl --config=cuda --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 //tensorflow:libtensorflow_cc.so"
- **TensorFlow version 1.9.0:
- **Python version**:
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 

- **CUDA/cuDNN version:/usr/local/cuda-9.0/
- **GPU model and memory**:
Wed Oct 10 20:14:44 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:04:00.0 Off |                    0 |
| N/A   51C    P0   136W / 250W |  16817MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           On   | 00000000:06:00.0 Off |                    0 |
| N/A   50C    P0   143W / 250W |  16817MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           On   | 00000000:07:00.0 Off |                    0 |
| N/A   49C    P0    93W / 250W |  16817MiB / 22912MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           On   | 00000000:08:00.0 Off |                    0 |
| N/A   50C    P0   138W / 250W |  16817MiB / 22912MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P40           On   | 00000000:0C:00.0 Off |                    0 |
| N/A   40C    P0    56W / 250W |   2435MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           On   | 00000000:0D:00.0 Off |                    0 |
| N/A   26C    P8    10W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P40           On   | 00000000:0E:00.0 Off |                    0 |
| N/A   25C    P8    10W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P40           On   | 00000000:0F:00.0 Off |                    0 |
| N/A   28C    P8    10W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|

my problem is  that when i use c++ api  to inference，but get error as follows:
2018-10-10 20:19:47.332240: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUresult(-1)
2018-10-10 20:19:47.332371: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 100-88-66-85
2018-10-10 20:19:47.332402: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 100-88-66-85
2018-10-10 20:19:47.332545: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.81.0
2018-10-10 20:19:47.332661: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.81.0
2018-10-10 20:19:47.332691: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 384.81.0
2018-10-10 20:19:47.349695: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.

the c++ code as follows:

int main(int argc, char const *argv[]) {
    const char* devices = getenv("CUDA_VISIBLE_DEVICES");
    if(devices!=NULL)
        LOG_INFO("devices:%s", devices);
    std::string model_path = "wavenet.pb";
    tensorflow::GraphDef graph;
    tensorflow::Status load_graph_status = ReadBinaryProto(tensorflow::Env::Default(), model_path.c_str(), &graph);
    if (!load_graph_status.ok()) {
        LOG_ERROR("Failed to load pb graph:%s", load_graph_status.error_message().c_str());
        return load_graph_status.code();
    }
    // config
    tensorflow::SessionOptions options;
    int num_threads_1 = 4;
    int num_threads_2 = 4;
    if (num_threads_1 > 0) {
        options.config.set_intra_op_parallelism_threads(num_threads_1);
        options.config.set_inter_op_parallelism_threads(num_threads_2);
	options.config.mutable_gpu_options()->set_visible_device_list("0");
    }
    // create session
    std::unique_ptr<tensorflow::Session> session;
    session.reset(tensorflow::NewSession(options));
    tensorflow::Status session_create_status = session->Create(graph);
    if (!session_create_status.ok()) {
        LOG_ERROR("Failed to create tensorflow graph: %s", session_create_status.error_message().c_str());
        return load_graph_status.code();
    }

    const std::string input_tensor_name = "Predict/mel:0";
    const std::string output_tensor_name = "Predict/wav:0";

    int32_t batch_size = 1;
    //int32_t frame_nums = (int)(24000 / 256);
    int32_t frame_nums = 1;
    int32_t dims = 80;
    std::vector<float> spectrum;
    std::vector<float> wave;
    spectrum.resize(frame_nums, 0);

    LOG_INFO("fill data to input tensor begin");
    tensorflow::Tensor input_tensor(tensorflow::DT_FLOAT, tensorflow::TensorShape({batch_size, frame_nums, dims}));
    auto input_tensor_matrix = input_tensor.tensor<float, 3>();
    for (int32_t x = 0; x < batch_size; ++x) {
        for (int y = 0; y < frame_nums; ++y) {
            for (int z = 0; z < dims; ++z) {
                int32_t index = x * frame_nums * dims + y * frame_nums + z;
                input_tensor_matrix(x, y, z) = spectrum[index];
            }
        }
    }
    LOG_INFO("fill data to input tensor end");
    std::vector<std::pair<std::string, tensorflow::Tensor>> inputs;
    std::vector<tensorflow::Tensor> outputs;
    inputs.push_back(std::pair<std::string, tensorflow::Tensor>(input_tensor_name, input_tensor));
    LOG_INFO("session run begin");
    tensorflow::Status run_status = session->Run(inputs, {output_tensor_name}, {}, &outputs);
    LOG_INFO("session run end");
    if (!run_status.ok()) {
        LOG_ERROR("Running model failed: %s", run_status.error_message().c_str());
        return load_graph_status.code();
    }
    auto output_c = outputs[0].tensor<float, 3>();
    int32_t length = outputs[0].dim_size(2);
    wave.resize(batch_size * 1 * length);
    for (int32_t x = 0; x < batch_size; ++x) {
        for (int y = 0; y < 1; ++y) {
            for (int z = 0; z < length; ++z) {
                int32_t index = x * 1 * length + y * 1 + z;
                wave[index] = output_c(x, y, z);
            }
        }
    }
    session->Close();
    return 0;
}

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce
Mobile device

**Comment by TsinghuaTop** [comment]
I have solved this problem，just export LD_LIBRARY_PATH of nvidia lib before the cuda
