### ISSUE TITLE
tf.matmul fails with CUBLAS_STATUS_NOT_SUPPORTED for large matrices when using CUDA 9.1 

### ISSUE THREAD

**Issue by malcolmst** [tensorflow/tensorflow#23473]
I am hitting this issue on multiple development machines with different GPUs, and all versions of Tensorflow >= 1.9.0. I have a CUDA 9.1 requirement on the host machine, so downgrading to CUDA 9.0 is not an option for me. 

See https://stackoverflow.com/questions/50911052/tensorflow-matmul-blas-xgemmbatched-launch-failed/50918250 for a possibly related issue, though that involved Tensorflow 1.8.0.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): _Yes, a minimum repro is below_
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): _Linux Ubuntu 16.04_
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: _n/a_
- TensorFlow installed from (source or binary): _source_
- TensorFlow version (use command below): _1.9.0 to 1.11.0 (does not reproduce in 1.8.0)_
- Python version: _2.7_
- Bazel version (if compiling from source): _Bazel 0.10.0 for  Tensorflow 1.9.0, Bazel 0.18.0 for Tensorflow 1.10.0 and newer_
- GCC/Compiler version (if compiling from source): _GCC 5.4.0_
- CUDA/cuDNN version: _CUDA 9.1.85 / cuDNN 7.0.5_
- GPU model and memory: _GTX 1080 w/ 7400 MB, GTX 1060 w/ 5600 MB_

**Describe the current behavior**

tf.matmul is failing to multiply matrices above a certain size, with error:
`failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED`

I have confirmed using `nvidia-smi` that the GPU is nowhere close to running out of memory.

**Describe the expected behavior**

The matrix multiplication should complete successfully.

**Code to reproduce the issue**

This is borrowed from the stackoverflow link above:

```python
import tensorflow as tf
import numpy as np

config = tf.ConfigProto()
config.gpu_options.allow_growth=True
tf.Session(config=config).close()

def calc():
    N = 15 # works for N <= 14
    a = 16
    b = 8
    X = np.random.rand(N, 11520, b, 1).astype(np.float32)
    print(X.nbytes*1e-6, "MB")
    W = np.random.rand(N, 11520, a, b).astype(np.float32)
    print(W.nbytes*1e-6, "MB")
    X_ = tf.constant(X, name="X-constant", dtype=tf.float32)
    W_ = tf.constant(W, name="W-constant", dtype=tf.float32)

    return tf.matmul(W_, X_, name="mymatmul")

tf.reset_default_graph()
a = calc()
sess = tf.Session()
sess.run(tf.global_variables_initializer())
b = sess.run(a)
sess.close()
print(b.shape)
```

**Other info / logs**

I found a workaround for this issue is to patch `CUDABlas::DoBlasGemmBatchedInternal` in `tensorflow/stream_extractor/cuda/cuda_blas.cc` to disable the `#if CUDA_VERSION >= 9010` block which calls `wrap::cublasGemmBatchedEx`. Downgrading to Tensorflow <= 1.8.0 also resolves the issue for me (that codeblock was added in Tensorflow 1.9.0).

Running the above code (N=15) with Tensorflow 1.11.0:
```
2018-11-02 23:13:48.059128: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-02 23:13:48.059860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.40GiB
2018-11-02 23:13:48.059884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-02 23:13:48.282603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-02 23:13:48.282631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-02 23:13:48.282636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-02 23:13:48.282790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7137 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
(5.529599999999999, 'MB')
(88.47359999999999, 'MB')
2018-11-02 23:13:48.963544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-02 23:13:48.963579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-02 23:13:48.963585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-02 23:13:48.963588: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-02 23:13:48.963722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7137 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-11-02 23:13:51.146858: E tensorflow/stream_executor/cuda/cuda_blas.cc:652] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED
2018-11-02 23:13:51.146900: E tensorflow/stream_executor/cuda/cuda_blas.cc:2574] Internal: failed BLAS call, see log for details
Traceback (most recent call last):
  File "./tf_matmul.py", line 25, in <module>
    b = sess.run(a)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMMBatched launch failed : a.shape=[172800,16,8], b.shape=[172800,8,1], m=16, n=1, k=8, batch_size=172800
	 [[{{node mymatmul}} = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](W-constant, X-constant)]]

Caused by op u'mymatmul', defined at:
  File "./tf_matmul.py", line 22, in <module>
    a = calc()
  File "./tf_matmul.py", line 19, in calc
    return tf.matmul(W_, X_, name="mymatmul")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 2015, in matmul
    a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1245, in batch_mat_mul
    "BatchMatMul", x=x, y=y, adj_x=adj_x, adj_y=adj_y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Blas xGEMMBatched launch failed : a.shape=[172800,16,8], b.shape=[172800,8,1], m=16, n=1, k=8, batch_size=172800
	 [[{{node mymatmul}} = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](W-constant, X-constant)]]
```

Reducing the matrix size (N=14):
```
2018-11-02 23:18:29.127555: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-02 23:18:29.128409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.39GiB
2018-11-02 23:18:29.128441: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-02 23:18:29.482292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-02 23:18:29.482346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-02 23:18:29.482361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-02 23:18:29.482670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7131 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
(5.160959999999999, 'MB')
(82.57535999999999, 'MB')
2018-11-02 23:18:30.200524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-02 23:18:30.200586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-02 23:18:30.200598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-02 23:18:30.200605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-02 23:18:30.200837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7131 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
(14, 11520, 16, 1)

```

After patching `CUDABlas::DoBlasGemmBatchedInternal` (N=15):

```
2018-11-02 23:28:05.667458: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-02 23:28:05.668033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.39GiB
2018-11-02 23:28:05.668046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-02 23:28:05.866043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-02 23:28:05.866069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-02 23:28:05.866074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-02 23:28:05.866218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7129 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
(5.529599999999999, 'MB')
(88.47359999999999, 'MB')
2018-11-02 23:28:06.452688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-02 23:28:06.452722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-02 23:28:06.452727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-02 23:28:06.452730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-02 23:28:06.452858: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7129 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
(15, 11520, 16, 1)

```

Patch for workaround:
```patch
diff --git a/tensorflow/stream_executor/cuda/cuda_blas.cc b/tensorflow/stream_executor/cuda/cuda_blas.cc
index ab7091b..50579b6 100644
--- a/tensorflow/stream_executor/cuda/cuda_blas.cc
+++ b/tensorflow/stream_executor/cuda/cuda_blas.cc
@@ -18,6 +18,8 @@ limitations under the License.
 
 #define SE_CUDA_DATA_HALF CUDA_R_16F
 
+#define USE_CUBLAS_GEMM_BATCHED_EX false
+
 #include "tensorflow/stream_executor/cuda/cuda_blas.h"
 
 // Both Eigen Half.h and CUDA cuda_fp16.h provide similar typedef for __half. As
@@ -2482,7 +2484,7 @@ port::Status CUDABlas::DoBlasGemmBatchedInternal(
 
   cudaDataType_t data_type = CUDADataType<T>::type;
 
-#if CUDA_VERSION >= 9010
+#if CUDA_VERSION >= 9010 && USE_CUBLAS_GEMM_BATCHED_EX
   int cc_major, cc_minor;
   if (stream->parent()->GetDeviceDescription().cuda_compute_capability(
           &cc_major, &cc_minor) &&
```

**Comment by harshini-gadige** [comment]
@mrry  PTAL

**Comment by mrry** [comment]
Forwarding this to @azaks2 who has access to more CUDA expertise than I do.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @azaks2: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sanjoy** [comment]
Closing as stale because we use CUDA 10.1 now.  Please reopen if necessary.

**Comment by Gaozhongpai** [comment]
> I am hitting this issue on multiple development machines with different GPUs, and all versions of Tensorflow >= 1.9.0. I have a CUDA 9.1 requirement on the host machine, so downgrading to CUDA 9.0 is not an option for me.
> 
> See https://stackoverflow.com/questions/50911052/tensorflow-matmul-blas-xgemmbatched-launch-failed/50918250 for a possibly related issue, though that involved Tensorflow 1.8.0.
> 
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): _Yes, a minimum repro is below_
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): _Linux Ubuntu 16.04_
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: _n/a_
> * TensorFlow installed from (source or binary): _source_
> * TensorFlow version (use command below): _1.9.0 to 1.11.0 (does not reproduce in 1.8.0)_
> * Python version: _2.7_
> * Bazel version (if compiling from source): _Bazel 0.10.0 for  Tensorflow 1.9.0, Bazel 0.18.0 for Tensorflow 1.10.0 and newer_
> * GCC/Compiler version (if compiling from source): _GCC 5.4.0_
> * CUDA/cuDNN version: _CUDA 9.1.85 / cuDNN 7.0.5_
> * GPU model and memory: _GTX 1080 w/ 7400 MB, GTX 1060 w/ 5600 MB_
> 
> **Describe the current behavior**
> 
> tf.matmul is failing to multiply matrices above a certain size, with error:
> `failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED`
> 
> I have confirmed using `nvidia-smi` that the GPU is nowhere close to running out of memory.
> 
> **Describe the expected behavior**
> 
> The matrix multiplication should complete successfully.
> 
> **Code to reproduce the issue**
> 
> This is borrowed from the stackoverflow link above:
> 
> ```python
> import tensorflow as tf
> import numpy as np
> 
> config = tf.ConfigProto()
> config.gpu_options.allow_growth=True
> tf.Session(config=config).close()
> 
> def calc():
>     N = 15 # works for N <= 14
>     a = 16
>     b = 8
>     X = np.random.rand(N, 11520, b, 1).astype(np.float32)
>     print(X.nbytes*1e-6, "MB")
>     W = np.random.rand(N, 11520, a, b).astype(np.float32)
>     print(W.nbytes*1e-6, "MB")
>     X_ = tf.constant(X, name="X-constant", dtype=tf.float32)
>     W_ = tf.constant(W, name="W-constant", dtype=tf.float32)
> 
>     return tf.matmul(W_, X_, name="mymatmul")
> 
> tf.reset_default_graph()
> a = calc()
> sess = tf.Session()
> sess.run(tf.global_variables_initializer())
> b = sess.run(a)
> sess.close()
> print(b.shape)
> ```
> 
> **Other info / logs**
> 
> I found a workaround for this issue is to patch `CUDABlas::DoBlasGemmBatchedInternal` in `tensorflow/stream_extractor/cuda/cuda_blas.cc` to disable the `#if CUDA_VERSION >= 9010` block which calls `wrap::cublasGemmBatchedEx`. Downgrading to Tensorflow <= 1.8.0 also resolves the issue for me (that codeblock was added in Tensorflow 1.9.0).
> 
> Running the above code (N=15) with Tensorflow 1.11.0:
> 
> ```
> 2018-11-02 23:13:48.059128: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-11-02 23:13:48.059860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
> name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
> pciBusID: 0000:01:00.0
> totalMemory: 7.92GiB freeMemory: 7.40GiB
> 2018-11-02 23:13:48.059884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
> 2018-11-02 23:13:48.282603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-02 23:13:48.282631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
> 2018-11-02 23:13:48.282636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
> 2018-11-02 23:13:48.282790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7137 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> (5.529599999999999, 'MB')
> (88.47359999999999, 'MB')
> 2018-11-02 23:13:48.963544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
> 2018-11-02 23:13:48.963579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-02 23:13:48.963585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
> 2018-11-02 23:13:48.963588: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
> 2018-11-02 23:13:48.963722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7137 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 2018-11-02 23:13:51.146858: E tensorflow/stream_executor/cuda/cuda_blas.cc:652] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED
> 2018-11-02 23:13:51.146900: E tensorflow/stream_executor/cuda/cuda_blas.cc:2574] Internal: failed BLAS call, see log for details
> Traceback (most recent call last):
>   File "./tf_matmul.py", line 25, in <module>
>     b = sess.run(a)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 887, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1110, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1286, in _do_run
>     run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1308, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InternalError: Blas xGEMMBatched launch failed : a.shape=[172800,16,8], b.shape=[172800,8,1], m=16, n=1, k=8, batch_size=172800
> 	 [[{{node mymatmul}} = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](W-constant, X-constant)]]
> 
> Caused by op u'mymatmul', defined at:
>   File "./tf_matmul.py", line 22, in <module>
>     a = calc()
>   File "./tf_matmul.py", line 19, in calc
>     return tf.matmul(W_, X_, name="mymatmul")
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 2015, in matmul
>     a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1245, in batch_mat_mul
>     "BatchMatMul", x=x, y=y, adj_x=adj_x, adj_y=adj_y, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> InternalError (see above for traceback): Blas xGEMMBatched launch failed : a.shape=[172800,16,8], b.shape=[172800,8,1], m=16, n=1, k=8, batch_size=172800
> 	 [[{{node mymatmul}} = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](W-constant, X-constant)]]
> ```
> 
> Reducing the matrix size (N=14):
> 
> ```
> 2018-11-02 23:18:29.127555: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-11-02 23:18:29.128409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
> name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
> pciBusID: 0000:01:00.0
> totalMemory: 7.92GiB freeMemory: 7.39GiB
> 2018-11-02 23:18:29.128441: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
> 2018-11-02 23:18:29.482292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-02 23:18:29.482346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
> 2018-11-02 23:18:29.482361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
> 2018-11-02 23:18:29.482670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7131 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> (5.160959999999999, 'MB')
> (82.57535999999999, 'MB')
> 2018-11-02 23:18:30.200524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
> 2018-11-02 23:18:30.200586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-02 23:18:30.200598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
> 2018-11-02 23:18:30.200605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
> 2018-11-02 23:18:30.200837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7131 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> (14, 11520, 16, 1)
> ```
> 
> After patching `CUDABlas::DoBlasGemmBatchedInternal` (N=15):
> 
> ```
> 2018-11-02 23:28:05.667458: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-11-02 23:28:05.668033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
> name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
> pciBusID: 0000:01:00.0
> totalMemory: 7.92GiB freeMemory: 7.39GiB
> 2018-11-02 23:28:05.668046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
> 2018-11-02 23:28:05.866043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-02 23:28:05.866069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
> 2018-11-02 23:28:05.866074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
> 2018-11-02 23:28:05.866218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7129 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> (5.529599999999999, 'MB')
> (88.47359999999999, 'MB')
> 2018-11-02 23:28:06.452688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
> 2018-11-02 23:28:06.452722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-02 23:28:06.452727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
> 2018-11-02 23:28:06.452730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
> 2018-11-02 23:28:06.452858: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7129 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> (15, 11520, 16, 1)
> ```
> 
> Patch for workaround:
> 
> ```diff
> diff --git a/tensorflow/stream_executor/cuda/cuda_blas.cc b/tensorflow/stream_executor/cuda/cuda_blas.cc
> index ab7091b..50579b6 100644
> --- a/tensorflow/stream_executor/cuda/cuda_blas.cc
> +++ b/tensorflow/stream_executor/cuda/cuda_blas.cc
> @@ -18,6 +18,8 @@ limitations under the License.
>  
>  #define SE_CUDA_DATA_HALF CUDA_R_16F
>  
> +#define USE_CUBLAS_GEMM_BATCHED_EX false
> +
>  #include "tensorflow/stream_executor/cuda/cuda_blas.h"
>  
>  // Both Eigen Half.h and CUDA cuda_fp16.h provide similar typedef for __half. As
> @@ -2482,7 +2484,7 @@ port::Status CUDABlas::DoBlasGemmBatchedInternal(
>  
>    cudaDataType_t data_type = CUDADataType<T>::type;
>  
> -#if CUDA_VERSION >= 9010
> +#if CUDA_VERSION >= 9010 && USE_CUBLAS_GEMM_BATCHED_EX
>    int cc_major, cc_minor;
>    if (stream->parent()->GetDeviceDescription().cuda_compute_capability(
>            &cc_major, &cc_minor) &&
> ```

Hi, I have the same problem. 

2020-04-01 20:21:43.695815: E tensorflow/stream_executor/cuda/cuda_blas.cc:652] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED
2020-04-01 20:21:43.695883: E tensorflow/stream_executor/cuda/cuda_blas.cc:2574] Internal: failed BLAS call, see log for details

InternalError (see above for traceback): Blas xGEMMBatched launch failed : a.shape=[245760,8,16], b.shape=[245760,16,16], m=8, n=16, k=16, batch_size=245760
	 [[node layers/einsum/MatMul (defined at /home/pai/3dfaceRe/RandLA-Net/RandLANet.py:327)  = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](layers/einsum/Reshape, layers/einsum/Reshape_1)]]
	 [[{{node optimizer/gradients/layers/Encoder_layer_3LFAmlp2/BiasAdd_grad/BiasAddGrad/_663}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6262_...iasAddGrad", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

I have Tensorflow = 1.12 and CUDA=9.2 in Conda environment. I couldn't find the file of  "tensorflow/stream_executor/cuda/cuda_blas.cc" and only have "tensorflow/stream_executor/cuda/cuda_blas.h" 

Does anyone know how to solve this problem?

**Comment by sanjoy** [comment]
> I have Tensorflow=1.12, Cudatoolkit=9.2, and Cudnn=7.6.5 in Conda environment.

If at all possible I'd suggest using a more recent version of TF.  1.12 is quite old, and we're not in a position to debug issues with it.

**Comment by HaotianWang6897** [comment]
My case due to a version conflict in CUDA9.0 and TensorFlow 1.12.0

Easiest solution:  use a NumPy function wrap in TensorFlow.

use result = tf.py_func(np_matmul, [x, y], tf.float32) instead.
