### ISSUE TITLE
matmul with large matrices fails with float16, but succeeds with float32

### ISSUE THREAD

**Issue by ilia-nikiforov** [tensorflow/tensorflow#23861]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes. see below

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
This bug occurs with every version of GPU tensorflow I've tried or built, including several binaries and currently building from source.

- **TensorFlow version (use command below)**:
v1.12.0-rc0-2836-gd63e3ea

- **Python version**:
2.7

- **Bazel version (if compiling from source)**:
0.19.1

- **GCC/Compiler version (if compiling from source)**:
5.4.0

- **CUDA/cuDNN version**:
Currently building from source with CUDA 10.0 and cuDNN 7.4, but previously the bug occurred with binaries using CUDA 9.0 and cuDNN 7.4 and cuDNN 7.0

- **GPU model and memory**:
GeForce GTX 1070 8GB

- **Exact command to reproduce**:
Run the following python script:
```
import numpy as np
import tensorflow as tf

xvar = tf.placeholder (tf.float16, name="x",shape=[None,2])

weight_init = tf.uniform_unit_scaling_initializer (factor=1,dtype=tf.float16)
W = tf.get_variable ("W",[2,2],initializer=weight_init,dtype=tf.float16)

output = tf.matmul (xvar,W)

init = tf.global_variables_initializer ()

with tf.Session () as sess:
    sess.run (init)
    o = sess.run (output, feed_dict = {xvar:np.zeros ((8500000,2),dtype=np.float16)})
```

### Describe the problem
Matmul fails with large float16 matrices. If you reduce the size of the matrix to 8e6, the code runs. If you keep the size of the matrix the same, but change all the data types to float32, it runs. The limiting factor seems to be the single largest dimension. For example, doing the matmul with sizes (8e6,100) and (100,100) works in float16

Perhaps this is not a Tensorflow issue, but an internal CUDA issue?

### Source code / logs
```
WARNING:tensorflow:From float16_demo.py:6: __init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
WARNING:tensorflow:From /home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2018-11-19 15:49:01.787213: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:993] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-19 15:49:01.787660: I tensorflow/compiler/xla/service/service.cc:149] XLA service 0x4863200 executing computations on platform CUDA. Devices:
2018-11-19 15:49:01.787676: I tensorflow/compiler/xla/service/service.cc:157]   StreamExecutor device (0): GeForce GTX 1070, Compute Capability 6.1
2018-11-19 15:49:01.787882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7465
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.52GiB
2018-11-19 15:49:01.787894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2018-11-19 15:49:01.788392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-19 15:49:01.788401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-11-19 15:49:01.788405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-11-19 15:49:01.788537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7316 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-11-19 15:49:03.017490: E tensorflow/stream_executor/cuda/cuda_blas.cc:652] failed to run cuBLAS routine cublasSgemmEx: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "float16_demo.py", line 15, in <module>
    o = sess.run (output, feed_dict = {xvar:np.zeros ((8500000,2),dtype=np.float16)})
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(8500000, 2), b.shape=(2, 2), m=8500000, n=2, k=2
	 [[node MatMul (defined at float16_demo.py:9) ]]

Caused by op u'MatMul', defined at:
  File "float16_demo.py", line 9, in <module>
    output = tf.matmul (xvar,W)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 2272, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4763, in mat_mul
    name=name)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 512, in new_func
    return func(*args, **kwargs)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3268, in create_op
    op_def=op_def)
  File "/home/ilia/tensorflow/venv-source-nightly-2018nov19/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1831, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(8500000, 2), b.shape=(2, 2), m=8500000, n=2, k=2
	 [[node MatMul (defined at float16_demo.py:9) ]]
```

**Comment by ymodak** [comment]
I was able to run your code snippet successfully. I suspect it's not a TensorFlow related issue, however you can try shutting down all the processes/notebooks that utilize your GPU and run the code again.

**Comment by ilia-nikiforov** [comment]
I am running this in multi-user.target, so other GPU utilization is
non-existent. Do you have the same GPU or different? Perhaps on other GPUs
the limit is higher? I understand that there may be a limit to how big
matrices can be, it just doesn't make sense for that limit to be lower for
fp16 than it is for fp32.

**Comment by FredVaugeois** [comment]
Could it be because of a change in the float type in Python 2.7 vs Python 3.6? I personally use Python 3.6 and it works with no problem... I know they tweaked some little details with floats in the newer version, but I think it's just related to int division (now giving floats instead of rounded integers), so it should not have anything to do with it. Still, that could be something to try out for you!

**Comment by reedwm** [comment]
/CC @chsigg, can you take a look?

**Comment by ilia-nikiforov** [comment]
Tried on python3 with the stable 1.13 binary release and CUDA 10.0, identical behavior

**Comment by ilia-nikiforov** [comment]
Identical behavior on python3 TF 2.0 alpha with the following code:

```
import numpy as np
import tensorflow as tf

@tf.function
def myMatMul (x,W):
    return tf.matmul (x,W)

W = np.ones ((2,2), dtype=np.float16)
x = np.zeros ((8500000,2), dtype=np.float16)

output = myMatMul (x,W)

```

As before, reducing the large dimension to 8e6 results in a successful computation, or keeping it at 8.5e6 and changing the data type to np.float32

**Comment by jvishnuvardhan** [comment]
@ilia-nikiforov Is this still an issue for you? I ran your code in [colab](https://colab.research.google.com/gist/jvishnuvardhan/d55d141cb5eab8da277f08bf37c9ff30/untitled48.ipynb) with GPU and don't see any issue. I guess your GPU may had less memory when compared to colab GPU. 

There were lot of performance improvement over the time and TF2.3 and `tf-nightly` has some performance upgrades. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as this was resolved in `tf-nightly`. Please feel free to reopen the issue If i am mistaken. Thanks!
