### ISSUE TITLE
tf.contrib.factorization.python.ops.factorization_ops.WALSModel greedy parallelization

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#24140]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04 and macOS 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12+
- Python version: 3.5
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 9.2
- GPU model and memory: Titan

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

when trying to train a WALSModel in parallel (e.g. with n different parameter sets or any other tf model) using the python multiprocessing module (or in two different scripts), CUDA errors occur. It seems that WALSModel is written to automatically parallelize itself and in a greedy manner...

looking at the __init__, I can not see a way to specify to limit this...
```
def __init__(self,
               input_rows,
               input_cols,
               n_components,
               unobserved_weight=0.1,
               regularization=None,
               row_init="random",
               col_init="random",
               num_row_shards=1,
               num_col_shards=1,
               row_weights=1,
               col_weights=1,
               use_factors_weights_cache=True,
               use_gramian_cache=True,
               use_scoped_vars=False):
```

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@SumNeuron Could you provide any example code to reproduce the error? Also, mention any details about context, describe the expected behavior, and provide any error snapshots. All these details will be useful to find a root cause of the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
@SumNeuron Could you provide any example code to reproduce the error? Also, mention any details about context, describe the expected behavior, and provide any error snapshots. All these details will be useful to find a root cause of the issue. Thanks!

**Comment by SumNeuron** [comment]
@jvishnuvardhan here is a google [colab] for the issue. Note, it will not run as it requires data to do so and colab's do not store uploaded data. It should, however, be sufficient to see what causes the error. Namely:

```
def wrapper():
    wals() #<--- run WALSModel

with Pool(2) as p:
    p.map(wrapper, [i for i in range(2)])
```

[colab]: https://colab.research.google.com/drive/1S6JLTI0cQkbXFijPAKznd5NcnyL3apg7

**Comment by alextp** [comment]
@agarwal-ashish I think you wrote wals, want to take a look at this?

**Comment by walidk** [comment]
I took a look at the attached colab.
Here is an attempt at writing a minimal working example that will run different WALS models with the multiprocessing library. This works for me, I am not seeing the issue described in the bug.

Please give it a try and let me know if this didn't work for you.

```
import tensorflow as tf, numpy as np
import scipy
from tensorflow.contrib.factorization.python.ops.factorization_ops import WALSModel

def to_sp_tensor(dense):
  sparse = scipy.sparse.coo_matrix(dense)
  sparse_indicies = list(zip(
    sparse.row.astype(np.int64).tolist(),
    sparse.col.astype(np.int64).tolist()))
  return tf.SparseTensor(
      sparse_indicies, sparse.data.astype(np.float32), sparse.shape)

def run_wals(input_matrix, embedding_dim, regularization, num_iter, tag):
  with tf.Graph().as_default():
    print('[%s] initializing model' % tag)
    num_rows, num_cols = input_matrix.shape
    model = WALSModel(num_rows, num_cols, embedding_dim, regularization=0.1)
    sp_input = to_sp_tensor(input_matrix)
    sp_input_t = to_sp_tensor(input_matrix.T)
    row_ops = model.update_row_factors(sp_input)
    col_ops = model.update_col_factors(sp_input_t, transpose_input=True)

    with tf.Session() as sess:
      sess.run(model.initialize_op)
      sess.run(model.worker_init)
      for i in range(num_iter):
        # update rows
        sess.run(model.row_update_prep_gramian_op)
        sess.run(model.initialize_row_update_op)
        _, _, loss, reg, _ = sess.run(row_ops)
        print('[%s] iteration %d row sweep, loss: %f' % (tag, i, loss + reg))
        # update cols
        sess.run(model.col_update_prep_gramian_op)
        sess.run(model.initialize_col_update_op)
        _, _, loss, reg, _ = sess.run(col_ops)
        print('[%s] iteration %d col sweep, loss: %f' % (tag, i, loss + reg))
    print('[%s] done.' % tag)
```
An important comment here: for the column solves, you need to feed the transposed matrix, and use the argument `transpose_input=True`. As written in the attached colab, the updates will not be correct.

To run with multiprocessing:
```
import multiprocessing

INPUT_MATRIX = np.array(
    [[0.1, 0.0, 0.2, 0.0, 0.4, 0.5, 0.0],
     [0.0, 1.1, 0.0, 1.3, 1.4, 0.0, 1.6],
     [2.0, 0.0, 0.0, 2.3, 0.0, 2.5, 0.0],
     [3.0, 0.0, 3.2, 3.3, 0.0, 3.5, 0.0],
     [0.0, 4.1, 0.0, 0.0, 4.4, 0.0, 4.6]])
embedding_dim = 3
num_iter = 4
regs = [0.01, 0.1]

ps = [
  multiprocessing.Process(
    target=run_wals, args=(INPUT_MATRIX, embedding_dim, regs[i], num_iter, i))
    for i in range(2)]
for p in ps:
  p.start()
for p in ps:
  p.join()
```

Output:
```
[0] initializing model
[1] initializing model
[0] iteration 0 row sweep, loss: 45.192287
[1] iteration 0 row sweep, loss: 40.113457
[0] iteration 0 col sweep, loss: 7.389457
[0] iteration 1 row sweep, loss: 4.829801
[1] iteration 0 col sweep, loss: 12.314854
[0] iteration 1 col sweep, loss: 4.464665
[0] iteration 2 row sweep, loss: 4.270123
[1] iteration 1 row sweep, loss: 10.322790
[0] iteration 2 col sweep, loss: 4.156906
[1] iteration 1 col sweep, loss: 9.163980
[0] iteration 3 row sweep, loss: 4.078035
[1] iteration 2 row sweep, loss: 8.338335
[0] iteration 3 col sweep, loss: 4.025699
[0] done.
[1] iteration 2 col sweep, loss: 7.691652
[1] iteration 3 row sweep, loss: 7.198600
[1] iteration 3 col sweep, loss: 6.796245
[1] done.
```

**Comment by SumNeuron** [comment]
@walidk  seems to work, I'll try putting it in my app's use case and see if that solves the problem

**Comment by walidk** [comment]
Thanks for the update. Closing this now.
Feel free to reopen if you run issues with the solution.

**Comment by SumNeuron** [comment]
@walidk it has been a while but for clarity (and anyone else who sees this in the future) I wish to clarify your statement regarding the need to transpose the sparse tensor:

>     col_ops = model.update_col_factors(sp_input_t, transpose_input=True)

According to the document string for `update_col_factors`

> `transpose_input` if True the input will be logically transposed and the columns corresponding to the transposed input are updated

By default `transpose_input` is false and as used in google's cloud computing [example](https://cloud.google.com/solutions/machine-learning/recommendation-system-tensorflow-create-model)

```python
row_update_op = model.update_row_factors(sp_input=input_tensor)[1]
col_update_op = model.update_col_factors(sp_input=input_tensor)[1]
```
While not explicitly stated in the docstring for the method `update_col_factors` it appears to imply that the argument  `transpose_input` is a boolean flag to save some time if the transpose matrix is already available. 

Further, since the docstring states "_the columns corresponding to the **transposed** input are updated_", passing a transformed matrix and then having it transpose it again seems to be wasteful. (as why not just pass the original matrix).
