### ISSUE TITLE
Memory error running tensorflow code on GPU

### ISSUE THREAD

**Issue by erickrf** [tensorflow/tensorflow#2416]
### Environment info

Operating System: Scientific Linux release 7.2 (Nitrogen)

Installed version of CUDA and cuDNN: 
$ ll /usr/local/cuda/lib/libcud*

```
-rw-r--r-- 1 root root 185K Mar 18 15:29 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root   16 Mar 18 15:29 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root   19 Mar 18 15:29 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 305K Mar 18 15:29 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 545K Mar 18 15:29 /usr/local/cuda/lib/libcudart_static.a
```

Installed version 0.8.0 with anaconda.

I'm getting a MemoryError when I try to run a tensorflow script on a server with GPU support. The same code, with the same inputs, runs without problems on my local machine, which is CPU only and has 8 GB of RAM. 

I tried to allocate up to 64 GB to run the script, and the same problem occurred. Here's the stacktrace:

```
Traceback (most recent call last):
  File "src/train.py", line 93, in <module>
    learning_rate=args.rate, l2_constant=args.l2)
  File "/hltsrv0/rocha/rte-lstm/src/rte_lstm.py", line 189, in __init__
    gradients, v = zip(*optimizer.compute_gradients(self.loss))
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 241, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 485, in gradients
    in_grads = control_flow_ops.tuple(in_grads)
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1784, in tuple
    tpl.append(with_dependencies([gate], t))
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1664, in with_dependencies
    return _Identity(output_tensor, name=name)
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 114, in _Identity
    return array_ops.identity(data, name=name)
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 609, in identity
    return _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1165, in __init__
    self._recompute_node_def()
  File "/hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1318, in _recompute_node_def
    self._control_inputs])
MemoryError
```

From the stack trace, I see that the error happens sometime during the gradient computation, but I have no idea why it only happens when I run the code in the server. 

By the way, I'm not experienced in GPU computation. I just tried running the same code in an environment with the cuda libraries and tensorflow with GPU support installed.

**Comment by mrry** [comment]
This doesn't look like the error is related to the GPU: the `MemoryError` is raised while you are **building** your graph, and before anything will be transferred to the GPU.

It's difficult to tell what's going wrong here without seeing your `train.py` code. One possibility is that your server has a 32-bit version of Python installed for some reason. Can you try running the following snippet and reporting the result?

```python
import sys
print("%x" % sys.maxsize, sys.maxsize > 2**32)
```

**Comment by erickrf** [comment]
It's 64.

```
In [2]: print("%x" % sys.maxsize, sys.maxsize > 2**32)
('7fffffffffffffff', True)
```

My `train.py` code is somewhat big. I will try to isolate the problem and post back.

**Comment by erickrf** [comment]
Ok, I tried some snippets via the interpreter and got a segfault as soon as I started a session:

```
In [2]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally

In [6]: sess = tf.Session()
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:05:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:06:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 2 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:09:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
Segmentation fault (core dumped)
```

I also tried `tf.InteractiveSession` with the same result.

I suppose that something could be wrong with CUDA libraries version... but I have no idea where to begin.

**Comment by erickrf** [comment]
My problem seems to be related to #152. I tried to set `CUDA_VISIBLE_DEVICES=1`, as indicated in that issue, since I'm using a shared server. This made python (but not ipython) work with a simple statement after `-c`, but the interactive shell still results in a segfault:

```
$ CUDA_VISIBLE_DEVICES=1 python -c "import tensorflow as tf;tf.InteractiveSession()"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:06:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:06:00.0)
```

```
$ CUDA_VISIBLE_DEVICES=1 python 
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
>>> sess = tf.InteractiveSession()
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:06:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:06:00.0)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted (core dumped)
```

Any suggestions about what might be wrong?

**Comment by mrry** [comment]
@zheng-xq: Do you have any ideas what could be causing an exception/segfault in the GPU device construction code path?

**Comment by girving** [comment]
The original `MemoryError` is probably caused by trying to allocate more memory than the machine has available.  In order to debug the segfaults, we'd have to get more information, such as stack traces or information from an attached debugger.

**Comment by zheng-xq** [comment]
@erickrf, one possibility is that with a shared server, some other processes are using that GPU. Could you run nvidia-smi and make sure no other is using that GPU? 

A few experiments to try: 

1. Allocate the server to yourself, if only temporarily, and see if the problem goes away. 
2. Add stack trace or printf near here and see what is causing the GPU construction to fail. 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/gpu_device.cc#L587

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen if it is still an issue.

**Comment by erickrf** [comment]
So I finally could look again into this problem.

@zheng-xq , I could not allocate the server just for myself, but here is the output of `nvidia-smi` at the time of a new similar `MemoryError`:

```
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:05:00.0     Off |                    0 |
| N/A   32C    P8    46W / 149W |   3501MiB / 11519MiB |     89%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
| N/A   69C    P0   172W / 149W |   3800MiB / 11519MiB |     91%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 0000:09:00.0     Off |                    0 |
| N/A   46C    P0    91W / 149W |   3500MiB / 11519MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 0000:0A:00.0     Off |                    0 |
| N/A   47C    P8    30W / 149W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     56514    C   python                                        3477MiB |
|    1     43200    C   python                                        3776MiB |
|    2     57034    C   python                                        3476MiB |
+-----------------------------------------------------------------------------+
```

So one of the GPU's was completely free.
I could not recompile tensorflow with the printf statements yet, because I don't have root access in this server and installing all the necessary requirements is quite difficult.

But I also tried running the following dummy script:

```
import tensorflow as tf

sess = tf.InteractiveSession()
x = tf.constant(1, shape=[100, 100, 100])
y = tf.constant(2, shape=[100, 100, 100])
z = x + y

print(z.eval())
```

Curiously, running the above script gives me different outputs depending on the amount of RAM allocated, and none of them is a Python `MemoryError`.

- With 8GB or less:
```
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:05:00.0
Total memory: 7.92GiB
Free memory: 7.79GiB
Segmentation fault (core dumped)
```
gdb says it was terminated with SIGSEGV. Stack:

```
#0  0x00002abe9c8880bc in perftools::gputools::StreamExecutor::DeviceMemoryUsage(long long*, long long*) const ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#1  0x00002abe9c623258 in tensorflow::GPUMachineManager() () from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#2  0x00002abe9c6214d0 in tensorflow::BaseGPUDeviceFactory::GetValidDeviceIds(std::vector<int, std::allocator<int> >*) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#3  0x00002abe9c621d50 in tensorflow::BaseGPUDeviceFactory::CreateDevices(tensorflow::SessionOptions const&, std::string const&, std::vector<tensorflow::Device*, std::allocator<tensorflow::Device*> >*) () from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#4  0x00002abe9c7fa0d6 in tensorflow::DeviceFactory::AddDevices(tensorflow::SessionOptions const&, std::string const&, std::vector<tensorflow::Device*, std::allocator<tensorflow::Device*> >*) () from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#5  0x00002abe9c5e5b71 in tensorflow::DirectSessionFactory::NewSession(tensorflow::SessionOptions const&) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#6  0x00002abe9c81c6d7 in tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#7  0x00002abe9c7eb0e1 in TF_NewSession () from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#8  0x00002abe9ba4ec3b in _wrap_TF_NewSession () from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#9  0x00002abe9219fe15 in call_function (oparg=<optimized out>, pp_stack=0x7ffdfdfbd588) at Python/ceval.c:4350
#10 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#11 0x00002abe921a0a2e in PyEval_EvalCodeEx (co=0x2abeee194cb0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=4, kws=0x2abf45186d48, kwcount=0, 
    defs=0x2abeee0932e8, defcount=3, closure=0x0) at Python/ceval.c:3582
#12 0x00002abe9219fa55 in fast_function (nk=<optimized out>, na=4, n=<optimized out>, pp_stack=0x7ffdfdfbd7a8, func=0x2abeee08ccf8) at Python/ceval.c:4446
#13 call_function (oparg=<optimized out>, pp_stack=0x7ffdfdfbd7a8) at Python/ceval.c:4371
#14 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#15 0x00002abe921a0a2e in PyEval_EvalCodeEx (co=0x2abeee0953b0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=1, kws=0x0, kwcount=0, defs=0x2abeee0934c8, 
    defcount=3, closure=0x0) at Python/ceval.c:3582
#16 0x00002abe9211c3a1 in function_call (func=0x2abeee098aa0, arg=0x2abe91f6ca50, kw=0x0) at Objects/funcobject.c:526
#17 0x00002abe920ecd23 in PyObject_Call (func=0x2abeee098aa0, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2546
#18 0x00002abe920ff4bf in instancemethod_call (func=0x2abeee098aa0, arg=0x2abe91f6ca50, kw=0x0) at Objects/classobject.c:2602
#19 0x00002abe920ecd23 in PyObject_Call (func=0x2abef7f5ecd0, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2546
#20 0x00002abe92159320 in slot_tp_init (self=0x2abf4517e2d0, args=0x2abe91eb2050, kwds=0x0) at Objects/typeobject.c:5715
#21 0x00002abe9214fdd8 in type_call (type=<optimized out>, args=0x2abe91eb2050, kwds=0x0) at Objects/typeobject.c:745
#22 0x00002abe920ecd23 in PyObject_Call (func=0x30dac40, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2546
#23 0x00002abe9219df54 in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7ffdfdfbddc8, func=0x30dac40) at Python/ceval.c:4568
#24 call_function (oparg=<optimized out>, pp_stack=0x7ffdfdfbddc8) at Python/ceval.c:4373
#25 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
(continues to vanilla python calls)
``` 

- With 10GB:
```
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:05:00.0
Total memory: 8.92GiB
Free memory: 8.10GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:06:00.0
Total memory: 8.92GiB
Free memory: 7.50GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 2 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:09:00.0
Total memory: 8.92GiB
Free memory: 8.12GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 3 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:0a:00.0
Total memory: 8.92GiB
Free memory: 8.40GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1 2 3 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 2:   Y Y Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 3:   Y Y Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:05:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K80, pci bus id: 0000:06:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:2) -> (device: 2, name: Tesla K80, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:3) -> (device: 3, name: Tesla K80, pci bus id: 0000:0a:00.0)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted (core dumped)
``` 
gdb says the program was terminated with SIGABRT and the following stack: 
```
#0  0x00002b80422765f7 in raise () from /lib64/libc.so.6
#1  0x00002b8042277ce8 in abort () from /lib64/libc.so.6
#2  0x00002b8054de59d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00002b8054de3946 in ?? () from /lib64/libstdc++.so.6
#4  0x00002b8054de3973 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00002b8054de3b93 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00002b8054e38e30 in std::__throw_system_error(int) () from /lib64/libstdc++.so.6
#7  0x00002b8054e3a559 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>) () from /lib64/libstdc++.so.6
#8  0x00002b804be074b0 in tensorflow::(anonymous namespace)::PosixEnv::StartThread(tensorflow::ThreadOptions const&, std::string const&, std::function<void ()>) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#9  0x00002b804bdf1338 in tensorflow::thread::ThreadPool::Impl::Impl(tensorflow::Env*, tensorflow::ThreadOptions const&, std::string const&, int) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#10 0x00002b804bdf1f2f in tensorflow::thread::ThreadPool::ThreadPool(tensorflow::Env*, tensorflow::ThreadOptions const&, std::string const&, int) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#11 0x00002b804bdf205a in tensorflow::thread::ThreadPool::ThreadPool(tensorflow::Env*, std::string const&, int) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#12 0x00002b804ba71f98 in tensorflow::(anonymous namespace)::NewThreadPool(tensorflow::SessionOptions const&) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#13 0x00002b804ba77abc in tensorflow::DirectSession::DirectSession(tensorflow::SessionOptions const&, tensorflow::DeviceMgr const*) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#14 0x00002b804ba77bb5 in tensorflow::DirectSessionFactory::NewSession(tensorflow::SessionOptions const&) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#15 0x00002b804bcae6d7 in tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) ()
   from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#16 0x00002b804bc7d0e1 in TF_NewSession () from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#17 0x00002b804aee0c3b in _wrap_TF_NewSession () from /hltsrv0/rocha/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#18 0x00002b8041631e15 in call_function (oparg=<optimized out>, pp_stack=0x7fffb2412cd8) at Python/ceval.c:4350
#19 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#20 0x00002b8041632a2e in PyEval_EvalCodeEx (co=0x2b809d626cb0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=4, kws=0x2b810c4c0d48, kwcount=0, 
    defs=0x2b809d5252e8, defcount=3, closure=0x0) at Python/ceval.c:3582
#21 0x00002b8041631a55 in fast_function (nk=<optimized out>, na=4, n=<optimized out>, pp_stack=0x7fffb2412ef8, func=0x2b809d51ecf8) at Python/ceval.c:4446
#22 call_function (oparg=<optimized out>, pp_stack=0x7fffb2412ef8) at Python/ceval.c:4371
#23 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#24 0x00002b8041632a2e in PyEval_EvalCodeEx (co=0x2b809d5273b0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=1, kws=0x0, kwcount=0, defs=0x2b809d5254c8, 
    defcount=3, closure=0x0) at Python/ceval.c:3582
(continues to vanilla python calls)
``` 

- With 12GB it works. 

Now, I have no idea how much RAM is required to have tensorflow running in GPU's, but 12GB seems definitely a huge amount for such a basic script.

**Comment by zheng-xq** [comment]
Could you set the CUDA_VISIBLE_DEVICES environmental variable to limit the GPU that is visible to TensorFlow? 

TensorFlow by default grabs all the GPUs visible to it, and grabs all the memory for suballocation. The user can configure how much memory it should ask. But 8G is definitely enough. The segfault is a bit troubling. If CUDA_VISIBLE_DEVICES doesn't fix any of this problem, we can ask the stream-executor team to investigate further.

**Comment by erickrf** [comment]
Ok, I ran `CUDA_VISIBLE_DEVICES=3 python test.py` (I checked with `nvidia-smi` that GPU 3 was not running anything), with 8GB of RAM allocated. Segfault again:

```
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:0a:00.0
Total memory: 7.92GiB
Free memory: 7.79GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:0a:00.0)
Segmentation fault (core dumped)
```

**Comment by yaroslavvb** [comment]
If you build tensorflow with `-c dbg --config=cuda` and run it under GDB, it will show which line in `StreamExecutor::DeviceMemoryUsage` causes the SEGSERV

**Comment by erickrf** [comment]
@yaroslavvb Well, it seems I cannot build tensorflow in this server, since it doesn't have internet access (and the other machines I can use which have internet don't have GPUs).

**Comment by yaroslavvb** [comment]
@erickrf You don't need to have GPU to build for GPU support, `--config=cuda` should work regardless

**Comment by erickrf** [comment]
@yaroslavvb Ok, so I finally compiled tensorflow in another machine. How can I install it in the server without internet access? I tried copying the whole repository with the compiled files, but it still searches pypi for some packages when I run `python setup.py develop`.

**Comment by stephenjia** [comment]
Hi @erickrf , do you solve your problem? I have the same issue as you had. 
When I run sess = tf.Session(), there is Segmentation fault (core dumped). And when I try to only allocate very small GPU memory, it is ok.

**Comment by erickrf** [comment]
@stephenjia I found out that in the server I was working with, I had to allocate 512 GB of RAM for GPU computation. It definitely sounds like an overkill but that solved it.

**Comment by stephenjia** [comment]
@erickrf  Thank you for your reply. But I remember you said without other operations, you just run 
" 
import tensorflow as tf
sess = tf.InteractiveSession()
"
It would give you an error of "
Total memory: 11.25GiB
Free memory: 11.16GiB
Segmentation fault (core dumped)"
I have the same problem and am a little confused about this.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by yzhwang** [comment]
Closing as the issue seems to have been solved. @erickrf please feel free to reopen the issue still exists.

**Comment by durgeshiitj** [comment]
I am facing the same issue.
Tried both tensorflow-gpu and tensorflow(cpu only) and got MemoryError.
I don't know how to fix this. 
Also, erickrf commented that giving 512GB of RAM to GPU solved issue, how to do that on server?

**Comment by kibromdst** [comment]
I had the same problem, but it was due to the fact that i had more than one program of python opened at a time. I was using Jupiter  notebook in my case, going to the running tab and closing the running programs that i don't need helped me solve this issue.

(https://user-images.githubusercontent.com/34263377/54976592-327e9000-4fde-11e9-9b89-d5cec2b4d799.png)

**Comment by waseemshariff126** [comment]
Try installing without caching: pip install --no-cache-dir tensorflow
