### ISSUE TITLE
frechet_classifier_distance triggers cuSolverDN issues

### ISSUE THREAD

**Issue by tydlwav** [tensorflow/tensorflow#24403]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): r1.13 from source
- TensorFlow version (use command below): 'v1.12.0-4609-g040ee45aa8' 1.12.0
- Python version: 3.6.7
- Bazel version (if compiling from source): 0.19
- GCC/Compiler version (if compiling from source): 7.3.1
- CUDA/cuDNN version: CUDA 10.0 with cuDNN 7.4.1
- GPU model and memory: RTX 2070 8 GB

**Describe the current behavior**
Trying to calculate FID triggers `Check failed: cusolverDnCreate(&cusolver_dn_handle) == CUSOLVER_STATUS_SUCCESS Failed to create cuSolverDN instance.`, and the program fails to execute. 

I have checked that `tf.contrib.gan.eval.run_inception` runs without problem, so the problem must be in `tf.contrib.gan.eval.frechet_classifier_distance`. 

**Describe the expected behavior**
It should calculate a frechet inception distance. 

**Code to reproduce the issue**
```
import tensorflow as tf

real = tf.zeros([1, 299, 299, 3], tf.float32)
fake = tf.ones([1, 299, 299, 3], tf.float32)
calc_fid = tf.contrib.gan.eval.frechet_classifier_distance(real, fake, tf.contrib.gan.eval.run_inception)

sess = tf.Session()
fid = sess.run(calc_fid)
```

**Other info / logs**

```
WARNING:tensorflow:From /home/michael/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py:162: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2018-12-17 11:39:37.256810: W tensorflow/core/framework/op_def_util.cc:355] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
WARNING:tensorflow:From /home/michael/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/michael/miniconda3/lib/python3.6/site-packages/tensorflow/contrib/gan/python/eval/python/classifier_metrics_impl.py:701: to_double (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2018-12-17 11:39:39.198829: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-17 11:39:39.218429: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4001425000 Hz
2018-12-17 11:39:39.218916: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55b50cbbed30 executing computations on platform Host. Devices:
2018-12-17 11:39:39.218937: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2018-12-17 11:39:39.359019: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-17 11:39:39.359747: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55b50c9b9ca0 executing computations on platform CUDA. Devices:
2018-12-17 11:39:39.359771: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2070, Compute Capability 7.5
2018-12-17 11:39:39.360173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:1c:00.0
totalMemory: 7.76GiB freeMemory: 7.16GiB
2018-12-17 11:39:39.360188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2018-12-17 11:39:39.584743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-17 11:39:39.584776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2018-12-17 11:39:39.584784: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2018-12-17 11:39:39.585158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6882 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:1c:00.0, compute capability: 7.5)
2018-12-17 11:39:42.809448: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2018-12-17 11:39:44.695693: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x55b50fba7850
2018-12-17 11:39:44.812389: F tensorflow/core/kernels/cuda_solvers.cc:94] Check failed: cusolverDnCreate(&cusolver_dn_handle) == CUSOLVER_STATUS_SUCCESS Failed to create cuSolverDN instance.
[1]    25740 abort (core dumped)  python test.py
```

**Comment by ymodak** [comment]
Is this still an issue?
I was able to execute your code snippet successfully using Google Colab GPU accelerator using Tf 1.13.rc1 . Can you please confirm? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by mathematiguy** [comment]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): r1.13 from source
- TensorFlow version (use command below): 'v1.12.0-4609-g040ee45aa8' 1.13.1
- Python version: 2.7.12
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10.0 with cuDNN 7
- GPU model and memory: RTX 2080 Ti

**Describe the current behavior**

Here's the full logs from running `test.py`

```
>> Downloading http://download.tensorflow.org/models/frozen_inception_v1_2015_12_05.tar.gz 100.0%
2019-04-20 01:10:46.046521: W tensorflow/core/framework/op_def_util.cc:355] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/gan/python/eval/python/classifier_metrics_impl.py:701: to_double (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-04-20 01:10:48.460746: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-20 01:10:48.576805: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-04-20 01:10:48.577507: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5b3dd40 executing computations on platform CUDA. Devices:
2019-04-20 01:10:48.577523: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-04-20 01:10:48.595965: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-04-20 01:10:48.596645: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4aeea50 executing computations on platform Host. Devices:
2019-04-20 01:10:48.596661: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-04-20 01:10:48.597154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
totalMemory: 10.73GiB freeMemory: 9.89GiB
2019-04-20 01:10:48.597168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-20 01:10:48.597759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-20 01:10:48.597768: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-04-20 01:10:48.597773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-04-20 01:10:48.598012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9621 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-04-20 01:10:49.943217: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-04-20 01:10:51.767228: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x4a3f850
2019-04-20 01:10:51.922493: F tensorflow/core/kernels/cuda_solvers.cc:94] Check failed: cusolverDnCreate(&cusolver_dn_handle) == CUSOLVER_STATUS_SUCCESS Failed to create cuSolverDN instance.
Aborted (core dumped)
```
Trying to calculate FID triggers Check failed: cusolverDnCreate(&cusolver_dn_handle) == CUSOLVER_STATUS_SUCCESS Failed to create cuSolverDN instance., and the program fails to execute.

I have checked that tf.contrib.gan.eval.run_inception runs without problem, so the problem must be in tf.contrib.gan.eval.frechet_classifier_distance.

**Describe the expected behavior**
It should calculate a frechet inception distance.

Code to reproduce the issue

```
import tensorflow as tf

real = tf.zeros([1, 299, 299, 3], tf.float32)
fake = tf.ones([1, 299, 299, 3], tf.float32)
calc_fid = tf.contrib.gan.eval.frechet_classifier_distance(real, fake, tf.contrib.gan.eval.run_inception)

sess = tf.Session()
fid = sess.run(calc_fid)
```

I ran the code inside of the `tensorflow/tensorflow:latest-gpu` docker image, and also inside `nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04` with `tensorflow-gpu` installed via `pip`.

I've also seen the same code run inside of a Google Collab notebook, so there must be some difference between that environment and this one.. But I haven't been able to figure it out.

I'd really like it if someone took a second look at this. If I could get some direction I'd have a look myself.

**Comment by tydlwav** [comment]
Try using conda to install the environment. I solved it this way. `conda create -n tf python==3.6.8` and then `conda install tensorflow-gpu`. It will get you tensorflow 1.13.1 with cuda 10 and cudnn 7.3.1.
