### ISSUE TITLE
distributed tensorflow mnist example hang at prepare_or_wait_for_session() 

### ISSUE THREAD

**Issue by s0okiym** [tensorflow/tensorflow#2472]
I tried both Distributed [tensorflow](https://www.tensorflow.org/versions/r0.8/how_tos/distributed/index.html) and [minist_softmax.py.txt](https://github.com/tensorflow/tensorflow/files/271770/mnist_softmax.py.txt). They both hang at the prepare_or_wait_for_session() function with non-chief worker tasks.

task_index == 0(chief worker ) can run as expected.
I can not find out the reasion why it behaves like this. 
Can anyone please give some advice?

**Comment by mrry** [comment]
We'll need some more information to debug this. How are you invoking the programs when they hang? What logs do you see from each process, if any?

**Comment by s0okiym** [comment]
as for the [minis_softmax.py.txt](https://github.com/tensorflow/tensorflow/files/271770/mnist_softmax.py.txt), I run the ps server on one machine using command: ython ./distribute_test.py --ps_hosts=10.93.128.27:2222 --worker_hosts=10.93.128.20:2223,10.93.128.20:2224 --job_name=ps --task_index=0

**Comment by s0okiym** [comment]
If there some requirements for installing and building tensorflow, I installed on centOS 7.2 using pip install following the instructions on tensorflow.org .  Is it necessary for me to build it from source in order to run the distributed tensor flow ? Or is it necessary to build from the newest source in order to run distributed tensor flow?

**Comment by s0okiym** [comment]
and  I checked the code of newest tensor flow source, the function prepare_or_wait_for_session 's code:<br> <pre><code>    if self._is_chief:
      sess = self._session_manager.prepare_session(
          master, init_op=self.init_op, saver=self.saver,
          checkpoint_dir=self._logdir, wait_for_checkpoint=wait_for_checkpoint,
          max_wait_secs=max_wait_secs, config=config,
          init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
      self._write_graph()
      if start_standard_services:
        self.start_standard_services(sess)
    else:
      sess = self._session_manager.wait_for_session(master,
                                                    config=config,
                                                    max_wait_secs=max_wait_secs)
    if start_standard_services:
      self.start_queue_runners(sess)
    return less</code></pre><br>  if the task is the chief one and start_standard_services is True, then self.start_queue_runners(less) will be called twice, Is this a bug?

**Comment by s0okiym** [comment]
I added some print() call at supervisor.py and session_manager.py in the source code of tensorflow,  then I found the reason why it hangs at prepare_or_wait_for_session():<br>

prepare_or_wait_for_session calls wait_for_session, The wait_for_session function in session_manager.py calls _mode_not_ready() function, and the _mode_not_ready() function returns a Exception, Here it is:<br>
<pre><code>Attempting to use uninitialized value global_step
	 [[Node: global_step/read = Identity[T=DT_FLOAT, _class=["loc:@global_step"], _device="/job:ps/replica:0/task:0/cpu:0"](global_step)]]
	 [[Node: Rank_2_S1 = _HostRecv[client_terminated=false, recv_device="/job:worker/replica:0/task:1/gpu:0", send_device="/job:ps/replica:0/task:0/cpu:0", send_device_incarnation=6943251664905551597, tensor_name="edge_12_Rank_2", tensor_type=DT_INT32, _device="/job:worker/replica:0/task:1/gpu:0"]()]]
	 [[Node: pack_G3 = _Recv[client_terminated=false, recv_device="/job:worker/replica:0/task:1/cpu:0", send_device="/job:worker/replica:0/task:1/gpu:0", send_device_incarnation=-7346167572165274731, tensor_name="edge_5_pack", tensor_type=DT_INT32, _device="/job:worker/replica:0/task:1/cpu:0"]()]]
Caused by op u'global_step/read', defined at:
  File "./distribute_test.py", line 96, in <module>
    tf.app.run()
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "./distribute_test.py", line 93, in main
    run_training(server, cluster_spec, num_workers)
  File "./distribute_test.py", line 32, in run_training
    initializer = tf.constant_initializer(0), trainable = False)
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 339, in get_variable
    collections=collections)
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 262, in get_variable
    collections=collections, caching_device=caching_device)
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 158, in get_variable
    dtype=variable_dtype)
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 209, in __init__
    dtype=dtype)
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 318, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 609, in identity
    return _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/data0/guohongyan/tools/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack() </code></pre>

**Comment by jnkh** [comment]
Is there any news on how to fix this? I am experiencing the exact same problem.

**Comment by perhapszzy** [comment]
I had the same problem as well, can somebody tell how to fix this?

**Comment by perhapszzy** [comment]
Found the problem. All variables in non-chief worker should be initialized by chief worker.

**Comment by jnkh** [comment]
Awesome! @perhapszzy any chance you could give a working code example of your solution?

**Comment by perhapszzy** [comment]
I'm putting all my codes into this repo:

https://github.com/caicloud/tensorflow-demo/tree/master/distributed

mnist_dnn.py and mnist_cnn.py should be working.

**Comment by perhapszzy** [comment]
I was using timestamp as name_scope to avoid re-use of parameters between two different runs, that doesn't work and now I' using tf.reset_default_graph(), this works well.

**Comment by utkrist** [comment]
@perhapszzy I have similar problem to yours. Basicaly, I'm trying to set different files as data source in each worker. I am therefore setting up worker specific variable scope for my dataset. What does reseting default graph in chief worker do? Would you like to share your experience with this. 

    with tf.variable_scope('data_source_task_index_%d' % FLAGS.task_index):
        batch_generator = MyCustomDataSet(FLAGS.batch_size)
