### ISSUE TITLE
Linking of rule '//tensorflow/contrib/nccl:python/ops/_nccl_ops.so' failed

### ISSUE THREAD

**Issue by Noirai** [tensorflow/tensorflow#24948]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: macOS 10.13.5
- TensorFlow installed from: source
- TensorFlow version: 1.11.0
- Python version: 3.6.5
- Bazel version (if compiling from source): 0.15.2
- GCC/Compiler version (if compiling from source): XCODE 8.3.2
- CUDA/cuDNN version: CUDA 10.0 / cuDNN 7.3.2 / NCCL 2.3.5
- GPU model and memory: GTX 1080 Ti 11GB

Trying to build tensorflow 1.11 from source and the following error occurred:

tensorflow/tensorflow/contrib/nccl/BUILD:24:1: Linking of rule '//tensorflow/contrib/nccl:python/ops/_nccl_ops.so' failed (Exit 1)
ld: library not found for -l:libnccl.so.2.3.5

Thanks a lot

**Comment by byronyi** [comment]
Could you try the latest tensorflow, i.e. master branch?

**Comment by Noirai** [comment]
> Could you try the latest tensorflow, i.e. master branch?

With latest version new errors emerged:
external/curl/lib/vtls/darwinssl.c:848:10: error: use of undeclared identifier 'TLS_AES_128_GCM_SHA256'
    case TLS_AES_128_GCM_SHA256:
         ^
external/curl/lib/vtls/darwinssl.c:851:10: error: use of undeclared identifier 'TLS_AES_256_GCM_SHA384'
    case TLS_AES_256_GCM_SHA384:
         ^
external/curl/lib/vtls/darwinssl.c:854:10: error: use of undeclared identifier 'TLS_CHACHA20_POLY1305_SHA256'
    case TLS_CHACHA20_POLY1305_SHA256:
         ^
external/curl/lib/vtls/darwinssl.c:857:10: error: use of undeclared identifier 'TLS_AES_128_CCM_SHA256'
    case TLS_AES_128_CCM_SHA256:
         ^
external/curl/lib/vtls/darwinssl.c:860:10: error: use of undeclared identifier 'TLS_AES_128_CCM_8_SHA256'
    case TLS_AES_128_CCM_8_SHA256:
         ^
external/curl/lib/vtls/darwinssl.c:863:10: error: use of undeclared identifier 'TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256'
    case TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:
         ^
external/curl/lib/vtls/darwinssl.c:866:10: error: use of undeclared identifier 'TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256'
    case TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:

**Comment by byronyi** [comment]
Did you bazel clean before building on master?

**Comment by Noirai** [comment]
> Did you bazel clean before building on master?
Yes, bazel clean --expunge before every build.
Downgrade from Xcode 9.4 to 9.0 successfully eliminated the 'darwinssl' error but still failed on NCCL.

ERROR: undeclared inclusion(s) in rule '//tensorflow/core/kernels:nccl_kernels':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/nccl_ops.cc':
  'third_party/nccl/nccl.h'
tensorflow/core/kernels/nccl_ops.cc:189:15: warning: private field 'reduction_op_' is not used [-Wunused-private-field]
  ncclRedOp_t reduction_op_;
              ^
1 warning generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by byronyi** [comment]
Sorry, I did not notice that you were on macOS. NCCL is specific to CUDA, and I do not believe that TF supports macOS+CUDA officially.

**Comment by Noirai** [comment]
> Sorry, I did not notice that you were on macOS. NCCL is specific to CUDA, and I do not believe that TF supports macOS+CUDA officially.

Thanks.

Followed some guides and now I'm stuck at 
Symbol not found: _ncclAllReduce

Trying to find a solution.

**Comment by Noirai** [comment]
Using 1.12 build from https://github.com/TomHeaven/tensorflow-osx-build. Seems to work now.
Closing
