### ISSUE TITLE
Fedora 23: build fails with missing libcudart.so.7.5 without `--genrule_strategy=standalone`

### ISSUE THREAD

**Issue by akors** [tensorflow/tensorflow#2499]
Hi, this is a continuation of Issue #2053, because that one was closed for no apparent reason.

Compiling the GPU version of the `tutorials_example_trainer` target fails on Fedora 23 with the message:

```
bazel-out/host/bin/tensorflow/cc/ops/random_ops_gen_cc: error while loading shared libraries: libcudart.so.7.5: cannot open shared object file: No such file or directory
Target //tensorflow/cc:tutorials_example_trainer failed to build
```

When using the command line

    path/to/bazel/output/bazel build -c opt --config=cuda -j 4 //tensorflow/cc:tutorials_example_trainer

When adding `--genrule_strategy=standalone`, the compilation succeeds.

I believe that either the Documentation should be updated to include this flag, or that the build system is changed to pass it automatically.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/pull/2504  can you let me know if that solves the problem ?

**Comment by akors** [comment]
Thanks, as far as I can see this fixes the problem.
