### ISSUE TITLE
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by Bahramudin** [tensorflow/tensorflow#25160]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12, 1.11
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:7.4.2, 7.3.1
- GPU model and memory: CUDA 9.0

**Describe the current behavior**
I have installed TF using pip, I have tested and it was able to detect the GPU, but when start to train, it throws the error below:

> UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
>          [[node FirstStageFeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d (defined at C:\Users\bahra\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:2777)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FirstStageFeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise, FirstStageFeatureExtractor/InceptionV2/Conv2d_1a_7x7/pointwise_weights/read/_165)]]
>          [[{{node BatchMultiClassNonMaxSuppression/map/while/Exit_6/_76}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1252_BatchMultiClassNonMaxSuppression/map/while/Exit_6", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Note**
I have tried TF 1.12, 1.11, and 1.8.0 all have the same problem.
Why it throwing this error and how to solve?

Before this error, I was able to train, and it was successfully worked, but when to start the second time training then this error happens.

**Comment by ymodak** [comment]
duplicate #24828 
Closing this issue so that we can focus on one thread. Thanks!

**Comment by ymodak** [comment]
Read your solution on the thread. Thanks a lot for sharing it, will keep a note of it moving forward.

**Comment by Tyrones1995** [comment]
anaconda Python 3.7  cuda10.0.130 cudnn 7.5.1  the same error 
UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv2D_12 (defined at <ipython-input-14-8e7270518a76>:174) ]]

**Comment by Tyrones1995** [comment]
Caused by op 'Conv2D_12', defined at:
  File "/home/wtl/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wtl/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/wtl/anaconda3/lib/python3.7/asyncio/base_events.py", line 528, in run_forever
    self._run_once()
  File "/home/wtl/anaconda3/lib/python3.7/asyncio/base_events.py", line 1764, in _run_once
    handle._run()
  File "/home/wtl/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-8e7270518a76>", line 318, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "<ipython-input-14-8e7270518a76>", line 208, in main
    logits = model(train_data_node, True)
  File "<ipython-input-14-8e7270518a76>", line 174, in model
    padding='SAME')
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/wtl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv2D_12 (defined at <ipython-input-14-8e7270518a76>:174) ]]

**Comment by leimao** [comment]
I am using TF container and this also happened. Before this error, I was able to train, and it was successfully worked, but when to start the second time training then this error happens. What is the problem here?

**Comment by Fotomaterjal** [comment]
Using cudnn-7.4.2 and cuda-10.0. Both should be usable by tensorflow 2.0 https://www.tensorflow.org/install/source#tested_build_configurations
but I'm running into the same issue as described above.

**Comment by FabianLaBP** [comment]
I was able to resolve this by installing an updated version of the libcudnn library (7.6.5 - I am using cuda 10.0 on Ubuntu 16.04) from the  [NVIDIA developer page](https://developer.nvidia.com/cudnn).

**Comment by Fotomaterjal** [comment]
I managed to get it running with cudnn/7.6.3/cuda-10.0 as well

**Comment by viditvarshney** [comment]
**Same error i got , The Reason of getting this error is due to the mismatch of the version of the cudaa/cudnn with your tensorflow version there are two methods to solve this:**

1.    Either you Downgrade your Tensorflow Version
   ` pip install --upgrade tensorflowgpu==1.8.0`

2.   Or You can follow the steps at Here.

    tip:  Choose your ubuntu version and follow the steps.:-)

**Comment by dsivakumar** [comment]
Workaround:
Fresh install TF 2.0 and ran a simple Minst tutorial, it was alright, opened another notebook, tried to run and encountered this issue.
I existed all notebooks and restarted Jupyter and open only one notebook, ran it successfully
Issue seems to be either memory or running more than one notebook on GPU

Thanks

**Comment by BryanBo-Cao** [comment]
@roebel https://github.com/tensorflow/tensorflow/issues/24496#issuecomment-630420518
@kabylan https://github.com/tensorflow/tensorflow/issues/24496#issuecomment-641978924


I think it's related to GPU memory as well, I was trying to run https://keras.io/examples/rl/deep_q_network_breakout/ in the following environment:

GPU: RTX 2060 Super
| OS/Driver/Lib  | Version |
| ------------- | ------------- |
| Ubuntu  | 18.04.4 LTS  |
| GPU Driver  | 450.36.06  |
| CUDA | 11.0 |
| Tensorflow | 2.2.0 |
| Keras | 2.3.1 |

Before running the code, the GPU status is:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 206...  On   | 00000000:01:00.0 Off |                  N/A |
| 41%   33C    P8     8W / 175W |      1MiB /  7979MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

After running the code, I got the error:
```
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model_1/conv2d/Conv2D (defined at <ipython-input-4-aa1698769333>:87) ]] [Op:__inference_predict_function_229]

Function call stack:
predict_function
```
And the CUDA memory is almost full:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 206...  On   | 00000000:01:00.0 Off |                  N/A |
| 41%   33C    P2    40W / 175W |   7902MiB /  7979MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      6753      C   ...Apps/anaconda3/bin/python     7899MiB |
+-----------------------------------------------------------------------------+
```
I tried
```
tf.config.experimental.set_memory_growth = True
```
but still had the same issue.

---
Although the system never raised CUDA memory errors, limiting GPU memory usage solved solved this problem in my case
```
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    # Restrict TensorFlow to only allocate 1GB * 2 of memory on the first GPU
    try:
        tf.config.experimental.set_virtual_device_configuration(
            gpus[0],
            [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024 * 2)])
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Virtual devices must be set before GPUs have been initialized
        print(e)
···
Check how to limit GPU https://www.tensorflow.org/guide/gpu

**Comment by SandraMnz** [comment]
@BryanBo-Cao 
I had the same error with:

GPU: GeForce RTX 2060
OS/Driver/Lib | Version
-- | --
Ubuntu | 18.04.4 LTS
GPU Driver | 435.21
CUDA | 10.1
Tensorflow | 2.2.0
Keras | 2.3.0

And your solution for limit the gpu is the only one that has worked to me.

**Comment by swordspoet** [comment]
> @BryanBo-Cao
> I had the same error with:
> 
> GPU: GeForce RTX 2060
> 
> OS/Driver/Lib	Version
> Ubuntu	18.04.4 LTS
> GPU Driver	435.21
> CUDA	10.1
> Tensorflow	2.2.0
> Keras	2.3.0
> And your solution for limiting the GPU usage is the only one that has worked to me.

If this doesn't fix your problem, then upgrade your cuDNN, it works for me.

**Comment by ebrarsahin** [comment]
SOLUTION:
Go to train.py add these codes

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

This way worked for me.

**Comment by helonayala** [comment]
> SOLUTION:
> Go to train.py add these codes
> 
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> config = ConfigProto()
> config.gpu_options.allow_growth = True
> session = InteractiveSession(config=config)
> 
> This way worked for me.

thanks mate, works here too

**Comment by HaoranCheng** [comment]
the same problem with the tensorflow-gpu2.0.0 and the Cuda 10.0.0+ cudnn 7.4.  Finally solved it by updating them to tensorflow-gpu 2.1.0 + CUDA 10.1 + cudnn 7.6.5 since Python 3.7 is what I need.
