### ISSUE TITLE
the cudnn lib directory is not in the tensorflow gpu docker image's LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by yeison** [tensorflow/tensorflow#2525]
libcudnn4 is installed in the gcr.io/tensorflow/tensorflow:latest-gpu docker image, but I get the following errors from the jupyter tensorflow tutorial:

F tensorflow/stream_executor/cuda/cuda_dnn.cc:204] could not find cudnnCreate in cudnn DSO; dlerror: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate

running env shows that LD_LIBRARY_PATH does not have a reference to the libcudnn.so location 

```
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:
```

**Comment by yeison** [comment]
https://github.com/tensorflow/tensorflow/pull/2527

**Comment by yeison** [comment]
See pull request for on simple fix: https://github.com/tensorflow/tensorflow/pull/2527

**Comment by yeison** [comment]
More detail here: https://github.com/NVIDIA/nvidia-docker/issues/45

**Comment by flx42** [comment]
That's because `LD_LIBRARY_PATH` is not the only path used for lookup.
The library is present in `/usr/lib/x86_64-linux-gnu/libcudnn.so.4`, it's just that the `dlopen` should be using the `SONAME`.

**Comment by 3XX0** [comment]
Probably a issue with the configuration script again.

`GetCudnnVersion` needs to return `4`, see:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/dso_loader.cc#L57
https://github.com/tensorflow/tensorflow/blob/14ac2235699509f512b44b71160239c153ab413d/configure#L243

And you might want to hardcode `"1"` for the CUDA library too
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/dso_loader.cc#L75

**Comment by jendap** [comment]
It does not return 4. It will return empty string. It should (probably) look for /usr/lib/x86_64-linux-gnu/libcudnn.so

@3XX0 what waas the story why the container doe not contain a symlink from `/usr/lib/x86_64-linux-gnu/libcudnn.so.4` to `/usr/lib/x86_64-linux-gnu/libcudnn.so`?

If we really have to have the number there we should modify the configure script to find the latest number by default. Or maybe even better - we could create a static constant set to CUDNN_MAJOR (macro in cudnn.h). That should work. But the link would be much better if cuda is somewhat backward compatible. We could compile for 4 and it would run even on 5. That will not happen if we look for exact filename containing the version.

@3XX0 what is the nvidia oppinion? We should finally fix this. It is getting back too often.

**Comment by 3XX0** [comment]
Symlinks like those are only useful for development purposes and we actually include them in our `devel` images (e.g. `cuda:7.5-cudnn4-devel`). When compiling, the linker will look up the soname of the library pointed by the symlink (in this case it will be `libcudnn.so.4`) and use it to build the binary dependencies.

The [soname](https://en.wikipedia.org/wiki/Soname) of a library defines its ABI compatibility, if it changes it means the ABI broke. With `dlopen` you are asking the dynamic linking loader to load a specific file. If you use the symlink, you are effectively giving up on enforcing a specific ABI. This can lead to undefined behaviors if the symlink points to something that you don't expect.

Now the cuDNN versionning scheme is confusing and they broke the ABI every single time (hence the bump in the soname). I raised the issue internally a while ago and they said they will probably provide backward compatibility in the future.
So for example, we might see cuDNN 4.5 with the same soname (`libcudnn.so.4`).

Using the constant is a good idea, hopefully `CUDNN_MAJOR` is akin to the soname and will only change if the ABI breaks (I will warn the cuDNN team about that). For CUDA, I think it is safe to just hardcode "1" because libcuda has always provided backward compatibilty.

**Comment by suharshs** [comment]
@jendap What is the status on this? Has it been resolved?

**Comment by gunan** [comment]
I think with the latest updates to our docker images, this issue is now resolved. Please let me know if it is still broken at head.
