### ISSUE TITLE
zlib.h error when compiling tutorials_example_trainer, but zlib is there

### ISSUE THREAD

**Issue by ivdorelian** [tensorflow/tensorflow#2536]
### Environment info
Operating System: Red Hat Enterprise Linux Server release 7.2

Installed version of CUDA and cuDNN: CUDA 7, cuDNN 4
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

-rw-r--r-- 1 root root 179466 Jan 26 22:19 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Jan 26 22:19 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.0
lrwxrwxrwx 1 root root     19 Jan 26 22:19 /usr/local/cuda/lib/libcudart.so.7.0 -> libcudart.so.7.0.28
-rwxr-xr-x 1 root root 303052 Jan 26 22:19 /usr/local/cuda/lib/libcudart.so.7.0.28
-rw-r--r-- 1 root root 546514 Jan 26 22:19 /usr/local/cuda/lib/libcudart_static.a

cuDNN is installed for the local user only.

If installed from sources, provide the commit hash:

b289bc7a50fc0254970c60aaeba01c33de61a728

### Steps to reproduce

I have followed the instructions at: https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#requirements 

Since I am not root, I had to install everything for the local user, but it seems to have worked. 

I get an error at this line:

bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

Saying:

ERROR: [...]/vlad/.cache/bazel/_bazel_vlad/6607a39fc04ec931b523fac975ff3100/external/png_archive/BUILD:23:1: Executing genrule @png_archive//:configure failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
[...]/vlad/.cache/bazel/_bazel_vlad/6607a39fc04ec931b523fac975ff3100/tensorflow/external/png_archive/libpng-1.2.53 [...]/vlad/.cache/bazel/_bazel_vlad/6607a39fc04ec931b523fac975ff3100/tensorflow
/tmp/tmp.pCUaj9eIKr [...]/vlad/.cache/bazel/_bazel_vlad/6607a39fc04ec931b523fac975ff3100/tensorflow/external/png_archive/libpng-1.2.53 [...]/vlad/.cache/bazel/_bazel_vlad/6607a39fc04ec931b523fac975ff3100/tensorflow

... a bunch more lines until:

checking for pow... no
checking for pow in -lm... yes
checking for zlibVersion in -lz... no
**configure: error: zlib not installed**
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 57.196s, Critical Path: 22.12s

### What have you tried?

I installed zlib, and the following program compiles with g++

    #include <cstdio>
    #include <zlib.h>

    int main()
    {
        printf("Hello world");
        return 0;
    }

I have the following in my .bashrc:

export LD_LIBRARY_PATH="$HOME/local/cuda/lib64:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$HOME/bin/zlibdev/lib:$LD_LIBRARY_PATH"
export CPATH="$HOME/local/cuda/include:$CPATH"
export CPATH="$HOME/bin/zlibdev/include:$CPATH"
export LIBRARY_PATH="$HOME/local/cuda/lib64:$LIBRARY_PATH"

export PKG_CONFIG_PATH="$HOME/bin/zlibdev/lib/pkgconfig"

Why can't bazel / tensorflow find zlib.h? It's there and accessible.

**Comment by vrv** [comment]
I'm not entirely sure -- since it's a ./configure problem for png (an external repo), pulling in @damienmg or @davidzchen in case they know what might be wrong.

**Comment by damienmg** [comment]
This happens because the environment isn't shipped in the genrule. A skylark auto-conf kinda rules could be used instead to generate the genrule. After seeing the code, it might even be possible to ship the zlib imported by a remote repository as a parameter for libpng

As a workaround, adding the list of export to [that line](https://github.com/tensorflow/tensorflow/blob/master/png.BUILD#L30) should do the trick.

**Comment by ivdorelian** [comment]
@damienmg can you please tell how to add the list of export there?

**Comment by damienmg** [comment]
replace
```python
    cmd = "pushd external/png_archive/%s; workdir=$$(mktemp -d -t tmp.XXXXXXXXXX); cp -a * $$workdir; pushd $$workdir; ./configure --enable-shared=no --with-pic=no; popd; popd; cp $$workdir/config.h $(@D); rm -rf $$workdir;" % prefix_dir,
```

with something like:
```python
    cmd = "\n".join([
       "export LD_LIBRARY_PATH='{LD_LIBRARY_PATH}'",
       "export CPATH='{CPATH}'",
       "export LIBRARY_PATH='{LIBRARY_PATH}'",
       "export PKG_CONFIG_PATH='{PKG_CONFIG_PATH}'",
        "pushd external/png_archive/" + prefix_dir,
        "workdir=$$(mktemp -d -t tmp.XXXXXXXXXX)",
        "cp -a * $$workdir",
        "pushd $$workdir",
        "./configure --enable-shared=no --with-pic=no",
        "popd",
        "popd",
        "cp $$workdir/config.h $(@D)",
        "rm -rf $$workdir",
    ],
```

Where you replace `{LD_LIBRARY_PATH}`, `{CPATH}`, `{LIBRARY_PATH}`, `{PKG_CONFIG_PATH}` by the values from your environment

**Comment by ivdorelian** [comment]
I have this:

```
genrule(
    name = "configure",
    srcs = glob(
        ["**/*"],
        exclude = [prefix_dir + "/config.h"],
    ),
    outs = [prefix_dir + "/config.h"],
    cmd = "\n".join([
       "export LD_LIBRARY_PATH='/home/mateinfo/vlad/bin/zlibdev/lib'",
       "export CPATH='/home/mateinfo/vlad/bin/zlibdev/include'",
       "export PKG_CONFIG_PATH='/home/mateinfo/vlad/bin/zlibdev/lib/pkgconfig'",
        "pushd external/png_archive/" + prefix_dir,
        "workdir=$$(mktemp -d -t tmp.XXXXXXXXXX)",
        "cp -a * $$workdir",
        "pushd $$workdir",
        "./configure --enable-shared=no --with-pic=no",
        "popd",
        "popd",
        "cp $$workdir/config.h $(@D)",
        "rm -rf $$workdir",
    ]),
)
```

But the same error appears. If I run:

`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

Then I get:

```
ERROR: /home/mateinfo/vlad/.cache/bazel/_bazel_vlad/6607a39fc04ec931b523fac975ff3100/external/grpc/BUILD:485:1: C++ compilation of rule '@grpc//:grpc_unsecure' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 40 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/grpc/src/core/compression/message_compress.c:41:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
```

zlib.h is in the CPATH location:

```
[vlad@headnode ~]$ ls /home/mateinfo/vlad/bin/zlibdev/include
zconf.h  zlib.h
```

Have I edited the cmd line wrong?

**Comment by damienmg** [comment]
Can you add a line `  cxx_builtin_include_directory: "/home/mateinfo/vlad/bin/zlibdev/include"` at https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL#L62?

**Comment by ivdorelian** [comment]
That worked. Thank you very much, and I apologize for the late reply.

**Comment by girving** [comment]
@damienmg Is there a version of that fix we could incorporate?

**Comment by damienmg** [comment]
girving: no we are down to auto-configuration of the nvcc crosstool again. @davidzchen is working on it AFAICT.

**Comment by davidzchen** [comment]
I should have a PR for the cuda autoconf later this week.

**Comment by davidzchen** [comment]
Here is the tracking bug for the cuda autoconf: #2873

**Comment by concretevitamin** [comment]
Closing since the original issue seems to have been resolved.

**Comment by erickrf** [comment]
I am having a similar problem. After making the suggested changes in the configuration files, I got past the first zlib error, but I'm still getting the second one: 

```
ERROR: /hardmnt/silvermoon0/home/rocha/.cache/bazel/_bazel_rocha/1d1a96c2ccf291e17b589991ea556cc1/external/png_archive/BUILD:33:1: C++ compilation of rule '@png_archive//:png' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /hardmnt/silvermoon0/home/rocha/.cache/bazel/_bazel_rocha/1d1a96c2ccf291e17b589991ea556cc1/execroot/tensorflow0.10 && \
  exec env - \
    PATH=/home/rocha/anaconda2/bin:/home/rocha/anaconda2/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/rocha/.local/bin:/home/rocha/bin:/home/rocha/.local/jdk1.8.0_101//bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 -MD -MF bazel-out/host/bin/external/png_archive/_objs/png/external/png_archive/libpng-1.2.53/pngwutil.d -iquote external/png_archive -iquote bazel-out/host/genfiles/external/png_archive -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/host/genfiles/external/png_archive/libpng-1.2.53 -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c external/png_archive/libpng-1.2.53/pngwutil.c -o bazel-out/host/bin/external/png_archive/_objs/png/external/png_archive/libpng-1.2.53/pngwutil.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/png_archive/libpng-1.2.53/pngwutil.c:16:0:
external/png_archive/libpng-1.2.53/png.h:548:18: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
                  ^
compilation terminated.
```

By the way, the current tensorflow version I'm working with is r0.10, and the CROSSTOOL file has a .tpl extension. Line 62 points to a comment in my version, so it evidently has changed a bit.

**Comment by davidzchen** [comment]
@erickrf - The main difference is that the `cuda_configure` rule generates a CROSSTOOL file from the CROSSTOOL.tpl, filling in values auto-detected from the system and the user input from the `configure` script, such as CUDA version. You should be able to still add a `cxx_builtin_include_directory` entry to the CROSSTOOL file for now until we add autoconfiguration for libraries such as zlib.

**Comment by erickrf** [comment]
So, I did add that line. the CROSSTOOL file has the following `cxx_builtin_include_directory` entries:

```
  cxx_builtin_include_directory: "/home/rocha/.local/include"
  cxx_builtin_include_directory: "/usr/lib/gcc/"
  cxx_builtin_include_directory: "/usr/local/include"
  cxx_builtin_include_directory: "/usr/include"
```

But there they are:
```
$ ls /home/rocha/.local/include
zconf.h  zlib.h
```

**Comment by erickrf** [comment]
Ok, I got it to work. If it is of use to anyone, I added to the CROSSTOOL file the following lines. At line 99, after `compiler_flag: "-fPIE"`:

    compiler_flag: "-I/home/rocha/.local/include"

And at line 126, after `linker_flag: "-Wl,--hash-style=gnu"`:

    linker_flag: "-L/home/rocha/.local/lib"
