### ISSUE TITLE
CUDA_ERROR_NO_DEVICE

### ISSUE THREAD

**Issue by jpiabrantes** [tensorflow/tensorflow#255]
I just installed TensorFlow for Ubuntu using the instructions on the [website](http://www.tensorflow.org/get_started/os_setup.md).

If I open a session in python:
```python
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
```

I get these warnings:
```sh
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 8
E tensorflow/stream_executor/cuda/cuda_driver.cc:466] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:86] kernel driver does not appear to be running on this host (joao): /proc/driver/nvidia/version does not exist
I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 8
```

What have I done wrong?

**Comment by vrv** [comment]
Do you have a GPU in your machine that you want to use?  

If not:
1) consider using the CPU binary, not the GPU binary
2) you should be able to ignore these warnings.  they are helpful for debugging for those who do want to use GPUs.

**Comment by jpiabrantes** [comment]
I do have GPU and I want to use it.

**Comment by vrv** [comment]
Then that means that our library is unable to detect your GPU.

1) What GPU do you have?
2) What cuda library version do you have installed?

**Comment by jpiabrantes** [comment]
My GPU is this one: NVIDIA Corporation GF108GL
For the cuda I first installed cuda-7.5 but then I had a few troubles and therefore installed cuda-7.0 . Maybe I messed something up when installing the cuda.. I will look more into it

**Comment by Yangqing** [comment]
Just FYI, Quadro 600 might be a little bit old for running TensorFlow... We officially support cuda compute capability 3.5 (and 3.0 seems to be working well too). Quadro 600 is at 2.1, so there might be a few bumps.

If you have cuda installed, running the device query binary from nvidia's samples would usually help checking if the GPU is properly detected.

**Comment by jpiabrantes** [comment]
Ok I did some cleaning and rebooting and now my GPU is found. But I guess it will be ignored because it's too old like @Yangqing pointed out. I have these warnings:

```sh
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 8
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:888] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:88] Found device 0 with properties: 
name: Quadro 600
major: 2 minor: 1 memoryClockRate (GHz) 1.28
pciBusID 0000:01:00.0
Total memory: 1023.19MiB
Free memory: 734.32MiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:122] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:611] Ignoring gpu device (device: 0, name: Quadro 600, pci bus id: 0000:01:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.5.
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 8
```

Now I know what I have to ask for x-mas. Thank you all

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/issues/25#issuecomment-156234658 if you're comfortable building from source -- may allow you to run on GPU, though it may not be that much faster than CPU.

Closing this for now -- feel free to re-open if there's anything else you need!

**Comment by rajarsheem** [comment]
so 2.1 capability devices won't be much faster than CPU?

**Comment by prayalankar2** [comment]
Does google n1-standard-8 (8 vCPUs, 30 GB memory) Have GPU support . I am trying to install nvidia drivers but it fails.

**Comment by brando90** [comment]
what if I don't want to use a GPU but I just want to use CPU?

**Comment by prayalankar2** [comment]
Simply install the CPU version of Tensorflow .

**Comment by Alek-dr** [comment]
I had a problem: failed call to cuInit: CUDA_ERROR_NO_DEVICE. And root of problem was enviroment varible CUDA_VISIBLE_DEVICES = 1. One is ID, not count. Switch it to 0.

**Comment by j-o-d-o** [comment]
I had that same problem. I think the issue was, that I used the AMI from a different ec2 instance and I had to run that command again: 
`sudo apt-get install -y linux-headers-$(uname -r)`

**Comment by HassebJ** [comment]
Just to expand on what @Alek-dr mentioned, if on your system the environment variable CUDA_VISIBLE_DEVICES is empty or set to a any value other than IDs of GPUs on your system then you might encounter this issue.

I have two GPUs installed so setting `export CUDA_VISIBLE_DEVICES=0,1` allows TensorFlow to use both of them.

**Comment by Deejep** [comment]
Setting the `CUDA_VISIBLE_DEVICES` variable to `0,1` doesn't work for me with 1 GPU and tensorflow installed with virtualenv python.

**Comment by HassebJ** [comment]
@Deejep As I said in my previous comments, I have 2 GPUs per node in my cluster that is why I set it to  0,1. For single GPU per node, `CUDA_VISIBLE_DEVICES=0` should work.

**Comment by Deejep** [comment]
Just fixed the issue. You must check if the script you are running doesn't set the variable to "".

**Comment by rjlee0** [comment]
os.environ['CUDA_VISIBLE_DEVICES'] = "0" 
I add this before tf.Session to solved it.
I have also tried "export CUDA_VISIBLE_DEVICES=0", and added the "os.environ['CUDA_VISIBLE_DEVICES'] = "0" " statement at the beginning of .py file. But it does not work
Only the add this before tf.Session effect.

**Comment by jalajthanaki** [comment]
I had same issue but I have resolved it by restarting my computer

**Comment by SnowMasaya** [comment]
I think nvidia-driver is not working.

You have to check command `nvidia-smi` 

If these command is not working, you have reboot your computer.

Maybe `nvidia-smi` works correctly.

**Comment by ZhongxuanWang** [comment]
This doesn't solve my issue. I ran `tf.config.list_physical_devices()` and I still can't see the GPU displayed, despite that error message is gone.

**Comment by sahil193101** [comment]
> Do you have a GPU in your machine that you want to use?
> 
> If not:
> 
> 1. consider using the CPU binary, not the GPU binary
> 2. you should be able to ignore these warnings.  they are helpful for debugging for those who do want to use GPUs.

hiii

**Comment by sahil193101** [comment]
> Do you have a GPU in your machine that you want to use?
> 
> If not:
> 
> 1. consider using the CPU binary, not the GPU binary
> 2. you should be able to ignore these warnings.  they are helpful for debugging for those who do want to use GPUs.


My TensorFlow is working fine giving the output I want but I get these errors which I don't understand  

```
2022-10-11 06:15:44.446179: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-10-11 06:15:44.446216: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-27-33): /proc/driver/nvidia/version does not exist
2022-10-11 06:15:44.447798: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Model loaded from disk
1/1 [==============================] - 1s 1s/step
[0.8738158]
SPOOFED FACE DETECTED

```

what are these errors??
