### ISSUE TITLE
Running code with Tensorflow GPU

### ISSUE THREAD

**Issue by HaoboZ** [tensorflow/tensorflow#25577]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 1.12.0
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: cuda=10.0/cudnn=7.4.2
- GPU model and memory: RTX 2080

**Describe the problem**

I installed the everything and ran the tests for cuda and cudnn that were said from and they both passed normally. Running small tests with tensorflow also worked, i.e. a linear regression model. However, I was trying to run a file using keras and doing a more complicated [model](https://github.com/tensorflow/models/tree/master/samples/outreach/blogs/segmentation_blogpost) and it threw errors when it started running an individual epoch. I also just ran the code with only a small portion of the images.

```
I tensorflow/stream_executor/platform/default/dso_loader.cc:161] successfully opened CUDA library libcudnn.so.7 locally
E tensorflow/stream_executor/cuda/cuda_dnn.cc:482] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E tensorflow/stream_executor/cuda/cuda_dnn.cc:482] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

...
...

tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d/Conv2D}}]]
	 [[conv2d_transpose_2/Shape/_1171]]
```

Running the code normally with tensorflow works fine, only the gpu version is failing. I tried both building it from source and using tf-nightly-gpu.

**Comment by ymodak** [comment]
duplicate #24828. Please take a look at the [workaround](https://github.com/tensorflow/tensorflow/issues/24828#issuecomment-457425190) used by another user.

**Comment by HaoboZ** [comment]
Already tried that. Cudnn was installed using the instructions [here](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#install-linux). 

Using conda list cudnn did not list any packages. The cudnn version was also the latest one available, compatible with cuda 10.0. I did try to use both methods since I first tried the debian file, which gave the same error. Later did the unzip to cuda location, still no difference and mnistCUDNN still passed, is there a possibility of conflict?

**Comment by crocoM4** [comment]
According to these [instructions](https://www.tensorflow.org/install/gpu) tensorflow is compatible with cuda 9.0 and, if i'm not mistaken, you have installed version 10.0. Maybe you should try to downgrade, i had a similar issue too

**Comment by HaoboZ** [comment]
I tried installing cuda 9.0 first, but it also crashed with a different error, saying some compatibility issues. I then read from [here](https://devtalk.nvidia.com/default/topic/1042338/does-it-work-rtx-2080-cuda-9-0-ubuntu-16-04-/) that it doesn't support turing architecture.

Only the default tensorflow on pip supports cuda 9.0, but the nightly build supports cuda 10.0. So it's to either build it from source or use the unstable nightly.

**Comment by ymodak** [comment]
@azaks2 Can you PTAL?

**Comment by ymodak** [comment]
@HaoboZ Can you please try installing TF 1.13.0-rc0? It supports cuda 10.0
Also are you able to execute your code in Google Colab successfully using GPU?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by bifeng** [comment]
@HaoboZ Did you solve this problem?

**Comment by HaoboZ** [comment]
Nope, changed the OS to Windows and it worked perfectly fine. That means it's probably not a problem with the hardware.

**Comment by Nikunjbansal99** [comment]
Solution: Restart the Kernel of Jupyter Notebook. Worked for me every time.
