### ISSUE TITLE
CUDA-related crash when training simple network

### ISSUE THREAD

**Issue by JustASquid** [tensorflow/tensorflow#25866]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, also tested on Ubuntu 18.04 on same machine
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0 and also 1.13.0rc2
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0 and also 10.0, cudnn 7.2 (appropriate cudnn versions for 9.0 and 10.0 respectively)
- GPU model and memory: GTX 1080 TI 11gb

**Describe the current behavior**

Depending on the batch size, during training there is eventually (After 1000 or so steps, sometimes a lot more steps with smaller batches) a CUDA-related crash, with one of a number of error messages. When the crash happens, sometimes the entire display on my computer goes black and resets.

This happens despite:
- No OOM errors on startup
- Using a bare-bones example CNN
- Trying with and without limiting the available memory with the option `tf.GPUOptions(per_process_gpu_memory_fraction=0.1, allow_growth=False)`
- Restarting the machine
- Reinstalling latest NVIDIA drivers
- Reinstalling CUDA
- Trying CUDA 9 (TF 1.12.0, conda env) and CUDA 10 (TF 1.13.0rc2, manual installation)

I'm beginning to suspect that this is a hardware issue but the GPU has never had any problems and can still run high intensity games for hours with no problems. There are also no abnormal temperature or other sensor readings in the diagnostics when this happens.

Is there anything I can do to narrow down whether this is a hardware problem?

**Describe the expected behavior**

No crash

**Code to reproduce the issue**
This code is taken from the [CNN tutorial](https://www.tensorflow.org/tutorials/estimators/cnn) with the exception of a line added to try limiting the GPU memory usage. The crash happens with or without this line.

For this particular example, a batch size of 50 was enough to consistently reproduce the error. The crash happens earlier with larger batch sizes however.

```
import tensorflow as tf
import numpy as np

tf.logging.set_verbosity(tf.logging.INFO)

def cnn_model_fn(features, labels, mode):
	"""Model function for CNN."""
	# Input Layer
	input_layer = tf.reshape(features["x"], [-1, 28, 28, 1])

	# Convolutional Layer #1
	conv1 = tf.layers.conv2d(
	  inputs=input_layer,
	  filters=32,
	  kernel_size=[5, 5],
	  padding="same",
	  activation=tf.nn.relu)

	# Pooling Layer #1
	pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 2], strides=2)

	# Convolutional Layer #2 and Pooling Layer #2
	conv2 = tf.layers.conv2d(
	  inputs=pool1,
	  filters=64,
	  kernel_size=[5, 5],
	  padding="same",
	  activation=tf.nn.relu)
	pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[2, 2], strides=2)

	# Dense Layer
	pool2_flat = tf.reshape(pool2, [-1, 7 * 7 * 64])
	dense = tf.layers.dense(inputs=pool2_flat, units=1024, activation=tf.nn.relu)
	dropout = tf.layers.dropout(
	  inputs=dense, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)

	# Logits Layer
	logits = tf.layers.dense(inputs=dropout, units=10)

	predictions = {
	  # Generate predictions (for PREDICT and EVAL mode)
	  "classes": tf.argmax(input=logits, axis=1),
	  # Add `softmax_tensor` to the graph. It is used for PREDICT and by the
	  # `logging_hook`.
	  "probabilities": tf.nn.softmax(logits, name="softmax_tensor")
	}

	if mode == tf.estimator.ModeKeys.PREDICT:
		return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)

	# Calculate Loss (for both TRAIN and EVAL modes)
	loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)

	# Configure the Training Op (for TRAIN mode)
	if mode == tf.estimator.ModeKeys.TRAIN:
		optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
		train_op = optimizer.minimize(
			loss=loss,
			global_step=tf.train.get_global_step())
		return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

	# Add evaluation metrics (for EVAL mode)
	eval_metric_ops = {
	  "accuracy": tf.metrics.accuracy(
		  labels=labels, predictions=predictions["classes"])
	}
	return tf.estimator.EstimatorSpec(
	  mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)
	  
# Load training and eval data
((train_data, train_labels),
 (eval_data, eval_labels)) = tf.keras.datasets.mnist.load_data()

train_data = train_data/np.float32(255)
train_labels = train_labels.astype(np.int32)  # not required

eval_data = eval_data/np.float32(255)
eval_labels = eval_labels.astype(np.int32)  # not required

gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.1, allow_growth=False)
session_config = tf.ConfigProto(gpu_options=gpu_options)
run_config = tf.estimator.RunConfig(session_config=session_config)	

# Create the Estimator
mnist_classifier = tf.estimator.Estimator(
    model_fn=cnn_model_fn, model_dir="./run", config=run_config)
	
# Set up logging for predictions
tensors_to_log = {"probabilities": "softmax_tensor"}

# Train the model
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": train_data},
    y=train_labels,
    batch_size=50,
    num_epochs=None,
    shuffle=True)

# train one step and display the probabilties
mnist_classifier.train(
    input_fn=train_input_fn,
    steps=10000000)

```

**Other info / logs**

*Example error message 1*
```
2019-02-21 16:43:26.973428: E tensorflow/stream_executor/cuda/cuda_driver.cc:1011] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered ::
2019-02-21 16:43:26.973442: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-02-21 16:43:26.984939: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
```

*Example error message 2*
```
2019-02-19 12:32:46.833634: E tensorflow/stream_executor/cuda/cuda_driver.cc:1011] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure ::
2019-02-19 12:32:46.833656: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 12:32:46.849082: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
```

*Example error message 3*
```
2019-02-19 13:19:11.936586: E tensorflow/stream_executor/cuda/cuda_driver.cc:1011] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure ::
2019-02-19 13:19:12.200064: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 13:19:12.204540: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 13:19:12.208523: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 13:19:12.213922: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 13:19:12.218206: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 13:19:12.223482: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 13:19:12.228027: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 13:19:12.233217: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-19 13:19:12.237655: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 000001A6735E4ED0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: GPU sync failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 102, in <module>
    steps=10000000)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1158, in _train_model_default
    saving_listeners)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1407, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "C:\Program Files\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: GPU sync failed
```

*Example Output and Error Message when running under cuda-memcheck on Ubuntu*
```
========= CUDA-MEMCHECK
INFO:tensorflow:Using config: {'_model_dir': './run', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ff649578710>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:From /home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-02-20 21:57:36.622307: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-02-20 21:57:36.717892: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-20 21:57:36.719031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:06:00.0
totalMemory: 10.91GiB freeMemory: 10.27GiB
2019-02-20 21:57:36.719054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-02-20 21:57:38.167083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-20 21:57:38.167111: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-02-20 21:57:38.167117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-02-20 21:57:38.167550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9930 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From /home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into ./run/model.ckpt.
INFO:tensorflow:loss = 2.3112628, step = 0
INFO:tensorflow:global_step/sec: 1.52266
INFO:tensorflow:loss = 2.2921445, step = 100 (65.674 sec)
INFO:tensorflow:global_step/sec: 1.52365
INFO:tensorflow:loss = 2.2698283, step = 200 (65.633 sec)
INFO:tensorflow:global_step/sec: 1.52262
INFO:tensorflow:loss = 2.2548892, step = 300 (65.676 sec)
INFO:tensorflow:global_step/sec: 1.51757
INFO:tensorflow:loss = 2.2342505, step = 400 (65.895 sec)
2019-02-20 22:02:30.594297: E tensorflow/stream_executor/cuda/cuda_driver.cc:684] failed to enqueue async memset operation: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-02-20 22:02:30.618259: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 0x55f0692849d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-02-20 22:02:30.618293: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 0x55f0692849d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-02-20 22:02:30.618303: E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 0x55f0692849d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: cuDNN Backward Filter function launch failure : input shape([500,1,28,28]) filter shape([5,5,1,32])
	 [[{{node gradients/conv2d/Conv2D_grad/Conv2DBackpropFilter}} = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/conv2d/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, ConstantFolding/gradients/conv2d/Conv2D_grad/ShapeN-matshapes-1, gradients/conv2d/Relu_grad/ReluGrad, ^gradients/conv2d/BiasAdd_grad/BiasAddGrad)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 102, in <module>
    steps=10000000)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: cuDNN Backward Filter function launch failure : input shape([500,1,28,28]) filter shape([5,5,1,32])
	 [[node gradients/conv2d/Conv2D_grad/Conv2DBackpropFilter (defined at cnn.py:59)  = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/conv2d/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, ConstantFolding/gradients/conv2d/Conv2D_grad/ShapeN-matshapes-1, gradients/conv2d/Relu_grad/ReluGrad, ^gradients/conv2d/BiasAdd_grad/BiasAddGrad)]]

Caused by op 'gradients/conv2d/Conv2D_grad/Conv2DBackpropFilter', defined at:
  File "cnn.py", line 102, in <module>
    steps=10000000)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "cnn.py", line 59, in cnn_model_fn
    global_step=tf.train.get_global_step())
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 400, in minimize
    grad_loss=grad_loss)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 519, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 814, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 408, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 814, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/nn_grad.py", line 526, in _Conv2DGrad
    data_format=data_format)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1092, in conv2d_backprop_filter
    dilations=dilations, name=name)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'conv2d/Conv2D', defined at:
  File "cnn.py", line 102, in <module>
    steps=10000000)
[elided 3 identical lines from previous traceback]
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "cnn.py", line 17, in cnn_model_fn
    activation=tf.nn.relu)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 417, in conv2d
    return layer.apply(inputs)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 817, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 204, in __call__
    name=self.name)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 957, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/daniel/miniconda3/envs/sorter/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)

InternalError (see above for traceback): cuDNN Backward Filter function launch failure : input shape([500,1,28,28]) filter shape([5,5,1,32])
	 [[node gradients/conv2d/Conv2D_grad/Conv2DBackpropFilter (defined at cnn.py:59)  = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/conv2d/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, ConstantFolding/gradients/conv2d/Conv2D_grad/ShapeN-matshapes-1, gradients/conv2d/Relu_grad/ReluGrad, ^gradients/conv2d/BiasAdd_grad/BiasAddGrad)]]

========= ERROR SUMMARY: 0 errors
```

**Comment by ymodak** [comment]
Your code is slightly different than the one in the tutorial. Can you please make following changes and execute again,
```python
mnist_classifier.train(input_fn=train_input_fn, steps=1000) # currently it has steps=10000000
```

**Comment by JustASquid** [comment]
@ymodak 

If the batch size is large enough, the crash happens with a smaller number of steps than 1000 to be sure. So yes, when executing again the issue still happens.

I tried running furmark (a GPU stress test) on the machine and after a similar amount of time I am seeing severe artifacts across the entire screen.

![img_20190222_132907235](https://user-images.githubusercontent.com/11645696/53219710-25a40f00-36b5-11e9-81af-aa7ae8feb174.jpg)

So I think we can be fairly confident that this is an issue with the graphics card hardware. If you feel that this makes it an issue not worth looking into, feel free to close this bug.

**Comment by ymodak** [comment]
Yes, Its fairly evident that it is more of a hardware issue. Thanks for sharing your investigation. I will close this issue, feel free to reopen if anything else comes up. Thanks!

**Comment by macfly1202** [comment]
HI, I want to reopen this because I encounter simlilar issue. 
I've run a custom model for more than 200 experimentation on 2 month and some scanning parameter training for 3 days without any issue.

Previously NO ISSUES was on driver 4.10, CUDA 9.0, Cudnn 7.3.1 
Ubuntu 16.04 
Tensorflow install from binary 
TensorFlow version (use command below): 1.12.0
Python 3.6
GPU model and memory: GTX 1080 TI 11gb 

For Now, ISSUES with: 
Nvidia driver 418.43
TensorFlow installed from: source
TensorFlow version: 1.13.0
Python version: 3.6
Bazel version (if compiling from source): 0.21.0 (higher version block building with a conveniant message that we must use 0.21.0) 
GCC/Compiler version (if compiling from source): GCC 5.4.0, recommended one 4.8.5 was failing on build.
CUDA/cuDNN version: 10.0 (tried 10.1 too), 7.4.2 (tried 7.5.1 too with CUDA 10.1)
cudnn 7.2 (appropriate cudnn versions for 9.0 and 10.0 respectively)
GPU model and memory: GTX 1080 TI 11gb  

```
 tensorflow/stream_executor/cuda/cuda_driver.cc:1000] could not wait stream on event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-03-19 23:31:22.049885: E tensorflow/stream_executor/cuda/cuda_driver.cc:1000] could not wait stream on event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-03-19 23:31:22.049943: E tensorflow/stream_executor/stream.cc:328] Error recording event in stream: error recording CUDA event on stream 0x5f6f9f0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2019-03-19 23:31:22.049953: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:740] failed to record completion event; therefore, failed to create inter-stream dependency
2019-03-19 23:31:22.049964: I tensorflow/stream_executor/stream.cc:5027] [stream=0x5f6f950,impl=0x5f6f130] did not memcpy host-to-device; source: 0x120b2480
2019-03-19 23:31:22.049886: E tensorflow/stream_executor/cuda/cuda_driver.cc:1131] failed to enqueue async memcpy from host to device: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure; GPU dst: 0x7f98f3649d00; host src: 0x7f988c0075c0; size: 19267584=0x1260000
2019-03-19 23:31:22.049972: I tensorflow/stream_executor/stream.cc:2079] [stream=0x5f6f950,impl=0x5f6f130] did not wait for [stream=0x5f6f710,impl=0x5f08840]
2019-03-19 23:31:22.049978: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-03-19 23:31:22.049989: I tensorflow/stream_executor/stream.cc:2079] [stream=0x5f6f950,impl=0x5f6f130] did not wait for [stream=0x5f6f710,impl=0x5f08840]
2019-03-19 23:31:22.050006: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
2019-03-19 23:31:22.050002: I tensorflow/stream_executor/stream.cc:5027] [stream=0x5f6f950,impl=0x5f6f130] did not memcpy host-to-device; source: 0x7f9b57c00b00
2019-03-19 23:31:22.050006: I tensorflow/stream_executor/stream.cc:2079] [stream=0x5f6f950,impl=0x5f6f130] did not wait for [stream=0x5f6f710,impl=0x5f08840]
2019-03-19 23:31:22.050085: I tensorflow/stream_executor/stream.cc:5027] [stream=0x5f6f950,impl=0x5f6f130] did not memcpy host-to-device; source: 0x7f9b57c01600 ```

I run models on my 1080ti weekly since january 2018 and never encounter a single issue. Nothing has change on my workstation hardware.

**Comment by JustASquid** [comment]
@macfly1202 

Sadly it looks very similar to my issue which was definitely a hardware issue. My problem also started happening without any hardware changes etc - I guess the GPU just died spontaneously. After I returned the card and got a replacement, the issue went away entirely.

Maybe try running https://www.geeks3d.com/gputest/ for a period of time (mine took 5 minutes or so) to see if you can replicate the artifacts or other graphical bugs.

**Comment by macfly1202** [comment]
@JustASquid thanks for answer. I run gputest / pixmark Piano in full screen during 40 minutes without any issue: GPU0 - core temp: 68 °C, core usage 100%
GPU0 - core temp: 68 °C, core usage 99%.

I will try compiled version to check especially the conda install tensorflow which embed the cuda package directly to check if errors occurs again.

**Comment by macfly1202** [comment]
[SOLVED] Just if someone have this issue, I use ubuntu 16.04 and reinstall driver from linux proprietary drivers reponow  according to a tutorial with CUDA 10.0 and Cudnn 7.3.1 (https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-ubuntu/). I didn't have issue anymore with this install. 
So there is something that cause issue with drivers  418.43 and cudnn 7.4.1. I had previously encounter issue with install tensorflow from PIP, conda and try built from source with same result in each case: failure reference here above.
Now, hapilly, issue is solve.

**Comment by KiransHub** [comment]
I'm running Windows, no issues with my GPU. I'm also getting the problem with my NVidia 1080.

**Comment by IsaacLord** [comment]
> @ymodak
> 
> If the batch size is large enough, the crash happens with a smaller number of steps than 1000 to be sure. So yes, when executing again the issue still happens.
> 
> I tried running furmark (a GPU stress test) on the machine and after a similar amount of time I am seeing severe artifacts across the entire screen.
> 
> ![img_20190222_132907235](https://user-images.githubusercontent.com/11645696/53219710-25a40f00-36b5-11e9-81af-aa7ae8feb174.jpg)
> 
> So I think we can be fairly confident that this is an issue with the graphics card hardware. If you feel that this makes it an issue not worth looking into, feel free to close this bug.

Hi!
Did you find any solution for this?

**Comment by macfly1202** [comment]
@ymodak : please read my comment above ; it solve my issue ; ```[SOLVED] Just if someone have this issue, I use ubuntu 16.04 and reinstall driver from linux proprietary drivers repo now according to a tutorial with CUDA 10.0 and Cudnn 7.3.1 (https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-ubuntu/). I didn't have issue anymore with this install.
So there is something that cause issue with drivers 418.43 and cudnn 7.4.1. I had previously encounter issue with install tensorflow from PIP, conda and try built from source with same result in each case: failure reference here above.
Now, hapilly, issue is solve.```

**Comment by esologic** [comment]
For what it's worth, I ran into this exact issue when interfacing with an NVIDIA tesla K80 via a docker container after the card had overheated. It was hard to debug as the `docker-build` process etc was working as expected.

**Comment by riyadfebrian** [comment]
i ran this error on windows 10 and GTX 1050
- Restarting PC doesnt work
- Kill GPU, flush memory didnt work
- Windows + Ctrl + Shift + B . doesnt work
-  I've make sure nothing change in the code... before this error comes, i've run training for several times w/o error
- make sure adding this snippet code, before any tensorflow calculation
 `physical_devices = tf.config.list_physical_devices('GPU')
try:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
    print("Setup memory growth")
except:
    # Invalid device or cannot modify virtual devices once initialized.
    print("Error gpu setup memory")` 

it doesn't work...
- nvidia-smi running without any problem

now I'm deadly stuck, only god knows what happen and what the solution.

**Comment by sjhsbhqf** [comment]
I just saw a discussion that may help you.

https://forum.faceswap.dev/viewtopic.php?t=1106
