### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS in SoftmaxCrossEntropyWithLogits when run in FP16

### ISSUE THREAD

**Issue by cbcase** [tensorflow/tensorflow#25977]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary (dockerhub: `tensorflow/tensorflow:1.13.0rc2-gpu-py3`)
- TensorFlow version (use command below): `b'v1.13.0-rc2-0-gc865ec5621' 1.13.0-rc2`
- Python version: 3.5.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0 / 7.4.1
- GPU model and memory: Quadro GV100, 32GB

**Describe the current behavior**
The `SoftmaxCrossEntropyWithLogits` op will hit a `CUDA_ERROR_ILLEGAL_ADDRESS` error when executed in fp16 with certain size inputs. 

**Describe the expected behavior**
No segfault -- though it's fine if the results are numerically bad.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import gen_nn_ops

mb = 4005
vocab = 8193

logits = tf.placeholder(tf.float16, shape=(mb, vocab))
labels = tf.placeholder(tf.int32, shape=(mb,))                        
targets = tf.one_hot(labels, depth=vocab, dtype=tf.float16)

xentropy, _ = gen_nn_ops.softmax_cross_entropy_with_logits(
    logits, targets)

logits_vals = np.random.randn(*logits.shape).astype(np.float16)
labels_vals = np.random.randint(0, vocab, size=labels.shape)

with tf.Session() as sess:
    ret = sess.run(xentropy, {logits: logits_vals,
                              labels: labels_vals})
```

**Other info / logs**
I've attached a log from cuda-memcheck. There is an illegal write in the relevant eigen kernel.
[memcheck-xentropy.log](https://github.com/tensorflow/tensorflow/files/2890344/memcheck-xentropy.log)

Other comments:
- This appears to be a recent regression -- I tried the same code on an older TF build (The nvidia 18.12-py3 container) and there was no error.
- This is a hard bug to hit, since `tf.nn.softmax_cross_entropy_with_logits_v2` will coerce its inputs to fp32.
- Many input sizes run fine; I haven't done thorough testing to establish which ones are OK and which aren't.
- As mentioned above, I don't expect numerically good answers in fp16 -- this came about as a result of perf measurements when coercing fp16 everywhere.

**Comment by jvishnuvardhan** [comment]
@cbcase Could you try it in recent TF1.13.1 version. I don't see any error. Thanks!

**Comment by cbcase** [comment]
Hi @jvishnuvardhan -- I just pulled `tensorflow/tensorflow:1.13.1-gpu-py3` (image id is `d1c5af36660b`) and got the same error running the above code as a standalone script. Anything else I can provide?

**Comment by ravikyram** [comment]
@cbcase 

Ca you try with TF version 1.15 and see if the issue still persists.I tried in colab with TF version 1.15 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/93f39b53adb0234e72c377306e0bcbd6/untitled121.ipynb).Thanks!

**Comment by ravikyram** [comment]
Closing the issue since the issue was resolved with TF 1.15 version. Thanks!
