### ISSUE TITLE
TensorFlow 1.13.1: ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PhungVanDuy** [tensorflow/tensorflow#26209]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.6 LTS
- TensorFlow installed from (source or binary): Binary (pip3 install -U tensorflow-gpu
- TensorFlow version: current version from pip (maybe version 1.13.1)
- Python version: Python 3.5.2
- Installed using virtualenv? pip? conda?: virtualenv environment with pip
- CUDA/cuDNN version: Cuda 9.0 
- GPU model and memory: Titan Xp

**Describe the problem**
I tried to install tensorflow-gpu follow the instruction at [link](https://www.tensorflow.org/install/gpu) and pip install -U tensorflow gpu. But when I check it `import tensorflow as tf` appear a bug as follow: 

> ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

Meanwhile, I also tried installing pytorch and succeeded. (Figure below)
![screenshot from 2019-02-28 20-31-09](https://user-images.githubusercontent.com/28798474/53569943-e0417f00-3b97-11e9-8a31-7c23a0f2b481.png)

**Comment by qpoisson** [comment]
how did you solve it ?

**Comment by helonayala** [comment]
up

**Comment by PhungVanDuy** [comment]
> how did you solve it?

Yes, I figured out my system installed Cuda 9.0 but maybe tensorflow 1.13.1 only support Cuda 10. So I  installed tensorflow 1.12.0 and it works!

Thanks!

**Comment by helonayala** [comment]
thanks mate

worked for me as well 

I will open an issue about it

**Comment by blemke** [comment]
I have TensorFlow 1.13.1 working on Ubunutu 16.04 with Python 3.7.2.
I had the error above using CUDA 10.1, but it went away after downgrading to CUDA 10.0

**Comment by mranon0007** [comment]
> > how did you solve it?
> 
> Yes, I figured out my system installed Cuda 9.0 but maybe tensorflow 1.13.1 only support Cuda 10. So I installed tensorflow 1.12.0 and it works!
> 
> Thanks!

Thank you. It worked for me.

**Comment by BornInWater** [comment]
> Yes, I figured out my system installed Cuda 9.0 but maybe tensorflow 1.13.1 only support Cuda 10. So I installed tensorflow 1.12.0 and it works!

Thanks a lot mate!

**Comment by Enzo90910** [comment]
> I have TensorFlow 1.13.1 working on Ubunutu 16.04 with Python 3.7.2.
> I had the error above using CUDA 10.1, but it went away after downgrading to CUDA 10.0

Same here, TF 1.13.1 would not import with latest CUDA (10.1) but worked fine after downgrade to CUDA 10.0. Thanks for the tip.

**Comment by shivangpatel** [comment]
Without downgrade any chance ?

**Comment by japrogramer** [comment]
same problem with
```
tensorflow-gpu==2.0.0a0
Python 3.7.3
5.0.7-arch1-1-ARCH
linux 5.0.7.arch1-1
Dell Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]
```

**Comment by shivangpatel** [comment]
We need to wait until **tensorflow** providing support to **CUDA10.1**.

**Comment by tshr729** [comment]
I had same problem with

`tensorflow-gpu==1.13.1
Python 3.7.3
OS = Ubuntu 18.04
cuda 10.1
cudNN = 7.5`

I fixed this by downgrading python to 3.5.5 and reinstall tensorflow-gpu

**Comment by Kailegh** [comment]
Can you explain how to easily downgrade from cuda 10.1->10.0? Do you also have to change the Cudnn libraries?

**Comment by Enzo90910** [comment]
> Can you explain how to easily downgrade from cuda 10.1->10.0? Do you also have to change the Cudnn libraries?

To my recollection, I only had to install 10.0 and it installed in the same directory and updated the symlink. I did not reinstall libcudnn because I don't need it yet, but you expect you would have to if you need it.

ls -l /usr/local/
lrwxrwxrwx   1 root root    9 Apr  2 19:57 cuda -> cuda-10.0
drwxr-xr-x  16 root root 4096 Apr  2 19:57 cuda-10.0
drwxr-xr-x  17 root root 4096 Apr  2 18:17 cuda-10.1

**Comment by wendy2003888** [comment]
> Can you explain how to easily downgrade from cuda 10.1->10.0? Do you also have to change the Cudnn libraries?

My situation is whichever install method I tried following the official archive [here](https://developer.nvidia.com/cuda-10.0-download-archive),  apt-get always install 10.1
If you face same problem, you can reference [this](https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-ubuntu/) article

**Comment by shivangpatel** [comment]
On ubuntu 18.10 - I successfully installed CUDA 10.0 toolkit by downgrading gcc and g++ version to 7.3. 
Now I can see my `nvcc --version` is `10.0 `.  

But still I getting that common errors.... `libcublas.so.10.0` is missing

Any IDEA ? Now what's a issue !

```

shivangpatel@shivangpatel:~$ python3 -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 3
Traceback (most recent call last):
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/shivangpatel/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by semal** [comment]
using tensorflow 1.12, it is working.

**Comment by kiitosu** [comment]
> Can you explain how to easily downgrade from cuda 10.1->10.0? Do you also have to change the Cudnn libraries?

you can do that with this command.
sudo apt purge cuda
sudo apt autoremove
sudo apt install cuda-10-0

And now it is working.

**Comment by apivovarov** [comment]
@kiitosu I tried that and still had the same error
When you install `cuda-10-0` on ubuntu 16.04 it does not install `libcudnn.so.7`
To install cudnn you need to download deb package from https://developer.nvidia.com/rdp/cudnn-download
and then install it 
```
sudo dpkg -i libcudnn7_7.5.1.10-1+cuda10.0_amd64.deb
```
After that `import tensorflow as tf` works!

**Comment by kiitosu** [comment]
> @kiitosu I tried that and still had the same error
> When you install `cuda-10-0` on ubuntu 16.04 it does not install `libcudnn.so.7`
> To install cudnn you need to download `cuDNN v7.5.1` deb package from https://developer.nvidia.com/rdp/cudnn-download
> and then install it
> 
> ```
> sudo dpkg -i libcudnn7_7.5.1.10-1+cuda10.0_amd64.deb
> ```
> 
> After that `import tensorflow as tf` works!

Yes I installed cuDNN before reinstall cuda10-0.

**Comment by 7thstorm** [comment]
I'm having a similar issue.
when I do nvcc --version, I get 
Cuda compilation tools, release 9.1, V9.1.85

but when I do nvidia-smi, 
I see cuda version 10 (I'm using 10 in my projects, so there's obviously an issue. How do I uninstall 9.x if that is the issue?

**Comment by archenroot** [comment]
@tshr729 - I wonder how got it working with CUDA 10.1 by just downgrading python, doesn't make much sense to me :-), the issue is in not supporeted version by Tensorflow itself...

So on my Gentoo system I have CUDA 10.1.105 which creates following platform links:
```
andromeda /opt/cuda/targets/x86_64-linux/lib # ls -la|grep cublas
lrwxrwxrwx 1 root root        17 May  3 11:14 libcublasLt.so -> libcublasLt.so.10
lrwxrwxrwx 1 root root        25 May  3 11:14 libcublasLt.so.10 -> libcublasLt.so.10.1.0.105
-rwxr-xr-x 1 root root  37058992 May  3 11:14 libcublasLt.so.10.1.0.105
-rw-r--r-- 1 root root  23513690 May  3 11:14 libcublasLt_static.a
lrwxrwxrwx 1 root root        15 May  3 11:14 libcublas.so -> libcublas.so.10
lrwxrwxrwx 1 root root        23 May  3 11:14 libcublas.so.10 -> libcublas.so.10.1.0.105
-rwxr-xr-x 1 root root  78315120 May  3 11:14 libcublas.so.10.1.0.105
-rw-r--r-- 1 root root  90723762 May  3 11:14 libcublas_static.a
```
So once I downgrade to 10.0.130 I get what Tensorflow looks for in following platform structure:
```
andromeda /opt/cuda/targets/x86_64-linux/lib # ls -la|grep cublas
lrwxrwxrwx 1 root root        17 Sep 12  2018 libcublas.so -> libcublas.so.10.0
lrwxrwxrwx 1 root root        21 Sep 12  2018 libcublas.so.10.0 -> libcublas.so.10.0.130
-rwxr-xr-x 1 root root  70796360 Sep 12  2018 libcublas.so.10.0.130
-rw-r--r-- 1 root root  88164166 May 17 17:51 libcublas_static.a
```

So now 10.0 link which is correct. I cannot understand how it by default works for you...

**Comment by htwang14** [comment]
> > how did you solve it?
> 
> Yes, I figured out my system installed Cuda 9.0 but maybe tensorflow 1.13.1 only support Cuda 10. So I installed tensorflow 1.12.0 and it works!
> 
> Thanks!

Maybe that's not true. I have a machine with tf 1.13.1 working well with CUDA 9.0 and another machine with tf 1.13.1 working well with CUDA 8.0

**Comment by jayagami** [comment]
if you are using conda

```shell
conda install cudatoolkit cudnn
```

I don't know why but it didi worked for me.
I searched for `libcublas.so.10.0` on pc, only found it on conda floader. 

> tensorflow-gpu=1.13.1
> python=3.7.3
> conda 4.6.14

**Comment by jmcarter9t** [comment]
I am using tensorflow-gpu=2.0.  Found `libcublas.so.10.0`  in `/usr/local/xxx-cu/targets/x86_64-linux/lib` (using Linux) using the `sudo find`. Then I added it to my `LD_LIBRARY_PATH` and it seemed to solve this issue.

**Comment by inprogs** [comment]
![sameubuntu1904stuffhere](https://user-images.githubusercontent.com/9089/58996980-b8972e00-87fa-11e9-83a0-a18b7bcc4de3.png)
as @archenroot mentioned - I do not understand that either

I specially made new 19.04 UBUNTU installation from scratch to rule off my all old dependencies.

It looks like some general problem with 

10 ```.0``` vs ```.1``` problem

even with tf-nightly-gpu

`(venv) pmasior@tr2950x:~$ python -c "from tensorflow.python.client import device_lib; print(device_lib.list_local_devices())"
2019-06-06 01:09:11.852551: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-06 01:09:11.891764: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3492930000 Hz
2019-06-06 01:09:11.893733: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x27c8160 executing computations on platform Host. Devices:
2019-06-06 01:09:11.893757: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-06 01:09:11.894730: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-06-06 01:09:11.938466: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-06 01:09:11.939175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.755
pciBusID: 0000:42:00.0
2019-06-06 01:09:11.939249: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-06-06 01:09:11.939284: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2019-06-06 01:09:11.939315: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2019-06-06 01:09:11.939346: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2019-06-06 01:09:11.939376: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2019-06-06 01:09:11.939405: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2019-06-06 01:09:11.941656: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-06-06 01:09:11.941677: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2019-06-06 01:09:12.009924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-06 01:09:12.009952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-06-06 01:09:12.009957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-06-06 01:09:12.011507: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-06 01:09:12.012722: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4cbebf0 executing computations on platform CUDA. Devices:
2019-06-06 01:09:12.012738: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10170710468233217199
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 10626384075838738102
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 11146589999346767740
physical_device_desc: "device: XLA_GPU device"
]
`

**Comment by sudheerExperiments** [comment]
Hello,

I had the same issue. I fixed it by adding the below command to the '**.bashrc**' file.

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.0/lib64/

**System configuration:**

```
Ubuntu 16.04 LTS
Cuda 10.0
cuDNN 7.6.0 for Cuda 10.0
```

I  used conda to configure my system.

**Comment by bsed** [comment]
2019-06-30 11:29:50.377478: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-06-30 11:29:50.627371: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-30 11:29:50.627688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
2019-06-30 11:29:50.627840: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/kelvin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib::/usr/local/cuda-10.1/lib64
2019-06-30 11:29:50.627943: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/kelvin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib::/usr/local/cuda-10.1/lib64
2019-06-30 11:29:50.628046: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/kelvin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib::/usr/local/cuda-10.1/lib64
2019-06-30 11:29:50.628156: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/kelvin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib::/usr/local/cuda-10.1/lib64
2019-06-30 11:29:50.628258: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/kelvin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib::/usr/local/cuda-10.1/lib64
2019-06-30 11:29:50.628347: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/kelvin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib::/usr/local/cuda-10.1/lib64
2019-06-30 11:29:50.628438: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/kelvin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib::/usr/local/cuda-10.1/lib64
2019-06-30 11:29:50.628451: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2019-06-30 11:29:50.628741: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-30 11:29:50.656947: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2893390000 Hz
2019-06-30 11:29:50.657609: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x51f97b0 executing computations on platform Host. Devices:
2019-06-30 11:29:50.657673: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-30 11:29:50.657886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-30 11:29:50.657925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      
2019-06-30 11:29:50.677345: W tensorflow/compiler/xla/service/platform_util.cc:256] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 2101870592
2019-06-30 11:29:50.677498: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
Aborted (core dumped)
(cv3)

**Comment by franva** [comment]
any update in September 2019?? 
I'm with Cuda 10.1

**Comment by mihaimaruseac** [comment]
Not for TF 1.13. Please switch to 1.15 or 2.0

**Comment by KwankiAhn** [comment]
> 
> 
> using tensorflow 1.12, it is working.

thanks !!! wired but works for me.
/usr/local/cuda-10.1/
tensorboard                   1.12.2
tensorboardX                  1.7
tensorflow                    1.12.0
tensorflow-estimator          1.13.0
tensorflow-gpu                1.13.1
tensorly                      0.4.4
Python 3.6.8

**Comment by sheldon-cb** [comment]
I had the same problem with tf 1.14 on Ubuntu 19.10 with Cuda 10.1 

`print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))`

If it reports 0 GPUs, it should list libraries that it can't find. I got it working by creating symlinks from the 10.1 libraries to the 10.0 names that TensorFlow reported was missing

`sudo ln -s /usr/lib/x86_64-linux-gnu/libcusparse.so.10.1.168 /usr/lib/x86_64-linux-gnu/libcusparse.so.10.0`

**Comment by Aquinius-Aquila** [comment]
I solved the problem with missing libraries in tensorflow-gpu by creating these links:

sudo ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart.so.10.2.89 /usr/local/cuda/lib64/libcudart.so.10.0
sudo ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5 /usr/local/cuda/lib64/libcudnn.so.7
sudo ln -s /usr/lib/x86_64-linux-gnu/libcublas.so.10.2.2.89 /usr/local/cuda/lib64/libcublas.so.10.0
sudo ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcufft.so.10.1.2.89 /usr/local/cuda/lib64/libcufft.so.10.0
sudo ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcurand.so.10.1.2.89 /usr/local/cuda/lib64/libcurand.so.10.0
sudo ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcusolver.so.10.3.0.89 /usr/local/cuda/lib64/libcusolver.so.10.0
sudo ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcusparse.so.10.3.1.89 /usr/local/cuda/lib64/libcusparse.so.10.0

**Comment by balloch** [comment]
> I had the same problem with tf 1.14 on Ubuntu 19.10 with Cuda 10.1
> 
> `print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))`
> 
> If it reports 0 GPUs, it should list libraries that it can't find. I got it working by creating symlinks from the 10.1 libraries to the 10.0 names that TensorFlow reported was missing
> 
> `sudo ln -s /usr/lib/x86_64-linux-gnu/libcusparse.so.10.1.168 /usr/lib/x86_64-linux-gnu/libcusparse.so.10.0`
> 
> You'll need to do a find to locate the library locations and there will likely be 5-10 libraries listed that you'll need to do this for.

This worked better for me than putting them in the CUDA directory at first, but that was because my LD_LIBRARY_PATH was not set. In the CUDA installer guide, they say that this is only necessary for the post-install of a runfile installer. This is bad advice. do it for all installations. Then @Aquinius-Aquila answer will work.

**Comment by NagabhushanSN95** [comment]
> if you are using conda
> 
> ```shell
> conda install cudatoolkit cudnn
> ```
> 
> no need to install cuda.
> 
> Recently I reinstalled ubuntu then have this problem.
> I searched for `libcublas.so.10.0` on pc, only found it under conda floader., maybe I should install cuda by deb.
> 
> > tensorflow-gpu=1.13.1
> > python=3.7.3
> > conda 4.6.14

Miraculously this worked! THough I had to specify cuda version as 10.0, otherwise it installed 10.2

`conda install cudatoolkit=10.0 cudnn`

**Comment by wibudonglao** [comment]
> > how did you solve it?
> 
> Yes, I figured out my system installed Cuda 9.0 but maybe tensorflow 1.13.1 only support Cuda 10. So I installed tensorflow 1.12.0 and it works!
> 
> Thanks!

Thanks! It was really helpful to me. I have been suffering this problem for 1 month and cant figure out how to fix this until i see your comment! <3
