### ISSUE TITLE
Profiling: libcupti.so cannot be loaded

### ISSUE THREAD

**Issue by wookayin** [tensorflow/tensorflow#2626]
### Environment info
Operating System: Linux Ubuntu 14.04 LTS (64bit)

Installed version of CUDA and cuDNN: CUDA 7.5.18 and CUDNN 4.0.7
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
❯❯❯ ls -l /usr/local/cuda-7.5/lib/libcud*
-rw----r-- 1 root root 189170  2월 24 18:12 /usr/local/cuda-7.5/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16  2월 24 18:12 /usr/local/cuda-7.5/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19  2월 24 18:12 /usr/local/cuda-7.5/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwx---r-x 1 root root 311596  2월 24 18:12 /usr/local/cuda-7.5/lib/libcudart.so.7.5.18
-rw----r-- 1 root root 558020  2월 24 18:12 /usr/local/cuda-7.5/lib/libcudart_static.a
```
```
❯❯❯ ls -l /usr/local/cuda-7.5/lib64/libcud*
-rw----r-- 1 root root   322936  2월 24 18:12 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16  2월 24 18:12 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19  2월 24 18:12 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwx---r-x 1 root root   383336  2월 24 18:12 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
-rw----r-- 1 root root   720192  2월 24 18:12 /usr/local/cuda-7.5/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13  3월  3 03:30 /usr/local/cuda-7.5/lib64/libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 root root       17  3월  3 03:30 /usr/local/cuda-7.5/lib64/libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxr-xr-x 1 root root 61453024  3월  3 03:30 /usr/local/cuda-7.5/lib64/libcudnn.so.4.0.7
```

If installed from binary pip package, provide:

1. Which pip package you installed : **Tensorflow 0.8.0 Nightly** Python2.7 Linux (GPU) e.g. [Build 118](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/118/)
2. The output from python -c "import tensorflow; print(tensorflow.__version__)". : 0.8.0

If installed from sources, provide the commit hash:

### Steps to reproduce

Although it is experimental, I am using the GPU profiling functionality with CUPTI. 

1. Run any tensorflow code that uses CUPTI or `tf.RunOptions.FULL_TRACE`.
2. The following error (segfault) occurs.

```
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcupti.so. LD_LIBRARY_PATH:
F tensorflow/core/common_runtime/gpu/cupti_wrapper.cc:57] Check failed: f != nullptr could not find cuptiActivityRegisterCallbacksin libcupti DSO; dlerror: /home/wookayin/.virtualenvs/tfdebug/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cuptiActivityRegisterCallbacks
[1]    82604 abort (core dumped)  python 19-mnist-profiling.py
```

Any TF code that invokes loading of `libcupti.so` will face the same error, but for convenience I will share a code that can run standalone: [19-mnist-profiling.py](https://gist.github.com/wookayin/06631c68bb48fc1d0a4eee77cbbba5f1)

### What have you tried?
The problem is that the shared library `libcupti.so` cannot be loaded. However, in some older nightly version (such as [Build 103](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/103/)) it worked.

UPD: I binary-searched to find the changeset to be blamed. Build 103 works, but [Build 104](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/104/) (Failed) and [Build 105](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/105/) does not work.
I highly suspect that this regression is since commit 6bd964c (but not sure):

- The path to `libcupti.so` would be `/usr/local/cuda/extras/CUPTI/lib64/libcupti.so`.
- After this commit, it seems that path to `libcupti.so` goes wrong. (but why?)

A strange thing to me is that tensorflow already has [a unit test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/timeline_test.py) for CUPTI and GPU tracing functionalities, so CI must have run this test as well. This bug might be happening in some environments only (like nightly build I installed via `pip`), or it can be a a bazel-related problem (when generating packages).

I have not investigated into this problem in detail; it looks that after some troubleshooting I can figure out what the cause is.

Thanks!

### Logs or other output that would be helpful

N/A

**Comment by aselle** [comment]
It looks like your local pre-sudo environment does not have access to libcupti.so but the default one in the sudo'd space does. The change that seems to have hit you is this

![image](https://cloud.githubusercontent.com/assets/326106/15761987/2f44e606-28d0-11e6-8bd2-1e877c3424dc.png)

So previously LD_LIBRARY_PATH was spelled wrong so it wasn't actually preserving the environment (see man sudo ) of that variable. Whereas now it is wiping out the default environment in sudo'd space. environment variables are usually wiped out for security (i.e. LD_PRELOAD and LD_LIBRARY_PATH are vulnerable to code injection that would run as root). 

So check the disparity with your environment between sudo'd and not sudo'd.

**Comment by prb12** [comment]
I'm not sure that the change to 'with_the_same_user' is relevant? 
(AFAIK, This is just used in our Jenkins test framework to ensure the LD_LIBRARY_PATH from the Docker container is used when running GPU tests as the user 'CI_BUILD_UID')

Note: the same GIT commit also changed the interpretation of the trace level enum.  Prior to this change, the TRACE_FULL option was only recording the host-side enqueueing of ops (i.e. what is now down if you specify 'SOFTWARE_TRACE') 

It is now the case the 'TRACE_FULL' will also try to enable the GPUTracer on CUDA builds.  
If you're running a python script, this requires libcupti to be on your LD_LIBRARY_PATH (since there's no other way to find the NVidia library.)

e.g. LD_LIBRARY_PATH=/usr/loca/cuda/lib64:/usrlocal/cuda/extras/lib64

**Comment by prb12** [comment]
Closing as (assumed) fixed.

**Comment by wookayin** [comment]
As of the current nightly build, I do not experience any segfault and it looks like that it is fixed with the latest available pip package.

Some information: I have the environment variable `LD_LIBRARY_PATH` unset (i.e. empty), and `ldconfig -p | grep libcupti` shows nothing. However, it seems that tensorflow can succesfully load the cupti module.

Thanks for the support!

**Comment by wookayin** [comment]
My mistake, with the [latest nightly](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.8.0-cp27-none-linux_x86_64.whl) the segfault still happens.

As @prb12 said, I think it might be necessary to include `/usr/local/cuda/extras/CUPTI/lib64` in the LD_LIBRARY_PATH or `/etc/ld.so.conf`. After configuring the path to libraries, the segfault does not occur, but I see a warning message for every invocation of `session.run()` (with metadata requested)

```
...
W tensorflow/core/common_runtime/gpu/gpu_tracer.cc:513] Unhandled API Callback for 2 41
W tensorflow/core/common_runtime/gpu/gpu_tracer.cc:513] Unhandled API Callback for 2 41
...
```

I think this might be another issue.

**Comment by prb12** [comment]
> I think this might be another issue.

Yes, the warning messages are a separate (known) issue which we are currently working on.  (also reported in [this StackOverflow post](http://stackoverflow.com/questions/37849009/warnings-when-executing-tensorflow-sample-code-mnist-with-summaries-py))

They are most likely due to differeces between versions of libcupti, and should be harmless (other than the undesirable log spam)

**Comment by shkr** [comment]
Appending `/usr/local/cuda/extras/CUPTI/lib64` to LD_LIBRARY_PATH environment variable solved the problem.

**Comment by wujun** [comment]
I fixed my problem according to shkr's suggestion

**Comment by auxsophia** [comment]
As said above, this solved my issue. In my case, I edited my ./bashrc file in the home directory by appending `/usr/local/cuda/extras/CUPTI/lib64` to the LD_LIBRARY_PATH.

`export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH:/usr/local/cuda/extras/CUPTI/lib64`

I got this error after following the [TensorBoard Tutorial](https://www.tensorflow.org/versions/r0.11/how_tos/summaries_and_tensorboard/index.html) from running their [mnist_with_summaries.py](https://github.com/tensorflow/tensorflow/blob/r0.11/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py). It occurred at the first summary logging (running FULL_TRACE).

**Comment by siddharthkhullar** [comment]
I'm facing this issue as well. Installed tf from source. Here's the log. Facing this issue while trying to run mnist_with_summaries.py.

I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.8475
pciBusID 0000:4b:00.0
Total memory: 7.92GiB
Free memory: 6.45GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:4b:00.0)
Accuracy at step 0: 0.0938
Accuracy at step 10: 0.6802
Accuracy at step 20: 0.818
Accuracy at step 30: 0.8561
Accuracy at step 40: 0.8777
Accuracy at step 50: 0.8767
Accuracy at step 60: 0.8853
Accuracy at step 70: 0.8833
Accuracy at step 80: 0.8885
Accuracy at step 90: 0.894
I tensorflow/stream_executor/dso_loader.cc:116] Couldn't open CUDA library LD_LIBRARY_PATH: 
F tensorflow/core/platform/default/gpu/cupti_wrapper.cc:59] Check failed: ::tensorflow::Status::OK() == (::tensorflow::Env::Default()->GetSymbolFromLibrary( GetDsoHandle(), kName, &f)) (OK vs. Not found: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cuptiActivityRegisterCallbacks)could not find cuptiActivityRegisterCallbacksin libcupti DSO

What is suspicious to me is the error calls out libcupti.so.8.0. (I think the version is 7.5), wonder why it's doing that!! All the other cudnn libraries are fine and are found locally. Any pointers?

**Comment by prb12** [comment]
> What is suspicious to me is the error calls out libcupti.so.8.0. (I think the version is 7.5), 

Why would that be suspicious if you're compiling from source and all the other CUDA libraries mentioned are CUDA8?   

> I have made the suggested changes to .bashrc with LD_LIBRARY_PATH. No luck.

This error report is not very meaningful without explaining how you configured your source tree (i.e. what versions of cuda libraries and header files did you point it at).    
 
Whatever version of CUDA header files you *built* against will have to match the shared library versions which are supplied at runtime via the `LD_LIBRARY_PATH` variable.

**Comment by auxsophia** [comment]
> Installed tf from source. 

Also important is which version you have. I think version 12 of TensorFlow might require cuda 8.0 :( 
But if you're installing from source, you should be able to specify cuda 7.5. 

You could also try version 11 of TensorFlow, but it will put you a little behind.

**Comment by siddharthkhullar** [comment]
I'm obviously new to this. I followed the instructions on getting started page for tf.
tensorflow: 0.12
cuDNN: v5.1
CUDA: 8.0 

This is how I configured the source (I'm assuming you're asking for ./configure options in tf? Exactly as suggested on the getting started tf page.
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python3.5/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.5/dist-packages]

Using python library path: /usr/local/lib/python3.5/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] N
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5       
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.0
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.......
____Loading package: tensorflow/contrib/factorization
____Loading package: tensorflow/contrib/tensor_forest/hybrid
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 742,277 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 1,488,145 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 2,232,595 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 2,977,045 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 3,722,913 bytes
INFO: All external dependencies fetched successfully.

**Comment by siddharthkhullar** [comment]
@prb12 Yes, it does. /extras/CUPTI/lib64 is on my LD_LIBRARY_PATH. Yes libcupti.so points to libcupti.so.8.0 which further points to a third file called libcupti.so.8.0.44 in that directory.

**Comment by aselle** [comment]
You can debug what libraries are being used by using LD_DEBUG environment variable to enable deubg printouts of the dynamic loader. 
```
LD_DEBUG=libs python tens.py  2>&1 | grep "calling init"
```
try that... make sure to resolve any generic ones... like i get
```
     39707:	calling init: /usr/local/cuda/lib64/libcudnn.so
```
but that is actually
```
$ ls -l /usr/local/cuda/lib64/libcudnn.so
lrwxrwxrwx 1 aselle xxx 13 Jul 26 22:55 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
```
Try removing the cuda 7.5 stuff. It likely is loading an incompatible library. If this doesn't work, build from a clean sandbox in case it built partially with 7.5 libraries.  Your initial report seemed to indicate you had 7.5 libraries installed.

**Comment by solomatov** [comment]
I've got a very similar error:

2017-05-14 23:24:50.784478: F tensorflow/core/platform/default/gpu/cupti_wrapper.cc:59] Non-OK-status: ::tensorflow::Env::Default()->GetSymbolFromLibrary( GetDsoHandle(), kName, &f) status: Not found: /home/kostik/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cuptiActivityRegisterCallbackscould not find cuptiActivityRegisterCallbacksin libcupti DSO

I use 1.11.0. Everything was installed as in the instruction.

**Comment by Carolzheng** [comment]
I have a similar problem. Error is pasted below (only the final error part).

My problem is that my libcupti.so.8.0 file is not in /usr/local/cuda/extras/CUPTI/lib64, it is in /usr/local/cuda8.0/lib64. I tried adding this path to LD_LIBRARY_PATH but didn't help. I didn't install CUDA myself, and am not familiar with CUDA at all so not sure why the path is a bit different from everyone else.

Any advice is highly appreciated. Thanks.


2018󈚧󈚴 13:58:56.835109: I tensorflow/stream_executor/dso_loader.cc:129] Couldn't open CUDA library libcupti.so.8.0. LD_LIBRARY_PATH: /lib64::/usr/local/cuda/extras/CUPTI/lib64
2018󈚧󈚴 13:58:56.835143: F ./tensorflow/stream_executor/lib/statusor.h:212] Non‑OK‑status: status_ status: Failed precondition: could not dlopen DSO: libcupti.so.8.0; dlerror: libcupti.so.8.0: cannot open shared object file: No such file or directory

**Comment by auxsophia** [comment]
Hey Carolzheng,

I'd suggest copying the file from /usr/local/cuda8.0/lib64 to whatever location you need it to be in. You can do it with the [cp command](https://www.computerhope.com/unix/ucp.htm) in the Linux terminal if you're on Ubuntu.

I bet you could also make a [symbolic link](https://kb.iu.edu/d/abbe) too.

Good luck.

**Comment by Carolzheng** [comment]
Thank you auxsophia for your advice, I tried that and now my error becomes:
2018󈚧󈚴 03:55:51.413954: F .tensorflow/stream_executor/lib/statusor.h:212] Couldn't open CUDA library libcupti.so.8.0. LD_LIBRARY_PATH: /lib64::/usr/local/cuda.0/extras/lib64

And my file was actually libcublas.so.8.0 not the libcupti.so.8.0. Does this indicate some error in cuda installation? Thanks very much.

**Comment by oren0e** [comment]
I get this error:
`W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory`

appending the extras path to the `$LD_LIBRARY_PATH` did help, but, then I started to get permission errors. So I found that I need to load my IDE with sudo (I use PyCharm), so after entering `sudo charm .` in my working directory the permission errors were gone but the previous error returned!
I tried to edit root's `.bashrc` but it didn't help.

I have `tensorflow-gpu 2.2.0`, with CUDA release 10.1, V10.1.243
OS: Ubuntu 18.04.4 LTS
GPU: GeForce RTX 2080 Ti/PCIe/SSE2

I am trying to use TensorBoard as a callback in Keras to monitor results. Please help.
