### ISSUE TITLE
Installing tensorflow-gpu

### ISSUE THREAD

**Issue by jxr006** [tensorflow/tensorflow#26987]
Folks,
In many of the forums you see countless people strugging to install the tensorflow for GPU.

If NVIDIA is really a partner you need to create files that say libcublas.latest with a sym link to the version.

It's pretty annoying that i have to deinstall cuda 10.1, because tensorflow-gpu only works with cuda 10.0, and that others struggle because the file name is 10 vs 10.0, etc..

this part makes installing a few hour/day process. 

It won't kill NVIDIA to have a few prior versions installed with the latest package.

Start typing: libcublas.so.9.0... all you see is hits on file not found for libcublas.so.8, libcublas.so.8.0, libcublas.so.9, libcublas.so.9.0, libcublas.so.10.0, libcublas.so.10, etc...

how much longer are you going to let this problem last?

Also, stop being so conda focused. Look what oracle did to java once they had the world on it.
stay with the open source standards. Conda is cr..p.

**Comment by meyerjo** [comment]
You don't have to uninstall CUDA 10.1. You only have to change the environment variables for your system or your virtualenv to the paths where CUDA 10.0 is located.

The error messages are not too beginner friendly, though.

**Comment by jxr006** [comment]
Nvidia support gave me a lot of bad info.

I found this to work:


$wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
$sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
$sudo apt-key adv --fetch-keys $https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
$sudo apt-get update
$wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
$sudo apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
$sudo apt-get update


$sudo apt-get install --no-install-recommends \
    cuda-10-0 \
    libcudnn7=7.4.1.5-1+cuda10.0  \
    libcudnn7-dev=7.4.1.5-1+cuda10.0


$sudo apt-get update && \
        sudo apt-get install nvinfer-runtime-trt-repo-ubuntu1804-5.0.2-ga-cuda10.0 \
        && sudo apt-get update \
        && sudo apt-get install -y --no-install-recommends libnvinfer-dev=5.0.2-1+cuda10.0

**Comment by ymodak** [comment]
We have updated the [gpu support page](https://www.tensorflow.org/install/gpu) on TF website with cuda requirements for TF version 1.13 and added linux gpu setup guide as well. Did you get a chance to take a look yet?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by akoslaczko** [comment]
Above instructions (also on the TF homepage) worked for me perfectly, except for the last line, which returned with the following error:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) libnvinfer-dev:amd64 < none -> 5.0.2-1+cuda10.0 @un puN Ib >
Broken libnvinfer-dev:amd64 Depends on libnvinfer5:amd64 < none | 5.1.2-1+cuda10.1 @un uH > (= 5.0.2-1+cuda10.0)
  Considering libnvinfer5:amd64 0 as a solution to libnvinfer-dev:amd64 9999
  Re-Instated cuda-license-10-1:amd64
  Re-Instated libcublas10:amd64
  Re-Instated cuda-cudart-10-1:amd64
  Re-Instated libnvinfer5:amd64
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libnvinfer-dev : Depends: libnvinfer5 (= 5.0.2-1+cuda10.0) but 5.1.2-1+cuda10.1 is to be installed
E: Unable to correct problems, you have held broken packages.

I had to state the following explicitly:

$sudo apt-get install -y --no-install-recommends libnvinfer5=5.0.2-1+cuda10.0

After that installing libnvinfer-dev=5.0.2-1+cuda10.0 also worked.
Thought it's worth mentioning here...

**Comment by adrianlubitz** [comment]
@ymodak you should include 

`$sudo apt-get install -y --no-install-recommends libnvinfer5=5.0.2-1+cuda10.0` 

into the [gpu support page](https://www.tensorflow.org/install/gpu)!
It took me a while to find this post.
I also found another small issue which was easy to solve but maybe worth mentioning:
[change of googles company name](https://medium.com/@andrea_45267/how-to-solve-the-changed-its-origin-value-from-google-inc-to-google-llc-apt-error-4675f891be1f)
Besides these two small things the guide is super clear! Good work! Thanks!

**Comment by asdfsx** [comment]
@ymodak I find a new problem, package `libnvinfer5=5.0.2-1+cuda10.0` and `libnvinfer-dev_5.1.2-1+cuda10.0_amd64.deb` is missing.
I can not find these packages on http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/. 
How to solve this problem?

**Comment by theclifbar** [comment]
> @ymodak you should include
> 
> `$sudo apt-get install -y --no-install-recommends libnvinfer5=5.0.2-1+cuda10.0`
> 
> into the [gpu support page](https://www.tensorflow.org/install/gpu)!

Quite unfortunate that this fix has been posted for 4 months but Google hasn't bothered to add it to the Tensorflow GPU install instructions for Ubuntu.  Poor docs hurt adoption.
