### ISSUE TITLE
Built TF 1.13.1 - libcublas.so.10.1: cannot open shared object file with classify_image.py

### ISSUE THREAD

**Issue by edrozenberg** [tensorflow/tensorflow#27155]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Slackware Linux 64 -current (14.2+)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.2
- Bazel version (if compiling from source): 0.21.0- (@non-git)
- GCC/Compiler version (if compiling from source): gcc-8.3.0-x86_64
- CUDA/cuDNN version: CUDA Version 10.1.105
- GPU model and memory: TITAN X (Pascal) 12 GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Running a tutorial sample `tensorflow/models-git/tutorials/image/imagenet]$ python3 classify_image.py` causes error:

```
2019-03-26 08:22:44.464647: I tensorflow/stream_executor/dso_loader.cc:142] Couldn't open CUDA library libcublas.so.10.1. LD_LIBRARY_PATH: 
2019-03-26 08:22:44.465972: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: could not dlopen DSO: libcublas.so.10.1; dlerror: libcublas.so.10.1: cannot open shared object file: No such file or directory
Aborted
```

**Describe the expected behavior**
Sample tutorial runs

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`tensorflow/models-git/tutorials/image/imagenet]$ python3 classify_image.py`

**Other info / logs**
This issue seems different from the other hundreds (thousands?) of similar reports. Most other similar issues are due to a mismatch between a binary (pre-compiled) tensorflow and the CUDA version installed by the user.

In my case, I successfully compiled TF 1.13.1 from source with GPU support. The tensorflow module loads in python3.

I can resolve the issue with running this sample by setting `LD_LIBRARY_PATH=/opt/nvidia/cuda/lib64` but this should NOT be necessary because I already configured this path in `/etc/ld.so.conf.d/cuda.conf` and ran `$ ldconfig`.

```
$ python3
Python 3.7.2 (default, Feb 19 2019, 23:15:48) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> 
```

```
$ cat /etc/ld.so.conf.d/cuda.conf 
/opt/nvidia/cuda/lib64
/opt/nvidia/cuda/extras/CUPTI/lib64
/opt/nvidia/nccl/lib
```

```
$ ls -al /opt/nvidia/cuda/lib64/libcublas.so.10.1
lrwxrwxrwx 1 root root 23 Mar 26 08:01 /opt/nvidia/cuda/lib64/libcublas.so.10.1 -> libcublas.so.10.1.0.105
```

```
$ ldconfig -p | grep libcublas
	libcublasLt.so.10 (libc6,x86-64) => /opt/nvidia/cuda/lib64/libcublasLt.so.10
	libcublasLt.so (libc6,x86-64) => /opt/nvidia/cuda/lib64/libcublasLt.so
	libcublas.so.10 (libc6,x86-64) => /opt/nvidia/cuda/lib64/libcublas.so.10
	libcublas.so (libc6,x86-64) => /opt/nvidia/cuda/lib64/libcublas.so
```

**Comment by edrozenberg** [comment]
Same issue running most things with Tensorflow. I need to always set `LD_LIBRARY_PATH=/opt/nvidia/cuda/lib64/` as an env var, otherwise Tensorflow fails to work due to the  libcublas not found error.

**Comment by Soulthym** [comment]
> Same issue running most things with Tensorflow. I need to always set `LD_LIBRARY_PATH=/opt/nvidia/cuda/lib64/` as an env var, otherwise Tensorflow fails to work due to the libcublas not found error.

Exactly the same problem, I will try this temporary fix though

**Comment by edrozenberg** [comment]
> > Same issue running most things with Tensorflow. I need to always set `LD_LIBRARY_PATH=/opt/nvidia/cuda/lib64/` as an env var, otherwise Tensorflow fails to work due to the libcublas not found error.
> 
> Exactly the same problem, but running ArchLinux and a GTX1070 Max-Q, I will try this temporary fix though.
> Edit: Not working here

A couple of things to check:

- Make sure you're specifying the lib(64) directory where CUDA is installed on your system. I installed CUDA in `/opt/nvidia/cuda` but it may be somewhere else on your system (`/usr/local`, etc)
- I had to create a few symlinks for a few CUDA library names that could not be found to make things work, may be required on your system also:
```
ln -s libcublas.so.10.1.0.105 libcublas.so.10.1
ln -s libcusolver.so.10.1.105 libcusolver.so.10.1
ln -s libcurand.so.10.1.105  libcurand.so.10.1
ln -s libcufft.so.10.1.105  libcufft.so.10.1
```

**Comment by edrozenberg** [comment]
Also note for TF 1.13.1 "TensorFlow GPU binaries are now built against CUDA 10 and TensorRT 5.0" so they may not work with CUDA 10.1. In my case I compiled TF 1.13.1 from source with CUDA 10.1 installed on my system.

**Comment by edrozenberg** [comment]
> Same issue running most things with Tensorflow. I need to always set `LD_LIBRARY_PATH=/opt/nvidia/cuda/lib64/` as an env var, otherwise Tensorflow fails to work due to the libcublas not found error.

For my case I found an easier workaround for now:
```
ln -s /opt/nvidia/cuda/lib64/libcublas.so.10.1 /usr/lib64/libcublas.so.10.1
```

As I document below I found out that it is looking in /usr/lib64 among other places, so I gave it what it wants.
https://github.com/tensorflow/tensorflow/pull/26230#issuecomment-480608904

**Comment by Soulthym** [comment]
> For my case I found an easier workaround for now:
> 
> ```
> ln -s /opt/nvidia/cuda/lib64/libcublas.so.10.1 /usr/lib64/libcublas.so.10.1
> ```
That fixed it for me until a better solution comes along, although under Arch the path is a bit different since `cuda` is directly under `/opt/` instead of `/opt/nvidia` :  
```
ln -s /opt/cuda/lib64/libcublas.so.10.1 /usr/lib64/libcublas.so.10.1
```  
Package used for install: `community/python-tensorflow-cuda 1.13.1-4`

**Comment by mathemaphysics** [comment]
For some reason, when installing Nvidia libraries from their own repositories, libcublas10 actually installs libcublas.so.10.2.XXX rather than 10.1 like it does for every other library in the CUDA Toolkit. I'm struggling to figure out how to get the 10.1 version of libcublas. Pulling my hair out because everything else is showing up.

**Comment by rtarquini** [comment]
@mathemaphysics having the same issue with 10.2 cublas being installed, I assume it is compatible. Did you figure it out? 
Having a problem getting a working pytorch build from source (1.5.0) with 10.2,  looking to find the root cause.

**Comment by mathemaphysics** [comment]
@rtarquini I had multiple versions installed. Unfortunately it seems Nvidia's apt repositories for Ubuntu 18.04 mixed up some minor version numbers that worked for some libraries (all of them other than cublas appeared to be okay).

I had to dig through the libraries and link the right ones and set the path right.

I later upgraded to 11 and it all worked just fine. Using 11 now.

**Comment by mohantym** [comment]
Hi @edrozenberg !
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
