### ISSUE TITLE
ResourceExhaustedError when testing Deep MNIST for experts

### ISSUE THREAD

**Issue by andorremus** [tensorflow/tensorflow#279]
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](MaxPool, Variable_4)]]
	 [[Node: range_3/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_207_range_3", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Conv2D_1', defined at:

A bit more info here 

I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 256 (256B) Pool: chunks: 64 free: 24 cumulative malloc: 73160 cumulative freed: 73120
Number of chunks: 64, in_use chunks: 40
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 512 (512B) Pool: chunks: 8 free: 8 cumulative malloc: 3040 cumulative freed: 3040
Number of chunks: 8, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 2048 (2.0KiB) Pool: chunks: 16 free: 16 cumulative malloc: 28080 cumulative freed: 28080
Number of chunks: 16, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 4096 (4.0KiB) Pool: chunks: 16 free: 5 cumulative malloc: 24035 cumulative freed: 24024
Number of chunks: 16, in_use chunks: 11
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 16384 (16.0KiB) Pool: chunks: 1 free: 1 cumulative malloc: 1 cumulative freed: 1
Number of chunks: 1, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 32768 (32.0KiB) Pool: chunks: 4 free: 2 cumulative malloc: 1002 cumulative freed: 1000
Number of chunks: 4, in_use chunks: 2
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 65536 (64.0KiB) Pool: chunks: 8 free: 3 cumulative malloc: 2011 cumulative freed: 2006
Number of chunks: 8, in_use chunks: 5
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 81920 (80.0KiB) Pool: chunks: 2 free: 1 cumulative malloc: 3 cumulative freed: 2
Number of chunks: 2, in_use chunks: 1
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 163840 (160.0KiB) Pool: chunks: 8 free: 8 cumulative malloc: 8020 cumulative freed: 8020
Number of chunks: 8, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 212992 (208.0KiB) Pool: chunks: 20 free: 15 cumulative malloc: 42248 cumulative freed: 42243
Number of chunks: 20, in_use chunks: 5
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 327680 (320.0KiB) Pool: chunks: 4 free: 4 cumulative malloc: 2000 cumulative freed: 2000
Number of chunks: 4, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 425984 (416.0KiB) Pool: chunks: 4 free: 4 cumulative malloc: 5 cumulative freed: 5
Number of chunks: 4, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 655360 (640.0KiB) Pool: chunks: 4 free: 4 cumulative malloc: 8020 cumulative freed: 8020
Number of chunks: 4, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 1310720 (1.25MiB) Pool: chunks: 6 free: 6 cumulative malloc: 12020 cumulative freed: 12020
Number of chunks: 6, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 2097152 (2.00MiB) Pool: chunks: 1 free: 1 cumulative malloc: 2020 cumulative freed: 2020
Number of chunks: 1, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 2621440 (2.50MiB) Pool: chunks: 8 free: 8 cumulative malloc: 16040 cumulative freed: 16040
Number of chunks: 8, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 5242880 (5.00MiB) Pool: chunks: 8 free: 8 cumulative malloc: 18060 cumulative freed: 18060
Number of chunks: 8, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 13631488 (13.00MiB) Pool: chunks: 8 free: 3 cumulative malloc: 2008 cumulative freed: 2003
Number of chunks: 8, in_use chunks: 5
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 31457280 (30.00MiB) Pool: chunks: 1 free: 1 cumulative malloc: 2 cumulative freed: 2
Number of chunks: 1, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 41943040 (40.00MiB) Pool: chunks: 1 free: 1 cumulative malloc: 1 cumulative freed: 1
Number of chunks: 1, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 251658240 (240.00MiB) Pool: chunks: 1 free: 0 cumulative malloc: 1 cumulative freed: 0
Number of chunks: 1, in_use chunks: 1
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 503316480 (480.00MiB) Pool: chunks: 0 free: 0 cumulative malloc: 0 cumulative freed: 0
Number of chunks: 0, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:339] Chunk size: 1006632960 (960.00MiB) Pool: chunks: 3 free: 3 cumulative malloc: 3 cumulative freed: 3
Number of chunks: 3, in_use chunks: 0
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:345] Aggregate Region Memory: 3576057856 (3.33GiB)
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:347] Aggregate Chunk Memory: 3539046400 (3.30GiB)
W tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:89] Out of GPU memory, see memory state dump above
W tensorflow/core/kernels/conv_ops.cc:162] Resource exhausted: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
W tensorflow/core/common_runtime/executor.cc:1027] 0x3c81ab0 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](MaxPool, Variable_4)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x49fab20 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](MaxPool, Variable_4)]]
	 [[Node: range_3/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_207_range_3", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x49fab20 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](MaxPool, Variable_4)]]
	 [[Node: Cast_1/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_206_Cast_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Traceback (most recent call last):
  File "/home/andorremus/PycharmProjects/facial-keypoints/mnist.py", line 93, in <module>
    print "test accuracy %g" % accuracy.eval(feed_dict={x: mnist.test.images, y_: mnist.test.labels, keep_prob:1.0}, session=sess)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 405, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2728, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 345, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 419, in _do_run
    e.code)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 10000 } dim { size: 14 } dim { size: 14 } dim { size: 64 }
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](MaxPool, Variable_4)]]
	 [[Node: range_3/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_207_range_3", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Conv2D_1', defined at:
  File "/home/andorremus/PycharmProjects/facial-keypoints/mnist.py", line 63, in <module>
    h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2))
  File "/home/andorremus/PycharmProjects/facial-keypoints/mnist.py", line 42, in conv2d
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 207, in conv2d
    use_cudnn_on_gpu=use_cudnn_on_gpu, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 633, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1710, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 988, in __init__
    self._traceback = _extract_stack()

**Comment by vrv** [comment]
Likely a dupe of: https://github.com/tensorflow/tensorflow/issues/136

We've fixed this at HEAD for reasonable GPU memory sizes, it will be in our next binary release.  If you feel comfortable building from source, you can make progress :)

**Comment by andorremus** [comment]
Yep, didn't see it. Thanks for pointing it out.

**Comment by Abdulaziz123** [comment]
I have also the exactly same issue. I use on CUDA
