### ISSUE TITLE
Import Error while building on Windows with cudnn64_7.dll

### ISSUE THREAD

**Issue by ly0koS** [tensorflow/tensorflow#28223]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows10 1809
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N?A
- TensorFlow installed from (source or binary):source
- TensorFlow version:r1.14
- Python version:3.6.8
- Installed using virtualenv? pip? conda?:No
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):visual studio 2015
- CUDA/cuDNN version:10.1/7.5.1
- GPU model and memory:780ti 3g

Although I already add cuda & cudnn locations to PATH , and when I run configure.py it do catch up the cuda &cudnn locations. But while compling I still get a wired Import Error.

//configure.py:
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.24.1 installed.
Please specify the location of python. [Default is C:\Users\ly0ko\AppData\Local\Programs\Python\Python36\python.exe]:

Found possible Python library paths:
  C:\Users\ly0ko\AppData\Local\Programs\Python\Python36\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\ly0ko\AppData\Local\Programs\Python\Python36\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]:
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 10.1 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include
Found cuDNN 7 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 3.5

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: -march=native

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

//build ERROR Massage:

ERROR: D:/programming/tf/tensorflow/tensorflow/python/keras/api/BUILD:12:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/ly0ko/_bazel_ly0ko/6bo2um6w/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.1\;C:\Users\ly0ko\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\ly0ko\AppData\Local\Programs\Python\Python36\;C:\Users\ly0ko\AppData\Local\Microsoft\WindowsApps;C:\Users\ly0ko\AppData\Roaming\npm;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1;C:\msys64;C:\msys64\usr\bin;
    SET PYTHON_BIN_PATH=C:/Users/ly0ko/AppData/Local/Programs/Python/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Users/ly0ko/AppData/Local/Programs/Python/Python36/lib/site-packages
    SET TF_CONFIGURE_IOS=0
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=3.5
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TF_NEED_TENSORRT=0
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/x64_windows-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.exe  --apidir=bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api --apiname=keras --apiversion=1  --package=tensorflow.python,tensorflow.python.keras --output_package=tensorflow.python.keras.api bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/activations/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/densenet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/inception_resnet_v2/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/inception_v3/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/mobilenet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/mobilenet_v2/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/nasnet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/resnet50/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/vgg16/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/vgg19/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/applications/xception/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/backend/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/callbacks/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/constraints/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/boston_housing/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/cifar10/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/cifar100/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/fashion_mnist/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/imdb/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/mnist/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/datasets/reuters/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/estimator/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/experimental/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/initializers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/layers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/layers/experimental/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/losses/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/metrics/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/mixed_precision/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/mixed_precision/experimental/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/models/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/optimizers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/optimizers/schedules/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/preprocessing/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/preprocessing/image/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/preprocessing/sequence/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/preprocessing/text/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/regularizers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/utils/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/wrappers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/python/keras/api/keras/wrappers/scikit_learn/__init__.py
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "\\?\C:\Users\ly0ko\AppData\Local\Temp\Bazel.runfiles_9jiiji0f\runfiles\org_tensorflow\tensorflow\python\platform\self_check.py", line 87, in preload_check
    ctypes.WinDLL(build_info.cudnn_dll_name)
  File "C:\Users\ly0ko\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\ly0ko\AppData\Local\Temp\Bazel.runfiles_9jiiji0f\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\ly0ko\AppData\Local\Temp\Bazel.runfiles_9jiiji0f\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\C:\Users\ly0ko\AppData\Local\Temp\Bazel.runfiles_9jiiji0f\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "\\?\C:\Users\ly0ko\AppData\Local\Temp\Bazel.runfiles_9jiiji0f\runfiles\org_tensorflow\tensorflow\python\platform\self_check.py", line 97, in preload_check
    % (build_info.cudnn_dll_name, build_info.cudnn_version_number))
ImportError: Could not find 'cudnn64_.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN  from this URL: https://developer.nvidia.com/cudnn
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by muddham** [comment]
@ly0koS Request you to please check all the below points and let us know .Thanks!
 1)The error suggests this. Did you try finding cudnn and putting it in your path?
if not  then use below method
you should rename the cudnn64_7.dll or cudnn64_8.dll as cudnn64_6.dll in the below path of your system
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

2)Stackoverflow links: Please refer these
https://stackoverflow.com/questions/48698536/tensorflow-gpu-import-tensorflow-importerror-could-not-find-cudnn64-7-dll

https://stackoverflow.com/questions/51824219/importerror-could-not-find-cudnn64-7-dll/51825974


3)Please go through the steps present in the below link for installing tensorflow
 https://www.tensorflow.org/install/gpu

4)Software requirements:
NVIDIA® GPU drivers —CUDA 10.0 requires 410.x or higher.

Hardware requirements:
NVIDIA® GPU card with CUDA® Compute Capability 3.5 or higher.

**Comment by ly0koS** [comment]
> @ly0koS Request you to please check all the below points and let us know .Thanks!
> 1)Stackoverflow links: Please refer these
> https://stackoverflow.com/questions/48698536/tensorflow-gpu-import-tensorflow-importerror-could-not-find-cudnn64-7-dll
> https://stackoverflow.com/questions/51824219/importerror-could-not-find-cudnn64-7-dll/51825974
> 2)The error suggests this. Did you try finding cudnn and putting it in your path?
> if not  then use below method
> you should rename the cudnn64_6.dll or cudnn64_8.dll as cudnn64_7.dll in the below path of your system
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
> 3)Please go through the steps present in the below link for installing tensorflow
> https://www.tensorflow.org/install/gpu
> 4)Software requirements:
> NVIDIA® GPU drivers —CUDA 10.0 requires 410.x or higher.
> Hardware requirements:
> NVIDIA® GPU card with CUDA® Compute Capability 3.5 or higher.

1)These are neither my problem and I did try all of them before I made the issue.

2)I do put the cudnn files in my path.
I use "where" in terminal and it returns C:\C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin

3)I just want to build tensorflow-gpu with AVX2 SSE enabled.

4)I meet all these requirements

**Comment by muddham** [comment]
@ly0koS Can you please downgrade your tensorflow to 1.12 and follow the steps as per [link](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12), if you are particular to use 1.14 then please downgrade CUDA to 10.0

**Comment by ly0koS** [comment]
> 
> 
> @ly0koS Can you please downgrade your tensorflow to 1.12 and follow the steps as per [link](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12), if you are particular to use 1.14 then please downgrade CUDA to 10.0

Thanks,downgrade to 1.12 fixed my problem!

**Comment by muddham** [comment]
@ly0koS  Closing this issue as downgrading to TF1.12 resolved this error

**Comment by yashrajjain726** [comment]
install tensorflow-gpu in a fresh new env to be detected . Since, one env has many versions, so it makes it confusing.
