### ISSUE TITLE
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#28285]
**System information**
- Linux Ubuntu 19.04
- TensorFlow installed from (binary)
- TensorFlow: tenserflow-gpu 1.13.1
- Python version: 3.6
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.5
- GPU model and memory: Nvidia Geforce 840m 3 go

** The problem that i get**

I have installed tenserflow using the command :

> pip install --upgrade tenserflow-gpu

I get this error : 

> ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

    Failed to load the native TensorFlow runtime.

How can i solve this ?
Note : Cuda worked fine and my graphic card drivers are installed

**Comment by jcaguirre89** [comment]
I have the same issue, system:
Linux Ubuntu 118.10
TensorFlow: tenserflow-gpu 1.13.1
Python version: 3.6
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: 10.1/7.5
GPU model and memory: Nvidia GeForce RTX 2080

**Comment by Leerw** [comment]
try
sudo ldconfig /usr/local/cuda-xx/lib64

**Comment by abdou31** [comment]
> try
> sudo ldconfig /usr/local/cuda-xx/lib64

dosn't solve the problem

**Comment by jcaguirre89** [comment]
#26150 is a good reference to this problem.

**Comment by abdou31** [comment]
> #26150 is a good reference to this problem. CUDA 10.1 is currently not supported.

This is not a solution if you tell me that  is not supported , I can't use another cuda version , i have ubuntu 19.04 and it support only cuda 10.1 so i can't downgrade ubuntu ( install other version <19.04 )

**Comment by gadagashwini** [comment]
@abdou31 Please have look on software requirements for tensorflow-gpu 1.13 and above version is mentioned in this [link](https://www.tensorflow.org/install/gpu#software_requirements).  Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by TekayaNidham** [comment]
in case anyone still facing this:
i got cuda 10.2 and i just ran into this problem and here's how i solved it : 
cd ~
gedit .bashrc
```
#add this in the end : 
export PATH=/usr/local/cuda-10.2/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64\${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda10.2/targets/x86_64linux\${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
