### ISSUE TITLE
UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

### ISSUE THREAD

**Issue by kernelizd** [tensorflow/tensorflow#28326]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): TF 2.0 alpha0
- Python version: 3.6
- Bazel version (if compiling from source): I don't know
- GCC/Compiler version (if compiling from source): I don't know
- CUDA/cuDNN version: cudnn 7.3.1, Cuda 10.0.1
- GPU model and memory: Titan RTX 24GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I just built one conv2d layer and gave it a random input, that's all. Throws error above.
I'm using Anaconda. I installed tf-gpu 2.0 alpha0 via command line, cause Anaconda doesn't offer it.

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
layer = tf.keras.layers.Conv2D(2, (3,3))
layer(np.random.rand(5,5,3,1))

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-4-7d2f5dcef289> in <module>
----> 1 layer(np.random.rand(5,5,3,1))

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    658           with base_layer_utils.autocast_context_manager(
    659               input_list, self._mixed_precision_policy.should_cast_variables):
--> 660             outputs = self.call(inputs, *args, **kwargs)
    661           self._handle_activity_regularization(inputs, outputs)
    662           self._set_mask_metadata(inputs, outputs, previous_mask)

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\keras\layers\convolutional.py in call(self, inputs)
    194 
    195   def call(self, inputs):
--> 196     outputs = self._convolution_op(inputs, self.kernel)
    197 
    198     if self.use_bias:

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\ops\nn_ops.py in __call__(self, inp, filter)
   1076 
   1077   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
-> 1078     return self.conv_op(inp, filter)
   1079 
   1080 

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\ops\nn_ops.py in __call__(self, inp, filter)
    632 
    633   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
--> 634     return self.call(inp, filter)
    635 
    636 

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\ops\nn_ops.py in __call__(self, inp, filter)
    231         padding=self.padding,
    232         data_format=self.data_format,
--> 233         name=self.name)
    234 
    235 

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\ops\nn_ops.py in conv2d(input, filter, strides, padding, use_cudnn_on_gpu, data_format, dilations, name, filters)
   1949                            data_format=data_format,
   1950                            dilations=dilations,
-> 1951                            name=name)
   1952 
   1953 

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py in conv2d(input, filter, strides, padding, use_cudnn_on_gpu, explicit_paddings, data_format, dilations, name)
   1119             input, filter, strides=strides, use_cudnn_on_gpu=use_cudnn_on_gpu,
   1120             padding=padding, explicit_paddings=explicit_paddings,
-> 1121             data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
   1122       except _core._SymbolicException:
   1123         pass  # Add nodes to the TensorFlow graph.

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py in conv2d_eager_fallback(input, filter, strides, padding, use_cudnn_on_gpu, explicit_paddings, data_format, dilations, name, ctx)
   1218   explicit_paddings, "data_format", data_format, "dilations", dilations)
   1219   _result = _execute.execute(b"Conv2D", 1, inputs=_inputs_flat, attrs=_attrs,
-> 1220                              ctx=_ctx, name=name)
   1221   _execute.record_gradient(
   1222       "Conv2D", _inputs_flat, _attrs, _result, name)

~\.conda\envs\alphagpu\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     64     else:
     65       message = e.message
---> 66     six.raise_from(core._status_to_exception(e.code, message), None)
     67   except TypeError as e:
     68     if any(ops._is_keras_symbolic_tensor(x) for x in inputs):

~\.conda\envs\alphagpu\lib\site-packages\six.py in raise_from(value, from_value)

UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

**Comment by kernelizd** [comment]
Some people reported the same thing but with tf 1.13, and they solved it by changing cudnn version to 7.4. In my case, Anaconda only offers 7.3.1 max! so, I tried downgrading to solve it, but that will knock down CUDA from 10.0 to 9.0 which makes TF 2.0 dead. So, I'm stuck with this version of Cudnn.
Other people recommended allowing memory growth and stuff like that. Did not work.

**Comment by kernelizd** [comment]
> * source

**Comment by Jonathan-Livingston-Seagull** [comment]
This error is for sure due to version mismatch of Cuda/cudnn. When I got this error I followed the instructions on this link https://www.tensorflow.org/install/gpu and it solved the problem. Have you tried that?

**Comment by achandraa** [comment]
@kernelizd : TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0). You can try @Jonathan-Livingston-Seagull's suggestion and let us know if that helps. Thanks!

**Comment by kernelizd** [comment]
In the webpage you referred me to tensorflow.org, it mentions this:
**cuDNN SDK (>= 7.4.1)**
as software requirement for TF 2.0
my cuDNN however is only 7.3 cause that is the latest Anaconda is offering.
It could very well be because of this

**Comment by Jonathan-Livingston-Seagull** [comment]
You could uninstall cudnn from the conda environment and install the required version of cudnn in your windows system natively and update the path variable accordingly. There is a separate section for windows set up in that link. Please follow those steps.

**Comment by kernelizd** [comment]
Great idea. Thanks

**Comment by shenyingying** [comment]
> In the webpage you referred me to tensorflow.org, it mentions this:
> **cuDNN SDK (>= 7.4.1)**
> as software requirement for TF 2.0
> my cuDNN however is only 7.3 cause that is the latest Anaconda is offering.
> It could very well be because of this

hi ,why there is also  UnknownError: Failed to get convolution algorithm. when i use cuda 10.0 cudann 7.4.1

**Comment by kernelizd** [comment]
I haven't actually tried it, I just blamed the my 7.3 cudnn. Based on your report that the same problem exists in 7.4, I reopened the issue.

**Comment by achandraa** [comment]
@kernelizd : Are you trying with CUDA 10.1 or CUDA 10.0 ? CUDA 10.1 is not supported for tf versions >=1.13.0.

**Comment by kernelizd** [comment]
I did. That issue is about TF 1.13. In my case it is TF 2.0-alpha
At any rate, the solutions offered for both cases are almost the same. I did try them but no luck.
I downgraded my cuda to 10, updated my cudnn to 7.4  and now it is working

**Comment by Frank17** [comment]
I hava 2 GPUs: RTX 2070
My TensorFlow is v1.13.1, cuda is 10.0 and cudnn is 7.4.1 for cuda10.
System version: CentOS 7.6

When I run the test code with TensorFlow and cnn layer, it still has this exception.
I can run the sample codes provided by cudnn but error when tensorflow.

**Comment by tacolovejudy** [comment]
RTX2060 and Win10 + Anaconda + CUDA 10.0 + Cudnn 7.4.1 ---- it's OK!

Because anaconda doesn't have cudnn 7.4.1.
I tried to install tf by pip instead of conda, it's work!

**Comment by sidd-hart** [comment]
I was facing the same issue with tensorflow-gpu version 2.0-beta, and figured this is definitely a tensorflow-cuda-cudnn version mismatch problem. The issue occuered because my default Python  came from Anaconda, whereas I was installing CUDA/CUDNN as instructed on  TF-gpu installation page. I installed the latest versions of both CUDA and CUDNN, but, every time I checked the versions shown were older ones, and not the ones I had installed. So I installed everything again using conda instead, and it seemed to work flawlessly.   

**Tensorflow version -- 2.0.0-beta1
CUDA version -- 10.1.168 
CUDNN version -- 7.6.0**

Use the following command to check CUDA installation by Conda:

`conda list cudatoolkit`

And the following command to check CUDNN version installed by conda:

`conda list cudnn`

If you want to install/update CUDA and CUDNN through CONDA, please use the following commands:

```
conda install -c anaconda cudatoolkit
conda install -c anaconda cudnn
```

Alternatively you can use following commands to check CUDA installation:

`nvidia-smi`
OR
`nvcc --version`

If you are using tensorflow-gpu through Anaconda package (You can verify this by simply opening Python in console and check if the default python shows Anaconda, Inc. when it starts, or you can run which python and check the location), then manually installing CUDA and CUDNN will most probably not work. You will have to update through conda instead.

If you want to install CUDA, CUDNN, or tensorflow-gpu manually, you can check out the instructions here https://www.tensorflow.org/install/gpu

**Comment by juwikuang** [comment]
I downgraded cuDnn from 7.6.2 to 7.4.1 and restarted. the problem solved.
my cuda is 10.0 always.
but the tensorflow page says 
[cuDNN SDK (>= 7.4.1)]
So I installed cuDNN 7.6.2 at first and worked fine before I started to use CNN.

**Comment by waleedt** [comment]
@sidd-hart Installing everything via conda totally worked for me with Tensorflow 2.0.0, Cuda 10.1, and Cudnn 7.6.2. Thank you so much!

**Comment by Frank17** [comment]
Actually, I've tried docker For GPU support, bug it failed. I pulled tensorflow/tensorflow:1.15.0-gpu-py3, and it still has this problem, I think it better to reopen this issue. @kernelizd 

stack trace as below:
```bash
>>> model.fit(x=input_data, y=output_data, epochs=10, batch_size=16)

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 1000 samples
Epoch 1/10
2019-11-19 07:31:08.837737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-19 07:31:09.597102: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-19 07:31:11.658410: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-11-19 07:31:11.674693: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 675, in fit
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 394, in model_iteration
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node replica_0/model/conv2d_2/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node replica_0/model/conv2d_2/Conv2D}}]]
	 [[replica_0/model/dense/Sigmoid/_105]]
0 successful operations.
1 derived errors ignored.
```

**Comment by PrieureDeSion** [comment]
I was facing the same problem with tf2.0

Setting up cudnn [7.6.1] and cudatoolkit [10.1] in my conda env fixed this for me! Thanks @sidd-hart

**Comment by sri9s** [comment]
I am facing the same error with an RTX 2080ti. Here is my output to nviidia-smi:

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 411.31                 Driver Version: 411.31                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce RTX 208... WDDM  | 00000000:0A:00.0  On |                  N/A |
> | 33%   55C    P2    65W / 250W |  10085MiB / 11264MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1608    C+G   Insufficient Permissions                   N/A      |
> |    0      3404    C+G   ...x64__8wekyb3d8bbwe\Microsoft.Photos.exe N/A      |
> |    0      6224    C+G   C:\Windows\explorer.exe                    N/A      |
> |    0      8004    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
> |    0      8860    C+G   ...osoft.LockApp_cw5n1h2txyewy\LockApp.exe N/A      |
> |    0      9324    C+G   ...54.91.0_x64__kzf8qxf38zg5c\SkypeApp.exe N/A      |
> |    0      9356    C+G   ....525.0_x64__8wekyb3d8bbwe\YourPhone.exe N/A      |
> |    0     10464    C+G   ...mmersiveControlPanel\SystemSettings.exe N/A      |
> |    0     10476    C+G   C:\Users\Sri\Anaconda3\pythonw.exe         N/A      |
> |    0     10652    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
> |    0     11748      C   C:\Users\Sri\Anaconda3\pythonw.exe         N/A      |
> |    0     12612    C+G   ...6)\Google\Chrome\Application\chrome.exe N/A      |
> |    0     12968    C+G   ...hell.Experiences.TextInput.InputApp.exe N/A      |
> |    0     13084    C+G   ...9.0_x64__8wekyb3d8bbwe\WinStore.App.exe N/A      |
> |    0     14328    C+G   ...oftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe N/A      |

+-----------------------------------------------------------------------------+

**Comment by Jay4869** [comment]
I am still facing the same problem with tf2.0, cudnn [7.6.4] and cudatoolkit [10.1] in my conda env. @sidd-hart

**Comment by raphaelvorias** [comment]
Got this error with tf2.0, cudnn 7, cuda 10.2 and 10.0.

**Comment by dayangkunurfaizah** [comment]
Hi all. I'm also having the same problem.

I'm using Ubuntu 18.04, cudnn 7.6.4 and using anaconda as well. Anyone can help? 

UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_189/convolution}}]]
	 [[metrics_4/acc/Mean_1/_14657]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_189/convolution}}]]
0 successful operations.
0 derived errors ignored.

**Comment by Jay4869** [comment]
@dayangkunurfaizah checkout colab, it works, but free GPU only can be used up to 12 hours. I still did not find any good solution for this.

**Comment by chauhansaurabhb** [comment]
@dayangkunurfaizah please try with the following settings:
 ``` 
from tensorflow.compat.v1.keras.backend import set_session
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
config.log_device_placement = True  # to log device placement (on which device the operation ran)
sess = tf.compat.v1.Session(config=config)
set_session(sess)
```

**Comment by xintin** [comment]
Hi All,
I am trying to run an example from [https://www.tensorflow.org/xla/tutorials/autoclustering_xla](https://www.tensorflow.org/xla/tutorials/autoclustering_xla) in my local. 

Configuration is: Conda End, TF2.1, cuDNN 7.6, cuda 10.1 and I have tried out various combination from [https://www.tensorflow.org/install/source#tested_build_configurations](https://www.tensorflow.org/install/source#tested_build_configurations) like for TF1.14, TF1.11 but it is throwing the same error as below:


I have followed solutions from [Stack Overflow](https://stackoverflow.com/questions/50622525/which-tensorflow-and-cuda-version-combinations-are-compatible); [https://www.tensorflow.org/install/gpu](https://www.tensorflow.org/install/gpu) and numerous other sources. Can someone please help me with this? I am using GeForce RTX 2080.


![image](https://user-images.githubusercontent.com/48321602/74702298-96520e80-51d7-11ea-89b7-43acabff54e7.png)

**Comment by jude90** [comment]
check you GPU resources usage by run command `nvidia-smi` . The issue  will occur when the Memory-Usage is overwhelming

**Comment by piaobuliao** [comment]
try:
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

ref
https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in

**Comment by OverlordDen** [comment]
> try:
> os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
> 
> ref
> https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in

Thank u very mutch

**Comment by yzcjtr** [comment]
Thank you @piaobuliao . You saved my day!

**Comment by Aakash7khadka** [comment]
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
  except RuntimeError as e:
    print(e)
#Just paste these lines to solve the problem

**Comment by ofshellohicy** [comment]
> https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in

save me time!!!

**Comment by abdulwaheedsoudagar** [comment]
Was facing the same issue, I think GPU is not able to load all the data at once.
I resolved it by reducing the batch size.

**Comment by Priyanshu-server** [comment]
GUYS, I was facing the same issue and found the solution..
you all must have copy and pasted the address of your cudnn folders in the environment variable, now delete them and copy and paste all the files in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\"your version" and then in respected folders like bin files in bin folder and lib file in lib folder and in end the include file in include folder and try again YOU WILL NOT GET ERROR !!
