### ISSUE TITLE
tf-nightly-gpu 1.14.1 failed to get device attribute 13 for device 0: CUDA_ERROR_UNKNOWN: unknown error

### ISSUE THREAD

**Issue by FiveSpeedFrog** [tensorflow/tensorflow#28582]
My Python version is 3.6.8, the operating system is Windows 10, the CUDA version is cuda_10.0.130,the cudnn version is cudnn-10.0-windows10-x64-v7.5.1.10, the GPU is Nvidia GTX965M, and the tf-nightly-gpu-1.14.1is installed.
When I run  "import tensorflow as tf"
there is no problem.
When I run  "python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"

An error was reported：
2019-05-10 12:33:26.728437: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: failed to get device attribute 13 for device 0: CUDA_ERROR_UNKNOWN: unknown error

How to solve this problem？Thanks！！

**Comment by jvishnuvardhan** [comment]
@FiveSpeedFrog Did you install tensorflow through Anaconda or pip? When you install tf-nightly-gpu-1.14.1, eager mode is activated by default. Can you just run the following code and send the error trace? Thanks!

```
import tensorflow as tf
print(tf.reduce_sum(tf.random_normal([1000, 1000])))
```

**Comment by FiveSpeedFrog** [comment]
Hello, I have given up using tf-nightly-gpu-1.14.1.
I am using tensorflow-gpu==1.12.0, and there are no errors.
Still thank you for your willingness to help.
Thank you!

**Comment by bstriner** [comment]
FWIW, I got this error right now on tf-nightly-gpu. Upgraded tf-estimator-nightly and tb-nightly and the problem went away.

**Comment by Rixtrema** [comment]
> FWIW, I got this error right now on tf-nightly-gpu. Upgraded tf-estimator-nightly and tb-nightly and the problem went away.

How exactly did you upgrade those? I am getting the same error with tf 1.15 and CUDA v10. Thanks!

**Comment by Yuki-Nagato** [comment]
I run into this error with tensorflow 2.1.0 and CUDA 10. Not always, but most of the times.

**Comment by ShixiangWang** [comment]
Same issue using 2.1.0

**Comment by jvishnuvardhan** [comment]
@Yuki-Nagato Can you please open a new issue with full error trace so that community will get benefited. Also, when you open new issue, please fill the issue template to describe details of your system. thanks!

**Comment by jvishnuvardhan** [comment]
@ShixiangWang Can you please open a new issue with full error trace so that community will get benefited. Also, when you open new issue, please fill the issue template to describe details of your system. thanks!

**Comment by al-farabi12** [comment]
Hi, I have the same problem too. My system is lenovo z500 ideapad on windows 10 with 'GeForce GT 740M' GPU.
when I installed tf 2  with cuda 10.2 and cuDNN 7.6 I was able to run pytorch command torch.cuda.is_available() and get True while tf could not recognize my GPU. 
Then I deleted cuda 10.2 and installed 10.1 and was able to find my GPU. 
However now I face problem of getting the name of gpu with command: tf.test.gpu_device_name()
some times it works and sometimes not.
Also the main problem is that when I want to run model(x_train[:1]) I get error during tf.matmul operation:
the log file give this trace:
InternalError: Blas GEMM launch failed : a.shape=(1, 784), b.shape=(784, 128), m=1, n=128, k=784 [Op:MatMul] in Jupiter notebook inside.
and the Jupyter console gives this error:
coreClock: 1.0325GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 13.41GiB/s
2020-03-13 00:25:01.698025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-03-13 00:25:01.724783: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-03-13 00:25:01.749689: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-03-13 00:25:01.773207: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-03-13 00:25:01.804865: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-03-13 00:25:01.829288: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-03-13 00:25:01.864333: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-03-13 00:25:01.882774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-03-13 00:25:01.898071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GT 740M computeCapability: 3.5
coreClock: 1.0325GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 13.41GiB/s
2020-03-13 00:25:01.928428: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-03-13 00:25:01.945189: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-03-13 00:25:01.961029: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-03-13 00:25:01.976427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-03-13 00:25:01.991357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-03-13 00:25:02.014377: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-03-13 00:25:02.040688: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-03-13 00:25:02.070685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-03-13 00:25:03.699888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-13 00:25:03.718350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2020-03-13 00:25:03.733347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2020-03-13 00:25:03.747231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1408 MB memory) -> physical GPU (device: 0, name: GeForce GT 740M, pci bus id: 0000:01:00.0, compute capability: 3.5)
2020-03-13 00:25:16.059771: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-03-13 00:25:16.082033: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-03-13 00:25:16.108546: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-03-13 00:25:16.130726: W tensorflow/stream_executor/stream.cc:2041] attempting to perform BLAS operation using StreamExecutor without BLAS support
[I 00:25:20.764 NotebookApp] Saving file at /Desktop/2020/tensorflow/Keras/Text Classification.ipynb
[I 00:26:38.414 NotebookApp] Saving file at /Desktop/2020/tensorflow/beginners.ipynb

PS. cuda 10.1 cudnn 7.6.5.32 and nvidia driver 425.31

**Comment by JiraTechGroup** [comment]
Thank you for you solution. it very useful and save my project.
