### ISSUE TITLE
[Train on official Docker image & custom TF build (no AVX)] failed to query event: CUDA_ERROR_LAUNCH_FAILED

### ISSUE THREAD

**Issue by saippuakauppias** [tensorflow/tensorflow#28693]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): used https://github.com/minimaxir/gpt-2-simple for finetuning
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 & Docker
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): custom build TF (without AVX) from https://github.com/yaroslavvb/tensorflow-community-wheels/issues/109
- TensorFlow version (use command below): b'v1.13.1-0-g6612da8' 1.13.1
- Python version: Python 3.5.2
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): Same as docker `tensorflow/tensorflow:latest-gpu-py3` & `tensorflow/tensorflow:devel-gpu-py3` (error reproduce in both)
- CUDA/cuDNN version: 10.0 / 7.4.1.5-1 ( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile )
- GPU model and memory: GeForce GTX 1080 Ti (11 Gb)

**Describe the current behavior**

> root@63f592f02a0e:/gpt2# python imdb_reviews.py
> ...
> 2019-05-14 07:05:22.669722: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
> 2019-05-14 07:05:22.669812: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
> Aborted (core dumped)

**Describe the expected behavior**
Train process (tested in google colab)...

**Code to reproduce the issue**
```bash
# tested on devel-gpu-py3 (where tf wheel builded) and latest-gpu-py3
docker pull tensorflow/tensorflow:latest-gpu-py3

# deep into docker image
docker run --runtime=nvidia -it  -v ~/projects/gpt2-simple:/gpt2 tensorflow/tensorflow:latest-gpu-py3 bash
```

In Docker:
```bash
pip uninstall tensorflow-gpu

cd /gpt2
# from https://github.com/yaroslavvb/tensorflow-community-wheels/issues/109
pip install tensorflow-1.13.1-cp35-cp35m-linux_x86_64.whl

# install gpt2-simple
pip install gpt_2_simple


# from https://gist.github.com/saippuakauppias/4f41ce1072a04588a2bab7dae00f9bb7
python imdb_reviews.py
```

**Other info / logs**
1. [tf_env.txt](https://github.com/tensorflow/tensorflow/files/3176534/tf_env.txt) attached.
2. Its error looks like https://github.com/tensorflow/tensorflow/issues/22477 but I dont understand where solution in that issue.
3. docker run without `-u $(id -u):$(id -g)` because with this I cant uninstall tensorflow:

<details>
  <summary>Example</summary>

```
docker run --runtime=nvidia -u $(id -u):$(id -g) -v ~/projects/gpt2-simple:/gpt2 -it tensorflow/tensorflow:latest-gpu-py3 bash

You are running this container as user with ID 1000 and group 1000,
which should map to the ID and group for your user on the Docker host. Great!

tf-docker / > pip uninstall tensorflow-gpu
WARNING: The directory '/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling tensorflow-gpu-1.13.1:
  Would remove:
    /usr/local/bin/freeze_graph
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.5/dist-packages/tensorflow/*
    /usr/local/lib/python3.5/dist-packages/tensorflow_gpu-1.13.1.dist-info/*
Proceed (y/n)? y
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/freeze_graph' -> '/tmp/pip-uninstall-n9t_qerr/freeze_graph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/uninstall.py", line 75, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py", line 825, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_uninstall.py", line 388, in remove
    moved.stash(path)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_uninstall.py", line 277, in stash
    renames(path, new_path)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/misc.py", line 305, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.5/shutil.py", line 553, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/freeze_graph'
```
</details>

4. Tensorflow debugger with mnist works fine and use GPU (I see it in nvidia-smi).
<details>
  <summary>Log</summary>

```
root@4697d32838f4:/gpt2# python -m tensorflow.python.debug.examples.debug_mnist
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/debug/examples/debug_mnist.py:46: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/mnist_data/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/mnist_data/train-labels-idx1-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting /tmp/mnist_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/mnist_data/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
2019-05-14 17:07:28.376774: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2800000000 Hz
2019-05-14 17:07:28.378926: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x6115c40 executing computations on platform Host. Devices:
2019-05-14 17:07:28.378987: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-14 17:07:28.598760: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-14 17:07:28.601785: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x61c1dd0 executing computations on platform CUDA. Devices:
2019-05-14 17:07:28.601829: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-05-14 17:07:28.602453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:0b:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-05-14 17:07:28.602502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-14 17:07:28.605463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-14 17:07:28.605502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-05-14 17:07:28.605525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-05-14 17:07:28.605978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10470 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:0b:00.0, compute capability: 6.1)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-14 17:07:29.756412: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
Accuracy at step 0: 0.1094
Accuracy at step 1: 0.098
Accuracy at step 2: 0.098
Accuracy at step 3: 0.098
Accuracy at step 4: 0.098
Accuracy at step 5: 0.098
Accuracy at step 6: 0.098
Accuracy at step 7: 0.098
Accuracy at step 8: 0.098
Accuracy at step 9: 0.098
```
</details>

**Comment by saippuakauppias** [comment]
I also builded tensorflow v1.12.2 and v.1.11.0 (CUDA 9 / cuDNN 7 / Bazel 0.15.0) from old official dockerfile ( https://github.com/tensorflow/tensorflow/blob/v1.12.2/tensorflow/tools/dockerfiles/dockerfiles/nvidia.Dockerfile + some things from dockerfile v1.13.1) and I get same results:
```
root@fe4fdf4cda67:/my-devel/gpt2-simple# python imdb_reviews.py
Loading checkpoint models/345M/model.ckpt
2019-05-15 07:00:34.445685: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-05-15 07:00:34.445688: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:706] failed to record completion event; therefore, failed to create inter-stream dependency
2019-05-15 07:00:34.445785: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
2019-05-15 07:00:34.445793: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:706] failed to record completion event; therefore, failed to create inter-stream dependency
Aborted (core dumped)
```

Maybe problem in my Ubuntu? How to find the problem?

**Comment by gadagashwini** [comment]
@saippuakauppias Make sure that LD_LIBRARY_PATH is set up correctly. Thanks!

**Comment by saippuakauppias** [comment]
@gadagashwini, what is the correct path to be?

I check LD_LIBRARY_PATH in docker image `tensorflow/tensorflow:1.13.1-gpu-py3`:
```
root@c119f9a4779c:/gpt2# echo $LD_LIBRARY_PATH 
/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

And with this env I get same error.

I changed env to:
```
/usr/local/cuda-10.0/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

And again get error in start post...

I checked again `tf_env_collect.sh` and get same results (as in first post in attachment).

**Comment by saippuakauppias** [comment]
@ymodak , @gadagashwini any suggestions for me?
Please...

**Comment by gadagashwini** [comment]
@saippuakauppias Please follow these steps to install Tensorflow-gpu using docker
$sudo docker pull tensorflow/tensorflow:latest-gpu
$sudo docker run -it tensorflow/tensorflow:latest-gpu
$#python
>>import tensorflow  

Please let us know how it progresses. Thanks!

**Comment by saippuakauppias** [comment]
``` bash
$ sudo docker run -it tensorflow/tensorflow:latest-gpu
$ # python
```

```
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

and:
``` bash
$ sudo docker run --runtime=nvidia -it tensorflow/tensorflow:latest-gpu
$ # python
```

```
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2019-05-31 18:24:40.299660: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted (core dumped)

```

**Comment by ymodak** [comment]
Did you install nvidia-docker(https://www.tensorflow.org/install/docker#tensorflow_docker_requirements)?

**Comment by saippuakauppias** [comment]
Yes, of course.

**Comment by angersson** [comment]
@saippuakauppias, I'm sorry, but we don't provide support for community-built packages.

IIRC, all of our official packages (and therefore the packages provided in our Docker images) depend on a CPU with AVX instructions to load, which is why your later tests have failed.

**Comment by saippuakauppias** [comment]
Can anyone look at my tf_env.txt and say if everything is normal there? I looked at similar problems with tf_env.txt file and there were radically different files.

I suspect that I have a problem with Cuda, and not with custom build tensorflow.

**Comment by saippuakauppias** [comment]
@angersson @ymodak @gadagashwini can you check my tf_env.txt from start post? Please

**Comment by saippuakauppias** [comment]
Same problem on v1.14.0 :(
```
root@f58a4b0f357f:/gpt2# python imdb_reviews.py
Fetching checkpoint: 1.05Mit [00:00, 574Mit/s]                                                      
Fetching encoder.json: 1.05Mit [00:00, 4.81Mit/s]                                                   
Fetching hparams.json: 1.05Mit [00:00, 777Mit/s]                                                    
Fetching model.ckpt.data-00000-of-00001:  46%|████████▏         | 228M/498M [00:20<00:26, 10.1Mit/s]
Fetching model.ckpt.data-00000-of-00001: 498Mit [00:44, 11.1Mit/s]                                  
Fetching model.ckpt.index: 1.05Mit [00:00, 524Mit/s]                                                
Fetching model.ckpt.meta: 1.05Mit [00:00, 8.16Mit/s]                                                
Fetching vocab.bpe: 1.05Mit [00:00, 6.46Mit/s]                                                      
2019-08-07 20:01:28.881234: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2800000000 Hz
2019-08-07 20:01:28.883414: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x508f1f0 executing computations on platform Host. Devices:
2019-08-07 20:01:28.883468: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-07 20:01:28.887221: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-07 20:01:29.334170: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-07 20:01:29.336751: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x536d0e0 executing computations on platform CUDA. Devices:
2019-08-07 20:01:29.336814: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-08-07 20:01:29.337238: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-07 20:01:29.339789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:0b:00.0
2019-08-07 20:01:29.340142: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-07 20:01:29.342040: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-07 20:01:29.343430: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-07 20:01:29.343813: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-07 20:01:29.345995: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-07 20:01:29.347726: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-07 20:01:29.352638: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-07 20:01:29.352833: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-07 20:01:29.355504: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-07 20:01:29.358011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-07 20:01:29.358084: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-07 20:01:29.361205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-07 20:01:29.361231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-07 20:01:29.361254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-07 20:01:29.361753: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-07 20:01:29.364404: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-07 20:01:29.366944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10470 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:0b:00.0, compute capability: 6.1)

WARNING: Logging before flag parsing goes to stderr.
W0807 20:01:36.900164 139762445911872 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/gpt_2_simple/src/sample.py:17: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Loading checkpoint models/117M/model.ckpt
W0807 20:01:56.259600 139762445911872 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-08-07 20:01:57.971873: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-08-07 20:01:57.971963: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
Aborted (core dumped)

```

**Comment by angersson** [comment]
I am closing this issue, since we don't support non-official packages.

**Comment by saippuakauppias** [comment]
The problem was in the video card. There were memory errors (can be verified through https://github.com/ForkLab/cuda_memtest ).
Solution: replace the video card.

**Comment by patric-r** [comment]
I am facing the same issue (Windows, tensorflow 2.1):
Random `Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure` errors when training LSTM networks, causing the kernel to fail.

When replacing the LSTM layers with GRU layers, everything works like a charm.
OCCT did not reveal any issues. Other stress tests worked perfectly.

Any hints/suggestions?
