### ISSUE TITLE
TensorFlow cannot detect my GPU

### ISSUE THREAD

**Issue by yyyreal** [tensorflow/tensorflow#2882]
I have a Ubuntu 14.04.4 with Titan X, cuda 7.5 and cudnn v4

cuda 7.5 was installed by a run file, just like I used to installed Caffe.
Environment variables have been added to /etc/profile  and ~/.bashrc 
A file named cuda.conf have been added to /etc/ld.so.conf.d/ 

I installed TensorFlow via pip, using the following command:

$ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl

I followed the install instruction carefully, but I still met some issues.

'>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally`

`>>> sess = tf.Session()

E tensorflow/stream_executor/cuda/cuda_driver.cc:481] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:114] retrieving CUDA diagnostic information for host: DeepLearning
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: DeepLearning
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported version is: 352.79
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.79  Wed Jan 13 16:17:53 PST 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported version is: 352.79
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:226] kernel version seems to match DSO: 352.79
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.`

It seems that TensorFlow cannot find my GPU.
I have no idea why these issues occur.
Please help, thanks

**Comment by zheng-xq** [comment]
Could you run "nvidia-smi" and report back what GPU is available? 

TensorFlow successfully load alll the Cuda libraries. But failed to find any GPU. We need to make sure GPUs are actually visible there.

**Comment by yyyreal** [comment]
@zheng-xq Here is my report
`+------------------------------------------------------+                       
| NVIDIA-SMI 352.79     Driver Version: 352.79         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:01:00.0      On |                  N/A |
| 22%   50C    P8    28W / 250W |    272MiB / 12287MiB |      8%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1161    G   /usr/bin/X                                     155MiB |
|    0      1917    G   compiz                                          90MiB |
+-----------------------------------------------------------------------------+`

**Comment by yyyreal** [comment]
@zheng-xq I managed to solve this issuse.
I happened to run `$sudo ldconfig`,  and the terminal prompted  me that 'libcudnn.so' is not a valid symbolic link, although I followde the install instruction setp by step.
So I deleted and reinstalled Cudnn in my own way.
At this time, tensorflow works correctly.
Thanks all the same.
Have a nice day.


s = tf.Session()
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 12.00GiB
Free memory: 11.67GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)

**Comment by rajiv235** [comment]
@yyyreal I am having the same problem with CUDA 8.0 and cudnn v5. Can you tell a bit more detail on how you were able to solve it? Thanks a ton!

**Comment by yyyreal** [comment]
@rajiv235 I reinstalled my cudnn library and  authorized right permission to .a and .so.5.1.5 files. Please double check you soft links.

**Comment by laventura** [comment]
Hi @yyyreal  -- I'm having the same problems!! It's driving me nuts.

Could you post the correct permissions to the files you listed ?("I reinstalled my cudnn library and authorized right permission to .a and .so.5.1.5 files. ")

Thanks!!

**Comment by laventura** [comment]
I'm on Mac OS X 10.11.6.  Installed CUDA 8, and CUDNN 5.1.  I've followed the install instructions from official TF site. (as of Jan 23, 2017)

**Any idea how to resolve this??**  Any help appreciated!! Thanks!

I'm getting this error: 
**"libcuda reported version is: 310.42.25;  kernel reported version is: Invalid argument: expected %d.%d or %d.%d.%d form for driver version; got ""**

```
>>> sess = tf.Session()
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: Atuls-MBP
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: Atuls-MBP
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 310.42.25
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Invalid argument: expected %d.%d or %d.%d.%d form for driver version; got ""

```

When I run deviceQuery: this is what I get:
```
./deviceQuery 
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 38
-> no CUDA-capable device is detected
Result = FAIL

```

My CUDA Driver: (from Apple > System Preferences > CUDA)
```
CUDA Driver Version: 8.0.57
GPU Driver Version: 10.10.14 310.42.25f02
```

My env vars:
```
echo $CUDA_HOME 
/usr/local/cuda
 py35 ▶ ~ ▶ Developer ❯ … ❯ x86_64 ❯ darwin ❯ release ▶ $ ▶ 
 py35 ▶ ~ ▶ Developer ❯ … ❯ x86_64 ❯ darwin ❯ release ▶ $ ▶ echo $DYLD_LIBRARY_PATH 
:/usr/local/cuda/lib:

uname -a 
Darwin Atuls-MBP 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
```

**Comment by rajiv235** [comment]
@yyyreal @laventura I was able to solve this issue. I did the following:
1. updated the CUDA driver to 367.52
2. Installed CUDA 8.0 toolkit and CUDNN 5.1. Make sure to use -R with cp while copying cudnn library to cuda-8.0\lib64. Need to reboot after this. Check with nvidia-smi if proper drivers are installed and CUDA device is detected.
3. Follow http://expressionflow.com/2016/10/09/installing-tensorflow-on-an-aws-ec2-p2-gpu-instance/ for tensorflow installation. (Note the newer version of tensorflow would require bazel 0.42(not 0.32 as mentioned in the post.) I used installer for bazel which worked fine.

After this TF should work with GPU.

**Comment by laventura** [comment]
@rajiv235 -- Thanks.  Your setup is Ubuntu I think.

I'm on Mac OS X 10.11.6.

I'm trying to see how to upgrade the existing GPU driver (reported from Apple > System Preferences > CUDA)

`GPU Driver Version: 10.10.14 310.42.25f02`

Maybe that's the source of the problem?? I dunno. 😩😩

**Comment by areche** [comment]
@laventura, most likely your GPU is disabled. Install gfxCardStatus, switch to Discrete Only and try again.
