### ISSUE TITLE
Tensorflow import error despite correct installation

### ISSUE THREAD

**Issue by paul2254** [tensorflow/tensorflow#2885]
Hi everyone!

### Environment info
Operating System: Ubuntu 16.04 LTS
Graphics card: GTX 1080 Founders Edition
Installed version of CUDA: 8.0 RC
Installed version of cuDNN: v5 (May 27, 2016), for CUDA 8.0 RC

Output of `ls -l /usr/local/cuda/lib64/libcud*`:
```
-rw-r--r-- 1 root root   560184 juin  15 16:06 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 juin  15 16:06 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 juin  15 16:06 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 juin  15 16:06 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 juin  15 16:06 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 78065952 juin  15 16:10 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 78065952 juin  15 16:10 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 78065952 juin  15 16:10 /usr/local/cuda/lib64/libcudnn.so.5.0.5
-rw-r--r-- 1 root root 68709594 juin  15 16:10 /usr/local/cuda/lib64/libcudnn_static.a
```

Tensorflow installed from source, last commit hash: 7644b3dd001355bf5e3734e541d9955277447601

## Problem
When I open the terminal and type
`$ python`
and then
`>>> import tensorflow`
I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow
```

### Steps to reproduce
Perform 'installing from sources' tutorial step by step https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#installing-from-sources for a GPU-enabled Tensorflow on Linux 64 bits

### What have you tried?
1- Re-installing step by step: no change
2- Typing in terminal `$ bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu` returns the correct output as indicated in the tutorial
3- Typing in terminal `$ bazel test -c opt //tensorflow/python:graph_util_test --test_output=streamed` returns 
```
OK
Converted 1 variables to const ops.
Converted 1 variables to const ops.
Target //tensorflow/python:graph_util_test up-to-date:
  bazel-bin/tensorflow/python/graph_util_test
INFO: Elapsed time: 379.479s, Critical Path: 299.62s
//tensorflow/python:graph_util_test                                      PASSED in 1.1s

Executed 1 out of 1 test: 1 test passes.
```

4- Adding `/home/paul/Downloads/tensorflow` to `PYTHONPATH` and then retry `import tensorflow`. This time I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/Downloads/tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/paul/Downloads/tensorflow/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow
```

I don't know what else to do to make this work. Would you have an idea?

Thanks a lot in advance,
Paul

**Comment by mrry** [comment]
Did you follow the instructions in [Create the pip package and install](https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#create-the-pip-package-and-install)? This step is necessary for your default Python installation to be able to `import tensorflow`.

**Comment by paul2254** [comment]
Thank you Derek for your message. It was precisely because of that. Now I feel bad. Next time I'll be more careful not to skip a part of the tutorial. 
Now everything works fine, thanks to you!

**Comment by mrry** [comment]
That's no problem - I'm glad it's working, and don't feel bad!

**Comment by vb2408** [comment]
Hi guys, i am facing the same issue but in windows? Please help me to solve

**Comment by wizardboy2010** [comment]
im using ubuntu i followed the tflow doc and im still facing the same problem

**Comment by jvdsidq** [comment]
How can I install Keras after installing theano? I tried to install keras but after complitation when I am trying to import keras it shows me error: No module name tensorflow.
I also changed the default backend from tensorflow to theano but still I am facing the same problem. Could you people please help me to fix it. I am working on Jetson TK1 Embedded Board and the board has some limitations of tensorflow.

**Comment by andrescerv** [comment]
> Did you follow the instructions in [Create the pip package and install](https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#create-the-pip-package-and-install)? This step is necessary for your default Python installation to be able to `import tensorflow`.

the link is deprecated... 404 not found
