### ISSUE TITLE
Tensorflow Session hangs when tf.Session() is created

### ISSUE THREAD

**Issue by ashwin1992** [tensorflow/tensorflow#2890]
### Environment info
Operating System:
 Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(
CUDA =7.5 cuDNN=4 

ashwin@smile-titan:~$ ls -l /usr/local/cuda-7.5/lib64/libcud*
-rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 61453024 Apr 20 17:27 /usr/local/cuda-7.5/lib64/libcudnn.so
-rwxr-xr-x 1 root root 61453024 Apr 20 17:27 /usr/local/cuda-7.5/lib64/libcudnn.so.4
-rwxr-xr-x 1 root root 61453024 Apr 20 17:27 /usr/local/cuda-7.5/lib64/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862 Apr 20 17:27 /usr/local/cuda-7.5/lib64/libcudnn_static.a

If installed from binary pip package, provide:

1. Installed tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl  (gpu support one)
2. Tensorflow version: 0.9.0rc0

### What have you tried?
1. When i do 
    
```
 import  tensorflow as tf 
 sess=tf.Session()
```

 
The program hangs. I am not able to do exit from the program as well. It was working fine 2 weeks before. I don't know whats wrong with this.

**Comment by aselle** [comment]
We have no released the non-release candidate version. Could you try that version and verify the problem has not been resolved. Also could you include the results of running

The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

**Comment by zhaolili** [comment]
I am facing the same problem, i am using Ubuntu 14.04 cuda 7.5

**Comment by aselle** [comment]
@ashwin1992 did you try  the new release 0.9.0  (rather than the RC)?
@zhaolili  did release 0.9.0 (rather than the RC) work?

**Comment by zhaolili** [comment]
yes, I was using version 0.9.0

**Comment by zhaolili** [comment]
BTW, I finally solved this problem by re-installing correct GPU device driver for Ubuntu 14.04.
My Ubuntu version is 14.04, but I mistakely installed device driver for Ubuntu 15.x. So everytime it hangs on starting tensorflow Session.

**Comment by vrv** [comment]
Nice find @zhaolili -- I'm tempted to close this bug since it's not TensorFlow-specific, it seems.

(It would be good to know if TensorFlow is somehow hitting unique bugs in the driver that others aren't, so if anyone wants to validate that other GPU software works fine before trying to update to the correct device driver, that would be useful debugging info for the future).
