### ISSUE TITLE
Importing Gtk before tensorflow causes crash

### ISSUE THREAD

**Issue by kalleknast** [tensorflow/tensorflow#2903]
### Environment info

Ubuntu 16.04
`uname -a
Linux p900 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Installed version of CUDA and cuDNN: 
Cuda compilation tools release 7.5, V7.5.17 and CUDNN is v 4

`ls -l /usr/local/cuda-7.5/lib/libcud*
-rw-r--r-- 1 root root 189170 Jun  2 10:18 /usr/local/cuda-7.5/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Jun  2 10:18 /usr/local/cuda-7.5/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Jun  2 10:18 /usr/local/cuda-7.5/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Jun  2 10:18 /usr/local/cuda-7.5/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Jun  2 10:18 /usr/local/cuda-7.5/lib/libcudart_static.a`

pip package installed:
`tensorflow-0.9.0rc0-cp35-cp35m-linux_x86_64.whl`

Output of `python3 -c "import tensorflow; print(tensorflow.__version__)"`:
...
`0.9.0rc0`

Python version:
Python 3.5.1+

Gtk version:
3.0
### Steps to reproduce
1. `import gi`
2. `from gi.repository import Gtk`
3. `import tensorflow`
### What I have tried
1. Removed any Ubuntu protobuf package (Ubuntu package is v 2.6.1):
   `sudo apt purge protobuf*`
2. Upgraded protobuf via pip3:
   `pip3 install --upgrade protobuf`
   ...
   `Requirement already up-to-date: protobuf in /usr/local/lib/python3.5/dist-packages
   Requirement already up-to-date: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf)
   Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages (from protobuf)`
3. Checked protobuf version installed via pip3:
   `ls /usr/local/lib/python3.5/dist-packages/proto*`
   `/usr/local/lib/python3.5/dist-packages/protobuf-3.0.0b2-py2.7-nspkg.pth`
   
   `/usr/local/lib/python3.5/dist-packages/protobuf-3.0.0b2.dist-info:`
   `DESCRIPTION.rst  INSTALLER  METADATA  metadata.json  namespace_packages.txt  RECORD  top_level.txt  WHEEL`
### Output after importing tensorflow

`[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.0.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "external/protobuf/src/google/protobuf/any.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.0.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "external/protobuf/src/google/protobuf/any.pb.cc".)
Aborted (core dumped)`
### Additional comments

As before ( #1373) this ONLY occurs when importing Gtk BEFORE tensorflow. The opposite order causes no crash, nor have I experienced any other crashes associated with tensorflow.

Curiously, when using version 0.8 of tensorflow, a very similar crash was caused by the opposite order of import (ie tensorflow before Gtk), but in that case the output was that: `This program requires version 2.6.1 of the Protocol Buffer runtime library, but the installed version is 3.0.0.` That is, the problem seemed to be caused by the reverse relationship between the protobuf versions. However, when upgrading tensorflow, I did not change the protobuf version. It was kept the same throughout.

**Comment by keveman** [comment]
The error message seems to indicate that you need the newer version of the protobuf runtime library, and not the python interface to protobuf that you install via `pip install`. Can you try `aptitude versions libprotobuf` to see what versions of the protobuf runtime library are available for Ubuntu 16.04, and if 3.0.0 is indeed available, install that?

**Comment by kalleknast** [comment]
@keveman: Only libprotobuf 2.6.1-1.3.
But, I will see if I can find some other way to install 3.0.

**Comment by kalleknast** [comment]
Sorry for the delay.
Inspite of doing my best to remove protobuf with apt-get I did still have it installed, and it was version 2.6:
`$ locate libprotobuf`
...
`/usr/lib/x86_64-linux-gnu/libprotobuf-lite.a`
`/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so`
`/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9`
`/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9.0.1`
`/usr/lib/x86_64-linux-gnu/libprotobuf.a`
`/usr/lib/x86_64-linux-gnu/libprotobuf.so`
`/usr/lib/x86_64-linux-gnu/libprotobuf.so.9`
`/usr/lib/x86_64-linux-gnu/libprotobuf.so.9.0.1`
...

Thus, I removed those files, compiled protobuf-3.0.0-beta-3.2 and moved the new files (as above but 10 instead of 9) to `/usr/lib/x86_64-linux-gnu/` so that I now have:
`locate libprotobuf`
...
`/usr/lib/x86_64-linux-gnu/libprotobuf-lite.a`
`/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so`
`/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.10`
`/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.10.0.0`
`/usr/lib/x86_64-linux-gnu/libprotobuf.a`
`/usr/lib/x86_64-linux-gnu/libprotobuf.so`
`/usr/lib/x86_64-linux-gnu/libprotobuf.so.10`
`/usr/lib/x86_64-linux-gnu/libprotobuf.so.10.0.0`
...

However, Gtk still needs `libprotobuf-lite.so.9`, so:

`In [1]: import gi`
 `In [2]: from gi.repository import Gtk`
`** (process:16293): WARNING **: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: libprotobuf-lite.so.9: cannot open shared object file: No such file or directory`
...

I returned the libprotobuf 9 files to `/usr/lib/x86_64-linux-gnu/` and the Gtk import works again, but importing tensorflow afterwards results in a crash. I.e. back to square 0.

However, this is not a particular big problem for me since it works if tensorflow is imported first, and I have removed the dependence on Gtk.

**Comment by jiapei100** [comment]
Exactly the same situation here...

**Comment by ChrisAntaki** [comment]
@jiapei100 Importing `tensorflow` before anything else sometimes resolves this issue

**Comment by andrei-pokrovsky** [comment]
Sometimes it resolves it, sometimes not :)

**Comment by gunan** [comment]
All I can think of is after apt-get purge command you may need to manually remove libprotobuf files under  `/usr/lib/x86_64-linux-gnu/`, if they are still there. Then install the correct protobuf version using `pip` as described in tensorflow.org.

**Comment by drpngx** [comment]
Closing this, since either:

* it's an install issue with inconsistent versions of protobuf
* it's a problem where you are trying to load multiple versions of protobuf in the same process space. You can't do that. You could attempt to use the `multiprocess` library if you are intent on this.

Feel free to reopen if that's not the case or if you want more information.
