### ISSUE TITLE
more cuDNN problems following audio_recognition tutorial

### ISSUE THREAD

**Issue by lovettchris** [tensorflow/tensorflow#29665]
The train.py script ran just fine, so I know my tensorflow-gpu installation is fine, and cuDNN is working.  But the label_wav.py script reports the infamous "Failed to get convolution algorithm. This is probably because cuDNN failed to initialize..."  During this exception the python process has successfully loaded cudnn64_7.dll and _pywrap_tensorflow_internal.pyd with no problem?  So question is, for v1.13.1 of tensorflow-gpu, on CUDA 10.0, what version of cudnn is needed exactly?  Would be nice if the release notes included the cudnn version required.

**System information**
- stock tensorflow example https://www.tensorflow.org/tutorials/sequences/audio_recognition
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, 1809
- TensorFlow installed from (source or binary): pip install tensorflow-gpu
- TensorFlow version (use command below): v1.13.1-0-g6612da8951      
- Python version: 3.6
- CUDA/cuDNN version: 10.0 and cudnn64_7.dll 
- GPU model and memory: NVIDIA 1080 

**Describe the current behavior**
Running the tutorial step fails with the cuDNN error:
```
python tensorflow/examples/speech_commands/label_wav.py --graph=/tmp/my_frozen_graph.pb --labels=/tmp/speech_commands_train/conv_labels.txt --wav=c:\datasets\speech_commands_v01\audio\left\a5d485dc_nohash_0.wav
```

**Describe the expected behavior**
Should work, especially since _pywrap_tensorflow_internal.pyd already successfully loaded into the python process, and so did cudnn64_7.dll

**Code to reproduce the issue**
See your tutorial on audio recognition.

**Other info / logs**
Attached is the full output of the label_wav.py command, including exception details, and a list of all modules loaded into the python process at the time of the failure.
[output.txt](https://github.com/tensorflow/tensorflow/files/3278584/output.txt)

**Comment by gadagashwini** [comment]
@lovettchris Compatible version for tensorflow-gpu 1.13.1 is CUDA 10 and cuDNN 7.4. Let us know if this combination works for you. Thanks!

**Comment by lovettchris** [comment]
Thanks, I installed "[Download cuDNN v7.4.2 (Dec 14, 2018), for CUDA 10.0](https://developer.nvidia.com/rdp/cudnn-archive#a-collapse742-10)" from the cuDNN archive, now it works properly.  Can you add this version info to the release notes in the future?

**Comment by gadagashwini** [comment]
@lovettchris Sure, Glad it worked. Will close this issue. Thanks!
