### ISSUE TITLE
restore() model with absolute and relative path

### ISSUE THREAD

**Issue by dsindex** [tensorflow/tensorflow#2973]
### Comment

restore succeeded with relative path(script directory), but failed with absolute path.
### Environment info

Operating System: 

Ubunto 14.04.1

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
22:16 $ ls -al /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   322936  8월 16  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16  8월 16  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19  8월 16  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336  8월 16  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192  8월 16  2015 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 61453024  5월 26 09:37 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 61453024  5월 26 09:37 /usr/local/cuda/lib64/libcudnn.so.4
-rwxr-xr-x 1 root root 61453024  5월 26 09:37 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862  5월 26 09:37 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:
1. Which pip package you installed.
   tensorflow-0.8.0    
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.8.0
```
### Steps to reproduce
1. train

```
https://github.com/tensorflow/tensorflow/blob/de1334da2c6e074c427d283898450de6e50a605d/tensorflow/models/embedding/word2vec_optimized.py

$ python word2vec_optimized.py --train_data=text8 --eval_data=questions-words.txt --save_path=tmp
```
1. test

```
https://github.com/dsindex/segm-lstm/blob/master/test_word2vec.py

$ python test_word2vec.py --model_path=tmp
...
checkpoint_dir =  tmp
checkpoint_path =  tmp/model.ckpt-2264698
model restored from tmp/model.ckpt-2264698
analogy = moscow
...

$ python test_word2vec.py --model_path=/path/to/segm-lstm/tensorflow/tensorflow/models/embedding/tmp
...
checkpoint_dir =  /path/to/segm-lstm/tensorflow/tensorflow/models/embedding/tmp
checkpoint_path =  model.ckpt-2264698
Traceback (most recent call last):
  File "test_word2vec.py", line 224, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "test_word2vec.py", line 204, in main
    model.saver.restore(session, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1088, in restore
    raise ValueError("Restore called with invalid save path %s" % save_path)
ValueError: Restore called with invalid save path model.ckpt-2264698
```

**Comment by andydavis1** [comment]
Looking through the documentation for saver.restore it looks like the 'save_path' argument requires a path that was previously returned by saver.save() or save.latest_checkpoint(). Did you try passing in the path returned by save.latest_checkpoint()

// In addition to checkpoint files, savers keep a protocol buffer on disk with
//  the list of recent checkpoints. This is used to manage numbered checkpoint
//  files and by `latest_checkpoint()`, which makes it easy to discover the path
//  to the most recent checkpoint. That protocol buffer is stored in a file named
//   'checkpoint' next to the checkpoint files.

**Comment by dsindex** [comment]
@andydavis1 

i tried tf.train.latest_checkpoint(). but it returned `None`

```shell

full_path = tf.train.latest_checkpoint(checkpoint_dir)
print("full_path = %s" % full_path)

$ python test_word2vec.py --model_path=/path/to/segm-lstm/tensorflow/tensorflow/models/embedding/tmp
...
full_path = None
checkpoint_dir = /path/to/segm-lstm/tensorflow/tensorflow/models/embedding/aaa
checkpoint_path = model.ckpt-20879
...
```

interestingly, the reverse case works. 

```shell
$ python test_word2vec.py --model_path=/path/to/segm-lstm/tensorflow/tensorflow/models/embedding/tmp

$ python test_word2vec.py --model_path=tmp
```

**Comment by aselle** [comment]
Since tf.train is in heavy development, moving to the new version 0.9.0 might help. Also 0.10.0 might also help which is coming soon. We are unlikely to dig into this deeply with an older version. Please try with the newest release. @martinwicke can correct me if I am wrong.

**Comment by martinwicke** [comment]
That is somewhat mysterious. Maybe there is a bug in how checkpoint paths are handled. The checkpoint logic is fairly old, but not deprecated, and ought to work.

**Comment by martinwicke** [comment]
For now, please use an absolute path for training as a workaround.

**Comment by concretevitamin** [comment]
Closing due to inactivity. Please comment with new information and I will reopen.

**Comment by martinwicke** [comment]
That was a little harsh -- however, it would be good to know if this is still an issue in 0.9. I think it probably is.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by jared-mess** [comment]
I can confirm this is still an issue with `'0.10.0rc0'`
I was using `os.path.join(os.getcwd(), "checkpoints")` in my code to save and restore, and we ran into problems. Specifically restoring the checkpoint on another machine fails because it's looking for an absolute path on my machine.
```
    checkpoint = tf.train.latest_checkpoint(checkpoint_dir)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1157, in latest_checkpoint
    if file_io.get_matching_files(ckpt.model_checkpoint_path):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/lib/io/file_io.py", line 52, in get_matching_files
    return pywrap_tensorflow.GetMatchingFiles(compat.as_bytes(filename), status)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.NotFoundError: /Users/Jared/Documents/MyProject/checkpoints
```
We tried loading a relative path, but that only worked AFTER I re-trained it with relative path.
@martinwicke's workaround works (train and restore with the same path)

**Comment by gunan** [comment]
I would like to solve this for 0.10. Reopening the issue and assigning to myself.

**Comment by aselle** [comment]
Thanks for letting us know this is still an issue @jared-mess

**Comment by gunan** [comment]
I was not able to reproduce this issue with a small unit test, I will try to manually play around with things and report what I can find

**Comment by rwightman** [comment]
I was going to create a separate issue for this but seems like my issue could be addressed by a fix for this one. I'm having the same issue as @jared-mess. I'm currently training a network on one machine, and want to run validation on another with the train folder mapped over network. Unfortunately the mappings on the machines result in different absolute paths so checkpoint restore fails as in jared's example. 

The latest_checkpoint ('checkpoint') file stores absolute paths when the save path is absolute and relative when the save path is relative as per https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L675

When the path is relative in the above code, it re-writes as relative to the save dir. Why isn't the path always be re-written as relative to the save dir, even for the absolute case? Is there a use case I'm missing where it makes any sense to have the paths saved in 'checkpoint' as absolute? 

If there is a use case for absolute checkpoint paths in the latest_checkpoint file, would it make sense to have a 'force_relative_paths' flag on the saver to force absolute paths to be re-written as relative? 

My current ugly hack for the issue is to read and re-write the 'checkpoint' file with a different script on the training machine and strip out the absolute portion of the paths. This works.

**Comment by jtyberg** [comment]
I'm hitting this issue as well.  My use case is the same as @jared-mess, where I train the model on machine A, download the model directory to a machine B, and try to restore the model from the model directory on B.  I'm on `0.10.0`.

**Comment by aselle** [comment]
@concretevitamin could you take a look.

**Comment by concretevitamin** [comment]
Just to confirm my understanding -- the workflow of "saving on one machine using relative path, moving the ckpt to another machine, restore there" **is** supported, correct?

I tried with this snippet:
```python
  def testSaveRelative(self):
    rel_path = "ckpts/step0"
    os.mkdir(os.path.join(os.getcwd(), "ckpts"))

    with self.test_session() as sess:
      v = tf.Variable(1.0, name="v")
      tf.initialize_all_variables().run()
      saver = tf.train.Saver()
      path = saver.save(sess, rel_path)
    self.assertEqual(rel_path, path)
```
and it passed, generating this `checkpoint` file:
```
model_checkpoint_path: "step0"
all_model_checkpoint_paths: "step0"
```

So this should not be marked as a "bug", and more like a feature request (use relative paths by default).  For this request, I am not the best person to evaluate the consequences (if any) though.

**Comment by jtyberg** [comment]
> (use relative paths by default)

+1

I also hit this when I'm using Tensorflow from within a Docker container.  If my container that trains the model mounts the directory to `/models`, and I have a different container that tries to restore the model, but mounts the directory to `/tf/models`, the second container can't restore it.

**Comment by martinwicke** [comment]
@concretevitamin are you working on this? It seems that the only change needed is in saver to make sure the checkpoint index always contains only relative paths, right?

**Comment by concretevitamin** [comment]
Unfortunately I am currently occupied with some other work, and I don't know the implications (esp. if there are any effects on internal workloads) of just changing the default behavior.  The status quo looks reasonable now, namely users can opt for using relative paths.

**Comment by jtyberg** [comment]
I worked around this by following @concretevitamin's example of using a relative path for the model directory.  I actually change the directory to the model directory and set the model directory to the current directory (relative, of course).

```
os.chdir(model_dir)
model_dir = './'
print("current working directory: %s" % os.getcwd())
print("model directory: %s" % model_dir)
...
m = tf.contrib.learn.LinearClassifier(model_dir=model_dir, feature_columns=wide_columns)
```

It's a little weird to me, but the model is saved without any path, and I'm able to load it when mounting the model directory into containers at different mount points.

**Comment by rwightman** [comment]
I certainly understand the concern of not knowing the implications of changing default behaviour. Perhaps adding an argument to force saving as relative to checkpoint dir would be a reasonable compromise that won't risk breaking existing code?

Using relative paths or changing working directories within the script aren't viable long term workarounds. Anyone who maintains their code and data or output in separate trees (ie /home/blah/code/project_xyz/...  and  /data/models/output/run-123) ... has to use rather ridiculous paths  '../../../../data/models/output/run-123' to get the desired behaviour.

**Comment by drpngx** [comment]
I see. That sounds to me like a good feature to have. Feel free to open a PR.

**Comment by AshishBora** [comment]
I was also facing `Restore called with invalid save path` error. Even after fixing the paths, the error persisted. The solution for me was upgrade to `v0.12.1` from `v0.11.0`

**Comment by ravyg** [comment]
Might be helpful:
Supports:
[GPU support works with Tensorflow r0.12 with Checkpoints](https://github.com/ravyg/tensorflow/commit/2a83490455f0f02ea05fc447551cacea1c1b8cb6)

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
