### ISSUE TITLE
No library found under: /usr/lib64/stubs/libcuda.so

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#29797]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 30
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master 
- Python version: 3.7
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.26.0
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia Quadro 2200M 4G

After problems with manually installed nvidia drivers, I've switched to using the nvidia packages from negativo17 (https://github.com/negativo17/nvidia-driver), and I get the below error when building TF. As per this issue

https://github.com/negativo17/cuda/issues/18

there are no stubs in the packages. Does the build absolutely need the stubs, or is there a workaround (e.g., some local modification I could make to the `bazel` config)?

Many thanks in advance!!

```
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=190
INFO: Reading rc options for 'build' from /home/key/code/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from /home/key/code/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/key/anaconda3/envs/0613/bin/python --action_env PYTHON_LIB_PATH=/home/key/anaconda3/envs/0613/lib/python3.7/site-packages --python_path=/home/key/anaconda3/envs/0613/bin/python --config=xla --action_env CUDA_TOOLKIT_PATH=/usr --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0 --action_env GCC_HOST_COMPILER_PATH=/home/key/MYBUILDS/GCC7/bin/gcc --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:xla in file /home/key/code/tensorflow/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:cuda in file /home/key/code/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/key/code/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file /home/key/code/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file /home/key/code/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/key/code/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at /home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl:1268:18):
 - /home/key/code/tensorflow/tensorflow/workspace.bzl:63:5
 - /home/key/code/tensorflow/WORKSPACE:94:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1033, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 608, in _find_libs
		_find_cuda_lib("cuda", repository_ctx, cpu_value, (cu...), ...)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 589, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s" % (based...))], ...)))
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 566, in find_lib
		auto_configure_fail(("No library found under: " + ",...)))
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: No library found under: /usr/lib64/stubs/libcuda.so
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1033, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 608, in _find_libs
		_find_cuda_lib("cuda", repository_ctx, cpu_value, (cu...), ...)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 589, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s" % (based...))], ...)))
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 566, in find_lib
		auto_configure_fail(("No library found under: " + ",...)))
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: No library found under: /usr/lib64/stubs/libcuda.so
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1033, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 608, in _find_libs
		_find_cuda_lib("cuda", repository_ctx, cpu_value, (cu...), ...)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 589, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s" % (based...))], ...)))
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 566, in find_lib
		auto_configure_fail(("No library found under: " + ",...)))
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: No library found under: /usr/lib64/stubs/libcuda.so

```

**Comment by skeydan** [comment]
Hi, just a quick update.

I've tried setting up a `/usr/lib64/stubs` directory and symlinking `libcuda.so` there, but I can't say if that's sufficient as now the build fails with 

```
ERROR: /home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/external/local_config_cuda/cuda/BUILD:1399:1: Executing genrule @local_config_cuda//cuda:cuda-bin failed (Exit 1)
cp: cannot open '/usr/bin/./sudoedit' for reading: Permission denied
cp: cannot open '/usr/bin/./locate' for reading: Permission denied
cp: cannot open '/usr/bin/./sudo' for reading: Permission denied
cp: cannot open '/usr/bin/./sudoreplay' for reading: Permission denied
cp: cannot open '/usr/bin/./chfn' for reading: Permission denied
cp: cannot open '/usr/bin/./chsh' for reading: Permission denied
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

It's true that these do not have read permissions, as assumed by the `cuda-bin` rule.
I'll try changing permissions (at least temporarily) to see how far that gets me in the build.

In the meantime, I'd be happy about any advice :-)
Thanks!

**Comment by skeydan** [comment]
Hi,

it turned out that my build worked with just the 2 aforementioned changes:

1. symlinking `libcuda.so` (only this single file) into a newly-created `stubs` dir
2. making the above files other-readable

Please feel free to close the issue! I'd be very happy though to learn why the build does not use `libcuda.so` directly, but that `stub`?
Would it make sense for the build config to check for existence of that directory (not necessarily the case on linux)?

Many thanks!

**Comment by gunan** [comment]
it is probably due to negativo drivers, but I am not 100% sure.
It may also be fedora, as we have never experimented with fedora before.
