### ISSUE TITLE
Custom OPS with registering gradient functions error in eager backprop

### ISSUE THREAD

**Issue by MKFMIKU** [tensorflow/tensorflow#31355]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): PIP
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: V10.0.130 / V7.0.5
- GPU model and memory: NVIDIA TITAN Xp

**Describe the current behavior**
If I run the code with directly
```
2019-08-06 11:32:33.687311: E tensorflow/stream_executor/cuda/cuda_driver.cc:1003] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-08-06 11:32:33.687356: E tensorflow/stream_executor/gpu/gpu_timer.cc:78] Invalid argument: error recording CUDA event on stream 0x7fce8a062590: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-08-06 11:32:33.687558: F ./tensorflow/core/kernels/reduction_gpu_kernels.cu.h:644] Non-OK-status: CudaLaunchKernel( ColumnReduceKernel<IN_T, T*, Op>, grid_dim, block_dim, 0, cu_stream, in, (T*)temp_storage.flat<int8_t>().data(), extent_x, extent_y, op, init) status: Internal: an illegal memory access was encountered
Aborted (core dumped)
```

If I run the code with `cuda-memcheck --binary-patching no python train_simple.py`
```
Traceback (most recent call last):
  File "train_simple.py", line 71, in <module>
    grads = tape.gradient(loss, model.trainable_variables)
  File "/media/disk1/fordata/web_server/kangfu/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 1002, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/media/disk1/fordata/web_server/kangfu/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py", line 76, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/media/disk1/fordata/web_server/kangfu/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 137, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/media/disk4/fordata/web_server/kangfu/HDRNet-TF/hdrnet_ops.py", line 24, in _bilateral_slice_grad
    grid_tensor, guide_tensor, input_tensor, grad, has_offset=has_offset)
  File "<string>", line 355, in bilateral_slice_apply_grad
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Failed launch BilateralSliceApplyGradKernel. [Op:BilateralSliceApplyGrad]
```
**Describe the expected behavior**
The code should calculate gradient properly without error. The custom ops run correctly in inferring mode, however, it throws bug during `model.fit` or below:
```
with tf.GradientTape() as tape:
    output = model(_full_res)
    loss = tf.keras.losses.mse(output, _full_res)
grads = tape.gradient(loss, model.trainable_variables)
```

**Code to reproduce the issue**
I define the custom ops like below:

```
REGISTER_KERNEL_BUILDER(Name("BilateralSlice").Device(DEVICE_GPU), BilateralSliceOp);
REGISTER_KERNEL_BUILDER(Name("BilateralSliceGrad").Device(DEVICE_GPU), BilateralSliceGradOp);
REGISTER_KERNEL_BUILDER(Name("BilateralSliceApply").Device(DEVICE_GPU), BilateralSliceApplyOp);
REGISTER_KERNEL_BUILDER(Name("BilateralSliceApplyGrad").Device(DEVICE_GPU), BilateralSliceApplyGradOp);
```
It seems like the custom ops not work OK in eager mode
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by MKFMIKU** [comment]
@ravikyram I commit the code used to reproduce the error in https://github.com/MKFMIKU/Tensorflow-Bug-Reproduce.

To get the error, you can:
```bash
git clone https://github.com/MKFMIKU/Tensorflow-Bug-Reproduce.git
cd Tensorflow-Bug-Reproduce
make
python run.py
```
then it outputs:
```
2019-08-08 17:50:50.689623: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-08 17:50:51.605504: E tensorflow/stream_executor/cuda/cuda_driver.cc:1003] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-08-08 17:50:51.605560: E tensorflow/stream_executor/gpu/gpu_timer.cc:78] Invalid argument: error recording CUDA event on stream 0x7fe3505d0550: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-08-08 17:50:51.605661: F ./tensorflow/core/kernels/reduction_gpu_kernels.cu.h:605] Non-OK-status: CudaLaunchKernel(ColumnReduceMax16ColumnsKernel<IN_T, T*, Op>, grid_dim, block_dim, 0, cu_stream, in, (T*)temp_storage.flat<int8_t>().data(), extent_x, extent_y, op, init) status: Internal: an illegal memory access was encountered
Aborted (core dumped)
```

**Comment by ravikyram** [comment]
@MKFMIKU 
I am trying to reproduce the issue with your instructions.
I am able to run the below two commands:
git clone https://github.com/MKFMIKU/Tensorflow-Bug-Reproduce.git
cd Tensorflow-Bug-Reproduce
but make command is throwing some error
![image](https://user-images.githubusercontent.com/51902062/62756296-cbe1a680-ba94-11e9-89e4-d83ab28fb658.png)
Thanks!

**Comment by MKFMIKU** [comment]
@ravikyram Seems like you don't have `nvcc` in your environment. The `nvidia-cuda-toolkit` should be installed before run `make`.

**Comment by amahendrakar** [comment]
@MKFMIKU,
Is this still an issue? Could you please upgrade to TensorFlow v2.3 and check if you are still facing the error?

>git clone https://github.com/MKFMIKU/Tensorflow-Bug-Reproduce.git
>cd Tensorflow-Bug-Reproduce
>make

Also while trying to reproduce the issue, on running the `make` step I am facing an error stating `Makefile:28: recipe for target 'build/bilateral_slice.cu.o' failed`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/cf1d67a0b1595ce316946c04e93aa6d0/31355.ipynb#scrollTo=4iyuE954ERri). Thanks!

**Comment by MKFMIKU** [comment]
It is solved after upgrade

**Comment by eduardinjo** [comment]
@MKFMIKU I encounter the same problem and it fails on tf2. How did you solve it?
