### ISSUE TITLE
libnvinfer-dev : Depends: libnvinfer5 (= 5.0.2-1+cuda10.0) but 5.1.5-1+cuda10.1 is to be installed

### ISSUE THREAD

**Issue by movie3105** [tensorflow/tensorflow#31417]
can someone tell me how to change the libvnfer to the right one ?
libnvinfer-dev : Depends: libnvinfer5 (= 5.0.2-1+cuda10.0) but 5.1.5-1+cuda10.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by movie3105** [comment]
i use ubuntu 16.04
and the way i install it : https://www.tensorflow.org/install/gpu
i follow the Ubuntu 16.04 (CUDA 10) installation

**Comment by gadagashwini** [comment]
@movie3105 Can you please elaborate the issue with context and commands or code if any. Thanks!

**Comment by dc3671** [comment]
@movie3105 
```
sudo apt-get install -y --no-install-recommends libnvinfer5=5.0.2-1+cuda10.0 libnvinfer-dev=5.0.2-1+cuda10.0
```

**Comment by gadagashwini** [comment]
@yifeif Can you please take a look? Thanks!

**Comment by yifeif** [comment]
I believe this has been resolved. Thanks @dc3671!

**Comment by dg-mp** [comment]
I have the same issue, but for version6 (6.0.1.5) with CUDA 10.1 on Ubuntu18.04 x86_64:
sudo dpkg -i nv-tensorrt-repo-ubuntu1804-cuda10.1-trt6.0.1.5-ga-20190913_1-1_amd64.deb
sudo apt-key add /var/nv-tensorrt-repo-cuda10.1-trt6.0.1.5-ga-20190913/7fa2af80.pub
sudo apt-get update
sudo apt-get install tensorrt

The final line returns the following:

The following packages have unmet dependencies:
 tensorrt : Depends: libnvinfer6 (= 6.0.1-1+cuda10.1) but 6.0.1-1+cuda10.2 is to be installed
            Depends: libnvinfer-plugin6 (= 6.0.1-1+cuda10.1) but 6.0.1-1+cuda10.2 is to be installed
            Depends: libnvparsers6 (= 6.0.1-1+cuda10.1) but 6.0.1-1+cuda10.2 is to be installed
            Depends: libnvonnxparsers6 (= 6.0.1-1+cuda10.1) but 6.0.1-1+cuda10.2 is to be installed
            Depends: libnvinfer-bin (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvinfer-dev (= 6.0.1-1+cuda10.1) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvinfer-plugin-dev (= 6.0.1-1+cuda10.1) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvparsers-dev (= 6.0.1-1+cuda10.1) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvonnxparsers-dev (= 6.0.1-1+cuda10.1) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvinfer-samples (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvinfer-doc (= 6.0.1-1+cuda10.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I presume it is unrelated, but, the sudo apt-get update call returns a bunch of warnings similar to the following (where my .../sources.list.d/cuda.list file contains only the text "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /"):

"W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/cuda.list:1
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/cuda.list:1"

Etc., etc.

Note that, unlike the case above, this version (libnvinfer 6.0.1-1+cuda10.1) is still posted at the repository, so that doesn't seem to be the issue.

**Comment by tomriddle54** [comment]
Don't know why every one is getting this error 
```tensorrt : Depends: libnvinfer7 (= 7.0.0-1+cuda10.0) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvinfer-plugin7 (= 7.0.0-1+cuda10.0) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvparsers7 (= 7.0.0-1+cuda10.0) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvonnxparsers7 (= 7.0.0-1+cuda10.0) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvinfer-bin (= 7.0.0-1+cuda10.0) but it is not going to be installed
            Depends: libnvinfer-dev (= 7.0.0-1+cuda10.0) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvinfer-plugin-dev (= 7.0.0-1+cuda10.0) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvparsers-dev (= 7.0.0-1+cuda10.0) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvonnxparsers-dev (= 7.0.0-1+cuda10.0) but 7.0.0-1+cuda10.2 is to be installed
            Depends: libnvinfer-samples (= 7.0.0-1+cuda10.0) but it is not going to be installed
            Depends: libnvinfer-doc (= 7.0.0-1+cuda10.0) but it is not going to be installed
``` 
I solved it by this command 
`sudo apt-get install -y --no-install-recommends libnvinfer7=7.0.0-1+cuda10.0 libnvinfer-dev=7.0.0-1+cuda10.0
`
 but got another error `/usr/bin/ld: cannot find -lnvcaffe_parser`

for your's try this one `sudo apt-get install -y --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1 libnvinfer-dev=6.0.1-1+cuda10.1`
