### ISSUE TITLE
Configure script attemps to seek for libcudart.so in wrong path

### ISSUE THREAD

**Issue by milohoffman** [tensorflow/tensorflow#3184]
Hi! I'm trying to configure build for cuda utilization. When I answer the question 

> Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/lib/x86_64-linux-gnu/libcudart.so

i get the following error:

> Invalid path to CUDA  toolkit. /usr/lib/x86_64-linux-gnu/**lib64**/libcudart.so cannot be found

but i have cuda installed in:

> $ ll /usr/lib/x86_64-linux-gnu/libcudart.so
lrwxrwxrwx 1 root root 16 мар 30 15:25 /usr/lib/x86_64-linux-gnu/libcudart.so -> libcudart.so.7.5

This happens because of the following code in `configure` file:
```
  if [ "$OSNAME" == "Linux" ]; then
    CUDA_RT_LIB_PATH="lib64/libcudart.so${TF_CUDA_EXT}"

```

Why it tries to look for cuda installation in `lib64` subdirectory? I think make me to symlink /usr/lib/**lib64**/ -> /usr/lib/**x86_64-linux-gnu**/ is cruel.

Forgot. My system is Ubuntu 16.04:

> $ uname -a
> Linux user-desktop 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aselle** [comment]
Most users install CUDA using the .sh run scripts NVIDIA provides. I assume you used a different installation method. We can't support every permutation of install methods for NVIDIA drivers, so we have chosen the way most people tend to do it, because usually people directly download from NVIDIA to get the most up to date driver. Hopefully doing such will solve your problem without the need to symlink.

**Comment by milohoffman** [comment]
Yes, I think you're right. Preferred installation method solved my problem. My bad, thank you. I think you may close the issue...
