### ISSUE TITLE
"Retval[0] does not have value" error when using conditions and control dependencies

### ISSUE THREAD

**Issue by MaximusMutschler** [tensorflow/tensorflow#32106]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6.8
- CUDA/cuDNN version: 9.0.252
- GPU model and memory: GeForce GTX 1050 4031MB

**Describe the current behavior**
 Error that gives us no information what is actually wrong:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
**Describe the expected behavior**
 no error and the result should be 4

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Note: you might have to run the code multiple times. The error appeared in 3 out of 5 runs.
```python
import tensorflow as tf

x= tf.constant(2.0)
bool_var = tf.get_variable("bool_var", initializer=tf.constant(True), trainable=False,
                                             dtype=tf.bool)
x_copy_var = tf.get_variable("x_copy_var", x.shape, initializer=tf.zeros_initializer(),trainable=False)

def true_func():
    assign_op = x_copy_var.assign(x)
    set_bool_var_false = bool_var.assign(False)
    with tf.control_dependencies([assign_op,set_bool_var_false]):
        return x*x_copy_var

cond = tf.cond(bool_var,true_func,lambda:x)
cond= tf.Print(cond,[cond])

sess= tf.Session()
sess.run(tf.global_variables_initializer())
sess.run([cond])
```

**Other info / logs**

Full error log:

/***/***/***/py36Env/bin/python3.6 /snap/pycharm-community/147/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 40811 --file /home/***/PycharmProjects/***/test/cond_test.py
pydev debugger: process 7200 is connecting

Connected to pydev debugger (build 192.6262.63)
WARNING:tensorflow:From /home/***/***/***/test/cond_test.py:16: Print (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2018-08-20.
Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`

2019-08-30 10:08:02.921500: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-30 10:08:02.928495: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2019-08-30 10:08:02.928527: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: u-172-c053
2019-08-30 10:08:02.928533: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: u-172-c053
2019-08-30 10:08:02.928562: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 390.87.0
2019-08-30 10:08:02.928584: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 390.87.0
2019-08-30 10:08:02.928589: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 390.87.0
Traceback (most recent call last):
  File "/localhome/***/virtualEnvironments/py36Env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/localhome/***/virtualEnvironments/py36Env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/localhome/***/virtualEnvironments/py36Env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/pycharm-community/147/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/snap/pycharm-community/147/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/147/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/snap/pycharm-community/147/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/147/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/***/***/***/test/cond_test.py", line 21, in <module>
    sess.run([cond])
  File "/localhome/***/virtualEnvironments/py36Env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/localhome/***/virtualEnvironments/py36Env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/localhome/***/virtualEnvironments/py36Env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/localhome/***/virtualEnvironments/py36Env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

**Comment by ppwwyyxx** [comment]
A few of such issues were fixed in COND_V2. Could you try with `export TF_ENABLE_COND_V2=1`?

**Comment by oanush** [comment]
@MaximusMutschler,
Can you try solution suggested by @ppwwyyxx. Thanks!

**Comment by MaximusMutschler** [comment]
Yes the solution works. Thanks a lot!

**Comment by oanush** [comment]
Closing since the issue is resolved.Thanks!
