### ISSUE TITLE
Make cuDNN compile-time vs. load-time validation use major version only

### ISSUE THREAD

**Issue by zer0n** [tensorflow/tensorflow#3225]
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
```
➜ ~ ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   322936 Feb 27 11:34 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Feb 27 11:34 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Feb 27 11:34 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Feb 27 11:34 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Feb 27 11:34 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Jul  7 01:57 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 root root       17 Jul  7 01:57 /usr/local/cuda/lib64/libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxr-xr-x 1 root root 61453024 Jul  7 01:57 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862 Jul  7 01:57 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. Pip package: `https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
➜ ~ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.9.0
```

### Steps to reproduce
1. `git clone https://github.com/soumith/convnet-benchmarks`
2. Go to `tensorflow` and run `python benchmark_googlenet.py`

### Logs
```
➜ tensorflow git:(master) python benchmark_googlenet.py
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:8a:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:8a:00.0)
E tensorflow/stream_executor/cuda/cuda_dnn.cc:346] Loaded cudnn library: 4004 but source was compiled against 4007.  If using a binary install, upgrade your cudnn library to match.  If building from sources, make sure the library loaded matches the version you specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:459] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)
[1]    18918 abort (core dumped)  python benchmark_googlenet.py
```

Notice the line: **Loaded cudnn library: 4004 but source was compiled against 4007**.  If using a binary install, upgrade your cudnn library to match.  If building from sources, make sure the library loaded matches the version you specified during compile configuration.

**Comment by zer0n** [comment]
The benchmark script ran fine with TF 0.8.

**Comment by aselle** [comment]
Did doing what the message say, work? I.e. you are using a binary pip so try upgrading cudnn?

**Comment by zer0n** [comment]
As you can see from the `ls -l /usr/local/cuda/lib64/libcud*`, my cuDNN is already 4.0.7. I cannot upgrade cuDNN further.

**Comment by aselle** [comment]
You probably have both an old and new version of cudnn on your machine and your search path LD_LIBRARY_PATH is finding the old one. Read the manual on LD_DEBUG so you can trace what libraries are loading (use grep with it)

**Comment by vrv** [comment]
What @aselle suggests is a good short-term diagnosis solution.

We can probably start thinking about making this check a little less restrictive by comparing only the major version number.  I believe NVidia has been providing ABI compatibility within major versions lately.  I'll try to get to this some time.

**Comment by zer0n** [comment]
@aselle Thanks. There was indeed a hidden cudnn 4.0.4.

**Comment by vrv** [comment]
Reopening to keep the feature request open

**Comment by oakkas** [comment]
I am having same issue: I am having same issue and tried everything.
E tensorflow/stream_executor/cuda/cuda_dnn.cc:347] Loaded runtime CuDNN library: 5004 (compatibility version 5000) but source was compiled with 5103 (compatibility version 5100). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:457] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
Aborted (core dumped)

I tried uninstall and install several times with cuda 7.5 and 8. I tried cudann 4, 5, 5.1. NOthing worked. 
What else I can do?

**Comment by drorhilman** [comment]
I am having exactly the same problem.

```
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y
> I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:06:00.0)
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K80, pci bus id: 0000:07:00.0)
> E tensorflow/stream_executor/cuda/cuda_dnn.cc:347] Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5103 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
> 
```

**Comment by dancsalo** [comment]
Hi @drorhilman I am running Ubuntu 14.04, Cuda 8.0 and received your same error with cuDNN 5.0. I upgraded to cuDNN 5.1 and the error went away.
