### ISSUE TITLE
tensorflow 2rc1 Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by alon1samuel** [tensorflow/tensorflow#32548]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): - Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2rc1
- Python version: 3.6.7
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce RTX 2070 - 8GRAM

**Describe the current behavior**
My program crashes when I try to execute it.

**Describe the expected behavior**
I want to fit my model to the dataset. 

**Code to reproduce the issue**

```
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import tensorflow as tf

DATA_URL = 'https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'

path = tf.keras.utils.get_file('mnist.npz', DATA_URL)
with np.load(path) as data:
  train_examples = data['x_train']
  train_labels = data['y_train']
  test_examples = data['x_test']
  test_labels = data['y_test']


train_examples = train_examples.reshape((-1, 28, 28, 1))
train_dataset = tf.data.Dataset.from_tensor_slices((train_examples, train_labels))
test_dataset = tf.data.Dataset.from_tensor_slices((test_examples, test_labels))
BATCH_SIZE = 64
SHUFFLE_BUFFER_SIZE = 100

train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)

model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(tf.keras.layers.MaxPooling2D((2, 2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))


model.compile(optimizer=tf.keras.optimizers.RMSprop(),
                loss=tf.keras.losses.SparseCategoricalCrossentropy(),
                metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

model.fit(train_dataset, epochs=10)
```

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

I've tried to do use these options which didn't help:

```
# 1st option
physical_devices = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```

```
# 2nd option
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)
```

I would be grateful for help

**Comment by babytut** [comment]
You should add something like that

```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
tf.keras.backend.set_session(tf.Session(config=config))
```

**Comment by alon1samuel** [comment]
> You should add something like that
> 
> ```
> config = tf.ConfigProto()
> config.gpu_options.allow_growth = True
> tf.keras.backend.set_session(tf.Session(config=config))
> ```

Hi, 
I tried it but I get an error of - 

`AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'
`

Are you sure it works on tf 2?

**Comment by gadagashwini** [comment]
@alon1samuel, I tried on colab it executed as expected. Please take a look at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/44b8bf34a49d3bf06307449a978053ca/untitled152.ipynb). Thanks!

**Comment by alon1samuel** [comment]
> @alon1samuel, I tried on colab it executed as expected. Please take a look at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/44b8bf34a49d3bf06307449a978053ca/untitled152.ipynb). Thanks!

Hi, 
Thanks for the response and the idea on how to run this. 
I'm afraid my purpose was to run this algorithm locally on my computer. 

Is there a way to add or change code lines in order for the algorithm to run locally? 
Or would you say that in tf2 there's no way for that, currently?

Regards,

**Comment by magomar** [comment]
Have you checked the warnings preceding that error?
I'm having the same issue after upgrading TF2 to the RC (release candidate) version. In my case it seems there is a mismatch between installed and compiled version of CuDNN (7.4.1 vs 7.6), which I'm trying to solve at the moment (without success so far)

**Comment by magomar** [comment]
I'm getting the same error running the RC version in AWS AMI, so this is not just my environment. According to the [TF2 documentation](https://www.tensorflow.org/install/gpu), it should be ok with CuDNN 7.4, right?

**Comment by alon1samuel** [comment]
> Have you checked the warnings preceding that error?
> I'm having the same issue after upgrading TF2 to the RC (release candidate) version. In my case it seems there is a mismatch between installed and compiled version of CuDNN (7.4.1 vs 7.6), which I'm trying to solve at the moment (without success so far)

I'm not getting warnings when I'm running this code...

**Comment by alon1samuel** [comment]
Is there news regarding the bug? @jvishnuvardhan

**Comment by alon1samuel** [comment]
It happens to me also in version 2.0.0 (in the official release)

**Comment by ptklx** [comment]
who solve it  ,it happens tome ,  the tf version 2.0.0,cuda 10.2,cudnn 7.6
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv1/Conv2D (defined at /pt/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_keras_scratch_graph_9659]

**Comment by ptklx** [comment]
config =tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
tf.compat.v1.Session(config=config)

**Comment by jvishnuvardhan** [comment]
@alon1samuel I tested it on colab and I don't see any error. May be this is more related to GPU drivers. Can you check a simple code that runs on GPU or just [`tf.test.is_gpu_available`](https://www.tensorflow.org/api_docs/python/tf/test/is_gpu_available)? I will check it later tomorrow on a GPU at home. Thanks!

**Comment by lgggy** [comment]
Hello. My system info is `tf.__version__=2.0.0, cuda.version=10.0.130, cuDNN.version=7.6.4`. And when I use `tf.keras.layers.Conv2D`, it shows the error "Failed to get convolution algorithm. This is probably because cuDNN failed to initialize.", howerver, it can use `tf.keras.layers.Dense` to train model without creating any problems.
My solution is 
```physical_devices = tf.config.experimental.list_physical_devices('GPU')``` 
```tf.config.experimental.set_memory_growth(physical_devices[0], True) ```
Then it will be good to train with Conv2D.
I want to know why this helps. And I know these instructions are to make GPU apply memory when it need.
Thanks a lot.

**Comment by alon1samuel** [comment]
> Hello. My system info is `tf.__version__=2.0.0, cuda.version=10.0.130, cuDNN.version=7.6.4`. And when I use `tf.keras.layers.Conv2D`, it shows the error "Failed to get convolution algorithm. This is probably because cuDNN failed to initialize.", howerver, it can use `tf.keras.layers.Dense` to train model without creating any problems.
> My solution is
> `physical_devices = tf.config.experimental.list_physical_devices('GPU')`
> `tf.config.experimental.set_memory_growth(physical_devices[0], True) `
> Then it will be good to train with Conv2D.
> I want to know why this helps. And I know these instructions are to make GPU apply memory when it need.
> Thanks a lot.

Thanks for this answer, it helped me know some more about the problem. 
It still doesn't work. but now it also says that my CUDNN-7.4.2 and source was compiled with 7.6.0. 
I've updated my cudnn to 7.6.4 and now it works!!! :) :) :) :+1: :+1: :100: 

Here is the error that was issued for if someone wants to know:


2019-11-03 09:20:32.326324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-03 09:20:32.326347: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-03 09:20:32.326366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-11-03 09:20:32.326385: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-11-03 09:20:32.326403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-11-03 09:20:32.326421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-11-03 09:20:32.326441: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-03 09:20:32.328514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-03 09:20:32.338509: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-03 09:20:32.340039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-03 09:20:32.340055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-11-03 09:20:32.340062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-11-03 09:20:32.346288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6761 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:17:00.0, compute capability: 7.5)
Epoch 1/10
2019-11-03 09:20:45.674047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-03 09:20:46.299255: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-03 09:20:48.026792: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.2 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2019-11-03 09:20:48.028412: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.2 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2019-11-03 09:20:48.029369: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node sequential/conv2d/Conv2D}}]]

**Comment by jvishnuvardhan** [comment]
@alon1samuel Please close the issue if it was already resolved for you. If you have any more concerns, please let us know. Thanks!
