### ISSUE TITLE
out of memory flood on the simplest op

### ISSUE THREAD

**Issue by iperov** [tensorflow/tensorflow#32709]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win7 x64
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0rc1
- Python version: 3.7.4
- CUDA/cuDNN version: 10.0, 3.7.5
- GPU model and memory: GTX 1060, 6GB

**Describe the current behavior**

```
import tensorflow as tf
x = [[2.]]
m = tf.matmul(x, x)
```

results infinite flood:
```
2019-09-21 14:55:58.537800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.540800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.543800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.546800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.549800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.552800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.555800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.566800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.569800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
2019-09-21 14:55:58.572800: I tensorflow/stream_executor/cuda/cuda_driver.cc:830
] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: ou
t of memory
```

**Describe the expected behavior**

expected to work properly

**Code to reproduce the issue**

```
import tensorflow as tf
x = [[2.]]
m = tf.matmul(x, x)
```

**Other logs**

```
2019-09-21 14:58:51.205800: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:44] Successfully opened dynamic library cudart64_100.dll
>>> tf.constant(1)
2019-09-21 14:58:54.148800: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-09-21 14:58:54.220800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
618] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
2019-09-21 14:58:54.226800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
618] Found device 1 with properties:
name: GeForce GT 730 major: 3 minor: 5 memoryClockRate(GHz): 0.9015
pciBusID: 0000:03:00.0
2019-09-21 14:58:54.229800: I tensorflow/stream_executor/platform/default/dlopen
_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-09-21 14:58:54.239800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
731] Ignoring visible gpu device (device: 1, name: GeForce GT 730, pci bus id: 0
000:03:00.0, compute capability: 3.5) with core count: 2. The minimum required c
ount is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROC
ESSOR_COUNT.
2019-09-21 14:58:54.245800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
746] Adding visible gpu devices: 0
2019-09-21 14:58:54.248800: I tensorflow/core/platform/cpu_feature_guard.cc:142]
 Your CPU supports instructions that this TensorFlow binary was not compiled to
use: AVX2
2019-09-21 14:58:54.308800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
618] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
2019-09-21 14:58:54.312800: I tensorflow/stream_executor/platform/default/dlopen
_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-09-21 14:58:54.319800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
746] Adding visible gpu devices: 0
2019-09-21 14:58:55.057800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-21 14:58:55.061800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
165]      0
2019-09-21 14:58:55.064800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
178] 0:   N
2019-09-21 14:58:55.071800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 wit
h 4675 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bu
s id: 0000:01:00.0, compute capability: 6.1)
```

**Comment by oanush** [comment]
@iperov ,
Tried running the code in colab for tf-2.0rc1 did not face any error, please take a look at the [gist](https://colab.sandbox.google.com/gist/oanush/f92701b1542fca43d2d1f66b0f262077/32709.ipynb) of the colab. kindly share us the gist if the issue is replicating.Thanks!

**Comment by iperov** [comment]
@oanush  did you try it with cudnn 7.5.0 ?

I installed 7.4.1 and all is fine.

**Comment by iperov** [comment]
also problem in windows, not in linux colab.

Read System information.

**Comment by mihaimaruseac** [comment]
Are you using the GPU device only for this compute task?

Seems like an issue in your GPU, not in TensorFlow

**Comment by iperov** [comment]
@mihaimaruseac are you troll?

this is simple task to reproduce the bug.

This bug is reproduced only with cudnn 7.5.0 on windows, but 7.4.1 works fine.

**Comment by mihaimaruseac** [comment]
No, not a troll. Please always assume good intent as I was basing my question on https://stackoverflow.com/questions/34514324/error-using-tensorflow-with-gpu/34514932#34514932

That being said, can you also post output of `nvidia-smi`, on both 7.5.0 and 7.4.1, before and after running your script?

**Comment by iperov** [comment]
> nvidia-smi, on both 7.5.0 and 7.4.1

nvidia-smi does not depend on cudnn.
cudnn is only the one dll that loaded by python environment.
I can pass to it any version I want. So 7.5.0 has bug, but 7.4.1 - has not.

**Comment by mihaimaruseac** [comment]
It doesn't depend on cudnn but it also shows the state of the GPU so we can detect if there is a memory leak.

**Comment by iperov** [comment]
I don't know why, but bug is no more reproducable :(

**Comment by mihaimaruseac** [comment]
So it turns out it was the state of your system.

**Comment by iperov** [comment]
or the hidden bug of tf

**Comment by mihaimaruseac** [comment]
Doubtful to be a hidden bug of TF (as it seems to always happen on your issues) but if it reproduces again please post full details and debug how much memory your GPU still has available.
