### ISSUE TITLE
device_lib.list_local_devices() InvalidArgumentError: Invalid device ordinal value (1). Valid range is [0, 0].

### ISSUE THREAD

**Issue by shun-lin** [tensorflow/tensorflow#32793]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): gLinux
- TensorFlow installed from (source or binary): pip3 installed
- TensorFlow version (use command below): 2.0.0-rc1
- Python version: 3.6.2
- CUDA/cuDNN version: 10.0, 7.6.3
- GPU model and memory:

output of ```nvidia-smi``` from the terminal:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.34       Driver Version: 430.34       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P1000        Off  | 00000000:65:00.0  On |                  N/A |
| 37%   52C    P0    N/A /  N/A |   1289MiB /  4037MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN RTX           Off  | 00000000:B3:00.0 Off |                  N/A |
| 41%   29C    P8    14W / 280W |   1155MiB / 24220MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

Snippet of code that cause the problem:
```python
import tensorflow as tf
from tensorflow.python.client import device_lib

device_lib.list_local_devices()
```

error message:
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-2-b6f1169dc7e5> in <module>
     2 from tensorflow.python.client import device_lib
     3 
---> 4 device_lib.list_local_devices()

~/.local/lib/python3.6/site-packages/tensorflow_core/python/client/device_lib.py in list_local_devices(session_config)
     39   return [
     40       _convert(s)
---> 41       for s in pywrap_tensorflow.list_devices(session_config=session_config)
     42   ]

~/.local/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py in list_devices(session_config)
   2247     return ListDevicesWithSessionConfig(session_config.SerializeToString())
   2248   else:
-> 2249     return ListDevices()
   2250 
   2251 

InvalidArgumentError: Invalid device ordinal value (1). Valid range is [0, 0].
	while setting up XLA_GPU_JIT device number 1
```

Potential cause and current workaround:
In the terminal output I notice that because the Quadro P1000  in my workstation only has 5 multiprocessor and so by default tf will not use it (minimum 8), so I added the following line to my ```.bashrc```

```
export TF_MIN_GPU_MULTIPROCESSOR_COUNT=5
```

and run ```source .bashrc``` and it works. Another potential solution if I don't want to set the min GPU Multiprocessor count I can remove the Quadro P1000 from my workstation. I suspect that there is an inconsistency within list_local_devices() that fetch all GPUs in the workstation but didn't update base on min gpu multiprocessor count rule. So I run another experiment to see if I can reproduce the error after setting ```TF_MIN_GPU_MULTIPROCESSOR_COUNT``` to 5

The below code will reproduce the same error:

```python
import tensorflow as tf
from tensorflow.python.client import device_lib

gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
device_lib.list_local_devices()
```
This will produce the same error but if we call ```device_lib.list_local_devices()``` before calling ```tf.config.experimental.set_visible_devices(gpus[0], 'GPU')``` and then we call ```device_lib.list_local_devices()``` again, there is no error. I suspect that maybe setting device to visible may interact weirdly with list_local_devices().

**Comment by ymodak** [comment]
Can you print the output of  ```which nvcc```? This will give you cuda runtime version whereas ```nvidia-smi``` shows latest installed cuda driver version. Both can be different.

**Comment by shun-lin** [comment]
Hi ymodak,

```which nvcc``` gives me the output ``` /usr/local/cuda/bin/nvcc```

and ```nvcc --version``` gives me the following output:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

I hope this helps!

**Comment by abhoi** [comment]
Facing the same issue. Any thoughts?

**Comment by shun-lin** [comment]
Hi @abhoi ,

may you provide me with the output of ```nvidia-smi``` from the terminal and maybe I can help you debug :)

**Comment by sanjoy** [comment]
@shun-lin Any chance you're willing to send a PR to fix this?

**Comment by shun-lin** [comment]
@sanjoy what I end up doing is

1) set ```export TF_MIN_GPU_MULTIPROCESSOR_COUNT=5``` in my config file to let TF use the less powerful GPU and 

2) Removing the less power GPU and just use the powerful GPU I have.

I have not spent much time diving deeper into where the the problem occurs (i.e. it should work without removing the less powerful GPU and know to only list the available devices) but when I have time outside of work I can definitely try to help out :)

**Comment by cheshire** [comment]
This is somewhat strange, because you're using the same configuration (as far as I can tell) as virtually everyone else using GPU: one powerful GPU for compute, other GPU for driving graphics. I really would not expect crashes on this codepath.

**Comment by shun-lin** [comment]
@cheshire exactly, I wanted to use my Quadro P1000 for general graphics use and Titan RTX for computing, but then I got the above error so I just remove the Quadro P1000. Do you have any insight into what may have gone wrong? Thank you so much for your time!

**Comment by maximuslee1226** [comment]
Hi Shun-lin, Did you get any response on this one? I am getting the same error in the following
/usr/local/cuda-10.2/bin/nvcc
Sun Jan 26 18:52:57 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 760     On   | 00000000:01:00.0 N/A |                  N/A |
| 42%   46C    P0    N/A /  N/A |   1150MiB /  4034MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 207...  On   | 00000000:02:00.0 Off |                  N/A |
|  6%   55C    P2    55W / 215W |    610MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
|    1       701      C   ...ndon/anaconda3/envs/cuda_env/bin/python   101MiB |
|    1      2629      C   ...ndon/anaconda3/envs/cuda_env/bin/python    99MiB |
|    1      8061      C   ...ndon/anaconda3/envs/cuda_env/bin/python   101MiB |
|    1     17581      C   ...ndon/anaconda3/envs/cuda_env/bin/python    99MiB |
|    1     20290      C   ...ndon/anaconda3/envs/cuda_env/bin/python    99MiB |
|    1     23923      C   ...ndon/anaconda3/envs/cuda_env/bin/python    99MiB |
+-----------------------------------------------------------------------------+
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by sanjoy** [comment]
@shun-lin Can you try running with tf-nightly?  The codepath that was causing the original error has been fixed.

@maximuslee1226 What version of TF are you using?

**Comment by maximuslee1226** [comment]
Hi Sanjoy, Thanks for your response. I am running tensorflow 1.14.0

**Comment by sanjoy** [comment]
> Hi Sanjoy, Thanks for your response. I am running tensorflow 1.14.0

Thank you.  I believe this issue has been fixed; can you check if you can reproduce the problem with tf-nightly?

**Comment by maximuslee1226** [comment]
How can I install tf-nightly?

**Comment by maximuslee1226** [comment]
never mind pip install tf-nightly

**Comment by shun-lin** [comment]
> @shun-lin Can you try running with tf-nightly? The codepath that was causing the original error has been fixed.
> 
> @maximuslee1226 What version of TF are you using?

Thanks for the suggestion, but I no longer have access to the powerful GPU due to switching to other team and therefore I wouldn't be able to know if the new `tf-nightly` build has fixed the issue, if @maximuslee1226 issue is fixed then I think we can closed this issue. Thank you so much for your help!

**Comment by maximuslee1226** [comment]
Hi Shun-lin, I tried, but it failed. I have tf-nightly installed, but it's still giving me the same error. cudnn installed and working find with samples after mnist test, but as soon as I call the tf.config.experimental.list_physical_devices(), I get the same error. I need some help! Thanks in advance.

**Comment by sanjoy** [comment]
Can you please share the log file?  The original error has now been replaced by a [`LOG(INFO)` line](https://github.com/tensorflow/tensorflow/blob/f54bb6f5578b931d79884302768996ba1073f685/tensorflow/compiler/jit/xla_gpu_device.cc#L161) so you're probably seeing a different error.

**Comment by cheshire** [comment]
Also could you say whether the crash is still there if you run under `TF_XLA_FLAGS='--tf_xla_enable_xla_devices=false'` ?

**Comment by betterze** [comment]
any update about this issue? I am also facing the same problem.

**Comment by cheshire** [comment]
@betterze Have you tried running under the environment variable specified in the previous comment?

**Comment by betterze** [comment]
@cheshire Thank you for your reply. How to run under TF_XLA_FLAGS='--tf_xla_enable_xla_devices=false' ? I am not sure where to change this variable. 

My promble is solved by:

~~~
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0" #(or "1" or "2")
~~~

Try 0,1,2 that represent different index of gpu. One of my gpu is not strong enough to train DL model, so I can choose any gpu except this one.

**Comment by cheshire** [comment]
@betterze It's an environment variable, `env TF_XLA_FLAGS='--tf_xla_enable_xla_devices=false' ./yourscript.py`

**Comment by mohantym** [comment]
Was able to replicate the issue with TF v2.5 in Google Colab with and without GPU  , They are not throwing errors in both situation ,please find the [gist](https://colab.research.google.com/gist/mohantym/c830549d3e3aa202f31519cf1a238ec2/32793_g.ipynb)  here .. Thanks!
