### ISSUE TITLE
Masking LSTM: OP_REQUIRES failed at cudnn_rnn_ops.cc:1498 : Unknown: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by mimxrt** [tensorflow/tensorflow#33148]
### System information
- **Have I written custom code**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.2 LTS
- **TensorFlow installed from (source or binary)**: Binary, pip
- **TensorFlow version (use command below)**: v2.0.0-rc2-26-g64c3d38 2.0.0
- **Python version**: Python 3.7.3
- **CUDA/cuDNN version**: CUDA=10.0, CUDNN=7.6.2.24-1
- **GPU model and memory**: Quadro RTX 6000 major: 7 minor: 5 memoryClockRate(GHz): 1.77

### Describe the problem
It seems there is an issue with the CuDNN LSTM implementation when using a `tf.keras.layers.Masking` layer. 

```
batch_size = 256
num_tsteps = 144
num_features = 130
num_units = 88
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(num_tsteps, num_features), batch_size=batch_size),
    tf.keras.layers.Masking(mask_value=0.0, input_shape=(num_tsteps, num_features)),
    tf.keras.layers.LSTM(num_units,  batch_input_shape=(batch_size, num_tsteps, num_features), return_sequences=True, stateful=False),
    tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(1)),
    tf.keras.layers.Activation('sigmoid'),
])
```
Similar to #33069 I receive this error during training and I have strictly right-padded data (I am doing trimming and right-padding manually). However, in contrast to this issue, I confirmed that I do not have any inputs containing only zeroes via the following snippet:

```
for i, e in enumerate(ds_train):
    res = []
    f, l = [x.numpy() for x in e]
    for j in range(f.shape[0]):
        if not (f[j] == 0.0).all():
            res.append(1)
        else:
            res.append(0)
    fin = [res[0]]
    for e in res[1:]:
        if e != fin[-1]:
            fin.append(e)
    print("i {}: {}".format(i, fin))

# Result:
i 0: [1, 0]
i 1: [1, 0]
i 2: [1, 0]
i 3: [1, 0]
i 4: [1]
i 5: [1, 0]
...
```
If I remove the Masking-layer, the error does not occur. I confirmed this by running a complete epoch (2324 batches), however, the training is probably pretty pointless when including the padded data.

Is there any other pitfall that I am missing that could cause this issue?

### Source code / logs
Python output:
```
Epoch 1/1000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: 


CancelledErrorTraceback (most recent call last)
<ipython-input-7-1c503c2dd55c> in <module>
----> 1 m.fit(train=True)

/ws/tf/vol_local/_model_lstm.py in fit(self, train, verbose)
    315             ]
    316             self.model.fit(ds_train, epochs=num_epochs, verbose=verbose, shuffle=False,
--> 317                                 validation_data=ds_val, validation_steps=None, callbacks=cbs)
    318             #self.model.save(sess_hdf5_path)
    319             self.model.save_weights(self.sess_h5_path.as_posix())

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    322                 mode=ModeKeys.TRAIN,
    323                 training_context=training_context,
--> 324                 total_epochs=epochs)
    325             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    326 

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    121         step=step, mode=mode, size=current_batch_size) as batch_logs:
    122       try:
--> 123         batch_outs = execution_function(iterator)
    124       except (StopIteration, errors.OutOfRangeError):
    125         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in execution_function(input_fn)
     84     # `numpy` translates Tensors to values in Eager mode.
     85     return nest.map_structure(_non_none_constant_value,
---> 86                               distributed_function(input_fn))
     87 
     88   return execution_function

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
    518         # Lifting succeeded, so variables are initialized and we can run the
    519         # stateless function.
--> 520         return self._stateless_fn(*args, **kwds)
    521     else:
    522       canon_args, canon_kwds = \

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in __call__(self, *args, **kwargs)
   1821     """Calls a graph function specialized to the inputs."""
   1822     graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 1823     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   1824 
   1825   @property

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _filtered_call(self, args, kwargs)
   1139          if isinstance(t, (ops.Tensor,
   1140                            resource_variable_ops.BaseResourceVariable))),
-> 1141         self.captured_inputs)
   1142 
   1143   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1222     if executing_eagerly:
   1223       flat_outputs = forward_function.call(
-> 1224           ctx, args, cancellation_manager=cancellation_manager)
   1225     else:
   1226       gradient_name = self._delayed_rewrite_functions.register()

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    509               inputs=args,
    510               attrs=("executor_type", executor_type, "config_proto", config),
--> 511               ctx=ctx)
    512         else:
    513           outputs = execute.execute_with_cancellation(

/ws/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

/ws/miniconda3/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node metrics/accuracy/broadcast_weights/assert_broadcastable/AssertGuard/else/_36/Assert/data_2/_62}}]]
	 [[loss/activation_loss/weighted_loss/broadcast_weights/assert_broadcastable/is_valid_shape/else/_1/has_valid_nonscalar_shape/then/_106/has_invalid_dims/concat/_28]] [Op:__inference_distributed_function_172102]

Function call stack:
distributed_function
```

Command line log:
```
2019-10-08 14:38:27.367875: W tensorflow/core/grappler/optimizers/implementation_selector.cc:310] Skipping optimization due to error while loading function libraries: Invalid argument: Functions '__inference___backward_cudnn_lstm_with_fallback_169668_171093' and '__inference___backward_cudnn_lstm_with_fallback_169668_171093_specialized_for_StatefulPartitionedCall_at___inference_distributed_function_172102' both implement 'lstm_dce676f4-acdd-4bb5-88d9-e8dd57573aba' but their signatures do not match.
2019-10-08 14:38:27.536666: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-08 14:38:39.982582: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-08 14:38:41.215567: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cudnn_rnn_ops.cc:1498 : Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1424): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
2019-10-08 14:38:41.215616: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1424): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond_64/then/_0/CudnnRNNV3}}]]
2019-10-08 14:38:41.215638: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Cancelled: [_Derived_]RecvAsync is cancelled.
	 [[{{node metrics/accuracy/broadcast_weights/assert_broadcastable/AssertGuard/else/_36/Assert/data_2/_62}}]]
	 [[loss/activation_loss/weighted_loss/broadcast_weights/assert_broadcastable/is_valid_shape/else/_1/has_valid_nonscalar_shape/then/_106/has_invalid_dims/concat/_28]]
2019-10-08 14:38:41.215693: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Cancelled: [_Derived_]RecvAsync is cancelled.
	 [[{{node metrics/accuracy/broadcast_weights/assert_broadcastable/AssertGuard/else/_36/Assert/data_2/_62}}]]
```

**Comment by oanush** [comment]
@mimxrt ,
Thanks for reporting the issue, can you please provide simple and standalone code to reproduce the issue?

**Comment by oanush** [comment]
Issue replicating with TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/11dcf7d43fb3a2ba2c1d97e22ff145d2/33148.ipynb) of colab.Thanks!

**Comment by mimxrt** [comment]
I found my mistake and updated the code accordingly. Please update the gist to represent the corrected and less verbose version below. The error happens in TF-2.0 and _does not_ happen in TF-1.0 (1.14.0). Please also try to removing the `Masking` layer to confirm the issue only exists with masking.

```
import numpy as np
import tensorflow as tf

# NOTE: Comment the block below for testing with TF-1.0
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

# NOTE: Uncomment the block below for testing with TF-1.0
# tf.compat.v1.enable_eager_execution()
# config = tf.compat.v1.ConfigProto()
# config.gpu_options.allow_growth = True
# sess = tf.compat.v1.Session(config=config)
# tf.compat.v1.keras.backend.set_session(sess)

assert tf.executing_eagerly()

batch_size = 256
num_tsteps = 144
num_features = 130
num_units = 88

#n_files = 3320
n_files = 10
num_epochs = 1000

seq_len_max_trunc = batch_size * num_tsteps
flen = 3728

### Create TFRecord

X = np.random.rand(flen + 1, num_features + 2)
n_label0 = int((flen + 1) * 0.2)
Y = np.concatenate((
    np.zeros((n_label0, 1)), # label 0
    np.ones((flen - n_label0 + 1, 1)), # label 1
), axis=0)
ds_out = tf.data.Dataset.from_tensor_slices((X, Y))
ds_ser = ds_out.map(lambda *x: 
   tf.reshape(tf.py_function(lambda *v: 
       tf.train.Example(features=tf.train.Features(feature={
           "features": tf.train.Feature(float_list=tf.train.FloatList(value=v[0].numpy())),
           "label": tf.train.Feature(float_list=tf.train.FloatList(value=v[1].numpy())),
       })).SerializeToString(), x, tf.string
   ), ()), num_parallel_calls=tf.data.experimental.AUTOTUNE
)
writer = tf.data.experimental.TFRecordWriter("temp.tfrecord")
writer.write(ds_ser)

### Read TFRecord and train

files = ["temp.tfrecord"] * n_files

model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(num_tsteps, num_features), batch_size=batch_size),
    tf.keras.layers.Masking(mask_value=0.0, input_shape=(num_tsteps, num_features)),
    tf.keras.layers.LSTM(num_units,  batch_input_shape=(batch_size, num_tsteps, num_features), return_sequences=True, stateful=False),
    tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(1)),
    tf.keras.layers.Activation('sigmoid'),
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])


def _prep_ds_file(file):
    _ds = tf.data.TFRecordDataset(file)
    _ds = _ds.map(lambda x: tf.io.parse_single_example(x, {
        "features": tf.io.FixedLenFeature([132], tf.float32),
        "label": tf.io.FixedLenFeature([1], tf.float32),
    }), num_parallel_calls=tf.data.experimental.AUTOTUNE)
        
    _ds = _ds.flat_map(lambda v: tf.data.Dataset.from_tensors((v["features"][2:], v["label"])))

    _trunc = min(seq_len_max_trunc, ((flen + 1) // num_tsteps) * num_tsteps)
    _ds = _ds.take(_trunc)

    _c_pad = (batch_size - ((flen + 1) // num_tsteps)) * num_tsteps
    if _c_pad >= 0:
        assert _c_pad + ((flen + 1) // num_tsteps * num_tsteps) == seq_len_max_trunc
        _ds_pad = tf.data.Dataset.from_tensors((
            tf.constant(0.0, shape=[num_features,]),
            tf.constant(0.0, shape=[1,])))
        _ds_pad = _ds_pad.repeat(_c_pad)
        _ds = _ds.concatenate(_ds_pad) # pad to correct size

    _ds = _ds.window(size=num_tsteps, shift=None, stride=1, drop_remainder=True)
    _ds = _ds.flat_map(lambda x, y: tf.data.Dataset.zip((x.batch(num_tsteps), y.batch(num_tsteps))))

    _ds = _ds.batch(batch_size, drop_remainder=True)
    
    return _ds


ds_fs = tf.data.Dataset.list_files(files, shuffle=True, seed=1)
fs_train = ds_fs.take(int(n_files * 0.7))
fs_val = ds_fs.skip(int(n_files * 0.7)).take(int(n_files * 0.1))

ds_train = [_prep_ds_file(f) for f in fs_train.take(1)][0]
for f in fs_train.skip(1):
    ds_train = ds_train.concatenate(_prep_ds_file(f))
ds_train = ds_train.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

cbs = [
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True),
]
model.fit(ds_train, epochs=num_epochs, verbose=1, shuffle=False,
          validation_data=None, validation_steps=None, callbacks=cbs)
```

**Comment by jvishnuvardhan** [comment]
@mimxrt I could reproduce the issue with `tf-nightly-gpu`. However, if I use only cpu then there is no error (with and without masking) as shown in the original post. I think root-cause may be due to `tf.config.experimental.set_memory_growth(gpu, True)`. Thanks!

**Comment by mimxrt** [comment]
Thank you for your reply. I'm not sure what you are saying though: did you try removing `tf.config.experimental.set_memory_growth(gpu, True)` at all? I tried and for me the same error happens. For me, the only difference is that TF occupies all available GPU memory.

Could you please try again if the error also happens without memory growth? If so, I guess the issue could be in the GPU LSTM implementation (cuDNN)?

**Comment by jvishnuvardhan** [comment]
@mimxrt I mentioned two things.
1. I could reproduce the issue with `tf-nightly-gpu`
2. Just tried to point some root-cause. I ran your code as it is in a cpu and I don't see any error. so I guess root-cause may be related to `tf.config.experimental.set_memory_growth(gpu, True)`. I may be wrong.

Thanks!

**Comment by mimxrt** [comment]
I see, thank you for the clarification. So in summary we can say that this issue does not happen on the CPU and that it is related to the GPU implementation. As I tried running it without `tf.config.experimental.set_memory_growth(gpu, True)` and the error still occurs, it should probably be save to rule that out as the cause/issue.

**Comment by jalilasadi** [comment]
same problem here. did you find any solution?

**Comment by mimxrt** [comment]
No sorry, still waiting for any help myself.

**Comment by ynsgnr** [comment]
I changed my model from:
`        self.model = Sequential([
            Embedding(len(self.item_map), self.embed_dim, input_length = X.shape[1],mask_zeros=True),
            LSTM(self.lstm_out),
            Dense(len(self.item_map)-1),
        ])
`
to:
`        self.model = Sequential([
            Embedding(len(self.item_map), self.embed_dim, input_length = X.shape[1]),
            Masking(mask_value=0),
            LSTM(self.lstm_out),
            Dense(len(self.item_map)-1),
        ])
`
And solved my isssue

I know @mimxrt's code has the same model and I dont know why it works for me,
but im adding this for anyone else comes here with the issue and maybe it can help with debugging

**Comment by jalilasadi** [comment]
@ynsgnr if you are running on CPU then it works properly, the problem is when you run it on GPU. By the way, you do not use the Timedistirbuted layer in your code since this problem shows up when you use Timedistributed with LSTM.

**Comment by jalilasadi** [comment]
@jvishnuvardhan, I tried your suggestion but it still produces the same error. I am new to GitHub , how to tell this problem to someone from TensorFlow? do they see our conversation ?

**Comment by mimxrt** [comment]
In my experience and example the issue stems from the Masking + LSTM combination, not from the TimeDistributed layer. Please try the example in https://github.com/tensorflow/tensorflow/issues/33148#issuecomment-540472342 without it, i.e.

```
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(num_tsteps, num_features), batch_size=batch_size),
    tf.keras.layers.Masking(mask_value=0.0, input_shape=(num_tsteps, num_features)),
    tf.keras.layers.LSTM(num_units,  batch_input_shape=(batch_size, num_tsteps, num_features), return_sequences=False, stateful=False),
    tf.keras.layers.Dense(1),
    tf.keras.layers.Activation('sigmoid'),
])
```
(change `return_sequences` to `False` and remove `TimeDistributed`).

You can also try to remove the Masking layer in the example above and the error will go away.

**Comment by jalilasadi** [comment]
but I have this model:
`        model=tf.keras.Sequential()
        embeding_layer=layers.Embedding(self.vocab_size,self.word_vector_dim,weights=[word_embeding_matrix],trainable=True,mask_zero=True)
        model.add(embeding_layer)
        model.add(layers.LSTM(50))
        model.add(layers.Dropout(0.5))
        model.add(layers.Dense(3,activation='softmax'))
        opt=tf.keras.optimizers.RMSprop(learning_rate=0.001)
        model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['accuracy'])
        self.model=model
`
which works fine and with no error. As you can see I used masking and LSTM at the same time. so in my experience the problem stem from TimeDistributed and masking.

**Comment by mimxrt** [comment]
Interesting. Can you provide a complete example like mine so I can try your code as well?

**Comment by jalilasadi** [comment]
the above example is a simple classifier, you can make a random dataset and feed the model with it, so you can see that it will work with no problem.
this is where the model does not work and produce an error while training :
``        model=tf.keras.Sequential()
        embeding_layer=layers.Embedding(self.vocab_size,self.word_vector_dim,weights=[word_embeding_matrix],trainable=False,mask_zero=True)
        model.add(TimeDistributed(embeding_layer))
        model.add(TimeDistributed(tf.keras.layers.LSTM(50)))
        model.add(tf.keras.layers.Bidirectional(costumized_lstm.Costumized_LSTM(50)))
        # model.add(tf.keras.layers.Bidirectional(costumized_lstm.Costumized_LSTM(100)))
        model.add(layers.Dense(3,activation='softmax'))
        opt=tf.keras.optimizers.Adam(learning_rate=0.001)
        model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['accuracy'])
``

**Comment by queirozfcom** [comment]
I have a similar issue, just posted a question on SO: https://stackoverflow.com/questions/58895694/cudnn-status-bad-param-when-trying-to-perform-inference-on-a-lstm-seq2seq-with-m

**Comment by qlzh727** [comment]
Sorry for the very late reply, I will take a close look this week. This issue is kind of tricky since the error is raised from cudnn kernel, which contains less information. The troubleshooting for root cause might take me sometime.

**Comment by michal-au** [comment]
@qlzh727 in case it helps, for me the problem goes away when I disable eager mode.

**Comment by qlzh727** [comment]
@houtoms, the error is raised from cudnn kernel and it only says there is a bad param. Could you provide more details about which param is bad? I am not familiar with the cudnn kernel detail at all.

**Comment by houtoms** [comment]
Yes, I can repro the error. Turns out the cudnnSetRNNDataDescriptor gives the BAD PARAM error. From the log, I can see you want to process the input data as 256 (batch size) x 144 (time steps) x 130 (unit size). But, when using masks, I observe that some entire sequences are masked out. For example, there could be only 25 meaningful sequences (at least having one time step) out of the 256 sequences in one batch. In this case, it seems the cuDNN requires the batch size to be 25. @mimxrt Can you first confirm the scenario I mentioned is what you want to do?

**Comment by mimxrt** [comment]
Thank you for your reply. The reason for processing 256 x 144 x 130 data is that I make the assumption that my maximum sequence (in real data) has approximately `256 * 144 = 36864` time steps (each time step has 130 values/features -> unit size). The shortest sequence has actually 3728 time steps. Hence, the input dataset in my example is generated using this shortest length and during processing the input is zero-padded to the longest sequence in `_prep_ds_file()`. During training, the `Masking` layer should then allow ignoring the zero-valued batch elements. Did that answer your question?

Now, I understand that you are saying that if any of my input batches does have at least one batch element that is completely filled with zeros (i.e. 144 x 130 zeros), cuDNN requires a different batch size for that batch. From my understanding [of the docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM#used_in_the_tutorials) the CuDNN kernel is used if

>  Inputs are not masked or strictly right padded.

And that is what I am doing, am I not? I use masking but made sure the data is strictly right padded. Some (or in this example code all) of the batches do have zero padding in the end that is bigger than one batch element (144 time steps) and therefore the entire batch element should be ignored.

If this is the wrong way of doing this, then what is the right way? Is it possible to change the batch size mid-training (i.e. per batch)? Otherwise, how can I train sequences of different length? Batch size 1?

**Comment by houtoms** [comment]
Yes, your understanding is correct. And cuDNN doesn't support zero samples in batch for now.

I am not sure if it is possible/how to change the batch size during training using tf.dataset (@qlzh727 some tf.dataset experts?). Batch size 1 could work, but it might significantly affect the performance. 

Or you could try to change the way you split your sequence into the batch, like using seq_len/batch_size as the current 'num_tsteps' rather than the fixed 144. But still you need to make sure the minimum seq_len >= batch_size.

**Comment by qlzh727** [comment]
@houtoms, Thanks for providing the context.

From high level API's perspective, I would expect the kernel to just return zeros for any of the sequence that is fully masked, rather than asking user to remove those values from the batch. It will be quite complicate to ask user to handle this on the python side.

@houtoms, will it be complicated to add this support (fully masked sequence) in the cudnn kernel?

**Comment by houtoms** [comment]
Yes, I agree with you. I am contacting the cuDNN about this issue. Will update when I get any feedback.

**Comment by houtoms** [comment]
Got some feedback from cuDNN and it sounds not complicated to do that. Already filed a request to them. For now, users still have to make sure they don't have such fully masked sequences in batch.

**Comment by qlzh727** [comment]
Thanks for the update.

**Comment by inkcherry** [comment]
> 我将模型从以下位置更改：
> 
> ```python
>         自我 .model =顺序（[
>             嵌入（len（self .item_map），self .embed_dim，input_length  = X.shape [ 1 ]，mask_zeros = True），
>             LSTM（self .lstm_out），
>             密集（len个（自 .item_map）- 1）
>         ]）
> ```
> 
> 至：
> 
> ```python
>         自我 .model =顺序（[
>             嵌入（len（self .item_map），self .embed_dim，input_length  = X.shape [ 1 ]），
>             遮罩（mask_value = 0），
>             LSTM（self .lstm_out），
>             密集（len个（自 .item_map）- 1）
>         ]）
> ```
> 
> 解决了我的问题
> 
> 我知道@mimxrt的代码具有相同的模型，我不知道为什么它对我有用，
> 但是我在这里为其他人添加了这个问题，也许它可以帮助调试



> I changed my model from:
> 
> ```python
>         self.model = Sequential([
>             Embedding(len(self.item_map), self.embed_dim, input_length = X.shape[1],mask_zeros=True),
>             LSTM(self.lstm_out),
>             Dense(len(self.item_map)-1),
>         ])
> ```
> 
> to:
> 
> ```python
>         self.model = Sequential([
>             Embedding(len(self.item_map), self.embed_dim, input_length = X.shape[1]),
>             Masking(mask_value=0),
>             LSTM(self.lstm_out),
>             Dense(len(self.item_map)-1),
>         ])
> ```
> 
> And solved my isssue
> 
> I know @mimxrt's code has the same model and I dont know why it works for me,
> but im adding this for anyone else comes here with the issue and maybe it can help with debugging

I think embedding(mask_zero=true) create this problem,there are two way I find to slove it 
1"mask_zero=False",but it changes code process
2 your way  
thanks a lot.

**Comment by mimxrt** [comment]
Thank you @qlzh727 and @houtoms, very much looking forward to the new cuDNN feature. In the meantime I will try to re-arrange my input dimensions.

**Comment by jalilasadi** [comment]
@houtoms and @qlzh727 thank you for the help. I am trying to implement a text classification model where the shape of the input is (samples, sentences, words, word_embeding) and I used TimeDistributed to implement it. having a fully masked sequence in this kind of model is inevitable. therefore it would be great if cuDNN supports fully masked sequence.

**Comment by jalilasadi** [comment]
as @michal-au said, I deactivate eager mode and remove callbacks from model.fit and now the model is working and training with no error! @houtoms is it possible to be an eager mode issue, not the cudnn issue?

**Comment by alldefector** [comment]
I can reproduce that `mask_zeros=True` is causing the crash. Doesn't matter if eager is on or off, with or without callbacks.

LSTM on a masked sequence is extremely common in NLP models, so this is a major bug in terms of impact.

**Comment by jalilasadi** [comment]
@houtoms so why when I deactivate eager mode it works with no error?

**Comment by houtoms** [comment]
@jalilasadi , I repro the error using mimxrt's python script posted above on Oct 10. The script works fine in both eager or graph mode if Masking layer is removed. Also, the script breaks in both modes if Masking layer is added.

**Comment by saverymax** [comment]
I was recently dealing with the same problem. Do you have any new information regarding this issue?

**Comment by qlzh727** [comment]
@jalilasadi, when eager mode is disabled, the code went to a different path that doesn't use fused cudnn kernel, hence no error will be raised.

**Comment by jalilasadi** [comment]
@qlzh727 thank you for your answer. I do not know what fused cudnn is, I am new to TensorFlow .does it make a difference in the result of the model that we implement or it just affects the computational performance?

**Comment by qlzh727** [comment]
THe fused cudnn lstm is faster to run on GPU, and should have the same math result as the standard implementation.

**Comment by qlzh727** [comment]
ping @houtoms for a status update from Nvidia side.

**Comment by houtoms** [comment]
Sure. Let me check with the CUDNN team and will update soon.

**Comment by mimxrt** [comment]
> Yes, your understanding is correct. And cuDNN doesn't support zero samples in batch for now.
> 
> I am not sure if it is possible/how to change the batch size during training using tf.dataset (@qlzh727 some tf.dataset experts?). Batch size 1 could work, but it might significantly affect the performance.
> 
> Or you could try to change the way you split your sequence into the batch, like using seq_len/batch_size as the current 'num_tsteps' rather than the fixed 144. But still you need to make sure the minimum seq_len >= batch_size.

@houtoms As it seems the implementation takes more time than expected I wanted to continue and try your suggestion of using a dynamic number of timesteps (instead of the fixed 144). Unfortunately I get an error when doing this in TF 2.1.0 (calling `model.fit()` with an input of `<PrefetchDataset shapes: ((128, None, 128), (128, None, 1)), types: (tf.float32, tf.float32)>`:

`
InvalidArgumentError:  ValueError: Attempt to convert a value (<BatchDataset shapes: ((128, None, 128), (128, None, 1)), types: (tf.float32, tf.float32)>) with an unsupported type (<class 'tensorflow.python.data.ops.dataset_ops.BatchDataset'>) to a Tensor.`

Could it be that I misunderstood your suggestion (note the `None` in the input dimensions)? All ideas are much appreciated.

**Comment by qlzh727** [comment]
@houtoms, I assume this should be fixed already with the latest CuDNN kernel?

**Comment by jalilasadi** [comment]
@qlzh727 I still get the same error with CuDNN 7.6.5. did you mean this version of CuDNN? because it is the last version of it.  this is my code 

` def BGRU_BGRU(self,metrics_file_path):
        self.metrics_file_path = metrics_file_path
        # tf.compat.v1.disable_eager_execution()

        model=tf.keras.Sequential()
        # embeding_layer=layers.Embedding(self.vocab_size,self.word_vector_dim,weights=[self.word_embeding_matrix],trainable=True,mask_zero=True)
        embeding_layer=layers.Embedding(self.vocab_size,self.word_vector_dim,mask_zero=True)
        model.add(TimeDistributed(embeding_layer))
        model.add(TimeDistributed(tf.keras.layers.Bidirectional(tf.keras.layers.GRU(50))))
        # model.add(TimeDistributed(tf.keras.layers.Bidirectional(tf.keras.layers.GRU(50,dropout=0.2,recurrent_dropout=0.2))))
        model.add(tf.keras.layers.Bidirectional(tf.keras.layers.GRU(50)))
        # model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(50,dropout=0.2,recurrent_dropout=0.2)))
        # model.add(tf.keras.layers.Dense(30,activation='sigmoid'))
        model.add(layers.Dense(self.config.number_of_classess,activation='softmax'))
        lr_schedule = tf.keras.optimizers.schedules.InverseTimeDecay(self.config.lr, decay_steps=self.config.decay_steps, decay_rate=1,staircase=False)
        opt = tf.keras.optimizers.RMSprop(learning_rate=lr_schedule)
        model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy', 'mse'])
        self.model = model
        return`

and this is the error that running this code produce: 

`Train on 33171 samples, validate on 8293 samples
Epoch 1/8
2020-02-29 03:04:13.742695: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-02-29 03:04:14.303999: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-02-29 03:04:15.018554: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at cudnn_rnn_ops.cc:1517 : Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
2020-02-29 03:04:15.018854: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond_31/then/_0/CudnnRNNV3}}]]
2020-02-29 03:04:15.019228: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: {{function_node __forward_cudnn_gru_with_fallback_681666_specialized_for_sequential_time_distributed_1_bidirectional_backward_gru_StatefulPartitionedCall_at___inference_distributed_function_687655}} {{function_node __forward_cudnn_gru_with_fallback_681666_specialized_for_sequential_time_distributed_1_bidirectional_backward_gru_StatefulPartitionedCall_at___inference_distributed_function_687655}} CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond_31/then/_0/CudnnRNNV3}}]]
	 [[sequential/time_distributed_1/bidirectional/backward_gru/StatefulPartitionedCall]]
	 [[Reshape_10/_28]]
2020-02-29 03:04:15.019884: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: {{function_node __forward_cudnn_gru_with_fallback_681666_specialized_for_sequential_time_distributed_1_bidirectional_backward_gru_StatefulPartitionedCall_at___inference_distributed_function_687655}} {{function_node __forward_cudnn_gru_with_fallback_681666_specialized_for_sequential_time_distributed_1_bidirectional_backward_gru_StatefulPartitionedCall_at___inference_distributed_function_687655}} CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond_31/then/_0/CudnnRNNV3}}]]
	 [[sequential/time_distributed_1/bidirectional/backward_gru/StatefulPartitionedCall]]
2020-02-29 03:04:15.023940: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at cudnn_rnn_ops.cc:1517 : Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
2020-02-29 03:04:15.024206: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond_31/then/_0/CudnnRNNV3}}]]

  300/33171 [..............................] - ETA: 26:472020-02-29 03:04:19.483701: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at cudnn_rnn_ops.cc:1517 : Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
2020-02-29 03:04:19.484099: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond/then/_0/CudnnRNNV3}}]]
2020-02-29 03:04:19.484494: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: {{function_node __inference_cudnn_gru_with_fallback_689679_specialized_for_sequential_time_distributed_1_bidirectional_backward_gru_StatefulPartitionedCall_at___inference_distributed_function_693569}} {{function_node __inference_cudnn_gru_with_fallback_689679_specialized_for_sequential_time_distributed_1_bidirectional_backward_gru_StatefulPartitionedCall_at___inference_distributed_function_693569}} CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond/then/_0/CudnnRNNV3}}]]
	 [[sequential/time_distributed_1/bidirectional/backward_gru/StatefulPartitionedCall]]
Traceback (most recent call last):
  File "C:\Users\jalil\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 2803, in variable_creator_scope
    yield
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 397, in fit
    prefix='val_')
  File "C:\Users\jalil\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 771, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 302, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\jalil\PycharmProjects\my_projects\coding_paian_nameh\model\classification_models.py", line 783, in on_epoch_end
    y_test_pred = self.model.predict(self.X_test)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 475, in _model_iteration
    total_epochs=1)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 638, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 545, in call
    ctx=ctx)
  File "C:\Users\jalil\PycharmProjects\my_projects\venv\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError:  [_Derived_]  CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1430): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond/then/_0/CudnnRNNV3}}]]
	 [[sequential/time_distributed_1/bidirectional/backward_gru/StatefulPartitionedCall]] [Op:__inference_distributed_function_693569]

Function call stack:
distributed_function -> distributed_function -> distributed_function`

**Comment by qlzh727** [comment]
@houtoms, do u know whether the fix has reach the public release? If that's the case, please share a script/colab that includes version and the working model. Thanks.

**Comment by houtoms** [comment]
@qlzh727 Not yet. We might need to wait for the next major release for the fix.

**Comment by super-pirata** [comment]
> 
> 
> @qlzh727 Not yet. We might need to wait for the next major release for the fix.

Do you have an estimate time for that?

**Comment by hucKOder** [comment]
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

Dissable eager execution and everything is running fine without the fused rnn kernel. Thx for the help guys :)

**Comment by NoelKennedy** [comment]
I have a work around that seems to work:  force TF to use the non CuDNN implementation by selecting a sigmoid activation instead of TANH

layers.LSTM(..., activation='sigmoid').

This forces TF to a generic GPU kernel.  It's slower but a slower implementation is a lot faster than not working at all ;p

**Comment by mimxrt** [comment]
If you really want that as a workaround, you can find the requirements for the cuDNN implementation [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM?hl=en#used-in-the-notebooks_1). 

> The requirements to use the cuDNN implementation are:
> 
> 1. activation == tanh
> 1. recurrent_activation == sigmoid
> 1. recurrent_dropout == 0
> 1. unroll is False
> 1. use_bias is True
> 1. Inputs are not masked or strictly right padded.

I guess changing any one of these will result in the CPU implementation being used.

**Comment by NoelKennedy** [comment]
That's right mimxrt.  I guess the interesting point here is that the inputs to my LSTM are always masked, but I have to force the non-cudnn implementation using the activation function.  Might be a clue for someone who can fix this.

**Comment by tstumm** [comment]
I'd be nice to have a flag on LSTM layers which allows to disable the use of the CuDNN implementation instead of either disabling eager execution or using non-default activation functions.

**Comment by sayakpaul** [comment]
Facing this same issue and reported here: https://github.com/tensorflow/tensorflow/issues/40982.

**Comment by qlzh727** [comment]
> I'd be nice to have a flag on LSTM layers which allows to disable the use of the CuDNN implementation instead of either disabling eager execution or using non-default activation functions.

There is a private field you can set to disable the cudnn kernel once the layer is created.
```
layer = tf.keras.layers.LSTM(4)
layer. _could_use_gpu_kernel = False
```
This will focus the lstm layer to use the non-cudnn implementation, even landed on GPU.

**Comment by sayakpaul** [comment]
@queirozfcom what would you suggest to use between this option and disabling eager execution as when eager execution is disabled it does work?

**Comment by qlzh727** [comment]
Disable eager will have larger side effects since it change the runtime to execute in graph/session context. We don't recommend user to fallback to graph unless they really need some feature in graph/session.

**Comment by sayakpaul** [comment]
Thanks :)

**Comment by thefxperson** [comment]
I am still facing this issue using TF 2.2.0. I also found the same workaround of forcing the LSTM to not use the cuDNN implementation to work, however it is nearly prohibitively slow. I found the generic GPU implementation took ~30 times longer to train per epoch than the cuDNN version. I hope this can be fixed soon.

**Comment by qlzh727** [comment]
I have disable the cudnn code path if there is fully masked data in the batch. It will have some performance dip since it fallback to generic kernel, but won't error out.

**Comment by ChuangLee** [comment]
facing this issue using TF 2.2.0 while evaluating

**Comment by qlzh727** [comment]
Please try with the latest nightly version.

**Comment by max1mn** [comment]
> 
> 
> @qlzh727 Not yet. We might need to wait for the next major release for the fix.

cudnn 8 is here, is there any info about this issue?

**Comment by stefan-falk** [comment]
@geetachavan1 I am using `tensorflow==2.3.0 but for this network:

```python
def call(self, inputs, training=None, memory_states=None, **kwargs):

    x = self.embedding(inputs, training=training)

    if memory_states is None:
        memory_states = self.get_initial_state(shape_list(x)[0])

    next_memory_states = []

    for i, (lstm, norm) in enumerate(self.lstm_stack):
        x = norm(x, training=training)
        outputs = lstm(x, training=training, initial_state=memory_states[i])
        x, state = outputs[0], outputs[1:]
        next_memory_states.append(state)

    return x, next_memory_states
```

where we have:

```python
self.embedding = layers.Embedding(vocab_size, embedding_size, mask_zero=True)
self.lstm_stack = list()
for _ in range(num_layers):
    lstm = layers.LSTM(
        units=lstm_units,
        return_sequences=True,
        return_state=True,
        dropout=dropout
    )
    norm = layers.LayerNormalization()
    self.lstm_stack.append((lstm, norm))
```

I am getting

```
Traceback (most recent call last):
  File "/home/sfalk/tmp/speech-v2/asr/bin/eval_transducer.py", line 153, in <module>
    main()
  File "/home/sfalk/tmp/speech-v2/asr/bin/eval_transducer.py", line 85, in main
    y_greedy = model.greedy_decode(encoder_inputs)[0]
  File "/home/sfalk/tmp/speech-v2/asr/model/transducer.py", line 351, in greedy_decode
    init_predict_network_state = PredictNetworkState(*self.predict_network(init_yseq))
  File "/home/sfalk/miniconda3/envs/asr2/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/sfalk/tmp/speech-v2/asr/model/transducer.py", line 118, in call
    outputs = lstm(x, training=training, initial_state=memory_states[i])
  File "/home/sfalk/miniconda3/envs/asr2/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 720, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/sfalk/miniconda3/envs/asr2/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/sfalk/miniconda3/envs/asr2/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 1176, in call
    last_output, outputs, new_h, new_c, runtime = gpu_lstm(
  File "/home/sfalk/miniconda3/envs/asr2/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 1401, in gpu_lstm
    outputs, h, c, _, _ = gen_cudnn_rnn_ops.cudnn_rnnv3(
  File "/home/sfalk/miniconda3/envs/asr2/lib/python3.8/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 1914, in cudnn_rnnv3
    return cudnn_rnnv3_eager_fallback(
  File "/home/sfalk/miniconda3/envs/asr2/lib/python3.8/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 2011, in cudnn_rnnv3_eager_fallback
    _result = _execute.execute(b"CudnnRNNV3", 5, inputs=_inputs_flat,
  File "/home/sfalk/miniconda3/envs/asr2/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1521): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)' [Op:CudnnRNNV3]
```

Shouldn't this be fixed?

**Comment by kaixih** [comment]
Some update: the cudnn v8.0.5 (next release) should be able to fix the issue exposed by https://github.com/tensorflow/tensorflow/issues/33148#issuecomment-540472342.

**Comment by iamarchit123** [comment]
When will this release happen .....looks like without CuDNN the implementation of LSTM runs very slow.

**Comment by max1mn** [comment]
> When will this release happen .....looks like without CuDNN the implementation of LSTM runs very slow.
cudnn 8.0.5 is already out https://docs.nvidia.com/deeplearning/cudnn/archives/index.html

**Comment by princio** [comment]
> Some update: the cudnn v8.0.5 (next release) should be able to fix the issue exposed by [#33148 (comment)](https://github.com/tensorflow/tensorflow/issues/33148#issuecomment-540472342).

@kaixih where did you read it?
I'd like to give it a try.

**Comment by celi52** [comment]
> > When will this release happen .....looks like without CuDNN the implementation of LSTM runs very slow.
> 
> cudnn 8.0.5 is already out https://docs.nvidia.com/deeplearning/cudnn/archives/index.html

I tried with `cudnn=8.0.4` `cudatoolkit=11.0.221`  `tensorflow-gpu=2.4.0,` and it fixed my problem.
cudnn can be installed by: 
`conda install -c nvidia cudnn`

**Comment by GeorgeG92** [comment]
I have the same issue on Google Colab using a Tesla P100 (tf 2.7.0, cuda v11.1, cudnn v8), when training lstm-based seq2seq models with a preceding Masking Layer On CPU the exact same code runs fine.
