### ISSUE TITLE
TF2.0 ptxas ignores PATH

### ISSUE THREAD

**Issue by DawyD** [tensorflow/tensorflow#33375]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 10.0/7.6
- GPU model and memory: GeForce RTX 2080 Ti

**Describe the problem**

I am receiving an error
`E tensorflow/stream_executor/cuda/ptxas_utils.cc:110] You are using ptxas 8.x, but TF requires ptxas 9.x (and strongly prefers >= 9.2.88).  Compilation of XLA kernels below will likely fail.`
suggesting that tensorflow uses ptxas version that ignores the PATH variable.

PATH, LD_LIBRARY_PATH, CUDA_HOME all points to the CUDA 10.0 directory
LD_LIBRARY_PATH also points to the CUDNN 7.6 directory

typing `ptxas --version` gives me:
`Cuda compilation tools, release 10.0, V10.0.145`

How is it possible that tensorflow launches ptxas of version 8 (probably from /usr/local/cuda/bin/) when all the important environment variables points to ptxas of version 10?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

The bug can be spotted for example when using tensorflow-addons and image rotate function.

```
import numpy as np
import tensorflow as tf
import tensorflow_addons as tfa

class Model:
    def __init__(self):
        tf.keras.backend.clear_session()
        
        inp = tf.keras.layers.Input((32,32,3), name='input_image')
        net = tf.keras.layers.Conv2D(3, 3, padding="same")(inp)

        self.model  = tf.keras.Model(inputs=inp, outputs=net)
        self.optimizer = tf.keras.optimizers.Adam()
        self.loss_obj = tf.keras.losses.MeanSquaredError()
        
    @tf.function
    def train_step(self):        
        angles_rad = tf.random.uniform((), 0, 3.14)
        images = tf.random.uniform((2,32,32,3))

        with tf.GradientTape() as tape:
            features = self.model(images, training=True)

            #angles_rad = tf.constant([0.5,0.4])
            rot_features = tfa.image.rotate(features, angles_rad, interpolation='NEAREST', name="rotate_features")
            
            loss = self.loss_obj(images, rot_features)

        variables = self.model.trainable_variables
        gradients = tape.gradient(loss, variables)
        self.optimizer.apply_gradients(zip(gradients, variables))
        return loss
    
    def train(self, nr_epochs):
        for epoch in range(nr_epochs):
            loss = self.train_step()
            print("Train Epoch {}: {}".format(epoch, loss))

trainer = Model()
trainer.train(5000)
```

**Any other info / logs**
Full log of the code above:

2019-10-15 15:23:07.768703: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-10-15 15:23:07.780261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:3b:00.0
2019-10-15 15:23:07.780892: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-15 15:23:07.782852: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-15 15:23:07.784779: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-10-15 15:23:07.785515: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-10-15 15:23:07.787842: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-10-15 15:23:07.790057: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-10-15 15:23:07.794875: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-15 15:23:07.796010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-15 15:23:07.796248: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-10-15 15:23:07.804370: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3200000000 Hz
2019-10-15 15:23:07.806385: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562d5b167670 executing computations on platform Host. Devices:
2019-10-15 15:23:07.806411: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-10-15 15:23:07.919879: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562d5b1ca830 executing computations on platform CUDA. Devices:
2019-10-15 15:23:07.919925: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-10-15 15:23:07.920755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:3b:00.0
2019-10-15 15:23:07.920810: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-15 15:23:07.920825: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-15 15:23:07.920837: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-10-15 15:23:07.920855: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-10-15 15:23:07.920867: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-10-15 15:23:07.920878: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-10-15 15:23:07.920894: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-15 15:23:07.921926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-15 15:23:07.921954: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-15 15:23:07.922826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-15 15:23:07.922841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-10-15 15:23:07.922853: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-10-15 15:23:07.923954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10312 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:3b:00.0, compute capability: 7.5)
2019-10-15 15:23:10.869688: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-15 15:23:12.622865: E tensorflow/stream_executor/cuda/ptxas_utils.cc:110] You are using ptxas 8.x, but TF requires ptxas 9.x (and strongly prefers >= 9.2.88).  Compilation of XLA kernels below will likely fail.

You do not need to update CUDA; cherry-picking the ptxas binary is sufficient.
2019-10-15 15:23:12.700955: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: ptxas exited with non-zero error code 65280, output: ptxas fatal   : Value 'sm_75' is not defined for option 'gpu-name'

Relying on driver to perform ptx compilation. This message will be only logged once.
2019-10-15 15:23:15.104683: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x562d5b1cdff0
2019-10-15 15:23:15.104819: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-10-15 15:23:15.436019: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-15 15:23:15.727354: F tensorflow/core/kernels/cuda_solvers.cc:99] Check failed: cublasCreate(&cublas_handle) == CUBLAS_STATUS_SUCCESS Failed to create cuBlas instance.
Aborted (core dumped)

**Comment by gadagashwini** [comment]
@DawyD, I tried on colab with Tf 2.0.0. It is working as expected please take a look at the [gist](https://colab.sandbox.google.com/gist/gadagashwini/78ce12516b50127ba4cf21df959063a7/untitled200.ipynb). Thanks!

**Comment by DawyD** [comment]
@gadagashwini, I know, that the code will work on colab and 99% of systems. The code is not the point of this issue. The point is, that if you have multiple installations of CUDA on the system, it is somehow unclear where the ptxas is loaded from.

**Comment by DawyD** [comment]
I found out that it truly loads the ptxas from /usr/local/bin completely ignoring the PATH and CUDA_HOME environment variables.

The workaround is to use create bin directory where we launch the python and link it to the $CUDA_HOME/bin bin directory.

**Comment by KANGRuipeng** [comment]
Mark

**Comment by lileicv** [comment]
Mark

**Comment by gadagashwini** [comment]
@DawyD, Thanks for the workaround. 
@KANGRuipeng and @lileicv  can you try the @DawyD's workaround and let us know if that helps. Thanks!

**Comment by kleyersoma** [comment]
> I found out that it truly loads the ptxas from /usr/local/bin completely ignoring the PATH and CUDA_HOME environment variables.
> 
> The workaround is to create a "bin" directory where we launch the python and link it to the $CUDA_HOME/bin directory.

Hello there, @DawyD could you please provide a more detailed explanation on how to do this new linked directory? Do I have to create a new env var?

**Comment by DawyD** [comment]
> > I found out that it truly loads the ptxas from /usr/local/bin completely ignoring the PATH and CUDA_HOME environment variables.
> > The workaround is to create a "bin" directory where we launch the python and link it to the $CUDA_HOME/bin directory.
> 
> Hello there, @DawyD could you please provide a more detailed explanation on how to do this new linked directory? Do I have to create a new env var?

Hi @kleyersoma. The workaround for this particular problem on unix-based machines is to link your cuda bin to your working directory. Go to the directory, where you launch your python code and create the link:
`ln -s /full/path/to/your/cuda/installation/bin .`
This sovles the problem. The point is that TF first tries to load the ptxas from ./bin directory, then from /usr/local/cuda/bin. Unfortunately, it completely ignores the environment variables (which I consider to be a bug).

**Comment by N0ciple** [comment]
Hello @DawyD 
I currently have the same problem as you did. There are several versions of CUDA installed on our GPU server, and since I am not sudo, I had to install CUDA in a custom directory. I guess you did the same.

I tried to create a symbolic link as you said, however tensorflow keeps ignoring the correct version of ptxas. Even physically copying the ptxas binary in a `bin` folder doesn't work either... Is there something I'm missing about the workaround you gave ?

Generally speaking, I guess there isn't a whole load of peoples complaining about the problem since, first, they have to had installed CUDA themselves, and then to carefully look at the logs to see the problem.

Nevertheless, I agree with you @DawyD I looks like a bug.

**Comment by angerson** [comment]
@cheshire Could this be a bug or miscommunication with the `pxtas` path loading code? It looks like the ptxas binary is supposed to load from the preferred CUDA root directory, but for these users it loads from the wrong place. Some of the logic is here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/gpu/asm_compiler.cc, e.g.:

```cpp
  string ptxas_path;
  auto env = tensorflow::Env::Default();
  for (const string& cuda_root :
       tensorflow::CandidateCudaRoots(options.preferred_cuda_dir)) {
    ptxas_path = tensorflow::io::JoinPath(cuda_root, "bin", "ptxas");
    VLOG(2) << "Looking for ptxas at " << ptxas_path;
    if (env->FileExists(ptxas_path).ok()) {
      break;
    }
  }
  TF_RETURN_IF_ERROR(env->FileExists(ptxas_path));
  VLOG(2) << "Using ptxas at " << ptxas_path;
```

**Comment by cheshire** [comment]
@angerson @DawyD TF does not read CUDA_HOME.
It is possible to check where asm_compiler looks by running with the environment variable `TF_CPP_VMODULE=asm_compiler=2`.
Basically at this point it will only look in the directory where CUDA is expected to be installed. I'm looking into feasibility/desirability of looking for ptxas under PATH, but as a workaround you can symlink ptxas into the directory where asm_compiler is looking.

**Comment by cheshire** [comment]
Ah apologies, I've missed the message above stating the workaround.
At the moment we are considering two possible fixes: either read the PATH variable and look for ptxas there, or try to figure out ptxas location from the locations of loaded shared objects (notably, `libcudart`)

**Comment by N0ciple** [comment]
> @angerson @DawyD TF does not read CUDA_HOME.
> It is possible to check where asm_compiler looks by running with the environment variable `TF_CPP_VMODULE=asm_compiler=2`.
> Basically at this point it will only look in the directory where CUDA is expected to be installed. I'm looking into feasibility/desirability of looking for ptxas under PATH, but as a workaround you can symlink ptxas into the directory where asm_compiler is looking.

Thanks for your answer @cheshire.
Very sorry if the following question looks dumb to you but I tried to run a simple job preceded by `export TF_CPP_VMODULE=asm_compiler=2` and I did not saw any additional ligne in the logs refering to the path the asm compiler was looking at.
Could you be more specific on how to do that ?

**Comment by cheshire** [comment]
@N0ciple `TF_CPP_VMODULE` simply states "print log messages with the file of a given name at a given verbosity level".
The file is called `asm_compiler` in a nightly version. If you have an earlier version, it was called `ptxas_utils`.

**Comment by FMalerba** [comment]
I'm having a similar issue where i get the same warning `You are using ptxas 8.x, but TF requires ptxas 9.x (and strongly prefers >= 9.2.88).  Compilation of XLA kernels below will likely fail.`
However when I run with the flag `TF_CPP_VMODULE=asm_compiler=2` I get this output:
`2020-05-20 14:57:36.735438: I tensorflow/stream_executor/gpu/asm_compiler.cc:169] Looking for ptxas at /usr/local/cuda-10.1/bin/bin/ptxas
2020-05-20 14:57:36.735500: I tensorflow/stream_executor/gpu/asm_compiler.cc:169] Looking for ptxas at /usr/local/cuda/bin/ptxas
2020-05-20 14:57:36.735521: I tensorflow/stream_executor/gpu/asm_compiler.cc:178] Using ptxas at /usr/local/cuda/bin/ptxas`
So it seems that when it's looking in cuda-10.1 it's going in the wrong dir (there is no cuda-10.1/bin/bin, the ptxas binary is in cuda-10.1/bin). Does anyone know how to fix this?

**Comment by kleyersoma** [comment]
> > > I found out that it truly loads the ptxas from /usr/local/bin completely ignoring the PATH and CUDA_HOME environment variables.
> > > The workaround is to create a "bin" directory where we launch the python and link it to the $CUDA_HOME/bin directory.
> > 
> > 
> > Hello there, @DawyD could you please provide a more detailed explanation on how to do this new linked directory? Do I have to create a new env var?
> 
> Hi @kleyersoma. The workaround for this particular problem on unix-based machines is to link your cuda bin to your working directory. Go to the directory, where you launch your python code and create the link:
> `ln -s /full/path/to/your/cuda/installation/bin .`
> This sovles the problem. The point is that TF first tries to load the ptxas from ./bin directory, then from /usr/local/cuda/bin. Unfortunately, it completely ignores the environment variables (which I consider to be a bug).

Thanks, it solved my problem!! Thanks!

**Comment by tootal** [comment]
mark, same problem.

**Comment by cheshire** [comment]
@tootal Could you open a new issue with a reproducer? For the original author the issue was fixed.

**Comment by DimChatz** [comment]
> > > I found out that it truly loads the ptxas from /usr/local/bin completely ignoring the PATH and CUDA_HOME environment variables.
> > > The workaround is to create a "bin" directory where we launch the python and link it to the $CUDA_HOME/bin directory.
> > 
> > 
> > Hello there, @DawyD could you please provide a more detailed explanation on how to do this new linked directory? Do I have to create a new env var?
> 
> Hi @kleyersoma. The workaround for this particular problem on unix-based machines is to link your cuda bin to your working directory. Go to the directory, where you launch your python code and create the link:
> `ln -s /full/path/to/your/cuda/installation/bin .`
> This sovles the problem. The point is that TF first tries to load the ptxas from ./bin directory, then from /usr/local/cuda/bin. Unfortunately, it completely ignores the environment variables (which I consider to be a bug).


I am sorry. I did this but all i got is : 
ln: failed to create symbolic link './bin': File exists

Do you know of another workaround @DawyD ?

**Comment by VickyRDK** [comment]
Can someone give a clear explanation on where to find the cuda path directory and the steps of the workaround ?

Will be much appreciated... Thank you

**Comment by tanzhenyu** [comment]
> > > I found out that it truly loads the ptxas from /usr/local/bin completely ignoring the PATH and CUDA_HOME environment variables.
> > > The workaround is to create a "bin" directory where we launch the python and link it to the $CUDA_HOME/bin directory.
> > 
> > 
> > Hello there, @DawyD could you please provide a more detailed explanation on how to do this new linked directory? Do I have to create a new env var?
> 
> Hi @kleyersoma. The workaround for this particular problem on unix-based machines is to link your cuda bin to your working directory. Go to the directory, where you launch your python code and create the link:
> `ln -s /full/path/to/your/cuda/installation/bin .`
> This sovles the problem. The point is that TF first tries to load the ptxas from ./bin directory, then from /usr/local/cuda/bin. Unfortunately, it completely ignores the environment variables (which I consider to be a bug).

This solves my problem and saves the day :-)

**Comment by Chaztikov** [comment]
> Hi @kleyersoma. The workaround for this particular problem on unix-based machines is to link your cuda bin to your working directory. Go to the directory, where you launch your python code and create the link:
> `ln -s /full/path/to/your/cuda/installation/bin .`
> This sovles the problem. The point is that TF first tries to load the ptxas from ./bin directory, then from /usr/local/cuda/bin. Unfortunately, it completely ignores the environment variables (which I consider to be a bug).

Hi, either @tanzhenyu or @DawyD  or anyone else available and willing to answer:
What directory would
"Go to the directory, where you launch your python code and create the link"
refer to? 
I am running Ubuntu 22.04, and 
which python3
gives
/usr/bin/python3
Is this the directory you're referring to?
If so, in my case I would do
ln -s /usr/local/cuda/bin /usr/bin/python3
Is that correct? Thanks.

**Comment by MuellerJY** [comment]
> > Hi, either @tanzhenyu or @DawyD or anyone else available and willing to answer: What directory would "Go to the directory, where you launch your python code and create the link" refer to? I am running Ubuntu 22.04, and which python3 gives /usr/bin/python3 Is this the directory you're referring to? If so, in my case I would do ln -s /usr/local/cuda/bin /usr/bin/python3 Is that correct? Thanks.
> 
> Hi @Chaztikov, the directory I was referring to, was the directory where you launch your python script, not the directory where the python executable is located. Anyway, in your case, the workaround wouldn't probably work as the TensorFlow 2.0 was primarily searching for CUDA installation in "/usr/local/cuda/bin", which is the directory you are referring to in the first place.

Sorry to bother you. I'm under Windows 10 OS and meet the following issues:
`Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only`
`Relying on driver to perform ptx compilation.`
`Modify $PATH to customize ptxas location.`
I've tried the method you recommended by using mklink cmd in Windows OS. However, warnings about do not disappear.
What should I do? 
Thanks for your attention!
