### ISSUE TITLE
Error: No OpKernel was registered to support Op 'NcclAllReduce'

### ISSUE THREAD

**Issue by PepeLotudo** [tensorflow/tensorflow#33656]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code/ but copy from the stock example (nothing out of the ordinary)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10 1903
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.0.0
- **Python version**: 3.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 10.0/7.6
- **GPU model and memory**: 4x GTX780ti 3GB each
- **Exact command to reproduce**: model_distributed.fit(X_train, y_train, epochs=4, batch_size=25)

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request. 4x GPUs are recognised. but failed to train. The train on the CPU works well, but then when moving to do it with the distributed strategy shows the error below. I've uninstalled and re-installed "pip install tensorflow-gpu" twice. Updated drivers. nothing seems to help. Code below. Any help will be highly appreciated. Thanks.

import time
import numpy as np
import tensorflow as tf

print(tf.__version__)

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

X_train = X_train / 255.
X_test = X_test / 255.

X_train = X_train.reshape(-1, 28*28)
X_test = X_test.reshape(-1, 28*28)

model_normal = tf.keras.models.Sequential()
model_normal.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))
model_normal.add(tf.keras.layers.Dropout(rate=0.2))
model_normal.add(tf.keras.layers.Dense(units=10, activation='softmax'))
model_normal.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

strategy = tf.distribute.MirroredStrategy()
print('Number of devices: {}'.format(strategy.num_replicas_in_sync))

with strategy.scope():
  model_distributed = tf.keras.Sequential([
      tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)),
      tf.keras.layers.Dropout(rate=0.2),
      tf.keras.layers.Dense(units=10, activation='softmax'),
      ])
  model_distributed.compile(loss='sparse_categorical_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

start_time = time.time()
model_normal.fit(X_train, y_train, epochs=4, batch_size=25)
print("Normal training took: {}".format(time.time() - start_time))

start_time = time.time()
model_distributed.fit(X_train, y_train, epochs=4, batch_size=25)
print("Distributed training took: {}".format(time.time() - start_time))

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

2019-10-24 07:50:25.464075: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2.0.0
2019-10-24 07:50:29.987980: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-10-24 07:50:30.090327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.15
pciBusID: 0000:01:00.0
2019-10-24 07:50:30.097223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.0455
pciBusID: 0000:02:00.0
2019-10-24 07:50:30.104573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.0845
pciBusID: 0000:03:00.0
2019-10-24 07:50:30.111754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.15
pciBusID: 0000:04:00.0
2019-10-24 07:50:30.118501: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-24 07:50:30.126709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3
2019-10-24 07:50:30.131151: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-10-24 07:50:30.809583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.15
pciBusID: 0000:01:00.0
2019-10-24 07:50:30.816475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.0455
pciBusID: 0000:02:00.0
2019-10-24 07:50:30.823594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.0845
pciBusID: 0000:03:00.0
2019-10-24 07:50:30.831552: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.15
pciBusID: 0000:04:00.0
2019-10-24 07:50:30.839507: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-24 07:50:30.848211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3
2019-10-24 07:50:32.420376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-24 07:50:32.465449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 2 3
2019-10-24 07:50:32.491610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N N N
2019-10-24 07:50:32.494431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N N N
2019-10-24 07:50:32.506160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2:   N N N N
2019-10-24 07:50:32.544545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3:   N N N N
2019-10-24 07:50:32.572199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2154 MB memory) -> physical GPU (device: 0, name: GeForce GTX 780 Ti, pci bus id: 0000:01:00.0, compute capability: 3.5)
2019-10-24 07:50:32.614321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 2154 MB memory) -> physical GPU (device: 1, name: GeForce GTX 780 Ti, pci bus id: 0000:02:00.0, compute capability: 3.5)
2019-10-24 07:50:32.670375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 2154 MB memory) -> physical GPU (device: 2, name: GeForce GTX 780 Ti, pci bus id: 0000:03:00.0, compute capability: 3.5)
2019-10-24 07:50:32.725417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 2154 MB memory) -> physical GPU (device: 3, name: GeForce GTX 780 Ti, pci bus id: 0000:04:00.0, compute capability: 3.5)
2019-10-24 07:50:33.211267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.15
pciBusID: 0000:01:00.0
2019-10-24 07:50:33.310413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.0455
pciBusID: 0000:02:00.0
2019-10-24 07:50:33.383430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.0845
pciBusID: 0000:03:00.0
2019-10-24 07:50:33.423598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.15
pciBusID: 0000:04:00.0
2019-10-24 07:50:33.446267: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-24 07:50:33.463455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3
2019-10-24 07:50:33.467760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-24 07:50:33.472212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 2 3
2019-10-24 07:50:33.475053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N N N
2019-10-24 07:50:33.478236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N N N
2019-10-24 07:50:33.481176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2:   N N N N
2019-10-24 07:50:33.486383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3:   N N N N
2019-10-24 07:50:33.492208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 2154 MB memory) -> physical GPU (device: 0, name: GeForce GTX 780 Ti, pci bus id: 0000:01:00.0, compute capability: 3.5)
2019-10-24 07:50:33.501615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:1 with 2154 MB memory) -> physical GPU (device: 1, name: GeForce GTX 780 Ti, pci bus id: 0000:02:00.0, compute capability: 3.5)
2019-10-24 07:50:33.510891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:2 with 2154 MB memory) -> physical GPU (device: 2, name: GeForce GTX 780 Ti, pci bus id: 0000:03:00.0, compute capability: 3.5)
2019-10-24 07:50:33.520186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:3 with 2154 MB memory) -> physical GPU (device: 3, name: GeForce GTX 780 Ti, pci bus id: 0000:04:00.0, compute capability: 3.5)
Number of devices: 4
Train on 60000 samples
Epoch 1/4
2019-10-24 07:50:35.783397: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2019-10-24 07:50:35.958561: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-24 07:50:35.963318: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-24 07:50:35.967782: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-24 07:50:35.974357: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
60000/60000 [==============================] - 10s 165us/sample - loss: 0.2815 - sparse_categorical_accuracy: 0.9183
Epoch 2/4
60000/60000 [==============================] - 8s 132us/sample - loss: 0.1353 - sparse_categorical_accuracy: 0.9603
Epoch 3/4
60000/60000 [==============================] - 8s 133us/sample - loss: 0.1052 - sparse_categorical_accuracy: 0.9674
Epoch 4/4
60000/60000 [==============================] - 8s 131us/sample - loss: 0.0841 - sparse_categorical_accuracy: 0.9741
Normal training took: 33.73987317085266
Train on 60000 samples
Epoch 1/4
   25/60000 [..............................] - ETA: 3:18:14Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Javier\Desktop\Personal files\VS\TensorFlow 2.0 Complete guide\distributed training.py", line 53, in <module>
    model_distributed.fit(X_train, y_train, epochs=4, batch_size=25)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 520, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\eager\function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\eager\function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node Adam/NcclAllReduce}}with these attrs: [reduction="sum", shared_name="c1", T=DT_FLOAT, num_devices=4]
Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>

         [[Adam/NcclAllReduce]] [Op:__inference_distributed_function_33245]
Press any key to continue . . .

**Comment by PepeLotudo** [comment]
Hi gadagashwini,

managed to get it to work if I replace "strategy = tf.distribute.MirroredStrategy()" with "strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())".

But the performance is way slower than doing it directly on the CPU.

When on CPU only: 39secs
When on GPU:1 only: 18.5 secs
When on tf.distribute.mirrorstrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce()): 65 secs
When on tf.distribute.mirrorstrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce(), device=GPU:1): 21 secs

All GPUs are the same. a bit confused why this is happening and wondering is getting it to work with the NCCL will make any difference.

I did implemented the tf.config.experimental.set_memory_growth(device=GPUdevice,enable=True)... all I noticed was the GPU memory was not allocated 100%. apart from that no difference.

Are you suggesting I create several logical GPUs inside one GPU? I want to be able to have better performance over 4x GPUs than a single one.

Regards,

**Comment by robieta** [comment]
```
2019-10-24 07:50:33.475053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0: N N N N
2019-10-24 07:50:33.478236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1: N N N N
2019-10-24 07:50:33.481176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2: N N N N
2019-10-24 07:50:33.486383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3: N N N N
```

TensorFlow logs device connectivity, and what this is saying is that there is no peer-to-peer connections on your GPUs. For reference on a 4xV100 cloud instance the topology is:
```
...] 0:   N Y Y Y
...] 1:   Y N Y Y
...] 2:   Y Y N Y
...] 3:   Y Y Y N
```

NCCL is Nvidia's library for cross device reduction. The main point is to take advantage of the peering connections and bypass the CPU / PCI, so even if you got it working (I suspect that you still have a misconfigured nccl, but unfortunately don't have time to debug your setup) I would expect that you would get similar performance to hierarchical copy because there's nothing a library can do but go through the host if there are no peering connections. A simple way to check this is with the tensorflow profiler (https://www.tensorflow.org/api_docs/python/tf/summary/trace_on?version=stable). If you see a giant block of reductions and cross device copies in the timeline, then you're probably device interconnect bound. Hope that helps.

**Comment by ymodak** [comment]
This is fixed latest tf-nightly. Thanks!

**Comment by gmoneymiller** [comment]
Hi.  I am getting the same error, yet I am using the tf-nightly.  The workaround works for me as well.

**Comment by hbellafkir** [comment]
`tf.distribute.MirroredStrategy()` uses NCCL in default. Apparently NCCL is not installed in your system, tha's why your have to change the call to `tf.distribute.mirrorstrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())`. See the documentation about `cross_device_ops` parameter [https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy](url). can you confirm?

**Comment by gmoneymiller** [comment]
I'll give it a try.

**Comment by rmothukuru** [comment]
@PepeLotudo,
With respect to [this comment](https://github.com/tensorflow/tensorflow/issues/33656#issuecomment-601958566), can you please confirm if the issue is resolved? If you face problems please check if you have installed **`NCCL`** as mentioned in [this comment](https://github.com/tensorflow/tensorflow/issues/33656#issuecomment-692710505). Thanks!

**Comment by PepeLotudo** [comment]
I dont know if it was fixed or not. Not using TF anymore. I moved to
pytorch.
Regards

**Comment by gmoneymiller** [comment]
I will test it this week.
