### ISSUE TITLE
GpuLaunchKernel errors with Internal: invalid device function

### ISSUE THREAD

**Issue by glaucimarfaleiro** [tensorflow/tensorflow#33696]
**System information**
- Windows 10
- TensorFlow GPU installed from PIP installer:
- TensorFlow version: 2.0.0
- Python version:  3.7.4
- CUDA/cuDNN version: 10.1
- GPU model and memory: Geforce GTX 1050 4GB

**Describe the current behavior**

I'm trying to run a facial recognition project and the message bellow appears

Using TensorFlow backend.

```
2019-10-24 14:32:44.154323: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-10-24 14:32:51.960166: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-10-24 14:32:52.321115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
2019-10-24 14:32:52.325985: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-24 14:32:52.331740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-24 14:32:52.335877: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-10-24 14:32:52.342803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
2019-10-24 14:32:52.346290: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-24 14:32:52.350583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-24 14:32:52.458458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-24 14:32:52.461435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-10-24 14:32:52.462925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-10-24 14:32:52.467353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3083 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-10-24 14:32:52.647343: F .\tensorflow/core/kernels/random_op_gpu.h:227] Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: invalid device function
```

**Comment by gowthamkpr** [comment]
Can you please provide the sequence of steps or a minimal code to reproduce this issue. Thanks!

**Comment by glaucimarfaleiro** [comment]
I trying to run this projetct
https://github.com/yu4u/age-gender-estimation.git

**Comment by gowthamkpr** [comment]
an you please try running the project on google colab and if see if you are encountering the same issue. Thanks!

**Comment by glaucimarfaleiro** [comment]
Here it goes

Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4479: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4479: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:190: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:190: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:197: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:197: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:203: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:203: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-10-24 20:30:03.809026: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-10-24 20:30:03.809331: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3c901c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-24 20:30:03.809372: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-10-24 20:30:03.814851: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-10-24 20:30:03.952342: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-24 20:30:03.953224: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3c90380 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2019-10-24 20:30:03.953256: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2019-10-24 20:30:03.954473: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-24 20:30:03.955200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
2019-10-24 20:30:03.962065: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-24 20:30:03.962146: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-24 20:30:04.052434: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-10-24 20:30:04.052667: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-10-24 20:30:04.052740: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-10-24 20:30:04.174903: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-10-24 20:30:04.175034: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-24 20:30:04.175183: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-24 20:30:04.175967: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-24 20:30:04.176739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-24 20:30:04.180762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-24 20:30:04.182365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-24 20:30:04.182402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-10-24 20:30:04.182418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-10-24 20:30:04.183538: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-24 20:30:04.184299: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-24 20:30:04.185021: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-10-24 20:30:04.185076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10805 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:207: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:207: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:216: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:216: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:223: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:223: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:2041: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:2041: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4271: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4271: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

VIDEOIO ERROR: V4L: can't open camera by index 0
Traceback (most recent call last):
  File "/content/age-gender-estimation/demo.py", line 138, in <module>
    main()
  File "/content/age-gender-estimation/demo.py", line 99, in main
    for img in image_generator:
  File "/content/age-gender-estimation/demo.py", line 60, in yield_images
    raise RuntimeError("Failed to capture image")
RuntimeError: Failed to capture image

**Comment by gowthamkpr** [comment]
Can you please share the github gist of the minimum reproducible example. Thanks!

**Comment by glaucimarfaleiro** [comment]
Unfortunately, this is not possible because the project has interdependent files.

**Comment by s2pstefan** [comment]
Replicates for me as well:

- Windows 10
- TensorFlow GPU installed from PIP installer:
- TensorFlow version: 2.0.0 (v2.0.0-rc2-26-g64c3d382ca)
- Python version: 3.7.3
- CUDA/cuDNN version: 10.1
- GPU model and memory: Geforce GTX 1080 6GB

Code:

```
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical


def network():
    model = Sequential()
    model.add(Dense(512, activation='relu', input_shape=((28*28),)))
    model.add(Dense(10, activation='softmax'))
    return model

def load_data():
    (training_images, training_labels), (test_images, test_labels) = mnist.load_data()

    training_images = training_images.reshape((60000, 28*28))
    training_images = training_images.astype('float32') / 255


    test_images = test_images.reshape((10000, 28 * 28))
    test_images = test_images.astype('float32') / 255

    training_labels = to_categorical(training_labels)
    test_labels = to_categorical(test_labels)

    return (training_images, training_labels), (test_images, test_labels)

def main():
    (training_images, training_labels), (test_images, test_labels) = load_data()
    network().compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    network().fit(training_images, training_labels, batch_size=128, epochs=5)

if __name__ == '__main__':
    main()

```

Logs:

Using TensorFlow backend.
2019-10-27 17:20:13.357299: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-10-27 17:20:14.819311: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-10-27 17:20:14.898322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:03:00.0
2019-10-27 17:20:14.898509: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-27 17:20:14.899011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-27 17:20:14.899295: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-10-27 17:20:14.902034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:03:00.0
2019-10-27 17:20:14.902229: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-27 17:20:14.902695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-27 17:20:14.989517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-27 17:20:14.989658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-10-27 17:20:14.989742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-10-27 17:20:14.990395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:03:00.0, compute capability: 6.1)
2019-10-27 17:20:15.255674: F .\tensorflow/core/kernels/random_op_gpu.h:227] Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: invalid device function

**Comment by s2pstefan** [comment]
I could reproduce the issue as well.

**System information**

- Windows 10
- TensorFlow GPU installed from PIP installer:
- TensorFlow version: 2.0.0
- Python version: 3.7.3
- CUDA/cuDNN version: 10.1
- GPU model and memory: Geforce GTX 1080 6GB

**Code**

```
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
print(1)
model.add(Dense(512, activation='relu', input_shape=((28 * 28),))) #crashes here
print(2) #not printed
```

Logs:

Using TensorFlow backend.
2019-10-27 18:19:50.390966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
1
2019-10-27 18:19:51.450798: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-10-27 18:19:51.525684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:03:00.0
2019-10-27 18:19:51.525870: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-27 18:19:51.526328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-27 18:19:51.526602: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-10-27 18:19:51.529355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:03:00.0
2019-10-27 18:19:51.529537: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-27 18:19:51.529999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-27 18:19:51.617783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-27 18:19:51.617918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-10-27 18:19:51.617997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-10-27 18:19:51.618650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:03:00.0, compute capability: 6.1)
2019-10-27 18:19:51.879458: F .\tensorflow/core/kernels/random_op_gpu.h:227] Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: invalid device function

**Comment by glaucimarfaleiro** [comment]
@s2pstefan, with you code, I had safe issue.

**Comment by gowthamkpr** [comment]
@s2pstefan I was not able to reproduce your error on colab. Heres my [github gist](https://colab.sandbox.google.com/gist/gowthamkpr/59ea8d13c80023f699328b7407b44fbb/untitled209.ipynb).

**Comment by s2pstefan** [comment]
Hi,

I see two issues with your test:

1. It does not use tensorflow-gpu
2. It does not run on Windows 10

I think this the error quite specific to this environment. Both @glaucimarfaleiro and myself were able to reproduce, given the correct setup.

**Comment by gowthamkpr** [comment]
I used tensorflow-gpu 2.0 but was not able to reproduce it. Heres ny [github gist](https://colab.sandbox.google.com/gist/gowthamkpr/3e9074efcea097b19009761df3be5cfd/untitled209.ipynb) I think this issue is specific to windows.

**Comment by s2pstefan** [comment]
Tensorflow should support windows.

From https://www.tensorflow.org/install:
TensorFlow is tested and supported on the following 64-bit systems: Ubuntu 16.04 or later, Windows 7 or later, macOS 10.12.6 (Sierra) or later (no GPU support), Raspbian 9.0 or later.

Not sure if you need more input from us, just let us know.

**Comment by s2pstefan** [comment]
Good news, it seems that this has been fixed in the latest tf-nighlty-gpu. @glaucimarfaleiro , can you please confirm?

**Comment by s2pstefan** [comment]
Good news, I tested again now and it seems that this issue has been fixed in the latest tf-nightly-gpu. @glaucimarfaleiro , can you please check as well?

**Comment by glaucimarfaleiro** [comment]
@s2pstefan, it worked with tf-nightly-gpu. Thanks a lot.

**Comment by fuckfrancisco** [comment]
I had this problem when compling TF 1.15.4 with --linkopt="/DEBUG:NONE" on windows
