### ISSUE TITLE
InternalError: Blas SGEMM launch failed : m=10, n=1, k=4 [Op:Conv2D] thrown when training Keras model with train_on_batch()

### ISSUE THREAD

**Issue by johan-andersson01** [tensorflow/tensorflow#33916]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 

    - `Yes`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
    - `Linux Ubuntu 18.04`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 

    - Docker image, `tensorflow/tensorflow:2.0.0-gpu-py3`
- TensorFlow version (use command below):

     - `v2.0.0-rc2-26-g64c3d38 2.0.0`

- Python version:

    - `3.6.8`

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
```

- GPU model and memory:

    - `GeForce GTX 960M, 2004MiB`

**Describe the current behavior**

When training a keras model with `train_on_batch()`, an InternalError is thrown (see stacktrace). Training the same model with `fit()` works.

**Describe the expected behavior**

No InternalError thrown and the attached code successfully executing.

**Code to reproduce the issue**

```
mkdir tf_issue
cp run.py tf_issue
docker run --gpus all -it  -v $(pwd)/tf_issue:/tf_issue tensorflow/tensorflow:2.0.0-gpu-py
python3 /tf_issue/run.py
```

(On my machine the above takes a few minutes when "setting up" Tensorflow, which is a bit ridiculous. But that's another issue)

```
## run.py ##
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras.optimizers import Adam

#tf.keras.backend.set_image_data_format("channels_first")

model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(filters=1, kernel_size=3, strides=2, input_shape=(224, 224, 3)))
model.add(tf.keras.layers.Conv2D(filters=1, kernel_size=3, strides=2))
model.add(tf.keras.layers.Conv2D(filters=1, kernel_size=3, strides=2))
model.add(tf.keras.layers.Conv2D(filters=1, kernel_size=3, strides=2))
model.add(tf.keras.layers.Conv2D(filters=1, kernel_size=3, strides=2))
model.add(tf.keras.layers.Conv2D(filters=1, kernel_size=3, strides=2))
model.add(tf.keras.layers.Conv2D(filters=1, kernel_size=2, strides=1, activation='sigmoid'))

model.compile( optimizer=Adam(), loss='binary_crossentropy')

model.summary()

gpu = tf.test.is_gpu_available()
print("GPU is available:", gpu)
assert(gpu)

batch_size = 10
x = np.random.random((batch_size, 224, 224, 3))
y = np.random.random((batch_size, 1, 1, 1))

print("x", x.shape)
print("y", y.shape)

y_pred = model.predict(x)
print("Predict successful: ", y_pred.shape)

print("Begin training with fit")
model.fit(x, y, epochs=10)
print("Fit successful")

print("Begin training with train_on_batch")
for i in range(10):
    model.train_on_batch(x, y)
print("On batch successful")
```

**Other info / logs**

Output and stack trace:

```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 111, 111, 1)       28        
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 55, 55, 1)         10        
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 27, 27, 1)         10        
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 13, 13, 1)         10        
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 6, 6, 1)           10        
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 2, 2, 1)           10        
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 1, 1, 1)           5         
=================================================================
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________
GPU is available: True
x (10, 224, 224, 3)
y (10, 1, 1, 1)
Predict successful:  (10, 1, 1, 1)
Begin training with fit
Train on 10 samples
Epoch 1/10

10/10 [==============================] - 1s 82ms/sample - loss: 0.6654
Epoch 2/10

10/10 [==============================] - 0s 870us/sample - loss: 0.6633
Epoch 3/10

10/10 [==============================] - 0s 882us/sample - loss: 0.6613
Epoch 4/10

10/10 [==============================] - 0s 1ms/sample - loss: 0.6594
Epoch 5/10

10/10 [==============================] - 0s 979us/sample - loss: 0.6574
Epoch 6/10

10/10 [==============================] - 0s 902us/sample - loss: 0.6555
Epoch 7/10

10/10 [==============================] - 0s 872us/sample - loss: 0.6536
Epoch 8/10

10/10 [==============================] - 0s 960us/sample - loss: 0.6517
Epoch 9/10

10/10 [==============================] - 0s 905us/sample - loss: 0.6498
Epoch 10/10

10/10 [==============================] - 0s 1ms/sample - loss: 0.6479
Fit successful
Begin training with train_on_batch
 not compiled to use: AVX2 FMA
2019-11-01 13:45:13.958471: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2019-11-01 13:45:13.959294: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4595560 executing computations on platform Host. Devices:
2019-11-01 13:45:13.959336: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-11-01 13:45:14.000846: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:14.001574: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x45973c0 executing computations on platform CUDA. Devices:
2019-11-01 13:45:14.001596: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 960M, Compute Capability 5.0
2019-11-01 13:45:14.001719: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:14.002377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.0975
pciBusID: 0000:01:00.0
2019-11-01 13:45:14.002406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-01 13:45:14.002417: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-01 13:45:14.002427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-11-01 13:45:14.002444: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-11-01 13:45:14.002454: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-11-01 13:45:14.002463: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-11-01 13:45:14.002473: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-01 13:45:14.002522: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:14.003154: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:14.003750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-01 13:45:14.003777: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-01 13:45:14.004647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-01 13:45:14.004660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-11-01 13:45:14.004667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-11-01 13:45:14.004779: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:14.005421: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:14.006043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1742 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2019-11-01 13:45:15.207106: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:15.207755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.0975
pciBusID: 0000:01:00.0
2019-11-01 13:45:15.207787: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-01 13:45:15.207801: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-01 13:45:15.207813: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-11-01 13:45:15.207824: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-11-01 13:45:15.207836: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-11-01 13:45:15.207847: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-11-01 13:45:15.207859: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-01 13:45:15.207910: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:15.208535: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:15.209130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-01 13:45:15.209154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-01 13:45:15.209161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-11-01 13:45:15.209168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-11-01 13:45:15.209276: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:15.209931: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-01 13:45:15.210556: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 1742 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2019-11-01 13:45:15.339203: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-01 13:45:17.264840: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-01 13:45:17.421437: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-11-01 13:45:17.421474: W tensorflow/stream_executor/stream.cc:1919] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "test_sample_weights.py", line 41, in <module>
    model.train_on_batch(x, y)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 973, in train_on_batch
    class_weight=class_weight, reset_metrics=reset_metrics)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_eager.py", line 311, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_eager.py", line 252, in _process_single_batch
    training=training))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_eager.py", line 127, in _model_loss
    outs = model(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/sequential.py", line 256, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/convolutional.py", line 197, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 1134, in __call__
    return self.conv_op(inp, filter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 238, in __call__
    name=self.name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 2010, in conv2d
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1031, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1130, in conv2d_eager_fallback
    ctx=_ctx, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=10, n=1, k=4 [Op:Conv2D]
```

Docker version:

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by johan-andersson01** [comment]
After some research into the error message `2019-11-01 13:45:17.421437: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED`, I tried adding the following to the start of `run.py` as specified in the [docs](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth):

```
physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```

The script then behaves as expected. But I suppose this still is an issue due to the different behaviours of `fit` and `train_on_batch`?

**Comment by oanush** [comment]
@johan-andersson01 ,
Can you please check this [comment](https://github.com/tensorflow/tensorflow/issues/27820#issuecomment-491014072) and let me know if it helps ?Thanks!

**Comment by johan-andersson01** [comment]
@oanush My laptop only has one GPU, so does that apply?

**Comment by ymodak** [comment]
[Limiting gpu memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) ,switching to single tensorflow process (avoid multiple tf process that consume gpu memory) is a good practice in situations like these. I will close this issue since this resolves your issue. Thanks!

**Comment by Alperen-KY** [comment]
Blas SGEMM launch failed : m=25600, n=16, k=32 [Op:Conv2D]

Did anyone solve the problem? 

_win10-gtx1660ti-python3.8-tf2.4-cuda11.0-cudnn8.1_

The all shell promt is:

C:\Users\KAYA\Desktop\Traffic Signs\RealTimeObjectDetection-main>python Tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_ssd_mobnet --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --num_train_steps=10000
2021-02-25 19:49:24.499158: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-02-25 19:49:28.301297: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-25 19:49:28.302373: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-02-25 19:49:28.334219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
2021-02-25 19:49:28.334365: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-02-25 19:49:28.345828: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-02-25 19:49:28.345948: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-02-25 19:49:28.350673: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-02-25 19:49:28.352197: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-02-25 19:49:28.362088: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-02-25 19:49:28.365249: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-02-25 19:49:28.366105: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-02-25 19:49:28.366283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-02-25 19:49:28.367151: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-25 19:49:28.369254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
2021-02-25 19:49:28.369432: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-02-25 19:49:28.369884: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-02-25 19:49:28.370665: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-02-25 19:49:28.371257: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-02-25 19:49:28.371741: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-02-25 19:49:28.372278: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-02-25 19:49:28.372908: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-02-25 19:49:28.373341: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-02-25 19:49:28.374574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-02-25 19:49:28.871044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-02-25 19:49:28.871193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-02-25 19:49:28.872214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2021-02-25 19:49:28.875582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4741 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021-02-25 19:49:28.876902: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0225 19:49:28.875259  1588 mirrored_strategy.py:350] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: 10000
I0225 19:49:28.875259  1588 config_util.py:552] Maybe overwriting train_steps: 10000
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0225 19:49:28.875259  1588 config_util.py:552] Maybe overwriting use_bfloat16: False
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.078698  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.080653  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.084666  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.085664  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.125950  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.129824  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.145821  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.146779  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.148811  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0225 19:49:29.149771  1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2021-02-25 19:49:30.502358: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-02-25 19:49:31.485765: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021-02-25 19:49:31.550024: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021-02-25 19:49:31.566173: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-02-25 19:49:31.985767: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2021-02-25 19:49:31.996015: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2021-02-25 19:49:31.996148: W tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 104, in main
    model_lib_v2.train_loop(
  File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\model_lib_v2.py", line 523, in train_loop
    dummy_prediction_dict = detection_model.predict(dummy_image, dummy_shapes)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\meta_architectures\ssd_meta_arch.py", line 570, in predict
    feature_maps = self._feature_extractor(preprocessed_inputs)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\meta_architectures\ssd_meta_arch.py", line 251, in call
    return self._extract_features(inputs)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\models\ssd_mobilenet_v2_fpn_keras_feature_extractor.py", line 219, in _extract_features
    image_features = self.classification_backbone(
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 424, in call
    return self._run_internal_graph(
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 560, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 248, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1013, in convolution_v2
    return convolution_internal(
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1143, in convolution_internal
    return op(
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2597, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 935, in conv2d
    return conv2d_eager_fallback(
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1024, in conv2d_eager_fallback
    _result = _execute.execute(b"Conv2D", 1, inputs=_inputs_flat, attrs=_attrs,
  File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=25600, n=16, k=32 [Op:Conv2D]

**Comment by Pamulapati13** [comment]
I had a similar issue.

> Blas SGEMM launch failed : m=25600, n=16, k=32 [Op:Conv2D]
> 
> Did anyone solve the problem?
> 
> _win10-gtx1660ti-python3.8-tf2.4-cuda11.0-cudnn8.1_
> 
> The all shell promt is:
> 
> C:\Users\KAYA\Desktop\Traffic Signs\RealTimeObjectDetection-main>python Tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_ssd_mobnet --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --num_train_steps=10000
> 2021-02-25 19:49:24.499158: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
> 2021-02-25 19:49:28.301297: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
> 2021-02-25 19:49:28.302373: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
> 2021-02-25 19:49:28.334219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
> pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
> coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
> 2021-02-25 19:49:28.334365: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
> 2021-02-25 19:49:28.345828: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
> 2021-02-25 19:49:28.345948: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
> 2021-02-25 19:49:28.350673: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
> 2021-02-25 19:49:28.352197: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
> 2021-02-25 19:49:28.362088: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
> 2021-02-25 19:49:28.365249: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
> 2021-02-25 19:49:28.366105: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
> 2021-02-25 19:49:28.366283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
> 2021-02-25 19:49:28.367151: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2021-02-25 19:49:28.369254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
> pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
> coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
> 2021-02-25 19:49:28.369432: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
> 2021-02-25 19:49:28.369884: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
> 2021-02-25 19:49:28.370665: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
> 2021-02-25 19:49:28.371257: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
> 2021-02-25 19:49:28.371741: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
> 2021-02-25 19:49:28.372278: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
> 2021-02-25 19:49:28.372908: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
> 2021-02-25 19:49:28.373341: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
> 2021-02-25 19:49:28.374574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
> 2021-02-25 19:49:28.871044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2021-02-25 19:49:28.871193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] 0
> 2021-02-25 19:49:28.872214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0: N
> 2021-02-25 19:49:28.875582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4741 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
> 2021-02-25 19:49:28.876902: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
> INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
> I0225 19:49:28.875259 1588 mirrored_strategy.py:350] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
> INFO:tensorflow:Maybe overwriting train_steps: 10000
> I0225 19:49:28.875259 1588 config_util.py:552] Maybe overwriting train_steps: 10000
> INFO:tensorflow:Maybe overwriting use_bfloat16: False
> I0225 19:49:28.875259 1588 config_util.py:552] Maybe overwriting use_bfloat16: False
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.078698 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.080653 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.084666 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.085664 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.125950 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.129824 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.145821 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.146779 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.148811 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> I0225 19:49:29.149771 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> 2021-02-25 19:49:30.502358: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
> 2021-02-25 19:49:31.485765: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0
> 
> 2021-02-25 19:49:31.550024: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0
> 
> 2021-02-25 19:49:31.566173: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
> 2021-02-25 19:49:31.985767: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2021-02-25 19:49:31.996015: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2021-02-25 19:49:31.996148: W tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
> Traceback (most recent call last):
> File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 113, in
> tf.compat.v1.app.run()
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\absl\app.py", line 300, in run
> _run_main(main, args)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
> sys.exit(main(argv))
> File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 104, in main
> model_lib_v2.train_loop(
> File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\model_lib_v2.py", line 523, in train_loop
> dummy_prediction_dict = detection_model.predict(dummy_image, dummy_shapes)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\meta_architectures\ssd_meta_arch.py", line 570, in predict
> feature_maps = self._feature_extractor(preprocessed_inputs)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in **call**
> outputs = call_fn(inputs, *args, **kwargs)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\meta_architectures\ssd_meta_arch.py", line 251, in call
> return self._extract_features(inputs)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\models\ssd_mobilenet_v2_fpn_keras_feature_extractor.py", line 219, in _extract_features
> image_features = self.classification_backbone(
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in **call**
> outputs = call_fn(inputs, *args, **kwargs)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 424, in call
> return self._run_internal_graph(
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 560, in _run_internal_graph
> outputs = node.layer(*args, **kwargs)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in **call**
> outputs = call_fn(inputs, *args, **kwargs)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 248, in call
> outputs = self._convolution_op(inputs, self.kernel)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
> return target(*args, **kwargs)
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1013, in convolution_v2
> return convolution_internal(
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1143, in convolution_internal
> return op(
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2597, in _conv2d_expanded_batch
> return gen_nn_ops.conv2d(
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 935, in conv2d
> return conv2d_eager_fallback(
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1024, in conv2d_eager_fallback
> _result = _execute.execute(b"Conv2D", 1, inputs=_inputs_flat, attrs=_attrs,
> File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
> tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=25600, n=16, k=32 [Op:Conv2D]

Hey @Alperen-KY , I had a similar issue and using this comment mentioned above helped me:
`physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)`

**Comment by Abdulrahman-Almutlaq** [comment]
> After some research into the error message `2019-11-01 13:45:17.421437: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED`, I tried adding the following to the start of `run.py` as specified in the [docs](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth):
> 
> ```
> physical_devices = tf.config.experimental.list_physical_devices('GPU')
> assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
> tf.config.experimental.set_memory_growth(physical_devices[0], True)
> ```
> 
> The script then behaves as expected. But I suppose this still is an issue due to the different behaviours of `fit` and `train_on_batch`?

Thank you very much, this solved the problem for me

**Comment by Alperen-KY** [comment]
> I had a similar issue.
> 
> > Blas SGEMM launch failed : m=25600, n=16, k=32 [Op:Conv2D]
> > Did anyone solve the problem?
> > _win10-gtx1660ti-python3.8-tf2.4-cuda11.0-cudnn8.1_
> > The all shell promt is:
> > C:\Users\KAYA\Desktop\Traffic Signs\RealTimeObjectDetection-main>python Tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_ssd_mobnet --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --num_train_steps=10000
> > 2021-02-25 19:49:24.499158: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
> > 2021-02-25 19:49:28.301297: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
> > 2021-02-25 19:49:28.302373: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
> > 2021-02-25 19:49:28.334219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
> > pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
> > coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
> > 2021-02-25 19:49:28.334365: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
> > 2021-02-25 19:49:28.345828: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
> > 2021-02-25 19:49:28.345948: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
> > 2021-02-25 19:49:28.350673: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
> > 2021-02-25 19:49:28.352197: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
> > 2021-02-25 19:49:28.362088: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
> > 2021-02-25 19:49:28.365249: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
> > 2021-02-25 19:49:28.366105: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
> > 2021-02-25 19:49:28.366283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
> > 2021-02-25 19:49:28.367151: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2
> > To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> > 2021-02-25 19:49:28.369254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
> > pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
> > coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
> > 2021-02-25 19:49:28.369432: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
> > 2021-02-25 19:49:28.369884: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
> > 2021-02-25 19:49:28.370665: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
> > 2021-02-25 19:49:28.371257: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
> > 2021-02-25 19:49:28.371741: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
> > 2021-02-25 19:49:28.372278: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
> > 2021-02-25 19:49:28.372908: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
> > 2021-02-25 19:49:28.373341: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
> > 2021-02-25 19:49:28.374574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
> > 2021-02-25 19:49:28.871044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
> > 2021-02-25 19:49:28.871193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] 0
> > 2021-02-25 19:49:28.872214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0: N
> > 2021-02-25 19:49:28.875582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4741 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
> > 2021-02-25 19:49:28.876902: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
> > INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
> > I0225 19:49:28.875259 1588 mirrored_strategy.py:350] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
> > INFO:tensorflow:Maybe overwriting train_steps: 10000
> > I0225 19:49:28.875259 1588 config_util.py:552] Maybe overwriting train_steps: 10000
> > INFO:tensorflow:Maybe overwriting use_bfloat16: False
> > I0225 19:49:28.875259 1588 config_util.py:552] Maybe overwriting use_bfloat16: False
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.078698 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.080653 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.084666 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.085664 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.125950 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.129824 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.145821 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.146779 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.148811 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > I0225 19:49:29.149771 1588 cross_device_ops.py:563] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
> > 2021-02-25 19:49:30.502358: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
> > 2021-02-25 19:49:31.485765: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0
> > 2021-02-25 19:49:31.550024: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0
> > 2021-02-25 19:49:31.566173: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
> > 2021-02-25 19:49:31.985767: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> > 2021-02-25 19:49:31.996015: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> > 2021-02-25 19:49:31.996148: W tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
> > Traceback (most recent call last):
> > File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 113, in
> > tf.compat.v1.app.run()
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
> > _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\absl\app.py", line 300, in run
> > _run_main(main, args)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
> > sys.exit(main(argv))
> > File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 104, in main
> > model_lib_v2.train_loop(
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\model_lib_v2.py", line 523, in train_loop
> > dummy_prediction_dict = detection_model.predict(dummy_image, dummy_shapes)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\meta_architectures\ssd_meta_arch.py", line 570, in predict
> > feature_maps = self._feature_extractor(preprocessed_inputs)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in **call**
> > outputs = call_fn(inputs, *args, **kwargs)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\meta_architectures\ssd_meta_arch.py", line 251, in call
> > return self._extract_features(inputs)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\object_detection\models\ssd_mobilenet_v2_fpn_keras_feature_extractor.py", line 219, in _extract_features
> > image_features = self.classification_backbone(
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in **call**
> > outputs = call_fn(inputs, *args, **kwargs)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 424, in call
> > return self._run_internal_graph(
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 560, in _run_internal_graph
> > outputs = node.layer(*args, **kwargs)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in **call**
> > outputs = call_fn(inputs, *args, **kwargs)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 248, in call
> > outputs = self._convolution_op(inputs, self.kernel)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
> > return target(*args, **kwargs)
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1013, in convolution_v2
> > return convolution_internal(
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1143, in convolution_internal
> > return op(
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2597, in _conv2d_expanded_batch
> > return gen_nn_ops.conv2d(
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 935, in conv2d
> > return conv2d_eager_fallback(
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1024, in conv2d_eager_fallback
> > _result = _execute.execute(b"Conv2D", 1, inputs=_inputs_flat, attrs=_attrs,
> > File "C:\Users\KAYA\anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
> > tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> > tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=25600, n=16, k=32 [Op:Conv2D]
> 
> Hey @Alperen-KY , I had a similar issue and using this comment mentioned above helped me:
> `physical_devices = tf.config.experimental.list_physical_devices('GPU')`
> `assert len(physical_devices) > 0, "Not enough GPU hardware devices available"`
> `tf.config.experimental.set_memory_growth(physical_devices[0], True)`

Thank you very much. I haven't been able to try again but I will.

**Comment by StatsGary** [comment]
Yes, that sorted it for me as well. Thanks, @skogsbrus for the original code snippet.
