### ISSUE TITLE
Tensorflow TensorRT: Could not load dynamic library 'libnvinfer.so.5'

### ISSUE THREAD

**Issue by maurera** [tensorflow/tensorflow#34329]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): Tensorflow 2.0
- Python version: 3.7.4
- CUDA/cuDNN version: 10.0
- GPU model and memory: V100

**Describe the current behavior**
_(Note - also posted to NVIDIA developer forums)_

I'm following the Tensorflow 2.0 [instructions](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#usage-example) for optimizing a SavedModel file with TensorRT. I have my Tensorflow model saved to models/mymodel. When I run the following:

```
from tensorflow.python.compiler.tensorrt import trt_convert as trt
converter = trt.TrtGraphConverterV2(input_saved_model_dir='models/mymodel')
converter.convert()
converter.save('models/mymodel_tensorrt')
```

I get the error (from second line):

> 2019-11-14 17:29:07.427738: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.5'; dlerror: libnvinfer.so.5: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/home/ubuntu/src/cntk/bindings/python/cntk/libs:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:
2019-11-14 17:29:07.427783: F tensorflow/compiler/tf2tensorrt/stub/nvinfer_stub.cc:49] getInferLibVersion symbol not found.
Aborted (core dumped)

Looking at the thread [here](https://devtalk.nvidia.com/default/topic/1036527/tensorrt/importerror-libnvinfer-so-4-cannot-open-shared-object-file-no-such-file-or-directory/), it seems like it may be an issue with needing to set LD_LIBRARY_PATH.

However, when I google setting the LD_LIBRARY_PATH, it seems only necessary when manually installing TensorRT from tar. I have not built/installed TensorRT separately and am just using what's bundled in with Tensorflow 2.0. 

**Describe the expected behavior**
The converter should run and save optimized model to 'models/mymodel_tensorrt'

**Comment by maurera** [comment]
I solved the problem. While it seems like some portion of tensorrt is bundled in with tensorflow-gpu, there are still installation steps required (see [installation under Ubuntu 18.04 (CUDA 10)](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_10)

I already had CUDA drivers installed (10.1). I ran the following code, without modifying version numbers, and this allowed me to successfully convert the model. I'm not sure if I needed to the "install NVIDIA driver", as I'm assuming that was already installed, as I had already been running tensorflow-gpu without issue.

```
# Add NVIDIA package repositories
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo apt-get update
wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
sudo apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
sudo apt-get update

# Install NVIDIA driver
sudo apt-get install --no-install-recommends nvidia-driver-418
# Reboot. Check that GPUs are visible using the command: nvidia-smi

# Install TensorRT. Requires that libcudnn7 is installed above.
sudo apt-get install -y --no-install-recommends libnvinfer5=5.1.5-1+cuda10.0 \
    libnvinfer-dev=5.1.5-1+cuda10.0
```

**Comment by ayadav10491** [comment]
It seems tensorrt library import was failing. Install tensorrt 
<https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html>

 -> Dowload and install tensorrt compatible with your cuda version. 
   <https://developer.nvidia.com/nvidia-tensorrt-6x-download>

 >sudo apt-get update
 >sudo apt-get install tensorrt
> sudo apt-get install python3-libnvinfer-dev (for python3)
>sudo apt-get install uff-converter-tf
>dpkg -l | grep TensorRT

**Comment by AhmadShaik** [comment]
If you are getting this error while running in jetson nano, 

Hi,

The error indicates that TensorFlow want to link TensorRT 5.0 library but your device already upgrades to 6.0.
Suppose you are using JetPack 4.3, so you need to update the TensorFlow link into v43.

We provide two TensorFlow version for JetPack 4.3 user now.

**TensorFlow 2.0**
`$ sudo pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v43 tensorflow-gpu
`
**TensorFlow 1.15**
`pip install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v43 tensorflow-gpu==1.15.0+nv19.12`

**Comment by quelibrio** [comment]
installing tensorflow-cpu solved the issue for me

**Comment by MalusJ** [comment]
For my case, I believe it means that you have the wrong version of library. libnvinfer.so.6 is located at 'TensorRT-*/lib' and the number 6 means tensorFlow is looking for the libvinfer of TensorRT6. So if it's "could not load dynamic library libnvinfer.so.5", it means that you need TensorRT 5 to run the code.

Same as above, if it is showing Could not load dynamic library 'libcudart.so.10.0', you need the library in cuda 10.0 to run the code.

So updating your tensorrt/Cuda/Cudnn to match your tensorflow version would help. Note that your tensorrt/cuda/cudnn version should also match each other.

**Comment by dtlam26** [comment]
Tensorflow has handled this in their [installation guide](https://www.tensorflow.org/install/gpu)
