### ISSUE TITLE
 Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by niccle27** [tensorflow/tensorflow#34518]
I researched that issue, but unfortunnately all i was able to find was a compatibility problems. i made sure to install exactly what was specified in the tensorflow gpu installation procedure. The only thing that is different is that i'm running the 430 nvidia driver (which was installed by asking to install the 418)

**System information**
- https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
- Ubuntu 18.04
- Tensorflow-gpu installed using pip 
- Tensorflow-gpu 2.0.0
- Python version: 3.6.8
- CUDA/cuDNN version: cuda 10.1 /cuDNN 7.6.5
- GPU model and memory: NVIDIA GeForce GTX 1050 Mobile  2Gb

**Describe the current behavior**
``` python
for image_path in TEST_IMAGE_PATHS:
  show_inference(detection_model, image_path)
```
``` python
Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
```
**Describe the expected behavior**
Expecting to show the image with rectangle for detected objects

**Code to reproduce the issue**
https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

I used the provided code and i'm getting this error while computing the block
 ``` python
for image_path in TEST_IMAGE_PATHS:
  show_inference(detection_model, image_path)
```

**Other info / logs**
 ``` python
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-18-c197149a2864> in <module>
      1 for image_path in TEST_IMAGE_PATHS:
----> 2   show_inference(detection_model, image_path)

<ipython-input-17-e474e557b383> in show_inference(model, image_path)
      4   image_np = np.array(Image.open(image_path))
      5   # Actual detection.
----> 6   output_dict = run_inference_for_single_image(model, image_np)
      7   # Visualization of the results of a detection.
      8   vis_util.visualize_boxes_and_labels_on_image_array(

<ipython-input-16-4110867dcb70> in run_inference_for_single_image(model, image)
      7 
      8   # Run inference
----> 9   output_dict = model(input_tensor)
     10 
     11   # All outputs are batches tensors.

~/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in __call__(self, *args, **kwargs)
   1079       TypeError: For invalid positional/keyword argument combinations.
   1080     """
-> 1081     return self._call_impl(args, kwargs)
   1082 
   1083   def _call_impl(self, args, kwargs, cancellation_manager=None):

~/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in _call_impl(self, args, kwargs, cancellation_manager)
   1119       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
   1120           list(kwargs.keys()), list(self._arg_keywords)))
-> 1121     return self._call_flat(args, self.captured_inputs, cancellation_manager)
   1122 
   1123   def _filtered_call(self, args, kwargs):

~/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1222     if executing_eagerly:
   1223       flat_outputs = forward_function.call(
-> 1224           ctx, args, cancellation_manager=cancellation_manager)
   1225     else:
   1226       gradient_name = self._delayed_rewrite_functions.register()

~/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    509               inputs=args,
    510               attrs=("executor_type", executor_type, "config_proto", config),
--> 511               ctx=ctx)
    512         else:
    513           outputs = execute.execute_with_cancellation(

~/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~/.local/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/batchnorm/mul_1 (defined at /home/niccle27/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
	 [[Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Switch_5/_970]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/batchnorm/mul_1 (defined at /home/niccle27/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_pruned_16931]

Function call stack:
pruned -> pruned
 ```

**Comment by niccle27** [comment]
``` python
physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```
Adding those lines just after importing the modules fixed the precedent issue. But i still cannot run , on jupyther, the kernel die: 

``` python
2019-11-23 21:33:10.370989: I tensorflow/stream_executor/cuda/cuda_driver.cc:830] failed to allocate 1.40G (1507524608 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```
Does anybody have a workarround this ?

**Comment by gadagashwini** [comment]
The code is working as expected with CPU version of Tensorflow. Please find the colab gist [here](https://colab.sandbox.google.com/gist/gadagashwini/c7ce19638ffb638e5b62374c28faa0e6/untitled270.ipynb).  Thanks!

**Comment by niccle27** [comment]
I haven't tried yet on the CPU, as i would like to be able use my GPU for training faster. Would it be possible to have a fix for it ? 

Thank you in advance

**Comment by toanphambk** [comment]
i have the same problem, with the same errortoo

**Comment by niccle27** [comment]
Still having the issue, even so i upgraded to latest cudnn package. Does anybody have a fix ?

**Comment by iatechicken** [comment]
Hope this helps. I was facing the similar issue with:
tensorlfow 2.0
CUDA 10.0
cuDNN 7.6.5

I downgraded to cuDNN 7.6.2 and my model is training now. I tried cuDNN 7.5.1 before cuDNN 7.6.2, but that complained that source was built with 7.6 + 

Also, you are on CUDA 10.1. I started with CUDA 10.2, but eventually decided to downgrade to CUDA 10.0 and it was working fine for smaller models until I hit the above error message with more robust CNNs.

**Comment by niccle27** [comment]
well, i tried to downgrade to cudnn 7.6.2 and CUDA 10.0, but the issue persist ... What configuration are you using to get this to work ?

**Comment by menatte** [comment]
I've the same issue. 

Latest tensorflow built from source (HEAD 55119aadc69d394047e5f75d514fb6488cd4adb4), Cuda 10.0, cudnn 7.6.5

**Comment by gowthamkpr** [comment]
@menatte Can you please downgrade to downgrade to cudnn 7.6.2 and let me know if it works. Thanks!

**Comment by niccle27** [comment]
I was able to get this to work by downgrading :

cudnn: 7.6.2.24-1+cuda10.0   
Driver Version: 430.50 
Tensorflow-gpu 1.14

That unfortunnately works for tensorflow only, the same error appear while using keras with the same backend

**Comment by azhuantou** [comment]
@niccle27 Thanks！

**Comment by azhuantou** [comment]
@niccle27 
Thanks!
It works by using tensorflow-gpu 1.14

**Comment by gowthamkpr** [comment]
@niccle27  I am closing this issue as it has been resolved. If you have any more concerns, please create an other issue and we can take a look at it. Thanks!

**Comment by yaswanth4512** [comment]
i need to use two class id's for this is it possible
