### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by xXNicolaXx** [tensorflow/tensorflow#34695]
I have TF 2.0 on Ubuntu 18.04 LTS.
My GPU is the Nvidia RTX 2070 with driver 440.33.01.
When I train a model everything is fine and it works correctly.
But after the model is saved as .h5 file and I load it back, I cannot predict anything and I got this log:

```
`Using TensorFlow backend.
2019-11-29 00:59:27.178674: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-11-29 00:59:27.220014: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.220381: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
2019-11-29 00:59:27.222887: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-29 00:59:27.259558: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-29 00:59:27.278651: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-11-29 00:59:27.284736: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-11-29 00:59:27.330947: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-11-29 00:59:27.359948: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-11-29 00:59:27.426684: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-29 00:59:27.426784: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.427108: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.427373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-29 00:59:27.427889: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-29 00:59:27.457927: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
2019-11-29 00:59:27.460601: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5169da0 executing computations on platform Host. Devices:
2019-11-29 00:59:27.460654: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-11-29 00:59:27.567015: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.567342: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x51fc6f0 executing computations on platform CUDA. Devices:
2019-11-29 00:59:27.567353: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2070, Compute Capability 7.5
2019-11-29 00:59:27.567459: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.567704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
2019-11-29 00:59:27.567727: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-29 00:59:27.567735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-29 00:59:27.567743: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-11-29 00:59:27.567749: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-11-29 00:59:27.567756: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-11-29 00:59:27.567763: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-11-29 00:59:27.567770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-29 00:59:27.567801: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.568059: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.568291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-29 00:59:27.568720: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-29 00:59:27.569778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-29 00:59:27.569787: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-11-29 00:59:27.569790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-11-29 00:59:27.570517: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.570901: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-29 00:59:27.571160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7225 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-11-29 00:59:30.035047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-29 00:59:30.389311: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-29 00:59:31.306557: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-11-29 00:59:31.307242: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-11-29 00:59:31.307791: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}}]]`

```

On Windows 10 it works correctly with the same loaded model. I tried also to downgrade TF to v. 1.14 but nothing changed.
I installed cuda with aptitude. The strange thing is that I can train a model but not load it.
This is my test code for load and test a model:

```
from keras.models import load_model

import cv2
from PIL import Image
from io import BytesIO
import numpy as np
import tensorflow as tf

modelN = load_model('../model/nvidiaModel.h5')
with open("../data/images/1574517989418963.jpg", "rb") as f:
    data = f.read()


def image_preprocess(image):
    image = cv2.cvtColor(image, cv2.COLOR_RGB2YUV)
    image = cv2.GaussianBlur(image, (3, 3), 0)
    image = cv2.resize(image, (200, 66))  # Image input size of the Nvidia model architecture
    image = (image / 127.5) - 1

    return image


image = Image.open(BytesIO(bytearray(data)))
image = np.asarray(image)
image = image_preprocess(image)
image = np.array([image])
steering_angle = str(modelN.predict_classes(image))
print(steering_angle)
```

**Comment by ravikyram** [comment]
@xXNicolaXx 

Can you help us with the supporting files to reproduce the issue in our environment. Thanks!

**Comment by xXNicolaXx** [comment]
> @xXNicolaXx
> 
> Can you help us with the supporting files to reproduce the issue in our environment. Thanks!

Yeah, for sure! Thank you!
This is my project link: [https://github.com/xXNicolaXx/AutoPilotServer/](url)
Under the "app" package, you can find the class testModel.py which load my trained model and try to predic a value taking an image from my "data" folder.
Under the "model" package, there is the file for start the training (keras_model.py).
If you need something else I will be glad to do everything possible for solving this issue!
Thanks again.

**Comment by ravikyram** [comment]
@xXNicolaXx 
can you please add the below lines of code and check.Use tf.keras instead of Keras
```
from tensorflow import keras
from tensorflow.keras.models import load_mode
```
Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/5dd8e139990c80ec08076311aa16e7dc/untitled431.ipynb). Is this the expected behavior?. Thanks!

**Comment by xXNicolaXx** [comment]
@ravikyram 
Hi,
thank you for your help.
I try to import tensorflow as you did in the code with:
`from tensorflow.keras.models import load_model`
and even if it's underline in red, because he didn't find the module, it load the class. (Another option is to call the function directly inside the code with `tf.keras.models.load_model('my_model.h5)`
Anyway, I still get this error.
But finally I find a solution for this, adding this code below(don't know why on Windows I don't need it:
```
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)
```
Now, it predicts the class with the loaded model.
Thank you so much for the support!
Have a nice day,
Nicola.

**Comment by sheila** [comment]
Thanks Nicola. It worked for me too.

**Comment by RoboEvangelist** [comment]
How about for C++?
I have the same problem, but in C++

**Comment by mohajer1373** [comment]
> @ravikyram
> Hi,
> thank you for your help.
> I try to import tensorflow as you did in the code with:
> `from tensorflow.keras.models import load_model`
> and even if it's underline in red, because he didn't find the module, it load the class. (Another option is to call the function directly inside the code with `tf.keras.models.load_model('my_model.h5)`
> Anyway, I still get this error.
> But finally I find a solution for this, adding this code below(don't know why on Windows I don't need it:
> 
> ```
> gpus = tf.config.experimental.list_physical_devices('GPU')
> if gpus:
>     try:
>         # Currently, memory growth needs to be the same across GPUs
>         for gpu in gpus:
>             tf.config.experimental.set_memory_growth(gpu, True)
>         logical_gpus = tf.config.experimental.list_logical_devices('GPU')
>         print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
>     except RuntimeError as e:
>         # Memory growth must be set before GPUs have been initialized
>         print(e)
> ```
> 
> Now, it predicts the class with the loaded model.
> Thank you so much for the support!
> Have a nice day,
> Nicola.

Thank you man, for the ResNets project, I added the piece of code before everything in resnet_run_loop.py file and worked well.
