### ISSUE TITLE
TensorFlow r0.9rc0 and r0.10rc0 cluster memory leak and core dump

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#3470]
### Environment info
Operating System: 
```
$ uname -svm
Linux #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

Installed version of CUDA and cuDNN: 
```
$ find /usr/lib -name libcud\*
/usr/lib/i386-linux-gnu/libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so.361.42
/usr/lib/i386-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libcudnn_static.a
/usr/lib/x86_64-linux-gnu/libcudnn_static_v5.a
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcudart.so.7.5.18
/usr/lib/x86_64-linux-gnu/libcudnn.so
/usr/lib/x86_64-linux-gnu/libcuda.so.361.42
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.0.5
/usr/lib/x86_64-linux-gnu/libcudart.so
/usr/lib/x86_64-linux-gnu/libcudart.so.7.5
/usr/lib/x86_64-linux-gnu/libcudadevrt.a
/usr/lib/x86_64-linux-gnu/libcudnn.so.5
/usr/lib/x86_64-linux-gnu/stubs/libcuda.so
/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libcudart_static.a
```

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

Built from source:
```
* No Google Cloud Platform support
* GPU support
* CUDA Compute Capability: 3.0, 3.5 and 5.2

printf '\n\nY\n\n\n/usr\n\n\n3.0,3.5,5.2\n' | ./configure
```

```
tensorflow-0.9.0rc0-py3-none-any.whl
```

```
0.9.0rc0
```

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

```
$ git rev-parse HEAD
2f5ca43750dcd052843fd02a841bf041c3958670
```

```
$ bazel version
...............
Build label: 0.2.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Apr 21 13:01:41 2016 (1461243701)
Build timestamp: 1461243701
Build timestamp as int: 1461243701
```

### Steps to reproduce
1. I'll provide a gist with an example and update.

### What have you tried?
1. Tried disabling summary and checkpoint restart.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

On 16 worker processes the memory consumption on the (single) PS process grows with >1MB/s. The worker processes also grows in memory size but not as much. My workers are only executing a sequence of "sess.run(..)" commands in the loop so I don't think its even possible to add stuff to the graph. We'll try to prove me wrong in the gist if I can get a usable repro.

### Update (TensorFlow r0.10 and debugging)

I just checked with the latest version of TensorFlow (r0.10) and it seems to leaks memory in the same way. Disclaimer: I used the TensorFlow package from TensorFlow.org but I have cuDNN 5 installed right now.

The TensorFlow package I used (in a Python 3.5 conda environment called `tf-r0.10`):

```
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl
$ pip install --upgrade $TF_BINARY_URL
```

1. I tried adding a `sess.graph.finalize()` and I got no exceptions, thus I make the assumption that the code does not create any new nodes in each iteration.

2. If I use the tmalloc from Ubuntu 16.04 (`libtcmalloc-minimal4`) the memory leak just got worse, but I did not get any output that I could try and examine why?

```
pre_window: source activate tf-r0.10 && export CUDA_VISIBLE_DEVICES='' LD_PRELOAD=/usr/lib/libtcmalloc_minimal_debug.so.4 HEAPPROFILE=/tmp/heapprofile HEAPCHECK=1
```

I can still reproduce the core dump with the `for _ in range(100)` change:

```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted (core dumped)
```

**Comment by concretevitamin** [comment]
Please do attach the repro snippet, the relevant logs, and please do perform debugging on your end first.

**Comment by hholst80** [comment]
https://gist.github.com/hholst80/84fb412660b0e2de03e47daec186d094

You will need a `.tmuxinator.yml` (and tmuxinator) to launch it:

```
name: cluster

# Runs before everything. Use it to start daemons etc.
pre: rm -rf log

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
pre_window: source activate tf-r0.9 && export CUDA_VISIBLE_DEVICES=''

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: ps

# Arrange panes in one of the five preset layouts:
# even-horizontal, even-vertical, main-horizontal, main-vertical, or tiled.

# If you have installed a GPU-compatible version of TensorFlow, the `ps` will also
# try to allocate GPU memory although it is not helpful. This could potentially
# crash the worker on the same machine as it has little to no GPU memory to
# allocate. To avoid this, you can prepend the previous command to start `ps`
# with: `CUDA_VISIBLE_DEVICES=''`

windows:
  - ps:
      layout: even-vertical
      panes:
              - python cluster.py --job_name=ps --task_index=0
              - sleep 5 && tensorboard --logdir log
  - worker0-3:
      layout: tiled
      panes:
              - python cluster.py --job_name=worker --task_index=0
              - python cluster.py --job_name=worker --task_index=1
              - python cluster.py --job_name=worker --task_index=2
              - python cluster.py --job_name=worker --task_index=3
  - worker4-7:
      layout: tiled
      panes:
              - python cluster.py --job_name=worker --task_index=4
              - python cluster.py --job_name=worker --task_index=5
              - python cluster.py --job_name=worker --task_index=6
              - python cluster.py --job_name=worker --task_index=7
  - worker8-11:
      layout: tiled
      panes:
              - python cluster.py --job_name=worker --task_index=8
              - python cluster.py --job_name=worker --task_index=9
              - python cluster.py --job_name=worker --task_index=10
              - python cluster.py --job_name=worker --task_index=11
  - worker12-15:
      layout: tiled
      panes:
              - python cluster.py --job_name=worker --task_index=12
              - python cluster.py --job_name=worker --task_index=13
              - python cluster.py --job_name=worker --task_index=14
              - python cluster.py --job_name=worker --task_index=15
```

**Comment by michaelisard** [comment]
mrry@ could you take a look at this or reassign?

**Comment by mrry** [comment]
Can you try the steps in [this documentation](http://stackoverflow.com/documentation/tensorflow/3883/how-to-debug-a-memory-leak-in-tensorflow#t=201607261538595171712) to narrow down the cause of the memory leak?

**Comment by hholst80** [comment]
I updated the issue.

**Comment by girving** [comment]
@mrry What are the next steps here?

**Comment by mrry** [comment]
Without a heap profile or a simple repro, there's not much more I can do.

@hholst80 I'm not familiar with tmuxinator, so I'm not sure if it is causing problems with producing a heap profile. Could you perhaps slim down the example so that you can create two processes from the command line, with no external dependencies?

**Comment by hholst80** [comment]
Run this in a script:

```
python cluster.py --job_name=ps --task_index=0 &
for $INDEX in `seq 0 15`; do
    python cluster.py --job_name=worker --task_index=$INDEX &
done
```

**Comment by mrry** [comment]
Thanks for those repro instructions! I've got it running locally and am seeing the leak in the parameter server. I'll keep this issue posted with updates....

**Comment by mrry** [comment]
An update: I was able to reproduce the memory leak with r0.10, and it seems to be due to an RPC stub object not being deleted correctly. This logic was changed just after r0.10 was branched, and it appears that the nightly code no longer has the same leak.

However, there's a second issue, which is related to the core dump you were seeing:

> 
> ```
> terminate called after throwing an instance of 'std::system_error'
>   what():  Resource temporarily unavailable
> Aborted (core dumped)
> ```

This is being caused by a **thread leak** in the distributed runtime. When I reproduced this and inspected a core dump, I found over 2000 threads blocked on a notification at the same point in the code, which is related to cleaning up after running a step. It appears that in some fraction of steps, at least one of the responses to these messages was being lost (or the request never made it to the remote server), which would leak a thread waiting on the response.

I have a workaround in preparation, and I'll send a PR soon.

**Comment by mrry** [comment]
An alternative and more plausible hypothesis for the "thread leak" I mentioned above: backpressure on the cleanup task would prevent these from completing in a timely manner. However, since the master doesn't block on the completion of that task before returning, a single client thread would be free to send more run requests, creating further cleanup tasks without bound. Since the worker service was only allowing a single cleanup task to complete at once, and the parameter server would be receiving cleanup tasks from all of the workers, this would create an unbounded number of threads in each master, eventually causing some of them to fail upon creating another thread.

There's a fix in PR #3757, which is under review now. I tested it locally, and it's been running for hours now on my local machine without failure. Can you try it and confirm that it works?

Thanks for persevering with this long-running issue!

**Comment by hholst80** [comment]
It seems by my rudimentary analysis to have improved the performance as well. Thank you very much @mrry for your work on this issue!

**Comment by mrry** [comment]
You're welcome, and I'm glad to hear it!
