### ISSUE TITLE
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by viswanath27** [tensorflow/tensorflow#34888]
[error_log.txt](https://github.com/tensorflow/tensorflow/files/3930650/error_log.txt)
Getting "Failed to get Convolution aglorithm" error 
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04**
- TensorFlow installed from (source or binary): **Binary [https://www.tensorflow.org/install/gpu](url)**
- TensorFlow version: **tensorboard==2.0.2, tensorflow-datasets==1.3.0, tensorflow-estimator==2.0.1, tensorflow-gpu==2.0.0, tensorflow-metadata==0.15.1**
- Python version: **Python 3.6.9**
- Installed using virtualenv? pip? conda?: **pip**
- Bazel version (if compiling from source): **Build label: 1.2.1**
- GCC/Compiler version (if compiling from source): **gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0** 
- CUDA/cuDNN version: 
**`nvidia-smi` command gives me CUDA version as 10.2 and `nvcc --version` command gives me Cuda compilation tools, release 9.1, V9.1.85**
- GPU model and memory: **GeForce GTX 1660 Ti/PCIe/SSE2  and Memory 15.6 GiB**

**Problem**
`tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.`

Earlier my GPU was not detected and had to go back and forth on drivers and CUDA library versions. I have followed the steps for Ubuntu 18.04 command set in Tensor Flow GPU installation site. I could detect the Graphics card, but having above issue. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I have run one of the image classification example give in TensorFlow tutorials and was getting the above error. I have attached the complete log. 

**Any other info / logs**
Included the logs and the code 
[image_classifier.txt](https://github.com/tensorflow/tensorflow/files/3930678/image_classifier.txt)
[error_log.txt](https://github.com/tensorflow/tensorflow/files/3930680/error_log.txt)

Stuck with this error and not able use the GPU for Tensor Flow computations with above system configuration. Please help me in this regard.

Thanks
Viswanath.B

**Comment by ymodak** [comment]
You may try limiting your gpu memory usage with ```set_memory_growth``` option.
See https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth
Put the following snippet on top of your code and execute again
```python
 import tensorflow as tf
 gpus= tf.config.experimental.list_physical_devices('GPU')
 tf.config.experimental.set_memory_growth(gpus[0], True)
```

**Comment by cirick** [comment]
I had this same issue. For me it was a mismatch in the cudnn toolkit version. If you scroll to the top above the traceback you might see something like `Loaded runtime CuDNN library: 7.5.1 but source was compiled with: 7.6.0`. 

So you need to make sure your CuDNN install is >7.6 which must be what TF2.0 needs. 
This gets you the PPA's and apt install commands to get 7.6: https://www.tensorflow.org/install/gpu

Then I found this script helpful to manage my cuda/cudnn installs now that I had multiple versions: 
https://github.com/phohenecker/switch-cuda
`source switch_cuda.sh 10.0`

I never found `set_memory_growth` to fix this issue, but once I had CUDA10 + CuDNN 7.6 and made sure my PATH and LD_LIBRARY_PATH were all correct with the switcher script it finally worked. Here is a very minimal fashion mnist that I used to verify the problem and fix. 

Note: Don't run this from a notebook at first. Notebooks can spin up their own path/environment. Make sure it runs as a standalone script from the command line first, then figure out the notebook. 
```python
import tensorflow as tf
import numpy as np
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
from tensorflow import keras

fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
train_images = train_images / 255.0
test_images = test_images / 255.0
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)

model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=2, padding='same', activation='relu', input_shape=(28,28,1)))
model.add(tf.keras.layers.MaxPooling2D(pool_size=2))
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(10, activation='softmax'))
model.summary()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(train_images, train_labels, batch_size=64, epochs=10, validation_data=(test_images, test_labels))

**Comment by viswanath27** [comment]
Hi Modak & Irick, 

Thank you for providing quick help on the issue I am facing. 

@ymodak , I tried to use the `set_memory_growth` but the issue is still persisting. 

@cirick , I have checked the cuda versions with the help of `source switch-cuda.sh` and `source switch-cuda.sh 9.0` commands. 

Error is not solved but changed though. 

Results for `source switch-cuda.sh` is below 
`$ source switch-cuda.sh`
`The following CUDA installations have been found (in '/usr/local'):`
`* cuda-9.0`
`* cuda-10.0`
`* cuda-10.1`
`* cuda-10.2`
`* cuda-9.0`

I have switched to latest version as 10.2 and Now the error turns to different one 

`2019-12-08 15:57:07.034647: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0`
`2019-12-08 15:57:07.195071: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7`
**`2019-12-08 15:57:07.492080: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR`**
**`2019-12-08 15:57:07.512555: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR`**
`2019-12-08 15:57:07.512627: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.`
`	 [[{{node sequential/conv2d/Conv2D}}]]`
`   64/60000 [..............................] - ETA: 13:29Traceback (most recent call last):`
`  File "2_test.py", line 27, in <module>
    model.fit(train_images, train_labels, batch_size=64, epochs=10, validation_data=(test_images, test_labels))`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit`
`    use_multiprocessing=use_multiprocessing)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
    total_epochs=epochs)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__`
`    result = self._call(*args, **kwds)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 520, in _call`
`    return self._stateless_fn(*args, **kwds)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__`
`    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call`
`    self.captured_inputs)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat`
`    ctx, args, cancellation_manager=cancellation_manager)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 511, in call`
`    ctx=ctx)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute`
`    six.raise_from(core._status_to_exception(e.code, message), None)`
`  File "<string>", line 3, in raise_from`
`tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.`
`	 [[node sequential/conv2d/Conv2D (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_distributed_function_983]`

`Function call stack:
distributed_function`

Attaching the log for your quick reference.
Is 9.0 suggested for by any case. 
[error1_log.txt](https://github.com/tensorflow/tensorflow/files/3936114/error1_log.txt)
[cuda_version.txt](https://github.com/tensorflow/tensorflow/files/3936115/cuda_version.txt)

**Comment by viswanath27** [comment]
Hi Guys,

Also posting details of the Nvidia driver and CUDA version details 
`vissu@vissu-Z390-M:~/graphics_card$ nvidia-smi`
`Sun Dec  8 16:15:58 2019       `
`+-----------------------------------------------------------------------------+`
`| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |`
`|-------------------------------+----------------------+----------------------+`
`| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |`
`| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |`
`|===============================+======================+======================|`
`|   0  GeForce GTX 166...  On   | 00000000:01:00.0  On |                  N/A |`
`|  0%   46C    P8    14W / 120W |   1097MiB /  5941MiB |      2%      Default |`
`+-------------------------------+----------------------+----------------------+`
                                                                   
`+-----------------------------------------------------------------------------+`


`| Processes:                                                       GPU Memory |`
`|  GPU       PID   Type   Process name                             Usage      |`
`|=============================================================================|`
`|    0      1023      G   /usr/lib/xorg/Xorg                            18MiB |`
`|    0      1212      G   /usr/bin/gnome-shell                          48MiB |`
`|    0      1423      G   /usr/lib/xorg/Xorg                           246MiB |`
`|    0      1568      G   /usr/bin/gnome-shell                         286MiB |`
`|    0      2068      G   ...quest-channel-token=4727398288044008870   493MiB |`
`+-----------------------------------------------------------------------------+`

Above command show CUDA is 10.2 but when I check with other commands

` nvcc --version | grep "release" | awk '{print $6}' | cut -c2- `
gives below results 
`9.0.176`
Also result for this command `cat /usr/local/cuda/version.txt` is `CUDA Version 9.0.176`
This is when I have choosen 9.0 using the above `source switch-cuda.sh` command 
also results of `dpkg -l | grep cuda` is below

`ii  cuda                                                        10.2.89-1                                       amd64        CUDA meta-package`
`ii  cuda-10-0                                                   10.0.130-1                                      amd64        CUDA 10.0 meta-package`
`ii  cuda-10-2                                                   10.2.89-1                                       amd64        CUDA 10.2 meta-package`
`ii  cuda-command-line-tools-10-0                                10.0.130-1                                      amd64        CUDA command-line tools`
`ii  cuda-command-line-tools-10-2                                10.2.89-1                                       amd64        CUDA command-line tools`
`ii  cuda-compat-10-1                                            418.87.01-1                                     amd64        CUDA Compatibility Platform`
`ii  cuda-compiler-10-0                                          10.0.130-1                                      amd64        CUDA compiler`
`ii  cuda-compiler-10-2                                          10.2.89-1                                       amd64        CUDA compiler`
`ii  cuda-cublas-10-0                                            10.0.130-1                                      amd64        CUBLAS native runtime libraries`
`ii  cuda-cublas-dev-10-0                                        10.0.130-1                                      amd64        CUBLAS native dev links, headers`
`ii  cuda-cudart-10-0                                            10.0.130-1                                      amd64        CUDA Runtime native Libraries`
`ii  cuda-cudart-10-2                                            10.2.89-1                                       amd64        CUDA Runtime native Libraries`
`ii  cuda-cudart-dev-10-0                                        10.0.130-1                                      amd64        CUDA Runtime native dev links, headers`
`ii  cuda-cudart-dev-10-2                                        10.2.89-1                                       amd64        CUDA Runtime native dev links, headers`
`ii  cuda-cufft-10-0                                             10.0.130-1                                      amd64        CUFFT native runtime libraries`
`ii  cuda-cufft-10-2                                             10.2.89-1                                       amd64        CUFFT native runtime libraries`
`ii  cuda-cufft-dev-10-0                                         10.0.130-1                                      amd64        CUFFT native dev links, headers`
`ii  cuda-cufft-dev-10-2                                         10.2.89-1                                       amd64        CUFFT native dev links, headers`
`ii  cuda-cuobjdump-10-0                                         10.0.130-1                                      amd64        CUDA cuobjdump`
`ii  cuda-cuobjdump-10-2                                         10.2.89-1                                       amd64        CUDA cuobjdump`
`ii  cuda-cupti-10-0                                             10.0.130-1                                      amd64        CUDA profiling tools interface.`
`ii  cuda-cupti-10-2                                             10.2.89-1                                       amd64        CUDA profiling tools runtime libs.`
`ii  cuda-cupti-dev-10-2                                         10.2.89-1                                       amd64        CUDA profiling tools interface.`
`ii  cuda-curand-10-0                                            10.0.130-1                                      amd64        CURAND native runtime libraries`
`ii  cuda-curand-10-2                                            10.2.89-1                                       amd64        CURAND native runtime libraries`
`ii  cuda-curand-dev-10-0                                        10.0.130-1                                      amd64        CURAND native dev links, headers`
`ii  cuda-curand-dev-10-2                                        10.2.89-1                                       amd64        CURAND native dev links, headers`
`ii  cuda-cusolver-10-0                                          10.0.130-1                                      amd64        CUDA solver native runtime libraries`
`ii  cuda-cusolver-10-2                                          10.2.89-1                                       amd64        CUDA solver native runtime libraries`
`ii  cuda-cusolver-dev-10-0                                      10.0.130-1                                      amd64        CUDA solver native dev links, headers`
`ii  cuda-cusolver-dev-10-2                                      10.2.89-1                                       amd64        CUDA solver native dev links, headers`
`ii  cuda-cusparse-10-0                                          10.0.130-1                                      amd64        CUSPARSE native runtime libraries`
`ii  cuda-cusparse-10-2                                          10.2.89-1                                       amd64        CUSPARSE native runtime libraries`
`ii  cuda-cusparse-dev-10-0                                      10.0.130-1                                      amd64        CUSPARSE native dev links, headers`
`ii  cuda-cusparse-dev-10-2                                      10.2.89-1                                       amd64        CUSPARSE native dev links, headers`
`ii  cuda-demo-suite-10-0                                        10.0.130-1                                      amd64        Demo suite for CUDA`
`ii  cuda-demo-suite-10-2                                        10.2.89-1                                       amd64        Demo suite for CUDA`
`ii  cuda-documentation-10-0                                     10.0.130-1                                      amd64        CUDA documentation`
`ii  cuda-documentation-10-2                                     10.2.89-1                                       amd64        CUDA documentation`
`ii  cuda-driver-dev-10-0                                        10.0.130-1                                      amd64        CUDA Driver native dev stub library`
`ii  cuda-driver-dev-10-2                                        10.2.89-1                                       amd64        CUDA Driver native dev stub library`
`ii  cuda-drivers                                                440.33.01-1                                     amd64        CUDA Driver meta-package`
`ii  cuda-gdb-10-0                                               10.0.130-1                                      amd64        CUDA-GDB`
`ii  cuda-gdb-10-2                                               10.2.89-1                                       amd64        CUDA-GDB`
`ii  cuda-gpu-library-advisor-10-0                               10.0.130-1                                      amd64        CUDA GPU Library Advisor.`
`ii  cuda-libraries-10-0                                         10.0.130-1                                      amd64        CUDA Libraries 10.0 meta-package`
`ii  cuda-libraries-10-2                                         10.2.89-1                                       amd64        CUDA Libraries 10.2 meta-package`
`ii  cuda-libraries-dev-10-0                                     10.0.130-1                                      amd64        CUDA Libraries 10.0 development meta-package`
`ii  cuda-libraries-dev-10-2                                     10.2.89-1                                       amd64        CUDA Libraries 10.2 development meta-package`
`ii  cuda-license-10-0                                           10.0.130-1                                      amd64        CUDA licenses`
`ii  cuda-license-10-2                                           10.2.89-1                                       amd64        CUDA licenses`
`ii  cuda-memcheck-10-0                                          10.0.130-1                                      amd64        CUDA-MEMCHECK`
`ii  cuda-memcheck-10-2                                          10.2.89-1                                       amd64        CUDA-MEMCHECK`
`ii  cuda-misc-headers-10-0                                      10.0.130-1                                      amd64        CUDA miscellaneous headers`
`ii  cuda-misc-headers-10-2                                      10.2.89-1                                       amd64        CUDA miscellaneous headers`
`ii  cuda-npp-10-0                                               10.0.130-1                                      amd64        NPP native runtime libraries`
`ii  cuda-npp-10-2                                               10.2.89-1                                       amd64        NPP native runtime libraries`
`ii  cuda-npp-dev-10-0                                           10.0.130-1                                      amd64        NPP native dev links, headers`
`ii  cuda-npp-dev-10-2                                           10.2.89-1                                       amd64        NPP native dev links, headers`
`ii  cuda-nsight-10-0                                            10.0.130-1                                      amd64        CUDA nsight`
`ii  cuda-nsight-10-2                                            10.2.89-1                                       amd64        CUDA nsight`
`ii  cuda-nsight-compute-10-0                                    10.0.130-1                                      amd64        NVIDIA Nsight Compute`
`ii  cuda-nsight-compute-10-2                                    10.2.89-1                                       amd64        NVIDIA Nsight Compute`
`ii  cuda-nsight-systems-10-2                                    10.2.89-1                                       amd64        NVIDIA Nsight Systems`
`ii  cuda-nvcc-10-0                                              10.0.130-1                                      amd64        CUDA nvcc`
`ii  cuda-nvcc-10-2                                              10.2.89-1                                       amd64        CUDA nvcc`
`ii  cuda-nvdisasm-10-0                                          10.0.130-1                                      amd64        CUDA disassembler`
`ii  cuda-nvdisasm-10-2                                          10.2.89-1                                       amd64        CUDA disassembler`
`ii  cuda-nvgraph-10-0                                           10.0.130-1                                      amd64        NVGRAPH native runtime libraries`
`ii  cuda-nvgraph-10-2                                           10.2.89-1                                       amd64        NVGRAPH native runtime libraries`
`ii  cuda-nvgraph-dev-10-0                                       10.0.130-1                                      amd64        NVGRAPH native dev links, headers`
`ii  cuda-nvgraph-dev-10-2                                       10.2.89-1                                       amd64        NVGRAPH native dev links, headers`
`ii  cuda-nvjpeg-10-0                                            10.0.130.1-1                                    amd64        NVJPEG native runtime libraries`
`ii  cuda-nvjpeg-10-2                                            10.2.89-1                                       amd64        NVJPEG native runtime libraries`
`ii  cuda-nvjpeg-dev-10-0                                        10.0.130.1-1                                    amd64        NVJPEG native dev links, headers`
`ii  cuda-nvjpeg-dev-10-2                                        10.2.89-1                                       amd64        NVJPEG native dev links, headers`
`ii  cuda-nvml-dev-10-0                                          10.0.130-1                                      amd64        NVML native dev links, headers`
`ii  cuda-nvml-dev-10-2                                          10.2.89-1                                       amd64        NVML native dev links, headers`
`ii  cuda-nvprof-10-0                                            10.0.130-1                                      amd64        CUDA Profiler tools`
`ii  cuda-nvprof-10-2                                            10.2.89-1                                       amd64        CUDA Profiler tools`
`ii  cuda-nvprune-10-0                                           10.0.130-1                                      amd64        CUDA nvprune`
`ii  cuda-nvprune-10-2                                           10.2.89-1                                       amd64        CUDA nvprune`
`ii  cuda-nvrtc-10-0                                             10.0.130-1                                      amd64        NVRTC native runtime libraries`
`ii  cuda-nvrtc-10-2                                             10.2.89-1                                       amd64        NVRTC native runtime libraries`
`ii  cuda-nvrtc-dev-10-0                                         10.0.130-1                                      amd64        NVRTC native dev links, headers`
`ii  cuda-nvrtc-dev-10-2                                         10.2.89-1                                       amd64        NVRTC native dev links, headers`
`ii  cuda-nvtx-10-0                                              10.0.130-1                                      amd64        NVIDIA Tools Extension`
`ii  cuda-nvtx-10-2                                              10.2.89-1                                       amd64        NVIDIA Tools Extension`
`ii  cuda-nvvp-10-0                                              10.0.130-1                                      amd64        CUDA nvvp`
`ii  cuda-nvvp-10-2                                              10.2.89-1                                       amd64        CUDA nvvp`
`ii  cuda-repo-ubuntu1804                                        10.0.130-1                                      amd64        cuda repository configuration files`
`ii  cuda-runtime-10-0                                           10.0.130-1                                      amd64        CUDA Runtime 10.0 meta-package`
`ii  cuda-runtime-10-2                                           10.2.89-1                                       amd64        CUDA Runtime 10.2 meta-package`
`ii  cuda-samples-10-0                                           10.0.130-1                                      amd64        CUDA example applications`
`ii  cuda-samples-10-2                                           10.2.89-1                                       amd64        CUDA example applications`
`ii  cuda-sanitizer-api-10-2                                     10.2.89-1                                       amd64        CUDA Sanitizer API`
`ii  cuda-toolkit-10-0                                           10.0.130-1                                      amd64        CUDA Toolkit 10.0 meta-package`
`ii  cuda-toolkit-10-2                                           10.2.89-1                                       amd64        CUDA Toolkit 10.2 meta-package`
`ii  cuda-tools-10-0                                             10.0.130-1                                      amd64        CUDA Tools meta-package`
`ii  cuda-tools-10-2                                             10.2.89-1                                       amd64        CUDA Tools meta-package`
`ii  cuda-visual-tools-10-0                                      10.0.130-1                                      amd64        CUDA visual tools`
`ii  cuda-visual-tools-10-2                                      10.2.89-1                                       amd64        CUDA visual tools`
`iU  libcudart9.1:amd64                                          9.1.85-3ubuntu1                                 amd64        NVIDIA CUDA Runtime Library`
`ii  libcudnn7                                                   7.4.1.5-1+cuda9.0                               amd64        cuDNN runtime libraries`
`ii  libnvinfer5                                                 5.1.5-1+cuda10.0                                amd64        TensorRT runtime libraries`
`ii  libnvinfer6                                                 6.0.1-1+cuda10.2                                amd64        TensorRT runtime libraries`
`ii  nv-tensorrt-repo-ubuntu1804-cuda10.2-trt6.0.1.8-ga-20191108 1-1                                             amd64        nv-tensorrt repository configuration files`
`iU  nvidia-cuda-doc                                             9.1.85-3ubuntu1                                 all          NVIDIA CUDA and OpenCL documentation`
`iU  nvidia-cuda-gdb                                             9.1.85-3ubuntu1                                 amd64        NVIDIA CUDA Debugger (GDB)`
`iU  nvidia-cuda-toolkit                                         9.1.85-3ubuntu1                                 amd64        NVIDIA CUDA development toolkit`

**Comment by viswanath27** [comment]
Hi Group, any work around here, stuck with this issue for a while.

**Comment by ymodak** [comment]
You need cuda 10.0 for TF 2.0 and your cuDNN version should be ```>=7.4.1```
See https://www.tensorflow.org/install/gpu#software_requirements

**Comment by viswanath27** [comment]
Hi Modak,
I have ensured that versions are matching as you mentioned above but still I have facing issue.

`2019-12-11 14:59:40.298600: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1`
`2019-12-11 14:59:40.456044: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:40.456342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.77`
`pciBusID: 0000:01:00.0`
`2019-12-11 14:59:40.489175: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0`
`2019-12-11 14:59:40.657288: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0`
`2019-12-11 14:59:40.728803: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0`
`2019-12-11 14:59:40.757395: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0`
`2019-12-11 14:59:40.943656: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0`
`2019-12-11 14:59:41.060736: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0`
`2019-12-11 14:59:41.553896: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7`
`2019-12-11 14:59:41.554229: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:41.555542: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:41.556574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0`
`2019-12-11 14:59:41.585149: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`
`2019-12-11 14:59:41.739272: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2904000000 Hz`
`2019-12-11 14:59:41.746819: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5c79c00 executing computations on platform Host. Devices:`
`2019-12-11 14:59:41.746892: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version`
`2019-12-11 14:59:41.895480: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:41.895800: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5c1ee50 executing computations on platform CUDA. Devices:`
`2019-12-11 14:59:41.895815: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1660 Ti, Compute Capability 7.5`
`2019-12-11 14:59:41.895935: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:41.896165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.77`
`pciBusID: 0000:01:00.0`
`2019-12-11 14:59:41.896204: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0`
`2019-12-11 14:59:41.896217: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0`
`2019-12-11 14:59:41.896227: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0`
`2019-12-11 14:59:41.896238: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0`
`2019-12-11 14:59:41.896248: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0`
`2019-12-11 14:59:41.896257: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0`
`2019-12-11 14:59:41.896269: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7`
`2019-12-11 14:59:41.896303: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:41.896543: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:41.896757: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0`
`2019-12-11 14:59:41.916107: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0`
`2019-12-11 14:59:41.938696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:`
`2019-12-11 14:59:41.938728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 `
`2019-12-11 14:59:41.938737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N `
`2019-12-11 14:59:41.970067: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:41.971719: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2019-12-11 14:59:41.972849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5269 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)`
`2019-12-11 14:59:50.411307: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0`
`2019-12-11 14:59:51.671797: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7`
`2019-12-11 14:59:54.084124: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR`
`2019-12-11 14:59:54.118009: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR`
`2019-12-11 14:59:54.118048: F tensorflow/core/kernels/conv_grad_input_ops.cc:1102] Check failed: stream->parent()->GetConvolveBackwardDataAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(stream->parent()), &algorithms) `

Will going back to TF 1.x verisons help. If I use tensorflow 2.0 wihtout gpu version things are working. But I wanted to leverage graphics card, but having issues in doing so. Let me know which TF 1.x version should be best to use along with above versions.

**Comment by viswanath27** [comment]
Got the issue fixed by installing the nightly build for tensorflow 2.0. 
`pip install tf-nightly`

Log shows up error related to conv2d fixed, possibly
`tf.keras`
`Export depthwise_conv2d in tf.keras.backend.`

Thanks for support.
Viswanath.B

**Comment by ymodak** [comment]
Glad it worked for you! Thanks for the update.

**Comment by wajeehulhassanvii** [comment]
> You may try limiting your gpu memory usage with `set_memory_growth` option.
> See https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth
> Put the following snippet on top of your code and execute again
> 
> ```python
>  import tensorflow as tf
>  gpus= tf.config.experimental.list_physical_devices('GPU')
>  tf.config.experimental.set_memory_growth(gpus[0], True)
> ```

It worked but not sure if it would limit the performance. Tried everything else though. Thank

**Comment by wajeehulhassanvii** [comment]
> You may try limiting your gpu memory usage with `set_memory_growth` option.
> See https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth
> Put the following snippet on top of your code and execute again
> 
> ```python
>  import tensorflow as tf
>  gpus= tf.config.experimental.list_physical_devices('GPU')
>  tf.config.experimental.set_memory_growth(gpus[0], True)
> ```

Something finally worked after two days of trying. Thank :)

**Comment by sebastianfast** [comment]
> > You may try limiting your gpu memory usage with `set_memory_growth` option.
> > See https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth
> > Put the following snippet on top of your code and execute again
> > ```python
> >  import tensorflow as tf
> >  gpus= tf.config.experimental.list_physical_devices('GPU')
> >  tf.config.experimental.set_memory_growth(gpus[0], True)
> > ```
> 
> Something finally worked after two days of trying. Thank :)

Thank you, it fixed it for me as well
