### ISSUE TITLE
sparse_matrix_sparse_matmul gives wrong result when run on GPU

### ISSUE THREAD

**Issue by chpohl** [tensorflow/tensorflow#34925]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.1.0-rc0
- **Python version**: 3.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.1.243
- **GPU model and memory**: Titan X
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
When using sparse matmul with 2 sparse matrices on GPU, the result is wrong (has bad indices and some entries are 0 that should not be). The code below fails with  

> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[256] = [0,0,0] is out of 
order. Many sparse ops require sorted indices.
>    Use `tf.sparse.reorder` to create a correctly ordered copy.

  The same code runs without any errors on CPU. 

### Source code / logs

```python
import tensorflow as tf
from tensorflow.python.ops.linalg.sparse import sparse


a = tf.random.uniform([5, 300, 200])
a = tf.nn.dropout(a, 0.5)
sa = tf.sparse.from_dense(a)
csr_sa = sparse.CSRSparseMatrix(sa)
smm = sparse.matmul(csr_sa, csr_sa, transpose_b=True)
smm = sparse.csr_sparse_matrix_to_sparse_tensor(smm._matrix, type=tf.dtypes.float32)
smm = tf.sparse.SparseTensor(indices=smm.indices, values=smm.values, dense_shape=smm.dense_shape)
mm = tf.linalg.matmul(a, a, transpose_b=True)
tf.debugging.assert_near(mm, tf.sparse.to_dense(smm))
```

**Comment by oanush** [comment]
Issue replicating when the code is run for TF- 2.1rc0 on GPU, kindly find [gist](https://colab.sandbox.google.com/gist/oanush/ed04be796abab02ae5728162de540f45/34925.ipynb) for the same. Works fine when run on CPU-[gist](https://colab.sandbox.google.com/gist/oanush/2597a2e5b62425631fbc8a2c009d9131/34925.ipynb).Thanks!

**Comment by sanjoy** [comment]
In case it helps, here are the operations that are executed on the GPU in the failing run.  I'd expect one or more of them to be breaking the "indices are sorted" invariant.

 * `BatchMatMulV2`
 * `Cast`
 * `CSRSparseMatrixToSparseTensor`
 * `Fill`
 * `GatherNd`
 * `GreaterEqual`
 * `Mul`
 * `NotEqual`
 * `RandomUniform`
 * `Shape`
 * `SparseMatrixSparseMatMul`
 * `SparseTensorToCSRSparseMatrix`
 * `Where`

**Comment by amahendrakar** [comment]
@chpohl,
Looks like the issue has been fixed. I was able to run the code on TF v2.3 without any error, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/9d0077ac5118cb0ece628dd16ceaa909/34925.ipynb). Thanks!

**Comment by penpornk** [comment]
I have verified that the issue is gone. I'm closing the issue. Please feel free to reopen it if there are further problems.
