### ISSUE TITLE
undeclared inclusion(s) in rule '@nccl_archive//:device_lib'

### ISSUE THREAD

**Issue by njzjz** [tensorflow/tensorflow#35122]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux centos 6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0
- Python version: 
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version: 10.0.130/7.6.4
- GPU model and memory:

**Describe the problem**

```
ERROR: /home/conda/.cache/bazel/_bazel_conda/6f8a02c56728b792c78882b32cc69e39/external/nccl_archive/BUILD.bazel:53:1: undeclared inclusion(s) in rule '@nccl_archive//:device_lib':
this rule is missing dependency declarations for the following files included by 'external/nccl_archive/src/collectives/device/max_f64_reduce.cu.cc':
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/cuda_runtime.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/crt/host_config.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/builtin_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/device_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/crt/host_defines.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/driver_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/vector_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/surface_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/texture_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/library_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/channel_descriptor.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/cuda_runtime_api.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/cuda_device_runtime_api.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/driver_functions.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/vector_functions.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/vector_functions.hpp'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/crt/common_functions.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/crt/math_functions.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/crt/math_functions.hpp'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/cuda_surface_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/cuda_texture_types.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/crt/device_functions.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/crt/device_functions.hpp'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/device_atomic_functions.h'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/device_atomic_functions.hpp'
  '/usr/local/cuda-10.0/targets/x86_64-linux/include/crt/device_double_functions.h'

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```bash
bazel build //tensorflow:libtensorflow_cc.so
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by njzjz** [comment]
Inspired by #32776 and https://github.com/tensorflow/tensorflow/commit/58b236b235ce57808c917feb19b9f895f628710c, I apply the following patch to resolve symbolic links, and it works.
```diff
diff --git a/third_party/gpus/cuda_configure.bzl b/third_party/gpus/cuda_configure.bzl
index af1bc96f00..2fd0bef286 100644
--- a/third_party/gpus/cuda_configure.bzl
+++ b/third_party/gpus/cuda_configure.bzl
@@ -373,8 +373,8 @@ def _cuda_include_path(repository_ctx, cuda_config):
             )
     inc_entries = []
     if target_dir != "":
-        inc_entries.append(target_dir)
-    inc_entries.append(cuda_config.cuda_toolkit_path + "/include")
+        inc_entries.append(str(repository_ctx.path(target_dir).realpath))
+    inc_entries.append(str(repository_ctx.path(cuda_config.cuda_toolkit_path + "/include").realpath))
     return inc_entries

 def enable_cuda(repository_ctx):
diff --git a/third_party/gpus/find_cuda_config.py b/third_party/gpus/find_cuda_config.py
index 39f2c21d3f..57067b3562 100644
--- a/third_party/gpus/find_cuda_config.py
+++ b/third_party/gpus/find_cuda_config.py
@@ -449,7 +449,7 @@ def find_cuda_config():
   cuda_version = os.environ.get("TF_CUDA_VERSION", "")
   base_paths = _list_from_env("TF_CUDA_PATHS",
                               _get_default_cuda_paths(cuda_version))
-  base_paths = [path for path in base_paths if os.path.exists(path)]
+  base_paths = [os.path.realpath(path) for path in base_paths if os.path.exists(path)]

   result = {}
   if "cuda" in libraries:
```

I don't know why others don't have this problem (only saw @shubham769 reported the problem), but the above solution should make sense.
