### ISSUE TITLE
Errors from `cuda_dnn.cc(1802): 'cudnnRNNForwardTraining...` or `cuda/cuda_dnn.cc(1959): 'cudnnRNNBackwardWeights...`

### ISSUE THREAD

**Issue by alewir** [tensorflow/tensorflow#35791]
**System information**
- Have I written custom code: no
- OS Platform: Windows 10
- TensorFlow installed from: binary
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python 3.6.8
- CUDA/cuDNN version: cuda_10.2.89_441.22_win10/cudnn-10.2-windows10-x64-v7.6.5.32
- GPU model and memory: Asus GeForxe GTX 980 Strix 4GB, Compute Capability 5.2
- nVidia driver: 441.87

![image](https://user-images.githubusercontent.com/3266706/72216802-14aaf900-3526-11ea-9cbd-a78f74b9e0d5.png)

**Describe the current behavior**

I'm just learning to use tensorflow. I've adapted some code from tutorials but during training getting any of 2 following errors in random epoch. Rarely it finishes without error...

**Other info / logs**
1. Either:

```
2020-01-11 22:24:39.258245: E tensorflow/stream_executor/dnn.cc:596] CUDNN_STATUS_INTERNAL_ERROR
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1959): 'cudnnRNNBackwardWeights
( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, input_desc.handles(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), output_desc.handles(), output_data.opaque(), workspace.opaque(), workspace.size(), rnn_desc.params_handle(), params_backprop_data->opaque(), reserve_space_data->opaque(), reserve_space_data->size())'
2020-01-11 22:24:39.259004: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at cudnn_rnn_ops.cc:1922 : Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 256, 256, 1, 256, 32, 256] 
2020-01-11 22:24:39.259641: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 256, 256, 1, 256, 32, 256] 
	 [[{{node gradients/CudnnRNN_grad/CudnnRNNBackprop}}]]
2020-01-11 22:24:39.260191: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Internal: {{function_node __inference___backward_cudnn_lstm_with_fallback_6848_7024_specialized_for_StatefulPartitionedCall_1_at___inference_distributed_function_9522}} {{function_node __inference___backward_cudnn_lstm_with_fallback_6848_7024_specialized_for_StatefulPartitionedCall_1_at___inference_distributed_function_9522}} Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 256, 256, 1, 256, 32, 256] 
	 [[{{node gradients/CudnnRNN_grad/CudnnRNNBackprop}}]]
	 [[StatefulPartitionedCall_1]]
2020-01-11 22:24:39.261943: I tensorflow/stream_executor/stream.cc:1990] [stream=000001EB81C23220,impl=000001EBF7EBD920] did not wait for [stream=000001EB81C231A0,impl=000001EBF7EBE3A0]
2020-01-11 22:24:39.262108: I tensorflow/stream_executor/stream.cc:4938] [stream=000001EB81C23220,impl=000001EBF7EBD920] did not memcpy host-to-device; source: 000001EB834B4180
2020-01-11 22:24:39.262270: E tensorflow/stream_executor/stream.cc:332] Error recording event in stream: Error recording CUDA event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2020-01-11 22:24:39.263052: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2020-01-11 22:24:39.263276: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
```

2. Or:

```
2020-01-12 08:21:48.672516: E tensorflow/stream_executor/dnn.cc:596] CUDNN_STATUS_INTERNAL_ERROR
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1802): 'cudnnRNNForwardTraining( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, input_desc.handles(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.handles(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
2020-01-12 08:21:48.674257: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2020-01-12 08:21:48.674423: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
2020-01-12 08:
Process finished with exit code -1073740791 (0xC0000409)
```

**Already tried**
- updating nvidia drivers, reinstalling cuda SDK, python, tensorflow
- downgrading to tensorflow 1.7 + cuda_10.0.130_411.31_win10 + cudnn-10.0-windows10-x64-v7.4.1.5
- burning GPU for a while to check stability

**Similar errors for**
cudnn-10.1-windows10-x64-v7.6.5.32 / cuda_10.1.243_426.00_win10
```
2020-01-12 15:56:23.613001: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2020-01-12 15:56:23.613167: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
2020
Process finished with exit code -1073740791 (0xC0000409)
```

**Describe the expected behavior**
tensorflow finishes training

**Code to reproduce the issue**
```
import datetime
import os

import pandas as pd
from numpy import reshape

import tensorflow as tf

EPOCHS = 500
BATCH_SIZE = 1000
TEST_SET_RATIO = 0.2

LEARNING_RATE = 0.001
DECAY = 5e-5
LOSS_FUNC = 'categorical_crossentropy'
DROPOUT = 0.2

L_AMOUNT = 2  # number of labels
RNN_SEQ_AMOUNT = 128  # number of RNN/LSTM sequence features
DNN_F_AMOUNT = 4  # number of DNN branch features

MIN_ACC_TO_SAVE_MODEL = 0.6


def create_model():
    # RNN
    rnn_input = tf.keras.layers.Input(shape=(RNN_SEQ_AMOUNT, 1))

    rnn = tf.keras.layers.LSTM(RNN_SEQ_AMOUNT, return_sequences=True)(rnn_input)
    rnn = tf.keras.layers.Dropout(DROPOUT)(rnn)
    rnn = tf.keras.layers.BatchNormalization()(rnn)

    rnn = tf.keras.layers.LSTM(RNN_SEQ_AMOUNT, return_sequences=True)(rnn)
    rnn = tf.keras.layers.Dropout(DROPOUT / 2)(rnn)
    rnn = tf.keras.layers.BatchNormalization()(rnn)

    rnn = tf.keras.layers.LSTM(RNN_SEQ_AMOUNT)(rnn)
    rnn = tf.keras.layers.Dropout(DROPOUT)(rnn)
    rnn = tf.keras.layers.BatchNormalization()(rnn)

    rnn_output = tf.keras.layers.Flatten()(rnn)

    # DNN
    dnn_input = tf.keras.layers.Input(shape=(DNN_F_AMOUNT,))

    dnn = tf.keras.layers.Dense(16, activation=tf.keras.activations.relu)(dnn_input)
    dnn = tf.keras.layers.Dense(8, activation=tf.keras.activations.relu)(dnn)

    dnn_output = tf.keras.layers.Dense(2, activation=tf.keras.activations.softmax)(dnn)

    # Concatenate above outputs
    combined_input = tf.keras.layers.Concatenate()([rnn_output, dnn_output])

    combined_nn = tf.keras.layers.Dense(128, activation=tf.keras.activations.relu)(combined_input)
    combined_nn = tf.keras.layers.Dense(64, activation=tf.keras.activations.relu)(combined_nn)

    combined_output = tf.keras.layers.Dense(units=L_AMOUNT, activation=tf.keras.activations.softmax)(combined_nn)

    # Model setup
    new_model = tf.keras.Model(inputs=[rnn_input, dnn_input], outputs=[combined_output])
    opt = tf.keras.optimizers.Adam(LEARNING_RATE,
                                   decay=DECAY)
    new_model.compile(optimizer=opt,
                      loss=LOSS_FUNC,
                      metrics=['accuracy'])

    print(new_model.summary())
    return new_model


class CustomModelCheckpoint(tf.keras.callbacks.ModelCheckpoint):
    def __init__(self, fp, monitor='val_loss', verbose=0, save_best_only=False, save_weights_only=False, mode='auto', save_freq='epoch', **kwargs):
        super().__init__(fp, monitor, verbose, save_best_only, save_weights_only, mode, save_freq, **kwargs)

    def on_epoch_end(self, epoch, logs=None):
        print("\n-------------------------------------------------------------------------------------------------------")
        print(f"epoch: {epoch}, training_acc: {round(float(logs['accuracy']), 4)}, validation_acc: {round(float(logs['val_accuracy']), 4)}")
        print("-------------------------------------------------------------------------------------------------------\n")

        if MIN_ACC_TO_SAVE_MODEL <= logs['accuracy']:
            super().on_epoch_end(epoch, logs)


if __name__ == '__main__':
    data_filename = 'train_2020-01-05_data.csv'
    print("Loading data file: %s" % data_filename)

    dataset = pd.read_csv('e:\\ml\\data\\training\\faulty\\%s' % data_filename, delimiter=',', header=None)
    dataset = dataset.drop(columns=[0, 1, 2, 3, 4, 5, 6]).values  # drop columns with additional information

    test_set_size = int(len(dataset) * TEST_SET_RATIO)
    print("Test set split at: %d" % test_set_size)

    train_data = dataset[:-test_set_size]
    test_data = dataset[-test_set_size:]  # use most recent data for testing

    rnn_tr_f = train_data[:, 0:RNN_SEQ_AMOUNT]
    rnn_ts_f = test_data[:, 0:RNN_SEQ_AMOUNT]

    combined_tr_l = train_data[:, RNN_SEQ_AMOUNT:RNN_SEQ_AMOUNT + L_AMOUNT]
    combined_ts_l = test_data[:, RNN_SEQ_AMOUNT:RNN_SEQ_AMOUNT + L_AMOUNT]

    dnn_tr_f = train_data[:, RNN_SEQ_AMOUNT + L_AMOUNT:]  # enhancement data is added in column after labels
    dnn_ts_f = test_data[:, RNN_SEQ_AMOUNT + L_AMOUNT:]

    rnn_tr_features = reshape(rnn_tr_f, (len(rnn_tr_f), RNN_SEQ_AMOUNT, 1))
    rnn_ts_features = reshape(rnn_ts_f, (len(rnn_ts_f), RNN_SEQ_AMOUNT, 1))

    # create model for combined RNN and DNN
    model = create_model()

    TRAINING_TIMESTAMP = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    model_name = "faulty_%s" % TRAINING_TIMESTAMP
    os.mkdir("e:\\ml\\models\\%s" % model_name)
    filepath = "e:\\ml\\models\\%s\\%s--{epoch:02d}-{val_accuracy:.3f}.model" % (model_name, model_name)
    checkpoint = CustomModelCheckpoint(filepath,
                                       monitor='val_accuracy',
                                       verbose=1,
                                       save_best_only=True,
                                       mode='max')

    log_dir = "e:\\ml\\logs\\fit\\" + model_name + ".model"
    tensorboard = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1, profile_batch=0)

    model.fit(x=[rnn_tr_features, dnn_tr_f],
              y=combined_tr_l,
              epochs=EPOCHS,
              shuffle=True,
              batch_size=BATCH_SIZE,
              validation_data=([rnn_ts_features, dnn_ts_f], combined_ts_l),
              callbacks=[checkpoint, tensorboard])
```

**DATA**

[train_2020-01-05_data.zip](https://github.com/tensorflow/tensorflow/files/4050437/train_2020-01-05_data.zip)

**Installed packages**

```
C:\WINDOWS\system32>pip list
Package              Version
-------------------- ----------
absl-py              0.9.0
astor                0.8.1
attrs                19.3.0
backcall             0.1.0
bleach               3.1.0
cachetools           4.0.0
certifi              2019.11.28
chardet              3.0.4
colorama             0.4.3
cycler               0.10.0
decorator            4.4.1
defusedxml           0.6.0
entrypoints          0.3
gast                 0.2.2
google-auth          1.10.0
google-auth-oauthlib 0.4.1
google-pasta         0.1.8
grpcio               1.26.0
h5py                 2.10.0
idna                 2.8
importlib-metadata   1.3.0
ipykernel            5.1.3
ipython              7.11.1
ipython-genutils     0.2.0
jedi                 0.15.2
Jinja2               2.10.3
json5                0.8.5
jsonschema           3.2.0
jupyter-client       5.3.4
jupyter-core         4.6.1
jupyterlab           1.2.4
jupyterlab-server    1.0.6
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
Markdown             3.1.1
MarkupSafe           1.1.1
matplotlib           3.1.2
mistune              0.8.4
more-itertools       8.0.2
nbconvert            5.6.1
nbformat             4.4.0
notebook             6.0.2
numpy                1.18.0
oauthlib             3.1.0
opt-einsum           3.1.0
pandas               0.25.3
pandocfilters        1.4.2
parso                0.5.2
patsy                0.5.1
pickleshare          0.7.5
pip                  19.3.1
prometheus-client    0.7.1
prompt-toolkit       3.0.2
protobuf             3.11.2
pyasn1               0.4.8
pyasn1-modules       0.2.8
Pygments             2.5.2
pyparsing            2.4.6
pyrsistent           0.15.6
python-dateutil      2.8.1
pytz                 2019.3
pywin32              227
pywinpty             0.5.7
pyzmq                18.1.1
requests             2.22.0
requests-oauthlib    1.3.0
rsa                  4.0
scipy                1.4.1
Send2Trash           1.5.0
setuptools           41.0.0
six                  1.13.0
statsmodels          0.10.2
tensorboard          2.1.0
tensorflow           2.1.0
tensorflow-estimator 2.1.0
termcolor            1.1.0
terminado            0.8.3
testpath             0.4.4
tornado              6.0.3
traitlets            4.3.3
urllib3              1.25.7
wcwidth              0.1.7
webencodings         0.5.1
Werkzeug             0.16.0
wheel                0.33.6
wrapt                1.11.2
zipp                 0.6.0
```

**Comment by ravikyram** [comment]
@alewir 
I have tried on colab with TF version 2.1.0-rc2 and was able to execute code successfully. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/ed4786d6fccb981dfde304f7201e4031/untitled563.ipynb). Thanks!

**Comment by alewir** [comment]
Hi, right, sometimes it finishes with a success although most of the cases it fails with any of above errors. I'm wondering if it isn't some GPU issue but it's hard to tell at this moment.

**Comment by enhany** [comment]
I can confirm the same error with TF 1.13 and 1.15.
The error raises only in Windows.
I tried to get this error in CentOS/Ubuntu with the same GPU - nothing.

**Comment by alewir** [comment]
@enhany may I ask you what GPU have you been using while getting the error? I'm wondering if the newer models from rtx 10XX and 20YY are affected...

**Comment by enhany** [comment]
@alewir  2070s

**Comment by jvishnuvardhan** [comment]
@alewir I don't see any issue with the code. I suspect root-cause is related to GPU cuda drivers or somethings related to them. `TF2.1` is built with cuda10.1 so please uninstall `cuda10.2`, unistall `TF2.1`, restart computer, install `cuda10.1`, install `TF2.1` and then test again. 

Please let us know how it progresses. Thanks!

**Comment by alewir** [comment]
I've did that (uninstalling everything from nvidia, wipeing out installation folders, cleaning registry from orphan paths) reinstalling everything as suggested by @jvishnuvardhan and... so far so good. I've run stable trainings thru-out the night and today. Usually it would fail for me already. I'll do some more testing and then I'll confirm if it's fully now stable.

**Comment by jvishnuvardhan** [comment]
@alewir Thanks for confirming the issue was resolved. Thanks again. I am closing it.

**Comment by faroit** [comment]
@jvishnuvardhan I get the same issue with similar code. Using tf2.1 on cuda 10.2 with driver 440.33.01. Interestingly this error only appears when all of the following settings

* under a strategy scope
* with more than one gpus
* when the sequence_length changes (e.g. going from train to test back to train)

any workaround?

**Comment by jvishnuvardhan** [comment]
@faroit Please create a new issue with details and a simple standalone code to reproduce the issue. Thanks!
