### ISSUE TITLE
Image retraining example: unable to run

### ISSUE THREAD

**Issue by cardshuffle** [tensorflow/tensorflow#3580]
### Environment info
Operating System: Ubuntu 14.04 LTS 64-bit

Installed version of CUDA and cuDNN: none (not using GPU)

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`): fc9162975e52978d3af38549b570cc3cc5f0ab66
2. The output of `bazel version`
```
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```
### Steps to reproduce
(instructions from [here](https://www.tensorflow.org/versions/r0.9/how_tos/image_retraining/index.html))
1. Run `cd ~`
2. Run `curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
tar xzf flower_photos.tgz`
3. Move to root of TensorFlow source directory
4. Run `bazel build tensorflow/examples/image_retraining:retrain`
5. Run `bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos`

### What have you tried?
1. The StackOverflow question [here](http://stackoverflow.com/questions/33622842/error-in-python-after-import-tensorflow-typeerror-init-got-an-unexpect) suggested uninstalling protobuf and reinstalling it with a version greater than or equal to 3.0.0a3. However, when I ran `pip uninstall protobuf`, I got this output:
`Can't uninstall 'protobuf'. No files were found to uninstall.`
I then tried to just run `pip install protobuf`, however, this was the output:
```
Requirement already satisfied (use --upgrade to upgrade): protobuf in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf)
Cleaning up...
```
I then tried to run `pip install 'protobuf>=3.0.0a3'` as suggested on the StackOverflow thread, but this was the output:
```
Downloading/unpacking protobuf>=3.0.0a3
  Downloading protobuf-3.0.0-py2.py3-none-any.whl (342kB): 342kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /usr/local/lib/python2.7/dist-packages (from protobuf>=3.0.0a3)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf>=3.0.0a3)
Installing collected packages: protobuf
  Found existing installation: protobuf 2.6.1
    Can't uninstall 'protobuf'. No files were found to uninstall.
  Can't roll back protobuf; was not uninstalled
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0.dist-info'

Storing debug log for failure in /home/me/.pip/pip.log
```
Some answers have suggested uninstalling and reinstalling TensorFlow along with protobuf, but I haven't tried that yet, since I wanted to avoid possibly messing anything up.

### Logs or other output that would be helpful
(output when I tried to run `bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos`)
```
Traceback (most recent call last):
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 78, in <module>
    import tensorflow as tf
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 16, in <module>2. 
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/core/framework/tensor_shape_pb2.py", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB2\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by JohnAllen** [comment]
Are you sure you have protobuf installed?

This output suggests you don't:

1. `Can't uninstall 'protobuf'. No files were found to uninstall`
2. `Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0.dist-info'` suggests it can't be installed for python 2.7

You can try to install with sudo.  Also, you can check what the output of ` import google.protobuf` is in the python interpreter of the version of python you're trying to install to (seems like it's `2.7`).  There shouldn't be any output actually.  That should not throw an error when you have it installed.

**Comment by cardshuffle** [comment]
My guess would be that I actually do have protobuf installed, as suggested by this when I ran `pip install 'protobuf>=3.0.0a3'`:
`Found existing installation: protobuf 2.6.1`
but neither uninstallation nor installation seem to work properly. 

As per your suggestion, I tried both `sudo apt-get install protobuf` and `sudo pip install protobuf`. The output of sudo pip is as follows:
```
Downloading/unpacking protobuf
  Downloading protobuf-2.6.1.tar.gz (188kB): 188kB downloaded
  Running setup.py (path:/tmp/pip_build_root/protobuf/setup.py) egg_info for package protobuf
    
    Installed /tmp/pip_build_root/protobuf/.eggs/google_apputils-0.4.2-py2.7.egg
    Searching for pytz>=2010
    Reading https://pypi.python.org/simple/pytz/
    Best match: pytz 2016.6.1
    Downloading https://pypi.python.org/packages/79/a7/74bf57f5b10bebb8e605dc277484bddc5559ad8cf5082c90fcd64ab5dcc6/pytz-2016.6.1-py2.7.egg#md5=3b1dd4a944e92e84a6510faf81abd655
    Processing pytz-2016.6.1-py2.7.egg
    Moving pytz-2016.6.1-py2.7.egg to /tmp/pip_build_root/protobuf/.eggs
    
    Installed /tmp/pip_build_root/protobuf/.eggs/pytz-2016.6.1-py2.7.egg
    Searching for python-gflags>=1.4
    Reading https://pypi.python.org/simple/python-gflags/
    Best match: python-gflags 3.0.5
    Downloading https://pypi.python.org/packages/1f/01/3ca6527f51b7ff26abb635d4e7e2fa8413c7cf191564cc2c1e535f50dec7/python-gflags-3.0.5.tar.gz#md5=0e3a06cb99b9883bf6abacc489f31297
    Processing python-gflags-3.0.5.tar.gz
    Writing /tmp/easy_install-TKfuvj/python-gflags-3.0.5/setup.cfg
    Running python-gflags-3.0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-TKfuvj/python-gflags-3.0.5/egg-dist-tmp-rkay2G
    zip_safe flag not set; analyzing archive contents...
    Moving python_gflags-3.0.5-py2.7.egg to /tmp/pip_build_root/protobuf/.eggs
    
    Installed /tmp/pip_build_root/protobuf/.eggs/python_gflags-3.0.5-py2.7.egg
    Searching for python-dateutil>=1.4
    Reading https://pypi.python.org/simple/python-dateutil/
    Best match: python-dateutil 2.5.3
    Downloading https://pypi.python.org/packages/b7/9f/ba2b6aaf27e74df59f31b77d1927d5b037cc79a89cda604071f93d289eaf/python-dateutil-2.5.3.zip#md5=52b3f339f41986c25c3a2247e722db17
    Processing python-dateutil-2.5.3.zip
    Writing /tmp/easy_install-O0nWd9/python-dateutil-2.5.3/setup.cfg
    Running python-dateutil-2.5.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-O0nWd9/python-dateutil-2.5.3/egg-dist-tmp-TXb00f
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    Moving python_dateutil-2.5.3-py2.7.egg to /tmp/pip_build_root/protobuf/.eggs
    
    Installed /tmp/pip_build_root/protobuf/.eggs/python_dateutil-2.5.3-py2.7.egg
    
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf)
Installing collected packages: protobuf
  Running setup.py install for protobuf
    Skipping installation of /usr/local/lib/python2.7/dist-packages/google/__init__.py (namespace package)
    
    Installing /usr/local/lib/python2.7/dist-packages/protobuf-2.6.1-py2.7-nspkg.pth
  Could not find .egg-info directory in install record for protobuf
Successfully installed protobuf
Cleaning up...
```
It says that protobuf was successfully installed, but I'm still getting the same error with `bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos`. It seems that the version installed is 2.6.1, which isn't the right version, but I can't upgrade it with `pip install 'protobuf>=3.0.0a3'` (it gives the same error).

Also, `sudo apt-get install protobuf` gives this output:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package protobuf
```
 `import google.protobuf` doesn't have any output in my interpreter (IPython Notebook).

**Comment by cardshuffle** [comment]
Also, `import tensorflow` in my interpreter gives a similar error to when I tried to run the bazel command:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-c653d7eaed8c> in <module>()
      4 from __future__ import print_function
      5 import numpy as np
----> 6 import tensorflow as tf
      7 from six.moves import cPickle as pickle
      8 from six.moves import range

/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22 
---> 23 from tensorflow.python import *

/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py in <module>()
     47 
     48 try:
---> 49   from tensorflow.core.framework.graph_pb2 import *
     50 except ImportError:
     51   msg = """%s\n\nError importing tensorflow.  Unless you are using bazel,

/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py in <module>()
     14 
     15 
---> 16 from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
     17 from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
     18 from tensorflow.core.framework import versions_pb2 as tensorflow_dot_core_dot_framework_dot_versions__pb2

/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/attr_value_pb2.py in <module>()
     14 
     15 
---> 16 from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
     17 from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
     18 from tensorflow.core.framework import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2

/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/tensor_pb2.py in <module>()
     14 
     15 
---> 16 from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
     17 from tensorflow.core.framework import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2
     18 

/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/tensor_shape_pb2.py in <module>()
     20   package='tensorflow',
     21   syntax='proto3',
---> 22   serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB/\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01\x62\x06proto3')
     23 )
     24 _sym_db.RegisterFileDescriptor(DESCRIPTOR)

TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by martinwicke** [comment]
Try `sudo pip install 'protobuf>=3.0.0a3'`. In your comment it looks like you have successfully installed protobuf 2.6.1, which is not what you want.

**Comment by cardshuffle** [comment]
It looks like that did the trick, though I also had to run `sudo pip install mock`. Thanks for your help!
