### ISSUE TITLE
Could not load dynamic library 'libnvinfer_plugin.so.6'

### ISSUE THREAD

**Issue by mjlbach** [tensorflow/tensorflow#35968]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): wheel
- TensorFlow version: 2.1.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip in virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Titan XP

**Describe the problem**
```
2020-01-16 20:21:32.912603: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6 

2020-01-16 20:21:32.912768: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6:  cannot open shared object file: No such file or directory 

2020-01-16 20:21:32.912782: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```
**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
import tensorflow
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
cuda-10-1/unknown,now 10.1.243-1 amd64 [installed]
cuda-command-line-tools-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-compiler-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cudart-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cudart-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cufft-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cufft-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cuobjdump-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cupti-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-curand-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-curand-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cusolver-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cusolver-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cusparse-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-cusparse-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-demo-suite-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-documentation-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-driver-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-drivers/unknown,now 440.33.01-1 amd64 [installed,automatic]
cuda-gdb-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-gpu-library-advisor-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-libraries-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-libraries-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-license-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-license-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-memcheck-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-misc-headers-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-npp-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-npp-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nsight-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nsight-compute-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nsight-systems-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvcc-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvdisasm-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvgraph-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvgraph-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvjpeg-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvjpeg-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvml-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvprof-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvprune-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvrtc-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvrtc-dev-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvtx-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-nvvp-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-repo-ubuntu1604/unknown,now 10.1.243-1 amd64 [installed,upgradable to: 10.2.89-1]
cuda-runtime-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-samples-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-sanitizer-api-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-toolkit-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-tools-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
cuda-visual-tools-10-1/unknown,now 10.1.243-1 amd64 [installed,automatic]
libcuda1-440/unknown,now 440.33.01-0ubuntu1 amd64 [installed,automatic]
libcudnn7/unknown,now 7.6.4.38-1+cuda10.1 amd64 [installed,upgradable to: 7.6.5.32-1+cuda10.2]
libcudnn7-dev/unknown,now 7.6.4.38-1+cuda10.1 amd64 [installed,upgradable to: 7.6.5.32-1+cuda10.2]
libnvinfer-dev/unknown,now 6.0.1-1+cuda10.1 amd64 [installed,upgradable to: 7.0.0-1+cuda10.2]
libnvinfer6/unknown,now 6.0.1-1+cuda10.1 amd64 [installed,upgradable to: 6.0.1-1+cuda10.2]
```

Note this doesn't occur on nightly

**Comment by AlexandreMarcotte** [comment]
I run into the same issue with slightly different system informations

**Comment by Catadanna** [comment]
Had the same issue on Linux, Ubuntu 18.04.3, when running in the console : 

`python -c; import keras;print(keras.__version__)`

The problem occurs when trying to import keras or tensorflow. I wonder if this is not related to the fact that Python2 has no more maintenance starting from 1st Jan 2020 ... I installed and use Python 3 but perhaps I must make some more updates ... to check.

**Comment by gnthibault** [comment]
This also arise when tensorflow-gpu is not installed, which is surprising

**Comment by Catadanna** [comment]
Found [this link](https://mc.ai/tensorflow-gpu-installation-on-ubuntu-18-04) with explication of how to install tensorflow-gpu on Linux. Is is really necessary?

**Comment by sharonwoo** [comment]
Almost exactly the same issue with fresh install of Ubuntu 18.04 LTS. 

I followed [this guide](https://www.pyimagesearch.com/2019/12/09/how-to-install-tensorflow-2-0-on-ubuntu/) almost to the letter but ran into issues with nvidia-drm, which I used tty3 to work around as suggested by one of the comments.

**Comment by Laksh47** [comment]
Try `ls /usr/local/cuda-10.0/lib64` or `ls /usr/local/cuda/lib64` and see if the libraries are found

and try exporting the path `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64`

Now try `tf.test.is_gpu_available()`

The above worked for me and my tensorflow-gpu version is 2.0

**Comment by mjlbach** [comment]
Just to reiterate, this is a problem with tensorflow 2.1, not nightly or 2.0. 

@gnthibault tensorflow and tensorflow-gpu now point to the same package as of 2.1

**Comment by jparr721** [comment]
Hi, just reporting that I too am seeing this same issue. Here's my system specs:

```
Kernel: 5.4.3-arch1-1 
CPU: Intel i9-9900K (16) @ 5.000GHz 
GPU: NVIDIA GeForce RTX 2070 Rev. A
```

```
$ pip freeze | grep tensorflow
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
```

**Comment by sharonwoo** [comment]
@mjlbach yes, reporting for tf 2.1. 

Downgraded back to 2.0 to get a working version of tf. Thought I would share in case anyone comes here looking for this issue after finally getting to ```pip install tensorflow-gpu``` after a few frazzled hours ironing out CUDA driver installation like I did. Sorry for the confusing wording, I have edited it.

**Comment by SalahAdDin** [comment]
I get the same problem, but because other reason:
```
2020-01-21 16:37:57.869790: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/lib/x86_64-linux-gnu/libnvinfer.so.6)
2020-01-21 16:37:57.870308: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/lib/x86_64-linux-gnu/libnvinfer.so.6)
```

It is because `GLIBC`.

**Comment by CMobley7** [comment]
I get the same problem as well. Had to downgrade to `2.0`.

**Comment by Catadanna** [comment]
I reinstalled Tensorflow 2.0 and Keras and now it works -- but not on Jupyter Notebook, where I get the same error when importing Tensorflow. Therefore I do not use Jupyter but other editors.

**Comment by sayakpaul** [comment]
I got the same error as well. When I downgraded to TensorFlow 2.0.0 (with `pip install tensorflow-gpu==2.0.0`) it solved the issue.

**Comment by SalahAdDin** [comment]
it is a warning, i found that [**TensorRT**](https://developer.nvidia.com/tensorrt) is a **nVidia** developed library to improve the _CNN_ performance, but i think it is not needed, I'm working with `tensorflow 2.0` in **Colab** and it is working very good.

You can find a tutorial here: https://medium.com/@ardianumam/installing-tensorrt-in-ubuntu-dekstop-1c7307e1dcf6

**Comment by gunan** [comment]
That is correct.
if you install tensorrt, the problem should go away.
But otherwise, TF should continue running.

**Comment by mjlbach** [comment]
Just to clarify, the install instructions for ubuntu 16.04 should be updated; there are several erros, one being that cuda-10-1 is the appropriate cuda package, the other is that  libnvinfer-plugin6=6.0.1-1+cuda10.1 is missing.

``` bash
# Add NVIDIA package repositories
# Add HTTPS support for apt-key
sudo apt-get install gnupg-curl
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.1.243-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_10.1.243-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo apt-get update
wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
sudo apt install ./nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
sudo apt-get update

# Install NVIDIA driver
# Issue with driver install requires creating /usr/lib/nvidia
sudo mkdir /usr/lib/nvidia
sudo apt-get install --no-install-recommends nvidia-418
# Reboot. Check that GPUs are visible using the command: nvidia-smi

# Install development and runtime libraries (~4GB)
sudo apt-get install --no-install-recommends \
    cuda-10-1 \
    libcudnn7=7.6.4.38-1+cuda10.1  \
    libcudnn7-dev=7.6.4.38-1+cuda10.1


# Install TensorRT. Requires that libcudnn7 is installed above.
sudo apt-get install -y --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1 \
    libnvinfer-dev=6.0.1-1+cuda10.1 \
    libnvinfer-plugin6=6.0.1-1+cuda10.1

```

**Comment by mjlbach** [comment]
See: https://github.com/tensorflow/docs/pull/1403

**Comment by mavengences** [comment]
Installing tensorflow-gpu==2.0 worked for me!

**Comment by mjlbach** [comment]
The solution isn't to downgrade tensorflow (there is no problem with tensorflow 2.1, just the install docs). Install the missing library:

``` bash
apt install libnvinfer-plugin6=6.0.1-1+cuda10.1
```
There is a PR to fix the docs.

**Comment by wllhf** [comment]
> This also arise when tensorflow-gpu is not installed, which is surprising
As tensorflow points to tensorflow-gpu now, uninstall tensorflow and install tensorflow-cpu if you are on a non GPU machine.

**Comment by kuppas** [comment]
I just verified GPU version is not installed and current TensorFlow details are
$  pip freeze | grep tensorflow
tensorflow==2.1.0
tensorflow-estimator==2.1.0

**Comment by TQuy** [comment]
> The solution isn't to downgrade tensorflow (there is no problem with tensorflow 2.1, just the install docs). Install the missing library:
> 
> ```shell
> apt install libnvinfer-plugin6=6.0.1-1+cuda10.1
> ```
> 
> There is a PR to fix the docs.

It leads to other error

> Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libnvinfer-plugin6

**Comment by mjlbach** [comment]
> > The solution isn't to downgrade tensorflow (there is no problem with tensorflow 2.1, just the install docs). Install the missing library:
> > ```shell
> > apt install libnvinfer-plugin6=6.0.1-1+cuda10.1
> > ```
> > 
> > 
> > There is a PR to fix the docs.
> 
> It leads to another error
> 
> > Reading package lists... Done
> > Building dependency tree
> > Reading state information... Done
> > E: Unable to locate package libnvinfer-plugin6

I don't know the specifics of your OS/package manager, but it is likely there is a conflicting package or you did not enable the right repos. This works on Ubuntu 16.04/18.04

**Comment by Black-Behemoth** [comment]
> > > The solution isn't to downgrade tensorflow (there is no problem with tensorflow 2.1, just the install docs). Install the missing library:
> > > ```shell
> > > apt install libnvinfer-plugin6=6.0.1-1+cuda10.1
> > > ```
> > > 
> > > 
> > > There is a PR to fix the docs.
> > 
> > 
> > It leads to another error
> > > Reading package lists... Done
> > > Building dependency tree
> > > Reading state information... Done
> > > E: Unable to locate package libnvinfer-plugin6
> 
> I don't know the specifics of your OS/package manager, but it is likely there is a conflicting package or you did not enable the right repos. This works on Ubuntu 16.04/18.04
Is is supposed to work on a system without NVidia card and hence without CUDA? And why would an NVidia-specific package be required in the first place? I am getting precisely the same error just importing tensorflow 2.1 from Ubuntu shell under Windows WSL. It goes away if I downgrade to tensorflow 2.0.

**Comment by mjlbach** [comment]
@Black-Behemoth Tensorflow 2.1 is no longer split into a gpu and non-gpu package

**Comment by Black-Behemoth** [comment]
> @Black-Behemoth Tensorflow 2.1 is no longer split into a gpu and non-gpu package

Does not explain why "import tensorflow" works in tensrflow 2.0 but attempts to invoke  a cuda library in tensorflow 2.1. On a laptop with an AMD card no less.

**Comment by giovp** [comment]
Had the same issue, agree with @gunan that tensorRT is not needed. 
Installing `conda install -c anaconda cudatoolkit=10.1` solved the issue.
I have cudnn 7.6.5

**Comment by Black-Behemoth** [comment]
> > @Black-Behemoth Tensorflow 2.1 is no longer split into a gpu and non-gpu package
> 
> Does not explain why "import tensorflow" works in tensrflow 2.0 but attempts to invoke a cuda library in tensorflow 2.1. On a laptop with an AMD card no less.

Quoting myself :D  to ad further that I have booted into MacOS, installed Homebrew and then tesnsorflow 2.1. "import tf" does not call for any libraries with *cuda* in their names there, so I see no reason why they should be needed in the first place on a machine without an NVidia card.

**Comment by viniciusribeiro-hotmart** [comment]
> That is correct.
> if you install tensorrt, the problem should go away.
> But otherwise, TF should continue running.

> @Black-Behemoth Tensorflow 2.1 is no longer split into a gpu and non-gpu package

And therefore it should give the user three Warnings whenever you use it on any computer without a Nvidia GPU? Feels odd to me indeed -- but then again -- what do I know.

Getting the same warnings here. (Intel gpu machine)

**Comment by david-waterworth** [comment]
I couldn't get this to work on Ubuntu 18.04 either - specifically the first part which is supposed to add the repo's didn't work (i.e. nothing added to /etc/apt/sources.list *) so everything else will clearly then fail.

What I ended up doing was to download the deb files directly from http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/

i.e. I located the version of libcudnn7, libcudnn7-dev, libnvinfer6, libnvinfer-dev, libnvinfer-plugin6 for my cuda version (which is 10.2 not 10.1 and I have driver 440 not 418 but it seems to be working) and installed them using `sudo apt install`

* I'm not a linux expert, I checked with `grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/` and the gnome gui tools.

**Comment by david-waterworth** [comment]
Some additional info I've discovered, the reason it failed for me (Ubuntu 18.04) is the step to install the key

> sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub

errors with 

> gpg: WARNING: unable to fetch URI http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub: Address family not supported by protocol

I'm not sure why, google suggest using http rather than https but that also fails. So I installed the key manually, i.e.

> wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
> sudo apt-key add 7fa2af80.pub

Also not sure if it's an error or warning but this probably should be done as the first step, installing `cuda-repo-ubuntu1604_10.1.243-1_amd64.deb` first generates a missing key message.

**Comment by joutsen** [comment]
@sharonwoo
I solved exactly the same problem by upgrading to CUDA 10.1 (both toolkit and CUDNN). I had CUDA 10.0 on Ubuntu 18.04.

**Comment by ai-starter** [comment]
I have the same problem. How to slove it?  Too many answers confuse me .Can someone summarize the solution to this problem?

**Comment by david-waterworth** [comment]
@ai-starter basically you need to upgrade to cuda 10.1 and install the correct version CUDNN and TensorRT libraries

You should be able to follow https://github.com/tensorflow/tensorflow/issues/35968#issuecomment-577329399

If it doesn't work this is what worked for me - I suspect what works may depend on what you currently have installed / how you installed it.

```
# install nvidia key
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo apt-key add 7fa2af80.pub

# add repo's
sudo bash -c 'echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /" > /etc/apt/sources.list.d/cuda.list'
sudo bash -c 'echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/machine-learning.list'

sudo apt-get update

# Install development and runtime libraries (~4GB)
sudo apt-get install --no-install-recommends \
    cuda-10-1 \
    libcudnn7=7.6.4.38-1+cuda10.1  \
    libcudnn7-dev=7.6.4.38-1+cuda10.1


# Install TensorRT. Requires that libcudnn7 is installed above.
sudo apt-get install -y --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1 \
    libnvinfer-dev=6.0.1-1+cuda10.1 \
    libnvinfer-plugin6=6.0.1-1+cuda10.1
```

**Comment by EdvardHolden** [comment]
I am experiencing the same issue with 'libnvinfer_plugin.so.6', even with cuda 10.1 and TensorRT 6.0.
However, 'tf.test.is_gpu_available()' yields True.

Might it be that the plugin doesn't come with the TensorRT installation?

**Comment by DuaneNielsen** [comment]
2 hours into troubleshooting this error.  What the hell is TensorRT and why do we even need it?  Seems like more trouble than it's worth to me.

**Comment by DuaneNielsen** [comment]
Ok, figured mine out.  Here's an outline of what i did.  I was running multiple TF versions, so I wanted to go the manual route.  I've had bad experiences with NVIDIA and Ubuntu nixing each others packages.

Checked https://www.tensorflow.org/install/source#tested_build_configurations for the versions required.

Downloaded local version of CUDA 10.1 from NVIDIA and ran the installer.  Carefully navigated the menus so that it only copied the files to /usr/local/cuda-10.1 directory  (ie: if it wanted to "help" me, i told it "no thanks").
Downloaded  cuDNN 7.6.5.32.tar.gz and tar xvf'd it to my download directory, it created a "cuda" directory
backed up /usr/local/cuda-10.1 by copying it
Copied the cuda/include/cudnn.h to /usr/local/cuda-10.1/include
Copied the contents of cuda/lib to /usr/local/cuda-10.1
Downloaded TensorRT 6 tarball
Extracted TensorRT 6 to my download directory.
Opened my .venv/bin/activate script

Added /usr/local/cuda-10.1 and TensorRT 6 to the LD_LIBRARY_PATH and EXPORT
```
LD_LIBRARY_PATH="/usr/local/cuda-10.1/lib64:/home/duane/Downloads/TensorRT-6.0.1.5/lib"
export LD_LIBRARY_PATH
```
then sourced the environment and ran

python
import tensorflow as tf
tf.test.is_gpu_available()

Wah lah...

2020-02-28 19:39:35.895538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/device:GPU:0 with 7386 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:08:00.0, compute capability: 7.5)

Then I went into my living room, sat on the lounge, drank a bottle of vodka, and passed out.

Now I feel much better :)

**Comment by behdadforghani-cbre** [comment]
I had to add --allow-downgrade flag to apt-get to install Tensorflow RT libnvinfer6. I.e.:

sudo apt-get install --no-install-recommends \
    cuda-10-1 \
    libcudnn7=7.6.4.38-1+cuda10.1  \
    libcudnn7-dev=7.6.4.38-1+cuda10.1

sudo apt-get install -y --allow-downgrades --no-install-recommends \
        libnvinfer6=6.0.1-1+cuda10.1 \
        libnvinfer-dev=6.0.1-1+cuda10.1 \
        libnvinfer-plugin6=6.0.1-1+cuda10.1

The problem went away.

**Comment by monikasoni** [comment]
I am using anaconda with Ububtu, as mentioned above 

- pip install tensorflow-gpu==2.0.0
- pip install tensorflow==2.0.0

worked for me too

**Comment by donalmadden** [comment]
> Just to clarify, the install instructions for Ubuntu 16.04 should be updated; there are several errors, one being that cuda-10-1 is the appropriate cuda package, the other is that libnvinfer-plugin6=6.0.1-1+cuda10.1 is missing.
> 
> ```shell
> # Add NVIDIA package repositories
> # Add HTTPS support for apt-key
> sudo apt-get install gnupg-curl
> wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.1.243-1_amd64.deb
> sudo dpkg -i cuda-repo-ubuntu1604_10.1.243-1_amd64.deb
> sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
> sudo apt-get update
> wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
> sudo apt install ./nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
> sudo apt-get update
> 
> # Install NVIDIA driver
> # Issue with driver install requires creating /usr/lib/nvidia
> sudo mkdir /usr/lib/nvidia
> sudo apt-get install --no-install-recommends nvidia-418
> # Reboot. Check that GPUs are visible using the command: nvidia-smi
> 
> # Install development and runtime libraries (~4GB)
> sudo apt-get install --no-install-recommends \
>     cuda-10-1 \
>     libcudnn7=7.6.4.38-1+cuda10.1  \
>     libcudnn7-dev=7.6.4.38-1+cuda10.1
> 
> 
> # Install TensorRT. Requires that libcudnn7 is installed above.
> sudo apt-get install -y --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1 \
>     libnvinfer-dev=6.0.1-1+cuda10.1 \
>     libnvinfer-plugin6=6.0.1-1+cuda10.1
> ```

Thanks so much - This worked perfectly on Ubuntu 19.10 for tensorflow 2.1.0 substituting Ubuntu 18.04 libs for the 16.04 ones above

**Comment by jchwenger** [comment]
@gunan:  @behdadforghani-cbre's solution to add `--allow-downgrades` to the last batch of installs solved the issue on two Ubuntu 18.04 machines, it might be good to add it to the [install page](https://www.tensorflow.org/install/gpu)? 
```
# Install TensorRT. Requires that libcudnn7 is installed above.
sudo apt-get install -y --allow-downgrades --no-install-recommends \
        libnvinfer6=6.0.1-1+cuda10.1 \
        libnvinfer-dev=6.0.1-1+cuda10.1 \
        libnvinfer-plugin6=6.0.1-1+cuda10.1
```

**Comment by rimdk** [comment]
I had the same issue and I solve it by adding cudatoolkit and cudnnin my environment. if you install tnsorflow with "pip install " the cudatoolkit and cudnn are not added automaticly, not like installing tensoflow with conda that add this libraries automaticlly.
so you need just to install cudatoolkit and cudnnin in your environement by the following command: 

conda install -c anaconda cudatoolkit=10.1 cudnn=7.6.4

**Comment by rimdk** [comment]
I had the same issue and I solve it by adding cudatoolkit and cudnnin my environment. if you install tnsorflow with "pip install " the cudatoolkit and cudnn are not added automatically, not like installing tensoflow with conda that add this libraries automatically.
so you need just to install cudatoolkit and cudnnin in your environment using the following command:

conda install -c anaconda cudatoolkit=10.1 cudnn=7.6.4

**Comment by gunan** [comment]
@lamberta PTAL. Looks like we may need to add tensorrt installation to our docs.

@reedwm I thought tensorrt was optional. Looks like our users are seeing problems if it is not installed?

**Comment by lamberta** [comment]
cc: @bixia1

**Comment by jchwenger** [comment]
Just to clarify: following the [steps](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101) to install TF2 on Ubuntu 18.04 I could make it work (GPU recognised), I just had the same error message as the original poster. TensorRT is indeed optional, but as the `--allow-downgrades` completed the install I thought it might be a nice addition.

@rmdk just to confirm, you say that you've done everything thru conda, sth like this:
```
conda install -c conda-forge tensorflow
conda install -c anaconda cudatoolkit=10.1 cudnn=7.6.4
```
And it worked? If so it might be worth adding it to the instructions.

**Comment by rimdk** [comment]
@jchwenger I installed all my invormnement using pip install, and when i tried to execute my program i had the same issue, so i added cudatoolkit=10.1 and cudnn=7.6.4 to my env using 
conda install -c anaconda cudatoolkit=10.1 cudnn=7.6.4, and it work for me.

**Comment by jchwenger** [comment]
@rimdk, grand, thank you!

**Comment by z3o7** [comment]
@behdadforghani-cbre's  solution to add --allow-downgrades , solved my issue in ubuntu 18.04

**Comment by dhiegomaga** [comment]
I think this thread summarizes very well what it's like working with cuda/tensorflow

**Comment by david-waterworth** [comment]
An additional problem I continuously encounter is the repo's mentioned in the installation guide will get updated with the newer version at some point but tensorflow requires a specific version. Hence once you get it working, in order to keep it working you really need to `hold` the installed packages (I'm specifically talking about apt on Linux). Otherwise next time you update packages it'll roll the cuda packages forward and break everything

**Comment by ARHassett** [comment]
Folks, I'm trying to run tensorflow from Google Colab, which can be found [here](https://colab.research.google.com/drive/1iJgo-mXyxUjtiVbjbExeYfib_MbcfolR)

I get as far as "Training", but when I start running the code I get the following:

`2021-02-02 16:40:50.077388: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-02-02 16:40:50.077542: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-02-02 16:40:50.077562: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.`


Any recommendations for solving this in this particular situation?

**Comment by sachinkmohan** [comment]
Make sure you have installed TensorRT and Cuda appropriately. This fixed my problem. 
I was trying to run on a conda environment where no TensorRT was installed. Later ran the same code on Jetson where everything was configured. Ran flawlessly!

**Comment by titusfx** [comment]
In my case is weird. I create a `virtualenv`, and I installed the requirements of my project. And my project worked for days. Then suddenly (with the same project). I'm getting this error, I've removed the `env/` folder and create it again, installed everything, and it worked. So, it seems something with a lib, not only a problem of `install what it is requested` on the terminal.
