### ISSUE TITLE
Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by abcdabcd987** [tensorflow/tensorflow#36025]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro, Kernel 5.3.18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `v2.1.0-rc2-17-ge5bf8de 2.1.0`
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Cuda 10.1, cuDNN 7.6.5
- GPU model and memory: RTX 2070 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Import a ResNet .pb model and run it. The following error will occur and whether setting `allow_growth` or not does not help:

```
2020-01-18 12:56:02.661655: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-01-18 12:56:02.666829: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/abcdabcd987/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/abcdabcd987/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/abcdabcd987/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
	 [[output/_3]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.
```

**Describe the expected behavior**

Run it successfully

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import os
import numpy as np
import tensorflow as tf

MODEL_PB_FILENAME = 'resnet_v1_50.pb'
INPUT_TENSOR_NAME = 'input:0'
OUTPUT_TENSOR_NAME = 'output:0'

def main():
    with tf.device('/GPU:0'):
        with tf.compat.v1.gfile.GFile(MODEL_PB_FILENAME, "rb") as f:
            graph_def = tf.compat.v1.GraphDef()
            graph_def.ParseFromString(f.read())
            g_in = tf.import_graph_def(graph_def, name="")

    config = tf.compat.v1.ConfigProto()
    # config.allow_soft_placement = True
    # config.log_device_placement = True
    # config.gpu_options.allow_growth = True

    sess = tf.compat.v1.Session(graph=g_in, config=config)

    batch_x = np.random.randn(1, 224, 224, 3);
    output = sess.run(
        OUTPUT_TENSOR_NAME,
        feed_dict={INPUT_TENSOR_NAME: batch_x})[0]
    print(output)
    print(tf.test.is_gpu_available())
    print('config', list(map(hex, config.SerializeToString())))


main()
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[test_tf.log](https://github.com/tensorflow/tensorflow/files/4081770/test_tf.log)

**Comment by Lasers67** [comment]
please check if enough memory on that particular GPU is available, sometimes this error occurs due to insufficient memory

**Comment by abcdabcd987** [comment]
@Lasers67 Thanks for the notice. I saw some people run into this issue because of OOM, but I'm not in this situation. `nvidia-smi` reports zero memory usage. The model, ResNet50, takes very few memory, especially when the batch size is one. And the same script runs on the same machine on other TensorFlow builds/versions.

**Comment by ymodak** [comment]
Can you please try setting `allow_growth`  option at the top of your code:
```python
import tensorflow as tf
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)

# your code 
```
Also what is your nvidia driver version?

**Comment by abcdabcd987** [comment]
Hi @ymodak, I tried `allow_growth`. It's the same.  The driver version is `440.44`.

**Comment by sanjoy** [comment]
Unfortunately I don't have easy access to an RTX 2070 so I cannot reproduce this error.

You said

> And the same script runs on the same machine on other TensorFlow builds/versions.

What other builds did you try?  And does this work on tf-nightly?

**Comment by cshimmin** [comment]
Hello, I was having the same issue when instantiating a relatively small network on an RTX 2080 8GB. @ymodak's suggestion of setting `allow_growth=True` seems to solve the issue for me, although I don't really understand why this step is necessary.

My setup is as follows:
 * tensorflow: v2.1.0-rc2-17-ge5bf8de 2.1.0
 * driver: 418.87.00
 * CUDA: 10.1
 * cuDNN: v7.6.5.32
 * python: 3.6.7
 * platform: CentOS 7 kernel 3.10.0-957.27.2.el7.x86_64

**Comment by tnybny** [comment]
@ymodak's suggestion solved the issue for me. After digging around a little more, it seems like this is a cuDNN issue with RTX GPUs (see https://github.com/tensorflow/tensorflow/issues/25446). 
Also seeing as tf.config is available in TF >=2.0, the way to perform this setting should be
`gpu_devices = tf.config.experimental.list_physical_devices("GPU")
 for device in gpu_devices:
      tf.config.experimental.set_memory_growth(device, True)`

**Comment by gionanide** [comment]
I am using:

- CUDA Version 10.0.130
- #define CUDNN_MAJOR 7
 #define CUDNN_MINOR 4
 #define CUDNN_PATCHLEVEL 2
- tensorflow 1.15.2

And had the same mistake. I tried lost of things (e.g., allow_growth=True) and did not work.

The thing that worked for me is downgrading to tensorflow 1.14 

- pip uninstall tensorflow-gpu
- pip install tensorflow-gpu==1.14

Taking advise from this post:
https://stackoverflow.com/questions/58097025/0-unknown-failed-to-get-convolution-algorithm-this-is-probably-because-cudnn?answertab=active#tab-top

**Comment by tanseersaji** [comment]
This solution worked for me.

> @ymodak's suggestion solved the issue for me. After digging around a little more, it seems like this is a cuDNN issue with RTX GPUs (see #25446).
> Also seeing as tf.config is available in TF >=2.0, the way to perform this setting should be
> 
> ```
> gpu_devices = tf.config.experimental.list_physical_devices("GPU")
> for device in gpu_devices:
>     tf.config.experimental.set_memory_growth(device, True)
> ```
> 
> If you are running on specific GPUs on a multi-GPU system, of course set CUDA_VISIBLE_DEVICES before this step.

**Comment by summa-code** [comment]
> This solution worked for me.
> 
> > @ymodak's suggestion solved the issue for me. After digging around a little more, it seems like this is a cuDNN issue with RTX GPUs (see #25446).
> > Also seeing as tf.config is available in TF >=2.0, the way to perform this setting should be
> > ```
> > gpu_devices = tf.config.experimental.list_physical_devices("GPU")
> > for device in gpu_devices:
> >     tf.config.experimental.set_memory_growth(device, True)
> > ```
> > 
> > 
> > If you are running on specific GPUs on a multi-GPU system, of course set CUDA_VISIBLE_DEVICES before this step.

If i do this, it ignores GPU. I observed this behavior in TF 2.4.

**Comment by Saduf2019** [comment]
@abcdabcd987 
Is this still an issue.

**Comment by Saduf2019** [comment]
@abcdabcd987
please update if you still face this issue on later versions of tf.
