### ISSUE TITLE
cudart64_101.dll not found, but I have CUDA installed

### ISSUE THREAD

**Issue by frogtd** [tensorflow/tensorflow#36111]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (10.0.18362 Build 18362)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1.0
- Python version: 3.7.6 (from windows store)
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10 and 10.1, but I also tried with just 10.1 and just 10.2
- GPU model and memory: NVIDIA GeForce GTX 1060 OC with 6GB GDDR5

**Describe the problem**
I'm getting the error Could not load dynamic library "'cudart64_101.dll'; dlerror: cudart64_101.dll
 not found", even though cuda is installed and the file exists on my computer
![Annotation 2020-01-21 162719](https://user-images.githubusercontent.com/31412003/72844651-f7cf9d80-3c6a-11ea-8133-ffec9d410cca.png)
**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf
import pathlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
np.set_printoptions(precision=4)

I get these from [https://www.tensorflow.org/guide/data](https://www.tensorflow.org/guide/data)

**Any other info / logs**
2020-01-21 16:18:17.197417: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-01-21 16:18:17.197832: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by gadagashwini** [comment]
@frogtd129,
You may need to find which directory these dlls are in, and then update your PATH to include that directory. Thanks

**Comment by frogtd129** [comment]
I added the directory to path and still get the same warning.

**Comment by joao-carvalheira** [comment]
I'm having the same problem. According to the [docs](https://www.tensorflow.org/install/gpu):  

> The following NVIDIA® software must be installed on your system:
> 
> NVIDIA® GPU drivers —CUDA 10.1 requires 418.x or higher.
> CUDA® Toolkit —TensorFlow supports CUDA 10.1 (TensorFlow >= 2.1.0)
> CUPTI ships with the CUDA Toolkit.
> cuDNN SDK (>= 7.6)
> (Optional) TensorRT 6.0 to improve latency and throughput for inference on some models.
> 


 I tried with CUDA 10.2 and the right cuDNN according to their website (
"Download cuDNN v7.6.5 (November 18th, 2019), for CUDA 10.2") and it worked, but then it stopped working and I don't know what I did. The GPU driver's version is higher than 418.x.

Now I'm using CUDA 10.1, cuDNN v7.6.5 and I'm getting the same error as OP.

**Comment by joao-carvalheira** [comment]
Using miniconda worked:  
```
conda create --name .conda_venv
conda activate .conda_venv
conda install tensorflow-gpu
```

**Comment by Mikkil** [comment]
> 
> 
> Using miniconda worked:
> 
> ```
> conda create --name .conda_venv
> conda activate .conda_venv
> conda install tensorflow-gpu
> ```

At first, I installed tensorflow-gpu using **pip** and after seeing this comment i tried it with **conda** and it worked for me!

**Comment by zepef** [comment]
The Conda install works great for me with TF2.1 and VSCode Win 10

**Comment by GuyGoldner** [comment]
**Solved in a simple but ugly way.**
I installed TensorFlow GPU v2.1, on top of CUDA 10.2.89 and cuDNN 7.6.5.32.
I got the same error in VSCode as described above.

Checked the CUDA installation folder :
_C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin_

Instead of the required cudart64_101.dll file there was a nice looking cudart64_10**2**.dll
Copied it and renamed to cudart64_101.dll and now it's working.

**Comment by jalpeshpanchal99** [comment]
Directory : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\ 

Download Link : https://www.dll-files.com/download/1d7955354884a9058e89bb8ea34415c9/cudart64_101.dll.html?c=N09pWDBSTVYxRE1rM2hpNjVUa2doQT09

**Comment by Passion999** [comment]
I got the same problem as you,you can use tensoflow2.0.0+CUDA10 instead to solve this problem.

**Comment by GuyGoldner** [comment]
You're supposed to use CUDA 10.1 with TensorFlow 2.1.0

Have a look here : https://www.tensorflow.org/install/gpu

> Software requirements
> 
> The following NVIDIA® software must be installed on your system:
> 
>     NVIDIA® GPU drivers —CUDA 10.1 requires 418.x or higher.
>     CUDA® Toolkit —TensorFlow supports CUDA 10.1 (TensorFlow >= 2.1.0)
>     CUPTI ships with the CUDA Toolkit.
>     cuDNN SDK (>= 7.6)
>     (Optional) TensorRT 6.0 to improve latency and throughput for inference on some models

I got the same problem some time ago when I installed TensorFlow GPU with CUDA 10.2.
When I checked the v10.2 folder for the file cudart64_101.dll I found ...10**2**.dll
That's when I should have suspected I messed up the installation... but instead I tried a BAD IDEA first:
I copied it and renamed it to ...101.dll- surprisingly enough it appeared to work and was a fun way to benchmark CPU vs GPU with different code variations but that's just asking for problems. So DON'T do that. 
Also, as a rule of thumb I do not suggest to manually add DLL files. Ever ! 
When something doesn't work as you expect you'll be wondering if it's you or the installation and you'll waste much more valuable time then.

**What you should do is** :
(Take a break) 
Uninstall TF.
Uninstall CUDA 10.2 and Nvidia's Nsight.
Install CUDA 10.1 and continue from there.

BTW, this guide is great - **Just read ahead before you do anything** :
https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781

**Comment by primesoftwareco** [comment]
I was running TF2.0 with CUDA 10.0 fine. I updated to TF2.1 and started having this error. I reinstalled CUDA to version 10.1 following this guide: https://www.tensorflow.org/install/gpu?hl=en. The error still persisted so eventually I tried it out of my conda environment and it worked.

**Comment by the-rccg** [comment]
FWIW, for me just copy-and-paste the *101.dll's into the 10.2/bin folder worked fine.

**Comment by daniahl** [comment]
I haven't managed to get tf to work with GPU since 1.14, for this reason. I'm on Win10, and using Anaconda environments. Was hoping that the recently released tf 2.1 conda package would solve the issue, but unfortunately it still persists.

So right now I have two environments, one (tf 1.14) where things work fine, and the other (tf 2.1) where tf can't find the dll.

For tf 1.14 the DLL is at: C:\Users\Daniel\Miniconda3\envs\tf\Library\bin\cudart64_100.dll - this directory is on the PATH and tf finds it and is happy.

For tf 2.1 the DLL is at C:\Users\Daniel\Miniconda3\envs\tf2\Library\bin\cudart64_101.dll - tf doesn't find this, even though the directory is on the PATH.

There's obviously a CUDA version difference, but AFAIK that's how it's supposed to be. The 2.1 env was just created today with conda create -n tf2 tensorflow-gpu, which seems to have pulled in the right dependencies as far as I can tell.

Are there perhaps any recent changes to dso_loader that could affect the file search behaviour? Noting that when using Anaconda/Miniconda the CUDA path is arbitrary since it contains the env name (as opposed to the regular CUDA installation in C:\Program Files\...)

**Comment by zepef** [comment]
I have it working with both the copy trick and Anaconda with an Nvidia 2070 max Q

**Comment by GuyGoldner** [comment]
@daniahl 
I don't use Anaconda but I suggest you revisit my comment above. Besides the versions and stuff listed there, there's a link to a guide which describes how to install (with obsolete versions, so use the ones I mentioned) but more important **how to check that every component works**.
I hope it would help you narrow down your search.

Good luck !

P.S.
Seems like you're nearly there. A PATH issue may very well be the cause.
Perhaps you could remove the old versions from the path and see what happens.

**Comment by daniahl** [comment]
Thing is, with Anaconda you're not supposed to need to install the CUDA toolkit separately; the toolkit and CuDNN come as conda packages. This is why I am curious as to whether tf now has trouble with that kind of setup. I could try by installing CUDA and CuDNN the "normal" way. If that solves it, however, there might be a bug somewhere, cause this shouldn't be needed.

**Comment by volkov-maxim** [comment]
> 
> 
> You're supposed to use CUDA 10.1 with TensorFlow 2.1.0
> 
> Have a look here : https://www.tensorflow.org/install/gpu
> 
> > Software requirements
> > The following NVIDIA® software must be installed on your system:
> > ```
> > NVIDIA® GPU drivers —CUDA 10.1 requires 418.x or higher.
> > CUDA® Toolkit —TensorFlow supports CUDA 10.1 (TensorFlow >= 2.1.0)
> > CUPTI ships with the CUDA Toolkit.
> > cuDNN SDK (>= 7.6)
> > (Optional) TensorRT 6.0 to improve latency and throughput for inference on some models
> > ```
> 
> I got the same problem some time ago when I installed TensorFlow GPU with CUDA 10.2.
> When I checked the v10.2 folder for the file cudart64_101.dll I found ...10**2**.dll
> That's when I should have suspected I messed up the installation... but instead I tried a BAD IDEA first:
> I copied it and renamed it to ...101.dll- surprisingly enough it appeared to work and was a fun way to benchmark CPU vs GPU with different code variations but that's just asking for problems. So DON'T do that.
> Also, as a rule of thumb I do not suggest to manually add DLL files. Ever !
> When something doesn't work as you expect you'll be wondering if it's you or the installation and you'll waste much more valuable time then.
> 
> **What you should do is** :
> (Take a break)
> Uninstall TF.
> Uninstall CUDA 10.2 and Nvidia's Nsight.
> Install CUDA 10.1 and continue from there.
> 
> BTW, this guide is great - **Just read ahead before you do anything** :
> https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781

Hardware requirements

The following GPU-enabled devices are supported:

    NVIDIA® GPU card with CUDA® Compute Capability 3.5 or higher. See the list of CUDA-enabled GPU cards.

Software requirements

The following NVIDIA® software must be installed on your system:

    NVIDIA® GPU drivers —CUDA 10.1 requires 418.x or higher.
    CUDA® Toolkit —TensorFlow supports CUDA 10.1 (TensorFlow >= 2.1.0)
    CUPTI ships with the CUDA Toolkit.
    cuDNN SDK (>= 7.6)
    (Optional) TensorRT 6.0 to improve latency and throughput for inference on some models.

https://www.tensorflow.org/install/gpu?hl=ru

**Comment by volkov-maxim** [comment]
> PATH

@gadagashwini, yes indeed, it seems like an obvious decision, but after changing the PATH environment variable in "System properties/Advanced/Environment Variables" Win10, "tflite_convert" tool stops raise an error about dynamic library cudart64_101.dll.
Now it looks like this:
```
$ tflite_convert.exe
2020-02-24 23:18:51.593706: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
```

**Comment by asears** [comment]
Creating environment with Conda, activating environment, upgrading pip, upgrading tensorflow 1.15 to 2.1 with pip, then install tensorflow-gpu with Conda and Nvidia 10.1 runtime worked for me.

Tensorflow 2.1.0
Windows 10 1909.
Conda 4.8.1
pip 20.0.2 from C:\tools\Anaconda3\envs\(my env)\lib\site-packages\pip (python 3.7)
cudatoolkit               10.1.243
cudnn                     7.6.5
```
>>> import tensorflow
2020-03-01 10:18:52.598939: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
```

DLL under
```
C:\tools\Anaconda3\envs\(my env)\Library\bin
```

![image](https://user-images.githubusercontent.com/7253192/75628399-90303a80-5ba6-11ea-80e8-299f18cdafc0.png)

Path entries - I replaced my created environment name with (my env)

```
C:\cuda\bin;
C:\tools\Anaconda3\envs\(my env);
C:\tools\Anaconda3\envs\(my env)\Library\mingw-w64\bin;

C:\tools\Anaconda3\envs\(my env)\Library\usr\bin;
C:\tools\Anaconda3\envs\(my env)\Library\bin;
C:\tools\Anaconda3\envs\(my env)\Scripts;
C:\tools\Anaconda3\envs\(my env)\bin;
C:\tools\Anaconda3\condabin;

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;
C:\Program Files\NVIDIA Corporation\NvStreamSrv;
C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0;
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;

C:\tools\Anaconda3;
C:\tools\Anaconda3\Library\mingw-w64\bin;
C:\tools\Anaconda3\Library\usr\bin;
C:\tools\Anaconda3\Library\bin;
C:\tools\Anaconda3\Scripts;
C:\Python38\Scripts;
C:\Python38;
```


There might be a bump in the version from 10.1 to 10.2 required here.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cudart_stub.cc

Seems to be hard-coded to 10.1?
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/stream_executor/cuda

**Comment by RyanCocking** [comment]
> 
> 
> Directory : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\
> 
> Download Link : https://www.dll-files.com/download/1d7955354884a9058e89bb8ea34415c9/cudart64_101.dll.html?c=N09pWDBSTVYxRE1rM2hpNjVUa2doQT09

Thanks so much @jalpeshpanchal99, this sorted it for me!

**Comment by numpad0** [comment]
Combinations of CUDA {10.2, 10.1U2, 10.1} + Python {3.8, 3.7.7} from store +pip didn't work for me. adding \bin to CUDNN_PATH, copying files around, didn't work either. I suspect binary incompatibility or permission issues rather than file actually missing.  

Uninstalling Python and replacing with Anaconda then `conda install tensorflow` solved it for me.

**Comment by gmikhail** [comment]
I have similar issue with CUDA 10.2.89, because it installs `cudart64_102.dll` but tensorflow 2.2.0rc1 requires `cudart64_101.dll`. The usual renaming of a copy of dll helped.

![Аннотация 2020-03-21 172112](https://user-images.githubusercontent.com/4838367/77229778-69a76300-6b98-11ea-89c3-81c48171b7a3.png)

PS: if you use Windows do not forget to restart the PC after CUDA installation, because system environment variables are updated

**Comment by daniahl** [comment]
Still no luck here. At first I thought TF2 might have issues with the anaconda paths to the dll files, but after having installed CUDA directly from NVIDIA to the default path, TF still complains that it can't find the DLL.
Pytorch finds the file and GPU works, so I really don't know why TF doesn't.

**Comment by lekstonjm** [comment]
@joao-carvalheira : Simple and efficient!
> ```
> conda create --name .conda_venv
> conda activate .conda_venv
> conda install tensorflow-gpu
> ```

**Comment by zepef** [comment]
Hello I would recommend adding specific 3.7 version of python as it is proven to be working nicely with TF2.

conda create -n tf2env python=3.7

and do not forget to get latest conda version at your base env

conda update -n base -c defaults conda

All the best !

________________________________
De : Jean-Michel Lekston <notifications@github.com>
Envoyé : dimanche 22 mars 2020 07:00
À : tensorflow/tensorflow <tensorflow@noreply.github.com>
Cc : Pierre-Emmanuel FEGA <zepef@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [tensorflow/tensorflow] cudart64_101.dll not found, but I have CUDA installed (#36111)


@joao-carvalheira<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoao-carvalheira&data=02%7C01%7C%7Ce204868de3934109ee0308d7ce695030%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637204824015577990&sdata=nMlD3Zrf1e8UVXvi9g81%2FUJ9mpYfQV5B9%2FcTAHQe%2F%2Fs%3D&reserved=0> : Simple and efficient!

conda create --name .conda_venv
conda activate .conda_venv
conda install tensorflow-gpu

**Comment by sliawatimena** [comment]
I copied
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudart64_102.dll
into cudart64_101.dll
So I have both (that actually the same file with different names).

It solved my problem.

**Comment by Pietroro** [comment]
> Also, as a rule of thumb I do not suggest to manually add DLL files. Ever !

Hey GuyGoldener, I was having the same problems the others were having and I resorted to downloading the 101.dll separately and manually adding it to the /bin folder. While I see that it's wrong, uninstalling CUDA 10.2 is easier said than done. I wanted to know if in this case an uninstall of CUDA 10.2 and fresh install of CUDA 10.1 is necessary in your opinion, considering the time it takes to freshly install CUDA again and the risks associated with uninstalling CUDA 10.2

**Comment by nbwuzhe** [comment]
> I have similar issue with CUDA 10.2.89, because it installs `cudart64_102.dll` but tensorflow 2.2.0rc1 requires `cudart64_101.dll`. The usual renaming of a copy of dll helped.
> 
> ![Аннотация 2020-03-21 172112](https://user-images.githubusercontent.com/4838367/77229778-69a76300-6b98-11ea-89c3-81c48171b7a3.png)
> 
> PS: if you use Windows do not forget to restart the PC after CUDA installation, because system environment variables are updated

No need to restart PC. Just re-launch cmd.exe or PowerShell will apply the new Env Variables.

**Comment by princewillzz** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/43216487/78386845-f1ab5500-75fb-11ea-9476-73485cb0e1ed.png)

**Comment by princewillzz** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/43216487/78386904-0daef680-75fc-11ea-8542-567368c436a4.png)
I had the same problem but I just copied "cudart64_102" with the name as "cudart_101.dll" and it worked.

**Comment by RainerHeintzmann** [comment]
I had a similar problem. I added the installation Cuda Toolkit 10.1 bin directory to the PATH variable, but the tensorflow environment did not seem to recongnize it and complained about not finding cudart64_101.dll. It turned out, that I did not restart PyCharm.
After closing and starting PyCharm, all the dlls were correctly recognized.

**Comment by Koebims** [comment]
> Directory : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\
> 
> Download Link : https://www.dll-files.com/download/1d7955354884a9058e89bb8ea34415c9/cudart64_101.dll.html?c=N09pWDBSTVYxRE1rM2hpNjVUa2doQT09

nice

**Comment by Lambik** [comment]
I have the same issue as @daniahl . Anaconda has put the `cudart64_101.dll` into my-env\Library\bin, but tensorflow does not find it there. Or does not look there.

I don't want to install a global CUDA setup, what if my games fail, or it gets updated by geforce experience, or my tf 1.14 conda starts failing. It should work with the dll that is just *right there*.

**Comment by HotEncoded** [comment]
I had the same error after installing with “the award winning new approach” condos create —name tf_gpu tensorflow-gpu.
I downgraded cudatookit using 

Conda install cudatoolkit==10.0.130

in anaconda prompt. No path adjustments needed. Cudart dll loads fine as well.

**Comment by smreichling** [comment]
I had this exact issue. On Windows 10, installed CUDA 10.1, python 3.7, tensorflow 2.1, PATH variable set correctly, but was still seeing this error.

The problem turned out to be that the version of python I had installed was the one from the Microsoft Store and _not_ the one from python.org. As it turns out, apps installed from the Microsoft Store are sandboxed. Windows restricts where they can load DLLs from pretty severely. Among [the restrictions](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order): Windows does not search the directories in the `PATH` env var for the DLLs. So app store python will never be able to find CUDA DLLs this way.

Long story short: be sure to install your python from python.org. Took me waaay too much spelunking of the tensorflow code for loading DLLs to figure this out.

**Comment by gunan** [comment]
@smreichling I was not aware of this. Thank you very much for the detailed analysis!
We should definitely document this in our installation documentation.
@lamberta where does this information best fit in our documents?

**Comment by E3V3A** [comment]
@smreichling 
> The problem turned out to be that the version of python I had installed was the one from the Microsoft Store and not the one from python.org. As it turns out, apps installed from the Microsoft Store are sandboxed. Windows restricts where they can load DLLs from pretty severely. Among the restrictions: Windows does not search the directories in the PATH env var for the DLLs. So app store python will never be able to find CUDA DLLs this way.

Is there a way to test this from command line? 
For example in a powershell or Conda CMD?

I have no idea which version was installed, since it was a while ago.

**Comment by Lambik** [comment]
> Maybe a fix without dealing with mismatching dlls.
> Works with Tf-GPU 2.1, installed as described below.
> 
> I had the same error after installing with “the award winning new approach”: conda create —name tf_gpu tensorflow-gpu.
> I downgraded cudatookit using
> 
> Conda install cudatoolkit==10.0.130
> 
> in anaconda prompt. No path adjustments needed. This cudatoolkit version seems to have xx_100.dll instead and loads fine when tensorflow is imported.

No this didn't solve anything for me either :(

First it warned (as it should):

```
The following packages will be DOWNGRADED:

  cudatoolkit                           10.1.243-h74a9793_0 --> 10.0.130-0
  cudnn                                    7.6.5-cuda10.1_0 --> 7.6.5-cuda10.0_0
  tensorflow                       2.1.0-gpu_py37h7db9008_0 --> 2.0.0-gpu_py37h57d29ca_0
  tensorflow-base                  2.1.0-gpu_py37h55f5790_0 --> 2.0.0-gpu_py37h390e234_0
  tensorflow-estima~                     2.1.0-pyhd54b08b_0 --> 2.0.0-pyh2649769_0
  tensorflow-gpu                           2.1.0-h0d30ee6_0 --> 2.0.0-h0d30ee6_0
```

which is something I don't want, I want tf 2.1.0, but for the sake of testing I did anyway.

Running it gave me the same error:

```
(D:\Data\Python-envs\tf-2-gpu) C:\Users\Me>python
Python 3.7.7 (default, Apr 15 2020, 05:09:04) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-04-23 16:44:29.635410: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
```

But in `D:\Data\Python-envs\tf-2-gpu\Library\bin` I do have a `cudart64_100.dll` file.

Afaik I'm not using the windows story python, since I never go there, and I just installed anaconda (miniconda) a while ago.

**Comment by lamberta** [comment]
> where does this information best fit in our documents?

Hmm. Well, if it is in fact an issue with the Windows Store python, there's two candidate locations (or both!):

- The WIndows section of the GPU setup guide: https://www.tensorflow.org/install/gpu#windows_setup
- The WIndows-specific setup instructions in the pip install guide: https://www.tensorflow.org/install/pip?lang=python3#windows

These docs live over here: https://github.com/tensorflow/docs/tree/master/site/en/install

Microsoft provides two guides:
- [Get started using Python on Windows for beginners](https://docs.microsoft.com/en-us/windows/python/beginners) (Windows Store)
- [Get started using Python on Windows for scripting and automation](https://docs.microsoft.com/en-us/windows/python/scripting)
  * "For some advanced scenarios (like needing to access/modify Python's installed files, make copies of binaries, or use Python DLLs directly) ..."

So maybe we can point off to the latter guide and include that blurb for some context.

**Comment by mihaimaruseac** [comment]
I'm thinking we should include the blurb in both locations on the website, both on the GPU setup guide and on the pip install one

**Comment by FirefoxMetzger** [comment]
The copy trick that is suggested multiple times in this issue seems like a bit of a hack to me. I ran into the same issue just now, and (1) installing CUDA 10.1 toolkit - on top of 10.2 - and (2) adding 
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin
```
to the path does the same trick.

Different versions of CUDA happily coexist with each other so installing both 10.1 and 10.2 is very possible. To me, this seems more Windows-style than manually copying a .dll. On this note, the CUDA toolkit creates environment variables called `CUDA_PATH`, `CUDA_PATH_V10_1`. `CUDA_PATH_V10_1`, ... . Perhaps it could be possible for Tensorflow to check for these variables and include the libraries found there; this would resolve the need to add the toolkit to the path, and would allow for an appropriate warning of the form `TensorFlow was compiled against CUDA XX.YY; however this CUDA version could not be found on your system.`

**Comment by gunan** [comment]
@chsigg @yifeif

**Comment by AndrewJWashington** [comment]
I had a similar issue and found out the issue was using Python 3.8. I downgraded to Python 3.7 and it started working.
Before that I tried reinstalling drivers, making sure all files existed, using conda vs venv, tf 2.1 vs tf 2.2, reinstalling tf, and explicitly installing tensorflow-gpu.

**Comment by gitgithan** [comment]
You can try this manually loading the dll if PATH fails even after adding: https://github.com/tensorflow/tensorflow/issues/30748#issuecomment-647106802

**Comment by jDavidnet** [comment]
> I had this exact issue. On Windows 10, installed CUDA 10.1, python 3.7, tensorflow 2.1, PATH variable set correctly, but was still seeing this error.
> 
> The problem turned out to be that the version of python I had installed was the one from the Microsoft Store and _not_ the one from python.org. As it turns out, apps installed from the Microsoft Store are sandboxed. Windows restricts where they can load DLLs from pretty severely. Among [the restrictions](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order): Windows does not search the directories in the `PATH` env var for the DLLs. So app store python will never be able to find CUDA DLLs this way.
> 
> Long story short: be sure to install your python from python.org. Took me waaay too much spelunking of the tensorflow code for loading DLLs to figure this out.

This was my issue.  I spent 4 hours trying various things till this was exactly the problem.  Please update the documentation ASAP!

**Comment by thanhlong1997** [comment]
> I had this exact issue. On Windows 10, installed CUDA 10.1, python 3.7, tensorflow 2.1, PATH variable set correctly, but was still seeing this error.
> 
> The problem turned out to be that the version of python I had installed was the one from the Microsoft Store and _not_ the one from python.org. As it turns out, apps installed from the Microsoft Store are sandboxed. Windows restricts where they can load DLLs from pretty severely. Among [the restrictions](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order): Windows does not search the directories in the `PATH` env var for the DLLs. So app store python will never be able to find CUDA DLLs this way.
> 
> Long story short: be sure to install your python from python.org. Took me waaay too much spelunking of the tensorflow code for loading DLLs to figure this out.

it worked for me when use gpu and tensorflow on window . thank

**Comment by Davidxswang** [comment]
> I had this exact issue. On Windows 10, installed CUDA 10.1, python 3.7, tensorflow 2.1, PATH variable set correctly, but was still seeing this error.
> 
> The problem turned out to be that the version of python I had installed was the one from the Microsoft Store and _not_ the one from python.org. As it turns out, apps installed from the Microsoft Store are sandboxed. Windows restricts where they can load DLLs from pretty severely. Among [the restrictions](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order): Windows does not search the directories in the `PATH` env var for the DLLs. So app store python will never be able to find CUDA DLLs this way.
> 
> Long story short: be sure to install your python from python.org. Took me waaay too much spelunking of the tensorflow code for loading DLLs to figure this out.

Thanks @smreichling ! This issue took me 6 hours. I had the same issue: installed Python from Microsoft Store, reinstalled cuda, cuDNN, tensorflow for 4 times, verified the path and rebooted for many many times..... until I found this solution.... Installing Python from Python.org is the solution for those struggling with the Python from MS Store. Remember install Python 64-bit version from Python.org. The default button on Python.org homepage will download the 32-bit version which will not let you install tensorflow at all when using pip.

**Comment by Moldoteck** [comment]
Almost all comments are misleading. Why you push the idea of copying files from conda 10.2 to 10.1. He clearly said that he tried with conda 10.1. Also, suggesting installing tf with conda isn't correct too: why we should be forced to use it? It should work simply by installing cuda+cudnn from official site and defining env variables accordingly + installing tf with pip. This shouldn't be a problem.

Also, what about this situation> I had Python 3.5 and tf 2.2 that worked just fine with cuda 10.1. I have created with conda a new environment with Python 3.8 and tf 2.2. Guess what? It does not detect cudart64_101.dll. So there are clearly problems here

**Comment by yrutis** [comment]
This page actually worked for me:
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html , section 3.3. I copied the files to cuda v.10.2.

**Comment by shtse8** [comment]
> > I had this exact issue. On Windows 10, installed CUDA 10.1, python 3.7, tensorflow 2.1, PATH variable set correctly, but was still seeing this error.
> > The problem turned out to be that the version of python I had installed was the one from the Microsoft Store and _not_ the one from python.org. As it turns out, apps installed from the Microsoft Store are sandboxed. Windows restricts where they can load DLLs from pretty severely. Among [the restrictions](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order): Windows does not search the directories in the `PATH` env var for the DLLs. So app store python will never be able to find CUDA DLLs this way.
> > Long story short: be sure to install your python from python.org. Took me waaay too much spelunking of the tensorflow code for loading DLLs to figure this out.
> 
> Thanks @smreichling ! This issue took me 6 hours. I had the same issue: installed Python from Microsoft Store, reinstalled cuda, cuDNN, tensorflow for 4 times, verified the path and rebooted for many many times..... until I found this solution.... Installing Python from Python.org is the solution for those struggling with the Python from MS Store. Remember to install Python 64-bit version from Python.org. The download button on Python.org homepage will download the 32-bit version by default which will not let you install tensorflow using pip.

Worked!!!!
I tried every solution in comments. spent 6 hours too. and it's because I installed python from Microsoft store.

**Comment by kingdavid72** [comment]
> Directory : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\
> 
> Download Link : https://www.dll-files.com/download/1d7955354884a9058e89bb8ea34415c9/cudart64_101.dll.html?c=N09pWDBSTVYxRE1rM2hpNjVUa2doQT09

First of all, I had the same problem as "cudart64_101.dll not found". 
Finally, get it to work by installing CUDA10.1 + cuDNN7.6.5 for CUDA10.1 with **pip install tensorflow** on windows 10. 
Here is the list of Not working methods
1) copy or rename or download external cudart64_101.dll and put them into CUDA folder
This never worked since 'cudnn64_7.dll' and 'cusparse64_10.dll' is also missing and never a good idea unless you know the details of the lib files well.
2) Install Python from python.org, not from Microsoft store or use python 3.7 etc....
well in fact even though Python form python.org alone did not help. the default installation path is weird enough, install in C:Python38 otherwise cause permission problem. After all, I used Python 3.8 and works fine. I even tried in **venv** isolate tf in a specific folder and still works.

in summary: The best way is to install proper libs, you do not have to uninstall CUDA11.0, it can co-exist. if you install CUDA 10.1 later, the System CUDA_PATH will be CUDA10.1. you can check it by **nvcc --version**. To check TensorFlow version
I used **python -c 'import tensorflow as tf; print(tf.__version__)'** and it nicely reported version 2.3.0

#cudatest.py file
import tensorflow as tf 
tf.config.list_physical_devices('GPU')

also reported followings
$ python cudatest.py
2020-07-31 11:52:36.145220: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-07-31 11:52:37.418972: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-07-31 11:52:38.406721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1650 Ti computeCapability: 7.5
coreClock: 1.485GHz coreCount: 16 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 178.84GiB/s
2020-07-31 11:52:38.406762: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-07-31 11:52:38.410134: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-07-31 11:52:38.412850: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-07-31 11:52:38.413875: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-07-31 11:52:38.417343: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-07-31 11:52:38.419256: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-07-31 11:52:38.425368: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-07-31 11:52:38.425437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0

Hope this one helps and
What else do you guys think that I have to check or test in Windows 10 laptop?

**Comment by frogtd** [comment]
I'm pretty sure the issue had do with the sandboxed nature of the python from the microsoft store, not anything to do with tensorflow.

**Comment by dcaled** [comment]
> 
> 
> I had a similar issue and found out the issue was using Python 3.8. I downgraded to Python 3.7 and it started working.
> Before that I tried reinstalling drivers, making sure all files existed, using conda vs venv, tf 2.1 vs tf 2.2, reinstalling tf, and explicitly installing tensorflow-gpu.

Thank was what worked for me. My problem was the new 3.8 version.  It worked when I changed to 3.7. Thank you!

**Comment by freedom9393** [comment]
First, check tensorflow **compatibility** with CUDA/cuDNN/Python from **[here](https://www.tensorflow.org/install/source#gpu)**
For me these worked fine:

- CUDA 10.0
- cuDNN 7.6
- Tensorflow-gpu 2.0.0

You might want to use newer versions. If so, just check compatibility

**Comment by mercierkevin35** [comment]
I tried with a 3.7.* version of python instead of 3.8.* and it works for me

**Comment by DavidLichy** [comment]
updating to the latest tf worked for me `pip install tf-nightly-gpu`

**Comment by CostanzoPablo** [comment]
I have the same problem and the solution is:

1) Uninstall all drivers that says "nvidia" from Uninstall programs (ALL, Cuda and gpu driver)
2) Install last nvidia drivers for your GPU https://uk.download.nvidia.com/GFE/GFEClient/3.21.0.36/GeForce_Experience_v3.21.0.36.exe
3) Install cuda 11.2 https://developer.download.nvidia.com/compute/cuda/11.2.1/local_installers/cuda_11.2.1_461.09_win10.exe
2) Install Anaconda https://repo.anaconda.com/archive/Anaconda3-2020.11-Windows-x86_64.exe
3) conda create -n cudaenv python=3.6
4) conda activate cudaenv
5) pip install tensorflow python-dotenv
6) Create a.py with this: import tensorflow as tf
7) run it: python a.py 
Output:
xxx: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll

**Comment by JDM-ULL-93** [comment]
It seems Python installed from Microsoft Store, for some reason, is not able to search for dll's through environment variables (Security Policies). One easy and temporary fix is , before this line of code
```python
import tensorflow as tf
````

Add the following code:

```python
import os
os.add_dll_directory(r"<your_path_to_NVIDIA_toolsets>\CUDA\<your_cuda_version\DEV\bin")
````

This way, tensorflow loader will be able to load "cudart64_101.dll"

**Comment by HonmaMeikodesu** [comment]
Microsoft Store is a **### disaster**😱

**Comment by theGiallo** [comment]
The `add_dll_directory` workardound wasn't working for me. I've solved adding to the `PATH` env variable `%CUDA_PATH%\bin`. Be sure to restart your IDE or terminal after that.
