### ISSUE TITLE
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by deerishi** [tensorflow/tensorflow#3616]
I installed Cuda 7.5 and cudnn v4. after making the symlinks for cudnn and changing the path variables, when I import tensorflow I get the error : ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory. ?

Any advice on how to proceed?

**Comment by yaroslavvb** [comment]
when you ran ./configure, did you specify 7.5 as cuda version?
Also a work-around for this kind of issue could be to find your
libcudart.so (maybe in /usr/lib/cuda) and symlink it to libcudart.so.7.0

**Comment by deerishi** [comment]
I only have libcudart.so.7.5 at /usr/local/cuda-7.5/targets/x86_64-linux/lib/libcudart.so.7.5
. I do not have libcudart.so.7.0. 
Also I did not install tensorflow from source.

**Comment by yaroslavvb** [comment]
You could "ln -s" your libcudart.so.7.5 to libcudart.so.7.0

**Comment by deerishi** [comment]
I reinstalled tensorflow, it worked, though a strange ting happened now. Tensorflow runs fine in the ipython shell, but if I execute the python  program  from the terminal I get the following error : 

`  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 58, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
`

I saw a fix at [https://github.com/tensorflow/tensorflow/issues/1415](url). But why does this only occur when I execute the python program and not in the ipython shell ?

Thanks!

**Comment by yaroslavvb** [comment]
Your ipython and Python have different values for sys.path

Basically you can have multiple Python distributions with their own sets of
libraries, so your Python and ipython probably come from different
distributions

**Comment by deerishi** [comment]
I thought that would be the case, but my Python path is set to /usr/local/lib/python2.7/dist-packages. its where google/protobuf is.

**Comment by yaroslavvb** [comment]
Package loading is done by traversing entries in sys.path until there's a
match. So if os.getcwd() and sys.path are identical between Python and
ipython, your package loading should be the same.

On Aug 2, 2016 7:38 PM, "Deepak" <notifications@github.com> wrote:

>

> I thought that would be the case, but my Python path is set to
/usr/local/lib/python2.7/dist-packages. its where google/protobuf is.
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/3616#issuecomment-237117351>,
or mute the thread

**Comment by deerishi** [comment]
I had to un install miniconda and anaconda , though it is working now. Although I double checked, there were no conflicts with protobuf from miniconda or anaconda, it  was'nt working with them installed. Does tensorflow has some other conflicts with anacondas or miniconda?

**Comment by poxvoculi** [comment]
This stackoverflow thread
http://stackoverflow.com/questions/33646541/tensorflow-and-anaconda-on-ubuntu
discusses some issues that can cause trouble between TF and anaconda on ubuntu.

**Comment by deerishi** [comment]
Thanks , I have exactly the same issue. Anyways I installed some of the anaconda packages by pip and its working fine now. 
Thanks @yaroslavvb  and @poxvoculi  for your help.
