### ISSUE TITLE
"Could not load dynamic library 'libnvinfer.so.6'" when installing from WSL 2

### ISSUE THREAD

**Issue by galah92** [tensorflow/tensorflow#36201]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu through **WSL 2** on Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version: 2.1.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip, no virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no, machine is Dell XPS 13 9530
- GPU model and memory: no

**Describe the problem**
When installing tensorflow using pip I'm getting:

    In [1]: import tensorflow as tf
    2020-01-25 11:20:08.541504: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
    2020-01-25 11:20:08.541639: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
    2020-01-25 11:20:08.541689: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

A fresh install of WSL 2 on Windows 10, I did:

    sudo apt update -y && sudo apt upgarde -y
    sudo apt install -y python3-pip
    python3 -m pip install pip --upgrade --user
    python3 -m pip install tensorflow --user

**Comment by ashutosh1919** [comment]
@galah92 , It seems that you must have GPU to work with the tensorflow-gpu packages. Your error is because the computer is not able to locate the file **libnvinfer.so.6**. If you have NVIDIA GPU installed and nvcc is running, please check TensorRT installation guide [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html). Also take a look at [this past issue](https://github.com/tensorflow/tensorflow/issues/34329). 

But it seems certain that the error will persist until you don't have NVIDIA Gpu with CUDA installed.

**Comment by galah92** [comment]
> @galah92 , It seems that you must have GPU to work with the tensorflow-gpu packages. Your error is because the computer is not able to locate the file **libnvinfer.so.6**. If you have NVIDIA GPU installed and nvcc is running, please check TensorRT installation guide [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html). Also take a look at [this past issue](https://github.com/tensorflow/tensorflow/issues/34329).
> 
> But it seems certain that the error will persist until you don't have NVIDIA Gpu with CUDA installed.

Thank you for the response. This is exactly was I understood from the error, but I installed the non-GPU version of tensorflow so I don't understand why it expects a GPU. The best part is that I don't even have a dedicated GPU on my machine (Dell XPS 13 9530). This is the installed package:

    galah92@XPS13:~$ python3 -m pip freeze | grep tensor
    tensorboard==2.1.0
    tensorflow==2.1.0
    tensorflow-estimator==2.1.0

**Comment by ashutosh1919** [comment]
@galah92 , Please install tensorflow==1.15 using pip and not 2.x because default mode for 2.x seems to be GPU and default mode for 1.15 is CPU

**Comment by ymodak** [comment]
@galah92 You can safely ignore those warning logs and continue using TF. Note that TF will implement cpu for all your computations. TF 2.x packages are provide both cpu and gpu support. 
See https://www.tensorflow.org/install/pip#tensorflow-2-packages-are-available

**Comment by Saduf2019** [comment]
@galah92 Please let us know if the above comment helps and issue is resolved.

**Comment by galah92** [comment]
@ymodak @Saduf2019 Thanks, I'm currently ignoring these warnings. It's just weird that that's the default, I didn't expect warning if my machine don't even have a GPU.
Thanks again.

**Comment by Saduf2019** [comment]
As the issue has been resolved, moving it to closed status

**Comment by G-shift** [comment]
I had the same issue, but they went away when I was more specific about the version of python. Tensorflow seems to tuned for python 2.7:

**~$ python2.7
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>>**

**Comment by G-shift** [comment]
I had the same issue, and the warnings went away when I used python2.7

**Comment by FirefoxMetzger** [comment]
@G-shift That is because python 2.7 defaults to TF1.X and doesn't use TF2. You can check with

```
python2 -m pip freeze | grep tensorflow
python3 -m pip freeze | grep tensorflow
```

and compare which versions you have installed in both pythons. Note that python 2 has reached it's end of life, so if you are writing any new code consider migrating to python 3 :)

**Comment by maxiadityakusuma** [comment]
> @galah92 , Please install tensorflow==1.15 using pip and not 2.x because default mode for 2.x seems to be GPU and default mode for 1.15 is CPU
> 
> Use
> 
> ```shell
> $ pip install tensorflow-cpu
> ```

Thanks, it worked
I am using Keras version 2.2.4 and TensorFlow version 1.15
