### ISSUE TITLE
Android demo crashes when package name is changed

### ISSUE THREAD

**Issue by cardshuffle** [tensorflow/tensorflow#3673]
### Environment info
Operating System: Ubuntu 14.04 LTS 64-bit
Installed version of CUDA and cuDNN: none (not using GPU)

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`): fc9162975e52978d3af38549b570cc3cc5f0ab66
2. The output of `bazel version`
```
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```

### Steps to reproduce
1. Open Android demo in Android Studio (not imported)
2. Change org/tensorflow/demo folder names to any other package name
3. Use replace in path to replace org.tensorflow.demo with the new package name
4. Run `bazel mobile-install //tensorflow/examples/android:tensorflow_demo --start_app`
5. The demo crashes on startup with the message "Unfortunately, TensorFlow Demo has stopped."

### What have you tried?
1. Importing the demo into Android Studio instead of simply opening it. Was unable to build/run, even without changing package name.
2. Modifying the `tensorflow_jni.h` file to remove occurrences of `ORG_TENSORFLOW`, etc. with the changed package name in the same format, e.g. `COM_ME`.
3. Looked through other possibly relevant files for references to the old package name, didn't find anything else, though I might've overlooked some.

### Logs or other output that would be helpful
(no output)

Also, as a general question, if I wanted to create my own Android app using TensorFlow, what sort of configuration would I need to do? I haven't found any explanation of how the demo works.

**Comment by cardshuffle** [comment]
Turns out I missed a line in `imageutils_jni.cc`, and after changing that, the error was fixed. But at the moment, the only way I can work on an Android app with TensorFlow is by modifying the demo project. If I try to make a copy in another location, Bazel doesn't work, and creating a copy by importing it into Android Studio doesn't work either. Is there a better way to handle this?

**Comment by girving** [comment]
@cardshuffle If your final question is also covered by https://github.com/tensorflow/tensorflow/issues/3685, can I close this one?

**Comment by cardshuffle** [comment]
Yes, logcat is available now that the project is properly opened in Android Studio.
