### ISSUE TITLE
when using mixed_precision.Policy('mixed_float16'), training is stuck at saving checkpoints for 0 

### ISSUE THREAD

**Issue by petkovacs19** [tensorflow/tensorflow#36900]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Debian GNU/Linux 9 (stretch) 
- TensorFlow installed from (source or
binary): binary
- TensorFlow version (use command below): 2.1
- Python version: 3.5.3
- Bazel
version (if compiling from source): 
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the current behavior**
When using tpu estimator in cpu mode and setting the precision policy to 'mixed_float16' training hangs at saving checkpoints for 0
**Describe the expected behavior**
Continue training using mixed precision, with default policy training is successfull

**Code to reproduce the issue** Provide a reproducible test case that is the
bare minimum necessary to generate the problem.
Use an example tpu_estimator from one of the tensorflow examples and set precision policy:
```
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

with TF_CPP_MIN_VLOG_LEVEL=2:
this message is getting repeated periodically:
2020-02-19 13:54:50.181246: I tensorflow/core/framework/model.cc:892] Starting optimization of tunable parameters with HillClimb
2020-02-19 13:54:50.181532: I tensorflow/core/framework/model.cc:943] Number of tunable parameters: 1
2020-02-19 13:54:50.181634: I tensorflow/core/framework/model.cc:946] Setting tunable parameter MapAndBatch(id:1) to 4
2020-02-19 13:54:50.181729: I tensorflow/core/kernels/data/model_dataset_op.cc:192] Waiting for 60000 ms.

**Comment by ravikyram** [comment]
@petkovacs19 

Could you please provide us colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by petkovacs19** [comment]
Thanks for the quick response! 
replication in colab: https://colab.research.google.com/drive/1UGx65koDCgR_h8doLYsbHnYMG4cdEyRf

**Comment by reedwm** [comment]
I don't know what the `df_tpu_estimator.py` file is. Can you post a self-contained colab or example to reproduce?

Also note, the `'mixed_float16'` policy only will have a performance improvement on GPUs, and otherwise there is no reason to use it. However, the policy should still work on CPUs, it will just be slow. Similarly, the `'mixed_bfloat16'` policy only has a performance improvement on TPUs.

**Comment by ravikyram** [comment]
@petkovacs19 

Any update on this issue please. Thanks!

**Comment by petkovacs19** [comment]
@reedwm Thanks for the clarification on the use of policies. The plan here was to do a simple few step test run on CPUs before running full training on GPUs

The issue is gone when getting rid of main method and running directly in notebook.

**Comment by ravikyram** [comment]
@petkovacs19 

Please close this thread if your issue was resolved. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
