### ISSUE TITLE
Hang on out of memory error

### ISSUE THREAD

**Issue by smatzek** [tensorflow/tensorflow#37029]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.1.0 and nightly, used `tensorflow/tensorflow:2.1.0-gpu-py3` and `tensorflow/tensorflow:nightly-gpu-py3 `
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:  P100 and V100
Driver: 440.33.01 
CUDA 10.1 in container

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TensorFlow hangs when it hits out of memory after it dumps the out of memory message.

**Describe the expected behavior**
TensorFlow should exit on non-zero return code on OOM.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
from tensorflow.keras import backend as K

import numpy as np


def random_image_generator(batch_size, num_classes, input_shape):
    templates = 2 * num_classes * np.random.random((num_classes,) + input_shape)
    random_data = np.random.normal(loc=0, scale=1., size=input_shape)
    while True:
        y = np.random.randint(0, num_classes, size=(batch_size,))
        x = np.zeros((batch_size,) + input_shape, dtype=np.float32)
        for i in range(batch_size):
            x[i] = templates[y[i]] + random_data
        x_array = np.array(x)
        y_array = tf.keras.utils.to_categorical(y, num_classes)
        yield(x_array, y_array)

def run_model():
    K.set_image_data_format('channels_first')
    image_dim = 5000
    input_shape = (3, image_dim, image_dim)

    num_classes = 15
    batch_size = 1
    model_class = tf.keras.applications.ResNet50
    model = model_class(weights=None, include_top=True, input_shape=input_shape,
                        classes=num_classes)

    model.compile(optimizer='rmsprop', loss='categorical_crossentropy')

    random_generator = random_image_generator(batch_size, num_classes,
                                              input_shape)
    model.fit(random_generator, steps_per_epoch=10,
              epochs=1)

run_model()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This program hangs after dumping the out of memory error on 16GB and 32GB GPUs (P100 and V100 tested). The program use to exit on TensorFlow 1.15. This happens on both the 2.1.0 and nightly containers on Intel x86 systems.

I originally hit this on built-from-source TensorFlow 2.1.0 on ppc64le. On that system, I attached gdb and dumped the stacks. It seems the code is hanging on the three thread stacks noted in the attachment.
[threeThreadStacks.txt](https://github.com/tensorflow/tensorflow/files/4246783/threeThreadStacks.txt)

**Comment by gadagashwini** [comment]
Was able to reproduce the issue on colab with Tf 2.1 and Tf-nightly.

**Comment by sanjoy** [comment]
This hangs inside `ParallelMapIterator::~ParallelMapIterator`.  Assigning to @jsimsa for further triaging.

**Comment by jsimsa** [comment]
@aaudiber could you please take a look?

**Comment by aaudiber** [comment]
From the stack traces, it looks like the program hangs while waiting for the Python generator function to complete. It isn't clear whether the Python function is hanging, or if it crashes but we fail to notify RunWithBorrowedArgs that it has finished. 

#6  0x00007fff462e9cd4 in tensorflow::condition_variable::wait
#7  0x00007fff4114079c in tensorflow::data::InstantiatedCapturedFunction::RunWithBorrowedArgs
#8  0x00007fff40d88d3c in tensorflow::data::GeneratorDatasetOp::Dataset::Iterator::GetNextInternal

@smatzek can you tell from the OOM error message where the OOM is encountered?

**Comment by aaudiber** [comment]
@gadagashwini I haven't been able to reproduce the hang. Can you share your repro methodology?

**Comment by gadagashwini** [comment]
@aaudiber, I could replicate the issue with Tf-gpu 2.1 on colab.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/b74f86d43ac19829827b59b3a149f876/untitled410.ipynb). At the end session stopped by saying `Your session crashed after using all available RAM`. Thanks!

**Comment by smatzek** [comment]
@aaudiber The stack after the memory region dump mentions FusedBatchNorm.

```
2020-02-28 16:35:54.147979: W tensorflow/core/framework/op_kernel.cc:1732] OP_REQUIRES failed at fused_batch_norm_op.cc:1181 : Resource exhausted: OOM when allocating tensor with shape[1,256,1250,1250] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
 1/10 [==>...........................] - ETA: 3:52Traceback (most recent call last):
  File "recreate.py", line 37, in <module>
    run_model()
  File "recreate.py", line 35, in run_model
    epochs=1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 718, in fit
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_v2.py", line 341, in fit
    total_epochs=epochs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 576, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 640, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2414, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1660, in _filtered_call
    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1741, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[1,256,1250,1250] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node resnet50/conv2_block2_3_bn/FusedBatchNormV3 (defined at recreate.py:35) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_distributed_function_19978]
```

**Comment by aaudiber** [comment]
> @aaudiber, I could replicate the issue with Tf-gpu 2.1 on colab.
> Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/b74f86d43ac19829827b59b3a149f876/untitled410.ipynb). At the end session stopped by saying `Your session crashed after using all available RAM`. Thanks!

@gadagashwini That's the behavior I get as well. In this case crashing after using all available RAM is the expected behavior, the issue is about hanging instead of crashing.


I spent some time trying to reproduce on my local GPU with both tf-nightly and tensorflow-2.1-gpu, but I've never been able to get a hang - the process always exits with an OOM error.

If the reported stack traces are to be believed, the hanging c++ thread is blocked waiting for the `random_image_generator` function to generate an element. It would be useful to know whether that python function is blocked during the hang, or whether the python function completed with an error, but failed to notify the GeneratorDataset thread. I visually inspected our logic for handling errors in calling a python function, and I don't see a way for the python function to complete without notifying the GeneratorDataset thread.

To debug further, I suggest simplifying the example as much as possible so that we can zero in on what exactly causes the hang.

**Comment by smatzek** [comment]
I gutted the random_image_generator and it does **NOT** hang for me.

Code:
```
import tensorflow as tf
from tensorflow.keras import backend as K

import numpy as np

image_dim = 5000
input_shape = (3, image_dim, image_dim)

num_classes = 15
batch_size = 1

templates = 2 * num_classes * np.random.random((num_classes,) + input_shape)
random_data = np.random.normal(loc=0, scale=1., size=input_shape)
y = np.random.randint(0, num_classes, size=(batch_size,))
x = np.zeros((batch_size,) + input_shape, dtype=np.float32)
for i in range(batch_size):
    x[i] = templates[y[i]] + random_data
x_array = np.array(x)
y_array = tf.keras.utils.to_categorical(y, num_classes)


def random_image_generator(batch_size, num_classes, input_shape):
    while True:
        yield(x_array, y_array)

def run_model():
    K.set_image_data_format('channels_first')

    model_class = tf.keras.applications.ResNet50
    model = model_class(weights=None, include_top=True, input_shape=input_shape,
                        classes=num_classes)

    model.compile(optimizer='rmsprop', loss='categorical_crossentropy')

    random_generator = random_image_generator(batch_size, num_classes,
                                              input_shape)
    model.fit(random_generator, steps_per_epoch=10,
              epochs=1)

run_model()
```

**Comment by aaudiber** [comment]
One idea is to add print statements to `random_image_generator` to see whether the function hangs.

**Comment by smatzek** [comment]
As noted in the original issue description, this hang on OOM did not occur on TF 1.15. The image generator is only calling out to tf.keras and numpy.

So this morning I tried the following container images:
tensorflow/tensorflow:1.15.2-gpu-py3 (has numpy 1.18.1)
tensorflow/tensorflow:2.0.0-gpu-py3  (has numpy 1.17.2)
tensorflow/tensorflow:2.1.0-gpu-py3 (has numpy 1.18.1)
tensorflow/tensorflow:nightly-gpu-py3 (has numpy 1.18.1)

The recreate program hangs on OOM in 2.1.0 and nightly. It does NOT hang in 1.15.2 or 2.0.0. The numpy levels used are noted above. I also upgrade numpy to 1.18.1 in my 2.0.0 container and it still did not hang.

Since the numpy levels remain constant and I see the change in behavior between 2.0.0 and 2.1.0 I suspect that something changed between 2.0.0 and 2.1.0 which is contributing to this behavior. Later today I'll diff tensorflow::data between the 2.0.0 and 2.1.0 tag levels and see if anything stands out to me.

**Comment by smatzek** [comment]
In my diff I noticed that the entire ParallelMapIterator class is new between 2.0.0 and 2.1.0. I spent over an hour investigating the code and following its waits/notifies. As far as I traced the code flows it looked OK to me.

I then added prints into the generator function and saw I do have a start without a yield. However, I do not think it is dependent on the actual work this function is doing. I replaced the work in the while loop with a simple sleep and still reproduced the hang on ParallelMapIterator.

I understand that the hang is "new" in 2.1.0 because ParallelMapIterator is doing the wait for all outstanding work on deconstruction. It may not have happened in the previous way this was called.

The random generator with only the sleep in the while/yield is:
```
def random_image_generator(batch_size, num_classes, input_shape):
    templates = 2 * num_classes * np.random.random((num_classes,) + input_shape)
    random_data = np.random.normal(loc=0, scale=1., size=input_shape)
    y = np.random.randint(0, num_classes, size=(batch_size,))
    x = np.zeros((batch_size,) + input_shape, dtype=np.float32)
    for i in range(batch_size):
        x[i] = templates[y[i]] + random_data
    x_array = np.array(x)
    y_array = tf.keras.utils.to_categorical(y, num_classes)
    while True:
        print('random_image_generator while start')
        time.sleep(1)
        print('random_image_generator while yield')
        yield(x_array, y_array)
```

In my recreate I see about 14 "while start" messages and 13 yields. So it's not the first result return either.

**Comment by aaudiber** [comment]
I don't think the issue is with `ParallelMapIterator` - it was moved between 2.0.0 and 2.1.0, but it's always had the logic of waiting for outstanding calls to finish during deconstruction: https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/core/kernels/data/parallel_map_iterator.cc#L70-L79

From the stack trace

#6 0x00007fff462e9cd4 in tensorflow::condition_variable::wait
#7 0x00007fff4114079c in tensorflow::data::InstantiatedCapturedFunction::RunWithBorrowedArgs
#8 0x00007fff40d88d3c in tensorflow::data::GeneratorDatasetOp::Dataset::Iterator::GetNextInternal

it looks like we're getting stuck here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/captured_function.cc#L717-L721. We call `lib_->Run` to invoke the python function, which is supposed to call `Notify()` when the python function completes (whether or not it succeeds). For some reason it looks like that callback never happens. It isn't clear whether that's because the python function itself never completes, or because `lib_->Run` fails to call `Notify` on some error-handling code path. If I could reproduce, I would add additional logging to see what happens in `lib_->Run`

**Comment by sushreebarsa** [comment]
Colab crashes while reproducing the issue with TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/b6d69794a8890503affb90f658e3da4d/untitled299.ipynb#scrollTo=juXh8fO8n5in)..Thanks!

**Comment by sushreebarsa** [comment]
@smatzek With the latest `tf-nightly` I believe the issue has been resolved with no crash anymore:Could you Please find the [gist ](https://colab.research.google.com/gist/sushreebarsa/93c4ba41732627df5e750ca1865ddb99/untitled299.ipynb#scrollTo=29gASIMYoGZD)here for reference and confirm the same ?Thank you!

**Comment by smatzek** [comment]
@sushreebarsa I see the gist failing with `InvalidArgumentError:  Default MaxPoolingOp only supports NHWC on device type CPU` rather than an out of memory error.

The [gist from June 23](https://colab.research.google.com/gist/sushreebarsa/b6d69794a8890503affb90f658e3da4d/untitled299.ipynb#scrollTo=juXh8fO8n5in), IS failing on OOM.

**Comment by tilakrayal** [comment]
Was able to reproduce the issue in tf v2.7. Please find the gist [here](https://colab.sandbox.google.com/gist/tilakrayal/f7355e559a93dd95610dcaf4d235a741/untitled162.ipynb)
