### ISSUE TITLE
TF 2.0 MultiWorkerMirror strategy hangs for MNIST Keras model training

### ISSUE THREAD

**Issue by arde171** [tensorflow/tensorflow#37108]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Red Hat Enterprise Linux Server release 7.4 (Maipo)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.0
- Python version: 3.7  
Bazel version (if compiling from source): 0.26.1 
- GCC/Compiler version (if compiling from
source): GCC 7.3.1
--
- CUDA/cuDNN version: - GPU model and memory: 10.1/7.6  NVIDIA TESLA V100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm using TF 2.0 multi-worker mirror strategy to  train keras mnist model using two nodes. Each node has 6 NVIDIA Tesla V100 GPUs. It hangs after starting the  grpc server.Please see the log for details.
 
**Describe the expected behavior**
It should start synchronous multi-worker training. 

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Please see the code in attachment.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Please see the log in attachment.

[mnist_multi_node_multi_gpu_py.txt](https://github.com/tensorflow/tensorflow/files/4258761/mnist_multi_node_multi_gpu_py.txt)
[worker0.txt](https://github.com/tensorflow/tensorflow/files/4259179/worker0.txt)
[worker1.txt](https://github.com/tensorflow/tensorflow/files/4259180/worker1.txt)

**Comment by arde171** [comment]
network issue. It works for me now.

**Comment by pbatk** [comment]
@arde171 Could you expand on what the network issue was? I am facing a very similar issue on only one of multiple machines on the network

**Comment by pbatk** [comment]
For anyone with this same issue, the only resolution I found was a complete OS reinstall. This surely is not a pleasant solution and is very likely not possible for most people. I validated all conceivable network configuration, full CUDA wipe/reinstall, full TF reinstall, etc. None of the solutions worked other than a system wipe and reinstall
