### ISSUE TITLE
tensorflow:Saver not created because there are no variables in the graph to restore

### ISSUE THREAD

**Issue by masumkmu** [tensorflow/tensorflow#37262]
I am a new bee trying to learn Tensorflow from this[ site ](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#test-tf-models). 
After all installation when I run:
`(tensorflow1) C:\tensorflow1\models\research\object_detection> jupyter notebook object_detection_tutorial.ipynb`
I got this message: "tensorflow:Saver not created because there are no variables in the graph to restore"

------------------------

### System information
- **Have I written custom code**: NO
- **OS Platform and Distribution: Windows 10_64
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:N/A
- **TensorFlow installed from (source or binary)**: conda install 
- **TensorFlow version (use command below)**: 2.1.0
- **Python version**: 3.7.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **CUDA/cuDNN version**: cudatoolkit =v10.1.243   cudnn  =v7.6.5
- **GPU model and memory**: GeForce 920MX  2GB

Problem:
I get the message 

> 
model_name = 'ssd_mobilenet_v1_coco_2017_11_17'
detection_model = load_model(model_name)

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

tensorflow:Saver not created because there are no variables in the graph to restore
and 
![image](https://user-images.githubusercontent.com/61747889/75795865-ddcac400-5dad-11ea-9fc6-c5e3f545c3d1.png)

finally end up with 
![image](https://user-images.githubusercontent.com/61747889/75796019-0fdc2600-5dae-11ea-8730-e19665de8371.png)

###Final error logs:
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-21-25f0f9a75087> in <module>
      1 for image_path in TEST_IMAGE_PATHS:
----> 2   show_inference(masking_model, image_path)

<ipython-input-17-e474e557b383> in show_inference(model, image_path)
      4   image_np = np.array(Image.open(image_path))
      5   # Actual detection.
----> 6   output_dict = run_inference_for_single_image(model, image_np)
      7   # Visualization of the results of a detection.
      8   vis_util.visualize_boxes_and_labels_on_image_array(

<ipython-input-16-4110867dcb70> in run_inference_for_single_image(model, image)
      7 
      8   # Run inference
----> 9   output_dict = model(input_tensor)
     10 
     11   # All outputs are batches tensors.

~\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   1549       TypeError: For invalid positional/keyword argument combinations.
   1550     """
-> 1551     return self._call_impl(args, kwargs)
   1552 
   1553   def _call_impl(self, args, kwargs, cancellation_manager=None):

~\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\eager\function.py in _call_impl(self, args, kwargs, cancellation_manager)
   1589       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
   1590           list(kwargs.keys()), list(self._arg_keywords)))
-> 1591     return self._call_flat(args, self.captured_inputs, cancellation_manager)
   1592 
   1593   def _filtered_call(self, args, kwargs):

~\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

~\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

~\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~\Anaconda3\envs\tensorflow1\lib\site-packages\six.py in raise_from(value, from_value)

ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted:  OOM when allocating tensor with shape[1166541600] and type int32 on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression/NonMaxSuppressionV2 (defined at <ipython-input-9-f8a3c92a04a4>:11) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[BatchMultiClassNonMaxSuppression/map/while/strided_slice/_170]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted:  OOM when allocating tensor with shape[1166541600] and type int32 on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression/NonMaxSuppressionV2 (defined at <ipython-input-9-f8a3c92a04a4>:11) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored. [Op:__inference_pruned_65677]

Function call stack:
pruned -> pruned

**Comment by amahendrakar** [comment]
@masumkmu,

The link you have provided does not have the code 
```
model_name = 'ssd_mobilenet_v1_coco_2017_11_17'
detection_model = load_model(model_name)
```
anywhere in the tutorial.

Also, I see that the tutorial is using TensorFlow 1.9, whereas you have TensorFlow 2.1 installed.

Could you please check out [this](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) official tutorial from TensorFlow, which uses TensorFlow 2.x for object detection. Thanks!

**Comment by Deadsec69** [comment]
I think thats more of the memory problem can you show us the output of nvidia-smi before runnnig the code and also the cudnn version

**Comment by amahendrakar** [comment]
@masumkmu,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Jackerho** [comment]
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
I don`t know why? who can tell me where the problem has been occurred..Thanks

**Comment by hyogrin** [comment]
Same issue here on "ssd_mobilenet_v1_coco_2017_11_17" and "ssd_mobilenet_v2_coco_2018_03_29" Does anyone find the solution? Does anyone knows the reason why it is not working? Using the frozen graphs is the best option for now?

**Comment by marued** [comment]
I'm having the same issue as op from "research/object_detection/object_detection_tutorial.ipynb".

**Comment by amahendrakar** [comment]
> I'm having the same issue as op from "research/object_detection/object_detection_tutorial.ipynb".

@marued,
Could you please submit a new issue from [this link](https://github.com/tensorflow/models/issues/new/choose) and fill in the issue template, so that we can track it there. Thanks!

**Comment by jajas** [comment]
I'm having the same issue as op from "research/object_detection/object_detection_tutorial.ipynb".
There is no answer about "ssd_mobilenet_v2_coco_2018_03_29" or other saved model.

**Comment by kwijik** [comment]
I use ML.NET and have the same issue: 
Saver not created because there are no variables in the graph to restore

**Comment by amahendrakar** [comment]
@kwijik,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the issue template, so that we can track it there. Thanks!

**Comment by ozett** [comment]
sorry, 
https://github.com/tensorflow/tensorflow/issues/37262#issuecomment-594477332
> 
> Could you please check out [this](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) official tutorial from TensorFlow, which uses TensorFlow 2.x for object detection. Thanks!

at 2020-06-26 the link seems broken...where is the 2.x correct ipython notebook for objectdetection?

**Comment by amahendrakar** [comment]
@ozett, 
Looks like the file has been removed. Could you please submit a new issue from [this link](https://github.com/tensorflow/models/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by ozett** [comment]
new issue here: https://github.com/tensorflow/models/issues/8736

**Comment by nawresmhedhbi** [comment]
any update ?

**Comment by mahamatnoumai** [comment]
Hi guys, here are my two cents about those people facing this kind  issues like `Saver not created because there are no variables in the graph to restore`
1. I believe you are trying to import frozen model that trained with tensorflow 1 by using tensorflow 2.
- check the version of the tensorflow you have installed in your system. 
2. if the model is trained with tensorflow 2, under the folder **saved_model** u will find while called variable and assets. try to load the model using tensorflow 2 as well. 
3. try to import your full path full path i mean you have to import **absolute path** to the file that you want to import. 

Hope this will help.

**Comment by knightperfectionist** [comment]
I am using 
bert-tensorflow==1.0.1
keras - 2.4.3


# We use the case model here
BERT_MODEL_HUB = "https://tfhub.dev/google/bert_cased_L-12_H-768_A-12/1"

def create_tokenizer_from_hub_module():
  """Get the vocab file and casing info from the Hub module."""
  with tf.Graph().as_default():
    bert_module = hub.Module(BERT_MODEL_HUB)
    tokenization_info = bert_module(signature="tokenization_info", as_dict=True)
    with tf.Session() as sess:
      vocab_file, do_lower_case = sess.run([tokenization_info["vocab_file"],
                                            tokenization_info["do_lower_case"]])
      
  return bert.tokenization.FullTokenizer(
      vocab_file=vocab_file, do_lower_case=do_lower_case)

tokenizer = create_tokenizer_from_hub_module()

After running above cell in Colab I'm getting the following msg

INFO:tensorflow:Saver not created because there are no variables in the graph to restore
INFO:tensorflow:Saver not created because there are no variables in the graph to restore

**Comment by 358383948** [comment]
@knightperfectionist Have you solved this problem?

**Comment by sujeethkanuganti** [comment]
I removed this line and it worked

 tf.compat.v1.disable_eager_execution()

**Comment by 358383948** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，现在我不在线。我在看到后，尽快给你回复。

**Comment by Petros626** [comment]
> @masumkmu,
> 
> The link you have provided does not have the code
> 
> ```
> model_name = 'ssd_mobilenet_v1_coco_2017_11_17'
> detection_model = load_model(model_name)
> ```
> 
> anywhere in the tutorial.
> 
> Also, I see that the tutorial is using TensorFlow 1.9, whereas you have TensorFlow 2.1 installed.
> 
> Could you please check out [this](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) official tutorial from TensorFlow, which uses TensorFlow 2.x for object detection. Thanks!

switching always to the neweste version , isnt the solution...

**Comment by 358383948** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，现在我不在线。我在看到后，尽快给你回复。

**Comment by Petros626** [comment]
> Hi guys, here are my two cents about those people facing this kind issues like `Saver not created because there are no variables in the graph to restore`
> 
> 1. I believe you are trying to import frozen model that trained with tensorflow 1 by using tensorflow 2.
> 
> * check the version of the tensorflow you have installed in your system.
> 
> 2. if the model is trained with tensorflow 2, under the folder **saved_model** u will find while called variable and assets. try to load the model using tensorflow 2 as well.
> 3. try to import your full path full path i mean you have to import **absolute path** to the file that you want to import.
> 
> Hope this will help.

Can you help further?

**Comment by Petros626** [comment]
> I removed this line and it worked
> 
> tf.compat.v1.disable_eager_execution()

You use the TF1 version or 2?
