### ISSUE TITLE
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by innjoshka** [tensorflow/tensorflow#37725]
**System information** 
- OS Platform and Distribution: Ubuntu 18.04.
- LInux Kernel: 
> 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- TensorFlow installed from source as written [here](https://www.tensorflow.org/install/source#gpu_support_2) (tried from binary also): 
- Build was with all flags OFF except cuda-Y
- TensorFlow version: 2.1.0
- Python version: 3.6.9 
- Bazel: 0.29.1
- GCC/Compiler version: 7.5.0 
- CUDA/cuDNN version: - GPU model and memory:
CUDA: 10.1
CuDNN: 7.6.5 ( tried 7.6.1 also)
GPU model: Nvidia Geforce 1660 Ti (6 GB)
------------------------------------------------------------------------------------------------------------------------------

Tried to execute simple MNIST CNN [example](https://keras.io/examples/mnist_cnn/) but with **tensorflow.keras** importing NOT keras!

**Error**
> UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[node sequential/conv2d/Conv2D (defined at <ipython-input-4-288e0dab5d94>:70) ]] [Op:__inference_distributed_function_1004]
> 
> Function call stack:
> distributed_function

------------------------------------------------------------------------------------------------------------------------------
Firstly, I got this error when installed tensorflow-gpu from binary via pip.

Then, I thought that against CUDA-10.1 I have to manually build tensorflow via bazel but after successful built - **I got the same error**. I have also tried change CuDNN version from 7.6.5 to 7.6.1 but again it did not help. 

**CUDA** downloaded **from nvidia website** and works perfectly
**CuDNN** is rightly installed by downloading it **from nvidia website** and copying into `/usr/loca/cuda-*`
```
cp -P cuda/include/cudnn.h /usr/local/cuda-${CUDA_VERSION}/include
cp -P cuda/lib64/libcudnn* /usr/local/cuda-${CUDA_VERSION}/lib64/
chmod a+r /usr/local/cuda-${CUDA_VERSION}/lib64/libcudnn*
```

If I try to train model without **Convolution layers** all works great with GPU calculations:
for example
```
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
```

If you need some additional information, I will add it.

Please, help me solve this issue, I truly don't know what else try using. BTW. As I am concerned, I need CUDA-10.1  because only this CUDA supports my Nvidia Geforce 1660 Ti.

**Comment by Saduf2019** [comment]
@innjoshka 
please share the tensorflow version on which this issue is faced.

could you please refer to existing similar issues as per error message shared:
#34355 #34888 #34518 #28326 #25160  #24828 #33666

**Comment by innjoshka** [comment]
@Saduf2019 updated tensorflow version.

from this issue #34888 I got it working

```
 import tensorflow as tf
 gpus= tf.config.experimental.list_physical_devices('GPU')
 tf.config.experimental.set_memory_growth(gpus[0], True)
```
But after **set_memory_growth**, NN now trains, 22s/epoch vs 30s/epoch cpu. ( Not the great improvement) And how is that possible that 6GB GPU errors on MNIST dataset with Conv2D layer? 

Without **set_memory_growth**  and without Conv2D layers on MNIST  train time on my machine takes 3s. model structure attached. 
```
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
```

Is that normal?

**Comment by gowthamkpr** [comment]
@innjoshka Can you please check this with `tensorflow 2.2.0-rc1` and let me know if the issue still persists. Thanks!

**Comment by innjoshka** [comment]
@gowthamkpr I will try, Should I build from source or download via pip (as I know `tensorflow 2.2.0-rc1` cannot be downloaded via pip, only build from source, am I right?)
Can you give working versions of packages to build `tensorflow 2.2.0-rc1`:
CUDA version
CuDNN version 
Bazel version
Nvidia driver version (435 is the latest for 10.1)

**Comment by Jamesbond32** [comment]
```
import tensorflow as tf
gpus= tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
```

using this code inside my jupyter notebook worked. 

```
tesorflow version = 2.1.0
Driver Version: 440.64       
CUDA Version: 10.2 
cudnn version: 7.6.5 
```

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Please add additional comments for us to open this issue again. Thanks!

**Comment by CARLOSALBERTOCORDERO** [comment]
I had this same issue and any one of this solution helped me, but I got another solution. Apparently some TF.keras libraries were giving me problems instead I imported just keras libraries. 
For example, here is my importing list for one project:
import sys
import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from keras.models import Sequential  # Can not be moved
from tensorflow.keras.models import load_model
from keras.layers import Conv2D, MaxPooling2D  # Can not be moved
from keras.layers import Activation, Dropout, Flatten, Dense # Can not be moved
from tensorflow.keras import backend as K
from tensorflow.keras.preprocessing import image
import numpy as np
from os import listdir
from os.path import isfile, join
from keras import optimizers
import matplotlib.pyplot as plt

I am using:
Python : 3.6.8
Cuda: 10
Cunn: 7.6.0
tensorflow-gpu       2.0.0
Keras                2.3.1

I spent more than 8 hours trying all the solutions of this chat and just after doing this importing and configuration everything goes well. Actually, really well.

I believe that I can upgrade to tensorflow 2.1 and the corresponding Cuda and Cunn without any problem.
