### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR after hours of HyperParameter optimization.

### ISSUE THREAD

**Issue by nistrup** [tensorflow/tensorflow#37932]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): **I'm using completely standard Tensorflow / Keras implementations, see code below.**
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): **Windows 10**
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): **tensorflow==2.1.0**
- Python version: - Bazel
version (if compiling from source): **Python 3.7**
- CUDA/cuDNN version: - GPU model and memory: **Nvidia GTX 1070 8GB, Cuda compilation tools release 10.1, V10.1.243**

**Describe the current behavior**

I was training and tuning HyperParameters using "Keras Tuner" for about ~2 hours until I noticed that no new trials where created in the "Tuner project" folder, this is my training setup:
![image](https://user-images.githubusercontent.com/17565925/77623713-e17ee000-6f40-11ea-9d7b-bc9e2fad9b5f.png)

And this is my dynamic model:
![image](https://user-images.githubusercontent.com/17565925/77623844-24d94e80-6f41-11ea-831c-55d1eb62ee31.png)

After I noticed the stand-still I checked my terminal and got the following error:
![Fejlmeddelse](https://user-images.githubusercontent.com/17565925/77624487-3111db80-6f42-11ea-84e4-70a111ff2478.png)

**Describe the expected behavior**

I would expect the training to keep running. It completed 48 permutations training each one 3 times, i.e. 144 models without error, so the sudden interruption and kernel restart is weird to me!

**Standalone code to reproduce the issue** 

In addition to the code referenced above, I've pretty much followed the setup in this Tensorflow tutorial: [Time series forecasting](https://www.tensorflow.org/tutorials/structured_data/time_series#single_step_model)

**Comment by Saduf2019** [comment]
@nistrup 
please refer to these issues as per the error faced  ##29632 #33848 #28254 and [comments](https://github.com/tensorflow/tensorflow/issues/24496)
let us know if it [helps](https://github.com/tensorflow/tensorflow/issues/34695)

**Comment by nistrup** [comment]
@Saduf2019 Thank you!

I seem to get a different error now after training several modes successfully I get this:

`InternalError:  [_Derived_]  Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 8, 128, 1, 90, 64, 128] 
	 [[{{node gradients/CudnnRNN_grad/CudnnRNNBackprop}}]]
	 [[StatefulPartitionedCall_2]] [Op:__inference_distributed_function_353504]

Function call stack:
distributed_function -> distributed_function -> distributed_function`

Any ideas?

**Comment by Saduf2019** [comment]
@nistrup 
with reference to the error shared please find these example issues, let us know if it helps:

#35950 #33536 #33924

**Comment by nistrup** [comment]
> @nistrup
> with reference to the error shared please find these example issues, let us know if it helps:
> 
> #35950 #33536 #33924

I'm afraid none of this has worked. I'll spend some time trying to do a completely clean install and maybe try to downgrade my GPU drivers as well. So far nothing has worked. The models train completely fine using CPU only and breaks seemingly at random when using GPU, like in https://github.com/tensorflow/tensorflow/issues/37942

**Comment by jliebers** [comment]
Hi @nistrup ,

please check my issue #37942. I might have found a solution for your problem as well. 🙂

**Comment by nistrup** [comment]
> Hi @nistrup ,
> 
> please check my issue #37942. I might have found a solution for your problem as well. 🙂

Thanks! It seems to have fixed one of my issues at least! Now I'm faced with this instead:

```
2020-03-27 17:21:28.275596: F .\tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)
[I 17:21:29.843 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel 2bac517a-c195-47ca-952b-c25881cf0757 restarted
```

And the Jupyter Kernel crashes. Any ideas? :)

**Comment by jliebers** [comment]
What is your batch_size as part of `batch_input_shape=(batch_size, n_timesteps, n_features)`?

**Comment by nistrup** [comment]
> What is your batch_size?
> 
> (As part of `batch_input_shape=(batch_size, n_timesteps, n_features)`)?

Currently 256, I'm using a setup where each HyperParameter permutation model is trained 3 times to give me an average score, the first model completes all 3 runs but then the kernel seems to die when starting the first run of the 2nd model.

**Comment by jliebers** [comment]
I had also issues with such a high batch_size. 197 for me, for instance, did not work out and it lead to crashes. Currently I use some value between 60 and 160 and it works. Remember that it needs to be a divisor of len(X). 😄

**Comment by nistrup** [comment]
> I also had this issues with such a high batch_size. `197` for me, for instance, did not work out and it lead to crashes with the same error.
> 
> Currently I use some value between 60 and 160 as `batch_size` and it works. Remember that it needs to be a divisor of len(X). 😄

I just tried with BATCH_SIZE = 64 and the exact same thing happens, i.e. kernel crashes with `Check failed: work_element_count > 0 (0 vs. 0)`

Regarding the fact that it needs to be a divisor of len(x_train), I think this should fix "itself" when constructing training data using the `.batch(BATCH_SIZE, drop_remainder=True)`

**Comment by jliebers** [comment]
Concerning `drop_remainder` I would think so too. 

I just checked and found that my error was slightly different:

```
2020-03-27 15:01:57.982960: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2020-03-27 15:01:57.983072: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
```

So my advice maybe (lowering the batch_size) was not right.

I fear, that you have gotten off the path that we shared, as your setup starts beginning to be different than mine. I really am not so happy about the current state of GPU-accelerated in Tensorflow/Keras, it is really tough to use. As I could not reproduce my problem with Google Colab, I really hope, that it is just an issue with my platform.

Good luck to you!

**Comment by nistrup** [comment]
I also think our paths have diverged slightly at this point! :)

Thanks a bunch for trying to help me out though, thoroughly appreciated!

**Comment by nistrup** [comment]
I think I will close this issue and create a new one related to my current issue instead since this seems to be unrelated at this point. Thanks! :)

**Comment by pavlexander** [comment]
@nistrup 
Could you elaborate something? As I understood - when setting the `batch_input_shape` then you are forcing yourself to use the input data of given dimensions. So, then, if I later wanted to predict the outcome based on the input of batch size = 1 - that wouldn't be possible, is that correct?

In my current implementation I use a batch size of 2048 for training, and I want to be able to use a batch size of 1 for predictions later on. Will it still be possible to use your proposed solution? (sorry I am new in ML)


On a side note, I would like to ask whether there is a difference between using a dataset with a given batch size and how is it different/how does it work with conjunction with the back-size that we define for the model layers and fit method..?

i.e. what's the difference between:

	steps_per_epoch = compute_steps_per_epoch(train_size) # int(train_size / batch_size)
	val_steps = compute_steps_per_epoch(validation_size)

	features = tf.convert_to_tensor(TRAIN_X, dtype=tf.float32)
	labels = tf.convert_to_tensor(TRAIN_y, dtype=tf.float32)

	features2 = tf.convert_to_tensor(VALIDATION_X, dtype=tf.float32)
	labels2 = tf.convert_to_tensor(VALIDATION_y, dtype=tf.float32)

	# Train model
	history = model.fit(
		x=features,
		y=labels,
		steps_per_epoch=steps_per_epoch,
		epochs=epochs,
		validation_data=(features2, labels2),
		validation_steps=val_steps,
		callbacks=[tensor_board, post_processing_callback, checkpoint],
		class_weight=d_class_weights
	)
					
and explicitly generating batches:

	compute_steps_per_epoch = lambda x: int(math.ceil(1. * x / batch_size))
		
	steps_per_epoch = compute_steps_per_epoch(train_size)
	val_steps = compute_steps_per_epoch(validation_size)

	buffer_size_train = train_size
	train_data_ds = tf.data.Dataset.from_tensor_slices((TRAIN_X, TRAIN_y))
	train_data_batch = train_data_ds\
		.shuffle(buffer_size_train)\
		.batch(batch_size, drop_remainder=True)\
		.repeat()

	buffer_size_validation = validation_size
	validation_data_ds = tf.data.Dataset.from_tensor_slices((VALIDATION_X, VALIDATION_y))
	validation_data_batch = validation_data_ds\
		.shuffle(buffer_size_validation)\
		.batch(batch_size, drop_remainder=True)\
		.repeat()

	steps_per_epoch = compute_steps_per_epoch(train_size)
	val_steps = compute_steps_per_epoch(validation_size)

	history = model.fit(
		x=train_data_batch,
		steps_per_epoch=steps_per_epoch,
		epochs=epochs,

		validation_data=validation_data_batch,
		validation_steps=val_steps,

		callbacks=[tensor_board, post_processing_callback, checkpoint],
		class_weight=d_class_weights
	)

**Comment by braibaud** [comment]
I have recently had the exact same problem on Windows 10 and I figured out a solution.

The machine used has got a dual graphic card, one of them is an NVidia Quadro P5200 (16GB) and the second one a standard Intel 630 used for display. I am running Keras 2.3.1 (on top of TensorFlow GPU 2.1.0) with Python 3.7.7.

The problem mentionned above was occurring regardless of the batch_size (it also failed when batch_size was set to 1).

What worked for me was to switch the NVidia card to `TCC` mode by running the following command (you need to **Run As Admin**).

`"C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe" -g 0 -dm 1`

Then reboot.
Then go to the Device Manager and re-enable the device (I am still unsure why this steps is required, but it seems to be).

After this, confirm the NVidia card has switched to TCC mode by running (you need to **Run As Admin**).

`"C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe"`

which should output something like this:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 451.77       Driver Version: 451.77       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P5200        TCC  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8     5W /  N/A |  15705MiB / 16296MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

(Note that once the card has switched to TCC mode, it disappear from the **Task Manager** performance tab.

I hope this helps.
