### ISSUE TITLE
Dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory;

### ISSUE THREAD

**Issue by Zethson** [tensorflow/tensorflow#38164]
**System information**
- OS Platform and Distribution: nvidia/cuda:10.1-base-ubuntu18.04 docker base
- TensorFlow installed from (source or binary): Custom
- TensorFlow version: 2.2rc2
- Python version: 3.73
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 10.1, 7.x
- GPU model and memory: 1050M

**Describe the problem**
Hi,

I am trying to create my own Docker container for Tensorflow on the GPU.

My base is: 
```
FROM nvidia/cuda:10.1-base-ubuntu18.04
LABEL authors="Lukas Heumos (lukas.heumos@posteo.net)" \
      description="Docker image containing all requirements for running machine learning on CUDA enabled GPUs"

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*

# Create a working directory and set it as default
RUN mkdir /app
RUN chmod 777 /app
WORKDIR /app

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user 
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user

 # Install Miniconda
RUN curl -so ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh
ENV PATH=/home/user/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

# Update Conda
RUN conda update conda
```

And my tensorflow container is: 

```
From mlflowcore/base:1.0.0

# Install the conda environment
COPY tensorflow_environment.yml .
RUN conda env create -f tensorflow_environment.yml && conda clean -a

# Activate the environment
RUN echo "source activate tensorflow-2.1-cuda-10.1" > ~/.bashrc
ENV PATH /opt/conda/envs/env/bin:$PATH

# Dump the details of the installed packages to a file for posterity
RUN conda env export --name tensorflow-2.1-cuda-10.1 > tensorflow-2.1-cuda-10.1.yml
```
with the environment.yml:

```
name: tensorflow-2.1-cuda-10.1
channels:
    - conda-forge
    - defaults
dependencies:
    - defaults::cudatoolkit=10.1
    #- defaults::tensorflow=2.1.0 -> distribute.MirroredStrategy API changed in 2.2 -> https://www.tensorflow.org/tutorials/distribute/custom_training
    - conda-forge::graphviz=2.40.1
    - conda-forge::python-graphviz=0.13.2
    - pip
    - pip:
      - tensorflow==2.2.0rc2
```

However, when trying to run stuff on the GPU I get:

> 2020-04-02 09:39:54.522822: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> 2020-04-02 09:39:54.570821: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2020-04-02 09:39:54.572960: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
> 2020-04-02 09:39:54.573491: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
> 2020-04-02 09:39:54.577211: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
> 2020-04-02 09:39:54.578817: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
> 2020-04-02 09:39:54.579250: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
> 2020-04-02 09:39:54.579268: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. 
> Skipping registering GPU devices...

Why does it not find that file? Where is it?

Help would be highly appreciated.
Thank you very much!
Best

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Simple 

`tf.config.list_physical_devices('GPU')`

Also ran an MNIST example. Without success.

**Any other info / logs**
I am using the very same Base & Docker image structure for Pytorch and XGBoost and it works flawlessly and uses the GPU. Hence, this is a Tensorflow issue.

**Comment by Zethson** [comment]
Oh, and using one of the already existing Tensorflow docker images is **not** an option for me. And yes, I've read all GPU installation guides for Tensorflow, but they're not helpful regarding my issue.

**Comment by Zethson** [comment]
Added

```
ENV LD_LIBRARY_PATH “$LD_LIBRARY_PATH:/usr/local/cuda/lib64”
ENV LD_LIBRARY_PATH “$LD_LIBRARY_PATH:/usr/local/cuda-10.1/compat”
```

And now get:

  ```
  2020-04-03 08:50:37.180018: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
    2020-04-03 08:50:37.181533: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination
    2020-04-03 08:50:37.181612: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 64683ab6f51a
    2020-04-03 08:50:37.181642: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 64683ab6f51a
    2020-04-03 08:50:37.181816: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 418.87.1
    2020-04-03 08:50:37.181877: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0
    2020-04-03 08:50:37.181898: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 440.64.0 does not match DSO version 418.87.1 – cannot find working devices in this configuration
```

I need to somehow update the Nvidia drivers maybe? I cannot reboot however in a Docker container...

**Comment by Zethson** [comment]
All right.
So the solution/issue is that installing tensorflow-gpu is required BEFORE installing  tensorflow==2.2.0rc2

So tensorflow-gpu must contain some packages or installation instructions that tensorflow==2.2.0rc2 does not have anymore.

**Comment by engrmz** [comment]
Hello everyone,
I solved the error by installing cuDNN 7.6. I followed these steps;

1. Remove cuda tool kit from anaconda environment using command ([conda remove cudatoolkit](conda remove cudatoolkit))

2. Download **cuDNN v7.6.4** (September 27, 2019), **for CUDA 10.1** [(https://developer.nvidia.com/rdp/cudnn-archive)](https://developer.nvidia.com/rdp/cudnn-archive)
              cuDNN _Runtime_ Library for Ubuntu18.04 (Deb)
              cuDNN _Developer_ Library for Ubuntu18.04 (Deb) 
              cuDNN _Code Samples_ and User Guide for Ubuntu18.04 (Deb)

2. Installed the above 3 files _in the same sequence_.

**Comment by amahendrakar** [comment]
> So the solution/issue is that installing tensorflow-gpu is required BEFORE installing tensorflow==2.2.0rc2

@Zethson,
Is this still an issue?

Also, please take a look at @engrmz's comment and check if it helps. Thanks!

**Comment by Zethson** [comment]
> > So the solution/issue is that installing tensorflow-gpu is required BEFORE installing tensorflow==2.2.0rc2
> 
> @Zethson,
> Is this still an issue?
> 
> Also, please take a look at @engrmz's comment and check if it helps. Thanks!

Honestly I don't know anymore because since then I moved on with my containers. Running into similar issues with libcudnn.so.8 atm. It's just a mess with Tensorflow. The same containers always, always, always run smoothly with Pytorch. But well it's difficult to get this smoothly.
