### ISSUE TITLE
Build fails Tensorflow 0.9, with cuda 8.0 on Ubuntu 16.04, ppc64le

### ISSUE THREAD

**Issue by npanpaliya** [tensorflow/tensorflow#3845]
Tensorflow 0.9, with cuda 8.0 fails to build on Ubuntu 16.04 linux ppc64le. Without cuda, it does build successfully. Is this NVIDIA driver issue? Or some eigen issue. Kindly help.

The error I get is as below -
external/eigen_archive/eigen-eigen-d02e6a705c30/unsupported/Eigen/CXX11/src/Tensor/TensorBroadcasting.h(192): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/folding.c", line 9819

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00020696_00000000-9_cwise_op_gpu_select.cu.compute_52.cpp1.ii".
Compilation aborted.
Aborted
ERROR: /home/nishidha/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/BUILD:973:1: output 'tensorflow/core/kernels/_objs/cwise_op_gpu/tensorflow/core/kernels/cwise_op_gpu_select.cu.pic.o' was not created.
ERROR: /home/nishidha/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/BUILD:973:1: not all outputs were created.
Target //tensorflow/tools/pip_package:build_pip_package failed to build

### Environment info
Operating System: Ubuntu 16.04, ppc64le
NVIDIA Driver: 361.78

Installed version of CUDA and cuDNN: Cuda 8.0 with cudnn 5.1
$ ls -s /usr/local/cuda/lib64
total 1239696
 48080 libcublas_device.a        0 libcufftw.so.8.0            0 libnppc.so.8.0         20320 libnppig.so.8.0.35    10864 libnpps_static.a
     0 libcublas.so            556 libcufftw.so.8.0.35       536 libnppc.so.8.0.35          0 libnppim.so               0 libnvblas.so
     0 libcublas.so.8.0         48 libcufftw_static.a         28 libnppc_static.a           0 libnppim.so.8.0           0 libnvblas.so.8.0
 37884 libcublas.so.8.0.35       0 libcuinj64.so               0 libnppial.so            4296 libnppim.so.8.0.35      584 libnvblas.so.8.0.35
 43936 libcublas_static.a        0 libcuinj64.so.8.0           0 libnppial.so.8.0           0 libnppi.so                0 libnvgraph.so
   552 libcudadevrt.a         5572 libcuinj64.so.8.0.35     9684 libnppial.so.8.0.35        0 libnppi.so.8.0            0 libnvgraph.so.8.0
     0 libcudart.so             36 libculibos.a                0 libnppicc.so          105316 libnppi.so.8.0.35      4568 libnvgraph.so.8.0.35
     0 libcudart.so.8.0          0 libcurand.so                0 libnppicc.so.8.0      131588 libnppi_static.a       6824 libnvgraph_static.a
   464 libcudart.so.8.0.35       0 libcurand.so.8.0         3864 libnppicc.so.8.0.35        0 libnppist.so              0 libnvrtc-builtins.so
   936 libcudart_static.a    57768 libcurand.so.8.0.35         0 libnppicom.so              0 libnppist.so.8.0          0 libnvrtc-builtins.so.8.0
     4 libcudnn5.0.5         57820 libcurand_static.a          0 libnppicom.so.8.0      13860 libnppist.so.8.0.35    9400 libnvrtc-builtins.so.8.0.35
     0 libcudnn.so               0 libcusolver.so           1104 libnppicom.so.8.0.35       0 libnppisu.so              0 libnvrtc.so
     0 libcudnn.so.5             0 libcusolver.so.8.0          0 libnppidei.so              0 libnppisu.so.8.0          0 libnvrtc.so.8.0
 76296 libcudnn.so.5.0.5     50916 libcusolver.so.8.0.35       0 libnppidei.so.8.0        528 libnppisu.so.8.0.35   19380 libnvrtc.so.8.0.34
 67748 libcudnn_static.a     21528 libcusolver_static.a     6912 libnppidei.so.8.0.35       0 libnppitc.so              0 libnvToolsExt.so
     0 libcufft.so               0 libcusparse.so              0 libnppif.so                0 libnppitc.so.8.0          0 libnvToolsExt.so.1
     0 libcufft.so.8.0           0 libcusparse.so.8.0          0 libnppif.so.8.0         2916 libnppitc.so.8.0.35      44 libnvToolsExt.so.1.0.0
143232 libcufft.so.8.0.35    42080 libcusparse.so.8.0.35   46544 libnppif.so.8.0.35         0 libnpps.so                4 stubs
126244 libcufft_static.a     50268 libcusparse_static.a        0 libnppig.so                0 libnpps.so.8.0
     0 libcufftw.so              0 libnppc.so                  0 libnppig.so.8.0         8564 libnpps.so.8.0.35

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`) - v0.9.0 (and cherry-pick two commits - 2c3385523f00ea7de97ec16a7c060b39b834a7f5 and ea9e00a630f91a459dd5858cb22e8cd1a666ba4e)
2. The output of `bazel version` - 0.2.0

### Steps to reproduce
1. ./configure - Enable GPU support, Cloud Platform support, and rest all with default
2. bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### What have you tried?
1. Building without GPU support works.

**Comment by sherrym** [comment]
This looks like a nvidia bug on powerpc.

**Comment by npanpaliya** [comment]
@sherrym , Thanks. Yes, it looks so. I tried by downgrading nvidia driver to 361.62 (cuda 8.0.27) and building Tensorflow 0.9, and it worked. Just one workaround is need to get rid of cuda 8 and gcc 5.4 compatibility issue. I'd to hand-edit /usr/local/cuda/include/host_config.h file to remove that #error that pops up if we've gcc greater 5.3. We've filed a NVIDIA bug for the same.

**Comment by prb12** [comment]
Appears not to be a TF issue.  Please reopen if this is not the case.

**Comment by joshsuihn** [comment]
I think this is a TF issue when building it on embedded.
http://stackoverflow.com/questions/39783919/tensorflow-on-nvidia-tx1/39903431 

-- a/tensorflow/core/kernels/cwise_op_gpu_select.cu.cc
+++ b/tensorflow/core/kernels/cwise_op_gpu_select.cu.cc
@@ -43,8 +43,14 @@ struct BatchSelectFunctor<GPUDevice, T> {
     const int all_but_batch = then_flat_outer_dims.dimension(1);
[
 #if !defined(EIGEN_HAS_INDEX_LIST)
-    Eigen::array<int, 2> broadcast_dims{{ 1, all_but_batch }};
-    Eigen::Tensor<int, 2>::Dimensions reshape_dims{{ batch, 1 }};
+    //DC Eigen::array<int, 2> broadcast_dims{{ 1, all_but_batch }};
+    Eigen::array<int, 2> broadcast_dims;
+    broadcast_dims[0] = 1;
+    broadcast_dims[1] = all_but_batch;
+    //DC Eigen::Tensor<int, 2>::Dimensions reshape_dims{{ batch, 1 }};
+    Eigen::Tensor<int, 2>::Dimensions reshape_dims;
+    reshape_dims[0] = batch;
+    reshape_dims[1] = 1;
 #else
     Eigen::IndexList<Eigen::type2index<1>, int> broadcast_dims;
     broadcast_dims.set(1, all_but_batch);](url)

**Comment by sunsided** [comment]
The same happens when building TensorFlow 1.0 on Tegra (Nvidia Jetson TX1) and cuda 8.0.34. Patching away the `#error` as @npanpaliya described (I had to do this trick once with Caffe) did not help for me; in fact, some of the cuda sources do _seem_ to get compiled. I tried both the 1.0 tag as well as master for a while now and nothing seems to work.

Here's the system info:

```
Linux tegra-ubuntu 3.10.96-tegra #1 SMP PREEMPT Wed Nov 9 19:42:57 PST 2016 aarch64 aarch64 aarch64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

I started the build using

```
bazel build --verbose_failures --local_resources 2048,.5,1.0 --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

At one point it was complaining abount `cwise_op_gpu_select.cu.pic.o`, during the last try it apparently chose to fail at `softmax_op_gpu.cu.pic.o`:
```
INFO: From Compiling tensorflow/core/common_runtime/gpu/gpu_tracer.cc:
tensorflow/core/common_runtime/gpu/gpu_tracer.cc:82:13: warning: 'const char* {anonymous}::getActivityOverheadKindString(CUpti_ActivityOverheadKind)' defined but not used [-Wunused-function]
 const char *getActivityOverheadKindString(CUpti_ActivityOverheadKind kind) {
             ^
INFO: From Compiling tensorflow/core/distributed_runtime/rpc/grpc_worker_service_impl.cc:
tensorflow/core/distributed_runtime/rpc/grpc_worker_service_impl.cc: In function 'const char* tensorflow::GrpcWorkerMethodName(tensorflow::GrpcWorkerMethod)':
tensorflow/core/distributed_runtime/rpc/grpc_worker_service_impl.cc:50:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: From Compiling tensorflow/core/debug/debug_io_utils.cc:
tensorflow/core/debug/debug_io_utils.cc:306:15: warning: 'tensorflow::Status tensorflow::CloseDebugURL(const string&)' defined but not used [-Wunused-function]
 static Status CloseDebugURL(const string& debug_url) { return Status::OK(); }
               ^
INFO: From Compiling tensorflow/core/kernels/softmax_op_gpu.cu.cc:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBroadcasting.h(275): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/folding.c", line 9819


1 catastrophic error detected in the compilation of "/tmp/tmpxft_00003c5c_00000000-9_softmax_op_gpu.cu.compute_52.cpp1.ii".
Compilation aborted.
Aborted
ERROR: /mnt/tensorflow/tensorflow/core/kernels/BUILD:2531:1: output 'tensorflow/core/kernels/_objs/softmax_op_gpu/tensorflow/core/kernels/softmax_op_gpu.cu.pic.o' was not created.
ERROR: /mnt/tensorflow/tensorflow/core/kernels/BUILD:2531:1: not all outputs were created or valid.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 6367.284s, Critical Path: 5141.64s
```
