### ISSUE TITLE
Install the TensorFlow-GPU and CUDA and CUDnn, but GPU not work when test.

### ISSUE THREAD

**Issue by jz1998** [tensorflow/tensorflow#38482]
**System information**
- OS Platform and Distribution: Win10, X64
- TensorFlow version: 1.15
- Python version: 3.5
- Installed using virtualenv? pip? conda?: pip install tensorflow_gpu-1.15.0-cp35-cp35m-win_amd64
- CUDA/cuDNN version: 10.2/7.6.5
- GPU model and memory: GTX1050

**problem details**
i use the Anaconda, the first i create a new environment which python version is 3.7 and TensorFlow-GPU is 2.1. and then i install the CUDA 10.2and CUDNN, 7.6.5, but when i test it, there is a error said can't find the cudart64_101.dll file, when i changed that file(cudart64_102.dll) its name to cudart64_101.dll, no error again, and when i run the follow code showing true
`#code 1`
`import tensorflow as tf`
`print(tf.test.is_gpu_available())`
and running that below code also show the GPU device log
`#code 2`
`import tensorflow as tf`
`sess = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(log_device_placement=True))`
all is going well on tensorflow 2.1 with GPU

but when i wanna to use tf-gpu 1.X, i install the tensorflow-gpu 1.15, with the same CUDA, CUDNN version, i made a copy of cudart64_101.dll and rename cudart_100.dll, when i run the above test code, the console shows no error, but show false in the code 1 and did not show GPU device info in code 2. i was wondering that if the CUDA/CUDNN version isn't fit the tensorflow-gpu version, is any error will show? i think there must be some error will be report. The problem is i don't know how to fix it **because it didn't report error** .

should i uninstall the CUDA 10.2 and CUDNN and install CUDA 10.0/10.1 but...

**Any other info / logs**
and when i import tensorflow in anaconda prompt , there is no warning or error, just shows 
`tensorflow/stream_executor/platform/default/http://dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll`

**Comment by ymodak** [comment]
TF 1.15 supports cuda 10.0 and cudnn >=7.4 . You have to roll back to cuda 10.0 
Thank you.

**Comment by jz1998** [comment]
THX, and i want to know if i roll back to CUDA 10.0, my another environment with tensorflow-gpu-2.1 can fit the CUDA 10.0? because i refer to the tensorflow.org only showing tensorflow-gpu-2.0 to CUDA 10.

Sorry, a little more question, someone told me that there can't exist tf-gpu or tf-cpu at the same time  in one environment, which means we should create two environments to manage tf-cpu and tf-gpu. is it true? 

and a not related question, can i instal the CUDA10.2 & CUDA 10.0 in win 10?

why tf 1.5 can not support CUDA > =10.0 same as the CUDNN can > =7.4?

Really thanks for your reply.

**Comment by ymodak** [comment]
Yes you can use TF 2.1 with cuda 10.0 as well. I will add TF 1.15 cuda info on the website.
You have to build TF from source for supporting cuda version other than the ones we already support.
This procedure is time consuming and often stressful for users. So we recommend installing tf using pip packages (pre built tf binaries). The only caveat here is that users have fix their environment as per our dependencies.
Having said that we do actively engage with the community and help as much as possible.
Thanks for using TF.

**Comment by jz1998** [comment]
I have rolled back to cuda 10.0, TF-GPU 1.15 can work with gpu well, but TF 2.1 can't, like the bug like i put forwoard first in TF 1.5 once. i think i can solve this by downgrading to TF 2.0, is it right? but you said can use TF 2.1 with cuda 2.1, there must be something i did wrong in this process. 

Building TF from source means i should do as [https://www.tensorflow.org/install/source_windows?](url) introduction or ...

Thanks for your active engagement sincerely.

**Comment by ymodak** [comment]
ahh.. You are right for TF 2.1 you need cuda 10.1 (my apologies). Yes TF 2.0 supports cuda 10.0.
Sorry for the confusion.
See [tested build configurations](https://www.tensorflow.org/install/source#gpu) Thanks!

**Comment by jz1998** [comment]
Fine,i felt i've solved my problem, thank you.
