### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED 

### ISSUE THREAD

**Issue by MoranReznik** [tensorflow/tensorflow#38565]
**System information**
- windows 10 64
- TensorFlow installed from anaconda
- TensorFlow version: 2.1
- Python version: 3.7.6
- Installed using conda
- CUDA/cuDNN version: 
not sure what cuda version i use: conda list cudatoolkit gives 10.1.243 but nvidia-smi gives cuda 11
cudnn version: 7.6.5
- GPU model and memory:
nvidia gtx 1660Ti 6GB turing
keras version: 2.3.1, keras base 2.3.1, keras-application 1.0.8, keras prepossessing 1.1 

when I an trying to use the layer conv2Dtranspose in a keras model I get the error:
```
2020-04-15 11:26:57.432157: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-04-15 11:26:57.438997: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-04-15 11:26:57.443860: F tensorflow/core/kernels/conv_grad_input_ops.cc:1163] Check failed: stream->parent()->GetConvolveBackwardDataAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(stream->parent()), &algorithms)
```
my guess is that there is a compatablity issue with my cuda or cudnn version, that I dont know how to change in anaconda. changing the version of anything else does not seem to work. 

Provide the exact sequence of commands / steps that you executed before running into the problem:

```
import os
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Model
from keras.optimizers import Adam
from keras.layers.advanced_activations import LeakyReLU
from keras.layers import Conv2D, Input,BatchNormalization, Flatten, Dense, Activation, Conv2DTranspose
from keras import backend as K
from sklearn.model_selection import train_test_split
from keras.callbacks.callbacks import EarlyStopping,Callback
from keras.backend.tensorflow_backend import set_session
import tensorflow as tf
gpus= tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

def adam_optimizer():
    return Adam(lr=0.000002, beta_1=0.5)

def build_generator(inputs, image_size):
    # network parameters
    layer_filters = [256, 128, 64, 32, 3]
    strides = 2
    x = inputs
    for filters in layer_filters:
        x = Conv2DTranspose(filters=filters,kernel_size=(3,3),strides=strides,padding='same')(x)
        shape = K.int_shape(x)
        x = Activation('relu')(x)
        x = BatchNormalization()(x)
    x = Activation('sigmoid')(x)
    generator = Model(inputs, x, name='generator')
    generator.compile(loss='binary_crossentropy',optimizer=adam_optimizer(),metrics=['accuracy'])
    return generator

inputs = Input(shape=(2,2,480))
g = build_generator(inputs, (64,64,3))

false_faces = g.predict(np.random.normal(size=(2,2,2,480)))
```
Any other info / logs:
logs from the notebook:
```
(base) C:\Users\Moran>jupyter notebook
[I 11:26:40.436 NotebookApp] Serving notebooks from local directory: C:\Users\Moran
[I 11:26:40.436 NotebookApp] The Jupyter Notebook is running at:
[I 11:26:40.436 NotebookApp] http://localhost:8888/?token=eeabd801c4c1b83aa79d704bf93c4465f305c688ebb846dc
[I 11:26:40.436 NotebookApp]  or http://127.0.0.1:8888/?token=eeabd801c4c1b83aa79d704bf93c4465f305c688ebb846dc
[I 11:26:40.436 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:26:40.508 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/Moran/AppData/Roaming/jupyter/runtime/nbserver-14384-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=eeabd801c4c1b83aa79d704bf93c4465f305c688ebb846dc
     or http://127.0.0.1:8888/?token=eeabd801c4c1b83aa79d704bf93c4465f305c688ebb846dc
[I 11:26:45.246 NotebookApp] Kernel started: 14241611-5379-485d-b99b-c51ef765ca55
2020-04-15 11:26:47.464197: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-04-15 11:26:50.655541: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-15 11:26:50.703563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
2020-04-15 11:26:50.715262: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-04-15 11:26:50.726496: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-04-15 11:26:50.737190: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-04-15 11:26:50.747595: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-04-15 11:26:50.759230: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-04-15 11:26:50.768199: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-04-15 11:26:50.786405: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-15 11:26:50.794014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-04-15 11:26:50.798597: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-04-15 11:26:50.811901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
2020-04-15 11:26:50.823790: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-04-15 11:26:50.830518: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-04-15 11:26:50.837440: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-04-15 11:26:50.844229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-04-15 11:26:50.851215: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-04-15 11:26:50.857471: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-04-15 11:26:50.864682: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-15 11:26:50.870630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-04-15 11:26:51.694569: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-15 11:26:51.700712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2020-04-15 11:26:51.705257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2020-04-15 11:26:51.710677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/device:GPU:0 with 4625 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-04-15 11:26:52.683708: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
2020-04-15 11:26:52.696926: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-04-15 11:26:52.703966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-04-15 11:26:52.710870: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-04-15 11:26:52.717898: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-04-15 11:26:52.726352: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-04-15 11:26:52.732807: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-04-15 11:26:52.738251: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-15 11:26:52.746009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-04-15 11:26:52.750168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-15 11:26:52.756798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2020-04-15 11:26:52.760471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2020-04-15 11:26:52.764642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4625 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-04-15 11:26:55.502574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-15 11:26:57.432157: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-04-15 11:26:57.438997: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-04-15 11:26:57.443860: F tensorflow/core/kernels/conv_grad_input_ops.cc:1163] Check failed: stream->parent()->GetConvolveBackwardDataAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(stream->parent()), &algorithms)
```
i am trying to solve this for days (!!) now - I looked at all similar problems but for no use  - the solutions there does not work or not apply to my case (for example, since I am using anaconda)

**Comment by gadagashwini** [comment]
@MoranReznik, Please provide the details about cuDNN version and also add the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environmental variable.Please refer this [doc](https://www.tensorflow.org/install/gpu#windows_setup). Thanks

**Comment by Saduf2019** [comment]
@MoranReznik,
please update as per above comment

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Hamza5** [comment]
I have the exact same problem!

**Comment by zhc7** [comment]
me too, this issue shouldn't be closed

**Comment by alexeyda** [comment]
same here, nvidia 1050ti on Dell Notebook

**Comment by BayanStudio** [comment]
I have same problem , GeForce GTX 1660 SUPER,cudnn-10.0-windows10-x64-v7.6.4.38

**Comment by sabziequinor** [comment]
This solved my problem with tf 2.2
```
tf.config.experimental.set_virtual_device_configuration(tf.config.experimental.list_physical_devices('GPU')[0], 
                                                        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])

```
