### ISSUE TITLE
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by Young768** [tensorflow/tensorflow#38929]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA -- 10.0, cuDNN -- 7.4.2
- GPU model and memory:

Quadro RTX 4000 -- 8G
GeForce RTX 2080 ti -- 12G

**Describe the problem**

I have two GPU on two machines, Quadro RTX 4000 and GeForce RTX 2080 ti. And I install the same NVIDIA-driver 440.59. I did the cuDNN sample test and it passed the test. And I ran the tensorflow [benchmark](https://github.com/tensorflow/models/tree/master/official/benchmark) using the below commands.  I used a small enough batch to avoid the OOM issue. The machine with GeForce RTX 2080 ti can successfully run the benchmark. But the machine with Quadro RTX 4000 cannot run the benchmark, which said "Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above." Do you have any idea about this issue? Is it related to hardware? 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
$python tf_cnn_benchmarks.py --data_format=NCHW --batch_size=32 --model=resnet50 --optimizer=momentum --variable_update=replicated --nodistortions --gradient_repacking=8 --num_gpus=2 --num_epochs=90 --weight_decay=1e-4 --use_fp16 --train_dir=/home/lab2

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I0426 23:04:18.110438 139678773683968 session_manager.py:502] Done running local_init_op.
INFO:tensorflow:Starting standard services.
I0426 23:04:24.543723 139678773683968 supervisor.py:737] Starting standard services.
INFO:tensorflow:Starting queue runners.
I0426 23:04:24.543950 139678773683968 supervisor.py:743] Starting queue runners.
Running warm up
2020-04-26 23:04:29.404714: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-04-26 23:04:30.068934: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-04-26 23:04:31.178428: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-04-26 23:04:32.225534: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-04-26 23:04:32.261894: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-04-26 23:04:32.295444: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v0/cg/conv0/conv2d/Conv2D (defined at /tmp/tmpq2hyfuxj.py:12) ]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v0/cg/conv0/conv2d/Conv2D (defined at /tmp/tmpq2hyfuxj.py:12) ]]
	 [[Reshape_603/_2957]]
0 successful operations.
1 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v0/cg/conv0/conv2d/Conv2D:
 Cast (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:101)	
 tower_0/v0/cg/conv0/Pad (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:204)

Input Source operations connected to node tower_0/v0/cg/conv0/conv2d/Conv2D:
 Cast (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:101)	
 tower_0/v0/cg/conv0/Pad (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:204)

Original stack trace for 'tower_0/v0/cg/conv0/conv2d/Conv2D':
  File "tf_cnn_benchmarks.py", line 73, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/root/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 68, in main
    bench.run()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1880, in run
    return self._benchmark_train()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2076, in _benchmark_train
    build_result = self._build_graph()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2110, in _build_graph
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2828, in _build_model
    gpu_compute_stage_ops, gpu_grad_stage_ops)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3345, in add_forward_pass_and_gradients
    outputs = maybe_compile(forward_pass_and_gradients, self.params)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3542, in maybe_compile
    return computation()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3199, in forward_pass_and_gradients
    input_list, phase_train, nclass)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/models/model.py", line 293, in build_network
    self.add_inference(network)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/models/resnet_model.py", line 308, in add_inference
    cnn.conv(64, 7, 7, 2, 2, mode='SAME_RESNET', use_batch_norm=True)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 209, in conv
    kernel_initializer=kernel_initializer)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 134, in _conv2d_impl
    use_bias=False)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/layers/convolutional.py", line 424, in conv2d
    return layer.apply(inputs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 450, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/tmpq2hyfuxj.py", line 12, in tf__call
    outputs = ag__.converted_call('_convolution_op', self, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (inputs, self.kernel), None)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 356, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in _call_unconverted
    return f(*args)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1079, in __call__
    return self.conv_op(inp, filter)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 635, in __call__
    return self.call(inp, filter)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 234, in __call__
    name=self.name)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

I0426 23:04:32.326952 139678773683968 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v0/cg/conv0/conv2d/Conv2D (defined at /tmp/tmpq2hyfuxj.py:12) ]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v0/cg/conv0/conv2d/Conv2D (defined at /tmp/tmpq2hyfuxj.py:12) ]]
	 [[Reshape_603/_2957]]
0 successful operations.
1 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v0/cg/conv0/conv2d/Conv2D:
 Cast (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:101)	
 tower_0/v0/cg/conv0/Pad (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:204)

Input Source operations connected to node tower_0/v0/cg/conv0/conv2d/Conv2D:
 Cast (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:101)	
 tower_0/v0/cg/conv0/Pad (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:204)

Original stack trace for 'tower_0/v0/cg/conv0/conv2d/Conv2D':
  File "tf_cnn_benchmarks.py", line 73, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/root/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 68, in main
    bench.run()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1880, in run
    return self._benchmark_train()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2076, in _benchmark_train
    build_result = self._build_graph()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2110, in _build_graph
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2828, in _build_model
    gpu_compute_stage_ops, gpu_grad_stage_ops)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3345, in add_forward_pass_and_gradients
    outputs = maybe_compile(forward_pass_and_gradients, self.params)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3542, in maybe_compile
    return computation()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3199, in forward_pass_and_gradients
    input_list, phase_train, nclass)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/models/model.py", line 293, in build_network
    self.add_inference(network)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/models/resnet_model.py", line 308, in add_inference
    cnn.conv(64, 7, 7, 2, 2, mode='SAME_RESNET', use_batch_norm=True)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 209, in conv
    kernel_initializer=kernel_initializer)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 134, in _conv2d_impl
    use_bias=False)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/layers/convolutional.py", line 424, in conv2d
    return layer.apply(inputs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 450, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/tmpq2hyfuxj.py", line 12, in tf__call
    outputs = ag__.converted_call('_convolution_op', self, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (inputs, self.kernel), None)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 356, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in _call_unconverted
    return f(*args)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1079, in __call__
    return self.conv_op(inp, filter)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 635, in __call__
    return self.call(inp, filter)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 234, in __call__
    name=self.name)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node tower_0/v0/cg/conv0/conv2d/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node tower_0/v0/cg/conv0/conv2d/Conv2D}}]]
	 [[Reshape_603/_2957]]
0 successful operations.
1 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 73, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/root/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 68, in main
    bench.run()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1880, in run
    return self._benchmark_train()
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2085, in _benchmark_train
    return self._benchmark_graph(result_to_benchmark, eval_build_results)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2294, in _benchmark_graph
    is_chief, summary_writer, profiler)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2430, in benchmark_with_session
    collective_graph_key=collective_graph_key)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 869, in benchmark_one_step
    results = sess.run(fetches, options=run_options, run_metadata=run_metadata)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v0/cg/conv0/conv2d/Conv2D (defined at /tmp/tmpq2hyfuxj.py:12) ]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v0/cg/conv0/conv2d/Conv2D (defined at /tmp/tmpq2hyfuxj.py:12) ]]
	 [[Reshape_603/_2957]]
0 successful operations.
1 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v0/cg/conv0/conv2d/Conv2D:
 Cast (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:101)	
 tower_0/v0/cg/conv0/Pad (defined at /root/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:204)

**Comment by Young768** [comment]
I added the following codes at the beginning of the benchmark file. The issue was gone.


from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)


But I still want to figure out if it is related to hardware?
Is there other solution to solve it stably?

**Comment by ravikyram** [comment]
@Young768 

Glad to know the issue got resolved.Please, go through the l[ink1](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/config/experimental/set_memory_growth), [link2](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) , [link3](https://stackoverflow.com/questions/55788883/limiting-gpu-memory-usage-by-keras-tf-2019) and see if it helps you. Please, close this thread as your issue was resolved. Thanks!
