### ISSUE TITLE
Tensorflow is not detecting GPU, while it is detected in PyTorch

### ISSUE THREAD

**Issue by rootsid** [tensorflow/tensorflow#38990]
**System information**
- Kali GNU/Linux 2020.1
- TensorFlow installed from (source or binary): pip source
- TensorFlow version: 2.1.0
- Python version: 3.7.7
- Installed using virtualenv? pip? conda?: pip in virtualenv
- CUDA/cuDNN version: (deepl) root@root:~/Documents/deepl# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
- GPU model and memory:
deepl) root@root:~/Documents/deepl# nvidia-smi
Tue Apr 28 23:46:25 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:01:00.0  On |                  N/A |
| 41%   37C    P8     7W / 225W |    632MiB /  7981MiB |     35%      Default |
+-------------------------------+----------------------+----------------------+

**Problem Description**
import tensorflow as tf
tf.test.gpu_device_name()

it throws a blank string not detecting a gpu while drivers are installed perfectly as PyTorch detected the gpu

tf.test.gpu_device_name()
''

while in PyTorch
import torch
torch.cuda.is_available()
true

**Any other info / logs**
There is no error in loading modules here are installation logs

`(deepl) root@root:~/Documents/deepl# pip install tensorflow-gpu
Collecting tensorflow-gpu
  Using cached tensorflow_gpu-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl (421.8 MB)
Requirement already satisfied: wrapt>=1.11.1 in ./lib/python3.7/site-packages (from tensorflow-gpu) (1.12.1)
Requirement already satisfied: astor>=0.6.0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (0.8.1)
Requirement already satisfied: absl-py>=0.7.0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (0.9.0)
Requirement already satisfied: scipy==1.4.1; python_version >= "3" in ./lib/python3.7/site-packages (from tensorflow-gpu) (1.4.1)
Requirement already satisfied: gast==0.2.2 in ./lib/python3.7/site-packages (from tensorflow-gpu) (0.2.2)
Requirement already satisfied: protobuf>=3.8.0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (3.11.3)
Requirement already satisfied: google-pasta>=0.1.6 in ./lib/python3.7/site-packages (from tensorflow-gpu) (0.2.0)
Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (2.1.0)
Requirement already satisfied: termcolor>=1.1.0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (1.1.0)
Requirement already satisfied: keras-preprocessing>=1.1.0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (1.1.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in ./lib/python3.7/site-packages (from tensorflow-gpu) (0.34.2)
Requirement already satisfied: opt-einsum>=2.3.2 in ./lib/python3.7/site-packages (from tensorflow-gpu) (3.2.1)
Requirement already satisfied: numpy<2.0,>=1.16.0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (1.18.3)
Requirement already satisfied: keras-applications>=1.0.8 in ./lib/python3.7/site-packages (from tensorflow-gpu) (1.0.8)
Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (2.1.1)
Requirement already satisfied: six>=1.12.0 in ./lib/python3.7/site-packages (from tensorflow-gpu) (1.14.0)
Requirement already satisfied: grpcio>=1.8.6 in ./lib/python3.7/site-packages (from tensorflow-gpu) (1.28.1)
Requirement already satisfied: setuptools in ./lib/python3.7/site-packages (from protobuf>=3.8.0->tensorflow-gpu) (46.1.3)
Requirement already satisfied: h5py in ./lib/python3.7/site-packages (from keras-applications>=1.0.8->tensorflow-gpu) (2.10.0)
Requirement already satisfied: requests<3,>=2.21.0 in ./lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (2.23.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in ./lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (1.14.1)
Requirement already satisfied: werkzeug>=0.11.15 in ./lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in ./lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (3.2.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (0.4.1)
Requirement already satisfied: idna<3,>=2.5 in ./lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in ./lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (2020.4.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (0.2.8)
Requirement already satisfied: rsa<4.1,>=3.1.4 in ./lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (4.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in ./lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (4.1.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in ./lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (3.1.0)
Installing collected packages: tensorflow-gpu
Successfully installed tensorflow-gpu-2.1.0`

>> I have tried installing pip install tensorflow-gpu==2.0.0 as well.

**Comment by oke-aditya** [comment]
try this in tf v2 `tf.config.list_physical devices()`

**Comment by rootsid** [comment]
Here's the result

tf.config.list_physical_devices(
    device_type=None
)

`[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU')]`

and for 

physical_devices = tf.config.list_physical_devices('GPU') 
print("Num GPUs:", len(physical_devices)) 

`Num GPUs: 0`

**Comment by oke-aditya** [comment]
Similar issues were reported earlier #12388 #13793. Have a look at them. It can happen because of CUDA Version mismatch.

**Comment by amahendrakar** [comment]
> Similar issues were reported earlier #12388 #13793. Have a look at them. It can happen because of CUDA Version mismatch.

@rootsid,
Could you please check @oke-aditya's comment and let us know if it works. Thanks!

**Comment by oke-aditya** [comment]
Could you please tell the reason so that I would know what solved it.

**Comment by rootsid** [comment]
Issue is still not resolved, i see on website that tensorflow works with 10.1 cuda version not with 10.2 and its a kali box, i mostly use it for security and need that speed boost of 10.2. So installing ubuntu on a separate hard drive for tensorflow.

**Comment by martinheda** [comment]
I had the same problems with no GPU detected as physical device, only XLA_GPU. 
My problems were fixed by building Tensorflow from source, (see https://www.tensorflow.org/install/source#common_installation_problems ) which took quite a long time, but after this  it works OK!
