### ISSUE TITLE
CuDNN LSTM failed with large batch size

### ISSUE THREAD

**Issue by gargargar** [tensorflow/tensorflow#39453]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2, 2.1
- Python version: 3.7.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.2, 10.1
- GPU model and memory: 1 x 2080Ti 11GB, 2 x 2080 8GB

**Describe the current behavior**
Sample code below fail with error:

> 2020-05-12 12:59:37.956635: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-05-12 12:59:38.245540: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-05-12 12:59:39.426585: E tensorflow/stream_executor/dnn.cc:613] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1847): 'cudnnRNNForwardTrainingEx( cudnn.handle(), rnn_desc.handle(), input_desc.data_handle(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.data_handle(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
2020-05-12 12:59:39.446537: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at cudnn_rnn_ops.cc:1517 : Internal: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 32, 32, 1, 5, 12928, 32]
2020-05-12 12:59:39.457993: I tensorflow/stream_executor/stream.cc:1990] [stream=0000022BBB859000,impl=0000022BBF43D210] did not wait for [stream=0000022BBB859180,impl=0000022BBF43D930]
2020-05-12 12:59:39.462903: I tensorflow/stream_executor/stream.cc:4938] [stream=0000022BBB859000,impl=0000022BBF43D210] did not memcpy host-to-device; source: 0000022BB566AF00
2020-05-12 12:59:39.467874: F tensorflow/core/common_runtime/gpu/gpu_util.cc:340] CPU->GPU Memcpy failed

If I disable GPU device or set mask_zero to False, or force to use not cudnn LTSM (via tf.keras.layers.RNN(tf.keras.layers.LSTMCell(32))(x)) it works.

I think it's somehow related with thing what I on each batch process on model not 128 (batch size) items, but 128x101 items.

**Describe the expected behavior**

It must compile without this error.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf

from tensorflow.keras.layers import Input, Activation, Embedding, LSTM, Dense, Dropout, Flatten, Concatenate, Dot
from tensorflow.keras.models import Model
from tensorflow.keras.utils import Sequence

#tf.config.set_visible_devices([], 'GPU')

strategy = tf.distribute.MirroredStrategy()

words = tf.constant(((1,1,1,1,1),(1,1,1,1,1)))
products = tf.ones((10000,101), dtype=tf.int32)

test_dataset = tf.data.Dataset.from_tensor_slices(products)
test_dataset = test_dataset.batch(128, drop_remainder=True)
test_dataset = strategy.experimental_distribute_dataset(test_dataset)

def create_model(words_count):
    input_words = Input(shape=tf.TensorShape(5), dtype='int32', name='input_words')

    x = Embedding(output_dim=32, input_dim=words_count, input_length=5, mask_zero=True)(input_words)
    #x = Embedding(output_dim=32, input_dim=words_count, input_length=5, mask_zero=False)(input_words)

    x = LSTM(32)(x)
    #x = tf.keras.layers.RNN(tf.keras.layers.LSTMCell(32))(x)

    model = Model(inputs=input_words, outputs=x)
    return model

with strategy.scope():
    model = create_model(11111)
    optimizer = tf.keras.optimizers.SGD()

print(model.summary())

@tf.function
def test_step(b_cmp):
    cmp_words = tf.gather(words, b_cmp)
    tmp = tf.reshape(cmp_words, (-1,5))
    tmp = model(tmp, training=False)
   
    # ...

    r = tf.reduce_sum(tmp)
    return r

for b_cmp in test_dataset:
    strategy.run(test_step, args=(b_cmp,))
```

**Comment by Saduf2019** [comment]
@gargargar 
I ran the code shared by disabling gpu and do not face any error on nightly, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/0e45010f60a01641b29094f83f8132c7/untitled178.ipynb), on tf 2.1 i face this error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/4dfffe6373c6071880f4fda639a322e2/untitled181.ipynb)

**Comment by gargargar** [comment]
> 
> 
> @gargargar
> I ran the code shared by disabling gpu and do not face any error on nightly, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/0e45010f60a01641b29094f83f8132c7/untitled178.ipynb), on tf 2.1 i face this error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/4dfffe6373c6071880f4fda639a322e2/untitled181.ipynb)

Sorry, but why do you tried to repeat it by disabling GPUs?
It's only arise on LSTM via cudnn, you must try it on nVidia Geforce 2060/2070/2080,etc (Turing architecture, maybe Pascal too, I didn't test).
If you try it on CPU, it works perfectly.

**Comment by Saduf2019** [comment]
@gargargar 
I ran the code with gpu enabled and do not face any error, please find the [gist for 2.1](https://colab.sandbox.google.com/gist/Saduf2019/e90a168b4b9eb9b60c41835e4e80d61d/with_gpu.ipynb) and for [nightly](https://colab.sandbox.google.com/gist/Saduf2019/394c249e1a93d3666f40edfafbb5c30e/untitled178.ipynb)

**Comment by gargargar** [comment]
It's very strange, I didn't see in your logs which video cards used? And more important any logs about cudnn usage?
It's very important to check with cudnn, as I understand tensorflow use cudnn optimization for LSTM if cudnn available (https://www.tensorflow.org/guide/keras/rnn).

Just checked on different machine with different OS: Ubuntu 18.04.4 LTS x64, 2x2080 8GB, tensorflow 2.2, cuda/cudnn 10.1. Absolutly same problem, see full logs:

```
almaz@tenflow:~/tf$ python3 error.py
2020-05-13 14:58:26.963321: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-13 14:58:27.000384: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.000931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.815GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.23GiB/s
2020-05-13 14:58:27.000985: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.001488: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties:
pciBusID: 0000:02:00.0 name: GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.71GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.23GiB/s
2020-05-13 14:58:27.001696: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-13 14:58:27.003030: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-13 14:58:27.004138: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-05-13 14:58:27.004357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-05-13 14:58:27.005751: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-05-13 14:58:27.006561: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-05-13 14:58:27.009493: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-13 14:58:27.009605: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.010185: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.010709: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.011233: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.011729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2020-05-13 14:58:27.038194: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3401880000 Hz
2020-05-13 14:58:27.038996: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f3418000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-13 14:58:27.039024: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-13 14:58:27.211211: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.228934: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.229553: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x45d2960 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-05-13 14:58:27.229574: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2020-05-13 14:58:27.229581: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080, Compute Capability 7.5
2020-05-13 14:58:27.229898: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.230418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.815GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.23GiB/s
2020-05-13 14:58:27.230486: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.230993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties:
pciBusID: 0000:02:00.0 name: GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.71GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.23GiB/s
2020-05-13 14:58:27.231030: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-13 14:58:27.231060: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-13 14:58:27.231075: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-05-13 14:58:27.231089: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-05-13 14:58:27.231104: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-05-13 14:58:27.231124: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-05-13 14:58:27.231139: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-13 14:58:27.231189: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.231714: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.232251: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.232777: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.233279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2020-05-13 14:58:27.233311: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-13 14:58:27.234867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-13 14:58:27.234891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 1
2020-05-13 14:58:27.234903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N N
2020-05-13 14:58:27.234912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 1:   N N
2020-05-13 14:58:27.235090: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.235945: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.236771: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.237555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7387 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-05-13 14:58:27.238061: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 14:58:27.238747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 7389 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080, pci bus id: 0000:02:00.0, compute capability: 7.5)
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_words (InputLayer)     [(None, 5)]               0
_________________________________________________________________
embedding (Embedding)        (None, 5, 32)             355552
_________________________________________________________________
lstm (LSTM)                  (None, 32)                8320
=================================================================
Total params: 363,872
Trainable params: 363,872
Non-trainable params: 0
_________________________________________________________________
None
2020-05-13 14:58:31.489239: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-13 14:58:31.734217: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-13 14:58:32.765123: E tensorflow/stream_executor/dnn.cc:613] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1847): 'cudnnRNNForwardTrainingEx( cudnn.handle(), rnn_desc.handle(), input_desc.data_handle(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.data_handle(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
2020-05-13 14:58:32.765186: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at cudnn_rnn_ops.cc:1517 : Internal: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 32, 32, 1, 5, 6464, 32]
2020-05-13 14:58:33.588367: E tensorflow/stream_executor/dnn.cc:613] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1847): 'cudnnRNNForwardTrainingEx( cudnn.handle(), rnn_desc.handle(), input_desc.data_handle(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.data_handle(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
2020-05-13 14:58:33.588441: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at cudnn_rnn_ops.cc:1517 : Internal: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 32, 32, 1, 5, 6464, 32]
2020-05-13 14:58:33.589990: I tensorflow/stream_executor/stream.cc:1990] [stream=0x45f9e30,impl=0x45f8f50] did not wait for [stream=0x45f9bb0,impl=0x45f8e70]
2020-05-13 14:58:33.590012: I tensorflow/stream_executor/stream.cc:4938] [stream=0x45f9e30,impl=0x45f8f50] did not memcpy host-to-device; source: 0x7f32c5e8e480
2020-05-13 14:58:33.590068: F tensorflow/core/common_runtime/gpu/gpu_util.cc:340] CPU->GPU Memcpy failed
Aborted (core dumped)
```

code slightly changed to not allocate full videocard memory on Linux, added on top of my code, after import:
```python
gpu_devices = tf.config.experimental.list_physical_devices('GPU')
for device in gpu_devices:
    tf.config.experimental.set_memory_growth(device, True)
```

I don't think this is just my error, 2 machines with different OS'es give same errors with cudnn.
Just checked, removed cudnn dll in Windows machine, and yes it works. Problem with cudnn + tensorflow + LSTM masking

**Comment by ned2** [comment]
I'm also seeing this same error that I can confirm is triggered by the combination of cuDNN + LSTM + masking.

Bisection reveals that this regression was introduced in `2.2.0rc2`

**Comment by qlzh727** [comment]
Seems to be a cudnn kernel issue, which might be related to https://github.com/tensorflow/tensorflow/issues/33148.

Adding @kaixih from Nvidia side for more insights.

**Comment by kaixih** [comment]
I feel this is a MirroredStrategy issue. I tested this script on my machine with 4 GPUs and it works fine (I didn't see any error). However, if I use `CUDA_VISIBLE_DEVICES=0 python lstm.py`, I can see the same error shown in https://github.com/tensorflow/tensorflow/issues/39453#issuecomment-627945705.

Then I tried the script with tf.distribute.MirroredStrategy(['/gpu:0']) or 2 GPUs but with no luck, meaning it seems I have to use all the available 4 GPUs to make things work.

I also tried the script in TF 2.1 but it gave other errors.

@qlzh727 What's your opinion? I think experts on MirroredStrategy might provide more insights.

**Comment by qlzh727** [comment]
Thanks @kaixih for the debug, let me add @guptapriya from distribution strategy team.

btw, when the error occurs with CUDNN_STATUS_EXECUTION_FAILED, what's the error detail from the cudnn kernel?

**Comment by guptapriya** [comment]
So it works with MirroredStrategy with 4 GPUs, but not with 1 or 2 GPUs?

**Comment by kaixih** [comment]
@qlzh727 I think CUDNN_STATUS_EXECUTION_FAILED is a generic error code to indicate the function failed to launch in the GPU.

**Comment by kaixih** [comment]
I removed the strategy and get the cudnn error when mask is enabled. Will get back to this later.

**Comment by kaixih** [comment]
I think I figured out the issue. It hit an unsupported case for CUDNN RNN LSTM, with the batch size 12928 in this case. That also explains why using 4 GPUs is fine (12928/4=3232 supported) but using 2 GPUs is not good (12928/2=6464, not supported). 

To confirm it is the case (for debugging purpose), you might want to add `tmp=tmp[0:4096,0]` after `tmp = tf.reshape(cmp_words, (-1,5))` and it should run.

I am contacting our cudnn team to confirm this finding.

**Comment by qlzh727** [comment]
Thanks @kaixih  for the findings. Please let us know if and when this will be fixed on the nvidia side.

**Comment by Saduf2019** [comment]
@gargargar 
I ran the code on tf-nightly and see a different warning message, please refer to this [gist here](https://colab.research.google.com/gist/Saduf2019/7ad4cc84e1dd683198edbd85f355701b/untitled602.ipynb)
