### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rongtianyue** [tensorflow/tensorflow#39463]
<em>Hello, I am getting a libcublas import error. </em>

**System information**
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID_LIKE=debian
VERSION_CODENAME=bionic
- TensorFlow installed from anaconda.
- TensorFlow version: v2
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda 
- CUDA/cuDNN version: 9.0
- GPU model and memory: 12 cores, 64GB RAM, 4x Titan Xp GPUs

**Problem**
ImportError

**Replication **
I have used my environment before perfectly fine, but stopped working today without me knowingly modifying anything that would cause this. I found similar errors like [this one](https://github.com/tensorflow/tensorflow/issues/15604). It seems that most of them are CUDA mismatch. Mine is not, running `which nvcc` gives /usr/local/cuda-9.0/bin/nvcc. Any clues?

**logs**
It seems libcublas isn't installed which is strange as I never recalled uninstalling it. 
Running `ldconfig -v` gives me the following: 

/sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/usr/lib/x86_64-linux-gnu/libfakeroot:
        libfakeroot-0.so -> libfakeroot-tcp.so
/usr/local/lib:
/lib/x86_64-linux-gnu:
        liblvm2cmd.so.2.02 -> liblvm2cmd.so.2.02
        libpthread.so.0 -> libpthread-2.27.so
        libmemusage.so -> libmemusage.so
        libcidn.so.1 -> libcidn-2.27.so
        libpcre.so.3 -> libpcre.so.3.13.3
        libncurses.so.5 -> libncurses.so.5.9
        libnss_files.so.2 -> libnss_files-2.27.so
        libply-splash-core.so.4 -> libply-splash-core.so.4.0.0
        liblvm2app.so.2.2 -> liblvm2app.so.2.2
        libulockmgr.so.1 -> libulockmgr.so.1.0.1
        libmvec.so.1 -> libmvec-2.27.so
        libidn.so.11 -> libidn.so.11.6.16
        libpci.so.3 -> libpci.so.3.5.2
        libnss_hesiod.so.2 -> libnss_hesiod-2.27.so
        libexpat.so.1 -> libexpat.so.1.6.7
        libfdisk.so.1 -> libfdisk.so.1.1.0
        libm.so.6 -> libm-2.27.so
        libnss_systemd.so.2 -> libnss_systemd.so.2
        libiw.so.30 -> libiw.so.30
        libmount.so.1 -> libmount.so.1.1.0
        libply-splash-graphics.so.4 -> libply-splash-graphics.so.4.0.0
        libnss_mdns6.so.2 -> libnss_mdns6.so.2
        libreadline.so.7 -> libreadline.so.7.0
        libnl-3.so.200 -> libnl-3.so.200.24.0
        libdevmapper-event.so.1.02.1 -> libdevmapper-event.so.1.02.1
        libthread_db.so.1 -> libthread_db-1.0.so
        libaudit.so.1 -> libaudit.so.1.0.0
        libsepol.so.1 -> libsepol.so.1
        libc.so.6 -> libc-2.27.so
        libext2fs.so.2 -> libext2fs.so.2.4
        libpamc.so.0 -> libpamc.so.0.82.1
        libwrap.so.0 -> libwrap.so.0.7.6
        libcryptsetup.so.12 -> libcryptsetup.so.12.2.0
        libpam_misc.so.0 -> libpam_misc.so.0.82.0
        libusb-1.0.so.0 -> libusb-1.0.so.0.1.0
        libbz2.so.1.0 -> libbz2.so.1.0.4
        libhistory.so.7 -> libhistory.so.7.0
        libnss_nisplus.so.2 -> libnss_nisplus-2.27.so
        libslang.so.2 -> libslang.so.2.3.1
        libattr.so.1 -> libattr.so.1.1.0
        liblzo2.so.2 -> liblzo2.so.2.0.0
        libSegFault.so -> libSegFault.so
        libgpg-error.so.0 -> libgpg-error.so.0.22.0
        libply-boot-client.so.4 -> libply-boot-client.so.4.0.0
        libkmod.so.2 -> libkmod.so.2.3.2
        libdevmapper-event-lvm2.so.2.02 -> libdevmapper-event-lvm2.so.2.02
        libcap.so.2 -> libcap.so.2.25
        libjson-c.so.3 -> libjson-c.so.3.0.1
        libe2p.so.2 -> libe2p.so.2.3
        libcrypt.so.1 -> libcrypt-2.27.so
        libnewt.so.0.52 -> libnewt.so.0.52.20
        libnss_nis.so.2 -> libnss_nis-2.27.so
        libply.so.4 -> libply.so.4.0.0
        libapparmor.so.1 -> libapparmor.so.1.4.2
        libatm.so.1 -> libatm.so.1.0.0
        libseccomp.so.2 -> libseccomp.so.2.4.1
        libparted.so.2 -> libparted.so.2.0.1
        libnih.so.1 -> libnih.so.1.0.0
        libparted-fs-resize.so.0 -> libparted-fs-resize.so.0.0.1
        libdns-export.so.1100 -> libdns-export.so.1100.1.1
        libpcprofile.so -> libpcprofile.so
        libtirpc.so.1 -> libtirpc.so.1.0.10
        libfuse.so.2 -> libfuse.so.2.9.7
        libnfsidmap.so.0 -> libnfsidmap.so.0.3.0
        libnss_mdns_minimal.so.2 -> libnss_mdns_minimal.so.2
        libutil.so.1 -> libutil-2.27.so
        libsmartcols.so.1 -> libsmartcols.so.1.1.0
        libblkid.so.1 -> libblkid.so.1.1.0
        libdl.so.2 -> libdl-2.27.so
        libnss_mdns4_minimal.so.2 -> libnss_mdns4_minimal.so.2
        libisns-nocrypto.so.0 -> libisns-nocrypto.so.0
        libdevmapper.so.1.02.1 -> libdevmapper.so.1.02.1
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.27.so is the dynamic linker, ignoring

        ld-linux-x86-64.so.2 -> ld-2.27.so
        libmnl.so.0 -> libmnl.so.0.2.0
        libnss_myhostname.so.2 -> libnss_myhostname.so.2
        libbsd.so.0 -> libbsd.so.0.8.7
        libprocps.so.6 -> libprocps.so.6.0.0
        libnss_mdns6_minimal.so.2 -> libnss_mdns6_minimal.so.2
        libnss_mdns.so.2 -> libnss_mdns.so.2
        libreadline.so.5 -> libreadline.so.5.2
        libnsl.so.1 -> libnsl-2.27.so
        libbrlapi.so.0.6 -> libbrlapi.so.0.6.6
        libcom_err.so.2 -> libcom_err.so.2.1
        liblzma.so.5 -> liblzma.so.5.2.2
        libss.so.2 -> libss.so.2.0
        libBrokenLocale.so.1 -> libBrokenLocale-2.27.so
        libz.so.1 -> libz.so.1.2.11
        libtinfo.so.5 -> libtinfo.so.5.9
        libgcc_s.so.1 -> libgcc_s.so.1
        librt.so.1 -> librt-2.27.so
        libgcrypt.so.20 -> libgcrypt.so.20.2.1
        libselinux.so.1 -> libselinux.so.1
        libnss_compat.so.2 -> libnss_compat-2.27.so
        libisc-export.so.169 -> libisc-export.so.169.0.1
        libuuid.so.1 -> libuuid.so.1.3.0
        libhistory.so.5 -> libhistory.so.5.2
        libudev.so.1 -> libudev.so.1.6.9
        libncursesw.so.5 -> libncursesw.so.5.9
        libacl.so.1 -> libacl.so.1.1.0
        libanl.so.1 -> libanl-2.27.so
        libresolv.so.2 -> libresolv-2.27.so
        libdbus-1.so.3 -> libdbus-1.so.3.19.4
        libnl-genl-3.so.200 -> libnl-genl-3.so.200.24.0
        libatasmart.so.4 -> libatasmart.so.4.0.5
        libnss_dns.so.2 -> libnss_dns-2.27.so
        libntfs-3g.so.88 -> libntfs-3g.so.88.0.0
        libpam.so.0 -> libpam.so.0.83.1
        libcap-ng.so.0 -> libcap-ng.so.0.0.0
        libkeyutils.so.1 -> libkeyutils.so.1.5
        libsystemd.so.0 -> libsystemd.so.0.21.0
        libnss_mdns4.so.2 -> libnss_mdns4.so.2
/usr/lib/x86_64-linux-gnu:
        librtmp.so.1 -> librtmp.so.1
        libnvidia-gtk2.so.430.26 -> libnvidia-gtk2.so.430.26
        libEGL_mesa.so.0 -> libEGL_mesa.so.0.0.0
        libwoff2dec.so.1.0.2 -> libwoff2dec.so.1.0.2
        libsndio.so.6.1 -> libsndio.so.6.1
        libcupsppdc.so.1 -> libcupsppdc.so.1
        libboost_program_options.so.1.65.1 -> libboost_program_options.so.1.65.1
        libpolkit-backend-1.so.0 -> libpolkit-backend-1.so.0.0.0
        libfwup.so.1 -> libfwup.so.1.10
        libgtksourceview-3.0.so.1 -> libgtksourceview-3.0.so.1.8.0
        libgee-0.8.so.2 -> libgee-0.8.so.2.6.1
        libhttp_parser.so.2.7.1 -> libhttp_parser.so.2.7.1
        libisccc.so.160 -> libisccc.so.160.0.2
        librasqal.so.3 -> librasqal.so.3.0.0
        libplds4.so -> libplds4.so
        libnvidia-glsi.so.430.26 -> libnvidia-glsi.so.430.26
        libbd_swap.so.2 -> libbd_swap.so.2.0.0
        libp11-kit.so.0 -> libp11-kit.so.0.3.0
        libclutter-gtk-1.0.so.0 -> libclutter-gtk-1.0.so.0.800.4
        libgstphotography-1.0.so.0 -> libgstphotography-1.0.so.0.1401.0
        libnvidia-gtk3.so.430.26 -> libnvidia-gtk3.so.430.26
        libxcb-dri2.so.0 -> libxcb-dri2.so.0.0.0
        libfreerdp-client2.so.2 -> libfreerdp-client2.so.2.0.0
        liblirc_client.so.0 -> liblirc_client.so.0.6.0
        libnm.so.0 -> libnm.so.0.1.0
        libnvidia-fbc.so.1 -> libnvidia-fbc.so.430.26
        libevent-2.1.so.6 -> libevent-2.1.so.6.0.2
        libcc1.so.0 -> libcc1.so.0.0.0
        libnvidia-rtcore.so.430.26 -> libnvidia-rtcore.so.430.26
        libdazzle-1.0.so.0 -> libdazzle-1.0.so.0
        libfftw3l_omp.so.3 -> libfftw3l_omp.so.3.5.7
        libflite_cmu_grapheme_lang.so.1 -> libflite_cmu_grapheme_lang.so.2.1
        libbabeltrace-ctf.so.1 -> libbabeltrace-ctf.so.1.0.0
        libclutter-gst-3.0.so.0 -> libclutter-gst-3.0.so.0.26.0
        libisl.so.19 -> libisl.so.19.0.0
        libzvbi-chains.so.0 -> libzvbi-chains.so.0.0.0
        libsamba-passdb.so.0 -> libsamba-passdb.so.0.27.0
        libgdata.so.22 -> libgdata.so.22.3.0
        libopen-pal.so.20 -> libopen-pal.so.20.10.1
        liboauth.so.0 -> liboauth.so.0.8.7
        libgsm.so.1 -> libgsm.so.1.0.12
        libqqwing.so.2 -> libqqwing.so.2.1.0
        libnspr4.so -> libnspr4.so
        libprotoc.so.10 -> libprotoc.so.10.0.0
        libGL.so.1 -> libGL.so.1.0.0
        libgxps.so.2 -> libgxps.so.2.2.2
        libavfilter.so.6 -> libavfilter.so.6.107.100
        libOpenCL.so.1 -> libOpenCL.so.1.0.0
        libsmbconf.so.0 -> libsmbconf.so.0
        libdcerpc-binding.so.0 -> libdcerpc-binding.so.0.0.1
        libnvidia-tls.so.430.26 -> libnvidia-tls.so.430.26
        libXfixes.so.3 -> libXfixes.so.3.1.0
        libbtrfs.so.0 -> libbtrfs.so.0.1
        libclucene-contribs-lib.so.1 -> libclucene-contribs-lib.so.2.3.3.4
        libfftw3.so.3 -> libfftw3.so.3.5.7
        libvisio-0.1.so.1 -> libvisio-0.1.so.1.0.6
        libtcmalloc_minimal_debug.so.4 -> libtcmalloc_minimal_debug.so.4.3.0
        libxcb-shm.so.0 -> libxcb-shm.so.0.0.0
        libtevent-util.so.0 -> libtevent-util.so.0.0.1
        libssl3.so -> libssl3.so
        libstartup-notification-1.so.0 -> libstartup-notification-1.so.0.0.0
        libapr-1.so.0 -> libapr-1.so.0.6.3
        libbrotlienc.so.1 -> libbrotlienc.so.1.0.4
        libaudio.so.2 -> libaudio.so.2.4
        libmpfr.so.6 -> libmpfr.so.6.0.1
        libmessaging-menu.so.0 -> libmessaging-menu.so.0.0.0
        libxcb-dri3.so.0 -> libxcb-dri3.so.0.0.0
        libboost_locale.so.1.65.1 -> libboost_locale.so.1.65.1
        libIexMath-2_2.so.12 -> libIexMath-2_2.so.12.0.0
        libXt.so.6 -> libXt.so.6.0.0
        libabw-0.1.so.1 -> libabw-0.1.so.1.0.2
        libidn2.so.0 -> libidn2.so.0.3.3
        libswscale.so.4 -> libswscale.so.4.8.100
        libGLESv1_CM_nvidia.so.1 -> libGLESv1_CM_nvidia.so.430.26
        libapt-pkg.so.5.0 -> libapt-pkg.so.5.0.2
        libutempter.so.0 -> libutempter.so.1.1.6
        libflite_cmu_us_slt.so.1 -> libflite_cmu_us_slt.so.2.1
        libmediaart-2.0.so.0 -> libmediaart-2.0.so.0.904.0
        libwx_gtk2u_xrc-3.0.so.0 -> libwx_gtk2u_xrc-3.0.so.0.4.0
        libnvidia-fatbinaryloader.so.430.26 -> libnvidia-fatbinaryloader.so.430.26
        libbrotlicommon.so.1 -> libbrotlicommon.so.1.0.4
        libtcmalloc_and_profiler.so.4 -> libtcmalloc_and_profiler.so.4.3.0
        libargon2.so.0 -> libargon2.so.0
        libgstsdp-1.0.so.0 -> libgstsdp-1.0.so.0.1401.0
        libtwolame.so.0 -> libtwolame.so.0.0.0
        libnvidia-eglcore.so.430.26 -> libnvidia-eglcore.so.430.26
        libcupsimage.so.2 -> libcupsimage.so.2
        libhunspell-1.6.so.0 -> libhunspell-1.6.so.0.0.1
        libpgm-5.2.so.0 -> libpgm-5.2.so.0.0.122
        libbabeltrace-dummy.so.1 -> libbabeltrace-dummy.so.1.0.0
        libecal-1.2.so.19 -> libecal-1.2.so.19.0.0
        libssh-gcrypt.so.4 -> libssh-gcrypt.so.4.5.0
        liblcms2.so.2 -> liblcms2.so.2.0.8
        libedataserverui-1.2.so.2 -> libedataserverui-1.2.so.2.0.0
        libXdamage.so.1 -> libXdamage.so.1.1.0
        libnvidia-glvkspirv.so.430.26 -> libnvidia-glvkspirv.so.430.26
        libflite_cmu_us_awb.so.1 -> libflite_cmu_us_awb.so.2.1
        libsvn_diff-1.so.1 -> libsvn_diff-1.so.1.0.0
        libgdk-x11-2.0.so.0 -> libgdk-x11-2.0.so.0.2400.32
        libcurl.so.4 -> libcurl.so.4.5.0
        libmythes-1.2.so.0 -> libmythes-1.2.so.0.0.0
        libexpatw.so.1 -> libexpatw.so.1.6.7
        libnorm.so.1 -> libnorm.so.1.0.0
        libGLESv2.so.2 -> libGLESv2.so.2.0.0
        libavahi-client.so.3 -> libavahi-client.so.3.2.9
        libxkbcommon-x11.so.0 -> libxkbcommon-x11.so.0.0.0
        libexempi.so.3 -> libexempi.so.3.4.5
        libgdk_pixbuf-2.0.so.0 -> libgdk_pixbuf-2.0.so.0.3611.0
        libwoff2enc.so.1.0.2 -> libwoff2enc.so.1.0.2
        libgphoto2.so.6 -> libgphoto2.so.6.0.0
        libgdk-3.so.0 -> libgdk-3.so.0.2200.30
        libva-x11.so.2 -> libva-x11.so.2.100.0
        libavahi-common.so.3 -> libavahi-common.so.3.5.3
        libgspell-1.so.1 -> libgspell-1.so.1.3.0
        librest-0.7.so.0 -> librest-0.7.so.0.0.0
        libsonic.so.0 -> libsonic.so.0.2.0
        libmpi_mpifh.so.20 -> libmpi_mpifh.so.20.11.0
        libndr.so.0 -> libndr.so.0.1.0
        libflite_cmu_indic_lang.so.1 -> libflite_cmu_indic_lang.so.2.1
        libmpi_usempi_ignore_tkr.so.20 -> libmpi_usempi_ignore_tkr.so.20.10.0
        libXtst.so.6 -> libXtst.so.6.1.0
        libhpip.so.0 -> libhpip.so.0.0.1
        libsvn_auth_kwallet-1.so.1 -> libsvn_auth_kwallet-1.so.1.0.0
        libchromaprint.so.1 -> libchromaprint.so.1.4.3
        libcupsmime.so.1 -> libcupsmime.so.1
        libespeak-ng.so.1 -> libespeak-ng.so.1.1.49
        libsnapd-glib.so.1 -> libsnapd-glib.so.1.0.0
        libxcb-keysyms.so.1 -> libxcb-keysyms.so.1.0.0
        libsvn_client-1.so.1 -> libsvn_client-1.so.1.0.0
        libxcb-present.so.0 -> libxcb-present.so.0.0.0
        libQt5Widgets.so.5 -> libQt5Widgets.so.5.9.5
        libijs-0.35.so -> libijs-0.35.so
        libsmbios_c.so.2 -> libsmbios_c.so.2.2.1
        libk5crypto.so.3 -> libk5crypto.so.3.1
        libasyncns.so.0 -> libasyncns.so.0.3.1
        libyajl.so.2 -> libyajl.so.2.1.0
        libinproctrace.so -> libinproctrace.so
        libplc4.so -> libplc4.so
        libraw.so.16 -> libraw.so.16.0.0
        libGLX_nvidia.so.0 -> libGLX_nvidia.so.430.26
        libbs2b.so.0 -> libbs2b.so.0.0.0
        liblz4.so.1 -> liblz4.so.1.7.1
        libXvMCW.so.1 -> libXvMCW.so.1.0.0
        libnetapi.so.0 -> libnetapi.so.0
        libsbc.so.1 -> libsbc.so.1.2.1
        libcdda_interface.so.0 -> libcdda_interface.so.0.10.2
        liborcus-parser-0.13.so.0 -> liborcus-parser-0.13.so.0.0.0
        liblouisutdml.so.8 -> liblouisutdml.so.8.0.0
        libfftw3q.so.3 -> libfftw3q.so.3.5.7
        libmtdev.so.1 -> libmtdev.so.1.0.0
        liblqr-1.so.0 -> liblqr-1.so.0.3.2
        libmwaw-0.3.so.3 -> libmwaw-0.3.so.3.0.13
        libgthread-2.0.so.0 -> libgthread-2.0.so.0.5600.4
        libnuma.so.1 -> libnuma.so.1.0.0
        libwayland-client.so.0 -> libwayland-client.so.0.3.0
        libopenmpt.so.0 -> libopenmpt.so.0.1.1
        librdmacm.so.1 -> librdmacm.so.1.1.17.1
        libgstriff-1.0.so.0 -> libgstriff-1.0.so.0.1401.0
        liblsan.so.0 -> liblsan.so.0.0.0
        libpipeline.so.1 -> libpipeline.so.1.5.0
        libopcodes-2.30-system.so -> libopcodes-2.30-system.so
        libudisks2.so.0 -> libudisks2.so.0.0.0
        libgstaudio-1.0.so.0 -> libgstaudio-1.0.so.0.1401.0
        libgnomekbd.so.8 -> libgnomekbd.so.8.0.0
        libdcerpc-samr.so.0 -> libdcerpc-samr.so.0.0.1
        libibus-1.0.so.5 -> libibus-1.0.so.5.0.517
        librevenge-0.0.so.0 -> librevenge-0.0.so.0.0.4
        libdmapsharing-3.0.so.2 -> libdmapsharing-3.0.so.2.9.39
        libssh-gcrypt_threads.so.4 -> libssh-gcrypt_threads.so.4.5.0
        libxcb-sync.so.1 -> libxcb-sync.so.1.0.0
        libvdpau.so.1 -> libvdpau.so.1.0.0
        libm17n-core.so.0 -> libm17n-core.so.0.4.1
        libuv.so.1 -> libuv.so.1.0.0
        libubsan.so.0 -> libubsan.so.0.0.0
        libXrandr.so.2 -> libXrandr.so.2.2.0
        libbluray.so.2 -> libbluray.so.2.0.2
        libisccfg.so.160 -> libisccfg.so.160.1.2
        librdf.so.0 -> librdf.so.0.0.0
        libndr-krb5pac.so.0 -> libndr-krb5pac.so.0.0.1
        libisc-pkcs11.so.169 -> libisc-pkcs11.so.169.0.1
        libaccountsservice.so.0 -> libaccountsservice.so.0.0.0
        libXcomposite.so.1 -> libXcomposite.so.1.0.0
        libheimntlm.so.0 -> libheimntlm.so.0.1.0
        libcdda_paranoia.so.0 -> libcdda_paranoia.so.0.10.2
        libgs.so.9 -> libgs.so.9.26
        libsoup-2.4.so.1 -> libsoup-2.4.so.1.8.0
        libtotem-plparser-mini.so.18 -> libtotem-plparser-mini.so.18.1.1
        libssl.so.1.1 -> libssl.so.1.1
        libjavascriptcoregtk-4.0.so.18 -> libjavascriptcoregtk-4.0.so.18.16.5
        libatomic.so.1 -> libatomic.so.1.2.0
        libform.so.5 -> libform.so.5.9
        libnghttp2.so.14 -> libnghttp2.so.14.15.2
        libunwind-ptrace.so.0 -> libunwind-ptrace.so.0.0.0
        libwhoopsie-preferences.so.0 -> libwhoopsie-preferences.so.0.0.0
        libxcb-image.so.0 -> libxcb-image.so.0.0.0
        libflite_cmu_time_awb.so.1 -> libflite_cmu_time_awb.so.2.1
        libgmime-3.0.so.0 -> libgmime-3.0.so.0.200.0
        libdconf.so.1 -> libdconf.so.1.0.0
        libiptc.so.0 -> libiptc.so.0.0.0
        libnvidia-cfg.so.1 -> libnvidia-cfg.so.430.26
        libfftw3_threads.so.3 -> libfftw3_threads.so.3.5.7
        libmlx4.so.1 -> libmlx4.so.1.0.17.1
        libxcb-res.so.0 -> libxcb-res.so.0.0.0
        libxcb-render.so.0 -> libxcb-render.so.0.0.0
        libapt-inst.so.2.0 -> libapt-inst.so.2.0.0
        liblockfile.so.1 -> liblockfile.so.1.0
        libpciaccess.so.0 -> libpciaccess.so.0.11.1
        libexslt.so.0 -> libexslt.so.0.8.17
        libdb-5.3.so -> libdb-5.3.so
        libodfgen-0.1.so.1 -> libodfgen-0.1.so.1.0.6
        libusbmuxd.so.4 -> libusbmuxd.so.4.0.0
        libflite_cmu_grapheme_lex.so.1 -> libflite_cmu_grapheme_lex.so.2.1
        libpeas-1.0.so.0 -> libpeas-1.0.so.0.2200.0
        libbind9.so.160 -> libbind9.so.160.0.6
        libclucene-shared.so.1 -> libclucene-shared.so.2.3.3.4
        libSDL2-2.0.so.0 -> libSDL2-2.0.so.0.8.0
        liborcus-mso-0.13.so.0 -> liborcus-mso-0.13.so.0.0.0
        libtsan.so.0 -> libtsan.so.0.0.0
        libopen-rte.so.20 -> libopen-rte.so.20.10.1
        libpcrecpp.so.0 -> libpcrecpp.so.0.0.1
        libharfbuzz-icu.so.0 -> libharfbuzz-icu.so.0.10702.0
        libdrm_radeon.so.1 -> libdrm_radeon.so.1.0.1
        libwx_gtk2u_core-3.0.so.0 -> libwx_gtk2u_core-3.0.so.0.4.0
        libnvidia-opencl.so.1 -> libnvidia-opencl.so.430.26
        libXxf86dga.so.1 -> libXxf86dga.so.1.0.0
        libMagickWand-6.Q16.so.3 -> libMagickWand-6.Q16.so.3.0.0
        libsvn_fs-1.so.1 -> libsvn_fs-1.so.1.0.0
        libunistring.so.2 -> libunistring.so.2.1.0
        libdv.so.4 -> libdv.so.4.0.3
        libXft.so.2 -> libXft.so.2.3.2
        libqmi-glib.so.5 -> libqmi-glib.so.5.2.0
        libnvidia-egl-wayland.so.1 -> libnvidia-egl-wayland.so.1.1.2
        libebook-contacts-1.2.so.2 -> libebook-contacts-1.2.so.2.0.0
        libxcb-util.so.1 -> libxcb-util.so.1.0.0
        libteamdctl.so.0 -> libteamdctl.so.0.1.5
        libsodium.so.23 -> libsodium.so.23.1.0
        libdbusmenu-glib.so.4 -> libdbusmenu-glib.so.4.0.12
        libwavpack.so.1 -> libwavpack.so.1.2.0
        libavahi-core.so.7 -> libavahi-core.so.7.0.2
        librhash.so.0 -> librhash.so.0
        libjbig.so.0 -> libjbig.so.0
        libxklavier.so.16 -> libxklavier.so.16.4.0
        libIlmImfUtil-2_2.so.22 -> libIlmImfUtil-2_2.so.22.0.0
        libeot.so.0 -> libeot.so.0.0.0
        libicudata.so.60 -> libicudata.so.60.2
        libOpenGL.so.0 -> libOpenGL.so.0.0.0
        libcups.so.2 -> libcups.so.2
        libfribidi.so.0 -> libfribidi.so.0.3.6
        libmm-glib.so.0 -> libmm-glib.so.0.3.0
        libplist.so.3 -> libplist.so.3.1.0
        libgnome-games-support-1.so.3 -> libgnome-games-support-1.so.3.0.0
        libcolamd.so.2 -> libcolamd.so.2.9.6
        libhcrypto.so.4 -> libhcrypto.so.4.1.0
        libibverbs.so.1 -> libibverbs.so.1.1.17.1
        libproxy.so.1 -> libproxy.so.1.0.0
        libwebp.so.6 -> libwebp.so.6.0.2
        libdcerpc-server.so.0 -> libdcerpc-server.so.0.0.1
        libglib-2.0.so.0 -> libglib-2.0.so.0.5600.4
        libtracker-sparql-2.0.so.0 -> libtracker-sparql-2.0.so.0.3.0
        libEGL.so.1 -> libEGL.so.1.0.0
        libXv.so.1 -> libXv.so.1.0.0
        libpulse-mainloop-glib.so.0 -> libpulse-mainloop-glib.so.0.0.5
        libfastjson.so.4 -> libfastjson.so.4.2.0
        libmpi_java.so.20 -> libmpi_java.so.20.10.0
        libestr.so.0 -> libestr.so.0.0.0
        libX11.so.6 -> libX11.so.6.3.0
        libvisual-0.4.so.0 -> libvisual-0.4.so.0.0.0
        libsamba-hostconfig.so.0 -> libsamba-hostconfig.so.0.0.1
        libzeitgeist-2.0.so.0 -> libzeitgeist-2.0.so.0.0.0
        libitm.so.1 -> libitm.so.1.0.0
        libxslt.so.1 -> libxslt.so.1.1.29
        libhpipp.so.0 -> libhpipp.so.0.0.1
        libyaml-0.so.2 -> libyaml-0.so.2.0.5
        libbfd-2.30-system.so -> libbfd-2.30-system.so
        libva-drm.so.2 -> libva-drm.so.2.100.0
        libXvMC.so.1 -> libXvMC.so.1.0.0
        libcrypto.so.1.1 -> libcrypto.so.1.1
        libwebpdemux.so.2 -> libwebpdemux.so.2.0.3
        libwpd-0.10.so.10 -> libwpd-0.10.so.10.0.2
        libical-glib.so.3 -> libical-glib.so.3.0.1
        libX11-xcb.so.1 -> libX11-xcb.so.1.0.0
        libpspell.so.15 -> libpspell.so.15.2.0
        libdrm_intel.so.1 -> libdrm_intel.so.1.0.0
        libcmis-c-0.5.so.5 -> libcmis-c-0.5.so.5.0.0
        libwmf-0.2.so.7 -> libwmf-0.2.so.7.1.0
        libavahi-glib.so.1 -> libavahi-glib.so.1.0.2
        libappstream-glib.so.8 -> libappstream-glib.so.8.0.10
        liblxc.so.1 -> liblxc.so.1.4.0
        libmpi_cxx.so.20 -> libmpi_cxx.so.20.10.0
        libdaemon.so.0 -> libdaemon.so.0.5.0
        libsmbldap.so.2 -> libsmbldap.so.2
        libmca_common_sm.so.20 -> libmca_common_sm.so.20.10.1
        libtic.so.5 -> libtic.so.5.9
        libunwind.so.8 -> libunwind.so.8.0.1
        libgc.so.1 -> libgc.so.1.0.3
        libgstfft-1.0.so.0 -> libgstfft-1.0.so.0.1401.0
        libpcsclite.so.1 -> libpcsclite.so.1.0.0
        liborcus-0.13.so.0 -> liborcus-0.13.so.0.0.0
        libasan.so.3 -> libasan.so.3.0.0
        libefivar.so.1 -> libefivar.so.1.34
        libGLX.so.0 -> libGLX.so.0.0.0
        libiec61883.so.0 -> libiec61883.so.0.1.1
        libassuan.so.0 -> libassuan.so.0.8.1
        libzmq.so.5 -> libzmq.so.5.1.5
        libwx_gtk2u_stc-3.0.so.0 -> libwx_gtk2u_stc-3.0.so.0.4.0
        libgstnet-1.0.so.0 -> libgstnet-1.0.so.0.1401.0
        libmpc.so.3 -> libmpc.so.3.1.0
        libflite_cmu_us_rms.so.1 -> libflite_cmu_us_rms.so.2.1
        libv4lconvert.so.0 -> libv4lconvert.so.0.0.0
        libgdbm.so.5 -> libgdbm.so.5.0.0
        libwnck-3.so.0 -> libwnck-3.so.0.3.0
        libQt5EglFSDeviceIntegration.so.5 -> libQt5EglFSDeviceIntegration.so.5.9.5
        libpanelw.so.5 -> libpanelw.so.5.9
        libmysofa.so.0 -> libmysofa.so.0.5.1
        libapt-private.so.0.0 -> libapt-private.so.0.0.0
        libevview3.so.3 -> libevview3.so.3.0.0
        libelf.so.1 -> libelf-0.170.so
        libgstreamer-1.0.so.0 -> libgstreamer-1.0.so.0.1401.0
        libgcr-ui-3.so.1 -> libgcr-ui-3.so.1.0.0
        libssl.so.1.0.0 -> libssl.so.1.0.0
        libpulse-simple.so.0 -> libpulse-simple.so.0.1.1
        libdw.so.1 -> libdw-0.170.so
        libXrender.so.1 -> libXrender.so.1.3.0
        libclutter-1.0.so.0 -> libclutter-1.0.so.0.2600.2
        libsvn_ra_svn-1.so.1 -> libsvn_ra_svn-1.so.1.0.0
        libXau.so.6 -> libXau.so.6.0.0
        libsvn_fs_x-1.so.1 -> libsvn_fs_x-1.so.1.0.0
        libvncclient.so.1 -> libvncclient.so.1.0.0
        libcroco-0.6.so.3 -> libcroco-0.6.so.3.0.1
        libgomp.so.1 -> libgomp.so.1.0.0
        libsvn_delta-1.so.1 -> libsvn_delta-1.so.1.0.0
        libbd_fs.so.2 -> libbd_fs.so.2.0.0
        libXcursor.so.1 -> libXcursor.so.1.0.2
        liborc-test-0.4.so.0 -> liborc-test-0.4.so.0.28.0
        libflite_usenglish.so.1 -> libflite_usenglish.so.2.1
        libwx_baseu-3.0.so.0 -> libwx_baseu-3.0.so.0.4.0
        libclucene-core.so.1 -> libclucene-core.so.2.3.3.4
        libpagemaker-0.0.so.0 -> libpagemaker-0.0.so.0.0.4
        libjackserver.so.0 -> libjackserver.so.0.1.0
        libffi.so.6 -> libffi.so.6.0.4
        libcdio_cdda.so.2 -> libcdio_cdda.so.2.0.0
        libdns.so.1100 -> libdns.so.1100.1.1
        libfftw3l_threads.so.3 -> libfftw3l_threads.so.3.5.7
        libmspub-0.1.so.1 -> libmspub-0.1.so.1.0.4
        libopenal.so.1 -> libopenal.so.1.18.2
        libexiv2.so.14 -> libexiv2.so.14.0.0
        libogg.so.0 -> libogg.so.0.8.2
        libnvidia-ifr.so.1 -> libnvidia-ifr.so.430.26
        libbluetooth.so.3 -> libbluetooth.so.3.18.16
        libLLVM-9.so.1 -> libLLVM-9.so.1
        libjson-glib-1.0.so.0 -> libjson-glib-1.0.so.0.400.2
        libXmuu.so.1 -> libXmuu.so.1.0.0
        libwx_gtk2u_qa-3.0.so.0 -> libwx_gtk2u_qa-3.0.so.0.4.0
        libtheora.so.0 -> libtheora.so.0.3.10
        libgrlnet-0.3.so.0 -> libgrlnet-0.3.so.0.0.3
        libepubgen-0.1.so.1 -> libepubgen-0.1.so.1.0.0
        libXdmcp.so.6 -> libXdmcp.so.6.0.0
        librevenge-generators-0.0.so.0 -> librevenge-generators-0.0.so.0.0.4
        libpixman-1.so.0 -> libpixman-1.so.0.34.0
        libnl-route-3.so.200 -> libnl-route-3.so.200.24.0
        libsecret-1.so.0 -> libsecret-1.so.0.0.0
        libperl.so.5.26 -> libperl.so.5.26.1
        libjpeg.so.8 -> libjpeg.so.8.1.2
        libboost_thread.so.1.65.1 -> libboost_thread.so.1.65.1
        libnss3.so -> libnss3.so
        libpytalloc-util.so.2 -> libpytalloc-util.so.2.1.10
        libgphoto2_port.so.12 -> libgphoto2_port.so.12.0.0
        libvolume_key.so.1 -> libvolume_key.so.1.2.2
        libwayland-server.so.0 -> libwayland-server.so.0.1.0
        libirs.so.160 -> libirs.so.160.0.4
        libtag.so.1 -> libtag.so.1.17.0
        libgdk_pixbuf_xlib-2.0.so.0 -> libgdk_pixbuf_xlib-2.0.so.0.3611.0
        liblangtag.so.1 -> liblangtag.so.1.4.1
        libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.430.26
        libdrm_nouveau.so.2 -> libdrm_nouveau.so.2.0.0
        libnetsnmptrapd.so.30 -> libnetsnmptrapd.so.30.0.3
        libgpm.so.2 -> libgpm.so.2
        libquadmath.so.0 -> libquadmath.so.0.0.0
        libcolord.so.2 -> libcolord.so.2.0.5
        libicutest.so.60 -> libicutest.so.60.2
        libopenjp2.so.7 -> libopenjp2.so.2.3.0
        libicutu.so.60 -> libicutu.so.60.2
        libdc1394.so.22 -> libdc1394.so.22.2.1
        libwayland-cursor.so.0 -> libwayland-cursor.so.0.0.0
        libpackagekit-glib2.so.18 -> libpackagekit-glib2.so.18.1.3
        libdbusmenu-gtk.so.4 -> libdbusmenu-gtk.so.4.0.12
        libinfinipath.so.4 -> libinfinipath.so.4.0
        libsysmetrics.so.1 -> libsysmetrics.so.1
        libSM.so.6 -> libSM.so.6.0.1
        libavahi-ui-gtk3.so.0 -> libavahi-ui-gtk3.so.0.1.4
        libflite_cmu_us_kal.so.1 -> libflite_cmu_us_kal.so.2.1
        libfabric.so.1 -> libfabric.so.1.9.3
        libflite_cmu_indic_lex.so.1 -> libflite_cmu_indic_lex.so.2.1
        libtcmalloc.so.4 -> libtcmalloc.so.4.3.0
        libbabeltrace-ctf-metadata.so.1 -> libbabeltrace-ctf-metadata.so.1.0.0
        libxcb-shape.so.0 -> libxcb-shape.so.0.0.0
        libLLVM-6.0.so.1 -> libLLVM-6.0.so.1
        libtcl8.6.so -> libtcl8.6.so.0
        libraw_r.so.16 -> libraw_r.so.16.0.0
        libnvcuvid.so.1 -> libnvcuvid.so.430.26
        libcanberra.so.0 -> libcanberra.so.0.2.5
        libsvn_auth_gnome_keyring-1.so.1 -> libsvn_auth_gnome_keyring-1.so.1.0.0
        libfftw3_omp.so.3 -> libfftw3_omp.so.3.5.7
        libXi.so.6 -> libXi.so.6.1.0
        libdatrie.so.1 -> libdatrie.so.1.3.3
        libmtp.so.9 -> libmtp.so.9.3.0
        libflite_cmu_us_kal16.so.1 -> libflite_cmu_us_kal16.so.2.1
        libcilkrts.so.5 -> libcilkrts.so.5.0.0
        libwx_gtk2u_propgrid-3.0.so.0 -> libwx_gtk2u_propgrid-3.0.so.0.4.0
        libopus.so.0 -> libopus.so.0.5.2
        libappindicator3.so.1 -> libappindicator3.so.1.0.0
        libgrilo-0.3.so.0 -> libgrilo-0.3.so.0.1.3
        libpopt.so.0 -> libpopt.so.0.0.0
        libatspi.so.0 -> libatspi.so.0.0.1
        libnvidia-encode.so.1 -> libnvidia-encode.so.430.26
        librom1394.so.0 -> librom1394.so.0.3.0
        libsvn_fs_util-1.so.1 -> libsvn_fs_util-1.so.1.0.0
        libIntelXvMC.so.1 -> libIntelXvMC.so.1.0.0
        libyelp.so.0 -> libyelp.so.0.0.0
        libmp3lame.so.0 -> libmp3lame.so.0.0.0
        libgraphite2.so.3 -> libgraphite2.so.3.0.1
        libshine.so.3 -> libshine.so.3.0.1
        libgd.so.3 -> libgd.so.3.0.5
        libgstbasecamerabinsrc-1.0.so.0 -> libgstbasecamerabinsrc-1.0.so.0.1401.0
        libwacom.so.2 -> libwacom.so.2.6.1
        libgoa-backend-1.0.so.1 -> libgoa-backend-1.0.so.1.0.0
        libswresample.so.2 -> libswresample.so.2.9.100
        libfontembed.so.1 -> libfontembed.so.1.0.0
        libnpth.so.0 -> libnpth.so.0.1.1
        libICE.so.6 -> libICE.so.6.3.0
        libxcb-xv.so.0 -> libxcb-xv.so.0.0.0
        libedata-cal-1.2.so.28 -> libedata-cal-1.2.so.28.0.0
        libgettextsrc-0.19.8.1.so -> libgettextsrc.so
        libpng16.so.16 -> libpng16.so.16.34.0
        libarchive.so.13 -> libarchive.so.13.2.2
        libgobject-2.0.so.0 -> libgobject-2.0.so.0.5600.4
        libcolord-gtk.so.1 -> libcolord-gtk.so.1.0.3
        libwebpmux.so.3 -> libwebpmux.so.3.0.1
        libxkbcommon.so.0 -> libxkbcommon.so.0.0.0
        libxcb-render-util.so.0 -> libxcb-render-util.so.0.0.0
        libvpx.so.5 -> libvpx.so.5.0.0
        libnvidia-compiler.so.430.26 -> libnvidia-compiler.so.430.26
        libpoppler.so.73 -> libpoppler.so.73.0.0
        libinput.so.10 -> libinput.so.10.13.0
        libindicator3.so.7 -> libindicator3.so.7.0.0
        libcheese.so.8 -> libcheese.so.8.0.10
        libnetsnmpmibs.so.30 -> libnetsnmpmibs.so.30.0.3
        libgstgl-1.0.so.0 -> libgstgl-1.0.so.0.1401.0
        libavformat.so.57 -> libavformat.so.57.83.100
        libcdio.so.17 -> libcdio.so.17.0.0
        libxmlsec1-nss.so.1 -> libxmlsec1-nss.so.1.2.25
        libtotem.so.0 -> libtotem.so.0.0.0
        libxcb-glx.so.0 -> libxcb-glx.so.0.0.0
        libaacs.so.0 -> libaacs.so.0.6.0
        libgeocode-glib.so.0 -> libgeocode-glib.so.0.0.0
        libgssapi.so.3 -> libgssapi.so.3.0.0
        libshotwell-plugin-dev-1.0.so.0 -> libshotwell-plugin-dev-1.0.so.0.28.4
        libdcerpc.so.0 -> libdcerpc.so.0.0.1
        libgstapp-1.0.so.0 -> libgstapp-1.0.so.0.1401.0
        libwhoopsie.so.0 -> libwhoopsie.so.0.0
        libmca_common_verbs.so.20 -> libmca_common_verbs.so.20.10.0
        libeatmydata.so.1 -> libeatmydata.so.1.1.2
        libjack.so.0 -> libjack.so.0.1.0
        libcupscgi.so.1 -> libcupscgi.so.1
        libzstd.so.1 -> libzstd.so.1.3.3
        libsmime3.so -> libsmime3.so
        libxcb.so.1 -> libxcb.so.1.1.0
        libgstvideo-1.0.so.0 -> libgstvideo-1.0.so.0.1401.0
        libdns-pkcs11.so.1100 -> libdns-pkcs11.so.1100.1.1
        libtotem-plparser.so.18 -> libtotem-plparser.so.18.1.1
        libGLdispatch.so.0 -> libGLdispatch.so.0.0.0
        libpwquality.so.1 -> libpwquality.so.1.0.2
        libtiff.so.5 -> libtiff.so.5.3.0
        libical.so.3 -> libical.so.3.0.1
        libspectre.so.1 -> libspectre.so.1.1.8
        libfreerdp2.so.2 -> libfreerdp2.so.2.0.0
        libfreetype.so.6 -> libfreetype.so.6.15.0
        libharfbuzz.so.0 -> libharfbuzz.so.0.10702.0
        libwx_gtk2u_adv-3.0.so.0 -> libwx_gtk2u_adv-3.0.so.0.4.0
        libgstrtsp-1.0.so.0 -> libgstrtsp-1.0.so.0.1401.0
        libetonyek-0.1.so.1 -> libetonyek-0.1.so.1.0.7
        libdee-1.0.so.4 -> libdee-1.0.so.4.2.1
        libasound.so.2 -> libasound.so.2.0.0
        libasn1.so.8 -> libasn1.so.8.0.0
        librevenge-stream-0.0.so.0 -> librevenge-stream-0.0.so.0.0.4
        libfftw3l.so.3 -> libfftw3l.so.3.5.7
        libxcb-icccm.so.4 -> libxcb-icccm.so.4.0.0
        libbd_utils.so.2 -> libbd_utils.so.2.1.0
        libcmis-0.5.so.5 -> libcmis-0.5.so.5.0.0
        libavcodec.so.57 -> libavcodec.so.57.107.100
        libmhash.so.2 -> libmhash.so.2.0.1
        libbdplus.so.0 -> libbdplus.so.0.1.0
        libraw1394.so.11 -> libraw1394.so.11.1.0
        libxcb-randr.so.0 -> libxcb-randr.so.0.1.0
        libgssapi_krb5.so.2 -> libgssapi_krb5.so.2.2
        libbabeltrace.so.1 -> libbabeltrace.so.1.0.0
        libdouble-conversion.so.1 -> libdouble-conversion.so.1.0
        libssh_threads.so.4 -> libssh_threads.so.4.5.0
        libssh.so.4 -> libssh.so.4.5.0
        libQt5DBus.so.5 -> libQt5DBus.so.5.9.5
        libwx_gtk2u_richtext-3.0.so.0 -> libwx_gtk2u_richtext-3.0.so.0.4.0
        libGeoIP.so.1 -> libGeoIP.so.1.6.12
        libsamba-credentials.so.0 -> libsamba-credentials.so.0.0.1
        libsvn_subr-1.so.1 -> libsvn_subr-1.so.1.0.0
        libsvn_ra-1.so.1 -> libsvn_ra-1.so.1.0.0
        libsamplerate.so.0 -> libsamplerate.so.0.1.8
        libevdocument3.so.4 -> libevdocument3.so.4.0.0
        libsemanage.so.1 -> libsemanage.so.1
        libmlx5.so.1 -> libmlx5.so.1.4.17.1
        libsvn_repos-1.so.1 -> libsvn_repos-1.so.1.0.0
        libsuitesparseconfig.so.5 -> libsuitesparseconfig.so.5.1.2
        libxcb-xinerama.so.0 -> libxcb-xinerama.so.0.0.0
        libbrotlidec.so.1 -> libbrotlidec.so.1.0.4
        libpcreposix.so.3 -> libpcreposix.so.3.13.3
        libjsoncpp.so.1 -> libjsoncpp.so.1.7.4
        libieee1284.so.3 -> libieee1284.so.3.2.2
        libnvidia-cbl.so.430.26 -> libnvidia-cbl.so.430.26
        libgeoclue-2.so.0 -> libgeoclue-2.so.0.0.0
        libedata-book-1.2.so.25 -> libedata-book-1.2.so.25.0.0
        libwx_baseu_xml-3.0.so.0 -> libwx_baseu_xml-3.0.so.0.4.0
        libcairo.so.2 -> libcairo.so.2.11510.0
        librhythmbox-core.so.10 -> librhythmbox-core.so.10.0.0
        libgcr-base-3.so.1 -> libgcr-base-3.so.1.0.0
        libexttextcat-2.0.so.0 -> libexttextcat-2.0.so.0.0.0
        liblwres.so.160 -> liblwres.so.160.0.1
        libtdb.so.1 -> libtdb.so.1.3.15
        libtcmalloc_debug.so.4 -> libtcmalloc_debug.so.4.3.0
        libnvidia-opticalflow.so.1 -> libnvidia-opticalflow.so.430.26
        libsvn_fs_base-1.so.1 -> libsvn_fs_base-1.so.1.0.0
        libwx_gtk2u_ribbon-3.0.so.0 -> libwx_gtk2u_ribbon-3.0.so.0.4.0
        libndp.so.0 -> libndp.so.0.1.0
        libGLU.so.1 -> libGLU.so.1.3.1
        liborc-0.4.so.0 -> liborc-0.4.so.0.28.0
        libgmodule-2.0.so.0 -> libgmodule-2.0.so.0.5600.4
        libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.0.0
        libXss.so.1 -> libXss.so.1.0.0
        libcanberra-gtk3.so.0 -> libcanberra-gtk3.so.0.1.9
        libsvn_ra_local-1.so.1 -> libsvn_ra_local-1.so.1.0.0
        libtheoradec.so.1 -> libtheoradec.so.1.1.4
        libpoppler-glib.so.8 -> libpoppler-glib.so.8.9.0
        libhx509.so.5 -> libhx509.so.5.0.0
        libbabeltrace-lttng-live.so.1 -> libbabeltrace-lttng-live.so.1.0.0
        libgsttag-1.0.so.0 -> libgsttag-1.0.so.0.1401.0
        libgstcheck-1.0.so.0 -> libgstcheck-1.0.so.0.1401.0
        libgstbase-1.0.so.0 -> libgstbase-1.0.so.0.1401.0
        libcrypto.so.1.0.0 -> libcrypto.so.1.0.0
        libgoa-1.0.so.0 -> libgoa-1.0.so.0.0.0
        libicalss.so.3 -> libicalss.so.3.0.1
        libsamdb.so.0 -> libsamdb.so.0.0.1
        libnfnetlink.so.0 -> libnfnetlink.so.0.2.0
        libndr-standard.so.0 -> libndr-standard.so.0.0.1
        libgtk-3.so.0 -> libgtk-3.so.0.2200.30
        libnetsnmpagent.so.30 -> libnetsnmpagent.so.30.0.3
        libxmlsec1.so.1 -> libxmlsec1.so.1.2.25
        libgusb.so.2 -> libgusb.so.2.0.10
        libxcb-xkb.so.1 -> libxcb-xkb.so.1.0.0
        libxmlsec1-openssl.so.1 -> libxmlsec1-openssl.so.1.2.25
        libisns.so.0 -> libisns.so.0
        libboost_system.so.1.65.1 -> libboost_system.so.1.65.1
        libgdbm_compat.so.4 -> libgdbm_compat.so.4.0.0
        libxcb-xfixes.so.0 -> libxcb-xfixes.so.0.0.0
        libgfortran.so.4 -> libgfortran.so.4.0.0
        libedit.so.2 -> libedit.so.2.0.56
        libebook-1.2.so.19 -> libebook-1.2.so.19.1.3
        libxapian.so.30 -> libxapian.so.30.4.0
        libnetfilter_conntrack.so.3 -> libnetfilter_conntrack.so.3.6.0
        libspeechd.so.2 -> libspeechd.so.2.6.0
        libmspack.so.0 -> libmspack.so.0.1.0
        libgnutls.so.30 -> libgnutls.so.30.14.10
        libaspell.so.15 -> libaspell.so.15.2.0
        libXaw.so.7 -> libXaw7.so.7.0.0
        libcaca++.so.0 -> libcaca++.so.0.99.19
        libphonenumber.so.7 -> libphonenumber.so.7.0
        libfreehand-0.1.so.1 -> libfreehand-0.1.so.1.0.2
        libsnappy.so.1 -> libsnappy.so.1.1.7
        libaprutil-1.so.0 -> libaprutil-1.so.0.6.1
        libshotwell-authenticator.so.0 -> libshotwell-authenticator.so.0.28.4
        libpulse.so.0 -> libpulse.so.0.20.2
        libFLAC.so.8 -> libFLAC.so.8.3.0
        libnetsnmphelpers.so.30 -> libnetsnmphelpers.so.30.0.3
        libQt5Svg.so.5 -> libQt5Svg.so.5.9.5
        libdjvulibre.so.21 -> libdjvulibre.so.21.6.0
        libfontconfig.so.1 -> libfontconfig.so.1.10.1
        libfftw3f_omp.so.3 -> libfftw3f_omp.so.3.5.7
        libgnome-menu-3.so.0 -> libgnome-menu-3.so.0.0.1
        libsoup-gnome-2.4.so.1 -> libsoup-gnome-2.4.so.1.8.0
        libsamba-policy.so.0 -> libsamba-policy.so.0.0.1
        libnvoptix.so.1 -> libnvoptix.so.430.26
        libQt5Network.so.5 -> libQt5Network.so.5.9.5
        libcamel-1.2.so.61 -> libcamel-1.2.so.61.0.0
        libmpdec.so.2 -> libmpdec.so.2.4.2
        libnotify.so.4 -> libnotify.so.4.0.0
        libgpgmepp.so.6 -> libgpgmepp.so.6.5.0
        libv4l2.so.0 -> libv4l2.so.0.0.0
        libsqlite3.so.0 -> libsqlite3.so.0.8.6
        libmbim-glib.so.4 -> libmbim-glib.so.4.2.0
        libatk-1.0.so.0 -> libatk-1.0.so.0.22810.1
        libXinerama.so.1 -> libXinerama.so.1.0.0
        libompitrace.so.20 -> libompitrace.so.20.10.0
        libvorbisfile.so.3 -> libvorbisfile.so.3.3.7
        libwayland-egl.so.1 -> libwayland-egl.so.1.0.0
        libQt5PrintSupport.so.5 -> libQt5PrintSupport.so.5.9.5
        libXRes.so.1 -> libXRes.so.1.0.0
        libpangocairo-1.0.so.0 -> libpangocairo-1.0.so.0.4000.14
        libmpi.so.20 -> libmpi.so.20.10.1
        libm17n-gui.so.0 -> libm17n-gui.so.0.4.1
        libminiupnpc.so.10 -> libminiupnpc.so.10
        libsvn_fs_fs-1.so.1 -> libsvn_fs_fs-1.so.1.0.0
        libfftw3f.so.3 -> libfftw3f.so.3.5.7
        libnvidia-glcore.so.430.26 -> libnvidia-glcore.so.430.26
        libgme.so.0 -> libgme.so.0.6.2
        libcupsfilters.so.1 -> libcupsfilters.so.1.0.0
        libicalss_cxx.so.3 -> libicalss_cxx.so.3.0.1
        libneon-gnutls.so.27 -> libneon-gnutls.so.27.3.2
        libpangoxft-1.0.so.0 -> libpangoxft-1.0.so.0.4000.14
        libva.so.2 -> libva.so.2.100.0
        libnetsnmp.so.30 -> libnetsnmp.so.30.0.3
        libEGL_nvidia.so.0 -> libEGL_nvidia.so.430.26
        libfwupd.so.2 -> libfwupd.so.2.0.0
        libfontenc.so.1 -> libfontenc.so.1.0.0
        libflite_cmulex.so.1 -> libflite_cmulex.so.2.1
        libXmu.so.6 -> libXmu.so.6.2.0
        libpangoft2-1.0.so.0 -> libpangoft2-1.0.so.0.4000.14
        libatk-bridge-2.0.so.0 -> libatk-bridge-2.0.so.0.0.0
        libevdev.so.2 -> libevdev.so.2.1.20
        libmenuw.so.5 -> libmenuw.so.5.9
        libstemmer.so.0d -> libstemmer.so.0d.0.0
        libXpm.so.4 -> libXpm.so.4.11.0
        libbd_part.so.2 -> libbd_part.so.2.0.0
        libisc.so.169 -> libisc.so.169.0.1
        libjbig2dec.so.0 -> libjbig2dec.so.0.0.0
        libQt5Gui.so.5 -> libQt5Gui.so.5.9.5
        libpython2.7.so.1.0 -> libpython2.7.so.1.0
        libthai.so.0 -> libthai.so.0.3.0
        libtevent.so.0 -> libtevent.so.0.9.34
        libgutenprint.so.2 -> libgutenprint.so.2.6.0
        libimobiledevice.so.6 -> libimobiledevice.so.6.0.0
        libmenu.so.5 -> libmenu.so.5.9
        libgio-2.0.so.0 -> libgio-2.0.so.0.5600.4
        libqpdf.so.21 -> libqpdf.so.21.0.2
        libcogl-path.so.20 -> libcogl-path.so.20.4.2
        libx265.so.146 -> libx265.so.146
        libgailutil.so.18 -> libgailutil.so.18.0.1
        libpeas-gtk-1.0.so.0 -> libpeas-gtk-1.0.so.0.2200.0
        libmozjs-52.so.0 -> libmozjs-52.so.0.0.0
        libsamba-errors.so.1 -> libsamba-errors.so.1
        libxtables.so.12 -> libxtables.so.12.0.0
        libcurl-gnutls.so.4 -> libcurl-gnutls.so.4.5.0
        libtheoraenc.so.1 -> libtheoraenc.so.1.1.2
        libImath-2_2.so.12 -> libImath-2_2.so.12.0.0
        libdumbnet.so.1 -> libdumbnet.so.1.0.1
        libcares.so.2 -> libcares.so.2.2.0
        libappstream.so.4 -> libappstream.so.0.12.0
        libgom-1.0.so.0 -> libgom-1.0.so.0.1.0
        libIex-2_2.so.12 -> libIex-2_2.so.12.0.0
        libcrack.so.2 -> libcrack.so.2.9.0
        libcdio_paranoia.so.2 -> libcdio_paranoia.so.2.0.0
        libgcab-1.0.so.0 -> libgcab-1.0.so.0.0.0
        libgailutil-3.so.0 -> libgailutil-3.so.0.0.0
        libvte-2.91.so.0 -> libvte-2.91.so.0.5200.2
        libshotwell-plugin-common.so.0 -> libshotwell-plugin-common.so.0.28.4
        libgif.so.7 -> libgif.so.7.0.0
        libXxf86vm.so.1 -> libXxf86vm.so.1.0.0
        libblockdev.so.2 -> libblockdev.so.2.0.0
        libflite.so.1 -> libflite.so.2.1
        libgstrtp-1.0.so.0 -> libgstrtp-1.0.so.0.1401.0
        libmpi_usempif08.so.20 -> libmpi_usempif08.so.20.10.0
        libvorbis.so.0 -> libvorbis.so.0.4.8
        libnettle.so.6 -> libnettle.so.6.4
        libpanel.so.5 -> libpanel.so.5.9
        libavdevice.so.57 -> libavdevice.so.57.10.100
        libunwind-x86_64.so.8 -> libunwind-x86_64.so.8.0.1
        libicui18n.so.60 -> libicui18n.so.60.2
        libxatracker.so.2 -> libxatracker.so.2.5.0
        libx264.so.152 -> libx264.so.152
        libsane.so.1 -> libsane.so.1.0.27
        libsoxr.so.0 -> libsoxr.so.0.1.1
        libraptor2.so.0 -> libraptor2.so.0.0.0
        libsensors.so.4 -> libsensors.so.4.4.0
        libnvidia-ml.so.1 -> libnvidia-ml.so.430.26
        libwebkit2gtk-4.0.so.37 -> libwebkit2gtk-4.0.so.37.44.4
        libm17n.so.0 -> libm17n.so.0.4.1
        libGLX_mesa.so.0 -> libGLX_mesa.so.0.0.0
        libglut.so.3 -> libglut.so.3.9.0
        libhpdiscovery.so.0 -> libhpdiscovery.so.0.0.1
        libicalvcal.so.3 -> libicalvcal.so.3.0.1
        libtk8.6.so -> libtk8.6.so.0
        libmca_common_libfabric.so.20 -> libmca_common_libfabric.so.20.10.0
        libpsl.so.5 -> libpsl.so.5.2.0
        libsamba-util.so.0 -> libsamba-util.so.0.0.1
        libldb.so.1 -> libldb.so.1.2.3
        libsndfile.so.1 -> libsndfile.so.1.0.28
        liblber-2.4.so.2 -> liblber-2.4.so.2.10.8
        libsasl2.so.2 -> libsasl2.so.2.0.25
        libavutil.so.55 -> libavutil.so.55.78.100
        libkpathsea.so.6 -> libkpathsea.so.6.2.3
        librubberband.so.2 -> librubberband.so.2.1.0
        libtasn1.so.6 -> libtasn1.so.6.5.5
        libtalloc.so.2 -> libtalloc.so.2.1.10
        libgettextlib-0.19.8.1.so -> libgettextlib.so
        libksba.so.8 -> libksba.so.8.11.6
        libdrm_amdgpu.so.1 -> libdrm_amdgpu.so.1.0.0
        libprotobuf.so.10 -> libprotobuf.so.10.0.0
        libass.so.9 -> libass.so.9.0.2
        libboost_iostreams.so.1.65.1 -> libboost_iostreams.so.1.65.1
        libe-book-0.1.so.1 -> libe-book-0.1.so.1.0.3
        libicuuc.so.60 -> libicuuc.so.60.2
        libgpod.so.4 -> libgpod.so.4.3.2
        libgirepository-1.0.so.1 -> libgirepository-1.0.so.1.0.0
        libboost_filesystem.so.1.65.1 -> libboost_filesystem.so.1.65.1
        libgudev-1.0.so.0 -> libgudev-1.0.so.0.2.0
        libshout.so.3 -> libshout.so.3.2.0
        libgbm.so.1 -> libgbm.so.1.0.0
        libheimbase.so.1 -> libheimbase.so.1.0.0
        libkrb5.so.3 -> libkrb5.so.3.3
        libwpg-0.3.so.3 -> libwpg-0.3.so.3.0.1
        libip6tc.so.0 -> libip6tc.so.0.1.0
        libcheese-gtk.so.25 -> libcheese-gtk.so.25.1.0
        libgexiv2.so.2 -> libgexiv2.so.2.0.0
        libtcmalloc_minimal.so.4 -> libtcmalloc_minimal.so.4.3.0
        libunity-extras.so.9 -> libunity-extras.so.9.0.2
        libgstcontroller-1.0.so.0 -> libgstcontroller-1.0.so.0.1401.0
        libwx_gtk2u_aui-3.0.so.0 -> libwx_gtk2u_aui-3.0.so.0.4.0
        libtiffxx.so.5 -> libtiffxx.so.5.3.0
        libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.430.26
        libglapi.so.0 -> libglapi.so.0.0.0
        libcolordprivate.so.2 -> libcolordprivate.so.2.0.5
        libwx_baseu_net-3.0.so.0 -> libwx_baseu_net-3.0.so.0.4.0
        libroken.so.18 -> libroken.so.18.1.0
        libxvidcore.so.4 -> libxvidcore.so.4.3
        libmpx.so.2 -> libmpx.so.2.0.1
        libdebconfclient.so.0 -> libdebconfclient.so.0.0.0
        libxkbfile.so.1 -> libxkbfile.so.1.0.2
        libedataserver-1.2.so.23 -> libedataserver-1.2.so.23.0.0
        libfftw3f_threads.so.3 -> libfftw3f_threads.so.3.5.7
        libenchant.so.1 -> libenchant.so.1.6.0
        libm17n-flt.so.0 -> libm17n-flt.so.0.4.1
        libkrb5.so.26 -> libkrb5.so.26.0.0
        libgpgme.so.11 -> libgpgme.so.11.19.0
        libkrb5support.so.0 -> libkrb5support.so.0.1
        libdrm.so.2 -> libdrm.so.2.4.0
        libwind.so.0 -> libwind.so.0.0.0
        libgstallocators-1.0.so.0 -> libgstallocators-1.0.so.0.1401.0
        libsnmp.so.30 -> libsnmp.so.30.0.3
        liblouis.so.14 -> liblouis.so.14.1.2
        libpolkit-agent-1.so.0 -> libpolkit-agent-1.so.0.0.0
        libpcap.so.0.8 -> libpcap.so.1.8.1
        libgraphene-1.0.so.0 -> libgraphene-1.0.so.0.800.0
        libpolkit-gobject-1.so.0 -> libpolkit-gobject-1.so.0.0.0
        libnssutil3.so -> libnssutil3.so
        libIlmThread-2_2.so.12 -> libIlmThread-2_2.so.12.0.0
        libspeex.so.1 -> libspeex.so.1.5.0
        libavc1394.so.0 -> libavc1394.so.0.3.0
        libmutter-2.so.0 -> libmutter-2.so.0.0.0
        libpcaudio.so.0 -> libpcaudio.so.0.0.0
        libyaml-cpp.so.0.5 -> libyaml-cpp.so.0.5.2
        libprofiler.so.0 -> libprofiler.so.0.4.8
        liblua5.3-c++.so.0 -> liblua5.3-c++.so.0.0.0
        libip4tc.so.0 -> libip4tc.so.0.1.0
        libaa.so.1 -> libaa.so.1.0.4
        libguile-2.0.so.22 -> libguile-2.0.so.22.8.1
        libhogweed.so.4 -> libhogweed.so.4.4
        libgtop-2.0.so.11 -> libgtop-2.0.so.11.0.0
        libcairo-gobject.so.2 -> libcairo-gobject.so.2.11510.0
        libopts.so.25 -> libopts.so.25.16.1
        libgrlpls-0.3.so.0 -> libgrlpls-0.3.so.0.0.0
        libsvn_wc-1.so.1 -> libsvn_wc-1.so.1.0.0
        libI810XvMC.so.1 -> libI810XvMC.so.1.0.0
        libwps-0.4.so.4 -> libwps-0.4.so.4.0.8
        libvorbisenc.so.2 -> libvorbisenc.so.2.0.11
        libao.so.4 -> libao.so.4.1.1
        libupower-glib.so.3 -> libupower-glib.so.3.0.1
        libHalf.so.12 -> libHalf.so.12.0.0
        libfftw3q_threads.so.3 -> libfftw3q_threads.so.3.5.7
        libv4l1.so.0 -> libv4l1.so.0.0.0
        libgnomekbdui.so.8 -> libgnomekbdui.so.8.0.0
        libmagic.so.1 -> libmagic.so.1.0.0
        libstdc++.so.6 -> libstdc++.so.6.0.25
        libpaper.so.1 -> libpaper.so.1.1.2
        libformw.so.5 -> libformw.so.5.9
        libwbclient.so.0 -> libwbclient.so.0.14
        libserf-1.so.1 -> libserf-1.so.1.3.0
        libndr-nbt.so.0 -> libndr-nbt.so.0.0.1
        libcuda.so.1 -> libcuda.so.430.26
        libhpmud.so.0 -> libhpmud.so.0.0.6
        libcogl.so.20 -> libcogl.so.20.4.2
        libgstpbutils-1.0.so.0 -> libgstpbutils-1.0.so.0.1401.0
        libasan.so.4 -> libasan.so.4.0.0
        libjacknet.so.0 -> libjacknet.so.0.1.0
        libgnome-desktop-3.so.17 -> libgnome-desktop-3.so.17.0.0
        libxml2.so.2 -> libxml2.so.2.9.4
        libhyphen.so.0 -> libhyphen.so.0.3.0
        libguilereadline-v-18.so.18 -> libguilereadline-v-18.so.18.0.0
        libQt5Core.so.5 -> libQt5Core.so.5.9.5
        libepoxy.so.0 -> libepoxy.so.0.0.0
        libQt5EglFsKmsSupport.so.5 -> libQt5EglFsKmsSupport.so.5.9.5
        libXext.so.6 -> libXext.so.6.4.0
        libebackend-1.2.so.10 -> libebackend-1.2.so.10.0.0
        libhwloc.so.5 -> libhwloc.so.5.7.6
        libXfont2.so.2 -> libXfont2.so.2.0.0
        libsgutils2.so.2 -> libsgutils2.so.2.0.0
        libwx_gtk2u_html-3.0.so.0 -> libwx_gtk2u_html-3.0.so.0.4.0
        liblua5.3.so.0 -> liblua5.3.so.0.0.0
        libgweather-3.so.15 -> libgweather-3.so.15.0.0
        libspeexdsp.so.1 -> libspeexdsp.so.1.5.0
        libunity.so.9 -> libunity.so.9.0.2
        libcolorhug.so.2 -> libcolorhug.so.2.0.5
        libefiboot.so.1 -> libefiboot.so.1.34
        libavresample.so.3 -> libavresample.so.3.7.0
        libdbusmenu-gtk3.so.4 -> libdbusmenu-gtk3.so.4.0.12
        libpython3.6m.so.1.0 -> libpython3.6m.so.1.0
        libcdr-0.1.so.1 -> libcdr-0.1.so.1.0.4
        libicuio.so.60 -> libicuio.so.60.2
        libjansson.so.4 -> libjansson.so.4.11.0
        libcrystalhd.so.3 -> libcrystalhd.so.3.6
        libMagickCore-6.Q16.so.3 -> libMagickCore-6.Q16.so.3.0.0
        libwebrtc_audio_processing.so.1 -> libwebrtc_audio_processing.so.1.0.0
        libwmflite-0.2.so.7 -> libwmflite-0.2.so.7.0.1
        libxshmfence.so.1 -> libxshmfence.so.1.0.0
        libmpg123.so.0 -> libmpg123.so.0.44.8
        libbd_loop.so.2 -> libbd_loop.so.2.0.0
        libical_cxx.so.3 -> libical_cxx.so.3.0.1
        libunwind-coredump.so.0 -> libunwind-coredump.so.0.0.0
        libgtk-x11-2.0.so.0 -> libgtk-x11-2.0.so.0.2400.32
        libltdl.so.7 -> libltdl.so.7.3.1
        libgdm.so.1 -> libgdm.so.1.0.0
        libgck-1.so.0 -> libgck-1.so.0.0.0
        libgmp.so.10 -> libgmp.so.10.3.2
        libotf.so.0 -> libotf.so.0.0.0
        libldap_r-2.4.so.2 -> libldap_r-2.4.so.2.10.8
        libnautilus-extension.so.1 -> libnautilus-extension.so.1.4.0
        libdbus-glib-1.so.2 -> libdbus-glib-1.so.2.3.4
        libzvbi.so.0 -> libzvbi.so.0.13.2
        libgccpp.so.1 -> libgccpp.so.1.0.3
        libsigsegv.so.2 -> libsigsegv.so.2.0.5
        libbd_part_err.so.2 -> libbd_part_err.so.2.0.0
        libcaca.so.0 -> libcaca.so.0.99.19
        libfftw3q_omp.so.3 -> libfftw3q_omp.so.3.5.7
        libwx_gtk2u_gl-3.0.so.0 -> libwx_gtk2u_gl-3.0.so.0.4.0
        libdotconf.so.0 -> libdotconf.so.0.0.1
        libQt5XcbQpa.so.5 -> libQt5XcbQpa.so.5.9.5
        libbd_crypto.so.2 -> libbd_crypto.so.2.0.0
        libwoff2common.so.1.0.2 -> libwoff2common.so.1.0.2
        libpostproc.so.54 -> libpostproc.so.54.7.100
        librsvg-2.so.2 -> librsvg-2.so.2.40.20
        libgnome-bluetooth.so.13 -> libgnome-bluetooth.so.13.0.1
        libpango-1.0.so.0 -> libpango-1.0.so.0.4000.14
        libboost_date_time.so.1.65.1 -> libboost_date_time.so.1.65.1
        libcogl-pango.so.20 -> libcogl-pango.so.20.4.2
        libnma.so.0 -> libnma.so.0.0.0
        libIlmImf-2_2.so.22 -> libIlmImf-2_2.so.22.0.0
        libwinpr2.so.2 -> libwinpr2.so.2.0.0
        libmpxwrappers.so.2 -> libmpxwrappers.so.2.0.1
        libexif.so.12 -> libexif.so.12.3.3
        libsmbclient.so.0 -> libsmbclient.so.0.2.3
        libgnome-autoar-0.so.0 -> libgnome-autoar-0.so.0.0.0
        libsvn_ra_serf-1.so.1 -> libsvn_ra_serf-1.so.1.0.0
        libbabeltrace-ctf-text.so.1 -> libbabeltrace-ctf-text.so.1.0.0
        libart_lgpl_2.so.2 -> libart_lgpl_2.so.2.3.21
/lib:
        libhandle.so.1 -> libhandle.so.1.0.3
/usr/lib:
        libnatpmp.so.1 -> libnatpmp.so.1
        libhgfs.so.0 -> libhgfs.so.0.0.0
        libBLT.2.5.so.8.6 -> libBLT.2.5.so.8.6
        libnetpbm.so.10 -> libnetpbm.so.10.0
        libvgauth.so.0 -> libvgauth.so.0.0.0
        libDeployPkg.so.0 -> libDeployPkg.so.0.0.0
        libgjs.so.0 -> libgjs.so.0.0.0
        libguestlib.so.0 -> libguestlib.so.0.0.0
        libvmtools.so.0 -> libvmtools.so.0.0.0
        libBLTlite.2.5.so.8.6 -> libBLTlite.2.5.so.8.6
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
(venv3) ron@climber2:~/fake-text-detect$

**Comment by Saduf2019** [comment]
@rongtianyue 
Can you please share your  cuda, cudnn version.
See https://www.tensorflow.org/install/source#gpu

**Comment by rongtianyue** [comment]
In my original post, I put 9.0. It hasn’t changed. I’m using tensorflow-gpu 1.12.0, accidentally wrote v2.

**Comment by Saduf2019** [comment]
@rongtianyue 
This is a very old version and there are no updates for this, can you please upgrade yo a later version and see if you face any issues.

**Comment by rongtianyue** [comment]
Updated version does not matter, same error.

**Comment by rongtianyue** [comment]
Any updates? If not, I will have to re-configure my entire development environment.

**Comment by rongtianyue** [comment]
any updates?

**Comment by rongtianyue** [comment]
Problem solved a while ago. the shared object file wasn't registering for some reason. had to recreate it.

**Comment by Saduf2019** [comment]
@rongtianyue 
Please confirm if we may move this to closed status as issue is resolved.
