### ISSUE TITLE
Documentation instructions on installing tensorflow with CUDA support doesn't work

### ISSUE THREAD

**Issue by dhiegomaga** [tensorflow/tensorflow#40278]
OS: Ubuntu 18.04
Graphics card: Nvidia 1050Ti

**Problem**
Following the instructions under https://www.tensorflow.org/install/gpu#install_cuda_with_apt gives the following error: 

```ssh
...

Unpacking libcudnn7-dev (7.6.4.38-1+cuda10.1) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-fjAi3S/55-libnvidia-compute-450_450.36.06-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
after executing this step
```ssh
sudo apt-get install --no-install-recommends \
>     cuda-10-1 \
>     libcudnn7=7.6.4.38-1+cuda10.1  \
>     libcudnn7-dev=7.6.4.38-1+cuda10.1
```

**Additional Info**
The complete message after running the above command is

```ssh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libnvidia-common-440 libnvidia-extra-440
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  cuda-command-line-tools-10-1 cuda-compiler-10-1 cuda-cudart-10-1
  cuda-cudart-dev-10-1 cuda-cufft-10-1 cuda-cufft-dev-10-1 cuda-cuobjdump-10-1
  cuda-cupti-10-1 cuda-curand-10-1 cuda-curand-dev-10-1 cuda-cusolver-10-1
  cuda-cusolver-dev-10-1 cuda-cusparse-10-1 cuda-cusparse-dev-10-1
  cuda-demo-suite-10-1 cuda-documentation-10-1 cuda-driver-dev-10-1
  cuda-drivers cuda-drivers-450 cuda-gdb-10-1 cuda-gpu-library-advisor-10-1
  cuda-libraries-10-1 cuda-libraries-dev-10-1 cuda-license-10-1
  cuda-license-10-2 cuda-memcheck-10-1 cuda-misc-headers-10-1 cuda-npp-10-1
  cuda-npp-dev-10-1 cuda-nsight-10-1 cuda-nsight-compute-10-1
  cuda-nsight-systems-10-1 cuda-nvcc-10-1 cuda-nvdisasm-10-1 cuda-nvgraph-10-1
  cuda-nvgraph-dev-10-1 cuda-nvjpeg-10-1 cuda-nvjpeg-dev-10-1
  cuda-nvml-dev-10-1 cuda-nvprof-10-1 cuda-nvprune-10-1 cuda-nvrtc-10-1
  cuda-nvrtc-dev-10-1 cuda-nvtx-10-1 cuda-nvvp-10-1 cuda-runtime-10-1
  cuda-samples-10-1 cuda-sanitizer-api-10-1 cuda-toolkit-10-1 cuda-tools-10-1
  cuda-visual-tools-10-1 default-jre default-jre-headless libcublas-dev
  libcublas10 libnvidia-cfg1-450 libnvidia-common-450 libnvidia-compute-450
  libnvidia-decode-450 libnvidia-encode-450 libnvidia-fbc1-450
  libnvidia-gl-450 libnvidia-ifr1-450 nsight-compute-2019.5.0
  nsight-systems-2019.5.2 nvidia-compute-utils-450 nvidia-dkms-450
  nvidia-driver-450 nvidia-kernel-common-450 nvidia-kernel-source-450
  nvidia-modprobe nvidia-settings nvidia-utils-450 openjdk-11-jre
  openjdk-11-jre-headless xserver-xorg-video-nvidia-450
Suggested packages:
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  | fonts-wqy-zenhei
The following packages will be REMOVED:
  libnvidia-cfg1-440 libnvidia-compute-440 libnvidia-decode-440
  libnvidia-encode-440 libnvidia-fbc1-440 libnvidia-fbc1-440:i386
  libnvidia-gl-440 libnvidia-ifr1-440 nvidia-compute-utils-440 nvidia-dkms-440
  nvidia-driver-430 nvidia-driver-440 nvidia-kernel-common-440
  nvidia-kernel-source-440 nvidia-utils-440 xserver-xorg-video-nvidia-440
The following NEW packages will be installed:
  cuda-10-1 cuda-command-line-tools-10-1 cuda-compiler-10-1 cuda-cudart-10-1
  cuda-cudart-dev-10-1 cuda-cufft-10-1 cuda-cufft-dev-10-1 cuda-cuobjdump-10-1
  cuda-cupti-10-1 cuda-curand-10-1 cuda-curand-dev-10-1 cuda-cusolver-10-1
  cuda-cusolver-dev-10-1 cuda-cusparse-10-1 cuda-cusparse-dev-10-1
  cuda-demo-suite-10-1 cuda-documentation-10-1 cuda-driver-dev-10-1
  cuda-drivers cuda-drivers-450 cuda-gdb-10-1 cuda-gpu-library-advisor-10-1
  cuda-libraries-10-1 cuda-libraries-dev-10-1 cuda-license-10-1
  cuda-license-10-2 cuda-memcheck-10-1 cuda-misc-headers-10-1 cuda-npp-10-1
  cuda-npp-dev-10-1 cuda-nsight-10-1 cuda-nsight-compute-10-1
  cuda-nsight-systems-10-1 cuda-nvcc-10-1 cuda-nvdisasm-10-1 cuda-nvgraph-10-1
  cuda-nvgraph-dev-10-1 cuda-nvjpeg-10-1 cuda-nvjpeg-dev-10-1
  cuda-nvml-dev-10-1 cuda-nvprof-10-1 cuda-nvprune-10-1 cuda-nvrtc-10-1
  cuda-nvrtc-dev-10-1 cuda-nvtx-10-1 cuda-nvvp-10-1 cuda-runtime-10-1
  cuda-samples-10-1 cuda-sanitizer-api-10-1 cuda-toolkit-10-1 cuda-tools-10-1
  cuda-visual-tools-10-1 default-jre default-jre-headless libcublas-dev
  libcublas10 libcudnn7 libcudnn7-dev libnvidia-cfg1-450 libnvidia-common-450
  libnvidia-compute-450 libnvidia-decode-450 libnvidia-encode-450
  libnvidia-fbc1-450 libnvidia-gl-450 libnvidia-ifr1-450
  nsight-compute-2019.5.0 nsight-systems-2019.5.2 nvidia-compute-utils-450
  nvidia-dkms-450 nvidia-driver-450 nvidia-kernel-common-450
  nvidia-kernel-source-450 nvidia-modprobe nvidia-settings nvidia-utils-450
  openjdk-11-jre openjdk-11-jre-headless xserver-xorg-video-nvidia-450
0 upgraded, 79 newly installed, 16 to remove and 239 not upgraded.
Need to get 0 B/2,205 MB of archives.
After this operation, 4,855 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Extracting templates from packages: 100%
(Reading database ... 294935 files and directories currently installed.)
Removing nvidia-driver-430 (440.59-0ubuntu0.18.04.1) ...
Removing nvidia-driver-440 (440.82-0ubuntu0~0.18.04.2) ...
Removing xserver-xorg-video-nvidia-440 (440.82-0ubuntu0~0.18.04.2) ...
Removing libnvidia-cfg1-440:amd64 (440.82-0ubuntu0~0.18.04.2) ...
Removing libnvidia-encode-440:amd64 (440.82-0ubuntu0~0.18.04.2) ...
Removing libnvidia-decode-440:amd64 (440.82-0ubuntu0~0.18.04.2) ...
Removing nvidia-utils-440 (440.82-0ubuntu0~0.18.04.2) ...
Removing libnvidia-fbc1-440:i386 (440.82-0ubuntu0~0.18.04.2) ...
Removing libnvidia-fbc1-440:amd64 (440.82-0ubuntu0~0.18.04.2) ...
Removing libnvidia-ifr1-440:amd64 (440.82-0ubuntu0~0.18.04.2) ...
Removing libnvidia-gl-440:amd64 (440.82-0ubuntu0~0.18.04.2) ...
Removing nvidia-compute-utils-440 (440.82-0ubuntu0~0.18.04.2) ...
Removing nvidia-dkms-440 (440.82-0ubuntu0~0.18.04.2) ...
Removing all DKMS Modules
Done.
INFO:Disable nvidia
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/dell_latitude
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/put_your_quirks_here
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/lenovo_thinkpad
update-initramfs: deferring update (trigger activated)
Removing nvidia-kernel-common-440 (440.82-0ubuntu0~0.18.04.2) ...
update-initramfs: deferring update (trigger activated)
Removing nvidia-kernel-source-440 (440.82-0ubuntu0~0.18.04.2) ...
Removing libnvidia-compute-440:amd64 (440.82-0ubuntu0~0.18.04.2) ...
Selecting previously unselected package cuda-license-10-1.
(Reading database ... 294368 files and directories currently installed.)
Preparing to unpack .../00-cuda-license-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-license-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-misc-headers-10-1.
Preparing to unpack .../01-cuda-misc-headers-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-misc-headers-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvcc-10-1.
Preparing to unpack .../02-cuda-nvcc-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvcc-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cuobjdump-10-1.
Preparing to unpack .../03-cuda-cuobjdump-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cuobjdump-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvprune-10-1.
Preparing to unpack .../04-cuda-nvprune-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvprune-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-compiler-10-1.
Preparing to unpack .../05-cuda-compiler-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-compiler-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvdisasm-10-1.
Preparing to unpack .../06-cuda-nvdisasm-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvdisasm-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-gdb-10-1.
Preparing to unpack .../07-cuda-gdb-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-gdb-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvprof-10-1.
Preparing to unpack .../08-cuda-nvprof-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvprof-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-sanitizer-api-10-1.
Preparing to unpack .../09-cuda-sanitizer-api-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-sanitizer-api-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-memcheck-10-1.
Preparing to unpack .../10-cuda-memcheck-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-memcheck-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cudart-10-1.
Preparing to unpack .../11-cuda-cudart-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cudart-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-driver-dev-10-1.
Preparing to unpack .../12-cuda-driver-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-driver-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cudart-dev-10-1.
Preparing to unpack .../13-cuda-cudart-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cudart-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cupti-10-1.
Preparing to unpack .../14-cuda-cupti-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cupti-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-gpu-library-advisor-10-1.
Preparing to unpack .../15-cuda-gpu-library-advisor-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-gpu-library-advisor-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvtx-10-1.
Preparing to unpack .../16-cuda-nvtx-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvtx-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-command-line-tools-10-1.
Preparing to unpack .../17-cuda-command-line-tools-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-command-line-tools-10-1 (10.1.243-1) ...
Selecting previously unselected package openjdk-11-jre-headless:amd64.
Preparing to unpack .../18-openjdk-11-jre-headless_11.0.7+10-2ubuntu2~18.04_amd64.deb ...
Unpacking openjdk-11-jre-headless:amd64 (11.0.7+10-2ubuntu2~18.04) ...
Selecting previously unselected package default-jre-headless.
Preparing to unpack .../19-default-jre-headless_2%3a1.11-68ubuntu1~18.04.1_amd64.deb ...
Unpacking default-jre-headless (2:1.11-68ubuntu1~18.04.1) ...
Selecting previously unselected package openjdk-11-jre:amd64.
Preparing to unpack .../20-openjdk-11-jre_11.0.7+10-2ubuntu2~18.04_amd64.deb ...
Unpacking openjdk-11-jre:amd64 (11.0.7+10-2ubuntu2~18.04) ...
Selecting previously unselected package default-jre.
Preparing to unpack .../21-default-jre_2%3a1.11-68ubuntu1~18.04.1_amd64.deb ...
Unpacking default-jre (2:1.11-68ubuntu1~18.04.1) ...
Selecting previously unselected package cuda-nsight-10-1.
Preparing to unpack .../22-cuda-nsight-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nsight-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvvp-10-1.
Preparing to unpack .../23-cuda-nvvp-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvvp-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvrtc-10-1.
Preparing to unpack .../24-cuda-nvrtc-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvrtc-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvrtc-dev-10-1.
Preparing to unpack .../25-cuda-nvrtc-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvrtc-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cusolver-10-1.
Preparing to unpack .../26-cuda-cusolver-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cusolver-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cusolver-dev-10-1.
Preparing to unpack .../27-cuda-cusolver-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cusolver-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-license-10-2.
Preparing to unpack .../28-cuda-license-10-2_10.2.89-1_amd64.deb ...
Unpacking cuda-license-10-2 (10.2.89-1) ...
Selecting previously unselected package libcublas10.
Preparing to unpack .../29-libcublas10_10.2.2.89-1_amd64.deb ...
Unpacking libcublas10 (10.2.2.89-1) ...
Selecting previously unselected package libcublas-dev.
Preparing to unpack .../30-libcublas-dev_10.2.2.89-1_amd64.deb ...
Unpacking libcublas-dev (10.2.2.89-1) ...
Selecting previously unselected package cuda-cufft-10-1.
Preparing to unpack .../31-cuda-cufft-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cufft-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cufft-dev-10-1.
Preparing to unpack .../32-cuda-cufft-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cufft-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-curand-10-1.
Preparing to unpack .../33-cuda-curand-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-curand-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-curand-dev-10-1.
Preparing to unpack .../34-cuda-curand-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-curand-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cusparse-10-1.
Preparing to unpack .../35-cuda-cusparse-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cusparse-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-cusparse-dev-10-1.
Preparing to unpack .../36-cuda-cusparse-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-cusparse-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-npp-10-1.
Preparing to unpack .../37-cuda-npp-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-npp-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-npp-dev-10-1.
Preparing to unpack .../38-cuda-npp-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-npp-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvml-dev-10-1.
Preparing to unpack .../39-cuda-nvml-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvml-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvjpeg-10-1.
Preparing to unpack .../40-cuda-nvjpeg-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvjpeg-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvjpeg-dev-10-1.
Preparing to unpack .../41-cuda-nvjpeg-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvjpeg-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package nsight-compute-2019.5.0.
Preparing to unpack .../42-nsight-compute-2019.5.0_2019.5.0.14-1_amd64.deb ...
Unpacking nsight-compute-2019.5.0 (2019.5.0.14-1) ...
Selecting previously unselected package cuda-nsight-compute-10-1.
Preparing to unpack .../43-cuda-nsight-compute-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nsight-compute-10-1 (10.1.243-1) ...
Selecting previously unselected package nsight-systems-2019.5.2.
Preparing to unpack .../44-nsight-systems-2019.5.2_2019.5.2.16-b54ef97_amd64.deb ...
Unpacking nsight-systems-2019.5.2 (2019.5.2.16-b54ef97) ...
Selecting previously unselected package cuda-nsight-systems-10-1.
Preparing to unpack .../45-cuda-nsight-systems-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nsight-systems-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvgraph-10-1.
Preparing to unpack .../46-cuda-nvgraph-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvgraph-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-nvgraph-dev-10-1.
Preparing to unpack .../47-cuda-nvgraph-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-nvgraph-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-visual-tools-10-1.
Preparing to unpack .../48-cuda-visual-tools-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-visual-tools-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-tools-10-1.
Preparing to unpack .../49-cuda-tools-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-tools-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-samples-10-1.
Preparing to unpack .../50-cuda-samples-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-samples-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-documentation-10-1.
Preparing to unpack .../51-cuda-documentation-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-documentation-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-libraries-dev-10-1.
Preparing to unpack .../52-cuda-libraries-dev-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-libraries-dev-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-toolkit-10-1.
Preparing to unpack .../53-cuda-toolkit-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-toolkit-10-1 (10.1.243-1) ...
Selecting previously unselected package libnvidia-common-450.
Preparing to unpack .../54-libnvidia-common-450_450.36.06-0ubuntu1_all.deb ...
Checking for existing driver runfile install
/var/lib/dpkg/tmp.ci/preinst: 6: /var/lib/dpkg/tmp.ci/preinst: [[: not found
Unpacking libnvidia-common-450 (450.36.06-0ubuntu1) ...
Preparing to unpack .../55-libnvidia-compute-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking libnvidia-compute-450:amd64 (450.36.06-0ubuntu1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-fjAi3S/55-libnvidia-compute-450_450.36.06-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so', which is also in package libnvidia-extra-440:amd64 440.82-0ubuntu0~0.18.04.2
Selecting previously unselected package libnvidia-decode-450:amd64.
Preparing to unpack .../56-libnvidia-decode-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking libnvidia-decode-450:amd64 (450.36.06-0ubuntu1) ...
Selecting previously unselected package libnvidia-encode-450:amd64.
Preparing to unpack .../57-libnvidia-encode-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking libnvidia-encode-450:amd64 (450.36.06-0ubuntu1) ...
Selecting previously unselected package libnvidia-fbc1-450:amd64.
Preparing to unpack .../58-libnvidia-fbc1-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking libnvidia-fbc1-450:amd64 (450.36.06-0ubuntu1) ...
Selecting previously unselected package libnvidia-gl-450:amd64.
Preparing to unpack .../59-libnvidia-gl-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking libnvidia-gl-450:amd64 (450.36.06-0ubuntu1) ...
Selecting previously unselected package libnvidia-ifr1-450:amd64.
Preparing to unpack .../60-libnvidia-ifr1-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking libnvidia-ifr1-450:amd64 (450.36.06-0ubuntu1) ...
Selecting previously unselected package nvidia-compute-utils-450.
Preparing to unpack .../61-nvidia-compute-utils-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-compute-utils-450 (450.36.06-0ubuntu1) ...
Selecting previously unselected package nvidia-kernel-source-450.
Preparing to unpack .../62-nvidia-kernel-source-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-kernel-source-450 (450.36.06-0ubuntu1) ...
Selecting previously unselected package nvidia-kernel-common-450.
Preparing to unpack .../63-nvidia-kernel-common-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-kernel-common-450 (450.36.06-0ubuntu1) ...
Selecting previously unselected package nvidia-dkms-450.
Preparing to unpack .../64-nvidia-dkms-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-dkms-450 (450.36.06-0ubuntu1) ...
Selecting previously unselected package nvidia-utils-450.
Preparing to unpack .../65-nvidia-utils-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-utils-450 (450.36.06-0ubuntu1) ...
Selecting previously unselected package libnvidia-cfg1-450:amd64.
Preparing to unpack .../66-libnvidia-cfg1-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking libnvidia-cfg1-450:amd64 (450.36.06-0ubuntu1) ...
Selecting previously unselected package xserver-xorg-video-nvidia-450.
Preparing to unpack .../67-xserver-xorg-video-nvidia-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking xserver-xorg-video-nvidia-450 (450.36.06-0ubuntu1) ...
Selecting previously unselected package nvidia-driver-450.
Preparing to unpack .../68-nvidia-driver-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-driver-450 (450.36.06-0ubuntu1) ...
Selecting previously unselected package nvidia-modprobe.
Preparing to unpack .../69-nvidia-modprobe_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-modprobe (450.36.06-0ubuntu1) ...
Selecting previously unselected package nvidia-settings.
Preparing to unpack .../70-nvidia-settings_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-settings (450.36.06-0ubuntu1) ...
Selecting previously unselected package cuda-drivers-450.
Preparing to unpack .../71-cuda-drivers-450_450.36.06-1_amd64.deb ...
Unpacking cuda-drivers-450 (450.36.06-1) ...
Selecting previously unselected package cuda-drivers.
Preparing to unpack .../72-cuda-drivers_450.36.06-1_amd64.deb ...
Unpacking cuda-drivers (450.36.06-1) ...
Selecting previously unselected package cuda-libraries-10-1.
Preparing to unpack .../73-cuda-libraries-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-libraries-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-runtime-10-1.
Preparing to unpack .../74-cuda-runtime-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-runtime-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-demo-suite-10-1.
Preparing to unpack .../75-cuda-demo-suite-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-demo-suite-10-1 (10.1.243-1) ...
Selecting previously unselected package cuda-10-1.
Preparing to unpack .../76-cuda-10-1_10.1.243-1_amd64.deb ...
Unpacking cuda-10-1 (10.1.243-1) ...
Selecting previously unselected package libcudnn7.
Preparing to unpack .../77-libcudnn7_7.6.4.38-1+cuda10.1_amd64.deb ...
Unpacking libcudnn7 (7.6.4.38-1+cuda10.1) ...
Selecting previously unselected package libcudnn7-dev.
Preparing to unpack .../78-libcudnn7-dev_7.6.4.38-1+cuda10.1_amd64.deb ...
Unpacking libcudnn7-dev (7.6.4.38-1+cuda10.1) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-fjAi3S/55-libnvidia-compute-450_450.36.06-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by dhiegomaga** [comment]
By the way, following the tutorial will leave the packages in a broken state, that's quite hard to fix. `apt --fix-broken install`will give something like: 

```ssh
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
because it can't overwrite `libnvidia-extra-440`, so you need to [force install it](https://askubuntu.com/questions/176121/dpkg-error-trying-to-overwrite-file-which-is-also-in). 

The issue is because the tutorial installs cuda driver version 430, but the latest version is 450, so it's overwritten and it fails.

**Comment by ChenFengYe** [comment]
@dhiegomaga  Hi, quite same issues. I am installing CUDA 11.0 on ubuntu 18.04

> $ apt-get -f install 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  nvidia-compute-utils-450 nvidia-utils-450
The following NEW packages will be installed:
  nvidia-compute-utils-450 nvidia-utils-450
0 upgraded, 2 newly installed, 0 to remove and 106 not upgraded.
251 not fully installed or removed.
Need to get 0 B/489 kB of archives.
After this operation, 1570 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 file:/var/cuda-repo-ubuntu1804-11-0-local  nvidia-compute-utils-450 450.36.06-0ubuntu1 [123 kB]
Get:2 file:/var/cuda-repo-ubuntu1804-11-0-local  nvidia-utils-450 450.36.06-0ubuntu1 [366 kB]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line
 76, <> line 2.)debconf: falling back to frontend: Readline
(Reading database ... 89397 files and directories currently installed.)
Preparing to unpack .../nvidia-compute-utils-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-compute-utils-450 (450.36.06-0ubuntu1) ...
dpkg: error processing archive /var/cuda-repo-ubuntu1804-11-0-local/./nvidia-compute-utils-450_450.36.06-0ubuntu1_amd64.deb (--unpack):
 unable to make backup link of './usr/bin/nvidia-cuda-mps-control' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../nvidia-utils-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-utils-450 (450.36.06-0ubuntu1) ...
dpkg: error processing archive /var/cuda-repo-ubuntu1804-11-0-local/./nvidia-utils-450_450.36.06-0ubuntu1_amd64.deb (--unpack):
 unable to make backup link of './usr/bin/nvidia-debugdump' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cuda-repo-ubuntu1804-11-0-local/./nvidia-compute-utils-450_450.36.06-0ubuntu1_amd64.deb
 /var/cuda-repo-ubuntu1804-11-0-local/./nvidia-utils-450_450.36.06-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Although I run apt-get -f install, still get this error. Do you have any advice to fix this conflicts?

**Comment by ChenFengYe** [comment]
With a force-overwrite option like
`apt-get -o Dpkg::Options::="--force-overwrite" install -f`

Error still followed:

> $ apt-get -o Dpkg::Options::="--force-overwrite" install --fix-broken
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  adwaita-icon-theme at-spi2-core ...(mannually omit) ... xserver-common xserver-xorg-core-hwe-18.04 xserver-xorg-video-nvidia-450 xtrans-dev
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  nvidia-compute-utils-450 nvidia-utils-450
The following NEW packages will be installed:
  nvidia-compute-utils-450 nvidia-utils-450
0 upgraded, 2 newly installed, 0 to remove and 106 not upgraded.
250 not fully installed or removed.
Need to get 0 B/489 kB of archives.
After this operation, 1570 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 file:/var/cuda-repo-ubuntu1804-11-0-local  nvidia-compute-utils-450 450.36.06-0ubuntu1 [123 kB]
Get:2 file:/var/cuda-repo-ubuntu1804-11-0-local  nvidia-utils-450 450.36.06-0ubuntu1 [366 kB]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line
 76, <> line 2.)debconf: falling back to frontend: Readline
(Reading database ... 89395 files and directories currently installed.)
Preparing to unpack .../nvidia-compute-utils-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-compute-utils-450 (450.36.06-0ubuntu1) ...
dpkg: error processing archive /var/cuda-repo-ubuntu1804-11-0-local/./nvidia-compute-utils-450_450.36.06-0ubuntu1_amd64.deb (--unpack):
 unable to make backup link of './usr/bin/nvidia-cuda-mps-control' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../nvidia-utils-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking nvidia-utils-450 (450.36.06-0ubuntu1) ...
dpkg: error processing archive /var/cuda-repo-ubuntu1804-11-0-local/./nvidia-utils-450_450.36.06-0ubuntu1_amd64.deb (--unpack):
 unable to make backup link of './usr/bin/nvidia-debugdump' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cuda-repo-ubuntu1804-11-0-local/./nvidia-compute-utils-450_450.36.06-0ubuntu1_amd64.deb
 /var/cuda-repo-ubuntu1804-11-0-local/./nvidia-utils-450_450.36.06-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ecpoppenheimer** [comment]
Also been having this problem.  Spent all day, and was on the verge of reinstalling my OS because this broke my package system so badly.

I don't really know what I am doing... but the following command was at least enough to fix the package manager so that I don't have to reinstall the OS.

sudo apt-get -o Dpkg::Options::="--force-overwrite" install libnvidia-compute-450

**Comment by ecpoppenheimer** [comment]
I did manage to get TF to recognize my GPU!  Nvidia driver is version 450.

**Comment by Lauler** [comment]
This installation process just nuked my Nvidia drivers too.

**Comment by Lauler** [comment]
The issue seems to be that the command

`sudo apt-get install --no-install-recommends nvidia-driver-430`

no longer installs a nvidia 430 driver, but defaults to installing nvidia-440 on ubuntu.

nvidia-430 drivers are a "transitional package", so it is not actually possible to install 430 anymore through apt-get nor from ppa. 
https://packages.ubuntu.com/bionic-updates/nvidia-driver-430
https://askubuntu.com/questions/1240294/cannot-downgrade-nvidia-driver-440-to-nvidia-driver-430-on-ubuntu-18-04

Does the nvidia 440 driver result in a mismatch with cuda 10.1?

**Comment by gunan** [comment]
@nluehr what would be the instructions to install cuda/cudnn?
Who would be the best person to ask this?

**Comment by alexantoinefortin** [comment]
If it helps people undoing their cuda install, I found 2 useful commands by browsing stackoverflow:

`dpkg --configure -a`: this command (ran with `sudo`) identified errors with a select few of my pacakges. Namely:
```
Errors were encountered while processing:
 libnvidia-ifr1-450:amd64
 cuda-drivers-450
 nvidia-driver-450
 cuda-drivers
 cuda-runtime-11-0
 cuda-11-0
 cuda-demo-suite-11-0
 cuda
```

After that, I ran this command to purge the packages:
`apt purge cuda cuda-demo-suite-11-0 cuda-11-0 cuda-runtime-11-0 cuda-drivers nvidia-driver-450 cuda-drivers-450 libnvidia-ifr1-450:amd64`

Finally, I could `apt autoremove` and my computer appears to be completely free of nvidia drivers now.

My next step is to go back to the nvidia website and to follow their instructions for installing the most recent version of `cuda` ...

**Comment by nluehr** [comment]
The users appear to be doing the correct things. There may be a bug in nvidia's driver packaging. I'm checking with the driver team.

**Comment by ChenFengYe** [comment]
To help someone new come, I find this problem may be related to the conflict between cuda and GPU Driver. In my case, I have no right to reinstall GPU driver. At first, I try to install cuda 11, but failed. Finally, I reinstall cuda 10.2 (this version can be correctly installed before), but it get broken again.

Some logs:
Results for `nvidia-smi`
> +---------------------------------------------------------------------------+
| NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+===============|
|   0  GeForce RTX 2080    Off  | 00000000:02:00.0 Off |                  N/A |
| 17%   38C    P0    37W / 215W |      0MiB /  7952MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

Results for `apt --fix-broken install`  (install cuda 10.2)

> ... 
Get:1 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1604/x86_64  nvidia-440 440.64.00-0ubuntu1 [131 MB]
Fetched 131 MB in 43s (3015 kB/s)                                                                                                                    
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line
 76, <> line 1.)debconf: falling back to frontend: Readline
(Reading database ... 90252 files and directories currently installed.)
Preparing to unpack .../nvidia-440_440.64.00-0ubuntu1_amd64.deb ...
Unpacking nvidia-440 (440.64.00-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/nvidia-440_440.64.00-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0', which is also in package libglx-mesa0:amd64 19.2.8-0ubuntu0~18.04.3
Errors were encountered while processing:
 /var/cache/apt/archives/nvidia-440_440.64.00-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
(base)

**Comment by ifarady** [comment]
anyone solve this problem?

**Comment by ecpoppenheimer** [comment]
If I recall correctly you need to install the 450 nvidia driver.  Which essentially just means replacing the number '430' with '450' in the install instructions.

Unless you broke your package manager, in which case you have to force overwrite the broken library.  As per my comment above, the following command fixed things for me:

sudo apt-get -o Dpkg::Options::="--force-overwrite" install libnvidia-compute-450

**Comment by jsgoller1** [comment]
Having this issue as well; trying to install Tensorflow with GPU support from [the documentation](https://www.tensorflow.org/install/gpu) on Ubuntu 20.04 LTS, ran into the same issue. I can no longer run `nvidia-smi` after running the `apt-get install` command for `# Install development and runtime libraries (~4GB)`.

**Comment by jsgoller1** [comment]
I eventually got this worked out for Ubuntu 20.04 LTS with an NVIDIA GTX 1070. This is a hack, and hopefully the packages are fixed correctly. Here's what I did, YMMV. 

**Problem**
I ran the documented instructions [on the Tensorflow site](https://www.tensorflow.org/install/gpu) and they left me with a bunch of broken packages and now `nvidia-smi` doesn't work.

**Solution**
Find the path of the package that is causing the issue and force in stall it with `dpkg`. I don't have the exact command I ran, but I had the same error message about a .dpkg file `trying to overwrite ...  which is also in package ...`. Going on @ChenFengYe's example above, we see:
```
Unpacking nvidia-440 (440.64.00-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/nvidia-440_440.64.00-0ubuntu1_amd64.deb (--unpack):
trying to overwrite '/usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0', which is also in package libglx-mesa0:amd64 19.2.8-0ubuntu0~18.04.3
Errors were encountered while processing:
/var/cache/apt/archives/nvidia-440_440.64.00-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
so the command to run would be:
```
sudo dpkg -i --force-all /var/cache/apt/archives/nvidia-440_440.64.00-0ubuntu1_amd64.deb
```
I then rebooted afterwords, and confirmed that my specific issue (trying to make sure TensorFlow could see my GPUs) was fixed:
```
>>> import tensorflow as tf
>>> print("GPUs Available: ", tf.config.experimental.list_physical_devices('GPU'))
GPUs Available:  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```
-----------
Here's a separate issue some of you may be having:

**Problem**
I ran the instructions from TensorFlow's setup page and now my machine is all screwed up with broken packages and that little annoying red symbol in the status bar won't go away. Also, I am having trouble installing other packages now. I hate Linux. Maybe I should quit my job.

**Solution**
No need to change career tracks. Just uninstall the broken packages. There is probably a nifty programmatic way to do this, but I just did it by hand. Run `sudo apt-get remove -f` to see which packages are broken, then add them to the list and run `sudo apt-get remove -f <package-name1> <package-name2> ...` until you are actually able to uninstall everything. 

**MAKE SURE YOU HAVE A GRAPHICS DRIVER PACKAGE INSTALLED BEFORE YOU REBOOT UNLESS YOU WANT TO SPEND SEVERAL HOURS SEARCHING STACK OVERFLOW FROM YOUR PHONE AND WISHING FOR THE SWEET EMBRACE OF DEATH**. This should do it:
```
sudo apt-get install nvidia-driver-450
```

**Comment by tanyapohn** [comment]
This error happens to me as well. After I forced install `libnvidia-compute-450`, my `nvidia-smi` is now changed like this which its driver supposes to be `440.83` isn't it?
![Screenshot from 2020-06-17 12-24-41](https://user-images.githubusercontent.com/51353899/84858581-ab5f8100-b095-11ea-80f5-a9cd66f46f00.png)

**Comment by jsgoller1** [comment]
@tanyapohn - `450` is the latest version of `nvidia-driver-*` available through `apt` (though I see `440` on the [nvidia website for drivers](https://www.geforce.com/drivers)). Are you having other `nvidia-smi` issues, or is this just something you noticed?

**Comment by tanyapohn** [comment]
@jsgoller1 Hi, 
Thank you for replying my comment.

It's something that I noticed after I encountered the error of:
```
Errors were encountered while processing:
 /tmp/apt-dpkg-install-fjAi3S/55-libnvidia-compute-450_450.36.06-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
``` 
And I fixed it by:
```
sudo apt-get -o Dpkg::Options::="--force-overwrite" install libnvidia-compute-450
```
Then, my `nvidia-smi` has changed from `440.83` to `450`.

Is that weird? However, training a model seems normal right now.

**Comment by gunan** [comment]
440 or 450 are just nvidia driver versions. CUDA versions usually have a minimum supported driver, anything newer will just work.

But again, I will defer to nvidia for the correct instructions.

**Comment by GuidoBartoli** [comment]
> @dhiegomaga Hi, quite same issues. I am installing CUDA 11.0 on ubuntu 18.04

Same problem here, installing CUDA 10.1 on Ubuntu 20.04 (Linux Mint 20). It corrupted my nvidia drivers, too... :(

**Comment by michaelgallacher** [comment]
+1
 Following the TensorFlow GPU instructions on a clean Ubuntu 18.04 fails with library conflicts. I thought it odd that I installed the '430' driver and yet most of the libs installed reported 440.  Running the following resolved it for me as well.

`sudo apt-get -o Dpkg::Options::="--force-overwrite" install libnvidia-compute-450`

**Comment by clockzhong** [comment]
@michaelgallacher ,thanks for your comments, your solution could help temprarily workaround this serious mistake in tensorflow's installation.

**Comment by arnabGudu** [comment]
> Also been having this problem. Spent all day, and was on the verge of reinstalling my OS because this broke my package system so badly.
> 
> I don't really know what I am doing... but the following command was at least enough to fix the package manager so that I don't have to reinstall the OS.
> 
> sudo apt-get -o Dpkg::Options::="--force-overwrite" install libnvidia-compute-450

the last command works

**Comment by neilteng** [comment]
facing the exact same issue:

```
sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  cuda-command-line-tools-10-1 cuda-compiler-10-1 cuda-cudart-10-1 cuda-cudart-dev-10-1 cuda-cufft-10-1 cuda-cufft-dev-10-1 cuda-cuobjdump-10-1 cuda-cupti-10-1 cuda-curand-10-1 cuda-curand-dev-10-1
  cuda-cusolver-10-1 cuda-cusolver-dev-10-1 cuda-cusparse-10-1 cuda-cusparse-dev-10-1 cuda-demo-suite-10-1 cuda-documentation-10-1 cuda-driver-dev-10-1 cuda-drivers cuda-drivers-450 cuda-gdb-10-1
  cuda-gpu-library-advisor-10-1 cuda-libraries-10-1 cuda-libraries-dev-10-1 cuda-license-10-1 cuda-license-10-2 cuda-memcheck-10-1 cuda-misc-headers-10-1 cuda-npp-10-1 cuda-npp-dev-10-1 cuda-nsight-10-1
  cuda-nsight-compute-10-1 cuda-nsight-systems-10-1 cuda-nvcc-10-1 cuda-nvdisasm-10-1 cuda-nvgraph-10-1 cuda-nvgraph-dev-10-1 cuda-nvjpeg-10-1 cuda-nvjpeg-dev-10-1 cuda-nvml-dev-10-1 cuda-nvprof-10-1
  cuda-nvprune-10-1 cuda-nvrtc-10-1 cuda-nvrtc-dev-10-1 cuda-nvtx-10-1 cuda-nvvp-10-1 cuda-runtime-10-1 cuda-samples-10-1 cuda-sanitizer-api-10-1 cuda-toolkit-10-1 cuda-tools-10-1 cuda-visual-tools-10-1
  dkms freeglut3 freeglut3-dev libatomic1:i386 libbsd0:i386 libcublas-dev libcublas10 libdrm-amdgpu1:i386 libdrm-dev libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386
  libedit2:i386 libelf1:i386 libexpat1:i386 libffi6:i386 libgl1:i386 libgl1-mesa-dev libgl1-mesa-dri:i386 libglapi-mesa:i386 libgles1 libglu1-mesa-dev libglvnd-core-dev libglvnd-dev libglvnd0:i386
  libglx-mesa0:i386 libglx0:i386 libice-dev libllvm9:i386 libnvidia-cfg1-450 libnvidia-common-440 libnvidia-common-450 libnvidia-compute-450 libnvidia-decode-450 libnvidia-encode-450 libnvidia-extra-440
  libnvidia-fbc1-450 libnvidia-gl-450 libnvidia-ifr1-450 libopengl0 libpciaccess0:i386 libpthread-stubs0-dev libsensors4:i386 libsm-dev libstdc++6:i386 libx11-6:i386 libx11-dev libx11-xcb-dev
  libx11-xcb1:i386 libxau-dev libxau6:i386 libxcb-dri2-0:i386 libxcb-dri2-0-dev libxcb-dri3-0:i386 libxcb-dri3-dev libxcb-glx0:i386 libxcb-glx0-dev libxcb-present-dev libxcb-present0:i386
  libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-sync1:i386 libxcb-xfixes0-dev libxcb1:i386 libxcb1-dev libxdamage-dev libxdamage1:i386 libxdmcp-dev libxdmcp6:i386
  libxext-dev libxext6:i386 libxfixes-dev libxfixes3:i386 libxi-dev libxmu-dev libxmu-headers libxnvctrl0 libxshmfence-dev libxshmfence1:i386 libxt-dev libxxf86vm-dev libxxf86vm1:i386 mesa-common-dev
  nsight-compute-2020.1.0 nsight-systems-2019.5.2 nvidia-compute-utils-450 nvidia-dkms-450 nvidia-driver-450 nvidia-kernel-common-450 nvidia-kernel-source-450 nvidia-modprobe nvidia-prime
  nvidia-settings nvidia-utils-450 pkg-config screen-resolution-extra x11proto-core-dev x11proto-damage-dev x11proto-dev x11proto-fixes-dev x11proto-input-dev x11proto-xext-dev x11proto-xf86vidmode-dev
  xorg-sgml-doctools xserver-xorg-video-nvidia-450 xtrans-dev
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libnvidia-compute-450
The following NEW packages will be installed:
  libnvidia-compute-450
0 upgraded, 1 newly installed, 0 to remove and 201 not upgraded.
124 not fully installed or removed.
Need to get 0 B/21.8 MB of archives.
After this operation, 115 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 201507 files and directories currently installed.)
Preparing to unpack .../libnvidia-compute-450_450.36.06-0ubuntu1_amd64.deb ...
Unpacking libnvidia-compute-450:amd64 (450.36.06-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/libnvidia-compute-450_450.36.06-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so', which is also in package libnvidia-extra-440:amd64 440.100-0ubuntu0.18.04.1
Errors were encountered while processing:
 /var/cache/apt/archives/libnvidia-compute-450_450.36.06-0ubuntu1_amd64.deb

```

**Comment by gunan** [comment]
@nluehr, are there any updates from the nvidia driver team?

**Comment by nluehr** [comment]
The 450.51.05 driver posted earlier this week with the CUDA 11 [toolkit](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64) resolves this issue. It is also included in the cuda developer deb repos, so a one line fix in the instructions will be sufficient.

Opened [PR 1616](https://github.com/tensorflow/docs/pull/1616) with fix.

**Comment by amahendrakar** [comment]
@dhiegomaga,
Is this still an issue?

The documentation has been updated for TensorFlow v2.4.1 and I did not face any errors on running the commands.

Please feel free to close the issue if resolved. Thanks!
