### ISSUE TITLE
Could not load dynamic library 'libcudnn.so.7'

### ISSUE THREAD

**Issue by paxth** [tensorflow/tensorflow#40349]
**System information**
- OS Platform and Distribution: Ubuntu 20.04 LTS
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.2.0
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 8.4.0
- CUDA/cuDNN version: 10.1

When I run the program like:

`import tensorflow as tf`

it shows no problem but when i do:

`import tensorflow as tf

rank_0_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_0_tensor)`

i get the error showing:
![Screenshot from 2020-06-10 15-10-32](https://user-images.githubusercontent.com/63995679/84252815-ba41b300-ab2c-11ea-9dac-bd225364f492.png)

Can anybody help?

**Comment by paxth** [comment]
> @paxth,
> The logs you are seeing on the console are not errors but information and warning messages. You can see the output of your script in the last line of the messages.
> 
> If you want to disable these logs try changing the log level using the below code
> 
> ```
> import os
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
> import tensorflow as tf
> ```
> 
> Thanks!

Okay, thanks! It worked but is there a way to permanently get rid of the warnings instead of doing the `import os` everytime?

**Comment by amahendrakar** [comment]
@paxth,
Sorry for the delayed response. Could you please try changing the log level in Python itself and check if it works. 

Please feel free to close the issue if resolved. Thanks!
