### ISSUE TITLE
Installation Issue:  Couldn't open CUDA library libcuda.so.1.

### ISSUE THREAD

**Issue by MahdiNazemi** [tensorflow/tensorflow#4078]
In the step where I have to run
`bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu`
I get the following messages:
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH:...
...
...
...
failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
...
...
...
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
...
...
...
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.

### Environment info
Operating System: Debian 8

Installed version of CUDA and cuDNN: CUDA 7.0, cuDNN 4.0.7
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
/usr/local/cuda/lib/libcudadevrt.a
/usr/local/cuda/lib/libcudart.so -> libcudart.so.7.0
/usr/local/cuda/lib/libcudart.so.7.0 -> libcudart.so.7.0.28
/usr/local/cuda/lib/libcudart.so.7.0.28
/usr/local/cuda/lib/libcudart_static.a

1. The commit hash (`git rev-parse HEAD`) 
`554ddd9ad2d4abad5a9a31f2d245f0b1012f0d10`

2. The output of `bazel version`
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0

P.S. I have two GPUs installed on my server. One is used for GUI (AMD) and the other is used for computation (NVIDIA).
Should I do anything to make sure the second GPU is being used?

**Comment by manjunaths** [comment]
Did you check on your system if libcuda.so.* does exist ? On my system it is in /usr/local/nvidia/lib64 and another of my system it is in /usr/lib/.

If it does exist, then set the LD_LIBRARY_PATH env variable to point to the correct path. If it doesn't you might've to install it on your system.

Cuda should not recognize the AMD device as a valid cuda target, so you should run on the right GPU.

**Comment by MahdiNazemi** [comment]
I have libcuda.so.7, but not libcuda.so.1

Should I reinstall cuda drivers?

**Comment by manjunaths** [comment]
You could just ln -s libcuda.so.7.* libcuda.so.1 and see if it works.

**Comment by MahdiNazemi** [comment]
I tried this solution. Now I get the following messages:

`E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUresult(-1)
...
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  340.96  Sun Nov  8 22:33:28 PST 2015
`

**Comment by chocolate9624** [comment]
@MahdiNazemi  Do you solve this problem? I also face the same situation. Thanks!

**Comment by MahdiNazemi** [comment]
@chocolate9624 I still have this issue. Please let me know if you find a solution.

**Comment by MahdiNazemi** [comment]
@chocolate9624 Could you find any solutions to the problem? I'm still looking for a solution...

**Comment by martinwicke** [comment]
Your driver (kernel module) is really old: 340.96. Can you upgrade to a more recent driver/cuda?

**Comment by MahdiNazemi** [comment]
I updated to the latest version on jessie-backports which is 352.79, but it didn't solve the issue.

**Comment by chocolate9624** [comment]
@MahdiNazemi  I solved this problem by comparing with other machines.  In /use/lib64 

libcuda.so -> /usr/lib64/libcuda.so.1
libcuda.so.1 -> /usr/lib64/nvidia/libcuda.so.1

libcuda.so.1 should be linked to   /usr/lib64/nvidia/libcuda.so.1

Good luck!

**Comment by MahdiNazemi** [comment]
Thanks a lot @chocolate9624.

Finally, I was able to solve the issue. It looks like none of the drivers that are available on Debian (jessie, jessie-backports, and stretch) can make the GPU work (not my Quadro nor my Tesla). I used the driver that is available on Nvidia's website and it solved the problem.

**Comment by martinwicke** [comment]
That's good to know. Is it an issue with the driver version, or about where they install to?

**Comment by MahdiNazemi** [comment]
I installed 3 different versions, i.e. 340.96, 352.79, and 367.44, but none of them worked. I don't think the problem is with the driver version, but I'm not sure if it's about where they are installed or not.

**Comment by ShiKaiWi** [comment]
Hi, I have solved it by these steps:
1.`sudo apt install nvidia-361-dev`
2.`sudo find /usr/ -name 'libcuda.so.1'` (then you will know path of `libcuda.so.1`)
3.just cp the `libcuda.so.1` to `/usr/local/cuda/lib/` 
__actually the libcuda.so.1 you find is a link, see:__
![image](https://cloud.githubusercontent.com/assets/8605990/19565023/13815d58-9718-11e6-8179-74433464ee0a.png)

**Comment by soichih** [comment]
@ShiKaiWi Which repo does the nvidia-361-dev come from? I am seeing following when I try to install it.

E: Unable to locate package nvidia-361-dev

**Comment by ShiKaiWi** [comment]
@soichih Hi, my os is ubuntu 16.04 so this repo is provided by default. So I suggest you can try to install nvidia-3**-dev (I guess the  version is 352 if you use ubuntu 14.04) and then try to find the `libcuda.so.1`.

**Comment by martinwicke** [comment]
Looks resolved. Thanks all.

**Comment by Yuyang01** [comment]
> Hi, I have solved it by these steps:
> 1.`$ sudo apt install nvidia-361-dev`
> 2.`$ sudo find /usr/ -name 'libcuda.so.1'` (then you will know path of `libcuda.so.1`)
> 3. just copy the `libcuda.so.1` to `/usr/local/cuda/lib/`
> _actually the `libcuda.so.1` you find is a link file, see:_
> ![image](https://cloud.githubusercontent.com/assets/8605990/19565023/13815d58-9718-11e6-8179-74433464ee0a.png)

it works for me

**Comment by movie3105** [comment]
hello sir i make mistake and accidentally delete the libcuda.so.1 like this :
![image](https://user-images.githubusercontent.com/52781140/62705467-ac586880-ba17-11e9-861b-6fc33bc5a625.png)

how can i solve this problem ?

**Comment by wanfuse123** [comment]
Directory of C:\Windows\System32\lxss\lib

09/18/2020  03:53 PM    <DIR>          .
08/30/2020  09:51 AM           124,664 libcuda.so
09/12/2020  08:44 AM           832,936 libd3d12.so
09/12/2020  08:44 AM         5,073,944 libd3d12core.so
09/12/2020  08:44 AM        25,069,816 libdirectml.so
09/12/2020  08:44 AM           878,768 libdxcore.so
08/30/2020  09:51 AM        40,496,936 libnvwgf2umx.so
               6 File(s)     72,477,064 bytes
               1 Dir(s)  643,723,309,056 bytes free

C:\Windows\System32\lxss\lib>mklink libcuda.so.1 libcuda.so
symbolic link created for libcuda.so.1 <<===>> libcuda.so

**Comment by petrovicluka** [comment]
> hello sir i make mistake and accidentally delete the libcuda.so.1 like this :
> ![image](https://user-images.githubusercontent.com/52781140/62705467-ac586880-ba17-11e9-861b-6fc33bc5a625.png)
> 
> how can i solve this problem ?
> or is that red icon mean deleted ? i'm not really s

> hello sir i make mistake and accidentally delete the libcuda.so.1 like this :
> ![image](https://user-images.githubusercontent.com/52781140/62705467-ac586880-ba17-11e9-861b-6fc33bc5a625.png)
> 
> how can i solve this problem ?
> or is that red icon mean deleted ? i'm not really sure

Could you manage to solve that issue? Because my libcudart.so is also in red color .
Thanks in advance!

**Comment by LokiInside** [comment]
where I can find those on Mac ? 
libcuda.so -> ?
libcuda.so.1 ->?
