### ISSUE TITLE
UnknownError:  [_Derived_]  CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#40982]
# System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**:
-   **Python version**:
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
When using `mask_zero=True` in `tf.keras.layers.Embedding` in a GPU environment LSTM layers causes:

```
UnknownError:  [_Derived_]  CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1496): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
	 [[{{node cond_17/then/_0/CudnnRNNV3}}]]
	 [[model/time_distributed_1/lstm/StatefulPartitionedCall]] [Op:__inference_train_function_16505]

Function call stack:
train_function -> train_function -> train_function
```

Full error trace is attached. 

[error_trace.txt.zip](https://github.com/tensorflow/tensorflow/files/4857504/error_trace.txt.zip)

Here's how we defined our network:

```
# Input and embeddings for words
word_in = Input(shape=(max_len, max_len_word,))

# Word level embedding
emb_word = TimeDistributed(
    Embedding(input_dim=(n_words + 2), 
        output_dim=200,
        input_length=max_len_word, 
        weights=[get_embedding_matrix(word_index, 
            embedding_path, embedding_dim)], 
        trainable=False,
        mask_zero=True
	)	
)(word_in)

# Word LSTM to get sent encodings by words
emb_sent = TimeDistributed(LSTM(units=32, return_sequences=False))(emb_word)

main_lstm = Bidirectional(LSTM(units=64, return_sequences=True))(emb_sent)
out = TimeDistributed(Dense(n_tags + 1, activation="softmax"))(main_lstm)

model = Model([word_in], out)
```

A few observations:
- When using a CPU environment, this issue does not show up. 
- When using `mask_zero=False` this issue does not show up but leads to misleading accuracy as obvious. 

### Source code / logs
[Colab Notebook](https://colab.research.google.com/gist/sayakpaul/b18aeca12e36f0f367e19548b81bf6a7/whats_the_news_model_baseline-1.ipynb).

**Comment by Saduf2019** [comment]
@sayakpaul 
Could you please refer to these links and let us know if it helps:
[link](https://stackoverflow.com/questions/58895694/cudnn-status-bad-param-when-trying-to-perform-inference-on-a-lstm-seq2seq-with-m) [link1](https://stackoom.com/question/3z7SY/%E5%B0%9D%E8%AF%95%E5%AF%B9%E5%85%B7%E6%9C%89%E5%B1%8F%E8%94%BD%E8%BE%93%E5%85%A5%E7%9A%84LSTM-Seq-Seq%E8%BF%9B%E8%A1%8C%E6%8E%A8%E7%90%86%E6%97%B6-CUDNN-STATUS-BAD-PARAM) [link2](https://github.com/tensorflow/tensorflow/issues/40750#issuecomment-648906371)  #33148 

I ran the code shared but face different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/db21531d9b70952890839fe424deb0bb/untitled251.ipynb) please provide executable code with all imports and dependencies.

**Comment by sayakpaul** [comment]
@Saduf2019 you probably forgot to run the cells in order. I just ran your gist and I did not get any errors. Here's the Gist: https://colab.research.google.com/gist/sayakpaul/74e1e8c553d6f29d7f59f2534c9bf83b/untitled251.ipynb.

**Comment by sayakpaul** [comment]
@qlzh727 any pointers?

**Comment by qlzh727** [comment]
I have fixed the related issue #33148. Please try your code with latest tf-nightly and see if it works. Thanks.

**Comment by sayakpaul** [comment]
Sure. Will try.

**Comment by qlzh727** [comment]
Assuming no news is good news. Closing this bug for now, and please reopen if you still see the issue.
