### ISSUE TITLE
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path. 

### ISSUE THREAD

**Issue by trevorwelch** [tensorflow/tensorflow#4105]
### Environment info
Operating System:
OS  10.10.5

Installed version of CUDA and cuDNN: 
```
$ ls -l /usr/local/cuda/lib/libcud*
-rwxr-xr-x  1 root           wheel      8280 Apr 13 01:02 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x  1 root           wheel        45 Apr 13 01:03 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudadevrt.a
lrwxr-xr-x  1 root           wheel        50 Apr 13 01:03 /usr/local/cuda/lib/libcudart.7.5.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.7.5.dylib
lrwxr-xr-x  1 root           wheel        46 Apr 13 01:03 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.dylib
lrwxr-xr-x  1 root           wheel        49 Apr 13 01:03 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart_static.a
-rwxr-xr-x@ 1 production204  staff  60108616 Feb  8  2016 /usr/local/cuda/lib/libcudnn.4.dylib
lrwxr-xr-x  1 root           admin        47 Aug 29 18:08 /usr/local/cuda/lib/libcudnn.5.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudnn.5.dylib
lrwxr-xr-x  1 root           admin        45 Aug 29 18:08 /usr/local/cuda/lib/libcudnn.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudnn.dylib
-rw-r--r--@ 1 production204  staff  59311504 Feb  8  2016 /usr/local/cuda/lib/libcudnn_static.a
```

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 
(can't get that far, but i'm using 0.10)
```
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.dylib locally
Segmentation fault: 11

```
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
```
4c49dbebef05442c7e72d6129a30574fcd13f0e1
```
2. The output of `bazel version`
```
$ bazel version
Build label: 0.3.1-homebrew
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Aug 4 09:59:58 2016 (1470304798)
Build timestamp: 1470304798
Build timestamp as int: 1470304798
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
INFO: Elapsed time: 0.076s

```

### What other attempted solutions have you tried?
- Downgrading to cuDNN4, switching between 4 and 5
- Re-installing bazel
- Modifying CROSSTOOL file according to various threads
- Manually linking CUDA libraries during `./configure` to not use symlinked libraries
- Various other hacks over the last week 😭

**Comment by vrv** [comment]
I got this recently too, I was somehow successful by just re-running ./configure and then immediately running bazel build, but I'm not sure what's going on.

**Comment by trevorwelch** [comment]
I just tried de-installing TF completely and then re-running with the same ./configure settings:

```
$ ./configure
Please specify the location of python. [Default is /Library/Frameworks/Python.framework/Versions/2.7/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] y
Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
  /Library/Python/2.7/site-packages
Please input the desired Python library path to use.  Default is [/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages]

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.0
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
INFO: Waiting for response from Bazel server (pid 63884)...
WARNING: /private/var/tmp/_bazel_production204/ed2bbf43bcd665c40f1e3ebaa04f68f6/external/boringssl_git/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_production204/ed2bbf43bcd665c40f1e3ebaa04f68f6/external/boringssl_git/WORKSPACE (@boringssl) does not match the name given in the repository's definition (@boringssl_git); this will cause a build error in future versions.
INFO: All external dependencies fetched successfully.
Configuration finished
```
Then running a simplified build command:

```
$ bazel build -c opt --config=cuda tensorflow/...
```

After a _very_ verbose and lengthy compile attempt, I received this error message (it caused OS X Terminal app to hang permanently as well, so I couldn't copy-paste, had to take a screenshot):

https://www.dropbox.com/s/riu5f4n5aj1opmk/Screenshot%202016-08-30%2016.33.48.png?dl=0

**Comment by Mistobaan** [comment]
Yes if you are developing TF it happens quite often. I think it might be something related with the caching system of bazel. After few hours it resets and I have to re run the configure again.

**Comment by davidzchen** [comment]
+cc @damienmg 

This seems to be a bug in Bazel.

Next time this happens, can you take a look at directory `bazel-tensorflow/external/local_config_cuda/crosstool` and let me know which files are there?

**Comment by trevorwelch** [comment]
@davidzchen thanks for your reply.

This error or some version of it is consistent:

```
$ ls -l
total 32
-rwxr-xr-x  1 production204  wheel   925 Aug 30 14:45 BUILD
-rwxr-xr-x  1 production204  wheel  9068 Aug 30 14:45 CROSSTOOL
drwxr-xr-x  3 production204  wheel   102 Aug 30 14:45 clang

production204@Trevors-MacBook-Pro crosstool $ 
```

**Comment by davidzchen** [comment]
I just saw your screenshot, and that appears to be a different problem than the `no such package '@local_config_cuda//crosstool': BUILD file not found on package path.` error, which seems to be a caching issue.

Do you mean that the `crosstool_wrapper_driver_is_not_gcc` error occurs consistently? Is it causing your Terminal.app to hang every time? If it reproduces consistently, you re-run the command with `--verbose_failures`?

**Comment by trevorwelch** [comment]
I meant that my TF builds seem to fail related to crosstool consistently, probably my naivete on the specifics for me to think that `crosstool_wrapper_driver_is_not_gcc` and `CROSSTOOL` could be the same problem!

**Comment by davidzchen** [comment]
No problem. The naming could be a bit confusing. The `@local_config_cuda//crosstool` error may be an issue with Bazel's caching; I have ran into it a couple of times myself, and it usually goes away after I re-run `./configure`.

Were you able to reproduce the `crosstool_wrapper_driver_is_not_gcc` error again? Looking at your screenshot, it looks like the `headerpad_max_install_names` flag is not spelled correctly for some reason since it is complaining about `eaderpad_max_install_names`.

**Comment by Dapid** [comment]
I am getting the same missing crosstool on Linux. The strange thing is that there isn't even a bazel-tensorflow directory:
```
[david@SQUIDS tensorflow]$ ls
ACKNOWLEDGMENTS  avro.BUILD   boringssl.BUILD  bzip2.BUILD  CONTRIBUTING.md  farmhash.BUILD  gmock.BUILD  ISSUE_TEMPLATE.md  jsoncpp.BUILD  nanopb.BUILD  png.BUILD      README.md   six.BUILD   third_party  util       zlib.BUILD
AUTHORS          boost.BUILD  bower.BUILD      configure    eigen.BUILD      gif.BUILD       grpc.BUILD   jpeg.BUILD         LICENSE        navbar.md     _python_build  RELEASE.md  tensorflow  tools        WORKSPACE
```

bazel is 0.3.1, and I have ran ./configure four times now.

**Comment by trevorwelch** [comment]
I do see that `eaderpad_max_install_names` reference in the screenshot above, however, after searching through all the files and folders in my TF directory I don't see that text anywhere, only `headerpad_max_install_names`. I don't know why the `h` would be getting clipped off.

**Comment by davidzchen** [comment]
@Dapid That is interesting. How did you run the `./configure` script? Can you paste the output

@damienmg Is there currently a way to inspect the contents of `/external` after running `bazel fetch` but before the Bazel output directories get symlinked?

@trevorwelch FWIW, most of the noise in the output are compiler warnings. The `dyld: Library not loaded: @rpath/libcudart.7.5.dylib` error is interesting. Can you verify whether the file `bazel-bin/tensorflow/cc/tutorials_example_trainer.runfiles/local_config_cuda/cuda/lib/libcudart.7.5.dylib` exists? If not, what files are under the `bazel-bin/tensorflow/cc/tutorials_example_trainer.runfiles/local_config_cuda/cuda/lib` directory?

**Comment by Dapid** [comment]
@davidzchen 

```
./configure 
Please specify the location of python. [Default is /home/david/.virtualenvs/py35/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /bin/gcc]: /usr/local/cuda/bin/gcc
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
libcudnn.so resolves to libcudnn.4
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 5.0
INFO: Reading 'startup' options from /home/david/.bazelrc: --batch
Warning: ignoring LD_PRELOAD in environment.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Reading 'startup' options from /home/david/.bazelrc: --batch
Warning: ignoring LD_PRELOAD in environment.
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/boringssl_git/WORKSPACE:1: Workspace name in /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/boringssl_git/WORKSPACE (@boringssl) does not match the name given in the repository's definition (@boringssl_git); this will cause a build error in future versions.
INFO: All external dependencies fetched successfully.
Configuration finished
```

```
git log
commit 6ce5b5c8298273e3861a75fb6ccde63b9dd157c5
Author: Sanders Kleinfeld <sandersk@users.noreply.github.com>
Date:   Sun Aug 28 01:00:52 2016 -0400
```

On branch r0.10.

**Comment by trevorwelch** [comment]
@davidzchen 
It does exist:

```
tensorflow$ cd bazel-bin/tensorflow/cc/tutorials_example_trainer.runfiles/local_config_cuda/cuda/lib/

lib$ ls -l
total 40
lrwxr-xr-x  1 production204  wheel  126 Aug 31 11:03 libcublas.7.5.dylib -> /private/var/tmp/_bazel_production204/ed2bbf43bcd665c40f1e3ebaa04f68f6/external/local_config_cuda/cuda/lib/libcublas.7.5.dylib
lrwxr-xr-x  1 production204  wheel  126 Aug 31 11:03 libcudart.7.5.dylib -> /private/var/tmp/_bazel_production204/ed2bbf43bcd665c40f1e3ebaa04f68f6/external/local_config_cuda/cuda/lib/libcudart.7.5.dylib
lrwxr-xr-x  1 production204  wheel  123 Aug 31 11:03 libcudnn.5.dylib -> /private/var/tmp/_bazel_production204/ed2bbf43bcd665c40f1e3ebaa04f68f6/external/local_config_cuda/cuda/lib/libcudnn.5.dylib
lrwxr-xr-x  1 production204  wheel  125 Aug 31 11:03 libcufft.7.5.dylib -> /private/var/tmp/_bazel_production204/ed2bbf43bcd665c40f1e3ebaa04f68f6/external/local_config_cuda/cuda/lib/libcufft.7.5.dylib
lrwxr-xr-x  1 production204  wheel  126 Aug 31 11:03 libcurand.7.5.dylib -> /private/var/tmp/_bazel_production204/ed2bbf43bcd665c40f1e3ebaa04f68f6/external/local_config_cuda/cuda/lib/libcurand.7.5.dylib

lib$ 
```

**Comment by lissyx** [comment]
I can confirm this also building on a Debian (sid, uptodate of today) system.

**Comment by jmhodges** [comment]
I've found I can induce this by Ctrl-C'ing in the middle of a fresh `bazel build`.

**Comment by FlorinAndrei** [comment]
Ubuntu-16.04, CUDA 8, java 1.8.0_101, bazel 0.3.1

Building from master today

Started ./configure in a virtual instance in VirtualBox, did a CTRL-C because it was taking too long. Went home, fired up the instance again, deleted tensorflow repo, cloned it again.

Did ./configure again with same options as before, it worked well except one warning at the beginning:

```
Found stale PID file (pid=20777). Server probably died abruptly, continuing...
```

Ignored it, and did the command to build for GPU:

```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

And it failed immediately:

```
INFO: Waiting for response from Bazel server (pid 9635)...
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
INFO: Elapsed time: 4.667s
```

**Comment by davidzchen** [comment]
There are two issues being discussed in this thread. @trevorwelch, let's move the `Library not loaded: @rpath/libcudart.7.5.dylib` discussion over to #4187. 

For the `'@local_config_cuda//crosstool': BUILD file not found` issue:

* If the Bazel output directories (i.e. `bazel-tensorflow`, etc.) exist, what is the output of `ls -l bazel-tensorflow/external/local_config_cuda/crosstool`?
* If not, what is the output of `ls -l $(bazel info output_base)/external/local_config_cuda/crosstool`

**Comment by asimonov** [comment]
i experience the same issue. tf 0.10. mac os el capitain. bazel 0.3.0

**Comment by davidzchen** [comment]
@asimonov - Can you print the contents of the `local_config_cuda/crosstool` directory as I mentioned in my comment above?

**Comment by asimonov** [comment]
David,

I cannot find local_config_cuda/crosstool directory anywhere in tensorflow directory.

Kind Regards,
Alexey

**Comment by rasmi** [comment]
@davidzchen I'm getting a broken symlink to
```
~/.cache/bazel/_bazel_/d217f35631206796f447d50c6f1d6243/external/local_config_cuda/crosstool
```

**Comment by davidzchen** [comment]
@asimonov @rasmi - Does the contents of the `local_config_cuda/cuda

**Comment by rasmi** [comment]
@davidzchen -- assuming you mean @jmhodges gist, yes. Just a bunch of cuda library files. Sure enough, running `./configure` and building again produces the crosstool directory with `BUILD`, `CROSSTOOL`, and a `clang/bin/crosstool_wrapper_driver_is_not_gcc` files. I was getting errors with `crosstool_wrapper_driver_is_not_gcc` [earlier](https://github.com/tensorflow/tensorflow/issues/190#issuecomment-244636243) when using gcc 4.9.1, and now I'm getting entirely unrelated errors in highwayhash when using gcc 4.7.2. Not sure if that has anything to do with it or if that's helpful, since this error seems further upstream from these compilation errors.

**Comment by JimmyKon** [comment]
@jmhodges 
@rasmi 
@davidzchen 

here my solution :)

https://github.com/JimmyKon/tensorflow_build_issue_fix

**Comment by Dapid** [comment]
On the error of  ` '@local_config_cuda//crosstool': BUILD file not found`:

```
$ bazel info output_base
Warning: ignoring LD_PRELOAD in environment.
.
/home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63
$ ls -l $(bazel info output_base)/external/local_config_cuda/crosstool
Warning: ignoring LD_PRELOAD in environment.
total 20
-rwxrwxr-x. 1 david david  925 Sep  1 13:38 BUILD
drwxrwxr-x. 3 david david 4096 Sep  1 13:38 clang
-rwxrwxr-x. 1 david david 8870 Sep  1 13:38 CROSSTOOL
```

Note that this only happens when I set a non default GCC, but since it is incompatible with CUDA I can only build for CPU.

**Comment by tornadomeet** [comment]
i solved this by careful setting the cuda/cudnn/gcc version when using ./configure

**Comment by asimonov** [comment]
This is what I have:

AlexPro:tensorflow alex$ bazel info output_base
/private/var/tmp/_bazel_alex/9a8b7d02e7f6ce832d52efe09806ba70

AlexPro:tensorflow alex$ ls -la /private/var/tmp/_bazel_alex/9a8b7d02e7f6ce832d52efe09806ba70/external/local_config_cuda
total 8
drwxr-xr-x    4 alex  wheel   136  6 Sep 07:10 .
drwxr-xr-x  168 alex  wheel  5712  6 Sep 07:10 ..
-rw-r--r--    1 alex  wheel   116  6 Sep 07:10 WORKSPACE
drwxr-xr-x    9 alex  wheel   306  6 Sep 07:10 cuda

**Comment by Dapid** [comment]
@tornadomeet can you show exactly what you used in configure?

**Comment by davidzchen** [comment]
Odd. It appears that even though you are running the `./configure` script to build with GPU support, `cuda_configure` seems to think that GPU support is disabled.

The way that `cuda_configure` determines whether GPU support is enabled is whether `TF_NEED_CUDA` is set to `"1"`, which is what the `./configure` script sets if you answered `y` to whether to build with GPU support.

If you are consistently reproducing the `'@local_config_cuda//crosstool': BUILD file not found` error, can you apply this [patch](https://gist.github.com/davidzchen/165e6ec139fcd9245b5721c8bf2fdd53) and run your `./configure` script and paste the debug (warning) messages from `cuda_configure.bzl` in the output?

**Comment by nsuke** [comment]
I've solved the same problem by putting `bazel  build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` into the last line of `configure`.
Looks like bazel configuration does not complete on `bazel fetch //...` in some cases.
`source configure` might work too.

**Comment by tornadomeet** [comment]
@Dapid i do not saved the configure info, can we get this anywhere(except the info output to the screen during configure)?

**Comment by gopi77** [comment]
Anyone solved the issue? please help
OS: Ubuntu 16.04, Cuda toolkit 8.0, cudnn-8.0-linux-x64-v5.1, GPU nvidia 1070

other settings:
CUDA_HOME=/usr/local/cuda-8.0
LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64
PATH=/usr/local/cuda-8.0/bin:/home/gopi/bin:/home/gopi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

My command window shown below .

gopi@gp:/home/tensorflow$ sudo ./configure 
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python2.7
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]
/usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: /usr/bin/gcc-5
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda-8.0
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1.5
Please specify the location where cuDNN 5.1.5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda-8.0]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
INFO: All external dependencies fetched successfully.
Configuration finished
gopi@gp:/home/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.

**Comment by JimmyKon** [comment]
@gopi77 

I met this error once after upgrade my gcc on my mac.
you can reinstall bazel and execute "bazel clean" before compile.

**Comment by davidzchen** [comment]
@gopi77 - Is there a reason why you are running `./configure` as sudo? Can you try running it without sudo?

@Dapid @nsuke - Can one of you apply the patch I linked in [my comment above](https://github.com/tensorflow/tensorflow/issues/4105#issuecomment-244868298), reproduce the failure, and paste the output that you get as described so that we can get some more state on why the error is happening?

**Comment by gopi77** [comment]
Hi JimmyKon 
I reinstalled bazel, even got fresh clone of tensorflow in different area. But the errors remain
gopi@gp:~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
.
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.

Anyone succeeded with this combination ?
OS: Ubuntu 16.04, Cuda toolkit 8.0, cudnn-8.0-linux-x64-v5.1, GPU nvidia 1070, nvidia driver 370.23.

Repeated installation of ubuntu, toolkit, nvidia drivers, tensorflow many times in the last 3 weeks. still no luck with GPU based run.
But cuda toolkit examples are working fine Ex: bilateral filter and also CPU only version of tensorflow binary working fine.

Davidzchen, 
I got python error and it disappeared using sudo ./configure.

Note: I mentioned compute capability as 6.1 (not visible in previous mail) for my nvidia 1070 card 

Regards
Gopi. J

**Comment by gopi77** [comment]
the error of ./configure without sudo shown below >>>


gopi@gp:~/tensorflow$ ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
./configure: line 66: tensorflow/tools/swig/swig_path: Permission denied
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

/usr/local/lib/python2.7/dist-packages
./util/python/python_config.sh: line 154: tools/bazel.rc: Permission denied

**Comment by nsuke** [comment]
@davidzchen in my case, it turned out that it works fine as long as I don't modify files under `third_party/gpus` between configure and build.
(It was due to #4233 if that matters)

Here's failure log with your patch:
```
$ ./configure
...
WARNING: /home/nsuke/tensorflow/third_party/gpus/cuda_configure.bzl:119:5: TF_NEED_CUDA: 1.
WARNING: /home/nsuke/tensorflow/third_party/gpus/cuda_configure.bzl:360:3: cuda_configure: _create_cuda_repository.
...
$ touch third_party/gpus/cuda_configure.bzl
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: /home/nsuke/tensorflow/third_party/gpus/cuda_configure.bzl:122:5: TF_NEED_CUDA not set.
WARNING: /home/nsuke/tensorflow/third_party/gpus/cuda_configure.bzl:304:3: cuda_configure: _create_dummy_repository.
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
INFO: Elapsed time: 0.553s
```

**Comment by davidzchen** [comment]
@gopi77 Seems that you have some permissions issue in the directory where you have cloned the tensorflow repo. Can you fix your permission issues and try again?

@nsuke Thanks, the debug messages and your explanation are very helpful. Yes, if you modify files under `third_party/gpus`, then Bazel will re-fetch. Since the environment variables read by `cuda_configure` (such as `TF_NEED_CUDA`, etc.) are no longer set (as they were set by the `configure` script), then `cuda_configure()` will run with all default values, in which case, it will configure with GPU support disabled. Is #4233 the reason why you were modifying files under `third_party/gpus` between running `./configure` and `bazel build`?

**Comment by asimonov** [comment]
I have just pulled the latest version of tensorflow, re-ran ./config and build now works. Not sure if you have applied any fixes...

**Comment by davidzchen** [comment]
@asimonov There have not been any fixes that went in for `cuda_configure` since 4c49dbebef05442c7e72d6129a30574fcd13f0e1, which went in 10 days ago and should be related to this issue.

All: If you are experiencing the `'@local_config_cuda//crosstool': BUILD file not found` issue, the most likely cause of the problem is that `cuda_configure` is being re-run during `bazel build` and is re-configuring with GPU support disabled.

1. **Are you modifying any files under `third_party/gpus` between running `./configure` and `bazel build`?** If so, then the reason why you are experiencing the error is because Bazel is re-fetching as explained [here](https://github.com/tensorflow/tensorflow/issues/4105#issuecomment-245110873). Please explain why you need to do so, and we'll see if we can come up with a solution to avoid that.
2. **If not**, please follow the instructions [here](https://github.com/tensorflow/tensorflow/issues/4105#issuecomment-244868298) so that I can have more state on why the error is happening.

**Comment by asimonov** [comment]
interesting…

I just did a pull, re-ran configure then checked that crosstool is there:

AlexPro:tensorflow alex$ ls -l $(bazel info output_base)/external/local_config_cuda
total 8
-rw-r--r--   1 alex  wheel  116  7 Sep 00:05 WORKSPACE
drwxr-xr-x   5 alex  wheel  170  7 Sep 00:05 crosstool
drwxr-xr-x  11 alex  wheel  374  7 Sep 00:05 cuda

then started the build

bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

I went through but failed later with 3 errors. Did not have time to check why. But at least the crosstool issue was gone.

Interestingly when i started build second time it failed with same crosstool issue.

**Comment by asimonov** [comment]
ah, just found the build error:

ERROR: /Users/alex/dev/tensorflow/tensorflow/stream_executor/BUILD:5:1: C++ compilation of rule '//tensorflow/stream_executor:stream_executor' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign ... (remaining 112 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

so it does look like the same issue. but this time it was going further (first try). before i would be failing straight away.

**Comment by Dapid** [comment]
@davidzchen I updated the repo (branch r0.10), applied the patch, and here are the results:

```
[david@SQUIDS tensorflow]$ ./configure 
Please specify the location of python. [Default is /home/david/.virtualenvs/py35/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: /usr/local/cuda/bin/gcc
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
libcudnn.so resolves to libcudnn.5
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 5.0
Warning: ignoring LD_PRELOAD in environment.
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
Warning: ignoring LD_PRELOAD in environment.
.
WARNING: /home/david/gits/tensorflow/third_party/gpus/cuda_configure.bzl:95:5: TF_NEED_CUDA: 1.
WARNING: /home/david/gits/tensorflow/third_party/gpus/cuda_configure.bzl:336:3: cuda_configure: _create_cuda_repository.
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/boringssl_git/WORKSPACE:1: Workspace name in /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/boringssl_git/WORKSPACE (@boringssl) does not match the name given in the repository's definition (@boringssl_git); this will cause a build error in future versions.
INFO: All external dependencies fetched successfully.
Configuration finished
[david@SQUIDS tensorflow]$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
Warning: ignoring LD_PRELOAD in environment.
WARNING: /home/david/gits/tensorflow/third_party/gpus/cuda_configure.bzl:95:5: TF_NEED_CUDA: 1.
WARNING: /home/david/gits/tensorflow/third_party/gpus/cuda_configure.bzl:336:3: cuda_configure: _create_cuda_repository.
WARNING: /home/david/gits/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/bit_depth.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/gemmlowp.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/map.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/output_stages.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/instrumentation.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/profiler.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
INFO: Found 1 target...
ERROR: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/zlib_archive/BUILD:7:1: C++ compilation of rule '@zlib_archive//:zlib' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 35 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/zlib_archive/zlib-1.2.8/zconf.h:395:0,
                 from external/zlib_archive/zlib-1.2.8/zlib.h:34,
                 from external/zlib_archive/zlib-1.2.8/zutil.h:22,
                 from external/zlib_archive/zlib-1.2.8/deflate.h:16,
                 from external/zlib_archive/zlib-1.2.8/deflate.c:52:
/usr/include/limits.h:123:26: error: no include path in which to search for limits.h
 # include_next <limits.h>
                          ^
In file included from external/zlib_archive/zlib-1.2.8/zconf.h:421:0,
                 from external/zlib_archive/zlib-1.2.8/zlib.h:34,
                 from external/zlib_archive/zlib-1.2.8/zutil.h:22,
                 from external/zlib_archive/zlib-1.2.8/deflate.h:16,
                 from external/zlib_archive/zlib-1.2.8/deflate.c:52:
/usr/include/sys/types.h:146:20: fatal error: stddef.h: No such file or directory
 #include <stddef.h>
                    ^
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.827s, Critical Path: 0.40s
[david@SQUIDS tensorflow]$ bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package
Warning: ignoring LD_PRELOAD in environment.
WARNING: /home/david/gits/tensorflow/third_party/gpus/cuda_configure.bzl:95:5: TF_NEED_CUDA: 1.
WARNING: /home/david/gits/tensorflow/third_party/gpus/cuda_configure.bzl:336:3: cuda_configure: _create_cuda_repository.
WARNING: /home/david/gits/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/bit_depth.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/gemmlowp.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/map.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/output_stages.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/instrumentation.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/profiler.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
INFO: Found 1 target...
ERROR: /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/external/re2/BUILD:9:1: C++ compilation of rule '@re2//:re2' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/david/.cache/bazel/_bazel_david/47d00ffdd2fc0515138a34f138cebd63/execroot/tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:/home/david/.local/modeller9.14/lib/x86_64-intel8:/opt/cudnn/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64 \
    PATH=/usr/lib64/openmpi/bin:/home/david/.local/bin:/home/david/.local/hmmer3.1/bin:/home/david/.virtualenvs/py35/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/data/rosetta_weekly/release_15_19/main/source/bin:/usr/local/cuda/bin:/home/david/.local/bin:/home/david/bin \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/local_linux-py3-opt/bin/external/re2/_objs/re2/external/re2/util/strutil.pic.d '-frandom-seed=bazel-out/local_linux-py3-opt/bin/external/re2/_objs/re2/external/re2/util/strutil.pic.o' -fPIC -iquote external/re2 -iquote bazel-out/local_linux-py3-opt/genfiles/external/re2 -iquote external/bazel_tools -iquote bazel-out/local_linux-py3-opt/genfiles/external/bazel_tools -isystem external/re2 -isystem bazel-out/local_linux-py3-opt/genfiles/external/re2 -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c external/re2/util/strutil.cc -o bazel-out/local_linux-py3-opt/bin/external/re2/_objs/re2/external/re2/util/strutil.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/re2/util/util.h:9:0,
                 from external/re2/util/strutil.cc:5:
/usr/include/stdio.h:33:21: fatal error: stddef.h: No such file or directory
 # include <stddef.h>
                     ^
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 0.834s, Critical Path: 0.36s

```

**Comment by gopi77** [comment]
Hi

I tried cloning the latest code and followed the steps as pe https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#installing-from-sources

Now the ./configure & bazel build are success, but some other failure, pasted below.

gopi@gp:~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
....
....
....
Target //tensorflow/cc:tutorials_example_trainer up-to-date:
  bazel-bin/tensorflow/cc/tutorials_example_trainer
INFO: Elapsed time: 1142.181s, Critical Path: 1109.17s

gopi@gp:~/tensorflow$ bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.835
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.43GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
Floating point exception (core dumped)

**Comment by FBrinkkemper** [comment]
Not entirely sure if it is the same issue, but I'm also receiving a BUILD file not found on package path error.

`~$ bazel test //home/Documents/magenta-master/magenta
ERROR: no such package 'home/Documents/magenta-master/magenta': BUILD file not found on package path.`

Iḿ using Bazel 0.3.1 on Ubuntu 16.04

**Comment by g2290412** [comment]
`ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.`

after restart system, even with the recomendations above

"bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer" is taking too long to execute, i've closed after 1 hour
OS: Ubuntu 16.04, Cuda toolkit 8.0, cudnn-8.0-linux-x64-v5.1, GPU nvidia 1070, Bazel 3.1

**Comment by FlorinAndrei** [comment]
It got worse. Before, if I deleted/recloned the repo and tried again, it would compile. Now it always fails.

```
root@machine-learning:/vagrant/packages/tensorflow# bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: Waiting for response from Bazel server (pid 17980)...
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
INFO: Elapsed time: 8.671s
```

```
# git rev-parse HEAD
warning: refname 'HEAD' is ambiguous.
1cb04a68d24187d4d02689e2bc8aba9b7abee154
```

```
root@machine-learning:/vagrant/packages/tensorflow# ls *bazel*
ls: cannot access '*bazel*': No such file or directory
root@machine-learning:/vagrant/packages/tensorflow# ls -l $(bazel info output_base)/external/local_config_cuda/crosstool
ls: cannot access '/root/.cache/bazel/_bazel_root/b0bb79a433b74dfa52314ef9af1d2ddd/external/local_config_cuda/crosstool': No such file or directory
root@machine-learning:/vagrant/packages/tensorflow# tree $(bazel info output_base)/external/local_config_cuda          
/root/.cache/bazel/_bazel_root/b0bb79a433b74dfa52314ef9af1d2ddd/external/local_config_cuda
|-- cuda
|   |-- BUILD
|   |-- build_defs.bzl
|   |-- cuda_config.h
|   |-- extras
|   |   `-- CUPTI
|   |       |-- include
|   |       |   `-- cupti.h
|   |       `-- lib64
|   |           `-- libcupti.so
|   |-- include
|   |   |-- cublas.h
|   |   |-- cuda.h
|   |   `-- cudnn.h
|   |-- lib64
|   |   |-- libcublas.so
|   |   |-- libcudart.so
|   |   |-- libcudart_static.a
|   |   |-- libcudnn.so
|   |   |-- libcufft.so
|   |   `-- libcurand.so
|   `-- platform.bzl
`-- WORKSPACE
```

**Comment by rasmi** [comment]
@davidzchen 

> Are you modifying any files under third_party/gpus between running ./configure and bazel build?

Yes, that makes sense. I'm modifying `bazel-tensorflow/external/protobuf/BUILD` to fix [this issue here](https://github.com/tensorflow/tensorflow/pull/3097#issuecomment-244814825) and `third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl` to fix [this issue here](https://github.com/tensorflow/tensorflow/issues/190#issuecomment-244636243). I got it to compile after re-running `./configure` and `bazel build`.

**Comment by FlorinAndrei** [comment]
All the compilation failures I've seen before only happen on the master branch. None of these issues persists when I switch to the r0.10 branch. Last night I was able to complete a build, Ubuntu 16.04, CUDA 8RC, cuDNN 5.1, nvidia-driver-370, python-2.7, and compute capability 6.1 (for Pascal GPU) - as soon as I switched to r0.10.

**Comment by anirudh2290** [comment]
Hi,

I am getting a similar error when running ./configure. "ERROR: The specified --crosstool_top '@local_config_cuda//crosstool:CROSSTOOL' is not a valid cc_toolchain_suite rule." Is this related to this issue. 
My configuration : 
export TF_NEED_GCP=0
export TF_NEED_CUDA=1
export TF_CUDA_VERSION=7.5
export TF_CUDNN_VERSION=5

Is this related to this issue ? I switched to r0.10 branch but still able to reproduce the issue.

**Comment by nsuke** [comment]
@anirudh2290 which version of bazel are you using ?
I've got the same error with this commit and after: bazelbuild/bazel@0d32fc88d6d179bedef4a04bc22c44583365b859
0.3.1 should be fine.

**Comment by anirudh2290** [comment]
@nsuke thank you. that was the problem. reverting to a previous commit worked.

**Comment by damienmg** [comment]
@anirudh2290 yes this is a recent change in Bazel. @davidzchen we should not longer use a filegroup to refer to crosstool but use cc_toolchain_suite

**Comment by davidzchen** [comment]
@damienmg Understood. I have added those changes to #4285

**Comment by gopi77** [comment]
Got this problem ERROR: no such package '@local_config_cuda//crosstool':  again today.
After various attempts the below steps worked.

1.  sudo apt-get upgrade bazel
2. ./configure (i didn't repeat this step >> $ git clone https://github.com/tensorflow/tensorflow)
3. # To build with GPU support:
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

4.
mkdir _python_build
cd _python_build
ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/* .
ln -s ../tensorflow/tools/pip_package/* .
python setup.py develop

5. cd tensorflow/models/image/mnist
$ python convolutional.py

**Comment by suiyuan2009** [comment]
meet the same issue.

**Comment by obo** [comment]
Hi. I'm getting "ERROR: no such package '@local_config_cuda//crosstool': BUILD file not found on package path." as well with:

- bazel: https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel-0.3.1-installer-linux-x86_64.sh
- tensorflow: commit a6c5f8e4e013e54fed8dfcf49fb6de365f018022 (patched according to https://github.com/tensorflow/tensorflow/issues/4312#issuecomment-246109583 to avoid the ios/android errors)
- cuda: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.5-18_amd64.deb
- python 3.5 as package from: sudo add-apt-repository -y ppa:fkrull/deadsnakes; sudo apt-get update; 
sudo apt-get -y install python3.5
- forced to use wheel>0.25.0

The issue for me happens deterministically, if I run tensorflow ./configure while trying to avoid interactive questions:

# set vars to avoid interactive
export PYTHON_BIN_PATH=/usr/bin/python
## No way to confirm the following default value to ./util/python/python_config.sh without actually hitting the Return key: :-((
##   /usr/lib/python3/dist-packages
export TF_NEED_GCP=n
export TF_NEED_CUDA=y
export GCC_HOST_COMPILER_PATH=/usr/bin/gcc
export TF_CUDA_VERSION=7.5
export CUDA_TOOLKIT_PATH=$CUDA_HOME
export TF_CUDNN_VERSION=4
export CUDNN_INSTALL_PATH=$CUDA_HOME
export TF_CUDA_COMPUTE_CAPABILITIES=3.0

If I run ./configure without setting the above variables, ie.:

ubuntu@aws17:~/tensorflow$ ./configure
~/tensorflow ~/tensorflow
Please specify the location of python. [Default is /usr/bin/python]:
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python3.5/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.5/dist-packages]

/usr/local/lib/python3.5/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]:
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify the Cudnn version you want to use. [Leave empty to use system default]:
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
libcudnn.so resolves to libcudnn.4
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.0

then the compilation works.

Note that there is probably no way to pass blank values (indicating "use the default" as opposed to undefined values indicating "I have not answered yet") for several of the variables. So ./configure in the interactive mode is getting various things blank while the less interactive ./configure has these values filled.

**Comment by kamal94** [comment]
A similar error now appears during the building process:



```
/home/kamal/.cache/bazel/_bazel_kamal/f9ae4eca457b390bb2ebe780caca64e0/external/protobuf/BUILD:333:1: Linking of rule '@protobuf//:protoc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/kamal/.cache/bazel/_bazel_kamal/f9ae4eca457b390bb2ebe780caca64e0/execroot/tensorflow && \
  exec env - \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/external/protobuf/protoc bazel-out/host/bin/external/protobuf/_objs/protoc/external/protobuf/src/google/protobuf/compiler/main.o bazel-out/host/bin/external/protobuf/libprotoc_lib.a bazel-out/host/bin/external/protobuf/libprotobuf.a bazel-out/host/bin/external/protobuf/libprotobuf_lite.a -lpthread -lstdc++ -B/usr/bin/ -pie -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,--gc-sections): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/host/bin/external/protobuf/_objs/protoc/external/protobuf/src/google/protobuf/compiler/main.o: In function `main':
main.cc:(.text.startup.main+0x2ad): undefined reference to `vtable for google::protobuf::compiler::php::Generator'
main.cc:(.text.startup.main+0x5fc): undefined reference to `vtable for google::protobuf::compiler::php::Generator'
main.cc:(.text.startup.main+0x707): undefined reference to `vtable for google::protobuf::compiler::php::Generator'
collect2: error: ld returned 1 exit status
Target //tensorflow/cc:tutorials_example_trainer failed to build
```

I think this might be related to	4316aeb

**Comment by sskgit** [comment]
Hi,

Facing similar issues for tensorflow build.
I am trying Tensoflow from the source and receive build error for 
a) C++ compilation of rule '@grpc//:gpr' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc 

b) ERROR: I/O error while writing action log: No space left on device.

Enviornment:

Cuda 8.0
CuDNN 5
Ubuntu 16.04
bazel 0.3
Nvidia K80
Azure VM N6 (56 GB Memory)

Tried ./configure and build several times. Configure is successful but build fails. 

Also tried, bazel clean, bazel clean --explunge and ran the build with reduced number of jobs
bazel build -c opt --config=cuda --jobs=10 //tensorflow/cc:tutorials_example_trainer

but the error continues..

Looked at this thread and also 

https://github.com/tensorflow/tensorflow/issues/190

Here is the full error message:

52adb8ea4f53b1b72067611e8a7eb020/external/grpc/BUILD:69:1: C++ compilation of rule '@grpc//:gpr' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 38 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
ERROR: I/O error while writing action log: No space left on device.
java.util.logging.ErrorManager: 2
java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.util.logging.FileHandler$MeteredStream.flush(FileHandler.java:196)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.util.logging.StreamHandler.flush(StreamHandler.java:259)
        at java.util.logging.FileHandler.publish(FileHandler.java:683)
        at java.util.logging.Logger.log(Logger.java:738)
        at java.util.logging.Logger.doLog(Logger.java:765)
        at java.util.logging.Logger.log(Logger.java:788)
        at java.util.logging.Logger.info(Logger.java:1489)
        at com.google.devtools.build.lib.profiler.AutoProfiler$LoggingElapsedTimeReceiver.accept(AutoProfiler.java:315)
        at com.google.devtools.build.lib.profiler.AutoProfiler$SequencedElapsedTimeReceiver.accept(AutoProfiler.java:262)
        at com.google.devtools.build.lib.profiler.AutoProfiler.completeAndGetElapsedTimeNanos(AutoProfiler.java:226)
        at com.google.devtools.build.lib.buildtool.ExecutionTool.saveCaches(ExecutionTool.java:725)
        at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:470)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:201)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:333)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:488)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:324)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)

**Comment by darrengarvey** [comment]
@sskgit - This looks like b) no space left on device is the reason for a) compilation of a file fails. You'll notice from the `bazel-*` symlinks in the tensorflow directory point to `$HOME/.cache/bazel/...`, so check you've got enough space on the partition you have `$HOME` mounted to.

**Comment by sskgit** [comment]
@darrengarvey Thanks for your response.

I tried sudo df and here is the output

df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev            28837212        0  28837212   0% /dev
tmpfs            5771196     9244   5761952   1% /run
/dev/sda1       29711408 29329736    365288  99% /
tmpfs           28855968        0  28855968   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs           28855968        0  28855968   0% /sys/fs/cgroup
none                  64        0        64   0% /etc/network/interfaces.dynamic.d
/dev/sdb1      356513788   135524 356378264   1% /mnt
tmpfs            5771196        0   5771196   0% /run/user/1000

It shows mounted on / has almost no space, and I think $VM/Username (i.e. $HOME) is on the same mount /, as there is no $HOME mounted on, in the output. Is this the right command?

At / (used space)

du -sch
2.3G    .
2.3G    total


At $HOME (used space)

du -sch
4.4G    .
4.4G    total

So, I am not sure what is occupying the remaining space? Total storage on this VM is 380 GB. 

Is there any way to get rid of bazel logs? Is it causing the space issue? If so, where? 

Thanks

 Also, if it is how do I free up some space?

**Comment by davidzchen** [comment]
@sskgit Running `bazel clean --expunge` should remove all of the generated files for the workspace. How much free space do you have after running that command?

@martinwicke Sorry for the late reply. I have been on call for a good part of the past week. That looks like a linker error in protobuf and does not seem related to this particular change. `crosstool_wrapper_driver_is_not_gcc` is a wrapper script that calls `gcc`. Is this on a newer version of protobuf?

**Comment by sskgit** [comment]
@davidzchen Thanks for your response. 

used bazel clean --expunge (this cleaned 500MB space) and re-configured tensorflow using ./configure

Run the bazel build again..

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

ERROR: /$HOME/Downloads/tensorflow/tensorflow/core/kernels/BUILD:1710:1: error while parsing .d file: /$HOME/.cache/bazel/_bazel_gpuadmin/52adb8ea4f53b1b72067611e8a7eb020/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/depth_space_ops_gpu/tensorflow/core/kernels/depthtospace_op_gpu.cu.pic.d (No such file or directory).
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
<built-in>: fatal error: when writing output to : No space left on device
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build

At $HOME:
du -sch
4.6G	.
4.6G	total


At /:
du -sch
2.3G	.
2.3G	total

df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             28G     0   28G   0% /dev
tmpfs           5.6G  9.1M  5.5G   1% /run
**/dev/sda1        29G   29G  9.8M 100% /**
tmpfs            28G     0   28G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            28G     0   28G   0% /sys/fs/cgroup
none             64K     0   64K   0% /etc/network/interfaces.dynamic.d
/dev/sdb1       340G  133M  340G   1% /mnt
tmpfs           5.6G     0  5.6G   0% /run/user/1000

This is a fairly new machine with few installer software (<200MB)

**Comment by davidzchen** [comment]
@sskgit Interesting. Can you open a bug at bazelbuild/bazel for this issue? Thanks.

**Comment by sskgit** [comment]
@davidzchen Opened an issue with bazel as well. I have tried the build almost 10 times in last couple of days. Still trying to figure why the build fails and how do I complete the build successfully.

**Comment by sskgit** [comment]
Space issue caused my Tensorflow build to fail. Clearing some space on the / mount made the build successful and Tensorflow now works as expected.

Thanks everyone for your help!

**Comment by TomAshley303** [comment]
This is happening for me too. I already have TF installed and working for GPU via the runfile but I wanted to compile it for optimizations. I get:

```
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/home/user/bin/tensorflow/third_party/gpus/cuda_configure.bzl", line 1039
                _create_local_cuda_repository(repository_ctx)
        File "/home/user/bin/tensorflow/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
                _host_compiler_includes(repository_ctx, cc)
        File "/home/user/bin/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
                get_cxx_inc_directories(repository_ctx, cc)
        File "/home/user/bin/tensorflow/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
                set(includes_cpp)
depsets cannot contain mutable items
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
        File "/home/user/bin/tensorflow/third_party/gpus/cuda_configure.bzl", line 1039
                _create_local_cuda_repository(repository_ctx)
        File "/home/user/bin/tensorflow/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
                _host_compiler_includes(repository_ctx, cc)
        File "/home/user/bin/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
                get_cxx_inc_directories(repository_ctx, cc)
        File "/home/user/bin/tensorflow/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
                set(includes_cpp)
depsets cannot contain mutable items
INFO: Elapsed time: 4.869s
FAILED: Build did NOT complete successfully (3 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

Steps to reproduce:

```
git clone --recurse-submodules https://github.com/tensorflow/tensorflow
cd tensorflow
$ ./configure
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Please specify the location of python. [Default is /home/user/.pyenv/versions/3.6.2/bin/python]: 
Found possible Python library paths:
/home/user/.pyenv/versions/3.6.2/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is /home/user/.pyenv/versions/3.6.2/lib/python3.6/site-packages
Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: y
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]: n
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [y/N]: n
No Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: n
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL support? [y/N]: n
No OpenCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]: 
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda-8.0
"Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]: 
Please specify the location where cuDNN 6 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda-8.0]:/usr/lib/x86_64-linux-gnu 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 6.1]
Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.
Configuration finished
$ bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=cuda -k //tensorflow/tools/pip_package:build_pip_package
```

If you notice that I've done something wrong, please let me know. I saw someone before mention something about `LD_LIBRARY_PATH` which I have set to `/usr/local/cuda-8.0/lib64`. I figured it was fine since as I said, I already have TF installed and running from the runfile download. I would like to be able to compile from source though.

**Comment by itssujeeth** [comment]
I’m also facing the same challenge - unable to build tensor flow on a gpu server.  Below given are the details.  OS is Ubuntu 16.04LTS

```
user@gpu-devbox:~/Workouts/tensorflow$ python --version
Python 2.7.12
```
```
user@gpu-devbox:~/Workouts/tensorflow$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1-16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
user@gpu-devbox:~/Workouts/tensorflow$ bazel version
Build label: 0.5.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 28 08:34:59 2017 (1501230899)
Build timestamp: 1501230899
Build timestamp as int: 1501230899
```
```
user@gpu-devbox:~/Workouts/tensorflow$ ./configure 
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Please specify the location of python. [Default is /usr/bin/python]: 
Found possible Python library paths:
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: 
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]: 
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [y/N]: 
No Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: 
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: 
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL support? [y/N]: 
No OpenCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: Y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]: 
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
"Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]: 
Please specify the location where cuDNN 6 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 6.1,6.1,6.1,6.1]6.1
Do you want to use clang as CUDA compiler? [y/N]: 
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Do you wish to build TensorFlow with MPI support? [y/N]: 
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.
Configuration finished
```
```
user@gpu-devbox:~/Workouts/tensorflow$ echo $CUDA_HOME
/usr/local/cuda-8.0

user@gpu-devbox:~/Workouts/tensorflow$ echo $LD_LIBRARY_PATH
/usr/local/cuda-8.0/lib64
```
```
user@gpu-devbox:~/Workouts/tensorflow$ bazel build --config=opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" ./tensorflow/tools/pip_package:build_pip_package 
.......
ERROR: no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
    File "/home/u19061/Workouts/tensorflow/third_party/gpus/cuda_configure.bzl", line 1039
        _create_local_cuda_repository(repository_ctx)
    File "/home/user/Workouts/tensorflow/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
        _host_compiler_includes(repository_ctx, cc)
    File "/home/user/Workouts/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
        get_cxx_inc_directories(repository_ctx, cc)
    File "/home/user/Workouts/tensorflow/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
        set(includes_cpp)
depsets cannot contain mutable items
INFO: Elapsed time: 5.488s
FAILED: Build did NOT complete successfully (3 packages loaded)
```

**Comment by itssujeeth** [comment]
Also - If when checked the cache doesn’t contain crosstool - Am I missing something here?
```
user@devbox:~/Workouts/tensorflow$ ls -l $(bazel info output_base)/external/local_config_cuda/crosstool
total 4
-rwxrwxr-x 1 user user 1267 Aug  1 16:32 BUILD
```

**Comment by sh1r0** [comment]
@itssujeeth #11949 fixes the issue when building tensorflow with gpu support using bazel 0.5.3.
