### ISSUE TITLE
UnknownError:    CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by ApelSYN** [tensorflow/tensorflow#41060]
This bug is a continuation of solving this problem:
https://github.com/tensorflow/tensorflow/issues/40877

**System information**
- Have I written custom code with tensorflow.keras.layers.LSTM layer:
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed: from source "bazel build --config=opt --config=cuda --config=mkl --copt=-march=native //tensorflow/tools/pip_package:build_pip_package"
- TensorFlow version: v1.12.1-35676-g89798077df 2.4.0
- Python version: 3.6.9
- Bazel version: Python 3.6.9
- GCC/Compiler version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: 10.2 / 8.0
- GPU model and memory: NVIDIA GeForce RTX 2080 TI 11G

The previously described error no longer occurs. No less, when trying to use the LSTM layer, another error appeared
```
UnknownError                              Traceback (most recent call last)
<ipython-input-24-66b029fffc15> in <module>
      1 # train
----> 2 hist = textClassifier.train(X_train[:10000], y_train[:10000])
      3 hist

<ipython-input-21-d0b8fb2d36c8> in train(self, X, y, w2v_model, verbose, X2)
    308 
    309     def train(self, X, y, w2v_model=None, verbose=0, X2=None):
--> 310         self.fit(X, y, w2v_model, verbose, X2)
    311         return self.hist
    312 

<ipython-input-21-d0b8fb2d36c8> in fit(self, X, y, w2v_model, verbose, X2)
    301                                   epochs           = self.epochs,
    302                                   batch_size       = self.batch_size,
--> 303                                   shuffle          = False)
    304 
    305         self.model      = model

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1097                 batch_size=batch_size):
   1098               callbacks.on_train_batch_begin(step)
-> 1099               tmp_logs = train_function(iterator)
   1100               if data_handler.should_sync:
   1101                 context.async_wait()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    838         # Lifting succeeded, so variables are initialized and we can run the
    839         # stateless function.
--> 840         return self._stateless_fn(*args, **kwds)
    841     else:
    842       canon_args, canon_kwds = \

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2842     with self._lock:
   2843       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2844     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2845 
   2846   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1845                            resource_variable_ops.BaseResourceVariable))],
   1846         captured_inputs=self.captured_inputs,
-> 1847         cancellation_manager=cancellation_manager)
   1848 
   1849   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1921       # No tape is watching; skip to running the function.
   1922       return self._build_call_outputs(self._inference_function.call(
-> 1923           ctx, args, cancellation_manager=cancellation_manager))
   1924     forward_backward = self._select_forward_and_backward_functions(
   1925         args,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    548               inputs=args,
    549               attrs=attrs,
--> 550               ctx=ctx)
    551         else:
    552           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

UnknownError:    CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1130): 'cudnnSetRNNDescriptor_v8( rnn_desc.get(), rnn_algo, rnn_mode, bias_mode, direction_mode, input_mode, data_type, compute_type, math_type, input_size, hidden_size, cell_size, num_layers, dropout_desc.handle(), aux_flags)'
	 [[{{node CudnnRNN}}]]
	 [[functional_3/bidirectional_1/forward_lstm_1/PartitionedCall]] [Op:__inference_train_function_13519]

Function call stack:
train_function -> train_function -> train_function
```

```bash
root@RedShark:/usr# python3 -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
2020-07-03 00:10:58.059582: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
v1.12.1-35676-g89798077df 2.4.0
```
If I turn off cuda ( os.environ['CUDA_VISIBLE_DEVICES'] = '' ), everything works fine on cpu.

**Comment by tstumm** [comment]
Probably related to #33148

**Comment by amahendrakar** [comment]
@ApelSYN,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here along with the dataset you are using. Thanks!

**Comment by ApelSYN** [comment]
@amahendrakar 
I created a small jupyter notebook in which you can reproduce this bug:
https://nomeroff.net.ua/tf/lstm_cuda_error/LSTM_cuda_error_example.zip

**Comment by amahendrakar** [comment]
@ApelSYN,
I was able to run the code without any issues on [TF v2.2](https://colab.research.google.com/gist/amahendrakar/0663bb997cf9614630f48212b45d67c0/41060.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/33f9cb91121983a628963b8e5b742927/41060-tf-nightly.ipynb). Please find the attached gist. 

Please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu) and check if you are running the compatible CUDA and cuDNN version. Thanks!

**Comment by ApelSYN** [comment]
I updated cuda to version 11 (from Nvidia https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork ) and everything worked for me even without additional rebuilding from the source. Thanks

**Comment by ApelSYN** [comment]
@amahendrakar
Still it took tensorflow to rebuild.

**Comment by nawabhussain** [comment]
@amahendrakar  Does Tensorflow 2.x support CUDA version 11? In their [documentation](https://www.tensorflow.org/install/gpu#software_requirements) they mention that it supports only version 10.1.

**Comment by xun-dao** [comment]
hi all, I solved it by set "_could_use_gpu_kernel = False". I use tensorflowonspark which opened by yahoo, and with the documents says, there are two ways to use GPU, first is cuDNN kernel. second is generic GPU
