### ISSUE TITLE
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by quinn** [tensorflow/tensorflow#41146]
https://www.tensorflow.org/tutorials/generative/style_transfer

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no. downloaded the notebook and ran verbatim. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 20.04

- TensorFlow installed from (source or binary):
pip
- TensorFlow version (use command below):
v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version:
3.8.3
- CUDA/cuDNN version:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 206...  Off  | 00000000:0A:00.0  On |                  N/A |
| 29%   48C    P2    73W / 175W |   7950MiB /  7979MiB |     41%      Default |
+-------------------------------+----------------------+----------------------+
```
- GPU model and memory:
Nvidia RTX 2060 Super 8GB

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
https://www.tensorflow.org/tutorials/generative/style_transfer jupyter notebook from this article, unmodified

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-21-5d399fb9441b> in <module>
      1 import tensorflow_hub as hub
      2 hub_module = hub.load('https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/1')
----> 3 stylized_image = hub_module(tf.constant(content_image), tf.constant(style_image))[0]
      4 tensor_to_image(stylized_image)

~/code/github.com/quinn/ml/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py in _call_attribute(instance, *args, **kwargs)
    484 
    485 def _call_attribute(instance, *args, **kwargs):
--> 486   return instance.__call__(*args, **kwargs)
    487 
    488 

~/code/github.com/quinn/ml/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   1603       TypeError: For invalid positional/keyword argument combinations.
   1604     """
-> 1605     return self._call_impl(args, kwargs)
   1606 
   1607   def _call_impl(self, args, kwargs, cancellation_manager=None):

~/code/github.com/quinn/ml/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_impl(self, args, kwargs, cancellation_manager)
   1643       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
   1644           list(kwargs.keys()), list(self._arg_keywords)))
-> 1645     return self._call_flat(args, self.captured_inputs, cancellation_manager)
   1646 
   1647   def _filtered_call(self, args, kwargs):

~/code/github.com/quinn/ml/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py in _call_flat(self, args, captured_inputs, cancellation_manager)
     98       captured_inputs = list(
     99           map(get_cross_replica_handle, captured_inputs))
--> 100     return super(_WrapperFunction, self)._call_flat(args, captured_inputs,
    101                                                     cancellation_manager)
    102 

~/code/github.com/quinn/ml/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1743         and executing_eagerly):
   1744       # No tape is watching; skip to running the function.
-> 1745       return self._build_call_outputs(self._inference_function.call(
   1746           ctx, args, cancellation_manager=cancellation_manager))
   1747     forward_backward = self._select_forward_and_backward_functions(

~/code/github.com/quinn/ml/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    591       with _InterpolateFunctionError(self):
    592         if cancellation_manager is None:
--> 593           outputs = execute.execute(
    594               str(self.signature.name),
    595               num_outputs=self._num_outputs,

~/code/github.com/quinn/ml/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node InceptionV3/Conv2d_1a_3x3/Conv2D (defined at /home/quinn/code/github.com/quinn/ml/venv/lib/python3.8/site-packages/tensorflow_hub/module_v2.py:102) ]] [Op:__inference_pruned_18205]

Function call stack:
pruned
```

**Comment by quinn** [comment]
i closed some stuff, got memory down to `1542MiB /  7979MiB`. still having same problem.

**Comment by quinn** [comment]
i added this mysterious incantation to the start of the script and it seems to work now:
```
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
```
should i preface everything i do in TF with this ?

**Comment by jnd77** [comment]
You can just set the env variable TF_FORCE_GPU_ALLOW_GROWTH to `true` ... (this issue is related to RTX cards)

**Comment by quinn** [comment]
@jnd77 thanks! is there documentation somewhere explaining why this affects RTX cards specifically?

**Comment by jnd77** [comment]
I never saw the documentation.
Just an issue I came across first time we bought an RTX card ...

**Comment by Saduf2019** [comment]
@jnd77 
Please refer to issues with similar error, [link](https://github.com/tensorflow/tensorflow/issues/25160#issuecomment-647104234) [link1](https://github.com/tensorflow/tensorflow/issues/36025#issuecomment-630375877) #37725  #34355 #24828

**Comment by jnd77** [comment]
@Saduf2019 thanks a lot for pointing to other issues. Actually am not the one who raised the issue. I was just pointing out I never saw in the official documentation the importance of this env variable for RTX cards.

Maybe it should be added somewhere, or alternatively the default value should become True, since more and more people will work with RTX cards.

Feel free to check with @quinn if the issue can be closed.

**Comment by Saduf2019** [comment]
@quinn 
Please update as per above comment.

**Comment by quinn** [comment]
`TF_FORCE_GPU_ALLOW_GROWTH` does seem to fix it. thank you @jnd77 ! @Saduf2019 Yes, I read many SO/github issues before posting this. I did eventually fix it with the code snippet I found. The env var solution is much succinct, but it seems like there should be either be a fix in the code for this, or official documentation added to capture searches and address the various combinations of hardware and library versions that seem to cause this error

**Comment by Saduf2019** [comment]
@quinn 
Please confirm if we may move this issue to closed status as its fixed.

**Comment by sreeragh-ar** [comment]
This is an issue of mismatch between loaded runtine CuDNN version and version with which the Tensorflow source was compiled.

I had to downgrade my conda CuDNN version from 7.6.5 to 7.6.4.

Steps I followed

`conda uninstall cudnn==7.6.5 // your version` 

Now to find the required version just run the Tensorflow code again and check the error.
`Loaded runtime CuDNN library: 7.1.4 but the source was compiled with: 7.6.4.  CuDNN library major and minor version needs to match `

Install the required version
`conda install cudnn==7.64`
