### ISSUE TITLE
 LSTM crash randomly on Windows 10: Failed to call ThenRnnBackward with model config

### ISSUE THREAD

**Issue by MichaelJanz** [tensorflow/tensorflow#41444]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2
- Python version: 3.7
- CUDA/cuDNN version: Cuda 11, cudnn 7
- GPU model and memory: rtx 2070, 8GB

**Describe the current behavior**
Hi, this is a follow up issue for this one : #37942 
The proposed answers might help, but the core if the issue is still not found. The only known solution so far is to switch the OS, which is not sufficient.

When using LSTM networks on windows 10, model training crashes randomly with an error message like:
```
Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 20, 250, 1, 910, 4, 250] 
	 [[{{node gradients/CudnnRNN_grad/CudnnRNNBackprop}}]]
	 [[PartitionedCall_3]] [Op:__inference_train_function_13679]
```

**Describe the expected behavior**

I would expect the code to either throw an comprehensible error message on a certain error or run through well.
But currently it is throwing error randomly, sometimes after a few steps, sometimes after some epochs.

**Standalone code to reproduce the issue**
@jlebar (thank you!) created a example notebook, which you can find [here](https://gist.github.com/jliebers/995c3c4da4ad2a6f9376d31ee2470ec5)
However, I was able to train that net without problem for 15 epochs, while in the example it crashed after three.
So you can find the code with my repository [here](https://github.com/MichaelJanz/random-LSTM-Crash-TF-Example)

**Other info / logs**

This is my terminal output:
```
[[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2020-07-16 08:35:27.443854: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:28.281334: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-07-16 08:35:28.507116: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:28.527048: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-07-16 08:35:29.449350: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:29.482832: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:29.510930: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:30.417794: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:30.459687: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:30.509665: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:30.560799: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
2020-07-16 08:35:31.524564: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1957): 'cudnnRNNBackwardData( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, output_desc.handles(), output_data.opaque(), output_desc.handles(), output_backprop_data.opaque(), output_h_desc.handle(), output_h_backprop_data.opaque(), output_c_desc.handle(), output_c_backprop_data.opaque(), rnn_desc.params_handle(), params.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), input_desc.handles(), input_backprop_data->opaque(), input_h_desc.handle(), input_h_backprop_data->opaque(), input_c_desc.handle(), input_c_backprop_data->opaque(), workspace.opaque(), workspace.size(), reserve_space_data->opaque(), reserve_space_data->size())'
2020-07-16 08:35:31.525235: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at cudnn_rnn_ops.cc:1922 : Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 20, 250, 1, 910, 4, 250]
2020-07-16 08:35:31.525583: W tensorflow/core/common_runtime/executor.cc:1086] [/job:localhost/replica:0/task:0/device:GPU:0] Executor start aborting: Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 20, 250, 1, 910, 4, 250]
         [[{{node gradients/CudnnRNN_grad/CudnnRNNBackprop}}]]
2020-07-16 08:35:31.526101: W tensorflow/core/common_runtime/executor.cc:1086] [/job:localhost/replica:0/task:0/device:GPU:0] Executor start aborting: Internal: {{function_node __inference___backward_gpu_lstm_with_fallback_8535_8711_specialized_for_PartitionedCall_3_at___inference_train_function_13679}} {{function_node __inference___backward_gpu_lstm_with_fallback_8535_8711_specialized_for_PartitionedCall_3_at___inference_train_function_13679}} Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 20, 250, 1, 910, 4, 250]
         [[{{node gradients/CudnnRNN_grad/CudnnRNNBackprop}}]]
         [[PartitionedCall_3]]
```

**Comment by ravikyram** [comment]
@MichaelJanz 

I have tried in colab with TF version 2.2 and i am seeing the below error (`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6cd2080103c8e39754885419a815a76c/untitled.ipynb).Thanks!

**Comment by MichaelJanz** [comment]
Please note, that several causes already have been discussed in the original thread #37942 

It seems to be, that the cause for this error lies within Windows 10, so it will perform different on colab. 
Also the error occurs while running `model.fit()`, not during evaluation (not even getting to that point).

As I mentioned, alot of possible causes have been discussed in the original thread, but it was closed without a real solution provided. The only real known solution so far is to switch the OS, which is not sufficient.

**Comment by andrewzlee** [comment]
+1 on working in colab but not elsewhere

I'm surprised this hasn't been an issue for more people. Even switching the OS to linux didn't work for me. I keep thinking it's an issue with more recent nvidia drivers, but haven't proved been able to prove it yet.

**Comment by stevenwong** [comment]
Hi all, I've ran into the same issue yesterday. I've managed to reproduce the error with the following code. I'm also on Windows 10, RTX 2060 with Cuda 10.1, driver 451.48, Tensorflow 2.1.0.

I've already tried some of the suggested fixes in the original [issue](https://github.com/tensorflow/tensorflow/issues/37942)

```
import numpy as np
import pandas as pd

import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU')
try:
	tf.config.experimental.set_memory_growth(physical_devices[0], True)
except:
	print('Could not set GPU memory growth')
	pass
	
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping


N = 1000
T = 2000
C = 5
batch_size = 1024

x = np.zeros((T+1, N, C), dtype='float32')

for t in range(T+1):
	if t == 0:
		x[t,:,] = np.random.normal(0., 1., (N, C))
	else:
		x[t,:,] = 0.95 * x[t-1,:,] + 0.05 * np.random.normal(0., 1., (N, C))

x = np.swapaxes(x, 0, 1)

for i in range(100):
	keras.backend.clear_session()
	input_layer = keras.layers.Input(shape=(None, C))
	nn = keras.layers.LSTM(batch_input_shape=(batch_size, T, C), units=32, return_sequences=True)(input_layer)
	nn = keras.layers.LSTM(units=16, return_sequences=True)(nn)
	nn = keras.layers.LSTM(units=8)(nn)
	output_layer = keras.layers.Dense(1)(nn)
	model = keras.Model(input_layer, output_layer)
	opt = keras.optimizers.Adam(lr=0.001)
	model.compile(loss='mse', optimizer=opt)

	c = EarlyStopping(min_delta=0.001, patience=5, restore_best_weights=True)
	model.fit(x[:750,:-1,:], x[:750,-1,1], batch_size=128, callbacks=[c],
		validation_data=(x[750:,:-1,:], x[750:,-1,1]), epochs=100)
```

**Comment by lriuui0x0** [comment]
Any progress on this problem?

**Comment by stevenwong** [comment]
Downgrading driver to 431.86 according to this [post](https://forums.developer.nvidia.com/t/cudnn-lstm-is-broken-above-driver-431-60-unexpected-event-status-1-cuda/108800) seems to have fixed the issue for me. Or at least I'm yet to encounter the same crash in half a day of training.

**Comment by MichaelJanz** [comment]
"Solution" for me was to switch to Ubuntu. The networks, that were causing the errors train very well here. Using cuda11, cudnn8 with TF-2.3 with nvidia-450 driver.

Still for anyone who cannot swap the os, that is no solution

**Comment by daviddiazsolis** [comment]
This is not a permanent solution, but I managed to make it work again by downgrading the NVIDIA driver to the last stable studio driver (431.86) as suggested here: https://forums.developer.nvidia.com/t/cudnn-lstm-is-broken-above-driver-431-60-unexpected-event-status-1-cuda/108800/2

You need to first download the corresponding studio driver from NVIDIA, then uninstall the whatever driver version you have now (in my case 442), then install the 431.86 again. This is trickier than it sounds, as NVIDIA utilities only allow you to downgrade to the previous version, and my case I was several versions ahead.

I ended up using DDU utility as suggested in other forums to wipe the previous driver from my machine, it did the job nicely (no safe mode was necessary).

Also, bear in mind that windows will try to automatically update the driver as soon as it gets a chance (creating the problem again). To avoid this you can disable automatic updates for your drivers following these instructions.

By the way, it wasn't necessary to apply the previous fixes suggested in the post (set batch_size or memory growth), just downgrading the driver did the trick.

I hope this helps, I wasted several hours trying to make it work!

**Comment by viliket** [comment]
I have the same problem and only the (batch_size + memory growth) workaround or downgrading to unsupported 431.86 driver version seem to help. See my full comment on another related issue https://github.com/tensorflow/tensorflow/issues/37942#issuecomment-699468891

**Comment by no-trick-pony** [comment]
Same problem here. But I too can confirm that a driver update resolved the issue for me on windows completely (was before on 45x now on 466.77)

If the author or anybody else could confirm that, I think this issue can be closed, since we now have a good permanent solution.

**Comment by sushreebarsa** [comment]
@MichaelJanz It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!
