### ISSUE TITLE
Fitting sometimes leads to NaN loss on TPU, while on CPU doesn't

### ISSUE THREAD

**Issue by sedol1339** [tensorflow/tensorflow#41635]
**System information**

- TensorFlow version (use command below): 2.2.0 (v2.2.0-0-g2b96f3662b)
- Python version: 3.6.9
- GPU model and memory: Google Colab TPU

I've found that sometimes fitting model on TPU leads to NaN loss, while fitting on CPU doesn't.

I fit Xception network with custom top layers, using only 5 batches, one per epoch. Standalone code:

```
import os
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import *

tf.get_logger().propagate = False
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu = 'grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)

with strategy.scope():
#with tf.device('/job:localhost/replica:0/task:0/device:CPU:0'):

  xception = tf.keras.applications.Xception(weights = 'imagenet', include_top = False, input_shape = (256, 256, 3))

  x = xception.output
  x = GlobalAveragePooling2D()(x)
  x = Dense(256, activation = 'relu')(x)
  x = Dropout(0.25)(x)
  predictions = Dense(10)(x)

  model = tf.keras.Model(inputs = xception.input, outputs = predictions)

  model.compile(
      loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True),
      optimizer = tf.keras.optimizers.Adam(learning_rate = 1e-8),
      metrics = ['accuracy']
  )

  batch_size = 7
  for epoch in range(5):
    X = np.random.rand(batch_size, 256, 256, 3)
    Y = np.zeros(batch_size)
    model.fit(X, Y, batch_size = batch_size, epochs = 1)
```

What i've found?
- if using TPU, batch_size < 8 fitting gives NaN loss after second epoch (or second batch, which is the same)
- if using TPU, batch_size < 8 and X is multiplied by zero, fitting gives NaN loss after first epoch
- if using TPU, batch_size >= 8, fitting doesn't give NaN loss
- if using TPU, batch_size >= 8 and X is multiplied by zero, fitting gives NaN loss after first epoch
- if using CPU, fitting doesn't give NaN loss in the cases described above

So, fitting gives NaN loss if we are using TPU and batch_size < 8 or X is an array of zeros.
I tested batch sizes 1, 7, 8, 64.
To train on CPU i used this command:
```
with tf.device('/job:localhost/replica:0/task:0/device:CPU:0'):
```
or just used Colab version with only CPU, which gives the same results.

Same behaviour occured when I was training this model on real data: fitting immediately led to NaN loss when some batch had less than 8 image-label pairs in it, for example when last batch in dataset was smaller.

I guess that it can be caused by less-precise float on TPU or by some error in parallel calculations on 8 TPU cores (/device:TPU:0, ..., /device:TPU:7).

**Comment by ravikyram** [comment]
I am able to reproduce the issue in colab with TF version 2.2.But i am seeing different error message with TF version 2.3-rc1 and nightly version(`2.4.0-dev20200722`) and i am seeing different error message(`InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=_Send; signature=tensor:T -> ; attr=T:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>; NodeDef: {{node _Send}}`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e3ea5e72d7e2866d2e162b6b317173f9/untitled174.ipynb).Thanks!

**Comment by sedol1339** [comment]
With tf-nightly TPU cannot be even initialized
https://github.com/tensorflow/tensorflow/issues/41542

**Comment by nikitamaia** [comment]
Thanks for this report @sedol1339. Regarding the NaNs, I don't think this is too surprising given the small batch size. And I suspect they are caused by all the batch norm layers within Xception. At a batch size of 7 if you set:

```
for layer in xception.layers:
  layer.trainable = False
```

then I am not seeing the NaNs. With batch norm, you're dividing by local batch statistics on each core, so with a global batch size < 8 on TPUs, the batch is being split for each core and you are more likely to divide by numbers close to 0.

**Comment by sedol1339** [comment]
So isn't it a bug? I thought that using TPU should not affect such things. Why system cannot use less than 8 cores if batch size if less that 8?

**Comment by nikitamaia** [comment]
No, I don't think it's a bug because batch norm would have problems at such a low global batch size. There's no way for the system to utilize fewer cores even if the batch size is smaller than the number of cores.

**Comment by sedol1339** [comment]
@nikitamaia I think i was too hasty to close the ticket, because this problem happens not only when you specify small batch size. Yes, batch size should be large enough for TPU.

But when you split dataset into large batches, the last batch may be very small. In this case loss will immediately become NaN. It's may be hard to understand the reason of NaN loss in this situation. So this behaviour should be eigther fixed or clearly written in TPU documentation.

**Comment by aigagror** [comment]
I had this same issue and after reading your comment, I dropped the last remaining batch and it fixed it for me! Thanks!

**Comment by kechan** [comment]
I ran into this problem too. I thought it must be data specific since i got this after constructing a bigger dataset and everything else was the same as before (it worked before). Reading this thread helps, it seems the solution is to not include the last batch? Is this still a bug or a hard requirement for TPU? I am guessing that my older dataset was lucky that its last batch is the same as the batch_size (i.e. no remainder smaller batch).

**Comment by tchaye59** [comment]
I spent quite some time debugging the `NaN` issue in my system and finally realized this is the issue. For ex: If you have 101 classes and you encode labels from 1-101, your model will always have a `NaN`! Because 101 is greater than the size of the logits!

Can we have at least a Warning popping up, instead of simply showing that the loss diverged with a NaN? That can bring down the debugging time to a great extent for many users.

_Originally posted by @kartik-hegde in https://github.com/tensorflow/tensorflow/issues/8484#issuecomment-354376609_

I also got the same error. It was because of the classes mismatch between the network output and the target classes

**Comment by omersavas26** [comment]
I have similar problem. I try to generate new image with gans model on google cloud tpu (v2.8). But some time i give nan value as loss and after i check to model weights, i see all weights are nan.

My code is:
`def build_generator(channels = CHANNELS, gf = GF, img_shape = IMG_SHAPE):
  def conv2d(layer_input, filters, f_size=4, bn=True):
    d = Conv2D(filters, kernel_size=f_size, strides=2, padding='same')(layer_input)
    d = LeakyReLU(alpha=0.2)(d)
    if bn:
      d = BatchNormalization(momentum=0.8)(d)
    return d

  def deconv2d(layer_input, skip_input, filters, f_size=4, dropout_rate=0):
    u = UpSampling2D(size=2)(layer_input)
    u = Conv2D(filters, kernel_size=f_size, strides=1, padding='same', activation='relu')(u)
    if dropout_rate:
      u = Dropout(dropout_rate)(u)
    u = BatchNormalization(momentum=0.8)(u)
    u = Concatenate()([u, skip_input]) #skip connection
    return u

  
  d0 = Input(shape=img_shape)

  # Downsampling
  d1 = conv2d(d0, gf, bn=False)
  d2 = conv2d(d1, gf*2)
  d3 = conv2d(d2, gf*4)
  d4 = conv2d(d3, gf*8)
  d5 = conv2d(d4, gf*8)
  d6 = conv2d(d5, gf*8)
  d7 = conv2d(d6, gf*8)

  # Upsampling
  u1 = deconv2d(d7, d6, gf*8)
  u2 = deconv2d(u1, d5, gf*8)
  u3 = deconv2d(u2, d4, gf*8)
  u4 = deconv2d(u3, d3, gf*4)
  u5 = deconv2d(u4, d2, gf*2)
  u6 = deconv2d(u5, d1, gf)

  u7 = UpSampling2D(size=2)(u6)
  output_img = Conv2D(channels, kernel_size=4, strides=1, padding='same', activation='tanh')(u7)

  return Model(d0, output_img)

def build_discriminator(df = DF, img_shape = IMG_SHAPE):
  def d_layer(layer_input, filters, f_size=4, bn=True):
      
      d = Conv2D(filters, kernel_size=f_size, strides=2, padding='same')(layer_input)
      d = LeakyReLU(alpha=0.2)(d)
      if bn:
          d = BatchNormalization(momentum=0.8)(d)
      return d

  img_Y = Input(shape=img_shape)
  img_X = Input(shape=img_shape)

  # Concatenate image and conditioning image by channels to produce input
  combined_imgs = Concatenate(axis=-1)([img_Y, img_X])

  d1 = d_layer(combined_imgs, df, bn=False)
  d2 = d_layer(d1, df*2)
  d3 = d_layer(d2, df*4)
  d4 = d_layer(d3, df*8)

  validity = Conv2D(1, kernel_size=4, strides=1, padding='same')(d4)

  return Model([img_Y, img_X], validity)


resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='local')
tf.config.experimental_connect_to_cluster(resolver)
# This is the TPU initialization code that has to be at the beginning.
tf.tpu.experimental.initialize_tpu_system(resolver)
print("All devices: ", tf.config.list_logical_devices('TPU')) 

strategy = tf.distribute.TPUStrategy(resolver)



with strategy.scope():
    optimizer = Adam(0.0002, 0.5)

    discriminator = build_discriminator()
    discriminator.compile(loss='mse', optimizer=optimizer, metrics=['accuracy'])

    # Build the generator
    generator = build_generator()

    # Input images and their conditioning images
    img_Y = Input(shape=IMG_SHAPE)
    img_X = Input(shape=IMG_SHAPE)

    # By conditioning on B generate a fake version of A
    fake_Y = generator(img_X)

    # For the combined model we will only train the generator
    discriminator.trainable = False

    # Discriminators determines validity of translated images / condition pairs
    valid = discriminator([fake_Y, img_Y])

    combined = Model(inputs=[img_Y, img_X], outputs=[valid, fake_Y])
    combined.compile(loss=['mse', 'mae'], loss_weights=[1, 100], optimizer=optimizer)




def train(epochs, batch_size=1, interval=10, disc_patch = DISC_PATCH, load_hour=0, debug = DEBUG):
    global WEIGHT_PATH 

    valid = np.ones((batch_size,) + disc_patch)
    fake = np.zeros((batch_size,) + disc_patch)

    for epoch in range(epochs):

        e_start_time = datetime.datetime.now()

        for batch_i, (imgs_Y, imgs_X) in enumerate(load_batch(Y_IMAGE_PATH, X_IMAGE_PATH, batch_size = batch_size)):

            print("A ", imgs_X.shape, generator.weights[0][0][0][0][0])

            if imgs_Y.shape[0] < batch_size:
                print("small size: "+str(imgs_Y.shape[0]))
                continue

            b_start_time = datetime.datetime.now()

            fake_Y = generator.predict(imgs_X) 

            #sometime i give uncorrect shape. for example (batch_size*2, 128, 128, 3). After i clear zero items in array
            temp = []
            for im in fake_Y:
                if im[0][0][0] == 0.0:
                    continue
                temp.append(im)
            fake_Y = np.array(temp)

            print("B ", generator.weights[0][0][0][0][0], discriminator.weights[0][0][0][0][0], fake_Y.shape)

            d_loss_real = discriminator.train_on_batch([imgs_Y, imgs_X], valid)
            print("C ", generator.weights[0][0][0][0][0], discriminator.weights[0][0][0][0][0], d_loss_real[0])

            d_loss_fake = discriminator.train_on_batch([fake_Y, imgs_X], fake)
            print("D ", generator.weights[0][0][0][0][0], discriminator.weights[0][0][0][0][0], d_loss_fake[0])

            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)
            g_loss = combined.train_on_batch([imgs_Y, imgs_X], [valid, fake_Y])
            print("E ", generator.weights[0][0][0][0][0], discriminator.weights[0][0][0][0][0], g_loss[0], valid.shape)



            b_time = datetime.datetime.now() - b_start_time
            e_time = datetime.datetime.now() - e_start_time
            s_time = datetime.datetime.now() - start_time

            print("F ", generator.weights[0][0][0][0][0], fake_Y[0][0][0][0], d_loss_real[0], d_loss_fake[0], g_loss[0])
            
         

`

and my responses is:

A  (16, 128, 128, 3) tf.Tensor(-0.06954389, shape=(), dtype=float32)
B  tf.Tensor(-0.06954389, shape=(), dtype=float32) tf.Tensor(-0.042074002, shape=(), dtype=float32) (16, 128, 128, 3)
C  tf.Tensor(-0.06954389, shape=(), dtype=float32) tf.Tensor(-0.042074002, shape=(), dtype=float32) 2.5190601348876953
D  tf.Tensor(-0.06954389, shape=(), dtype=float32) tf.Tensor(-0.042074002, shape=(), dtype=float32) 2.438002586364746
E  tf.Tensor(nan, shape=(), dtype=float32) tf.Tensor(-0.042074002, shape=(), dtype=float32) **nan** (16, 8, 8, 1)
F  **tf.Tensor(nan, shape=(), dtype=float32)** 0.031393494 2.5190601348876953 2.438002586364746 **nan**


Mean is "g_loss = combined.train_on_batch([imgs_Y, imgs_X], [valid, fake_Y])" line make nan all weight and g_loss variable

How can i fix it?

Regards.

**Comment by dhruvkej9** [comment]
@sedol1339 @omersavas26 add these in model.fit and it will work fine
steps_per_epoch = train.shape[0]//batch_Size
validation_steps = validate.shape[0]//batch_Size

This is the solution for fixing the problem
