### ISSUE TITLE
ResourceExhaustedError (out of memory) when training a Saved Model

### ISSUE THREAD

**Issue by OlegPonomaryov** [tensorflow/tensorflow#41780]
**System information**
- **OS Platform and Distribution:** Linux Ubuntu 18.04.4 64-bit
- **TensorFlow installed from:** pip
- **TensorFlow version:** 2.3.0-rc2 and 2.4.0-dev20200727
- **Python version:** 3.7.6
- **CUDA/cuDNN version:** CUDA 10.1, cuDNN 7.6.4.38
- **GPU model and memory:** RTX 2060 Super (8 GB)

**Describe the current behavior**
When building a model with a pretrained Xception net as base, than saving it in the Saved Model format, loading and running fit(), ResourceExhaustedError (out of memory) occurs.

**Describe the expected behavior**
When training the model with the same dataset, but without saving or if the Keras H5 format is used, everything is alright, so it looks like there is actually enough GPU memory and the loaded Saved Model should also train without errors. I've also tried replacing Xception with InceptionV3 and this removes the error.

**Standalone code to reproduce the issue**
https://github.com/OlegPonomaryov/xception-saved-model-bug-demo/blob/master/model.ipynb

**Comment by Saduf2019** [comment]
@OlegPonomaryov 
I am unable to access the link shared for the code, please provide with simple stand alone code for us to replicate the issue or if possible share a colab gist with the error faced.

**Comment by OlegPonomaryov** [comment]
@Saduf2019 
Sorry, I've made the repository private by mistake, please, try the link again, now it works.

**Comment by Saduf2019** [comment]
@OlegPonomaryov
I ran the code shared and do not face any error as in the repository, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d9eb0bcb587dbcbb2010495950cb968e/untitled309.ipynb)

**Comment by OlegPonomaryov** [comment]
@Saduf2019 
Thank you for the response.

> I ran the code shared and do not face any error as in the repository, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d9eb0bcb587dbcbb2010495950cb968e/untitled309.ipynb)

Were you using GPU or CPU for training? 26s/step when training looks more like a CPU performance, however, I think, a GPU is needed to reproduce this issue. Maybe the issue is even more specific, like occurring only on GPUs with the same memory amount as mine or maybe even of the same series. I understand, that this, unfortunately, makes the issue much harder to reproduce.

> Please try[ limiting GPU memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and check if you are still facing the same issue.

Thank you, I've tried setting memory_limit=4096, and there is still this error with the loaded Saved Model, but everything is OK with the other models. This is quiet interesting, because while the other models can work even with 4 GB of GPU memory, the loaded Saved Model throws ResourceExhaustedError even with all 8 GB available.

> Below are few issues with same error:
> [link](https://stackoverflow.com/questions/59394947/how-to-fix-resourceexhaustederror-oom-when-allocating-tensor) [link1](https://github.com/balancap/SSD-Tensorflow/issues/267) [link2](https://www.kaggle.com/c/siim-acr-pneumothorax-segmentation/discussion/97660)

These and other discussions of similar issues I've stumbled upon suggest to reduce either a model or an input size. However, in my case exactly the same models work well with exactly the same input data, but only the loaded Saved Model causes OOM. This makes me think, that there might be some bug with memory allocation specific for the loaded Saved Model.

**Comment by nikitamaia** [comment]
Hi @OlegPonomaryov, I have tried the code you shared in colab on the GPU runtime, and I'm not seeing an issue (to reproduce this, you can use the gist provided by @Saduf2019 but change the runtime type to GPU). I've also run this in GCP with a K80 and still do not see the error. 
Strangely the error message in your notebook seems to be referencing TF1 `report_tensor_allocations_upon_oom`. But that being said did you try and follow what was suggested in the error message?

As a first experiment, since you have the saved model, can you try (in a new notebook environment) just loading the model and training? Do you still see the error in that case?

**Comment by OlegPonomaryov** [comment]
Hi @nikitamaia, sorry for late reply. Thank you for hints, I've tried just loading the Saved Model  and have encountered the same error. When loading just Keras H5 model, everything is still alright.

As for `report_tensor_allocations_upon_oom`, I haven't found a way to set `RunOptions` for `tf.keras` models. However, I've tried profiling memory usage with Tensorboard (using `tensorboard-plugin-profile`).

Here is [a branch]( https://github.com/OlegPonomaryov/xception-saved-model-bug-demo/tree/saved-model-only), that contains the notebook modified to just load the Saved Model and to collect Tensorboard logs when running fit() (logs are also there).

Here is [a similar branch](https://github.com/OlegPonomaryov/xception-saved-model-bug-demo/tree/h5-model-only) but with the Keras H5 model.

Unfortunately, sharing the profile plugin logs through [tensorboard.dev](https://tensorboard.dev/) currently is not supported, so I guess the only way to view them is to download them and open in your local instance of Tensorboard. Alternatively, here are [screenshots](https://imgur.com/a/UDDBhwG) of memory profiling tabs both for the Saved Model and Keras H5 model.

I notice differences in Peak Heap Usage and Peak Memory Usage, but I don't see any operations in the Memory Breakdown Table that consume too much memory. However, I have zero experience with Tensorboard profiling, so might just be missing some obvious things.

**Comment by nikitamaia** [comment]
Thanks for sharing these screenshots. I also ran some experiments using the colab GPU runtime, which is a T4 with ~15GB. I ran for 3 epochs and noticed the peak memory usage for the H5 model was about the same as what you saw (~3.6GB) but close to 10GB for the savedmodel, which probably explains why you're getting the resource exhausted error on an 8GB device. 

Can you run some similar experiments for InceptionV3 since you said that worked for you? I'm curious what the difference will be between H5 and savedmodel peak memory usage, since the almost 3x difference for Xception does seem awfully high.

**Comment by OlegPonomaryov** [comment]
@nikitamaia So I've tested this with 3 other models (including InceptionV3). In all 3 cases there was no OOM error, so Tensorboard was able to log peak memory usage through all training process. Here are the results:

## InceptionV3
### Saved Model
Peak Heap Usage 5.13 GiBs
Peak Memory Usage 5.13 GiBs
### Keras H5
Peak Heap Usage 2.63 GiBs
Peak Memory Usage 2.63 GiBs

## MobileNetV2
### Saved Model
Peak Heap Usage 4.41 GiBs
Peak Memory Usage 4.41 GiBs
### Keras H5
Peak Heap Usage 2.11 GiBs
Peak Memory Usage 2.11 GiBs


## ResNet50V2
### Saved Model
Peak Heap Usage 6.62 GiBs
Peak Memory Usage 6.62 GiBs
### Keras H5
Peak Heap Usage 3.62 GiBs
Peak Memory Usage 3.62 GiBs

In all experiments a model loaded from tjhe Keras H5 used approximately 2 times less GPU memory than a model loaded from the Saved Model. So it looks like a performance issue with the Saved Model in general rather then with the Xception model (of course if there is no mistake in my code that I've missed).

**Comment by OlegPonomaryov** [comment]
A little bit more experiments.

I've tried replacing .fit(dataset, epochs=1) with .predict(dataset)
in both notebooks.
Everything runs OK, Peak Heap Usage and Peak Memory Usage are 3.62 GiBs for the Saved Model and 3.63 GiBs for the Keras H5. So the problem seemd to be specifically with the predict() method.

I've tried replacing
with tf.profiler.experimental.Profile(SAVED_MODEL_PROFILING_LOG):
    saved_model.fit(dataset, epochs=1)

with
saved_model_copy = tf.keras.models.Sequential(saved_model.layers)
saved_model_copy.compile(loss="categorical_crossentropy")
with tf.profiler.experimental.Profile(SAVED_MODEL_PROFILING_LOG):
    saved_model_copy.fit(dataset, epochs=1)

Everything runs OK, Peak Heap Usage and Peak Memory Usage are 3.62 GiBs

**Comment by OlegPonomaryov** [comment]
A little bit more experiments. I\ve tried replacing `.fit(dataset, epochs=1)` with `.predict(dataset)` in both ["Saved Model only"](https://github.com/OlegPonomaryov/xception-saved-model-bug-demo/tree/saved-model-only) and ["Keras H5 only"](https://github.com/OlegPonomaryov/xception-saved-model-bug-demo/tree/h5-model-only) notebooks. Everything runs OK, Peak Heap Usage and Peak Memory Usage are 3.62 GiBs for the Saved Model and 3.63 GiBs for the Keras H5. So the problem seems to be specifically with the `fit()` method.

I've also tried to make a "copy" of the loaded Saved Model by replacing
```
with tf.profiler.experimental.Profile(SAVED_MODEL_PROFILING_LOG):
    saved_model.fit(dataset, epochs=1)
```
with
```
saved_model_copy = tf.keras.models.Sequential(saved_model.layers)
saved_model_copy.compile(loss="categorical_crossentropy")
with tf.profiler.experimental.Profile(SAVED_MODEL_PROFILING_LOG):
    saved_model_copy.fit(dataset, epochs=1)
```
in the "Saved Model only" notebook.
I've actually done it already in the initial notebook, just wanted to check memory usage with Tensorboard. Everything also runs OK, Peak Heap Usage and Peak Memory Usage are 3.62 GiBs.

**Comment by OlegPonomaryov** [comment]
And another update, I've also tried the VGG16 and here are the results:
### Saved Model
**Peak Heap Usage:** 0.20 GiBs
**Peak Memory Usage:** 5.83 GiBs
### Keras H5
**Peak Heap Usage:** 5.22 GiBs
**Peak Memory Usage:** 5.22 GiBs

So in contrast to other models, in this case Peak Memory Usage of the Saved Model is just a little bit higher compared to the Keras H5. The Saved Model also has an oddly low  Peak Heap Usage, but this happens sometimes, I think it's caused by some Tensorboard behavior rather than by the model itself.

**Comment by sachinprasadhs** [comment]
I have tried to limit the GPU memory to 4096 and run the `Xception` model and I did not get any `ResourceExhaustedErrror` please find the Tensorflow 2.7 gist [here](https://colab.research.google.com/gist/sachinprasadhs/2bbf5d1bdf2a5d7b2fbae9e5a78ad921/untitled309.ipynb). Thanks!
