### ISSUE TITLE
Error output shape of `tf.gather` in tflite

### ISSUE THREAD

**Issue by KangGrandesty** [tensorflow/tensorflow#41804]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.15.0

---

`tf.gather` has error behavior in tflite model.

My script:

```python
import os

import tensorflow as tf
from tensorflow.contrib import quantize as contrib_quantize

os.environ['CUDA_VISIBLE_DEVICES'] = ''
MODEL = './test.tflite'


def convert():
    with tf.Graph().as_default() as g:
        with tf.Session() as sess:
            data = tf.placeholder('float32', [1, 512, 2], name='data')
            indices = tf.placeholder('int64', [1, 1], name='indices')
            output = tf.gather(data, indices, batch_dims=1)

            # Tensor("GatherV2:0", shape=(1, 1, 2), dtype=float32)
            print(output)
            contrib_quantize.experimental_create_eval_graph(
                input_graph=g)
            converter = tf.lite.TFLiteConverter.from_session(
                sess,
                input_tensors=[data, indices],
                output_tensors=[output])
            tflite_model = converter.convert()
            with open(MODEL, "wb") as w:
                w.write(tflite_model)


def load():
    interpreter = tf.lite.Interpreter(MODEL)
    interpreter.allocate_tensors()
    output_details = interpreter.get_output_details()

    # [
    # {'name': 'GatherV2', 'index': 0,
    # 'shape': array([1, 1, 1, 2], dtype=int32),
    # 'dtype': <class 'numpy.float32'>,
    # 'quantization': (0.0, 0)}
    # ]
    print(output_details)


if __name__ == '__main__':
    convert()
    load()

```

The shape of `output` is `[1, 1, 2]` in graph, but its `[1, 1, 1, 2]` in tflite.

**logs**

```bash
2020-07-28 16:41:55.462113: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-28 16:41:56.271049: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-07-28 16:41:56.271163: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ubun
2020-07-28 16:41:56.271185: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ubun
2020-07-28 16:41:56.271414: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 410.48.0
2020-07-28 16:41:56.271483: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 410.48.0
2020-07-28 16:41:56.271502: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 410.48.0
2020-07-28 16:41:56.272061: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2020-07-28 16:41:56.304875: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394405000 Hz
2020-07-28 16:41:56.308426: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d426dd1c60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-28 16:41:56.308484: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

Tensor("GatherV2:0", shape=(1, 1, 2), dtype=float32)
2020-07-28 16:41:56.323565: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-07-28 16:41:56.323821: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-07-28 16:41:56.327368: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2020-07-28 16:41:56.327398: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   function_optimizer: function_optimizer did nothing. time = 0.008ms.
2020-07-28 16:41:56.327411: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-07-28 16:41:56.332508: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-07-28 16:41:56.332641: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-07-28 16:41:56.342305: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2020-07-28 16:41:56.342358: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 4 nodes (0), 3 edges (0), time = 4.117ms.
2020-07-28 16:41:56.342383: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 4 nodes (0), 3 edges (0), time = 0.212ms.
[{'name': 'GatherV2', 'index': 0, 'shape': array([1, 1, 1, 2], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 1.15 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/84aa3653703cc8f9248d8416cd0ab8f3/untitled192.ipynb).Thanks!

**Comment by mihaimaruseac** [comment]
Can you try on 2.3 / nightly?

**Comment by KangGrandesty** [comment]
@mihaimaruseac . I try the tf2.3 in colab[[here](https://colab.research.google.com/drive/11PhuxdgaZ9SlU0-cylp4K5zN_R61CP1b#scrollTo=3urVVjb9Ouu6)]. `tf.gather` works with no error occurred!

It seems this problem is disappeared in tf2.x. But in tf1.x, it is still confused.

**Comment by mihaimaruseac** [comment]
We won't be able to fix 1.x behavior as that is outside of the patch policy. Recommended path is to update to TF2.3

**Comment by KangGrandesty** [comment]
Ok! I will try to update my code.
