### ISSUE TITLE
 Could not dlopen library 'libcudnn.so.7' for CUDA9.1

### ISSUE THREAD

**Issue by marlon-shiftone** [tensorflow/tensorflow#42156]
I'm using CUDA9.1 and tensorflow version 1.14.0.   When I run the code it is not using the GPUs. It seems it started once I've update the Keras version. Anyway I get this error:

```
2020-08-08 19:17:16.746067: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2020-08-08 19:17:16.747865: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-08-08 19:17:16.749660: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2020-08-08 19:17:16.750029: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2020-08-08 19:17:16.752270: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2020-08-08 19:17:16.753794: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2020-08-08 19:17:16.754002: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-9.0/lib64:/usr/local/cuda/lib64:/usr/local/cuda-9.1/lib64:
2020-08-08 19:17:16.754018: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2020-08-08 19:17:16.754071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-08 19:17:16.754089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1
2020-08-08 19:17:16.754097: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N Y
2020-08-08 19:17:16.754103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   Y N
2020-08-08 19:17:16.762468: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e828a90720 executing computations on platform CUDA. Devices:
2020-08-08 19:17:16.762491: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla V100-SXM2-32GB, Compute Capability 7.0
2020-08-08 19:17:16.762499: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): Tesla V100-SXM2-32GB, Compute Capability 7.0
2020-08-08 19:17:16.961125: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
W0808 19:17:17.188626 140541490861888 deprecation_wrapper.py:119] From /home/shiftone/vsd-shiftone/env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.
```

**Comment by Srikeshram** [comment]
Try installing CUDnn....

**Comment by marlon-shiftone** [comment]
Problem is solved! Thank you very much!

**Comment by Srikeshram** [comment]
Thank You....

**Comment by Saduf2019** [comment]
@marlon-shiftone 
Please move the issue to closed status if resolved.
