### ISSUE TITLE
CUBLAS_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by chocolate-skyr** [tensorflow/tensorflow#42298]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tf-nightly
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: GeFroce 2080 Ti (X2)

**Describe the problem**
I'm struggling to get off the ground here with multi-gpu tensorflow.  I've eventually gotten stuck with"cublas not initialized."  Thank you for having a look. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # Create 2 virtual GPUs with 1GB memory each
  try:
    tf.config.experimental.set_virtual_device_configuration(
        gpus[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024),
         tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPU,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)

mirrored_strategy = tf.distribute.MirroredStrategy()

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train[:,:,:,np.newaxis] / 255.0
x_test = x_test[:,:,:,np.newaxis] / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

with mirrored_strategy.scope():
    model4 = Sequential()
    model4.add(Conv2D(filters=64, kernel_size=2, padding='same', activation='relu', input_shape=(28,28, 1))) 
    model4.add(Conv2D(filters=64, kernel_size=2))
    model4.add(MaxPooling2D(pool_size=2))
    model4.add(Flatten())
    model4.add(Dense(10, activation='softmax'))

model4.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model4.summary()

model4.fit(x_train, y_train, epochs=2, validation_split=0.1)

_, test_acc = model4.evaluate(x_test, y_test)
print(test_acc)

model4.save_weights('cnn.h5')

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

(base_gpu) C:\Users\Mo\BTC>python test.py
2020-08-12 23:09:37.482332: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-08-12 23:09:40.326028: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-08-12 23:09:40.483740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:67:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-12 23:09:40.497852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:68:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-12 23:09:40.515569: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-08-12 23:09:40.530217: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-08-12 23:09:40.545759: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll 
2020-08-12 23:09:40.552588: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-08-12 23:09:40.566705: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-08-12 23:09:40.574656: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-08-12 23:09:40.597844: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-08-12 23:09:40.602568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
Num GPUs Available:  2
2020-08-12 23:09:40.606521: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-12 23:09:40.672282: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x227a512f230 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-12 23:09:40.700825: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-12 23:09:41.131362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:67:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-12 23:09:41.146897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:68:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-12 23:09:41.183979: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-08-12 23:09:41.228784: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-08-12 23:09:41.251706: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-08-12 23:09:41.259688: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-08-12 23:09:41.303717: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-08-12 23:09:41.328316: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-08-12 23:09:41.353029: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-08-12 23:09:41.379921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-08-12 23:09:42.687780: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-12 23:09:42.695670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 
2020-08-12 23:09:42.700946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N N
2020-08-12 23:09:42.723277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   N N 
2020-08-12 23:09:42.747771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1024 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:67:00.0, compute capability: 7.5)
2020-08-12 23:09:42.782663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 1024 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:67:00.0, compute capability: 7.5)
2020-08-12 23:09:42.814118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 8582 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:68:00.0, compute capability: 7.5)
2020-08-12 23:09:42.864267: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x22831d21960 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-12 23:09:42.889142: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-08-12 23:09:42.914052: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2 Physical GPU, 3 Logical GPUs
WARNING:tensorflow:NCCL is not supported when using virtual GPUs, fallingback to reduction to one device
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 28, 28, 64)        320
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 27, 27, 64)        16448     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 64)        0
_________________________________________________________________
flatten (Flatten)            (None, 10816)             0
_________________________________________________________________
dense (Dense)                (None, 10)                108170
=================================================================
Total params: 124,938
Trainable params: 124,938
Non-trainable params: 0
_________________________________________________________________
2020-08-12 23:09:44.300510: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
Epoch 1/2
2020-08-12 23:09:47.355213: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-08-12 23:09:47.364005: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.387331: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.431316: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.473173: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.491439: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.499352: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.539511: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.569205: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.593318: E tensorflow/stream_executor/cuda/cuda_blas.cc:225] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.605302: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-08-12 23:09:47.643972: E tensorflow/stream_executor/cuda/cuda_dnn.cc:325] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.643972: E tensorflow/stream_executor/cuda/cuda_dnn.cc:325] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.673588: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-08-12 23:09:47.649853: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-08-12 23:09:47.700174: E tensorflow/stream_executor/cuda/cuda_dnn.cc:325] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.723925: E tensorflow/stream_executor/cuda/cuda_dnn.cc:325] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.746358: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-08-12 23:09:47.769343: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-08-12 23:09:47.819798: E tensorflow/stream_executor/cuda/cuda_dnn.cc:325] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.844975: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-08-12 23:09:47.870709: E tensorflow/stream_executor/cuda/cuda_dnn.cc:325] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-08-12 23:09:47.880941: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    model4.fit(x_train, y_train, epochs=2, validation_split=0.1)
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\keras\engine\training.py", line 103, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1102, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\eager\def_function.py", line 787, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\eager\def_function.py", line 847, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\eager\function.py", line 2922, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1853, in _filtered_call
    return self._call_flat(
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\eager\function.py", line 1933, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\eager\function.py", line 552, in call
    outputs = execute.execute(
  File "C:\Users\Mo\anaconda3\envs\base_gpu\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: 4 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node replica_2/sequential/conv2d/Conv2D (defined at C:\Users\Mo\anaconda3\envs\base_gpu\lib\threading.py:932) ]]
         [[div_no_nan_1/ReadVariableOp_4/_88]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node replica_2/sequential/conv2d/Conv2D (defined at C:\Users\Mo\anaconda3\envs\base_gpu\lib\threading.py:932) ]]
  (2) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node replica_2/sequential/conv2d/Conv2D (defined at C:\Users\Mo\anaconda3\envs\base_gpu\lib\threading.py:932) ]]
         [[gradient_tape/replica_1/sequential/conv2d/BiasAdd/BiasAddGrad/_144]]
  (3) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node replica_2/sequential/conv2d/Conv2D (defined at C:\Users\Mo\anaconda3\envs\base_gpu\lib\threading.py:932) ]]
         [[AddN_2/_132]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_3014]

**Comment by ravikyram** [comment]
@chocolate-skyr 

Can you see the issues with similar error #35029, #9489 and see if it helps you.Thanks!

**Comment by chocolate-skyr** [comment]
Thank you.  What ended up working fixing my issue was:
reinstalling python with conda which downgraded the cuda toolkit / cudnn to appropriate versions

**Comment by ravikyram** [comment]
@chocolate-skyr 

Glad to know your issue was resolved.Please, close this thread as your issue was resolved. Thanks!
