### ISSUE TITLE
cudart64_101.dll and nvcuda.dll not found

### ISSUE THREAD

**Issue by nickums** [tensorflow/tensorflow#42436]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1.  It must be a bug, a feature request, or a significant problem with the
    documentation (for small docs fixes please send a PR instead).
2.  The form below must be filled out.
3.  It shouldn't be a TensorBoard issue. Those go
    [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**:
-   **Python version**:
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by nickums** [comment]
Unlike the problem where the use had a GPU, I do not have one (as far as I know),
I am using latest Tensorflow on windows10 with Python3.7     Here is my Traceback:
Using TensorFlow backend.
2020-08-17 18:29:14.951355: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-17 18:29:14.962198: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-08-17 18:30:32.541365: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-08-17 18:30:32.552535: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-17 18:30:32.806754: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: my-pc
2020-08-17 18:30:32.824316: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: my-pc
2020-08-17 18:30:33.789209: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1d8417a3ed0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-17 18:30:33.812819: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):

**Comment by Saduf2019** [comment]
@nickums 
Please find which directory these dlls are in, and then update your PATH to include that directory. 
also make sure you update appropriate cuda environment paths.
See [https://www.tensorflow.org/install/gpu#software_requirements](https://www.tensorflow.org/install/gpu#software_requirements)


#36111 #41909 #42354 [link](https://stackoverflow.com/questions/59823283/could-not-load-dynamic-library-cudart64-101-dll-on-tensorflow-cpu-only-install) [link1](https://python-forum.io/Thread-Tensorflow-cudart64-101-dll-could-not-find-dll) for the path of these files.
[link2](https://stackoverflow.com/questions/49397373/tensorflow-gpu-importerror-could-not-find-nvcuda-dll/49397448) nvcuda.dll related error.

**Comment by nickums** [comment]
Thanks for responding.  Looking at tensorflow hardware requirements, .it seems I need an NVIDIA GPU.
Not possible with my humble laptop so I'll start again with the 'lite' android-oriented version.

**Comment by Saduf2019** [comment]
@nickums 
Please move this issue to resolved status if this is not an issue anymore.

**Comment by nickums** [comment]
lite is not the answer, stil need to create models with tensorflow 1st.
But can image processing be done without an NVIDIA GPU?

**Comment by Saduf2019** [comment]
@nickums 
It would be slow,please try colab and let us know.

**Comment by nickums** [comment]
now I've relocated nvcuda.dll  to the python DLL directory the error no oonger occurs, and my program is running
albeit without a GPU.

**Comment by Saduf2019** [comment]
@nickums 
Thanks for your update, glad the issue is resolved.

**Comment by nickums** [comment]
thankyouvery much  for bringing colab to my attention, enabling me to use a GPU.  
Without one my code runs for hours....
