### ISSUE TITLE
Error executing quickstart noteboook

### ISSUE THREAD

**Issue by Fetzii** [tensorflow/tensorflow#42463]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win 10
-   **TensorFlow installed from (source or binary)**: conda gpu version
-   **TensorFlow version (use command below)**: 2.1.0
-   **Python version**: 3.7.7
-   **CUDA/cuDNN version**: cudatoolkit - 10.1.243 - h74a9793_0 - anaconda
                                                cudnn - 7.6.5 - cuda10.1_0 - anaconda
-   **GPU model and memory**: GTX 750 TI - 2GB

### Describe the problem
I wanted to test the tf quick start notebook: https://tensorflow.google.cn/tutorials/quickstart/advanced and got the following error message:
```UnknownError                              Traceback (most recent call last)
<ipython-input-10-cdcc13267505> in <module>
      9 
     10   for images, labels in train_ds:
---> 11     train_step(images, labels)
     12 
     13   for test_images, test_labels in test_ds:

~\anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

~\anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    630         # Lifting succeeded, so variables are initialized and we can run the
    631         # stateless function.
--> 632         return self._stateless_fn(*args, **kwds)
    633     else:
    634       canon_args, canon_kwds = \

~\anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   2361     with self._lock:
   2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2364 
   2365   @property

~\anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
   1609          if isinstance(t, (ops.Tensor,
   1610                            resource_variable_ops.BaseResourceVariable))),
-> 1611         self.captured_inputs)
   1612 
   1613   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~\anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

~\anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

~\anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~\anaconda3\envs\tf\lib\site-packages\six.py in raise_from(value, from_value)

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node my_model/conv2d/Conv2D (defined at <ipython-input-5-1e051998210b>:10) ]] [Op:__inference_train_step_566]

Errors may have originated from an input operation.
Input Source operations connected to node my_model/conv2d/Conv2D:
 images (defined at <ipython-input-10-cdcc13267505>:11)

Function call stack:
train_step
```

I installed tf, cuda and cudnn using ```conda install -c anaconda tensorflow-gpu```

**Comment by Saduf2019** [comment]
@Fetzii 
Please try limiting GPU memory growth as shown in this [guide here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and let us know if you are facing the same issue. 

Can you please try setting allow_growth option at the top of your code:

```
import tensorflow as tf
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)

# your code 
```

You may refer to similar error issues below:
#41886 #36025  #41196 [link](https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in)

**Comment by Fetzii** [comment]
Solved issue using #36025

**Comment by Saduf2019** [comment]
@Fetzii 
Thank you for your update, glad to hear the issue is resolved.
