### ISSUE TITLE
Successful NUMA node read from SysFS had negative value (-1)

### ISSUE THREAD

**Issue by engrmz** [tensorflow/tensorflow#42738]
Hello everyone,
I am running a tensorflow code on GPU and getting the following warnings and errors. 

```
coreClock: 1.176GHz coreCount: 5 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 74.65GiB/s
2020-08-28 16:02:27.033368: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-28 16:02:27.033380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-28 16:02:27.033390: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-28 16:02:27.033400: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-28 16:02:27.033411: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-28 16:02:27.033421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-28 16:02:27.033431: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-28 16:02:27.033482: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 16:02:27.033732: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 16:02:27.033932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-28 16:02:27.033951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-28 16:02:27.033957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-08-28 16:02:27.033961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 

INFO:tensorflow:Running local_init_op.
I0828 16:08:52.357333 139711269271360 session_manager.py:505] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0828 16:08:52.375836 139711269271360 session_manager.py:508] Done running local_init_op.
2020-08-28 16:08:52.660709: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-28 16:08:53.080643: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-28 16:08:53.190000: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-08-28 16:08:53.218688: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR


tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet18/conv2d/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet18/conv2d/Conv2D}}]]
	 [[add_5/_453]]
0 successful operations.
0 derived errors ignored.
```

1.   successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2.  Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
3. Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

Can anyone please help me in solving these issues? Thanks

-mz

**Comment by amahendrakar** [comment]
@engrmz,
In order to expedite the trouble-shooting process, please provide the complete code, dataset you are using and the below details

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory 

Thanks!

**Comment by amahendrakar** [comment]
@engrmz,
Also, try setting a hard limit on the total GPU memory as shown in [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and let us know if it works. Thanks!

**Comment by engrmz** [comment]
Hi @amahendrakar ,
Thanks for your prompt response. 
Here are the details;

-  I am running the code, CvxNet from [here](https://github.com/tensorflow/graphics/tree/master/tensorflow_graphics/projects/cvxnet)
- Ubuntu 18.04
- Tensorflow=2.2.0
- Python = 3.7.6
- cudatoolkit               10.1.243             h6bb024c_0  
- cudnn                     7.6.5                cuda10.1_0  
- tensorboard               2.2.1              pyh532a8cf_0  
- tensorboard-plugin-wit    1.6.0                      py_0  
- tensorflow                2.2.0           mkl_py37h6e9ce2d_0  
- tensorflow-base           2.2.0           mkl_py37hd506778_0  
- tensorflow-estimator      2.2.0              pyh208ff02_0  
- tensorflow-gpu            2.2.0                     <pip>
- tensorflow-graphics-gpu   1.0.0                     <pip>

- NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0
- GPU GeForce GTX 960M (4046MiB)



By considering your recommendations I used;
```
gpu_devices = tf.config.experimental.list_physical_devices('GPU')
for device in gpu_devices:
    tf.config.experimental.set_memory_growth(device, True)
```
It solves the error, but the warning **NUMA node read from SysFS had negative value (-1)** is still here. Secondly, the output of the code is incorrect (dummy output).

**Comment by engrmz** [comment]
Could it be due to a problem with the Ubuntu? I am thinking to re-install it.

**Comment by amahendrakar** [comment]
@engrmz,
Could you please update TensorFlow to v2.3 and check if you are still facing the same issue. Thanks!

**Comment by mikkeljakobsen** [comment]
> ```
> gpu_devices = tf.config.experimental.list_physical_devices('GPU')
> for device in gpu_devices:
>     tf.config.experimental.set_memory_growth(device, True)
> ```
Thank you. Had the exact same problem. This worked.

**Comment by amahendrakar** [comment]
> Could you please update TensorFlow to v2.3 and check if you are still facing the same issue. Thanks!

@engrmz,
Any updates regarding this issue? Thanks!

**Comment by skaldek** [comment]
Same issue using r2.4 sources on arch.

**Comment by amahendrakar** [comment]
@skaldek,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by xbbkok** [comment]
same problem

**Comment by AndyMcPython** [comment]
here too

**Comment by stefan-falk** [comment]
Same issue on Ubuntu 16.04, Tensorflow 2.5.0

**Comment by yeahQing** [comment]
The same problem occurred in tensorflow r2.5.0 with ubuntu20.04

**Comment by Sur3** [comment]
Same problem with tensorflow-2.5.0-r1 on Gentoo.

**Comment by joaomamede** [comment]
The same problem occurred in TF 2.2.0 with RHEL8.3

**Comment by nsssayom** [comment]
To get rid of this non-fatal warning use this command:
`for a in /sys/bus/pci/devices/*; do echo 0 | sudo tee -a $a/numa_node; done`

For details go to [this question](https://stackoverflow.com/questions/44232898/memoryerror-in-tensorflow-and-successful-numa-node-read-from-sysfs-had-negativ) in stackoverflow.

**Comment by sdbibon** [comment]
> To get rid of this non-fatal warning use this command:
> `for a in /sys/bus/pci/devices/*; do echo 0 | sudo tee -a $a/numa_node; done`
> 
> For details go to [this question](https://stackoverflow.com/questions/44232898/memoryerror-in-tensorflow-and-successful-numa-node-read-from-sysfs-had-negativ) in stackoverflow.

**Comment by Adrian-Yan16** [comment]
@nsssayom this worked for me too, thanks

**Comment by JuanVargas** [comment]
same problem. Ubuntu 21.10. 
Hey TF guys: Wake up. CUDA/GPUs work just fine with Julia on same machine.

**Comment by Nickrader** [comment]
If I understand correctly, most processors have ONE numa node per physical processor (CPU package, not individual cores).
So for anyone not using a server or workstation, this warning should mean little. (i.e. anyone with a normal desktop/laptop setup)

> For x86, there has traditionally been one NUMA node per physical processor package. In this configuration, all cores on the same physical processor belong to a single NUMA node. 
https://iopscience.iop.org/article/10.1088/1742-6596/664/9/092010/pdf

Can use `numactl --hardware` to check on Linux.
https://wiki.xenproject.org/wiki/Xen_on_NUMA_Machines

https://en.wikipedia.org/wiki/Non-uniform_memory_access

**Comment by Ananthzeke** [comment]
https://lapina-tistory-com.translate.goog/137?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-GB
This site has the follow solution

**Comment by Kuramenai** [comment]
It seems like there's a way to fix the numa issue here 
https://gist.github.com/zrruziev/b93e1292bf2ee39284f834ec7397ee9f

**Comment by kaveenkumar** [comment]
> To get rid of this non-fatal warning use this command: `for a in /sys/bus/pci/devices/*; do echo 0 | sudo tee -a $a/numa_node; done`
> 
> For details go to [this question](https://stackoverflow.com/questions/44232898/memoryerror-in-tensorflow-and-successful-numa-node-read-from-sysfs-had-negativ) in stackoverflow.

Worked! thanks.

**Comment by luoxin2002** [comment]
> To get rid of this non-fatal warning use this command: `for a in /sys/bus/pci/devices/*; do echo 0 | sudo tee -a $a/numa_node; done`
> 
> For details go to [this question](https://stackoverflow.com/questions/44232898/memoryerror-in-tensorflow-and-successful-numa-node-read-from-sysfs-had-negativ) in stackoverflow.

it works!!
