### ISSUE TITLE
TF lite fails conversion with post train int quantization, converts fine without: RuntimeError: Mismatch between number of weight maxs and channels

### ISSUE THREAD

**Issue by albertsokol** [tensorflow/tensorflow#43104]
Hey there, I've managed to convert StyleGan2 to a tf lite model with your recent advice, however now upon trying to quantize the model I'm getting an error. The model converts **with no issues** if quantization is not used. It also converts fine with dynamic range quantization, only failing if a **representative dataset** is used. I have replicated the issue on a small part of the full model here.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): tried on tf 2.3, tf nightly 

If possible, please share a link to Colab/Jupyter/any notebook.
**Link to colab notebook with all commands and downloads:**
https://colab.research.google.com/drive/1b-o3cPz_1er_EQC0Ezq-vsTmlH55kmAe?usp=sharing

**Link to SavedModel tar**
https://drive.google.com/file/d/1BdFA3CJ-uDIFrLWMTy9hAWPKTHWp9YCw/view?usp=sharing

**Link to successfully converted tf lite model without post-train quantization**
https://drive.google.com/file/d/157ujWxsnjAuR2tn5es5Oz3rRIYNwmiwO/view?usp=sharing

**Command used to run the converter or code if you’re using the Python API**
Takes in [1, 18, 512] tensor of random input:
```python
samples = []

for i in range(10):
    sample = np.random.randn(1, 18, 512)
    sample = sample.astype(np.float32)
    samples.append(sample)

def representative_data_gen():
    for sample in samples:
        yield [sample]
```

Converter code
```python
converter = tf.lite.TFLiteConverter.from_saved_model('/content/synth_const')
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen

tflite_model = converter.convert()

with tf.io.gfile.GFile('synth_const_opt.tflite', 'wb') as f:
    f.write(tflite_model)
```

**The output from the converter invocation**

```
2020-09-10 11:03:29.887482: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-10 11:03:30.014402: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-10 11:03:32.260056: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.260451: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.260987: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-09-10 11:03:32.261050: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-09-10 11:03:32.261693: I tensorflow/compiler/jit/xla_gpu_device.cc:161] Ignoring visible XLA_GPU_JIT device. Device number is 1, reason: Invalid argument: Invalid device ordinal value (1). Valid range is [0, 0].
2020-09-10 11:03:32.319520: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.319815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6325GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-10 11:03:32.319865: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.320143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:05:00.0 name: GeForce GTX 1050 Ti computeCapability: 6.1
coreClock: 1.392GHz coreCount: 6 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 104.43GiB/s
2020-09-10 11:03:32.320163: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-10 11:03:32.320177: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-10 11:03:32.320188: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-10 11:03:32.320198: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-10 11:03:32.320208: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-10 11:03:32.320218: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-10 11:03:32.320228: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-10 11:03:32.320263: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.320548: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.320844: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.321124: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.321394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1843] Ignoring visible gpu device (device: 1, name: GeForce GTX 1050 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1) with core count: 6. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
2020-09-10 11:03:32.321401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-10 11:03:32.321419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-10 11:03:32.321424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 
2020-09-10 11:03:32.321428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N N 
2020-09-10 11:03:32.321432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   N N 
2020-09-10 11:03:32.321489: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.321776: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.322041: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9842 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-09-10 11:03:32.366684: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
2020-09-10 11:03:32.366717: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 88 nodes (84), 89 edges (86), time = 31.342ms.
2020-09-10 11:03:32.366721: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.045ms.
2020-09-10 11:03:32.479552: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
2020-09-10 11:03:32.479576: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
2020-09-10 11:03:32.498762: I tensorflow/compiler/jit/xla_gpu_device.cc:161] Ignoring visible XLA_GPU_JIT device. Device number is 1, reason: Invalid argument: Invalid device ordinal value (1). Valid range is [0, 0].
2020-09-10 11:03:32.498945: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.499265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.6325GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-09-10 11:03:32.499316: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.499602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:05:00.0 name: GeForce GTX 1050 Ti computeCapability: 6.1
coreClock: 1.392GHz coreCount: 6 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 104.43GiB/s
2020-09-10 11:03:32.499622: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-10 11:03:32.499636: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-10 11:03:32.499645: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-10 11:03:32.499654: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-10 11:03:32.499663: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-10 11:03:32.499672: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-10 11:03:32.499681: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-10 11:03:32.499718: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.500010: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.500314: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.500599: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.500966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1843] Ignoring visible gpu device (device: 1, name: GeForce GTX 1050 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1) with core count: 6. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
2020-09-10 11:03:32.500978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-10 11:03:32.501002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-10 11:03:32.501007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 
2020-09-10 11:03:32.501011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N N 
2020-09-10 11:03:32.501015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   N N 
2020-09-10 11:03:32.501084: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.501389: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-10 11:03:32.501696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9842 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/y4tsu/PycharmProjects/sg2_nhwc_reduced_cleanup/test_pieces.py", line 187, in <module>
    main()
  File "/home/y4tsu/PycharmProjects/sg2_nhwc_reduced_cleanup/test_pieces.py", line 174, in main
    write_synth_const(g_params, convert)
  File "/home/y4tsu/PycharmProjects/sg2_nhwc_reduced_cleanup/test_pieces.py", line 81, in write_synth_const
    tflite_model = converter.convert()
  File "/home/y4tsu/anaconda3/envs/tf2_3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/y4tsu/anaconda3/envs/tf2_3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 899, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "/home/y4tsu/anaconda3/envs/tf2_3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 638, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/y4tsu/anaconda3/envs/tf2_3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 450, in _calibrate_quantize_model
    return calibrate_quantize.calibrate_and_quantize(
  File "/home/y4tsu/anaconda3/envs/tf2_3/lib/python3.8/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 95, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Mismatch between number of weight maxs and channels: 1 vs 512
```

I think the Quantize op is expecting a shape that it's not receiving, but I've tried changing the dimensionality of tensors at various points and I haven't been able to identify the source of the issue. If you have any ideas please let me know!

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/4fcbcbff9c163f9736ceb964702ce8fe/untitled412.ipynb).

**Comment by sunzhe09** [comment]
I met the same problem

**Comment by stalex91** [comment]
Do all ops in the model are in list of supported for quantization?

**Comment by stalex91** [comment]
@liufengdb do you have any update on this issue?

**Comment by sachinprasadhs** [comment]
The issue is fixed in the Tf Nightly 2.6 version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/ced1a80dc4182d664e761aaf803d8c37/43104.ipynb). 
Closing the issue since the issue is fixed, feel free to reopen. Thanks!
