### ISSUE TITLE
cuDNN error when passing all-masked sequences to RNN layers on GPU

### ISSUE THREAD

**Issue by pandrey-fr** [tensorflow/tensorflow#43103]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: CentOS 8
- TensorFlow installed from: binary (pip)
- TensorFlow version: 2.3.0 (v2.3.0-rc2-23-gb36436b087)
- Python version: 3.6.8
- CUDA/cuDNN version: 10.1 / 7
- GPU model and memory: RTX 6000 (24GB)

**Describe the current behavior**

When passing a boolean mask together with data to a RNN layer running on GPU, a cuDNN error is raised if any row of the mask is made entirely of False values, _i.e._ if one of the batched input sequences is made entirely of padding values.

The raised error is the following:
```
UnknownError: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1521): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)' [Op:CudnnRNNV3]
```

This may seem as an edge case, but can be encountered when reshaping a [batch, block, sequence, dimension] tensor with variable-size (therefore zero-padded) blocks of sequences representing e.g. a long text into a [..., sequence, dimension] tensor to be processed at once by a RNN and then reshaped back to [batch, block, rnn_dim].

I was able to implement a work-around using a custom wrapper class, but this does not feel like a righteous solution.

**Describe the expected behavior**

I would expect the RNN to output some default value (e.g. a vector or zeros) representing the all-padding sequence(s), as it does on CPU.

**Standalone code to reproduce the issue**

Minimal code to reproduce the error:

```python
import tensorflow as tf

gru = tf.keras.layers.GRU(128)
rng = tf.random.get_global_generator()
inp = rng.normal((8, 64, 256))
msk = tf.concat([tf.ones((4, 64), dtype=tf.bool), tf.zeros((4, 64), dtype=tf.bool)], axis=0)

# works
with tf.device('CPU:0'):
    gru(inp, mask=msk)
# works
with tf.device('GPU:0'):
    gru(inp, mask=tf.ones_like(msk))
# fails
with tf.device('GPU:0'):
    gru(inp, mask=msk)
```

Workaround I implemented, which "unmasks" all-padding sequences, thus triggering unrequired computations:
```python
import tensorflow as tf

class SafeRNN(tf.keras.layers.Wrapper):
    """Wrapper for keras RNN layers avoiding a mask-caused cuda error."""

    def call(self, inputs, mask=None, **kwargs):
        """Run inputs through the wrapped layer."""
        if mask is not None:
            valid = tf.reduce_any(mask, axis=1, keepdims=True)
            mask = tf.where(valid, mask, tf.ones_like(mask))
        return self.layer(inputs, mask=mask, **kwargs)

    def compute_mask(self, inputs, mask=None):
        """Return an output mask tensor."""
        if mask is None:
            return None
        return tf.reduce_any(mask, axis=1)

gru = SafeRNN(tf.keras.layers.GRU(128))
rng = tf.random.get_global_generator()
inp = rng.normal((8, 64, 256))
msk = tf.concat([tf.ones((4, 64), dtype=tf.bool), tf.zeros((4, 64), dtype=tf.bool)], axis=0)

# works
with tf.device('GPU:0'):
    gru(inp, mask=msk)
```

**Other info**

This issue is not consistent from a system to the other; it does not trigger on my Linux Mint 19.1 system, with the same Python, TensorFlow and CUDA/cuDNN versions (but distinct GPU: Quadro P1000).

**Comment by ravikyram** [comment]
@pandrey-fr 

I have tried in colab with TF nightly version(`2.4.0-dev20200910`) and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/1b31cd0dc4889e6dcbb817e6517bb76d/untitled334.ipynb). Thanks!

**Comment by pandrey-fr** [comment]
Indeed, the issue is solved in nightly. I will therefore use my workaround with the current stable release and discard it when I upgrade to 2.4 after a stable release is issued.
It is a bit tiring to constantly have to maintain / upgrade code to get such apparently-small bug fixes which are not back-ported to previous stable releases, but at least the bug seems fixed; thank you!
