### ISSUE TITLE
kernel version 367.44.0 does not match DSO version 352.99.0

### ISSUE THREAD

**Issue by mattare2** [tensorflow/tensorflow#4349]
I can't seem to load GPUs.  After a first install of CUDA, I didn't have this error, but tensorflow couldn't find any GPUs (despite nvidia-smi finding one).  After a second install based on these instructions: http://tech.marksblogg.com/tensorflow-nvidia-gtx-1080.html I had the following error.

Thanks for your help!

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
-rw-r--r-- 1 root root 189170 Sep 12 23:50 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Sep 12 23:50 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Sep 12 23:50 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Sep 12 23:50 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Sep 12 23:50 /usr/local/cuda/lib/libcudart_static.a

Compiled from:
http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda_7.5.18_linux.run

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/cuda/lib64:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:2259] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.10.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

 tf.Session()
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: XXX
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: XXX
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: 352.99.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.44  Wed Aug 17 22:24:07 PDT 2016
GCC version:  gcc version 4.9.4 (Ubuntu 4.9.4-2ubuntu1~14.04.1) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.44.0
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:296] kernel version 367.44.0 does not match DSO version 352.99.0 -- cannot find working devices in this configuration
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.

**Comment by mattare2** [comment]
Follow these 10 easy steps to success:

1.    Download cuda-8.run file
2.    Download Nvidia-367.18-driver.run file
3.    Remove old drivers (apt remove --purge nvidia*)
4.    (Remove old cuda files (e.g. apt remove --purge libcuda*)
5.    Remove old nvidia.deb packages (just in case that's necessary?)
6.    Remove my cuda folders (/usr/local/cuda*) (again, just in case)
7.    reboot
8.    Run the Nvidia-367.18.run file
9.    run the cuda-8.run file. Decline on installing the old drivers (361?)
10.   reboot

**Comment by BioGeek** [comment]
After removing the NVIDIA drivers with apt remove --purge nvidia*`  and rebooting, I only got a blank screen upon restart. 

Luckily I was still able to log in via a terminal and [install the latest stable NVIDIA drivers](http://askubuntu.com/questions/744419/blank-screen-after-nvidia-install).

But probably there is a better way then just throwing all your drivers away.

**Comment by milangritta** [comment]
Also try rebooting, duh! I was having the same problem after updating packages but I found a solution on stackoverflow. IT WORKED! Before you try a heavy intervention, try restarting, it worked for me 👍

**Comment by yun-long** [comment]
@milangritta Genius !

**Comment by mytrjp** [comment]
I had the same issue, but surprisingly rebooting the desktop worked for me! Before that I was not able to get any information even through 'nvidia-smi'. Now it's working without error !

**Comment by sivakarthikgade** [comment]
Restart solved the issue.

**Comment by Light--** [comment]
> Also try rebooting, duh! I was having the same problem after updating packages but I found a solution on stackoverflow. IT WORKED! Before you try a heavy intervention, try restarting, it worked for me 👍

DO NOTHING AND JUST RESTART YOUR COMPUTER WILL FIX IT !!!!! THANKS!!

**Comment by JianquanWang** [comment]
Rebooting not works for me

**Comment by kevindegila** [comment]
Here to confirm that rebooting work. Try it before anything else.

**Comment by maryamxasghari** [comment]
Can someone help me please with this issue?
Thank you

$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch

2021-10-16 14:56:09.420644: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2021-10-16 14:56:09.420676: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Primer
2021-10-16 14:56:09.420700: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Primer
2021-10-16 14:56:09.420758: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 470.57.2
2021-10-16 14:56:09.420782: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.91.3
2021-10-16 14:56:09.420791: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 460.91.3 does not match DSO version 470.57.2 -- cannot find working devices in this configuration

$ uname -a
Linux Primer 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ nvidia-settings --help

nvidia-settings:  version 470.57.02
  The NVIDIA X Server Settings tool.

$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch

$ sudo prime-select query
nvidia

$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  460.91.03  Fri Jul  2 06:04:10 UTC 2021
GCC version:  gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

$ sudo lspci -v | grep VGA
02:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1) (prog-if 00 [VGA controller])
03:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1) (prog-if 00 [VGA controller])
04:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1) (prog-if 00 [VGA controller])

$ lspci | grep -i nvidia
02:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
02:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
03:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
03:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
04:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
04:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)

$ dpkg -l | grep -i nvidia
ii  cuda-nsight-compute-11-2                        11.2.0-1   amd64        NVIDIA Nsight Compute
ii  cuda-nsight-compute-11-4                        11.4.2-1   amd64        NVIDIA Nsight Compute
ii  cuda-nsight-systems-11-2                        11.2.0-1   amd64        NVIDIA Nsight Systems
ii  cuda-nsight-systems-11-4                        11.4.2-1   amd64        NVIDIA Nsight Systems
ii  cuda-nvtx-11-2                                  11.2.67-1   amd64        NVIDIA Tools Extension
ii  cuda-nvtx-11-4                                  11.4.120-1   amd64        NVIDIA Tools Extension
ii  libaccinj64-10.1:amd64                          10.1.243-3   amd64        NVIDIA ACCINJ Library (64-bit)
ii  libcublas10:amd64                               10.1.243-3   amd64        NVIDIA cuBLAS Library
ii  libcublaslt10:amd64                             10.1.243-3   amd64        NVIDIA cuBLASLt Library
ii  libcudart10.1:amd64                             10.1.243-3   amd64        NVIDIA CUDA Runtime Library
ii  libcufft10:amd64                                10.1.243-3   amd64        NVIDIA cuFFT Library
ii  libcufftw10:amd64                               10.1.243-3   amd64        NVIDIA cuFFTW Library
ii  libcuinj64-10.1:amd64                           10.1.243-3   amd64        NVIDIA CUINJ Library (64-bit)
ii  libcupti-dev:amd64                              10.1.243-3   amd64        NVIDIA CUDA Profiler Tools Interface development files
ii  libcupti-doc                                    10.1.243-3   all          NVIDIA CUDA Profiler Tools Interface documentation
ii  libcupti10.1:amd64                              10.1.243-3   amd64        NVIDIA CUDA Profiler Tools Interface runtime library
ii  libcurand10:amd64                               10.1.243-3   amd64        NVIDIA cuRAND Library
ii  libcusolver10:amd64                             10.1.243-3   amd64        NVIDIA cuSOLVER Library
ii  libcusolvermg10:amd64                           10.1.243-3   amd64        NVIDIA cuSOLVERmg Library
ii  libcusparse10:amd64                             10.1.243-3   amd64        NVIDIA cuSPARSE Library
ii  libnppc10:amd64                                 10.1.243-3   amd64        NVIDIA Performance Primitives core runtime library
ii  libnppial10:amd64                               10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Arithmetic and Logic
ii  libnppicc10:amd64                               10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Color Conversion
ii  libnppicom10:amd64                              10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Compression
ii  libnppidei10:amd64                              10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Data Exchange and Initialization
ii  libnppif10:amd64                                10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Filters
ii  libnppig10:amd64                                10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Geometry transforms
ii  libnppim10:amd64                                10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Morphological operations
ii  libnppist10:amd64                               10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Statistics
ii  libnppisu10:amd64                               10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Support
ii  libnppitc10:amd64                               10.1.243-3   amd64        NVIDIA Performance Primitives lib for Image Threshold and Compare
ii  libnpps10:amd64                                 10.1.243-3   amd64        NVIDIA Performance Primitives for signal processing runtime library
ii  libnvgraph10:amd64                              10.1.243-3   amd64        NVIDIA Graph Analytics library (nvGRAPH)
ii  libnvidia-cfg1-470:amd64                        470.57.02-0ubuntu1   amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-common-460                            460.27.04-0ubuntu1   all          Shared files used by the NVIDIA libraries
ii  libnvidia-common-470                            470.57.02-0ubuntu1   all          Shared files used by the NVIDIA libraries
ii  libnvidia-compute-418:amd64                     430.50-0ubuntu3   amd64        Transitional package for libnvidia-compute-430
ii  libnvidia-compute-430:amd64                     470.57.02-0ubuntu1   amd64        Transitional package for libnvidia-compute-470
rc  libnvidia-compute-450:amd64                     450.102.04-0ubuntu0.20.04.1   amd64        NVIDIA libcompute package
rc  libnvidia-compute-460:amd64                     460.91.03-0ubuntu0.20.04.1   amd64        NVIDIA libcompute package
ii  libnvidia-compute-470:amd64                     470.57.02-0ubuntu1   amd64        NVIDIA libcompute package
ii  libnvidia-decode-470:amd64                      470.57.02-0ubuntu1   amd64        NVIDIA Video Decoding runtime libraries
ii  libnvidia-encode-470:amd64                      470.57.02-0ubuntu1   amd64        NVENC Video Encoding runtime library
ii  libnvidia-extra-470:amd64                       470.57.02-0ubuntu1   amd64        Extra libraries for the NVIDIA driver
ii  libnvidia-fbc1-470:amd64                        470.57.02-0ubuntu1   amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-gl-470:amd64                          470.57.02-0ubuntu1   amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-ifr1-470:amd64                        470.57.02-0ubuntu1   amd64        NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  libnvidia-ml-dev                                10.1.243-3   amd64        NVIDIA Management Library (NVML) development files
ii  libnvjpeg10:amd64                               10.1.243-3   amd64        NVIDIA JPEG library (nvJPEG)
ii  libnvrtc10.1:amd64                              10.1.243-3   amd64        CUDA Runtime Compilation (NVIDIA NVRTC Library)
ii  libnvtoolsext1:amd64                            10.1.243-3   amd64        NVIDIA Tools Extension Library
ii  libnvvm3:amd64                                  10.1.243-3   amd64        NVIDIA NVVM Library
ii  nsight-compute                                  10.1.243-3   amd64        NVIDIA Nsight Compute
ii  nsight-compute-2020.3.0                         2020.3.0.18-1   amd64        NVIDIA Nsight Compute
ii  nsight-compute-2021.2.2                         2021.2.2.1-1   amd64        NVIDIA Nsight Compute
rc  nvidia-compute-utils-450                        450.102.04-0ubuntu0.20.04.1   amd64        NVIDIA compute utilities
rc  nvidia-compute-utils-460                        460.91.03-0ubuntu0.20.04.1   amd64        NVIDIA compute utilities
ii  nvidia-compute-utils-470                        470.57.02-0ubuntu1   amd64        NVIDIA compute utilities
ii  nvidia-cuda-dev                                 10.1.243-3   amd64        NVIDIA CUDA development files
ii  nvidia-cuda-doc                                 10.1.243-3   all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                                 10.1.243-3   amd64        NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                             10.1.243-3   amd64        NVIDIA CUDA development toolkit
rc  nvidia-dkms-450                                 450.102.04-0ubuntu0.20.04.1   amd64        NVIDIA DKMS package
rc  nvidia-dkms-460                                 460.91.03-0ubuntu0.20.04.1   amd64        NVIDIA DKMS package
ii  nvidia-dkms-470                                 470.57.02-0ubuntu1   amd64        NVIDIA DKMS package
ii  nvidia-driver-470                               470.57.02-0ubuntu1   amd64        NVIDIA driver metapackage
rc  nvidia-kernel-common-450                        450.102.04-0ubuntu0.20.04.1   amd64        Shared files used with the kernel module
rc  nvidia-kernel-common-460                        460.91.03-0ubuntu0.20.04.1   amd64        Shared files used with the kernel module
ii  nvidia-kernel-common-470                        470.57.02-0ubuntu1   amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-470                        470.57.02-0ubuntu1   amd64        NVIDIA kernel source package
ii  nvidia-modprobe                                 470.57.02-0ubuntu1   amd64        Load the NVIDIA kernel driver and create device files
ii  nvidia-prime                                    0.8.14   all          Tools to enable NVIDIA's Prime
ii  nvidia-profiler                                 10.1.243-3   amd64        NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings                                 470.57.02-0ubuntu1   amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-utils-470                                470.57.02-0ubuntu1   amd64        NVIDIA driver support binaries
ii  nvidia-visual-profiler                          10.1.243-3   amd64        NVIDIA Visual Profiler for CUDA and OpenCL
ii  nvtop                                           1.0.0-1ubuntu2   amd64        Interactive NVIDIA GPU process monitor
ii  screen-resolution-extra                         0.18build1   all          Extension for the nvidia-settings control panel
ii  xserver-xorg-video-nvidia-470                   470.57.02-0ubuntu1   amd64        NVIDIA binary Xorg driver
