### ISSUE TITLE
TensorBoard callback doesn't update step properly

### ISSUE THREAD

**Issue by sehoffmann** [tensorflow/tensorflow#43568]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: 18.04.1-Ubuntu
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.6.9
- CUDA/cuDNN version: libcudart.so.10.1
- GPU model and memory: GeForce RTX 2080 Ti

**Describe the current behavior**
If using `tf.summary` operations while an `tf.keras.callbacks.TensorBoard` callback is active, the default `step` is always `0`.
This does not affect the step value of logged metrics, because `tf.keras.Model` does not rely on the default step, but directly uses `_train_counter`.

The reason for this is in https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/keras/callbacks.py#L2075 which evaluates the value of the `step` variable, i.e `self._train_step` aka `self.model._train_counter` once when `on_train_begin()` or a similar method is called, but not when a new batch starts.

**Describe the expected behavior**
The default step value, i.e the value returned by `tf.summary.experimental.get_step()`, should reflect the current step. As `self._train_step` is a variable it should be sufficient to just pass it directly to `tf.summary.experimental.set_step()`.

**Standalone code to reproduce the issue**
log an arbitrary scalar with `tf.summary.scalar` during training but don't provide a step argument. Make sure that you created a `tf.keras.callbacks.TensorBoard` and set the `update_freq` parameter.

**Comment by sehoffmann** [comment]
I wrote a quick hotfix which works for me:

```
class TensorBoardFix(tf.keras.callbacks.TensorBoard):
    """
    This fixes incorrect step values when using the TensorBoard callback with custom summary ops
    """

    def on_train_begin(self, *args, **kwargs):
        super(TensorBoardFix, self).on_train_begin(*args, **kwargs)
        tf.summary.experimental.set_step(self._train_step)


    def on_test_begin(self, *args, **kwargs):
        super(TensorBoardFix, self).on_test_begin(*args, **kwargs)
        tf.summary.experimental.set_step(self._val_step)
```

**Comment by sehoffmann** [comment]
If you are modifying the code you might want to consider updating the documentation as well. It's currently undocumented that the `TensorBoard` callback sets the default writer. I stumbled upon this issue initially after I tried to hijack the writer from the TensorBoard callback, realizing that the class already does what I wanted.

**Comment by Saduf2019** [comment]
@sehoffmann 
Could you please verify with latest versions of tf and let us know if you still face the problem.

**Comment by Cheelem** [comment]
This problem still exists in TensorFlow 2.5.0. When I use `tf.summary.*`  operations to record scalars and images I want, their steps are always 0 in TensorBoard. And the wrapper class `TensorBoardFix` mentioned by @sehoffmann works as a temporary solution with TF 2.5.0.

**Comment by DachuanZhao** [comment]
> @sehoffmann
> Could you please verify with latest versions of tf and let us know if you still face the problem.

This problem still exists in TensorFlow 2.6.0 , too . Can I push a PR which contains the hotfix to ```keras``` to fix it ?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
