### ISSUE TITLE
UnknownError: Failed to get convolution algorithm. 

### ISSUE THREAD

**Issue by RomanGirin** [tensorflow/tensorflow#43764]
**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
TensorFlow installed from (source or binary): binary **(no errors during installation)**
TensorFlow version: 2.3.1
Python version: 3.7.5
CUDA/cuDNN version: 10.1
GPU model and memory: RTX 1660 Ti 6.00GB
[full script output.txt](https://github.com/tensorflow/tensorflow/files/5322982/full.script.output.txt)

**Describe the current behavior**
The code below throws the following exception 

`tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]
`
Full script's output is attached.
The code is pretty standard, it's weird to get this error. In the script I also put code that trains model via Keras's model.fit() - and it works. **The error occurs when GradientTape-approach is used.**
Also the same code (version with training via Keras model.fit() and version with GradiantTape) works fine on GoogleColab https://colab.research.google.com/drive/1fjbvlpEEEm3yvyKhcGyel3vLguEkU9GN?usp=sharing

**Standalone code to reproduce the issue**

```

import tensorflow as tf

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train[..., tf.newaxis].astype("float32")
x_test = x_test[..., tf.newaxis].astype("float32")
nb_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, nb_classes)
y_test = tf.keras.utils.to_categorical(y_test, nb_classes)
dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(32)

# oversimplified model just for example
inputs = tf.keras.layers.Input(shape=(28, 28, 1))
x = tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu')(inputs)
x = tf.keras.layers.MaxPool2D(2)(x)
x = tf.keras.layers.Flatten()(x)
outputs = tf.keras.layers.Dense(nb_classes, activation='softmax')(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

loss_func = tf.keras.losses.CategoricalCrossentropy()
optimizer = tf.keras.optimizers.Adam()

for i, (xx, yy) in enumerate(dataset):
    with tf.GradientTape() as tape:
        y_pred = model(xx)
        loss = loss_func(yy, y_pred)
    grad = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grad, model.trainable_variables))
    print('batch {} processed'.format(i))

# if used this approach to train - everything works
# model.compile(loss=tf.keras.losses.CategoricalCrossentropy(), optimizer=tf.keras.optimizers.Adam())
# model.fit(x_train, y_train, batch_size=128, validation_data=(x_test, y_test))
# model.evaluate(x_test, y_test, batch_size=128, verbose=1)
```

**Other info / logs** 
Full script output is attached.

**Comment by RomanGirin** [comment]
That may be obvious from the description of the bug, but for more precise issue localization:  if Convolution layer is excluded from the model everything works too.
But **usage tf.keras.layers.Conv2D causes described above bug.**

**Comment by ravikyram** [comment]
@RomanGirin 

I have tried in colab with TF version 2.3.0 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/564e7bc08f0128fa8c084b68b2437227/untitled416.ipynb).Please, help us with reproducible code. It helps us in localizing the issue faster. Thanks!

**Comment by RomanGirin** [comment]
@ravikyram  Yes, I register the issue on my laptop only too. Both, in virtual environment and 'globally' in the system (also running as Administator).
Is there any list what can be checked based on the script's output attached above?

It is likely environmental problem in my laptop, but I keep wonder why keras model.fit() works then?

Is this part of the script's output gives us some clue?
```
2020-10-05 19:57:05.600720: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-10-05 19:57:05.601278: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
```

**Comment by bhack** [comment]
@RomanGirin I don't think it is a Tensorflow bug. Double check you cudnn version and https://github.com/tensorflow/tensorflow/issues/39989

**Comment by RomanGirin** [comment]
@bhack thank you for the reply! 
my cudnn version is cudnn-10.1-windows10-x64-v7.6.5.32
I also tried cudnn-10.1-windows10-x64-v8.0.3.33 with no luck

Checked environment vars: 
in particular i have in PATH
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp

I also have var CUDA_PATH with value
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
and CUDA_PATH_V10_1
with the same value
The paths in the var's values corresponds to the actual ones where I copied cudnn. 

Also I tried to run this addition of vars with no luck
https://www.tensorflow.org/install/gpu#windows_setup

Run through "check list" here
https://forums.developer.nvidia.com/t/could-not-create-cudnn-handle-cudnn-status-alloc-failed/108261/2
In particular, I'm the only user in the system (this is laptop) no possible side effects from other training processes. And the error is consistent (not occurring from time to time)

The issue still remains
Any help is very appreciated!

**Comment by RomanGirin** [comment]
Also, just in case, checked that I have installed CUDA 10.1 with the update 2

CUDA Toolkit 10.1 update2 Archive https://developer.nvidia.com/cuda-10.1-download-archive-update2?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal

The issue still remains
Any help is very appreciated!

**Comment by RomanGirin** [comment]
@ravikyram @bhack  found a workaround. Set GPU memory growth setting to 'true' instead of default https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth

Looks like a bug in memory allocation logic in TF or CUDA engine to me.

I consider it as workaround. It would be cool if it wouldn't be necessary to use this settings. Because (quote from https://www.tensorflow.org/guide/gpu) "By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to CUDA_VISIBLE_DEVICES) visible to the process. This is done to more efficiently use the relatively precious GPU memory resources on the devices by reducing memory fragmentation." 

These two comments may be relevant to this issue also:
https://github.com/tensorflow/tensorflow/issues/6698#issuecomment-297179317 (this one relates to TF 1.X but root cause may be the same)
https://github.com/tensorflow/tensorflow/issues/6698#issuecomment-613039907

**Comment by ravikyram** [comment]
@RomanGirin 

Please, close this thread if your issue was resolved. Thanks!

**Comment by RomanGirin** [comment]
@ravikyram I don't think it should be considered like a solution. It's just work around because it may lead to GPU memory fragmentation as noted in TF docs (https://www.tensorflow.org/guide/gpu)

Looks like a bug in memory allocation logic in TF or CUDA engine to me.

Thanks for all the replies anyway!!

**Comment by sanjoy** [comment]
@imintz is looking into possibly fixing this for good.

**Comment by yashrajjain726** [comment]
Don't close the thread, because neither of the solution, worked for me. I installed Anaconda with Python 3.8, CUDA 10.1,cuDNN 8.0.3 on my Window 10 with GPU Configuration - GTX 1050 . Please Help me.

**Comment by sanjoy** [comment]
@yashrajjain726 Does https://github.com/tensorflow/tensorflow/issues/43764#issuecomment-706560533 work for you?

**Comment by yashrajjain726** [comment]
Nope.

**Comment by RomanGirin** [comment]
@yashrajjain726 take a look at this check list https://forums.developer.nvidia.com/t/could-not-create-cudnn-handle-cudnn-status-alloc-failed/108261/2 just in case if it's environmental problem

**Comment by yashrajjain726** [comment]
Ohk, So My error is cleared when I used the cuDNN v7.6.5 with CUDA 10.1

**Comment by Saduf2019** [comment]
@RomanGirin 
Could you please provide access to the colab gist so we could verify if this is fixed in later tf versions or could you please confirm if this is still an issue on latest tf version.

**Comment by RomanGirin** [comment]
I had the error more than a half of year ago! 
I'm sorry but the only code I have left for the case is provided above in this issue
