### ISSUE TITLE
Tensorflow does not work because of Cudnn library issue

### ISSUE THREAD

**Issue by manasmacherla** [tensorflow/tensorflow#43778]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.15.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0 and 7.4
- GPU model and memory: RTX 2060 6GB VRAM

**Describe the problem**
I first installed tf 2.3.0 with CUDA version: 10.1 and CUDnn version: 7.6. I had to work with some old code of mine so I uninstalled the previous CUDA, deleted all the files, and did a fresh install of the CUDA and CUDnn versions mentioned above along with tf 1.15.0. When I try to run the TensorFlow python program I keep getting the same error. It has something to do with source compilation of the previous CUDnn version (7.6.0), I cannot seem to find how to undo this, I tried reinstalling anaconda as well and checked all the environment variable paths of my system, all of them seem to point to the right directories.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I ran the file via command line using python main.py. 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

EPOCH 1 ...
2020-10-04 16:15:46.208813: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-04 16:15:47.780566: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.2 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-10-04 16:15:47.793953: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.2 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1_1/Conv2D}}]]
         [[Mean/_73]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1_1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_test.py", line 202, in <module>
    run()
  File "main_test.py", line 193, in run
    correct_label, keep_prob, learning_rate)
  File "main_test.py", line 146, in train_nn
    feed_dict={input_image: image, correct_label: label,                                keep_prob: 0.5, learning_rate: 0.0009})
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv1_1/Conv2D (defined at C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
         [[Mean/_73]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv1_1/Conv2D (defined at C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'conv1_1/Conv2D':
  File "main_test.py", line 202, in <module>
    run()
  File "main_test.py", line 184, in run
    input_image, keep_prob, vgg_layer3_out, vgg_layer4_out, vgg_layer7_out = load_vgg(sess, vgg_path)
  File "main_test.py", line 36, in load_vgg
    tf.saved_model.loader.load(sess, [vgg_tag], vgg_path)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 422, in load
    **saver_kwargs)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\training\saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\importer.py", line 517, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3561, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3561, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3451, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "C:\Users\manas\anaconda3\envs\tensorflow1-gpu\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by Saduf2019** [comment]
@manasmacherla 
We do not support anaconda build/install issues officially.
Please refer to these issues and let us know if it helps, else please create issue in respective repo:
#25160 [link](https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in), [link1](https://medium.com/@adwin596/solved-error-failed-to-get-convolution-algorithm-4396982082a7),[link2](https://superuser.com/questions/1397250/cudnn-error-failed-to-get-convolution-algorithm).

**Comment by manasmacherla** [comment]
These links did not provide any solution but downgrading to tf 1.14.0 worked. Thanks.

**Comment by Saduf2019** [comment]
@manasmacherla 
Thanks for the update, the issue #25160 is directed towards downgrading as done,glad that the issue is resolved.
