### ISSUE TITLE
ValueError: The same saveable will be restored with two names: layer_with_weights-1/_table/.ATTRIBUTES/table

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#44005]
tensorflow 2.3.1

**Describe the current behavior**

When I run ```! pip install -U tensorflow```  at the begin and run ```! saved_model_cli show --dir 'my_pet_classifier' --all``` at the end of this [document](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers)'s colab , it raises error :

```
2020-10-14 08:20:39.291886: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['Age'] tensor_info:
        dtype: DT_INT64
        shape: (-1, 1)
        name: serving_default_Age:0
    inputs['Breed1'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_Breed1:0
    inputs['Color1'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_Color1:0
    inputs['Color2'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_Color2:0
    inputs['Fee'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: serving_default_Fee:0
    inputs['FurLength'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_FurLength:0
    inputs['Gender'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_Gender:0
    inputs['Health'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_Health:0
    inputs['MaturitySize'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_MaturitySize:0
    inputs['PhotoAmt'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: serving_default_PhotoAmt:0
    inputs['Sterilized'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_Sterilized:0
    inputs['Type'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_Type:0
    inputs['Vaccinated'] tensor_info:
        dtype: DT_STRING
        shape: (-1, 1)
        name: serving_default_Vaccinated:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['dense_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict
2020-10-14 08:20:41.728805: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-14 08:20:41.738107: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-10-14 08:20:41.738155: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (1a8174b158ac): /proc/driver/nvidia/version does not exist
Traceback (most recent call last):
  File "/usr/local/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 1185, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 715, in show
    _show_all(args.dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 307, in _show_all
    _show_defined_functions(saved_model_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 187, in _show_defined_functions
    trackable_object = load.load(saved_model_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 603, in load
    return load_internal(export_dir, tags, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 633, in load_internal
    ckpt_options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 131, in __init__
    self._restore_checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 330, in _restore_checkpoint
    load_status = saver.restore(variables_path, self._checkpoint_options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 1320, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 914, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 290, in restore_saveables
    tensor_saveables)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 361, in validate_and_slice_inputs
    _add_saveable(saveables, seen_ops, converted_saveable_object)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 331, in _add_saveable
    saveable.name)
ValueError: The same saveable will be restored with two names: layer_with_weights-1/_table/.ATTRIBUTES/table
```

**Comment by DachuanZhao** [comment]
Maybe [https://github.com/tensorflow/tfjs/issues/3977](https://github.com/tensorflow/tfjs/issues/3977)  is the same problem .

**Comment by abattery** [comment]
@jvishnuvardhan Sorry. I am not familiar with this part.

**Comment by DachuanZhao** [comment]
Hi , @jvishnuvardhan . Is there anyone who knows how to solve it ?

**Comment by nagachika** [comment]
I run into the same problem. And the issue seems reproducible on 2.4.1 (which is the current default version on Colab).
The error messages from saved_model_cli on 2.4.1 is slightly changed from saved_model_cli on 2.3.1.

The cell executed in [the tutorial Colab notebook](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers):

```
! saved_model_cli show --all --dir my_pet_classifier
```

The output from the cell:
```
(snip)
  Method name is: tensorflow/serving/predict
Traceback (most recent call last):
  File "/usr/local/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 990, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 691, in show
    _show_all(args.dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 283, in _show_all
    _show_defined_functions(saved_model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 176, in _show_defined_functions
    trackable_object = load.load(saved_model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/saved_model/load.py", line 528, in load
    return load_internal(export_dir, tags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/saved_model/load.py", line 552, in load_internal
    export_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/saved_model/load.py", line 114, in __init__
    meta_graph.graph_def.library))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 312, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/function_def_to_graph.py", line 59, in function_def_to_graph
    fdef, input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/function_def_to_graph.py", line 218, in function_def_to_graph_def
    op_def = default_graph._get_op_def(node_def.op)  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/ops.py", line 3712, in _get_op_def
    c_api.TF_GraphGetOpDef(self._c_graph, compat.as_bytes(type), buf)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'DenseBincount' in binary running on 0796e2c3d036. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

The notebook I used to reproduced the issue was saved in my gist.

https://colab.research.google.com/gist/nagachika/335371ac06432a19ca7027b64d61f740/preprocessing_layers.ipynb

I hope this might help.

**Comment by jvishnuvardhan** [comment]
@nagachika Looks like this is an issue when we have `--all`. In the mean time, Removing that `--all` may be workaround.
```
! saved_model_cli show --dir my_pet_classifier #this doesn't throw error
# ! saved_model_cli show --all --dir my_pet_classifier  # this throws the error

```

[Here](https://colab.research.google.com/gist/jvishnuvardhan/ca3f4e19a2de5947aae4d3b67917467b/preprocessing_layers.ipynb) is a gist for our reference. Thanks!

**Comment by nagachika** [comment]
@jvishnuvardhan Thank you for your information!

I have confirmed that the following command line works for me to retrieve inputs/outputs signatures.
Thanks again!

```
saved_model_cli show --tag_set serve --signature_def serving_default --dir my_pet_classifier
```

**Comment by MarkDaoust** [comment]
Hi @allenlavoie, @k-w-w,

I just got assigned this.  I have no idea what's going wrong, do you have any advice?

That model saves and loads cleanly in the colab tutorial. 

Is there something wrong with `saved_model_cli`? Is that tool still maintained?

**Comment by rafiqhasan** [comment]
@MarkDaoust 

This is closely linked to https://github.com/tensorflow/serving/issues/1720 and https://github.com/tensorflow/serving/issues/1812

All these are somehow affecting saved_model_cli and also breaking inference via TFMS

**Comment by rthadur** [comment]
cc @ymodak

**Comment by rafiqhasan** [comment]
Team, you have been able to reproduce this issue all the way from version 2.3.1 but when can we expect a solution ?

**Comment by pjpratik** [comment]
@DachuanZhao _! saved_model_cli show --dir 'my_pet_classifier' --all_  did not produce error in TF 2.11. Could you please check the gist [here](https://colab.research.google.com/gist/pjpratik/790db6177e5865e278193e57b7f3e2d4/44005.ipynb#scrollTo=jnQgOGzelIhI) and let us know if it helps. Thank you.
