### ISSUE TITLE
cuDNN in invalid state after OOM

### ISSUE THREAD

**Issue by dbergh** [tensorflow/tensorflow#44047]
**System information**
- Have I written custom code
- OS Platform and Distribution:  Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.13.1-0-g6612da8951
- Python version: 3.6.9
- CUDA/cuDNN version: CUDA 10.0.130-1, cuDNN 7.6.5
- GPU model and memory: GeForce RTX 2070 super, 8 GiB

**Describe the current behavior**
After getting ResourceExhaustedError during an operation using cuDNN (for instance due to out of memory) it seems like cuDNN is left in a broken state and further calls using cuDNN fail even if they don't exceed the resources.

**Describe the expected behavior**
I would expect further calls to cuDNN to be ok. This is important since it seems that the only way to know if a computation will use too much resources (for instance when determining optimal batch size) is to actually try and fail.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
from tensorflow.python.framework.errors_impl import ResourceExhaustedError

x = tf.placeholder(tf.float32, shape=[None, None, None, None, 32])
fil = tf.zeros((3, 3, 3, 32, 32), dtype=tf.float32)
conv = tf.nn.conv3d(x, filter=fil, strides=(1, 1, 1, 1, 1), padding='VALID', name=None)

with tf.Session() as sess:
    try:
        c = np.zeros((1, 370, 370, 370, 32), np.float32)
        sess.run(conv, feed_dict={x: c})
        r1 = sess.run(conv)
    except ResourceExhaustedError:
        print('Resource Error')

with tf.Session() as sess:
    c = np.zeros((1, 100, 100, 100, 32), np.float32)
    sess.run(conv, feed_dict={x: c})
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-10-15 13:41:46.910748: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-15 13:41:47.076574: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-15 13:41:47.077067: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1414860 executing computations on platform CUDA. Devices:
2020-10-15 13:41:47.077083: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2070 SUPER, Compute Capability 7.5
2020-10-15 13:41:47.096784: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3498230000 Hz
2020-10-15 13:41:47.097210: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x158f0a0 executing computations on platform Host. Devices:
2020-10-15 13:41:47.097229: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-10-15 13:41:47.097351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2070 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.815
pciBusID: 0000:01:00.0
totalMemory: 7.79GiB freeMemory: 7.31GiB
2020-10-15 13:41:47.097368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-10-15 13:41:47.098194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-15 13:41:47.098208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-10-15 13:41:47.098215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-10-15 13:41:47.098286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7110 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-10-15 13:41:47.100978: W tensorflow/core/framework/allocator.cc:124] Allocation of 6483584000 exceeds 10% of system memory.
2020-10-15 13:42:01.641512: W tensorflow/core/common_runtime/bfc_allocator.cc:267] Allocator (GPU_0_bfc) ran out of memory trying to allocate 5.94GiB.  Current allocation summary follows.
2020-10-15 13:42:01.641594: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (256): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641616: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (512): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641638: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2020-10-15 13:42:01.641656: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2048): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641672: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641688: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641704: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16384): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641720: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641742: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (65536): 	Total Chunks: 1, Chunks in use: 1. 108.0KiB allocated for chunks. 108.0KiB in use in bin. 108.0KiB client-requested in use in bin.
2020-10-15 13:42:01.641759: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (131072): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641775: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (262144): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641791: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (524288): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641807: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641823: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641839: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4194304): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641856: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641872: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641888: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641904: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641924: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 13:42:01.641942: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (268435456): 	Total Chunks: 2, Chunks in use: 1. 6.94GiB allocated for chunks. 6.04GiB in use in bin. 6.04GiB client-requested in use in bin.
2020-10-15 13:42:01.641960: I tensorflow/core/common_runtime/bfc_allocator.cc:613] Bin for 5.94GiB was 256.00MiB, Chunk State: 
2020-10-15 13:42:01.641986: I tensorflow/core/common_runtime/bfc_allocator.cc:619]   Size: 926.76MiB | Requested Size: 0B | in_use: 0, prev:   Size: 6.04GiB | Requested Size: 6.04GiB | in_use: 1
2020-10-15 13:42:01.642004: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f86a6000000 of size 110592
2020-10-15 13:42:01.642017: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f86a601b000 of size 1280
2020-10-15 13:42:01.642031: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f86a601b500 of size 6483584000
2020-10-15 13:42:01.642043: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Free  at 0x7f8828755900 of size 971780864
2020-10-15 13:42:01.642055: I tensorflow/core/common_runtime/bfc_allocator.cc:638]      Summary of in-use Chunks by size: 
2020-10-15 13:42:01.642071: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 1280 totalling 1.2KiB
2020-10-15 13:42:01.642087: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 110592 totalling 108.0KiB
2020-10-15 13:42:01.642101: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 6483584000 totalling 6.04GiB
2020-10-15 13:42:01.642116: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 6.04GiB
2020-10-15 13:42:01.642136: I tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats: 
Limit:                  7455476941
InUse:                  6483695872
MaxInUse:               6483695872
NumAllocs:                       3
MaxAllocSize:           6483584000

2020-10-15 13:42:01.642153: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ***************************************************************************************_____________
2020-10-15 13:42:01.642223: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at conv_ops_3d.cc:161 : Resource exhausted: OOM when allocating tensor with shape[1,368,368,368,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Resource Error
2020-10-15 13:42:01.801362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-10-15 13:42:01.801391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-15 13:42:01.801396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-10-15 13:42:01.801400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-10-15 13:42:01.801462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7110 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-10-15 13:42:02.948064: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-15 13:42:02.967863: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node Conv3D}}]]
	 [[{{node Conv3D}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py", line 19, in <module>
    sess.run(conv, feed_dict={x: c})
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv3D (defined at /home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py:7) ]]
	 [[node Conv3D (defined at /home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py:7) ]]

Caused by op 'Conv3D', defined at:
  File "/home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py", line 7, in <module>
    conv = tf.nn.conv3d(x, filter=fil, strides=(1, 1, 1, 1, 1), padding='VALID', name=None)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1440, in conv3d
    dilations=dilations, name=name)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv3D (defined at /home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py:7) ]]
	 [[node Conv3D (defined at /home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py:7) ]]


Process finished with exit code 1
```

**Comment by dbergh** [comment]
I turned out that I reduced the minimal example above to much (it fails even if I remove the first run). Here is an update:
```
import tensorflow as tf
import numpy as np
from tensorflow.python.framework.errors_impl import ResourceExhaustedError

config = tf.ConfigProto()
config.gpu_options.allow_growth = True

x = tf.placeholder(tf.float32, shape=[None, None, None, None, 1])
fil = tf.zeros((3, 3, 3, 1, 32), dtype=tf.float32)
conv = tf.nn.convolution(x, filter=fil, padding='VALID', name=None)

with tf.Session(config=config) as sess:
    try:
        c = np.zeros((1, 370, 370, 370, 1), np.float32)
        sess.run(conv, feed_dict={x: c})
    except ResourceExhaustedError:
        print('Resource Error')

with tf.Session(config=config) as sess:
    c = np.zeros((1, 30, 30, 30, 1), np.float32)
    sess.run(conv, feed_dict={x: c})
```
Produces
```
/home/dbergh/.virtualenvs/boneseg/bin/python3.6 /home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-10-15 17:15:28.759710: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-15 17:15:28.917081: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-15 17:15:28.917568: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0xf48540 executing computations on platform CUDA. Devices:
2020-10-15 17:15:28.917584: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2070 SUPER, Compute Capability 7.5
2020-10-15 17:15:28.936804: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3498230000 Hz
2020-10-15 17:15:28.937281: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x10c0cc0 executing computations on platform Host. Devices:
2020-10-15 17:15:28.937311: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-10-15 17:15:28.937464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2070 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.815
pciBusID: 0000:01:00.0
totalMemory: 7.79GiB freeMemory: 7.29GiB
2020-10-15 17:15:28.937484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-10-15 17:15:28.938429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-15 17:15:28.938445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-10-15 17:15:28.938453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-10-15 17:15:28.938536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7096 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-10-15 17:15:39.476332: W tensorflow/core/common_runtime/bfc_allocator.cc:267] Allocator (GPU_0_bfc) ran out of memory trying to allocate 5.94GiB.  Current allocation summary follows.
2020-10-15 17:15:39.476412: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (256): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476452: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (512): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476476: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2020-10-15 17:15:39.476496: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2048): 	Total Chunks: 2, Chunks in use: 2. 7.0KiB allocated for chunks. 7.0KiB in use in bin. 6.8KiB client-requested in use in bin.
2020-10-15 17:15:39.476515: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476532: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476550: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16384): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476567: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476609: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (65536): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476628: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (131072): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476645: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (262144): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476670: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (524288): 	Total Chunks: 1, Chunks in use: 0. 1015.8KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476709: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476764: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476802: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4194304): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476835: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476865: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476883: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476900: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476923: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-10-15 17:15:39.476946: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (268435456): 	Total Chunks: 3, Chunks in use: 2. 6.93GiB allocated for chunks. 6.19GiB in use in bin. 6.13GiB client-requested in use in bin.
2020-10-15 17:15:39.476968: I tensorflow/core/common_runtime/bfc_allocator.cc:613] Bin for 5.94GiB was 256.00MiB, Chunk State: 
2020-10-15 17:15:39.476999: I tensorflow/core/common_runtime/bfc_allocator.cc:619]   Size: 756.47MiB | Requested Size: 0B | in_use: 0, prev:   Size: 5.94GiB | Requested Size: 5.94GiB | in_use: 1
2020-10-15 17:15:39.477020: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7fafde000000 of size 6379012096
2020-10-15 17:15:39.477036: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Free  at 0x7fb15a380000 of size 793221376
2020-10-15 17:15:39.477051: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7fb18a000000 of size 268435456
2020-10-15 17:15:39.477066: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7fb21f400000 of size 3584
2020-10-15 17:15:39.477081: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7fb21f400e00 of size 1280
2020-10-15 17:15:39.477095: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7fb21f401300 of size 3584
2020-10-15 17:15:39.477109: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Free  at 0x7fb21f402100 of size 1040128
2020-10-15 17:15:39.477122: I tensorflow/core/common_runtime/bfc_allocator.cc:638]      Summary of in-use Chunks by size: 
2020-10-15 17:15:39.477140: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 1280 totalling 1.2KiB
2020-10-15 17:15:39.477157: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 2 Chunks of size 3584 totalling 7.0KiB
2020-10-15 17:15:39.477174: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 268435456 totalling 256.00MiB
2020-10-15 17:15:39.477190: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 6379012096 totalling 5.94GiB
2020-10-15 17:15:39.477205: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 6.19GiB
2020-10-15 17:15:39.477227: I tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats: 
Limit:                  7441717658
InUse:                  6647456000
MaxInUse:               6647456000
NumAllocs:                       5
MaxAllocSize:           6379012096

2020-10-15 17:15:39.477247: W tensorflow/core/common_runtime/bfc_allocator.cc:271] **************************************************************************************__________****
2020-10-15 17:15:39.477328: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at conv_ops_3d.cc:399 : Resource exhausted: OOM when allocating tensor with shape[1,32,368,368,368] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Resource Error
2020-10-15 17:15:39.497736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-10-15 17:15:39.497773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-15 17:15:39.497779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-10-15 17:15:39.497783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-10-15 17:15:39.497842: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7096 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-10-15 17:15:40.247329: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-15 17:15:40.251851: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node convolution}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py", line 21, in <module>
    sess.run(conv, feed_dict={x: c})
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node convolution (defined at /home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py:10) ]]

Caused by op 'convolution', defined at:
  File "/home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py", line 10, in <module>
    conv = tf.nn.convolution(x, filter=fil, padding='VALID', name=None)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 851, in convolution
    return op(input, filter)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 208, in __call__
    name=self.name)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1440, in conv3d
    dilations=dilations, name=name)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node convolution (defined at /home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py:10) ]]


Process finished with exit code 1
```

while the code
```
import tensorflow as tf
import numpy as np
from tensorflow.python.framework.errors_impl import ResourceExhaustedError

config = tf.ConfigProto()
config.gpu_options.allow_growth = True

x = tf.placeholder(tf.float32, shape=[None, None, None, None, 1])
fil = tf.zeros((3, 3, 3, 1, 32), dtype=tf.float32)
conv = tf.nn.convolution(x, filter=fil, padding='VALID', name=None)

# with tf.Session(config=config) as sess:
#     try:
#         c = np.zeros((1, 370, 370, 370, 1), np.float32)
#         sess.run(conv, feed_dict={x: c})
#     except ResourceExhaustedError:
#         print('Resource Error')

with tf.Session(config=config) as sess:
    c = np.zeros((1, 30, 30, 30, 1), np.float32)
    sess.run(conv, feed_dict={x: c})
```
produces the output
```
/home/dbergh/.virtualenvs/boneseg/bin/python3.6 /home/dbergh/.PyCharm2019.3/config/scratches/scratch_59.py
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/dbergh/.virtualenvs/boneseg/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-10-15 17:16:25.418268: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-15 17:16:25.585102: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-15 17:16:25.585564: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x237e670 executing computations on platform CUDA. Devices:
2020-10-15 17:16:25.585579: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2070 SUPER, Compute Capability 7.5
2020-10-15 17:16:25.604750: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3498230000 Hz
2020-10-15 17:16:25.605156: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x24f72f0 executing computations on platform Host. Devices:
2020-10-15 17:16:25.605177: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-10-15 17:16:25.605303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2070 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.815
pciBusID: 0000:01:00.0
totalMemory: 7.79GiB freeMemory: 7.29GiB
2020-10-15 17:16:25.605321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-10-15 17:16:25.606144: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-15 17:16:25.606159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-10-15 17:16:25.606166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-10-15 17:16:25.606249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7096 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)

Process finished with exit code 0
```
indicating success.

**Comment by dbergh** [comment]
Ok. With 2.3.1 (over cuda 10.1) I get no error. The tensorflow 2 version of the code would be.

```
import tensorflow.compat.v1 as tf
import numpy as np
from tensorflow.python.framework.errors_impl import ResourceExhaustedError
tf.disable_v2_behavior()

config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True

x = tf.placeholder(tf.float32, shape=[None, None, None, None, 1])
fil = tf.zeros((3, 3, 3, 1, 32), dtype=tf.float32)
conv = tf.nn.convolution(x, filter=fil, padding='VALID', name=None)

with tf.Session(config=config) as sess:
    try:
        c = np.zeros((1, 370, 370, 370, 1), np.float32)
        sess.run(conv, feed_dict={x: c})
    except ResourceExhaustedError:
        print('Resource Error')

with tf.Session(config=config) as sess:
    c = np.zeros((1, 30, 30, 30, 1), np.float32)
    sess.run(conv, feed_dict={x: c})
```

**Comment by dbergh** [comment]
If someone else runs into this:
The error seems to subtly depend on the order of execution. The following code
```
import tensorflow as tf
import numpy as np
from tensorflow.python.framework.errors_impl import ResourceExhaustedError

config = tf.ConfigProto()
config.gpu_options.allow_growth = True

x = tf.placeholder(tf.float32, shape=[None, None, None, None, 1])
fil = tf.zeros((3, 3, 3, 1, 32), dtype=tf.float32)
conv = tf.nn.convolution(x, filter=fil, padding='VALID', name=None)

with tf.Session(config=config) as sess:
    c = np.zeros((1, 30, 30, 30, 1), np.float32)
    sess.run(conv, feed_dict={x: c})

with tf.Session(config=config) as sess:
    try:
        c = np.zeros((1, 370, 370, 370, 1), np.float32)
        sess.run(conv, feed_dict={x: c})
    except ResourceExhaustedError:
        print('Resource Error')

with tf.Session(config=config) as sess:
    c = np.zeros((1, 30, 30, 30, 1), np.float32)
    sess.run(conv, feed_dict={x: c})
```

produces no error.
