### ISSUE TITLE
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by arita89** [tensorflow/tensorflow#44085]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Scientific Linux 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary):  pip install tensorflow-gpu==1.13.1
- TensorFlow version:Desktop
- Python version:3.6.2
- Installed using virtualenv? pip? conda?: virtualenv and pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0
- GPU model and memory:

**Describe the problem**
I have set up a virtual environment, to run ImageAI on a custom detection task (https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMDETECTIONTRAINING.md) . ImageAI requires now outdated packages, that i have installed in the virtualenv.

pip install tensorflow-gpu==1.13.1 for gpu
 or pip install tensorflow==1.13.1 for cpu
pip install opencv-python
pip install keras==2.2.4
pip install numpy==1.16.1
pip install imageai --upgrade

module load cuda/9.0

**Provide the exact sequence of commands / steps that you executed before running into the problem**
i have installed the packages with the version recommended.

the code itself its just the one from the webpage to retrain yolov3 over a test dataset

from imageai.Detection.Custom import DetectionModelTrainer
import os

INPUT_DIR = "/zhome/94/5/101974/data/hololens/"

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory=INPUT_DIR)
trainer.setTrainConfig(object_names_array=["hololens"], batch_size=4, num_experiments=10, train_from_pretrained_model="pretrained-yolov3.h5", show_network_summary=True)
trainer.trainModel()

"""## evaluate performance"""
trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory=INPUT_DIR)
metrics = trainer.evaluateModel(model_path=INPUT_DIR+"models", json_path="hololens/json/detection_config.json", iou_threshold=0.5, object_threshold=0.3, nms_threshold=0.5)
print(metrics)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

sing TensorFlow backend.
Traceback (most recent call last):
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib64/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "retraining_YOLO_new_data.py", line 22, in <module>
    from imageai.Detection.Custom import DetectionModelTrainer
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/imageai/Detection/__init__.py", line 2, in <module>
    from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/imageai/Detection/keras_retinanet/models/resnet.py", line 19, in <module>
    import keras
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib64/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by arita89** [comment]
Hello again, 
 i really would love to use colab, but after last deeplearning project i got my quota of gpu very much limited. Also its quite unstable, so it finds a device once and 9 times not. 

Plus I am connected to a linux remote server of my uni, which is used by students to run on gpu, so i really cant believe the hardware they are using is not up to the task. 

 i changed from CUDA9.0 to CUDA10.0 which is the one compatible with TF 1.13.1 (that i need to use).
I added the installation directory of cuda10 to the LD library path.

I cant find anywhere the CUPTI and cuDNN directories (i guess as a user and not adm i dont have visibilities on these? )

I uninstalled TF1.13.1 and TF-GPU 1.13.1, uninstalled protobuf, reinstalled TF and TF-GPU. 

The error persists, now its just with a different version:
----------------------------------------------------------------------------------------------------------------------------------------
sing TensorFlow backend.
Traceback (most recent call last):
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib64/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "retraining_YOLO_new_data.py", line 22, in <module>
    from imageai.Detection.Custom import DetectionModelTrainer
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/imageai/Detection/__init__.py", line 2, in <module>
    from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/imageai/Detection/keras_retinanet/models/resnet.py", line 19, in <module>
    import keras
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/zhome/94/5/101974/Desktop/Env/nn_train/lib64/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib64/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
**ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory**


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by amahendrakar** [comment]
@arita89,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if you are facing the same issue. Thanks!

**Comment by arita89** [comment]
well i can try, just the package that i am trying to make work (imageAI) was updated lastly in Dec2019 and goes with these versions of tensorflow and keras. 

if you tell me that there is no way to resolve this issue that i can just try my way with the latest packages and probably a lot of more debugging

**Comment by amahendrakar** [comment]
@arita89,
Could you please uninstall all the packages and check if a fresh installation of CUDA 10 with cuDNN 7.4 works? Thanks!

**Comment by arita89** [comment]
hei, i basically updated the package to tf 2.3 and now it works, maybe minor error messages here and there, but trains and all.
thanks for your support, in times of panic its something valuable :)

**Comment by amahendrakar** [comment]
@arita89,
Happy to help :)

Marking the issue as closed since it is resolved. Please feel free to re-open if necessary. Thanks!
