### ISSUE TITLE
docs: Failed to initialize NVML: Driver/library version mismatch

### ISSUE THREAD

**Issue by tekumara** [tensorflow/tensorflow#44301]
## URL(s) with the issue:

https://www.tensorflow.org/install/gpu#install_cuda_with_apt

## Description of issue (what needs changing):

I'm following the Ubuntu 18.04 (CUDA 10.1) instructions. I installed the NVIDIA package repositories & NVIDIA driver 450 and rebooted, then ran nvidia-smi:
```
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   62C    P0    63W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I then installed cuda-10-1, libcudnn7=7.6.5.32-1+cuda10.1, libcudnn7-dev=7.6.5.32-1+cuda10.1 as per the instructions. Now I get:

```
$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
```

I'm running Ubuntu 18.04.5 LTS (Bionic Beaver)

**Comment by tekumara** [comment]
I've rebooted after installing cuda & libcudnn, and now it works:

```
$ nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   24C    P8    29W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

It looks like the nvidia driver version was upgraded to 455.

Would it be worth updating the docs to move the reboot to the end of the instructions?

**Comment by tekumara** [comment]
Actually, a better solution might be to update the driver instructions to install 455 instead of 450, eg:
```
sudo apt-get install --no-install-recommends nvidia-driver-455
```
Because cuda-10-1 installs cuda-drivers-455, which installs nvidia-driver-455

**Comment by tekumara** [comment]
Because cuda-10-1 installs cuda-drivers-455, which installs nvidia-driver-455, perhaps a better solution is to remove this line from the instructions:
```
sudo apt-get install --no-install-recommends nvidia-driver-450
```

**Comment by ravikyram** [comment]
@tekumara 

Please, see this [SO link](https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch) and see if it helps you. Is this issue related to Tensorflow?
Thanks!

**Comment by tekumara** [comment]
It's working for me now but I believe the docs could be improved as mentioned above.

**Comment by ravikyram** [comment]
@tekumara 

The requested change has been implemented in this [PR#1749](https://github.com/tensorflow/docs/pull/1749).Please, verify once and close the issue. Thanks!
