### ISSUE TITLE
docs: Unable to locate package libcudnn7

### ISSUE THREAD

**Issue by tekumara** [tensorflow/tensorflow#44300]
## URL(s) with the issue:

https://www.tensorflow.org/install/gpu#install_cuda_with_apt

## Description of issue (what needs changing):

I'm following the Ubuntu 18.04 (CUDA 10.1) instructions. I've installed the NVIDIA package repositories & NVIDIA driver and rebooted. I now try to install cuda & libcudnn7:

```
$ sudo apt-get install --no-install-recommends \
    cuda-10-1 \
    libcudnn7=7.6.5.32-1+cuda10.1  \
    libcudnn7-dev=7.6.5.32-1+cuda10.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcudnn7
E: Unable to locate package libcudnn7-dev
```

I'm running Ubuntu 18.04.5 LTS (Bionic Beaver)

**Comment by tekumara** [comment]
I've run `sudo apt-get update` again (since rebooting as recommended) and now it works!

**Comment by tekumara** [comment]
I've run `sudo apt-get update` (again?) and now it works!

**Comment by tekumara** [comment]
It looks like I missed running the second `sudo apt-get update` in the instructions. I've run it again, and it works!
