### ISSUE TITLE
Layer.add_loss has wrong behaviour when building Sequential model in for loop

### ISSUE THREAD

**Issue by merplumander** [tensorflow/tensorflow#44590]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Catalina
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1     2.3.1
- Python version: 3.6.5
- CUDA/cuDNN version: Not using CUDA
- GPU model and memory: Not using GPU

This code:
```
    import tensorflow as tf

    tf.random.set_seed(0)
    model = tf.keras.Sequential()
    inputs = tf.keras.Input(shape=(1,))
    model.add(inputs)
    layer1 = tf.keras.layers.Dense(1)
    layer1.add_loss(lambda :tf.reduce_sum(layer1.kernel))
    model.add(layer1)
    layer2 = tf.keras.layers.Dense(1)
    layer2.add_loss(lambda :tf.reduce_sum(layer2.kernel))
    model.add(layer2)

    print(model.get_weights())
    print(model.losses)
```

Correctly produces:
   [array([[-0.7206192]], dtype=float32), array([0.], dtype=float32), array([[0.19195998]], dtype=float32), array([0.], 
   dtype=float32)]
   [<tf.Tensor: shape=(), dtype=float32, numpy=-0.7206192>, <tf.Tensor: shape=(), dtype=float32, numpy=0.19195998>]

I.e. the first kernel weight is the first loss and the second kernel weight is the second loss.

I would expect the following code to produce the same result:

```
    tf.random.set_seed(0)
    model = tf.keras.Sequential()
    inputs = tf.keras.Input(shape=(1,))
    model.add(inputs)
    for i in range(2):
        layer = tf.keras.layers.Dense(1)
        layer.add_loss(lambda :tf.reduce_sum(layer.kernel))
        model.add(layer)

    print(model.get_weights())
    print(model.losses)
```

But it produces:
    [array([[-0.7206192]], dtype=float32), array([0.], dtype=float32), array([[0.19195998]], dtype=float32), array([0.], 
    dtype=float32)]
    [<tf.Tensor: shape=(), dtype=float32, numpy=0.19195998>, <tf.Tensor: shape=(), dtype=float32, numpy=0.19195998>]
I.e. it takes the second kernel weight for both losses.

**Comment by ravikyram** [comment]
@merplumander 

Please, refer similar issue #44048 and see if it helps you. Thanks!

**Comment by merplumander** [comment]
I think this issue is a different one. I'm not attempting to use the same layer instance twice. The variable "layer" holds two different instances in the for loop. This also happens when the layer instances have different numbers of units for example.


```
import tensorflow as tf

layer_units = [2, 1]

tf.random.set_seed(0)
model = tf.keras.Sequential()
inputs = tf.keras.Input(shape=(1,))
model.add(inputs)
layer1 = tf.keras.layers.Dense(layer_units[0])
layer1.add_loss(lambda :tf.reduce_sum(layer1.kernel))
model.add(layer1)
layer2 = tf.keras.layers.Dense(layer_units[1])
layer2.add_loss(lambda :tf.reduce_sum(layer2.kernel))
model.add(layer2)

print(model.losses)
```

Correctly produces:
`[<tf.Tensor: shape=(), dtype=float32, numpy=-1.4183385>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.6315678>]`



Whereas:

```
layer_units = [2, 1]

tf.random.set_seed(0)
model = tf.keras.Sequential()
inputs = tf.keras.Input(shape=(1,))
model.add(inputs)
for i in range(2):
    layer = tf.keras.layers.Dense(layer_units[i])
    layer.add_loss(lambda :tf.reduce_sum(layer.kernel))
    model.add(layer)

print(model.get_weights())
print(model.losses)
```

Incorrectly produces:
`[<tf.Tensor: shape=(), dtype=float32, numpy=-0.6315678>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.6315678>]`


So the code with the for the loop incorrectly uses the loss of the last layer for both layers.

**Comment by merplumander** [comment]
I found a workaround for my specific use case, but I still think this is a bug and should be addressed in general.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3.1 and nightly version(`2.5.0-dev20201116`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/cf06e08a197f11de3d6733613d0e4e5f/untitled518.ipynb). Thanks!

**Comment by evonbevern** [comment]
I am able to reproduce the issue but am having trouble pinpointing it. I am having trouble deciding whether the bug is caused in model.losses or model.add_loss(). If you attempt to print model.losses in the for loop before line 10, as seen below, in the buggy test case the program throws an attribute error: 

`import tensorflow as tf

tf.random.set_seed(0)
model = tf.keras.Sequential()
inputs = tf.keras.Input(shape=(1,))
model.add(inputs)
for i in range(2):
    layer = tf.keras.layers.Dense(1)
    print(model.losses)
    layer.add_loss(lambda :tf.reduce_sum(layer.kernel))
    model.add(layer)
print(model.get_weights())
print(model.losses)`

`[]
Traceback (most recent call last):
  File "GitTestCase2.py", line 10, in <module>
    print(model.losses)
  File "/home/jdvisnaw/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1470, in losses
    loss_tensor = regularizer()
  File "/home/jdvisnaw/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1546, in _tag_callable
    loss = loss()
  File "GitTestCase2.py", line 11, in <lambda>
    layer.add_loss(lambda :tf.reduce_sum(layer.kernel))
AttributeError: 'Dense' object has no attribute 'kernel' `

**Comment by merplumander** [comment]
Thanks for looking into it!

**Comment by jdvisnaw** [comment]
I am working with evonbevern to try to find this bug, after a bit of testing it does not seem to be the model.losses, we are currently trying to see if it is something in the add_loss function, or if the problem exists elsewhere

**Comment by jdvisnaw** [comment]
So after playing with the code a bit more, the first large difference I have found between the provided test cases is that in each test case, the second time in each that layer.add_loss(lambda :tf.reduce_sum(layer.kernel)) is called, in add_loss() is another function, _tag_callable(), that returns different values, the correct value for test case 1 but the incorrect value in test case 2. In _tag_callable() is another call to a function loss() that modifies the loss variable in _tag_callable(). I am having trouble either finding where loss() is located or if this is some sort of other call. Tracing and investigating loss() will help tell if there is a incorrect value being returned somewhere or if the first value is being overwritten. evonbevern and I are students at the university of michigan investigating this bug as a final project, and this is both of our first time working with and contributing to such a large code bank so any help or advice would be appreciated!

**Comment by merplumander** [comment]
Sounds like you guys are doing a good job so far 👍
I’m also working on my final project, so we’re all in the same boat ^^

**Comment by jdvisnaw** [comment]
Well after another 12 hours of playing with the code, I have narrowed down where the issue may be but have yet to solve it. The line loss() I believe is an overloaded operator that returns the tensor information including the numpy value. The second time through the loop this loss() value returns the wrong value but I do not think it modifies the value at all so  I believe the bug has to be somewhere in the line layer = tf.keras.layers.Dense(layer_units[i]). Even though the second time through the loop is a new layer instance, I believe there must be some reference to the original held in memory somewhere that gets overwritten. I am still unsure why this is though. I had a lot of trouble getting the numpy information out of both the layer and model references intermittently while running the test case making it very difficult to narrow where numpy is changed for testing.

**Comment by Saduf2019** [comment]
@merplumander 
Is this still an issue, can you please try on latest tf version and update us.

**Comment by merplumander** [comment]
Hi,
thanks for following up on this. It's still an issue for me on tf version 2.4.1.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210530, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/05382c3748387ba6797c95b683971a8c/44590.ipynb). Thanks!

**Comment by prasanthcakewalk** [comment]
**Short answer:**
Replacing
```
for i in range(2):
    layer = tf.keras.layers.Dense(1)
    layer.add_loss(lambda :tf.reduce_sum(layer.kernel))
    model.add(layer)
```
with
```
for i in range(2):
    layer = tf.keras.layers.Dense(1)
    layer.add_loss(tf.reduce_sum(layer.kernel))
    model.add(layer)
```
should fix the issue.

----
**Long answer:**
The argument to `add_loss` can either be "Loss tensor, or list/tuple of tensors. Rather than tensors, losses may also be zero-argument callables which create a loss tensor." (from `add_loss` [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#add_loss))

The zero-argument callable `lambda : tf.reduce_sum(layer.kernel)` isn't called within `add_loss` itself but later on (during compilation, I would expect). The lambda function does not store a reference to the `layer` object which existed when the lambda function is defined. Rather, when called, the lambda function will use the current `layer` object (in its scope) to compute the loss, resulting in the observed behavior. 

The simple fix to is pass the loss tensor directly to `add_loss` instead of a callable. If `add_loss` had only accepted zero-argument callables (and not a tensor directly), one can do
```
def make_loss(layer):
    return lambda : tf.reduce_sum(layer.kernel)

for i in range(2):
    layer = tf.keras.layers.Dense(1)
    layer.add_loss(make_loss(layer))
    model.add(layer)
```
Here `layer` in the lambda function's scope doesn't get overwritten in the for-loop.

A non-tensorflow example:
```
x = 0
func = lambda : x
print(func())
x = 1
print(func())
```
prints 0 and 1. But,
```
def make_func(x):
    return lambda : x
x = 0
func = make_func(x)
print(func())
x = 1
print(func())
```
prints 0 and 0.

**Comment by SuryanarayanaY** [comment]
Hi @merplumander,
As per the [comments](https://github.com/tensorflow/tensorflow/issues/44590#issuecomment-1285535870) above by @prasanthcakewalk , i have made changes to test it and now it works fine within for loop also.Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/160d0c21cd31312d54470f8def2f0671/44590.ipynb). Thankyou @prasanthcakewalk  for the solution and information also.
