### ISSUE TITLE
Resource exhausted error when running tf.keras.Model.predict on large tensor

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#44986]
I'm trying to run `tf.keras.Model.predict` on a complex tensor with shape: (1532, 128, 2049, 2). With a batch size of 4, the model throws a ResourceExhaustedError after the predictions on all the separate batches have been completed, when it is concating the predictions together.

However, if I perform the batching manually, feeding one batch at a time through the model, there is no error. It seems the problem is that the concating at the end of the prediction loop is occurring on the GPU and not on the CPU.

Here's the error.

```
~//lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    128       raise ValueError('{} is not supported in multi-worker mode.'.format(
    129           method.__name__))
--> 130     return method(self, *args, **kwargs)
    131 
    132   return tf_decorator.make_decorator(

~//lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1612             callbacks.on_predict_batch_end(end_step, {'outputs': batch_outputs})
   1613       callbacks.on_predict_end()
-> 1614     all_outputs = nest.map_structure_up_to(batch_outputs, concat, outputs)
   1615     return tf_utils.to_numpy_or_python_type(all_outputs)
   1616 

~//lib/python3.7/site-packages/tensorflow/python/util/nest.py in map_structure_up_to(shallow_tree, func, *inputs, **kwargs)
   1137       lambda _, *values: func(*values),  # Discards the path arg.
   1138       *inputs,
-> 1139       **kwargs)
   1140 
   1141 

~//lib/python3.7/site-packages/tensorflow/python/util/nest.py in map_structure_with_tuple_paths_up_to(shallow_tree, func, *inputs, **kwargs)
   1233                     in _yield_flat_up_to(shallow_tree, inputs[0], is_seq)]
   1234   results = [func(*args, **kwargs) for args in zip(flat_path_list,
-> 1235                                                    *flat_value_lists)]
   1236   return pack_sequence_as(structure=shallow_tree, flat_sequence=results,
   1237                           expand_composites=expand_composites)

~/lib/python3.7/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
   1232   flat_path_list = [path for path, _
   1233                     in _yield_flat_up_to(shallow_tree, inputs[0], is_seq)]
-> 1234   results = [func(*args, **kwargs) for args in zip(flat_path_list,
   1235                                                    *flat_value_lists)]
   1236   return pack_sequence_as(structure=shallow_tree, flat_sequence=results,

~/lib/python3.7/site-packages/tensorflow/python/util/nest.py in <lambda>(_, *values)
   1135   return map_structure_with_tuple_paths_up_to(
   1136       shallow_tree,
-> 1137       lambda _, *values: func(*values),  # Discards the path arg.
   1138       *inputs,
   1139       **kwargs)

~/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in concat(tensors, axis)
   2671   if isinstance(tensors[0], ragged_tensor.RaggedTensor):
   2672     return ragged_concat_ops.concat(tensors, axis=axis)
-> 2673   return array_ops.concat(tensors, axis=axis)
   2674 
   2675 

~/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py in concat(values, axis, name)
   1652           dtype=dtypes.int32).get_shape().assert_has_rank(0)
   1653       return identity(values[0], name=name)
-> 1654   return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
   1655 
   1656 

~/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py in concat_v2(values, axis, name)
   1205       return _result
   1206     except _core._NotOkStatusException as e:
-> 1207       _ops.raise_from_not_ok_status(e, name)
   1208     except _core._FallbackException:
   1209       pass

~/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6841   message = e.message + (" name: " + name if name is not None else "")
   6842   # pylint: disable=protected-access
-> 6843   six.raise_from(core._status_to_exception(e.code, message), None)
   6844   # pylint: enable=protected-access
   6845 

~/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

ResourceExhaustedError: OOM when allocating tensor with shape[1532,128,2049,2] and type complex64 on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:ConcatV2] name: concat
```

**Comment by amahendrakar** [comment]
@lminer,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using.

Also, try setting a hard limit on the total GPU memory as shown in [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and let us know if you are facing the same error. Thanks!

**Comment by lminer** [comment]
@amahendrakar  the problem seems to occur when the output of the model is complex. Here's a simply example that gives a resource exhausted error on a RTX 2080 ti on the final concat operation.

```python
import numpy as np
import tensorflow as tf

def to_complex(x):
    return tf.dtypes.complex(x, x)
    
base_model = tf.keras.applications.DenseNet201(weights='imagenet', include_top=False)
x = base_model.output
x = tf.keras.layers.Lambda(to_complex)(x)


model = tf.keras.Model(inputs=base_model.input, outputs=x)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')
X = np.random.rand(10000, 224, 224, 3).astype("float32")
out = model.predict(X, batch_size=64)
```

I'm running:
ubuntu 18.04
tensorflow 2.3.1
RTX 2080 ti

**Comment by amahendrakar** [comment]
@lminer,
The source of the error seems to be `X = np.random.rand(10000, 224, 224, 3).astype("float32")`. I was able to run the code without any issues with an array of a smaller size.

Is there any specific reason you are using such a large array? Thanks!

**Comment by lminer** [comment]
@amahendrakar I'm running inference on audio files, which at higher sample rates can get very large. That array is actually pretty normal sized for me. Is there a reason that the final concatenate needs to occur on the GPU? Is it even any faster?

**Comment by hangqiu** [comment]
Any solution or workaround for this? Isn't this happening to any imagenet prediction, which has to concat a (>1.2M, 1000) tensor as output? I'm observing same OOM error when extracting last activation layers of an efficientnet for imagenet prediction, which needs to concat a (>1.2M, 1280) tensor, but doesn't seem to have the same error if I get the 1000 class output directly...

**Comment by pablo-pnunez** [comment]
My solution:
`with tf.device("cpu:0"): prediction = model.predict()`
Using the CPU for the inference solves the problem in my case.

**Comment by agraham9966** [comment]
> My solution:
> `with tf.device("cpu:0"): prediction = model.predict()`
> Using the CPU for the inference solves the problem in my case.

I can verify this works for me - amazingly. My cpu maxed out to 100 but it did return a prediction without OOM error. 

It would be great if tensorflow had a solution for this. Maybe an ability to inference over tiles within the tensor and reconstruct the output if there is no other option.

**Comment by Saghar-H** [comment]
> My solution:
> `with tf.device("cpu:0"): prediction = model.predict()`
> Using the CPU for the inference solves the problem in my case.

Unfortunately, It didn't solve my problem and it stops with this message: "Killed" :(

**Comment by jvishnuvardhan** [comment]
@lminer I can reproduce the issue with `tf-nightly` (`TF2.8.dev`). 
 As it is related to keras, Is it possible for you to move this issue to keras-team/keras repo?

Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues). Thanks!
