### ISSUE TITLE
Could not load dynamic library 'libcudnn.so.8'

### ISSUE THREAD

**Issue by martinpolacek** [tensorflow/tensorflow#45200]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7.9
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tf-nightly-gpu 2.5.0.dev20201125
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): ---
- GCC/Compiler version (if compiling from source): ---
- CUDA/cuDNN version: 11.1
- GPU model and memory: 10 x 1080Ti 11GB

I want to create keras model using multiple GPUs.

I have prepared simple code to display visible devices:

```
import os
import tensorflow as tf

os.environ["CUDA_VISIBLE_DEVICES"]="7, 8, 9"
tf.config.experimental.list_logical_devices('GPU')
```

But my output is:

```
2020-11-26 10:23:19.183104: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-11-26 10:23:22.087731: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-11-26 10:23:22.089534: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-11-26 10:23:22.894765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 0 with properties:
pciBusID: 0000:0d:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2020-11-26 10:23:22.901688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 1 with properties:
pciBusID: 0000:0e:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2020-11-26 10:23:22.908844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 2 with properties:
pciBusID: 0000:0f:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2020-11-26 10:23:22.908893: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-11-26 10:23:22.913327: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-11-26 10:23:22.913376: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2020-11-26 10:23:22.914897: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-11-26 10:23:22.915190: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-11-26 10:23:22.917940: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2020-11-26 10:23:22.918885: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2020-11-26 10:23:22.919011: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2020-11-26 10:23:22.919038: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1764] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

**Comment by ValleZ** [comment]
Same happens for Ubuntu WSL 2 after following https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-wsl2 and not using docker:
```
>>> import tensorflow_text as text
2020-11-26 14:56:59.928177: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> import tensorflow as tf
>>> import tensorflow_hub as hub
>>> text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
rocessor = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/1")>>> preprocessor = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/1")
2020-11-26 14:57:22.940593: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-11-26 14:57:22.952421: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-11-26 14:57:23.213309: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:927] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2020-11-26 14:57:23.213654: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1070 computeCapability: 6.1
coreClock: 1.683GHz coreCount: 15 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 238.66GiB/s
2020-11-26 14:57:23.213728: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-11-26 14:57:23.253183: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-11-26 14:57:23.253310: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2020-11-26 14:57:23.282988: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-11-26 14:57:23.290707: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-11-26 14:57:23.309221: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2020-11-26 14:57:23.313288: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2020-11-26 14:57:23.313511: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
```

**Comment by martinpolacek** [comment]
Solved using Anaconda.

**Comment by akshayrana30** [comment]
Same issue with "tensorflow==2.4.0rc" on WSL 2 Ubuntu with Cuda 11

**Comment by FGhavamian** [comment]
> Solved using Anaconda.

Anaconda doesn't have `tf-nightly-gpu 2.5.0`. Care to elaborate on how you fix it?

**Comment by alonkipnis** [comment]
Same issue with Ubuntu 18.04.4, tensorflow==2.4.1, and Cuda 11.0. 

I'm not sure why this issue is closed.

**Comment by jaunruh** [comment]
Same issue with Ubuntu 20.04, tensorflow 2.4.1 and cuda 11.2.

**Comment by ValleZ** [comment]
Vanilla tensorflow doesn't work with cuda out of the box. Just follow Nvidia's instructions and use containerized special tensorflow-nvidia with pre-set up environment around.

**Comment by Saduf2019** [comment]
@ValleZ 
Please create a new issue as this issue is in closed status.

**Comment by barmanroys** [comment]
> Vanilla tensorflow doesn't work with cuda out of the box. Just follow Nvidia's instructions and use containerized special tensorflow-nvidia with pre-set up environment around.

Faced the same error. Can point me to any specific link which gives the necessary packages and installation instruction? Also, does it mean all my development efforts will have to be inside a docker container?

**Comment by lxy764139720** [comment]
> Same issue with Ubuntu 20.04, tensorflow 2.4.1 and cuda 11.2.
> 
> EDIT:
> In my case the issue was, that I needed to install `libcudnn8`. I did so downloading and executing the debian package from [here](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/).

It helps me a lot!
My env is Ubuntu 20.04 kernel 5.8.0-45-generic,nvidia-460.67,cuda 11.0,cudnn v8.0.5,tensorflow 2.4.1.
I downloaded and installed "libcudnn8_8.0.5.39-1+cuda11.0_amd64.deb", and the question was solved.

**Comment by HeliumPeng** [comment]
I got same situation when using my school's GPU farm, and I ran "conda install -c nvidia cudnn", then the problem is gone(The machine had already install CUDA10.1 and cudnn8.0.4)

**Comment by staniPetrox** [comment]
> I got same situation when using my school's GPU farm, and I ran "conda install -c nvidia cudnn", then the problem is gone(The machine had already install CUDA10.1 and cudnn8.0.4)

Worked for me as well

**Comment by MortenTabaka** [comment]
You can also use `**conda install -c conda-forge cudnn**`, if it would not start download after using `conda install -c nvidia cudnn` (as it was in my case). It helped me solve the problem.

Ubuntu 18.04; TensorFlow 2.5.0;

[conda-forge cudnn](https://anaconda.org/conda-forge/cudnn)

**Comment by WeyShi** [comment]
I solved it by adding the link of my lib to .bashrc and then `source .bashrc`.

**Comment by ChasedByDeath** [comment]
> I solved it by adding the link of my lib to .bashrc and then `source .bashrc`.

Can you please explain elaborately what exactly you did? Thank you!

**Comment by ChasedByDeath** [comment]
> Same issue with Ubuntu 20.04, tensorflow 2.4.1 and cuda 11.2.
> 
> EDIT: In my case the issue was, that I needed to install `libcudnn8`. I did so downloading and executing the debian package from [here](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/).

**Thank you so much**. This seem to have fixed the problem for me. 
My setup details -
Operating System: Ubuntu 20.04.3 LTS
Kernel: Linux 5.11.0-43-generic
Architecture: x86-64

Nvidia driver: 470.86 
Cuda toolkit: 11.2, V11.2.67
Tensorflow: 2.5.2

**Comment by zgfh** [comment]
see: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/11729624/177709010-2519b31a-9054-4dc5-8616-b01b70decc35.png">

this work for me (centos7)
```
find / -name "*libcuda.so*"
cd /usr/lib64/
ls -al |grep cuda
 ln -s libcuda.so.515.43.04 libcudnn.so.8
```
<img width="757" alt="image" src="https://user-images.githubusercontent.com/11729624/177709162-17a11a0d-2432-4467-abf0-d136b7b085af.png">

**Comment by veronica320** [comment]
> see: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html <img alt="image" width="1207" src="https://user-images.githubusercontent.com/11729624/177709010-2519b31a-9054-4dc5-8616-b01b70decc35.png">
> 
> this work for me (centos7)
> 
> ```
> find / -name "*libcuda.so*"
> cd /usr/lib64/
> ls -al |grep cuda
>  ln -s libcuda.so.515.43.04 libcudnn.so.8
> ```
> 
> <img alt="image" width="757" src="https://user-images.githubusercontent.com/11729624/177709162-17a11a0d-2432-4467-abf0-d136b7b085af.png">

Works for me! Thanks!

**Comment by andriworld** [comment]
This worked for me on Ubuntu 22.04.1 LTS
`sudo apt install nvidia-cudnn`

It's a large install but it worked best for me as several other library files were missing.

**Comment by matifali** [comment]
or simply `sudo apt install libcudnn8`
