### ISSUE TITLE
Unable to install CUDA 11.1 and cuDNN 8.05 for tensorflow 2.3

### ISSUE THREAD

**Issue by anirudhakulkarni** [tensorflow/tensorflow#45258]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.3
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1 and 8.05
- GPU model and memory: GeForce GTX 1650 4GB

**Describe the problem**
Unable to detect GPU
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Installed tensorflow 2.3
Installed CUDA 11.1
Downloaded cuDNN 8.05
added files from cuDNN to the respective folders in CUDA directory
added CUDA to the path
imported tensorflow-gpu in python shows error that gpu not found
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ahtik** [comment]
TensorFlow 2.3 requires CUDA 10.1. CUDA 11.0 (not CUDA 11.1) becomes supported with TensorFlow 2.4.

With Win10 you can easily install CUDA 10.1 in addition to your current CUDA 11.1 simply by installing CUDA 10.1 on top of current setup but make sure to **not** install any drivers by doing it (CUDA 10.1 is compatible with the latest drivers).

After that make sure your CUDA-related system environment variables point to the 10.1 version.

Would this fix the error?

**Comment by Saduf2019** [comment]
@anirudhakulkarni 
Please refer to this comment on [cuda 11.1](https://github.com/tensorflow/tensorflow/issues/44159#issuecomment-735542190), could you please use nightly and let us know.

**Comment by anirudhakulkarni** [comment]
@ahtik  thanks for the response. This should work I guess. But I wanted to know if I could use CUDA 11.1
@Saduf2019 thanks for the response. I tried the nightly:
it said:
tf-nightly-gpu 2.5.0.dev20201128 requires numpy~=1.19.2, but you'll have numpy 1.18.5 which is incompatible.
and installed my previous numpy 1.19.4 and installed 1.18.5
But still when I tried to check if its working by:
`import tensorflow as tf`
`print(tf.test.is_gpu_available())`
it throws:
WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2020-11-30 19:19:10.581054: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-30 19:19:10.593149: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-11-30 19:19:11.267760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1650 computeCapability: 7.5
coreClock: 1.56GHz coreCount: 16 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 119.24GiB/s
2020-11-30 19:19:11.268049: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-11-30 19:19:11.752064: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-11-30 19:19:11.752305: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-11-30 19:19:12.020271: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-11-30 19:19:12.055871: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-11-30 19:19:12.058268: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-11-30 19:19:12.266522: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-11-30 19:19:12.289685: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-11-30 19:19:12.289912: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1764] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-11-30 19:19:13.228085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-30 19:19:13.228375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1273]      0
2020-11-30 19:19:13.229647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1286] 0:   N
2020-11-30 19:19:13.232971: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
False

**Comment by Saduf2019** [comment]
@anirudhakulkarni 
Please confim if you have used cuda 11 and not 11.1

**Comment by anirudhakulkarni** [comment]
Its 11.1. I mentioned it 11.1 everywhere

**Comment by ahtik** [comment]
@Saduf2019 It looks like the use of "cuda 11" is causing confusion in quite a few issues, maybe worth being more explicit in triage with the full version numbers (11.0 instead of 11). For most, version 11 is seen as 11.x.

**Comment by ahtik** [comment]
@anirudhakulkarni Your nightly build with Cuda 11.1 "mostly" works (the only error is cusolver not being found).

In our system the following works, feel free to try this setup and let me know:
1.  I have updated to CUDA 11.1.1 (it's an in-place update for the existing 11.1). Reiterating - whenever installing a new or older CUDA, *always* choose Advanced mode to exclude any driver installation.
2. Latest cudnn has been downloaded to `C:\cudnn-8.0.5\11.1\`
The following works (env paths are for our own internal use for being able to easily switch between CUDA installations):
```
\python38\python.exe -m venv \p\venv-tf-n
\p\venv-tf-n\Scripts\activate
python -m pip install -U pip
pip install tf-nightly-gpu==2.5.0.dev20201130 numpy==1.19.3

SET CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
SET PATH=C:\cudnn-8.0.5\11.1\bin;%CUDA_PATH%\bin;%CUDA_PATH%\libnvvp;%PATH%
python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])));print(tf.config.list_physical_devices('GPU'))"
```

**Comment by anirudhakulkarni** [comment]
thank you @ahtik for help.
Just to confirm :
1. `\python38\python.exe -m venv \p\venv-tf-n`
`\p\venv-tf-n\Scripts\activate` 
these 2 lines didn't work on my system so I didn't create virtual environment.
2. I downloaded the cudnn again. It was named "cudnn-11.1-windows-x64-v8.0.5.39" so to follow your instructions I copied it to C drive and renamed it as cudnn-8.0.5 and there was a folder by name cuda and I renamed it as 11.1 so as to match with the path you mentioned

Result:
Same didn't work.
2020-12-02 12:29:29.506366: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-02 12:29:31.895115: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-02 12:29:31.896303: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-12-02 12:29:31.918460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1650 computeCapability: 7.5
coreClock: 1.56GHz coreCount: 16 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 119.24GiB/s
2020-12-02 12:29:31.918715: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-02 12:29:31.927910: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-02 12:29:31.928266: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-02 12:29:31.935820: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-12-02 12:29:31.938315: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-12-02 12:29:31.939781: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-12-02 12:29:31.963246: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-12-02 12:29:31.964109: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-02 12:29:31.964623: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1764] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-12-02 12:29:31.965561: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-02 12:29:31.969817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-02 12:29:31.969998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1273]
2020-12-02 12:29:31.970462: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
tf.Tensor(990.16626, shape=(), dtype=float32)
[]

After this I reinstalled CUDA 11.1 (without drivers. I already have NVIDIA studio driver 457.30 ) and restarted system but still no luck. same error message

**Comment by ahtik** [comment]
@anirudhakulkarni Oh, I just noticed that my PATH was already "littered" with the CUDA 11.0 paths, so the CUDA 11.1 took precedence but cusolver64_10.dll was still taken from the CUDA 11.0 dir.

This explains why it first worked for me. You're also saving yourself time by additionally installing CUDA 11.0 and making sure it is being used. Having CUDA 11.0 should make it possible to use both `tensorflow==2.4.0rc3` and nightly. For the latest "stable" release `tensorflow==2.3.1` you'd need CUDA 10.1.

My cudnn instruction might have been too involved, could be easier to just extract the contents to the CUDA dir as instructed in docs. I just prefer to have a bit more control over deployment and need multiple cuda&cudnn combinations.

If  you install CUDA 11.0 then does it work with `tensorflow==2.4.0rc3` and/or `tf-nightly-gpu==2.5.0.dev20201201`?

The choice of "primary"/active CUDA is only taken from the Windows env variables.

For CUDA 11.0 I'm using `cudnn-8.0.4.30`.

PS. My venv commands were expecting python to be installed in c:\python38\ dir.

Adding my console output for reference.
```
\p\venv-tf-n\Scripts\activate

(venv-tf-n) C:\Users\ak>SET CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1

(venv-tf-n) C:\Users\ak>SET PATH=C:\cudnn-8.0.5\11.1\bin;%CUDA_PATH%\bin;%CUDA_PATH%\libnvvp;%PATH%

(venv-tf-n) C:\Users\ak>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])));print(tf.config.list_physical_devices('GPU'))"
2020-12-02 10:17:27.383440: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-02 10:17:30.824838: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-02 10:17:30.826042: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-12-02 10:17:30.856819: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 SUPER computeCapability: 7.5
coreClock: 1.8GHz coreCount: 40 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-12-02 10:17:30.856915: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-02 10:17:31.243185: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-02 10:17:31.243282: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-02 10:17:31.465292: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-12-02 10:17:31.492316: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-12-02 10:17:31.716494: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-12-02 10:17:31.891929: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-12-02 10:17:32.928875: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-02 10:17:32.929293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1869] Adding visible gpu devices: 0
2020-12-02 10:17:32.931569: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-02 10:17:32.932795: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 SUPER computeCapability: 7.5
coreClock: 1.8GHz coreCount: 40 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-12-02 10:17:32.932929: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-02 10:17:32.933032: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-02 10:17:32.933130: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-02 10:17:32.933226: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-12-02 10:17:32.933298: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-12-02 10:17:32.933356: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-12-02 10:17:32.933409: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-12-02 10:17:32.933471: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-02 10:17:32.933554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1869] Adding visible gpu devices: 0
2020-12-02 10:17:33.866419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-02 10:17:33.866513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1273]      0
2020-12-02 10:17:33.866770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1286] 0:   N
2020-12-02 10:17:33.868306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1413] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6611 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-12-02 10:17:33.869560: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
tf.Tensor(914.61194, shape=(), dtype=float32)
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

**Comment by Saduf2019** [comment]
@anirudhakulkarni
 Please update, is this still an issue

**Comment by anirudhakulkarni** [comment]
Sorry @ahtik  @Saduf2019  for the delayed response.
No, it didn't work—same error.
This time I am attaching some relevant info too.
The output of pip list:
~~~
Package                  Version
------------------------ -------------------
absl-py                  0.10.0
argcomplete              1.10.0
astroid                  2.4.1
astunparse               1.6.3
atomicwrites             1.4.0
attrs                    19.3.0
backcall                 0.1.0
beautifulsoup4           4.8.0
bleach                   3.1.5
cachetools               4.1.1
certifi                  2020.4.5.1
cffi                     1.14.3
chardet                  3.0.4
colorama                 0.4.3
cryptography             3.1.1
cssselect                1.1.0
cycler                   0.10.0
Cython                   0.29.21
dataclasses              0.6
decorator                4.4.2
defusedxml               0.6.0
dill                     0.3.2
distro                   1.5.0
dlx                      1.0.4
docplex                  2.15.194
docx2txt                 0.8
EasyProcess              0.3
EbookLib                 0.17.1
entrypoint2              0.2.1
entrypoints              0.3
extract-msg              0.23.1
fastdtw                  0.3.4
fastjsonschema           2.14.5
flatbuffers              1.12
future                   0.18.2
gast                     0.3.3
google-auth              1.21.3
google-auth-oauthlib     0.4.1
google-pasta             0.2.0
grpcio                   1.32.0
h5py                     2.10.0
idna                     2.9
imageio                  2.8.0
IMAPClient               2.1.0
inflection               0.5.1
ipykernel                5.3.0
ipython                  7.15.0
ipython-genutils         0.2.0
isort                    4.3.21
javaobj-py3              0.4.1
jedi                     0.17.0
Jinja2                   2.11.2
joblib                   0.16.0
json5                    0.9.5
jsonschema               3.2.0
jupyter-client           6.1.3
jupyter-core             4.6.3
jupyterlab               2.1.4
jupyterlab-server        1.1.5
Keras-Preprocessing      1.1.2
keyboard                 0.13.5
kiwisolver               1.2.0
lazy-object-proxy        1.4.3
lxml                     4.5.2
Markdown                 3.2.2
MarkupSafe               1.1.1
matplotlib               3.2.1
mccabe                   0.6.1
mistune                  0.8.4
more-itertools           8.4.0
mosspy                   1.0.8
MouseInfo                0.1.3
mpmath                   1.1.0
mss                      6.0.0
multitasking             0.0.9
nbconvert                5.6.1
nbformat                 5.0.6
nest-asyncio             1.4.0
networkx                 2.5
notebook                 6.0.3
ntlm-auth                1.5.0
numpy                    1.19.3
oauthlib                 3.1.0
olefile                  0.46
opencv-python            4.4.0.42
opt-einsum               3.3.0
packaging                20.4
pandas                   1.0.4
pandocfilters            1.4.2
parsel                   1.6.0
parso                    0.7.0
pdfminer                 20191125
pdfminer.six             20181108
pickleshare              0.7.5
Pillow                   7.1.2
pip                      20.3.1
pluggy                   0.13.1
ply                      3.11
prometheus-client        0.8.0
prompt-toolkit           3.0.5
protobuf                 3.13.0
psutil                   5.7.2
py                       1.8.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
PyAutoGUI                0.9.50
pybind11                 2.5.0
pycparser                2.20
pycryptodome             3.9.8
PyGetWindow              0.0.8
Pygments                 2.6.1
pylint                   2.5.2
PyMsgBox                 1.0.8
pyparsing                2.4.7
PyPDF2                   1.26.0
pyperclip                1.8.0
PyRect                   0.1.4
pyrsistent               0.16.0
pyscreenshot             2.2
PyScreeze                0.1.26
pytest                   5.4.3
python-constraint        1.4.0
python-dateutil          2.8.1
python-pptx              0.6.18
pytube                   9.6.0
pytube3                  9.6.4
PyTweening               1.0.3
pytz                     2020.1
pywin32                  227
pywinpty                 0.5.7
PyYAML                   5.3.1
pyzmq                    19.0.1
qiskit                   0.21.0
qiskit-aer               0.6.1
qiskit-aqua              0.7.5
qiskit-ibmq-provider     0.9.0
qiskit-ignis             0.4.0
qiskit-terra             0.15.2
qsharp                   0.12.2007.2031
Quandl                   3.5.2
requests                 2.23.0
requests-ntlm            1.1.0
requests-oauthlib        1.3.0
retworkx                 0.5.0
rsa                      4.6
scikit-learn             0.23.2
scipy                    1.4.1
selenium                 3.141.0
Send2Trash               1.5.0
setuptools               47.1.0
six                      1.15.0
sklearn                  0.0
sortedcontainers         2.2.2
soupsieve                2.0.1
SpeechRecognition        3.8.1
sympy                    1.6.2
tabula                   1.0.5
tabula-py                2.2.0
tb-nightly               2.5.0a20201128
tensorboard              2.4.0
tensorboard-plugin-wit   1.7.0
tensorboardX             2.1
tensorflow               2.4.0rc3
tensorflow-estimator     2.4.0rc0
tensorflow-gpu           2.3.1
tensorflow-gpu-estimator 2.3.0
termcolor                1.1.0
terminado                0.8.3
testpath                 0.4.4
textract                 1.6.3
tf-estimator-nightly     2.4.0.dev2020102301
tf-nightly-gpu           2.5.0.dev20201130
threadpoolctl            2.1.0
toml                     0.10.1
torch                    1.7.0+cpu
torchaudio               0.7.0
torchvision              0.8.1+cpu
tornado                  6.0.4
traitlets                4.3.3
typing-extensions        3.7.4.3
tzlocal                  1.5.1
urllib3                  1.25.9
w3lib                    1.22.0
wcwidth                  0.2.3
webencodings             0.5.1
websockets               8.1
Werkzeug                 1.0.1
wheel                    0.35.1
wrapt                    1.12.1
xlrd                     1.2.0
XlsxWriter               1.3.6
yfinance                 0.1.54
~~~
Environment variables:
![image](https://user-images.githubusercontent.com/29736196/101255888-2d775b00-3745-11eb-89a4-6a6b7483f821.png)

Final output for ```python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])));print(tf.config.list_physical_devices('GPU'))"``` :
~~~
C:\Users\91930>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])));print(tf.config.list_physical_devices('GPU'))"
2020-12-05 21:54:10.995836: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-05 21:54:13.347310: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-05 21:54:13.348033: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-12-05 21:54:14.457474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1650 computeCapability: 7.5
coreClock: 1.56GHz coreCount: 16 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 119.24GiB/s
2020-12-05 21:54:14.457650: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-05 21:54:14.464722: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-05 21:54:14.464862: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-05 21:54:14.468456: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-12-05 21:54:14.469702: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-12-05 21:54:14.470886: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-12-05 21:54:14.474321: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-12-05 21:54:14.496440: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-05 21:54:14.496592: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1764] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-12-05 21:54:14.497192: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-05 21:54:14.497932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-05 21:54:14.498055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1273]
2020-12-05 21:54:14.499112: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
tf.Tensor(22.821045, shape=(), dtype=float32)
[]
~~~

Also to make sure I installed Cudnn correctly, the directory structure for relevant folders is:
~~~
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin>ls
bin2c.exe              cudnn_adv_infer64_8.dll  curand64_10.dll      nppig64_11.dll   nvjpeg64_11.dll
compute-sanitizer.bat  cudnn_adv_train64_8.dll  cusolver64_11.dll    nppim64_11.dll   nvlink.exe
crt                    cudnn_cnn_infer64_8.dll  cusolverMg64_11.dll  nppist64_11.dll  nvprof.exe
cublas64_11.dll        cudnn_cnn_train64_8.dll  cusparse64_11.dll    nppisu64_11.dll  nvprune.exe
cublasLt64_11.dll      cudnn_ops_infer64_8.dll  fatbinary.exe        nppitc64_11.dll  nvrtc-builtins64_111.dll
cuda-memcheck.exe      cudnn_ops_train64_8.dll  nppc64_11.dll        npps64_11.dll    nvrtc64_111_0.dll
cudafe++.exe           cufft64_10.dll           nppial64_11.dll      nvblas64_11.dll  nvvp.bat
cudart32_110.dll       cufftw64_10.dll          nppicc64_11.dll      nvcc.exe         ptxas.exe
cudart64_110.dll       cuinj64_111.dll          nppidei64_11.dll     nvcc.profile
cudnn64_8.dll          cuobjdump.exe            nppif64_11.dll       nvdisasm.exe
~~~
~~~
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1>ls
CUDA_Toolkit_Release_Notes.txt  EULA.txt  bin                extras   lib      nvml  src
DOCS                            README    compute-sanitizer  include  libnvvp  nvvm  tools
~~~
~~~
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include>ls
CL                           cudnn_version.h                           nppi_filtering_functions.h
builtin_types.h              cufft.h                                   nppi_geometry_transforms.h
channel_descriptor.h         cufftXt.h                                 nppi_linear_transforms.h
common_functions.h           cufftw.h                                  nppi_morphological_operations.h
cooperative_groups           curand.h                                  nppi_statistics_functions.h
cooperative_groups.h         curand_discrete.h                         nppi_support_functions.h
crt                          curand_discrete2.h                        nppi_threshold_and_compare_operations.h
cuComplex.h                  curand_globals.h                          npps.h
cub                          curand_kernel.h                           npps_arithmetic_and_logical_operations.h
cublas.h                     curand_lognormal.h                        npps_conversion_functions.h
cublasLt.h                   curand_mrg32k3a.h                         npps_filtering_functions.h
cublasXt.h                   curand_mtgp32.h                           npps_initialization.h
cublas_api.h                 curand_mtgp32_host.h                      npps_statistics_functions.h
cublas_v2.h                  curand_mtgp32_kernel.h                    npps_support_functions.h
cuda                         curand_mtgp32dc_p_11213.h                 nvPTXCompiler.h
cuda.h                       curand_normal.h                           nvblas.h
cudaD3D10.h                  curand_normal_static.h                    nvfunctional
cudaD3D11.h                  curand_philox4x32_x.h                     nvjpeg.h
cudaD3D9.h                   curand_poisson.h                          nvml.h
cudaGL.h                     curand_precalc.h                          nvrtc.h
cudaProfiler.h               curand_uniform.h                          nvtx3
cuda_awbarrier.h             cusolverDn.h                              sm_20_atomic_functions.h
cuda_awbarrier_helpers.h     cusolverMg.h                              sm_20_atomic_functions.hpp
cuda_awbarrier_primitives.h  cusolverRf.h                              sm_20_intrinsics.h
cuda_bf16.h                  cusolverSp.h                              sm_20_intrinsics.hpp
cuda_bf16.hpp                cusolverSp_LOWLEVEL_PREVIEW.h             sm_30_intrinsics.h
cuda_d3d10_interop.h         cusolver_common.h                         sm_30_intrinsics.hpp
cuda_d3d11_interop.h         cusparse.h                                sm_32_atomic_functions.h
cuda_d3d9_interop.h          cusparse_v2.h                             sm_32_atomic_functions.hpp
cuda_device_runtime_api.h    device_atomic_functions.h                 sm_32_intrinsics.h
cuda_egl_interop.h           device_atomic_functions.hpp               sm_32_intrinsics.hpp
cuda_fp16.h                  device_double_functions.h                 sm_35_atomic_functions.h
cuda_fp16.hpp                device_functions.h                        sm_35_intrinsics.h
cuda_gl_interop.h            device_launch_parameters.h                sm_60_atomic_functions.h
cuda_occupancy.h             device_types.h                            sm_60_atomic_functions.hpp
cuda_pipeline.h              driver_functions.h                        sm_61_intrinsics.h
cuda_pipeline_helpers.h      driver_types.h                            sm_61_intrinsics.hpp
cuda_pipeline_primitives.h   fatBinaryCtl.h                            surface_functions.h
cuda_profiler_api.h          fatbinary.h                               surface_functions.hpp
cuda_runtime.h               fatbinary_section.h                       surface_indirect_functions.h
cuda_runtime_api.h           host_config.h                             surface_indirect_functions.hpp
cuda_surface_types.h         host_defines.h                            surface_types.h
cuda_texture_types.h         library_types.h                           texture_fetch_functions.h
cudalibxt.h                  math_constants.h                          texture_fetch_functions.hpp
cudart_platform.h            math_functions.h                          texture_indirect_functions.h
cudnn.h                      mma.h                                     texture_indirect_functions.hpp
cudnn_adv_infer.h            npp.h                                     texture_types.h
cudnn_adv_train.h            nppcore.h                                 thrust
cudnn_backend.h              nppdefs.h                                 vector_functions.h
cudnn_cnn_infer.h            nppi.h                                    vector_functions.hpp
cudnn_cnn_train.h            nppi_arithmetic_and_logical_operations.h  vector_types.h
cudnn_ops_infer.h            nppi_color_conversion.h
cudnn_ops_train.h            nppi_data_exchange_and_initialization.h
~~~
~~~

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64>ls
OpenCL.lib         cudnn_adv_infer.lib      cudnn_ops_infer64_8.lib  nppc.lib     nppitc.lib
cublas.lib         cudnn_adv_infer64_8.lib  cudnn_ops_train.lib      nppial.lib   npps.lib
cublasLt.lib       cudnn_adv_train.lib      cudnn_ops_train64_8.lib  nppicc.lib   nvblas.lib
cuda.lib           cudnn_adv_train64_8.lib  cufft.lib                nppidei.lib  nvjpeg.lib
cudadevrt.lib      cudnn_cnn_infer.lib      cufftw.lib               nppif.lib    nvml.lib
cudart.lib         cudnn_cnn_infer64_8.lib  curand.lib               nppig.lib    nvptxcompiler_static.lib
cudart_static.lib  cudnn_cnn_train.lib      cusolver.lib             nppim.lib    nvrtc.lib
cudnn.lib          cudnn_cnn_train64_8.lib  cusolverMg.lib           nppist.lib
cudnn64_8.lib      cudnn_ops_infer.lib      cusparse.lib             nppisu.lib

~~~

This is all I have. I am still unsure where did I go wrong. Any suggestion will be extremely helpful.

**Comment by ahtik** [comment]
@anirudhakulkarni As said, it is not recommended to keep going with CUDA 11.1, even after renaming `cusolver64_11` to `cusolver64_10` unless there is no possibility to install CUDA 11.0 in your Windows installation :)

`cusolver64_10.dll` is part of CUDA 11.0 and CUDA 10.1 installation, `cusolver64_11.dll` is part of CUDA 11.1.
Using a wrong version `.dll` simply by renaming it asks for more confusing errors than the one you had at the startup :)

Please consider installing CUDA 11.0, which is supported and would work with `tensorflow==2.4.0rc3`, `tensorflow==2.4.0rc4` and for example the latest `tf-nightly-gpu==2.5.0.dev20201206`.

**Comment by Saduf2019** [comment]
@anirudhakulkarni 
As already informed repeatedly please CUDA 11.0 and not 11.1.

**Comment by anirudhakulkarni** [comment]
Thanks for resolving the issue. It worked with CUDA 11.0.
