### ISSUE TITLE
Error while updating tensorflow installed from source

### ISSUE THREAD

**Issue by kkjh0723** [tensorflow/tensorflow#4531]
### Environment info
Operating System: Ubuntu 14.04.4

Installed version of CUDA and cuDNN: CUDA 8.0, cuDNN 5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

    -rw-r--r-- 1 root root   560184  7월 29 09:12 /usr/local/cuda-8.0/lib64/libcudadevrt.a
    lrwxrwxrwx 1 root root       16  7월 29 09:12 /usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
    lrwxrwxrwx 1 root root       19  7월 29 09:12 /usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
    -rwxr-xr-x 1 root root   394472  7월 29 09:12 /usr/local/cuda-8.0/lib64/libcudart.so.8.0.27
    -rw-r--r-- 1 root root   737516  7월 29 09:12 /usr/local/cuda-8.0/lib64/libcudart_static.a
    -rwxr-xr-x 1 root root 78065952  7월 29 09:43 /usr/local/cuda-8.0/lib64/libcudnn.so
    -rwxr-xr-x 1 root root 78065952  7월 29 09:43 /usr/local/cuda-8.0/lib64/libcudnn.so.5
    -rwxr-xr-x 1 root root 78065952  7월 29 09:43 /usr/local/cuda-8.0/lib64/libcudnn.so.5.0.5
    -rw-r--r-- 1 root root 68709594  7월 29 09:43 /usr/local/cuda-8.0/lib64/libcudnn_static.a

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)

`ca1aa4ad2d4e011e8479319e10d73281a50f7560`

2. The output of `bazel version`

     Build label: 0.2.3
     Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
     Build time: Tue May 17 14:21:13 2016 (1463494873)
     Build timestamp: 1463494873
     Build timestamp as int: 1463494873

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

I installed tensorflow around two monthes ago and I've used it.
Then, I tried to update by following [Stackoverflow](http://stackoverflow.com/questions/34239537/how-to-update-tensorflow-from-source).

I first tried 'git pull', it could not be merged since I have some changes in source.
So I reset the source by

    git fetch --all
    git reset --hard origin/master

Then I did `./configure`. But it gives errors. I attached the output of the configure below.
It's weird because I successfully update with this way before.
Actually, I also tried same way in another system (Cuda 7.0 cuDNN 4), but failed with similar error message...

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

    Please specify the location of python. [Default is /home/jinhyung/anaconda2/bin/python]: 
    Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
    No Google Cloud Platform support will be enabled for TensorFlow
    Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
    No Hadoop File System support will be enabled for TensorFlow
    Found possible Python library paths:
      /home/jinhyung/anaconda2/lib/python2.7/site-packages
    Please input the desired Python library path to use.  Default is [/home/jinhyung/anaconda2/lib/python2.7/site-packages]
    
    /home/jinhyung/anaconda2/lib/python2.7/site-packages
    Do you wish to build TensorFlow with GPU support? [y/N] y
    GPU support will be enabled for TensorFlow
    Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
    Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
    Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
    Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
    Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
    Please specify a list of comma-separated Cuda compute capabilities you want to build with.
    You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
    Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
    INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    .
    ERROR: /home/jinhyung/tensorflow/tensorflow/tensorflow.bzl:567:26: Traceback (most recent call last):
    	File "/home/jinhyung/tensorflow/tensorflow/tensorflow.bzl", line 561
    		rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
    	File "/home/jinhyung/tensorflow/tensorflow/tensorflow.bzl", line 567, in rule
    		attr.label_list(cfg = "data", allow_files = True)
    expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead:     data.
    ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors.
    Configuration finished

**Comment by Oryak** [comment]
I was able to fix it locally for me by reverting
https://github.com/tensorflow/tensorflow/commit/7bcdcbbf60fc08346fd8016270a0563f4b51362b
and changing in the lines 567 and following: 

`
            cfg = DATA_CFG,
...
            cfg = HOST_CFG,

`

**Comment by ic** [comment]
@Oryak Same observation for the commit that causes the problem. However, the change you propose depends on the Bazel version. That will work before 0.3.1, if I am not mistaken (it may even be the 0.3.x series). From 0.3.1, `cfg` should be a string. See #4371 for related and recent activity.

**Comment by jmchen-g** [comment]
@jart Could you take a look at this? Thanks.

**Comment by kkjh0723** [comment]
@Oryak I could install without error after I update the bazel version 0.3.1. Problem solved.

**Comment by kamal94** [comment]
@kkjh0723 Problem not solved on linux. The [following correction](https://github.com/tensorflow/tensorflow/issues/4371#issuecomment-249340251) was needed. Bazel still pulls from an outdated protobuf archive

**Comment by jart** [comment]
The first solution is to upgrade Bazel to 0.3.1. But we have another problem @kamal94 identified where we need to update our protobuf dependency. See #4561.

**Comment by ccravens** [comment]
I also ran into this issue just now. I initially used homebrew on Mac to install bazel v0.2.3. After uninstall v0.2.3 and manually downloading and installing v0.3.1 it appears that the configuration finishes correctly.

**Comment by rahulgithub** [comment]
@ccravens  How did you uninstall bazel that was installed brew.. Thanks
