### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by jordan-bird** [tensorflow/tensorflow#45779]
**System information**
- OS: Windows 10
- TensorFlow installed from (source or binary):  "pip install tensorflow"
- TensorFlow version: 2.4.0
- Python version: 3.6.8
- Installed using: pip
- CUDA/cuDNN version: CUDA 11.0, cuDNN v8.0.4 (September 28th, 2020) for CUDA 11.0
- GPU model and memory: NVidia RTX2080Ti 11gb

Hi, 

I'm having a problem installing the new version of TF and some help would be greatly appreciated

When I launch TensorFlow, everything works as expected:

`2020-12-17 02:38:06.341560: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-17 02:38:08.362868: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-17 02:38:08.363763: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-12-17 02:38:08.393157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-12-17 02:38:08.393327: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-17 02:38:08.402693: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-17 02:38:08.402832: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-17 02:38:08.408295: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-12-17 02:38:08.410941: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-12-17 02:38:08.420106: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-12-17 02:38:08.424734: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-12-17 02:38:08.426865: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-17 02:38:08.427022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
Num GPUs Available:  1
2020-12-17 02:38:08.443738: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-17 02:38:08.444619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-12-17 02:38:08.444716: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-17 02:38:08.445101: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-17 02:38:08.446152: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-17 02:38:08.446937: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-12-17 02:38:08.447301: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-12-17 02:38:08.447647: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-12-17 02:38:08.448059: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-12-17 02:38:08.448403: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-17 02:38:08.448795: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2020-12-17 02:38:08.969074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-17 02:38:08.969175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2020-12-17 02:38:08.970017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2020-12-17 02:38:08.970724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9416 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-12-17 02:38:08.971475: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set`

But then, when I begin training the model:

`2020-12-17 02:38:10.285052: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2020-12-17 02:38:10.484223: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-17 02:38:10.925209: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-17 02:38:10.929739: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-17 02:38:11.425989: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-12-17 02:38:11.426101: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-12-17 02:38:11.428154: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-12-17 02:38:11.428256: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-12-17 02:38:11.428655: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:697 : Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
Traceback (most recent call last):
  File "style.py", line 226, in <module>
    combination_image, base_image, style_reference_image
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 895, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 560, in call
    ctx=ctx)
  File "C:\Users\Jordan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node model/block1_conv1/Relu (defined at style.py:159) ]] [Op:__inference_compute_loss_and_grads_1267]

Function call stack:
compute_loss_and_grads`

I used to use older versions of tensorflow-gpu on my GTX980 but had to update for my new RTX2080Ti, I've installed the CUDA and cuDNN versions noted here: https://www.tensorflow.org/install/gpu

Unfortunately using this combination doesn't seem to work, help would be greatly appreciated. The above errors occur when attempting to run the Keras style transfer example https://keras.io/examples/generative/neural_style_transfer/ during the final block of code:
`for i in range(1, iterations + 1):
	loss, grads = compute_loss_and_grads(
		combination_image, base_image, style_reference_image
	)
	optimizer.apply_gradients([(grads, combination_image)])
	print(i)
	if i % 100 == 0:
		print("Iteration %d: loss=%.2f" % (i, loss))
		img = deprocess_image(combination_image.numpy())
		fname = result_prefix + "_at_iteration_%d.png" % i
		keras.preprocessing.image.save_img(fname, img)`

Thanks,
Jordan

**Comment by jordan-bird** [comment]
GitHub is breaking lines so I've pasted an easier to read console output here: https://pastebin.com/7Fu9Kezs

After "Training..." is printed is when the model begins to train and the errors occur

**Comment by amahendrakar** [comment]
@jordan-bird,
Please try setting a hard limit on the total GPU memory as shown in [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and check if it helps. 

> GitHub is breaking lines so I've pasted an easier to read console output here

And to preserve the formatting in GitHub please add ``` (i.e. three back ticks) before and after the error log.

Thanks!

**Comment by jordan-bird** [comment]
Works like a charm! 

For anyone who also comes across this problem, the first solution listed on the guide linked by @amahendrakar produced the same error but the second block of code below it:

```gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)```

Fixed the issues and the training is now being performed by the GPU

**Comment by jfgf11** [comment]
Thank you soo much!!!! this solution worked perfectly 👍

**Comment by baranaldemir** [comment]
I have the same problem and I have only one GPU. I tried all 3 solutions recommended in the link and none of them worked. I still suffer from memory allocation problems. Here is the error I get:

 `2021-03-12 00:28:29.804317: I tensorflow/core/common_runtime/bfc_allocator.cc:1036] 3 Chunks of size 58491904 totalling 167.35MiB
2021-03-12 00:28:29.815991: I tensorflow/core/common_runtime/bfc_allocator.cc:1036] 1 Chunks of size 59466752 totalling 56.71MiB
2021-03-12 00:28:29.816114: I tensorflow/core/common_runtime/bfc_allocator.cc:1036] 1 Chunks of size 74294272 totalling 70.85MiB
2021-03-12 00:28:29.816233: I tensorflow/core/common_runtime/bfc_allocator.cc:1036] 1 Chunks of size 122827776 totalling 117.14MiB
2021-03-12 00:28:29.816355: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Sum Total of in-use chunks: 1002.91MiB
2021-03-12 00:28:29.816469: I tensorflow/core/common_runtime/bfc_allocator.cc:1042] total_region_allocated_bytes_: 1073741824 memory_limit_: 1073741824 available bytes: 0 curr_region_allocation_bytes_: 2147483648
2021-03-12 00:28:29.816722: I tensorflow/core/common_runtime/bfc_allocator.cc:1048] Stats: 
Limit:                      1073741824
InUse:                      1051624448
MaxInUse:                   1073741824
NumAllocs:                      825054
MaxAllocSize:                569103872
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2021-03-12 00:28:29.817160: W tensorflow/core/common_runtime/bfc_allocator.cc:441] *********************************************_************************************x***************xx
2021-03-12 00:28:29.817274: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at fused_batch_norm_op.cc:1448 : Resource exhausted: OOM when allocating tensor with shape[8,32,237,237] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "C:\Users\baran\.conda\envs\tf2.4\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\baran\.conda\envs\tf2.4\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\baran\.conda\envs\tf2.4\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,56,237,237] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node batch_normalization_3/FusedBatchNorm}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
`

**Comment by amahendrakar** [comment]
@baranaldemir,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
