### ISSUE TITLE
Could not load dynamic library 'libcudart.so.11.0'

### ISSUE THREAD

**Issue by ido-tera-group** [tensorflow/tensorflow#45930]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.4.0
- Python version: 3.7.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: libcudnn8_8.0.5.39-1+cuda11.0_amd64.deb (I also installed the dev version)
- NVIDIA Driver Version: 450.80.02
- GPU model and memory: GeForce RTX 2080 Super with Max-Q Design

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I tried following the instructions as described in: https://www.tensorflow.org/install/gpu
- I installed Ubuntu 20.04 (which installed the NVIDIA driver)
- Installed python using pyenv
- sudo apt install nvidia-cuda-toolkit
- pip install tensorflow
- Installed: libcudnn8_8.0.5.39-1+cuda11.0_amd64.deb
- (saw that it failed to find 'libcudart.so.11.0')
- Installed: libcudnn8-dev_8.0.5.39-1+cuda11.0_amd64.deb
- (still failed to find 'libcudart.so.11.0')

Is there a way for me to check which part of the installation broke?
Any ideas on what I can do to fix this?
Thanks!

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
PyDev console: starting.
Python 3.7.9 (default, Dec 22 2020, 21:13:51) 
[GCC 9.3.0] on linux
>>> import tensorflow as tf
>>> print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
2020-12-22 22:56:35.044676: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2020-12-22 22:56:35.044691: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/ido/TeraResearch/venv/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
2020-12-22 22:56:35.938373: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-22 22:56:35.938801: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-12-22 22:56:37.494184: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-12-22 22:56:37.494273: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ido-ml
2020-12-22 22:56:37.494291: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ido-ml
2020-12-22 22:56:37.494480: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 450.80.2
2020-12-22 22:56:37.494544: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 450.80.2
2020-12-22 22:56:37.494561: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 450.80.2
Num GPUs Available:  0
```

**Comment by ravikyram** [comment]
@ido-tera-group 

As per the build configurations from [here](https://www.tensorflow.org/install/source#gpu) it should work with this configuration. Can you please create a fresh environment and try to install from scratch and see if the issue still persists.Thanks!

**Comment by ido-tera-group** [comment]
Can you refer me to clear instructions on how to install? I see a bunch of blogs each with different ideas... 
Is there an official (or semi-offical) guide that should actually work? Thanks!

**Comment by ravikyram** [comment]
@ido-tera-group 

Please, refer the tutorial from [here](https://www.tensorflow.org/install/gpu#install_cuda_with_apt).Thanks!

**Comment by ido-tera-group** [comment]
I see, thank you! After tinkering a bit, it worked.. But I changed the instructions to work for 20.04:

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt-get update
```

Perhaps the docs should be updated?

Thanks again!

**Comment by ido-tera-group** [comment]
I celebrated too soon.. tensorflow did import without that immediate message, but when I tried building a model, I got:

```
2020-12-24 15:31:52.325975: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-24 15:31:52.326576: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-12-24 15:31:52.341852: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-24 15:31:52.342269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Super with Max-Q Design computeCapability: 7.5
coreClock: 1.23GHz coreCount: 48 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 327.88GiB/s
2020-12-24 15:31:52.342442: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-24 15:31:52.343750: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-12-24 15:31:52.343787: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2020-12-24 15:31:52.343824: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2020-12-24 15:31:52.343872: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2020-12-24 15:31:52.343906: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-12-24 15:31:52.343938: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2020-12-24 15:31:52.344019: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-12-24 15:31:52.344026: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

Any clues?

**Comment by ido-tera-group** [comment]
I ended up manually installing the missing libraries, and finally got it to work!  <whew>

... but now... for some reason conv1d isn't working:

```
2020-12-26 20:54:59.125017: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops.cc:1106 : Not found: No algorithm worked!

tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found:  No algorithm worked!
	 [[node sequential/conv1d/conv1d (defined at /egg_analysis/dl_eggs.py:191) ]]
  (1) Not found:  No algorithm worked!
	 [[node sequential/conv1d/conv1d (defined at /egg_analysis/dl_eggs.py:191) ]]
	 [[assert_greater_equal/Assert/AssertGuard/pivot_f/_3/_27]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_1582]
```

Is this due to improper installation or something else? (it worked on my CPU, and if I remove the conv1d layer, it also works)

Thanks!

**Comment by ravikyram** [comment]
@ido-tera-group 

If you follow the guidelines as mentioned in above link , you should be able to install it. Glad to know you installed.Please, close this thread if your issue was resolved. Thanks!

**Comment by thijstriemstra** [comment]
saw same error:
```
2021-01-06 17:05:11.751597: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0';
dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/Qt/5.14.1/lib
2021-01-06 17:05:11.751625: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

but it's harmless, I don't want to use a GPU.

**Comment by emadboctorx** [comment]
I'm having the same problem if I try to install python3.8 on google colab + tensorflow 2.4

**Comment by wijjj** [comment]
Still having the same issue here.

**Comment by Wanxp** [comment]
I has same problem ,and solved this problem by those step.
### First, find out where the "libcudart.so.11.0" is
If you lost other at error stack, you can replace the "libcudart.so.11.0" by your word  in below:
```shell
sudo find / -name 'libcudart.so.11.0'
```
Output in my system.This result shows  where the "libcudart.so.11.0" is in my system:
```text
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.0
```
If the result shows nothing, please make sure you have install cuda or other staff that must install in your system.
### Second, add the path to environment file.
1. edit /etc/profile
```shell
sudo vim /etc/profile
```
2. add path to profile file (the second row of below is the path that I already added before that this problem occers. you can replace by your path that your "libcudart.so.11.0" in)
```text
export LD_LIBRARY_PATH=/usr/local/cuda-11.1/targets/x86_64-linux/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/extras/CUPTI/lib64
```
3. make environment file work
```shell
source /etc/profile
```
### Last, when it all done, you can try your python code again.
Hope it help for you!

### At the end
I do every thing on guide list to install tensorflow. But still occurs the same problem
my environment:
system: ubuntu: 20.04LTS
tensorflow: 2.4.1
python3: 3.8
pip3: 21
cuda:11.1
cudnn:8.
gpu:GT860M
gpu driver:460.39

My error stack before solve this problem:
```shell
2021-01-31 15:04:10.925736: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2021-01-31 15:04:10.925774: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-01-31 15:04:11.738577: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-01-31 15:04:11.771425: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-31 15:04:11.771969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1770] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 860M computeCapability: 5.0
coreClock: 1.0195GHz coreCount: 5 deviceMemorySize: 1.96GiB deviceMemoryBandwidth: 74.65GiB/s
2021-01-31 15:04:11.772084: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2021-01-31 15:04:11.772174: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2021-01-31 15:04:11.772255: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2021-01-31 15:04:11.772333: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2021-01-31 15:04:11.772413: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2021-01-31 15:04:11.772490: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2021-01-31 15:04:11.772567: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2021-01-31 15:04:11.772745: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-01-31 15:04:11.772763: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1803] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```
After I fix it , the python code works fine

**Comment by chriscardillo** [comment]
A short quick fix that worked for me

Running Ubuntu 20.04, Python 3.8.5, cuDNN 8.1.0, on an RTX 2080 Super.

I downloaded [this run file](https://developer.nvidia.com/cuda-11.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=runfilelocal) from NVIDIA, then only opted in to install the CUDA 11 toolkit. After it finished downloading, I added `/usr/local/cuda-11.0/bin` to my PATH and `/usr/local/cuda-11.0/lib64` to my LD_LIBRARY_PATH. 

After that, my GPU was functional again.

**Comment by Yeah21** [comment]
you can try to add these code to load dynamic library

from ctypes import *
lib8 = cdll.LoadLibrary('/data/users/CHDHPC/2017902628/cuda/lib64/libcublas.so.11')
lib1 = cdll.LoadLibrary('/data/users/CHDHPC/2017902628/cuda/lib64/libcudart.so.11.0')
lib2 = cdll.LoadLibrary('/data/users/CHDHPC/2017902628/cuda/lib64/libcublasLt.so.11')
lib3 = cdll.LoadLibrary('/data/users/CHDHPC/2017902628/cuda/lib64/libcufft.so.10')
lib4 = cdll.LoadLibrary('/data/users/CHDHPC/2017902628/cuda/lib64/libcurand.so.10')
lib5 = cdll.LoadLibrary('/data/users/CHDHPC/2017902628/cuda/lib64/libcusolver.so.10')
lib6 = cdll.LoadLibrary('/data/users/CHDHPC/2017902628/cuda/lib64/libcusparse.so.11')
lib7 = cdll.LoadLibrary('/data/users/CHDHPC/2017902628/cuda/lib64/libcudnn.so.8')

**Comment by GF-Huang** [comment]
The fucking stupid bug still exist in the latest tf today.

**Comment by GF-Huang** [comment]
[I 2021-02-10 12:56:49.480 ServerApp] Kernel started: 5746087b-7f04-4517-a0a3-afc5ae7ad726
2021-02-10 12:57:07.427237: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-10 12:57:07.427347: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-02-10 12:57:40.203717: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-10 12:57:40.261141: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-10 12:57:40.261205: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-10 12:57:40.261248: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ubuntu-desktop): /proc/driver/nvidia/version does not exist
2021-02-10 12:57:40.261892: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-10 12:57:40.262545: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set

**Comment by aseedb** [comment]
I had the same problem, it was solved by installing cudatoolkit
`conda install cudatoolkit`

**Comment by GF-Huang** [comment]
> I had the same problem, it was solved by installing cudatoolkit
> `conda install cudatoolkit`

My computer no GPU, why I need cudatoolkit?

**Comment by Palang2014** [comment]
> I had the same problem, it was solved by installing cudatoolkit
> `conda install cudatoolkit`

This worked for me as well.

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/107724109-0a0cf580-6d1e-11eb-8b28-bceb4e2c3a1b.png)

**Comment by vortune** [comment]
Ubuntu 20.04 doesn't upgrade to CUDA-11.x. Please follow the instructions at the [CUDA download page](https://developer.nvidia.com/cuda-downloads) to install CUDA-11.x.

After all, don't forget joint the CUDA library path with environment of `LD_LIBRARY_PATH`.
`echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/targets/x86_64-linux/lib' >> ~/.bashrc
`

**Comment by KvitnucaZahradka** [comment]
The way I solved this problem was the following:

- My setup: Ubuntu 18.04, Tensor Flow 2.4. 
- I got missing libraries: `libcudart.so.11.0`,`libcusparse.so.11`.
- I did not want to install `conda` but rather just use `pip`.

My solution:
- Just run Ubuntu 18.04 docker, where you install `cudatoolkit` (version that has cuda 11)
- inside that docker find locations of `libcudart.so.11.0`,`libcusparse.so.11` & copy them into your main machine (or use docker - shared folder)
- once you have them in the main machine (in whatever location), add that directory path into `~/.bashrc` as mentioned in many solutions above.

**Comment by dbolser** [comment]
> I see, thank you! After tinkering a bit, it worked.. But I changed the instructions to work for 20.04:
> 
> ```
> wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
> sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
> sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
> sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
> sudo apt-get update
> ```
> 
> Perhaps the docs should be updated?
> 
> Thanks again!

Thanks for this. What package did you subsequently install?

**Comment by unnir** [comment]
this helped me: 

`conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
`

**Comment by JapinderSandhu** [comment]
> I had the same problem, it was solved by installing cudatoolkit
> `conda install cudatoolkit`

this worked for me

**Comment by StevenMapes** [comment]
> I ended up manually installing the missing libraries, and finally got it to work!
> 
> ... but now... for some reason conv1d isn't working:
> 
> ```
> 2020-12-26 20:54:59.125017: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops.cc:1106 : Not found: No algorithm worked!
> 
> tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
>   (0) Not found:  No algorithm worked!
> 	 [[node sequential/conv1d/conv1d (defined at /egg_analysis/dl_eggs.py:191) ]]
>   (1) Not found:  No algorithm worked!
> 	 [[node sequential/conv1d/conv1d (defined at /egg_analysis/dl_eggs.py:191) ]]
> 	 [[assert_greater_equal/Assert/AssertGuard/pivot_f/_3/_27]]
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_train_function_1582]
> ```
> 
> Is this due to improper installation or something else? (it worked on my CPU, and if I remove the conv1d layer, it also works)
> 
> Thanks!

Could you post the instructions of you installed to fix this please as the notes cover 16.04 and 18.04 but not 20.04 which I#m also having troubles with now

**Comment by singh-aymcommerce** [comment]
> I ended up manually installing the missing libraries, and finally got it to work!
> 
> ... but now... for some reason conv1d isn't working:
> 
> ```
> 2020-12-26 20:54:59.125017: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops.cc:1106 : Not found: No algorithm worked!
> 
> tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
>   (0) Not found:  No algorithm worked!
> 	 [[node sequential/conv1d/conv1d (defined at /egg_analysis/dl_eggs.py:191) ]]
>   (1) Not found:  No algorithm worked!
> 	 [[node sequential/conv1d/conv1d (defined at /egg_analysis/dl_eggs.py:191) ]]
> 	 [[assert_greater_equal/Assert/AssertGuard/pivot_f/_3/_27]]
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_train_function_1582]
> ```
> 
> Is this due to improper installation or something else? (it worked on my CPU, and if I remove the conv1d layer, it also works)
> 
> Thanks!

This following error is resolved. Please add following lines after the imports : 

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

**Comment by NarenZen** [comment]
Please run these command. It will solve the issue

wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
sudo apt-get update
sudo apt-get -y install cuda

**Comment by braindotai** [comment]
> this helped me:
> 
> `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch `

What the hell, it seriously worked for me! Can't believe it, what a lol sol.

**Comment by ithllc** [comment]
normally don't post but go to the following link below, do exactly as the instructions say, then reboot your linux box(server) and you should be fine.

https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_network

PS, other people wrote the correct steps but in the case that the download URL changes or etc.... I have provided the downloads link from NVIDIA

**Comment by lyh16** [comment]
I am running TensorFlow v2.4.1 and PyTorch v1.8.1 LTS with an NVIDIA RTX 3090 on a JupyterHub(The Littlest Jupyter Hub).
The suggestions that involve the "apt" command are therefore impractical in my case.
After scouring the internet(Github+Stack Overflow+etc.)  for multiple days, I've come up with a solution for JupyterHub users.
My suggested solutions are intended for JupyterHub users, but hopefully a quick look at the code might give other people an idea for different environments.

https://github.com/lyh16/jupyterhub-cudnn-installer

**Comment by buxizhizhoum** [comment]
These command works.

```
wget https://developer.download.nvidia.com/compute/cuda/11.4.0/local_installers/cuda_11.4.0_470.42.01_linux.run
sudo sh cuda_11.4.0_470.42.01_linux.run
```
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=10&target_type=runfile_local

**Comment by aafaqin** [comment]
> I had the same problem, it was solved by installing cudatoolkit
> `conda install cudatoolkit`
I directly installed 
Nvidia Driver, CUDA, CuDnn whatever newer versions from the archive i got still i got this error but after running conda install cudatoolkit everything started working properly. 
Thank you so much.

**Comment by ferroao** [comment]
This worked for me sudo apt-get install cuda-cudart-11-0

**Comment by BakaZoro** [comment]
> I had the same problem, it was solved by installing cudatoolkit
> `conda install cudatoolkit`

Thanks! This worked for me .

**Comment by dlwlgus53** [comment]
> > this helped me:
> > `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch `
> 
> What the hell, it seriously worked for me! Can't believe it, what a lol sol.

Works on me too but I don't know why

**Comment by cyriltw** [comment]
> I has same problem ,and solved this problem by those step.
> 
> ### First, find out where the "libcudart.so.11.0" is
> If you lost other at error stack, you can replace the "libcudart.so.11.0" by your word in below:
> 
> ```shell
> sudo find / -name 'libcudart.so.11.0'
> ```
> 
> Output in my system.This result shows where the "libcudart.so.11.0" is in my system:
> 
> ```
> /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.0
> ```
> 
> If the result shows nothing, please make sure you have install cuda or other staff that must install in your system.
> 
> ### Second, add the path to environment file.
> 1. edit /etc/profile
> 
> ```shell
> sudo vim /etc/profile
> ```
> 
>  2. append path to  "LD_LIBRARY_PATH" in profile file
> 
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.1/targets/x86_64-linux/lib
> ```
> 
>  3. make environment file work
> 
> ```shell
> source /etc/profile
> ```
> 
> ### Last, when it all done, you can try your python code again.
> Hope it help for you!
> 
> ### At the end
> I do every thing on guide list to install tensorflow. But still occurs the same problem my environment: ubuntu: 20.04LTS tensorflow: 2.4.1 python3: 3.8 pip3: 21 CUDA: 11.1 cuDNN: 8.1.0 GPU: GeForce GTX 860M GPU Driver: 460.39
> 
> My error stack before solve this problem:
> 
> ```shell
> 2021-01-31 15:04:10.925736: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
> 2021-01-31 15:04:10.925774: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> 2021-01-31 15:04:11.738577: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
> 2021-01-31 15:04:11.771425: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2021-01-31 15:04:11.771969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1770] Found device 0 with properties: 
> pciBusID: 0000:01:00.0 name: GeForce GTX 860M computeCapability: 5.0
> coreClock: 1.0195GHz coreCount: 5 deviceMemorySize: 1.96GiB deviceMemoryBandwidth: 74.65GiB/s
> 2021-01-31 15:04:11.772084: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
> 2021-01-31 15:04:11.772174: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
> 2021-01-31 15:04:11.772255: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
> 2021-01-31 15:04:11.772333: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
> 2021-01-31 15:04:11.772413: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
> 2021-01-31 15:04:11.772490: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
> 2021-01-31 15:04:11.772567: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
> 2021-01-31 15:04:11.772745: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
> 2021-01-31 15:04:11.772763: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1803] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
> Skipping registering GPU devices...
> ```
> 
> After I fix it , the python code works fine

Hi, in this how do you do Step #2? 

1. Do you open your virtual python environment, then do these changes to add it? 
2. Do you simply open the `etc/profile` file and add to the end?

**Comment by songssssss** [comment]
I'm facing the same problem. I installed tensorflow-gpu 2.2.0 using Anaconda and it will automatically download cudnn 7.6 and toolkit 10.1.  anyone using anaconda also faces the same problem? ( i installed tensorflow-gpu by running this line `conda create -n tf-gpu tensorflow-gpu==2.2.0 python==3.8`)

**Comment by Slyderek** [comment]
> 

Thanks a lot. This hugely helps. God bless you!

**Comment by imatiach-msft** [comment]
I'm seeing this warning but with just tensorflow installed, not tensorflow-gpu.  I just want to suppress this warning for my library users.  What is the recommended way to suppress this warning for the regular tensorflow package?

**Comment by imatiach-msft** [comment]
Oh, I guess those two packages are now combined into one:
https://www.tensorflow.org/install
![image](https://user-images.githubusercontent.com/24683184/148239161-8fb1dbb6-5da2-47e9-b41e-823fcdc310b1.png)

it's really annoying to users to show this warning though if they actually don't want to use the GPU

**Comment by nguyenviettuan96** [comment]
conda install cudatoolkit=11.3 -c pytorch -c conda-forge
This worked for me

**Comment by Kamlesh364** [comment]
System information

OS Platform and Distribution : Linux Ubuntu 20.04
TensorFlow version: 2.5.0
Python version: 3.8.10
NVIDIA Driver Version: 470.86
GPU model: GeForce RTX 3060

**ERROR**

2022-01-20 20:10:02.523095: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/cuda/include:/usr/lib/cuda/lib64:/opt/ros/noetic/lib:/usr/lib/cuda/include:/usr/lib/cuda/lib64::/usr/local/cuda/targets/x86_64-linux/lib
2022-01-20 20:10:02.523121: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Please help me to solve this issue**

**Comment by JanPokorny** [comment]
For anyone having this issue (ping @Kamlesh364), I strongly recommend checking out Docker and using the official images: https://hub.docker.com/r/tensorflow/tensorflow/. It's a new technology to learn, but then saves a lot of time when solving these dependency-hell problems, since the Docker image has all the dependencies (including CUDA) pre-installed. Docker also integrates nicely with VSCode (check out devcontainers).

You just need to install a CUDA-capable driver and enable GPU passthrough to Docker: [Linux tutorial](https://towardsdatascience.com/how-to-properly-use-the-gpu-within-a-docker-container-4c699c78c6d1), [Windows tutorial](https://stackoverflow.com/a/66437683/6099426).

**Comment by shaynemei** [comment]
@Kamlesh364 What is the output of `nvcc --version`?

**Comment by Kamlesh364** [comment]
I've resolved the issue by performing following-
1. Removed currently installed cuda and tensorflow versions.
2. Installed cuda-toolkit using the command `sudo apt install nvidia-cuda-toolkit`
3. upgraded to NVIDIA Driver Version: 510.54
4. Installed Tensorflow==2.7.0

and everything is just amazing now:)
thanks for the help.

**Comment by shaynemei** [comment]
Good to know!
Another solution that worked for me is to find the correct version of Tensorflow that matches my OS, CUDA version, and python version here: https://www.tensorflow.org/install/source#gpu

**Comment by Kamlesh364** [comment]
> Good to know! Another solution that worked for me is to find the correct version of Tensorflow that matches my OS, CUDA version, and python version here: https://www.tensorflow.org/install/source#gpu, and just `pip install` that version of tensorflow.

ya, this is the most applicable solution for this issue.

**Comment by MihirUpasani** [comment]
> normally don't post but go to the following link below, do exactly as the instructions say, then reboot your linux box(server) and you should be fine.
> 
> https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_network
> 
> PS, other people wrote the correct steps but in the case that the download URL changes or etc.... I have provided the downloads link from NVIDIA

This seemed to work for me. Thank you @ithllc! You've saved my assignment! :)

**Comment by HelloWorldLTY** [comment]
I believe the document should be updated soon, because cudatool=11.2 cannot work

**Comment by zzj0402** [comment]
https://anaconda.org/nvidia/cuda-toolkit

**Comment by mohantym** [comment]
Hi @ido-tera-group !
Current documentation is updated  and suggests to install cudatoolkits through Conda instead of downloading and setting path manually .

Could you create a new environment and test with [new instruction ](https://www.tensorflow.org/install/pip#:~:text=of%20the%20installation.-,4.%20GPU%20setup,-You%20can%20skip)
and give us an update.

Re-opening until it is considered as resolved from your side.

Thank you!

**Comment by dafogongdu** [comment]
HI.. still having a same issue..

**Comment by mohantym** [comment]
@dafogongdu !

Could you create a new issue with details as re-opening this will be a duplicate to effort to this issue.
We can not replicate the exact behaviour from our side with new instructions from website.

Thank you!

**Comment by vamshi8134** [comment]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/usr/lib/python3.8/pdb.py", line 1705, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/usr/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/content/drive/MyDrive/OpenPSG/tools/train.py", line 2, in <module>
    import argparse
  File "/usr/local/lib/python3.8/dist-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/usr/local/lib/python3.8/dist-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/usr/local/lib/python3.8/dist-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.8/dist-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
Uncaught exception. Entering post mortem debugging

**Comment by marthasimons87** [comment]
I hope this bug is fixed!! [👀](https://writemyessay.ca/)
File "/usr/local/lib/python3.8/dist-packages/mmdet/apis/init.py", line 2, in
from .inference import (async_inference_detector, inference_detector,
File "/usr/local/lib/python3.8/dist-packages/mmdet/apis/inference.py", line 7, in
from mmcv.ops import RoIPool

**Comment by celikmustafa89** [comment]
ONE BUG TO RULE THEM ALL 

still exists, unbelievable.

**Comment by flydragon2018** [comment]
“locate" the XXX file first,
then add it to PATH  and/or  LD_LIBRARY_PATH, depending on what kind of file It is.

I have similar problem,  due to too many virtual envs and messed up.

**Comment by dsanmiguel** [comment]
What solved the problems for me with cuda12.2 on Ubuntu 22.04 LTS was setting below PATHs according to Nvidia Installation instructions (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions) in my ~/.bashrc file:

export PATH=/usr/local/cuda-12.2/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

The fix is then running the following commands: 

sudo cp /usr/local/cuda-12.2/lib64/libcudart.so.12 /usr/local/cuda-12.2/lib64/libcudart.so.11.0
sudo cp /usr/lib/x86_64-linux-gnu/libnvinfer.so.8.6.1 /usr/local/cuda-12.2/lib64/libnvinfer.so.7
sudo cp /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so.8.6.1 /usr/local/cuda-12.2/lib64/libnvinfer_plugin.so.7


Your file names and locations will vary so please adjust accordingly. As someone suggested above use command below to locate above file locations (if they exist): 
 
sudo find / -name 'whateverfileyouwant'

It seems recent TensorFlow versions have not updated the names, versions, and locations of these files for more recent CUDA versions so we are just copying the new files to the old location and renaming them to their old names while keeping the recent versions with their original names in their original locations.

**Comment by jonathanmarvens** [comment]
> ## What solved the problems for me with cuda12.2 on Ubuntu 22.04 LTS was setting below PATHs according to Nvidia CUDA Installation instructions
> 
> Source: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions
> ## To do this I added the below lines to my ~/.bashrc file
> 
> ```
> export PATH=/usr/local/cuda-12.2/bin${PATH:+:${PATH}}
> export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
> ```
> 
> ## The fix is then running the following commands:
> 
> ```
> sudo cp /usr/local/cuda-12.2/lib64/libcudart.so.12 /usr/local/cuda-12.2/lib64/libcudart.so.11.0
> sudo cp /usr/lib/x86_64-linux-gnu/libnvinfer.so.8.6.1 /usr/local/cuda-12.2/lib64/libnvinfer.so.7
> sudo cp /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so.8.6.1 /usr/local/cuda-12.2/lib64/libnvinfer_plugin.so.7
> sudo cp /usr/local/cuda-12.2/lib64/libcublas.so.12 /usr/local/cuda-12.2/lib64/libcublas.so.11
> sudo cp /usr/local/cuda-12.2/lib64/libcublasLt.so.12 /usr/local/cuda-12.2/lib64/libcublasLt.so.11
> sudo cp /usr/local/cuda-12.2/lib64/libcufft.so.11 /usr/local/cuda-12.2/lib64/libcufft.so.10
> sudo cp /usr/local/cuda-12.2/targets/x86_64-linux/lib/libcusparse.so.12 /usr/local/cuda-12.2/lib64/libcusparse.so.11
> ```
> 
> Your file names and locations will vary so please adjust accordingly. As someone suggested above use command below to locate above file locations (if they exist):
> 
> ```
> sudo find / -name 'whateverfileyouwant'
> ```
> 
> # It seems recent TensorFlow versions have not updated the names, versions, and locations of these files for more recent CUDA versions so we are just copying the new files to the old location and renaming them to their old names while keeping the recent versions with their original names in their original locations.

Please **DON'T** do this; masking CUDA Toolkit versions like this can and will break some CUDA-dependent code, and it'll be a pain to figure out what's gone wrong. Instead, just install the CUDA Toolkit 11 libraries alongside the CUDA Toolkit 12 ones. It works just fine. _E.g._, in **Ubuntu**, [_after setting up the NVIDIA CUDA APT repository_](https://docs.nvidia.com/cuda/cuda-installation-guide-linux#ubuntu), you'd run something like `sudo apt install cuda cuda-11-8 cuda-toolkit cuda-toolkit-11-8 libcudnn8-dev`.

**Comment by dsanmiguel** [comment]
Haven't had any problems yet and have used this setup extensively. If I encounter any problems, I will let you know. Even if I do, the fix doesn't seem like a pain at all since it is just removing the handful of copies I made.

**Comment by awawwaa** [comment]
Now it's 12/14/2024, the stupid bug still exists, unbelievable
