### ISSUE TITLE
Tensorflow 2.4  CUDA 11   CUDA_ERROR_LAUNCH_FAILED

### ISSUE THREAD

**Issue by Migateak** [tensorflow/tensorflow#45987]
------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Win10  -2004
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**:  2.4
-   **Python version**: 3.6.1
-   **CUDA/cuDNN version**: CUDA 11.0 -  cudNN 8.0.4
-   **GPU model and memory**: GTX 1660 Super 6GB (+ GT 730 2GB) with 456.55 driver.
-   **Exact command to reproduce**: py -3.6 generate.py

### Describe the problem
Hello, I have had a problem with tensorflow and cuda for days ... the program works with the CPU but I would like to use the latter with my GPU. However, the program refuses to end. the program starts but as soon as it arrives at 5/54 or 6/54 it crashes with the message bellow.
I tried to change the version of cuda + cudnn, change the driver version of my gpu but nothing works, I still find this error.
The program is [here](https://github.com/Migateak/tensorflowtextgen) with data, it's not mine but it's for a generation of auto text.

### Source code / logs

> Epoch 1/50
>  5/54 [=>............................] - ETA: 18s - loss: 4.20602020-12-27 12:11:08.578867: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: 
> unspecified launch failure
> 2020-12-27 12:11:08.578954: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_EXECUTION_FAILED
> in tensorflow/stream_executor/cuda/cuda_dnn.cc(1972): 'cudnnRNNBackwardData( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, output_desc.handles(), output_data.opaque(), output_desc.handles(), output_backprop_data.opaque(), output_h_desc.handle(), output_h_backprop_data.opaque(), output_c_desc.handle(), output_c_backprop_data.opaque(), rnn_desc.params_handle(), params.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), input_desc.handles(), input_backprop_data->opaque(), input_h_desc.handle(), input_h_backprop_data->opaque(), input_c_desc.handle(), input_c_backprop_data->opaque(), workspace.opaque(), workspace.size(), reserve_space_data->opaque(), reserve_space_data->size())'
> 2020-12-27 12:11:08.579262: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:220] Unexpected Event status: 1
> 2020-12-27 12:11:08.579796: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at cudnn_rnn_ops.cc:1926 : Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 1024, 1024, 1, 200, 64, 1024]
>

**Comment by ahtik** [comment]
@Migateak Did you also try with cudnn-8.0.5.39 together with CUDA 11.0? GPU drivers can be the latest, mine are 460.89.

`generate.py` finished with all 50 epochs under my Windows 10, CUDA 11.0, TF2.4 pypi wheel, CUDNN cudnn-8.0.5.39, python 3.6.8,  i7-9700K, RTX 2070S, venv created with pip -m venv.

What's your full output from this?
`python -c "import tensorflow as tf;print(tf.config.list_physical_devices('GPU'))"`
Are you setting the GPU used by tensorflow manually? I'd presume only the 1660 is used? GTX1660S has the same compute capability as mine (7.5), so there shouldn't be much specific why the GPU shouldn't work, out of memory would give OOM throwable.

```
Epoch 1/50
54/54 [==============================] - 15s 224ms/step - loss: 3.6513 - val_loss: 3.7777
Epoch 2/50
54/54 [==============================] - 14s 245ms/step - loss: 3.0833 - val_loss: 2.5486
........
Epoch 49/50
54/54 [==============================] - 25s 436ms/step - loss: 0.4176 - val_loss: 2.3835
Epoch 50/50
54/54 [==============================] - 29s 511ms/step - loss: 0.4064 - val_loss: 2.4149
```
![image](https://user-images.githubusercontent.com/140952/103170900-37721280-4848-11eb-9ea4-032c46370dc1.png)

**Comment by Migateak** [comment]
@ahtik thank you for your answer, I try that and I edit as soon as it's done: D

**Comment by jihankim** [comment]
Hi. I also have the same error so frequently. It sometimes gives such error message, or just hangs.

It looks it is related with using RNNs. After update the tensorflow to the latest 2.4.0, using Conv or Dense layers were perfectly fine. Regardless of using Bidirectional, RNN seems causing this problem, randomly.

I tried CUDA 10.1 + cuDNN 7.6.5, but it didn't solve the problem.

Using CPU only works totally fine, so I don't think it is related with the network layer design or data.


My settings are:
Have I written custom code (as opposed to using a stock example script
provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10 enterprise 1809
TensorFlow installed from (source or binary): pip install tensorflow
TensorFlow version (use command below): 2.4
Python version: 3.8.6
CUDA/cuDNN version: CUDA 11.0 - cudNN 8.0.5.39
GPU model and memory: Quadro P2000 5GB with 460.89 driver.

This is my output of the command:
> python -c "import tensorflow as tf;print(tf.config.list_physical_devices('GPU'))"
2020-12-27 08:45:02.471099: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-27 08:45:05.003397: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-27 08:45:05.017145: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-12-27 08:45:05.063024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:21:00.0 name: Quadro P2000 computeCapability: 6.1
coreClock: 1.4805GHz coreCount: 8 deviceMemorySize: 5.00GiB deviceMemoryBandwidth: 130.53GiB/s
2020-12-27 08:45:05.088476: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-12-27 08:45:05.106946: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-27 08:45:05.113806: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-27 08:45:05.123704: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-12-27 08:45:05.130466: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-12-27 08:45:05.143146: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-12-27 08:45:05.152674: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-12-27 08:45:05.158809: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-27 08:45:05.166689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

**Comment by Migateak** [comment]
@jihankim have you found a solution?

**Comment by jihankim** [comment]
@Migateak No. But just forcing using CPU works fine. I think this problem is related with the GPU implementation.

**Comment by Migateak** [comment]
@jihankim what is your CPU ?

**Comment by jihankim** [comment]
> @jihankim what is your CPU ?

my CPU is Intel Xeon Silver 4116

**Comment by ahtik** [comment]
@jihankim Can you provide a minimal complete code with the dataset that is 
crashing, so one could try to reproduce?

**Comment by amahendrakar** [comment]
@Migateak,
I did not face any errors while running the code, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/01c8df7cded1430e7cbcf29485ec495a/45987.ipynb).

Please try limiting the GPU memory growth as shown in [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and check if you are facing the same issue. Thanks!

**Comment by amahendrakar** [comment]
> is there a way to choose which GPU to use? to force TF used the 1660S?

To select a particular GPU, please go through the [manual device placement](https://www.tensorflow.org/guide/gpu#manual_device_placement) section of the guide. Thanks!

**Comment by ion-elgreco** [comment]
This stuff is in no way reproducible on a machine which does not have this error, so I don't get why code is asked. It's clearly a strange incompatibility of some drivers or hardware.

**Comment by jihankim** [comment]
I tried my code on Colab, and it worked fine with gpu. I think there is some compatibility issues related with gpu model or cuda version or cudnn version or nvidia driver... It is going to be really tricky to find out which combination makes such issues..

**Comment by Migateak** [comment]
@amahendrakar by adding the code [here ](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) to my program a new error appears (nice !)
Btw, if I add this:

> import os
> os.environ["CUDA_VISIBLE_DEVICES"] = "0"
> import tensorflow as tf
> config = tf.compat.v1.ConfigProto()
> config.gpu_options.allow_growth=True
> session = tf.compat.v1.Session(config=config)

which also limits the GPU (same output as the code above if I run it alone), It still does not work !
always the same error as the first post..

@ion-elgreco concerning dead VRAM, what is it concretely?
The problem is that when launching the program, during the first "batches", my card responds normally: CUDA processor at 100%, increase in graphics memory ... in short in my opinion the problem is software but I do not know not how to test each element and see which one does not work with which given that I have the same software configuration as you ....

and how to do that? (the PS)

**Comment by jihankim** [comment]
I downgraded my system to TF2.3, CUDA 10.1, and CUDNN 7.6.5. And the same code is working fine with GPU so far....
In summary, I tried
TF2.4    CUDA11.1    CUDNN 8.0.5
TF2.4    CUDA10.2    CUDNN 8.0.5
TF2.4    CUDA10.1    CUDNN 7.6.5
TF2.3    CUDA10.1    CUDNN 7.6.5 <= only this combination seems working fine so far...

**Comment by ion-elgreco** [comment]
> I downgraded my system to TF2.3, CUDA 10.1, and CUDNN 7.6.5. And the same code is working fine with GPU so far....
> In summary, I tried
> TF2.4 CUDA11.1 CUDNN 8.0.5
> TF2.4 CUDA10.2 CUDNN 8.0.5
> TF2.4 CUDA10.1 CUDNN 7.6.5
> TF2.3 CUDA10.1 CUDNN 7.6.5 <= only this combination seems working fine so far...

You may want to try Nvidia developer driver 465.21: https://developer.nvidia.com/cuda/wsl/download

This has fixed the cuda error issues for me.

**Comment by Migateak** [comment]
No way, thanks you !!
TF2.3 CUDA10.1 CUDNN 7.6.5 with Nvidia 460.89 work perfectly

**Comment by Migateak** [comment]
I was going to say omg this works! with TF 2.3, CUDA 10.1 and cudNN 7.6.5 but in fact no ... the first 5 epochs, perfect, no problem and ... the return of the error :

> Epoch 5/50
>  2/54 [>.............................] - ETA: 7s - loss: 2.01372020-12-30 14:38:33.944420: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
> 2020-12-30 14:38:33.944495: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_EXECUTION_FAILED in tensorflow/stream_executor/cuda/cuda_dnn.cc(2011): 'cudnnRNNBackwardData

I will try with the developer driver and edit this message

**Comment by ion-elgreco** [comment]
> I was going to say omg this works! with TF 2.3, CUDA 10.1 and cudNN 7.6.5 but in fact no ... the first 5 epochs, perfect, no problem and ... the return of the error :
> 
> > Epoch 5/50
> > 2/54 [>.............................] - ETA: 7s - loss: 2.01372020-12-30 14:38:33.944420: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
> > 2020-12-30 14:38:33.944495: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_EXECUTION_FAILED in tensorflow/stream_executor/cuda/cuda_dnn.cc(2011): 'cudnnRNNBackwardData
> 
> I will try with the developer driver and edit this message
> 
> **EDIT**
> Victory! finally, it works! with the dev driver 465.21 (thanks a lot @ion-elgreco )

Good to see that it works! Seems that developer driver is far more stable.

**Comment by ahtik** [comment]
> TF2.3 CUDA10.1 CUDNN 7.6.5 <= only this combination seems working fine so far...

@ion-elgreco Wonderful, great to hear it works! Would you mind sharing how you got this combination working with an RTX 3080?

I've been holding off the upgrade thinking the RTX 3xxx line requires CUDA11.1 -> build TF from source using unsupported CUDA version or doing some tweaks with the CUDA libs to trick the TF installation?

Apologies if asking the code and dataset didn't seem useful :-) It was my attempt to get the deeper understanding how cuDNN might be broken with the latest line of RTX. CuDNN doesn't seem to be super stable yet with the RTX 30 series.

If in trouble, sometimes easier to just remove the cuDNN from CUDA installation and try again. Nice to know the latest dev driver and Windows preview combination works. There are some known issues like https://github.com/pytorch/pytorch/issues/49592, hope it goes smooth and not affecting your model.

**Comment by ion-elgreco** [comment]
> > TF2.3 CUDA10.1 CUDNN 7.6.5 <= only this combination seems working fine so far...
> 
> @ion-elgreco Wonderful, great to hear it works! Would you mind sharing how you got this combination working with an RTX 3080?
> 
> I've been holding off the upgrade thinking the RTX 3xxx line requires CUDA11.1 -> build TF from source using unsupported CUDA version or doing some tweaks with the CUDA libs to trick the TF installation?
> 
> Apologies if asking the code and dataset didn't seem useful :-) It was my attempt to get the deeper understanding how cuDNN might be broken with the latest line of RTX. CuDNN doesn't seem to be super stable yet with the RTX 30 series.
> 
> If in trouble, sometimes easier to just remove the cuDNN from CUDA installation and try again. Nice to know the latest dev driver and Windows preview combination works. There are some known issues like [pytorch/pytorch#49592](https://github.com/pytorch/pytorch/issues/49592), hope it goes smooth and not affecting your model.

I think you may have tagged the wrong person. TF2.3 does not work for me, at least it works after a 20min slow startup of TensorFlow. But that is not practical.

I have conda with all my packages, installed tensorflow 2.4 with pip inside my conda env. Then I have Cuda 11.0 update 1 installed and cudnn 8.0.4 with the developer driver 465.12. This developer driver was key for my current setup with a ryzen cpu and rtx 3080. I don't know why, but cudnn and cuda is stable now. 

I am not on an insider build of windows. I am running **Windows 10 Pro, Version 20H2, OS build 19042.685**

We need TensorFlow builds with cuda 11.1, because that's where the official support starts for RTX 30 series cards https://github.com/tensorflow/tensorflow/issues/46093.

**Comment by Migateak** [comment]
> 
> 
> > TF2.3 CUDA10.1 CUDNN 7.6.5 <= only this combination seems working fine so far...
> 
> @ion-elgreco Wonderful, great to hear it works! Would you mind sharing how you got this combination working with an RTX 3080?
> 
> I've been holding off the upgrade thinking the RTX 3xxx line requires CUDA11.1 -> build TF from source using unsupported CUDA version or doing some tweaks with the CUDA libs to trick the TF installation?
> 
> Apologies if asking the code and dataset didn't seem useful :-) It was my attempt to get the deeper understanding how cuDNN might be broken with the latest line of RTX. CuDNN doesn't seem to be super stable yet with the RTX 30 series.
> 
> If in trouble, sometimes easier to just remove the cuDNN from CUDA installation and try again. Nice to know the latest dev driver and Windows preview combination works. There are some known issues like [pytorch/pytorch#49592](https://github.com/pytorch/pytorch/issues/49592), hope it goes smooth and not affecting your model.

Hey, Did you try with CUDA 11.1 and the dev driver 465.21 ?
given that for the moment everything is working I don't want to break everything xD
Have you tried it and if so, everything works? I would like to know before I break everything

**Comment by ighgusp** [comment]
I have had the same problem and I don't think it is a driver issue but I have found a solution that is logical and works.
 
Windows has a service called TDR (Timeout Detection and Recovery) which pings the GPU to check it hasn't frozen. If it does not get a reply within 2 seconds it resets the GPU causing the CUDA operation to fail. The point of failure can be a bit random depending on the operation that was conducted at the time of the reset. 

To fix this problem start the Nvidia Nsight Monitor in admin mode (start it by right-clicking and chose run as Administrator). Then right click the task bar icon and select options. Now locate the TDR section and either disable the TDR or increase the timeout period. I increased the timeout period to 20 seconds which appears to be enough for my ML tasks.

It is likely that the downgrade in drivers works because they doesn’t utilize the GPU as effectively as the newer driver why there is enough power left for the ping service to get its response back in time. This should however be a pretty pore reason not to upgrade drivers as it probably means slower processing of you task at hand. 

In addition to this there was also a driver issue which appeared after the TDR fix which is similar to the one above but less random in its behavior, happened at the same place in the cudnn code every time and appears to be LSTM specific (I don't remember the exact error message). By upgrading to the latest driver version 461.40 That also disappeared and now everything works flawlessly.

**Comment by ion-elgreco** [comment]
> I have had the same problem and I don't think it is a driver issue but I have found a solution that is logical and works.
> 
> Windows has a service called TDR (Timeout Detection and Recovery) which pings the GPU to check it hasn't frozen. If it does not get a reply within 2 seconds it resets the GPU causing the CUDA operation to fail. The point of failure can be a bit random depending on the operation that was conducted at the time of the reset.
> 
> To fix this problem start the Nvidia Nsight Monitor in admin mode (start it by right-clicking and chose run as Administrator). Then right click the task bar icon and select options. Now locate the TDR section and either disable the TDR or increase the timeout period. I increased the timeout period to 20 seconds which appears to be enough for my ML tasks.
> 
> It is likely that the downgrade in drivers works because they doesn’t utilize the GPU as effectively as the newer driver why there is enough power left for the ping service to get its response back in time. This should however be a pretty pore reason not to upgrade drivers as it probably means slower processing of you task at hand.
> 
> In addition to this there was also a driver issue which appeared after the TDR fix which is similar to the one above but less random in its behavior, happened at the same place in the cudnn code every time and appears to be LSTM specific (I don't remember the exact error message). By upgrading to the latest driver version 461.40 That also disappeared and now everything works flawlessly.

Since 461.09 it was fixed. Good to see new driver versions are still working and not breaking it again.
