### ISSUE TITLE
Tensorflow 2.4 not showing available GPU even after successful cuda and cudnn installation

### ISSUE THREAD

**Issue by patilaum** [tensorflow/tensorflow#46233]
OS - ubuntu 20.04
python -3..8.5
GPU - RTX 2060
Cudnn - v7.6.5

Output of `tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)`:
`WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2021-01-07 00:08:12.313080: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-07 00:08:12.315365: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-01-07 00:08:12.403099: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2021-01-07 00:08:12.403164: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: aum-GF65-Thin-9SEXR
2021-01-07 00:08:12.403176: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: aum-GF65-Thin-9SEXR
2021-01-07 00:08:12.403275: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 450.80.2
2021-01-07 00:08:12.403328: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 450.80.2
2021-01-07 00:08:12.403345: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 450.80.2
False
`
OUTPUT of `dpkg -l | grep cuda-toolkit`

`ii  cuda-toolkit-11-0                               11.0.2-1                              amd64        CUDA Toolkit 11.0 meta-package
ii  nvidia-cuda-toolkit                             10.1.243-3                            amd64        NVIDIA CUDA development toolkit
`

OUTPUT of `nvidia-smi` 
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8     6W /  N/A |    306MiB /  5934MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       920      G   /usr/lib/xorg/Xorg                 45MiB |
|    0   N/A  N/A      1469      G   /usr/lib/xorg/Xorg                106MiB |
|    0   N/A  N/A      1647      G   /usr/bin/gnome-shell              125MiB |
|    0   N/A  N/A      2647      G   /usr/lib/firefox/firefox            3MiB |
|    0   N/A  N/A      2690      G   /usr/lib/firefox/firefox            3MiB |
|    0   N/A  N/A      2723      G   /usr/lib/firefox/firefox            3MiB |
|    0   N/A  N/A      3681      G   /usr/lib/firefox/firefox            3MiB `

After succesful installation of CUDA 11, nvidia-cuda-toolkit 10.1 and tensorflow 2.4 (also tried tensorflow-gpu 2.2.0 but same error) I am still getting NO GPUs FOUND.

PLEASE HELP!!

**Comment by Saduf2019** [comment]
@patilaum 
Could you check this issue which is similar to your [issue](https://github.com/tensorflow/tensorflow/issues/19266#issuecomment-399686258). If those solutions doesn't work, could you uninstall and reinstall CUDA and cuDNN? Please let us know how it progresses. Also, try to uninstall and reinstall tensorflow-gpu and try following the instructions from [TensorFlow](https://www.tensorflow.org/install/source) website.
also refer to [link](https://stackoverflow.com/questions/59499764/tensorflow-not-tensorflow-gpu-failed-call-to-cuinit-unknown-error-303]), [link1](https://victorwyee.com/engineering/failed-call-to-cuinit-cuda-error-unknown/)Thanks!

**Comment by patilaum** [comment]
@Saduf2019  Uninstalled and installed cuda and cudnn many times now. Have tried all the steps given in those links that you shared but ended up broken packages of NVIDIA. Now I have reinstalled the OS on my system. Could you tell me the precise steps to install tensorflow 2.2.0 and above on ubuntu 20.04 with python 3.8.5?

**Comment by patilaum** [comment]
Solved!
Here's what I did:
1. installed [cuda toolkit ](https://developer.nvidia.com/cuda-11.0-download-archive) 11.0- important thing here is I did not install 10.1 as I think it creates a conflict with already installed cuda 11.0 shown in nvidia smi
2. reboot after `sudo apt-get install nvidia-modprobe` is must
3. disabled SECURE BOOT - most important
@Saduf2019  Thanks a lot

**Comment by Saduf2019** [comment]
@patilaum
Glad to hear the issue is resolved, than you for the update.
