### ISSUE TITLE
Unexpected Events CUDA_ERROR_ILLEGAL_ADDRESS and CUDA_ERROR_LAUNCH_FAILED

### ISSUE THREAD

**Issue by Urkchar** [tensorflow/tensorflow#46247]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: I have followed this tutorial using my own data. Tutorial: https://stackabuse.com/text-generation-with-python-and-tensorflow-keras/
My data: https://gist.github.com/Urkchar/e01a667c1656e874f918ff92db5b998f
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Microsoft Windows 10 Home version 10.0.19041 Build 19041
-   **TensorFlow installed from (source or binary)**: I installed TensorFlow with `pip install tensorflow`
-   **TensorFlow version**: 2.4.0
-   **Python version**: 3.8.6
-   **CUDA/cuDNN version**: CUDA version 11.2. cuDNN version 8.0.5
-   **GPU model and memory**: Nvidia GTX 1070 with 8 GB memory
-   **Exact command to reproduce**:
`model.fit(x, y, epochs=8, batch_size=256, callbacks=desired_callbacks)`

I receive unexpected errors when trying to fit a model. Examples include `CUDA_ERROR_ILLEGAL_ADDRESS` and `CUDA_ERROR_LAUNCH_FAILED`. Full logs and error messages below. 
Stuff like `F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1` Makes me think that this is a bug because these are unexpected errors or failures. 
```py
import sys
import numpy
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
from keras.utils import np_utils
from keras.callbacks import ModelCheckpoint

print(sys.version_info)


def tokenize_words(text_input):
    # Lowercase everything to standardize it
    text_input = text_input.lower()

    # Instantiate the tokenizer
    tokenizer = RegexpTokenizer(r"\w+")
    tokens = tokenizer.tokenize(text_input)

    # If the create token isn't in the stop words, make it part of "filtered"
    filtered = filter(lambda token: token not in stopwords.words("english"), tokens)
    return " ".join(filtered)


input_file = open("yejibro_data.txt").read()
# input_file = open("84-0.txt", "r", encoding="utf-8").read()

# Preprocces the input data, make tokens
processed_inputs = tokenize_words(input_file)

chars = sorted(set(processed_inputs))
char_to_num = dict((c, i) for i, c in enumerate(chars))

input_len = len(processed_inputs)
vocab_len = len(chars)
print(f"Total number of characters: {input_len}")
print(f"Total vocab: {vocab_len}")

seq_length = 100
x_data = []
y_data = []

# Loop through inputs, start at the beginning and go until we hit the final character we can create
# a sequence out of
for i in range(0, input_len - seq_length, 1):
    # Define input and output sequences
    # Input is the current character plus desired sequence length
    in_seq = processed_inputs[i:i + seq_length]

    # Out sequence is the initial character plus total sequence length
    out_seq = processed_inputs[i + seq_length]

    # We now convert list of characters to integers based on previous mappings and add the values to
    # our lists
    x_data.append([char_to_num[char] for char in in_seq])
    y_data.append(char_to_num[out_seq])

n_patterns = len(x_data)
print(f"Total patterns: {n_patterns}")

x = numpy.reshape(x_data, (n_patterns, seq_length, 1))
x = x/float(vocab_len)

y = np_utils.to_categorical(y_data)

model = Sequential()
model.add(LSTM(256, input_shape=(x.shape[1], x.shape[2]), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(256, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(128))
model.add(Dropout(0.2))
model.add(Dense(y.shape[1], activation="softmax"))

model.compile(loss="categorical_crossentropy", optimizer="adam")

# print(model.summary())

filepath = "model_weights_saved.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor="loss", verbose=1, save_best_only=True, mode="min")
desired_callbacks = [checkpoint]

model.fit(x, y, epochs=8, batch_size=256, callbacks=desired_callbacks)
```
Here are some error messages and logs that occurred at seemingly random points during the code. 
https://paste.pythondiscord.com/yomuzokuto.apache
https://paste.pythondiscord.com/orusujidaq.yaml
https://paste.pythondiscord.com/igexetayen.swift
https://paste.pythondiscord.com/ovawipegap.yaml
https://paste.pythondiscord.com/yopitiweri.less

Final note: I would be very happy to include more information when needed. I may have neglected to include some information that is necessary to figure out what's going on so please let me know. 
Final final note: This is my first bug report on GitHub so I tired to follow the template to the best of my ability.

**Comment by Saduf2019** [comment]
@Urkchar 
Can you please refer to this [issue](https://stackoverflow.com/questions/46241403/tensorflow-throw-cuda-error-launch-failed-after-a-long-run) and let us know if it helps.
please ensure you are using the [following](
https://www.tensorflow.org/install/source#gpu) configs.

**Comment by ymodak** [comment]
@Urkchar Please roll back to cuda 11.0 (currently you are on 11.2) for TF 2.4

**Comment by Urkchar** [comment]
> @Urkchar
> Can you please refer to this [issue](https://stackoverflow.com/questions/46241403/tensorflow-throw-cuda-error-launch-failed-after-a-long-run) and let us know if it helps.
> please ensure you are using the [following](https://www.tensorflow.org/install/source#gpu) configs.

I will be happy to try out one of those configs. 
How can I check which build tools and which compiler I am using? I didn't install these manually so perhaps they came with something else?

**Comment by Urkchar** [comment]
> @Urkchar Please roll back to cuda 11.0 (currently you are on 11.2) for TF 2.4

I will try this. Thank you. So TensorFlow currently doesn't support CUDA 11.2?

**Comment by Urkchar** [comment]
> @Urkchar Please roll back to cuda 11.0 (currently you are on 11.2) for TF 2.4

Should I get the update or the base version of 11.0? Does it matter?
![image](https://user-images.githubusercontent.com/49205496/103973105-43a57c00-5134-11eb-93aa-80bda562727f.png)

**Comment by Urkchar** [comment]
I changed from CUDA 11.2 to CUDA 11.0 (base) and was training fine up until epoch 8. It crashed with `CUDNN_STATUS_INTERNAL_ERROR` and `CUDA_ERROR_LAUNCH_FAILED`. Full output: https://paste.pythondiscord.com/egadilaqex.yaml
I was monitoring the temperature of my GPU like was suggested in https://stackoverflow.com/questions/46241403/tensorflow-throw-cuda-error-launch-failed-after-a-long-run however there were no values out of the ordinary.

**Comment by Urkchar** [comment]
Now I'm getting this error `CUDA_ERROR_ILLEGAL_ADDRESS`. Full output: https://paste.pythondiscord.com/yusegemuga.apache
It appears to happen at random points during `model.fit(...)`. I ran the same exact code again and I got this error https://paste.pythondiscord.com/olovaguvun.apache
I ran the exact same code a third time and got this error: https://paste.pythondiscord.com/elufotohog.apache
Fourth time gave this different error: https://paste.pythondiscord.com/damicanuli.sql
Running a fifth tame gave what appears to be the same error as Run 3 of this post however there was also the number `20` as the last line of output. Full output: https://paste.pythondiscord.com/ladifezepu.apache
If you need more examples of what's going on, I'd be happy to run this code some more.

**Comment by Saduf2019** [comment]
@Urkchar 
Can you please refer to these solved issues for the error reported above and let us know.
[link](https://www.mathworks.com/matlabcentral/answers/303228-cuda_error_illegal_address), [link1](https://github.com/tensorflow/tensorflow/issues/6509)

**Comment by Urkchar** [comment]
I tried the fix in the first link, setting the environment variables and I still get the error. Full output: https://paste.pythondiscord.com/ujexuzaqih.apache
I'm unsure what I'm supposed to try for link1. From what I can tell, the fix was temporarily disabling some "kernels". This however was merged into the full release I think so I believe that I already have this fix. https://github.com/tensorflow/tensorflow/pull/6822
If I'm missing something from either of the links, please let me know.

**Comment by sanjoy** [comment]
Are you able to run the program under [CUDA memcheck](https://docs.nvidia.com/cuda/cuda-memcheck/index.html)?  If yes, can you please attach the logs?  That could give us a strong hint on what's going on.

Please also attach `"yejibro_data.txt"`, with it I will be able to check if it reproduces on my end.

**Comment by Urkchar** [comment]
> Are you able to run the program under [CUDA memcheck](https://docs.nvidia.com/cuda/cuda-memcheck/index.html)? If yes, can you please attach the logs? That could give us a strong hint on what's going on.
> 
> Please also attach `"yejibro_data.txt"`, with it I will be able to check if it reproduces on my end.

Data
[yejibro_data.txt](https://github.com/tensorflow/tensorflow/files/5806483/yejibro_data.txt)
The data changed slightly since my first post. There were some lines with odd characters (áäæéñóôö) so I wanted to see if removing those helped. It didn't. The new data is attached of course.
Logs
https://gist.github.com/Urkchar/ad6faf20f52732fb3eab2cd04684f01d

**Comment by sanjoy** [comment]
Thanks, unfortunately the reproducer runs fine on my Titan-V.

This is a bit of a shot in the dark but does setting the `TF_FORCE_GPU_ALLOW_GROWTH` env var to `1` workaround the issue?

**Comment by Urkchar** [comment]
I can try that. For my knowledge, what would that do?

**Comment by Urkchar** [comment]
> Thanks, unfortunately the reproducer runs fine on my Titan-V.
> 
> This is a bit of a shot in the dark but does setting the `TF_FORCE_GPU_ALLOW_GROWTH` env var to `1` workaround the issue?

Something is not quite right with your idea.
```
2021-01-13 00:03:47.680127: E tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] The TF_FORCE_GPU_ALLOW_GROWTH environment variable is set but could not be parsed: "1". Valid values are "true" or "false". Using original config value of 0.
```

**Comment by sanjoy** [comment]
Sorry, please set `TF_FORCE_GPU_ALLOW_GROWTH` to `true`.  This prevents TensorFlow from allocating all of the GPU memory on startup.  My (purely speculative) idea is that allocating all of the GPU memory on startup is preventing cuDNN from initializing.

**Comment by Urkchar** [comment]
After applying that workaround, I tried running it how I normally would in Visual Studio Code. I got this error
https://gist.github.com/Urkchar/d95c204fade15be20dfc92d1ec207867
As you can see, there's also another problem with the ETA. It used to be between 4 and 7 minutes per epoch and now it's about 2 hours. I am running it with cuda-memcheck now but I fear it could take a long time before an error is encountered.

**Comment by stefan-falk** [comment]
Have you been able to solve this? I am facing a similar issue and it might be related (see https://github.com/tensorflow/tensorflow/issues/50326).

**Comment by stefan-falk** [comment]
Have you been able to solve this? I am facing a similar issue and it might be related (see https://github.com/tensorflow/tensorflow/issues/50326).

**Comment by Urkchar** [comment]
> Have you been able to solve this? I am facing a similar issue and it might be related (see #50326).

I think I was able to solve this. I think it was because I didn't install cuDNN correctly.
