### ISSUE TITLE
tensorflow not working with RTX 3070 cuda 11.1+cudnn 8.0 and 11.2+cudnn 8.1

### ISSUE THREAD

**Issue by game-sys** [tensorflow/tensorflow#46975]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

I have first installed cuda 11.1 and cudnn 8.0 but i was getting error could not find file libcusolver.so.10 
to solve this i run command 
sudo ln -s /usr/local/cuda-11.1/lib64/libcusolver.so.11 /usr/local/cuda-11.1/lib64/libcusolver.so.10
error was resolved and showed message 
Successfully opened dynamic library libcusolver.so.10
but now i got another error shown below
I also tried cuda 11.2 and cudnn 8.1 there with the same error could not find file libcusolver.so.10  i am getting error could not find libcudnn.so.8

Please help me i just re installed multiple cuda versions cudnn versions and nvidia drivers but could not resolve the issue

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow-gpu 
- TensorFlow version (use command below): 2.4.1
- Python version:3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 11.1 cudnn 8.0
- GPU model and memory: RTX 3070

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

2021-02-07 02:05:18.468688: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
2021-02-07 02:05:19.608268: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-07 02:05:19.608796: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-02-07 02:05:19.636743: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:19.637151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Graphics Device computeCapability: 8.6
coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-02-07 02:05:19.637166: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-02-07 02:05:19.638801: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-02-07 02:05:19.638838: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-02-07 02:05:19.639414: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-02-07 02:05:19.639618: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-02-07 02:05:19.835524: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-02-07 02:05:19.837327: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-02-07 02:05:19.837692: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-02-07 02:05:19.837958: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:19.839606: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:19.851728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-02-07 02:05:19.852873: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-07 02:05:19.854566: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-07 02:05:19.854939: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:19.856558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Graphics Device computeCapability: 8.6
coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-02-07 02:05:19.856623: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-02-07 02:05:19.856695: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-02-07 02:05:19.856746: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-02-07 02:05:19.856795: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-02-07 02:05:19.856844: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-02-07 02:05:19.856893: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-02-07 02:05:19.856942: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-02-07 02:05:19.856991: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-02-07 02:05:19.857186: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:19.858869: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:19.860412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-02-07 02:05:19.866190: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-02-07 02:05:22.758155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-02-07 02:05:22.758203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-02-07 02:05:22.758221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-02-07 02:05:22.758447: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:22.759222: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:22.759935: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-07 02:05:22.760605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6864 MB memory) -> physical GPU (device: 0, name: Graphics Device, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-02-07 02:05:22.990187: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-02-07 02:05:23.007092: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2899885000 Hz
Epoch 1/12
2021-02-07 02:05:23.350598: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-02-07 02:05:27.235033: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-02-07 02:05:27.282436: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-02-07 02:05:29.037626: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-02-07 02:05:29.061028: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    validation_data=(x_test, y_test))
  File "/home/mohsin/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/mohsin/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/mohsin/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/mohsin/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/mohsin/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/mohsin/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/mohsin/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node sequential/conv2d/Conv2D (defined at main.py:63) ]] [Op:__inference_train_function_790]

Function call stack:
train_function

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@game-sys 

Please take a look at this [comment ](https://github.com/tensorflow/tensorflow/issues/43947#issuecomment-716102142)from issue #43947 and #45848  with a similar error and let us know if it helps. Thanks!

**Comment by game-sys** [comment]
https://github.com/tensorflow/tensorflow/issues/45848#issuecomment-748130779 and other mentioned downgrading cuda to 11.0 and cudnn 8.0, but I think cuda 11.0 is not supported in rtx 3070. Please can you confirm

**Comment by nicolaspanel** [comment]
> [#45848 (comment)](https://github.com/tensorflow/tensorflow/issues/45848#issuecomment-748130779) and other mentioned downgrading cuda to 11.0 and cudnn 8.0, but I think cuda 11.0 is not supported in rtx 3070. Please can you confirm

see https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

**Comment by game-sys** [comment]
**i tried to install cuda 11.0 using :**

wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda-repo-ubuntu2004-11-0-local_11.0.2-450.51.05-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu2004-11-0-local_11.0.2-450.51.05-1_amd64.deb
sudo apt-key add /var/cuda-repo-ubuntu2004-11-0-local/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda

**but i got error :**

Processing triggers for initramfs-tools (0.136ubuntu6.3) ...
update-initramfs: Generating /boot/initrd.img-5.8.0-41-generic
Errors were encountered while processing:
 nvidia-dkms-450
 nvidia-driver-450
 cuda-drivers-450
 cuda-drivers
 cuda-runtime-11-0
 cuda-11-0
 cuda-demo-suite-11-0
 cuda
E: Sub-process /usr/bin/dpkg returned an error code (1)

i think cuda 11.0 or 450 driver do not support rtx 3000 series, although https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html state it support 11.0 or i dont if it not support with ubuntu 20 as i installed cuda 11.1 which use 455 driver and 11.2 which use 460 driver using above method and I got no error.

**Comment by game-sys** [comment]
**I purge cuda 11.0 using command:**
# Remove existing CuDA versions
sudo apt --purge remove "cublas*" "cuda*"
sudo apt --purge remove "nvidia*"
rm -rf /usr/local/cuda*
sudo apt-get autoremove && sudo apt-get autoclean

**and upgrade to cuda 11.1 using command:**
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/11.1.0/local_installers/cuda-repo-ubuntu2004-11-1-local_11.1.0-455.23.05-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu2004-11-1-local_11.1.0-455.23.05-1_amd64.deb
sudo apt-key add /var/cuda-repo-ubuntu2004-11-1-local/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda

updated paths

**Comment by game-sys** [comment]
**run my code on terminal using command:**
python main.py 
obviously not installed CUDNN so got a message 
2021-02-09 00:39:50.118328: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-02-09 00:39:50.119809: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-02-09 00:39:50.119836: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-02-09 00:39:50.120394: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-02-09 00:39:50.120525: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-02-09 00:39:50.120603: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.1/lib64:/usr/local/cuda-11.1/lib64:
2021-02-09 00:39:50.120943: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-02-09 00:39:50.120991: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.1/lib64:/usr/local/cuda-11.1/lib64:
2021-02-09 00:39:50.120999: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

then i downloaded **CUDNN 8.0** and 
**installed it using command:**
sudo cp cuda/include/cudnn*.h /usr/local/cuda/include 
sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda/lib64 
sudo chmod a+r /usr/local/cuda/include/cudnn*.h /usr/local/cuda/lib64/libcudnn*

**Comment by game-sys** [comment]
Still issue is not solved waiting for your reply :(

**Comment by nathanin** [comment]
hey @game-sys FWIW I have TensorFlow running with cuda 11.0 + cudnn 8.0.4

Perhaps cuda 11.1 would bring performance improvements, but if you're blocked from working at all because of this, there are options. Cheers

**Comment by game-sys** [comment]
@nathanin how did u install cuda 11.0 did u install it like i showed above or some another way because using above method it also install Nvidia 450 driver which is the problem i think and can u please confirm your driver version. Thanks

**Comment by miramar-labs** [comment]
I observe the same issue - I install tensorflow 2.4.1 into a docker container and run jupyter lab from there... nvidia-smi works fine but tensorflow reports zero GPUs available ... adding two lines to the docker file solves the problem:

`# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

# Install Tensorflow
RUN pip install --quiet --no-cache-dir \
    'tensorflow==2.4.1' && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

## BUG FIX:
ENV LD_LIBRARY_PATH=/usr/local/cuda-11.2/targets/x86_64-linux/lib:$LD_LIBRARY_PATH
RUN ln -s /usr/local/cuda-11.2/targets/x86_64-linux/lib/libcusolver.so.11 $(python -c "import tensorflow.python as x; print(x.__path__[0])")/libcusolver.so.10`

**Comment by nathanin** [comment]
`nvidia-smi`:
```
Mon Feb 15 13:31:01 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3070    Off  | 00000000:08:00.0 Off |                  N/A |
|  0%   40C    P8    18W / 240W |     18MiB /  7979MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1628      G   /usr/lib/xorg/Xorg                  9MiB |
|    0   N/A  N/A      1937      G   /usr/bin/gnome-shell                4MiB |
+-----------------------------------------------------------------------------+
```

I'm not entirely sure where the `CUDA Version: 11.2` comes from, it must have been installed when I installed the driver from the nvidia ppa. The environment I have working was built by installing `cudatoolkit` from conda with: `conda install -c nvidia cudatoolkit=11.0` (the pytorch conda channel will probably also work):
```
conda list | grep cuda
cudatoolkit               11.0.221             h6bb024c_0    nvidia
cudnn                     8.0.4                cuda11.0_0    nvidia
```

I have found `cudnn=8.0.4` to be necessary with the 3070. With `cudnn=8.0` everything appears to load, but actually calling a 2D convolution will error.

**Comment by game-sys** [comment]
@nathanin nvidia-smi return cuda version 11.2 it state that your driver can support cuda 11.2 you can check actual version  of cuda using nvcc --version and i installed all cuda cudnn using Nvidia guidelines on webpage while i will also try conda and let u know.

**Comment by sanjoy** [comment]
Hi,

TensorFlow 2.4 needs CUDA 11.**0**.  Can you confirm that you've tried running it with CUDA 11.0 and it didn't work?

**Comment by game-sys** [comment]
In above comment i mentioned i installed cuda 11.0 https://github.com/tensorflow/tensorflow/issues/46975#issuecomment-775356022
Method used for installation is also mentioned and error i got is also mentioned please let me know did i follow correct steps to install cuda 11.0.

**Comment by miramar-labs** [comment]
one thing to note is that with cuda 11.x :
- nvidia-smi IS able to detect the GPU
- tensorflow is NOT able to detect the GPU
- pytorch IS able to detect the GPU

**Comment by game-sys** [comment]
@miramar-labs same issue here :(

**Comment by miramar-labs** [comment]
@game-sys   try running this workaround:

'''ln -s /usr/local/cuda-11.2/targets/x86_64-linux/lib/libcusolver.so.11 $(python -c "import tensorflow.python as x; print(x.path[0])")/libcusolver.so.10'''

**Comment by miramar-labs** [comment]
I wrote a utility to test this .. 

https://github.com/miramar-labs/cuda-tf-torch-test

**Comment by miramar-labs** [comment]
Looking at the TF [build docs](https://www.tensorflow.org/install/source) I noticed that TF 2.4.0 is tested for compatibility with CUDA 11.0 and cuDNN 8.0 .... so I downgraded to those versions and things went a lot smoother :)   
11.2 != 11.0  ....
What I learned: stick to the versions of TF/CUDA/cuDNN mentioned in the docs ... go beyond at your own risk :)

**Comment by game-sys** [comment]
@miramar-labs which driver u are using is it 460 and how u install cuda because when i install cuda 11.0 it also come with driver and it install driver automatically and rtx 3070 dont support driver 450 can u please run nvidia smi, and nvcc -- version what it is returning

**Comment by miramar-labs** [comment]
@game-sys  I have a [repo on github](https://github.com/miramar-labs/tensorflow-build) for building TF ... I added some pretty detailed notes as to exactly what versions of things I ended up using .. hope it helps :)

**Comment by game-sys** [comment]
Ok i will try and let u know. @miramar-labs

**Comment by game-sys** [comment]
I solve it by just creating a conda environment 
**using command**
conda create -n tensor2 python=3.6 tensorflow-gpu cudatoolkit cudnn
and then I ran **command**

python
>>> import tensorflow as tf
>>>tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)

It **returned** 

WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2021-03-06 11:39:38.634479: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-03-06 11:39:38.658818: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2899885000 Hz
2021-03-06 11:39:38.659188: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5621530cce70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-06 11:39:38.659204: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-03-06 11:39:38.659809: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-03-06 11:39:38.701441: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:39:38.703134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 3070 computeCapability: 8.6
coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-03-06 11:39:38.733974: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-03-06 11:39:38.958161: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-03-06 11:39:39.074762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-03-06 11:39:39.128519: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-03-06 11:39:39.348554: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-03-06 11:39:39.399564: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-03-06 11:39:39.851696: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-03-06 11:39:39.851985: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:39:39.853718: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:39:39.855140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-03-06 11:39:39.855246: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-03-06 11:39:40.116405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-06 11:39:40.116440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2021-03-06 11:39:40.116448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2021-03-06 11:39:40.116630: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:39:40.117258: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:39:40.117840: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:39:40.118403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/device:GPU:0 with 6987 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-03-06 11:39:40.140623: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5621541ecce0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-03-06 11:39:40.140679: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 3070, Compute Capability 8.6
True


but i dont know what this mean 
successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:39:40.117840: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero

is it correctly installed

**Comment by game-sys** [comment]
I ran a simple python file
>import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K


batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()


if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')



# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
validation_data=(x_test, y_test))

but it **hang** on 
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
2021-03-06 11:47:01.777594: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-03-06 11:47:01.812831: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.813431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 3070 computeCapability: 8.6
coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-03-06 11:47:01.813620: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-03-06 11:47:01.815197: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-03-06 11:47:01.816635: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-03-06 11:47:01.816843: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-03-06 11:47:01.818293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-03-06 11:47:01.819109: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-03-06 11:47:01.822096: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-03-06 11:47:01.822182: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.822686: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.823101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-03-06 11:47:01.823360: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-03-06 11:47:01.828401: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2899885000 Hz
2021-03-06 11:47:01.828730: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d67c663200 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-06 11:47:01.828744: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-03-06 11:47:01.828871: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.829358: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 3070 computeCapability: 8.6
coreClock: 1.725GHz coreCount: 46 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2021-03-06 11:47:01.829393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-03-06 11:47:01.829404: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-03-06 11:47:01.829413: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-03-06 11:47:01.829422: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-03-06 11:47:01.829431: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-03-06 11:47:01.829439: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-03-06 11:47:01.829448: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-03-06 11:47:01.829492: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.829898: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.830287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-03-06 11:47:01.830310: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-03-06 11:47:01.896638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-06 11:47:01.896662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2021-03-06 11:47:01.896666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2021-03-06 11:47:01.896778: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.897152: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.897498: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-06 11:47:01.897840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7007 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-03-06 11:47:01.899080: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d67d8d3850 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-03-06 11:47:01.899090: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 3070, Compute Capability 8.6

**Comment by game-sys** [comment]
**After 5 min** 
Epoch 1/12
2021-03-06 11:51:58.746746: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
**After 2 min**
2021-03-06 11:53:25.153184: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7

**Comment by walli55** [comment]
LICENSE

**Comment by walli55** [comment]
Alomaisi

**Comment by mchuv** [comment]
Hi I want to share my results with you:

Operative System: Ubuntu 20.04
CPU : AMD Ryzen 7 3800X
TensorFlow version: 2.4
Python version: 3.8 (default with Ubuntu)
Cuda version :  11.1.0   The installer name is : cuda_11.1.0_455.23.05_linux.run
CudNN version: 8.0.5    The installer package is : libcudnn8_8.0.5.39-1+cuda11.1_amd64.deb

**The first error a got was:**

Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.

I solved it creating the symbolic link with:

sudo ln -s ./libcusolver.so.11 ./libcusolver.so.10

The current directory was: /usr/local/cuda-11.1/lib64

**The second error was:**

Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR 

I solved it adding the following two lines of code after the imports in my python code:

physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

**Finally i want to share my speed results:**

With my MacBook Pro 2019 15" Core i7 + AMD GPU 555X + Apple Custom TensorFlow 2.4 the training of a model takes 45minutes per epoch, using TensorFlow 2.2 and CPU it takes 60 minutes per epoch.

With my new Ryzen 7 3080X custom assembled PC, using CPU it takes 24 minutes per epoch.

With my new Ryzen 7 3080X custom assembled PC, using RTX 3070 GPU it only takes 5:20 minutes per epoch, this is a super improvement in my training.


I hope it can help you, i spent 2 days trying to solve this errors.

**Comment by SohaibAnwaar** [comment]
Hy I hope that  you all are doing good. I need to train my mrcnn model on gtx 3070. Model loads onto the gpu but stuck while starting training no error appears but it stuck.

Versions I am using:

1. Tensorflow 2.4
2. cudnn 8
3. cuda 11.0
4. nvidia-drivers 460


![Screenshot from 2021-04-18 12-45-13](https://user-images.githubusercontent.com/29427728/115138252-681ec780-a044-11eb-9e7d-c567d1219df0.png)

![Screenshot from 2021-04-18 12-45-37](https://user-images.githubusercontent.com/29427728/115138260-6ead3f00-a044-11eb-8e35-7fb1f976b51e.png)

![Screenshot from 2021-04-18 12-47-57](https://user-images.githubusercontent.com/29427728/115138273-7ec51e80-a044-11eb-91df-b8f536cb8952.png)


I will really be thankful to you for helping me out. Thank you

**Comment by mchuv** [comment]
Hi, sorry I can't help you, because I only work with local training and never use Jupiter and/or Notebooks.

**Comment by SohaibAnwaar** [comment]
> Hi, sorry I can't help you, because I only work with local training and never use Jupiter and/or Notebooks.

I am currently using this repo
Github Link: https://github.com/SohaibAnwaar/Mask-Rcnn-Tensorflow-2.0

I tried by using py file But still stuck on the same point
![Screenshot from 2021-04-18 14-55-46](https://user-images.githubusercontent.com/29427728/115141570-94dbda80-a056-11eb-81d5-47cab56f59ae.png)

**Comment by nikonyrh** [comment]
I struggled with this as well, having just purchased a 3070 TI. I had to symlink the libcusolver.so as well, but it didn't resolve all of my issues. I got everything working with these additional steps:
- Upgrade Tensorflow 2.4 -> 2.5
- Upgrade CUDA 11.1 -> 11.2 ([link](https://developer.nvidia.com/cuda-11.2.2-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal))
- Install cudnn-11.2-linux-x64-v8.1.1.33

I kept the 460.91.03 driver I used with the previous 1080 TI. Actually I intended to update it first but couldn't get it to work via a ".run" installer or apt :D

**Comment by sushreebarsa** [comment]
@game-sys Could you try with the latest TF version (2.9.0) and let us know the outcome?
Thank you!
