### ISSUE TITLE
CUDA_ERROR_NO_BINARY_FOR_GPU on A100 when compiled with CC 7.0

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#47058]
**System information**
- Have I written custom code: No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.4
- Bazel version (if compiling from source): 3.7.1
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: A100

**Describe the current behavior**

I'm compiling TF for our cluster with a CUDA 11 driver but 10.1 toolkit (there are reasons not to upgrade nvcc yet). Hence the maximum supported CUDA compute capability by nvcc is 7.0, but the A100 GPUs used have 8.0. This shouldn't be a problem as the CUDA driver can JIT compile the 7.0 PTX code for the A100.

However running the tests from the TensorFlow repo yields errors like: `tensorflow.python.framework.errors_impl.InternalError: Failed to load in-memory CUBIN: CUDA_ERROR_NO_BINARY_FOR_GPU: no kernel image is available for execution on the device [Op:Abs]`

Following the error message I come to `GpuExecutor::GetKernel` which has some logic whether to load a cubin or ptx binary, so my feeling is that that is faulty.

**Describe the expected behavior**

PTX code is loaded and kernel executed successfully

**Standalone code to reproduce the issue**

- `export TF_CUDA_COMPUTE_CAPABILITIES=3.7,6.1,7.0`
- `bazel test --config=noaws --config=nogcp --config=nohdfs --compilation_mode=opt --config=opt --subcommands --verbose_failures --jobs=64 --copt="-fPIC" --distinct_host_configuration=false --config=mkl --test_output=errors --build_tests_only --local_test_jobs=1 --test_timeout=3600 --test_size_filters=small -- //tensorflow/core/kernels/mlir_generated:gpu_abs_test_gpu`

**Other info / logs**
Example error:

```
ERROR: testBroadcastWithBatchParamsAndBiggerEvent (__main__.CategoricalTest)
CategoricalTest.testBroadcastWithBatchParamsAndBiggerEvent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/distributions/categorical_test.py", line 296, in testBroadcastWithBatchParamsAndBiggerEvent
    "norm_cdf": norm.cdf(real_event_tf),
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/distributions/distribution.py", line 898, in cdf
    return self._call_cdf(value, name)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/distributions/distribution.py", line 874, in _call_cdf
    return self._cdf(value, **kwargs)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/distributions/normal.py", line 207, in _cdf
    return special_math.ndtr(self._z(x))
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/distributions/special_math.py", line 143, in ndtr
    return _ndtr(x)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/distributions/special_math.py", line 151, in _ndtr
    z = math_ops.abs(w)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 401, in abs
    return gen_math_ops._abs(x, name=name)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 46, in _abs
    _ops.raise_from_not_ok_status(e, name)
  File "/dev/shm/s3248973-EasyBuild/TensorFlow/2.4.1/fosscuda-2019b-Python-3.7.4/tmp9lUSI1-bazel-tf/fdff6046a749a079864ed2bee7e018bf/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/distributions/categorical_test_gpu.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Failed to load in-memory CUBIN: CUDA_ERROR_NO_BINARY_FOR_GPU: no kernel image is available for execution on the device [Op:Abs]
```

**Comment by Flamefire** [comment]
I think I was able to trace this to ultimately `tf_to_gpu_binary` which is used to compile MLIR code to SASS (CUDA binary format) which is then put as binary inside the executable and loaded via `LoadModuleFromCuBin`
However it looks like PTX code is not included when creating that (fat) binary which makes TensorFlow basically unusable on GPUs it has not been exactly compiled for.
Any ideas how to solve that?

**Comment by sherhut** [comment]
You want to specify something like

`TF_CUDA_COMPUTE_CAPABILITIES="sm_35,sm_50,sm_60,sm_70,sm_75,compute_80"`

where the `sm_xx` are the compute capabilities you want to ship fully compiled cubins for and the `compute_xx` are the ones that also include a PTX source variant. Can you try and report whether that fixes your issue?

**Comment by Flamefire** [comment]
No this does not help. The current values used (7.5 and so on) are already converted to `compute_75`: https://github.com/tensorflow/tensorflow/blob/v2.4.1/third_party/gpus/cuda_configure.bzl#L425-L430

The problem is that this is ignored by the kernel builder: https://github.com/tensorflow/tensorflow/blob/v2.4.1/third_party/gpus/cuda_configure.bzl#L425-L430

See also https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.cc#L52 for that param

**Comment by sherhut** [comment]
Looking at this, I believe we are generating a ptx variant. Could you try remove the `"--cmdline=--compile-only",` in this file https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/stream_executor/gpu/asm_compiler.cc#L300 and see whether that helps?

I will prepare a patch to clean this up, just wanting to check whether this fixes your issue.

**Comment by Flamefire** [comment]
No this does not fix the issue. The reason is that the tf_to_gpu_binary did not include the PTX code at all

However the mentioned line can likely be removed. I had problems after I patched the generator to return either PTX or SM code depending on whether it was passed sm_* or compute_*. Those problems were resolved by removing the `--compile-only` and I asked on SO for clarification without any response so far: https://stackoverflow.com/questions/66171048/significance-of-compile-only-for-cuda-fatbinary-creation

But again: This alone does not work, because no PTX code is returned in 2.4.1, see https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc#L170-L185 where the `!generate_fatbin_` branch is taken and the ptx code is ignored. My patch consisted of mainly:
```
--- a/tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc
+++ b/tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc
@@ -171,6 +171,11 @@ class GpuKernelToBlobPass
         // Skip fatbin generation and return the first and only GPU machine
         // code. This is currently only used for `tf_to_gpu_binary` and will
         // eventually disappear.
+        if (is_compute_profile) {
+          std::vector<uint8_t> ptx_bytes;
+          std::copy(ptx.begin(), ptx.end(), std::back_inserter(ptx_bytes)); // can probably be done in the ctor directly
+          return ptx_bytes;
+        }
         return gpu_asm;
       }

```

During my tests on a cluster with A100s this did seemingly work, but the CUDA JIT compilation from PTX turned out to be REALLY slow and produced GigaBytes of compiled code in the compute cache folder. To make that worse, the default cache folder is inside the users HOME which on clusters is usually a NFS mounted folder making it even slower which is why I ultimately gave up on that.

**Comment by sherhut** [comment]
Thank you for looking into this further. I had missed that this was using the `tf_to_gpu_binary` path. You are correct, on that path we only include ptx code and we really should ship a fatbin there, as well.

With TensorFlow 2.5 this path will go away. I believe another valid approach would be to remove the entire block for `!generate_fatbin" and use the fatbin path always. With the additional fix of removing the `--cmdline=--compile-only` string.

It is unlikely, though, that this will address your performance issue. The driver will still need to jit the ptx code for every involved operation, which is inherently slow.

**Comment by SuryanarayanaY** [comment]
Hi @Flamefire ,

I just wanted to check status of this issue from backlog.As there is changes in Paths with latest versions I have changed the target to `tensorflow/core/kernels/mlir_generated:gpu_binary_ops_test.cc`  and tested the bazel build which is success. Please refer the attached command and its log below.

```
tf2) suryanarayanay@ubuntu-surya-test:~/tensorflow$ bazel test --config=noaws --config=nogcp --config=nohdfs --compilation_mode=opt --config=opt --subcommands --verbose_failures --jobs=64 --copt="-fPIC" --distinct_host_configuration=false --config=mkl --test_output=errors --build_tests_only --local_test_jobs=1 --test_timeout=3600 --test_size_filters=small -- //tensorflow/core/kernels/mlir_generated:gpu_binary_ops_test.cc
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=91
INFO: Reading rc options for 'test' from /home/suryanarayanay/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'test' from /home/suryanarayanay/tensorflow/.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'test' from /home/suryanarayanay/tensorflow/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/home/suryanarayanay/miniconda3/envs/tf2/bin/python3 --action_env PYTHON_LIB_PATH=/home/suryanarayanay/miniconda3/envs/tf2/lib/python3.9/site-packages --python_path=/home/suryanarayanay/miniconda3/envs/tf2/bin/python3
INFO: Reading rc options for 'test' from /home/suryanarayanay/tensorflow/.bazelrc:
  Inherited 'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Reading rc options for 'test' from /home/suryanarayanay/tensorflow/.tf_configure.bazelrc:
  'test' options: --flaky_test_attempts=3 --test_size_filters=small,medium
INFO: Found applicable config definition build:short_logs in file /home/suryanarayanay/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/suryanarayanay/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition test:v2 in file /home/suryanarayanay/tensorflow/.tf_configure.bazelrc: --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial,-v1only --build_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
INFO: Found applicable config definition build:noaws in file /home/suryanarayanay/tensorflow/.bazelrc: --define=no_aws_support=true
INFO: Found applicable config definition build:nogcp in file /home/suryanarayanay/tensorflow/.bazelrc: --define=no_gcp_support=true
INFO: Found applicable config definition build:nohdfs in file /home/suryanarayanay/tensorflow/.bazelrc: --define=no_hdfs_support=true
INFO: Found applicable config definition build:opt in file /home/suryanarayanay/tensorflow/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:mkl in file /home/suryanarayanay/tensorflow/.bazelrc: --define=build_with_mkl=true --define=enable_mkl=true --define=tensorflow_mkldnn_contraction_kernel=0 --define=build_with_openmp=true -c opt
INFO: Found applicable config definition build:linux in file /home/suryanarayanay/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/suryanarayanay/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 test targets...
INFO: Elapsed time: 0.966s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
(tf2) suryanarayanay@ubuntu-surya-test:~/tensorflow$ 
```

I hope the problem resolved already and please confirm whether you want to still test it for any particular target ? 
Please feel free to close the issue if resolved.If not please confirm the issue and build configs/targets that are failing with latest versions.

 Thanks!

**Comment by Flamefire** [comment]
Haven't seen this issue lately and the related code has changed considerably. So I guess this has been fixed by now in recent version(s).

**Comment by SuryanarayanaY** [comment]
@Flamefire ,

Thanks for response. Yes , there has been changes in paths compared to your earlier tested targets and bug fixed in recent versions already.Please feel free to close the issue or let us know if we can close the issue. Thanks!
