### ISSUE TITLE
Tensorflow not using GPU eventhough it is detecting it.

### ISSUE THREAD

**Issue by tavishm** [tensorflow/tensorflow#47876]
**System information**
- I have custom code
- Linux, Ubuntu 20.04
- Not on a mobile device
- Binary
- Tensorflow: v2.4.1
- Python version: python3.8
- CUDA/cuDNN version: v11.0, v8.0.4
- GPU model and memory: Nvidia GTX 1080 Ti, 16 GB

Tensorflow detects my GPU. When I do` tf.config.list_physical_devices()`
I get

```

2021-03-18 13:21:44.097589: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-18 13:21:44.113342: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-18 13:21:44.230424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:0a:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-03-18 13:21:44.230498: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-03-18 13:21:44.248080: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-03-18 13:21:44.248189: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-03-18 13:21:44.257026: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-03-18 13:21:44.261437: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-03-18 13:21:44.277956: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-03-18 13:21:44.285094: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-03-18 13:21:44.288191: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-03-18 13:21:44.295201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

But when I'm training `nvidia-smi`
returns 

```
Thu Mar 18 13:22:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:0A:00.0  On |                  N/A |
| 32%   57C    P0    65W / 250W |    381MiB / 11177MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3413      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      5526      G   /usr/lib/xorg/Xorg                116MiB |
|    0   N/A  N/A      5669      G   /usr/bin/gnome-shell               96MiB |
|    0   N/A  N/A      7173      G   ...AAAAAAAAA= --shared-files       75MiB |
|    0   N/A  N/A      7628      G   ...AAAAAAAAA= --shared-files       14MiB |
|    0   N/A  N/A      7636      G   ...AAAAAAAA== --shared-files       15MiB |
|    0   N/A  N/A    277380      G   ...AAAAAAAAA= --shared-files       11MiB |
+-----------------------------------------------------------------------------+

```
It doesn't look like my GPU is being used.

I expect the GPU to be used

I'm just import tensorflow and expecting it to use the GPU, tell me if there's another way.
I remember setting an environment variable `CUDA_VISIBLE_DEVICES` a few versions ago. Is it still necessary to set this?

**Comment by tavishm** [comment]
Is there something I'm doing wrong?

**Comment by tavishm** [comment]
I've solved the issue, turns out I had to set the environment variable. I'm closing this issue.
