### ISSUE TITLE
CUDA_ERROR_UNKNOWN in Docker Rootless Mode.

### ISSUE THREAD

**Issue by gmaratos** [tensorflow/tensorflow#48002]
## Summary
Tensorflow docker image fails to use GPU

## Configuration
1. Debian 10
2. Nvidia driver 460.32.03
3. 3 RTX 2080, 128 GB of Memory

## Explanation
I was trying to set up a Tensorflow container in rootless-mode. I had to jump through a few hoops, like disabling cgroups and manually installing slirp4netns (v1.1.4).

I tried the docker containers tensorflow/tensorflow:latest-gpu and tensorflow/tensorflow:2.4.1-gpu both seem to not work.

I run
```
docker run -it --rm --gpus all tensorflow/tensorflow:latest-gpu python
```
and everything starts normally. nvidia-smi reports all three of my gpu's. If I try to test functionality I get unknown error that I don't know how to track down in the container.

```
>>> import tensorflow as tf
2021-03-23 05:58:32.641242: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0

>>> print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
2021-03-23 05:59:00.670935: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 05:59:00.673743: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-23 05:59:00.705979: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2021-03-23 05:59:00.706237: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 45f73818aefd
2021-03-23 05:59:00.706366: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 45f73818aefd
2021-03-23 05:59:00.706791: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.32.3
2021-03-23 05:59:00.706968: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.32.3
2021-03-23 05:59:00.707088: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.32.3
Num GPUs Available:  0
```

## Extra Information
If it helps I tried to use these resources.

https://docs.docker.com/engine/install/debian/.
https://docs.docker.com/engine/security/rootless/
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker

**Comment by gmaratos** [comment]
Docker version = 20.10.5

**Comment by Saduf2019** [comment]
@gmaratos 
Please confirm if you are using tensorflow 1.14, as there is no support for yf 1.x , please upgrade to/install tf 2.x and let us know if you face any issues.

**Comment by gmaratos** [comment]
Yes I can confirm on both images

$> docker run -it --rm --gpus all tensorflow/tensorflow:latest-gpu python
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-03-23 13:52:44.163052: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> tf.__version__
'2.4.1'

$> docker run -it --rm --gpus all tensorflow/tensorflow:2.4.1-gpu python
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-03-23 13:54:20.110771: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> tf.__version__
'2.4.1'

**Comment by ymodak** [comment]
Please take a look at this related [thread](https://github.com/tensorflow/tensorflow/issues/32623)
Also see this particular [solution]((https://github.com/tensorflow/tensorflow/issues/32623#issuecomment-533936509).) posted by the user. Thanks!

**Comment by gmaratos** [comment]
Ok this fixed the problem. I ran the Device Node Verification script from [here](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications).

Now all three GPU's are available in the container. Unfortunately I was a little too eager and just ran the script first. I cannot confirm if `nvidia-modprobe` also solves the problem or what the device permissions were before I ran it.

Somehow how I missed that previous issue, thank you so much for your help.
