### ISSUE TITLE
TensorFlow Lite conversion error when using the slice semantics to expand the last dimension

### ISSUE THREAD

**Issue by barabanus** [tensorflow/tensorflow#48018]
### 1. System information

- Linux 5.11.4-arch1-1 #1 SMP PREEMPT Sun, 07 Mar 2021 18:00:49 +0000 x86_64 GNU/Linux
- TensorFlow 2.4.1 from `tensorflow-opt-cuda` package (https://archlinux.org/packages/community/x86_64/tensorflow-opt-cuda)

### 2. Code

Please unzip this protobuf file before running the code: [tflite-strided-slice-fail.zip](https://github.com/tensorflow/tensorflow/files/6191669/tflite-strided-slice-fail.zip)

```python
# use tensorflow API v1
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

PROTOBUF_PATH = "tflite-strided-slice-fail.pb"

with tf.gfile.GFile(PROTOBUF_PATH, "rb") as fprotobuf:
    graphDef = tf.GraphDef()
    graphDef.ParseFromString(fprotobuf.read())

X = tf.placeholder(dtype=tf.float32, shape=[1, 309], name="X")
P = tf.placeholder(dtype=tf.float32, shape=[1], name="P")

Yhat, = tf.import_graph_def(
    graphDef,

    input_map={
        "runtime/X:0": X,
        "runtime/P:0": P,
    },
    name="model",
    return_elements=[f"runtime/Y/fast/32:0"]
)

with tf.Session() as session:
    converter = tf.lite.TFLiteConverter.from_session(
        session,
        input_tensors=[X, P],
        output_tensors=[Yhat]
    )
    flatbuffer = converter.convert()
```

### 3. Failure after conversion
```
ConverterError: /usr/lib/python3.9/site-packages/tensorflow/python/framework/importer.py:400:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:538:0: note: called from
/home/barabanus/work/4a-games/pfnn-tools/test/tflite-fail-1.py:14:0: note: called from
/usr/lib/python3.9/site-packages/IPython/utils/py3compat.py:168:0: note: called from
/usr/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2740:0: note: called from
/usr/lib/python3.9/site-packages/IPython/core/shellapp.py:377:0: note: called from
/usr/lib/python3.9/site-packages/IPython/core/shellapp.py:452:0: note: called from
/usr/lib/python3.9/site-packages/IPython/core/shellapp.py:328:0: note: called from
/usr/lib/python3.9/site-packages/IPython/terminal/ipapp.py:323:0: note: called from
/usr/lib/python3.9/site-packages/traitlets/config/application.py:87:0: note: called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
```

### 5. Any other info / logs
The problem has to do with the slice semantics when I try to expand the last dimension of a tensor like `tensor[..., None]` to match matrix multiplication dimensions requirement. Usually it works, but I found an example of computational graph which fails to convert with TFLite.

The problem has been solved by replacing the slice semantics `X[..., None]` with `tf.expand_dims(X, axis=-1)` and `Y[0]` with `tf.squeeze(Y, axis=0)`, but it should have been worked with the slice semantics.

The full log:
```
2021-03-23 19:32:32.072655: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /usr/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-03-23 19:32:33.177145: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:32:33.177749: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-23 19:32:33.290409: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-03-23 19:32:33.290438: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (rb15): /proc/driver/nvidia/version does not exist
2021-03-23 19:32:33.290815: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-23 19:32:33.291632: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:32:33.291674: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2021-03-23 19:32:33.294267: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-03-23 19:32:33.294368: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-03-23 19:32:33.294574: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:32:33.310613: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2200660000 Hz
2021-03-23 19:32:33.312516: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.005ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.

2021-03-23 19:32:33.318140: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-03-23 19:32:33.318275: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-03-23 19:32:33.318494: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:32:33.320979: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.003ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.

2021-03-23 19:32:33.331507: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored output_format.
2021-03-23 19:32:33.331542: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored drop_control_dependency.
2021-03-23 19:32:33.341942: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:32:33.341994: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
loc(callsite("model/runtime/strided_slice_26"("/usr/lib/python3.9/site-packages/tensorflow/python/framework/importer.py":400:0) at callsite("/usr/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py":538:0 at "/home/barabanus/work/4a-games/pfnn-tools/test/tflite-fail-1.py":14:0))): error: 'tf.StridedSlice' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 210, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: /usr/lib/python3.9/site-packages/tensorflow/python/framework/importer.py:400:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:538:0: note: called from
/home/barabanus/work/4a-games/pfnn-tools/test/tflite-fail-1.py:14:0: note: called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/barabanus/work/4a-games/pfnn-tools/test/tflite-fail-1.py", line 31, in <module>
    flatbuffer = converter.convert()
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1947, in convert
    return super(TFLiteConverter, self).convert()
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1300, in convert
    result = _toco_convert_impl(
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 608, in toco_convert_impl
    data = toco_convert_protos(
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: /usr/lib/python3.9/site-packages/tensorflow/python/framework/importer.py:400:0: error: 'tf.StridedSlice' op is neither a custom op nor a flex op
/usr/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:538:0: note: called from
/home/barabanus/work/4a-games/pfnn-tools/test/tflite-fail-1.py:14:0: note: called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
```

**Comment by abattery** [comment]
Please use the Select TF option. https://www.tensorflow.org/lite/guide/ops_select

**Comment by barabanus** [comment]
@abattery Thank you for examining this issue. Unfortunately, using TF within our runtime environment is not possible. I fixed the issue by replacing `tensor[..., None]` with `tf.expand_dims(tensor, axis=-1)`.

Usually, `tensor[..., None]` works without a problem within both TF and TFLite. Before I tried to post this issue I failed to make a simple example for which `tensor[..., None]` would not convert to TFLite, so TFLite is aware of this kind of strided slice op. I used a simplified example from the real project instead where `tensor[..., None]` doesn't convert.

I suggest to modify TFLite converter so that when it meets dimension expansion using slice semantics it replaces the op with `tf.expand_dims()`.

**Comment by abattery** [comment]
Actually, FYI, @thaink is working on all the cases of TF strided slice op in TFLite op. Thanks for the suggestion. Closing since the problem has been resolved.

**Comment by barabanus** [comment]
@abattery Could you please link this issue with the one @thaink works with? I'll double check the issue is fixed.

**Comment by abattery** [comment]
Closed because you fixed the issue by using the other pattern with expand_dims op. @thaink is working on delivering the improvement of TFLite strided slice op kernel, which hasn't been done yet.

**Comment by thaink** [comment]
I think it is fair to keep this bug opened. My PR for supporting ellipsis_mask and new_axis_mask is almost complete. I'll send it shortly.

**Comment by thaink** [comment]
The feature is added at commit be1238ceddf16e5668547b0702228a5b1aed2527. you can try to convert it with tomorrow's nightly.

**Comment by barabanus** [comment]
@thaink Thank you very much, I'll do it these weekends

**Comment by barabanus** [comment]
I probably wait for updated `tensorflow-opt-cuda` package and then reopen the issue in the case it's not fixed. Thank you very much for your work.
