### ISSUE TITLE
TensorFlow Lite allocation error after successful conversion: tfl.Slice node failed to prepare

### ISSUE THREAD

**Issue by barabanus** [tensorflow/tensorflow#48022]
### 1. System information

- Linux 5.11.4-arch1-1 #1 SMP PREEMPT Sun, 07 Mar 2021 18:00:49 +0000 x86_64 GNU/Linux
- TensorFlow 2.4.1 from `tensorflow-opt-cuda` package (https://archlinux.org/packages/community/x86_64/tensorflow-opt-cuda)

### 2. Code

Please unzip this protobuf file before running the code: [allocate-fail-protobuf.zip](https://github.com/tensorflow/tensorflow/files/6191821/allocate-fail-protobuf.zip)

```python
# use tensorflow API v1
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

PROTOBUF_PATH = "allocate-fail.pb"

with tf.gfile.GFile(PROTOBUF_PATH, "rb") as fprotobuf:
    graphDef = tf.GraphDef()
    graphDef.ParseFromString(fprotobuf.read())

X = tf.placeholder(dtype=tf.float32, shape=[1, 309], name="X")
P = tf.placeholder(dtype=tf.float32, shape=[1], name="P")

Yhat, = tf.import_graph_def(
    graphDef,

    input_map={
        "runtime/X:0": X,
        "runtime/P:0": P,
    },
    name="model",
    return_elements=[f"runtime/Y/fast/32:0"]
)

with tf.Session() as session:
    converter = tf.lite.TFLiteConverter.from_session(
        session,
        input_tensors=[X, P],
        output_tensors=[Yhat]
    )
    flatbuffer = converter.convert()

interpreter = tf.lite.Interpreter(model_content=flatbuffer)
interpreter.allocate_tensors()
```

### 3. Failure after conversion
The computational graph converts without an error, but when I try to allocate tensors there's internal error within TensorFlow Lite C modules:
```
Traceback (most recent call last):
  File "/home/barabanus/work/4a-games/pfnn-tools/test/tflite-allocate-fail.py", line 34, in <module>
    interpreter.allocate_tensors()
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Invalid begin and size.Node number 20 (SLICE) failed to prepare.
```
The error refers to `tfl.Slice` operation within the graph.

### 5. Any other info / logs

TFLite model after conversion: [allocate-fail-flatbuffer.zip](https://github.com/tensorflow/tensorflow/files/6191844/allocate-fail-flatbuffer.zip)

The full log:
```
2021-03-23 19:48:41.585258: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /usr/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-03-23 19:48:42.626809: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:48:42.627325: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-23 19:48:42.739393: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-03-23 19:48:42.739422: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (rb15): /proc/driver/nvidia/version does not exist
2021-03-23 19:48:42.739809: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-23 19:48:42.740475: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:48:42.740514: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2021-03-23 19:48:42.742921: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-03-23 19:48:42.743008: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-03-23 19:48:42.743161: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:48:42.757234: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2200660000 Hz
2021-03-23 19:48:42.758795: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.004ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.

2021-03-23 19:48:42.764013: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-03-23 19:48:42.764171: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-03-23 19:48:42.764396: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:48:42.766009: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.002ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.

2021-03-23 19:48:42.776385: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored output_format.
2021-03-23 19:48:42.776410: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored drop_control_dependency.
2021-03-23 19:48:42.786790: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-23 19:48:42.786850: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/home/barabanus/work/4a-games/pfnn-tools/test/tflite-allocate-fail.py", line 34, in <module>
    interpreter.allocate_tensors()
  File "/usr/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Invalid begin and size.Node number 20 (SLICE) failed to prepare.
```

**Comment by abattery** [comment]
Could you verify the given input is also valid in your TF model as well?

**Comment by barabanus** [comment]
@abattery Let me modify the example to show yout that it works fine:

```python
# use tensorflow API v1
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

PROTOBUF_PATH = "tflite-allocate-fail.pb"

with tf.gfile.GFile(PROTOBUF_PATH, "rb") as fprotobuf:
    graphDef = tf.GraphDef()
    graphDef.ParseFromString(fprotobuf.read())

X = tf.placeholder(dtype=tf.float32, shape=[1, 309], name="X")
P = tf.placeholder(dtype=tf.float32, shape=[1], name="P")

Yhat, = tf.import_graph_def(
    graphDef,

    input_map={
        "runtime/X:0": X,
        "runtime/P:0": P,
    },
    name="model",
    return_elements=[f"runtime/Y/fast/32:0"]
)

with tf.Session() as session:

    result = session.run(
        Yhat,
        feed_dict={
            X: tf.random.normal(shape=[1, 309]).eval(session=session),
            P: tf.random.normal(shape=[1]).eval(session=session),
    })
    print(result)

    converter = tf.lite.TFLiteConverter.from_session(
        session,
        input_tensors=[X, P],
        output_tensors=[Yhat]
    )
    flatbuffer = converter.convert()
    with open("allocate-fail.tflite", "wb") as fout:
        fout.write(flatbuffer)


interpreter = tf.lite.Interpreter(model_content=flatbuffer)
interpreter.allocate_tensors()
```

We used this graph (with correct weights) successfully within our TF project until we migrated to TFLite.

**Comment by abattery** [comment]
I verified that the above error is gone at the tf-nightly version.

**Comment by Saduf2019** [comment]
@barabanus 
Please move this to closed status if resolved.
