### ISSUE TITLE
Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: :/usr/local/cuda-7.5/lib64

### ISSUE THREAD

**Issue by AFAgarap** [tensorflow/tensorflow#4827]
I have a system where I installed CUDA 7.5 for TensorFlow 0.10.0. The specs of my system is written in #4825 . However, I have a small problem when importing `tensorflow` in my Python 3.5.2

Screenshot of the problem.

![screenshot from 2016-10-08 01-11-11](https://cloud.githubusercontent.com/assets/11130276/19199007/8a0a861c-8cf4-11e6-8155-6a71ff932947.png)

Any help would be great!

**Comment by tatatodd** [comment]
@AFAgarap For future note, please cut-and-paste text into your issues, rather than attaching screenshots.

Please answer the following question:

---

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

---

Also note that the following two errors seem to indicate a mix-up between cuda 7.5 and 8.0:

`/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5 is not a symbolic link`
`Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: :/usr/local/cuda-7.5/lib64`

**Comment by AFAgarap** [comment]
@tatatodd Yes, I do have cuda 8.0 installed. I installed 7.5 when I couldn't get 8.0 to work cor TensorFlow.

**Comment by AFAgarap** [comment]
Output of `ls -l /usr/local/cuda-7.5/lib/libcud*`:

```
-rw-r--r-- 1 root root 189170 Oct  8 00:30 /usr/local/cuda-7.5/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Oct  8 00:30 /usr/local/cuda-7.5/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Oct  8 00:30 /usr/local/cuda-7.5/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Oct  8 00:30 /usr/local/cuda-7.5/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Oct  8 00:30 /usr/local/cuda-7.5/lib/libcudart_static.a
```

**Comment by AFAgarap** [comment]
I already removed CUDA 8.0 by `sudo -r /usr/local/cuda-8.0` but the same error persists.

**Comment by AFAgarap** [comment]
Am good with this already. I reinstalled CUDA 7.5 and cuDNN. I have a new problem though #4841

**Comment by clockzhong** [comment]
I've a similar problem for CUDA 8.0(latest version) also. The following is my error output when I doing a simple test on my newly installed environment:
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: /usr/local/cuda-8.0/lib64
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally

**Comment by AFAgarap** [comment]
@clockzhong Did you try reinstalling CUDA? What's the version of your TensorFlow? Did you upgrade to the latest version?

**Comment by clockzhong** [comment]
@AFAgarap I'm very sorry, it seems my mistake. I mixed the CUDA library with CUDNN library. I need install both of them. Thanks for your reply, I'll correct this mistake soon

**Comment by AFAgarap** [comment]
Oh, good. Glad to help. :)

**Comment by terminator9487** [comment]
@clockzhong  Hi, I met the same problem. How did you solve that problem? Just reinstall the CUDA and CUDnn?  Thanks a lot

**Comment by clockzhong** [comment]
@terminator9487 
Yes, I've not installed CUDnn library. So what I did is just installing both CUDA and CUDnn. They are different libraries, and you also need pay special attention on their versions also. 
It's really a pity that they haven't provided a complete package to setup the tensorflow working environment. 
I think the tensorflow, CUDA, and CUDnn fast development pacing is the reason that they couldn't provide one complete package. These 3 packages developers just keep updating to their latest version in their own developers environment. But any version mismatch or package missing will cause us facing problems. The situation will be better when these 3 packages become stable.

**Comment by abomm** [comment]
I just had this exact same problem. I had to use the above advice and found my libcuda directory with this lost shared object, and in my case I ran:

```bash
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/
```

...and then everything worked for me when I ran my Tensorflow script in `python3.6` .

**Comment by ekchacon** [comment]
@abomm 
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/
It works for me. With CUDA Toolkit 11.2, Tensorflow 2.4.1, cuDNN 11.1 and Python 3.8.
