### ISSUE TITLE
[TensorflowLite GPUDelegate] Outputs NaN Tensors

### ISSUE THREAD

**Issue by Fabian-Ket** [tensorflow/tensorflow#48523]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Android 10 mobile / Windows 10 Desktop
- Mobile device: OnePlus 7T
- Python version: 3.6.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.4.1
- CUDA / cuDNN: CUDA 11.0 / cuDNN 8.0
- TensorFlow Lite version: 2.4.0

**Describe the current behavior**
A tensorflow lite model outsputs NaN tensors if GPUDelegate is used. Only on GPUDelegate, not on CPU, not on NnApiDelegate, not on XNNPack. Specific the tensors demo_class01, demo_class02, demo_class03, demo_class04. If I round the input of the tf.keras.layers.Multiply() layers to 4 digits, NaN output is gone, but performance is then the same on GPU as on CPU. Please look at the standalone code to see the tensor naming. The interessting thing is, that I have to use 4 different output classifications (demo_class01, demo_class02, demo_class03, demo_class04) to produce the NaN tensor output in Android Studio console, if less, constant tensors get printed. It seems like GPUDelegate + Multiply() is numerical instabil if the inputs have a too hight precision. Because if I round the inputs, the NaNs are gone (bit this seems more like a workaround).

Edit:
Another model with 210x210x3 input outputs NaN tensors even with the rounding.

The output printed in Android Studio is the following:
```
demo_class01: [NaN, NaN, NaN, NaN]
demo_class02: [NaN, NaN, NaN, NaN]
demo_class03: [NaN, NaN, NaN, NaN]
demo_class04: [NaN, NaN, NaN, NaN]
```

For rounding I used the following in the "working" model:
```
    def tf_round(x, decimals=0):
        multiplier = tf.constant(10**decimals, dtype=x.dtype)
        return tf.round(x * multiplier) / multiplier
    
    out_relu  = tf_round(out_relu, 4)
    demo_slice01 = tf_round(demo_slice01, 4)
    demo_slice02 = tf_round(demo_slice02, 4)
    demo_slice03 = tf_round(demo_slice03, 4)
    demo_slice04 = tf_round(demo_slice04, 4)
```

**Describe the expected behavior**
Non NaN tensors without extra steps.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Following demo model code:
```
def create_demo():

    demo_ins = tf.keras.layers.Input(shape=(300, 300, 3), name="demo_ins", batch_size=1)
    
    model = tf.keras.applications.MobileNetV2(include_top=False, weights="imagenet", input_shape=(300, 300, 3), 
                                              pooling=None, input_tensor=demo_ins)
    out_relu = model.get_layer(name="out_relu").output
    
    demo_conv01 = tf.keras.layers.Conv2D(4, (3, 3), padding="same", strides=(1, 1), 
                                         kernel_initializer="he_uniform", name="demo_conv01")(out_relu)
    demo_bn01   = tf.keras.layers.BatchNormalization(name="demo_bn01")(demo_conv01)
    demo_softmax01 = tf.keras.layers.Softmax(axis=2, name="a_demo_softmax01")(demo_bn01)
    
    
    demo_slice01 = tf.keras.layers.Lambda(lambda x: x[:, :, :, 0], name="demo_slice01")(demo_softmax01)
    demo_slice02 = tf.keras.layers.Lambda(lambda x: x[:, :, :, 1], name="demo_slice02")(demo_softmax01)
    demo_slice03 = tf.keras.layers.Lambda(lambda x: x[:, :, :, 2], name="demo_slice03")(demo_softmax01)
    demo_slice04 = tf.keras.layers.Lambda(lambda x: x[:, :, :, 3], name="demo_slice04")(demo_softmax01)
    
    demo_slice01_reshape = tf.keras.layers.Reshape([10, 10, 1], name="demo_slice01_reshape")(demo_slice01)
    demo_slice02_reshape = tf.keras.layers.Reshape([10, 10, 1], name="demo_slice02_reshape")(demo_slice02)
    demo_slice03_reshape = tf.keras.layers.Reshape([10, 10, 1], name="demo_slice03_reshape")(demo_slice03)
    demo_slice04_reshape = tf.keras.layers.Reshape([10, 10, 1], name="demo_slice04_reshape")(demo_slice04)
    
    demo_mul01 = tf.keras.layers.Multiply(name="w_demo_mul01")([out_relu, demo_slice01_reshape])
    demo_mul02 = tf.keras.layers.Multiply(name="x_demo_mul02")([out_relu, demo_slice02_reshape])
    demo_mul03 = tf.keras.layers.Multiply(name="y_demo_mul03")([out_relu, demo_slice03_reshape])
    demo_mul04 = tf.keras.layers.Multiply(name="z_demo_mul04")([out_relu, demo_slice04_reshape])
    
    demo_block_conv01 = tf.keras.layers.Conv2D(3, (3, 3), padding="same", strides=(1, 1), 
                                                   kernel_initializer="he_uniform", name="demo_block_conv01")
    demo_block_bn01   = tf.keras.layers.BatchNormalization(name="demo_block_bn01")
    demo_block_relu01 = tf.keras.layers.ReLU(name="demo_block_relu01")
    demo_block_flatten = tf.keras.layers.Flatten(name="demo_block_flatten")
    demo_block_softmax01 = tf.keras.layers.Dense(4, activation="softmax", name="demo_block_softmax01")
    
    def block(inputs):
        
        conv01  = demo_block_conv01(inputs)
        bn01    = demo_block_bn01(conv01)
        relu01  = demo_block_relu01(bn01)
        flatten = demo_block_flatten(relu01)
        softmax01 = demo_block_softmax01(flatten)
        
        return softmax01
        
    demo_class01 = tf.keras.layers.Layer(name="b_demo_class01")(block(demo_mul01))
    demo_class02 = tf.keras.layers.Layer(name="c_demo_class02")(block(demo_mul02))
    demo_class03 = tf.keras.layers.Layer(name="d_demo_class03")(block(demo_mul03))
    demo_class04 = tf.keras.layers.Layer(name="e_demo_class04")(block(demo_mul04))
    
    model = tf.keras.models.Model(
        inputs=[model.input], 
        outputs=[demo_softmax01, 
                 demo_class01, demo_class02, demo_class03, demo_class04, 
                 demo_mul01, demo_mul02, demo_mul03, demo_mul04]
    )
    
    return model 
```

Following tfLite convert code:
```
model = create_demo()
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open("demo.tflite", 'wb') as f:
    f.write(tflite_model)
```

Following tfLite Interpreter code:
```
Interpreter.Options opt = new Interpreter.Options();
CompatibilityList compatList = new CompatibilityList();

GpuDelegate.Options gpuOptions = compatList.getBestOptionsForThisDevice();
GpuDelegate delegate = new GpuDelegate(gpuOptions);

opt.addDelegate(delegate);
interpreter = new Interpreter(modelByteBuffer, opt);
```

Edit02:

Maybe it helps, the tensorflow lite output map should be the following:
```
Map<Integer, Object> outputMap = new HashMap<>();

float[][][][] aMap = new float[1][10][10][4];

float[][][][] demo_mul01 = new float[1][10][10][1280];
float[][][][] demo_mul02 = new float[1][10][10][1280];
float[][][][] demo_mul03 = new float[1][10][10][1280];
float[][][][] demo_mul04 = new float[1][10][10][1280];

float[][] demo_class01 = new float[1][4];
float[][] demo_class02 = new float[1][4];
float[][] demo_class03 = new float[1][4];
float[][] demo_class04 = new float[1][4];

outputMap.put(0, aMap);

outputMap.put(1, demo_class01);
outputMap.put(2, demo_class02);
outputMap.put(3, demo_class03);
outputMap.put(4, demo_class04);

outputMap.put(5, demo_mul01);
outputMap.put(6, demo_mul02);
outputMap.put(7, demo_mul03);
outputMap.put(8, demo_mul04);
```

**Other info / logs** 
I tryed differnet Tensorflow versions different Converter options like:

```
converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
```

With this options the NaNs are gone but the performance impact is so strong, I could just use the old converter and use the mobile CPU.

I attached a converted TensorflowLite NaN model created with the code above.
[demo_issue.zip](https://github.com/tensorflow/tensorflow/files/6311102/demo_issue.zip)

**Comment by abattery** [comment]
@impjdi could you take a look?

**Comment by impjdi** [comment]
Are you running this in FP16 mode?

**Comment by Fabian-Ket** [comment]
If it is the default, yes. How do you set the running mode?

**Comment by impjdi** [comment]
Nah, that's just the stage when you create the model.  There's another mode for the actual runtime.  Given that you use:

```
GpuDelegate.Options gpuOptions = compatList.getBestOptionsForThisDevice();
```

which is implemented as

```
    return new GpuDelegate.Options();
```

which takes the default values:

```
    boolean precisionLossAllowed = true;
    boolean quantizedModelsAllowed = true;
    int inferencePreference = INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER;
```

I think it's running at FP16 mode.  If you set `precisionLossAllowed` to `false` and the problem is gone, that means that your model is not numerically stable enough to be run at FP16.

**Comment by Fabian-Ket** [comment]
I already tried with:

```
Interpreter.Options opt = new Interpreter.Options();
CompatibilityList compatList = new CompatibilityList();

GpuDelegate.Options gpuOptions = compatList.getBestOptionsForThisDevice();
gpuOptions.setPrecisionLossAllowed(false);

GpuDelegate delegate = new GpuDelegate(gpuOptions);
opt.addDelegate(delegate);

Interpreter interpreter= new Interpreter(modelByteBuffer, opt);
```

also tried to play around with:

```
gpuOptions.setQuantizedModelsAllowed(...)
gpuOptions.setInferencePreference(...)
```

Nothing changed I still get demo_classXX: [NaN, NaN, NaN, NaN]

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
