### ISSUE TITLE
macbook pro GPU version, successfully opened CUDA library, but not found the GPU

### ISSUE THREAD

**Issue by wwxFromTju** [tensorflow/tensorflow#4858]
Hi ALL:
I am a chinese student, so may be English is bas. Sorry.
now I use the tensorflow GPU version. I user the pip to down the python3 GPU version, and down the all about the GPU file.
But i can successfully opened CUDA library, but not found the GPU, like this:
`In [1]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.dylib locally
`

`
In [2]: tf.Session()
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: wangxiaoweideWindows.local
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: wangxiaoweideWindows.local
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: 346.3.6
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: Invalid argument: expected %d.%d or %d.%d.%d form for driver version; got ""
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
`

and I find the I can't deviceQuery the GPU:

`➜  ~ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Apr_11_13:23:40_CDT_2016
Cuda compilation tools, release 7.5, V7.5.26
`

`
➜  ~ ~/cuda-samples/bin/x86_64/darwin/release/deviceQuery
/Users/codeMan/cuda-samples/bin/x86_64/darwin/release/deviceQuery Starting...
 CUDA Device Query (Runtime API) version (CUDART static linking)
cudaGetDeviceCount returned 38
-> no CUDA-capable device is detected
Result = FAIL`

now I use the mac os, and Xcode8, how to solve it ?

**Comment by yaroslavvb** [comment]
If you can't run deviceQuery, then the problem is not with TensorFlow. Perhaps your computer does not have a CUDA-capable GPU

**Comment by wwxFromTju** [comment]
@yaroslavvb 
My macbook pro 2014 have NVIDIA 750M, and I find the mac GPU course to download the library.
so how to solve? I don't know. THX

**Comment by wwxFromTju** [comment]
OK. I solve, is easy:NVIDIA CUDA 7.5 FOR MAC OS X RELEASE
download this, then OK!!!!!!
http://www.nvidia.com/object/macosx-cuda-7.5.30-driver.html

@yaroslavvb THX!

**Comment by jart** [comment]
Glad you solved the problem @wwxFromTju. We hope TensorFlow serves you well in your studies. If you have any other questions in the future, the [Stack Overflow](http://stackoverflow.com/questions/tagged/tensorflow) community is a better forum for support. We try to keep this issue tracker focused on bugs and feature requests.

**Comment by CosmosShadow** [comment]
Thanks, That helps me.

**Comment by laventura** [comment]
Hello @jart @wwxFromTju 

I have similar problem as yours.:

**_Any help appreciated!! thanks!_**

**"libcuda reported version is: 310.42.25; 
kernel reported version is: Invalid argument: expected %d.%d or %d.%d.%d form for driver version; got ""**
My detailed problem is here: https://github.com/tensorflow/tensorflow/issues/2882

In brief: CUDA Driver (from Apple > System Preferences > CUDA)
```
CUDA Driver Version: 8.0.57
GPU Driver Version: 10.10.14 310.42.25f02
```

My setup:
I'm on Mac OS X 10.11.6. Installed CUDA 8, and CUDNN 5.1. I've followed the install instructions from official TF site. (as of Jan 23, 2017)

```
./deviceQuery 
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 38
-> no CUDA-capable device is detected
Result = FAIL
```

**Comment by yaroslavvb** [comment]
@laventura sounds like you don't have CUDA-capable device (if your video card is AMD, it is not CUDA-capable)

**Comment by laventura** [comment]
@yaroslavvb 

Here are the reports from System Report:  _(About This Mac > System Report > Graphics )_

So - _does this support CUDA or does it not? I 'm at a loss to figure this out now._ 

```
NVIDIA GeForce GT 750M:
  Chipset Model:	NVIDIA GeForce GT 750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2048 MB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0fe9
  Revision ID:	0x00a2
  ROM Revision:	3776
  gMux Version:	4.0.8 [3.2.8]
  Displays:
Color LCD:
  Display Type:	Retina LCD
  Resolution:	2880 x 1800 Retina
  Retina:	Yes
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Built-In:	Yes

---- 
Intel Iris Pro:
  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0d26
  Revision ID:	0x0008
  gMux Version:	4.0.8 [3.2.8]
```

**Comment by yaroslavvb** [comment]
Yes it should. It seems your problem is outside of tensorflow since devicequery fails, maybe Nvidia support forums have tips

**Comment by laventura** [comment]
I've been running between CUDA/GPU and Tensorflow issues... 😩😩

**_TensorFlow on GPU worked for me earlier,_** with an older version of TensorFlow (0.10? cant recall) and   perhaps older CUDA too (also can't recall) 

I've seen the networks train faster with this same GPU... 

Unfortunately, upgrading TF led to many of these errors.. and now I can't figure out if it is GPU/CUDA problem or TF.

Of course, nobody in the Nvidia DevTalk forums have had similar issues... 😟

[The older problem was that TF couldn't use all the GPU memory....]

(See here: https://github.com/aymericdamien/TensorFlow-Examples/issues/38#issuecomment-265595019)

**Comment by yaroslavvb** [comment]
`./deviceQuery` failing indicates this is not a TF problem, but a general GPU problem

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 5256 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:48764 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWmia-0032g0-Op
	for greg@biomassiv.es; Thu, 26 Jan 2017 10:16:12 -0600
Date: Wed, 25 Jan 2017 13:25:14 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485379514;
	bh=6z/AkFDojFc8QDhBXTHoeUbzRf+AWSxwJCLdajE99mk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iYzUvQiiIlFeLCLDQslc/bdByhGKReWQ0ncUmNl/48FWVUBdFdEHDGYU83YoU3dzU
	 PLH5UC7CG6J9Kbr99g7NxOZsdeH/BDN5DxKCL+3txE83r0vj5shuDzcVgOwwn2Du6R
	 pp9I1AUWA3yEjsTO2CxyxCXetJ8lH3QAb0sbrHrw=

**Comment by vrv** [comment]
@biomassives you seem to have started spamming github threads, so I have blocked you.  Please contact us offline once you've fixed whatever you're doing to stop spamming threads.

**Comment by richardxiong** [comment]
@laventura hello, I'm running exactly the same problem as you, with `./deviceQuery` failing. Did you solve that problem? Thanks!

**Comment by richardxiong** [comment]
@laventura Hello, have you solved your problem? I have run into exactly the same problem, with `./deviceQuery` failing indicates the CUDA-capable device, but I follow the instruction on [here](https://gist.github.com/jganzabal/8e59e3b0f59642dd0b5f2e4de03c7687). Thanks!
