### ISSUE TITLE
ValueError: Found two metrics with the same name: Dense_xx Accuracy. TensorFlow 2.4

### ISSUE THREAD

**Issue by hasanabs** [tensorflow/tensorflow#48690]
**System information**
- OS: Linux Ubuntu 20.04 as well as Windows 10
- TensorFlow version (use command below): 2.4.1
- Python version: 3.79
- CUDA version: 11.2
- GPU model and memory: RTX 3060

**Issue**
Previously I upgraded my Tensorflow to 2.4.
I got an error message like "ValueError: Found two metrics with the same name: dense_xx_accuracy". 
Then, I downgraded my TF to 2.1 and everything is working fine again.

**Log**
2021-04-22 14:36:23.743926: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Nt.2 Np.2 Nr.4 M.4 RIS.4
2021-04-22 14:36:24.521915: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-22 14:36:24.522409: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-04-22 14:36:24.526771: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-22 14:36:24.526787: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: user-system-sharing
2021-04-22 14:36:24.526791: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: user-system-sharing
2021-04-22 14:36:24.526838: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.67.0
2021-04-22 14:36:24.526851: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.67.0
2021-04-22 14:36:24.526855: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.67.0
2021-04-22 14:36:24.526974: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-22 14:36:24.527331: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-22 14:36:24.605219: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2021-04-22 14:36:24.605238: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2021-04-22 14:36:24.607251: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2021-04-22 14:36:24.653744: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-04-22 14:36:24.654329: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2799925000 Hz
Epoch 1/50
Traceback (most recent call last):

  File "/home/user/Documents/Python/RIS/RIS-DNN_Cosine_Training.py", line 110, in <module>
    model.fit(np.transpose(D),train_labels_app, validation_split=0.25, batch_size=512, epochs=50, callbacks=[callbacks_list, tensorboard], shuffle=True)

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)

  File "/usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)

ValueError: in user code:

    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:758 train_step
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:387 update_state
        self.build(y_pred, y_true)
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:329 build
        self._set_metric_names()
    /usr/local/anaconda3/envs/AI/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:349 _set_metric_names
        m._name))

    ValueError: Found two metrics with the same name: dense_3_accuracy

**Comment by Saduf2019** [comment]
@hasanabs 
Please share code such that we could replicate the error reported or a colab gist with the code and error.

Based on the error logs, you may refer to this link an let us know: [link](https://stackoverflow.com/questions/62905851/valueerror-found-two-metrics-with-the-same-name-recall),

**Comment by hasanabs** [comment]
> @hasanabs
> Please share code such that we could replicate the error reported or a colab gist with the code and error.
> 
> Based on the error logs, you may refer to this link and let us know: [link](https://stackoverflow.com/questions/62905851/valueerror-found-two-metrics-with-the-same-name-recall),

Yes this is my training file and its function
[B-DNN_Training.py](https://github.com/hasanabs/B_DNN/blob/main/B-DNN_Training.py)
[fungsi_dnn.py](https://github.com/hasanabs/B_DNN/blob/main/fungsi_dnn.py)

**Comment by hasanabs** [comment]
I found the main problem, it turns out that in TF 2.4 there is a slight change in the way to call accuracy but for sparse_categorical_crossentropy

This is the change needed for solve this problem. First, delete the line I commented on, then define loss and matrices as in the green area
![Screenshot from 2021-04-30 10-25-33](https://user-images.githubusercontent.com/26079804/116641799-0a717000-a9a0-11eb-83bc-0f63c3ddf07d.png)
