### ISSUE TITLE
Obsolete NVIDIA driver check for CUDA 11.2

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#48722]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installed from: binary
- TensorFlow version: 2.5.0
- Python version: 3.8
- CUDA/cuDNN version: 11.2/8.1.1 (Docker image: `tensorflow/tensorflow:2.5.0-gpu`)

**Describe the current behavior**

```bash
docker run --gpus all --entrypoint python tensorflow/tensorflow:2.5.0-gpu -c "import tensorflow as tf; tf.zeros([50])"
```

When running the Docker command above and GPU driver 455 installed on the host, the following error message is logged:

> `E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`
> `I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: f7b7a8f85319`
> `I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: f7b7a8f85319`
> `I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.73.1`
> `I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 455.32.0`
> `E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 455.32.0 does not match DSO version 460.73.1 -- cannot find working devices in this configuration`

However, this driver version check is no longer accurate. Starting with CUDA 11.1, minor CUDA versions no longer require a driver update. So all CUDA 11.x versions are compatible with driver versions >= 450.

This change is referred as the "CUDA Enhanced Compatibility" in the [CUDA Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) guide.

**Describe the expected behavior**

TensorFlow binaries should comply with the [CUDA Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) guide. So TensorFlow with CUDA 11.2 should work with GPU drivers >= 450 instead of >= 460.

See in particular the Table 1 that specifies the driver requirement for each CUDA version:

CUDA Toolkit | Linux x86_64 Required Driver Version
-- | --
CUDA 11.3 | >= 450.80.02
CUDA 11.2 | >= 450.80.02
CUDA 11.1 (11.1.0) | >= 450.80.02
CUDA 11.0 (11.0.3) | >= 450.36.06
CUDA 10.2 (10.2.89) | >= 440.33
CUDA 10.1 (10.1.105) | >= 418.39
CUDA 10.0 (10.0.130) | >= 410.48

**Comment by guillaumekln** [comment]
I updated the issue to clarify it was executed in a Docker container and the logs also report an error from `cuInit`.

**Comment by sanjoy** [comment]
I believe we print the warning about driver/DSO version mismatch only if `cuInit` fails.  I.e. you're seeing the warning because there was a definite failure, though the message could be incorrect about the root cause.

I don't see why `cuInit` itself fails -- as you said, by the docs, 11.2 should work fine with 455.  Do things work ok if you upgrade the host driver to 460?

**Comment by guillaumekln** [comment]
I confirm that it works with driver 460 but not 455. I tested with the official TensorFlow 2.5.0 GPU Docker image:

```
docker run --gpus all --entrypoint python tensorflow/tensorflow:2.5.0-gpu -c "import tensorflow as tf; tf.zeros([50])"
```

With driver 455.45.01 the GPU is not detected and the driver mismatch is logged:

```
I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 538e7c2fb724
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 538e7c2fb724
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.73.1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 455.45.1
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 455.45.1 does not match DSO version 460.73.1 -- cannot find working devices in this configuration
```

With driver 460.73.01 the GPU is successfully detected:

```
I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:1e.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
```

**Comment by sanjoy** [comment]
@nluehr Any idea (TLDR: `cuInit` fails with CUDA 11.2 and 455 and we don't know why).

**Comment by guillaumekln** [comment]
Note that we only mentioned driver 455 here, but there is probably the same error for all drivers in range >=450,<460 even though they should be compatible with CUDA 11.2.

**Comment by nluehr** [comment]
I am unable to reproduce the failure on my machine with Ubuntu 20.04 and 455.45.01 running the tensorflow/tensorflow:2.5.0-gpus Docker image. On a failing system what is the output of `nvidia-smi` within the container?

**Comment by guillaumekln** [comment]
Thanks for the feedback. Here's the `nvidia-smi` output within the container:

```text
$ docker run --gpus all --entrypoint nvidia-smi tensorflow/tensorflow:2.5.0-gpu
Thu Jun 17 08:09:26 2021 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   24C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

For reference, this was run on a fresh `g4dn.xlarge` EC2 instance with "Deep Learning Base AMI (Ubuntu 18.04) Version 39.0". I just ran the following initialization steps before running the above Docker command:

* Uninstall current GPU driver
* Reboot
* Install GPU driver 455.45.01
* Reboot

**Comment by guillaumekln** [comment]
This is probably a nvidia-docker issue, not a TensorFlow issue. It works after manually changing the `libcuda.so` simlink within the container:

```bash
ln -sf /usr/lib/x86_64-linux-gnu/libcuda.so.455.45.01 /usr/lib/x86_64-linux-gnu/libcuda.so.1
```

**Comment by guillaumekln** [comment]
Note: extending the TensorFlow Docker image and removing the package `cuda-compat-11-2` is also a way to workaround this issue.
