### ISSUE TITLE
'File' value has no field or method 'append' in in _prune_relocatable_code rule @nccl_archive//:device_pruned:

### ISSUE THREAD

**Issue by Davidy22** [tensorflow/tensorflow#48874]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mint 20.1, Ubuntu 20.04 base
- TensorFlow installed from (source or binary): Source
- TensorFlow version: origin/r2.5
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: Regular version installed via pip, but that's not the one with the issue
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 9.3
- CUDA/cuDNN version: CUDA 11.3, cuDNN 8
- GPU model and memory: GeForce GT 750M, Driver Version: 418.113
- Clang 12
- NCCL 2.9.6 installled with the local installer off nvidia site

Configure options were CUDA only, CUDA and cuDNN autodetected, python 3.8, GPU capability 3.0, using clang without experimental download, default flags, no android. Running the following line I copied off an online guide:

`bazel build --config=opt --config=cuda --local_resources 2048,.5,1.0 //tensorflow/tools/pip_package:build_pip_package`

I got:
```
WARNING: The following configs were expanded more than once: [cuda_clang, cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'local_resources' is deprecated: --local_resources is deprecated. Please use --local_ram_resources and --local_cpu_resources instead.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=190
INFO: Reading rc options for 'build' from /home/davidoso/Downloads/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/davidoso/Downloads/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/davidoso/Downloads/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3.8/dist-packages --python_path=/usr/bin/python3 --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.3 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.0 --action_env LD_LIBRARY_PATH=:/usr/local/cuda-11.3/lib64 --config=cuda_clang --action_env CLANG_CUDA_COMPILER_PATH=/usr/local/bin/clang --config=cuda_clang
INFO: Found applicable config definition build:short_logs in file /home/davidoso/Downloads/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/davidoso/Downloads/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda_clang in file /home/davidoso/Downloads/tensorflow/.bazelrc: --config=cuda --repo_env TF_CUDA_CLANG=1 --@local_config_cuda//:cuda_compiler=clang
INFO: Found applicable config definition build:cuda in file /home/davidoso/Downloads/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:cuda_clang in file /home/davidoso/Downloads/tensorflow/.bazelrc: --config=cuda --repo_env TF_CUDA_CLANG=1 --@local_config_cuda//:cuda_compiler=clang
INFO: Found applicable config definition build:cuda in file /home/davidoso/Downloads/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file /home/davidoso/Downloads/tensorflow/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:cuda in file /home/davidoso/Downloads/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:linux in file /home/davidoso/Downloads/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/davidoso/Downloads/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Build options --@local_config_cuda//:cuda_compiler, --action_env, and --repo_env have changed, discarding analysis cache.
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/davidoso/Downloads/tensorflow/WORKSPACE:23:14: in <toplevel>
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace0.bzl:105:34: in workspace
  /home/davidoso/.cache/bazel/_bazel_davidoso/3a3497116f85579b213da4e18ca6049d/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /home/davidoso/.cache/bazel/_bazel_davidoso/3a3497116f85579b213da4e18ca6049d/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: /home/davidoso/.cache/bazel/_bazel_davidoso/3a3497116f85579b213da4e18ca6049d/external/nccl_archive/BUILD.bazel:54:17: in _prune_relocatable_code rule @nccl_archive//:device_pruned: 
Traceback (most recent call last):
	File "/home/davidoso/.cache/bazel/_bazel_davidoso/3a3497116f85579b213da4e18ca6049d/external/local_config_nccl/build_defs.bzl", line 207, column 15, in _prune_relocatable_code_impl
		output.append(outputs)
Error: 'File' value has no field or method 'append'
INFO: Repository pybind11 instantiated at:
  /home/davidoso/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:1068:20: in _tf_repositories
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository mkl_dnn_v1 instantiated at:
  /home/davidoso/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:180:20: in _tf_repositories
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository cython instantiated at:
  /home/davidoso/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:856:20: in _tf_repositories
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository jsoncpp_git instantiated at:
  /home/davidoso/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:693:20: in _tf_repositories
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
INFO: Repository cudnn_frontend_archive instantiated at:
  /home/davidoso/Downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:1118:21: in workspace
  /home/davidoso/Downloads/tensorflow/tensorflow/workspace2.bzl:157:20: in _tf_repositories
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:112:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/davidoso/Downloads/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@nccl_archive//:device_pruned' failed
INFO: Elapsed time: 679.978s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (363 packages loaded, 16248 targets configured)

```

I specifically notice the one error on the nccl part, copied below to highlight it

```
ERROR: /home/davidoso/.cache/bazel/_bazel_davidoso/3a3497116f85579b213da4e18ca6049d/external/nccl_archive/BUILD.bazel:54:17: in _prune_relocatable_code rule @nccl_archive//:device_pruned: 
Traceback (most recent call last):
	File "/home/davidoso/.cache/bazel/_bazel_davidoso/3a3497116f85579b213da4e18ca6049d/external/local_config_nccl/build_defs.bzl", line 207, column 15, in _prune_relocatable_code_impl
		output.append(outputs)
Error: 'File' value has no field or method 'append'
```

**Comment by saikumarchalla** [comment]
@Davidy22  Could you please try using CUDA 11.2 instead of 11.3 on a new virtual environment and let us know if you facing the issues still. Thanks!

**Comment by saikumarchalla** [comment]
Duplicate issue: #48652

**Comment by Davidy22** [comment]
Followed the solution that was taken in the attached report, replaced

`output.append(outputs)`

with

`outputs.append(output)`

In the offending file and it worked, might make a pull request some time if i got the time to find where this gets generated

**Comment by saikumarchalla** [comment]
@Davidy22  Please go ahead and close the issue since the issue was resolved for you. Please feel free to submit a PR to fix the  issue. Thanks!

**Comment by bermeitinger-b** [comment]
This is not fixed in 2.5.1.

**Comment by Davidy22** [comment]
I could have sworn I saw a pull request for this. The fix was just one line too. I can reopen and open a pull request.

**Comment by rthadur** [comment]
This is available in latest versions https://github.com/tensorflow/tensorflow/blob/master/third_party/nccl/build_defs.bzl.tpl#L207 , closing this issue . Thank you
