### ISSUE TITLE
virtualenv pip3 install fails

### ISSUE THREAD

**Issue by ashwin** [tensorflow/tensorflow#4894]
I am trying to install TensorFlow in virtualenv using Python 3.4.

I did:
```
$ pyvenv-3.4 --system-site-packages tensorflow
$ source tensorflow/bin/activate
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp34-cp34m-linux_x86_64.whl
$ pip3 install --upgrade $TF_BINARY_URL
```

The pip3 install ends in this error:

```
Installing collected packages: tensorflow, protobuf, wheel, numpy, six, setuptools                                                                                                                                                                                        │
Cleaning up...                                                                                                                                                                                                                                                            │
  Removing temporary dir /tmp/pip_build_ashwin...                                                                                                                                                                                                                         │
Exception:                                                                                                                                                                                                                                                                │
Traceback (most recent call last):                                                                                                                                                                                                                                        │
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main                                                                                                                                                                                             │
    status = self.run(options, args)                                                                                                                                                                                                                                      │
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run                                                                                                                                                                                         │
    requirement_set.install(install_options, global_options, root=options.root_path)                                                                                                                                                                                      │
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install                                                                                                                                                                                                 │
    requirement.install(install_options, global_options, *args, **kwargs)                                                                                                                                                                                                 │
  File "/usr/lib/python3/dist-packages/pip/req.py", line 672, in install                                                                                                                                                                                                  │
    self.move_wheel_files(self.source_dir, root=root)                                                                                                                                                                                                                     │
  File "/usr/lib/python3/dist-packages/pip/req.py", line 902, in move_wheel_files                                                                                                                                                                                         │
    pycompile=self.pycompile,                                                                                                                                                                                                                                             │
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 206, in move_wheel_files                                                                                                                                                                                       │
    clobber(source, lib_dir, True)                                                                                                                                                                                                                                        │
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 175, in clobber                                                                                                                                                                                                │
    os.makedirs(dest)                                                                                                                                                                                                                                                     │
  File "/usr/lib/python3.4/os.py", line 237, in makedirs                                                                                                                                                                                                                  │
    mkdir(name, mode)                                                                                                                                                                                                                                                     │
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.4/site-packages' 
```

Why is pip3 install inside a virtual environment trying to write in `/usr/lib/python3.4`? How to make this install work?

Operating System: Ubuntu 14.04
Installed version of CUDA and cuDNN: CUDA 7.5 and cuDNN 5
```
lrwxrwxrwx 1 root root   16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcublas.so -> libcublas.so.7.5                                                                                                                                                                       │
lrwxrwxrwx 1 root root   19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcublas.so.7.5 -> libcublas.so.7.5.18                                                                                                                                                                │
-rwxr-xr-x 1 root root  23M Aug 15  2015 /usr/local/cuda-7.5/lib64/libcublas.so.7.5.18                                                                                                                                                                                    │
-rw-r--r-- 1 root root  28M Aug 16  2015 /usr/local/cuda-7.5/lib64/libcublas_device.a                                                                                                                                                                                     │
-rw-r--r-- 1 root root  27M Aug 16  2015 /usr/local/cuda-7.5/lib64/libcublas_static.a                                                                                                                                                                                     │
-rw-r--r-- 1 root root 316K Aug 16  2015 /usr/local/cuda-7.5/lib64/libcudadevrt.a                                                                                                                                                                                         │
lrwxrwxrwx 1 root root   16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5                                                                                                                                                                       │
lrwxrwxrwx 1 root root   19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18                                                                                                                                                                │
-rwxr-xr-x 1 root root 375K Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18                                                                                                                                                                                    │
-rw-r--r-- 1 root root 704K Aug 16  2015 /usr/local/cuda-7.5/lib64/libcudart_static.a                                                                                                                                                                                     │
lrwxrwxrwx 1 root root   15 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcufft.so -> libcufft.so.7.5                                                                                                                                                                         │
lrwxrwxrwx 1 root root   16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcufftw.so -> libcufftw.so.7.5                                                                                                                                                                       │
lrwxrwxrwx 1 root root   19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcufftw.so.7.5 -> libcufftw.so.7.5.18                                                                                                                                                                │
-rwxr-xr-x 1 root root 438K Aug 15  2015 /usr/local/cuda-7.5/lib64/libcufftw.so.7.5.18                                                                                                                                                                                    │
-rw-r--r-- 1 root root  42K Aug 16  2015 /usr/local/cuda-7.5/lib64/libcufftw_static.a                                                                                                                                                                                     │
lrwxrwxrwx 1 root root   18 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcufft.so.7.5 -> libcufft.so.7.5.18                                                                                                                                                                  │
-rwxr-xr-x 1 root root 107M Aug 15  2015 /usr/local/cuda-7.5/lib64/libcufft.so.7.5.18                                                                                                                                                                                     │
-rw-r--r-- 1 root root 110M Aug 16  2015 /usr/local/cuda-7.5/lib64/libcufft_static.a                                                                                                                                                                                      │
lrwxrwxrwx 1 root root   17 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcuinj64.so -> libcuinj64.so.7.5                                                                                                                                                                     │
lrwxrwxrwx 1 root root   20 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcuinj64.so.7.5 -> libcuinj64.so.7.5.18                                                                                                                                                              │
-rwxr-xr-x 1 root root 5.5M Aug 15  2015 /usr/local/cuda-7.5/lib64/libcuinj64.so.7.5.18                                                                                                                                                                                   │
-rw-r--r-- 1 root root 1.6M Aug 16  2015 /usr/local/cuda-7.5/lib64/libculibos.a                                                                                                                                                                                           │
lrwxrwxrwx 1 root root   16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcurand.so -> libcurand.so.7.5                                                                                                                                                                       │
lrwxrwxrwx 1 root root   19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcurand.so.7.5 -> libcurand.so.7.5.18                                                                                                                                                                │
-rwxr-xr-x 1 root root  50M Aug 15  2015 /usr/local/cuda-7.5/lib64/libcurand.so.7.5.18                                                                                                                                                                                    │
-rw-r--r-- 1 root root  50M Aug 16  2015 /usr/local/cuda-7.5/lib64/libcurand_static.a                                                                                                                                                                                     │
lrwxrwxrwx 1 root root   18 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcusolver.so -> libcusolver.so.7.5                                                                                                                                                                   │
lrwxrwxrwx 1 root root   21 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcusolver.so.7.5 -> libcusolver.so.7.5.18                                                                                                                                                            │
-rwxr-xr-x 1 root root  36M Aug 15  2015 /usr/local/cuda-7.5/lib64/libcusolver.so.7.5.18                                                                                                                                                                                  │
-rw-r--r-- 1 root root  16M Aug 16  2015 /usr/local/cuda-7.5/lib64/libcusolver_static.a                                                                                                                                                                                   │
lrwxrwxrwx 1 root root   18 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcusparse.so -> libcusparse.so.7.5                                                                                                                                                                   │
lrwxrwxrwx 1 root root   21 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcusparse.so.7.5 -> libcusparse.so.7.5.18                                                                                                                                                            │
-rwxr-xr-x 1 root root  36M Aug 15  2015 /usr/local/cuda-7.5/lib64/libcusparse.so.7.5.18                                                                                                                                                                                  │
-rw-r--r-- 1 root root  43M Aug 16  2015 /usr/local/cuda-7.5/lib64/libcusparse_static.a
```

**Comment by jart** [comment]
Try putting the word `sudo` before that last command and it should work. If not, please let us know.

**Comment by ashwin** [comment]
@jart Using `sudo` would install the files outside the virtual environment in the root filesystem. Wouldn't that invalidate the reason of using virtualenv in the first place?

**Comment by jart** [comment]
I failed to notice the pyvenv-3.4 command. In that case, this is probably a bug in pip. The backtrace seems to trace only into pip, which seems to be trying to create a folder in your system directory, even though the virtualenv is activated.

**Comment by ashwin** [comment]
My pip3 is v1.5.4 on Ubuntu 14.04. Since this is a LTS version of Ubuntu, a large number of folks might be having this same error. Is the error reproducible on your computer?

**Comment by jart** [comment]
I just installed TensorFlow using the commands you provided above on my Goobuntu 14.04 LTS workstation with pip3 v1.5.4 with python3.4 for both CPU and GPU and it worked. I'm sorry I wish I could help but I can't reproduce this.

**Comment by metropt** [comment]
The same problem here!

**Comment by alexeieleusis** [comment]
I tried this and finished without errors, I don't know yet if it works https://stackoverflow.com/a/38088879/224255

tl;dr add `--user` parameter to the `install` command: `pip3 install tensorflow --user`

**Comment by idrismunir** [comment]
@alexeieleusis your suggestion works for me. Thanks
