### ISSUE TITLE
Tensorflow fails to find GPU device (CUDA 8.0)

### ISSUE THREAD

**Issue by maxim5** [tensorflow/tensorflow#4895]
- Operating System: Ubuntu 16.04
- Installed version of CUDA and cuDNN: CUDA 8.0.27, cuDNN 5.1.5
```
$ ls ~/bin/cuda-8.0/lib64/libcud*
/home/maxim/bin/cuda-8.0/lib64/libcudadevrt.a    /home/maxim/bin/cuda-8.0/lib64/libcudart.so.8.0.27  /home/maxim/bin/cuda-8.0/lib64/libcudnn.so.5
/home/maxim/bin/cuda-8.0/lib64/libcudart.so      /home/maxim/bin/cuda-8.0/lib64/libcudart_static.a   /home/maxim/bin/cuda-8.0/lib64/libcudnn.so.5.1.5
/home/maxim/bin/cuda-8.0/lib64/libcudart.so.8.0  /home/maxim/bin/cuda-8.0/lib64/libcudnn.so          /home/maxim/bin/cuda-8.0/lib64/libcudnn_static.a
```
`nvidia-smi` shows the GPU.
- Environment variables:
```
declare -x CUDA_HOME="/home/maxim/bin/cuda-8.0"
declare -x PATH="/home/maxim/bin/anaconda2/bin:/home/maxim/bin/cuda-8.0/bin:/home/maxim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
declare -x LD_LIBRARY_PATH="/home/maxim/bin/cuda-8.0/lib64:"
``` 
- Tensorflow version: 0.10.0rc0 (installed by Anaconda)
- Note that on the same machine Theano _works perfectly_:
```
$ python theano_check1.py 
Using gpu device 0: GeForce GTX 960M (CNMeM is disabled, cuDNN 5105)
```

But Tensorflow does not:
```
Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
```

**Comment by yaroslavvb** [comment]
How did you install TensorFlow? Official binaries (11rc0 and before) don't support CUDA 8.0, only CUDA 7.5

**Comment by maxim5** [comment]
> How did you install TensorFlow?

`conda install tensorflow`
It looks like 0.10.0rc0 is the latest version in Anaconda.
I have also tried 0.11.0rc0 from `pip`, nothing's changed.

> Official binaries (11rc0 and before) don't support CUDA 8.0, only CUDA 7.5

Interesting. The doc says "The GPU version works best with Cuda Toolkit 7.5 and cuDNN v5"

BTW Nvidia lists CUDA Toolkit 7.5 and below under "archived":
https://developer.nvidia.com/cuda-toolkit-archive
And CUDA Toolkit 8.0 is the only version supported for Ubuntu 16.04, so I guess I don't have a workaround to downgrade CUDA.

**Comment by yaroslavvb** [comment]
@maxim5 yeah, I had to downgrade my Ubuntu down from 16.04 in order to get CUDA working

**Comment by maxim5** [comment]
In case anyone has the same problem: tensorflow supports CUDA 8.0, if you build it from sources *and configure accordingly).
The following post worked for me: https://alliseesolutions.wordpress.com/2016/09/08/install-gpu-tensorflow-from-sources-w-ubuntu-16-04-and-cuda-8-0-rc/

The issue is therefore: support CUDA 8.0 out of the box, because it is the primary CUDA version now.

**Comment by jart** [comment]
CUDA 8.0 will be supported soon. Right now we only officially support 7.0 - 7.5. Please see #2559 which is tracking this.
