### ISSUE TITLE
Saver returning paths that cause GetMatchingPaths to go digging around in parent dirs

### ISSUE THREAD

**Issue by osdf** [tensorflow/tensorflow#4913]
Note: This works without problems in 0.10.0rc0 (default pip install-ed according to website).
### Environment info

Operating System:
Ubuntu 15.10

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
-rw-r--r-- 1 root root 189170 Jan  1  2016 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Jan  1  2016 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Jan  1  2016 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Jan  1  2016 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Jan  1  2016 /usr/local/cuda/lib/libcudart_static.a
```

If installed from binary pip package, provide:
1. A link to the pip package you installed. Tried with two packages:
   -  `https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl
     `
   -  `https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcurand.so locally
0.11.0rc0
```
### Logs or other output that would be helpful

Relevant part of error (the file `/tmp/6d7079c109e5_0-saver_853` is supposed to be loaded by `self.saver.restore` (tf.Saver instance), it exists).

```
Parameters according to early stopping: /tmp/6d7079c109e5_0-saver_853
Training finished after 854/854 iterations.
Traceback (most recent call last):
  File "run.py", line 297, in <module>
    run(config)
  File "step.py", line 109, in run
    step(config=config)
  File "step.py", line 237, in  step
    model.fit(dset, config)
  File "model.py", line 210, in fit
    self.saver.restore(self.sess, save_path=early_stop_name)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1360, in restore
    if not file_io.get_matching_files(file_path):
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 254, in get_matching_files
    compat.as_bytes(filename), status)]
  File "/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.PermissionDeniedError: /tmp/systemd-private-a9da6f279d7b4869b7f687b66db5c7dd-rtkit-daemon.service-xozhXc
```

After restarting the computer and re-running the above, the `PermessionDeniedError` now points at `tensorflow.python.framework.errors.PermissionDeniedError: /tmp/systemd-private-bc171111db824721b4f4cec0e0a363ec-systemd-timesyncd.service-MARv8I`

**Comment by jart** [comment]
Is there any chance you might be running into the same issue as #4852?

**Comment by osdf** [comment]
@jart thanks for pointing to the updated #4852. However, I'm not sure if is related to numpy in my case? I see in the log of #4852 that something with `numpy` happens. This is not the case in my code. The model I want to save was stored by TF with `early_stop_name = self.saver.save(self.sess, save_path=_path)`. No numpy involved inbetween this saving and restoring a few lines later. Also, it seems that according to the error message above it wants to access some `systemd` temp file, which it should not try to access.

**Comment by osdf** [comment]
A quick experiment confirmed: If the above `save_path` is something like `~/tmp/` (i.e. in my local home), the problem does not exist. So the global `/tmp` causes problems. `tensorboard` logs into `/tmp` without problems, as additional information.

**Comment by osdf** [comment]
Reading https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/file_io.py#L252, it says `errors.OpError: If there are filesystem / directory listing errors.` So the above error is supposed to happen, if I interpret this correctly. However, it should not, as the `listing error` is concerned with a directory `tensorflow` has no business in dealing with.

**Comment by osdf** [comment]
@jart @rohan100jain Going a bit through the history, this seems to be related to a larger change introduced some time ago here: https://github.com/tensorflow/tensorflow/commit/02adcaeec5f541870750e46ef5b1663bd9b61246#diff-1cc1b8538a5abd0cad0209d2aa34b116R134

**Comment by jart** [comment]
Your most recent comment leads me to suspect this might be related to #4921. Could you please take a look at that?

**Comment by jart** [comment]
I took a closer look. What is the `save_path` you're passing to `self.saver.restore`? If it's a value like `/tmp/foo` then `FileSystem::GetMatchingPaths` is going to go digging around in your /tmp directory. It needs to be a value like `/tmp/foo/bar-?????-of-nnnnn` which is returned by `Saver.save()`. So the `save_path` parameter really should be called `save_pattern`.

**Comment by osdf** [comment]
It is `/tmp/6d7079c109e5_0-saver_853`, returned by `Saver.save()` (though I set this name there, too). So you are saying that it needs to be in a separate directory in `/tmp`, e.g. like `/tmp/6d7079c109e5/`?

**Comment by jart** [comment]
@rohan100jain This one sounds like it could be a file i/o related bug. I'm not sure if it's necessarily related to #4921. Although there does appear to be overlap.

@osdf I'm stating the painfully obvious here, but sudo might be a workaround for the time being.

**Comment by rohan100jain** [comment]
I think for a short term fix, can you make it sub dir? I need to change GetMatchingFiles to ignore some of these permission failures and not throw an error. 

The way get matching files works is that it finds the top level directory that doesn't have a wildcard which is /tmp and then recursively looks into it to find matches. So making a subdir will not only fix this but make this go faster too. 

But I agree that we need to refine the saver / GetMatchingFiles behavior to not do so badly on such cases.

**Comment by osdf** [comment]
Thanks @rohan100jain !

**Comment by rohan100jain** [comment]
I made https://github.com/tensorflow/tensorflow/commit/c15bb7b6f64fbc4bfd19aeccfd8b8df99012b74c 

This should help a bit I think. Hopefully this would mean that the Permission denied error directories aren't being looked at. I'll fix that too now though.

**Comment by osdf** [comment]
Thanks @rohan100jain for your effort!! I resolved the issue now by having a subdirectory with-in `/tmp`, which then is used to write saver objects. Actually, this is much cleaner and easier to handle (just move the whole subdirectory out of `tmp`). Should I close this issue?

**Comment by rohan100jain** [comment]
Actually I would like to fix this entirely (i.e. even without the sub-dir). Could you try that out and let me know if there are still issues?

**Comment by rohan100jain** [comment]
I think this should be fixed now. Closing issue now. Please reopen if you still face problems.
