### ISSUE TITLE
Distributed inception stuck at tf.initialize_all_variables()

### ISSUE THREAD

**Issue by mbz** [tensorflow/tensorflow#4932]
I'm running distributed training of Inception but its behavior is unpredictable and time to time the _**chief**_ node stuck at (I found out the line through adding logs for every line):

```
tensorflow/tensorflow/python/training/session_manager.py:233
sess.run(init_op, feed_dict=init_feed_dict)
```

The `init_op` is assigned to `tf.initialize_all_variables()` in Inception distributed training. As I mentioned, the behavior is random and it only happens time to time.

Has anyone else has this issues?

I'm running the latest version of TF compiled from source + cuda 7.5 + cudnn 5.1.3

**Comment by jart** [comment]
Hey @mrry what are good steps for people to troubleshoot intermittent hanging issues when distributed?

**Comment by yaroslavvb** [comment]
@mbz what if you run it with less threads? (intra_op_parallelism_threads=1, inter_op_parallelism_threads=1). Sometimes it's useful to get a stack trace under `gdb` using `where` or `thread apply all backtrace`. Running it with "-c dbg" compiled version of TensorFlow will give line numbers

**Comment by mrry** [comment]
This sounds like a connectivity issue. The `init_op` itself should be non-blocking, so it's most likely that the chief is having difficulty connecting to one of your PS tasks. (For example, it pings all of the PS tasks at session creation, and will block until it gets a response.)

As Yaroslav suggests, attaching `gdb` and getting a stack trace is probably the best way to get to the bottom of this.

**Comment by mbz** [comment]
Thanks for the reply. I tried setting `intra_op_parallelism_threads=1, inter_op_parallelism_threads=1` but the same issue still happened. Now, I'm working on building a debug build to get gdb running. 

Just to make sure what Derek is saying: so session creation is async and when it get to `sess.run` it blocks till it gets a response back from all the PSs? It would be great if you point me to this part of the code since I only have one PS so this should be easy to trace.

**Comment by mrry** [comment]
@mbz Here's where it would block (on the first `sess.run()` call) in Python: https://github.com/tensorflow/tensorflow/blob/f794cd393b1e7821fcc3cdcee9b6a4400f2540bf/tensorflow/python/client/session.py#L998. Here's where it would block in the C++ runtime: https://github.com/tensorflow/tensorflow/blob/f794cd393b1e7821fcc3cdcee9b6a4400f2540bf/tensorflow/core/distributed_runtime/master.cc#L168.

It's also possible that the chief has made it past these points, and some connection has dropped. We disable fail_fast on the RPCs so gRPC will retry until it gets a response... this means that if a process fails we assume something (e.g. a cluster manager like Kubernetes) will restart the process for us. These might be a little harder to see though, because almost all of the Master->Worker RPCs are asynchronous, but there are various places where a stack trace would be informative.

**Comment by mbz** [comment]
Thanks for the info @mrry. I put some traces here and there and you are exactly correct about the line which the code is waiting. Communication issues can also justify the random behavior of the system.

I also checked the `fail_fast` flag you mentioned. It seems to be False, hardcoded (am I right?). Therefore, the clients should try to reconnect, don't they? Is it possible to log the connection errors? That should help figuring out the issue a little bit.

**Comment by mrry** [comment]
Yes, `fail_fast` should be false, and clients should try to reconnect, so this sounds like a permanent failure. I haven't played much with gRPC logging, but it [appears](https://github.com/grpc/grpc/blob/1a62ec83b7af9c4437164d10fa23197c64542382/src/core/lib/support/log.c#L81) that setting the environment variable `GRPC_VERBOSITY=DEBUG` (or `INFO`) should cause it to print more logs.

**Comment by aselle** [comment]
@mbz, do you have any updates? What's your current status?

**Comment by mbz** [comment]
I'm still working on this. Please keep the bug the open for a few more
days, I will come back with more details and feedbacks.

**Comment by prb12** [comment]
Closing due to lack of activity.

**Comment by mbz** [comment]
Wanted to update (and close) this thread.
It turned out to be a DNS issue on our network.

Thank you for great help :)
