### ISSUE TITLE
Encountered error while starting profiler: Unavailable: CUPTI error: CUPTI could not be loaded or symbol could not be found.

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#49977]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (64bit)
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.15.0
- Python version: `Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)] on win32`
- Installed using virtualenv? pip? conda?: I installed tensorflow-gpu==1.15 inside a conda environment, and this automatically installed cuDNN too, but I had installed manually the Cuda Computing Toolkit and I also added the following environment variables `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin` and `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64`, and there's also this system variable `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0` and `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3` (with different names: yes, I installed 2 versions of the Cuda Computing Toolkit because, after having installed the latest one, v11.3, I realised that TF 1.15 requires version 10.0)
- CUDA/cuDNN version: `cudatoolkit               10.0.130                      0` and `cudnn                     7.6.5                cuda10.0_0`  (shown with `conda list`)
- GPU model and memory: `NVIDIA Quadro RTX 4000 major: 7 minor: 5 memoryClockRate(GHz): 1.545`

**Describe the problem**

I am getting the following errors

```
name: NVIDIA Quadro RTX 4000 major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2021-06-01 19:41:45.931750: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-06-01 19:41:45.931822: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-06-01 19:41:45.931893: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-06-01 19:41:45.931965: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2021-06-01 19:41:45.932036: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2021-06-01 19:41:45.932109: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2021-06-01 19:41:45.932181: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-06-01 19:41:45.932274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-06-01 19:41:45.932356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-01 19:41:45.932427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-06-01 19:41:45.932472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2021-06-01 19:41:45.932569: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6710 MB memory) -> physical GPU (device: 0, name: NVIDIA Quadro RTX 4000, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021-06-01 19:41:51.889919: I tensorflow/core/profiler/lib/profiler_session.cc:205] Profiler session started.
2021-06-01 19:41:51.889989: W tensorflow/core/profiler/lib/profiler_session.cc:213] Encountered error while starting profiler: Unavailable: CUPTI error: CUPTI could not be loaded or symbol could not be found.
2021-06-01 19:41:51.893350: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 0 kernel records, 0 memcpy records.
2021-06-01 19:41:51.893617: E tensorflow/core/platform/default/device_tracer.cc:70] CUPTI error: CUPTI could not be loaded or symbol could not be found.
2021-06-01 19:41:52.546494: I tensorflow/core/profiler/lib/profiler_session.cc:205] Profiler session started.
```

although, as I said, cuDNN seems to be installed (by conda automatically when installing tensorflow-gpu 1.15), the Cuda Computing Toolkit is also installed, and I added the following paths to the system variables

1.  `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin` (only to my user variables),
2.  `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64` (user variables)
3.  `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0` (system variable)
4.  `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3` (system variable)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I don't have the exact sequence because I cannot share my code right now. But, as you can see above, the DDLs like `cudart64_100.dll` are successfully loaded, so I don't understand why I get this error

> CUPTI error: CUPTI could not be loaded or symbol could not be found.

It's so annoying because I don't know whether I am actually using the GPU. Right now, my experiments take a long time and I don't know if this is due to the fact that I am or not using the GPU.

**Any other info / logs**

I need to use tensorflow v 1.15 because I am using another library that use this version. Moreover, I am aware of similar questions/issues on the web, but people seem to suggest to add `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64` to the system variables (e.g. [here](https://stackoverflow.com/a/57592360)), which I already did.

**Comment by Saduf2019** [comment]
@nbro 
There is no active support for tf 1.x, please upgrade to 2.x and ensure you have the path variable updated for cuda and let us know in case you face any issues.

**Comment by nbro** [comment]
@Saduf2019 I said above that I cannot update to TF 2.0 because I am using a library that requires TF 1.15, i.e. stable-baselines. So, could you please help me with this issue? This was a very common issue in the past, so there must be a solution to this problem (I guess).

**Comment by Saduf2019** [comment]
@nbro 
Inside of you CUDA installation directory, there is an extras\CUPTI\lib64 directory that contains the cupti64_101.dll that is trying to be loaded. Adding that directory to your path should resolve the issue,please refer to this [link](https://stackoverflow.com/questions/56860180/tensorflow-cuda-cupti-error-cupti-could-not-be-loaded-or-symbol-could-not-be).

Issues with same error: #33002, [link](https://forum.level1techs.com/t/fix-cuda-for-tensorflow-2-0/155135/2),[link2](https://github.com/tensorflow/tensorflow/issues/43030#issuecomment-736206189)

**Comment by nbro** [comment]
@Saduf2019 I said in the post above that `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64` was added to my environment variables. Inside my folder `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64`, I have `cupti64_100.dll` (rather than `cupti64_101.dll`), but I don't think this is the problem because, as far as I understood, TF 1.15 requires CUDA v10.0, which seems to come with `cupti64_100.dll`. Anyway, I already said above that I looked at that Stack Overflow post. Those 2 last links are for TF 2.

**Comment by nbro** [comment]
@Saduf2019 Ok, I found the problem. I was indeed adding `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64` as a **user** variable, but I was adding this path as a separate variable named something like `CUPTI (for TensorFlow)`, while what I added to do was to add this path to the user variable called `Path` that is (or should be) already there as a user variable.
