### ISSUE TITLE
Incorrect Results of MatMul on TFLite with GPU Delegate

### ISSUE THREAD

**Issue by Kipsora** [tensorflow/tensorflow#51417]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung S10e
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master
- Python version: 3.8.10
- Bazel version (if compiling from source): 4.0.0
- GCC/Compiler version (if compiling from source): 10.2.0
- CUDA/cuDNN version: 11.4
- GPU model and memory: RTX 2080 Ti 11GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`: v1.12.1-59750-g417a4452453 2.7.0

**Describe the current behavior**

I create a very simple model with only one `reshape` operator and one `matmul` operator. It seems that the TFLite converter will remove the reshape operator but keep the shape before the reshape operator, which is not a problem on CPU but however will cause incorrect results on GPU delegate.

We can visualize the model using netron and one of the inputs for `FullyConnected` op is 3-dimensional, while this may not be the problem since reshaping tensor may just be another view of the data in the memory, it does produce incorrect results when using it with GPU delegate (see below).

**Describe the expected behavior**
On GPU delegate, it should produce the correct results.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): Yes
- Briefly describe your candidate solution(if contributing): I haven't got a chance to view the codebase of FullyConnected op yet but I am willing to help :) I guess there are two possible solutions:
  - Let TFLite converter keep the reshape operator
  - Let TFLite interpreter able to handle such case

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

The python code to generate the model:
```python
import tensorflow as tf

tfv1 = tf.compat.v1


def convert_to_tflite_model(path: str, graph: tf.Graph, input_tensors, output_tensors, use_fp16_optimization=False):
  with graph.as_default(), tfv1.Session(graph=graph) as session:
    session.run(tfv1.global_variables_initializer())
    converter = tfv1.lite.TFLiteConverter.from_session(
      session, input_tensors=input_tensors, output_tensors=output_tensors)
    if use_fp16_optimization:
      converter.optimizations = [tf.lite.Optimize.DEFAULT]
      converter.target_spec.supported_types = [tf.float16]

    with open(path, "wb") as writer:
      writer.write(converter.convert())


def generate_matmul_tflite_model(basename: str,
                                 use_fp16_optimization=False):
  with tf.Graph().as_default() as graph:
    a = tfv1.placeholder(tf.float32, shape=[2, 8, 4], name="a")
    w = tfv1.get_variable("w", shape=[16, 4], dtype=tf.float32)
    s = tfv1.reshape(a, [2 * 8, -1])
    c = tfv1.matmul(s, w, transpose_b=True)

    convert_to_tflite_model(basename + '.tflite', graph, [a, w], [c],
                            use_fp16_optimization=use_fp16_optimization)


def main():
  generate_matmul_tflite_model("matmul", use_fp16_optimization=False)


if __name__ == "__main__":
  main()
``` 

We can visualize it in [netron](https://netron.app):

![Screenshot_20210810_174759](https://user-images.githubusercontent.com/23658877/128939552-6a8de325-0d4e-4cae-9077-55cd59e63cf4.png)

As you can see one of the inputs to the `FullyConnected` is 3-dimensional and the reshape op just get disappeared.

Then we can use the tool `run_delegate_testing.sh` to test the model (should change the kMaxPrint to 100 since the first 16 elements are correct):
```shell
$ tensorflow/lite/delegates/gpu/cl/testing/run_delegate_testing.sh -m matmul.tflite
```

The patch to modify the `kMaxPrint`:
```c++
diff --git a/tensorflow/lite/delegates/gpu/cl/testing/delegate_testing.cc b/tensorflow/lite/delegates/gpu/cl/testing/delegate_testing.cc
index eb924406ecd..d17b8a9c5bc 100644
--- a/tensorflow/lite/delegates/gpu/cl/testing/delegate_testing.cc
+++ b/tensorflow/lite/delegates/gpu/cl/testing/delegate_testing.cc
@@ -69,7 +69,7 @@ void CompareCPUGPUResults(tflite::Interpreter* cpu, tflite::Interpreter* gpu,
 
     std::cout << "Output " << tensor_ptr->name << ":" << std::endl;
 
-    const int kMaxPrint = 10;
+    const int kMaxPrint = 100;
     int printed = 0;
     int total_different = 0;
     for (int k = 0; k < tensor_elements_count; ++k) {
```

Please refer to the log below.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Replacing 1 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 1 partitions.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
Output MatMul:
Element #0: CPU value - 1.55481, GPU value - 1.55469, abs diff - 0.000122547
Element #1: CPU value - -0.968265, GPU value - -0.967773, abs diff - 0.000491381
Element #3: CPU value - 1.34608, GPU value - 1.3457, abs diff - 0.000380635
Element #4: CPU value - -1.47071, GPU value - -1.46973, abs diff - 0.00098145
Element #5: CPU value - 0.576554, GPU value - 0.576172, abs diff - 0.000382423
Element #6: CPU value - 0.716986, GPU value - 0.716309, abs diff - 0.000677407
Element #7: CPU value - -1.51386, GPU value - -1.5127, abs diff - 0.00116575
Element #8: CPU value - 1.26207, GPU value - 1.26074, abs diff - 0.00132298
Element #9: CPU value - -0.136021, GPU value - -0.135742, abs diff - 0.000278458
Element #10: CPU value - -1.08425, GPU value - -1.08398, abs diff - 0.000262737
Element #11: CPU value - 1.55344, GPU value - 1.55273, abs diff - 0.000708699
Element #12: CPU value - -0.946549, GPU value - -0.946289, abs diff - 0.000260055
Element #13: CPU value - -0.316031, GPU value - -0.315918, abs diff - 0.000113398
Element #14: CPU value - 1.35969, GPU value - 1.35938, abs diff - 0.00031805
Element #15: CPU value - -1.46148, GPU value - -1.46094, abs diff - 0.000540376
Element #16: CPU value - -0.968265, GPU value - 1.26074, abs diff - 2.22901
Element #17: CPU value - 2.00199, GPU value - -1.80371, abs diff - 3.8057
Element #18: CPU value - -1.64891, GPU value - 1.09766, abs diff - 2.74657
Element #19: CPU value - 0.153611, GPU value - 0.369385, abs diff - 0.215774
Element #20: CPU value - 1.4481, GPU value - -1.58105, abs diff - 3.02915
Element #21: CPU value - -2.04669, GPU value - 1.69629, abs diff - 3.74298
Element #22: CPU value - 1.22751, GPU value - -0.637695, abs diff - 1.86521
Element #23: CPU value - 0.441976, GPU value - -0.863281, abs diff - 1.30526
Element #24: CPU value - -1.80531, GPU value - 1.76562, abs diff - 3.57093
Element #25: CPU value - 1.91808, GPU value - -1.44531, abs diff - 3.36339
Element #26: CPU value - -0.702171, GPU value - 0.123291, abs diff - 0.825462
Element #27: CPU value - -1.00014, GPU value - 1.2832, abs diff - 2.28334
Element #28: CPU value - 2.00964, GPU value - -1.80273, abs diff - 3.81237
Element #29: CPU value - -1.62704, GPU value - 1.07227, abs diff - 2.6993
Element #30: CPU value - 0.117366, GPU value - 0.400391, abs diff - 0.283024
Element #31: CPU value - 1.4736, GPU value - -1.59473, abs diff - 3.06833
Element #32: CPU value - -0.28901, GPU value - -0.967773, abs diff - 0.678764
Element #33: CPU value - -1.64891, GPU value - 2, abs diff - 3.64891
Element #34: CPU value - 2.44461, GPU value - -1.64648, abs diff - 4.09109
Element #35: CPU value - -1.5469, GPU value - 0.152832, abs diff - 1.69973
Element #36: CPU value - -0.422372, GPU value - 1.44727, abs diff - 1.86964
Element #37: CPU value - 2.09906, GPU value - -2.04492, abs diff - 4.14398
Element #38: CPU value - -2.3217, GPU value - 1.22656, abs diff - 3.54826
Element #39: CPU value - 0.936071, GPU value - 0.441895, abs diff - 0.494176
Element #40: CPU value - 1.09799, GPU value - -1.80371, abs diff - 2.9017
Element #41: CPU value - -2.37146, GPU value - 1.91602, abs diff - 4.28747
Element #42: CPU value - 2.00219, GPU value - -0.701172, abs diff - 2.70336
Element #43: CPU value - -0.245977, GPU value - -0.999023, abs diff - 0.753046
Element #44: CPU value - -1.68062, GPU value - 2.00781, abs diff - 3.68844
Element #45: CPU value - 2.44303, GPU value - -1.625, abs diff - 4.06803
Element #46: CPU value - -1.51312, GPU value - 0.117432, abs diff - 1.63056
Element #47: CPU value - -0.464946, GPU value - 1.47168, abs diff - 1.93663
Element #48: CPU value - 1.34608, GPU value - -0.135742, abs diff - 1.48183
Element #49: CPU value - 0.153611, GPU value - 1.91602, abs diff - 1.7624
Element #50: CPU value - -1.5469, GPU value - -2.37109, abs diff - 0.824197
Element #51: CPU value - 1.86863, GPU value - 1.18066, abs diff - 0.687964
Element #52: CPU value - -0.895937, GPU value - 0.825195, abs diff - 1.72113
Element #53: CPU value - -0.697382, GPU value - -2.26172, abs diff - 1.56434
Element #54: CPU value - 1.80761, GPU value - 2.12891, abs diff - 0.321292
Element #55: CPU value - -1.66569, GPU value - -0.523438, abs diff - 1.14225
Element #56: CPU value - 0.369921, GPU value - -1.44531, abs diff - 1.81523
Element #57: CPU value - 1.1821, GPU value - 2.41211, abs diff - 1.23001
Element #58: CPU value - -1.91526, GPU value - -1.70898, abs diff - 0.206277
Element #59: CPU value - 1.3217, GPU value - -0.178589, abs diff - 1.50029
Element #60: CPU value - 0.187421, GPU value - 1.94238, abs diff - 1.75496
Element #61: CPU value - -1.56671, GPU value - -2.35938, abs diff - 0.792663
Element #62: CPU value - 1.86072, GPU value - 1.14355, abs diff - 0.717167
Element #63: CPU value - -0.865786, GPU value - 0.865723, abs diff - 1.73151
Element #64: CPU value - -1.47071, GPU value - -0.289062, abs diff - 1.18165
Element #65: CPU value - 1.4481, GPU value - -1.64648, abs diff - 3.09458
Element #66: CPU value - -0.422372, GPU value - 2.44336, abs diff - 2.86573
Element #67: CPU value - -0.895937, GPU value - -1.54492, abs diff - 0.648985
Element #68: CPU value - 1.59362, GPU value - -0.421875, abs diff - 2.01549
Element #69: CPU value - -1.18738, GPU value - 2.09766, abs diff - 3.28504
Element #70: CPU value - -0.0413711, GPU value - -2.32031, abs diff - 2.27894
Element #71: CPU value - 1.24146, GPU value - 0.93457, abs diff - 0.306894
Element #72: CPU value - -1.58158, GPU value - 1.09766, abs diff - 2.67924
Element #73: CPU value - 0.826114, GPU value - -2.37109, abs diff - 3.19721
Element #74: CPU value - 0.501611, GPU value - 2, abs diff - 1.49839
Element #75: CPU value - -1.48186, GPU value - -0.245605, abs diff - 1.23626
Element #76: CPU value - 1.43561, GPU value - -1.67969, abs diff - 3.1153
Element #77: CPU value - -0.394892, GPU value - 2.44141, abs diff - 2.8363
Element #78: CPU value - -0.919374, GPU value - -1.5127, abs diff - 0.593322
Element #79: CPU value - 1.59678, GPU value - -0.464355, abs diff - 2.06113
Element #80: CPU value - 0.576554, GPU value - -1.08398, abs diff - 1.66054
Element #81: CPU value - -2.04669, GPU value - -0.701172, abs diff - 1.34552
Element #82: CPU value - 2.09906, GPU value - 2, abs diff - 0.0990589
Element #83: CPU value - -0.697382, GPU value - -1.91406, abs diff - 1.21668
Element #84: CPU value - -1.18738, GPU value - 0.501953, abs diff - 1.68933
Element #85: CPU value - 2.24963, GPU value - 1.25879, abs diff - 0.99084
Element #86: CPU value - -1.75353, GPU value - -2.14648, abs diff - 0.392954
Element #87: CPU value - 0.0427394, GPU value - 1.54785, abs diff - 1.50511
Element #88: CPU value - 1.69766, GPU value - 0.123291, abs diff - 1.57437
Element #89: CPU value - -2.26207, GPU value - -1.70898, abs diff - 0.553082
Element #90: CPU value - 1.25951, GPU value - 2.11133, abs diff - 0.851816
Element #91: CPU value - 0.615522, GPU value - -1.05078, abs diff - 1.6663
Element #92: CPU value - -2.06418, GPU value - -0.737305, abs diff - 1.32687
Element #93: CPU value - 2.08295, GPU value - 2.01562, abs diff - 0.0673242
Element #94: CPU value - -0.658837, GPU value - -1.89648, abs diff - 1.23765
Element #95: CPU value - -1.22166, GPU value - 0.464355, abs diff - 1.68602
Element #96: CPU value - 0.716986, GPU value - 1.3457, abs diff - 0.628717
Element #97: CPU value - 1.22751, GPU value - 0.152832, abs diff - 1.07468
Element #98: CPU value - -2.3217, GPU value - -1.54492, abs diff - 0.776779
Element #99: CPU value - 1.80761, GPU value - 1.86719, abs diff - 0.0595728
Element #100: CPU value - -0.0413711, GPU value - -0.895996, abs diff - 0.854625
Printed 100 different elements, threshhold - 0.0001, next different elements skipped
Total 254 different elements, for output #0, threshhold - 0.0001
CPU time - 0.013906ms
GPU time(CPU->GPU->CPU) - 2.14057ms
```

**Comment by abattery** [comment]
@impjdi could you take a look?

**Comment by impjdi** [comment]
Yeah, the GPU backends `MATMUL` (aka `FULLY_CONNECTED`) is not feature complete and may fail in various situations, including this one.  Unfortunately, everyone working on shaders are out, and it may take a long time to fix this.

In the short term, I would remove all the optional things, such as flattening and transposing.  If you look at your example, the tensor dimensions don't match up in a mathematical sense; it will only work if you flatten `a` to 16x4 and then transpose `w`.  You might get the correct answer when you make it explicitly 16x4 and 4x16 without fancy options that TFLite GPU doesn't handle.

I do agree we should fail if things are not compatible, but this might be your short term solution if you want to be unblocked.

**Comment by Kipsora** [comment]
Yeah I totally understand that on GPU delegate does not support every option. But it will also fail even without the `transpose_b` option, like the model like as follows:

```python
  with tf.Graph().as_default() as graph:
    a = tfv1.placeholder(tf.float32, shape=[2, 8, 4], name="a")
    w = tfv1.get_variable("w", shape=[4, 16], dtype=tf.float32)
    s = tfv1.reshape(a, [2 * 8, -1])   # this operator will disappear!
    c = tfv1.matmul(s, w)
```

I think the problem is not lacking of implementation of those options in `MatMul` kernel. The problem is that the `tf.reshape` operator seems disappeared when exporting the TFLite model. I guess the TFLite converter "assumes" that the `MatMul` is able to handle 3-dim inputs (so we can remove the reshape) but it actually isn't on GPU delegate.

But if you use `tf.compat.v1.layers.flatten`, the reshape operator will be there:

```python
  with tf.Graph().as_default() as graph:
    a = tfv1.placeholder(tf.float32, shape=[2, 8, 4], name="a")
    w = tfv1.get_variable("w", shape=[32, 16], dtype=tf.float32)
    s = tf.compat.v1.layers.flatten(a)
    c = tfv1.matmul(s, w)
```

Visualization:
![Screenshot_20210811_210209](https://user-images.githubusercontent.com/23658877/129122509-e80c81e4-091c-4e4b-b030-8c81e6323dfa.png)

**Comment by impjdi** [comment]
Thanks for digging deeper into this.  If you use `tf.compat.v1.layers.flatten`, is the output correct?

**Comment by Kipsora** [comment]
Yes (assuming the abs diff threshold is `0.01`). The above model will have the testing log as follows:

```
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
RESHAPE: Operation is not supported.
TRANSPOSE: Operation is not supported.
1 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
INFO: Replacing 1 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 2 partitions.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
Output MatMul:
Element #0: CPU value - -0.0561157, GPU value - -0.0565186, abs diff - 0.000402838
Element #1: CPU value - -0.235481, GPU value - -0.234985, abs diff - 0.00049594
Element #2: CPU value - -0.198347, GPU value - -0.198975, abs diff - 0.000628054
Element #3: CPU value - 0.0211472, GPU value - 0.0202637, abs diff - 0.000883516
Element #4: CPU value - 0.221198, GPU value - 0.218872, abs diff - 0.00232619
Element #5: CPU value - 0.217881, GPU value - 0.216797, abs diff - 0.00108384
Element #6: CPU value - 0.0142447, GPU value - 0.0144043, abs diff - 0.000159643
Element #7: CPU value - -0.202488, GPU value - -0.202759, abs diff - 0.000270754
Element #8: CPU value - -0.233054, GPU value - -0.233398, abs diff - 0.000344336
Element #10: CPU value - 0.179725, GPU value - 0.178711, abs diff - 0.00101388
Element #11: CPU value - 0.243563, GPU value - 0.243896, abs diff - 0.000333682
Element #12: CPU value - 0.0834703, GPU value - 0.0822754, abs diff - 0.00119487
Element #13: CPU value - -0.153364, GPU value - -0.152344, abs diff - 0.0010207
Element #14: CPU value - -0.249196, GPU value - -0.248047, abs diff - 0.00114955
Element #15: CPU value - -0.115919, GPU value - -0.115723, abs diff - 0.000195846
Element #16: CPU value - -0.168952, GPU value - -0.169067, abs diff - 0.000115559
Element #17: CPU value - 0.23118, GPU value - 0.230225, abs diff - 0.000955477
Element #18: CPU value - 0.418766, GPU value - 0.418457, abs diff - 0.00030908
Element #20: CPU value - -0.179584, GPU value - -0.180298, abs diff - 0.000713363
Element #21: CPU value - -0.4154, GPU value - -0.414551, abs diff - 0.000849575
Element #22: CPU value - -0.269299, GPU value - -0.27002, abs diff - 0.000720531
Element #23: CPU value - 0.124395, GPU value - 0.123169, abs diff - 0.00122568
Element #25: CPU value - 0.311867, GPU value - 0.312744, abs diff - 0.000876725
Element #26: CPU value - -0.0667149, GPU value - -0.0679321, abs diff - 0.00121719
Element #27: CPU value - -0.38396, GPU value - -0.38208, abs diff - 0.00187981
Element #28: CPU value - -0.348194, GPU value - -0.348877, abs diff - 0.00068295
Element #29: CPU value - 0.00770001, GPU value - 0.00559235, abs diff - 0.00210766
Element #30: CPU value - 0.356515, GPU value - 0.356689, abs diff - 0.00017485
Element #31: CPU value - 0.377551, GPU value - 0.376953, abs diff - 0.000598162
Total 29 different elements, for output #0, threshhold - 0.0001
CPU time - 0.014532ms
GPU time(CPU->GPU->CPU) - 1.29234ms
```

**Comment by Kipsora** [comment]
I manually disabled the reshape operator in `model_builder.cc` but if I enabled it to run on GPU the results are still correct (see below).

```
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
TRANSPOSE: Operation is not supported.
1 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
INFO: Replacing 1 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 2 partitions.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
Output MatMul:
Element #0: CPU value - -0.0561157, GPU value - -0.0555921, abs diff - 0.000523593
Element #1: CPU value - -0.235481, GPU value - -0.234969, abs diff - 0.000512362
Element #3: CPU value - 0.0211472, GPU value - 0.0206675, abs diff - 0.000479735
Element #4: CPU value - 0.221198, GPU value - 0.22065, abs diff - 0.000548571
Element #5: CPU value - 0.217881, GPU value - 0.217768, abs diff - 0.000113145
Element #6: CPU value - 0.0142447, GPU value - 0.014671, abs diff - 0.000426342
Element #7: CPU value - -0.202488, GPU value - -0.201914, abs diff - 0.000573993
Element #8: CPU value - -0.233054, GPU value - -0.23286, abs diff - 0.000193775
Element #9: CPU value - -0.0493513, GPU value - -0.0497158, abs diff - 0.000364546
Element #10: CPU value - 0.179725, GPU value - 0.179137, abs diff - 0.000587821
Element #11: CPU value - 0.243563, GPU value - 0.243292, abs diff - 0.000270531
Element #12: CPU value - 0.0834703, GPU value - 0.0837656, abs diff - 0.000295311
Element #13: CPU value - -0.153364, GPU value - -0.152775, abs diff - 0.000589684
Element #14: CPU value - -0.249196, GPU value - -0.248855, abs diff - 0.000341728
Element #15: CPU value - -0.115919, GPU value - -0.116139, abs diff - 0.000220343
Element #16: CPU value - -0.168952, GPU value - -0.169855, abs diff - 0.0009031
Element #17: CPU value - 0.23118, GPU value - 0.230849, abs diff - 0.000331476
Element #18: CPU value - 0.418766, GPU value - 0.419311, abs diff - 0.000544816
Element #19: CPU value - 0.22134, GPU value - 0.222261, abs diff - 0.000920296
Element #20: CPU value - -0.179584, GPU value - -0.179135, abs diff - 0.000449657
Element #21: CPU value - -0.4154, GPU value - -0.415835, abs diff - 0.000434399
Element #22: CPU value - -0.269299, GPU value - -0.270218, abs diff - 0.000919074
Element #23: CPU value - 0.124395, GPU value - 0.123836, abs diff - 0.000558779
Element #24: CPU value - 0.40372, GPU value - 0.404036, abs diff - 0.000315309
Element #25: CPU value - 0.311867, GPU value - 0.312767, abs diff - 0.000899494
Element #26: CPU value - -0.0667149, GPU value - -0.0660583, abs diff - 0.000656664
Element #27: CPU value - -0.38396, GPU value - -0.38415, abs diff - 0.000189781
Element #28: CPU value - -0.348194, GPU value - -0.349056, abs diff - 0.000861824
Element #29: CPU value - 0.00770001, GPU value - 0.00695852, abs diff - 0.00074149
Element #31: CPU value - 0.377551, GPU value - 0.378358, abs diff - 0.000806987
Total 30 different elements, for output #0, threshhold - 0.0001
CPU time - 0.034635ms
GPU time(CPU->GPU->CPU) - 1.51333ms
```

**Comment by Kipsora** [comment]
@impjdi There is an optimization pass in the MLIR pass [`RemoveReshapeBeforeFullyConnected`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/transforms/optimize.cc#L1260-L1295) that causes the problem. So if I disable it by the patch below, the issue is resolved. 

```c++
diff --git a/tensorflow/compiler/mlir/lite/transforms/optimize.cc b/tensorflow/compiler/mlir/lite/transforms/optimize.cc
index 3553d0e5e9a..c2b6a958c2a 100644
--- a/tensorflow/compiler/mlir/lite/transforms/optimize.cc
+++ b/tensorflow/compiler/mlir/lite/transforms/optimize.cc
@@ -1429,8 +1429,8 @@ void OptimizePass::runOnFunction() {
   // Merge reshapes into fully connected ops before we start moving them past
   // binary ops.
   OwningRewritePatternList phase_0_patterns(&getContext());
-  phase_0_patterns.insert<RemoveReshapeAfterFullyConnected,
-                          RemoveReshapeBeforeFullyConnected>(ctx);
+  phase_0_patterns.insert<RemoveReshapeAfterFullyConnected/*,
+                          RemoveReshapeBeforeFullyConnected*/>(ctx);
   (void)applyPatternsAndFoldGreedily(func, std::move(phase_0_patterns));
 
   // Potentially the binary ops might be fused together, like hard_swish, thus
@@ -1459,7 +1459,7 @@ void OptimizePass::runOnFunction() {
       FuseBinaryOpToFollowingConv2D, FuseBinaryOpToFollowingDepthwiseConv2D,
       FuseBinaryOpToFollowingFullyConnected, FuseConv2DAndMulWithQDQs,
       FuseDepthwiseConv2DAndMulWithQDQs, ConvertTrivialTransposeOpToReshapeOp,
-      RemoveReshapeAfterFullyConnected, RemoveReshapeBeforeFullyConnected,
+      RemoveReshapeAfterFullyConnected, /*RemoveReshapeBeforeFullyConnected,*/
       FuseUnpackAndConcatToReshape>(ctx);
   if (enable_canonicalization_)
     AddCanonicalizationPatterns(ctx, &phase_2_patterns);
```

So the comment says:

> Remove Reshape before FullyConnected when `keep_num_dims=false` and Reshape does not alter the last dimension as FullyConnected will collapse all other dimensions into a single dimension.

However, this is not true (at least currently) for `FullyConnected` op on GPU delegate. But disabling the `RemoveReshapeBeforeFullyConnected` optimization pass is only a workaround. I guess this issue is really resolved only after the GPU delegate can handle such case.

**Comment by impjdi** [comment]
@Kipsora Thanks for digging deeper into this!  On behalf of TFLite & TFLite GPU, really appreciate it!

@renjie-liu According to Jiacheng's findings, this optimization pass doesn't seem compatible with the GPU.  Can we drop this, or make this TAC specific, or find another solution?

**Comment by renjie-liu** [comment]
SG, I will file a bug to track this

**Comment by renjie-liu** [comment]
Meanwhile, can you try TAC: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/mlir/lite/experimental/tac

thanks!

**Comment by sushreebarsa** [comment]
@Kipsora Have you referred the comments above and let me know if it helps?
Thank you!

**Comment by Kipsora** [comment]
Hi @sushreebarsa, I basically managed to handle this problem by removing the optimization pass and have been busy since. So I didn't notice the TAC solution. I will try it this week after sometime

**Comment by pkgoogle** [comment]
Hi @Kipsora, ever got a chance to circle back to this?
