### ISSUE TITLE
ipython ImportError: Library not loaded: @rpath/libcudart.8.0.dylib

### ISSUE THREAD

**Issue by ohadle** [tensorflow/tensorflow#5141]
I just installed 0.11rc1 from pip (`TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0rc1-py2-none-any.whl`), with a brand-new CUDA 8.0 installation, and got this error:
```
In [1]: import tensorflow as tf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

/Users/me/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22
---> 23 from tensorflow.python import *
     24
     25

/Users/me/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     47 _default_dlopen_flags = sys.getdlopenflags()
     48 sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 49 from tensorflow.python import pywrap_tensorflow
     50 sys.setdlopenflags(_default_dlopen_flags)
     51

/Users/me/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     26                 fp.close()
     27             return _mod
---> 28     _pywrap_tensorflow = swig_import_helper()
     29     del swig_import_helper
     30 else:

/Users/me/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py in swig_import_helper()
     22         if fp is not None:
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
     25             finally:
     26                 fp.close()

ImportError: dlopen(/Users/me/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/me/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
```
(Similar to https://github.com/tensorflow/tensorflow/issues/4187 but different error.)
Looks like a [path issue](http://stackoverflow.com/questions/37933890/tensorflow-gpu-setup-error-with-cuda-on-pycharm) but I don't see a problem:
```
➜  ~ echo $PATH
/Users/me/anaconda/bin:/usr/local/cuda/bin:/Developer/NVIDIA/CUDA-8.0/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
➜  ~ echo $DYLD_LIBRARY_PATH
/usr/local/cuda/lib:/Developer/NVIDIA/CUDA-8.0/lib:
➜  ~ ll /Developer/NVIDIA/CUDA-8.0/lib/libcudart*
-rwxr-xr-x 1 root wheel 285K Sep 27 00:59 /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x 1 root wheel   19 Sep 27 00:59 /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib -> libcudart.8.0.dylib
-rw-r--r-- 1 root wheel 599K Sep 27 00:59 /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
```
I also get a segfault when importing in python:
```
➜  ~ python -c "import tensorflow;"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.dylib locally
[1]    60723 segmentation fault  python -c "import tensorflow;"
```
Tried the [suggestion from the docs](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#mac-os-x-segmentation-fault-when-import-tensorflow), didn't work:
```
ln -sf /usr/local/cuda/lib/libcuda.dylib /usr/local/cuda/lib/libcuda.1.dylib
```

On OSX 10.11.6, CUDA 8.0.46, no CUDNN installed yet.

Is this a SIP issue? Should the install procedure be updated?
I don't know if I can turn off SIP, this is a work computer.

**Comment by yaroslavvb** [comment]
Apparently SIP prevents you from overriding `DYLD_LIBRARY_PATH` which would explain why the library is not found -- https://groups.google.com/forum/#!topic/caffe-users/waugt62RQMU

**Comment by ohadle** [comment]
Is it just that variable? Can TF be set up to use another variable (`TF_LIBRARY_PATH`)?
If not I'll see what I can do about SIP.

**Comment by yaroslavvb** [comment]
That variable is not used by TF, but by `dlopen` which is a system call. PS: only older macs support CUDA, which means that GPUs are old/slow and don't give a performance advantage over CPU. The main reason for using GPU tensorflow on Mac is for debugging a model that you'll eventually deploy on linux GPU

**Comment by ohadle** [comment]
Well I got a pretty awesome speedup by using the mac (2014, 750M) with Theano :)
Let me know if I should close this issue, or leave it for the docs.

**Comment by xinqiu** [comment]
I can't run 

```python
import tensorflow as tf
with tf.Session() as sess:
  with tf.device("/gpu:0"):
    matrix1 = tf.constant([[3., 3.]])
    matrix2 = tf.constant([[2.],[2.]])
    product = tf.matmul(matrix1, matrix2)
    result = sess.run([product])
    print result
```

in Pycharm, but can run in Terminal.
How I can run the code in Pycharm?
I have added DYLD_LIBRARY_PATH in Configurations->Environment variables.

**Comment by drpngx** [comment]
Sorry, I don't have a mac to try here, but could you give me the backtrace using gdb? If it's the tensorflow so lib loading the library, could you try to rebuild using -Wl,--rpath and/or using patchelf to see if that fixes it?

**Comment by ohadle** [comment]
Strange.
I installed CUDNN. Now TF seems to run fine called from python:
```
➜  ~ python -c "import tensorflow;"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.dylib locally
```
(more complex example [here](https://gist.github.com/ohadle/5c73237d337f2b955d00c9ec857ab0a8))
But running from ipython still gives the error above.

How to I use gdb on the ipython script?

**Comment by drpngx** [comment]
You can just say "gdb ipython" instead of just python.

At this point you might want to use strace to figure out whether it's loading the same files on both ends.

**Comment by ohadle** [comment]
When I try `gdb ipython` I get:
```
"/Users/me/anaconda/bin/ipython": not in executable format: File format not recognized
```

Apparently the OSX version of strace is dtrace. Results (/meaningless gibberish?) here:
https://gist.github.com/ohadle/5c73237d337f2b955d00c9ec857ab0a8

**Comment by yaroslavvb** [comment]
Here's a similar-looking crash that only happens in IPython and not in Python. The solution is to run `python <my anaconda virtual environment path>/bin/ipython` instead of `ipython`

PS, you can also get stack traces on MacOS from diagnostics reports folder, as shown here: https://github.com/tensorflow/tensorflow/issues/3494#issuecomment-239081963

"gdb ipython" doesn't work because "ipython" is a shell script, an alternative way is to start ipython, then "gdb -p <process id>", then do import tensorflow.

**Comment by drpngx** [comment]
Nice!! Do you know why the difference? I wonder if that's something we could work around on our end.

@ohadle does that work for you?

**Comment by ohadle** [comment]
Yep, works for me.
Let me know if gdb / traces are still needed.

**Comment by yaroslavvb** [comment]
@drpngx My first guess would be that `IPython.start_ipython()` doesn't propagate the environment variables from the parent process

**Comment by yaroslavvb** [comment]
@drpngx My first guess would be that `IPython.start_ipython()` doesn't
propagate the environment variables from the parent process

**Comment by drpngx** [comment]
Thanks! Closing this ticket, as it is "solved". Looping internally.

**Comment by bhomass** [comment]
I disabled SIP, but still get the error
Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tensorflow/python/_pywrap_tensorflow.so

what else do I try?

**Comment by ohadle** [comment]
Good to know.
1. Make sure you have cuDNN installed.
2. Try running from python (not ipython). E.g. `python -c "import tensorflow"`

**Comment by yaroslavvb** [comment]
Does your DYLD_LIBRARY_PATH contain a path which has /libcudart.8.0.dylib?

**Comment by bhomass** [comment]
/libcudart.8.0.dylib definitely is there. not sure how to check cuDNN. but I passed the CUDA installation check.

**Comment by AlienceGG** [comment]
I met this problem right now , and I don't know how to fix it ...:(

**Comment by harpreet1010** [comment]
Add the following to your bash profile. This will provide Tensorflow the path needed to get to this dylib.

export DYLD_LIBRARY_PATH="/Developer/NVIDIA/CUDA-8.0/lib:$DYLD_LIBRARY_PATH"

**Comment by visionscaper** [comment]
Exactly the same issue. `libcudart.8.0.dylib` is available on the `DYLD_LIBRARY_PATH`:

    $ python -c "import tensorflow"
    dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_    Ucuda_Scuda_Slib in /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
    dyld: warning, LC_RPATH ../local_config_cuda/cuda/lib in /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
    dyld: warning, LC_RPATH ../local_config_cuda/cuda/extras/CUPTI/lib in /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
      File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
      File "/usr/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
        _pywrap_tensorflow = swig_import_helper()
      File "/usr/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
    ImportError: dlopen(/usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
      Referenced from: /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
      Reason: image not found

  
    $ echo $DYLD_LIBRARY_PATH
    :/usr/local/cuda/lib
  
    $ ls -all /usr/local/cuda/lib/libcudart.8.0.dylib
    lrwxr-xr-x@ 1 root  wheel  50 Sep 27 00:00 /usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib

    $ ls -all /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
    -rwxr-xr-x@ 1 root  wheel  291712 Sep 26 23:59 /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib

Any input is appreciated.

**Comment by visionscaper** [comment]
FYI, it works with ipython after the applying the hack in issue #2910 (`ln -s libcuda.dylib libcuda.1.dylib`). How could this be?

**Comment by harpreet1010** [comment]
Yes this is interesting indeed. I have had to create the sym link as well
as fix DYLD_PATH for tensor flow GPU to work.

**Comment by martin-gorner** [comment]
I have this issue as well.
MacOS using an external GPU.
DYLD_LIBRARY_PATH is set (to /usr/local/cuda/lib)
/usr/local/cuda/lib/libcudart.8.0.dylib exists

It works when I disable SIP. But something turns SIP on on a regular basis. Annoying.

**Comment by yaroslavvb** [comment]
I suspect installing macos security updates enables sip

**Comment by martin-gorner** [comment]
Actually, SIP seems to be re-enabled on every reboot of the machine.

**Comment by yaroslavvb** [comment]
Not for me (10.12.2 (16C67)), do you have security update installed every
time you rebooted machine?

**Comment by laoyao** [comment]
I have the same issue. @martin-gorner . Do you resolve it？

**Comment by laoyao** [comment]
<img width="586" alt="2017-02-19 10 10 56" src="https://cloud.githubusercontent.com/assets/870777/23103101/55600106-f6f0-11e6-8fde-06a34c6dcc05.png">

**Comment by lelayf** [comment]
Same issue here. Building on Mac Pro with custom Nvidia Titan Black instead of factory AMD card, macOS Sierra, trying to build r1.0 branch with bazel and SSE4.2 enabled. /usr/local/cuda/lib/libcudart.8.0.dylib exists, DYLIB_LIBRARY_PATH and DYLIB_FALLBACK_LIBRARY_PATH are set to include /usr/local/cuda/lib. Even tried using LD_LIBRARY_PATH and LIBRARY_PATH but issue persists. Also restarted OS with SIP disabled, which `csrutil status` shows it still is.

**Comment by DolanDack** [comment]
```
import tensorflow
Traceback (most recent call last):

  File "<ipython-input-1-a649b509054f>", line 1, in <module>
    import tensorflow

  File "/Users/georgiospapadopoulos/anaconda/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *

  File "/Users/georgiospapadopoulos/anaconda/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "/Users/georgiospapadopoulos/anaconda/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/georgiospapadopoulos/anaconda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/georgiospapadopoulos/anaconda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/georgiospapadopoulos/anaconda/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/georgiospapadopoulos/anaconda/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/georgiospapadopoulos/anaconda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/georgiospapadopoulos/anaconda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found


Failed to load the native TensorFlow runtime.
```

I have the same issue. Can someone please re-open the ticket? I would really like to be able to code using spyder and ipython due to the familiar environment.

**Comment by yaroslavvb** [comment]
@lelayf the issue is https://github.com/tensorflow/tensorflow/issues/7227 the solution is to build bazel from head or downgrade to 0.4.3

@DolanDack can you use it from outside of Spyder but not inside of Spyder? Most likely the issue is that your spider environment is not setting PATH, DYLD_LIBRARY_PATH, LD_LIBRARY_PATH properly

**Comment by bradleygibson** [comment]
Exactly the same situation as @visionscaper.  Originally:
```
Socrates:~ bRad$ python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/bRad/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/bRad/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/bRad/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/bRad/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Based on this thread, I then created  a symlink:
```
Socrates:~ cd /usr/local/lib
Socrates:lib ln -s ../cuda/lib/ libcudart.8.0.dylib
```

But with the symlink I get a "not a file" error:
```
Traceback (most recent call last):
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/bRad/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/bRad/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libcudart.8.0.dylib: not a file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/bRad/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/bRad/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/bRad/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libcudart.8.0.dylib: not a file


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

My environment:
```
Socrates:~ bRad$ echo $DYLD_LIBRARY_PATH
/usr/local/cuda/lib:/Developer/NVIDIA/CUDA-8.0/lib:
Socrates:~ bRad$ l /usr/local/cuda/lib/libcudart.8.0.dylib
lrwxr-xr-x@ 1 root  wheel  50 Jan 11 17:33 /usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
Socrates:~ bRad$ l  /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
-rwxr-xr-x@ 1 root  wheel   285K Jan 11 17:32 /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
```

Note that CUDA sample apps build and run fine:
```
Socrates:~ bRad$ cd /usr/local/cuda/bin/x86_64/darwin/release
Socrates:release bRad$ ./vectorAdd
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

Any ideas?

**Comment by bradleygibson** [comment]
The solution presented in https://github.com/tensorflow/tensorflow/issues/6729 resolved my issue.  Namely,
```
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH=${CUDA_HOME}/lib:${CUDA_HOME}/extras/CUPTI/lib:/Developer/NVIDIA/CUDA-8.0/lib
export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
export PATH=$DYLD_LIBRARY_PATH:$PATH
```
+ ensuring that pyenv is not active (remove `eval "$(pyenv init -)"` if you have it) yields:

```
Socrates:~ bRad$ python -c "import tensorflow as tf"
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.8.0.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.8.0.dylib locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.1.dylib. LD_LIBRARY_PATH: /usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib:/Developer/NVIDIA/CUDA-8.0/lib
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.8.0.dylib locally
```

**Comment by vaibhavravi** [comment]
@bradleygibson Worked! Thank you so much. I think setting the environment variables helped me because I had done everything else beforehand and it still was not working for me.

**Comment by bradleygibson** [comment]
@vaibhavravi Yes, there are shenanigans going on with LD_LIBRARY in particular...   Glad it worked for you too!

**Comment by martin-gorner** [comment]
@laoyao No solution yet, just a workaround, reboot on recovery partition, disable SIP.Again and again... Fortunately a mac is quick to boot these days.

**Comment by vaibhavravi** [comment]
UPDATE: I have to update the path variables each time I activate/deactivate the tensorflow environment before launching jupyter notebook using:

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/cuda/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Developer/NVIDIA/CUDA-8.0/lib
export PATH=$PATH:/Developer/NVIDIA/CUDA-8.0/lib

After doing this, tensorflow imports fine inside jupyter.

**Comment by asimonov** [comment]
I am on El Capitain, have SIP disabled and set the paths as above. but still see the build error on master:

ERROR: /Users/alexeysimonov/dev/tensorflow/tensorflow/cc/BUILD:312:1: Executing genrule //tensorflow/cc:logging_ops_genrule failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 5.
dyld: Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /private/var/tmp/_bazel_root/9a8b7d02e7f6ce832d52efe09806ba70/execroot/tensorflow/bazel-out/host/bin/tensorflow/cc/ops/logging_ops_gen_cc
  Reason: image not found
/bin/bash: line 1: 15710 Trace/BPT trap: 5       bazel-out/host/bin/tensorflow/cc/ops/logging_ops_gen_cc bazel-out/local_darwin-py3-opt/genfiles/tensorflow/cc/ops/logging_ops.h bazel-out/local_darwin-py3-opt/genfiles/tensorflow/cc/ops/logging_ops.cc tensorflow/cc/ops/op_gen_overrides.pbtxt 0
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by vaibhavravi** [comment]
@asimonov Please refer to my comment above. You need to re-export the path variables from within the tensorflow virtual environment. I had to do this each time I source-activated tensorflow.

**Comment by asimonov** [comment]
i do not use virtualenv. I try to install to default conda environment

**Comment by asimonov** [comment]
I made it work -- see my comment at https://github.com/tensorflow/tensorflow/issues/7633

**Comment by chrysm** [comment]
my system keeps persistently looking for @rpath/libcudart.7.5.dylib even though i've uninstalled 7.5 completely and installed 8.0.  i've also done a complete wipe and reinstall of tensorflow.  none of the suggestions here have solved this.

**Comment by abrahamrhoffman** [comment]
@bradleygibson you da man! Worked great for me as well! W00p W00p!
