### ISSUE TITLE
CUBLAS_STATUS_INVALID_VALUE when using `tf.matmal` to calculate large size of tensors

### ISSUE THREAD

**Issue by njzjz** [tensorflow/tensorflow#51889]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Feroda 34
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9.6
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version: 11.3.1/8.2.1
- GPU model and memory: 2080 Super 8GB

**Describe the current behavior**
We are developers of [deepmd-kit](https://github.com/deepmodeling/deepmd-kit), a deep learning package based on TensorFlow in areas of computational chemistry and computational material. To give convenience to our users, we use `conda-build` to [build TensorFlow](https://github.com/deepmd-kit-recipes/tensorflow-base-feedstock/blob/master/recipe/build.sh) and our programs from source, and distribute them using an offline package, ensuring our users have the same library environment. As reported by our users in deepmodeling/deepmd-kit#1061 and deepmodeling/deepmd-kit#1062, when using `tf.matmal` to calculate large size of tensors, an error happened below. The original error should be ` failed to run cuBLAS routine: CUBLAS_STATUS_INVALID_VALUE`, and this causes `Blas xGEMV launch failed`. When we try to descrease the size of the tensor, and it works fine. However, I believe the error is not related to the memory, as some one also got this error in 40GB A100, where the memory is enough and there is no OOM message. And also, **it works fine with CUDA 10.1 and cuDNN 7**. I think it may be an internal error in TensorFlow or cuBLAS.

```
2021-09-08 17:04:15.418750: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-09-08 17:04:15.794003: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-09-08 17:04:15.839986: E tensorflow/stream_executor/cuda/cuda_blas.cc:564] failed to run cuBLAS routine: CUBLAS_STATUS_INVALID_VALUE
Traceback (most recent call last):
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas xGEMV launch failed : a.shape=[1,1228800,2], b.shape=[1,1,2], m=1228800, n=1, k=2
	 [[{{node gradients/filter_type_all/MatMul_6_grad/MatMul}}]]
	 [[l2_virial_test/_45]]
  (1) Internal: Blas xGEMV launch failed : a.shape=[1,1228800,2], b.shape=[1,1,2], m=1228800, n=1, k=2
	 [[{{node gradients/filter_type_all/MatMul_6_grad/MatMul}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jz748/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
    sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/main.py", line 437, in main
    train_dp(**dict_args)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 102, in train
    _do_work(jdata, run_opt, is_compress)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 163, in _do_work
    model.train(train_data, valid_data)
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 497, in train
    self.valid_on_the_fly(fp, [train_batch], valid_batches, print_header=True)
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 591, in valid_on_the_fly
    train_results = self.get_evaluation_results(train_batches)
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 643, in get_evaluation_results
    results = self.loss.eval(self.sess, feed_dict, natoms)
  File "/home/jz748/codes/deepmd-kit/deepmd/loss/ener.py", line 140, in eval
    error, error_e, error_f, error_v, error_ae, error_pf = run_sess(sess, run_data, feed_dict=feed_dict)
  File "/home/jz748/codes/deepmd-kit/deepmd/utils/sess.py", line 20, in run_sess
    return sess.run(*args, **kwargs)
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/jz748/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas xGEMV launch failed : a.shape=[1,1228800,2], b.shape=[1,1,2], m=1228800, n=1, k=2
	 [[node gradients/filter_type_all/MatMul_6_grad/MatMul (defined at /codes/deepmd-kit/deepmd/descriptor/se_t.py:353) ]]
	 [[l2_virial_test/_45]]
  (1) Internal: Blas xGEMV launch failed : a.shape=[1,1228800,2], b.shape=[1,1,2], m=1228800, n=1, k=2
	 [[node gradients/filter_type_all/MatMul_6_grad/MatMul (defined at /codes/deepmd-kit/deepmd/descriptor/se_t.py:353) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node gradients/filter_type_all/MatMul_6_grad/MatMul:
 filter_type_all/matrix_1_1_1/read (defined at /codes/deepmd-kit/deepmd/utils/network.py:174)

Input Source operations connected to node gradients/filter_type_all/MatMul_6_grad/MatMul:
 filter_type_all/matrix_1_1_1/read (defined at /codes/deepmd-kit/deepmd/utils/network.py:174)

Original stack trace for 'gradients/filter_type_all/MatMul_6_grad/MatMul':
  File "/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
    sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
  File "/codes/deepmd-kit/deepmd/entrypoints/main.py", line 437, in main
    train_dp(**dict_args)
  File "/codes/deepmd-kit/deepmd/entrypoints/train.py", line 102, in train
    _do_work(jdata, run_opt, is_compress)
  File "/codes/deepmd-kit/deepmd/entrypoints/train.py", line 158, in _do_work
    model.build(train_data, stop_batch)
  File "/codes/deepmd-kit/deepmd/train/trainer.py", line 329, in build
    self._build_network(data)
  File "/codes/deepmd-kit/deepmd/train/trainer.py", line 353, in _build_network
    = self.model.build (self.place_holders['coord'],
  File "/codes/deepmd-kit/deepmd/model/ener.py", line 229, in build
    = self.descrpt.prod_force_virial (atom_ener, natoms)
  File "/codes/deepmd-kit/deepmd/descriptor/se_t.py", line 353, in prod_force_virial
    [net_deriv] = tf.gradients (atom_ener, self.descrpt_reshape)
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_impl.py", line 169, in gradients
    return gradients_util._GradientsHelper(
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_util.py", line 681, in _GradientsHelper
    in_grads = _MaybeCompile(grad_scope, op, func_call,
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_util.py", line 338, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gradients_util.py", line 682, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/math_grad.py", line 1733, in _MatMulGrad
    grad_a = gen_math_ops.mat_mul(grad, b, transpose_b=True)
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5716, in mat_mul
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

...which was originally created as op 'filter_type_all/MatMul_6', defined at:
  File "/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
    sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
[elided 4 identical lines from previous traceback]
  File "/codes/deepmd-kit/deepmd/train/trainer.py", line 353, in _build_network
    = self.model.build (self.place_holders['coord'],
  File "/codes/deepmd-kit/deepmd/model/ener.py", line 159, in build
    = self.descrpt.build(coord_,
  File "/codes/deepmd-kit/deepmd/descriptor/se_t.py", line 316, in build
    self.dout, self.qmat = self._pass_filter(self.descrpt_reshape,
  File "/codes/deepmd-kit/deepmd/descriptor/se_t.py", line 388, in _pass_filter
    layer, qmat = self._filter(tf.cast(inputs_i, self.filter_precision), type_i, name='filter_type_all'+suffix, natoms=natoms, reuse=reuse, trainable = trainable, activation_fn = self.filter_activation_fn)
  File "/codes/deepmd-kit/deepmd/descriptor/se_t.py", line 499, in _filter
    ebd_env_ij = embedding_net(ebd_env_ij,
  File "/codes/deepmd-kit/deepmd/utils/network.py", line 188, in embedding_net
    hidden = tf.reshape(activation_fn(tf.matmul(xx, w) + b), [-1, outputs_size[ii]])
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py", line 3489, in matmul
    return gen_math_ops.mat_mul(
  File "/anaconda3/envs/dpdev113/lib/python3.9/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5716, in mat_mul
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
```

**Describe the expected behavior**

It works without errors.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no, I don't have the idea about the reason
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
I haven't successfully created a minimum code to reproduce the error. Maybe provide later...

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

`Blas xGEMV launch failed` is raised here:
https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/kernels/matmul_op_impl.h#L431-L436

**Comment by tilakrayal** [comment]
@njzjz ,
Every TensorFlow release is compatible with a certain version, for more information please take a look at the [tested build](https://www.tensorflow.org/install/source#gpu) configurations.In this case, can you please try installing TensorFlow v2.5 with CUDA 11.2 and cuDNN 8 .1and check if you are facing the same error. Thanks!

**Comment by njzjz** [comment]
Hi @tilakrayal, CUDA 11.2 works for me. So, I guess there is still something incompatible with CUDA 11.3 in the source code, even if I built from source?

**Comment by tilakrayal** [comment]
@njzjz ,
As mentioned above please follow  the tested build configurations and try to install tf v2.5 with compatible cuda and cudnn and let us know if you are facing any issue. CUDA 11.3 is incompatible with v2.5 as every tensorflow release is compatible with certain version.Hope it r helps to resolve the issue.Thanks!
