### ISSUE TITLE
Context in use?

### ISSUE THREAD

**Issue by noisychannel** [tensorflow/tensorflow#526]
Running the following with GPU support : 

``python convolutional.py``

throws the error:
``F tensorflow/stream_executor/cuda/cuda_driver.cc:383] Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(context) (0 vs. 216)``

``Aborted``

It seems like 216 when calling cuCtxSetCurrent (which I'm assuming assigns the context to the calling CPU thread) corresponds to CUDA_ERROR_CONTEXT_ALREADY_IN_USE. 

What may be causing this error? It seems like the script successfully transfers data to the GPU and fails when initialize_all_variables() is called.

**Comment by noisychannel** [comment]
The complete log is here : http://pastebin.com/as0fWvYv

**Comment by noisychannel** [comment]
And the same issue with tutorials_example_trainer. Log here : http://pastebin.com/vPkFfete

**Comment by zheng-xq** [comment]
@noisychannel, could you provide a bit more information about your running
environment. I see that you have two K20m on your machine. Is this a
dedicated machine, or something shared?

**Comment by noisychannel** [comment]
Tried both scenarios : 
1. Dedicated with 2 K20s. 
2. Shared with 2 K20s and 1 available and selected for use. 

Same issue in both cases.

**Comment by digitalsword** [comment]
@noisychannel  I have the same issue. Did you solve it?

**Comment by noisychannel** [comment]
No, the issue remains.

**Comment by digitalsword** [comment]
@zheng-xq Is the bug fixed in the recently released tensorflow 0.7?

**Comment by noisychannel** [comment]
Any updates here?

**Comment by zheng-xq** [comment]
I've started an offline conversation with the stream-executor team, since the error originates from stream-executor. Still wait for their response. 

@leary-google, @eliben, anything from the stream-executor side?

**Comment by digitalsword** [comment]
I am still seeing the same cuda error for tensorflow 0.7. The error is ```Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(context) (0 vs. 216)```

version:
```
commit b88971051fbc49fa1e0b91ec1b0b60defa11697e
Merge: 5a30c8f 00986d4
Author: Derek Murray <mrry@google.com>
Date:   Fri Feb 26 05:08:35 2016 -0800
```

error:
```
++ python cifar10_train.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.5 locally
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:08:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:718] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:08:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256B
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 512B
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 4.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 16.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 32.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 64.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 128.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 512.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 1.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 2.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 4.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 8.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 16.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 32.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 64.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 128.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:107] Allocating 10.60GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:118] GPU 0 memory begins at 0x13047a0000 extends to 0x15aaa4019a
F tensorflow/stream_executor/cuda/cuda_driver.cc:383] Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(context) (0 vs. 216)
./run.sh: line 4: 33880 Aborted                 python cifar10_train.py
```

**Comment by RasmooL** [comment]
Indeed, I am seeing the same error sometimes on a shared K40. It seems to happen when someone else has completed a job, and somehow the context is not cleared? I am sure that no job is actually executing on the GPU at the time.

**Comment by crscardellino** [comment]
I am having the same issue with GPU:1, I can run without problems in GPU:0, but when trying to force the graph to be in GPU:1, using Graph.device(), I get the following: http://pastebin.com/ekTgqJ0U

**Comment by zxvix** [comment]
I encountered the error `Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(context) (0 vs. 216)` recently, which turned out to be caused by someone accidently set the compute mode of GPU to be EXCLUSIVE_THREAD. Revert it back to DEFAULT solved my error.

**Comment by girving** [comment]
@zheng-xq: Should we contact the Stream Executor folk offline?  It looks like they might not have Github notifications turned on.

**Comment by noisychannel** [comment]
Issue still exists in 0.9.

**Comment by noisychannel** [comment]
Out of curiosity, how is this not a bigger issue? Is there a specific condition where this failure occurs? It seems like the process crashes whether all or any GPUs are available on the machine. 

How do other people get around this?

**Comment by danpovey** [comment]
Regarding the comment of @zxvix, saying: "I encountered the error Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(context) (0 vs. 216) recently, which turned out to be caused by someone accidently set the compute mode of GPU to be EXCLUSIVE_THREAD. Revert it back to DEFAULT solved my error."

Sometimes on shared clusters there are valid reasons for setting exclusive mode for GPUs.  Does TensorFlow require particular modes?  Is EXCLUSIVE_PROCESS a possibility?

**Comment by zheng-xq** [comment]
Adding @henline, who is the owner of stream-executor.

**Comment by kramimus** [comment]
I am seeing a similar issue on 0.9 compiled from source, HEAD:

```
commit 554ddd9ad2d4abad5a9a31f2d245f0b1012f0d10
Merge: 89e1cc5 a0745a7
Author: yifeif <fengyifei2026@gmail.com>
Date:   Tue Jul 26 16:17:21 2016 -0700
```

I am on a shared cluster with a scheduler, so I should have exclusive access to the node during my time slice. It looks like exclusive mode is set, but there are no running processes at the time time I try to use it:

```   
[2016-07-28T17:59:19Z]: +------------------------------------------------------+                       
[2016-07-28T17:59:19Z]: | NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
[2016-07-28T17:59:19Z]: |-------------------------------+----------------------+----------------------+
[2016-07-28T17:59:19Z]: | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
[2016-07-28T17:59:19Z]: | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
[2016-07-28T17:59:19Z]: |===============================+======================+======================|
[2016-07-28T17:59:19Z]: |   0  Tesla K40m          Off  | 0000:08:00.0     Off |                    0 |
[2016-07-28T17:59:19Z]: | N/A   25C    P8    19W / 235W |     23MiB / 11519MiB |      0%    E. Thread |
[2016-07-28T17:59:19Z]: +-------------------------------+----------------------+----------------------+
[2016-07-28T17:59:19Z]:                                                                                
[2016-07-28T17:59:19Z]: +-----------------------------------------------------------------------------+
[2016-07-28T17:59:19Z]: | Processes:                                                       GPU Memory |
[2016-07-28T17:59:19Z]: |  GPU       PID  Type  Process name                               Usage      |
[2016-07-28T17:59:19Z]: |=============================================================================|
[2016-07-28T17:59:19Z]: |  No running processes found                                                 |
[2016-07-28T17:59:19Z]: +-----------------------------------------------------------------------------+
[2016-07-28T17:59:21Z]: Using TensorFlow backend.
[2016-07-28T17:59:22Z]: I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
[2016-07-28T17:59:22Z]: I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
[2016-07-28T17:59:22Z]: I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
[2016-07-28T17:59:23Z]: I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.4.0.7 locally
[2016-07-28T17:59:23Z]: I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
[2016-07-28T17:59:34Z]: I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
[2016-07-28T17:59:34Z]: name: Tesla K40m
[2016-07-28T17:59:34Z]: major: 3 minor: 5 memoryClockRate (GHz) 0.745
[2016-07-28T17:59:34Z]: pciBusID 0000:08:00.0
[2016-07-28T17:59:34Z]: Total memory: 11.25GiB
[2016-07-28T17:59:34Z]: Free memory: 11.15GiB
[2016-07-28T17:59:34Z]: I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
[2016-07-28T17:59:34Z]: I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
[2016-07-28T17:59:34Z]: I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:08:00.0)
[2016-07-28T17:59:34Z]: F tensorflow/stream_executor/cuda/cuda_driver.cc:395] Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(cuda_context->context()) (0 vs. 216)
[2016-07-28T17:59:34Z]: X_train shape: (60000, 1, 28, 28)
[2016-07-28T17:59:34Z]: 60000 train samples
[2016-07-28T17:59:34Z]: 10000 test samples
[2016-07-28T17:59:41Z]: /tmp/wrapper5271742824235601482.sh: line 12: 61655 Aborted                 (core dumped) python mnist_cnn.py
[2016-07-28T17:59:41Z]: Exited with code 0
```

**Comment by danpovey** [comment]
Tensorflow guys, if I were you I would change the assert statement that
fails here:

cuda/cuda_driver.cc:395] Check failed: CUDA_SUCCESS ==
dynload::cuCtxSetCurrent(cuda_context->context()) (0 vs. 216)

to some code that prints out the text form of the CUDA exit code, and maybe
for good measure tries to invoke nvidia-smi to get extra information.  We
found this necessary in Kaldi in order to ensure that when there are
problems, all the information needed is in the log.
Dan

**Comment by henline** [comment]
Hi, I'm the owner of StreamExecutor. Sorry for arriving late to this discussion.

I believe this problem is caused in all cases by GPUs with their compute mode set to EXCLUSIVE_THREAD (just as mentioned by @zxvix). The solution is to set the compute mode to DEFAULT or EXCLUSIVE_PROCESS, which can be done via one of the following commands:

    $ nvidia-smi --compute-mode=0 # for DEFAULT
    $ nvidia-smi --compute-mode=3 # for EXCLUSIVE_PROCESS

The `nvidia-smi -q` command can also be used to query the current compute mode of the device.

If anyone is seeing this error when the device compute mode is either DEFAULT or EXCLUSIVE_PROCESS, please let me know, because I don't think that should be possible.

StreamExecutor will not work in either EXCLUSIVE_THREAD or PROHIBITED compute mode, but in response to @danpovey's question about shared clusters, EXCLUSIVE_PROCESS mode should be fine.

There are no plans in StreamExecutor to support EXCLUSIVE_THREAD mode because it is listed as deprecated in the nvidia-smi help message. There are also no plans to support PROHIBITED mode because I think that mode prevents the creation of contexts, and StreamExecutor cannot function with that restriction.

In response to @danpovey's suggestion about adding a better error message for this case, I think that's a good idea. I will work on getting a patch up to warn about the device compute mode if `cuCtxSetCurrent` fails and the compute mode is set to an unsupported setting.

**Comment by kramimus** [comment]
Thanks, good to know it should work in EXCLUSIVE_PROCESS.

**Comment by alextp** [comment]
So it sounds like this is working as intended, since StreamExecutor doesn't plan on supporting modes other than EXCLUSIVE_PROCESS.

**Comment by noisychannel** [comment]
Just to confirm, StreamExecutor works with EXCLUSIVE_PROCESS. Hopefully, @danpovey's suggestion about better error messages will be added in soon. It may be hard for people to search for this issue.

**Comment by MidoAssran** [comment]
For anyone using GPU based tensorflow on Compute Canada resources, submitting the job by specifying EXCLUSIVE_PROCESS worked for me.

**Comment by zafarali** [comment]
@MidoAssran Thanks for that! Will try it out.

**Comment by 201power** [comment]
I meet this error  
![image](https://user-images.githubusercontent.com/7299296/31105041-dfe35b10-a795-11e7-9d64-22c460ebaefd.png)
change compute_mode does not solve the issue, any guidance?

**Comment by danpovey** [comment]
I can't really see what it's saying (next time paste as text), but in any
case I don't  know what this might be.  Maybe all the GPUs were already in
use.

**Comment by 201power** [comment]
The GPU might be in use. This happened in a TF session followed immediately by another TF session.

**Comment by dee6600** [comment]
changing compute mode didn't solve the problem, i am getting the same error, my cards are two tesla k80 's

**Comment by zhouchaopku** [comment]
> Hi, I'm the owner of StreamExecutor. Sorry for arriving late to this discussion.
> 
> I believe this problem is caused in all cases by GPUs with their compute mode set to EXCLUSIVE_THREAD (just as mentioned by @zxvix). The solution is to set the compute mode to DEFAULT or EXCLUSIVE_PROCESS, which can be done via one of the following commands:
> 
> ```
> $ nvidia-smi --compute-mode=0 # for DEFAULT
> $ nvidia-smi --compute-mode=3 # for EXCLUSIVE_PROCESS
> ```
> 
> The `nvidia-smi -q` command can also be used to query the current compute mode of the device.
> 
> If anyone is seeing this error when the device compute mode is either DEFAULT or EXCLUSIVE_PROCESS, please let me know, because I don't think that should be possible.
> 
> StreamExecutor will not work in either EXCLUSIVE_THREAD or PROHIBITED compute mode, but in response to @danpovey's question about shared clusters, EXCLUSIVE_PROCESS mode should be fine.
> 
> There are no plans in StreamExecutor to support EXCLUSIVE_THREAD mode because it is listed as deprecated in the nvidia-smi help message. There are also no plans to support PROHIBITED mode because I think that mode prevents the creation of contexts, and StreamExecutor cannot function with that restriction.
> 
> In response to @danpovey's suggestion about adding a better error message for this case, I think that's a good idea. I will work on getting a patch up to warn about the device compute mode if `cuCtxSetCurrent` fails and the compute mode is set to an unsupported setting.

Sorry to trouble you. I have set the mode to DEFAULT (nvidia-smi --compute-mode=0), and it indeed takes effect by the info. from nvidia-smi -q. But I still got the error "tensorflow/stream_executor/cuda/cuda_driver.cc:225] Check failed: CUDA_SUCCESS == cuCtxSetCurrent(cuda_context->context()) (0 vs. 3)".
