### ISSUE TITLE
 Couldn't open CUDA library libcupti.so.7.5

### ISSUE THREAD

**Issue by K-Wu** [tensorflow/tensorflow#5282]
### Environment info

Operating System: Linux Ubuntu 14.04 LTS (64bit)

Installed version of CUDA and cuDNN:  CUDA7.5, cuDNN4
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): 

-rw-r--r-- 1 root root 189170 Apr 23  2016 libcudadevrt.a
lrwxrwxrwx 1 root root     16 Apr 23  2016 libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Apr 23  2016 libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Apr 23  2016 libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Apr 23  2016 libcudart_static.a

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`) c82f4962b9b8ba871880958a459d6d4f3587111b
2. The output of `bazel version` 0.3.2
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

codes are from: https://github.com/tensorflow/tensorflow/raw/r0.11/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py

goes wrong here:

```
if i % 100 == 99:  # Record execution stats
        run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
        run_metadata = tf.RunMetadata()
        summary, _ = sess.run([merged, train_step],
                              feed_dict=feed_dict(True),
                              options=run_options,
                              run_metadata=run_metadata)
        train_writer.add_run_metadata(run_metadata, 'step%03d' % i)
        train_writer.add_summary(summary, i)
        print('Adding run metadata for', i)
```
### Logs or other output that would be helpful

(If logs are large, please upload as attachment or provide link).

```
Accuracy at step 0: 0.1045
Accuracy at step 10: 0.6843
Accuracy at step 20: 0.8074
Accuracy at step 30: 0.8511
Accuracy at step 40: 0.878
Accuracy at step 50: 0.8869
Accuracy at step 60: 0.89
Accuracy at step 70: 0.8928
Accuracy at step 80: 0.893
Accuracy at step 90: 0.8945
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcupti.so.7.5. LD_LIBRARY_PATH: /home/wk15/intel/mkl/lib/intel64:/usr/local/cuda/lib64:/home/wk15/intel/mkl/lib/intel64::/home/wk15/intel/mkl/lib/:/home/wk15/lib:/home/wk15/local/lib:/home/wk15/intel/mkl/lib/:/home/wk15/lib:/home/wk15/local/lib:/home/wk15/boost-1-61-binary/lib
F tensorflow/core/platform/default/gpu/cupti_wrapper.cc:59] Check failed: ::tensorflow::Status::OK() == (::tensorflow::Env::Default()->GetSymbolFromLibrary( GetDsoHandle(), kName, &f)) (OK vs. Not found: /home/wk15/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cuptiActivityRegisterCallbacks)could not find cuptiActivityRegisterCallbacksin libcupti DSO
```

**Comment by drpngx** [comment]
It looks like you need to install the package

```
sudo apt-get install libcupti-dev
```

@gunan this looks like this is a new requirement. `libcupti` appears to be a dev profiling library. Not sure when we introduced this requirement.

**Comment by xinghedyc** [comment]
@drpngx it works for me. thanks!

**Comment by drpngx** [comment]
Nice!

**Comment by gunan** [comment]
@aselle @zheng-xq @martinwicke 
I think this is a clue right here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu#L90

Any idea when/how we started depending on libcupti?

**Comment by drpngx** [comment]
@yifeif

**Comment by brannondorsey** [comment]
I just ran into this issue with a fresh pip install of r0.12 from pip. Running `sudo apt-get install libcupti-dev` installed the missing dependency, however it appears that this is may still be a problem.

**Comment by gunan** [comment]
It is now clear that we are depending on libcupti.
We will add it to the list of our dependencies.

**Comment by brannondorsey** [comment]
Great to hear, thanks for the quick response.

**Comment by thesuperzapper** [comment]
This seems to be an issue with the current Docker-gpu image as well. That is, `libcupti-dev` is missing.

**Comment by BKJackson** [comment]
The libcupti.dylib file is in the CUDA extras folder (e.g., /Developer/NVIDIA/CUDA-8.0/extras/CUPTI/lib/libcupti.8.0.dylib).  

I created a symbolic link from /usr/local/cuda/lib with 

    sudo ln -s /Developer/NVIDIA/CUDA-8.0/extras/CUPTI/lib/libcupti.8.0.dylib libcupti.dylib
