### ISSUE TITLE
tensorflow2.4 can't train 2 model together on 2 different GPU

### ISSUE THREAD

**Issue by nistarlwc** [tensorflow/tensorflow#53153]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows10
- TensorFlow installed from (source or binary): pip install 
- TensorFlow version (use command below): tensorflow-gpu==2.4
- Python version: python3 .8
- CUDA/cuDNN version: cuda11.1 cudnn8.0
- GPU model and memory: RTX2080ti * 2, 12G

**Describe the current behavior**
my train code was tensorflow1.13,  use:    
     `import tensorflow.compat.v1 as tf`     
    ` tf.disable_v2_behavior()` 
Now it can train in tensorflow2.4.  

I try to train 2 modeles with different learning_rate and same batchsize on 2 different GPU,   
first can run with  ` os.environ['CUDA_VISIBLE_DEVICES'] = '0'`,  
but secend use `os.environ['CUDA_VISIBLE_DEVICES'] = '1'`, can't run for `out of memory`

`failed to allocate 9.20G (9874664192 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory`

**Comment by arshPratap** [comment]
@nistarlwc sir , you can try reducing the batch size of the 2 models in the training loop (until it works) .The reason for this error to pop up is that the the gpu runs out of memory while trying to train the models.If the above method doesn't work try taking a look at this issues : 

- [stack overflow](https://stackoverflow.com/questions/39465503/cuda-error-out-of-memory-in-tensorflow/46021109)
- [datascience stack exchange](https://datascience.stackexchange.com/questions/47073/cuda-error-out-of-memory-out-of-memory-how-to-increase-batch-size)

If the error still persists,feel free to notify us.Thanks

**Comment by nistarlwc** [comment]
> @nistarlwc sir , you can try reducing the batch size of the 2 models in the training loop (until it works) .The reason for this error to pop up is that the the gpu runs out of memory while trying to train the models.If the above method doesn't work try taking a look at this issues :
> 
> * [stack overflow](https://stackoverflow.com/questions/39465503/cuda-error-out-of-memory-in-tensorflow/46021109)
> * [datascience stack exchange](https://datascience.stackexchange.com/questions/47073/cuda-error-out-of-memory-out-of-memory-how-to-increase-batch-size)
> 
> If the error still persists,feel free to notify us.Thanks

I tried it.  
can run 8 batchsize in GPU0, and can run 8 batchsize in GPU1.
But when run first model with 8 batchsize in GPU0, secend can't run any batchsize, include 1 batchsize.  
So I think that this is a bug.

May be the problem is:
`2021-11-22 11:46:08.250497: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
INFO:__main__:GPU was detected...`

**Comment by mohantym** [comment]
Hi @nistarlwc! Could you please share the standalone code to reproduce this issue as  it is bit difficult to find the same from above threads ?

**Comment by nistarlwc** [comment]
Problem solved, install cuda11.1.1, and can run it
