### ISSUE TITLE
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by NHQ** [tensorflow/tensorflow#5343]
I have installed cuda 7.5, not 8, but when I get this error when I try to import tensflow (having installed ts binaries for 7.5, gpu, linux).  I have tried un- and re-installing everything repeatedly.  I may have at one time attempted to install cuda 8 in the past, but 7.5 is in my $path.

the complete error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
```

**Comment by aselle** [comment]
What exact binary (url, whl file) did you install? Many (all @gunan?) new binaries will be Cuda 8.0 only. What you are seeing indicates that you downloaded a cuda 8 binary.

**Comment by gunan** [comment]
Correct, starting 0.11.0rc1, all our prebuilt packages are now built for cuda8.
With cuda7.5, you either need to install the 0.11.0rc0 wheel file, or build from sources.

**Comment by aselle** [comment]
Thanks @gunan.

**Comment by NHQ** [comment]
Was yesterday 0rctober 1?

**Comment by allanruin** [comment]
I am using jupyter notebook to use keras which has tensorflow as backend. I have `libcudart.so.8.0` in `usr/local/cuda-8.0/` as showed by below:

    $ locate libcudart.so.8.0
    /usr/local/cuda-8.0/lib64/libcudart.so.8.0
    /usr/local/cuda-8.0/lib64/libcudart.so.8.0.44

but still, when the import part of keras run, I got 

	/home/allan/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py in swig_import_helper()
	     22         if fp is not None:
	     23             try:
	---> 24                 _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
	     25             finally:
	     26                 fp.close()

	ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Could anyone help?

**Comment by gunan** [comment]
There is very little information here.
Could you create a new issue, filling in all the fields required by the template?

**Comment by hadsed** [comment]
Perhaps you need to make a symbolic link from `/usr/local/cuda` to `/usr/local/cuda-8.0`? That seemed to fix the issue for me

**Comment by prateek-agarwal** [comment]
Traceback (most recent call last):
  File "evaluate.py", line 3, in <module>
    import transform, numpy as np, vgg, pdb, os
  File "src/transform.py", line 1, in <module>
    import tensorflow as tf, pdb
  File "/home/prateek/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/prateek/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/prateek/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/prateek/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/prateek/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by gunan** [comment]
If you are still seeing this problem, please file a new issue.
From your error message, it does not look related to me.

**Comment by silentsnooc** [comment]
I have installed `cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb` but as I try to import tensorflow I get
```
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
```

I do not have a `/usr/local/cuda/` directoryafter installation

```
stefan@stefan-pc:~$ ls -la /usr/local/
total 44
drwxr-xr-x 11 root root 4096 Feb  9 19:19 .
drwxr-xr-x 13 root root 4096 Feb  2 19:32 ..
drwxr-xr-x  3 root root 4096 Feb  9 19:34 bin
drwxr-xr-x  3 root root 4096 Feb  9 19:19 cuda-8.0
...
```

The `cuda-8.0` directory only contains

```
stefan@stefan-pc:~$ ls -la /usr/local/cuda-8.0/
total 12
drwxr-xr-x  3 root root 4096 Feb  9 19:19 .
drwxr-xr-x 11 root root 4096 Feb  9 19:19 ..
drwxr-xr-x  3 root root 4096 Jän  9 20:43 targets
```

Which I think comes from cuDNN.

I don't quite understand why it does not find `libcudart.so.8.0`. Not sure what the `.deb` file installed if not CUDA.

**Comment by aselle** [comment]
@silentsnooc,   you probably should open a new issue with full context of your install environment ( we have an issue template). However, here is generic information:

1. `dpkg -L <package>` will list files installed by installing a deb. You can also use `find` or `locate` to find the file if that doesn't help.  

2. If you can't find libcudart.so.8.0, install CUDA properly (possibly manually). If you cannot run NVidia CUDA demos, CUDA is not installed properly. Sometimes it is better to use the NVidia shell script install method rather than a debian package to install both the NVidia driver and the CUDA toolkit. I find that works more reliably. However, if you do this, you must be careful to remove all .deb related cuda information. I'd suggest finding a good tutorial online on installing NVidia kernel drivers and cuda toolkit and following them. 

3. Try TensorFlow. If it can't find find  libcudart.so.8.0, add the directory that contains it to LD_LIBRARY_PATH environment variable.

Your issue is likely  a  generic CUDA installation issue rather than a TensorFlow specific problem.  Installing nvidia drivers and cuda on Linux is harder than one would like. Sometimes it goes smoothly, but often it does not.

Thanks!

**Comment by silentsnooc** [comment]
@aselle Hi! Thank you very much for that information. I'll take a look at it. It's frustrating because I just setup the whole thing on another machine but like you said: sometimes it goes smoothly and sometimes not. I'll try to go with the shell approach that you suggested.

**Comment by Jaspereclipse** [comment]
One possible case I've found is that the environment (IDE) you run your Python does not have access to the file. If you try import tensorflow in CLI and it works, then probably you should consider this possibility.

**Comment by maxss280** [comment]
Double check that you have exported the LD_LIBRARY_PATH
`export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64`

Was fighting this issue too and that solved it for me. Existed and everything lol

**Comment by badjano** [comment]
I also am getting the ImportError but I have located libcudart.so.8.0 inside /usr/local/cuda-8.0/lib64 and I have the symlink cuda pointing to cuda-8.0.

I have received a warning when installing cuda 8 that I needed to have at least nvidia driver 361, which I ignored because I have 367.57

**Comment by gunan** [comment]
Import Error can have a lot of different underlying issues. We will need to see the full error message.
Could you file a new issue, by filling out the full template?

**Comment by badjano** [comment]
No problem... Yesterday I tried to install the graphics driver that came with cuda, but my gtx 970 stopped working with ubuntu, today I'm trying to figure out why, but If I come across that error again, I'll file a new issue, thanks

**Comment by sayadyaghoobi** [comment]
i got same error, but with caffe !, i installed cuda 8 and for some application it worked fine but for caffe this issue got me confusing:

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    import caffe
  File "/Caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/Caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

**Comment by badjano** [comment]
Sorry, I forgot to come back here, the problem was that I forgot to export the path to cuda lib, here is the solution:

http://askubuntu.com/questions/889015/cant-install-cuda-8-but-have-correct-nvidia-driver-ubuntu-16

**Comment by smolendawid** [comment]
For me, the only thing that works is to type
sudo ldconfig /usr/local/cuda/lib64

**Comment by jaydenso** [comment]
sudo ldconfig /usr/local/cuda/lib64  works for me.

**Comment by thisHemit** [comment]
sudo ldconfig /usr/local/cuda/lib64 works for me.
OS: LinuxMint 18 (Sarah)
cuda_version: 8.0
cuDNN_version: 5.1

**Comment by Namlich** [comment]
sudo ldconfig /usr/local/cuda/lib64 works for me as well, but i have to do it EVERYTIME i've restarted my computer.. Any tips how to avoid this?

**Comment by alirzsedghi** [comment]
sudo ldconfig /usr/local/cuda/lib64 works for me also, but i need to do it once in a while (no matter if i restart or not). weird !!

**Comment by Damian89** [comment]
@sedghi same here... ldconfig helped, but after a while (hours, days) theres no effect...

**Comment by markroxor** [comment]
If you are using cuda-9.0 try `sudo apt install nvidia-cuda-dev` .
This is the only thing worked for me,

**Comment by alan23273850** [comment]
@maxss280's method works for me! In fact I have written some path settings, but with wrong syntax. So, this step, checking if environment variables are valid, is very important.

BTW, when something must be redone for each time computer restarted, I think writing the command into .bashrc file may be a kind of solution.

**Comment by codelibra** [comment]
@maxss280 Works!
`export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64`
or
`export LD_LIBRARY_PATH=/usr/local/cuda/lib64`

**Comment by arch-rh1** [comment]
I have **Cuda 9.0 , cudnn 7.0 on Ubuntu 16.04**.
I built Tensorflow 1.6 since the release notes states it has pre-compiled binaries for cuda 9.0 and cudnn 7.0.

`ldconfig -v: libcublas.so.9.0`

upon running:

> import tensorflow as tf

I still get the error:
`ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
`
My Questions:

**1. Shouldn't Tensorflow 1.6 work with cuda 9.0/ cudnn 7.0 ?
2. Is there any way I can continue using cuda 9.0 ?? I really cannot use 8.0**

**Comment by arch-rh1** [comment]
I'm not sure why it is looking for libcublas.so.8.0. Is there any cache stored from which `sudo -H pip install tensorflow-gpu` builds the package?  I do uninstall tensorflow-gpu each time using `sudo -H pip uninstall tensorflow-gpu` each time. So I'm not sure what's going on...

I built from source using bazel too. Still the same error!!!!! 

Any thoughts??

**Comment by estelleaf** [comment]
Hi there,
On my computer I had :

cudnn5.1
cuda8.0
When importing tensorflow, I had the same error ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
To overcome this issue I installed tensorflow 1.4 instead of 1.6
But then I had another issue : libcudnn.so.6: cannot open shared object file: No such file or directory
This was because I had cudnn5.1 as required but actually it needs cudnn6
Here are the steps to uninstall cudnn5.1 and install cudnn6:
1- Uninstall cudnn 5.1
rm -f /usr/include/cudnn.h
rm -f /usr/lib/x86_64-linux-gnu/libcudnn
rm -f /usr/local/cuda-/lib64/libcudnn
2- Install cudnn6
After having subscribed to nvdia, go to here https://developer.nvidia.com/rdp/cudnn-download and download cudnn6 for cuda8 and then go to the folder where you downloaded the cudnn and do :
$ tar xvzf cudnn-8.0-linux-x64-v5.1-ga.tgz
$ sudo cp -P cuda/include/cudnn.h /usr/local/cuda/include
$ sudo cp -P cuda/lib64/libcudnn /usr/local/cuda/lib64
$ sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*

Now you should have tensorflow
Try it on typing in the console:
$python

import tensorflow
If you want to work in anaconda and the error persists , try :
$jupyter notebook --generate-config

then you can find the name of the directory where you have your config file (Ill call it

) and open /jupyter_notebook_config.py and add at the top :
import os
c = get_config()
os.environ['LD_LIBRARY_PATH'] = '/usr/local/cuda-8.0/lib64:usr/local/cuda-8.0/lib64/libcudart.so.8.0'
c.Spawner.env.update('LD_LIBRARY_PATH')

Now it should work...

Here are the websites that helped me:

https://askubuntu.com/questions/952075/how-to-upgrade-tensorflow-to-v1-3-cudnn-cuda-upgrade
https://developer.nvidia.com/rdp/cudnn-download
https://medium.com/@ikekramer/installing-cuda-8-0-and-cudnn-5-1-on-ubuntu-16-04-6b9f284f6e77
https://stackoverflow.com/questions/43984135/tensorflow-gpu-can-not-be-called-from-jupyterhub-jupyter-notebook-why

**Comment by Bingohong** [comment]
maybe this was because the path usr/local/lib dont have the .so  file ,so you can cp the .so file to /usr/local/lib then ldconfig.
- sudo cp  /lusr/local/cuda-9.0/libcudart.so.9.0 /usr/local/lib 
- sudo ldconfig
these steps works

**Comment by stephenbalaban** [comment]
If you're using Ubuntu 16.04 or Ubuntu 18.04 and want to get TensorFlow with GPU support installed, there is a deb package for that in the Lambda Stack repository.

You can install the repository and the package with this line:


    LAMBDA_REPO=$(mktemp) && \
    wget -O${LAMBDA_REPO} https://lambdal.com/static/files/lambda-stack-repo.deb && \
    sudo dpkg -i ${LAMBDA_REPO} && rm -f ${LAMBDA_REPO} && \
    sudo apt-get update && sudo apt-get install -y lambda-stack-cuda

What it does:

 1. Download and installs the Lambda Stack Repository (essentially adds a file to /etc/apt/sources.list.d/)
 2. Updates apt and installs the `lambda-stack-cuda` package.
 3. Installs CUDA, Drivers, CuDNN, and TensorFlow with CuDNN and GPU support into the proper system level directories. You won't need to modify your `LD_LIBRARY_PATH` or `PATH` as the shared libraries are placed in directories that `ld` already checks at link time.

**Comment by linpanusst** [comment]
I have solve the problem. I think it is because the tensorflow ==1.4 , so I uninstall tensorflow-gpu==1.4 in coach (any ohter env)and then install the latest tensorflow gpu and the problem done.

pip3 uninstall tensorflow-gpu
pip3 install tensorflow-gpu

I was using Carla in Coach and running demos.

**Comment by noorkhokhar99** [comment]
> I have installed `cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb` but as I try to import tensorflow I get
> 
> ```
> ImportError: Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
>   File "/usr/lib/python3.5/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
> ```
> I do not have a `/usr/local/cuda/` directoryafter installation
> 
> ```
> stefan@stefan-pc:~$ ls -la /usr/local/
> total 44
> drwxr-xr-x 11 root root 4096 Feb  9 19:19 .
> drwxr-xr-x 13 root root 4096 Feb  2 19:32 ..
> drwxr-xr-x  3 root root 4096 Feb  9 19:34 bin
> drwxr-xr-x  3 root root 4096 Feb  9 19:19 cuda-8.0
> ...
> ```
> The `cuda-8.0` directory only contains
> 
> ```
> stefan@stefan-pc:~$ ls -la /usr/local/cuda-8.0/
> total 12
> drwxr-xr-x  3 root root 4096 Feb  9 19:19 .
> drwxr-xr-x 11 root root 4096 Feb  9 19:19 ..
> drwxr-xr-x  3 root root 4096 Jän  9 20:43 targets
> ```
> Which I think comes from cuDNN.
> 
> I don't quite understand why it does not find `libcudart.so.8.0`. Not sure what the `.deb` file installed if not CUDA.


Try:  conda install -c anaconda cudatoolkit

**Comment by sudheerExperiments** [comment]
Hello,

I had the same issue. I fixed it by adding the below command to the '**.bashrc**' file.

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.0/lib64/

**System configuration:**

```
Ubuntu 16.04 LTS
Tensorflow GPU 2.0beta1
Cuda 10.0
cuDNN 7.6.0 for Cuda 10.0
```

I  used conda to configure my system.
