### ISSUE TITLE
failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED on a AWS p2.xlarge instance

### ISSUE THREAD

**Issue by beeva-ivanfernandez** [tensorflow/tensorflow#5354]
Hi,

I have been running docker images on a **Centos 7.0 AWS p2.xlarge** instance. I have previously installed on it:
CUDA: **cuda-repo-rhel7-8.0.44-1.x86_64.rpm**
NVIDIA **drivers 361.42**

I have also installed **nvidia-docker** [following instructions](https://github.com/NVIDIA/nvidia-docker)

I have successfully run all notebooks from Docker images (as fas as I've tried tensorflow/tensorflow:latest-devel-gpu and tensorflow/tensorflow:latest-gpu):

Running **tensorflow** version within the docker containter: **0.11.0rc2**
**Bazel** version: Build label: **0.3.2**
root@de73edc73418:~# nvidia-smi -l
Wed Nov  2 12:02:54 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 361.42     Driver Version: 361.42         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:00:1E.0     Off |                    0 |
| N/A   57C    P0    70W / 149W |  10948MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

However when I try to launch a [Single GPU computing example with tensorflow](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/5_MultiGPU/multigpu_basics.py) and get the following error:

`I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_3: /job:localhost/replica:0/task:0/gpu:0
MatMul_4: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_4: /job:localhost/replica:0/task:0/gpu:0
MatMul_5: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_5: /job:localhost/replica:0/task:0/gpu:0
MatMul_6: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_6: /job:localhost/replica:0/task:0/gpu:0
MatMul_7: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_7: /job:localhost/replica:0/task:0/gpu:0
MatMul_8: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_8: /job:localhost/replica:0/task:0/gpu:0
MatMul_9: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_9: /job:localhost/replica:0/task:0/gpu:0
AddN: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] AddN: /job:localhost/replica:0/task:0/cpu:0
E tensorflow/stream_executor/cuda/cuda_blas.cc:367] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support
E tensorflow/stream_executor/cuda/cuda_blas.cc:367] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support
`

Not sure if is something related to Nvidia drivers, OS or some library mismatch. Any idea?

**Comment by beeva-ivanfernandez** [comment]
Working installing cudnn and adding them to the path :).

tar -zxf cudnn-8.0-linux-x64-v5.1.tgz
sudo cp cuda/include/cudnn.h /usr/local/cuda/include
sudo cp cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
export CUDA_HOME=/usr/local/cuda

**Comment by beeva-ivanfernandez** [comment]
'Ran out of memory' exception masked 'failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED' exception when running a large tensorflow calculation. 

When running a smaller matrix multiplication example CUBLAS exception arises again

**Comment by aselle** [comment]
- Can you run TensorFlow binary from outside the Docker container? 
- CUBLAS_STATUS_NOT_INITIALIZED is a classic CUDA runtime not setup properly problem. It's best to remove the complication of docker if you can. 
- Avoid using latest tags, instead use specific versions. You can also try nightly if you want a bleeding edge version, but you probably want to name or tag the container id once you get a working config if you are using nightly.

**Comment by beeva-ivanfernandez** [comment]
thank you Aselle

- Yes, no problem with it
- Unfortunately that's part of my approach. I am using nvidia-docker to decouple the whole thing and running from containers in AWS.
- I will follow your advice and it'll give a try to previous versions.

**Comment by aselle** [comment]
I really have no ability to test this, so I am marking it as community support. You might try asking on stackoverflow which might have more AWS docker users.

- Make sure you docker pull to make sure your container is up to date.
- Make sure to upgrade your nvidia-docker install.
- I would also try making sure you can run a non-tensorflow cublas program (perhaps one of the nvidia demos).

**Comment by beeva-ivanfernandez** [comment]
thx @aselle. I'll give a try on stackoverflow

**Comment by yufengg** [comment]
if you're still having trouble, try adding `/usr/local/cuda/extras/CUPTI/lib64` to your `LD_LIBRARY_PATH`. I had the same error and this fixed it (I was on mac though, so verify that directory on your system)

On mac it was `/usr/local/cuda/extras/CUPTI/lib`

**Comment by bushibushi** [comment]
Thanks @yufengg !!! How did you come up with this fix ?

**Comment by laventura** [comment]
Hi @yufengg -- Is this ```/usr/local/cuda/extras/CUPTI/lib64``` applicable for MacbookPro (with Nvidia GPU) as well? Thanks.

I'm getting this same error:
```
[I 23:59:13.425 NotebookApp] Kernel restarted: 82276eab-ae23-4637-8050-b40a3097613e
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.dylib locally
[I 00:00:40.514 NotebookApp] Saving file at /15_Style_Transfer.ipynb
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] OS X does not support NUMA - returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GT 750M
major: 3 minor: 0 memoryClockRate (GHz) 0.9255
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.52GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_blas.cc:372] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support
[I 00:02:40.823 NotebookApp] Saving file at /15_Style_Transfer.ipynb
```

**Comment by paulstey** [comment]
Hi @laventura, I'm not sure if you found a solution yet, but switching from Python 2.7 to Python 3.5 worked for me when I was getting that error.

**Comment by 714586886** [comment]
I  added /usr/local/cuda/extras/CUPTI/lib64 to my LD_LIBRARY_PATH,but don't work.
And my environment is:
Ubuntu 16.04    Tensorflow1.0.0  CUDA8.0   Cudnn5.1
How to fix this problem?

**Comment by zixia** [comment]
I ran into this problem when I'm running <https://github.com/davidsandberg/facenet/> inside docker image `tensorflow/tensorflow:latest-gpu-py3`.

LD_LIBRARY_PATH is already included CUPTI but still get this wrong.

However, the jupyter can run without any problem.

**Comment by subashp** [comment]
I faced the same issue and none of the above method worked out for me. What I realized is the memory allocation is failing. I reduced my GPU memory percentage from per_process_gpu_memory_fraction=0.95 to per_process_gpu_memory_fraction=0.8 to get past it.

**Comment by jeremy-rutman** [comment]
yes this seems to be out-of-memory being misreported

**Comment by yiran-THU** [comment]
@laventura 
HI,I come across the same problem ,and this method `/usr/local/cuda/extras/CUPTI/lib64` doesn't work for me.
Have you solved this problem now?

**Comment by ahmed-shariff** [comment]
Setting `per_process_gpu_memory_fraction` does fix the problem. Though the fraction does not have to be so low. As xorg uses only 5MB, I was able to get away with setting the fraction to 0.99

**Comment by hzxie** [comment]
Maybe the following command helps:

    sudo rm -rf .nv/

Good luck.

**Comment by ahangchen** [comment]
I try @hzxie 's suggestion and CUBLAS__STATUS_NOT_INITIALIZED changes to OOM.

**Comment by jeremy-rutman** [comment]
OOM is out of memory - so if you now turn down per_process_gpu_memory_fraction or put your net on a diet you may get past it.

**Comment by 1160300630** [comment]
I try @hzxie's suggestion and i works!! thanks

**Comment by duyvuleo** [comment]
I experienced the same problem. I confirm that @hzxie 's suggestion works like a charm. Thanks!

**Comment by utkrist** [comment]
Thank you VERY VERY MUCH @hzxie.

**Comment by zhenglilei** [comment]
@hzxie   A very good suggestion!
In my case, it is 
`sudo rm -rf ~/.nv/`

**Comment by jiapei100** [comment]
@yufengg

This solved my issue... Thanks...

**Comment by Frankxsh** [comment]
> Hi,
> 
> I have been running docker images on a **Centos 7.0 AWS p2.xlarge** instance. I have previously installed on it:
> CUDA: **cuda-repo-rhel7-8.0.44-1.x86_64.rpm**
> NVIDIA **drivers 361.42**
> 
> I have also installed **nvidia-docker** [following instructions](https://github.com/NVIDIA/nvidia-docker)
> 
> I have successfully run all notebooks from Docker images (as fas as I've tried tensorflow/tensorflow:latest-devel-gpu and tensorflow/tensorflow:latest-gpu):
> 
> Running **tensorflow** version within the docker containter: **0.11.0rc2**
> **Bazel** version: Build label: **0.3.2**
> root@de73edc73418:~# nvidia-smi -l
> Wed Nov 2 12:02:54 2016
> +------------------------------------------------------+
> | NVIDIA-SMI 361.42 Driver Version: 361.42 |
> |-------------------------------+----------------------+----------------------+
> | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 Tesla K80 Off | 0000:00:1E.0 Off | 0 |
> | N/A 57C P0 70W / 149W | 10948MiB / 11519MiB | 0% Default |
> +-------------------------------+----------------------+----------------------+
> 
> However when I try to launch a [Single GPU computing example with tensorflow](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/5_MultiGPU/multigpu_basics.py) and get the following error:
> 
> `I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_3: /job:localhost/replica:0/task:0/gpu:0 MatMul_4: /job:localhost/replica:0/task:0/gpu:0 I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_4: /job:localhost/replica:0/task:0/gpu:0 MatMul_5: /job:localhost/replica:0/task:0/gpu:0 I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_5: /job:localhost/replica:0/task:0/gpu:0 MatMul_6: /job:localhost/replica:0/task:0/gpu:0 I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_6: /job:localhost/replica:0/task:0/gpu:0 MatMul_7: /job:localhost/replica:0/task:0/gpu:0 I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_7: /job:localhost/replica:0/task:0/gpu:0 MatMul_8: /job:localhost/replica:0/task:0/gpu:0 I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_8: /job:localhost/replica:0/task:0/gpu:0 MatMul_9: /job:localhost/replica:0/task:0/gpu:0 I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul_9: /job:localhost/replica:0/task:0/gpu:0 AddN: /job:localhost/replica:0/task:0/cpu:0 I tensorflow/core/common_runtime/simple_placer.cc:819] AddN: /job:localhost/replica:0/task:0/cpu:0 E tensorflow/stream_executor/cuda/cuda_blas.cc:367] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support E tensorflow/stream_executor/cuda/cuda_blas.cc:367] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support `
> 
> Not sure if is something related to Nvidia drivers, OS or some library mismatch. Any idea?

Administrator Rights。
I open pycharm in Admin, and it works and no wrong!(Although I don't know why
