### ISSUE TITLE
[TF:TRT] Tensorflow Docker 2.7.0-gpu has incompatible TRT version 8.0.0

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/tensorflow#53697]
**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from: binary
- TensorFlow version: 2.7.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 11.2
- GPU model and memory: NVIDIA T4, 16GB

**Steps to reproduce the issue**
Setup tensorflow/tensorflow:2.7.0-gpu container
```
$ sudo docker run -it --name tf270 --gpus all tensorflow/tensorflow:2.7.0-gpu
```
Test TF/TRT
```
$ apt list --installed | grep infer

libnvinfer-plugin8/unknown,now 8.0.0-1+cuda11.0 amd64 [installed,upgradable to: 8.2.0-1+cuda11.4]
libnvinfer8/unknown,now 8.0.0-1+cuda11.0 amd64 [installed,upgradable to: 8.2.0-1+cuda11.4]

$ python3
import tensorflow as tf
import tensorflow.compiler as tf_cc
tf_cc.tf2tensorrt._pywrap_py_utils.get_linked_tensorrt_version()

(7, 2, 2)
```
As you can see the installed TRT version is 8.0.0 but Tensorflow was built and linked with TRT 7.2.2.

@DEKHTIARJonathan  @bixia1 @sanjoy

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you look at this issue?

**Comment by Saduf2019** [comment]
@apivovarov 
This is already tracked in your issue [link](https://github.com/tensorflow/tensorflow/issues/53529#issuecomment-1006301417).
Can we have this in one issue so we do not duplicate it.

**Comment by apivovarov** [comment]
Issue [53529](https://github.com/tensorflow/tensorflow/issues/53529) says "TRT Converter not working". My (this) issue is more general - TF/TRT is not working in TF 2.7.0 Docker image in General. 

Question. Where is Docker file for TF 2.7.0 Docker image? I can open PR to fix it.

**Comment by Saduf2019** [comment]
@apivovarov 
Please feel free to open a PR for the fix.

**Comment by apivovarov** [comment]
@Saduf2019 Do you know which Dockerfile is used to build TF 2.7.0 Docker image?

**Comment by SuryanarayanaY** [comment]
> @Saduf2019 Do you know which Dockerfile is used to build TF 2.7.0 Docker image?

Hi @apivovarov ,

Please find the [source](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/tf_sig_build_dockerfiles) for files that used to build docker images. As Tf2.7 version is outdated most likely the issue was resolved with latest stable releases.Please try the Docker Image of any latest release(>2.10v) and let us know if you still observed this version mismatch error please come back and confirm us.

Thank you!

**Comment by SuryanarayanaY** [comment]
For TF2.12v the linked TF:TRT version is 8.4.3 which is mentioned at source [here](https://colab.research.google.com/gist/SuryanarayanaY/ba67167f00fa3d77df8884163d3baf00/53697.ipynb) from docker files.

The same is also tested and outputs TF:TRT version as 8.4.3 for both TF2.12v and tf-nightly versions as well. Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/ba67167f00fa3d77df8884163d3baf00/53697.ipynb) also. The same applicable to docker images also.

**Comment by SuryanarayanaY** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks.
