### ISSUE TITLE
EfficientDet D0 pre-build TRT engine failed. TF 2.7.0, TRT 7.2.3

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/tensorflow#53730]
Ubuntu 18.04
Tensorflow 2.7.0
Cuda 11.1.1
TenosrRT 7.2.3.4
CuDNN 8.1.1.33
Cuda Compute Capability 7.5
Hardware: g4dn.8xlarge (Tesla Turing T4 Tensor Core)

TF2 Model is from TensorFlow 2 Detection Model Zoo - [EfficientDet D0 512x512](http://download.tensorflow.org/models/object_detection/tf2/20200711/efficientdet_d0_coco17_tpu-32.tar.gz)

I tried to convert saved model to TRT model and then pre-build TRT engine. The conversion worked fine but pre-build TRT engine failed.
```
import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt

conversion_params = trt.TrtConversionParams()

converter = trt.TrtGraphConverterV2(
    input_saved_model_dir="saved_model",
    conversion_params=conversion_params)

converter.convert()

import numpy as np
def my_input_fn():
    input_shapes = [(1,512,512,3)]
    for shape in input_shapes:
        yield [np.zeros(shape).astype(np.uint8)]

converter.build(input_fn=my_input_fn)
```
Error:
```
>>> converter.build(input_fn=my_input_fn)
2022-01-12 05:55:45.849139: I tensorflow/compiler/tf2tensorrt/common/utils.cc:58] Linked TensorRT version: 7.2.3
2022-01-12 05:55:45.849218: I tensorflow/compiler/tf2tensorrt/common/utils.cc:60] Loaded TensorRT version: 7.2.3
2022-01-12 05:57:02.621885: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.630204: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.630291: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:945] TF-TRT Warning: Engine creation for StatefulPartitionedCall/EfficientDet-D0/bifpn/TRTEngineOp_0_17 failed. The native segment will be used instead. Reason: INTERNAL: Failed to build TensorRT engine
2022-01-12 05:57:02.630314: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:797] TF-TRT Warning: Engine retrieval for input shapes: [[1,64,64,64], [1,32,32,64]] failed. Running native segment for StatefulPartitionedCall/EfficientDet-D0/bifpn/TRTEngineOp_0_17
2022-01-12 05:57:02.644741: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8101
2022-01-12 05:57:02.647927: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-01-12 05:57:02.778160: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.778302: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.778392: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:945] TF-TRT Warning: Engine creation for StatefulPartitionedCall/TRTEngineOp_0_19 failed. The native segment will be used instead. Reason: INTERNAL: Failed to build TensorRT engine
2022-01-12 05:57:02.778412: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:797] TF-TRT Warning: Engine retrieval for input shapes: [[1,64,32,32], [1,64,64,64], [1,64,32,32]] failed. Running native segment for StatefulPartitionedCall/TRTEngineOp_0_19
2022-01-12 05:57:02.808375: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.808446: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.808480: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:945] TF-TRT Warning: Engine creation for StatefulPartitionedCall/WeightSharedConvolutionalBoxPredictor/ClassPredictionTower/conv2d_1/TRTEngineOp_0_41 failed. The native segment will be used instead. Reason: INTERNAL: Failed to build TensorRT engine
2022-01-12 05:57:02.808495: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:797] TF-TRT Warning: Engine retrieval for input shapes: [[1,64,64,64]] failed. Running native segment for StatefulPartitionedCall/WeightSharedConvolutionalBoxPredictor/ClassPredictionTower/conv2d_1/TRTEngineOp_0_41
2022-01-12 05:57:02.809402: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.809463: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.809507: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:945] TF-TRT Warning: Engine creation for StatefulPartitionedCall/WeightSharedConvolutionalBoxPredictor/BoxPredictionTower/conv2d_1/TRTEngineOp_0_31 failed. The native segment will be used instead. Reason: INTERNAL: Failed to build TensorRT engine
2022-01-12 05:57:02.809522: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:797] TF-TRT Warning: Engine retrieval for input shapes: [[1,64,64,64]] failed. Running native segment for StatefulPartitionedCall/WeightSharedConvolutionalBoxPredictor/BoxPredictionTower/conv2d_1/TRTEngineOp_0_31
2022-01-12 05:57:02.821888: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.821946: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.821980: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:945] TF-TRT Warning: Engine creation for StatefulPartitionedCall/WeightSharedConvolutionalBoxPredictor/ClassPredictionTower/conv2d_2/TRTEngineOp_0_46 failed. The native segment will be used instead. Reason: INTERNAL: Failed to build TensorRT engine
2022-01-12 05:57:02.821995: W tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:797] TF-TRT Warning: Engine retrieval for input shapes: [[1,64,64,64]] failed. Running native segment for StatefulPartitionedCall/WeightSharedConvolutionalBoxPredictor/ClassPredictionTower/conv2d_2/TRTEngineOp_0_46
2022-01-12 05:57:02.823642: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.823698: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.825524: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.825598: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2022-01-12 05:57:02.832321: E tensorflow/stream_executor/dnn.cc:764] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(5553): 'cudnnPoolingForward( cudnn.handle(), pooling_desc.handle(), &alpha, src_desc.handle(), input_data.opaque(), &beta, dest_desc.handle(), output_data->opaque())'
2022-01-12 05:57:02.833347: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at trt_engine_op.cc:542 : INTERNAL: {{function_node StatefulPartitionedCall/TRTEngineOp_0_21_native_segment}} dnn PoolForward launch failed
	 [[{{node StatefulPartitionedCall/EfficientDet-D0/bifpn/node_23/3_up_lvl_5/input_3_up_lvl_4/downsample_max_x2/MaxPool}}]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1223, in build
    func(*map(ops.convert_to_tensor, inp))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1707, in __call__
    return self._call_impl(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/wrap_function.py", line 249, in _call_impl
    args, kwargs, cancellation_manager)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1725, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1774, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 603, in call
    ctx=ctx)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) INTERNAL:  dnn PoolForward launch failed
	 [[{{node StatefulPartitionedCall/EfficientDet-D0/bifpn/node_23/3_up_lvl_5/input_3_up_lvl_4/downsample_max_x2/MaxPool}}]]
	 [[StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/TRTEngineOp_0_30/_168]]
  (1) INTERNAL:  dnn PoolForward launch failed
	 [[{{node StatefulPartitionedCall/EfficientDet-D0/bifpn/node_23/3_up_lvl_5/input_3_up_lvl_4/downsample_max_x2/MaxPool}}]]
	 [[StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/non_max_suppression_with_scores_77/NonMaxSuppressionV5/_584]]
0 successful operations.
0 derived errors ignored. [Op:__inference_pruned_135734]

Function call stack:
pruned -> pruned
```

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by christopherbate** [comment]
This can happen if you have many processes running and run out of GPU memory, leaving other libraries like CUDNN and CUBLAS no available memory for initialization. Are you running multiple builds at the same time?

**Comment by apivovarov** [comment]
Chris, thank you for the info about possible GPU OOM issue.
To answer your questions - I run one engine build.

I was able to solve the issue with TRT engine build for EfficientDet D0 model by setting memory growth config param to True
```
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```
I also checked used GPU memory during the engine build with `nvidia-smi pmon`. At one moment it showed `mem 99%` for 1 second.
```
# gpu        pid  type    sm   mem   enc   dec   command
# Idx          #   C/G     %     %     %     %   name
    0       8288     C    98    99     -     -   python3.7
```
I also checked peak memory usage after the engine was built. It showed only 4.06 GB peak usage.
```
tf.config.experimental.get_memory_info('GPU:0')
{'current': 53,567,488, 'peak': 4,361,667,840}
```
I'm not sure how `99% mem` reported by nvidia-smi and only 4.06 GB peak usage reported by TF can be explained. GPU has 16GB of memory.

But anyway, the problem with engine building is solved. Saved TRT model (with pre-built engine) works and it works slightly faster than the original (non-converted) TF model.
