### ISSUE TITLE
modprobe: ERROR: ../libkmod/libkmod-module.c:832 kmod_module_insert_module() could not find module by name='nvidia_367_uvm'

### ISSUE THREAD

**Issue by KeithYin** [tensorflow/tensorflow#5473]
here is the details:
modprobe: ERROR: ../libkmod/libkmod-module.c:832 kmod_module_insert_module() could not find module by name='nvidia_367_uvm'
modprobe: ERROR: could not insert 'nvidia_367_uvm': Unknown symbol in module, or unknown parameter (see dmesg)
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:140] kernel driver does not appear to be running on this host (gzhao-b1208): /proc/driver/nvidia/version does not exist
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.

it worked fine yesterday.

**Comment by WenchenLi** [comment]
Hi @KeithYin  I have exactly the same issue, how did you fix it?

**Comment by KeithYin** [comment]
i just reinstall the nvidia driver, then that issue is gone.@WenchenLi
