### ISSUE TITLE
CUDNN_STATUS_BAD_PARAM in version 0.11.0rc1

### ISSUE THREAD

**Issue by Goolley** [tensorflow/tensorflow#5476]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

Following steps i did:
1. Install tensorflow
2. Execute the source example to make sure everything is fine
3. Run srcnn.py in  https://github.com/liliumao/Tensorflow-srcnn/blob/master/srcnn.py

Then I encounter the error message
F tensorflow/stream_executor/cuda/cuda_dnn.cc:444] could not set cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM

What is more strange is that the program did trained 160 times and then show the error message.
And it only happens after iteration 160 times.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
#2033 #1787

### Environment info
Operating System : CentOS 7.2.1511+ tensorflow 0.11.0rc1

Installed version of CUDA and cuDNN: CUDA 8.0 & cuDNN 5.1
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11.0rc1

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
https://github.com/liliumao/Tensorflow-srcnn/blob/master/srcnn.py

### What other attempted solutions have you tried?
1. Transfer the cuda version to 7.5, however the tf.0.11.0rc1 needs cuda 8.0.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties:
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.3925
pciBusID 0000:03:00.0
Total memory: 3.94GiB
Free memory: 3.82GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:03:00.0)
2016-11-08 06:08:00.274964: step 0, duration = 0.457
2016-11-08 06:08:00.705598: step 10, duration = 0.020
2016-11-08 06:08:01.106745: step 20, duration = 0.019
2016-11-08 06:08:01.492362: step 30, duration = 0.019
2016-11-08 06:08:01.849530: step 40, duration = 0.018
2016-11-08 06:08:02.245288: step 50, duration = 0.019
2016-11-08 06:08:02.629120: step 60, duration = 0.019
2016-11-08 06:08:02.979037: step 70, duration = 0.018
2016-11-08 06:08:03.341024: step 80, duration = 0.018
2016-11-08 06:08:03.706578: step 90, duration = 0.019
2016-11-08 06:08:04.098436: step 100, duration = 0.019
2016-11-08 06:08:04.476913: step 110, duration = 0.019
2016-11-08 06:08:04.895861: step 120, duration = 0.019
2016-11-08 06:08:05.262154: step 130, duration = 0.019
2016-11-08 06:08:05.670712: step 140, duration = 0.019
2016-11-08 06:08:06.018086: step 150, duration = 0.018
2016-11-08 06:08:06.387210: step 160, duration = 0.018
F tensorflow/stream_executor/cuda/cuda_dnn.cc:444] could not set cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM
[1]    3640 abort (core dumped)  python3 srcnn.py

**Comment by aselle** [comment]
@zheng-xq  please take a look and suggest fixes.

**Comment by Goolley** [comment]
I found the bug.
It was because the input data array dead at 170 iteration.
It did not have a traditional python error, but a tensorflow ones.

Thanks guys a lot.

**Comment by barrykui** [comment]
@Goolley Hi, what do you mean by `the input data array dead`? I also encounter the error message now.

**Comment by chhwang** [comment]
@barrykui In my case, it is when I feed an empty array in a placeholder.

**Comment by Goolley** [comment]
@barrykui My input array is not an legal array since i have some mistake on  the index.
