### ISSUE TITLE
tensorflow/core/kernels/conv_ops_gpu.cc:336] None of the algorithms provided by cuDNN frontend heuristics worked

### ISSUE THREAD

**Issue by WingsOfPanda** [tensorflow/tensorflow#55059]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.9.9
- Bazel version (if compiling from source): bazel 5.0.0
- GCC/Compiler version (if compiling from source): g++ (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
- CUDA/cuDNN version: 11.4
- GPU model and memory: NVIDIA GeForce RTX 3090 sm_8.6 with 25447170048B RAM and 82 cores

**Describe the problem**

after I build and installed, when I run model with conv3d ops, it will return the following msg:

> 2022-02-25 09:26:56.521222: W tensorflow/core/kernels/conv_ops_gpu.cc:336] None of the algorithms provided by cuDNN frontend heuristics worked; trying fallback algorithms.  Conv: batch: 1
> in_depths: 1
> out_depths: 40
> in: 256
> in: 256
> in: 256
> data_format: 1
> filter: 3
> filter: 3
> filter: 3
> dilation: 1
> dilation: 1
> dilation: 1
> stride: 1
> stride: 1
> stride: 1
> padding: 2
> padding: 2
> padding: 2
> dtype: DT_FLOAT
> group_count: 1
> device_identifier: "NVIDIA GeForce RTX 3090 sm_8.6 with 25447170048B RAM and 82 cores"
> version: 1
> 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

anything that use conv3d ops

**Any other info / logs**

the model, like unet, can be finished even with the above msg. But I think this msg shows that cuDNN is not envolved? and hence the gpu is not used?

**Comment by mohantym** [comment]
Hi @WingsOfPanda ! Could you please try again after a building from a source with Cuda 11.2 and CudNN 8.1 
 with 2.8 Branch. Please use Bazel 4.2.1 while building from [the source](https://www.tensorflow.org/install/source). Thank you!

**Comment by WingsOfPanda** [comment]
Hi @mohantym . Thank you for your suggestions. I changed to coda 11.2 and cudnn 8.1 and it worked! I still use Bazel 5.0.0 btw.

**Comment by tangrug** [comment]
I solve this problem by install tensorflow using pip rather than conda.
try "pip install tensorflow-gpu"
