### ISSUE TITLE
tensorflow/examples/learn/text_classification_builtin_rnn_model.py references removed TensorFlowRNNClassifier

### ISSUE THREAD

**Issue by darrengarvey** [tensorflow/tensorflow#5541]
### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

$ ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root 560184 May 19 01:44 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 May 19 01:47 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root     19 May 19 01:47 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rw-r--r-- 1 root root 394472 May 19 01:44 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root 737516 May 19 01:44 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root     37 Sep 12 12:36 /usr/local/cuda/lib64/libcudnn.so -> /usr/lib/x86_64-linux-gnu/libcudnn.so
lrwxrwxrwx 1 root root     39 Sep 12 12:36 /usr/local/cuda/lib64/libcudnn.so.5 -> /usr/lib/x86_64-linux-gnu/libcudnn.so.5
lrwxrwxrwx 1 root root     43 Sep 12 12:36 /usr/local/cuda/lib64/libcudnn.so.5.1.5 -> /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.5
lrwxrwxrwx 1 root root     43 Sep 12 12:38 /usr/local/cuda/lib64/libcudnn_static.a -> /usr/lib/x86_64-linux-gnu/libcudnn_static.a
lrwxrwxrwx 1 root root     46 Sep 12 12:38 /usr/local/cuda/lib64/libcudnn_static_v5.a -> /usr/lib/x86_64-linux-gnu/libcudnn_static_v5.a

If installed from source, provide 

1. git rev-parse HEAD = 2ac978d2532dd359dd7ebbd27ac13dfa147d755d
2. $ bazel version
Build label: 0.4.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 17:54:14 2016 (1478109254)
Build timestamp: 1478109254
Build timestamp as int: 1478109254

The file `tensorflow/examples/learn/text_classification_builtin_rnn_model.py` references `TensorFlowRNNClassifier`, which was removed in dfb1bfe6aec58700547f6525289090c737bfe453 so presumably this example should also be removed.

That commit doesn't mention why the class was removed and it looks quite useful. What is the replacement for it? `get_rnn_model()`? I can provide a PR to remove the example but wanted to check first if actually there is another word-level RNN example for `tf.contrib.learn` to point to?

**Comment by rishsriv** [comment]
Are there any updates on this?

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
