### ISSUE TITLE
Problem with gpu memory allocation

### ISSUE THREAD

**Issue by JamesJacquesDiego** [tensorflow/tensorflow#56019]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.9.8

### CUDA/cuDNN version

11.2

### GPU model and memory

notebook version of nvidia gtx 1060 (6GB)

### Current Behaviour?

```shell
I use tensorflow for image classification (20 classes) with convolutions. My dataset contains about 20000 train images and 5000 test images. Images (RGB) have 200x256 pixels. When I run script to train model using cpu everything seems fine. However when I try run script using gpu, after loading my training and test data I get error on model_fit function.

Num GPUs Available:  1
2022-05-04 17:58:58.482057: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-04 17:59:03.655618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4634 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx.x, compute capability: 6.1
1 Physical GPUs, 1 Logical GPUs
Path: D:/Dataset/seg_train
Loading seg_train
Path: D:/Dataset/seg_test
Loading seg_test
2022-05-04 18:02:48.971100: W tensorflow/core/common_runtime/bfc_allocator.cc:462] Allocator (GPU_0_bfc) ran out of memory trying to allocate 10.44GiB (rounded to 11206656000)requested by op _EagerConst
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
2022-05-04 18:02:48.996013: I tensorflow/core/common_runtime/bfc_allocator.cc:1010] BFCAllocator dump for GPU_0_bfc
2022-05-04 18:02:48.996173: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (256):  Total Chunks: 16, Chunks in use: 16. 4.0KiB allocated for chunks. 4.0KiB in use in bin. 392B client-requested in use in bin.
2022-05-04 18:02:48.996308: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (512):  Total Chunks: 1, Chunks in use: 1. 512B allocated for chunks. 512B in use in bin. 512B client-requested in use in bin.
2022-05-04 18:02:48.996473: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (1024):         Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2022-05-04 18:02:48.996629: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (2048):         Total Chunks: 2, Chunks in use: 1. 7.0KiB allocated for chunks. 3.5KiB in use in bin. 3.4KiB client-requested in use in bin.
2022-05-04 18:02:48.996889: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (4096):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:48.997493: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (8192):         Total Chunks: 1, Chunks in use: 1. 9.5KiB allocated for chunks. 9.5KiB in use in bin. 9.5KiB client-requested in use in bin.
2022-05-04 18:02:48.997960: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (16384):        Total Chunks: 1, Chunks in use: 0. 19.0KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:48.998482: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (32768):        Total Chunks: 2, Chunks in use: 1. 79.5KiB allocated for chunks. 36.0KiB in use in bin. 36.0KiB client-requested in use in bin.
2022-05-04 18:02:48.999113: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (65536):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:48.999710: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (131072):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.000273: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (262144):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.000742: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (524288):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.001208: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (1048576):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.001671: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (2097152):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.002131: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (4194304):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.002700: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (8388608):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.004034: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (16777216):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.004682: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (33554432):     Total Chunks: 1, Chunks in use: 1. 44.56MiB allocated for chunks. 44.56MiB in use in bin. 44.56MiB client-requested in use in bin.
2022-05-04 18:02:49.005383: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (67108864):     Total Chunks: 1, Chunks in use: 0. 89.12MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.007520: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (134217728):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.008016: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (268435456):    Total Chunks: 1, Chunks in use: 0. 4.39GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-04 18:02:49.008477: I tensorflow/core/common_runtime/bfc_allocator.cc:1033] Bin for 10.44GiB was 256.00MiB, Chunk State:
2022-05-04 18:02:49.008888: I tensorflow/core/common_runtime/bfc_allocator.cc:1039]   Size: 4.39GiB | Requested Size: 0B | in_use: 0 | bin_num: 20, prev:   Size: 44.56MiB | Requested Size: 44.56MiB | in_use: 1 | bin_num: -1
2022-05-04 18:02:49.009335: I tensorflow/core/common_runtime/bfc_allocator.cc:1046] Next region of size 4859428864
2022-05-04 18:02:49.025604: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00000 of size 256 next 1
2022-05-04 18:02:49.025772: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00100 of size 1280 next 2
2022-05-04 18:02:49.026373: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00600 of size 256 next 3
2022-05-04 18:02:49.026991: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00700 of size 256 next 4
2022-05-04 18:02:49.028407: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00800 of size 256 next 5
2022-05-04 18:02:49.028560: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00900 of size 256 next 6
2022-05-04 18:02:49.029196: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00a00 of size 256 next 9
2022-05-04 18:02:49.029937: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00b00 of size 256 next 10
2022-05-04 18:02:49.030556: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00c00 of size 256 next 11
2022-05-04 18:02:49.031054: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00d00 of size 256 next 14
2022-05-04 18:02:49.031553: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00e00 of size 256 next 15
2022-05-04 18:02:49.031906: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00f00 of size 512 next 16
2022-05-04 18:02:49.032334: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01100 of size 256 next 19
2022-05-04 18:02:49.032719: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01200 of size 256 next 20
2022-05-04 18:02:49.033158: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01300 of size 256 next 21
2022-05-04 18:02:49.033523: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01400 of size 256 next 24
2022-05-04 18:02:49.033892: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01500 of size 256 next 25
2022-05-04 18:02:49.034323: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01600 of size 256 next 26
2022-05-04 18:02:49.034824: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b03a01700 of size 3584 next 7
2022-05-04 18:02:49.035472: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a02500 of size 3584 next 8
2022-05-04 18:02:49.035923: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b03a03300 of size 19456 next 23
2022-05-04 18:02:49.036957: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07f00 of size 9728 next 22
2022-05-04 18:02:49.039251: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b03a0a500 of size 44544 next 13
2022-05-04 18:02:49.039789: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a15300 of size 36864 next 12
2022-05-04 18:02:49.040234: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b03a1e300 of size 93454336 next 18
2022-05-04 18:02:49.040779: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0933e300 of size 46727168 next 17
2022-05-04 18:02:49.041233: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b0bfce300 of size 4719123712 next 18446744073709551615
2022-05-04 18:02:49.041719: I tensorflow/core/common_runtime/bfc_allocator.cc:1071]      Summary of in-use Chunks by size:
2022-05-04 18:02:49.042440: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 16 Chunks of size 256 totalling 4.0KiB
2022-05-04 18:02:49.042831: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 512 totalling 512B
2022-05-04 18:02:49.043889: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 1280 totalling 1.2KiB
2022-05-04 18:02:49.044474: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 3584 totalling 3.5KiB
2022-05-04 18:02:49.044901: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 9728 totalling 9.5KiB
2022-05-04 18:02:49.045330: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 36864 totalling 36.0KiB
2022-05-04 18:02:49.045784: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 46727168 totalling 44.56MiB
2022-05-04 18:02:49.046196: I tensorflow/core/common_runtime/bfc_allocator.cc:1078] Sum Total of in-use chunks: 44.62MiB
2022-05-04 18:02:49.046552: I tensorflow/core/common_runtime/bfc_allocator.cc:1080] total_region_allocated_bytes_: 4859428864 memory_limit_: 4859428864 available bytes: 0 curr_region_allocation_bytes_: 9718857728
2022-05-04 18:02:49.046902: I tensorflow/core/common_runtime/bfc_allocator.cc:1086] Stats:
Limit:                      4859428864
InUse:                        46783232
MaxInUse:                    140225792
NumAllocs:                          34
MaxAllocSize:                 46727168
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2022-05-04 18:02:49.047317: W tensorflow/core/common_runtime/bfc_allocator.cc:474] ***_________________________________________________________________________________________________
Traceback (most recent call last):
  File "D:\DatasetProcessing\ImageClassification.py", line 394, in <module>
    main()
  File "D:\DatasetProcessing\ImageClassification.py", line 387, in main
    first_model()
  File "D:\DatasetProcessing\ImageClassification.py", line 162, in first_model
    history = model.fit(train_images, train_labels, batch_size=2, epochs=4)
  File "D:\WinPython\WPy64-3980\python-3.9.8.amd64\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\WinPython\WPy64-3980\python-3.9.8.amd64\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.

I have a notebook with nvidia gtx 1060 (6GB) gpu. I've installed the newest driver available for this gpu and cuda version 11.2. I checked gpu values in task manager when script was running but it was 1% up to 5%. It looks like tensorflow is not using gpu at all.

I tried to use:

TF_GPU_ALLOCATOR=cuda_malloc_async

and

memory_limit=4096

and

allow_growth=True

I've also decreased batch_size from 128 to 2. But neither of these options worked.
```

### Standalone code to reproduce the issue

```shell
model = tf.keras.Sequential([
            tf.keras.layers.Conv2D(32, (3,3), activation = 'relu', input_shape = (200, 256, 3)),
            tf.keras.layers.MaxPooling2D(2,2),
            tf.keras.layers.Conv2D(32, (3,3), activation = 'relu'),
            tf.keras.layers.MaxPooling2D(2,2),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(128, activation = tf.nn.relu),
            tf.keras.layers.Dense(20, activation = tf.nn.softmax)
        ])
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(train_images, train_labels, batch_size=2, epochs=4)
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@JamesJacquesDiego ,
Usually, this error raises when GPU memory is full.Please clear the memory and test your code.Also please take a look at this [issue1](https://github.com/tensorflow/tensorflow/issues/52086#issuecomment-1013298718) and [issue2](https://github.com/aymericdamien/TensorFlow-Examples/issues/38) with the similar error.Thanks!

**Comment by JamesJacquesDiego** [comment]
Thank you for your suggestions. But I've checked gpu usage in task manager when script was running. And the usage was from 1% to 5%. It looks like tensorflow is not using gpu memory at all.

In the info there was information that tensorflow tried to allocate about 10GB of memory (but I have only 6GB gpu). I've also tried memory_limit=4096 and allow_growth=True.
PS
When I use the same code but with cpu there is no problem.

**Comment by Kubasinska** [comment]
This looks like a GPU related OOM. Here is a more reproducible example based on what you provided earlier. You could try varying the input size and see if reducing the input size starts the network training.

```python
import tensorflow as tf
import numpy as np
rand = np.random.default_rng()

x = np.random.rand(1000, 200, 256, 3)
y = np.array([rand.integers(20) for i in range(1000)])

model = tf.keras.Sequential([
            tf.keras.layers.Conv2D(32, (3,3), activation = 'relu', input_shape = (200, 256, 3)),
            tf.keras.layers.MaxPooling2D(2,2),
            tf.keras.layers.Conv2D(32, (3,3), activation = 'relu'),
            tf.keras.layers.MaxPooling2D(2,2),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(128, activation = tf.nn.relu),
            tf.keras.layers.Dense(20, activation = tf.nn.softmax)
        ])
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(x, y, batch_size=2, epochs=4)
```

**Comment by JamesJacquesDiego** [comment]
I've added three lines of code after y variable:
config = tf.compat.v1.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction=0.5
sess = tf.compat.v1.Session(config=config) 
   
I've run your code and first 5 times it worked, but after that I got error. Here is what i get when it works:

2022-05-11 02:29:31.044577: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

2022-05-11 02:29:31.044577: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-11 02:29:37.276618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:29:37.415072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
Epoch 1/4

```
2022-05-11 02:29:31.044577: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-11 02:29:37.276618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:29:37.415072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:29:42.112058: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
500/500 [==============================] - 13s 12ms/step - loss: 3.0854 - accuracy: 0.0520 
Epoch 2/4
500/500 [==============================] - 6s 12ms/step - loss: 2.9949 - accuracy: 0.0510
Epoch 3/4
500/500 [==============================] - 6s 12ms/step - loss: 2.9938 - accuracy: 0.0550
Epoch 4/4
500/500 [==============================] - 6s 11ms/step - loss: 2.9932 - accuracy: 0.0580
```

And here is what I get when it doesn't work:


```

2022-05-11 02:29:31.044577: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-11 02:29:37.276618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx.x, compute capability: 6.1
2022-05-11 02:29:37.415072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:29:42.112058: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
2022-05-11 02:31:19.739728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:32:20.290753: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:32:50.716189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:33:19.014200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
Traceback (most recent call last):

  File "D:scripts\gpu_test.py", line 33, in <module>
    history = model.fit(x, y, batch_size=2, epochs=4)

  File "D:WinPython\WPy64-3980\python-3.9.8.amd64\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "D:WinPython\WPy64-3980\python-3.9.8.amd64\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.


2022-05-11 02:29:31.044577: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-11 02:29:37.276618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:29:37.415072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:29:42.112058: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
2022-05-11 02:31:19.739728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:32:20.290753: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:32:50.716189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:33:19.014200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3071 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: xxxx:xx:xx:x, compute capability: 6.1
2022-05-11 02:33:29.241618: W tensorflow/core/common_runtime/bfc_allocator.cc:462] Allocator (GPU_0_bfc) ran out of memory trying to allocate 585.94MiB (rounded to 614400000)requested by op _EagerConst
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
Current allocation summary follows.
Current allocation summary follows.
2022-05-11 02:33:29.241729: I tensorflow/core/common_runtime/bfc_allocator.cc:1010] BFCAllocator dump for GPU_0_bfc
2022-05-11 02:33:29.241792: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (256): 	Total Chunks: 107, Chunks in use: 107. 26.8KiB allocated for chunks. 26.8KiB in use in bin. 4.6KiB client-requested in use in bin.
2022-05-11 02:33:29.241846: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (512): 	Total Chunks: 13, Chunks in use: 13. 6.5KiB allocated for chunks. 6.5KiB in use in bin. 6.5KiB client-requested in use in bin.
2022-05-11 02:33:29.241897: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2022-05-11 02:33:29.241948: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (2048): 	Total Chunks: 10, Chunks in use: 10. 35.0KiB allocated for chunks. 35.0KiB in use in bin. 33.8KiB client-requested in use in bin.
2022-05-11 02:33:29.241998: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (4096): 	Total Chunks: 4, Chunks in use: 3. 23.8KiB allocated for chunks. 17.5KiB in use in bin. 10.1KiB client-requested in use in bin.
2022-05-11 02:33:29.242049: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (8192): 	Total Chunks: 16, Chunks in use: 16. 158.0KiB allocated for chunks. 158.0KiB in use in bin. 153.4KiB client-requested in use in bin.
2022-05-11 02:33:29.242098: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (16384): 	Total Chunks: 1, Chunks in use: 0. 20.0KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242343: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (32768): 	Total Chunks: 14, Chunks in use: 13. 534.0KiB allocated for chunks. 492.0KiB in use in bin. 468.0KiB client-requested in use in bin.
2022-05-11 02:33:29.242411: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (65536): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242460: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (131072): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242504: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (262144): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242548: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (524288): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242591: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242631: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242671: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (4194304): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242711: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242752: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242800: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (33554432): 	Total Chunks: 14, Chunks in use: 13. 650.33MiB allocated for chunks. 604.50MiB in use in bin. 604.50MiB client-requested in use in bin.
2022-05-11 02:33:29.242845: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (67108864): 	Total Chunks: 1, Chunks in use: 0. 93.00MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242890: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (134217728): 	Total Chunks: 1, Chunks in use: 0. 167.44MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-05-11 02:33:29.242937: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (268435456): 	Total Chunks: 4, Chunks in use: 3. 2.11GiB allocated for chunks. 1.72GiB in use in bin. 1.72GiB client-requested in use in bin.
2022-05-11 02:33:29.242978: I tensorflow/core/common_runtime/bfc_allocator.cc:1033] Bin for 585.94MiB was 256.00MiB, Chunk State: 
2022-05-11 02:33:29.243026: I tensorflow/core/common_runtime/bfc_allocator.cc:1039]   Size: 402.54MiB | Requested Size: 2.96MiB | in_use: 0 | bin_num: 20, prev:   Size: 585.94MiB | Requested Size: 585.94MiB | in_use: 1 | bin_num: -1
2022-05-11 02:33:29.243062: I tensorflow/core/common_runtime/bfc_allocator.cc:1046] Next region of size 3221127168
2022-05-11 02:33:29.243140: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00000 of size 256 next 1
2022-05-11 02:33:29.243175: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00100 of size 1280 next 2
2022-05-11 02:33:29.243205: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00600 of size 256 next 3
2022-05-11 02:33:29.243232: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00700 of size 256 next 4
2022-05-11 02:33:29.243267: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00800 of size 256 next 5
2022-05-11 02:33:29.243389: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00900 of size 256 next 6
2022-05-11 02:33:29.243430: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00a00 of size 256 next 9
2022-05-11 02:33:29.243460: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00b00 of size 256 next 10
2022-05-11 02:33:29.243489: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00c00 of size 256 next 11
2022-05-11 02:33:29.243517: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00d00 of size 256 next 14
2022-05-11 02:33:29.243544: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00e00 of size 256 next 15
2022-05-11 02:33:29.243573: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a00f00 of size 512 next 16
2022-05-11 02:33:29.243601: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01100 of size 256 next 19
2022-05-11 02:33:29.243629: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01200 of size 256 next 20
2022-05-11 02:33:29.243656: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01300 of size 256 next 21
2022-05-11 02:33:29.243684: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01400 of size 256 next 24
2022-05-11 02:33:29.243712: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01500 of size 256 next 25
2022-05-11 02:33:29.243740: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01600 of size 256 next 26
2022-05-11 02:33:29.243767: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01700 of size 256 next 29
2022-05-11 02:33:29.243795: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01800 of size 256 next 30
2022-05-11 02:33:29.243823: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01900 of size 256 next 31
2022-05-11 02:33:29.243850: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01a00 of size 256 next 32
2022-05-11 02:33:29.243878: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01b00 of size 256 next 33
2022-05-11 02:33:29.243906: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01c00 of size 256 next 34
2022-05-11 02:33:29.243933: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01d00 of size 256 next 35
2022-05-11 02:33:29.243961: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01e00 of size 256 next 36
2022-05-11 02:33:29.243989: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a01f00 of size 256 next 38
2022-05-11 02:33:29.244017: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a02000 of size 256 next 39
2022-05-11 02:33:29.244045: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a02100 of size 512 next 41
2022-05-11 02:33:29.244072: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a02300 of size 256 next 43
2022-05-11 02:33:29.244100: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a02400 of size 256 next 7
2022-05-11 02:33:29.244128: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a02500 of size 3584 next 8
2022-05-11 02:33:29.244156: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03300 of size 256 next 90
2022-05-11 02:33:29.244184: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03400 of size 256 next 91
2022-05-11 02:33:29.244211: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03500 of size 256 next 92
2022-05-11 02:33:29.244239: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03600 of size 256 next 93
2022-05-11 02:33:29.244276: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03700 of size 256 next 94
2022-05-11 02:33:29.244305: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03800 of size 256 next 95
2022-05-11 02:33:29.244337: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03900 of size 256 next 106
2022-05-11 02:33:29.244368: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03a00 of size 256 next 112
2022-05-11 02:33:29.244396: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03b00 of size 256 next 113
2022-05-11 02:33:29.244424: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03c00 of size 256 next 104
2022-05-11 02:33:29.244452: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03d00 of size 256 next 108
2022-05-11 02:33:29.244481: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a03e00 of size 5376 next 28
2022-05-11 02:33:29.244508: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a05300 of size 3584 next 37
2022-05-11 02:33:29.244537: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a06100 of size 3584 next 44
2022-05-11 02:33:29.244564: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a06f00 of size 256 next 46
2022-05-11 02:33:29.244593: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07000 of size 512 next 48
2022-05-11 02:33:29.244620: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07200 of size 256 next 50
2022-05-11 02:33:29.244648: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07300 of size 256 next 51
2022-05-11 02:33:29.244676: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07400 of size 256 next 52
2022-05-11 02:33:29.244703: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07500 of size 256 next 53
2022-05-11 02:33:29.244731: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07600 of size 256 next 54
2022-05-11 02:33:29.244758: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07700 of size 256 next 55
2022-05-11 02:33:29.244786: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07800 of size 256 next 56
2022-05-11 02:33:29.244813: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07900 of size 256 next 57
2022-05-11 02:33:29.244841: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07a00 of size 256 next 58
2022-05-11 02:33:29.244869: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07b00 of size 256 next 76
2022-05-11 02:33:29.244896: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07c00 of size 256 next 73
2022-05-11 02:33:29.244924: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07d00 of size 512 next 67
2022-05-11 02:33:29.244952: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a07f00 of size 256 next 70
2022-05-11 02:33:29.244980: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a08000 of size 256 next 66
2022-05-11 02:33:29.245008: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a08100 of size 256 next 115
2022-05-11 02:33:29.245035: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a08200 of size 256 next 23
2022-05-11 02:33:29.245063: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a08300 of size 10240 next 22
2022-05-11 02:33:29.245092: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a0ab00 of size 43008 next 13
2022-05-11 02:33:29.245121: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a15300 of size 36864 next 12
2022-05-11 02:33:29.245149: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b03a1e300 of size 48758784 next 40
2022-05-11 02:33:29.245176: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0689e300 of size 10240 next 42
2022-05-11 02:33:29.245204: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068a0b00 of size 36864 next 45
2022-05-11 02:33:29.245231: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068a9b00 of size 10240 next 49
2022-05-11 02:33:29.245363: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068ac300 of size 256 next 64
2022-05-11 02:33:29.245404: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068ac400 of size 6912 next 60
2022-05-11 02:33:29.245433: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068adf00 of size 3584 next 68
2022-05-11 02:33:29.245462: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068aed00 of size 8192 next 74
2022-05-11 02:33:29.245490: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068b0d00 of size 256 next 72
2022-05-11 02:33:29.245517: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068b0e00 of size 256 next 77
2022-05-11 02:33:29.245545: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068b0f00 of size 512 next 79
2022-05-11 02:33:29.245573: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068b1100 of size 11264 next 75
2022-05-11 02:33:29.245600: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068b3d00 of size 10240 next 69
2022-05-11 02:33:29.245628: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068b6500 of size 43008 next 65
2022-05-11 02:33:29.245655: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068c0d00 of size 36864 next 63
2022-05-11 02:33:29.245683: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068c9d00 of size 256 next 80
2022-05-11 02:33:29.245710: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068c9e00 of size 3584 next 81
2022-05-11 02:33:29.245738: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068cac00 of size 256 next 82
2022-05-11 02:33:29.245766: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068cad00 of size 36864 next 83
2022-05-11 02:33:29.245794: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d3d00 of size 256 next 84
2022-05-11 02:33:29.245822: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d3e00 of size 512 next 85
2022-05-11 02:33:29.245850: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d4000 of size 10240 next 86
2022-05-11 02:33:29.245877: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d6800 of size 256 next 87
2022-05-11 02:33:29.245905: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d6900 of size 512 next 59
2022-05-11 02:33:29.245933: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d6b00 of size 256 next 88
2022-05-11 02:33:29.245961: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d6c00 of size 256 next 111
2022-05-11 02:33:29.245989: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d6d00 of size 256 next 105
2022-05-11 02:33:29.246017: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d6e00 of size 256 next 97
2022-05-11 02:33:29.246044: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d6f00 of size 256 next 100
2022-05-11 02:33:29.246072: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d7000 of size 256 next 102
2022-05-11 02:33:29.246100: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d7100 of size 512 next 117
2022-05-11 02:33:29.246127: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d7300 of size 256 next 118
2022-05-11 02:33:29.246155: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d7400 of size 256 next 120
2022-05-11 02:33:29.246183: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d7500 of size 256 next 122
2022-05-11 02:33:29.246210: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d7600 of size 256 next 103
2022-05-11 02:33:29.246238: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d7700 of size 3584 next 109
2022-05-11 02:33:29.246276: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068d8500 of size 8192 next 99
2022-05-11 02:33:29.246414: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068da500 of size 12288 next 98
2022-05-11 02:33:29.246455: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068dd500 of size 10240 next 89
2022-05-11 02:33:29.246484: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068dfd00 of size 43008 next 101
2022-05-11 02:33:29.246512: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068ea500 of size 36864 next 96
2022-05-11 02:33:29.246540: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068f3500 of size 3584 next 119
2022-05-11 02:33:29.246568: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068f4300 of size 36864 next 121
2022-05-11 02:33:29.246597: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068fd300 of size 512 next 123
2022-05-11 02:33:29.246624: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068fd500 of size 10240 next 124
2022-05-11 02:33:29.246652: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068ffd00 of size 256 next 125
2022-05-11 02:33:29.246680: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068ffe00 of size 256 next 126
2022-05-11 02:33:29.246708: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b068fff00 of size 256 next 127
2022-05-11 02:33:29.246735: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900000 of size 256 next 128
2022-05-11 02:33:29.246763: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900100 of size 256 next 129
2022-05-11 02:33:29.246791: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900200 of size 256 next 130
2022-05-11 02:33:29.246819: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900300 of size 256 next 131
2022-05-11 02:33:29.246846: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900400 of size 256 next 132
2022-05-11 02:33:29.246874: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900500 of size 256 next 144
2022-05-11 02:33:29.246902: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900600 of size 256 next 134
2022-05-11 02:33:29.246930: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900700 of size 256 next 141
2022-05-11 02:33:29.246958: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900800 of size 512 next 149
2022-05-11 02:33:29.246986: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900a00 of size 256 next 139
2022-05-11 02:33:29.247014: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900b00 of size 256 next 151
2022-05-11 02:33:29.247042: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900c00 of size 256 next 145
2022-05-11 02:33:29.247070: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900d00 of size 256 next 138
2022-05-11 02:33:29.247098: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06900e00 of size 5632 next 148
2022-05-11 02:33:29.247126: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06902400 of size 3584 next 153
2022-05-11 02:33:29.247154: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06903200 of size 8192 next 152
2022-05-11 02:33:29.247182: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06905200 of size 256 next 135
2022-05-11 02:33:29.247209: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06905300 of size 256 next 142
2022-05-11 02:33:29.247237: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06905400 of size 512 next 154
2022-05-11 02:33:29.247410: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06905600 of size 11264 next 146
2022-05-11 02:33:29.247503: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06908200 of size 10240 next 133
2022-05-11 02:33:29.247584: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0690aa00 of size 43008 next 150
2022-05-11 02:33:29.247687: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06915200 of size 36864 next 140
2022-05-11 02:33:29.247751: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0691e200 of size 256 next 155
2022-05-11 02:33:29.247782: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0691e300 of size 3584 next 156
2022-05-11 02:33:29.247811: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0691f100 of size 256 next 157
2022-05-11 02:33:29.247840: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0691f200 of size 36864 next 158
2022-05-11 02:33:29.247868: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06928200 of size 256 next 159
2022-05-11 02:33:29.247896: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06928300 of size 512 next 160
2022-05-11 02:33:29.247924: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06928500 of size 10240 next 161
2022-05-11 02:33:29.247952: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692ad00 of size 256 next 162
2022-05-11 02:33:29.247981: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692ae00 of size 256 next 163
2022-05-11 02:33:29.248009: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692af00 of size 256 next 164
2022-05-11 02:33:29.248037: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b000 of size 256 next 165
2022-05-11 02:33:29.248065: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b100 of size 256 next 166
2022-05-11 02:33:29.248093: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b200 of size 256 next 167
2022-05-11 02:33:29.248121: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b300 of size 256 next 168
2022-05-11 02:33:29.248149: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b400 of size 256 next 169
2022-05-11 02:33:29.248177: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b500 of size 256 next 170
2022-05-11 02:33:29.248206: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b600 of size 256 next 173
2022-05-11 02:33:29.248233: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b700 of size 256 next 184
2022-05-11 02:33:29.248272: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692b800 of size 512 next 179
2022-05-11 02:33:29.248300: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692ba00 of size 256 next 174
2022-05-11 02:33:29.248328: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692bb00 of size 256 next 171
2022-05-11 02:33:29.248356: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692bc00 of size 256 next 188
2022-05-11 02:33:29.248384: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692bd00 of size 256 next 182
2022-05-11 02:33:29.248412: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b0692be00 of size 6400 next 190
2022-05-11 02:33:29.248440: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0692d700 of size 3584 next 176
2022-05-11 02:33:29.248468: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b0692e500 of size 20480 next 185
2022-05-11 02:33:29.248495: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06933500 of size 10240 next 181
2022-05-11 02:33:29.248523: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b06935d00 of size 43008 next 175
2022-05-11 02:33:29.248551: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b06940500 of size 36864 next 187
2022-05-11 02:33:29.248579: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b06949500 of size 48057856 next 18
2022-05-11 02:33:29.248607: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0971e300 of size 48758784 next 17
2022-05-11 02:33:29.248636: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0c59e300 of size 48758784 next 116
2022-05-11 02:33:29.248670: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b0f41e300 of size 48758784 next 114
2022-05-11 02:33:29.248701: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b1229e300 of size 48758784 next 107
2022-05-11 02:33:29.248730: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b1511e300 of size 48758784 next 137
2022-05-11 02:33:29.248757: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b17f9e300 of size 48758784 next 143
2022-05-11 02:33:29.248785: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b1ae1e300 of size 48758784 next 147
2022-05-11 02:33:29.248812: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b1dc9e300 of size 97517568 next 178
2022-05-11 02:33:29.248840: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b2399e300 of size 48758784 next 186
2022-05-11 02:33:29.248867: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at b2681e300 of size 175570944 next 27
2022-05-11 02:33:29.248895: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b30f8e300 of size 48758784 next 47
2022-05-11 02:33:29.248923: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b33e0e300 of size 48758784 next 78
2022-05-11 02:33:29.248950: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b36c8e300 of size 48758784 next 61
2022-05-11 02:33:29.248978: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b39b0e300 of size 48758784 next 71
2022-05-11 02:33:29.249006: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b3c98e300 of size 614400000 next 62
2022-05-11 02:33:29.249034: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b6137e300 of size 614400000 next 110
2022-05-11 02:33:29.249061: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at b85d6e300 of size 614400000 next 136
2022-05-11 02:33:29.249090: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at baa75e300 of size 422092032 next 18446744073709551615
2022-05-11 02:33:29.249119: I tensorflow/core/common_runtime/bfc_allocator.cc:1071]      Summary of in-use Chunks by size: 
2022-05-11 02:33:29.249164: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 107 Chunks of size 256 totalling 26.8KiB
2022-05-11 02:33:29.249202: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 13 Chunks of size 512 totalling 6.5KiB
2022-05-11 02:33:29.249252: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 1280 totalling 1.2KiB
2022-05-11 02:33:29.249291: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 10 Chunks of size 3584 totalling 35.0KiB
2022-05-11 02:33:29.249326: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 5376 totalling 5.2KiB
2022-05-11 02:33:29.249361: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 5632 totalling 5.5KiB
2022-05-11 02:33:29.249396: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 6912 totalling 6.8KiB
2022-05-11 02:33:29.249431: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 3 Chunks of size 8192 totalling 24.0KiB
2022-05-11 02:33:29.249467: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 10 Chunks of size 10240 totalling 100.0KiB
2022-05-11 02:33:29.249503: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 2 Chunks of size 11264 totalling 22.0KiB
2022-05-11 02:33:29.249538: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 12288 totalling 12.0KiB
2022-05-11 02:33:29.249572: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 9 Chunks of size 36864 totalling 324.0KiB
2022-05-11 02:33:29.249607: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 4 Chunks of size 43008 totalling 168.0KiB
![image1-before running script](https://user-images.githubusercontent.com/44622349/167747019-e74d87d2-5612-409c-a945-d3d65631782f.PNG)
![image2-running script](https://user-images.githubusercontent.com/44622349/167747021-1682e710-809e-4e3f-b2d2-dac0e3ab5576.PNG)
![image3-error](https://user-images.githubusercontent.com/44622349/167747022-8cd3dbd1-1541-4b77-9681-a9e12a4d5ab6.PNG)

2022-05-11 02:33:29.249643: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 13 Chunks of size 48758784 totalling 604.50MiB
2022-05-11 02:33:29.249679: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 3 Chunks of size 614400000 totalling 1.72GiB
2022-05-11 02:33:29.249716: I tensorflow/core/common_runtime/bfc_allocator.cc:1078] Sum Total of in-use chunks: 2.31GiB
2022-05-11 02:33:29.249757: I tensorflow/core/common_runtime/bfc_allocator.cc:1080] total_region_allocated_bytes_: 3221127168 memory_limit_: 3221127168 available bytes: 0 curr_region_allocation_bytes_: 6442254336
2022-05-11 02:33:29.249807: I tensorflow/core/common_runtime/bfc_allocator.cc:1086] Stats: 
Limit:                      3221127168
InUse:                      2477818880
MaxInUse:                   2575324928
NumAllocs:                      432324
MaxAllocSize:                614400000
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2022-05-11 02:33:29.249874: W tensorflow/core/common_runtime/bfc_allocator.cc:474] **_***********__***____****************************************************************_____________

```

I used OHM to check gpu memory values. I've added images.

**Comment by Kubasinska** [comment]
The lines you added have no effect, I assume you read [this issue](https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory), you need to use the instructions related to TensorFlow 2. However, it seems that you don't have enough memory on the GPU. 

To test this assertion you could change the input size( e.g.  `x = np.random.rand(1000, 200, 256, 3)` to  `x = np.random.rand(1000, 100, 100, 3)` ) and see if the error persis

**Comment by JamesJacquesDiego** [comment]
So those lines don't work?
```
config = tf.compat.v1.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction=0.5
sess = tf.compat.v1.Session(config=config)
```

The code you've pasted  (with input size you set) works first few times and after 4th or 5th time I get error. 

It works after I've change input size to `x = np.random.rand(1000, 100, 100, 3)` as you advised but reducing resolution of my images in my network is not a solution. What if I will need more images in the future to train my network or if smaller resolution would be bad for classification results?

When I tried to run the script with my network then I get info that tensorflow tries to allocate about 10GB. I have gtx 1060 so I have only 6GB.

@Kubasinska Don't get me wrong. Thanks for your suggestions and help. I am grateful but I'm trying to find the best solution.

I have only about 25000 images in my dataset. Some people train networks with few millions images. I don't know how they do it. Do they divide their data somehow into chunks?

**Comment by tilakrayal** [comment]
@JamesJacquesDiego ,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.Thanks!

**Comment by JamesJacquesDiego** [comment]
Well, it's almost a complete code. Above I load my train and test images with labels. Below I generate plots to display data. I've decreased resolution of my images and now it works. But it should be some way to load only part of dataset to gpu memory or create additional memory like with ram we can do (virtual ram)?

**Comment by tilakrayal** [comment]
@JamesJacquesDiego ,
I was facing different error while executing the mentioned code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f7d41bd80ea5b9b250d4e357bb0e3694/untitled346.ipynb).

**Comment by JamesJacquesDiego** [comment]
train_images and train_labels are images and classes which i load. Here is used
`x = np.random.rand(1000, 200, 256, 3)
y = np.array([rand.integers(20) for i in range(1000)])`
to simulate those data

**Comment by Venon282** [comment]
no solution ?
