### ISSUE TITLE
Segmentation Fault when using NCCL with MultiWorkerMirroredStrategy

### ISSUE THREAD

**Issue by bluepra** [tensorflow/tensorflow#56812]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu
-   **TensorFlow installed from (source or binary)**: 
-   **TensorFlow version (use command below)**: 2.6.5
-   **Python version**: 3.8.10
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**: 
-   **CUDA/cuDNN version**:  11.6
-   **GPU model and memory**: V100
-   **Exact command to reproduce**: 

### Describe the problem
I am using 2 VMs each running a docker container. Each container uses 1 GPU.

I am trying to use TF's MutliWorkerMirroredStrategy. Currently if I choose the RING, the training successfully runs on 2 VMs (1 GPU each):
com_options=tf.distribute.experimental.CommunicationOptions(implementation=tf.distribute.experimental.CommunicationImplementation.RING)
strategy = tf.distribute.MultiWorkerMirroredStrategy(communication_options=com_options)

BUT 

When I switch to NCCL:
com_options=tf.distribute.experimental.CommunicationOptions(implementation=tf.distribute.experimental.CommunicationImplementation.NCCL)
strategy = tf.distribute.MultiWorkerMirroredStrategy(communication_options=com_options)

I get a Segmentation fault on my second VM, and then my first VM's training also stops.

#### When I run the training script on VM1:
2022-07-18 18:00:15.159072: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> VM_1_IP:6006, 1 -> VM_2_IP3:6006}
2022-07-18 18:00:15.159629: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:427] Started server with target: grpc://VM_1_IP:6006
80d296ca77be:32:176 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.2<0>
80d296ca77be:32:176 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
80d296ca77be:32:176 [0] NCCL INFO NET/IB : No device found.
80d296ca77be:32:176 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0>
80d296ca77be:32:176 [0] NCCL INFO Using network Socket

#### Then I run modify 'TF_CONFIG' environment variable, and run the the same training script on VM2, when I get this output:
a64a33f123c8:508:652 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.2<0>
a64a33f123c8:508:652 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
a64a33f123c8:508:652 [0] NCCL INFO NET/IB : No device found.
a64a33f123c8:508:652 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0>
a64a33f123c8:508:652 [0] NCCL INFO Using network Socket
a64a33f123c8:508:659 [0] NCCL INFO Call to connect returned Connection refused, retrying
a64a33f123c8:508:659 [0] NCCL INFO Call to connect returned Connection refused, retrying
a64a33f123c8:508:659 [0] NCCL INFO Call to connect returned Connection refused, retrying
a64a33f123c8:508:659 [0] NCCL INFO Call to connect returned Connection refused, retrying

and eventually...

a64a33f123c8:508:659 [0] bazel-out/k8-opt/bin/external/nccl_archive/_virtual_includes/include_hdrs/socket.h:406 NCCL WARN Connect to 172.17.0.2<49089> failed : Connection refused
a64a33f123c8:508:659 [0] NCCL INFO external/nccl_archive/src/bootstrap.cc:354 -> 2
a64a33f123c8:508:659 [0] NCCL INFO external/nccl_archive/src/init.cc:564 -> 2
a64a33f123c8:508:659 [0] NCCL INFO external/nccl_archive/src/init.cc:878 -> 2

Segmentation fault (core dumped)

#### Back on VM1, I see:
NCCL version 2.8.3+cudaCUDA_MAJOR.CUDA_MINOR
WARNING:tensorflow:/job:worker/replica:0/task:1 seems down, retrying 1/3
WARNING:tensorflow:/job:worker/replica:0/task:1 seems down, retrying 1/3
WARNING:tensorflow:/job:worker/replica:0/task:1 seems down, retrying 2/3
WARNING:tensorflow:/job:worker/replica:0/task:1 seems down, retrying 2/3
ERROR:tensorflow:Cluster check alive failed, /job:worker/replica:0/task:1 is down, aborting collectives: failed to connect to all addresses
Additional GRPC error information from remote target /job:worker/replica:0/task:1:
:{"created":"@1658167387.074927655","description":"Failed to pick subchannel","file":"external/com_github_grpc_grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1658167387.073967999","description":"failed to connect to all addresses","file":"external/com_github_grpc_grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}
ERROR:tensorflow:Cluster check alive failed, /job:worker/replica:0/task:1 is down, aborting collectives: failed to connect to all addresses
Additional GRPC error information from remote target /job:worker/replica:0/task:1:
:{"created":"@1658167387.074927655","description":"Failed to pick subchannel","file":"external/com_github_grpc_grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1658167387.073967999","description":"failed to connect to all addresses","file":"external/com_github_grpc_grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}
2022-07-18 18:03:07.075266: E tensorflow/core/common_runtime/base_collective_executor.cc:247] BaseCollectiveExecutor::StartAbort Unavailable: cluster check alive failed, /job:worker/replica:0/task:1 is down

Why does switching to NCCL cause this segmentation fault error?
Any help is appreciated!

**Comment by sachinprasadhs** [comment]
It seems like it is failing to establish all connections. Is there anyway you can initialize NCCL environment to try the solution to make sure if the error is caused by NCCL.

**Comment by bluepra** [comment]
What do you mean by "initialize NCCL environment"?
And where exactly does "export NCCL_DEBUG=INFO" go? In the docker run command?

Sorry I am very new to all this.

**Comment by bluepra** [comment]
So its something to do with containers. I stopped using Docker containers and just used NCCL with 2 VMs and it works!

**Comment by sachinprasadhs** [comment]
@bluepra , If your issue is resolved, could you please close this issue. Thanks
