### ISSUE TITLE
Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found

### ISSUE THREAD

**Issue by TamirRozenfeld** [tensorflow/tensorflow#57103]
### Issue Type

Bug

### Source

source

### Tensorflow Version

tf2.9.1

### Custom Code

No

### OS Platform and Distribution

windows 10

### Current Behaviour?

```shell
Should i do something with that ?
Ofc i have GPU in my Computer
```

### Standalone code to reproduce the issue

```shell
'''import tensorflow as tf
print("TensorFlow version:", tf.__version__)'''
```

### Relevant log output

```shell
C:\Users\tamir\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/tamir/PycharmProjects/pythonProject/module_one.py
2022-08-11 14:21:29.345331: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-08-11 14:21:29.345439: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
TensorFlow version: 2.9.1

Process finished with exit code 0
```

**Comment by mohantym** [comment]
Hi @TamirRozenfeld 
Quick fix is to download 'cudart64_110.dll' from [dll-files.com ](https://www.dll-files.com/cudart64_110.dll.html) and paste it into cudatoolkit/bin file location.

Can you confirm that you are using Cuda 11.2 and CudNN 8.1 and followed instructions from [here](https://www.tensorflow.org/install/pip#windows). (Updated one) 

Thank you!

**Comment by TamirRozenfeld** [comment]
"Quick fix is to download 'cudart64_110.dll' from [dll-files.com ](https://www.dll-files.com/cudart64_110.dll.html)and paste it into cudatoolkit/bin file location." It's doesn't work,

After I've seen your response I followed the instructions from [here](https://www.tensorflow.org/install/pip#windows) i still have the same problem

**Comment by mohantym** [comment]
Hi @gadagashwini !
Could you look at this issue.
Thank you!

**Comment by gadagashwini** [comment]
Hi @TamirRozenfeld, Use Conda to install CUDA and cuDNN, which takes care the path setting.

```
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
python3 -m pip install tensorflow
# Verify install:
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

**Comment by TamirRozenfeld** [comment]
> Hi @TamirRozenfeld, Use Conda to install CUDA and cuDNN, which takes care the path setting.
> 
> ```
> conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
> python3 -m pip install tensorflow
> # Verify install:
> python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
> ```

I did 
but the gpu isn't compatible 
![image](https://user-images.githubusercontent.com/108065131/184336220-f40c8c7e-bdbf-46d5-998d-5775b098a480.png)
i have some missing files

**Comment by gadagashwini** [comment]
Hi @TamirRozenfeld, Looks like CUDA version incompatibility with GPU cards,
Try,
`conda install -c conda-forge cudatoolkit=11.0 cudnn=8.0`

Thank you!

**Comment by afbpinheiro** [comment]
@TamirRozenfeld I had the problem you describe in the last image because I installed my python version via microsoft store. 
I uninstalled it and installed python via the usual means and it worked.

Note: I also needed to add the relevant miniconda folders to the system path

**Comment by gadagashwini** [comment]
HI @afbpinheiro, You can set up miniconda folder path using below steps

> After the installation is done, we need to set up the environment variable. 
> Go to Control Panel -> System and Security -> System 
> Under the Advanced System Setting option click on Environment Variables .

Thank you!

**Comment by piyushpradhan22** [comment]
# Add this line to __init__.py inside tensorflow (somepath\Python39\site-packages\tensorflow)
import os
os.add_dll_directory("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin/")

It will work without any issue.

**Comment by surendrallam** [comment]
> @TamirRozenfeld I had the problem you describe in the last image because I installed my python version via microsoft store. I uninstalled it and installed python via the usual means and it worked.
> 
> Note: I also needed to add the relevant miniconda folders to the system path

Thanks @TamirRozenfeld, this solution had worked for me.

**Comment by surendrallam** [comment]
This error is most likely due to three issues: 

1. You haven't installed CUDA and CUDNN from Nvidia.

2. You don't have an NVIDIA graphics card on your computer (integrated or external )

3. having an outdated Microsoft Visual C++ Redistributable for Visual Studio if you are using a Windows.
go ahead to [https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170][1] and install an updated version of Microsoft Visual C++ Redistributable that fits your system.


  [1]: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170.

If you checklist all the above , you won't have any error messages like that.
