### ISSUE TITLE
XLA bug for ReLU after convolution

### ISSUE THREAD

**Issue by mu40** [tensorflow/tensorflow#57611]
### Issue Type

Bug

### Source

binary, official 2.9.1-gpu Docker image

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux CentOS Stream release 8

### Python version

3.8.10

### CUDA/cuDNN version

11.2

### Current Behaviour?

With XLA enabled, ReLU after a convolution causes a CUDNN_STATUS_INTERNAL_ERROR. The error disappears when ReLU is replaced with LeakyReLU.

In 2019, a similar issue was resolved for JAX by updating XLA (https://github.com/google/jax/issues/1049). The bug comes up when running the below Python code in the official tensorflow/tensorflow:2.9.1-gpu Docker image from May 2022:

```shell
singularity pull docker://tensorflow/tensorflow:2.9.1-gpu
singularity exec -e --nv tensorflow_2.9.1-gpu.sif python ./relu.py
```

### Standalone code to reproduce the issue

```python
import os
import tensorflow as tf

os.environ['TF_XLA_FLAGS'] = '--tf_xla_auto_jit=2'

model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv1D(filters=1, kernel_size=1))
model.add(tf.keras.layers.ReLU())
model.compile(loss='MSE')

x = tf.ones(shape=(1, 32, 1))
model.fit(x, y=x, epochs=2)
```

### Relevant log output

```
2022-09-04 09:21:09.113717: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-04 09:21:17.262140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 29503 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1a:00.0, compute capability: 7.0
2022-09-04 09:21:17.290599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 30988 MB memory:  -> device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1c:00.0, compute capability: 7.0
2022-09-04 09:21:17.291712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 30988 MB memory:  -> device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1d:00.0, compute capability: 7.0
2022-09-04 09:21:17.292349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 30988 MB memory:  -> device: 3, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1e:00.0, compute capability: 7.0
2022-09-04 09:21:17.954855: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1750] (One-time warning): Not using XLA:CPU for cluster.

If you want XLA:CPU, do one of the following:

 - set the TF_XLA_FLAGS to include "--tf_xla_cpu_global_jit", or
 - set cpu_global_jit to true on this session's OptimizerOptions, or
 - use experimental_jit_scope, or
 - use tf.function(jit_compile=True).

To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a
proper command-line flag, not via TF_XLA_FLAGS).
Epoch 1/2
2022-09-04 09:21:18.525364: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x7f12e801d660 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-09-04 09:21:18.525426: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): Tesla V100-SXM2-32GB, Compute Capability 7.0
2022-09-04 09:21:18.525438: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (1): Tesla V100-SXM2-32GB, Compute Capability 7.0
2022-09-04 09:21:18.525449: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (2): Tesla V100-SXM2-32GB, Compute Capability 7.0
2022-09-04 09:21:18.525459: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (3): Tesla V100-SXM2-32GB, Compute Capability 7.0
2022-09-04 09:21:18.657529: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:263] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-09-04 09:21:23.648975: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
2022-09-04 09:21:36.916665: I tensorflow/compiler/jit/xla_compilation_cache.cc:478] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
1/1 [==============================] - 19s 19s/step - loss: 1.0000
Epoch 2/2
Traceback (most recent call last):
  File "./relu.py", line 12, in <module>
    model.fit(x, y=x, epochs=2)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

CUDNN_STATUS_INTERNAL_ERROR
in tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
         [[{{node cluster_0_1/xla_run}}]] [Op:__inference_train_function_502]
```
</details>

**Comment by SakshiSingh25** [comment]
Hello, I'm interested in working on it. Kindly grant me permission for the same.

**Comment by tilakrayal** [comment]
@mu40,
Could you please try to run the below command before executing the code. I tried and was able to execute the code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/e77b153e09bad8d87774792a149c04ca/untitled567.ipynb).

**!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2**

Thank you!

**Comment by SakshiSingh25** [comment]
okay Thank you.

**Comment by mu40** [comment]
Thanks. I am not sure if apt could actually install packages inside the container, but it looks like this particular one is already at the requested version.
```shell
singularity exec -e --nv tensorflow_2.9.1-gpu.sif apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2
```

The call generates the following output, and the error persists.
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcudnn8 is already the newest version (8.1.0.77-1+cuda11.2).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
W: Not using locking for read only lock file /var/lib/dpkg/lock-frontend
W: Not using locking for read only lock file /var/lib/dpkg/lock
W: Not using locking for read only lock file /var/cache/apt/archives/lock
```

**Comment by tilakrayal** [comment]
@mu40<
I was able to execute the given code without any issue/error on tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0df2f69ccd0a4866aa066cc6f06f42e3/untitled582.ipynb). Thank you!

**Comment by mu40** [comment]
Interesting - while the code ran fine with tf-nightly, it looks like it failed with 2.9.0 for you.

I just tried the nightly-gpu Docker image, which executed the code without error, too. However, execution still fails with 2.10.0-gpu. Does this suggest an XLA version issue like it was for JAX?

**Comment by tilakrayal** [comment]
@mu40,
As it was the bug in tensorflow v2.9 and 2.10, the issue was fixed in the **tf-nightly** version. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0df2f69ccd0a4866aa066cc6f06f42e3/untitled582.ipynb). Thank you!
