### ISSUE TITLE
GPU memory usage depends on data size

### ISSUE THREAD

**Issue by Dapid** [tensorflow/tensorflow#57623]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.6-2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Fedora 36

### Python version

3.9

### CUDA/cuDNN version

11.7

### GPU model and memory

RTX 2070, 8GiB

### Current Behaviour?

```shell
Training a small model on small batches runs out of GPU memory if the total amount of data is large.

The same code works fine on TF 2.5, but fails on 2.6, 2.7, 2.8, and 2.9.
```

### Standalone code to reproduce the issue

```shell
Here is a handy script: https://gist.github.com/Dapid/3f58697edf91c6610ed5e7b681db440f

In short, a tiny model is trained on a fixed array of data. If the total amount of data is small, it runs; otherwise, it crashes.

Running `python benchmark.py` works, but `python benchmark.py --big` doesn't. Using the `tf.data` API doesn't make a difference.
```

### Relevant log output

```shell
-09-06 10:52:22.131172: W tensorflow/core/common_runtime/bfc_allocator.cc:462] Allocator (GPU_0_bfc) ran out of memory trying to allocate 15.26GiB (rounded to 16384000000)requested by op _EagerConst

Defining `TF_GPU_ALLOCATOR=cuda_malloc_async`:

```
2022-09-06 10:58:16.939018: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 16384000000 exceeds 10% of free system memory.
2022-09-06 10:58:23.313713: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 16384000000 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)
 Reported by CUDA: Free memory/Total memory: 1111293952/8369799168
2022-09-06 10:58:23.313737: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                      6184304640
InUse:                        67126312
MaxInUse:                    201327628
NumAllocs:                          13
MaxAllocSize:                 67108864
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2022-09-06 10:58:23.313745: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;
2022-09-06 10:58:23.313749: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 5
2022-09-06 10:58:23.313753: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 2
2022-09-06 10:58:23.313755: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1
2022-09-06 10:58:23.313758: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 16384, 1
2022-09-06 10:58:23.313761: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 67108864, 1
```
```

**Comment by sushreebarsa** [comment]
@Dapid I tried to replicate the issue, could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/96ae4a4de769cbd25f570713fac2ce8e/57623.ipynb#scrollTo=Eed4vIgxNa3H) and confirm the same?
Thank you!

**Comment by Dapid** [comment]
At least in the instance of Colab I am getting it is not possible to reproduce because the GPU has more memory than RAM. `nvidia-smi` reports `15109MiB`, while `free -h` reports `10G` free.

If you have an instance with more RAM, you can run `main(True, False)` or `main(True, True)`, and skip the argparse, which I only added because it is convenient for the CLI.

**Comment by gadagashwini** [comment]
Hi @Dapid, When I was trying to replicating with Tf 2.9 and CUDA 11.4. I got the below error.Please take a look and provide more information. Thank you!

```
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-07 10:06:57.779530: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:06:57.780442: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:06:57.781248: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:06:57.781988: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:06:57.782778: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:06:57.783602: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:07:00.007772: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:07:00.008768: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:07:00.011353: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:07:00.012214: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:07:00.013043: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:07:00.013903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13672 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2022-09-07 10:07:00.015790: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-07 10:07:00.016539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13777 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(None, 4096)]            0         
                                                                 
 dense (Dense)               (None, 4096)              16781312  
                                                                 
=================================================================
Total params: 16,781,312
Trainable params: 16,781,312
Non-trainable params: 0
_________________________________________________________________
Training on 1000 data points and 15.625 MiB.
Epoch 1/3
2022-09-07 10:07:02.883347: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x55e1200aeb60 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-09-07 10:07:02.883514: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2022-09-07 10:07:02.883590: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
2022-09-07 10:07:02.953460: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-09-07 10:07:03.198310: W tensorflow/compiler/xla/service/gpu/nvptx_helper.cc:56] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
Searched for CUDA in the following directories:
  ./cuda_sdk_lib
  /usr/local/cuda-11.2
  /usr/local/cuda
  .
You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2022-09-07 10:07:03.260160: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:327] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2022-09-07 10:07:03.260703: I tensorflow/compiler/jit/xla_compilation_cache.cc:476] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2022-09-07 10:07:03.260951: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:327 : INTERNAL: libdevice not found at ./libdevice.10.bc
2022-09-07 10:07:03.284157: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:327] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2022-09-07 10:07:03.284591: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:327 : INTERNAL: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "/home/gadag/57623.py", line 47, in <module>
    main(args.big, args.data)
  File "/home/gadag/57623.py", line 38, in main
    model.fit(train_data, train_data, epochs=3, verbose=1, batch_size=16)
  File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/gadag/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "/home/gadag/57623.py", line 47, in <module>
      main(args.big, args.data)
    File "/home/gadag/57623.py", line 38, in main
      model.fit(train_data, train_data, epochs=3, verbose=1, batch_size=16)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1637, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1233, in train_function
      return step_function(self, iterator)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1217, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1206, in run_step
      outputs = model.train_step(data)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1014, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 500, in minimize
      self.apply_gradients(grads_and_vars)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 985, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 550, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 988, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1038, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/home/gadag/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1033, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall'
libdevice not found at ./libdevice.10.bc
         [[{{node StatefulPartitionedCall}}]] [Op:__inference_train_function_498]
```

**Comment by Dapid** [comment]
@gadagashwini is your environment working? It looks like Tensorflow is not finding CUDA, based on:

```
2022-09-07 10:07:03.198310: W tensorflow/compiler/xla/service/gpu/nvptx_helper.cc:56] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
Searched for CUDA in the following directories:
  ./cuda_sdk_lib
  /usr/local/cuda-11.2
  /usr/local/cuda
```
and

```
Node: 'StatefulPartitionedCall'
libdevice not found at ./libdevice.10.bc
         [[{{node StatefulPartitionedCall}}]] [Op:__inference_train_function_498]
```

Note that you are training on 1000 data points, which fits perfectly in memory and works for me.

**Comment by gadagashwini** [comment]
Hi @Dapid, The instance has CUDA installed. 

```
(base) gadag@ashwini-gpu:~$ nvidia-smi
Thu Sep  8 06:03:43 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P0    27W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:00:05.0 Off |                    0 |
| N/A   57C    P0    28W /  70W |      0MiB / 15109MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by Dapid** [comment]
But look at the error:

```
2022-09-07 10:07:03.198310: W tensorflow/compiler/xla/service/gpu/nvptx_helper.cc:56] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
```

and 

```
Node: 'StatefulPartitionedCall'
libdevice not found at ./libdevice.10.bc
         [[{{node StatefulPartitionedCall}}]] [Op:__inference_train_function_498]
```

On my machine:

```
$ find /usr/local -name libdevice*
/usr/local/cuda-11.7/nvvm/libdevice
/usr/local/cuda-11.7/nvvm/libdevice/libdevice.10.bc
```

It seems to be chocking on running on the GPU itself. It looks like it could not run anything at all. My problem is that GPU vRAM usage depends on the size of the data, which shouldn't matter because we are only sending minibatches.


And it is not just for training, inference too:

```
import numpy as np

from tensorflow.keras import layers, models


def get_model(n_inputs: int) -> models.Model:
    inp = layers.Input(shape=(n_inputs,))

    out = layers.Dense(n_inputs, activation='linear')(inp)
    m = models.Model(inputs=inp, outputs=out)
    m.compile(loss='mse', optimizer='adam')
    m.summary()
    return m


def main(big: bool):
    model = get_model(4096)

    N = 1_000_000 if big else 1_000
    train_data = np.zeros((N, 4096), dtype=np.float32)
    print(f'Evaluating on {train_data.shape[0]} data points and {train_data.nbytes / 1024**2} MiB.')

    model.predict(train_data, batch_size=16, verbose=1)
```
`main(False)` quickly processes the 15 MiB of data, but `main(False)` runs out of GPU memory because it tries to push the 15 GiB all at once. It should work because I have 30 GiB of RAM. So, `model.predict` and `model.fit` seem to be behaving like their cousins `model.predict_on_batch` and `model.fit_on_batch`, at least when it comes to memory usage.

And as I said earlier, this works with TF 2.5.

**Comment by colindean** [comment]
@gadagashwini, you probably need to adjust how NVCC and libdevice are getting loaded.

I hit the same problem with of a job running inside of a container that I built on top of a Miniconda3 base. An extract:

```
export APP_PREFIX=$("${CONDA_CLI}" run --name ${APP_ENV_NAME} env | grep ^CONDA_PREFIX= 2> /dev/null | cut -d= -f2) && \
"${CONDA_CLI}" env config vars set --name ${APP_ENV_NAME} "XLA_FLAGS=--xla_gpu_cuda_data_dir=${APP_PREFIX}/lib/" && \
mkdir -p $APP_PREFIX/lib/nvvm/libdevice && \
cp $APP_PREFIX/lib/libdevice.10.bc $APP_PREFIX/lib/nvvm/libdevice
```

More widely applicable, you'd need to link the installation location of `libdevice.10.bc` into `${APP_PREFIX}/lib/nvvm/libdevice` and set `XLA_FLAGS=--xla_gpu_cuda_data_dir=${APP_PREFIX}/lib/`, where `$APP_PREFIX` is something like `/opt/conda/devs/yourEnv` for conda or just `/lib` or `/usr/lib` for using a normal Debian base.

See also the [Ubuntu 20.04 instructions on the PIP installation instructions page for TF](https://www.tensorflow.org/install/pip#ubuntu_2204).

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by Dapid** [comment]
The problem persists on 2.17.
