### ISSUE TITLE
Tensorflow pypi wheel for Linux has outdated TensorRT dependency

### ISSUE THREAD

**Issue by fehrin** [tensorflow/tensorflow#57671]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### CUDA/cuDNN version

11.7/8.5

### Current Behaviour?

```shell
On Ubuntu 20.04 Tensorflow 2.10 as installed via pip tries to dlopen libnvinfer from TensorRT, which is different from the Windows pypi package (no TensorRT dependency) and more important it wants the outdated version 7 which is only available up to Ubuntu 18.04 and only compatible with CUDA up to version 11.2. Either the TensorRT dependency should not be there (as it was before and is still on Windows) or it should be against the current version 8.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print(tf.config.list_physical_devices("GPU"))
```

### Relevant log output

```shell
2022-09-12 17:53:57.425679: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-12 17:53:57.566393: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-12 17:53:57.596092: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-09-12 17:53:58.180614: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-09-12 17:53:58.180675: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-09-12 17:53:58.180680: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-09-12 17:53:58.968890: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2022-09-12 17:53:59.000480: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-12 17:53:59.000632: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
```
</details>

**Comment by tilakrayal** [comment]
@fehrin,
Could you please confirm whether you are trying to build the tensorflow from the official doc [link](https://github.com/tensorflow/tensorflow/tree/v2.10.0). Thank you!

**Comment by fehrin** [comment]
@tilakrayal I do not build tensorflow, i use the prebuilt package from pypi.org. And this package (the Linux one) is built with/against TensorRT, which is new (the Tensorflow versions 2.9.x are not built with TensorRT), is this intentional? The real problem is that the pypi Linux package of Tensorflow (with Python 3.10) is built against TensorRT version 7, this version is outdated, if at all TensorRT version 8 should be used.

**Comment by gadagashwini** [comment]
Hi @fehrin,
# Install TensorRT
```
sudo apt-get install -y --no-install-recommends libnvinfer8=8.2.3-1+cuda11.4 \
    libnvinfer-dev=8.2.3-1+cuda11.4
```

**Comment by fehrin** [comment]
@gadagashwini This does not resolve the problem because the pypi package refers to libnvinfer7. After installing libnvinfer8 libnvinfer7 still will not be found as explained in the original bug report.

**Comment by mihaimaruseac** [comment]
Because of the way TF is built with optimizations, we can only target one version of GPU libraries.

**Comment by mihaimaruseac** [comment]
There is a separate team within TF that manages CUDA libraries. They need to send updates for these libraries before the branch cut for a release.

**Comment by fehrin** [comment]
@mihaimaruseac It is halfways clear now, but there are remaining unanswered question: Why is TensorRT support included in Tensorflow 2.10, when it was not up to and including 2.9.2, was this a deliberate decision and is this documented in the release notes? And why is TensorRT support included in Tensorflow 2.10 for Linux but not in Tensorflow 2.10 for Windows?

**Comment by mihaimaruseac** [comment]
We need someone from the CUDA/GPU team to answer these.

**Comment by gowthamkpr** [comment]
@bixia1 Can you please look into this. Thanks!!

**Comment by MemoonaTahira** [comment]
Same question, I have tensorrt version 8.5.1.7 installed with cudatoolkit=11.2, cudnn=8.1, python=3.10 and tensorflow=2.11, and tensorflow comaplains it cannot find `Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7:` even though libnvinfer.so.8 is installled inside the tensorrt folder and in the path. 


To install tensorrt 7, I will need to downgrade to python 3.8 and I don't want to do that right now. Is there any other fix?

**Comment by mihaimaruseac** [comment]
CC @learning-to-play @rishikasinha-tf

**Comment by mihaimaruseac** [comment]
Also, duplicates #57679?

**Comment by MemoonaTahira** [comment]
In case this helps, 

I just downgraded to python 3.8, and installed tensorrt with pip install nvidia-tensorrt, and it installed nearly 2.2 GB worth of packages as dependencies, including cublas, cuda-nvrtc, cuda-runtime and cudnn. I also had to add tensorrt to path. And I also had to install cudatoolkit + cudnn (11.2 and 8.1) again for the correct version for tensorflow 2.10 via conda. (since these packages are on the path, and the other 4 packages (cublas, cuda-nvrtc, cuda-runtime and cudnn) installed with tensorrt are not, there are no conflict). It is working now, but honestly all I needed was:

1- Tensorflow 2.10 or 2.11 working with tensorrt 8, for which I could have used pip install tensorrt
OR
2- the tensorrtt 7 availabe via pip and not via nvidia-tensorrt

**Comment by mihaimaruseac** [comment]
Should be fixed in `tf-nightly` and with upcoming TF 2.12

**Comment by jthibaut** [comment]
I have the same issue: Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7
But I am lost; I tried to follow the instructions and it doesn't work.
Anyone could help me ? I am not an IT specialist.
Regards

**Comment by MemoonaTahira** [comment]
@jthibaut Hi, first try this: Install miniconda, and then install python=3.10, cudnn=8.1 and cudatoolkit=11.2 (officially supported versions of python, cudnn and cudatoolkit for now for tensorflow) with conda and create an environment variable (official instructions are here: https://www.tensorflow.org/install/pip),but in place of `pip install tensorflow`,  install `pip install tf-nightly', and then install `pip install tensorrt` which will install tensorrt 8. Supposedly the latest tf-nightly release will work with tensorrt 8 which has 'libnvinfer.so.8'

I wrote a blog with instructions too in case it helps,  it should work for both WSL and Ubuntu: https://medium.com/@MemoonaTahira/installing-tensorflow-with-gpu-support-on-windows-wsl-in-2022-a9c4a064678b 

If not, tagging you on another post where someone has posted a working fix which I tried and it works which involves downgrading to python 3.8 and then installing tensorrt 7.

**Comment by MemoonaTahira** [comment]
@jthibaut If you look closely, it has a W in front of the 10% memory exceed warning. You can ignore this safely. If it was an E, it means an error and you'd need to fix it. And in case it helps, I is for info and is neither a warning or an error. 

You can run `watch nvidia-smi` to see GPU utilization, or open any resource monitor, you'll see your GPU usage. 

The second error seems to be related to your code, and not the installation.

**Comment by jthibaut** [comment]
Thank you,
even with a GPU I succeeded in crashing my kernel !

**Comment by sayakpaul** [comment]
The easiest way to leverage TensorRT is via an NGC. This resource could be useful: https://huggingface.co/spaces/sayakpaul/tensorrt-tf
