### ISSUE TITLE
GPU becomes unavailable after computer wakes up 

### ISSUE THREAD

**Issue by Sadrpour** [tensorflow/tensorflow#5777]
I noticed many have issues with GPU being unavailable with message (e.g., [issue 394](https://github.com/tensorflow/tensorflow/issues/394))

`E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_UNKNOWN
` 
some suggested `sudo apt-get install nvidia-modprobe`  but it does not work for all including me. my GPU works until i put the computer to sleep/suspense, but after waking up the computer i always get the message above and the GPU (gtx 1070) is no longer available in execution of the code (only CPU is used) in nvidia docker.  I also noticed if prior to suspending the computer i exit the docker and then restart it when i wake the computer the GPU is still available in docker. So, the problem happens if i suspend the computer while the ipython-notebook session is up and running. 

I am using nvidia-docker 

`nvidia-docker run -it -p 8888:8888 -v /*..../Data/docker:/docker --name TensorFlow   gcr.io/tensorflow/tensorflow:latest-gpu /bin/bash`

Nvidia-smi and nvidia-debugdump -l both show the GPU is installed and driver is up to date within docker and in the host. 

when i run nvidia-smi in docker the output is 

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0      On |                  N/A |
|  0%   41C    P0    39W / 180W |    450MiB /  8105MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

                                                                               

```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: ca234sff235
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: ca234sff235
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: 367.57.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 4.9.3 (Ubuntu 4.9.3-13ubuntu2) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.57.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:293] kernel version seems to match DSO: 367.57.0
```

Software specs:
OS: Ubuntu 16.04 LTS - 64 bit
GPU driver: nvidia 367.57
Cuda : 7.5

**Comment by prb12** [comment]
This seems most likely to be an issue with your NVidia driver / CUDA installation.
 @zheng-xq  I seem to remember that these cards need Cuda8.0 ?

**Comment by aPere3** [comment]
I'm having the exact same bug using the docker version of tensorflow.
Specs:
+ __os__: Linux Mint 18 Cinnamon 64 bit
+ __gpu__: Geforce 940M
+ __driver__: 367.57
+ __cuda__: 8.0
+ __cudnn__: 5.1

**Comment by zheng-xq** [comment]
@Sadrpour, @aPere3, the best way to diagnose is to compile the vectorAdd samples from your Cuda SDK. If you can run it successfully, but TensorFlow cannot, it might be a TF issue. Otherwise, it is likely to be a problem with your local Cuda installation.

**Comment by bicepjai** [comment]
i have the same issue

Titan X
CUDA Version 8.0.44
NVIDIA Driver Version: 367.57
Ubunut 16.04  4.4.0-64-generic

**Comment by Sadrpour** [comment]
I still have not found a fix either

**Comment by mmakowski** [comment]
Same problem:

* TensorFlow: tensorflow-gpu 1.0.0 installed via pip in Anaconda sandbox
* GPU: GeForce GTX 680
* cuda: 8.0
* cudnn: 5.1.5
* NVIDIA driver: 375.39
* OS: Ubuntu 16.10 64 bit

**Comment by mmakowski** [comment]
@zheng-xq, this is the test that I ran. My interpretation is that the issue is caused by TensorFlow:

1. run vectorAdd -- OK
2. sleep/wake up
3. run vectorAdd -- OK
4. sleep/wake up
5. run vectorAdd -- OK
6. run python and in there `import tensorflow as tf`
7. run vectorAdd -- OK
8. sleep/wake up
9. run vectorAdd -- OK
10. in the previously open python session: `tf.test.gpu_device_name()` -- OK
11. run vectorAdd -- OK
12. sleep/wake up
13. run vectorAdd -- **FAILED**
14. in the previously open python session: `tf.test.gpu_device_name()` -- **FAILED**
15. run vectorAdd -- **FAILED**

## Command output details

### Successful vectorAdd

```
$ ./vectorAdd 
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

### TensorFlow import

```
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
```

### Successful gpu_device_name

```
>>> tf.test.gpu_device_name()
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 680
major: 3 minor: 0 memoryClockRate (GHz) 1.15
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.68GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 680, pci bus id: 0000:01:00.0)
'/gpu:0'
```

### Failed vectorAdd

```
$ ./vectorAdd 
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code all CUDA-capable devices are busy or unavailable)!
```

### Failed gpu_device_name

```
>>> tf.test.gpu_device_name()
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 680, pci bus id: 0000:01:00.0)
*** Error in `python': double free or corruption (fasttop): 0x0000000003e25870 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x790cb)[0x7f540c3d70cb]
/lib/x86_64-linux-gnu/libc.so.6(+0x8275a)[0x7f540c3e075a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f540c3e418c]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x1aa1df)[0x7f53cc6071df]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0xd051b)[0x7f53cc52d51b]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(cuStreamCreate+0x5b)[0x7f53cc64d29b]
/home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so(_ZN9perftools8gputools4cuda10CUDADriver12CreateStreamEPNS1_11CudaContextEPP11CUstream_st+0x4b)[0x7f53e05e7dbb]
/home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so(_ZN9perftools8gputools4cuda10CUDAStream4InitEv+0x21)[0x7f53e05fd461]
/home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so(_ZN9perftools8gputools14StreamExecutor14AllocateStreamEPNS0_6StreamE+0x29)[0x7f53e0678eb9]
/home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so(_ZN9perftools8gputools6Stream4InitEv+0x178)[0x7f53e0672a58]
/home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so(_ZN10tensorflow13BaseGPUDevice4InitERKNS_14SessionOptionsE+0x39a)[0x7f53e04da2ca]
/home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so(_ZN10tensorflow20BaseGPUDeviceFactory13CreateDevicesERKNS_14SessionOptionsERKSsPSt6vectorIPNS_6DeviceESaIS8_EE+0x48d)[0x7f53e04de6fd]
/home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so(_ZN10tensorflow13DeviceFactory10AddDevicesERKNS_14SessionOptionsERKSsPSt6vectorIPNS_6DeviceESaIS8_EE+0x12e)[0x7f53e050751e]
/home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so(+0xdf8fc8)[0x7f53dea55fc8]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyCFunction_Call+0xf9)[0x7f540d3175e9]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x8fb5)[0x7f540d39ebd5]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7f540d39f166]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(+0x144b49)[0x7f540d39fb49]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x91d5)[0x7f540d39edf5]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7f540d39f166]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(+0x144b49)[0x7f540d39fb49]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x48)[0x7f540d39fcd8]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalCode+0x3b)[0x7f540d39fd1b]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyRun_InteractiveOneObject+0x1e6)[0x7f540d3c7276]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyRun_InteractiveLoopFlags+0x5e)[0x7f540d3c75de]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(PyRun_AnyFileExFlags+0x4c)[0x7f540d3c771c]
/home/mmakowski/anaconda3/envs/tensorflow/bin/../lib/libpython3.5m.so.1.0(Py_Main+0xde2)[0x7f540d3e1a02]
python(main+0x15d)[0x400add]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f540c37e3f1]
python[0x4008b9]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:02 9311838                            /home/mmakowski/anaconda3/envs/tensorflow/bin/python3.5
00601000-00602000 rw-p 00001000 08:02 9311838                            /home/mmakowski/anaconda3/envs/tensorflow/bin/python3.5
024ea000-03e43000 rw-p 00000000 00:00 0                                  [heap]
200000000-200100000 rw-s 2d7043000 00:06 454                             /dev/nvidiactl
200100000-200104000 rw-s 2d7148000 00:06 454                             /dev/nvidiactl
200104000-200120000 ---p 00000000 00:00 0 
200120000-200520000 rw-s 2d7155000 00:06 454                             /dev/nvidiactl
200520000-200524000 rw-s 2d656c000 00:06 454                             /dev/nvidiactl
200524000-200540000 ---p 00000000 00:00 0 
200540000-200940000 rw-s 2d6580000 00:06 454                             /dev/nvidiactl
200940000-200a40000 rw-s 2d6198000 00:06 454                             /dev/nvidiactl
200a40000-200b40000 rw-s 2d62c6000 00:06 454                             /dev/nvidiactl
200b40000-200c40000 rw-s 2d63d1000 00:06 454                             /dev/nvidiactl
200c40000-200d40000 rw-s 2d5ccc000 00:06 454                             /dev/nvidiactl
200d40000-200e40000 rw-s 33dd2a000 00:06 454                             /dev/nvidiactl
200e40000-200ec2000 rw-s 2d5eb1000 00:06 454                             /dev/nvidiactl
200ec2000-900000000 ---p 00000000 00:00 0 
7f5378000000-7f5378021000 rw-p 00000000 00:00 0 
7f5378021000-7f537c000000 ---p 00000000 00:00 0 
7f537c000000-7f537c021000 rw-p 00000000 00:00 0 
7f537c021000-7f5380000000 ---p 00000000 00:00 0 
7f5380000000-7f5380021000 rw-p 00000000 00:00 0 
7f5380021000-7f5384000000 ---p 00000000 00:00 0 
7f5384000000-7f5384021000 rw-p 00000000 00:00 0 
7f5384021000-7f5388000000 ---p 00000000 00:00 0 
7f5388000000-7f5388021000 rw-p 00000000 00:00 0 
7f5388021000-7f538c000000 ---p 00000000 00:00 0 
7f538c000000-7f538c021000 rw-p 00000000 00:00 0 
7f538c021000-7f5390000000 ---p 00000000 00:00 0 
7f5390000000-7f5390021000 rw-p 00000000 00:00 0 
7f5390021000-7f5394000000 ---p 00000000 00:00 0 
7f5394033000-7f53957fb000 rw-p 00000000 00:00 0 
7f53957fb000-7f53957fc000 ---p 00000000 00:00 0 
7f53957fc000-7f5395ffc000 rw-p 00000000 00:00 0 
7f5395ffc000-7f5395ffd000 ---p 00000000 00:00 0 
7f5395ffd000-7f53967fd000 rw-p 00000000 00:00 0 
7f53967fd000-7f53967fe000 ---p 00000000 00:00 0 
7f53967fe000-7f5396ffe000 rw-p 00000000 00:00 0 
7f5396ffe000-7f5396fff000 ---p 00000000 00:00 0 
7f5396fff000-7f53977ff000 rw-p 00000000 00:00 0 
7f53977ff000-7f5397800000 ---p 00000000 00:00 0 
7f5397800000-7f5398000000 rw-p 00000000 00:00 0 
7f5398000000-7f5398021000 rw-p 00000000 00:00 0 
7f5398021000-7f539c000000 ---p 00000000 00:00 0 
7f539c000000-7f539c021000 rw-p 00000000 00:00 0 
7f539c021000-7f53a0000000 ---p 00000000 00:00 0 
7f53a0000000-7f53a0021000 rw-p 00000000 00:00 0 
7f53a0021000-7f53a4000000 ---p 00000000 00:00 0 
7f53a4000000-7f53a4021000 rw-p 00000000 00:00 0 
7f53a4021000-7f53a8000000 ---p 00000000 00:00 0 
7f53a8000000-7f53a8021000 rw-p 00000000 00:00 0 
7f53a8021000-7f53ac000000 ---p 00000000 00:00 0 
7f53ac000000-7f53ac021000 rw-p 00000000 00:00 0 
7f53ac021000-7f53b0000000 ---p 00000000 00:00 0 
7f53b0000000-7f53b0021000 rw-p 00000000 00:00 0 
7f53b0021000-7f53b4000000 ---p 00000000 00:00 0 
7f53b4000000-7f53b4021000 rw-p 00000000 00:00 0 
7f53b4021000-7f53b8000000 ---p 00000000 00:00 0 
7f53b8000000-7f53b8021000 rw-p 00000000 00:00 0 
7f53b8021000-7f53bc000000 ---p 00000000 00:00 0 
7f53bc000000-7f53bc021000 rw-p 00000000 00:00 0 
7f53bc021000-7f53c0000000 ---p 00000000 00:00 0 
7f53c0000000-7f53c0021000 rw-p 00000000 00:00 0 
7f53c0021000-7f53c4000000 ---p 00000000 00:00 0 
7f53c44c1000-7f53c44c2000 ---p 00000000 00:00 0 
7f53c44c2000-7f53c4cc2000 rw-p 00000000 00:00 0 
7f53c4cc2000-7f53c4cc3000 ---p 00000000 00:00 0 
7f53c4cc3000-7f53c54c3000 rw-p 00000000 00:00 0 
7f53c54c3000-7f53c54c4000 ---p 00000000 00:00 0 
7f53c54c4000-7f53c5cc4000 rw-p 00000000 00:00 0 
7f53c5cc4000-7f53c5cc5000 ---p 00000000 00:00 0 
7f53c5cc5000-7f53c64c5000 rw-p 00000000 00:00 0 
7f53c64c5000-7f53c64c6000 ---p 00000000 00:00 0 
7f53c64c6000-7f53c6cc6000 rw-p 00000000 00:00 0 
7f53c6cc6000-7f53c6cc7000 r-xp 00000000 08:02 9570451                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/google/protobuf/internal/_api_implementation.cpython-35m-x86_64-linux-gnu.so
7f53c6cc7000-7f53c6ec6000 ---p 00001000 08:02 9570451                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/google/protobuf/internal/_api_implementation.cpython-35m-x86_64-linux-gnu.so
7f53c6ec6000-7f53c6ec7000 rw-p 00000000 08:02 9570451                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/google/protobuf/internal/_api_implementation.cpython-35m-x86_64-linux-gnu.so
7f53c6ec7000-7f53c7107000 rw-p 00000000 00:00 0 
7f53c7107000-7f53c7116000 r-xp 00000000 08:02 9972711                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_socket.so
7f53c7116000-7f53c7316000 ---p 0000f000 08:02 9972711                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_socket.so
7f53c7316000-7f53c731b000 rw-p 0000f000 08:02 9972711                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_socket.so
7f53c731b000-7f53c735b000 rw-p 00000000 00:00 0 
7f53c735b000-7f53c738f000 r-xp 00000000 08:02 9972731                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/pyexpat.so
7f53c738f000-7f53c758f000 ---p 00034000 08:02 9972731                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/pyexpat.so
7f53c758f000-7f53c7593000 rw-p 00034000 08:02 9972731                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/pyexpat.so
7f53c7593000-7f53c75d3000 rw-p 00000000 00:00 0 
7f53c75d3000-7f53c75d8000 r-xp 00000000 08:02 9972734                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/select.so
7f53c75d8000-7f53c77d7000 ---p 00005000 08:02 9972734                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/select.so
7f53c77d7000-7f53c77d9000 rw-p 00004000 08:02 9972734                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/select.so
7f53c77d9000-7f53c77dc000 r-xp 00000000 08:02 9972706                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_posixsubprocess.so
7f53c77dc000-7f53c79db000 ---p 00003000 08:02 9972706                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_posixsubprocess.so
7f53c79db000-7f53c79dc000 rw-p 00002000 08:02 9972706                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_posixsubprocess.so
7f53c79dc000-7f53c79e2000 r-xp 00000000 08:02 9972740                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/zlib.so
7f53c79e2000-7f53c7be2000 ---p 00006000 08:02 9972740                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/zlib.so
7f53c7be2000-7f53c7be4000 rw-p 00006000 08:02 9972740                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/zlib.so
7f53c7be4000-7f53c7bfa000 r-xp 00000000 08:02 9054830                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libz.so.1.2.8
7f53c7bfa000-7f53c7df9000 ---p 00016000 08:02 9054830                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libz.so.1.2.8
7f53c7df9000-7f53c7dfa000 rw-p 00015000 08:02 9054830                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libz.so.1.2.8
7f53c7dfa000-7f53c7dff000 r-xp 00000000 08:02 9972722                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/binascii.so
7f53c7dff000-7f53c7fff000 ---p 00005000 08:02 9972722                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/binascii.so
7f53c7fff000-7f53c8000000 rw-p 00005000 08:02 9972722                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/binascii.so
7f53c8000000-7f53c8200000 rw-p 00000000 00:00 0 
7f53c8228000-7f53c82a8000 rw-p 00000000 00:00 0 
7f53c82a8000-7f53ca736000 r-xp 00000000 08:02 4859634                    /usr/lib/x86_64-linux-gnu/libcurand.so.8.0.44
7f53ca736000-7f53ca936000 ---p 0248e000 08:02 4859634                    /usr/lib/x86_64-linux-gnu/libcurand.so.8.0.44
7f53ca936000-7f53cbd07000 rw-p 0248e000 08:02 4859634                    /usr/lib/x86_64-linux-gnu/libcurand.so.8.0.44
7f53cbd07000-7f53cc211000 rw-p 00000000 00:00 0 
7f53cc211000-7f53cc253000 r-xp 00000000 08:02 4861323                    /usr/lib/nvidia-375/libnvidia-fatbinaryloader.so.375.39
7f53cc253000-7f53cc452000 ---p 00042000 08:02 4861323                    /usr/lib/nvidia-375/libnvidia-fatbinaryloader.so.375.39
7f53cc452000-7f53cc45c000 rw-p 00041000 08:02 4861323                    /usr/lib/nvidia-375/libnvidia-fatbinaryloader.so.375.39
7f53cc45c000-7f53cc45d000 rw-p 00000000 00:00 0 
7f53cc45d000-7f53ccb2b000 r-xp 00000000 08:02 4850112                    /usr/lib/x86_64-linux-gnu/libcuda.so.375.39
7f53ccb2b000-7f53ccd2a000 ---p 006ce000 08:02 4850112                    /usr/lib/x86_64-linux-gnu/libcuda.so.375.39
7f53ccd2a000-7f53cce46000 rw-p 006cd000 08:02 4850112                    /usr/lib/x86_64-linux-gnu/libcuda.so.375.39
7f53cce46000-7f53cce52000 rw-p 00000000 00:00 0 
7f53cce52000-7f53d5a3a000 r-xp 00000000 08:02 4859540                    /usr/lib/x86_64-linux-gnu/libcufft.so.8.0.44
7f53d5a3a000-7f53d5c39000 ---p 08be8000 08:02 4859540                    /usr/lib/x86_64-linux-gnu/libcufft.so.8.0.44
7f53d5c39000-7f53d5c48000 rw-p 08be7000 08:02 4859540                    /usr/lib/x86_64-linux-gnu/libcufft.so.8.0.44
7f53d5c48000-7f53d5ca0000 rw-p 00000000 00:00 0 
7f53d5ca0000-7f53da82d000 r-xp 00000000 08:02 4862601                    /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.5
7f53da82d000-7f53daa2c000 ---p 04b8d000 08:02 4862601                    /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.5
7f53daa2c000-7f53daa4a000 rw-p 04b8c000 08:02 4862601                    /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.5
7f53daa4a000-7f53daa74000 rw-p 00000000 00:00 0 
7f53daa74000-7f53dd1f9000 r-xp 00000000 08:02 4850666                    /usr/lib/x86_64-linux-gnu/libcublas.so.8.0.45
7f53dd1f9000-7f53dd3f8000 ---p 02785000 08:02 4850666                    /usr/lib/x86_64-linux-gnu/libcublas.so.8.0.45
7f53dd3f8000-7f53dd416000 rw-p 02784000 08:02 4850666                    /usr/lib/x86_64-linux-gnu/libcublas.so.8.0.45
7f53dd416000-7f53dd424000 rw-p 00000000 00:00 0 
7f53dd424000-7f53dd43a000 r-xp 00000000 08:02 10621433                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libgcc_s.so.1
7f53dd43a000-7f53dd639000 ---p 00016000 08:02 10621433                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libgcc_s.so.1
7f53dd639000-7f53dd63a000 rw-p 00015000 08:02 10621433                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libgcc_s.so.1
7f53dd63a000-7f53dd63b000 rw-p 00074000 08:02 10621433                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libgcc_s.so.1
7f53dd63b000-7f53dd7a6000 r-xp 00000000 08:02 10621922                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libstdc++.so.6.0.21
7f53dd7a6000-7f53dd9a6000 ---p 0016b000 08:02 10621922                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libstdc++.so.6.0.21
7f53dd9a6000-7f53dd9b0000 r--p 0016b000 08:02 10621922                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libstdc++.so.6.0.21
7f53dd9b0000-7f53dd9b2000 rw-p 00175000 08:02 10621922                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libstdc++.so.6.0.21
7f53dd9b2000-7f53dd9b6000 rw-p 00000000 00:00 0 
7f53dd9b6000-7f53dd9f7000 rw-p 00178000 08:02 10621922                   /home/mmakowski/anaconda3/envs/tensorflow/lib/libstdc++.so.6.0.21
7f53dd9f7000-7f53dda59000 r-xp 00000000 08:02 4859534                    /usr/lib/x86_64-linux-gnu/libcudart.so.8.0.44
7f53dda59000-7f53ddc59000 ---p 00062000 08:02 4859534                    /usr/lib/x86_64-linux-gnu/libcudart.so.8.0.44
7f53ddc59000-7f53ddc5c000 rw-p 00062000 08:02 4859534                    /usr/lib/x86_64-linux-gnu/libcudart.so.8.0.44
7f53ddc5c000-7f53ddc5d000 rw-p 00000000 00:00 0 
7f53ddc5d000-7f53e9b1a000 r-xp 00000000 08:02 9972949                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
7f53e9b1a000-7f53e9d1a000 ---p 0bebd000 08:02 9972949                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
7f53e9d1a000-7f53e9e0c000 r--p 0bebd000 08:02 9972949                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
7f53e9e0c000-7f53e9e13000 rw-p 0bfaf000 08:02 9972949                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
7f53e9e13000-7f53e9eb0000 rw-p 00000000 00:00 0 
7f53e9eb0000-7f53e9f68000 r-xp 00000000 08:02 7623074                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/random/mtrand.cpython-35m-x86_64-linux-gnu.so
7f53e9f68000-7f53ea167000 ---p 000b8000 08:02 7623074                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/random/mtrand.cpython-35m-x86_64-linux-gnu.so
7f53ea167000-7f53ea18c000 rw-p 000b7000 08:02 7623074                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/random/mtrand.cpython-35m-x86_64-linux-gnu.so
7f53ea18c000-7f53ea1ce000 rw-p 00000000 00:00 0 
7f53ea1ce000-7f53ea1d7000 r-xp 00000000 08:02 7622830                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/fft/fftpack_lite.cpython-35m-x86_64-linux-gnu.so
7f53ea1d7000-7f53ea3d6000 ---p 00009000 08:02 7622830                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/fft/fftpack_lite.cpython-35m-x86_64-linux-gnu.so
7f53ea3d6000-7f53ea3d7000 rw-p 00008000 08:02 7622830                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/fft/fftpack_lite.cpython-35m-x86_64-linux-gnu.so
7f53ea3d7000-7f53ea457000 rw-p 00000000 00:00 0 
7f53ea457000-7f53ea480000 r-xp 00000000 08:02 7622130                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so
7f53ea480000-7f53ea67f000 ---p 00029000 08:02 7622130                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so
7f53ea67f000-7f53ea681000 rw-p 00028000 08:02 7622130                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so
7f53ea681000-7f53ea683000 rw-p 000c3000 08:02 7622130                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so
7f53ea683000-7f53ea687000 r-xp 00000000 08:02 7622119                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so
7f53ea687000-7f53ea887000 ---p 00004000 08:02 7622119                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so
7f53ea887000-7f53ea888000 rw-p 00004000 08:02 7622119                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so
7f53ea888000-7f53ea88a000 rw-p 00019000 08:02 7622119                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so
7f53ea94b000-7f53ea94e000 r-xp 00000000 08:02 9972707                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_random.so
7f53ea94e000-7f53eab4d000 ---p 00003000 08:02 9972707                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_random.so
7f53eab4d000-7f53eab4e000 rw-p 00002000 08:02 9972707                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_random.so
7f53eab4e000-7f53ead5a000 r-xp 00000000 08:02 9311604                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libcrypto.so.1.0.0
7f53ead5a000-7f53eaf5a000 ---p 0020c000 08:02 9311604                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libcrypto.so.1.0.0
7f53eaf5a000-7f53eaf81000 rw-p 0020c000 08:02 9311604                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libcrypto.so.1.0.0
7f53eaf81000-7f53eaf85000 rw-p 00000000 00:00 0 
7f53eaf85000-7f53eaff2000 r-xp 00000000 08:02 9055575                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libssl.so.1.0.0
7f53eaff2000-7f53eb1f1000 ---p 0006d000 08:02 9055575                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libssl.so.1.0.0
7f53eb1f1000-7f53eb1fc000 rw-p 0006c000 08:02 9055575                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libssl.so.1.0.0
7f53eb1fc000-7f53eb201000 r-xp 00000000 08:02 9972695                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_hashlib.so
7f53eb201000-7f53eb401000 ---p 00005000 08:02 9972695                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_hashlib.so
7f53eb401000-7f53eb402000 rw-p 00005000 08:02 9972695                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_hashlib.so
7f53eb402000-7f53eb442000 rw-p 00000000 00:00 0 
7f53eb442000-7f53eb466000 r-xp 00000000 08:02 9315096                    /home/mmakowski/anaconda3/envs/tensorflow/lib/liblzma.so.5.2.2
7f53eb466000-7f53eb666000 ---p 00024000 08:02 9315096                    /home/mmakowski/anaconda3/envs/tensorflow/lib/liblzma.so.5.2.2
7f53eb666000-7f53eb667000 rw-p 00024000 08:02 9315096                    /home/mmakowski/anaconda3/envs/tensorflow/lib/liblzma.so.5.2.2
7f53eb667000-7f53eb66d000 r-xp 00000000 08:02 9972700                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_lzma.so
7f53eb66d000-7f53eb86d000 ---p 00006000 08:02 9972700                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_lzma.so
7f53eb86d000-7f53eb86f000 rw-p 00006000 08:02 9972700                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_lzma.so
7f53eb86f000-7f53eb880000 r-xp 00000000 08:02 9972670                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_bz2.so
7f53eb880000-7f53eba80000 ---p 00011000 08:02 9972670                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_bz2.so
7f53eba80000-7f53eba82000 rw-p 00011000 08:02 9972670                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_bz2.so
7f53eba82000-7f53eba84000 r-xp 00000000 08:02 9972725                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/grp.so
7f53eba84000-7f53ebc84000 ---p 00002000 08:02 9972725                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/grp.so
7f53ebc84000-7f53ebc85000 rw-p 00002000 08:02 9972725                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/grp.so
7f53ebc85000-7f53ebe45000 rw-p 00000000 00:00 0 
7f53ebe45000-7f53ebe5c000 r-xp 00000000 08:02 9972705                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_pickle.so
7f53ebe5c000-7f53ec05c000 ---p 00017000 08:02 9972705                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_pickle.so
7f53ec05c000-7f53ec060000 rw-p 00017000 08:02 9972705                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_pickle.so
7f53ec060000-7f53ec0e0000 rw-p 00000000 00:00 0 
7f53ec0e0000-7f53ec26e000 r-xp 00000000 08:02 7622228                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/core/umath.cpython-35m-x86_64-linux-gnu.so
7f53ec26e000-7f53ec46d000 ---p 0018e000 08:02 7622228                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/core/umath.cpython-35m-x86_64-linux-gnu.so
7f53ec46d000-7f53ec473000 rw-p 0018d000 08:02 7622228                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/core/umath.cpython-35m-x86_64-linux-gnu.so
7f53ec473000-7f53ec475000 rw-p 00000000 00:00 0 
7f53ec475000-7f53ec486000 r-xp 00000000 08:02 9972691                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_datetime.so
7f53ec486000-7f53ec685000 ---p 00011000 08:02 9972691                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_datetime.so
7f53ec685000-7f53ec688000 rw-p 00010000 08:02 9972691                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_datetime.so
7f53ec688000-7f53ec6c8000 rw-p 00000000 00:00 0 
7f53ec6c8000-7f53fa6c8000 rw-p 00000000 00:00 0 
7f53fa6c8000-7f53fa6c9000 ---p 00000000 00:00 0 
7f53fa6c9000-7f53faec9000 rw-p 00000000 00:00 0 
7f53faec9000-7f53faeca000 ---p 00000000 00:00 0 
7f53faeca000-7f53fb6ca000 rw-p 00000000 00:00 0 
7f53fb6ca000-7f53fb6cb000 ---p 00000000 00:00 0 
7f53fb6cb000-7f53fbecb000 rw-p 00000000 00:00 0 
7f53fbecb000-7f53fbecc000 ---p 00000000 00:00 0 
7f53fbecc000-7f53fc6cc000 rw-p 00000000 00:00 0 
7f53fc6cc000-7f53fc6cd000 ---p 00000000 00:00 0 
7f53fc6cd000-7f53fcecd000 rw-p 00000000 00:00 0 
7f53fcecd000-7f53fcece000 ---p 00000000 00:00 0 
7f53fcece000-7f53fd6ce000 rw-p 00000000 00:00 0 
7f53fd6ce000-7f53ff6ce000 rw-p 00000000 00:00 0 
7f53ff6ce000-7f53ff6cf000 ---p 00000000 00:00 0 
7f53ff6cf000-7f53ffecf000 rw-p 00000000 00:00 0 
7f53ffecf000-7f5405ecf000 rw-p 00000000 00:00 0 
7f5406000000-7f5406200000 rw-p 00000000 00:00 0 
7f5406360000-7f5406361000 ---p 00000000 00:00 0 
7f5406361000-7f5406ca1000 rw-p 00000000 00:00 0 
7f5406ca1000-7f5406caa000 r-xp 00000000 08:02 9972698                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_json.so
7f5406caa000-7f5406eaa000 ---p 00009000 08:02 9972698                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_json.so
7f5406eaa000-7f5406eab000 rw-p 00009000 08:02 9972698                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_json.so
7f5406eab000-7f54078ec000 rw-p 00000000 00:00 0 
7f54078ec000-7f5407abf000 r-xp 00000000 08:02 9570583                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so
7f5407abf000-7f5407cbe000 ---p 001d3000 08:02 9570583                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so
7f5407cbe000-7f5407ccd000 rw-p 001d2000 08:02 9570583                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so
7f5407ccd000-7f5407cce000 rw-p 00000000 00:00 0 
7f5407cce000-7f5407cd2000 r-xp 00000000 08:02 10486480                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5407cd2000-7f5407ed1000 ---p 00004000 08:02 10486480                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5407ed1000-7f5407ed2000 r--p 00003000 08:02 10486480                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5407ed2000-7f5407ed3000 rw-p 00004000 08:02 10486480                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5407ed3000-7f5407fc3000 r-xp 00000000 08:02 7622696                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/.libs/libgfortran-ed201abd.so.3.0.0
7f5407fc3000-7f54081c2000 ---p 000f0000 08:02 7622696                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/.libs/libgfortran-ed201abd.so.3.0.0
7f54081c2000-7f54081c4000 rw-p 000ef000 08:02 7622696                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/.libs/libgfortran-ed201abd.so.3.0.0
7f54081c4000-7f54081c5000 rw-p 00000000 00:00 0 
7f54081c5000-7f54081cc000 rw-p 000f2000 08:02 7622696                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/.libs/libgfortran-ed201abd.so.3.0.0
7f54081cc000-7f540a4e0000 r-xp 00000000 08:02 7622694                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
7f540a4e0000-7f540a6df000 ---p 02314000 08:02 7622694                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
7f540a6df000-7f540a6fe000 rw-p 02313000 08:02 7622694                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
7f540a6fe000-7f540a761000 rw-p 00000000 00:00 0 
7f540a761000-7f540a7dd000 rw-p 02425000 08:02 7622694                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
7f540a7dd000-7f540a9ab000 r-xp 00000000 08:02 7622227                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
7f540a9ab000-7f540abab000 ---p 001ce000 08:02 7622227                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
7f540abab000-7f540abba000 rw-p 001ce000 08:02 7622227                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
7f540abba000-7f540abcc000 rw-p 00000000 00:00 0 
7f540abcc000-7f540abd2000 rw-p 0097f000 08:02 7622227                    /home/mmakowski/.local/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
7f540abd2000-7f540abda000 r-xp 00000000 08:02 9972726                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/math.so
7f540abda000-7f540adda000 ---p 00008000 08:02 9972726                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/math.so
7f540adda000-7f540addc000 rw-p 00008000 08:02 9972726                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/math.so
7f540addc000-7f540ae1c000 rw-p 00000000 00:00 0 
7f540ae3d000-7f540ae7d000 rw-p 00000000 00:00 0 
7f540ae7d000-7f540ae7e000 r-xp 00000000 08:02 9972704                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_opcode.so
7f540ae7e000-7f540b07d000 ---p 00001000 08:02 9972704                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_opcode.so
7f540b07d000-7f540b07e000 rw-p 00000000 08:02 9972704                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_opcode.so
7f540b07e000-7f540b0fe000 rw-p 00000000 00:00 0 
7f540b0fe000-7f540b106000 r-xp 00000000 08:02 9972714                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_struct.so
7f540b106000-7f540b305000 ---p 00008000 08:02 9972714                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_struct.so
7f540b305000-7f540b308000 rw-p 00007000 08:02 9972714                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_struct.so
7f540b308000-7f540b328000 r-xp 00000000 08:02 9972685                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_ctypes.so
7f540b328000-7f540b527000 ---p 00020000 08:02 9972685                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_ctypes.so
7f540b527000-7f540b52c000 rw-p 0001f000 08:02 9972685                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_ctypes.so
7f540b52c000-7f540b551000 r-xp 00000000 08:02 10489680                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f540b551000-7f540b750000 ---p 00025000 08:02 10489680                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f540b750000-7f540b754000 r--p 00024000 08:02 10489680                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f540b754000-7f540b755000 rw-p 00028000 08:02 10489680                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f540b755000-7f540b782000 r-xp 00000000 08:02 10486924                   /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f540b782000-7f540b982000 ---p 0002d000 08:02 10486924                   /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f540b982000-7f540b983000 r--p 0002d000 08:02 10486924                   /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f540b983000-7f540b984000 rw-p 0002e000 08:02 10486924                   /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f540b9b9000-7f540b9f1000 r-xp 00000000 08:02 9048574                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libreadline.so.6.2
7f540b9f1000-7f540bbf1000 ---p 00038000 08:02 9048574                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libreadline.so.6.2
7f540bbf1000-7f540bbf9000 rw-p 00038000 08:02 9048574                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libreadline.so.6.2
7f540bbf9000-7f540bbfa000 rw-p 00000000 00:00 0 
7f540bbfa000-7f540bbff000 r-xp 00000000 08:02 9972732                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/readline.so
7f540bbff000-7f540bdff000 ---p 00005000 08:02 9972732                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/readline.so
7f540bdff000-7f540be01000 rw-p 00005000 08:02 9972732                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/readline.so
7f540be01000-7f540be41000 rw-p 00000000 00:00 0 
7f540be41000-7f540be43000 r-xp 00000000 08:02 9972696                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_heapq.so
7f540be43000-7f540c043000 ---p 00002000 08:02 9972696                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_heapq.so
7f540c043000-7f540c045000 rw-p 00002000 08:02 9972696                    /home/mmakowski/anaconda3/envs/tensorflow/lib/python3.5/lib-dynload/_heapq.so
7f540c045000-7f540c085000 rw-p 00000000 00:00 0 
7f540c085000-7f540c35e000 r--p 00000000 08:02 4852825                    /usr/lib/locale/locale-archive
7f540c35e000-7f540c51b000 r-xp 00000000 08:02 10486940                   /lib/x86_64-linux-gnu/libc-2.24.so
7f540c51b000-7f540c71b000 ---p 001bd000 08:02 10486940                   /lib/x86_64-linux-gnu/libc-2.24.so
7f540c71b000-7f540c71f000 r--p 001bd000 08:02 10486940                   /lib/x86_64-linux-gnu/libc-2.24.so
7f540c71f000-7f540c721000 rw-p 001c1000 08:02 10486940                   /lib/x86_64-linux-gnu/libc-2.24.so
7f540c721000-7f540c725000 rw-p 00000000 00:00 0 
7f540c725000-7f540c82d000 r-xp 00000000 08:02 10489734                   /lib/x86_64-linux-gnu/libm-2.24.so
7f540c82d000-7f540ca2c000 ---p 00108000 08:02 10489734                   /lib/x86_64-linux-gnu/libm-2.24.so
7f540ca2c000-7f540ca2d000 r--p 00107000 08:02 10489734                   /lib/x86_64-linux-gnu/libm-2.24.so
7f540ca2d000-7f540ca2e000 rw-p 00108000 08:02 10489734                   /lib/x86_64-linux-gnu/libm-2.24.so
7f540ca2e000-7f540ca35000 r-xp 00000000 08:02 10490209                   /lib/x86_64-linux-gnu/librt-2.24.so
7f540ca35000-7f540cc34000 ---p 00007000 08:02 10490209                   /lib/x86_64-linux-gnu/librt-2.24.so
7f540cc34000-7f540cc35000 r--p 00006000 08:02 10490209                   /lib/x86_64-linux-gnu/librt-2.24.so
7f540cc35000-7f540cc36000 rw-p 00007000 08:02 10490209                   /lib/x86_64-linux-gnu/librt-2.24.so
7f540cc36000-7f540cc38000 r-xp 00000000 08:02 10490217                   /lib/x86_64-linux-gnu/libutil-2.24.so
7f540cc38000-7f540ce37000 ---p 00002000 08:02 10490217                   /lib/x86_64-linux-gnu/libutil-2.24.so
7f540ce37000-7f540ce38000 r--p 00001000 08:02 10490217                   /lib/x86_64-linux-gnu/libutil-2.24.so
7f540ce38000-7f540ce39000 rw-p 00002000 08:02 10490217                   /lib/x86_64-linux-gnu/libutil-2.24.so
7f540ce39000-7f540ce3c000 r-xp 00000000 08:02 10489732                   /lib/x86_64-linux-gnu/libdl-2.24.so
7f540ce3c000-7f540d03b000 ---p 00003000 08:02 10489732                   /lib/x86_64-linux-gnu/libdl-2.24.so
7f540d03b000-7f540d03c000 r--p 00002000 08:02 10489732                   /lib/x86_64-linux-gnu/libdl-2.24.so
7f540d03c000-7f540d03d000 rw-p 00003000 08:02 10489732                   /lib/x86_64-linux-gnu/libdl-2.24.so
7f540d03d000-7f540d055000 r-xp 00000000 08:02 10490205                   /lib/x86_64-linux-gnu/libpthread-2.24.so
7f540d055000-7f540d255000 ---p 00018000 08:02 10490205                   /lib/x86_64-linux-gnu/libpthread-2.24.so
7f540d255000-7f540d256000 r--p 00018000 08:02 10490205                   /lib/x86_64-linux-gnu/libpthread-2.24.so
7f540d256000-7f540d257000 rw-p 00019000 08:02 10490205                   /lib/x86_64-linux-gnu/libpthread-2.24.so
7f540d257000-7f540d25b000 rw-p 00000000 00:00 0 
7f540d25b000-7f540d4b5000 r-xp 00000000 08:02 9190569                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libpython3.5m.so.1.0
7f540d4b5000-7f540d6b4000 ---p 0025a000 08:02 9190569                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libpython3.5m.so.1.0
7f540d6b4000-7f540d71b000 rw-p 00259000 08:02 9190569                    /home/mmakowski/anaconda3/envs/tensorflow/lib/libpython3.5m.so.1.0
7f540d71b000-7f540d74b000 rw-p 00000000 00:00 0 
7f540d74b000-7f540d770000 r-xp 00000000 08:02 10486928                   /lib/x86_64-linux-gnu/ld-2.24.so
7f540d773000-7f540d937000 rw-p 00000000 00:00 0 
7f540d95f000-7f540d960000 rw-p 00000000 00:00 0 
7f540d960000-7f540d961000 rw-s f7de4000 00:06 455                        /dev/nvidia0
7f540d961000-7f540d962000 rw-s 2d6194000 00:06 454                       /dev/nvidiactl
7f540d962000-7f540d963000 rw-s f7de4000 00:06 455                        /dev/nvidia0
7f540d963000-7f540d964000 rw-s 2d6569000 00:06 454                       /dev/nvidiactl
7f540d964000-7f540d965000 rwxp 00000000 00:00 0 
7f540d965000-7f540d96c000 r--s 00000000 08:02 5132810                    /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f540d96c000-7f540d96f000 rw-p 00000000 00:00 0 
7f540d96f000-7f540d970000 r--p 00024000 08:02 10486928                   /lib/x86_64-linux-gnu/ld-2.24.so
7f540d970000-7f540d971000 rw-p 00025000 08:02 10486928                   /lib/x86_64-linux-gnu/ld-2.24.so
7f540d971000-7f540d972000 rw-p 00000000 00:00 0 
7ffd6beec000-7ffd6bf0e000 rw-p 00000000 00:00 0                          [stack]
7ffd6bfd4000-7ffd6bfd6000 r--p 00000000 00:00 0                          [vvar]
7ffd6bfd6000-7ffd6bfd8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
```

**Comment by zheng-xq** [comment]
Since both vectorAdd and tf crashed after wakeup, I consider this a Cuda driver issue. TensorFlow holds an active context the entire time. And it seems that the Cuda driver has a problem restoring the active context after the wakeup.

**Comment by mmakowski** [comment]
Thanks for the response, @zheng-xq. I confirmed that if the python session is shut down before the PC is put to sleep and then restarted after the wake up, the problem does not occur, so the issue indeed seems to have something to do with the cuda context being active when the system is suspended. My work-around for now is to restart Jupyter kernel (I use TF mostly from Jupyter notebooks) before suspending the PC. I will try to file a bug against cuda.

**Comment by pierrekilly** [comment]
Hello all!
I was running in the same issue and finally managed to make it work after resume without rebooting the computer.

You just need to `rmmod` the `nvidia` module (and all dependent modules, in my case `nvidia_uvm`) and then `modprobe` them agin (in reverse order):

```
sudo rmmod nvidia_uvm
sudo rmmod nvidia
sudo modprobe nvidia
sudo modprobe nvidia_uvm
```

Hope this helps :)

**Comment by mmakowski** [comment]
Thanks @pierrekilly. Unfortunately this does not work for me ("module is in use") -- probably due to the GPU being the only graphics card in my system.

**Comment by pierrekilly** [comment]
@mmakowski I had this message because I didn't stop my Jupyter notebook server. Make sure you stop everything that could hold the GPU before doing this. I have an hybrid graphic card, so the `module is in use` problem might also be due to the GPU beeing the only graphic card, as you say, but it's worth a try :)

**Comment by harpone** [comment]
I'm having this problem too, and I think it appeared after upgrading TF to 1.1... haven't touched nvidia drivers in a long time. I definitely didn't have that problem before.

Trying `rmmod nvidia`, I get `rmmod: ERROR: Module nvidia is in use by: nvidia_modeset` so now I just have to reboot dammit...

**Comment by pierrekilly** [comment]
@harpone Try like this:
```
sudo rmmod nvidia_modeset
sudo rmmod nvidia
sudo modprobe nvidia
sudo modprobe nvidia_modeset
```
You have to remove the modules that use the `nvidia` one before beeing able to remove it.

**Comment by yuanzhaoYZ** [comment]
Thanks @pierrekilly ! That worked for me.
I was able to get around the issue by running the following script after my devbox wakes up.

```
sudo rmmod nvidia_uvm
sudo rmmod nvidia_drm
sudo rmmod nvidia_modeset
sudo rmmod nvidia
sudo modprobe nvidia
sudo modprobe nvidia_modeset
sudo modprobe nvidia_drm
sudo modprobe nvidia_uvm
```

**Comment by hyuen** [comment]
Is there a solution to this problem for people that only have one gpu and it is being used as a display?

**Comment by denzp** [comment]
A solution that works for me is a systemd service that kills all CUDA consuming processes and restarts `nvidia-docker` (since I use tensorflow inside docker conteiner).

```
$ nvidia-smi -q | grep "Driver Version"

Driver Version: 387.12
```

And the service itself:
```
[Unit]
Description=Kill processes with initialized CUDA before sleep
Before=sleep.target
StopWhenUnneeded=yes

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/zsh -c 'nvidia-smi pmon -c 1 | awk \'$3 == "C" { system("kill -9 " $2) }\''
ExecStart=/usr/bin/systemctl stop nvidia-docker.service
ExecStop=/usr/bin/systemctl start nvidia-docker.service

[Install]
WantedBy=sleep.target
```

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by alextp** [comment]
Closing for now. Please reopen if @denzp's solution or the others mentioned in this thread don't work.

**Comment by YJonmo** [comment]
I had the same problem after waking up the Ubuntu from sleep mode. 
Solution for me was to kill the compiz. 
Perhaps anything else which was left on before the sleep must be killed upon the wake up (as some others have also indicated on this issue).

**Comment by FlorentF9** [comment]
Same issue for me (Linux Mint 18.3, Nvidia Quadro M1200, driver version 384.130, Cuda 9.0 and Keras/TF).

> Thanks @pierrekilly ! That worked for me.
> I was able to get around the issue by running the following script after my devbox wakes up.
> 
> ```
> sudo rmmod nvidia_uvm
> sudo rmmod nvidia_drm
> sudo rmmod nvidia_modeset
> sudo rmmod nvidia
> sudo modprobe nvidia
> sudo modprobe nvidia_modeset
> sudo modprobe nvidia_drm
> sudo modprobe nvidia_uvm
> ```

This does not work for me, I get stuck at `sudo rmmod nvidia_drm`:
```
rmmod: ERROR: Module nvidia_drm is in use
```
It prevents other modules (nvidia_modeset and nvidia) from being stopped.

**Comment by jdknox** [comment]
> A solution that works for me is a systemd service that kills all CUDA consuming processes . . .

```
$ nvidia-smi pmon -c 1

# gpu        pid  type    sm   mem   enc   dec   command
# Idx          #   C/G     %     %     %     %   name
    0       1323     G     0     0     0     0   Xorg
.
.
.
```
Is it recommended to kill Xorg on every suspend?

**Comment by ruffson** [comment]
> Same issue for me (Linux Mint 18.3, Nvidia Quadro M1200, driver version 384.130, Cuda 9.0 and Keras/TF).
> 
> > Thanks @pierrekilly ! That worked for me.
> > I was able to get around the issue by running the following script after my devbox wakes up.
> > ```
> > sudo rmmod nvidia_uvm
> > sudo rmmod nvidia_drm
> > sudo rmmod nvidia_modeset
> > sudo rmmod nvidia
> > sudo modprobe nvidia
> > sudo modprobe nvidia_modeset
> > sudo modprobe nvidia_drm
> > sudo modprobe nvidia_uvm
> > ```
> 
> This does not work for me, I get stuck at `sudo rmmod nvidia_drm`:
> 
> ```
> rmmod: ERROR: Module nvidia_drm is in use
> ```
> 
> It prevents other modules (nvidia_modeset and nvidia) from being stopped.


For what it's worth this is still a problem in 2021 for me on Fedora 33. I tried to follow this advise but I could also not unload `nvidia_drm` for the same reason. But after loading the first module in the list again, things worked for me again. So for me it was just:

```
sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
```

Not claiming this works for everyone though.

**Comment by Mvrjustid** [comment]
If you meet
`rmmod: ERROR: Module nvidia_drm is in use`
when you are trying to do
`sudo rmmod nvidia_uvm
sudo rmmod nvidia_drm
sudo rmmod nvidia_modeset
sudo rmmod nvidia
sudo modprobe nvidia
sudo modprobe nvidia_modeset
sudo modprobe nvidia_drm
sudo modprobe nvidia_uvm`

**Be careful to do the following, if you are unfamiliar with how to use the command line control of Linux**

You may want to try the following
1. change to a text console (pressing Ctrl+Alt+F2)
2. log in as Root
3. `systemctl isolate multi-user.target`
3. Type in the command above one by one, or do the driver update-related things.
4. After you finish, `systemctl start graphical.target`
5. Now, you can try to restart your machine and check if CUDA device become available or not. I'd prefer to verify this by cd into the end of /samples within CUDA-XX folder, and run ./bandwidthTest, e.g., my folder is at /usr/local/cuda-11.2/samples/bin/x86_64/linux/release, then I run '$ ./bandwidthTest'
If you can get this test passed, your device should be available now!

**Comment by hrbigelow** [comment]
For what it's worth, I got this error as well after suspending and waking up.  I didn't need to rmmod / modprobe anything.  Just needed to kill the jupyter notebook that had been running before the suspend.  Note sure if it'll work for others, but worth a try:

[https://forums.developer.nvidia.com/t/reset-driver-without-rebooting-on-linux/40625](https://forums.developer.nvidia.com/t/reset-driver-without-rebooting-on-linux/40625)

"As stated elsewhere, the CUDA runtime should do a pretty good job of cleaning up without any of this as long as you kill any host processes associated with the crash session."

**Comment by ruffson** [comment]
Killing the jupyter notebook (or any of the processes using the GPU) never worked for me.

However I did not have this problem anymore since I started using the recently introduced nvidia systemd services: `nvidia-suspend`, `nvidia-resume` and `nvidia-hybernate` mentioned e.g. [here](https://www.nvidia.com/Download/driverResults.aspx/171981/en-us).

To make it work I added a `nvidia-suspend.conf` to `/etc/modprobe.d/` which just contains:
```
options nvidia NVreg_PreserveVideoMemoryAllocations=1
```
and then enabled these three services. So far I did not have any problems again after using this setup for about a month with several suspends.

**Comment by hrbigelow** [comment]
Ahh, interesting. That does sound like a solid solution.  Just for reference, what setup do you have?

I have
Ubuntu 20.04
GTX 1070 MaxQ
Driver 465.19.01
CUDA 11.3

**Comment by ruffson** [comment]
> Ahh, interesting. That does sound like a solid solution. Just for reference, what setup do you have?
> 
> I have
> Ubuntu 20.04
> GTX 1070 MaxQ
> Driver 465.19.01
> CUDA 11.3

I have
Fedora 34
RTX 3080 (mobile)
Driver 465.31
CUDA 11.3

**Comment by 4ndt3s** [comment]
I have: Ubuntu 20.04, RTX2060 (mobile) and I use the default nvidia drivers (no extra repository setup). First tried with `nvidia-driver-465` (11.3) but it does not have the service files (nvidia-suspend, nvidia-resume and nvidia-hybernate), then I found out that `nvidia-driver-460` (11.2) does:
```
$ apt-file list nvidia-driver-460
....
nvidia-driver-460: /usr/share/doc/nvidia-driver-460/nvidia
nvidia-driver-460: /usr/share/doc/nvidia-driver-460/nvidia-hibernate.service
nvidia-driver-460: /usr/share/doc/nvidia-driver-460/nvidia-resume.service
nvidia-driver-460: /usr/share/doc/nvidia-driver-460/nvidia-sleep.sh
nvidia-driver-460: /usr/share/doc/nvidia-driver-460/nvidia-suspend.service
```
So I installed it with:  
  
`$ sudo apt install nvidia-driver-460`  
  
Then create the file `/etc/modprobe.d/nvidia.conf ` with `options nvidia NVreg_PreserveVideoMemoryAllocations=1` as @ruffson suggests. And restart.  
  
To install the scripts I followed the official instructions from nvidia driver [readme](https://download.nvidia.com/XFree86/Linux-x86_64/460.80/README/powermanagement.html), specifically:  
```
$ sudo install /usr/share/doc/nvidia-driver-460/nvidia-suspend.service /etc/systemd/system/
$ sudo install /usr/share/doc/nvidia-driver-460/nvidia-hibernate.service /etc/systemd/system/
$ sudo install /usr/share/doc/nvidia-driver-460/nvidia-resume.service /etc/systemd/system/
$ sudo install /usr/share/doc/nvidia-driver-460/nvidia /lib/systemd/system-sleep/
$ sudo install /usr/share/doc/nvidia-driver-460/nvidia-sleep.sh /usr/bin/
$ sudo systemctl enable nvidia-suspend.service
$ sudo systemctl enable nvidia-hibernate.service 
$ sudo systemctl enable nvidia-resume.service 
```
And problem solved. My docker containers (with gpus=all) keep working after suspend and resume my laptop.

**Comment by Demetrio92** [comment]
I tried a bunch of things from this thread without any success. 

* disabling `nvidia-suspend.service` and co services
* enabling `nvidia-suspend.service` and co services
* patching `/usr/bin/nvidia-sleep.sh`
* config `options nvidia NVreg_PreserveVideoMemoryAllocations=1`

-----

What did work is **killing all CUDA-utilizing processes before suspending**. Most common scenario would be shutting down jupyter notebooks or terminating running console in an IDE.

**Comment by Demetrio92** [comment]
My service file
```service
[Unit]
Description=Kill processes with initialized CUDA before sleep
Before=suspend.target
StopWhenUnneeded=yes

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/bash -c "nvidia-smi pmon -c 1 | grep 'python' | awk '{ print $2 }' | sudo xargs -n1 kill -9"

[Install]
WantedBy=suspend.target
```

How to enable: https://www.shubhamdipt.com/blog/how-to-create-a-systemd-service-in-linux/

---
I couldn't get @denzp `awk` stuff working, so I simplified it.

**Comment by explodoboy** [comment]
Most definitely a necro, but dropping a quick comment for anyone who's going through the same issue. If you attempt to rmmod any of the modules (in my case, nvidia_uvm) and get:

"rmmod: ERROR: Module nvidia_uvm is not currently loaded"

Then, try to modprobe the missing...module? Don't know the terminology. Anyways, I was able to painlessly fix my own issues with a single _sudo modprobe nvidia_uvm_.

**Comment by jobs-git** [comment]
> > Same issue for me (Linux Mint 18.3, Nvidia Quadro M1200, driver version 384.130, Cuda 9.0 and Keras/TF).
> > > Thanks [@pierrekilly](https://github.com/pierrekilly) ! That worked for me.
> > > I was able to get around the issue by running the following script after my devbox wakes up.
> > > ```
> > > sudo rmmod nvidia_uvm
> > > sudo rmmod nvidia_drm
> > > sudo rmmod nvidia_modeset
> > > sudo rmmod nvidia
> > > sudo modprobe nvidia
> > > sudo modprobe nvidia_modeset
> > > sudo modprobe nvidia_drm
> > > sudo modprobe nvidia_uvm
> > > ```
> > 
> > 
> > This does not work for me, I get stuck at `sudo rmmod nvidia_drm`:
> > ```
> > rmmod: ERROR: Module nvidia_drm is in use
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It prevents other modules (nvidia_modeset and nvidia) from being stopped.
> 
> For what it's worth this is still a problem in 2021 for me on Fedora 33. I tried to follow this advise but I could also not unload `nvidia_drm` for the same reason. But after loading the first module in the list again, things worked for me again. So for me it was just:
> 
> ```
> sudo rmmod nvidia_uvm
> sudo modprobe nvidia_uvm
> ```
> 
> Not claiming this works for everyone though.

This works for me. My docker with tensorflow + torch loses access to CUDA after resuming from sleep. This is even the nvidia-smi from docker still reports an active gpu. This bash from host will restore access for tensorflow + torch

```bash
sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
```
