### ISSUE TITLE
`Nan` errors multiple-gpu training with `MirroredStrategy` - RTX A5000 PCIe4.0

### ISSUE THREAD

**Issue by JGuillaumin** [tensorflow/tensorflow#57893]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### CUDA/cuDNN version

CUDA11.0 & cuDNN8.1.0

### GPU model and memory

RTX A5000 24GB

### Current Behaviour?

```shell
I moved 8 Nvidia RTX A5000 from an old server (ASRockRack 3U8G-C612 : 2 Intel Xeon E5-2640 v4 with 8 PCIe3.0 lanes. Details here https://www.asrockrack.com/general/productdetail.asp?Model=3U8G-C612#Specifications) to a more recent server populated with 10 Nvidia RTX A5000 (including the 8 ones from the former server + 2 new RTX A5000) (Supermicro SYS-420GP-TNR : 2 Intel Xeon Gold 5317 with 12 PCIe4.0 lanes. Details here https://www.supermicro.com/en/products/system/gpu/4u/sys-420gp-tnr). 


I kept the same OS version (Ubuntu 20.04, with kernel=5.13.0-52-generic) and same driver version 515.57.
All the 10 RTX A5000 are visible with `nvidia-smi`, but when I start to execute my code I have `nan` in losses and model's outputs after few iterations (less than 10, sometimes at the second iteration). It happens only when I use multiple GPUs. 


I wrote code that reproduces the errors.

I used docker image provided by Tensorflow : `tensorflow/tensorflow:2.10.0-gpu-jupyter` (SHA `[tensorflow/tensorflow@sha256:a72deb34d32e26cf4253608b0e86ebb4e5079633380c279418afb5a131c499d6]`). 

Choice of `cross_device_ops=tf.distribute.ReductionToOneDevice(reduce_to_device="/cpu:0")` ? 
* If I use `tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.NcclAllReduce())`, the call to `distributed_train_step()` is hanging on the new server .. Need to `docker stop` the container. 
* Whatever the `cross_device_ops` the script is working properly on the old server. 

What you can see in the outputs : 
* Everything is OK for the first replicate, no `nan` in his inputs, `per_samples_losses`
* But for the second replicate (if 2 GPUs) we have `nan` values in `images` used in `train_step()` and `nan` 


What is strange ? 
* `images` from the distributed dataset does not contain `nan` values whiles `images` collected after the train steps contains `nan`
* And these `nan` values are only present on the second replica (or more if more than 2 GPUs) never on the 1st replica. 


After searching on past issues and StackOverflow, as first actions:
* I disabled 'Intel VMX' within BIOS options. Same errors after. 
* Re-install drivers (even to 515.76). Same errors after. I roll-back to 515.57



Also, I added old Nvidia TitanX (Pascal) into the older server to test the code. 
And before, when the 8 RTX A5000 were in the old server, everything was working well with my experiments. 


Feel free to ask me any questions or more details. 

Best regards
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
import os
from pprint import pprint


def main():
    print(f"tf.version.GIT_VERSION : {tf.version.GIT_VERSION}")
    print(f"tf.version.VERSION : {tf.version.VERSION}")

    print("tf.config.list_physical_devices() : ")
    pprint(tf.config.list_physical_devices())

    fashion_mnist = tf.keras.datasets.fashion_mnist

    (train_images, train_labels), (_, _) = fashion_mnist.load_data()
    # create 4D np.ndarray [N,H,W] -> [N,H,W,1]
    train_images = train_images[..., np.newaxis]

    # scale pixels to [0, 1]
    train_images = train_images / np.float32(255)

    # get the tf.distribute.Strategy
    # strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.NcclAllReduce())  # tested
    strategy = tf.distribute.MirroredStrategy(
        cross_device_ops=tf.distribute.ReductionToOneDevice(reduce_to_device="/cpu:0")
    )
    print(f"Strategy : {strategy}")
    print(f"Number of devices: {strategy.num_replicas_in_sync}")

    # some training arguments
    buffer_size = len(train_images)
    batch_size_per_replica = 64
    global_batch_size = batch_size_per_replica * strategy.num_replicas_in_sync

    # create tf.data.Dataset
    train_dataset = (
        tf.data.Dataset.from_tensor_slices((train_images, train_labels))
        .shuffle(buffer_size)
        .batch(global_batch_size)
    )
    # extend to a distributed one version
    train_dist_dataset = strategy.experimental_distribute_dataset(train_dataset)

    with strategy.scope():
        # Set reduction to `NONE` so you can do the reduction afterwards and divide by
        # global batch size.
        loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
            from_logits=True, reduction=tf.keras.losses.Reduction.NONE
        )

        def compute_loss(_labels, _predictions):
            _per_example_loss = loss_object(_labels, _predictions)
            _averaged_loss = tf.nn.compute_average_loss(
                _per_example_loss, global_batch_size=global_batch_size
            )
            return _averaged_loss, _per_example_loss

    with strategy.scope():
        model = create_model()
        optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

    def train_step(inputs):
        _images, _labels = inputs
        with tf.GradientTape() as tape:
            _predictions = model(_images, training=True)
            _averaged_loss, _per_example_loss = compute_loss(_labels, _predictions)

        gradients = tape.gradient(_averaged_loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))

        # return : averaged loss on all example, per_example_loss ([batch_size,] Tensor) and input images
        return _averaged_loss, _per_example_loss, _images

    @tf.function
    def distributed_train_step(dataset_inputs):
        _per_replica_averaged_losses, _per_replica_per_example_loss, _per_replica_images = strategy.run(
            train_step, args=(dataset_inputs,)
        )
        return (
            strategy.reduce(tf.distribute.ReduceOp.SUM, _per_replica_averaged_losses, axis=None),
            _per_replica_per_example_loss,
            _per_replica_images,
        )

    train_dist_iter = iter(train_dist_dataset)
    iteration = 0
    for _ in range(10):
        # get next (images, labels) from the dataset
        images, labels = next(train_dist_iter)
        # do we have nan in these images ?
        print(f"iteration={iteration}")
        if strategy.num_replicas_in_sync > 1:
            print(
                "\t nan in per_replica_images from dataset : ",
                {replica: np.isnan(images.numpy()).any() for replica, images in enumerate(images.values)},
            )
        else:
            # if single replica (CPU or mono-GPU) : specific print statements
            print(
                "\t nan in per_replica_images from dataset : ",
                {0: np.isnan(images.numpy()).any()},
            )

        averaged_loss, per_replica_per_sample_losses, per_replica_images = distributed_train_step(
            (images, labels)
        )
        print(f"\t averaged_loss = {averaged_loss}")

        if strategy.num_replicas_in_sync > 1:
            # do we have nan in images returned by train_step() and distributed_train_step() ?
            print(
                "\t nan in per_replica_images              : ",
                {
                    replica: np.isnan(images.numpy()).any()
                    for replica, images in enumerate(per_replica_images.values)
                },
            )
            # do we have nan in losses per samples per replica ?
            print(
                "\t nan in per_replica_per_sample_losses   : ",
                {
                    replica: np.isnan(per_sample_losses.numpy()).any()
                    for replica, per_sample_losses in enumerate(per_replica_per_sample_losses.values)
                },
            )
            print("\n")
        else:
            # if single replica (CPU or mono-GPU) : specific print statements.
            # do we have nan in images returned by train_step() and distributed_train_step() ?
            print(
                "\t nan in per_replica_images              : ",
                {0: np.isnan(per_replica_images.numpy()).any()},
            )
            # do we have nan in losses per samples per replica ?
            print(
                "\t nan in per_replica_per_sample_losses   : ",
                {0: np.isnan(per_replica_per_sample_losses.numpy()).any()},
            )
            print("\n")

        iteration += 1


def create_model():
    model = tf.keras.Sequential(
        [
            tf.keras.layers.Conv2D(32, 3, activation="relu"),
            tf.keras.layers.MaxPooling2D(),
            tf.keras.layers.Conv2D(64, 3, activation="relu"),
            tf.keras.layers.MaxPooling2D(),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(64, activation="relu"),
            tf.keras.layers.Dense(10),
        ]
    )

    return model


if __name__ == "__main__":
    main()
```

### Relevant log output

```shell
On new server with 2 GPUs : nan in `images` used in the `train_step()` after 1 iteration

CUDA_VISIBLE_DEVICES="0,1" python nan_error_tf.py
[...logs...]
iteration=0
	 nan in per_replica_images from dataset :  {0: False, 1: False}
	 averaged_loss = 2.320328712463379
	 nan in per_replica_images              :  {0: False, 1: False}
	 nan in per_replica_per_sample_losses   :  {0: False, 1: False}

iteration=1
	 nan in per_replica_images from dataset :  {0: False, 1: False}
	 averaged_loss = nan
	 nan in per_replica_images              :  {0: False, 1: True}
	 nan in per_replica_per_sample_losses   :  {0: False, 1: False}

iteration=2
	 nan in per_replica_images from dataset :  {0: False, 1: False}
	 averaged_loss = nan
	 nan in per_replica_images              :  {0: False, 1: True}
	 nan in per_replica_per_sample_losses   :  {0: True, 1: False}

iteration=3
	 nan in per_replica_images from dataset :  {0: False, 1: False}
	 averaged_loss = nan
	 nan in per_replica_images              :  {0: False, 1: True}
	 nan in per_replica_per_sample_losses   :  {0: True, 1: False}


On new server with 1 GPU : No `nan`, no issue. 
```shell
CUDA_VISIBLE_DEVICES="0" python nan_error_tf.py
[... logs ...]
iteration=0
	 nan in per_replica_images from dataset :  {0: False}
	 averaged_loss = 2.3019003868103027
	 nan in per_replica_images              :  {0: False}
	 nan in per_replica_per_sample_losses   :  {0: False}

iteration=1
	 nan in per_replica_images from dataset :  {0: False}
	 averaged_loss = 2.2981200218200684
	 nan in per_replica_images              :  {0: False}
	 nan in per_replica_per_sample_losses   :  {0: False}


iteration=2
	 nan in per_replica_images from dataset :  {0: False}
	 averaged_loss = 2.0697689056396484
	 nan in per_replica_images              :  {0: False}
	 nan in per_replica_per_sample_losses   :  {0: False}

iteration=3
	 nan in per_replica_images from dataset :  {0: False}
	 averaged_loss = 1.8743340969085693
	 nan in per_replica_images              :  {0: False}
	 nan in per_replica_per_sample_losses   :  {0: False}

```
If I use the same script, with 1 or 2 (or more) GPUs on the old server, everything is working well.
```
</details>

**Comment by gadagashwini** [comment]
Hi @JGuillaumin, I got `Nan` in iteration=0, looks like memory allocation exceeded.
Could you confirm the issue by seeing below log.

```
022-09-29 09:33:31.602937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13707 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2022-09-29 09:33:31.605150: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-29 09:33:31.605909: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13777 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5
Strategy : <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x7fb7a455fca0>
Number of devices: 2
2022-09-29 09:33:32.471247: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.
2022-09-29 09:33:32.746323: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.
2022-09-29 09:33:33.056265: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.
2022-09-29 09:33:33.356340: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:784] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
op: "TensorSliceDataset"
input: "Placeholder/_0"
input: "Placeholder/_1"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_FLOAT
      type: DT_UINT8
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: 60000
  }
}
attr {
  key: "is_files"
  value {
    b: false
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\024TensorSliceDataset:0"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 28
        }
        dim {
          size: 28
        }
        dim {
          size: 1
        }
      }
      shape {
      }
    }
  }
}
attr {
  key: "replicate_on_split"
  value {
    b: false
  }
}
experimental_type {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_DATASET
    args {
      type_id: TFT_PRODUCT
      args {
        type_id: TFT_TENSOR
        args {
          type_id: TFT_FLOAT
        }
      }
      args {
        type_id: TFT_TENSOR
        args {
          type_id: TFT_UINT8
        }
      }
    }
  }
}

2022-09-29 09:33:33.489965: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.
iteration=0
         nan in per_replica_images from dataset :  {0: False, 1: False}
```

**Comment by JGuillaumin** [comment]
After testing many stuff (update kernel, remove some GPUs (keep only 2, 4 or 8), compiling from source, playing with many obscure Nvidia env variables, ...) I realized that I had the same issue with pytorch code. 

After digging more into NCCL issues, I found this [one](https://github.com/NVIDIA/nccl/issues/606) and this documentation page from [NCCL](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs). 

> IO virtualization (also known as, VT-d or IOMMU) can interfere with GPU Direct by redirecting all PCI point-to-point traffic to the CPU root complex, causing a significant performance reduction or even a hang.

I had to disable ACS from the BIOS. Now everything is working well.
