### ISSUE TITLE
nvcc fatal   : Unknown option '-expt-relaxed-constexpr' while bazel build

### ISSUE THREAD

**Issue by kkjh0723** [tensorflow/tensorflow#5799]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

### Environment info
Operating System: Ubuntu 14.04.4

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA v7.0
cuDNN 4

    -rw-r--r-- 1 root root   310328  3월  6  2015 /usr/local/cuda/lib64/libcudadevrt.a
    lrwxrwxrwx 1 root root       16  3월  6  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.0
    lrwxrwxrwx 1 root root       19  3월  6  2015 /usr/local/cuda/lib64/libcudart.so.7.0 -> libcudart.so.7.0.28
    -rwxr-xr-x 1 root root   377896  3월  6  2015 /usr/local/cuda/lib64/libcudart.so.7.0.28
    -rw-r--r-- 1 root root   708938  3월  6  2015 /usr/local/cuda/lib64/libcudart_static.a
    -rwxr-xr-x 1 root root 61453024  6월  9 18:46 /usr/local/cuda/lib64/libcudnn.so
    -rwxr-xr-x 1 root root 61453024  6월  9 18:46 /usr/local/cuda/lib64/libcudnn.so.4
    -rwxr-xr-x 1 root root 61453024  6월  9 18:46 /usr/local/cuda/lib64/libcudnn.so.4.0.7
    -rwxr-xr-x 1 root root 48217000 11월 24  2015 /usr/local/cuda/lib64/libcudnn.so.7.0
    -rwxr-xr-x 1 root root 48217000 11월 24  2015 /usr/local/cuda/lib64/libcudnn.so.7.0.64
    -rw-r--r-- 1 root root 62025862  6월  9 18:46 /usr/local/cuda/lib64/libcudnn_static.a

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
55dbc54192a378c5e685c52595f42503f037320e

2. The output of `bazel version`

    Build label: 0.3.2
    Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

I'm trying to install from source and faces following errors while build. I'm not sure what is the problem. Is this because of CUDA version?

    bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
    
    ...
    ERROR: /home/jinhyung/tensorflow/tensorflow/core/kernels/BUILD:1128:1: error while parsing .d file: /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/resize_nearest_neighbor_op_gpu/tensorflow/core/kernels/resize_nearest_neighbor_op_gpu.cu.pic.d (No such file or directory).
    nvcc fatal   : Unknown option '-expt-relaxed-constexpr'
    Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by prb12** [comment]
Your bazel version does not appear to be very recent..
Could you try installing a recent build as per https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#installing-from-sources ?

**Comment by kkjh0723** [comment]
Thanks for the answer. However, it shows same error after I changed the bazel to the latest version. I did again from configure step.

**Comment by jarya** [comment]
I was able to fix this by reverting #5256. Turns out this flag isn't compatible with CUDA 7.0.

**Comment by prb12** [comment]
@gunan I believe we still support CUDA 7.0?  Could you please take a look at this.

**Comment by vrv** [comment]
I reverted it the same day in
https://github.com/vrv/tensorflow/commit/14bc025ffb79a224d027ca29ca5a8ab128ff6646

**Comment by prb12** [comment]
@vrv Thanks Vijay!  Hadn't noticed that.
@kkjh0723  Could you please sync to head and confirm that the problem is already fixed?

**Comment by vrv** [comment]
Interesting, I thought I merged that, but it never went through in master.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L424 :(

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/commit/14bc025ffb79a224d027ca29ca5a8ab128ff6646 So I did merge it, and then
https://github.com/tensorflow/tensorflow/commit/584d4a193c41918d33d0d43c0d13b055dfb5b254 added it back somehow.  Bleh :(

**Comment by gunan** [comment]
argh, cant figure out git, I guess it was a bad merge?
