### ISSUE TITLE
tf.numpy_function in tf.data.Dataset.map causes CUDA_ERROR_OUT_OF_MEMORY after hundreds of epochs

### ISSUE THREAD

**Issue by RocaVincent** [tensorflow/tensorflow#58747]
### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10.6

### Bazel version

5.3.2

### GCC/Compiler version

gcc 9.3.0

### CUDA/cuDNN version

11.8/8.6.0

### GPU model and memory

Nvidia Quadro RTX 6000, 25.8G memory

### Current Behaviour?

```shell
I use `tf.data.Dataset` for my input pipeline as follows:
  1. `from_generator`
  2. `cache`
  3. `shuffle`
  4. `repeat`
  5. `map`
  6. `batch`
  7. `prefetch`

The step 5 call a data-augmentation function where there is a call to `tf.numpy_function` which wraps `scipy.ndimage.rotate`.

After a variable number of epochs (in general more than 100), a `CUDA_OUT_OF_MEMORY` appears and the kernel crashed. If I remove the call to `tf.numpy_function` from the data-augmentation function, I don't have this problem. Note that I don't use `tf.py_function` as it looks much slower.
```

### Standalone code to reproduce the issue

```shell
I haven't managed to create a simple reproducer for this bug.
```

### Relevant log output

```shell
2022-12-01 02:26:32.244730: E tensorflow/stream_executor/cuda/cuda_driver.cc:796] failed to alloc 17179869184 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2022-12-01 02:26:32.299769: W ./tensorflow/core/common_runtime/device/device_host_allocator.h:46] could not allocate pinned host memory of size: 17179869184
```

**Comment by tilakrayal** [comment]
@RocaVincent,
Could you please try limiting GPU memory growth using any of the methods listed in this guide.
https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth

Also tensorflow v2.10 is not compatible with CUDA/CudNN - 11.8/8.6.0. Please take a look at this official doc [link](https://www.tensorflow.org/install/source#gpu) for the reference. Thank you!

**Comment by tilakrayal** [comment]
@RocaVincent,
In order to expedite the trouble-shooting process, could you please provide a complete code you are using. Thank you!

**Comment by RocaVincent** [comment]
@tilakrayal The code is too complexe and I haven't managed to create a simple reproducer. But I tried the same code with the [classical pip install](https://www.tensorflow.org/install/pip) and the error disappeared.
