### ISSUE TITLE
Issue with CUDA library directory not being detected properly by Tensorflow Ubuntu 22.04

### ISSUE THREAD

**Issue by Srking501** [tensorflow/tensorflow#59013]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.9.13

### CUDA/cuDNN version

11.6

### Current Behaviour?

```shell
I have followed the exact instruction of installing TensorFlow under pip and made sure that I had installed the right drivers from the official Ubuntu repositories (`nvidia-driver-510`, `nvidia-cuda-toolkit`, `nvidia-cudnn`). Then ran `python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"` which was successful with only the obvious warning that I had not installed the optional [TensorRT](https://docs.nvidia.com/deeplearning/tensorrt/archives/index.html#trt_7)

However, I had this lingering issue when running simple model using [Tensorflow beginner tutorial](https://www.tensorflow.org/tutorials/quickstart/beginner) that it kept stating that my GPU is out of memory. 

It turns out that it could not find the CUDA library directory which expected it to be installed under `/usr/local/cuda`, but Ubuntu `apt` installed it in `/usr/lib/cuda`. The temporary solution I have made was to create a symlink `sudo ln -s /usr/lib/cuda /usr/local/cuda` which made TensorFlow work and run the model (so far everything is working fine).

Furthermore, I remember having this problem back when I was Pop!_OS 20.04 in 2020.
```

### Standalone code to reproduce the issue

```shell
If you start a new Ubuntu 22.04 desktop, first use a *default* install of [Anaconda base (version 2022.10)](https://repo.anaconda.com/archive/Anaconda3-2022.10-Linux-x86_64.sh) then do the following:


# Install nvidia drivers and the cuda + cudnn libraries
sudo apt install nvidia-driver-510 nvidia-cuda-toolkit nvidia-cudnn

# Run the [Tensorflow setup](https://www.tensorflow.org/install/pip) - Last updated 2022-12-20 UTC.
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/

# Enter Anaconda base first before continuing at the rest of the setup
conda activate base
python3 -m pip install tensorflow
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"


It then should display like the following:

```
2022-12-25 20:02:49.726066: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-25 20:02:50.208855: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-25 20:02:50.208895: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-12-25 20:02:50.208901: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-12-25 20:02:50.833468: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-12-25 20:02:50.858985: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-12-25 20:02:50.859152: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

Using the [TensorFlow 2 quickstart for beginners notebook](https://www.tensorflow.org/tutorials/quickstart/beginner) - Last updated 2022-12-23 UTC - first install jupyter under the Anaconda base:

```bash
pip install notebook
```

Run all, this block should fail:

## Train and evaluate your model

Use the `Model.fit` method to adjust your model parameters and minimize the loss: 

```Python
model.fit(x_train, y_train, epochs=5)
```

It returns this error:

```
Epoch 1/5
2022-12-25 20:03:55.460107: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:326] libdevice is required by this HLO module but was not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
2022-12-25 20:03:55.460453: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
2022-12-25 20:03:55.487711: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:326] libdevice is required by this HLO module but was not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
2022-12-25 20:03:55.487986: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
2022-12-25 20:03:55.504571: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:326] libdevice is required by this HLO module but was not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
2022-12-25 20:03:55.504808: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
2022-12-25 20:03:55.520155: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:326] libdevice is required by this HLO module but was not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
2022-12-25 20:03:55.520379: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:446 : INTERNAL: libdevice not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
/tmp/ipykernel_16666/2168363081.py in <module>
----> 1 model.fit(x_train, y_train, epochs=5)

~/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     50   try:
     51     ctx.ensure_initialized()
---> 52     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     53                                         inputs, attrs, num_outputs)
     54   except core._NotOkStatusException as e:

InternalError: Graph execution error:

Detected at node 'StatefulPartitionedCall_2' defined at (most recent call last):
    File "/home/srking501/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/srking501/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
...
    File "/home/srking501/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_2'
libdevice not found at /usr/local/cuda/nvvm/libdevice/libdevice.10.bc
	 [[{{node StatefulPartitionedCall_2}}]] [Op:__inference_train_function_40623]
```

As you can see it is trying to access `/usr/local/cuda` however Ubuntu 22.04 default installation of Nvidia CUDA is in `/usr/lib/cuda`. Therefore, if you create a symlink to the actual place of CUDA it should work when you rerun the model: 

```
sudo ln -s /usr/lib/cuda/ /usr/local/cuda
```

(tl;dr) In conclusion, the problem is that it is trying to find CUDA in `/usr/local/cuda` but Ubuntu default location of CUDA library by Ubuntu's official repositories is in `/usr/lib/cuda`, thus requiring to make the solution of symlink (look right above this paragraph).
```


### Relevant log output

```shell
2022-12-25 20:11:21.322263: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-25 20:11:21.806424: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-25 20:11:21.806462: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-12-25 20:11:21.806467: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
v2.11.0-rc2-17-gd5b57ca93e5 2.11.0
```
</details>

**Comment by RustyToms** [comment]
I had a similar problem the last few days following the instructions at https://www.tensorflow.org/install/pip, for Ubuntu Linux on Windows 11 WSL2. After looking through several similar situations it seemed that the XLA_FLAGS environment variable needed to be updated with the location of the cuda installation. It seemed to me that something went wrong with the miniconda tensorflow installation, I couldn't even find the cuda files. So I installed it without miniconda: `sudo apt install nvidia-cuda-toolkit` but it still didn't work until I updated the ~/.profile file with `export XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/cuda/`, which is where the installation ended up, and restarted the session. Then everything worked fine.

I'm not sure if it was just me and the process of fiddling trying to fix it but I made a few other changes to my .profile file that may have contributed, so here it is in full. This Ubuntu Linux instance was only setup to run a local session of Google Colab with tensorflow right now.

```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

#DO THESE BEFORE .bashrc IS CALLED SO MINICONDA IS FIRST IN THE PATH,
# OR ELSE MINICONDA DOESN'T WORK
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# Make Nvidia Cuda less noisy with warnings
export TF_CPP_MIN_LOG_LEVEL="2"

#Tell tensorflow where CUDA is
export XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/cuda/


# Configure system paths for Conda
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
```

**Comment by SuryanarayanaY** [comment]
Hi @Srking501 ,
I have tried to replicate the issue you mentioned in a VM with Ubuntu 20.04, 2 x NVIDIA A100 40GB GPUs, x86/64 Architecture and with Venv of TF2.11.Initially i got the same error as mentioned by you.Then i tried `whereis cuda` command and it returns location `cuda: /local/usr/cuda` which is contrast. Then i proceeded with commands as per below attached photographs and the Error is gone. Even though my VM has Ubuntu 20.04 but the Error is same as you mentioned which was  mentioned by you.For me the error was gone and starts working fine when i installed nvidia-cuda-toolkit in venv. 

<img width="1512" alt="Screenshot 2022-12-28 at 6 58 49 PM" src="https://user-images.githubusercontent.com/116063290/209822861-c03fd229-e49b-46b5-b63d-5aca087c82b5.png">
<img width="1512" alt="Screenshot 2022-12-28 at 6 58 49 PM" src="https://user-images.githubusercontent.com/116063290/209823080-7f226329-5a71-4972-b117-3236620effb8.png">
<img width="1512" alt="Screenshot 2022-12-28 at 6 59 23 PM" src="https://user-images.githubusercontent.com/116063290/209823105-d633a737-ed85-47fc-8c45-c47f3e6e63a7.png">
 Could you please refer above details and comeback with your views ?

**Comment by Srking501** [comment]
Tensorflow requires the use of the CUDA library toolkit to be able to utilise the Nvidia's GPUs (`nvidia-cuda-toolkit`) - also requires the use of Nvidia CUDNN library to run the model under the [Tensorflow beginner tutorial `Last updated 2022-12-23 UTC`](https://www.tensorflow.org/tutorials/quickstart/beginner), at least in Ubuntu 22.04 desktop (`nvidia-cudnn`). So that seems to be right. 

However, I have noticed that the [Ubuntu Official Repository of `nvidia-cuda-toolkit`](https://packages.ubuntu.com/jammy/nvidia-cuda-toolkit) installs the CUDA library in `/usr/lib/cuda` whereas if you use (Nvidia's Official Repository of `cuda` for Ubuntu)[https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu] and install it through `sudo apt-get install cuda` (and to include all GDS packages `sudo apt-get install nvidia-gds`) the CUDA library will end up in `/usr/local/cuda`.

**Comment by SuryanarayanaY** [comment]
Hi @Srking501 ,

Thanks for confirmation.It seems the behaviour in VM has been different.I will also double check VM behaviour meanwhile with fresh installation. 
I assume the behaviour mentioned by you is in Local Linux desktop right? So in your case symlink using `sudo ln -s /usr/lib/cuda/ /usr/local/cuda` alone worked for your case ?Whether XLA compilation also works with it or it needs additional `export XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/cuda/` setting in `~/.profile `.Could you please test and confirm the same so that it can taken care in documentation or if possible in build config also.

Thank you!

**Comment by Srking501** [comment]
Glad for all the help and replies! I would test the following and get back to you. But first, may I ask how do I do XLA compilation?

**Comment by SuryanarayanaY** [comment]
Hi @Srking501 ,
XLA compilation can be done by the setting `jit_compile=True` or `jit_compile='autoclustering'`. For keras models you can pass this argument during `model.compile()` and for custom training loops you can pass it to `tf.function()`.Please note that not all Ops are compatible to XLA.
We have also option of autoclustering which automatically does jit_compilation if the Op is available for jit_compile but this is also having limitations and also kind of unpredictable w.r.t behaviour and performance.

Please refer to attached resource [here](https://www.tensorflow.org/xla) and subsequent pages for details about XLA and how to implement it in the code.
You may test with minimal code only that might be available  from the tutorials.

Thank you!

**Comment by Srking501** [comment]
Sorry for the delay, I have still have not tested to what you stated. I was really busy at the time; I will hopefully reply within 2 Days - if further delays happen, I will notify this issue about it.

**Comment by Srking501** [comment]
Hello @SuryanarayanaY,

I've tried to make `XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/cuda/` in `~/.profile` but always breaks for me, I still do not what it is (maybe try it in your side by spinning a [Ubuntu Desktop Image](https://ubuntu.com/download/desktop)).

But at least, the `sudo ln -s /usr/lib/cuda/ /usr/local/cuda` seemed to be working fine with no issues.

I deeply apologise for the delay, I had really busy 2 weeks.

Kindest Regards and Thank you for taking the issue.

**Comment by SuryanarayanaY** [comment]
Hello @Srking501 ,

I have tested on VM with Ubuntu 22.04 and the installation done at usr/local/cuda-12.0 as attached below.

<img width="1512" alt="Screenshot 2023-01-19 at 11 51 56 AM" src="https://user-images.githubusercontent.com/116063290/213375677-eea4626a-e4b8-44b5-a947-24183f00d442.png">

Then i tested the code referred by you and it's executing fine and GPU also detected fine.
```
(tf) suryanarayanay@surya-ubuntu-22-04:~$ python beginner.py
2023-01-19 06:49:32.677942: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-19 06:49:32.810478: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-19 06:49:33.596668: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/suryanarayanay/miniconda3/envs/tf/lib/
2023-01-19 06:49:33.596770: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/suryanarayanay/miniconda3/envs/tf/lib/
2023-01-19 06:49:33.596784: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
TensorFlow version: 2.11.0
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 0s 0us/step
2023-01-19 06:49:39.104320: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-19 06:49:40.471785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38235 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
2023-01-19 06:49:40.473583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38235 MB memory:  -> device: 1, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:05.0, compute capability: 8.0
2023-01-19 06:49:42.296781: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
Epoch 1/5
2023-01-19 06:49:43.592397: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x23fe2930 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-01-19 06:49:43.592434: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA A100-SXM4-40GB, Compute Capability 8.0
2023-01-19 06:49:43.592441: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (1): NVIDIA A100-SXM4-40GB, Compute Capability 8.0
2023-01-19 06:49:43.597561: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-01-19 06:49:43.679944: I tensorflow/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2023-01-19 06:49:43.732617: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2939 - accuracy: 0.9146
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1470 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1113 - accuracy: 0.9660
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0894 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0779 - accuracy: 0.9749
313/313 - 1s - loss: 0.0709 - accuracy: 0.9783 - 593ms/epoch - 2ms/step
(tf) suryanarayanay@surya-ubuntu-22-04:~$ whereis cuda
cuda: /usr/local/cuda
(tf) suryanarayanay@surya-ubuntu-22-04:~$ 
```
I learnt that some Local Ubuntu OS coming with pre installed Nvidia drivers.May be the difference may be due to the way CUDA drivers being installed.On the VM I tested it installs the driver/cuda toolkit as expected.We can get the location of CUDA using `whereis cuda` and if it could not found at `usr/local/cuda` then sym link as confirmed by you will make it works.

Thanks for sharing your observations and discussions happened in the thread.Shall we close the issue if the purpose resolved.

Thank you!
