### ISSUE TITLE
Crash when running tensorflow.python.ops.gen_nn_ops.fused_batch_norm_grad_v3

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59399]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_nn_ops
try:
  try:
    with tf.device('/CPU'):
      y_backprop_tensor = tf.random.uniform([4, 10, 10, 2], dtype=tf.float32)
      y_backprop = tf.identity(y_backprop_tensor)
      x_tensor = tf.random.uniform([4, 10, 10, 2], dtype=tf.float32)
      x = tf.identity(x_tensor)
      scale_tensor = tf.random.uniform([2], dtype=tf.float32)
      scale = tf.identity(scale_tensor)
      reserve_space_1_tensor = tf.random.uniform([2], dtype=tf.float32)
      reserve_space_1 = tf.identity(reserve_space_1_tensor)
      reserve_space_2_tensor = tf.random.uniform([2], dtype=tf.float32)
      reserve_space_2 = tf.identity(reserve_space_2_tensor)
      epsilon = -43.999
      data_format = "NHWC"
      is_training = True
      reserve_space_3_tensor = tf.random.uniform([], dtype=tf.float32)
      reserve_space_3 = tf.identity(reserve_space_3_tensor)
      out = gen_nn_ops.fused_batch_norm_grad_v3(y_backprop=y_backprop,x=x,scale=scale,reserve_space_1=reserve_space_1,reserve_space_2=reserve_space_2,epsilon=epsilon,data_format=data_format,is_training=is_training,reserve_space_3=reserve_space_3,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      y_backprop = tf.identity(y_backprop_tensor)
      y_backprop = tf.cast(y_backprop, tf.float32)
      x = tf.identity(x_tensor)
      x = tf.cast(x, tf.float32)
      scale = tf.identity(scale_tensor)
      scale = tf.cast(scale, tf.float32)
      reserve_space_1 = tf.identity(reserve_space_1_tensor)
      reserve_space_1 = tf.cast(reserve_space_1, tf.float32)
      reserve_space_2 = tf.identity(reserve_space_2_tensor)
      reserve_space_2 = tf.cast(reserve_space_2, tf.float32)
      reserve_space_3 = tf.identity(reserve_space_3_tensor)
      reserve_space_3 = tf.cast(reserve_space_3, tf.float32)
      gen_nn_ops.fused_batch_norm_grad_v3(y_backprop=y_backprop,x=x,scale=scale,reserve_space_1=reserve_space_1,reserve_space_2=reserve_space_2,epsilon=epsilon,data_format=data_format,is_training=is_training,reserve_space_3=reserve_space_3,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-22 05:52:28.151968: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-22 05:52:28.716365: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/
2023-01-22 05:52:28.716529: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/
2023-01-22 05:52:28.716537: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-22 05:52:29.223621: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.228281: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.228421: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.228740: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-22 05:52:29.229170: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.229271: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.229359: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.601354: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.601502: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.601600: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 05:52:29.601697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3521 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
2023-01-22 05:52:30.152358: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:428] Loaded cuDNN version 8100
2023-01-22 05:52:30.154285: E tensorflow/compiler/xla/stream_executor/dnn.cc:887] CUDNN_STATUS_BAD_PARAM
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(5936): 'cudnnBatchNormalizationBackward( cudnn.handle(), mode, &one, &zero, &one, &zero, x_descriptor.handle(), x.opaque(), x_descriptor.handle(), y_backprop.opaque(), x_descriptor.handle(), x_backprop->opaque(), scale_offset_descriptor.handle(), scale.opaque(), scale_backprop->opaque(), offset_backprop->opaque(), epsilon, mean.opaque(), inv_var.opaque())'
Error:{{function_node __wrapped__FusedBatchNormGradV3_device_/job:localhost/replica:0/task:0/device:GPU:0}} cuDNN launch failure : input shape ([4,10,10,2]) [Op:FusedBatchNormGradV3]

```
```
</details>

**Comment by synandi** [comment]
@tilakrayal, could you please check this issue?

I was able to replicate the issue with negative epsilon values(<=-1) in Colab in TF v2.11, kindly refer to this [gist](https://colab.sandbox.google.com/gist/synandi/1cd98cf2f3ecb010a53bb810e042755f/59399.ipynb). The above issue is not producing errors when the epsilon values are positive or -0. Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/ed4a1a2fd89e35437db07efb1f27e4ad/59399_2.ipynb). Thank you!

**Comment by mihaimaruseac** [comment]
not a vuln

**Comment by rajasekharporeddy** [comment]
Hi @dmc1778 

The issue seems to be fixed in recent TensorFlow versions. I have verified the repro code with TF 2.17.1 on Colab T4 GPU, and it now correctly throws an Exception.

```
Error:{{function_node __wrapped__FusedBatchNormGradV3_device_/job:localhost/replica:0/task:0/device:GPU:0}} cuDNN launch failure : input shape ([4,10,10,2]) [Op:FusedBatchNormGradV3] name:
```

Please find the attached [gist](https://colab.sandbox.google.com/gist/malla456/4950939e41cea2e8c78822f181698c52/tf_59399.ipynb) for reference.

Thank you.

**Comment by malla456** [comment]
Hi@comckay,
I have reviewed the code and made some changes,changed [1] to tf.constant([1]).
It is working fine for me. Please find the [gist](https://colab.sandbox.google.com/gist/malla456/382a3cb4acd33a07175324f001549d3c/56819.ipynb) here for reference.
Thank you!
