### ISSUE TITLE
You must feed a value for placeholder tensor ... with dtype int32

### ISSUE THREAD

**Issue by Davidy22** [tensorflow/tensorflow#59779]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

v1.12.1-89814-gbaac3548e86 2.13.0-dev20230222

### Custom Code

No

### OS Platform and Distribution

Fedora Linux 37

### Python version

3.11

### CUDA/cuDNN version

CUDA Version: 12.0, CUDNN unavailable,  not using gpu anyway

### Current Behaviour?

```shell
When training a model defined with the subclass interface, tensorflow throws up many copies of a warning that doesn't appear to have any visible consequences. It does not halt training and model performance seems unaffected, but reporting because somewhat unsightly and may be the source of some insidious error. This error message did not appear when running the same code under TF 2.11, python 3.10. Issue began immediately after upgrade to TF 2.12, python 3.11. Also confirmed present in nightly.
```

### Standalone code to reproduce the issue

```shell
from tensorflow import keras

class build_rnn(keras.Model):
  def __init__(self, layer_size = 128, dim = 5, dropout = 0.2):
    super().__init__(self)
    self.pre = keras.Sequential([keras.layers.Input(shape=(None, dim), ragged=True), keras.layers.GaussianNoise(0.2)])

    self.rnn1 = keras.layers.LSTM(layer_size, return_sequences = True, return_state = True, dropout = dropout, kernel_regularizer=l1(1e-6), recurrent_regularizer=l1(1e-6), bias_regularizer=l1(1e-6))
    self.bn = keras.layers.BatchNormalization()
    self.rnn2 = keras.layers.LSTM(layer_size, return_sequences = True, return_state = True, dropout = dropout, kernel_regularizer=l2(1e-6), recurrent_regularizer=l2(1e-6), bias_regularizer=l2(1e-6))
    self.res = keras.layers.Add()
    self.rnn3 = keras.layers.LSTM(layer_size, return_sequences = False, return_state = True, dropout = dropout, kernel_regularizer=l1_l2(1e-6), recurrent_regularizer=l1_l2(1e-6), bias_regularizer=l1_l2(1e-6))
    
    self.dense1 = keras.layers.Dense(32, kernel_regularizer=l1(1e-5), bias_regularizer=l2(1e-5))
    self.bn2 = keras.layers.BatchNormalization()
    self.dense2 = keras.layers.Dense(16, kernel_regularizer=l2(1e-5), bias_regularizer=l1_l2(1e-5))
    self.hosp_out = keras.layers.Dense(1, activation = "sigmoid")

    self.dense4 = keras.layers.Dense(128, kernel_regularizer=l1(1e-5), bias_regularizer=l2(1e-5))
    self.dropout3 = keras.layers.Dropout(0.2)
    self.dense5 = keras.layers.Dense(64, kernel_regularizer=l2(1e-6), bias_regularizer=l1_l2(1e-5))
    self.row_out = keras.layers.Dense(dim, activation = "linear")

    
  def call(self, inputs, states=None, return_state=False, training=False):
    x = inputs
    x = self.pre(x, training=training)
    if states is not None: s1, s2, s3 = states
    else: s1 = s2 = s3 = None

    x, h1, s1 = self.rnn1(x, initial_state=s1, training=training)
    xr = self.bn(x, training=training)
    xr, h2, s2 = self.rnn2(xr, initial_state=s2, training=training)
    x = self.res([x, xr])
    x, h3, s3 = self.rnn3(x, initial_state=s3, training=training)

    y = self.dense1(x, training=training)
    y = self.bn2(y, training=training)
    y = self.dense2(y, training=training)
    y = self.hosp_out(y, training=training)

    z = self.dense4(x, training=training)
    z = self.dropout3(z, training=training)
    z = self.dense5(z, training=training)
    z = self.row_out(z, training=training)

    if return_state:
      return y, z, ([h1, s1], [h2, s2], [h3, s3])
      #return x, [h1, s1]
    else:
      return y, z


rmodel = build_rnn(dim = len(columns))

rmodel.compile(loss = ["binary_crossentropy", 'mse'], optimizer=keras.optimizers.experimental.AdamW())

rmodel.fit(x_train, [y_train, z_train], epochs = 100, callbacks=callbacks.EarlyStopping(monitor="loss", patience=7), verbose = 2)
```

### Relevant log output

```shell
2023-02-23 16:48:07.354061: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-02-23 16:48:07.355191: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-02-23 16:48:07.356586: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-02-23 16:48:07.569860: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-02-23 16:48:07.571111: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-02-23 16:48:07.572353: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-02-23 16:48:07.762177: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-02-23 16:48:07.763419: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-02-23 16:48:07.764506: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-02-23 16:48:09.234512: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-02-23 16:48:09.235990: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-02-23 16:48:09.237207: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-02-23 16:48:09.419726: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-02-23 16:48:09.420944: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-02-23 16:48:09.422073: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-02-23 16:48:09.593760: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-02-23 16:48:09.595009: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-02-23 16:48:09.596323: I tensorflow/core/common_runtime/executor.cc:1214] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
```
</details>

**Comment by synandi** [comment]
I was able to replicate the issue in Fedora Linux 37 iusing tf-nightly. Please find the screenshot of the same below.
![image](https://user-images.githubusercontent.com/98147397/220966631-18b16166-bc9d-47e9-a46f-5799e1109ff1.png)
It seems like we have to dig more into this issue, we will update soon here. Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @Davidy22 , Thanks for reporting.

This problem already brought to our attention.This log is safe to ignore as you can see the below message from log.
It is also not affecting the functionality here. Please refer to the comment [here](https://github.com/tensorflow/tensorflow/issues/59117#issuecomment-1402908928) that this log may provide context for some other errors for certain use cases.But it should be moved to debug log for which action is under progress.

> Executor start aborting (this does not indicate an error and you can ignore this message)

**Comment by Davidy22** [comment]
Yeah, it didn't actually impact any of my running code, which ran pretty much the same between tf 2.11 and 2.12 with the only visible difference being that unsightly message. The downgrade would be appreciated, I would like to have less harmless error messages filling screens when not needed

**Comment by SuryanarayanaY** [comment]
Hi @Davidy22 ,
Incase If you want to filter out the logs to only Warning and above levels you can use the below code at the top of your code.

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
```

**Comment by Davidy22** [comment]
Oh that'll be nice. I assume it'll also potentially end up hidiing messages that I might want to see, but this should be good enough until the  tf release happens that cleans this up. I'm on 2.12 RC0, I presume I'll see the resolution to this come down in the final release?

**Comment by SuryanarayanaY** [comment]
@Davidy22 ,
This is already under purview of Developer team.I hope this might be resolved in next release mostly. 

Thanks!

**Comment by egolfbr** [comment]
> TF_CPP_MIN_LOG_LEVEL

This did not work for me. 
Instead 
`export TF_CPP_MIN_LOG_LEVEL=2`

**Comment by shkarupa-alex** [comment]
Same issue (a lot of spam messages) starting from tf 2.12

**Comment by learning-to-play** [comment]
Hi @qqfish, Commit [80a4e5f9e4e103f722df3632db88fdb31537bb26](https://github.com/tensorflow/tensorflow/commit/80a4e5f9e4e103f722df3632db88fdb31537bb26) introduced extra log messages (for most Intel Models) and caused performance degradation. Intel would like to know if this change can be rolled back. Could you please share your thoughts?

**Comment by pradip-gubhaju** [comment]
Somebody helpe me please...

2023-05-22 20:15:25.042266: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-22 20:15:25.047489: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-05-22 20:15:33.030265: I tensorflow/core/common_runtime/executor.cc:1210] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): CANCELLED: GetNextFromShard was cancelled
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
2023-05-22 20:15:33.030866: I tensorflow/core/common_runtime/executor.cc:1210] [/job:localhost/replica:0/task:0/device:GPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): CANCELLED: GetNextFromShard was cancelled
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]] [type.googleapis.com/tensorflow.DerivedStatus='']

**Comment by Pranil51** [comment]
> @Davidy22 , This is already under purview of Developer team.I hope this might be resolved in next release mostly.
> 
> Thanks!

any update regarding it @SuryanarayanaY

**Comment by naddeoa** [comment]
> 

Make sure you `os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'` before you import tensorflow.

**Comment by shkarupa-alex** [comment]
It's a bad decision to make unuseful logging and force users to disable it.

**Comment by JKubovy** [comment]
The problem is that in the flood of many "fake" warnings, the real one can get lost.

**Comment by SuryanarayanaY** [comment]
CC ing - @qqfish for update.

**Comment by MasterHM-ml** [comment]
> Hi @Davidy22 , Incase If you want to filter out the logs to only Warning and above levels you can use the below code at the top of your code.
> 
> ```
> import os
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
> ```

This solved my issue of flooding my terminal with this warning `log`. I am using **Google Colab**.

**Comment by zhezherun** [comment]
Any chance of backporting a fix for this from TF2.13 into TF2.12.x?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by Davidy22** [comment]
Oh, I haven't seen the issue in a while, fully forgot about it. I guess if I haven't seen it that probably means this got cleared up at some point. I kind of thought a dev would have closed this ticket after fixing the issue, I see there was a PR that referred to this ticket a while back and then we didn't have anyone come round to close this when that got merged, I'll close this one now.
