### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by dkokron** [tensorflow/tensorflow#5994]
Attempting to install master on a SLES11sp3 system under
gcc-4.9.3
Python 3.5.1
bazel-0.4.1

TensorFlow hash is
git rev-parse HEAD
a70a2d9f0e7d34e36018e83e4b17c45a26a2f3dc

Seems similar to
https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/Tm5ztabIUCw

./configure
~/play/TensorFlow/tensorflow ~/play/TensorFlow/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: /nasa/pkgsrc/2016Q2/bin/python3.5
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /nasa/pkgsrc/2016Q2/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/nasa/pkgsrc/2016Q2/lib/python3.5/site-packages]

Using python library path: /nasa/pkgsrc/2016Q2/lib/python3.5/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] N
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /nasa/pkgsrc/2015Q4/gcc49/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /nasa/cuda/7.5
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /nasa/cuda/7.5]: /u/dkokron/play/cuDNN/cuda
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.5
..........
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
..........
INFO: All external dependencies fetched successfully.
Configuration finished

bazel --output_base=/tmp/dkokron build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home6/dkokron/play/TensorFlow/tensorflow/tensorflow/core/BUILD:1121:1: Executing genrule //tensorflow/core:version_info_gen failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 260, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 212, in generate
    git_version = get_git_version(data["path"])
  File "tensorflow/tools/git/gen_git_source.py", line 150, in get_git_version
    val = bytes(subprocess.check_output([
AttributeError: 'module' object has no attribute 'check_output'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.236s, Critical Path: 1.79s

ll /nasa/cuda/7.5/lib64/libcu*
lrwxrwxrwx 1 hsp cstaff        16 Feb 11  2016 /nasa/cuda/7.5/lib64/libcublas.so -> libcublas.so.7.5
lrwxrwxrwx 1 hsp cstaff        19 Feb 11  2016 /nasa/cuda/7.5/lib64/libcublas.so.7.5 -> libcublas.so.7.5.18
-rwxr-xr-x 1 hsp cstaff  23938736 Feb 11  2016 /nasa/cuda/7.5/lib64/libcublas.so.7.5.18
-rw-r--r-- 1 hsp cstaff  28585480 Feb 11  2016 /nasa/cuda/7.5/lib64/libcublas_device.a
-rw-r--r-- 1 hsp cstaff  28220076 Feb 11  2016 /nasa/cuda/7.5/lib64/libcublas_static.a
-rw-r--r-- 1 hsp cstaff    322936 Feb 11  2016 /nasa/cuda/7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 hsp cstaff        16 Feb 11  2016 /nasa/cuda/7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 hsp cstaff        19 Feb 11  2016 /nasa/cuda/7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 hsp cstaff    383336 Feb 11  2016 /nasa/cuda/7.5/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 hsp cstaff    720192 Feb 11  2016 /nasa/cuda/7.5/lib64/libcudart_static.a
lrwxrwxrwx 1 hsp cstaff        15 Feb 11  2016 /nasa/cuda/7.5/lib64/libcufft.so -> libcufft.so.7.5
lrwxrwxrwx 1 hsp cstaff        18 Feb 11  2016 /nasa/cuda/7.5/lib64/libcufft.so.7.5 -> libcufft.so.7.5.18
-rwxr-xr-x 1 hsp cstaff 111231960 Feb 11  2016 /nasa/cuda/7.5/lib64/libcufft.so.7.5.18
-rw-r--r-- 1 hsp cstaff 115104400 Feb 11  2016 /nasa/cuda/7.5/lib64/libcufft_static.a
lrwxrwxrwx 1 hsp cstaff        16 Feb 11  2016 /nasa/cuda/7.5/lib64/libcufftw.so -> libcufftw.so.7.5
lrwxrwxrwx 1 hsp cstaff        19 Feb 11  2016 /nasa/cuda/7.5/lib64/libcufftw.so.7.5 -> libcufftw.so.7.5.18
-rwxr-xr-x 1 hsp cstaff    447664 Feb 11  2016 /nasa/cuda/7.5/lib64/libcufftw.so.7.5.18
-rw-r--r-- 1 hsp cstaff     42206 Feb 11  2016 /nasa/cuda/7.5/lib64/libcufftw_static.a
lrwxrwxrwx 1 hsp cstaff        17 Feb 11  2016 /nasa/cuda/7.5/lib64/libcuinj64.so -> libcuinj64.so.7.5
lrwxrwxrwx 1 hsp cstaff        20 Feb 11  2016 /nasa/cuda/7.5/lib64/libcuinj64.so.7.5 -> libcuinj64.so.7.5.18
-rwxr-xr-x 1 hsp cstaff   5751400 Feb 11  2016 /nasa/cuda/7.5/lib64/libcuinj64.so.7.5.18
-rw-r--r-- 1 hsp cstaff   1649726 Feb 11  2016 /nasa/cuda/7.5/lib64/libculibos.a
lrwxrwxrwx 1 hsp cstaff        16 Feb 11  2016 /nasa/cuda/7.5/lib64/libcurand.so -> libcurand.so.7.5
lrwxrwxrwx 1 hsp cstaff        19 Feb 11  2016 /nasa/cuda/7.5/lib64/libcurand.so.7.5 -> libcurand.so.7.5.18
-rwxr-xr-x 1 hsp cstaff  51765952 Feb 11  2016 /nasa/cuda/7.5/lib64/libcurand.so.7.5.18
-rw-r--r-- 1 hsp cstaff  51992564 Feb 11  2016 /nasa/cuda/7.5/lib64/libcurand_static.a
lrwxrwxrwx 1 hsp cstaff        18 Feb 11  2016 /nasa/cuda/7.5/lib64/libcusolver.so -> libcusolver.so.7.5
lrwxrwxrwx 1 hsp cstaff        21 Feb 11  2016 /nasa/cuda/7.5/lib64/libcusolver.so.7.5 -> libcusolver.so.7.5.18
-rwxr-xr-x 1 hsp cstaff  37034328 Feb 11  2016 /nasa/cuda/7.5/lib64/libcusolver.so.7.5.18
-rw-r--r-- 1 hsp cstaff  16613348 Feb 11  2016 /nasa/cuda/7.5/lib64/libcusolver_static.a
lrwxrwxrwx 1 hsp cstaff        18 Feb 11  2016 /nasa/cuda/7.5/lib64/libcusparse.so -> libcusparse.so.7.5
lrwxrwxrwx 1 hsp cstaff        21 Feb 11  2016 /nasa/cuda/7.5/lib64/libcusparse.so.7.5 -> libcusparse.so.7.5.18
-rwxr-xr-x 1 hsp cstaff  36816424 Feb 11  2016 /nasa/cuda/7.5/lib64/libcusparse.so.7.5.18
-rw-r--r-- 1 hsp cstaff  44445334 Feb 11  2016 /nasa/cuda/7.5/lib64/libcusparse_static.a

ll /u/dkokron/play/cuDNN/cuda/lib64/
total 117596
lrwxrwxrwx 1 dkokron scicon       13 Jun 10 01:20 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 dkokron scicon       17 Jun 10 01:20 libcudnn.so.5 -> libcudnn.so.5.1.3
-rwx------ 1 dkokron scicon 60696704 Jun 10 01:18 libcudnn.so.5.1.3
-rw------- 1 dkokron scicon 59715990 Jun 10 01:18 libcudnn_static.a

**Comment by poxvoculi** [comment]
SLES11sp3 is not a supported operating system.  Hopefully someone in the community can help you.  Might be good to ask on stackoverflow.

**Comment by gunan** [comment]
The root cause of the failure seems to be right here:
```
val = bytes(subprocess.check_output([
AttributeError: 'module' object has no attribute 'check_output'
```
which looks really weird. Does SLES have a different subprocess module?
could you try running python manually and checking:
```
import subprocess
'check_output' in dir(subprocess)
```

**Comment by gunan** [comment]
Also I found this online:
http://stackoverflow.com/questions/26894024/subprocess-check-output-module-object-has-out-attribute-check-output

Maybe the python libraries have an old version of subprocess?

**Comment by dkokron** [comment]
In reply to gunan.

Python 3.5.1 (default, Jul 28 2016, 13:15:08)
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> 'check_output' in dir(subprocess)
True
>>>

**Comment by gunan** [comment]
it looks like check_output is available, but during build, somehow it is not.
I would guess this would be something specific to your python setup.

The root cause of your issue is:
```
val = bytes(subprocess.check_output([
AttributeError: 'module' object has no attribute 'check_output'
```

I cannot really say why this is happening, since check_output is actually available in your python's subprocess module. At this point, I would say someone more familiar with your python setup or stack overflow (as suggested above) would be the best place to ask.

**Comment by gunan** [comment]
Not sure what is going on here, because it is really difficult to get a SLES/openSuse box ready with all TF  dependencies. I will probably not be able to reproduce the problem.

But I am sure that the culprit is your subprocess library. Therefore I will close the issue.

**Comment by gunan** [comment]
Another great suggestion I received from @aselle is using cmake.
That might be a much better solution, as bazel also does not have official support for SLES.

I heard that a lot of our users on CentOS have successfully built TF using cmake.

**Comment by dkokron** [comment]
Gunan,

We were eventually able to get a working TF environment using the Anaconda
framework.
Thank you for all the help and suggestions.

Dan

**Comment by mjlm** [comment]
I got the same error when trying to install TensorFlow with a Python installation that was not the default one on the system. Adding the desired version to the path solved the issue, e.g. with:
```
PATH=~/tensorflow-0.12.0-nogpu/bin:$PATH
export PATH
```

In my case, I was using python 3 and there was no file in my /bin folder that was just called `python`, so I added a symlink:
```
ln -s ~/tensorflow-0.12.0-nogpu/bin/python3.5 ~/tensorflow-0.12.0-nogpu/bin/python
```

**Comment by ChristophorusReyhan** [comment]
I got it working by adding this function to configure.py
```
def check_output(command_list):
    proc = subprocess.Popen(command_list, stdout=subprocess.PIPE)
    proc.wait()
    return proc.stdout.read()
```
below run_shell function and change all 
`subprocess.check_output(cmd)`
to
`check_output(cmd)`
the problem is the configure script use default python. 
```
if [ -z "$PYTHON_BIN_PATH" ]; then
  PYTHON_BIN_PATH=$(which python || which python3 || true)
fi
```
which is python 2.6 in my machine. `check_output` was introduced in python 2.7.
I know it's 2 y.o. issue but there's no explanation about the compatibility problem.

**Comment by ChristophorusReyhan** [comment]
Another workaround is that specifying the python to use by changing 
`PYTHON_BIN_PATH=$(which python || which python3 || true)`
to
`PYTHON_BIN_PATH=$(which python<python version above 2.7> || which python3 || true)`
in `configure` shellscript
