### ISSUE TITLE
Tensorflow not recognizing GPU in Spyder

### ISSUE THREAD

**Issue by WenTheProgrammer** [tensorflow/tensorflow#60269]
I have followed this YouTube tutorial since I want to use GPU for tensorflow model training: https://www.youtube.com/watch?v=yLVFwAaFACk&ab_channel=DigitalSreeni. However, I was still not able to detect GPU of my computer in Spyder:

```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17504734730771000338
xla_global_id: -1
]
```
My system is Windows 11. My tensorflow version is 2.12.0. My GPUs are NVIDIA GeForce RTX 2060 and Intel® UHD Graphics 630. My NVIDIA CUDA version is 12.1. I used cudnn-windows-x86_64-8.8.1.3_cuda12-archive. My Anaconda is fully updated. My Spyder version is 5.4.2.
Any help will be much appreciated!

**Comment by tiruk007** [comment]
@WenTheProgrammer 
Sorry for the late reply, Beginning with Tensorflow 2.11, support for GPU on native windows has changed. You will need to install TensorFlow in WSL2 or install tensorflow-cpu within windows machines or try the TensorFlow-DirectML-Plugin.
https://www.tensorflow.org/install/pip#windows-native
https://www.tensorflow.org/install/pip#windows-wsl2

Going forward, Tensorflow support will be developed and maintained by Tensorflow Official build collaborators (Intel, AWS, ARM, linaro etc.). For more details please take a look at this [link].(https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html)

Thank you !

**Comment by WenTheProgrammer** [comment]
Simply following the instructions in this link worked for me!
https://www.tensorflow.org/install/pip#windows-native
