### ISSUE TITLE
tf.math.abs has different results when running under CPU or GPU

### ISSUE THREAD

**Issue by PengHaoYu** [tensorflow/tensorflow#60654]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Mobile device

/

### Python version

3.7.5

### Bazel version

/

### GCC/Compiler version

/

### CUDA/cuDNN version

11.2

### GPU model and memory

GeForce RTX 2080Ti

### Current Behaviour?

`tf.math.abs` has different results when running under CPU or GPU.

The reproduction colab link is here: [colab](https://colab.research.google.com/drive/1pjhCrZTnmUktYZ75BKb2XqCMrdVnRqOP#scrollTo=D2E0G6uJiDMO).

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = tf.constant([3.4e+307 + 0.j], dtype=tf.complex128)

with tf.device("/cpu:0"):
    a = tf.math.abs(x)
    print(a)

with tf.device("/gpu:0"):
    a = tf.math.abs(x)
    print(a)
```

### Relevant log output

```shell
tf.Tensor([3.4e+307], shape=(1,), dtype=float64)
tf.Tensor([inf], shape=(1,), dtype=float64)
```
</details>

**Comment by SuryanarayanaY** [comment]
Hi @PengHaoYu ,

I have replicated the issue with TF2.12 and also tf-nightly versions.Please refer [gist](https://colab.research.google.com/gist/SuryanarayanaY/6b50a7a535f20faed65d8992b726a226/60654_nightly.ipynb#scrollTo=iSrj5x_Z2oUX).

Needs to dig more into the issue and let you know. Thanks!

**Comment by malla456** [comment]
HI@PengHaoYU,

I executed the code using TensorFlow version 2.17, and it worked successfully.It works same under CPU and GPU,
Kindly refer to this [gist](https://colab.sandbox.google.com/gist/malla456/8c2ca8defe2c42b19e01466c0af87e1b/60654.ipynb) for the details.

Thanks
