### ISSUE TITLE
Could not load dynamic library 'libcublasLt.so.12'; dlerror: libcublasLt.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jagiella** [tensorflow/tensorflow#61326]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.13.0-rc2-7-g1cb1a030a62 2.13.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 23.10

### Python version

3.11

### CUDA/cuDNN version

11.8.0-1/8.9.3.28-1+cuda12.1

### GPU model and memory

NVIDIA GeForce GTX 960M, 4096MiB

### Current behavior?

running the mobilenet from keras included by tensorflow leads to the following error:
```
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory                                                         
Abgebrochen (Speicherabzug geschrieben)
```

### Standalone code to reproduce the issue

```shell
python -c 'from tensorflow.keras.applications.mobilenet import MobileNet; import numpy as np; m = MobileNet(); m.predict(np.zeros((32,224,224,3)))'
```

### Relevant log output

```shell
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory                                                         
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by jagiella** [comment]
Okay I fixed it! I needed to install another flavor of the libcudnn matching my cuda version:

```
sudo apt-get install libcudnn8=8.9.3.28-1+cuda11.8
```
