### ISSUE TITLE
Abort when running

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#61543]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.11.0

### Custom code

Yes

### OS platform and distribution

22.04

### Python version

3.9

### CUDA/cuDNN version

nvidia-cudnn-cu11==8.6.0.163, cudatoolkit=11.8.0

### Current behavior?

Due to a Negative Large Integer. The behavior is bizarre. It would be best if you ran multiple times to see the Abort.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_math_ops
try:
  try:
    with tf.device('/CPU'):
      splits_tensor = tf.constant(-1000000, shape=[129, 1, 1], dtype=tf.float16,)
      splits = tf.identity(splits_tensor)
      values_tensor = tf.saturate_cast(tf.constant(-153, shape=[3456], dtype=tf.int64,),dtype=tf.uint64)
      values = tf.identity(values_tensor)
      weights_tensor = tf.saturate_cast(tf.constant(-1012756988, shape=[128, 27], dtype=tf.int64,),dtype=tf.int16)
      weights = tf.identity(weights_tensor)
      size = -3046875451
      out = gen_math_ops.ragged_bincount(splits=splits,values=values,weights=weights,size=size,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      splits = tf.identity(splits_tensor)
      splits = tf.cast(splits, tf.float16)
      values = tf.identity(values_tensor)
      values = tf.cast(values, tf.uint64)
      weights = tf.identity(weights_tensor)
      weights = tf.cast(weights, tf.int16)
      gen_math_ops.ragged_bincount(splits=splits,values=values,weights=weights,size=size,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-08-13 01:58:36.322308: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-08-13 01:58:37.120869: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.139665: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.139841: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.140154: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-13 01:58:37.140677: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.140794: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.140896: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.187990: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.188156: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.188267: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:58:37.188356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 152 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
Error:can't convert negative int to unsigned
2023-08-13 01:58:37.207611: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:735] failed to allocate 152.81M (160235520 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-13 01:58:37.207886: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:735] failed to allocate 137.53M (144211968 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-13 01:58:37.208138: I tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:735] failed to allocate 123.78M (129790976 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-13 01:58:37.213816: F ./tensorflow/python/eager/pywrap_tensor_conversion.h:58] Check failed: !PyErr_Occurred() 
Aborted
```
```

**Comment by SuryanarayanaY** [comment]
Hi @dmc1778 ,

The issue seems resolved already from TF2.12 onwards. I have tested the code and its raising intended error without abort in Tf2.12 and tf-nightly as well.Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/8e096b58e03a15983accd675cbe9a9a2/61543_2-12_nightly_2-11.ipynb).

I even tried with TF2.11v even there it's raising intended error only even multiple runs in attached colab gist. Could you please verify it again. Thanks!

**Comment by mihaimaruseac** [comment]
Closing as resolved at head
