### ISSUE TITLE
GPU not detected even after installing CUDA, cuDNN correct versions

### ISSUE THREAD

**Issue by majorisgit** [tensorflow/tensorflow#62080]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.14.0

### Custom code

No

### OS platform and distribution

Windows 10 22H2 19045.3448

### Python version

3.10.10

### CUDA/cuDNN version

CUDA v11.2, cudnn-11.2-windows-x64-v8.1.0.77

### GPU model and memory

GeForce GTX 960M, 4Gb

### Current behavior?

Unable to detect the GPU. TF says: 

`print(tf.test.is_built_with_cuda())
False`

### Standalone code to reproduce the issue

```shell
It is an installation issue. 

C:\Users\user>python
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensorflow as tf
>>> print(tf.test.is_built_with_cuda())
False
>>> print(tf.config.list_physical_devices('GPU'))
[]
>>>
>>> print(tf.config.list_physical_devices())
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
>>>
```

### Relevant log output

```shell
C:\Windows\system32>
python -V 
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
---------------------------------------------------------------------------------
pip list
Package                      Version
---------------------------- ------------
absl-py                      2.0.0
anyio                        4.0.0
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.4.0
astunparse                   1.6.3
async-lru                    2.0.4
attrs                        23.1.0
Babel                        2.13.0
backcall                     0.2.0
beautifulsoup4               4.12.2
bleach                       6.1.0
cachetools                   5.3.1
certifi                      2023.7.22
cffi                         1.16.0
charset-normalizer           3.3.0
colorama                     0.4.6
comm                         0.1.4
contourpy                    1.1.1
cycler                       0.12.1
debugpy                      1.8.0
decorator                    5.1.1
defusedxml                   0.7.1
exceptiongroup               1.1.3
executing                    2.0.0
fastjsonschema               2.18.1
flatbuffers                  23.5.26
fonttools                    4.43.1
fqdn                         1.5.1
gast                         0.5.4
google-auth                  2.23.3
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.59.0
h5py                         3.10.0
idna                         3.4
ipykernel                    6.25.2
ipython                      8.16.1
ipython-genutils             0.2.0
ipywidgets                   8.1.1
isoduration                  20.11.0
jedi                         0.19.1
Jinja2                       3.1.2
joblib                       1.3.2
json5                        0.9.14
jsonpointer                  2.4
jsonschema                   4.19.1
jsonschema-specifications    2023.7.1
jupyter                      1.0.0
jupyter_client               8.3.1
jupyter-console              6.6.3
jupyter_core                 5.4.0
jupyter-events               0.7.0
jupyter-lsp                  2.2.0
jupyter_server               2.7.3
jupyter_server_terminals     0.4.4
jupyterlab                   4.0.6
jupyterlab-pygments          0.2.2
jupyterlab_server            2.25.0
jupyterlab-widgets           3.0.9
keras                        2.14.0
kiwisolver                   1.4.5
libclang                     16.0.6
Markdown                     3.5
MarkupSafe                   2.1.3
matplotlib                   3.8.0
matplotlib-inline            0.1.6
mistune                      3.0.2
ml-dtypes                    0.2.0
mpmath                       1.3.0
nbclient                     0.8.0
nbconvert                    7.9.2
nbformat                     5.9.2
nest-asyncio                 1.5.8
notebook                     7.0.4
notebook_shim                0.2.3
numpy                        1.26.0
oauthlib                     3.2.2
opt-einsum                   3.3.0
overrides                    7.4.0
packaging                    23.2
pandas                       2.1.1
pandocfilters                1.5.0
parso                        0.8.3
pickleshare                  0.7.5
Pillow                       10.0.1
pip                          23.2.1
platformdirs                 3.11.0
plotly                       5.17.0
prometheus-client            0.17.1
prompt-toolkit               3.0.39
protobuf                     4.24.4
psutil                       5.9.5
pure-eval                    0.2.2
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
Pygments                     2.16.1
pyparsing                    3.1.1
python-dateutil              2.8.2
python-json-logger           2.0.7
pytz                         2023.3.post1
pywin32                      306
pywinpty                     2.0.12
PyYAML                       6.0.1
pyzmq                        25.1.1
qtconsole                    5.4.4
QtPy                         2.4.0
referencing                  0.30.2
requests                     2.31.0
requests-oauthlib            1.3.1
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rpds-py                      0.10.4
rsa                          4.9
scikit-learn                 1.3.1
scipy                        1.11.3
Send2Trash                   1.8.2
setuptools                   65.5.0
six                          1.16.0
sniffio                      1.3.0
soupsieve                    2.5
stack-data                   0.6.3
sympy                        1.12
tenacity                     8.2.3
tensorboard                  2.14.1
tensorboard-data-server      0.7.1
tensorflow                   2.14.0
tensorflow-estimator         2.14.0
tensorflow-intel             2.14.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.3.0
terminado                    0.17.1
threadpoolctl                3.2.0
tinycss2                     1.2.1
tomli                        2.0.1
tornado                      6.3.3
tqdm                         4.66.1
traitlets                    5.11.2
types-python-dateutil        2.8.19.14
typing_extensions            4.8.0
tzdata                       2023.3
uri-template                 1.3.0
urllib3                      2.0.6
wcwidth                      0.2.8
webcolors                    1.13
webencodings                 0.5.1
websocket-client             1.6.4
Werkzeug                     3.0.0
wheel                        0.41.2
widgetNVIDIA snbextension           4.0.9
wrapt                        1.14.1
---------------------------------------------------------------------------------
Hardware: GeForce GTX 960M
https://www.nvidia.com/en-us/geforce/gaming-laptops/geforce-gtx-960m/specifications/
https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

CUDA Cores
1096 + Boost Base Clock (MHz)
GTX 960M Memory Specs:
2500 MHz Memory Clock
GDDR5 Memory Interface
128-bit Memory Interface Width
80Memory Bandwidth (GB/sec)
GTX 960M Technology Support: Yes 
NVIDIA® Optimus™ Support 1 Yes 
NVIDIA Battery Boost™ Support 2
2.0NVIDIA GPU Boost™ Yes
NVIDIA GameStream™-Ready Yes
GeForce ShadowPlay™ Yes
NVIDIA GameWorks™
12 API Microsoft DirectX
4.5 OpenGL 
CUDA Yes
PCI Express 3.0 Bus Support
Windows 8 and 8.1
Windows 7OS Certification

Processor	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.60 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor

---------------------------------------------------------------------------------

>>> import tensorflow as tf
>>> print(tf.__version__)
2.14.0

---------------------------------------------------------------------------------
Used table from here: https://www.tensorflow.org/install/source_windows

tensorflow 2.14.0,	Python 3.7-3.10,	cuDNN 8.1	CUDA 11.2

CUDA v11.2, cudnn-11.2-windows-x64-v8.1.0.77, Python 3.10.10
---------------------------------------------------------------------------------

>>> print(tf.test.is_built_with_cuda())
False
>>> print(tf.config.list_physical_devices('GPU'))
[]
>>>
>>> print(tf.config.list_physical_devices())
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
>>>

---------------------------------------------------------------------------------
OS

Edition	Windows 10 Home
Version	22H2
Installed on	‎2/‎28/‎2023
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0
```

**Comment by SuryanarayanaY** [comment]
@majorisgit ,

For GPU package with all required CUDA libraries you need to use `pip install tensorflow[and-cuda]` command.

Whether you resolved this ? Are you still having issues please feel free to discuss.

**Comment by RobinUuo** [comment]
I'm also having this problem, installed tensorflow 2.13 after using `pip install tensorflow[and-cuda] `command, but still can't use GPU calculations

**Comment by majorisgit** [comment]
> I'm also having this problem, installed tensorflow 2.13 after using `pip install tensorflow[and-cuda] `command, but still can't use GPU calculations

Windows native support for GPU is not supported any more in TensorFlow. 
I had to install Windows Subsystem for Linux (WSL 2). I Ran Linux inside Windows. Then followed the instructions from this installation [doc](https://gist.github.com/MihailCosmin/affa6b1b71b43787e9228c25fe15aeba)
It worked, the GPU is detected and I can use it for calculations. The problem is solved.
