### ISSUE TITLE
TensorFlow doesn't detect cuda drivers

### ISSUE THREAD

**Issue by zeionara** [tensorflow/tensorflow#62328]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.1

### Custom code

No

### OS platform and distribution

Li

### Mobile device

Gentoo Linux 6.1.57-gentoo-x86_64

### Python version

3.11.5

### CUDA/cuDNN version

11.8/8.7.0.84

### GPU model and memory

NVIDIA GeForce GTX 1650 Mobile / Max-Q

### Current behavior?

Current behaviour: list of cuda-capable devices is empty

```sh
> python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2023-11-06 01:01:39.145881: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-06 01:01:39.200934: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-06 01:01:39.201518: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-06 01:01:40.245608: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-11-06 01:01:41.021740: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-06 01:01:41.022476: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[]
```

Expected behaviour: list of coda-capable devices contains one item.

I would be happy to reproduce the bug in `tf-nightly`, but I can't even install it due to broken dependencies with tensorrt:

```sh
> python3 -m pip install 'tf-nightly[and-cuda]'
Collecting tf-nightly[and-cuda]
  Using cached tf_nightly-2.16.0.dev20231103-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tf-nightly[and-cuda])
  Using cached absl_py-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting astunparse>=1.6.0 (from tf-nightly[and-cuda])
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=23.5.26 (from tf-nightly[and-cuda])
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tf-nightly[and-cuda])
  Using cached gast-0.5.4-py3-none-any.whl (19 kB)
Collecting google-pasta>=0.1.1 (from tf-nightly[and-cuda])
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting h5py>=3.10.0 (from tf-nightly[and-cuda])
  Using cached h5py-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting libclang>=13.0.0 (from tf-nightly[and-cuda])
  Using cached libclang-16.0.6-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting ml-dtypes~=0.3.1 (from tf-nightly[and-cuda])
  Using cached ml_dtypes-0.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting opt-einsum>=2.3.2 (from tf-nightly[and-cuda])
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting packaging (from tf-nightly[and-cuda])
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tf-nightly[and-cuda])
  Using cached protobuf-4.25.0-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Requirement already satisfied: setuptools in ./miniconda3/envs/tf-test/lib/python3.11/site-packages (from tf-nightly[and-cuda]) (68.0.0)
Collecting six>=1.12.0 (from tf-nightly[and-cuda])
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting termcolor>=1.1.0 (from tf-nightly[and-cuda])
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting typing-extensions>=3.6.6 (from tf-nightly[and-cuda])
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting wrapt<1.15,>=1.11.0 (from tf-nightly[and-cuda])
  Using cached wrapt-1.14.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting grpcio<2.0,>=1.24.3 (from tf-nightly[and-cuda])
  Using cached grpcio-1.59.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting tb-nightly~=2.16.0.a (from tf-nightly[and-cuda])
  Using cached tb_nightly-2.16.0a20231105-py3-none-any.whl.metadata (1.7 kB)
Collecting tf-estimator-nightly~=2.14.0.dev (from tf-nightly[and-cuda])
  Using cached tf_estimator_nightly-2.14.0.dev2023080308-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting keras-nightly~=3.0.0.dev (from tf-nightly[and-cuda])
  Using cached keras_nightly-3.0.0.dev2023110403-py3-none-any.whl.metadata (5.3 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tf-nightly[and-cuda])
  Using cached tensorflow_io_gcs_filesystem-0.34.0-cp311-cp311-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
Collecting numpy<2.0.0,>=1.23.5 (from tf-nightly[and-cuda])
  Using cached numpy-1.26.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting nvidia-cublas-cu12==12.2.5.6 (from tf-nightly[and-cuda])
  Using cached nvidia_cublas_cu12-12.2.5.6-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.2.142 (from tf-nightly[and-cuda])
  Using cached nvidia_cuda_cupti_cu12-12.2.142-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvcc-cu12==12.2.140 (from tf-nightly[and-cuda])
  Using cached nvidia_cuda_nvcc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.2.140 (from tf-nightly[and-cuda])
  Using cached nvidia_cuda_nvrtc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.2.140 (from tf-nightly[and-cuda])
  Using cached nvidia_cuda_runtime_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cudnn-cu12==8.9.4.25 (from tf-nightly[and-cuda])
  Using cached nvidia_cudnn_cu12-8.9.4.25-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cufft-cu12==11.0.8.103 (from tf-nightly[and-cuda])
  Using cached nvidia_cufft_cu12-11.0.8.103-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.3.141 (from tf-nightly[and-cuda])
  Using cached nvidia_curand_cu12-10.3.3.141-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.5.2.141 (from tf-nightly[and-cuda])
  Using cached nvidia_cusolver_cu12-11.5.2.141-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.2.141 (from tf-nightly[and-cuda])
  Using cached nvidia_cusparse_cu12-12.1.2.141-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.18.3 (from tf-nightly[and-cuda])
  Using cached nvidia_nccl_cu12-2.18.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.2.140 (from tf-nightly[and-cuda])
  Using cached nvidia_nvjitlink_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting tensorrt==8.6.1.post1 (from tf-nightly[and-cuda])
  Using cached tensorrt-8.6.1.post1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorrt-bindings==8.6.1 (from tf-nightly[and-cuda])
  Using cached tensorrt_bindings-8.6.1-cp311-none-manylinux_2_17_x86_64.whl (980 kB)
INFO: pip is looking at multiple versions of tf-nightly[and-cuda] to determine which version is compatible with other requirements. This could take a while.
Collecting tf-nightly[and-cuda]
  Using cached tf_nightly-2.16.0.dev20231102-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
  Using cached tf_nightly-2.16.0.dev20231101-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
  Using cached tf_nightly-2.16.0.dev20231031-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
  Using cached tf_nightly-2.16.0.dev20231026-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Collecting tb-nightly~=2.15.0.a (from tf-nightly[and-cuda])
  Using cached tb_nightly-2.15.0a20231023-py3-none-any.whl.metadata (1.7 kB)
Collecting tf-nightly[and-cuda]
  Using cached tf_nightly-2.16.0.dev20231025-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Collecting nvidia-nccl-cu12==2.16.5 (from tf-nightly[and-cuda])
  Using cached nvidia_nccl_cu12-2.16.5-py3-none-manylinux1_x86_64.whl (188.7 MB)
Collecting tf-nightly[and-cuda]
  Using cached tf_nightly-2.16.0.dev20231024-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
  Using cached tf_nightly-2.16.0.dev20231022-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
INFO: pip is still looking at multiple versions of tf-nightly[and-cuda] to determine which version is compatible with other requirements. This could take a while.
  Using cached tf_nightly-2.16.0.dev20231021-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
  Using cached tf_nightly-2.16.0.dev20231020-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
  Using cached tf_nightly-2.16.0.dev20231013-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
Collecting ml-dtypes~=0.2.0 (from tf-nightly[and-cuda])
  Using cached ml_dtypes-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting keras-nightly~=2.15.0.dev (from tf-nightly[and-cuda])
  Using cached keras_nightly-2.15.0.dev2023092207-py3-none-any.whl.metadata (2.5 kB)
Collecting tf-nightly[and-cuda]
  Using cached tf_nightly-2.15.0.dev20231012-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20231011-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached tf_nightly-2.15.0.dev20231010-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20231009-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20231006-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20231005-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20231004-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20231003-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20231002-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20231001-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230930-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230929-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230928-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230927-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230926-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230925-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230924-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230923-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230922-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230921-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230920-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230919-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
  Using cached tf_nightly-2.15.0.dev20230918-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting nvidia-cuda-runtime-cu11==11.8.89 (from tf-nightly[and-cuda])
  Using cached nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)
Collecting nvidia-cublas-cu11==11.11.3.6 (from tf-nightly[and-cuda])
  Using cached nvidia_cublas_cu11-11.11.3.6-py3-none-manylinux1_x86_64.whl (417.9 MB)
Collecting nvidia-cufft-cu11==10.9.0.58 (from tf-nightly[and-cuda])
  Using cached nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
Collecting nvidia-cudnn-cu11==8.7.0.84 (from tf-nightly[and-cuda])
  Using cached nvidia_cudnn_cu11-8.7.0.84-py3-none-manylinux1_x86_64.whl (728.5 MB)
Collecting nvidia-curand-cu11==10.3.0.86 (from tf-nightly[and-cuda])
  Using cached nvidia_curand_cu11-10.3.0.86-py3-none-manylinux1_x86_64.whl (58.1 MB)
Collecting nvidia-cusolver-cu11==11.4.1.48 (from tf-nightly[and-cuda])
  Using cached nvidia_cusolver_cu11-11.4.1.48-py3-none-manylinux1_x86_64.whl (128.2 MB)
Collecting nvidia-cusparse-cu11==11.7.5.86 (from tf-nightly[and-cuda])
  Using cached nvidia_cusparse_cu11-11.7.5.86-py3-none-manylinux1_x86_64.whl (204.1 MB)
Collecting nvidia-nccl-cu11==2.16.5 (from tf-nightly[and-cuda])
  Using cached nvidia_nccl_cu11-2.16.5-py3-none-manylinux1_x86_64.whl (210.3 MB)
Collecting nvidia-cuda-cupti-cu11==11.8.87 (from tf-nightly[and-cuda])
  Using cached nvidia_cuda_cupti_cu11-11.8.87-py3-none-manylinux1_x86_64.whl (13.1 MB)
Collecting nvidia-cuda-nvcc-cu11==11.8.89 (from tf-nightly[and-cuda])
  Using cached nvidia_cuda_nvcc_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (19.5 MB)
Collecting tf-nightly[and-cuda]
  Using cached tf_nightly-2.15.0.dev20230917-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tf_nightly-2.15.0.dev20230916-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tf_nightly-2.15.0.dev20230915-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tf_nightly-2.15.0.dev20230914-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tf_nightly-2.15.0.dev20230913-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tf_nightly-2.15.0.dev20230911-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tf_nightly-2.15.0.dev20230910-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tf_nightly-2.15.0.dev20230909-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tf_nightly-2.15.0.dev20230908-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230907-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230906-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230904-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230903-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230902-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230901-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230831-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230830-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230829-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230828-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230827-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230826-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230825-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230824-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230817-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230816-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230815-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230814-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230813-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230812-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230811-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230810-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting tb-nightly~=2.14.0.a (from tf-nightly[and-cuda])
  Using cached tb_nightly-2.14.0a20230808-py3-none-any.whl.metadata (1.8 kB)
Collecting keras-nightly~=2.14.0.dev (from tf-nightly[and-cuda])
  Using cached keras_nightly-2.14.0.dev2023080207-py3-none-any.whl.metadata (2.5 kB)
Collecting tf-nightly[and-cuda]
  Using cached tf_nightly-2.15.0.dev20230809-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230808-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
  Using cached tf_nightly-2.15.0.dev20230807-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
ERROR: Cannot install tf-nightly[and-cuda]==2.15.0.dev20230807, tf-nightly[and-cuda]==2.15.0.dev20230808, tf-nightly[and-cuda]==2.15.0.dev20230809, tf-nightly[and-cuda]==2.15.0.dev20230810, tf-nightly[and-cuda]==2.15.0.dev20230811, tf-nightly[and-cuda]==2.15.0.dev20230812, tf-nightly[and-cuda]==2.15.0.dev20230813, tf-nightly[and-cuda]==2.15.0.dev20230814, tf-nightly[and-cuda]==2.15.0.dev20230815, tf-nightly[and-cuda]==2.15.0.dev20230816, tf-nightly[and-cuda]==2.15.0.dev20230817, tf-nightly[and-cuda]==2.15.0.dev20230824, tf-nightly[and-cuda]==2.15.0.dev20230825, tf-nightly[and-cuda]==2.15.0.dev20230826, tf-nightly[and-cuda]==2.15.0.dev20230827, tf-nightly[and-cuda]==2.15.0.dev20230828, tf-nightly[and-cuda]==2.15.0.dev20230829, tf-nightly[and-cuda]==2.15.0.dev20230830, tf-nightly[and-cuda]==2.15.0.dev20230831, tf-nightly[and-cuda]==2.15.0.dev20230901, tf-nightly[and-cuda]==2.15.0.dev20230902, tf-nightly[and-cuda]==2.15.0.dev20230903, tf-nightly[and-cuda]==2.15.0.dev20230904, tf-nightly[and-cuda]==2.15.0.dev20230906, tf-nightly[and-cuda]==2.15.0.dev20230907, tf-nightly[and-cuda]==2.15.0.dev20230908, tf-nightly[and-cuda]==2.15.0.dev20230909, tf-nightly[and-cuda]==2.15.0.dev20230910, tf-nightly[and-cuda]==2.15.0.dev20230911, tf-nightly[and-cuda]==2.15.0.dev20230913, tf-nightly[and-cuda]==2.15.0.dev20230914, tf-nightly[and-cuda]==2.15.0.dev20230915, tf-nightly[and-cuda]==2.15.0.dev20230916, tf-nightly[and-cuda]==2.15.0.dev20230917, tf-nightly[and-cuda]==2.15.0.dev20230918, tf-nightly[and-cuda]==2.15.0.dev20230919, tf-nightly[and-cuda]==2.15.0.dev20230920, tf-nightly[and-cuda]==2.15.0.dev20230921, tf-nightly[and-cuda]==2.15.0.dev20230922, tf-nightly[and-cuda]==2.15.0.dev20230923, tf-nightly[and-cuda]==2.15.0.dev20230924, tf-nightly[and-cuda]==2.15.0.dev20230925, tf-nightly[and-cuda]==2.15.0.dev20230926, tf-nightly[and-cuda]==2.15.0.dev20230927, tf-nightly[and-cuda]==2.15.0.dev20230928, tf-nightly[and-cuda]==2.15.0.dev20230929, tf-nightly[and-cuda]==2.15.0.dev20230930, tf-nightly[and-cuda]==2.15.0.dev20231001, tf-nightly[and-cuda]==2.15.0.dev20231002, tf-nightly[and-cuda]==2.15.0.dev20231003, tf-nightly[and-cuda]==2.15.0.dev20231004, tf-nightly[and-cuda]==2.15.0.dev20231005, tf-nightly[and-cuda]==2.15.0.dev20231006, tf-nightly[and-cuda]==2.15.0.dev20231009, tf-nightly[and-cuda]==2.15.0.dev20231010, tf-nightly[and-cuda]==2.15.0.dev20231011, tf-nightly[and-cuda]==2.15.0.dev20231012, tf-nightly[and-cuda]==2.16.0.dev20231013, tf-nightly[and-cuda]==2.16.0.dev20231020, tf-nightly[and-cuda]==2.16.0.dev20231021, tf-nightly[and-cuda]==2.16.0.dev20231022, tf-nightly[and-cuda]==2.16.0.dev20231024, tf-nightly[and-cuda]==2.16.0.dev20231025, tf-nightly[and-cuda]==2.16.0.dev20231026, tf-nightly[and-cuda]==2.16.0.dev20231031, tf-nightly[and-cuda]==2.16.0.dev20231101, tf-nightly[and-cuda]==2.16.0.dev20231102 and tf-nightly[and-cuda]==2.16.0.dev20231103 because these package versions have conflicting dependencies.

The conflict is caused by:
    tf-nightly[and-cuda] 2.16.0.dev20231103 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231102 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231101 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231031 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231026 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231025 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231024 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231022 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231021 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231020 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.16.0.dev20231013 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231012 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231011 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231010 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231009 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231006 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231005 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231004 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231003 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231002 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20231001 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230930 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230929 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230928 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230927 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230926 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230925 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230924 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230923 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230922 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230921 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230920 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230919 depends on tensorrt-libs==8.6.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230918 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230917 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230916 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230915 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230914 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230913 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230911 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230910 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230909 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230908 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230907 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230906 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230904 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230903 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230902 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230901 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230831 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230830 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230829 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230828 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230827 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230826 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230825 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230824 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230817 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230816 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230815 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230814 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230813 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230812 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230811 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230810 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230809 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230808 depends on tensorrt==8.5.3.1; extra == "and-cuda"
    tf-nightly[and-cuda] 2.15.0.dev20230807 depends on tensorrt==8.5.3.1; extra == "and-cuda"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Standalone code to reproduce the issue

I've just copied commands from the official website:

```shell
python3 -m pip install 'tensorflow[and-cuda]'
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

### Relevant log output
Driver:

```sh
> nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650        Off | 00000000:01:00.0  On |                  N/A |
| N/A   43C    P8               3W /  50W |    119MiB /  4096MiB |      7%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     15023    C+G   ...95206080,4704969098354582108,262144       36MiB |
|    0   N/A  N/A     26218      G   /usr/bin/X                                   81MiB |
+---------------------------------------------------------------------------------------+
```

Log of the `tensorflow[and-cuda]` installation:

```shell
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting absl-py>=1.0.0 (from tensorflow[and-cuda])
  Using cached absl_py-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow[and-cuda])
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=23.5.26 (from tensorflow[and-cuda])
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow[and-cuda])
  Using cached gast-0.5.4-py3-none-any.whl (19 kB)
Collecting google-pasta>=0.1.1 (from tensorflow[and-cuda])
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting h5py>=2.9.0 (from tensorflow[and-cuda])
  Using cached h5py-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting libclang>=13.0.0 (from tensorflow[and-cuda])
  Using cached libclang-16.0.6-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting ml-dtypes==0.2.0 (from tensorflow[and-cuda])
  Using cached ml_dtypes-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting numpy>=1.23.5 (from tensorflow[and-cuda])
  Using cached numpy-1.26.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow[and-cuda])
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting packaging (from tensorflow[and-cuda])
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow[and-cuda])
  Using cached protobuf-4.25.0-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Requirement already satisfied: setuptools in ./miniconda3/envs/tf-test/lib/python3.11/site-packages (from tensorflow[and-cuda]) (68.0.0)
Collecting six>=1.12.0 (from tensorflow[and-cuda])
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting termcolor>=1.1.0 (from tensorflow[and-cuda])
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting typing-extensions>=3.6.6 (from tensorflow[and-cuda])
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting wrapt<1.15,>=1.11.0 (from tensorflow[and-cuda])
  Using cached wrapt-1.14.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow[and-cuda])
  Using cached tensorflow_io_gcs_filesystem-0.34.0-cp311-cp311-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow[and-cuda])
  Using cached grpcio-1.59.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting tensorboard<2.15,>=2.14 (from tensorflow[and-cuda])
  Downloading tensorboard-2.14.1-py3-none-any.whl.metadata (1.7 kB)
Collecting tensorflow-estimator<2.15,>=2.14.0 (from tensorflow[and-cuda])
  Downloading tensorflow_estimator-2.14.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting keras<2.15,>=2.14.0 (from tensorflow[and-cuda])
  Downloading keras-2.14.0-py3-none-any.whl.metadata (2.4 kB)
Collecting nvidia-cuda-runtime-cu11==11.8.89 (from tensorflow[and-cuda])
  Using cached nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)
Collecting nvidia-cublas-cu11==11.11.3.6 (from tensorflow[and-cuda])
  Using cached nvidia_cublas_cu11-11.11.3.6-py3-none-manylinux1_x86_64.whl (417.9 MB)
Collecting nvidia-cufft-cu11==10.9.0.58 (from tensorflow[and-cuda])
  Using cached nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
Collecting nvidia-cudnn-cu11==8.7.0.84 (from tensorflow[and-cuda])
  Using cached nvidia_cudnn_cu11-8.7.0.84-py3-none-manylinux1_x86_64.whl (728.5 MB)
Collecting nvidia-curand-cu11==10.3.0.86 (from tensorflow[and-cuda])
  Using cached nvidia_curand_cu11-10.3.0.86-py3-none-manylinux1_x86_64.whl (58.1 MB)
Collecting nvidia-cusolver-cu11==11.4.1.48 (from tensorflow[and-cuda])
  Using cached nvidia_cusolver_cu11-11.4.1.48-py3-none-manylinux1_x86_64.whl (128.2 MB)
Collecting nvidia-cusparse-cu11==11.7.5.86 (from tensorflow[and-cuda])
  Using cached nvidia_cusparse_cu11-11.7.5.86-py3-none-manylinux1_x86_64.whl (204.1 MB)
Collecting nvidia-nccl-cu11==2.16.5 (from tensorflow[and-cuda])
  Using cached nvidia_nccl_cu11-2.16.5-py3-none-manylinux1_x86_64.whl (210.3 MB)
Collecting nvidia-cuda-cupti-cu11==11.8.87 (from tensorflow[and-cuda])
  Using cached nvidia_cuda_cupti_cu11-11.8.87-py3-none-manylinux1_x86_64.whl (13.1 MB)
Collecting nvidia-cuda-nvcc-cu11==11.8.89 (from tensorflow[and-cuda])
  Using cached nvidia_cuda_nvcc_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (19.5 MB)
INFO: pip is looking at multiple versions of tensorflow[and-cuda] to determine which version is compatible with other requirements. This could take a while.
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
WARNING: tensorflow 2.13.1 does not provide the extra 'and-cuda'
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow[and-cuda])
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting keras<2.14,>=2.13.1 (from tensorflow[and-cuda])
  Downloading keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
Collecting numpy<=1.24.3,>=1.22 (from tensorflow[and-cuda])
  Downloading numpy-1.24.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 10.9 MB/s eta 0:00:00
Collecting tensorboard<2.14,>=2.13 (from tensorflow[and-cuda])
  Downloading tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 11.1 MB/s eta 0:00:00
Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow[and-cuda])
  Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow[and-cuda])
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting wrapt>=1.11.0 (from tensorflow[and-cuda])
  Downloading wrapt-1.15.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.9/78.9 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: wheel<1.0,>=0.23.0 in ./miniconda3/envs/tf-test/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow[and-cuda]) (0.41.2)
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading google_auth-2.23.4-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8 (from tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading Markdown-3.5.1-py3-none-any.whl.metadata (7.1 kB)
Collecting requests<3,>=2.21.0 (from tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading werkzeug-3.0.1-py3-none-any.whl.metadata (4.1 kB)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading cachetools-5.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 kB 6.6 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 6.4 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting MarkupSafe>=2.1.1 (from werkzeug>=1.0.1->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.9/83.9 kB 7.6 MB/s eta 0:00:00
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow[and-cuda])
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 9.0 MB/s eta 0:00:00
Downloading absl_py-2.0.0-py3-none-any.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 5.7 MB/s eta 0:00:00
Downloading flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Downloading grpcio-1.59.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 10.8 MB/s eta 0:00:00
Downloading h5py-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 10.9 MB/s eta 0:00:00
Downloading keras-2.13.1-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.2 MB/s eta 0:00:00
Downloading libclang-16.0.6-py2.py3-none-manylinux2010_x86_64.whl (22.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 10.9 MB/s eta 0:00:00
Downloading protobuf-4.25.0-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.4/294.4 kB 10.0 MB/s eta 0:00:00
Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 8.7 MB/s eta 0:00:00
Downloading tensorflow_io_gcs_filesystem-0.34.0-cp311-cp311-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 11.2 MB/s eta 0:00:00
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 6.1 MB/s eta 0:00:00
Downloading tensorflow-2.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (479.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 479.7/479.7 MB 6.0 MB/s eta 0:00:00
Downloading google_auth-2.23.4-py2.py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.3/183.3 kB 8.9 MB/s eta 0:00:00
Downloading Markdown-3.5.1-py3-none-any.whl (102 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.2/102.2 kB 8.1 MB/s eta 0:00:00
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 6.2 MB/s eta 0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 11.1 MB/s eta 0:00:00
Downloading werkzeug-3.0.1-py3-none-any.whl (226 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.7/226.7 kB 10.6 MB/s eta 0:00:00
Downloading cachetools-5.3.2-py3-none-any.whl (9.3 kB)
Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 10.5 MB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.3/140.3 kB 8.9 MB/s eta 0:00:00
Downloading MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
Downloading urllib3-2.0.7-py3-none-any.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 kB 9.0 MB/s eta 0:00:00
Installing collected packages: libclang, flatbuffers, wrapt, urllib3, typing-extensions, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, six, pyasn1, protobuf, packaging, oauthlib, numpy, MarkupSafe, markdown, keras, idna, grpcio, gast, charset-normalizer, certifi, cachetools, absl-py, werkzeug, rsa, requests, pyasn1-modules, opt-einsum, h5py, google-pasta, astunparse, requests-oauthlib, google-auth, google-auth-oauthlib, tensorboard, tensorflow
Successfully installed MarkupSafe-2.1.3 absl-py-2.0.0 astunparse-1.6.3 cachetools-5.3.2 certifi-2023.7.22 charset-normalizer-3.3.2 flatbuffers-23.5.26 gast-0.4.0 google-auth-2.23.4 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.59.2 h5py-3.10.0 idna-3.4 keras-2.13.1 libclang-16.0.6 markdown-3.5.1 numpy-1.24.3 oauthlib-3.2.2 opt-einsum-3.3.0 packaging-23.2 protobuf-4.25.0 pyasn1-0.5.0 pyasn1-modules-0.3.0 requests-2.31.0 requests-oauthlib-1.3.1 rsa-4.9 six-1.16.0 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.1 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 termcolor-2.3.0 typing-extensions-4.5.0 urllib3-2.0.7 werkzeug-3.0.1 wrapt-1.15.0
```

**Comment by zeionara** [comment]
If someone is solving the same issue, I've installed `cuda toolkit` and `cudnn`, updated `LD_LIBRARY_PATH` and it worked, basically:

```sh
> conda activate tf-test
> conda install cudatoolkit=11.8
> export LD_LIBRARY_PATH="$HOME/miniconda3/envs/tf-test/lib"
> conda install cudnn=8.9
> python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2023-11-06 01:43:59.188890: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-06 01:44:00.239682: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-11-06 01:44:01.023567: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-06 01:44:01.065869: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-06 01:44:01.066223: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```
