### ISSUE TITLE
Tensorflow 2.13.1 not detecting GPU on Jetson Orin, not built with CUDA

### ISSUE THREAD

**Issue by Paul-Mick** [tensorflow/tensorflow#62711]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.13.1

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Mobile device

NVIDIA Jetson AGX Orin

### Python version

3.8

### Bazel version

NA

### GCC/compiler version

NA

### CUDA/cuDNN version

CUDA 11.8/cuDNN 8.6.0.163

### GPU model and memory

NA

### Current behavior?

I am working on an object detection project and am ready to train my model, but Tensorflow does not recognize my GPU. Looking into it further, I found that my Tensorflow had been without GPU or CUDA support, just XLA support.

I had installed Tensorflow with pip.

I know that Tensorflow 2.13.1 does not have the "and-cuda" extra, so how can I specify through pip installation that Tensorflow be installed with GPU and CUDA support?

P.S. I want to avoid switching to Tensorflow 2.14.* because I am using python 3.8 which Tensorflow 2.13.1 is the last supporting version of.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

print(tf.config.list_logical_devices())
print(tf.config.list_physical_devices())
print(tf.test.is_built_with_cuda())
print(tf.test.is_built_with_gpu_support())
print(tf.test.is_built_with_rocm())
print(tf.test.is_built_with_xla())
print(tf.version.GIT_VERSION)
print(tf.version.VERSION)
```

### Relevant log output

```shell
[LogicalDevice(name='/device:CPU:0', device_type='CPU')]
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
False
False
False
True
v2.13.1-0-gf841394b
2.13.1
```

**Comment by SuryanarayanaY** [comment]
Hi @Paul-Mick ,

Please find the installation instructions for Tf2.13v from the history of [pip.md ](https://github.com/tensorflow/docs/blob/513d92d69cacbe9f2bda19e96045e6b836c93545/site/en/install/pip.md)file.

In Tf2.13v you need to install CUDA toolkit manually using the instructions in the attached link.

**Comment by Paul-Mick** [comment]
Thanks for the reply.

The instructions in the pip.md file did not resolve my issue.

Luckily I found the solution elsewhere: the [NVIDIA Jetson Framework Installation Page](https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html)

Apparently there is a special version of Tensorflow for Jetson devices, the newest of which is 2.14.0+nv23.11.

Installing this with `pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v60dp tensorflow==2.14.0+nv23.11` has Tensorflow recognizing my GPU properly.

Just wanted to post this incase others have the same issue.

**Comment by SuryanarayanaY** [comment]
@Paul-Mick ,

Tensorflow officially provides installation instructions for Ubuntu only. Your [comment](https://github.com/tensorflow/tensorflow/issues/62711#issuecomment-1875936782) can help others who uses the Jetson device. Just curious to mention that in above comment you installed TF2.14v which you are not intending to earlier?

**Comment by Paul-Mick** [comment]
@SuryanarayanaY 

You are correct, I did end up installing Tensorflow 2.14 which I was not intending to. I had run into a weird issue on my AGX Orin where the ethernet adapter would go down every once in a while, and I was unable able to fix it directly.

I ended up re-flashing the Orin to JetPack 6.0DP, which supports CUDA 12.2 and cuDNN 8.9. When looking into installing Tensorflow on Jetson devices deeper I found [NVIDIA's index of Tensorflow builds for Jetson](https://developer.download.nvidia.com/compute/redist/jp), and decided to use the newest of those, which is 2.14.0+nv23.11.

I did not want to upgrade Tensorflow originally because it would have required completely restarting my project, but since that was going to happen anyhow when re-flashing my Orin upgrading became less troublesome. And using the version of Tensorflow built for Jetson fixed my original issue.
