### ISSUE TITLE
Multiple GPUs: Out of Memory

### ISSUE THREAD

**Issue by KlaymenGC** [tensorflow/tensorflow#6310]
Hi,

I used to train my model on a single GPU with a batch size of ```20``` (images) without a problem. Now I want to take advantage of multiple GPU training. Currently I'm using 4 GPUs and want to do **data-parallel replicated training** with a batch size of ```20*4```.

If I understood it correctly, each batch will be splitted into 4 equal parts (in this case for every model on each GPU, the batch size will be ```20```) and be feeded to each GPU.  But I'm getting out of memory error:

```
...
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ********************************************************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 1.32GiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:975] Resource exhausted: OOM when allocating tensor with shape[80,921600,6]
...
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[80,921600,6]
```
any suggestions will be greatly appreciated!

**Comment by zakizhou** [comment]
From my understanding, you didn't catch how multi-gpus training works, imaging you want to training 10 epochs and you have 2 gpus, and then you manually set `num_epochs = 5`, both of your gpu will take 5 epochs training cocurrently and that's why your training time can be a half (neglecting network consumption). It's not like what you think about the multi-gpus training that splits a single batch to mini-batch. Back to you problem, a single gpu can only process 20 examples at a time, then you set it 80 so your gpu ran oom.

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.

**Comment by satishbro** [comment]
I am getting the same problem. I want to train 30 images including two classes. I am actually running Tensorflow in a CPU version, the batch size is actually 24. Is there any help for my thing ?

**Comment by satishbro** [comment]
Actually, I was running it from Virtual Machine . I just increased the internal memory and it works fine now. 
You can try like this.

**Comment by jojomaracas** [comment]
On 22 Nov 2017 09:53, satishbro <notifications@github.com> wrote:

Actually, I was running it from Virtual Machine . I just increased the internal memory and it works fine now.
You can try like this.

**Comment by mohapatras** [comment]
> From my understanding, you didn't catch how multi-gpus training works, imaging you want to train 10 epochs and you have 2 gpus, and then you manually set `num_epochs = 5`, both of your gpu will take 5 epochs training cocurrently and that's why your training time can be a half (neglecting network consumption). It's not like what you think about the multi-gpus training that splits a single batch to mini-batch. Back to you problem, a single gpu can only process 20 examples at a time, then you set it 80 so your gpu ran oom. The way to solve your problem is keeping `batch_size = 20` and decreasing `num_epochs`(make sure you write code properly that collects gradients from all gpus to central cpu and do averaging gradients and updating of variables)

Can you please elaborate more on this ? Usually "Images per GPU" is pushed and that gets multiplied by "no. of GPUs" given. for examples, batch of 20 per GPU and num GPU is 4, that gets multiplied and a total of 20 x 4 = 80 samples are pushed.

@zakizhou  Am I missing something in your comments ?
