### ISSUE TITLE
WhereOp: Race condition between counting the number of true elements and writing them

### ISSUE THREAD

**Issue by hosang** [tensorflow/tensorflow#6378]
I have the same problem as issue #4033 and [tensorflow/models#486](https://github.com/tensorflow/models/issues/486) happening to me in my own project with the nightly wheel. It is running fine on CPU, the problem only happens on GPU (titan x pascal).

The code that's causing the problem is this:
`pair_idxs = tf.where(tf.greater_equal(iou, params.thresh))`
(iou is a tensor, params.thresh is a python float)

WIth the error message: 
```
InvalidArgumentError (see above for traceback): WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 31641 elements; but when writing their indices, saw 187 elements.
         [[Node: Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](GreaterEqual/_25)]]
```

Cuda:
```
-rw-r--r-- 1 foo bar   52M Dec  8 20:06 libcublas_device.a
lrwxrwxrwx 1 foo bar    16 Dec  8 20:06 libcublas.so -> libcublas.so.8.0
lrwxrwxrwx 1 foo bar    19 Dec  8 20:07 libcublas.so.8.0 -> libcublas.so.8.0.45
-rwxr-xr-x 1 foo bar   40M Dec  8 20:06 libcublas.so.8.0.45
-rw-r--r-- 1 foo bar   46M Dec  8 20:07 libcublas_static.a
-rw-r--r-- 1 foo bar  546K Dec  8 20:07 libcudadevrt.a
lrwxrwxrwx 1 foo bar    16 Dec  8 20:06 libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 foo bar    19 Dec  8 20:07 libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 foo bar  406K Dec  8 20:06 libcudart.so.8.0.44
-rw-r--r-- 1 foo bar  757K Dec  8 20:07 libcudart_static.a
lrwxrwxrwx 1 foo bar    15 Dec  8 20:06 libcufft.so -> libcufft.so.8.0
lrwxrwxrwx 1 foo bar    18 Dec  8 20:07 libcufft.so.8.0 -> libcufft.so.8.0.44
-rwxr-xr-x 1 foo bar  140M Dec  8 20:06 libcufft.so.8.0.44
-rw-r--r-- 1 foo bar  124M Dec  8 20:07 libcufft_static.a
lrwxrwxrwx 1 foo bar    16 Dec  8 20:06 libcufftw.so -> libcufftw.so.8.0
lrwxrwxrwx 1 foo bar    19 Dec  8 20:07 libcufftw.so.8.0 -> libcufftw.so.8.0.44
-rwxr-xr-x 1 foo bar  466K Dec  8 20:06 libcufftw.so.8.0.44
-rw-r--r-- 1 foo bar   42K Dec  8 20:07 libcufftw_static.a
lrwxrwxrwx 1 foo bar    17 Dec  8 20:06 libcuinj64.so -> libcuinj64.so.8.0
lrwxrwxrwx 1 foo bar    20 Dec  8 20:06 libcuinj64.so.8.0 -> libcuinj64.so.8.0.44
-rwxr-xr-x 1 foo bar  6.2M Dec  8 20:06 libcuinj64.so.8.0.44
-rw-r--r-- 1 foo bar  1.6M Dec  8 20:07 libculibos.a
lrwxrwxrwx 1 foo bar    16 Dec  8 20:06 libcurand.so -> libcurand.so.8.0
lrwxrwxrwx 1 foo bar    19 Dec  8 20:07 libcurand.so.8.0 -> libcurand.so.8.0.44
-rwxr-xr-x 1 foo bar   57M Dec  8 20:07 libcurand.so.8.0.44
-rw-r--r-- 1 foo bar   57M Dec  8 20:06 libcurand_static.a
lrwxrwxrwx 1 foo bar    18 Dec  8 20:06 libcusolver.so -> libcusolver.so.8.0
lrwxrwxrwx 1 foo bar    21 Dec  8 20:07 libcusolver.so.8.0 -> libcusolver.so.8.0.44
-rwxr-xr-x 1 foo bar   52M Dec  8 20:06 libcusolver.so.8.0.44
-rw-r--r-- 1 foo bar   22M Dec  8 20:07 libcusolver_static.a
lrwxrwxrwx 1 foo bar    18 Dec  8 20:07 libcusparse.so -> libcusparse.so.8.0
lrwxrwxrwx 1 foo bar    21 Dec  8 20:06 libcusparse.so.8.0 -> libcusparse.so.8.0.44
-rwxr-xr-x 1 foo bar   41M Dec  8 20:07 libcusparse.so.8.0.44
-rw-r--r-- 1 foo bar   50M Dec  8 20:06 libcusparse_static.a
```

cuDNN:
```
lrwxrwxrwx 1 foo bar  13 Jul 27 07:55 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 foo bar  17 Jul 27 07:55 libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 foo bar 76M Jul 27 07:53 libcudnn.so.5.1.5
-rw-r--r-- 1 foo bar 67M Jul 27 07:53 libcudnn_static.a
```

`tenserflow.__version__: 0.12.head`

**Comment by hosang** [comment]
I managed to build a small reproducing example:
```
np.random.seed(42)
iou_data = np.random.rand(10, 20)

data = tf.placeholder(shape=iou_data.shape, dtype=tf.float32)
iou = data + 1
pair_idxs = tf.where(tf.greater_equal(iou, 0.5))

with tf.Session():
    tf.global_variables_initializer().run()
    idxs = pair_idxs.eval(feed_dict={data: iou_data})
```

The issue is not happening if iou is a placeholder.

**Comment by hosang** [comment]
This also fails, but commenting out the assignment makes it work.
```
iou = tf.placeholder(shape=[1], dtype=tf.float32)
cmp = tf.Variable([False], dtype=tf.bool)
cmp = cmp.assign(iou >= 0.5)
pair_idxs = tf.where(cmp)

with tf.Session():
    tf.global_variables_initializer().run()
    idxs = pair_idxs.eval(feed_dict={iou: [0.1]})
```

**Comment by aselle** [comment]
@zheng-xq, do you have any insights on the concurrency issue here. I don't see the problem with the Titan X Maxwell edition on current nightly.

**Comment by AmnonDrory** [comment]
On my system a similar error was produced as a result of the GPU running out of memory.

**Comment by lancejchen** [comment]
I met the same issue, turned out I already started a training instance so all my GPU memory are used up. After I kill that instance, the issue is gone.

**Comment by hosang** [comment]
@aselle updating to a newer version fixed the problem for me and I didn't encounter the problem again.

**Comment by byronyi** [comment]
@hosang Maybe you could close the issue then.
