### ISSUE TITLE
Issue with tf.one_hot() in 0.12.0 in GPU mode (CUDA_ERROR_ILLEGAL_ADDRESS)

### ISSUE THREAD

**Issue by SergeyBykov1** [tensorflow/tensorflow#6509]
I'm using a LeNet-5 mnist example from Udacity's course. Link to the source code is below.
Training works ok on a CPU (config = tf.ConfigProto(device_count = {'GPU': 0})),
but fails in a GPU mode with the following 'CUDA_ERROR_ILLEGAL_ADDRESS' error:

> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
name: GeForce GTX 1060 6GB
major: 6 minor: 1 memoryClockRate (GHz) 1.7845
pciBusID 0000:01:00.0
Total memory: 6.00GiB
Free memory: 5.01GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0)
Training...
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: **CUDA_ERROR_ILLEGAL_ADDRESS**
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:198] Unexpected Event status: 1

I have reproduced same error on two setups.
Environment 1 (Home PC):
- windows 10; 
- latest anaconda 4.2.0, python 3.5; 
- cuda 8
- cudnn 5.1 (for win10)
- tensorflow 0.12.0 gpu (https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.0-cp35-cp35m-win_amd64.whl)
- GeForce GTX 1060 6Gb

Environment 2 (Work PC):
- windows 7; 
- latest anaconda 4.2.0, python 3.5; 
- cuda 8
- cudnn 5.1 (for win7)
- tensorflow 0.12.0 gpu (https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.0-cp35-cp35m-win_amd64.whl)
- GeForce GTX 660 3Gb

I'm sharing two scripts with minor changes that allow a workaround:
https://drive.google.com/open?id=0B6jkkqMOGy5cNHh3TVpxU283Ykk

Main difference:
Script from example that crashes (LabLenetBad.py) uses raw mnist label data with the tf.one_hot() call.
The workaround (LabLenetGood.py) reads mnist data with (one_hot=True) flag and does not use tf.one_hot() call on the Y placeholder.

I think that tf.one_hot does not work properly on the gpu.

**Comment by gunan** [comment]
https://github.com/vlfeat/matconvnet/issues/65

In this issue, I see that some people were able to go around the problem by changing their drivers.
Can it be the same issue here?

**Comment by SergeyBykov1** [comment]
@gunan I've updated Nvidia's driver to the most recent version (376.33) on my Work PC.

The issue still occurs.
I'd like to note that sometimes it triggers only CUDA_ERROR_ILLEGAL_ADDRESS error.
But sometimes it triggers CUDA_ERROR_ILLEGAL_ADDRESS + some cudnn errors.

> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to que
ry event: CUDA_ERROR_ILLEGAL_ADDRESS
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\gpu\gpu_event_mgr.cc:198] Unexpected Event status: 1
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_IN
TERNAL_ERROR
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_B
AD_PARAM
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\kernels\conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(
&algorithms)

P.S. I've written a similar comment already, but it has strangely disappeared from the topic.

**Comment by guschmue** [comment]
I know there is a problem with one_hot(T=uint8) that results in the CUDA_ERROR_ILLEGAL_ADDRESS.
Looked at this in the past but found nothing obvious in the source. 
Let me attach a debugger and see if we find this.
This happens only for T=uint8, int32 will work fine.

**Comment by name-name** [comment]
Thanks for sharing!! I had the same problem and when I replace the tf.one_hot by the following hand-written implementation it finally works.
#instead of    one_hot_y = tf.one_hot(y, 43)

num_labels = 43
sparse_labels = tf.reshape(y, [-1, 1])
derived_size = tf.shape(sparse_labels)[0]
indices = tf.reshape(tf.range(0, derived_size, 1), [-1, 1])
concated = tf.concat(1, [indices, sparse_labels])
outshape = tf.concat(0, [tf.reshape(derived_size, [1]), tf.reshape(num_labels, [1])])
one_hot_y = tf.sparse_to_dense(concated, outshape, 1.0, 0.0)

**Comment by michaelisard** [comment]
@ebrevdo any idea what the problem is here?

**Comment by guschmue** [comment]
a simple repro case attached (only happens on windows/gpu).
I'm think this showed only for uint8 in the past but now I see it also for int32.
--
import tensorflow as tf
import numpy as np

data = np.zeros(shape=(3, 5), dtype='int32')
input = tf.placeholder(tf.int32, data.shape, name="input")
one_hot_op = tf.one_hot(input, depth=3, dtype=tf.float32)

init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(one_hot_op, feed_dict = {input : data}))

**Comment by gunan** [comment]
CC @mrry (for windows) @zheng-xq (for CUDA, in case error message looks familiar)

**Comment by ebrevdo** [comment]
Do you get the same issue with tf.reverse_sequence?

**Comment by guschmue** [comment]
tf.reverse_sequence works ok, at least tensorflow/python/kernel_tests/reverse_sequence_op_test.py does pass.
tensorflow/python/kernel_tests/diag_op_test.py fails.
I can collect some info with nvidia debugger ... takes me a little: need to recompile with enough symbol info.

**Comment by gunan** [comment]
Merging duplicate issues.
@weixsong @aclaussen1 @buaahsh

Quoting some information from a duplicate:
(@buaahsh)

>  Here is my code:
>
>with tf.Session() as sess:
>    # with tf.device("/cpu:0"):
>    x = tf.ones(shape=[3, 3])
>    x_diag = tf.diag_part(x)
>    x_diag_matrix = tf.matrix_diag(x_diag)
>    print(sess.run(x_diag_matrix))
>It works ok on a CPU but fails in a GPU mode with the following 'CUDA_ERROR_ILLEGAL_ADDRESS' >error:
>
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
>name: Tesla K40m
>major: 3 minor: 5 memoryClockRate (GHz) 0.745
>pciBusID 0000:27:00.0
>Total memory: 11.16GiB
>Free memory: 11.09GiB
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0: Y
>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:27:00.0)
>E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:586] Could not identify NUMA node of /job:localhost/replica:0/task:0/gpu:0, defaulting to 0. Your kernel may not have been built with NUMA support.
>E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
>F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:198] Unexpected >Event status: 1
>I have tried
>
>x = tf.ones(shape=[3, 3])
>x_diag = tf.diag_part(x)
>and x_diag_matrix = tf.matrix_diag([1., 1., 1.]) , Both work ok in a GPU mode. Maybe the tensor couldn't >be input of tf.matrix_diag() in a Windows GPU mode?

**Comment by guschmue** [comment]
no funny: after recompiling the cuda kernels with -G one_hot works now.
The diag_op still dies:
>	CUmodule 1c133fcdc00 - [4] const __operator_()__ - Line 40	CUDA
 	CUmodule 1c133fcdc00 - [3] const coeff - Line 130	CUDA
 	CUmodule 1c133fcdc00 - [2] evalScalar - Line 136	CUDA
 	CUmodule 1c133fcdc00 - [1] run - Line 209	CUDA
 	CUmodule 1c133fcdc00 - [0] EigenMetaKernel<TensorEvaluator<TensorAssignOp<TensorMap<Tensor<double,int=2,int=1,__int64>,int=16,MakePointer>,TensorGeneratorOp<MatrixDiagPartGenerator<double>,TensorMap<Tensor<double,int=2,int=1,__int64>,int=16,MakePointer> const > const > const ,GpuDevice>,__int64> - Line 244	CUDA

I'll spend some more time on this later today.

**Comment by ebrevdo** [comment]
Derek, looks like a Windows cuda / eigen issue.

**Comment by ebrevdo** [comment]
Sergey, can you run the job with cuda-memcheck?  You may have to recompile -c dbg.  Not sure.

**Comment by revelationnow** [comment]
I'm facing the same issue, I ran the cuda-memcheck on the job and I see a lot of null pointer accesses from EigenMetaKernel.
[error_log.txt](https://github.com/tensorflow/tensorflow/files/695756/error_log.txt)

**Comment by revelationnow** [comment]
Wondering if anyone is looking into this. An update would be good.

**Comment by guschmue** [comment]
I'm looking at but have not had luck yet. My biggest issue is that when I compile the kernels with full debug info my repro case doesn't fail anymore. But I found that the one_hot tests in tensorflow/python/kernel_tests/one_hot_op_test.py.py can still repro a crash and before it crashes the results of tests are already wrong. When it crashes the arguments in EigenMetaKernel->EigenMetaKernelEval are wrong, like step_size is some very high number.
I'll spend some more time on it today and might need help if I don't find something.

**Comment by gunan** [comment]
@rmlarsen @benoitsteiner 
Adding for possible issues in Eigen.

**Comment by mrry** [comment]
A small update here: I've managed to reproduce the failures, but I'll have to rely on people more experienced in Eigen/CUDA/MSVC to figure out why this op is being compiled to incorrect code on Windows.

In the mean time, I've sent out #6822, which disables the broken GPU kernels for `tf.one_hot()` (and some `tf.matrix_diag()` and `tf.matrix_diag_part()`, which seem to have the same failure mode, and both also use the generator interface), while we work on a fix.

**Comment by Pyrestone** [comment]
Hi guys, what's the status on this?
I've encountered the same bug on Windows/GPU with a GTX Titan Black.
When I replaced 
`target_one_hot=tf.onehot(targets,vocab_size_targets,dtype=tf.float32)`

with the workaround by name-name
it worked just fine.

here's the function wrapper i used for the workaround:
```
def one_hot_patch(x,depth):
                #workaround by name-name
                sparse_labels=tf.reshape(x,[-1,1])
                derived_size=tf.shape(sparse_labels)[0]
                indices=tf.reshape(tf.range(0,derived_size,1),[-1,1])
                concated=tf.concat(1,[indices,sparse_labels])
                outshape=tf.concat(0,[tf.reshape(derived_size,[1]),tf.reshape(depth,[1])])
                return tf.sparse_to_dense(concated, outshape,1.0,0.0)
target_one_hot=one_hot_patch(targets,vocab_size_targets)
```
my `targets` and `vocab_size_targets` are both tf.int32 Tensors.

I'm currently on r0.12 (pip installation) with cuda 8.0 and CuDNN 5.1

**Comment by mrry** [comment]
@Pyrestone We disabled the broken GPU kernel for `tf.one_hot()` in the Windows build, so if you upgrade to 1.0.0rc0 you should no longer need the patch.

**Comment by jaejun-yoo** [comment]
@mrry Then the problems are now gone?  (I am using win10 64bit tf-gpu-0.12.1 with cuda 8.0 and CuDNN 5.1) 

I encountered similar issue with 0.12.1 and tried suggested get-arounds and found the results are strange. [Here](https://github.com/jaejun-yoo/Three-ways-to-avoid-tf.one_hot-function-) you can find three get-arounds I have tried to avoid using tf.one_hot().
I found that the substitutes worked fine(give the same output with one-hot) but the final results (came out from the script) were somewhat strange or wrong... I doubt that this is due to the other issue cuz I have only changed the part for one_hot function in the code which worked fine before it. Maybe my fault somewhere?... :(

**Comment by smasoudn** [comment]
I have the same issue with `tf.one_hot()` . Here is my settings:

- Windows 10
- NVIDIA GeForce GTX 1070
- Cudda 8.0
- CuDnn 5.1
- TensorFlow 0.12

Error:    Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
             Kernel died

**Comment by gunan** [comment]
The problem is resolved in 1.0.0-rc0, 1 or 2..
Please upgrade and try again.

**Comment by strickon** [comment]
tested rc2 windows 10, gtx 1060, cuda 8 cudnn 5.1

The kernel diag_op_test fails

I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:03:00.0)
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:198] Unexpected Event status: 1


I am still getting this error in some code I am running.  Doesnt happen with the cpu version
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:397] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:404] error retrieving driver version: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:364] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\kernels\conv_ops.cc:605] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)

**Comment by gunan** [comment]
#6822 explicitly disables diag_op_test because of failures when using GPU.
We are working on debugging those problems.

**Comment by strickon** [comment]
So is there some official statement about what GPUs and versions of CUDA and cudnn work on windows 10 and for all platforms for that matter?  It is just Pascal that has the issue?  It would be helpful if there were some specific information about what features work and don't work, rather than run code and get random errors.

While I know that certain tests fail, I am not familiar enough with tensor flow yet to fully understand what that means for what features of the api won't work.

Thanks

**Comment by jaejun-yoo** [comment]
@gunan I tested rc2 and the error message was gone (which didn't in rc1). Thank you for your comment!

**Comment by MikeZhu92** [comment]
I come up with the same issue. It can be solved by the solution provided by`name-name`
Here is my computer info:
>  Win 8.1  (64bit)
>  GPU     GT 750M 4G (GK107)
>    CUDA  8.0.60
>  cuDNN  5.1
>  tensorflow-gpu 0.12.1

I have tried tensorflow-gpu 1.0.0 (not sure whether rc1 or 2) (Install using `pip install tensorflow-gpu`)

It actually make things worse, the program will get error in both situations. 
(1. with the original code      2. replace the tf.one_hot() ) 

Here is the info I have got in tensorflow-gpu 1.0.0 with `tf.one_hot()`
```
ValueError                                Traceback (most recent call last)
<ipython-input-8-967bb02bb6da> in <module>()
      2 
      3 logits = LeNet(x)
----> 4 cross_entropy = tf.nn.softmax_cross_entropy_with_logits(logits, one_hot_y)
      5 loss_operation = tf.reduce_mean(cross_entropy)
      6 optimizer = tf.train.AdamOptimizer(learning_rate = rate)

C:\Users\name \Miniconda3\envs\env1\lib\site-packages\tensorflow\python\ops\nn_ops.py in softmax_cross_entropy_with_logits(_sentinel, labels, logits, dim, name)
   1576   """
   1577   _ensure_xent_args("softmax_cross_entropy_with_logits", _sentinel,
-> 1578                     labels, logits)
   1579 
   1580   # TODO(pcmurray) Raise an error when the labels do not sum to 1. Note: This

C:\Users\name \Miniconda3\envs\env1\lib\site-packages\tensorflow\python\ops\nn_ops.py in _ensure_xent_args(name, sentinel, labels, logits)
   1531   if sentinel is not None:
   1532     raise ValueError("Only call `%s` with "
-> 1533                      "named arguments (labels=..., logits=..., ...)" % name)
   1534   if labels is None or logits is None:
   1535     raise ValueError("Both labels and logits must be provided.")

ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
```

The info I have got in tensorflow-gpu 0.12.1 with `tf.one_hot()` is
```
c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
```

**Comment by mrry** [comment]
@MikeZhu92 The error you're seeing seems to be from one of the breaking function signature changes that were made before the 1.0 release. Fortunately the solution to *that* problem is simple. Replace the following line in your code:

```python
cross_entropy = tf.nn.softmax_cross_entropy_with_logits(logits, one_hot_y)
```

...with the following line that names the arguments:

```
cross_entropy = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=one_hot_y)
```

**Comment by MikeZhu92** [comment]
@mrry Thank you for help, I didn't realize that yesterday. 
It fixes the issue in tensorflow-gpu 1.0.0. For 0.12.1 it's still give me error message about the cuDNN stuff.
I have switched to 1.0.0 to push myself going through some updated features in the latest version. 
Tensorflow is evolving really fast 👍

**Comment by DIPRECXY** [comment]
I solved the problem by upgrading cuDNN to v5.1 version. You can have a try.
cuDNN download : https://developer.nvidia.com/rdp/cudnn-download

**Comment by ohernpaul** [comment]
I can confirm that upgrading to higher than 0.12 resolved this issue.

[...gpu_event_mgr.cc:198] Unexpected Event status: 1 lead me to this thread

My machine has 2 1080s running tf 0.12.0rc1 and using tf.onehot, causing my gpu driver to crash, as well as python. 

Upgraded to tf 1.0.0 and updated some concat and SparseTensor calls, and my program worked.
