### ISSUE TITLE
could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM Check failed: stream->parent()-GetConvolveAlgorithms(&algorithms) ```

### ISSUE THREAD

**Issue by aclaussen1** [tensorflow/tensorflow#6606]
I'm trying to use tensorflow for this project: https://github.com/ibab/tensorflow-wavenet

I've gotten to the point where when I import tensorflow, I get the messages that all the CUDA libraries are successfully opened locally.

I can run the following python code from https://www.tensorflow.org/get_started/os_setup#run_tensorflow_from_the_command_line and it works fine.

> import tensorflow as tf
> hello = tf.constant('Hello, TensorFlow!')
> sess = tf.Session()
> print(sess.run(hello))
Hello, TensorFlow!
> a = tf.constant(10)
> b = tf.constant(32)
> print(sess.run(a + b))
42
>

However when I run the wavenet project, I get the following error messages and then python crashes.

```
c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
name: GeForce GTX 950
major: 5 minor: 2 memoryClockRate (GHz) 1.19
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.65GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950, pci bus id: 0000:01:00.0)
WARNING:tensorflow:From train.py:249 in main.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Trying to restore saved checkpoints from ./logdir\train\2017-01-02T16-17-15 ... No checkpoint found.
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\kernels\conv_ops.cc:532] Check failed: stream->parent()-GetConvolveAlgorithms(&algorithms)
```

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/4251

### Environment info
Operating System:
Windows

Installed version of CUDA and cuDNN: 
cuDNN v5.1 (August 10, 2016), for CUDA 8.0

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'tensor' is not defined

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### What other attempted solutions have you tried?

I have tried reinstalling Cuda, different versions of cudnn. Looked at different issues with same error messages but nothing seemed to help.

**Comment by weixsong** [comment]
Hi, @aclaussen1 , I got the same issue when running https://github.com/ibab/tensorflow-wavenet, and I also tried many solutions, but all failed.

Have you fixed the issue?

**Comment by weixsong** [comment]
I'm using TensorFlow on Windows Server 2012, TensorFlow version is 0.12.1
I've install CUDA (CUDA Version 8.0.44), and install cuDnn (cuDNN v5.1 (August 10, 2016), for CUDA 8.0).

that cuDnn is build for windows 10.

But when I run my tensorflow code is get some error about:

am_executor\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_IN
TERNAL_ERROR
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_B
AD_PARAM
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\kernels\conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(
&algorithms)
It seems the cuDNN version is not correct, but I tried cuDNN v5.0, also got this exception.

does anyone know how to fix this issue?
Thanks very much.

**Comment by gunan** [comment]
This seems to be same as #6509

**Comment by gunan** [comment]
Closing duplicate issue. Please follow #6509 for updates.

**Comment by aclaussen1** [comment]
I gave up on Windows and got it to work with Ubuntu

**Comment by SHMCU** [comment]
I am in Ubuntu, I have this three errors and I found it is because insufficient memory on the GPU I specified. That GPU is occupied by some other programs. I changed to another GPU with more memory available. The problem is gone.

**Comment by Parkwdllcr** [comment]
today I get the same issue,but not 干掉it!

**Comment by cliffzwj** [comment]
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.7
sess = tf.Session(config=config)
sess.run(init)

**Comment by jxmelody** [comment]
I have the same error, I found that @cliffzwj 's solution does work! thanks~
