### ISSUE TITLE
using TensorFlow on Windows Server 2012

### ISSUE THREAD

**Issue by weixsong** [tensorflow/tensorflow#6660]
I'm using TensorFlow on Windows Server 2012, TensorFlow version is 0.12.1
I've install CUDA (CUDA Version 8.0.44), and install cuDnn (cuDNN v5.1 (August 10, 2016), for CUDA 8.0).

that cuDnn is build for windows 10.

But when I run my tensorflow code is get some error about:
```
am_executor\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_IN
TERNAL_ERROR
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_B
AD_PARAM
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\kernels\conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(
&algorithms)
```

It seems the cuDNN version is not correct, but I tried cuDNN v5.0, also got this exception.

does anyone know how to fix this issue?
Thanks very much.

**Comment by weixsong** [comment]
ps, tensorflow will report load cudnn64_5.dll successfully:
```
dirname(inspect.getfile(tensorflow)))'
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfu
lly opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfu
lly opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfu
lly opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfu
lly opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfu
lly opened CUDA library curand64_80.dll locally
```

**Comment by gunan** [comment]
I will try to reproduce the problem when I find the time.
But could you try installing windows 7 build of cudnn and see if that resolves the issue?

**Comment by weixsong** [comment]
Hi, @gunan , using cuDNN for windows 7 still got the same issue.

**Comment by gunan** [comment]
This seems to be the same as #6509
Let's follow the other issue to merge all discussion.

**Comment by gunan** [comment]
Closing duplicate issue, as the other one seems to have more information.
Please follow #6059 for resolution.

**Comment by normansiboro** [comment]
@weixsong How could you install tensorflow on windows server 2012.
I have tried it many times and it didn't work. 
Here is my case:
First I installed python 3.5.* but it gave me error and I found that windows server 2012 only supports python 2.7.* and the I installed python 2.7.*. 
After installing python 2.7, I installed tensorflow but I got error that there are no support version and I found that tensorflow on windows only supports python 3.5 and 3.6
Do you have any advice

**Comment by aqibmumtaz** [comment]
after spending hours I am able to fix this issue here is my answer on stackoverflow https://stackoverflow.com/a/50475864/1996802

**Comment by pratyushlohumi26** [comment]
> @weixsong How could you install tensorflow on windows server 2012.
> I have tried it many times and it didn't work.
> Here is my case:
> First I installed python 3.5.* but it gave me error and I found that windows server 2012 only supports python 2.7.* and then I installed python 2.7.*.
> After installing python 2.7, I installed tensorflow but I got an error that there are no support version and I found that tensorflow on windows server only supports python 3.5 and 3.6
> Do you have any advice?

@normansiboro Are you sure about what you wrote in your comment, so according to you windows server 2012 R2 can't run Tensorflow as tf is not there  for that os ?

Or where you able to find a workaround for it?
