### ISSUE TITLE
Library not loaded: @rpath/libcudart.8.0.dylib when running TF GPU on MacOS

### ISSUE THREAD

**Issue by abossenbroek** [tensorflow/tensorflow#6729]
Something related to linking seems to cause the build to fail on Mac OS 10.12.2 when building with CUDA.

Verbose build error is:

```
$ bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package
INFO: Found 1 target...
ERROR: /Users/anton/tmp/tensorflow/tensorflow/contrib/ffmpeg/BUILD:66:1: Executing genrule //tensorflow/contrib/ffmpeg:decode_audio_op_py_pygenrule failed: bash failed: error executing command 
  (cd /private/var/tmp/_bazel_anton/d3361bfa15c75c42ab541f3d83e8eba4/execroot/tensorflow && \
  exec env - \
    PATH=/usr/local/cuda/bin:/Users/anton/.pyenv/shims:/Users/anton/.rbenv/shims:/Users/anton/.scalaenv/shims:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/anton/unix/bin:/usr/local/cuda/bin \
    TMPDIR=/var/folders/4r/mq7ht1z11t72w5b5b6014zwm0000gn/T/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/contrib/ffmpeg/gen_decode_audio_op_py_py_wrappers_cc 1 > bazel-out/local_darwin-py3-opt/genfiles/tensorflow/contrib/ffmpeg/ops/gen_decode_audio_op_py.py'): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 6.
dyld: Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /private/var/tmp/_bazel_anton/d3361bfa15c75c42ab541f3d83e8eba4/execroot/tensorflow/bazel-out/host/bin/tensorflow/contrib/ffmpeg/gen_decode_audio_op_py_py_wrappers_cc
  Reason: image not found
/bin/bash: line 1: 72493 Abort trap: 6           bazel-out/host/bin/tensorflow/contrib/ffmpeg/gen_decode_audio_op_py_py_wrappers_cc 1 > bazel-out/local_darwin-py3-opt/genfiles/tensorflow/contrib/ffmpeg/ops/gen_decode_audio_op_py.py
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2.707s, Critical Path: 0.32s
```

### Related posts
It seems that Caffe had similar issues due to Apple dropping the `LD_LIBRARY_PATH` environment variable: https://github.com/BVLC/caffe/issues/3227

### Environment info
Operating System: Mac OS 10.12.2

Installed version of CUDA and cuDNN: 
```
$ ls -l /usr/local/cuda/lib/libcud*
-rwxr-xr-x  1 root  wheel  13504 Nov  3 19:39 /usr/local/cuda/lib/libcuda.dylib*
lrwxr-xr-x  1 root  wheel     45 Nov  3 19:40 /usr/local/cuda/lib/libcudadevrt.a@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
lrwxr-xr-x  1 root  wheel     50 Nov  3 19:40 /usr/local/cuda/lib/libcudart.8.0.dylib@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x  1 root  wheel     46 Nov  3 19:40 /usr/local/cuda/lib/libcudart.dylib@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
lrwxr-xr-x  1 root  wheel     49 Nov  3 19:40 /usr/local/cuda/lib/libcudart_static.a@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
lrwxr-xr-x  1 root  admin     47 Jan  8 16:48 /usr/local/cuda/lib/libcudnn.5.dylib@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.5.dylib
lrwxr-xr-x  1 root  admin     45 Jan  8 16:48 /usr/local/cuda/lib/libcudnn.dylib@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.dylib
lrwxr-xr-x  1 root  admin     48 Jan  8 16:48 /usr/local/cuda/lib/libcudnn_static.a@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn_static.a
```

##### Configuration command
```
Please specify the location of python. [Default is /Users/anton/.pyenv/shims/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Error in sitecustomize; set PYTHONVERBOSE for traceback:
KeyError: 'PYTHONPATH'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
KeyError: 'PYTHONPATH'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
KeyError: 'PYTHONPATH'
Found possible Python library paths:
  /Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages]

Using python library path: /Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] Y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
libcudnn.dylib resolves to libcudnn.dylib
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.5  	 
Extracting Bazel installation...
............
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.........
____Loading package: tensorflow/tools/git
____Loading package: tensorflow/contrib/opt
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 40,960 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 444,518 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 743,716 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 1,170,534 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 1,597,352 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 1,998,646 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 2,251,050 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 2,675,032 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 3,144,390 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 3,579,716 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 3,788,162 bytes
INFO: All external dependencies fetched successfully.
Configuration finished
```

#### Git revision
```
$ git rev-parse HEAD
ec7929b878926c39255254e9aea992f0bc65aa68
```

#### Bazel version
```
$ bazel version
Build label: 0.4.3-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 15:20:15 2016 (1482420015)
Build timestamp: 1482420015
Build timestamp as int: 1482420015
```

### Update
I modified `third_party/gpus/crosstool/CROSSTOOL.tpl`  the following lines 
```
  cxx_flag: "-std=c++11"
  linker_flag: "-Wl,-no-as-needed"
``` 
in the toolchain section to: 
```
  cxx_flag: "-std=c++11"
  linker_flag: "-Wl,-no-as-needed,-rpath,/usr/local/cuda/lib"
```

Now I get failures at:
```
ERROR: /Users/anton/tmp/tensorflow/tensorflow/python/BUILD:793:1: Executing genrule //tensorflow/python:control_flow_ops_pygenrule failed: bash failed: error executing command 
  (cd /private/var/tmp/_bazel_anton/d3361bfa15c75c42ab541f3d83e8eba4/execroot/tensorflow && \
  exec env - \
    PATH=/usr/local/cuda/bin:/Users/anton/.pyenv/shims:/Users/anton/.rbenv/shims:/Users/anton/.scalaenv/shims:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/anton/unix/bin:/usr/local/cuda/bin \
    TMPDIR=/var/folders/4r/mq7ht1z11t72w5b5b6014zwm0000gn/T/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/python/gen_control_flow_ops_py_wrappers_cc @tensorflow/python/ops/hidden_ops.txt 1 > bazel-out/local_darwin-py3-opt/genfiles/tensorflow/python/ops/gen_control_flow_ops.py'): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 6.
dyld: Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /private/var/tmp/_bazel_anton/d3361bfa15c75c42ab541f3d83e8eba4/execroot/tensorflow/bazel-out/host/bin/tensorflow/python/gen_control_flow_ops_py_wrappers_cc
  Reason: image not found
/bin/bash: line 1: 45635 Abort trap: 6           bazel-out/host/bin/tensorflow/python/gen_control_flow_ops_py_wrappers_cc @tensorflow/python/ops/hidden_ops.txt 1 > bazel-out/local_darwin-py3-opt/genfiles/tensorflow/python/ops/gen_control_flow_ops.py
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1683.463s, Critical Path: 1587.37s
```

I got a bit further but it seems that I need to modify the link options in more files.

**Comment by yaroslavvb** [comment]
Can you run tensorflow GPU from an official MacOS GPU PIP package? There are some SIP-related issues which also cause a failure there

**Comment by abossenbroek** [comment]
Installed the GPU version from the official page and `import tensorflow as tf` leads to an error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/private/var/tmp/_bazel_anton/d3361bfa15c75c42ab541f3d83e8eba4/execroot/tensorflow/tensorflow/python/__init__.py in <module>()
     60     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 61     from tensorflow.python import pywrap_tensorflow
     62     sys.setdlopenflags(_default_dlopen_flags)

ImportError: cannot import name 'pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

/private/var/tmp/_bazel_anton/d3361bfa15c75c42ab541f3d83e8eba4/execroot/tensorflow/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

/private/var/tmp/_bazel_anton/d3361bfa15c75c42ab541f3d83e8eba4/execroot/tensorflow/tensorflow/python/__init__.py in <module>()
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     73 
     74 # Protocol buffers

ImportError: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_anton/d3361bfa15c75c42ab541f3d83e8eba4/execroot/tensorflow/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow'


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by abossenbroek** [comment]
The install goes well.  Just ran the tests and those as expected but not sure whether tensorflow is using my GPU. I ran the test described on https://www.tensorflow.org/how_tos/using_gpu/ to see whether Tensorflow sees my gpus and unfortunately it doesn't. The output is:
```
MatMul: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] MatMul: /job:localhost/replica:0/task:0/cpu:0
b: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] b: /job:localhost/replica:0/task:0/cpu:0
a: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:819] a: /job:localhost/replica:0/task:0/cpu:0
[[ 22.  28.]
 [ 49.  64.]]
```

**Comment by yaroslavvb** [comment]
You should see something like this if you installed MacOS GPU version

```
(tf12rc1) (tf12rc1)bash-3.2$ python 
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.dylib locally
>>> 
```

**Comment by abossenbroek** [comment]
Same issue:
```
In [1]: import tensorflow as tf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/__init__.py in <module>()
     48     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 49     from tensorflow.python import pywrap_tensorflow
     50     sys.setdlopenflags(_default_dlopen_flags)

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow = swig_import_helper()
     29     del swig_import_helper

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
     25             finally:

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: dlopen(/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
```

**Comment by yaroslavvb** [comment]
So this is not an issue with building, but rather you not being able to load your cuda libraries during runtime

Some troubleshooting is here:
https://github.com/tensorflow/tensorflow/issues/5141

(ln -s your libcuda file, disable SIP, make sure you set LD_LIBRARY_PATH, and DYLD_LIBRARY_PATH correctly)

**Comment by yaroslavvb** [comment]
Also see https://github.com/tensorflow/tensorflow/issues/6693

**Comment by abossenbroek** [comment]
Tried the following:
```
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib/
```

```
$ python3 -c "import tensorflow;"
Error in sitecustomize; set PYTHONVERBOSE for traceback:
KeyError: 'PYTHONPATH'
Traceback (most recent call last):
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

directory shows:
```
$ ls -al /usr/local/cuda/lib/libcudart.8.0.dylib 
lrwxr-xr-x  1 root  wheel  50 Nov  3 19:40 /usr/local/cuda/lib/libcudart.8.0.dylib@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
```

What should  I try next?

**Comment by yaroslavvb** [comment]
turn off SIP?

On Mon, Jan 9, 2017 at 11:23 AM, Anton Bossenbroek <notifications@github.com

**Comment by abossenbroek** [comment]
wanted to prevent that for security reasons.... but will try that.

**Comment by yaroslavvb** [comment]
Doesn't work with SIP unfortunately. Also LD_LIBRARY_PATH as I mentioned above

**Comment by jart** [comment]
I'm terribly confused by this issue. In the original error message, [python_op_gen_main.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/python_op_gen_main.cc) is crashing when invoked by a genrule to create a Python wrapper for contrib/ffmpeg:decode_audio_op because it can't load Cuda due to [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection)? I'm not sure why that tool needs to link Cuda, which is clearly build messiness. But why would SIP prevent linking Cuda?

**Comment by yaroslavvb** [comment]
@jart The way TensorFlow loads dynamic libraries is not secure (loading by relative path means someone could trick TF to load malicious code from an all-writeable location). So MacOS disables it https://github.com/BVLC/caffe/issues/3227 

As far to why `gen_decode_audio_op_py_py_wrappers_cc` needs CUDA, a possibility is that is it built in in the wrong mode. Bazel builds in [two configurations](https://bazel.build/versions/master/docs/be/general.html#cross-compilation-considerations) "host" configuration and "target" configuration. The tool is a `cc_binary` [target](https://github.com/tensorflow/tensorflow/blob/ec7929b878926c39255254e9aea992f0bc65aa68/tensorflow/tensorflow.bzl#L146) which I suspect implies target mode. The proper fix would be to force it to be built in host mode. One way of forcing host mode is to `tools` property of genrule , ie like [tensorflow/compiler/aot/tfcompile.bzl](https://github.com/tensorflow/tensorflow/blob/f94e20f2c704f037a113d350fd7c431e3fd75df8/tensorflow/compiler/aot/tfcompile.bzl#L140)

There's an internal issue if you search for "avx2", "ppluzhnikov" and "tool" that addressed similar problem in TF

**Comment by jart** [comment]
Where is TensorFlow loading libraries by relative path? I know with op libraries get_path_to_datafile() turns relative .so paths into absolute paths before passing them along to dlopen. I'm not sure where cuda is being loaded, but I'd like to know more. If TensorFlow is being insecure, it should be fixed.

Re: Cuda dep, that program is [passed](https://github.com/tensorflow/tensorflow/blob/1f5d61d0b4a2ae08319650ae78c5609c515615db/tensorflow/tensorflow.bzl#L219) to genrule via tools so Bazel is guaranteed to build it with host configuration, which seems to be a result of the internal issue you mentioned. So my best guess is Cuda is being superfluously linked because the tool depends on core:lib_internal and core:lib_internal depends on everything. Hopefully someday we can get rid of all of these hourglasses in the build graph. They make builds so slow.

**Comment by yaroslavvb** [comment]
I'm just going by the error message which say `@rpath/libcudart.8.0.dylib`, which I'm assuming means that `libcudart` is loaded by path relative to location in `DYLD_LIBRARY_PATH` which Apple thought was a security hazard. I guess I don't understand why cuda is being loaded then -- my understanding was that dynamic linking of cuda was a property of target configuration rather than a particular target to be included. IE, you if you build core:lib_internal without `--config=cuda` , there won't be any references to cuda runtime

**Comment by jart** [comment]
@gunan do we dllopen() cuda with a relative path?

**Comment by yaroslavvb** [comment]
Actually, maybe it's not an issue of SIP, but `LD_LIBRARY_PATH` environment getting lost during tool invocation:

Someone else hit similar issue and fixed it by modifying Bazel's genrule-setup.sh to add `LD_LIBRARY_PATH` in https://github.com/tensorflow/tensorflow/issues/4187#issuecomment-272656233

There's been a similar issue with tools getting called by Bazel not getting the environment propagated, and it was due to misconfiguration in CROSSTOOL file: https://github.com/tensorflow/tensorflow/issues/3261#issuecomment-234147379

**Comment by gunan** [comment]
For CUDA, I think we have an indirection setup by cuda_configure.bzl
@davidzchen @damienmg Could you take a look?
Looks like we are having quite a few issues with CUDA on macos.

**Comment by damienmg** [comment]
Have you tried to use `--action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARYPATH` flags? So those environment get shipped in the action?

**Comment by damienmg** [comment]
(side-note: there should be no update to the CROSSTOOL by end users, please tell us if some more things are needed to make build works everywhere).

**Comment by yaroslavvb** [comment]
BTW, I just hit this issue when building today's head on Mac and was able to get things building with @damienmg 's suggestion

export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib
export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
export PATH=$DYLD_LIBRARY_PATH:$PATH
export flags="--config=cuda --config=opt"
bazel build $flags --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARYPATH //tensorflow/tools/pip_package:build_pip_package &> ~/temp/bazel_output.txt

**Comment by drpngx** [comment]
Should we update our documentation then?

**Comment by yaroslavvb** [comment]
Maybe under common problems? https://www.tensorflow.org/get_started/os_setup#common_problems

Not 100% sure what those flags do. IE, it worked for `bazel build`, but not for `bazel test`, it fails with error which suggests env problems (work-around is to do `bazel test sometes` followed by `bazel-bin/.../sometest`)

**Comment by drpngx** [comment]
Thanks! Looping internally. `--config=opt` sets `-march=native` to get `-mavx` etc.

**Comment by gunan** [comment]
I think for macos build we can set these environment variables through our bazelrc.
So users wont need to manually set them.

**Comment by damienmg** [comment]
/cc @aehlig: Is it normal that action_env is not passed to test?

--action_env tell which environment variable to pass to compile action
--test_env tell which environment variable to set to test action

Default value for action_env is LD_LIBRARY_PATH and PATH, we do not put DYLD_LIBRARY_PATH by default. So if explicitely set from the command line you want to add PATH and LD_LIBRARY_PATH too.

From the help of Bazel exactly:
```
  --action_env (a 'name=value' assignment with an optional value part; may be used multiple times)
    Specifies the set of environment variables available available to actions. 
    Variables can be either specified by name, in which case the value will be 
    taken from the invocation environment, or by the name=value pair which sets 
    the value independent of the invocation environment. This option can be 
    used multiple times; for options given for the same variable, the latest 
    wins, options for different variables accumulate.
  --test_env (a 'name=value' assignment with an optional value part; may be used multiple times)
    Specifies additional environment variables to be injected into the test 
    runner environment. Variables can be either specified by name, in which 
    case its value will be read from the Bazel client environment, or by the 
    name=value pair. This option can be used multiple times to specify several 
    variables. Used only by the 'bazel test' command.
```

**Comment by martin-gorner** [comment]
I have the exact same problem, just running Tensorflow (not building it):
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

MacOS 10.12.2
Using an eGPU
DYLD_LIBRARY_PATH=:/usr/local/cuda/lib
ls -al /usr/local/cuda/lib/libcudart*
/usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
/usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
/usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a

Disabling SIP fixes this

**Comment by yaroslavvb** [comment]
To summarize for new users who find this:

On MacOS you need to do this:

1. Disable SIP (Security Integrity Protection)
2. Set environment variables point to your CUDA installation

ie, 
```
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib
export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
export PATH=$DYLD_LIBRARY_PATH:$PATH

```
Furthermore, if you are running TF through `bazel` as in `bazel test`, you need to make sure those env vars are propagated, by using `--action_env` flags

`bazel test $flags --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package`

**Comment by normanheckscher** [comment]
I have not disabled SIP on my current OSX install. I can compile TensorFlow from the head and release branches successfully.

**Comment by bradleygibson** [comment]
This solution also worked for me (OSX 10.12.3, TensorFlow-GPU 1.0.0, Python 3.6.)

Note that I had to remove a line from my `.bash_profile` which "activated pyenv" (removed `eval "$(pyenv init -)"`).  The fix presented here appeared to have no effect until this was done.

FYI disabling SIP does not appear to be necessary (ie. my SIP is **enabled**.)

```
Socrates:~ bRad$ python -c "import tensorflow as tf"
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.8.0.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.8.0.dylib locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.1.dylib. LD_LIBRARY_PATH: /usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib:/Developer/NVIDIA/CUDA-8.0/lib
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.dylib locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.8.0.dylib locally
```

Thanks, everyone.

**Comment by jason-riddle** [comment]
In my case, I am not allowed to disable SIP by the admin. From Apple's page on [Dynamic Libraries](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html), they note that the following.

> The standard locations for dynamic libraries are ~/lib, /usr/local/lib, and /usr/lib.

I didn't want to clutter /usr/local/lib or /usr/lib, so I moved my files to ~/lib.

```bash
cp -r /usr/local/cuda/lib ~/lib
```

and set

```bash
export DYLD_LIBRARY_PATH="${HOME}/lib:${DYLD_LIBRARY_PATH}"
```

and it seems to work fine.

**Comment by andreasgal** [comment]
This fixed the problem for me on mac: install_name_tool -add_rpath /usr/local/cuda/lib /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so

**Comment by vade** [comment]
Hi - just to mention I've had similar issues following the instructions for 1.0

I can confirm the following fixes all worked:



[x] Install_name_tool fix posted by @jason-riddle
[x] Stack Overflow posts linked by @normanheckscher worked
[x] @bradleygibson symlink fix (seems the easiest)

**Comment by gojira** [comment]
I just hit this building pip for 1.0 on 10.12.3 - anaconda python 3.5

This worked for me
✔︎ Stack Overflow posts linked by @normanheckscher worked

I know I had to do that a while back but haven't had to do it for a while.

Then toward the end I hit #7227 and had to revert to bazel 0.4.3.  And then it all worked.

**Comment by to-bee** [comment]
Adding path variables to .bash_profile as @yaroslavvb described worked

**Further steps I've done:**
disabling SIP on osx
don't forget to checkout tensorflow repo with all submodules:
`git clone --recurse-submodules https://github.com/tensorflow/tensorflow`

**Comment by gunan** [comment]
Looks like there were a few workarounds posted.
I am closing this issue, as we also dropped support for NVIDIA GPU support on MacOS.

**Comment by metakermit** [comment]
As mentioned in the other huge GH issue for build troubleshooting on Macs, I've published another slightly more up-to-date tutorial here:

https://metakermit.com/2017/compiling-tensorflow-with-gpu-support-on-a-macbook-pro/

(TensorFlow 1.3.0, CUDA 8.0 and cuDNN 6.0)
