### ISSUE TITLE
CUDA_ERROR_NO_DEVICE with Tesla K40c

### ISSUE THREAD

**Issue by Stephaninos** [tensorflow/tensorflow#684]
Hi,

I'm trying to use TF on a machine with 40 CPUs and 1 Tesla K40c. 

The machine is running openSUSE 13.2 and has CUDA 7 and cuDNN 6.5 installed.

**Problem**

When trying to run a simple test script

```
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print sess.run(hello)
a = tf.constant(10)
b = tf.constant(32)
print sess.run(a+b)
```

I get this output + the error "CUDA_ERROR_NO_DEVICE":

```
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 40
E tensorflow/stream_executor/cuda/cuda_driver.cc:481] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:114] retrieving CUDA diagnostic information for host: ml-login2
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: ml-login2
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported version is: 346.46
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  346.46  Tue Feb 17 17:56:08 PST 2015
GCC version:  gcc version 4.8.3 20140627 [gcc-4_8-branch revision 212064] (SUSE Linux) 
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported version is: 346.46
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:226] kernel version seems to match DSO: 346.46
I tensorflow/core/common_runtime/gpu/gpu_init.cc:127] DMA: 
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 40
Device mapping: no known devices.
I tensorflow/core/common_runtime/direct_session.cc:134] Device mapping:

Const: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:304] Const: /job:localhost/replica:0/task:0/cpu:0
Hello, TensorFlow!
Const_2: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:304] Const_2: /job:localhost/replica:0/task:0/cpu:0
Const_1: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:304] Const_1: /job:localhost/replica:0/task:0/cpu:0
add: /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:304] add: /job:localhost/replica:0/task:0/cpu:0
```

**What I've tried**
I've tried reinstalling the CUDA toolkit, installing TF from source, but all resulted in the same error. 
nvidia-smi properly finds the GPU and I can successfully run GPU computations through C code that depends on CUDA. It seems that somehow TF can't detect the GPU.

Is this a known issue with k40c GPUs and is there a fix?

Thanks!
-Stephan

**Comment by skearnes** [comment]
Does this crash your program? What is CUDA_VISIBLE_DEVICES set to? I get similar output when I set CUDA_VISIBLE_DEVICES=-1, but my program still runs. (I am also using a K40c).

**Comment by Stephaninos** [comment]
@skearnes Thanks so much! After adding the CUDA_VISIBLE_DEVICES=0 environment variable, TF now detects the GPU :).

**Comment by timsainb** [comment]
Where do you set CUDA_VISIBLE_DEVICES?

**Comment by jrimclean** [comment]
I'm having what appears to be the same problem. I get the error message:

> Device mapping: no known devices.
I tensorflow/core/common_runtime/direct_session.cc:175] Device mapping:

From running:

```python
import tensorflow as tf
# Creates a graph.
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print sess.run(c)
```

Setting CUDA_VISIBLE_DEVICES=0 did not solve it for me however. I have Python2.7, Cuda 7.5, and cuDNN v4 installed. I installed TensorFlow using pip.

**Comment by Sadrpour** [comment]
anybody found a solution for this ?

**Comment by rajiv235** [comment]
I am also having the same problem with CUDA,8.0 cuDNN v5.

**Comment by dmitry-xnor** [comment]
Same here. On Google Cloud, no less.

**Comment by tbchj** [comment]
also have the same question. but the differents is when i use gpu in docker container,will occur the question.  but on my linux environment, it's ok. thankyou

**Comment by dmitry-xnor** [comment]
@tbchj, the issue is probably that you need to use https://github.com/NVIDIA/nvidia-docker for GPU to work in Docker. You don't _have_ to use it, but then you'll basically have to replicate it, and that's no fun, so just use nvidia-docker.

**Comment by tbchj** [comment]
@dmitry-xnor   yeah, i had already installed nvidia-docker.  if container use gpu must according to  nvidia-docker ? because i used k8s, and the base of k8s  used  is  docker. now i run gpu on k8s   by using the way of  docker volumn (k8s  volumeMounts).  and it works. also needs nvidia-docker.  
now gpu works.    thank you

**Comment by dmitry-xnor** [comment]
From what I understand, k8s needs to be set up specifically to support GPUs. Try starting your container with nvidia-docker and see if that works, just to narrow down the root cause.

**Comment by tbchj** [comment]
@dmitry-xnor  enen, yes, k8s needs to be set up specifically to support GPUs. kubelet servicce has some parameters to set for gpu.
do you use this? k8s+docker+tensorflow

**Comment by dmitry-xnor** [comment]
No, in my case it's just docker+tensorflow. I would be interested in reading a HOWTO if you get this working, though. We do have a need for k8s, just not the time to investigate the details.

**Comment by tbchj** [comment]
now ,our team is building a platform using k8s,gpu,cpu,tensorflow  for training. it's simple, up to now, it  basically works well .   i will consider to write something  if  i'm not busy. haha
