### ISSUE TITLE
cudnn.h header not found on Ubuntu when using NVidia's CUDNN .debs

### ISSUE THREAD

**Issue by hawkinsp** [tensorflow/tensorflow#6850]
The official libcudnn5-dev package from NVidia (developers.nvidia.com), version 5.1.5-1+cuda-8.0, places the cudnn.h header at
`/usr/include/x86_64-linux-gnu/cudnn_v5.h`

but Tensorflow's config script looks for it at:
`/usr/lib/x86_64-linux-gnu/include/cudnn.h`

which means that running Tensorflow's `configure` script fails.

A workaround is to add a symlink:
```
sudo mkdir /usr/lib/x86_64-linux-gnu/include
sudo ln -s /usr/include/x86_64-linux-gnu/cudnn_v5.h /usr/lib/x86_64-linux-gnu/include/cudnn.h
```
after which Tensorflow's `configure` script completes successfully.

**Comment by jart** [comment]
@davidzchen would it be possible to make cuda_configure.bzl compatible with the NVidia Debian packages?

cc: @gunan

**Comment by gunan** [comment]
deb package for cudnn is new. We do handle this for CUDA deb packages, we probably need a very similar mechanism for cudnn.

**Comment by npanpaliya** [comment]
We are also facing the same issue on powerpc64le. Could anyone please let us know when can we get the fix for it?

**Comment by gunan** [comment]
Ping!
@davidzchen @damienmg 
how difficult would it be to add this functionality to cuda_configure.bzl?

**Comment by damienmg** [comment]
It would probably be a small change like 2 or 3 lines.

**Comment by gunan** [comment]
Another possible workaround:
@hawkinsp would it work if you add the path `/usr/lib/x86_64-linux-gnu` to your `LD_LIBRARY_PATH` ?

**Comment by hawkinsp** [comment]
@gunan Given the problem is finding the header file, not the .so libraries, I doubt setting LD_LIBRARY_PATH would help.

Note also that it's not just the path that is different, the header is called "cudnn_v5.h" not "cudnn.h".

This is a configuration we should support without needing workarounds (Ubuntu with NVidia's CUDA/CUDNN packages).

**Comment by hartb** [comment]
Submitted a pull request with a possible fix. Works for me on POWER Ubuntu with both tarball and deb package cuDNN installs.

**Comment by gunan** [comment]
In my tests, on ubuntu the installed package redirects the header to `/usr/local/cuda/include/cudnn.h` using `/etc/alternatives`.
Which specific OS are you running into this problem?

**Comment by hartb** [comment]
The OS is Ubuntu 16.04 for IBM POWER (ppc64le).  The cuDNN .deb packages are:

libcudnn5_5.1.5-1+cuda8.0_ppc64el.deb
libcudnn5-dev_5.1.5-1+cuda8.0_ppc64el.deb
libcudnn5-doc_5.1.5-1+cuda8.0_ppc64el.deb

The redirect with those packages doesn't involve /usr/local/cuda* at all:

/usr/include/cudnn.h -> /etc/alternatives/libcudnn -> /usr/include/powerpc64le-linux-gnu/cudnn_v5.h

And update-alternatives offers no other option.

**Comment by gunan** [comment]
I am not sure with the above link structure why we would have failures.
@hawkinsp could you confirm after #7151 issue is resolved?
Also, do you have the link through etc/alternatives as @hartb described (I can confirm that link structure gets built for me when I try in docker)

**Comment by hawkinsp** [comment]
Seems fixed for me at head. Closing.

I also have the the /usr/include/cudnn.h -> /etc/alternatives/libcudnn -> /usr/include/x86_64-linux-gnu/cudnn_v5.h symlink chain as @hartb described.

**Comment by kiariendegwa** [comment]
I don't think this is fixed with the newest tag 1.5.0-rc1, you've still gotta make the symbolic link before using bazel to build.

**Comment by PouriaCh** [comment]
I am new to linking. I got confused. I did several linking and I think I messed it up. Could anyone give me the exact commands for link chain of /usr/include/cudnn.h -> /etc/alternatives/libcudnn -> /usr/include/x86_64-linux-gnu/cudnn_v5.h?

**Comment by hartb** [comment]
@PouriaCh If you can use the .deb packages for the cuDNN install (available for cuDNN 5.1 at https://developer.nvidia.com/rdp/cudnn-archive) then I think the install process should create the links for you. You shouldn't have to do it by hand (and you'd probably want to remove any manually-created links before doing the .deb install).

With recent versions of TF, we've been using the cuDNN tarball install. That doesn't create any of those links.  We unpack the tarball so the cuDNN stuff lands under /usr/local/cuda:

`$ sudo tar -C /usr/local --no-same-owner -xvf cudnn...tgz`

And then inform TF build of the location during the configure step:

`CUDNN_INSTALL_PATH=/usr/local/cuda-x.y`

That's been working for us (on Power, rather than x86, but I think should be the same).
