### ISSUE TITLE
Tensorflow require Protobuf 3.1 while attempting to use incompatible 3.0 function calls

### ISSUE THREAD

**Issue by allannk** [tensorflow/tensorflow#6875]
**Environment:**
Arch Linux with CUDA 8.0 and cuDNN 5.1

```
/opt/cuda/lib64/libcudadevrt.a
/opt/cuda/lib64/libcudart.so -> libcudart.so.8.0
/opt/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
/opt/cuda/lib64/libcudart.so.8.0.44
/opt/cuda/lib64/libcudart_static.a
/opt/cuda/lib64/libcudnn.so -> libcudnn.so.5
/opt/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
/opt/cuda/lib64/libcudnn.so.5.0.5
/opt/cuda/lib64/libcudnn.so.5.1.5
/opt/cuda/lib64/libcudnn_static.a
```

Tensorflow was succesfully compiled from source for a C++ pipeline using
**Bazel** 0.4.3
**Protobuf** 3.1.x (also tried 3.2.x)
**Tensorflow** r1.0 (as well as master <9830ed87d46245a72a9d0c2dce854e6732c5542a>)

with the command: 
`bazel build -c opt --config=cuda --copt=-march=native --verbose_failures //tensorflow/core:tensorflow //tensorflow/cc:cc_ops tensorflow:libtensorflow_cc.so`

In _my_ CPP pipeline, the following include breaks the compile process
`#include <tensorflow/core/public/session.h>`

```
/srv/builds/tensorflow/bazel-genfiles/tensorflow/core/protobuf/config.pb.h:1490:95: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::Get(const string*) const’
 return visible_device_list_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                                                                                             ^
In file included from /srv/builds/tensorflow/bazel-genfiles/tensorflow/core/framework/graph.pb.h:23:0,
                 from /srv/builds/tensorflow/tensorflow/core/public/session.h:22,
                 from src/fragments/tensorflow.h:48,
                 from src/blocks/detector.h:27,
                 from src/json_deserializer.h:22,
                 from src/blocks/assign_camera.cpp:2:
/usr/include/google/protobuf/arenastring.h:66:31: note: candidate: const string& google::protobuf::internal::ArenaStringPtr::Get() const
   inline const ::std::string& Get() const { return *ptr_; }
                               ^~~
/usr/include/google/protobuf/arenastring.h:66:31: note:   candidate expects 0 arguments, 1 provided
```

----------------------------------------------

Digging in the documentation, I see for the python part that Protobuf 3.1.x is required, however 3.1.x had an API change from 3.0.X for the ArenaStringPtr::Get(), where the former takes a string as argument while the newer doesn't. I could downgrade to Protobuf 3.0.X, but macro's in e.g. error_codes.pb.h specifies a requirement for 3.1.X `#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION`

**Comment by allannk** [comment]
Just now, I had success compiling Tensorflow r0.12 (and presumably also r1.0, although it remain untested). 

For others that might have these issues, the problem is indeed related to protobuf versioning, and inspecting the bazel-genfiles external parts, I figured that tensorflow is pulling an unnamed branch of Protobuf that doesn't have the problems described above. Installing 3.0.x, 3.1.x or even 3.2.x will not work, only the one in `~/.cache/bazel/_bazel_allan/83...59/external/protobuf` will work. Compiling from this folder did the trick.

**Comment by samhodge** [comment]
Thank you for putting up this response to your own issue, you may have just saved me several hours of head scratching.
