### ISSUE TITLE
TensorFlow is not detecting the GPU, whereas PyTorch is successfully identifying it.

### ISSUE THREAD

**Issue by buttaRahul** [tensorflow/tensorflow#70845]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### Python version

3.11

### CUDA/cuDNN version

CUDA version: 11.8, cuDNN version: 8.7.0.0

### GPU model and memory

NVIDIA GeForce RTX 4060,  8188MiB

### Current behavior?

tensorflow unable to detect GPU, 

### Standalone code to reproduce the issue

```shell
tf.config.list_physical_devices()
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
Using device: cuda
```

**Comment by sushreebarsa** [comment]
@buttaRahul I was able to detect the GPU in Google colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/3ee5f24e7acfdcd8c21c83e0b92a85bc/70845.ipynb).
Thank you!

**Comment by FrejaThoresen** [comment]
I have the same issue on my device with cuDNN 9 (also tested with version 8.7), CUDA 12.3 and tensorflow 2.16.1. Installation works fine with pytorch, but tensorflow can not detect the GPU. 

I see that the installation with pip is installing nvidia libraries, including some related to cuDNN, which may not have the same version as the one installed on the device, could this be a lead?

**Comment by sushreebarsa** [comment]
@buttaRahul  Could you please verify if your system recognizes the GPU using the NVIDIA System Management Interface:

```
nvidia-smi
```
Please ensure that CUDA is correctly installed and the paths are set correctly:
```
nvcc --version

```
also verify the cudnn version:
```
cat /usr/local/cuda/include/cudnn_version.h | grep CUDNN_MAJOR -A 2

```

```
pip uninstall tensorflow tensorflow-gpu
pip install tensorflow==2.14.0
```
then install TF GPU and let us know?

@FrejaThoresen Yes, the installation of NVIDIA libraries via pip that differ from your system's installed versions of CUDA and cuDNN could be causing conflicts. This is a common issue when there are mismatched versions. Please refer [TensorFlow compatibility guide](https://www.tensorflow.org/install/source#gpu) for the same. 
Thank you!

**Comment by mihaimaruseac** [comment]
Please use TF 2.17, see #63362

**Comment by FrejaThoresen** [comment]
I can confirm it works with Python 3.12, Tensorflow 2.17, Cuda 12.3, and cuDNN 8.9.7. I suspect the issue was caused by a mismatch between the pip versions of Nvidia cudnn installations and the cuDNN installation.

Tensorflow finding the GPU
```
>> python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2024-07-24 15:06:12.214574: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-24 15:06:12.223961: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-24 15:06:12.226778: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-24 15:06:12.233782: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-24 15:06:12.794225: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721826373.167169  141358 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1721826373.187865  141358 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1721826373.188006  141358 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
(tf_py12) freya@agora-linux-ai:~/Documents/Code/thin-slice-classifier$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```

cuDNN version
```
>> cat /usr/include/x86_64-linux-gnu/cudnn_v*.h | 
grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 9
#define CUDNN_PATCHLEVEL 7
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

/* cannot use constexpr here since this is a C-only file */
```

pip nvidia libraries
```
>> pip list | grep nvidia
nvidia-cublas-cu12       12.3.4.1
nvidia-cuda-cupti-cu12   12.3.101
nvidia-cuda-nvcc-cu12    12.3.107
nvidia-cuda-nvrtc-cu12   12.3.107
nvidia-cuda-runtime-cu12 12.3.101
nvidia-cudnn-cu12        8.9.7.29
nvidia-cufft-cu12        11.0.12.1
nvidia-curand-cu12       10.3.4.107
nvidia-cusolver-cu12     11.5.4.101
nvidia-cusparse-cu12     12.2.0.103
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.3.101
```

pip tensorflow
```
pip list | grep tensor
tensorboard              2.17.0
tensorboard-data-server  0.7.2
tensorflow               2.17.0
```

Driver version
```
>> nvidia-smi
Wed Jul 24 15:11:31 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 ...    On  |   00000000:01:00.0  On |                  N/A |
| 29%   31C    P8              6W /  125W |     126MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1255      G   /usr/lib/xorg/Xorg                            116MiB |
|    0   N/A  N/A      1303      G   /usr/bin/gnome-shell                            6MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by mihaimaruseac** [comment]
Since it works on 2.17, moving towards closing this issue. Thank you @FrejaThoresen

**Comment by tharun571** [comment]
For anyone else encountering "PyTorch works but TensorFlow doesn't detect GPU" - this is a classic framework-specific CUDA compatibility issue.

Common causes:
1. **Different CUDA requirements**: TensorFlow 2.14 needs CUDA 11.8, while PyTorch 2.x supports CUDA 11.8-12.x
2. **cuDNN version differences**: Each framework has specific cuDNN dependencies
3. **LD_LIBRARY_PATH conflicts**: PyTorch might find CUDA libs that TensorFlow can't

Quick debug:
```python
# Check what CUDA version TF was built with:
import tensorflow as tf
print(tf.sysconfig.get_build_info())

# vs PyTorch:
import torch
print(torch.version.cuda)
```

I built a cross-framework compatibility checker: **[env-doctor](https://github.com/mitulgarg/env-doctor)**

It validates BOTH PyTorch AND TensorFlow against your driver/CUDA setup simultaneously, showing:
- Why one framework detects GPU but the other doesn't
- Which CUDA/cuDNN versions each framework needs
- Exact pip install commands for both frameworks that match YOUR driver

Full disclosure: I'm the author. Sharing because this "one works, one doesn't" scenario is exactly what it diagnoses. Hope it helps future readers!

**Comment by mihaimaruseac** [comment]
See also, #106653

**Comment by buttaRahul** [comment]
> For anyone else encountering "PyTorch works but TensorFlow doesn't detect GPU" - this is a classic framework-specific CUDA compatibility issue.
> 
> Common causes:
> 
> 1. **Different CUDA requirements**: TensorFlow 2.14 needs CUDA 11.8, while PyTorch 2.x supports CUDA 11.8-12.x
> 2. **cuDNN version differences**: Each framework has specific cuDNN dependencies
> 3. **LD_LIBRARY_PATH conflicts**: PyTorch might find CUDA libs that TensorFlow can't
> 
> Quick debug:
> 
> # Check what CUDA version TF was built with:
> import tensorflow as tf
> print(tf.sysconfig.get_build_info())
> 
> # vs PyTorch:
> import torch
> print(torch.version.cuda)
> I built a cross-framework compatibility checker: **[env-doctor](https://github.com/mitulgarg/env-doctor)**
> 
> It validates BOTH PyTorch AND TensorFlow against your driver/CUDA setup simultaneously, showing:
> 
> * Why one framework detects GPU but the other doesn't
> * Which CUDA/cuDNN versions each framework needs
> * Exact pip install commands for both frameworks that match YOUR driver
> 
> Full disclosure: I'm the author. Sharing because this "one works, one doesn't" scenario is exactly what it diagnoses. Hope it helps future readers!

Just quoting this since it might help future readers.

I’ve personally run into a lot of CUDA / cuDNN mismatch issues earlier.

In addition to the above comments, it’s always a good idea to refer to the latest official documentation, since CUDA/cuDNN compatibility changes quite often:
https://www.tensorflow.org/install/source#gpu
@tharun571 
Thanks for sharing about env-doctor will definitely keep it in mind the next time I run into similar issues.
