### ISSUE TITLE
failed to query current context: CUDA_ERROR_DEINITIALIZED

### ISSUE THREAD

**Issue by wchan** [tensorflow/tensorflow#713]
This is a regression problem, code was working fine 2 wks ago, did a git sync to the head and now I have this log message:

I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:103] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:02:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:127] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:137] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:705] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Allocating 11.27GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:52] GPU 0 memory begins at 0x2306c80000 extends to 0x25d8436a67
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 16.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 32.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 64.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 128.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 256.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 512.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 8.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 16.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 32.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 64.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 128.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 256.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 512.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 8.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 16.00GiB
create_encoder graph time 0.569116
create_decoder graph time 2.629546
create_loss graph time 0.960969
create_optimizer graph time 34.311540
F tensorflow/stream_executor/cuda/cuda_driver.cc:299] failed to query current context: CUDA_ERROR_DEINITIALIZED
F tensorflow/stream_executor/cuda/cuda_driver.cc:299] failed to query current context: CUDA_ERROR_DEINITIALIZED
F tensorflow/stream_executor/cuda/cuda_driver.cc:299] failed to query current context: CUDA_ERROR_DEINITIALIZED
F tensorflow/stream_executor/cuda/cuda_driver.cc:408] Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(prior_context_) (0 vs. 4)
Aborted (core dumped)

Note: (the create_*) is my code creating the graph.
The python code it crashes on is:
sess.run(tf.initialize_all_variables())

**Comment by alexatknit** [comment]
I've got the same issue

**Comment by vrv** [comment]
I have a suspicion that our mega-commit 1c579361cd1e088dd5e05a394b1561a73e3667ba might have introduced a change that broke this (there are a bunch of changes that could be responsible, including changes to the stream executor and updating to a new version of Eigen, among other things).

It would be great if someone could confirm if it works at 295625035eefc7801cfe831bd1ba851faacb7579 but fails at the commit right after.

**Comment by skearnes** [comment]
@vrv 2956250 works for me; 1c57936 does not.

**Comment by vrv** [comment]
Cool, thanks for verifying.  If you have time:

Revert the WORKSPACE file and eigen.BUILD changes (to use an earlier version of Eigen) and see if the problem goes away.

I'll dig into potential other issues in that commit.

**Comment by skearnes** [comment]
Checking out WORKSPACE and eigen.BUILD from 2956250 does not fix the problem.

**Comment by vrv** [comment]
Ok thanks, that helps.

**Comment by vrv** [comment]
@zheng-xq, who independently was trying to debug this.

**Comment by alexatknit** [comment]
I reverted to 2956250 and it seems to work, but the execution speed is cut in half

**Comment by vrv** [comment]
Yup, that commit improved speed for some models, @zheng-xq is looking into what broke it.

**Comment by zheng-xq** [comment]
I can confirm that with eigen-a0661a2bb165, an Eigen kernel fails to
launch. But with the older eigen-ce5a455b34c0, this problem goes away.

My reproducing command line:

bazel run -c opt --config=cuda
//tensorflow/models/image/alexnet:alexnet_benchmark

Passing to @benoitsteiner

**Comment by vrv** [comment]
@zheng-xq: what eigen kernel failed, so we can figure out which kernel was the problem?

**Comment by zheng-xq** [comment]
The kernel that was causing problem is:

EigenMetaKernel_Vectorizable<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float,
1, 1, int>, 16>,
Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_right<float, float,
Eigen::internal::scalar_product_op<float, float>, true>,
Eigen::TensorMap<Eigen::Tensor<float const, 1, 1, int>, 16> const> const>
const, Eigen::GpuDevice>, int>

It came from cwise_mul:

tensorflow::BinaryOp<Eigen::GpuDevice, tensorflow::functor::mul<float> >

**Comment by benoitsteiner** [comment]
When running "bazel-bin/tensorflow/models/image/alexnet/alexnet_benchmark --benchmarks=all" on my machine, I get the following error:
external/re2/re2/regexp.cc:136: Bad reference count 65535
F tensorflow/stream_executor/cuda/cuda_driver.cc:408] Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(prior_context_) (0 vs. 4)

**Comment by vrv** [comment]
Okay, we rolled back the change to switch to the newer version of Eigen, which apparently had some issues.  https://github.com/tensorflow/tensorflow/commit/22267addd64b00f9457605cdce3d82276a478780

So things should be now be working.

However, this uses an older version of Eigen that has some speed problems.

@benoitsteiner has upstreamed a newer fix to Eigen which should bring back the speed improvements *and* not crash things, so look for that soon.

Closing this for now, let us know if you still see problems.

**Comment by jeremybarnes** [comment]
FWIW, I spent some time independently debugging this issue as well.   What I found was that the preprocessor magic in Eigen was removing nvcc's ability to know what templated kernels to instantiate for the device code.  The fix for the non-convolutional kernels was to modify the `eigen/unsupported/CXX11/src/tensor/TensorDeviceCuda.h` file and modify the LAUNCH_CUDA_KERNEL macro for the device code to force instantiation of the kernel:

```
#ifndef __CUDA_ARCH__
#define LAUNCH_CUDA_KERNEL(kernel, gridsize, blocksize, sharedmem, device, ...)            \
    (kernel) <<< (gridsize), (blocksize), (sharedmem), (device).stream() >>> (__VA_ARGS__); \
    assert(cudaGetLastError() == cudaSuccess);
#else
#define LAUNCH_CUDA_KERNEL(...)  \
    { static const auto __attribute__((__unused__)) __makeTheKernelInstantiate = &(kernel); } \
   eigen_assert(false && "Cannot launch a kernel from another kernel" __CUDA_ARCH__);
#endif
```
