### ISSUE TITLE
failed to enqueue convolution on stream: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by SeveQ** [tensorflow/tensorflow#734]
Hi guys,

I'm just trying to run the Deep MNIST example on my GeForce GTX 980Ti (it worked on the CPU) but am getting the above mentioned error message during the training phase. Can anyone point me to the right direction what might be wrong?

Here's what `ipython notebook` outputs on my Ubuntu 14.04 system with CUDA 7.0, cuDNN 6.5 and NVIDIA drivers version 352.39 (linux-x86_64): http://pastebin.com/f4y3c9CH

Thanks

**Comment by SeveQ** [comment]
Seems this was related to an incorrectly configured LD_LIBRARY_PATH variable. Now it works. Well, kind of...

**Comment by qixianbiao** [comment]
Hello, I have the same problem, can you please point out how you solved this issue?

**Comment by SeveQ** [comment]
I rebooted my PC. Seems there were some env variables screwed up that have been reset after rebooting. 

I think, the important variables are LD_LIBRARY_PATH which should contain the path to your libcudaxyz.so files and PATH which should contain the path to the nvcc binary. See also there: http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-linux/#environment-setup

I hope this helps...

**Comment by JeremyCCHsu** [comment]
I have the same problem, and I can't solve it even after your I followed your suggestion.
Tensorflow actually runs, if no CNN modules are used.
(but without CNN, what's the point to use Tensorflow?)

==== Commands & Error Mesages ====
~$ python /usr/local/lib/python2.7/dist-packages/tensorflow/models/image/cifar10/cifar10_train.py

...
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:73] Allocating 11.27GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:83] GPU 0 memory begins at 0x1306d40000 extends to 0x15d8484a67
F tensorflow/stream_executor/cuda/cuda_dnn.cc:828] failed to enqueue convolution on stream: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

**Comment by bbrumpom** [comment]
I have a similar error message, in my case I am able to train let say model A, and the only thing I change in model B are sizes of convolution filters and pooling windows. I am wondering if it can be caused because the matrix operations are too computionally expensive? The error message:
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Quadro K2000
major: 3 minor: 0 memoryClockRate (GHz) 0.954
pciBusID 0000:01:00.0
Total memory: 1.94GiB
Free memory: 1.83GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K2000, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1110] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_TIMEOUT
E tensorflow/stream_executor/cuda/cuda_timer.cc:54] Internal: error destroying CUDA event in context 0x2f838f0: CUDA_ERROR_LAUNCH_TIMEOUT
E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0x2f838f0: CUDA_ERROR_LAUNCH_TIMEOUT
F tensorflow/stream_executor/cuda/cuda_dnn.cc:1251] failed to enqueue convolution on stream: CUDNN_STATUS_EXECUTION_FAILED
Aborted (core dumped)

**Comment by liuhyCV** [comment]
@joaanna have you solve your problem? I have the same error with you

**Comment by weiliu620** [comment]
I have the same error if my input image size is too large for a convnet model. So it might be related to the out of memory issue.

**Comment by lauphedo** [comment]
Try reducing your batch size, image size,... anything that reduces needed remory. This will avoid running out of memory (including this error message).

**Comment by fastlater** [comment]
@lauphedo  so what you mean is cudnn_status_mapping_error is related to memory too? I have been having this error for a couple of days even when I followed instructions from different webpages and still get the error. I am using a Nvidia Quadro K2000 2GB of memory.

**Comment by lauphedo** [comment]
@fastlater: Yes, in my experience it is related to the running-out-of-memory issue. It seems that weiliu620 made the same experience. 
What kind of images do you use? What's your batch size?

**Comment by fastlater** [comment]
@lauphedo  Well, in my case, I guess it is because problems with cuda installation. I was testing a code with the same image used in their demo. Then, I tried one of my old codes and the same error came out so it should be something else and not a memory issue. I hope I could solve this problem soon and report the solution.
