### ISSUE TITLE
The outputs of conv1d differs significantly on the CPU and GPU

### ISSUE THREAD

**Issue by PhyllisJi** [tensorflow/tensorflow#74785]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.12.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.10

### Current behavior?

When conv1d used the same parameter settings, we gave the same input and found the largest difference in the output tensor 0.178863525390625.

### Standalone code to reproduce the issue

```shell
import h5py
import tensorflow as tf
import numpy as np

tf.random.set_seed(42)

def chebyshev_distance(A: np.ndarray, B: np.ndarray):
    if A is None or B is None:
        return 0.0
    if A.shape != B.shape:
        return 9999999
    else:
        return float(np.max(np.abs(A - B)))

h5_file_path = "./output_diff_initial_weights.h5"
npz_path = "./output_diff_input.npz"
conv1d_layer = tf.keras.layers.Conv1D(filters=64, kernel_size=7, padding="valid")
layer_name = 'conv1d_2351'

data = np.load(npz_path)
inp = data['inp']
input_shape = inp.shape[1:]

with h5py.File(h5_file_path, 'r') as h5_file:
    weights = h5_file[f'{layer_name}/{layer_name}/kernel:0'][:]
    biases = h5_file[f'{layer_name}/{layer_name}/bias:0'][:]
    

conv1d_layer.build(input_shape)
conv1d_layer.set_weights([weights, biases])


with tf.device('/CPU:0'):
    x_cpu = tf.constant(inp, dtype=tf.float32)
    output_cpu = conv1d_layer(x_cpu)


if tf.config.list_physical_devices('GPU'):
    with tf.device('/GPU:0'):
        x_gpu = tf.constant(inp, dtype=tf.float32)
        output_gpu = conv1d_layer(x_gpu)

else:
    print("GPU not available.")
    
output_diff = chebyshev_distance(output_cpu.numpy(), output_gpu.numpy())
print(output_diff)
```
https://github.com/PhyllisJi/MoCoDiff_Bug/tree/tf-issue-%2374785
This repository provides the inputs and weights.Just type python conv1d_test.py.

**Comment by rahulsamant37** [comment]
To address the issue with the observed discrepancy between CPU and GPU outputs in your Conv1D layer
1-Ensure that both CPU and GPU are using the same floating-point precision.
```
x_cpu = tf.constant(inp, dtype=tf.float32)
x_gpu = tf.constant(inp, dtype=tf.float32)
```
2-Enable deterministic operations for TensorFlow on GPU.
```
tf.config.experimental.enable_op_determinism()
```
3-Double-check your environment consistency (CUDA, cuDNN, TensorFlow versions).

also, You've already mentioned trying TensorFlow Nightly, but if you're still using an older version on your main environment, upgrading to the latest stable version could potentially fix issues related to discrepancies between CPU and GPU computations.
By taking these steps, you should be able to identify and potentially resolve the discrepancy you're observing.

Let me know if any of these solutions work for you!

**Comment by PhyllisJi** [comment]
> To address the issue with the observed discrepancy between CPU and GPU outputs in your Conv1D layer 1-Ensure that both CPU and GPU are using the same floating-point precision.
> 
> ```
> x_cpu = tf.constant(inp, dtype=tf.float32)
> x_gpu = tf.constant(inp, dtype=tf.float32)
> ```
> 
> 2-Enable deterministic operations for TensorFlow on GPU.
> 
> ```
> tf.config.experimental.enable_op_determinism()
> ```
> 
> 3-Double-check your environment consistency (CUDA, cuDNN, TensorFlow versions).
> 
> also, You've already mentioned trying TensorFlow Nightly, but if you're still using an older version on your main environment, upgrading to the latest stable version could potentially fix issues related to discrepancies between CPU and GPU computations. By taking these steps, you should be able to identify and potentially resolve the discrepancy you're observing.
> 
> Let me know if any of these solutions work for you!

Step 2 solved my problem!
