### ISSUE TITLE
GPU: no known devices, despite cuda's deviceQuery returning a "PASS" result

### ISSUE THREAD

**Issue by oelmekki** [tensorflow/tensorflow#7648]
Hi guys,

Sorry, I know there's already been tons of GPU related issues, but I could not find any that seems to be related to my problem.

The main symptom: when running tensorflow, my gpu is not detected ([the code being run](https://gist.github.com/oelmekki/cafda411bf5c2ea695d984fa98e0995b), and [its output](https://gist.github.com/oelmekki/77235c6b0dde99b3438f190eb557f40f)).

What differs from usual issues is that cuda seems properly installed and running `./deviceQuery` from cuda samples is successful ([output](https://gist.github.com/oelmekki/fe65a15daec45aa90ec33b10b51d3aae)).

I have two graphical cards:

* an old GTX 650 used for my monitors (I don't want to use that one with tensorflow)
* a GTX 1060 that I want to dedicate to tensorflow

I use:

* [tensorflow-1.0.0](https://pypi.python.org/pypi/tensorflow)
* cuda-8.0 ([ls -l /usr/local/cuda/lib64/libcud*](https://gist.github.com/oelmekki/6e5e9d7d1ea871e1d73efae307efe9ce))
* cudnn-5.1.10
* python-2.7.12
* nvidia-drivers-375.26 (this was installed by cuda and replaced my distro driver package)

I've tried:

* adding `/usr/local/cuda/bin/` to `$PATH`
* forcing gpu placement in tensorflow script using `with tf.device('/gpu:1'):` (and `with tf.device('/gpu:0'):` when it failed, for good measure)
* whitelisting the gpu I wanted to use with `CUDA_VISIBLE_DEVICES`, in case the presence of my old unsupported card did cause problems
* running the script with sudo (because why not)

Here are the outputs of [nvidia-smi](https://gist.github.com/oelmekki/7bdcb5cc2f791cea561a60f8b21e87b5) and [nvidia-debugdump -l](https://gist.github.com/oelmekki/b83a5a0a72e8924aeb44b70b3598f9b4), in case it's useful.

At this point, I feel like I have followed all the breadcrumbs and have no idea what I could try else. I'm not even sure if I'm contemplating a bug or a configuration problem. Any advice about how to debug this would be greatly appreciated. Thanks!

**Comment by yaroslavvb** [comment]
As a shot in the dark, maybe try TF 1.0 and look at output of verbose logging

`export TF_CPP_MIN_LOG_LEVEL=1`

There's also `export TF_CPP_MIN_LOG_LEVEL=2` but that can be 100's of MBs of output

**Comment by vrv** [comment]
This is a question that should be posted on StackOverflow -- can you post it there and link us?

**Comment by oelmekki** [comment]
Sure, I asked it here : http://stackoverflow.com/questions/42326748/tensorflow-on-gpu-no-known-devices-despite-cudas-devicequery-returning-a-pas

**Comment by oelmekki** [comment]
@yaroslavvb Thanks for the tip!

Actually, using this does not provide any more info than not using it:

```
$ TF_CPP_MIN_LOG_LEVEL=1 python gpu.py
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Device mapping: no known devices.
MatMul: (MatMul): /job:localhost/replica:0/task:0/cpu:0
b: (Const): /job:localhost/replica:0/task:0/cpu:0
a: (Const): /job:localhost/replica:0/task:0/cpu:0
[[ 22.  28.]
 [ 49.  64.]]
```

(I've also tried to export the variable globally just in case, but it produces the same result)

Funny enough, setting log_level to 2 actually produces a lesser amount of output:

```
$ TF_CPP_MIN_LOG_LEVEL=2 python gpu.py
Device mapping: no known devices.
MatMul: (MatMul): /job:localhost/replica:0/task:0/cpu:0
b: (Const): /job:localhost/replica:0/task:0/cpu:0
a: (Const): /job:localhost/replica:0/task:0/cpu:0
[[ 22.  28.]
 [ 49.  64.]]
```

**Comment by yaroslavvb** [comment]
@oelmekki debug logging was added recently, can you try this with TF 1.0?

**Comment by oelmekki** [comment]
This is already what I'm using, actually :)

```
$ python -c "import tensorflow; print(tensorflow.__version__)"
1.0.0
```

**Comment by yaroslavvb** [comment]
Sorry, it's TF_CPP_MIN_VLOG_LEVEL not TF_CPP_MIN_LOG_LEVEL (there's also TF_CPP_MIN_LOG_LEVEL which will disable TF_CPP_MIN_VLOG_LEVEL if set)

**Comment by oelmekki** [comment]
Great, thanks, I have a lot more of debugging info indeed :+1: 

Since Vijay mentioned this should be discussed on SO instead, I won't paste it here, but let me know if you want to look at it at any point.

Thanks for help!

**Comment by collawolley** [comment]
hi @oelmekki @yaroslavvb did you managed to resolve the issue?
I have the same problem able to use GPU before updating tensorflow to V1.3.0. I have also upgraded my Cudnn to V6. My CUDA is v8.0 so I don't seem to understand where the problem is coming from. I can verify that my tensorflow is GPU version because I used tfBInaryUrl for Python2.7-PGU support. Aside this, I have also installed several times with 'pip install tensorflow-gpu' and I still cannot run my codes on gpu. Theano works fine and I could run code with GPU if I use theano. 

When I tried to force the computation to be run on GPU , my codes wouldn't run and now, I got this mesage "Device mapping: no known devices.

The frustrating thing is that I was using the GPU before I upgraded to v1.3.0/

I would appreciate any help as regards this problem.
"

**Comment by oelmekki** [comment]
Hi @collawolley,

Indeed, it was solved for me : the problem was that there's a different lib to install for using gpu, `tensorflow-gpu` instead of `tensorflow` ( more info here : https://stackoverflow.com/questions/42326748/tensorflow-on-gpu-no-known-devices-despite-cudas-devicequery-returning-a-pas ).

That being said, it's been a while since I haven't used tensorflow (I used it to generate word embedding, but now there are a lot already available), so I can't say for sure if this answer is still relevant.

Best wishes!

**Comment by olalonde** [comment]
I had same issue and `pip install tensorflow-gpu` fixed it for me as well.

**Comment by pGit1** [comment]
pip install tensorflow-gpu wont work for me. Im doing pip install tensorflow-gpu==1.4 since when i do pip install tensorflow-gpu i get this cannot find lib cublas 9.0 error.

**Comment by ahsteven** [comment]
I am now having the same problem. It was working. I am not sure what broke it. I did app-get update and apt get upgrade today. There was some nvidia stuff in those upgrades. I have also been using conda environments. Now no version of tf I have, either native or conda env is able to find the GPU.

I am using GTX 1070
Ubuntu 16.04
Python 3.5
tf 1.5.0
Cuda 9.1
cudnn 7.0.5

**Comment by JGSweets** [comment]
Similar issue, tf-gpu detects properly with python 3 while python 2 tf-gpu doesn't detect GPUS.

This seems to be localized to python 2 versions of TF-GPU
