### ISSUE TITLE
failed call to cuInit: CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by essamgoda** [tensorflow/tensorflow#7653]
when i run tensorflow gpu my gpy is gt 620m 
linux mint 18.1
```
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: essam-goda
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: essam-goda
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 340.101.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  340.101  Thu Dec  1 15:52:31 PST 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 340.101.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 340.101.0
```

**Comment by aselle** [comment]
Could you google search this error and try to follow some of the advice. For example, this error appears here
https://github.com/tensorflow/tensorflow/issues/2882
1. One thing is you could have no permissions to run on the GPU as a user (you could try sudo)
2. Make sure nvidia-smi works
3. try some of the  cuda demos and make sure they work to narrow it down from being just a GPU install/configure problem

Good Luck!

**Comment by gangadhar-p** [comment]
I am having the same exact issue since upgrading to Tensorflow 1.0 


`E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: gangadhar-All-Series
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: gangadhar-All-Series
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 367.57.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  `

**Comment by gangadhar-p** [comment]
Issue resolved after Ubuntu restart. I installed updates and was pending a restart, after the restart GPU was detected.

**Comment by essamgoda** [comment]
@aselle 
when run nvidia-smi result is 
 
```
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
```

**Comment by aselle** [comment]
@essamgoda that sounds like cuda isn't installed quite right. Try doing what it says, otherwise searching for methods of reinstalling nvidia drivers (sometimes you have to work pretty hard to remove remaining parts of cuda if you have used a mix of manual and automatic methods).

**Comment by essamgoda** [comment]
@aselle  i uninstall nvidia driver and cuda and tensorflow-gpu (via pip)  and install again

try to install from source code (to write GPU card with CUDA Compute Capability of my driver) show error in build

result 
```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: essam-goda
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: essam-goda
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 375.39.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.39  Tue Jan 31 20:47:00 PST 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

```

nvidia-smi result is
```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 620M     Off  | 0000:01:00.0     N/A |                  N/A |
| N/A   36C    P8    N/A /  N/A |    205MiB /   964MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

```

**Comment by essamgoda** [comment]
@aselle   i uninstall nvidia driver and cuda and tensorflow-gpu (via pip) and install again

try to install from source code (to write GPU card with CUDA Compute Capability of my driver) show error in build

when i run 
```

I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GT 620M
major: 2 minor: 1 memoryClockRate (GHz) 1.25
pciBusID 0000:01:00.0
Total memory: 964.44MiB
Free memory: 756.19MiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:948] Ignoring visible gpu device (device: 0, name: GeForce GT 620M, pci bus id: 0000:01:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.0.
```

can i change configuration to 2.1 ? or my drive will not work ever ?

**Comment by aselle** [comment]
You could try compiling from source with compute capability 2.1 specified as the required version. However, I believe from this stackoverflow post, you need at least compute capability 3.0 to use cudnn.
http://stackoverflow.com/questions/33760192/how-to-know-which-cudnn-version-one-should-use
@zheng-xq, can you verify that tensorflow requires at least 3.0?

**Comment by zheng-xq** [comment]
Yes. The minimum version that is officially supported is 3.0.

**Comment by aselle** [comment]
Thanks @zheng-xq. Closing the issue since this won't be something that can work.

**Comment by abhigenie92** [comment]
@aselle Hi, is there any alternative to make it work without running it as root?

```
nvidia-smi
Mon Aug 14 07:26:58 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.82                 Driver Version: 375.82                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P400         Off  | 0000:01:00.0      On |                  N/A |
| 34%   46C    P8    12W /  N/A |    116MiB /  1990MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40c          Off  | 0000:03:00.0     Off |                    0 |
| 27%   50C    P8    21W / 235W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40c          Off  | 0000:04:00.0     Off |                    0 |
| 28%   55C    P8    30W / 235W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2165    G   /usr/lib/xorg/Xorg                              60MiB |
|    0      2271    G   gnome-shell                                     54MiB |
+-----------------------------------------------------------------------------+
```

Without sudo:
Please note:
`2017-08-14 07:28:29.379866: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
````
python simple_mlp_tensorflow.py
2017-08-14 07:28:29.374191: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:28:29.374211: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:28:29.374216: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:28:29.374219: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:28:29.374222: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:28:29.379866: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2017-08-14 07:28:29.379893: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: gonzo
2017-08-14 07:28:29.379898: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: gonzo
2017-08-14 07:28:29.379919: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 375.82.0
2017-08-14 07:28:29.379936: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.82  Wed Jul 19 21:16:49 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
"""
2017-08-14 07:28:29.379948: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.82.0
2017-08-14 07:28:29.379953: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 375.82.0

```
As root with sudo:
```
sudo /nohome/jaan/abhishek/anaconda3/bin/python simple_mlp_tensorflow.py
2017-08-14 07:27:35.067365: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:27:35.067388: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:27:35.067392: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:27:35.067395: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:27:35.067398: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-08-14 07:27:35.294553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:03:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
2017-08-14 07:27:35.479863: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x16b60d0 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-08-14 07:27:35.480328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 1 with properties:
name: Quadro P400
major: 6 minor: 1 memoryClockRate (GHz) 1.2525
pciBusID 0000:01:00.0
Total memory: 1.94GiB
Free memory: 1.80GiB
2017-08-14 07:27:35.660972: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x130fb80 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-08-14 07:27:35.661598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 2 with properties:
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:04:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
2017-08-14 07:27:35.661622: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 0 and 1
2017-08-14 07:27:35.662012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 1 and 0
2017-08-14 07:27:35.662023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 1 and 2
2017-08-14 07:27:35.662037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 2 and 1
2017-08-14 07:27:35.662051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1 2
2017-08-14 07:27:35.662059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y N Y
2017-08-14 07:27:35.662066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   N Y N
2017-08-14 07:27:35.662072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   Y N Y
2017-08-14 07:27:35.662085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:03:00.0)
2017-08-14 07:27:35.662094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1017] Ignoring gpu device (device: 1, name: Quadro P400, pci bus id: 0000:01:00.0) with Cuda multiprocessor count: 2. The minimum required count is 8. You can adjust this requirement with the env var TF_MIN_GPU_MULTIPROCESSOR_COUNT.
2017-08-14 07:27:35.662103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 2, name: Tesla K40c, pci bus id: 0000:04:00.0)
```

**Comment by poppingtonic** [comment]
I've experienced a similar problem with Ubuntu 17.04: 

https://github.com/tensorflow/tensorflow/issues/394#issuecomment-325960549

**Comment by evolu8** [comment]
Possible solution: I had this issue, nvidia-smi was working fine, and it turned out I was placing my device where none existed. I have two environments. One with many GPUs one with just one. Running the code one the single GPU machine but placing the device on position '1' (or any other than '0') gave rise to this error.

**Comment by tharuniitk** [comment]
Adding following lines to .bashrc worked for me!!

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64:/usr/local/cuda-8.0/targets/x86_64-linux/lib/"

**Comment by CLIsVeryOK** [comment]
I met the same problem, and I find nvidia-smi not work as aselle suggest.
I re install the nvdia-smi follows https://blog.csdn.net/w5688414/article/details/78287199
then reboot my computer, everything works!

**Comment by Jhouny** [comment]
> Issue resolved after Ubuntu restart. I installed updates and was pending a restart, after the restart GPU was detected.
The same for me after creating virtual environment and installing dependencies

**Comment by ggdupont** [comment]
Hi guys,
Not 100% sure it's relevant but I got the same error message on a clean AWS g3 instance booted with AWS ubuntu deeplearning AMI. nvidia-smi is working well and I can confirm the GPU is available in the right conda env where tensorflow is installed by default by calling:
`
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

get_available_gpus()
`
output:
`['/device:GPU:0']`

Then trying to train the nlu part of my bot, I have the same:
`2019-03-04 09:52:50.156502: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error`

Few more context:
- python 3.6.5 :: Anaconda custom (64-bit)
- rasa-nlu==0.14.4
- tensorflow==1.12.0

Last note: the training run well on CPU, it's just super long...

**Comment by ggdupont** [comment]
> > Issue resolved after Ubuntu restart. I installed updates and was pending a restart, after the restart GPU was detected.
> > The same for me after creating virtual environment and installing dependencies

On my end, reloading the conda environment used was the trick (probably similar to reboot since it has reloaded path and variable and such...)

**Comment by rsingh2083** [comment]
> when i run tensorflow gpu my gpy is gt 620m
> linux mint 18.1
> 
> ```
> E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_UNKNOWN
> I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: essam-goda
> I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: essam-goda
> I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 340.101.0
> I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  340.101  Thu Dec  1 15:52:31 PST 2016
> GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
> """
> I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 340.101.0
> I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 340.101.0
> ```

Sometimes a simple reboot  works
