### ISSUE TITLE
Issue with Ubuntu 16.04 GPU install: Bus error (core dumped)

### ISSUE THREAD

**Issue by jiexunsee** [tensorflow/tensorflow#7663]
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: CUDA 8.0, cuDNN 5.1

jiexun@jiexun-XPS-15-9560:~$ ls -l /usr/local/cuda-8.0/lib64/libcud*
-rw-r--r-- 1 root root   556000 Feb 19 15:48 /usr/local/cuda-8.0/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Feb 19 15:48 /usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Feb 19 15:48 /usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.61
-rwxr-xr-x 1 root root   415432 Feb 19 15:48 /usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
-rw-r--r-- 1 root root   775162 Feb 19 15:48 /usr/local/cuda-8.0/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Feb 19 16:10 /usr/local/cuda-8.0/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       18 Feb 19 16:10 /usr/local/cuda-8.0/lib64/libcudnn.so.5 -> libcudnn.so.5.1.10
-rwxr-xr-x 1 root root 42762752 Feb 19 16:10 /usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10

Installed GPU enabled TensorFlow with:
pip install tensorflow-gpu

Error message importing tensorflow:
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
Bus error (core dumped)

#### Any idea why the above 'Bus error' is happening? Thanks a lot!

----
I also tried installing from source, but got this error when creating the pip package:
, after running `bazel build --config opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`:
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-self-assign'
ERROR: /home/jiexun/tensorflow/tensorflow/python/BUILD:2279:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow.so' failed: link_dynamic_library.sh failed: error executing command external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o ... (remaining 27 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local_linux-py3-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Slib/libcudnn.so.5: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1332.429s, Critical Path: 853.44s

**Comment by aselle** [comment]
@zheng-xq, @jart, @gunan do either of you have insight? It looks like one warning sign is that -Wno-self-assign is not being found which looks like the warning is a gcc warning that doesn't exist on clang. But that is only a warning.

**Comment by gabbifish** [comment]
In the off-chance you're in Chris Manning's Natural Language Processing with Deep Learning class (CS 224N), I found that deleting the VM you're currently using and restarting TensorFlow (and all dependencies) installation with a fresh VM is a quick solution.

**Comment by gunan** [comment]
Is it possible your `LD_LIBRARY_PATH` is not setup correctly?

**Comment by jiexunsee** [comment]
@gabbifish haha I'm just trying to install tensorflow gpu from scratch on my computer!

@gunan I set it as 
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64"
export CUDA_HOME=/usr/local/cuda

**Comment by gunan** [comment]
This looks very similar to #6744
And the build error message points to an issue with your libcudnn.so file.
Could you retry installing libcudnn?

**Comment by jiexunsee** [comment]
I will try and let you know, thanks a lot for the help!

**Comment by prb12** [comment]
Closing due to lack of activity.  Please reopen if necessary.

**Comment by jiexunsee** [comment]
thanks for the help, I reinstalled everything and it works now!
