### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY with tf.contrib.learn (basic linear regression model)

### ISSUE THREAD

**Issue by gajop** [tensorflow/tensorflow#7680]
### Environment info
Operating System: Ubuntu 16.04,  GeForce GTX TITAN X

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
ls /usr/local/cuda-8.0/lib64/libcud*
/usr/local/cuda-8.0/lib64/libcudadevrt.a
/usr/local/cuda-8.0/lib64/libcudart.so
/usr/local/cuda-8.0/lib64/libcudart.so.8.0
/usr/local/cuda-8.0/lib64/libcudart.so.8.0.44
/usr/local/cuda-8.0/lib64/libcudart_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so
/usr/local/cuda-8.0/lib64/libcudnn.so.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/lib64/libcudnn_static.a

### If installed from binary pip package, provide:

1) Installed with pip tensorflow-gpu
2) ~ python -c "import tensorflow; print(tensorflow.__version__)
1.0.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Using the provided tf.contrib.learn model in get_started/get_started documentation
```
import tensorflow as tf
import numpy as np

features = [tf.contrib.layers.real_valued_column("x", dimension=1)]
estimator = tf.contrib.learn.LinearRegressor(feature_columns=features)
x = np.array([1., 2., 3., 4.])
y = np.array([0., -1., -2., -3.])
input_fn = tf.contrib.learn.io.numpy_input_fn({"x":x}, y, batch_size=4, num_epochs=1000)
estimator.fit(input_fn=input_fn, steps=10)

```

The Core model works fine.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

```
python test-oom.py 
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpew3U6z
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /home/gajop/projekti/ubuntu-ranking-dataset-creator/env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 11.92GiB
Free memory: 11.52GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 11.92G (12799180800 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
```

**Comment by gajop** [comment]
related https://github.com/tensorflow/tensorflow/issues/7677

**Comment by PaulKlym** [comment]
Hi, I have the same issue:
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: GeForce GT 740M
major: 3 minor: 5 memoryClockRate (GHz) 1.0325
pciBusID 0000:09:00.0
Total memory: 1.96GiB
Free memory: 1.90GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GT 740M, pci bus id: 0000:09:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 1.96G (2100953088 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
```

**Comment by Carmezim** [comment]
Apparently there is something consuming your GPU memory (`Total memory: 11.92GiB
Free memory: 11.52GiB`) making unavailable the amount TensorFlow is trying to allocate. 

Your can set how much memory TensorFlow will have available for use with [tf.GPUOptions](https://www.tensorflow.org/api_docs/python/tf/GPUOptions)
```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)  #define amount of GPU memory
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```
For instance if you have 12GB, ~4GB will be allocated for TensorFlow.
Your other option is to use a NVidia SMI to see where your memory is going.

**Comment by gajop** [comment]
I'll try to explicitly limit memory usage when I'm back at the computer, but it still seems that allocating all the GPU memory is clearly a bug.
Am I interpreting it wrong?

**Comment by poxvoculi** [comment]
Today's a Google corporate holiday, so followup may be slow, but this looks like it could be a recently introduced bug.  By default, TF should be trying to allocate all of the free memory on the GPU, not the total memory.  Your error message indicates it's trying to allocate total memory.  As @Carmezim notes, there is a work-around.

**Comment by hajome73** [comment]
In tensorflow\contrib\learn\python\learn\estimators\run_config.py you can change the GPUOption.
I changed in `def __init__`  **per_process_gpu_memory_fraction** to **0.7** .

**Comment by trd714** [comment]
I have the same issue when trying to run the basic usage program from https://www.tensorflow.org/get_started/get_started using the version 1.0.1. TensorFlow tries to allocate the total memory:

`I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 960M
major: 5 minor: 0 memoryClockRate (GHz) 1.176
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.57GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 3.95G (4240965632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY`

Any news on fixing this?

By the way, the program also generates some warnings:

`WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp8_ec6rtc
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /home/trd/apps/miniconda/envs/mt/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.`

The one from head.py about deprecation and removal after 2016-11-30 looks extremely weird to me.

**Comment by gunan** [comment]
@trd714 Could you try out the suggestion by @hajome73, the one right above your comment?

**Comment by trd714** [comment]
@gunan Yes, it works.
But I like the solution by Carmezim (https://github.com/tensorflow/tensorflow/issues/7680#issuecomment-281084099) much more as it doesn't involve hard coding anything in the TensorFlow package.

**Comment by gunan** [comment]
The solution by @Carmezim suppresses error messages, does not fix anything.
It is OK to use it in the warning messages described in that issue.

In your case,, you are seeing an actual error message.
You will get bad results so just using that solution over there will not help you for fixing the training process.

**Comment by trd714** [comment]
@gunan I see, thank you.

But anyway the solution by @hajome73 doesn't seem to be ideal.
I took a closer look at the output after applying the solution and it looks suspicious to me. See this gist: https://gist.github.com/trd714/551cd37e00a57a83ae40a36f195b470b.
Firstly, I see two lines that say "Creating TensorFlow device" (27 and 32).
Secondly, I get "Out of range" at line 33. After reading the line number 34 I assume that it's somehow related to the CPU as it states _device="/job:localhost/replica:0/task:0/cpu:0". Are lines 33 and 34 an issue at all? If yes, are they related to the initial issue or should I create a new one?

P.S. I had to wrap the last statement at https://www.tensorflow.org/get_started/get_started#basic_usage (estimator.evaluate(input_fn=input_fn)) in a print() function to get the output.

**Comment by gunan** [comment]
In tf logging library, the error message lines that start with `I` means information, this line is just for information, nothing bad is happening there. `W` means warning, something unexpected happened but The overall process will still run, it may be nothing. These messages you should be aware of, but most of the time can be ignored. All your current logs are information or Warning, so it all looks OK to me.

`E` means Error, which means something bad happened. Something that has to be fixed.
`CUDA_ERROR_OUT_OF_MEMORY` was an error, so it had to be fixed.
Current messages are all benign.

**Comment by trd714** [comment]
@gunan Thank you for the information.
By the way, today I've updated to 1.1.0-rc1 and the example works out of the box.

@gajop Do you experience the issue on 1.1.0-rc1?

**Comment by JulesKzl** [comment]
I had the same issue with Tensorflow 1.0.1 and boston.py . Works now fine without errors with update 1.1.0 .

**Comment by mangalbhaskar** [comment]
I'm new to TF and I'd the same issue following the getting started  tf.contrib.learn tutorial. I'm using TF 1.0.0-rc2 with gpu support. On various forums people have pointed out to limit the GPU fraction memory, it worked; though it also worked only by starting a session without any GPU settings.
```
sess = tf.Session() 
```
This solves the issue and does not have to specifically provide the GPU memory fraction. I have tried with following:
```
#config = tf.ConfigProto()
#config.gpu_options.per_process_gpu_memory_fraction = 0.3
#config.allow_soft_placement = True
#config.log_device_placement = True
#sess = tf.Session(config=config)

# Added this line and error was fixed
sess = tf.Session()

# Declare list of features. We only have one real-valued feature. There are many
# other types of columns that are more complicated and useful.
features = [tf.contrib.layers.real_valued_column("x", dimension=1)]
... 
```
From the documentation on [GPU usage](https://www.tensorflow.org/tutorials/using_gpu):
> By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to CUDA_VISIBLE_DEVICES) visible to the process

I can only speculate that starting a session limits the GPU memory allocation, though I have no idea why starting a Session solved the GPU memory issue. It would be great if someone can kindly explain.

**Comment by secsilm** [comment]
I had the same issue. Here is my solution.

Add the `config`  option when you define your estimator, for exzample: 

```python
config = tf.contrib.learn.RunConfig(gpu_memory_fraction=0.3)
estimator = tf.contrib.learn.LinearRegressor(feature_columns=features, config=config)
```

But I still want to know how I can only use CPU.

**Comment by gunan** [comment]
Before running TF, if you set `export CUDA_VISIBLE_DEVISES=""` That should make all of your GPUs invisible to TF. One you start, it should run things on your CPU.
Could you try it out?

**Comment by secsilm** [comment]
@gunan I'm using MINGW32 bash on Windows and that didn't work for me. TensorFlow still use GPU to compute.

**Comment by gunan** [comment]
MINGW32 on windows is not a tested/supported platform.
Therefore, I cannot really comment on how that might work, or if even GPU access correctly works on your setup.

I recommend heading to stackoverflow to reach out to community for help on your issue.
As the initial issue on ubuntu seems to be resolved/addressed, I will close this issue.
