### ISSUE TITLE
NVIDIA GPU not being detected, no error messages provided. All minimum requirements met.

### ISSUE THREAD

**Issue by alexanderjalexander** [tensorflow/tensorflow#77729]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.10

### Custom code

No

### OS platform and distribution

Windows

### Python version

3.10

### GPU model and memory

NVIDIA GTX 1650 Max-Q | 4GB VRAM

### Current behavior?

I am in need of GPU support on my laptop for TensorFlow. I natively run Windows for all my development, and while WSL2 Tensorflow "works," it is unbearingly slow when I try to run Jupyter notebooks connecting to WSL2 from PyCharm. So, the following steps are what I took to install Tensorflow 2.10, in hopes of getting GPU support.

- Installed Python 3.10
- Installed CUDA Toolkit v12.6 and v11.8
- Installed cuDNN v9.5 and cuDNN v8.9
- Verified my GPU has a compatible CUDA version (12.6) (see nvidia-smi output below)
```+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0             12W /   35W |      19MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```
- Created a new PyCharm project with a venv based off of Python 3.10
- Targeted the project's venv and installed tensorflow with the line `python -m pip install "tensorflow<2.11"`
- Attempted to verify the installation using `python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"`

Even after cross-referencing the documentation to ensure my versions are correct and installing any and all dependencies based on warning provided, my dGPU is still undetected and not shown in the Python commandline output. Any and all advice is appreciated, I'm willing to try anything at this point.

### Standalone code to reproduce the issue

```shell
python -c "import tensorflow as tf; print(tf.config.list_physical_devices())"
```

### Relevant log output

```shell
> []
```

**Comment by alexanderjalexander** [comment]
Issue closed. After reproducing the steps one more time, it turns out the venv in question was not targeted properly. An alternate venv was targeted instead. Thus the GPU was not supported due to this problem.
