### ISSUE TITLE
Unable to register CUDA plug-ins runnung docker image latest-gpu-jypyter

### ISSUE THREAD

**Issue by VsevolodLvov** [tensorflow/tensorflow#79520]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.18.0

### Custom code

No

### OS platform and distribution

docker desktop 4.35.1 , ubuntu 24.04.1 LTS, WSL 2.3.24.0

### Mobile device

None

### Python version

Python 3.11.0rc1 (provided by tensorflow docker image)

### CUDA/cuDNN version

12.7

### GPU model and memory

NVIDIA GeForce RTX 4060 Ti 16G

### Current behavior?

I Strictly followed the instructions provided in:
https://www.tensorflow.org/install/docker 
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
Got correct results running a sample workload (as suggested in nvidia contaner toolkit installation manual)

![image](https://github.com/user-attachments/assets/6f8c74e6-e23d-4395-8ffc-314f69af5bc7)

Downloaded tensorflow/tensorflow latest-gpu-jupyter image and ran the container.
Opend a new jupyter notebook (http://127.0.0.1:8888/tree?token=...)
Importing tensorflow I wanted to check the GPU support.
Got error messages and empy available gpu list.
`2024-11-06 10:31:50.143673: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730889110.283427      23 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730889110.322596      23 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 10:31:50.712357: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.`

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.__version__

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
```

### Relevant log output

```shell
2024-11-06 10:31:50.143673: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730889110.283427      23 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730889110.322596      23 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 10:31:50.712357: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
'2.18.0'

Num GPUs Available:  0
2024-11-06 10:31:54.748888: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (34)
```

**Comment by VsevolodLvov** [comment]
I run Windows: 10.0.19045.5011

**Comment by chanangaza** [comment]
same as above. running 2.17.1-gpu results in all OK.

**Comment by VsevolodLvov** [comment]
Did not find 2.17.1 docker image, used 2.17.0 instead - unfortunally the same result: the same errors and no GPU found.
![image](https://github.com/user-attachments/assets/15b36eb6-4570-4b6c-93fc-ede5e3d5f714)

**Comment by chanangaza** [comment]
> Did not find 2.17.1 docker image, used 2.17.0 instead - unfortunatally the same result: the same errors and no GPU found. ![image](https://private-user-images.githubusercontent.com/106977073/383855149-15b36eb6-4570-4b6c-93fc-ede5e3d5f714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTM5MzUsIm5iZiI6MTczMDk5MzYzNSwicGF0aCI6Ii8xMDY5NzcwNzMvMzgzODU1MTQ5LTE1YjM2ZWI2LTQ1NzAtNGI2Yy05M2ZjLWVkZTVlM2Q1ZjcxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNTMzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGQxNWE2MmM0ODVhYmEwZDZjMDE2NzgxM2IyNWE1ZGE0M2Q2MzlkMzM2YmIxMzAxMjk0ZDEzMjU3MDkwNjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fjL6CXFmcqppGzc6J_87DVtPXfdNW7pGXc4beFgqwyE)

sorry, my bad meant `2.17.0-gpu`.

below is what I get with `2.17.0-gpu`:
![image](https://github.com/user-attachments/assets/42f52e58-b12c-4e50-a7d2-bec8be6f17f3)

output of same but with `2.18.0-gpu`:
![image](https://github.com/user-attachments/assets/1b761b75-5f10-4183-9932-67ee137cea58)

**Comment by psavarmattas** [comment]
I was stuck with it also the way I solved it was to use this command:
` docker run --gpus all -it -p 8888:8888 tensorflow/tensorflow:2.17.0-gpu-jupyter` 
This allowed the docker container to use the gpus. Hope this helps!

**Comment by tilakrayal** [comment]
@learning-to-play

**Comment by VsevolodLvov** [comment]
> I was stuck with it also the way I solved it was to use this command: ` docker run --gpus all -it -p 8888:8888 tensorflow/tensorflow:2.17.0-gpu-jupyter` This allowed the docker container to use the gpus. Hope this helps!

Yes! It seems to work. Though error messages and warnings still persist. Anyhow, I was expecting TF 2.18 to work. Sadly enough, it would not.
