### ISSUE TITLE
failed initializing StreamExecutor for CUDA device ordinal 0

### ISSUE THREAD

**Issue by encorechow** [tensorflow/tensorflow#7983]
I encountered a strange issue that tensorflow asks for extreme amount of memory and report an error, which I cannot find any solution over the internet. I have two Titan X, the gpu0 is running traning process which occupies the whole memory of gpu0 and 100m of gpu1. I was trying to run inference python program on gpu1 and got that error. 

System settings: Ubuntu 16.04, Cuda 8.0, CUDNN 5.1 for 8.0, Nvidia 367.57 driver, tensorflow 1.0.0. The rest you can see in the log. 

```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
E tensorflow/core/common_runtime/direct_session.cc:137] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615
Traceback (most recent call last):
  File "inference.py", line 143, in <module>
    main()
  File "inference.py", line 102, in main
    sess = tf.Session(config=config)
  File "/home/zhouzh/virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1187, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/zhouzh/virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 552, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/zhouzh/virtualenvs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
```

**Comment by gunan** [comment]
Tensorflow tries to preallocate memory on the GPUs. I think the default is 70%  of the GPU memory.

The easiest solution would be to have the two different processes sequentially.
Or you can use the `CUDA_VISIBLE_DEVICES` environment variables to give exclusive access to each process. In your programs, you would then start your session to use `gpu:0`

**Comment by prb12** [comment]
Closing due to lack of activity.

**Comment by encorechow** [comment]
@gunan Thanks for your reply. Yeah I knew this environment variables. But this problem actually randomly happened if I already occupied most of the memory in gpu0. Even When I create a session with single tf.constant. Do you have any ideas about this?

**Comment by gunan** [comment]
No matter how small a variable you create TF preallocates GPU memory.
The randomness may come from the concurrency, the exact timing where you start both programs.

In any case, this is the expected behaviour from TF.
You can search for `CUDA_ERROR_OUT_OF_MEMORY` to read more about this, there are quite a few github issues filed about this problem.

**Comment by encorechow** [comment]
@gunan Okay got you. Thanks!

**Comment by mytrjp** [comment]
I had experienced the same issue. What exactly worked for me that I just closed all opened terminals and opened again, then it worked! . Because I was working on multiple virtual environments at the same time and most probably this caused GPU's memory overloaded. 
Hope works for all having this issue.

**Comment by me6ran** [comment]
thank you @mytrjp  
I checked first GPU load by nvidia-smi command and found some apps are running on top of that. after closing them, and closing current terminal, and open terminal again it starts working.

**Comment by amirstar** [comment]
I had experienced the same issue. I had 8 GPUs and run two python scripts on two of them. What worked for me that I just closed one of the python programs.

**Comment by xiaoyanzhuo** [comment]
I have experience same issue when I ran codes on 4GPUs, when I open jupyter notebook using GPU, and then another python script in terminal. Check 'nvidia-smi' and figured out the first GPU(0) memory is almost fully utilized, and I specify the other 3 GPU using os.environ["CUDA_VISIBLE_DEVICES"] ="1,2,3"  then both of them can work together and didn't need to close one to support the other one.

**Comment by MeghnaNatraj** [comment]
A couple of things that helped me:

1. Close all terminal windows and start fresh (or kill as many processes as you can -- specifically GPU related.)

2. I further got another error that the GPU does not have sufficient memory


```
2019-09-18 15:39:14.544076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with **2491 MB** memory) -> physical GPU (device: 0, name: Quadro P1000, pci bus id: 0000:65:00.0, compute capability: 6.1)
.
.

2019-09-18 15:37:02.323090: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate **2.25GiB** with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
```
You'll notice in the above logs that the GPU has ~2.4 GB but the memory needed was 2.25GB. Technically, it should work, but maybe it needs a bit more memory (maybe 2.25 + extra) and it failed. 

I just tried training a smaller model (4X smaller) and the issue went away! Basically my GPU isn't great :laughing:

**Comment by boveiri** [comment]
I currently faced such error:
Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 6442450944

I have only one 6GB GPU, there is only one terminal to run the program (Anaconda+PyCharm) on Windows 7 (x64). Guidance in step-by-step fashion is highly appreciated.  The CUDA version is 9 and CuDNN is 7, and the Tensorflow and its gpu version are 1.10.

**Comment by Aldhubri** [comment]
try to use these two commands to check and rest your CUDA 
 nvidia-smi
 nvidia-smi --gpu-reset

**Comment by LukeLIN-web** [comment]
My GPu vram has  0.594Gi/93.584Gi] but still have this issue.
