### ISSUE TITLE
Multi-GPU Inference using FIFO Queues issue in TF v1.0.0

### ISSUE THREAD

**Issue by agupta74** [tensorflow/tensorflow#8061]
Here is an example multi-gpu inference code which produces incorrect Output in TF v1.0.0 but produces correct output in v0.11.0 (single GPU produces correct output in both versions). Please refer to the attached code for more details.

[InferenceTest.txt](https://github.com/tensorflow/tensorflow/files/817729/InferenceTest.txt)
[Inference.txt](https://github.com/tensorflow/tensorflow/files/817730/Inference.txt)

**Correct Output (TF v0.11) -- 2 GPUs** 
python InferenceTest.py 2
-------------------------
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
**************** Using 2 GPUs *****************
TensorFlow version:  0.11.0
GPU ID List:  [0, 1]
Device:  /gpu:0
Device:  /gpu:1
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla M40
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:00:05.0
Total memory: 11.21GiB
Free memory: 11.09GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x37b9dc0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 1 with properties: 
name: Tesla M40
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:00:09.0
Total memory: 11.21GiB
Free memory: 11.09GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 0 to device ordinal 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:855] cannot enable peer access from device ordinal 1 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y N 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 1:   N Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40, pci bus id: 0000:00:05.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla M40, pci bus id: 0000:00:09.0)
Input Value 0
Input Value 1
Input Value 2
Input Value 3
Input Value 4
Input Value 5
Input Value 6
Input Value 7
Input Value 8
Input Value 9
Input Queue Size=  10
Results Queue Size=  0
Processing: Input Queue Size=  8
Processing: Results Queue Size=  2
Processing: Input Queue Size=  6
Processing: Results Queue Size=  4
Processing: Input Queue Size=  4
Processing: Results Queue Size=  6
Processing: Input Queue Size=  2
Processing: Results Queue Size=  8
Processing: Input Queue Size=  0
Processing: Results Queue Size=  10
************* Dequeue Results ********************
Results Queue Size=  10
Dequeue Results: Results Output  1:
Dequeue Results: Results Queue Size=  9
Dequeue Results: Results Output  2:
Dequeue Results: Results Queue Size=  8
Dequeue Results: Results Output  3:
Dequeue Results: Results Queue Size=  7
Dequeue Results: Results Output  4:
Dequeue Results: Results Queue Size=  6
Dequeue Results: Results Output  6:
Dequeue Results: Results Queue Size=  5
Dequeue Results: Results Output  5:
Dequeue Results: Results Queue Size=  4
Dequeue Results: Results Output  7:
Dequeue Results: Results Queue Size=  3
Dequeue Results: Results Output  8:
Dequeue Results: Results Queue Size=  2
Dequeue Results: Results Output  9:
Dequeue Results: Results Queue Size=  1
Dequeue Results: Results Output  10:
Dequeue Results: Results Queue Size=  0
Final Input Queue Size=  0
Final Results Queue Size=  0

***************************************************************************************************
**Wrong Output (TF v1.0.0) -- 2 GPUs** 
python InferenceTest.py 2
-------------------------
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
**************** Using 2 GPUs *****************
TensorFlow version:  1.0.0
GPU ID List:  [0, 1]
Device:  /gpu:0
Device:  /gpu:1
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla M40
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:00:05.0
Total memory: 11.21GiB
Free memory: 11.09GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x1999d60
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 1 with properties: 
name: Tesla M40
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:00:09.0
Total memory: 11.21GiB
Free memory: 11.09GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 0 and 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 1 and 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y N 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 1:   N Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40, pci bus id: 0000:00:05.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla M40, pci bus id: 0000:00:09.0)
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:1 for node 'Tower_1/Dequeue_Input_Data/fifo_queue_Dequeue' because the input edge from 'Input_FIFO_Queue/fifo_queue' is a reference connection and already has a device field set to /CPU:0
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:1 for node 'Tower_1/Results_Enqueue/fifo_queue_enqueue' because the input edge from 'Results_FIFO_Queue/fifo_queue' is a reference connection and already has a device field set to /CPU:0
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:0 for node 'Tower_0/Dequeue_Input_Data/fifo_queue_Dequeue' because the input edge from 'Input_FIFO_Queue/fifo_queue' is a reference connection and already has a device field set to /CPU:0
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:0 for node 'Tower_0/Results_Enqueue/fifo_queue_enqueue' because the input edge from 'Results_FIFO_Queue/fifo_queue' is a reference connection and already has a device field set to /CPU:0
Input Value 0
Input Value 1
Input Value 2
Input Value 3
Input Value 4
Input Value 5
Input Value 6
Input Value 7
Input Value 8
Input Value 9
Input Queue Size=  10
Results Queue Size=  0
Processing: Input Queue Size=  9
Processing: Results Queue Size=  2
Processing: Input Queue Size=  8
Processing: Results Queue Size=  4
Processing: Input Queue Size=  7
Processing: Results Queue Size=  6
Processing: Input Queue Size=  6
Processing: Results Queue Size=  8
Processing: Input Queue Size=  5
Processing: Results Queue Size=  10
Processing: Input Queue Size=  4
Processing: Results Queue Size=  12
Processing: Input Queue Size=  3
Processing: Results Queue Size=  14
Processing: Input Queue Size=  2
Processing: Results Queue Size=  16
Processing: Input Queue Size=  1
Processing: Results Queue Size=  18
Processing: Input Queue Size=  0
Processing: Results Queue Size=  20
************* Dequeue Results ********************
Results Queue Size=  20
Dequeue Results: Results Output  1:
Dequeue Results: Results Queue Size=  19
Dequeue Results: Results Output  1:
Dequeue Results: Results Queue Size=  18
Dequeue Results: Results Output  2:
Dequeue Results: Results Queue Size=  17
Dequeue Results: Results Output  2:
Dequeue Results: Results Queue Size=  16
Dequeue Results: Results Output  3:
Dequeue Results: Results Queue Size=  15
Dequeue Results: Results Output  3:
Dequeue Results: Results Queue Size=  14
Dequeue Results: Results Output  4:
Dequeue Results: Results Queue Size=  13
Dequeue Results: Results Output  4:
Dequeue Results: Results Queue Size=  12
Dequeue Results: Results Output  5:
Dequeue Results: Results Queue Size=  11
Dequeue Results: Results Output  5:
Dequeue Results: Results Queue Size=  10
Dequeue Results: Results Output  6:
Dequeue Results: Results Queue Size=  9
Dequeue Results: Results Output  6:
Dequeue Results: Results Queue Size=  8
Dequeue Results: Results Output  7:
Dequeue Results: Results Queue Size=  7
Dequeue Results: Results Output  7:
Dequeue Results: Results Queue Size=  6
Dequeue Results: Results Output  8:
Dequeue Results: Results Queue Size=  5
Dequeue Results: Results Output  8:
Dequeue Results: Results Queue Size=  4
Dequeue Results: Results Output  9:
Dequeue Results: Results Queue Size=  3
Dequeue Results: Results Output  9:
Dequeue Results: Results Queue Size=  2
Dequeue Results: Results Output  10:
Dequeue Results: Results Queue Size=  1
Dequeue Results: Results Output  10:
Dequeue Results: Results Queue Size=  0
Final Input Queue Size=  0
Final Results Queue Size=  0

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: CentOS 7.2.1511

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
![cudaversion](https://cloud.githubusercontent.com/assets/21690396/23567127/a771fd10-0009-11e7-88bb-daa27a1b28c2.PNG)

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp35-cp35m-linux_x86_64.whl 
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

See the output above for 2 different tensor flow versions

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by mrry** [comment]
I think this is an instance of a previous issue: #7038. This was fixed at `HEAD` but not in the 1.0 release. Can you try a nightly build and see if that fixes your problem? Thanks!

/cc @alextp to confirm.

**Comment by alextp** [comment]
Yes, this looks like that issue.

**Comment by agupta74** [comment]
I am trying to build tensorflow with the latest master branchbut getting the following error. Any ideas on how this could be fixed?

ERROR: /home/agupta2/TensorFlow_Sources/tensorflow/tensorflow/stream_executor/BUILD:39:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/56ec560c84df85845595d71cca739b3f/execroot/tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/lib64/:/root/anaconda3/lib/:/usr/local/cuda/lib64/:/usr/local/cuda/extras/CUPTI/lib64/: \
    PATH=/home/agupta2/Bazel/output:/root/anaconda3/bin:/usr/local/cuda/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/opt/ibutils/bin \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-march=native' '-std=c++11' '-march=native' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.d '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DTENSORFLOW_USE_JEMALLOC -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -iquote external/jemalloc -iquote bazel-out/local_linux-py3-opt/genfiles/external/jemalloc -iquote external/bazel_tools -iquote bazel-out/local_linux-py3-opt/genfiles/external/bazel_tools -iquote external/protobuf -iquote bazel-out/local_linux-py3-opt/genfiles/external/protobuf -iquote external/eigen_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local_linux-py3-opt/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local_linux-py3-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive -iquote external/highwayhash -iquote bazel-out/local_linux-py3-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda -isystem external/jemalloc/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/jemalloc/include -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/protobuf/src -isystem external/eigen_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/local_linux-py3-opt/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda/include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/stream_executor/cuda/cuda_blas.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/stream_executor/cuda/cuda_blas.cc: In member function 'virtual bool perftools::gputools::cuda::CUDABlas::GetBlasGemmAlgorithms(std::vector<long long int>*)':
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:9: error: 'CUBLAS_GEMM_ALGO5' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
         ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:28: error: 'CUBLAS_GEMM_ALGO6' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                            ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:47: error: 'CUBLAS_GEMM_ALGO7' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                                               ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:64: error: unable to deduce 'std::initializer_list<_Tp>&&' from '{CUBLAS_GEMM_DFALT, CUBLAS_GEMM_ALGO0, CUBLAS_GEMM_ALGO1, CUBLAS_GEMM_ALGO2, CUBLAS_GEMM_ALGO3, CUBLAS_GEMM_ALGO4, <expression error>, <expression error>, <expression error>}'
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                                                                ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cublasOperation_t perftools::gputools::cuda::{anonymous}::CUDABlasTranspose(perftools::gputools::blas::Transpose)':
tensorflow/stream_executor/cuda/cuda_blas.cc:410:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cublasFillMode_t perftools::gputools::cuda::{anonymous}::CUDABlasUpperLower(perftools::gputools::blas::UpperLower)':
tensorflow/stream_executor/cuda/cuda_blas.cc:421:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cublasDiagType_t perftools::gputools::cuda::{anonymous}::CUDABlasDiagonal(perftools::gputools::blas::Diagonal)':
tensorflow/stream_executor/cuda/cuda_blas.cc:432:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cudaDataType_t perftools::gputools::cuda::{anonymous}::CUDAComputationType(perftools::gputools::blas::ComputationType)':
tensorflow/stream_executor/cuda/cuda_blas.cc:519:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cublasSideMode_t perftools::gputools::cuda::{anonymous}::CUDABlasSide(perftools::gputools::blas::Side)':
tensorflow/stream_executor/cuda/cuda_blas.cc:443:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by agupta74** [comment]
It looks like that I have an older version of Cuda 8 libraries. Please ignore my previous email.

**Comment by prb12** [comment]
@agupta74  Please let us know if building at head solves your problem.

**Comment by agupta74** [comment]
I was able to build successfully from sources using master branch. The issue is fixed. We can close this issue now. Thanks !

**Comment by mrry** [comment]
Great—thanks for verifying!

**Comment by agupta74** [comment]
I would like to know in which version of TensorFlow release will the fix for this issue be delivered?  Based on the release notes of the latest TensorFlow release (TensorFlow 1.1.0- rc1), I do not see the fix for this issue delivered yet.

**Comment by Goddard** [comment]
Getting this error in 1.3
