### ISSUE TITLE
bug in cudnn  for cnn?

### ISSUE THREAD

**Issue by morusu** [tensorflow/tensorflow#8360]
tensorflow 1.0
cuda 8.0
cudnn 5.0

install method:
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp27-none-linux_x86_64.whl 

when  I run the  models/tutorials/image/mnist/convolutional.py
I got:
E tensorflow/stream_executor/cuda/cuda_dnn.cc:390]Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5110 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to matchIf building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:605] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
Aborted

I thought it may be the cudnn, I load cudnn5110 and export it to LD_LIBURARY_PATH
but I  got another problem:
E tensorflow/stream_executor/cuda/cuda_dnn.cc:397] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  361.62  Tue May 24 20:21:31 PDT 2016
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
"""
I tensorflow/stream_executor/cuda/cuda_dnn.cc:408] running driver version: 361.62.0
E tensorflow/stream_executor/cuda/cuda_dnn.cc:364] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F tensorflow/core/kernels/conv_ops.cc:605] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
Aborted (core dumped)

How can i fix this problem?

it's the driver's problem ?

**Comment by gunan** [comment]
Please fill all of the issue template when filing issues.

Moreover, TensorFlow does not have official support for RedHat.
Therefore, I will mark this issue Community Support.
You can probably get more help on this through stackoverflow.

**Comment by morusu** [comment]
@gunan thanks for ur attention.  I solved this problem already. I down load the  cudnn5110 for cuda7.5 but not for 8.0 , and use it with my cuda8.0, it works.  But I don't know why this can work
