### ISSUE TITLE
Tensorflow GPU "no known devices" after update from version 0.12.1 to 1.0.1 - everything was fine before

### ISSUE THREAD

**Issue by pierluigiferrari** [tensorflow/tensorflow#8734]
### Environment info

Operating System:

Ubuntu Linux 16.04

Installed version of CUDA and cuDNN: 

CUDA 8.0.44
cuDNN 5.1.10
Driver version 367.57.0

Output of `ls -l /path/to/cuda/lib/libcud*`:

-rw-r--r-- 1 root root   558720 Sep 14  2016 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep 14  2016 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep 14  2016 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rw-r--r-- 1 root root   415432 Sep 14  2016 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Sep 14  2016 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 84163560 Mar 27 11:43 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 84163560 Mar 27 11:43 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 84163560 Mar 27 11:43 /usr/local/cuda/lib64/libcudnn.so.5.1.10
-rw-r--r-- 1 root root 70364814 Mar 27 11:43 /usr/local/cuda/lib64/libcudnn_static.a

If installed from binary pip package, provide:

A link to the pip package you installed: I don't know what you mean by that :(

Tensorflow versions:
0.12.1 before the issue
1.0.1 caused the issue

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

On an AWS g2.2xlarge instance with
    * Ubuntu 16.04, 
    * CUDA and cuDNN versions as listed above
    * tensorflow-gpu 0.12.1 installed using pip
run the example code from the [tensorflow "Using GPUs" website](https://www.tensorflow.org/tutorials/using_gpu).

The output for me is:

```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 3.94GiB
Free memory: 3.91GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GRID K520, pci bus id: 0000:00:03.0)
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GRID K520, pci bus id: 0000:00:03.0
I tensorflow/core/common_runtime/direct_session.cc:255] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GRID K520, pci bus id: 0000:00:03.0

MatMul: (MatMul): /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:827] MatMul: (MatMul)/job:localhost/replica:0/task:0/gpu:0
b: (Const): /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:827] b: (Const)/job:localhost/replica:0/task:0/gpu:0
a: (Const): /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:827] a: (Const)/job:localhost/replica:0/task:0/gpu:0
[[ 22.  28.]
 [ 49.  64.]]
```

Now update Tensorflow

`pip install tensorflow-gpu --upgrade`

and run the example code again. Now the output for me is:

```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Device mapping: no known devices.
I tensorflow/core/common_runtime/direct_session.cc:257] Device mapping:

MatMul: (MatMul): /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:841] MatMul: (MatMul)/job:localhost/replica:0/task:0/cpu:0
b: (Const): /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:841] b: (Const)/job:localhost/replica:0/task:0/cpu:0
a: (Const): /job:localhost/replica:0/task:0/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:841] a: (Const)/job:localhost/replica:0/task:0/cpu:0
[[ 22.  28.]
 [ 49.  64.]]
```

It's not even giving me any hints as to what might be the problem, it just says "no known devices". 

How come the GRID K520 was a known device **just** before I updated Tensorflow and now it isn't anymore?

Nothing else happened in the meantime apart from updating Tensorflow, no other changes to the system were made in any way (at least not from my side).

### Logs or other output that would be helpful

nvidia-smi output:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   39C    P0    38W / 125W |      0MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by gunan** [comment]
I think @tfboyd was able to run TF on AWS successfully. Could you comment?

**Comment by pierluigiferrari** [comment]
@gunan It's been a while so I'm not a hundred percent sure if I remember correctly, but I believe the issue was that an automatic unattended NVIDIA GPU driver update that ran in the background broke everything, because the K520 GPUs in the AWS g2.2xlarge instances were too old and incompatible with whatever driver version updater tried to install. It left the system in an inconsistent state. That whole thing must have happened in the background exactly when I updated TensorFlow, and so I falsely attributed the failure to the TF upgrade. I never really found out whether this was actually the problem since I just stopped using AWS shortly after, but I think you can close this issue.

**Comment by gunan** [comment]
@pierluigiferrari Thank you very much for the status update. Then I will close this issue.
