### ISSUE TITLE
[CUDA] illegal memory access in ShuffleInTensor3Simple

### ISSUE THREAD

**Issue by jwnhy** [tensorflow/tensorflow#87438]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.8.1

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 24.04

### Python version

3.12.9

### CUDA/cuDNN version

cuDNN: 90300

### GPU model and memory

H100 80G

### Current behavior?

compute-sanitizer reports Illegal Memory Access.

Expect: no IMA should occur.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from keras import layers
import os
os.environ["TF_DISABLE_RZ_CHECK"] = "1"
tf.keras.backend.set_image_data_format('channels_first')
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
tensor = tf.random.uniform([2, 1, 392366])
model = layers.Conv1D(filters=2147483647, kernel_size=1, strides=392366, groups=1)
model(tensor)
```

### Relevant log output

```shell
========= COMPUTE-SANITIZER
========= Invalid __global__ write of size 4 bytes
=========     at void tensorflow::functor::ShuffleInTensor3Simple<float, (int)2, (int)1, (int)0, (bool)0>(int, const T1 *, tensorflow::functor::Dimension<(int)3>, T1 *)+0x660
=========     by thread (128,0,0) in block (8,0,0)
=========     Address 0x2e9c2ff600 is out of bounds
=========     and is 517 bytes after the nearest allocation at 0x2c9c2ff400 of size 8,589,934,588 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x37f187]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x15a13]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_runtime/lib/libcudart.so.12
=========     Host Frame:cudaLaunchKernel [0x75750]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_runtime/lib/libcudart.so.12
=========     Host Frame:absl::lts_20230802::Status tensorflow::GpuLaunchKernel<int, float const*, tensorflow::functor::Dimension<3>, float*, int, float const*, tensorflow::functor::Dimension<3>, float*>(void (*)(int, float const*, tensorflow::functor::Dimension<3>, float*), dim3, dim3, unsigned long, CUstream_st*, int, float const*, tensorflow::functor::Dimension<3>, float*) [0x2b5018e4]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2
=========     Host Frame:tensorflow::functor::TransformFilter<Eigen::GpuDevice, float, int, 4>::operator()(Eigen::GpuDevice const&, tensorflow::FilterTensorFormat, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorMap<Eigen::Tensor<float, 4, 1, int>, 16, Eigen::MakePointer>) [0x2b5015ff]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2
=========     Host Frame:void tensorflow::LaunchConvOpImpl<float>(tensorflow::OpKernelContext*, bool, tensorflow::Tensor const&, tensorflow::Tensor const&, absl::lts_20230802::InlinedVector<long, 3ul, std::allocator<long> > const&, absl::lts_20230802::InlinedVector<long, 3ul, std::allocator<long> > const&, tensorflow::Padding const&, std::vector<long, std::allocator<long> > const&, tensorflow::TensorFormat, tensorflow::Tensor*) [0x29a96f55]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2
=========     Host Frame:tensorflow::Conv2DOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*) [0x29c03560]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2
=========     Host Frame:tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) [0x6d474d4]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2
=========     Host Frame:tensorflow::(anonymous namespace)::SingleThreadedExecutorImpl::Run(tensorflow::Executor::Args const&) [0x6df8f47]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2
=========     Host Frame:tensorflow::FunctionLibraryRuntimeImpl::RunSync(tensorflow::FunctionLibraryRuntime::Options, unsigned long, absl::lts_20230802::Span<tensorflow::Tensor const>, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*) [0x6db8723]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2
=========     Host Frame:tensorflow::ProcessFunctionLibraryRuntime::RunMultiDeviceSync(tensorflow::FunctionLibraryRuntime::Options const&, unsigned long, std::vector<std::variant<tensorflow::Tensor, tensorflow::TensorShape>, std::allocator<std::variant<tensorflow::Tensor, tensorflow::TensorShape> > >*, std::function<absl::lts_20230802::Status (tensorflow::ProcessFunctionLibraryRuntime::ComponentFunctionData const&, tensorflow::ProcessFunctionLibraryRuntime::InternalArgs*)>) const [0x6dc572f]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2
=========     Host Frame:tensorflow::ProcessFunctionLibraryRuntime::RunSync(tensorflow::FunctionLibraryRuntime::Options const&, unsigned long, absl::lts_20230802::Span<tensorflow::Tensor const>, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*) const [0x6dcbb7c]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2
=========     Host Frame:tensorflow::KernelAndDeviceFunc::Run(tensorflow::ScopedStepContainer*, tensorflow::EagerKernelArgs const&, std::vector<std::variant<tensorflow::Tensor, tensorflow::TensorShape>, std::allocator<std::variant<tensorflow::Tensor, tensorflow::TensorShape> > >*, tsl::CancellationManager*, std::optional<tensorflow::EagerFunctionParams> const&, std::optional<tensorflow::ManagedStackTrace> const&, tsl::CoordinationServiceAgent*) [0x24f3ddef]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2
=========     Host Frame:tensorflow::EagerKernelExecute(tensorflow::EagerContext*, absl::lts_20230802::InlinedVector<tensorflow::TensorHandle*, 4ul, std::allocator<tensorflow::TensorHandle*> > const&, std::optional<tensorflow::EagerFunctionParams> const&, tsl::core::RefCountPtr<tensorflow::KernelAndDevice> const&, tensorflow::GraphCollector*, tsl::CancellationManager*, absl::lts_20230802::Span<tensorflow::TensorHandle*>, std::optional<tensorflow::ManagedStackTrace> const&) [0x24ee98d5]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2
=========     Host Frame:tensorflow::ExecuteNode::Run() [0x24ef33af]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2
=========     Host Frame:tensorflow::EagerExecutor::SyncExecute(tensorflow::EagerNode*) [0x24f39243]
=========                in /opt/ext/jwnhy/miniconda3/envs/tf218/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2
=========     Host Frame:tensorflow::(anonymous namespace)::EagerLocalExecute(tensorflow::EagerOperation*, tensorflow::TensorHandle**, int*) [0x24ee925a]
```

**Comment by Venkat6871** [comment]
Hi **@jwnhy** ,
Apologies for the delay, and thanks for your patience.
I ran your code on Colab using TensorFlow 2.18.0, and it threw the following error:
```
ResourceExhaustedError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 
```
This error occurs because the program is trying to allocate more GPU memory than is available. The issue seems to be caused by the large number of filters used in your model.
To resolve this, I reduced the number of filters, and it worked fine for me. I am attaching a [gist](https://colab.sandbox.google.com/gist/Venkat6871/c303ccbfb914063351ba7b79d03fbbe5/87438_tf_2-18-0-nightly-v.ipynb) here for your reference.

Thank you!

**Comment by jwnhy** [comment]
Sorry I mistyped the version number...
I found this issue on the latest tensorflow 2.18.

I am using an H100 with 80GiB ram to find this issue.

Can you try to reproduce this on a card with more ram?

**Comment by Kayyuri** [comment]
Hi @jwnhy,
Thank you so much for filing this issue! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.
To avoid duplicate work, please leave a comment here if you decide to take it on!

Thank you again for your interest and we look forward to seeing your contributions!
