### ISSUE TITLE
Tensorflow does not recognize GPU

### ISSUE THREAD

**Issue by Corey4005** [tensorflow/tensorflow#88676]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.18.0

### Custom code

No

### OS platform and distribution

WSL Linux Ubuntu 24.04

### GCC/compiler version

13.3.0

### GPU model and memory

RTX A4000 16GB

### Current behavior?

First, I installed Anaconda3-2025.10.1-Linux using wget and the shell script. 

### 1.  Install Anaconda Commands:

```
wget https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh
bash Anaconda3-2024.10-1-Linux-x86_64.sh
```

I selected yes on the location in which it generally installs.
Anaconda was installed in /home/user/anaconda3. 
I also allowed anaconda to update my shell profile by selecting yes. 
I rebooted the shell and went to step 2. 

### 2. I made sure my drivers were up to date. 

I ran the nvidia-smi command to check this and saw the latest driver for my NVIDIA RTX A4000 GPUs. The image below shows the output with the most up to date drivers. 

![Image](https://github.com/user-attachments/assets/89e0f560-be70-4f80-ba24-85cb5a7fc469)

### 3. I installed the latest cuda toolkit using the following commands. 

```
sudo apt-key del 7fa2af80
wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda_12.8.0_570.86.10_linux.run
sudo sh cuda_12.8.0_570.86.10_linux.run
```

### 4. I set my path to the cuda toolkit and the lib64 in my .bashrc file

I put the at the bottom of the file and rebooted the shell 

```
export PATH=/usr/local/cuda-12.8/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:$PATH
```

### 5. I install cuDNN
I downloaded the tar file for linux [here](https://developer.nvidia.com/rdp/cudnn-archive). It does seem that there is a file for 24.04, but the tar file did work when I installed it. 
```
tar -xvf cudnn-linux-x86_64-8.9.7.29_cuda12-archive.tar.xz
```
This unraveled a lot of files on my machine. I followed the installation instructions [here](https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-850/install-guide/)

specifically, I did the following: 

```
sudo cp cudnn-*-archive/include/cudnn*.h /usr/local/cuda/include 
sudo cp -P cudnn-*-archive/lib/libcudnn* /usr/local/cuda/lib64 
sudo chmod a+r /usr/local/cuda/include/cudnn*.h /usr/local/cuda/lib64/libcudnn*
```

When I run nvcc -V, I get: 

![Image](https://github.com/user-attachments/assets/31ec4ac5-aaf9-4532-95da-2e3794c69ba7)

### 6 I install a virtual environment and activate it. 

```
conda create -n tf python==3.12
conda activate tf
python3 -m pip install tensorflow[and-cuda]
```

Then, when I check for GPU support, I get errors and my GPU is not recognized:

### 7 The errors are shown below: 

```
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

Errors: 

```
2025-03-05 15:55:46.327193: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-05 15:55:46.338383: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1741211746.350376   17653 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741211746.354146   17653 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-05 15:55:46.365820: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-05 15:55:48.179254: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: RESOURCE_EXHAUSTED: Failed call to cuInit: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```

What am I doing wrong? 

### Standalone code to reproduce the issue

```shell
I am getting a CUDA_ERROR_OUT_OF_MEMORY upon install and my GPU is not being listed.
```

### Relevant log output

```shell

```

**Comment by zainali-AT** [comment]
The highest version of CUDA supported by your drivers is 12.3, whereas the version of CUDA you installed is 12.8 Try downgrading CUDA to <=12.3 and try again.

**Comment by Venkat6871** [comment]
Hi **@Corey4005**, thanks for raising your concern here.
Hi **@zainali-AT**, thanks for your response.
The latest CUDA version is not compatible with your machines. When installing TensorFlow with GPU support, the CUDA version is installed automatically by using the following command:
```
python3 -m pip install tensorflow[and-cuda]
```
There is no need to manually install the CUDA Toolkit. I am attaching the official [documentation1](https://www.tensorflow.org/install/pip#windows-wsl2), [documentation2](https://www.tensorflow.org/install/source#gpu) for installing TensorFlow using pip and checking compatibility versions. Based on this documentation, I installed it, and it worked fine for me. Please find the details below for your reference.
```
(tf_env) maayara@venkat-gpu1:~$ python3
Python 3.9.21 (main, Dec 11 2024, 16:24:11) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print(tf.__version__)
2.18.0
>>> print(tf.config.list_physical_devices("GPU"))
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]
>>> exit()
(tf_env) maayara@venkat-gpu1:~$ nvidia-smi
Thu Mar  6 05:55:43 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.144.03             Driver Version: 550.144.03     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       1MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       1MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

Thank you!

**Comment by Corey4005** [comment]
> Hi **[@Corey4005](https://github.com/Corey4005)**, thanks for raising your concern here. Hi **[@zainali-AT](https://github.com/zainali-AT)**, thanks for your response. The latest CUDA version is not compatible with your machines. When installing TensorFlow with GPU support, the CUDA version is installed automatically by using the following command:
> 
> ```
> python3 -m pip install tensorflow[and-cuda]
> ```
> 
> There is no need to manually install the CUDA Toolkit. I am attaching the official [documentation1](https://www.tensorflow.org/install/pip#windows-wsl2), [documentation2](https://www.tensorflow.org/install/source#gpu) for installing TensorFlow using pip and checking compatibility versions. Based on this documentation, I installed it, and it worked fine for me. Please find the details below for your reference.
> 
> ```
> (tf_env) maayara@venkat-gpu1:~$ python3
> Python 3.9.21 (main, Dec 11 2024, 16:24:11) 
> [GCC 11.2.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import tensorflow as tf
> >>> print(tf.__version__)
> 2.18.0
> >>> print(tf.config.list_physical_devices("GPU"))
> [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]
> >>> exit()
> (tf_env) maayara@venkat-gpu1:~$ nvidia-smi
> Thu Mar  6 05:55:43 2025       
> +-----------------------------------------------------------------------------------------+
> | NVIDIA-SMI 550.144.03             Driver Version: 550.144.03     CUDA Version: 12.4     |
> |-----------------------------------------+------------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> |                                         |                        |               MIG M. |
> |=========================================+========================+======================|
> |   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
> | N/A   38C    P8              9W /   70W |       1MiB /  15360MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> |   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
> | N/A   40C    P8              9W /   70W |       1MiB /  15360MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
>                                                                                          
> +-----------------------------------------------------------------------------------------+
> | Processes:                                                                              |
> |  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
> |        ID   ID                                                               Usage      |
> |=========================================================================================|
> |  No running processes found                                                             |
> +-----------------------------------------------------------------------------------------+
> ```
> 
> Thank you!

Hi, @Venkat6871. Thank you for the reply. I am going to provide exact steps I am following after seeing your recommendation that I do not install cuda manually and provide outputs for your review. 

First, I wiped WSL and reinstalled to get a fresh vm. 

### 1. In powershell
``` 
wsl --unregister Ubuntu 
wsl --install
```

I now have a new install. 

### 2. Opening WSL and looking at my version 

```
lsb_release -a 
```
The following image shows the output. 

![Image](https://github.com/user-attachments/assets/2979beb5-6bfc-4d6c-9b9c-a5633cd2dd71)

### 3. I pull the latest conda and install

```
wget https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh
bash Anaconda3-2024.10-1-Linux-x86_64.sh
```
The installation location is set by default to `/home/user/anaconda3`. 

I also allow conda to initialize by selecting `yes` when prompted. I then restart wsl and see that conda environments are now available by seeing `(base)` in my shell. 

### 4. I create a conda environment with python 3.9 as suggested for tensorflow 2.18.0 in the [documentation](https://www.tensorflow.org/install/source#gpu) you provided and activate. 

```
conda create -n tf python==3.12
conda activate tf
```

### 5. I install tensorflow and cuda using: 

```
python3 -m pip install tensorflow[and-cuda]
```
python version shows: 

```
python3 --version
```
![Image](https://github.com/user-attachments/assets/073dcc4e-4824-4147-bbb4-1dbb91ab7818)

pip version shows: 

```
![Image](https://github.com/user-attachments/assets/234144ce-3b13-4b92-b0aa-45078d58aa72)
```
### 7 I run the following command and get:
```
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

![Image](https://github.com/user-attachments/assets/590e35cf-d17c-411c-a9fb-06216f7a58f7)

nvidia-smi shows: 

![Image](https://github.com/user-attachments/assets/7c6c84cb-7478-46c2-bde8-ac61ff2f84b4)


Am I installing the wrong versions?

**Comment by Corey4005** [comment]
> The highest version of CUDA supported by your drivers is 12.3, whereas the version of CUDA you installed is 12.8 Try downgrading CUDA to <=12.3 and try again. Look up [here](https://www.tensorflow.org/install/source#gpu) to find compatible versions of CUDA, cuDNN, gcc and Python for your installed Tensorflow version.

How would I downgrade? Is there a command I can provide pip to get 12.3 instead?

**Comment by Corey4005** [comment]
Hello @tilakrayal @Venkat6871 @zainali-AT. 

I am still unable to get Tensorflow to work.

I am going to walk through some new developments, however in an effort to work towards a transparent solution that others can follow. To just start over again with a fresh install, I just unregistered WSL as I had done in prior steps and reinstalled ubuntu. 

![Image](https://github.com/user-attachments/assets/01c550d8-99a8-4cd1-bb44-e799d67f28db)

First, I have double checked my driver. I looked online and found that the RTX A4000 has driver [572.60 available](https://www.nvidia.com/en-us/drivers/details/241085/). I installed this driver such that nvidia-smi now lists CUDA 12.8, shown below. 

![Image](https://github.com/user-attachments/assets/e4abdb08-e7c4-494b-a798-59ff5830b1fa)

Could @tilakrayal, @Venkat6871 or @zainali-AT please verify I have installed the correct driver for my GPUs? 

Then, I updated and upgraded using the following commands: 

```
sudo apt update
sudo apt upgrade
```

Afterwards, I installed anaconda as prior, which installed anaconda in /home/user/anaconda3. I also let it initialize conda by changing my bashrc file shown below:

```
wget https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh
bash Anaconda3-2024.10-1-Linux-x86_64.sh
```

Does this `.bashrc` file look ok? 

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/user/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/user/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/user/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/user/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

Afterwards, I create an environment and python 3.12 using the following command:

```
conda create -n tf python==3.12
```

I then activate and install tensorflow and cuda:

```
pip install tensorflow[and-cuda]
```

Here is the packages that were installed after running conda list:

```
# packages in environment at /home/user/anaconda3/envs/tf:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   2.1.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
bzip2                     1.0.8                h5eee18b_6
ca-certificates           2025.2.25            h06a4308_0
certifi                   2025.1.31                pypi_0    pypi
charset-normalizer        3.4.1                    pypi_0    pypi
expat                     2.6.4                h6a678d5_0
flatbuffers               25.2.10                  pypi_0    pypi
gast                      0.6.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.71.0                   pypi_0    pypi
h5py                      3.13.0                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
keras                     3.9.0                    pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0
libclang                  18.1.1                   pypi_0    pypi
libffi                    3.4.4                h6a678d5_1
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
libuuid                   1.41.5               h5eee18b_0
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
ml-dtypes                 0.4.1                    pypi_0    pypi
namex                     0.0.8                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
numpy                     2.0.2                    pypi_0    pypi
nvidia-cublas-cu12        12.5.3.2                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.5.82                  pypi_0    pypi
nvidia-cuda-nvcc-cu12     12.5.82                  pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.5.82                  pypi_0    pypi
nvidia-cuda-runtime-cu12  12.5.82                  pypi_0    pypi
nvidia-cudnn-cu12         9.3.0.75                 pypi_0    pypi
nvidia-cufft-cu12         11.2.3.61                pypi_0    pypi
nvidia-curand-cu12        10.3.6.82                pypi_0    pypi
nvidia-cusolver-cu12      11.6.3.83                pypi_0    pypi
nvidia-cusparse-cu12      12.5.1.3                 pypi_0    pypi
nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.5.82                  pypi_0    pypi
openssl                   3.0.16               h5eee18b_0
opt-einsum                3.4.0                    pypi_0    pypi
optree                    0.14.1                   pypi_0    pypi
packaging                 24.2                     pypi_0    pypi
pip                       25.0            py312h06a4308_0
protobuf                  5.29.3                   pypi_0    pypi
pygments                  2.19.1                   pypi_0    pypi
python                    3.12.0               h996f2a0_0
readline                  8.2                  h5eee18b_0
requests                  2.32.3                   pypi_0    pypi
rich                      13.9.4                   pypi_0    pypi
setuptools                75.8.0          py312h06a4308_0
six                       1.17.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorflow                2.18.0                   pypi_0    pypi
termcolor                 2.5.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2025a                h04d1e81_0
urllib3                   2.3.0                    pypi_0    pypi
werkzeug                  3.1.3                    pypi_0    pypi
wheel                     0.45.1          py312h06a4308_0
wrapt                     1.17.2                   pypi_0    pypi
xz                        5.6.4                h5eee18b_1
zlib                      1.2.13               h5eee18b_1
```

Can you verify that these are the correct versions? 

Output from shell: 

```
Python 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 17:29:18) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2025-03-10 15:55:25.474408: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-10 15:55:25.484407: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1741640125.496393    4606 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741640125.500028    4606 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-10 15:55:25.512041: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> tf.config.list_physical_devices('GPU')
2025-03-10 15:55:37.500622: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: RESOURCE_EXHAUSTED: Failed call to cuInit: CUDA_ERROR_OUT_OF_MEMORY: out of memory
[]
```

**Comment by Corey4005** [comment]
Also @Venkat6871, I install python 3.9.21 and used pip install tensorflow[and-cuda] and got the same result:

```
python
Python 3.9.21 (main, Dec 11 2024, 16:24:11)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2025-03-10 16:15:17.136808: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-10 16:15:17.146938: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1741641317.158879    5197 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741641317.162466    5197 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-10 16:15:17.174416: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> print(tf.__version__)
2.18.0
>>> print(tf.config.list_physical_devices("GPU"))
2025-03-10 16:15:49.531676: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: RESOURCE_EXHAUSTED: Failed call to cuInit: CUDA_ERROR_OUT_OF_MEMORY: out of memory
[]
>>> exit()

nvidia-smi
Mon Mar 10 16:16:00 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.03             Driver Version: 572.60         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A4000               On  |   00000000:19:00.0 Off |                  Off |
| 41%   27C    P8             10W /  140W |      18MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA RTX A4000               On  |   00000000:1A:00.0 Off |                  Off |
| 41%   30C    P8              9W /  140W |       0MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA RTX A4000               On  |   00000000:67:00.0 Off |                  Off |
| 41%   29C    P8              5W /  140W |       0MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA RTX A4000               On  |   00000000:68:00.0  On |                  Off |
| 41%   31C    P8              9W /  140W |     510MiB /  16376MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

so, I installed the same python and the same tensorflow versions as you and it seems I am still getting the same error. 

There must be something wrong with my system that I am not understanding. 

Exact packages I installed to replicate your terminal outputs: 

```
# packages in environment at /home/user/anaconda3/envs/tf:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   2.1.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
ca-certificates           2025.2.25            h06a4308_0
certifi                   2025.1.31                pypi_0    pypi
charset-normalizer        3.4.1                    pypi_0    pypi
flatbuffers               25.2.10                  pypi_0    pypi
gast                      0.6.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.71.0                   pypi_0    pypi
h5py                      3.13.0                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
importlib-metadata        8.6.1                    pypi_0    pypi
keras                     3.9.0                    pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0
libclang                  18.1.1                   pypi_0    pypi
libffi                    3.4.4                h6a678d5_1
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
ml-dtypes                 0.4.1                    pypi_0    pypi
namex                     0.0.8                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
numpy                     2.0.2                    pypi_0    pypi
nvidia-cublas-cu12        12.5.3.2                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.5.82                  pypi_0    pypi
nvidia-cuda-nvcc-cu12     12.5.82                  pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.5.82                  pypi_0    pypi
nvidia-cuda-runtime-cu12  12.5.82                  pypi_0    pypi
nvidia-cudnn-cu12         9.3.0.75                 pypi_0    pypi
nvidia-cufft-cu12         11.2.3.61                pypi_0    pypi
nvidia-curand-cu12        10.3.6.82                pypi_0    pypi
nvidia-cusolver-cu12      11.6.3.83                pypi_0    pypi
nvidia-cusparse-cu12      12.5.1.3                 pypi_0    pypi
nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.5.82                  pypi_0    pypi
openssl                   3.0.16               h5eee18b_0
opt-einsum                3.4.0                    pypi_0    pypi
optree                    0.14.1                   pypi_0    pypi
packaging                 24.2                     pypi_0    pypi
pip                       25.0             py39h06a4308_0
protobuf                  5.29.3                   pypi_0    pypi
pygments                  2.19.1                   pypi_0    pypi
python                    3.9.21               he870216_1
readline                  8.2                  h5eee18b_0
requests                  2.32.3                   pypi_0    pypi
rich                      13.9.4                   pypi_0    pypi
setuptools                75.8.0           py39h06a4308_0
six                       1.17.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorflow                2.18.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.37.1                   pypi_0    pypi
termcolor                 2.5.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2025a                h04d1e81_0
urllib3                   2.3.0                    pypi_0    pypi
werkzeug                  3.1.3                    pypi_0    pypi
wheel                     0.45.1           py39h06a4308_0
wrapt                     1.17.2                   pypi_0    pypi
xz                        5.6.4                h5eee18b_1
zipp                      3.21.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1
```

**Comment by zainali-AT** [comment]
@Corey4005 What is the output of `nvcc --version`

**Comment by zainali-AT** [comment]
@Corey4005 Based on your output of `nvidia-smi`, the highest supported version of CUDA on your machine is 12.3, for which the corresponding [TensorFlow version is 2.17](https://www.tensorflow.org/install/source#gpu). 
I would suggest deleting the current CUDA toolkit 
```
sudo apt --purge remove nvidia-cuda-toolkit
sudo apt autoremove
```
Then installing CUDA 12.3 using the runfile option 
```
wget https://developer.download.nvidia.com/compute/cuda/12.3.0/local_installers/cuda_12.3.0_545.23.06_linux.run
sudo sh cuda_12.3.0_545.23.06_linux.run --silent --toolkit
```

Copy over the include and lib files to /usr/local as mentioned in the post-install screen
`nvcc --version` now should report 12.3

Then install tensorflow 2.17

**Comment by Corey4005** [comment]
> [@Corey4005](https://github.com/Corey4005) Based on your output of `nvidia-smi`, the highest supported version of CUDA on your machine is 12.3, for which the corresponding [TensorFlow version is 2.17](https://www.tensorflow.org/install/source#gpu). I would suggest deleting the current CUDA toolkit
> 
> ```
> sudo apt --purge remove nvidia-cuda-toolkit
> sudo apt autoremove
> ```
> 
> Then installing CUDA 12.3 using the runfile option
> 
> ```
> wget https://developer.download.nvidia.com/compute/cuda/12.3.0/local_installers/cuda_12.3.0_545.23.06_linux.run
> sudo sh cuda_12.3.0_545.23.06_linux.run --silent --toolkit
> ```
> 
> Copy over the include and lib files to /usr/local as mentioned in the post-install screen `nvcc --version` now should report 12.3
> 
> Then install tensorflow 2.17

Hi, @zainali-AT. Just to clarify... I need to install CUDA? It seems like it was suggested I do not need to install it per @Venkat6871's comments: 

"There is no need to manually install the CUDA Toolkit. I am attaching the official [documentation1](https://www.tensorflow.org/install/pip#windows-wsl2), [documentation2](https://www.tensorflow.org/install/source#gpu) for installing TensorFlow using pip and checking compatibility versions. Based on this documentation, I installed it, and it worked fine for me. Please find the details below for your reference."

When I run nvidia-smi, I get 12.8 now after installing [this driver](https://www.nvidia.com/en-us/drivers/details/241085/)

Also see the output:

 
![Image](https://github.com/user-attachments/assets/ad75006c-440b-4090-a1c0-b717f449ddd8)

To follow the documentation, it seems like it is suggesting I need to install CUDA 12.5, and provided the image above, it looks like I can support up to 12.8. Therefore, Tensorflow 2.18 should run per the `nvidia-smi` output I am showing above, correct? 

I ran the following commands to get 12.5: 

```
wget https://developer.download.nvidia.com/compute/cuda/12.5.0/local_installers/cuda_12.5.0_555.42.02_linux.run
sudo sh cuda_12.5.0_555.42.02_linux.run
``` 

I should note that it does not give me any output to copy files to any directory. However, the ouptut suggest that I set my paths. I do that here: 

```
export PATH=/usr/local/cuda-12.5/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.5/lib64:$PATH
```

Then, when I run `nvcc --version` I get:

![Image](https://github.com/user-attachments/assets/5899f396-3302-4cc5-87cb-43fcccd2e34f)


I am still getting the same error even after nvcc is installed. 

```
Python 3.9.21 (main, Dec 11 2024, 16:24:11)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2025-03-14 12:52:00.348718: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-14 12:52:00.358413: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1741974720.370189    1088 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741974720.373698    1088 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-14 12:52:00.387155: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> tf.__version__
'2.18.0'
>>> print(tf.config.list_physical_devices('GPU'))
2025-03-14 12:52:25.012176: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: RESOURCE_EXHAUSTED: Failed call to cuInit: CUDA_ERROR_OUT_OF_MEMORY: out of memory
[]

```

Can you help me understand what files I am supposed to be copying over? The only output I got from the cuda runfile was to set my paths.
