### ISSUE TITLE
Error when building Tensorflow

### ISSUE THREAD

**Issue by JackieTseng** [tensorflow/tensorflow#8892]
When I use `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` to build tensorflow, I got so many unknown warnings and one error as follow.
```
ERROR: /home/jackie/.cache/bazel/_bazel_jackie/c3ef17997092dfc0d7384ef6a12887e6/external/nccl_archive/BUILD:33:1: C++ compilation of rule '@nccl_archive//:nccl' failed: clang failed: error executing command /usr/bin/clang -MD -MF bazel-out/local_linux-opt/bin/external/nccl_archive/_objs/nccl/external/nccl_archive/src/broadcast.cu.pic.d ... (remaining 56 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
clang: error: Unsupported CUDA gpu architecture: sm_61
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 162.278s, Critical Path: 35.42s
```

For more information,
```
Ubuntu 16.04
CUDA 8.0
cuDNN v5.1
GTX-1080
tensorflow-gpu-1.1
```
bazel
```
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
```
clang
```
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda
```
configure
```
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
```

**Comment by gunan** [comment]
Looks like this is a problem between clang and cuda 8.0.
One option, you can use gcc as your host compiler.
We have not fully tested clang yet.

**Comment by JackieTseng** [comment]
@gunan Yeah, that's right. I just tested gcc to compile and it works though with warnings. Thanks!

**Comment by gunan** [comment]
Warnings are known issues, we are working on fixing them.
Thanks for verifying, closing the issue.
