### ISSUE TITLE
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by talos19** [tensorflow/tensorflow#8900]
I am trying to use tensorflow-gpu on my system. I have re-installed it many times, it gives the error give below. But when I use tensorflow-cpu it works fine. I have cuda 8.0 toolkit installed and cudnn 5.1
```
Traceback (most recent call last):
  File "finetune.py", line 17, in <module>
    import tensorflow as tf
  File "/home/saurabh/code/env/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/saurabh/code/env/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/saurabh/code/env/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/saurabh/code/env/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/saurabh/code/env/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by aselle** [comment]
I trust you didn't look for the common reasons and solution url included in that message. It wouldn't work, because it is a broken link that we should fix. Still, please try the stuff listed here:
[See common installation problems](https://www.tensorflow.org/install/install_linux)

**Comment by talos19** [comment]
Okay! Is there any other way I can safely install tensorflow-gpu and work with? I am using python 2.7 right now in virtual env. I have already installed tensorflow using the link you suggested it gives the same error! 
Also, is there any issue with cudnn or cuda toolkit installation?

**Comment by talos19** [comment]
I have fixed the error and tensorflow works with GPU! (with stackover flow [I](http://stackoverflow.com/questions/43162667/importerror-libcudart-so-8-0-cannot-open-shared-object-file-no-such-file-or-d) just re-installed everything. It worked. 
One important thing is  after` pip install --upgrade tensorflow-gpu`, it showed the same error. Thus, I used Requires CUDA toolkit 7.5 and CuDNN v5. For other versions, see "Install from sources" below.
`export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl 
` Then resolved the error by itself. Also, I was giving wrong **$CUDA_HOME** path

**Comment by gunan** [comment]
@aselle looks like the code is already fixed to point to the correct url, but it did not make it into the release yet.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/pywrap_tensorflow.py#L49
With the next release, the error message should be fixed.

@talos19 It looks like TF 0.10 is working for you. TF 0.10 was the last release with cuda 7.5 support. All the other release not working for you, and this version working for you means you have cuda 7.5 installed, contrary to what you reported in the issue.
If you would like to use the latest version of TF, you need to upgrade both your CUDA and cuDNN installations.
