### ISSUE TITLE
Execution Stuck after few steps in sess.run()

### ISSUE THREAD

**Issue by ajeetksingh** [tensorflow/tensorflow#8950]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

Execution is stuck in between steps. For few steps, it seems to run fine but after that the execution just halts without throwing any exception or the error.

### Environment info
Operating System: Ubuntu 14.04
GPU: NVIDIA TITAN X (Pascal)
GPU Memory: 12GB

Installed version of CUDA and cuDNN: 
-rw-r--r-- 1 root root   556000 Mar 29 05:10 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Mar 29 05:10 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Mar 29 05:10 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.61
-rwxr-xr-x 1 root root   415432 Mar 29 05:10 /usr/local/cuda/lib64/libcudart.so.8.0.61
-rw-r--r-- 1 root root   775162 Mar 29 05:10 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Apr  4 13:18 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       18 Apr  4 13:18 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.10
-rwxr-xr-x 1 root root 84163560 Apr  4 13:18 /usr/local/cuda/lib64/libcudnn.so.5.1.10
lrwxrwxrwx 1 root root       18 Apr  4 12:55 /usr/local/cuda/lib64/libcudnn.so.6 -> libcudnn.so.6.0.20
-rwxrwxrwx 1 root root 84163560 Apr  4 13:17 /usr/local/cuda/lib64/libcudnn.so.6.0.20
-rwxrwxrwx 1 root root 70364814 Apr  4 13:18 /usr/local/cuda/lib64/libcudnn_static.a

If installed from binary pip package, provide:

1. A link to the pip package you installed:

https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp34-cp34m-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I ran the mnist_deep.py script provided in tutorials.

### What other attempted solutions have you tried?
Previously, the display used to get hang showing error CUDA_LAUNCH_ERROR_TIMEOUT. On nvidia forum, someone suggested to switch off the X-server. I switched it off, but the problem still persisted.
I noticed that the script was hogging full memory of GPU, I tried to limit the allocation by using "allow_growth" flag. But the problem still persists. 

### Logs or other output that would be helpful
step 47, training accuracy 0.64
step 48, training accuracy 0.72
step 49, training accuracy 0.7
step 50, training accuracy 0.68
step 51, training accuracy 0.76
step 52, training accuracy 0.66
step 53, training accuracy 0.82
step 54, training accuracy 0.82
step 55, training accuracy 0.64
step 56, training accuracy 0.64
step 57, training accuracy 0.74
step 58, training accuracy 0.76
step 59, training accuracy 0.8
step 60, training accuracy 0.68
step 61, training accuracy 0.88
step 62, training accuracy 0.62
step 63, training accuracy 0.84
step 64, training accuracy 0.72
step 65, training accuracy 0.76
step 66, training accuracy 0.74
step 67, training accuracy 0.86
step 68, training accuracy 0.76
step 69, training accuracy 0.9
step 70, training accuracy 0.84
step 71, training accuracy 0.82
step 72, training accuracy 0.7

Attached is the screenshot of "nvidia-smi"
![nvidia-smi](https://cloud.githubusercontent.com/assets/1628210/24651492/a5b54ada-194b-11e7-8ba2-9c3ff6dc2901.PNG)

**Comment by drpngx** [comment]
@nealwu did we check recently that `mnist_deep` works?

**Comment by drpngx** [comment]
/CC: @jmchen-g since it's related to models.

**Comment by nealwu** [comment]
That's odd, I just ran it and it worked fine for me. @ajeetksingh can you make sure that you aren't running anything else on the GPU at the same time? And it's normal for it to use the full memory.

My output below:

```
step 0, training accuracy 0.14
step 100, training accuracy 0.76
step 200, training accuracy 0.9
step 300, training accuracy 0.82
...
step 19700, training accuracy 1
step 19800, training accuracy 1
step 19900, training accuracy 1
test accuracy 0.9932
```

**Comment by derekhh** [comment]
@ajeetksingh Can you check what your % CPU utilization is while TF hangs? What is the model of your motherboard?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
