### ISSUE TITLE
html5lib dependency issue

### ISSUE THREAD

**Issue by LiyuCode** [tensorflow/tensorflow#8971]
Install Tensorflow from source, met `html5lib` dependency issue:

```
Processing dependencies for tensorflow==1.1.0rc0
error: html5lib 1.0b8 is installed but html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 is required by {'bleach'}
```

### 1.1 OS:
Linux Mint 18.1 Cinnamon 64-bit
### 1.2 CUDA & CUDNN:
GPU: Nvidia Titan X Pascal
```
$ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   556000 Apr  5 00:46 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Apr  5 00:46 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Apr  5 00:46 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.61
-rwxr-xr-x 1 root root   415432 Apr  5 00:46 /usr/local/cuda/lib64/libcudart.so.8.0.61
-rw-r--r-- 1 root root   775162 Apr  5 00:46 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Apr  5 00:47 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Apr  5 00:47 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 79337624 Apr  5 00:47 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Apr  5 00:47 /usr/local/cuda/lib64/libcudnn_static.a
```
### 1.3 Tensorflow git version
```
$ git rev-parse HEAD
a9b7946540a27cc53bbdc9db1564196979fe30ae
```

### 1.4 Bazel version
```
$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
```

### 1.5 Installed html4lib
```
$sudo -H pip3 list
...
html5lib (0.9999999)
...
```

## 2. Reproduction
After clone the git, executing a script with the following commands to install [developer mode] :

```
bazel clean
./configure
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=cuda -k //tensorflow/tools/pip_package:build_pip_package
#bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
sudo rm -r _python_build
mkdir _python_build
cd _python_build
ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/* .
ln -s ../tensorflow/tools/pip_package/* .
sudo -H python3 setup.py develop
```

**Comment by peporiz0r** [comment]
I ran into a similar problem when I tried to use tensorboard.
First I got the error:

    No module named 'html5lib.filters.base'

I fixed it by unistalling html5lib via pip and installing version 0.9999.
LinuxMint, Anaconda in a python 3.5 env.

**Comment by LiyuCode** [comment]
Problem solved by changing the html5lib version to 0.

Step 1: edit `tensorflow/tools/pip_package/setup.py`, update
```
'html5lib == 1.0b8',
```
to 
```
'html5lib == 0.9999999',
```

Step 2: edit `tensorflow/workspace.bzl`, update
```
  native.new_http_archive(
      name = "org_html5lib",
      urls = [
          "http://bazel-mirror.storage.googleapis.com/github.com/html5lib/html5lib-python/archive/1.0b8.tar.gz",
          "https://github.com/html5lib/html5lib-python/archive/1.0b8.tar.gz",
      ],
      sha256 = "adb36c879264e8880b92589c4c4fe0814cd9d157b73328b14d728f48a6bab0a4",
      strip_prefix = "html5lib-python-1.0b8",
      build_file = str(Label("//third_party:html5lib.BUILD")),
  )
```
to
```
  native.new_http_archive(
      name = "org_html5lib",
      urls = [
          "http://bazel-mirror.storage.googleapis.com/github.com/html5lib/html5lib-python/archive/0.9999999.tar.gz",
          "https://github.com/html5lib/html5lib-python/archive/0.9999999.tar.gz",
      ],
      sha256 = "184257f98539159a433e2a2197309657ae1283b4c44dbd9c87b2f02ff36adce8",
      strip_prefix = "html5lib-python-0.9999999.tar.gz",
      build_file = str(Label("//third_party:html5lib.BUILD")),
  )
```

**Comment by asimshankar** [comment]
Do yo need to build from head? Could you build from the release branch (or better still use the release binaries) instead?

Appreciate the report, but the release branches will be more stable.

(FYI: @dandelionmane @jart )

**Comment by jart** [comment]
Wow it looks like html5lib tags each release with two IDs. One <1.0 and one >1.0. https://pypi.python.org/pypi/html5lib So 0.9999999 actually is the same version we're using now, which is 1.0b8. What a nightmare. Sending a PR now.

CC: @dandelionmane
