### ISSUE TITLE
TensorFlow with CUDA: RTX 5xxx series isn't supported (CUDA_ERROR_INVALID_HANDLE)

### ISSUE THREAD

**Issue by weyn9q** [tensorflow/tensorflow#90291]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.18

### Custom code

Yes

### OS platform and distribution

WSL2

### CUDA/cuDNN version

12.8

### GPU model and memory

5070TI

### Current behavior?

hi guys. i upgraded my GPU to 5070ti and found that tensorflow is still not working with new nvidia cards

honestly i knew that can be problems. but its been 3 month since nvidia released new gpu, i thought now should be no prob already.

any idea how long it will take until at least there will be a nightly version which will fix the problem?
like 1-2 weeks or half a year ? :)

or maybe someone found an easy way to fix it?

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.Input(shape=(20,)),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])
```

### Relevant log output

```shell
2025-03-31 14:23:13.091967: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-31 14:23:13.734399: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1743398598.268271   13190 gpu_device.cc:2429] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
W0000 00:00:1743398598.270049   13190 gpu_device.cc:2429] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
I0000 00:00:1743398598.408238   13190 gpu_device.cc:2018] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13123 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 5070 Ti, pci bus id: 0000:01:00.0, compute capability: 12.0
2025-03-31 14:23:18.851409: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:40] 'cuModuleLoadData(&module, data)' failed with 'CUDA_ERROR_INVALID_PTX'

2025-03-31 14:23:18.851466: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:40] 'cuModuleGetFunction(&function, module, kernel_name)' failed with 'CUDA_ERROR_INVALID_HANDLE'

2025-03-31 14:23:18.851502: W tensorflow/core/framework/op_kernel.cc:1843] INTERNAL: 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE'
2025-03-31 14:23:18.851526: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INTERNAL: 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE'
Traceback (most recent call last):
  File "/mnt/c/Users/alex/desktop/test111.py", line 3, in <module>
    model = tf.keras.Sequential([
  File "/home/alexflame/.local/lib/python3.10/site-packages/keras/src/models/sequential.py", line 76, in __init__
    self._maybe_rebuild()
  File "/home/alexflame/.local/lib/python3.10/site-packages/keras/src/models/sequential.py", line 149, in _maybe_rebuild
    self.build(input_shape)
  File "/home/alexflame/.local/lib/python3.10/site-packages/keras/src/layers/layer.py", line 229, in build_wrapper
    original_build_method(*args, **kwargs)
  File "/home/alexflame/.local/lib/python3.10/site-packages/keras/src/models/sequential.py", line 195, in build
    x = layer(x)
  File "/home/alexflame/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/alexflame/.local/lib/python3.10/site-packages/keras/src/backend/tensorflow/core.py", line 152, in convert_to_tensor
    return tf.cast(x, dtype)
tensorflow.python.framework.errors_impl.InternalError: {{function_node __wrapped__Cast_device_/job:localhost/replica:0/task:0/device:GPU:0}} 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE' [Op:Cast] name:
```

**Comment by weyn9q** [comment]
spend whole day to build custom tensorflow build but didnt succeed.

now finally found how to solve this problem. not perfect solution as it could be, but still better then nothing :)

https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel-25-02.html#

**Comment by weyn9q** [comment]
ohh seems its impossible. thinking about move to pytorch. i dont want but :(

but i really stuck here with this problems and i dont think will be any updates here soon. 
i cant run any of my codes with new GPU.
nvidia container works but its soo complicated. docker still not fully optimizated with many mistakes. cant work good.

example - i have my own pretrained model which i am using to train RL agent. lets say i have 2 code.
first one is for train model ( later - pretrained)
second is use pretrained get embeddings train RL agent.

without nvidia docker i just cant run any of them coz of CUDA errors.
with docker first code can run if will fix some mistakes which happens only if use docker. but.
second code i cant deserialize custom layers from pretrained idk why. coz of docker i think. probably because they were builded with another drivers.

i decided to check if i will train model in docker again and will try to use it in second code will it work or no. it is not working.
i still cant deserialize custom layers even with newly trained model. i am giving up.

before on 4xxx videocard everything was perfect. now idk what to do

**Comment by AndrewTG5** [comment]
Same issue same scenario here. Tried updating every driver I could think of. Hoping for at least a nightly version soon so I can work again.

**Comment by kyo-x17** [comment]
Same issue with tf-nightly-2.20.0.dev20250602. Looking forward to the updates.

**Comment by mardock2009** [comment]
Im built yesterday and finally works :)
Tested RTX 5070ti and WSL-2 Ubuntu 22.04
Python 3.10.12
cuda 12.8.0
sm12.0
cudnn 9.10.2_1.0
tf_nightly-2.20.0.dev0+selfbuilt-cp310-cp310-linux_x86_64.whl

![Image](https://github.com/user-attachments/assets/2d852549-95c9-400f-9616-33eef86c685a)

https://github.com/mardock2009/tensorflow-working-DeepfaceLab-for-RTX5070ti/blob/main/README.md

compile with clang LLVM 20.1.7 solved issue ...
topic to close

**Comment by WoDeXinHaoLeng69** [comment]
shit, i try all tensorflow but it doesn't work, the only thing i can do is to use cpu run my project
BTW my computer and environment -> GPU 5090 CUDA 12.8

**Comment by heapsoftware** [comment]
Getting same issue here when trying to use the latest TensorFlow nvidia docker

**Comment by bignollo** [comment]
Same Issue, Tried the solutions mentioned on other threads with no luck

**Comment by larschristensen** [comment]
@bignollo Nightly is now built using cuda 12.8, so have you tried using that? It works for me on RTX 5090.

**Comment by 456Xander** [comment]
Tried it on my 5080 machine, using nightly works, but I still get a warning: 
`TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0a. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.`

**Comment by larschristensen** [comment]
> Tried it on my 5080 machine, using nightly works, but I still get a warning: `TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0a. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.`

I get the same warning, but it works just fine.

**Comment by bignollo** [comment]
> [@bignollo](https://github.com/bignollo) Nightly is now built using cuda 12.8, so have you tried using that? It works for me on RTX 5090.

YES, It's working now!!!! thanks for the advice.
Does anyone knows when the nightly will become the stable version?

**Comment by rlogwood** [comment]
Thanks all for the news!! I'm also able to use TensorFlow with the nightly build on Ubuntu 25.10 with 5080, tests here: https://github.com/rlogwood/gpu_tests

**Comment by PenDZ-Alter** [comment]
> [@bignollo](https://github.com/bignollo) Nightly is now built using cuda 12.8, so have you tried using that? It works for me on RTX 5090.

I have tried in 2026 but it's not working now :(

Is it because nightly built with CUDA 12.9? or i should install CUDA Toolkit first in WSL2?

**Comment by larschristensen** [comment]
> > [@bignollo](https://github.com/bignollo) Nightly is now built using cuda 12.8, so have you tried using that? It works for me on RTX 5090.
> 
> I have tried in 2026 but it's not working now :(
> 
> Is it because nightly built with CUDA 12.9? or i should install CUDA Toolkit first in WSL2?

I have not tried on WSL2, but try to install it in a clean (virtual) environment using `pip install tf-nightly[and-cuda]`. That should bring in the needed CUDA libraries automatically.

**Comment by PenDZ-Alter** [comment]
> I have not tried on WSL2, but try to install it in a clean (virtual) environment using `pip install tf-nightly[and-cuda]`. That should bring in the needed CUDA libraries automatically.

I did, when i see `cuda_compute_capabilities` in tf-nightly, it returns like this : 

```python
['sm_60', 'sm_70', 'sm_80', 'sm_89', 'compute_90']
```

Seems like, tf-nightly is not build with `sm_120` or `compute_120` on WSL2, how unfortunate 😪

**Comment by PenDZ-Alter** [comment]
But, it solved when i try using docker from NGC anyway, using this command : 

```bash
docker pull nvcr.io/nvidia/tensorflow:25.01-tf2-py3
```

**Comment by mitulgarg** [comment]
I have a tool that may help solve this issue 
https://github.com/mitulgarg/env-doctor

**Comment by CamiloMunozb1** [comment]
Hey guys, I tried using PyTorch for a 5070 and it worked on CUDA version 12.8. It's not a complete solution for TensorFlow, but until something else is fixed, it's a viable option. For anyone interested, here's the download link. 
https://pytorch.org/get-started/locally/

**Comment by ngothiensinh** [comment]
Hope this does help. I came up with a custom Docker container of Nvidia, accept older Tensorflow version but with newer CUDA version.
Post here: https://medium.com/p/30d3f488271b

**Comment by pmaselkowski** [comment]
I accidentally figured out solution. When importing `torch`, suddenly TensorFlow detects GPU. I have RTX 5070 Ti, TensorFlow 2.21.0

```python
import tensorflow as tf

print(tf.config.list_physical_devices())
```

```bash
python tf_check.py 
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
```

```python
import tensorflow as tf
import torch
print(tf.config.list_physical_devices())
```

```bash
python tf_check.py 
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

```

**Comment by Syraxius** [comment]
Hi guys :D

For convenience, you can download and install the pre-built and packaged .whl files here (TensorFlow 2.21 stable for Python 3.10, 3.11, 3.12 and 3.13)

https://github.com/Syraxius/TensorflowDockerBuilder/releases/tag/v2.21.0-sm120-cuda128-py310-py313

If needed, you can also build it yourself in Docker using this repository

Tested on my own RTX 5090 but since it targets sm_120 it could work for...
- GeForce RTX 5090
- GeForce RTX 5080
- GeForce RTX 5070 Ti
- GeForce RTX 5070
- GeForce RTX 5060 Ti
- GeForce RTX 5060
- GeForce RTX 5050
- NVIDIA RTX PRO 6000 Blackwell Server Edition
- NVIDIA RTX PRO 4500 Blackwell Server Edition
- NVIDIA RTX PRO 6000 Blackwell Workstation Edition
- NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
- NVIDIA RTX PRO 5000 Blackwell
- NVIDIA RTX PRO 4500 Blackwell
- NVIDIA RTX PRO 4000 Blackwell
- NVIDIA RTX PRO 4000 Blackwell SFF Edition
- NVIDIA RTX PRO 2000 Blackwell

**Comment by Venkat6871** [comment]
Hi @weyn9q,

Apologies for the delay, and thanks for your patience.

This issue was originally reported with TensorFlow 2.18 on an RTX 5070 Ti (Blackwell, compute capability 12.0). TensorFlow has since had engineering work around Blackwell/compute capability 12.0 support, including changes to the CUDA build configuration.

Could you please try the latest stable TensorFlow release with the currently supported CUDA/driver configuration and let us know whether you still see the `CUDA_ERROR_INVALID_PTX` / `CUDA_ERROR_INVALID_HANDLE` errors?
If the issue still reproduces, please provide the TensorFlow version, NVIDIA driver version, CUDA version, GPU model, and the relevant error output so we can determine whether the remaining issue is covered by the existing Blackwell tracking work.

Thank you!
