### ISSUE TITLE
New version of nVidia Windows GPU driver causing TF in WSL process crash.

### ISSUE THREAD

**Issue by sunshinejnjn** [tensorflow/tensorflow#92251]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.19.0

### Custom code

No

### OS platform and distribution

WSL Ubuntu 24.04.1

### Python version

3.12

### CUDA/cuDNN version

any 12.x

### GPU model and memory

rtx 4090

### Current behavior?

With GPU driver 576.02, this happens:

If you set the environment variable with 
`os.environ["CUDA_VISIBLE_DEVICES"] = ""`
to disable the CUDA GPU.
TensorFlow will fail with a "free(): double free detected in tcache 2" if you check GPU availability with 
`physical_devices = tf.config.list_physical_devices('GPU')`
and the whole process will crash (leading to a Jupyter kernel death).

Drivers with version 572.42 and before work fine.
Tested with TF 2.18 and 2.19, both have the same behavior.
Also, tested with CUDA 12.5 and 12.6. Same behaviors, too.

On native Linux Ubuntu 24.04.1 with nvidia-drives-570-server, everything is fine.

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ["CUDA_VISIBLE_DEVICES"] = ""

import tensorflow as tf

try:
    physical_devices = tf.config.list_physical_devices('GPU')
    print(physical_devices)
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
except:
    print("gpu not found, gpu init error!")
```

### Relevant log output

```shell
free(): double free detected in tcache 2

crash (core dumped)
```

**Comment by KAVYANSHTYAGI** [comment]
We must add a guard check before accessing physical_devices[0].

Minimal correct patch would look like this:


physical_devices = tf.config.list_physical_devices('GPU')
if physical_devices:  # Only if there is at least one GPU
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
else:
    print("gpu not found, gpu init error!")


This solves it cleanly because:

-No indexing into an empty list.

-No invalid memory operations.

-No double free crash.

**Comment by sunshinejnjn** [comment]
Thanks KAVYANSHTYAGI.

But, only this operation `tf.config.list_physical_devices('GPU')` itself would cause the crash. No matter if there is a returned value or not.

The code posted simply demonstrates a usual usage which works fine with *normal* GPU drivers.
Tested with over 5 versions of GPU drivers and various WSL VMs last afternoon. The new GPU driver is indeed the root cause of this crash bug.

**Comment by KAVYANSHTYAGI** [comment]
Thanks for the clarification!

You're right 
I now understand that the crash happens at list_physical_devices('GPU') itself, not later during device usage.

In that case, I think the more robust fix would be to wrap the call to context.context().list_physical_devices('GPU') in a try-except block, so that if the driver misbehaves, TensorFlow can catch the error and handle it gracefully (e.g., log error and return empty list) rather than letting the process crash.

**Comment by sunshinejnjn** [comment]
Just wanna report that the newest version 576.28 will cause the same problem: kernel died / crash.

**Comment by nocanstillbb** [comment]
```bash
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7ded859 in __GI_abort () at abort.c:79
#2  0x00007ffff7e58266 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7f82298 "%s\n") at ../sysdeps/posix/libc_fatal.c:156
#3  0x00007ffff7e602fc in malloc_printerr (str=str@entry=0x7ffff7f845d0 "free(): double free detected in tcache 2") at malloc.c:5347
#4  0x00007ffff7e61f6d in _int_free (av=0x7ffff7fb7b80 <main_arena>, p=0x9fd1ac0, have_lock=0) at malloc.c:4201
#5  0x00007fff1138e005 in ?? () from /usr/lib/wsl/drivers/nvltsi.inf_amd64_ebbed3c683b430e5/libcuda.so.1.1
#6  0x00007fff113a20a9 in ?? () from /usr/lib/wsl/drivers/nvltsi.inf_amd64_ebbed3c683b430e5/libcuda.so.1.1
#7  0x00007fff111cc29d in ?? () from /usr/lib/wsl/drivers/nvltsi.inf_amd64_ebbed3c683b430e5/libcuda.so.1.1
#8  0x00007fff111cd695 in ?? () from /usr/lib/wsl/drivers/nvltsi.inf_amd64_ebbed3c683b430e5/libcuda.so.1.1
#9  0x00007fff1118d5b4 in ?? () from /usr/lib/wsl/drivers/nvltsi.inf_amd64_ebbed3c683b430e5/libcuda.so.1.1
#10 0x00007fff11226ec2 in ?? () from /usr/lib/wsl/drivers/nvltsi.inf_amd64_ebbed3c683b430e5/libcuda.so.1.1
#11 0x00007fff111b2a6b in cuInit () from /usr/lib/wsl/drivers/nvltsi.inf_amd64_ebbed3c683b430e5/libcuda.so.1.1
#12 0x00007ffff3adca0a in ?? () from /root/yolo11_venv/lib/python3.9/site-packages/torch/lib/../../nvidia/cuda_runtime/lib/libcudart.so.12
#13 0x00007ffff3adfe00 in ?? () from /root/yolo11_venv/lib/python3.9/site-packages/torch/lib/../../nvidia/cuda_runtime/lib/libcudart.so.12
#14 0x00007ffff7db94df in __pthread_once_slow (once_control=0x7ffff3d531f0, init_routine=0x7ffff3adfdb0) at pthread_once.c:116
#15 0x00007ffff3b29179 in ?? () from /root/yolo11_venv/lib/python3.9/site-packages/torch/lib/../../nvidia/cuda_runtime/lib/libcudart.so.12
#16 0x00007ffff3ad03cf in ?? () from /root/yolo11_venv/lib/python3.9/site-packages/torch/lib/../../nvidia/cuda_runtime/lib/libcudart.so.12
#17 0x00007ffff3af3c5a in cudaGetDeviceCount () from /root/yolo11_venv/lib/python3.9/site-packages/torch/lib/../../nvidia/cuda_runtime/lib/libcudart.so.12
#18 0x00007fffa0ddb28a in c10::cuda::device_count() () from /root/yolo11_venv/lib/python3.9/site-packages/torch/lib/libc10_cuda.so
#19 0x00007fffebe9ea13 in THCPModule_getDeviceCount_wrap(_object*, _object*) () from /root/yolo11_venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
```

```bash
(yolo11_venv) root@7518018792c3:~# nvidia-smi
Fri May 23 09:36:00 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.57.04              Driver Version: 576.52         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060        On  |   00000000:01:00.0  On |                  N/A |
| N/A   47C    P8              6W /   80W |     490MiB /   6144MiB |     21%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A              25      G   /Xwayland                             N/A      |
+-----------------------------------------------------------------------------------------+
(yolo11_venv) root@7518018792c3:~#
```

**Comment by Gumo-A** [comment]
I experienced the same problem today. The culprit was the line `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"` as OP said.

In my env (see screenshot below), running `tf.config.set_visible_devices([], "GPU")` just after tf import fixed the problem for me,
the script I'm running uses tf without GPU as I wanted and the double free error does not occur.

<img width="1999" height="1036" alt="Image" src="https://github.com/user-attachments/assets/94e5094d-6cac-4fb3-87f5-eadf9bceffa8" />

**Comment by alert101** [comment]
I've been experiencing this same issue.

@Gumo-A Thank you for the workaround, works fine.

**Comment by mitulgarg** [comment]
WSL2 GPU forwarding has specific requirements - you might have installed 
drivers inside WSL2 (wrong) or be missing library paths.

env-doctor diagnoses WSL2 GPU issues:

pip install env-doctor
env-doctor check

GitHub: https://github.com/mitulgarg/env-doctor

**Comment by BarclayII** [comment]
Upgrading NVIDIA driver to 591.74 solved the problem for me.

**Comment by Kayyuri** [comment]
Hi @sunshinejnjn,
Could you please try using the latest version of NVIDIA driver and  let us know if this issue has been resolved from your end? 

Thanks!
