### ISSUE TITLE
PyCharm won't correctly import tensorflow

### ISSUE THREAD

**Issue by BDHU** [tensorflow/tensorflow#9530]
I get the following error when I try to run a python program:

`ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory`

I understand this is a simple error most people would encounter when they start tensorflow. I did checked the solutions on Stackoverflow and I managed to run the same program in Terminal. What I did is I made an virtualenv and I activated it and when I try using python3 to run the program it successfully proceeds without any error. However the error always appear when I run the program in PyCharm even with python interpreter set to the location of virtualenv I created. Can someone tell me why as I had no idea why it works in terminal but not with PyCharm.

**Comment by BDHU** [comment]
I've read this Stackoverflow post [Pycharm environment different than command line](https://stackoverflow.com/questions/19715724/pycharm-environment-different-than-command-line) and it seems that the problem is not related to tensorflow but PrCharm itself. PyCharm won't reserve bash environment unless evoked from command line. So the solution to he problem is to type `charm` from command line and everything works fine now. Closing this issue now.

**Comment by infelane** [comment]
Got the same today, but for 7.0:
`ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory` 
Above solution is still relevant

**Comment by chamwen** [comment]
![screenshot from 2018-06-01 12-32-39](https://user-images.githubusercontent.com/33860245/40821210-0645be68-6598-11e8-92a1-8085d97ff9f2.png)
just add an environment variable `LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH` on Pycharm, it's the bug of PyCharm

**Comment by YoungKang1222** [comment]
when I use remote intepreter in my linux, I encounter the problem in my local windows Pycharm:
ImportError: libcublsa.so.9.0: cannot open shared object file: No such file or directory

**Comment by inspirepassion** [comment]
This helps which is from Stackoverflow @Sachin G. (https://stackoverflow.com/questions/27063361/how-to-run-pycharm-in-ubuntu-run-in-terminal-or-run)
> The question is already answered, Updating answer to add the PyCharm bin directory to $PATH var, so that pycharm editor can be opened from anywhere(path) in terminal.
> 
> Edit the bashrc file,
>` nano .bashrc`
> 
> Add following line at the end of bashrc file
> `export PATH="<path-to-unpacked-pycharm-installation-directory>/bin:$PATH"`
> 
> Now you can open pycharm from anywhere in terminal
> `pycharm.sh`

**Comment by javierfs** [comment]
Same for me @toxato . I am running Pycharm on a remote interpreter (in a remote virtual-env). It seems it does not save the paths. As @chamwen says, this can be solved. However, Pycharm will recognize /usr/local/cuda/lib64:$LD_LIBRARY_PATH as the path in your local computer, not remotely. Any ideas how can we set up that path in such a way that Pycharm will recognize this as a remote path?

**Comment by javierfs** [comment]
I think I fixed it @toxato. You should create a shell wrapper (remoteEnv.sh) which looks like: 

!/bin/bash
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}


# added by Anaconda3 installer
export PATH="/home/javier/anaconda3/bin:$PATH"



source /home/javier/anaconda3/bin/activate AIenv
#Now we call python which should be python from our virtualenv
python "$@"


and then configure that as your remote interpreter. Hope it helps!

**Comment by MingleiLI** [comment]
> when I use remote intepreter in my linux, I encounter the problem in my local windows Pycharm:
ImportError: libcublsa.so.9.0: cannot open shared object file: No such file or directory

I have the same problem when using remote interpreter.

**Comment by nkzyj** [comment]
![default](https://user-images.githubusercontent.com/41919591/50206391-362ec500-03a6-11e9-858d-277ee5723d4b.png)
Add a environment variable LIBRARY_PATH=/usr/local/cuda-9.0/lib64(depends on your path), then you don't need to start pycharm form console.
![default](https://user-images.githubusercontent.com/41919591/50206482-8574f580-03a6-11e9-8a5f-9cf25a6dd515.png)

**Comment by GlowingHorse** [comment]
> ![screenshot from 2018-06-01 12-32-39](https://user-images.githubusercontent.com/33860245/40821210-0645be68-6598-11e8-92a1-8085d97ff9f2.png) just add an environment variable `LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH` on Pycharm, it's the bug of PyCharm

I also found this problem when debug tensorflow 2.12 with pycharm on Ubuntu 22.04.
And I solved it by adding Environment variables both for the Python Console (Settings -> Build, Execution, Deployment -> Console -> Python Console) and in the Run/Debug Configuration.

Because I use the TF 2.12 version, as official website's suggestions, the setting for is like:
```LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib```.
Here, you should replace CONDA_PREFIX and CUDNN_PATH with your absolute path, like:
```LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shi/anaconda3/envs/tf2/lib/:/home/shi/anaconda3/envs/tf2/lib/python3.9/site-packages/nvidia/cudnn/lib```.

**Comment by Inmoresentum** [comment]
After doing a lot of research, I was finally able to solve my issue.
I followed the instructions from the [official page](https://www.tensorflow.org/install/pip) for the initial setup.
After that it was able to detect that I had GPU using terminal zsh, but whenever I wanted to train a model, it would error out:

```shell
    Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice.
    ...
    Couldn't invoke ptxas --version
    ...
    InternalError: libdevice not found at ./libdevice.10.bc [Op:__some_op]
```

Which I fixed by following
`Ubuntu 22.04` section from the [official page](https://www.tensorflow.org/install/pip).
However, now I can only run the models from the shell and whenever I try to run the model meaning `.py`  or `.ipynb` file
from PyCharm it again shows the previously mentioned errors (1. PyCharm not detecting the GPU, which I 
fixed by adding an environment variable `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/{your_user}/miniconda3/envs/tf/lib/:/home/{your_user}/miniconda3/envs/tf/lib/python3.9/site-packages/nvidia/cudnn/lib`)
and this fix is also mentioned in the previous posts as well. 2. `Couldn't invoke ptxas --version` which I fixed by adding another environment variable in the configuration
`XLA_FLAGS=--xla_gpu_cuda_data_dir=/home/{your_username}/miniconda3/envs/tf/lib/`).

I am using `Pop!_OS 22.04` with `TensorFlow version 2.13.0`

The above two environment variables fixed the issue for PyCharm. At least for me :)
