### ISSUE TITLE
TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0 CUDA_ERROR_INVALID_HANDLE

### ISSUE THREAD

**Issue by MikeHallettUK** [tensorflow/tensorflow#97387]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf-nightly-2.21.0.dev20250722

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Mobile device

no

### Python version

3.11

### CUDA/cuDNN version

12.8.1/9.8

### GPU model and memory

RTX5080 16gb

### Current behavior?

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1753232013.685876   24341 gpu_device.cc:2431] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.

CUDA_ERROR_INVALID_HANDLE

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.client import device_lib
import keras

print("Keras version: ", keras.__version__)

print(device_lib.list_local_devices())

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor = tf.convert_to_tensor(x)

print("Tensor: ", tensor)

# ========================================== define model ======================================
input_data = keras.Input(shape = (8,1))

# Data Encoder
dx = keras.layers.Dense(16, activation='relu')(input_data)

print("dx", dx.shape)
```

### Relevant log output

```shell
Keras version:  3.10.0.dev2025072204
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1753232219.958168   25258 gpu_device.cc:2431] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
I0000 00:00:1753232220.029881   25258 gpu_device.cc:2020] Created device /device:GPU:0 with 11546 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 5080, pci bus id: 0000:01:00.0, compute capability: 12.0
W0000 00:00:1753232220.033014   25258 gpu_device.cc:2431] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
W0000 00:00:1753232220.035555   25258 gpu_device.cc:2431] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
I0000 00:00:1753232220.037159   25258 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 11546 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 5080, pci bus id: 0000:01:00.0, compute capability: 12.0
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13363326776403279234
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 12107055104
locality {
  bus_id: 1
  links {
  }
}
incarnation: 7207726466463925696
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 5080, pci bus id: 0000:01:00.0, compute capability: 12.0"
xla_global_id: 416903419
]
Tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int64)
2025-07-23 10:57:00.115747: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:40] 'cuModuleLoadData(&module, data)' failed with 'CUDA_ERROR_INVALID_PTX'

2025-07-23 10:57:00.115757: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:40] 'cuModuleGetFunction(&function, module, kernel_name)' failed with 'CUDA_ERROR_INVALID_HANDLE'

2025-07-23 10:57:00.115761: W tensorflow/core/framework/op_kernel.cc:1842] INTERNAL: 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE'
2025-07-23 10:57:00.115766: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INTERNAL: 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE'
Traceback (most recent call last):
  File "/home/mike/catkin_ws2/src/mypy311/scripts/tftest.py", line 19, in <module>
    dx = keras.layers.Dense(16, activation='relu')(input_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/PycharmProjects/py311/.venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/mike/PycharmProjects/py311/.venv/lib/python3.11/site-packages/keras/src/backend/tensorflow/core.py", line 152, in convert_to_tensor
    return tf.cast(x, dtype)
           ^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InternalError: {{function_node __wrapped__Cast_device_/job:localhost/replica:0/task:0/device:GPU:0}} 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE' [Op:Cast] name: 

Process finished with exit code 1
```

**Comment by MikeHallettUK** [comment]
Runs fine with PYTORCH...

**Comment by Venkat6871** [comment]
Hi @MikeHallettUK ,
Thank you for raising your issue here. I tried running your code on Colab using TensorFlow version 2.19.0 with GPU support, and it worked fine for me. I am attaching a [gist](https://colab.sandbox.google.com/gist/Venkat6871/eca82a6e1769c891d2c82c38d6a3c7e1/97387_tf_2-19-0-v.ipynb) here for your reference. Please let me know if I missed anything.

Additionally, I noticed that you have installed incompatible versions. Could you please update them as per the documentation and let us know if the issue still persists? Here is the [documentation](https://www.tensorflow.org/install/source#gpu) for your reference.

Also, note that there are ongoing discussions and similar reports related to this GPU. You may find these issues helpful:
#90291, #89272

Thank you!

**Comment by MikeHallettUK** [comment]
Thanks for such quick reply... Yes, I know my code runs on other GPUs... but sadly not on Nvidia 50X0 (compute capability 12.0).

and I have struggled to build from source (as per others on CUDA 12.8.1/9.8) : but I failed.  The compile stops ~ 25% in, with:

"clang: error: unsupported CUDA gpu architecture: sm_120" 

.. any ideas how to fix that ?

Mike

**Comment by Donya-Vafanejad** [comment]
@Donya-Vafanejad

**Comment by paicaloid** [comment]
> Thanks for such quick reply... Yes, I know my code runs on other GPUs... but sadly not on Nvidia 50X0 (compute capability 12.0).
> 
> and I have struggled to build from source (as per others on CUDA 12.8.1/9.8) : but I failed. The compile stops ~ 25% in, with:
> 
> "clang: error: unsupported CUDA gpu architecture: sm_120"
> 
> .. any ideas how to fix that ?
> 
> Mike

I solve this error by follow [this](https://github.com/tensorflow/tensorflow/issues/89272#issuecomment-2899591572).
It fix error `clang: error: unsupported CUDA gpu architecture: sm_120` and build it successful but when i install, it got the same error...

```
2025-07-25 04:27:08.400210: W tensorflow/core/framework/op_kernel.cc:1842] INTERNAL: 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE'
2025-07-25 04:27:08.400242: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INTERNAL: 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE'
   ❌ Computation test failed: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE' [Op:Mul] name:
```

For me, i change to use this image `nvcr.io/nvidia/tensorflow:25.02-tf2-py3` with Nvidia 5060 and my code is work right now.

**Comment by water980** [comment]
Hi everyone,

I’m currently running TensorFlow with an RTX 5000 series GPU. At the moment, the only way I can get it to work is by using NVIDIA’s NGC container, which technically runs but is not the same as having native support as described in the official documentation.

I also noticed that this issue has been open for over a month, and there are at least two other open issues describing the same problem with RTX 5000 / compute capability 12.0.

Could you please share if there has been any progress on adding native support for RTX 5000 GPUs? Is there a planned timeline or an upcoming release where this will be included?

It would be really helpful to know if work is ongoing, or if we should continue relying on containers and custom builds for the foreseeable future.

Thanks a lot for your work!

**Comment by doiko** [comment]
Hi everyone,
this issue still exists on the RTX 5000 series (compute capability 12.0). Is there any plan to mitigate it or an expected timeline for native support? It would be helpful to know if work is ongoing or if relying on containers/custom builds will remain the only option.
Thanks a lot for your work!

**Comment by arrunkumarr** [comment]
Hello all,

Any luck for WSL2 with Compute capability 12.0 " TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer."

any ETA/ workarounds for Blackwell ?

nvidia-smi
Sun Nov 
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.102.01             Driver Version: 581.57         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5080        On  |   00000000:01:00.0  On |                  N/A |
|  0%   35C    P8             11W /  360W |     960MiB /  16303MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+


Thanks!

**Comment by MikeHallettUK** [comment]
Interesting this is taking so long ? 

Is there a reason not to support Nvidia key product Blackwell ?

**Comment by larschristensen** [comment]
@MikeHallettUK I believe nightly is now built using cuda 12.8, so it should work. I just did a small test with nightly on an RTX 5090 and it seems to work out-of-the-box.

**Comment by mihaimaruseac** [comment]
As a reminder: each version of TF is targeting a specific CUDA release. Other versions _might_ work (but the code would need to be compiled, either by the JIT compiler or you actually having to compile a version of TF from source), but these are not really supported by the TF team.

**Comment by pavansai018** [comment]
> [@MikeHallettUK](https://github.com/MikeHallettUK) I believe nightly is now built using cuda 12.8, so it should work. I just did a small test with nightly on an RTX 5090 and it seems to work out-of-the-box.

Yes. I too faced the same issue. Installing tf-nightly solved the issue.

**Comment by mihaimaruseac** [comment]
In that case, it will be fully resolved with the next TF release.

**Comment by MikeHallettUK** [comment]
on Ubuntu 24.04 with "nvidia-smi"   showing Driver Version: 580.95.05      CUDA Version: 13.0 ...

within a .venv ...   pip3 install tf-nightly[and-cuda]   when tested gives error:

W0000 00:00:1763102316.477334    4144 cuda_executor.cc:1802] GPU interconnect information not available: 
INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.

W0000 00:00:1763102316.477348    4144 gpu_device.cc:2362] Cannot dlopen some GPU libraries. 
Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU.

? Do I need to downgrade CUDA from v 13.0 ?  ... pytorch still works fine.

**Comment by larschristensen** [comment]
@MikeHallettUK Works for me with nvidia driver version 580 with RTX 5090 on Ubuntu 24.04. Have you tried doing `pip3 install tf-nightly[and-cuda]` in a fresh virtual env? If you have cuda 13 installed in your virtual env, then yes you need to downgrade to cuda 12.8/12.9.

**Comment by pavansai018** [comment]
RTX 50XX has compute capability 12.0 - a very new architecture. Stable TensorFlow versions lack pre-compiled GPU kernels for this architecture, causing JIT compilation failures for certain operations (especially float32).

**Error Mechanism:**

- TensorFlow looks for pre-compiled GPU kernels → Not found for compute capability 12.0

- Attempts JIT compilation from PTX code → Fails with CUDA_ERROR_INVALID_PTX

- Float32 operations fail while some int32 operations work (different kernels)

I too faced the same problem with my RTX 5060 GPU. Below are the steps to be followed so that you can solve the issue.
**Step by Step Solution:**
I have created a conda environment with Python version 3.11.4
`conda create --name tf_gpu python=3.11.4 pip`
`conda activate tf_gpu`

Install CUDA toolkit. (Provides CUDA 12.5.1 runtime libraries that match TensorFlow’s requirements. Using conda avoids system-wide installation conflicts.)

`conda install nvidia/label/cuda-12.5.1::cuda-toolkit`

Install Tensorflow Nightly. Nightly builds contain latest GPU kernel support, including pre-compiled kernels for compute capability 12.0, eliminating JIT compilation failures.

`pip3 install tf-nightly`

Configure the library path. Ensures TensorFlow can locate CUDA libraries installed by conda. This is persistent and automatic for the environment.

`conda env config vars set LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH`

`conda deactivate`
`conda activate tf_gpu`

This approach provides a stable GPU-enabled TensorFlow installation specifically optimized for RTX 50XX’s architecture.

https://forums.developer.nvidia.com/t/how-can-i-use-my-rtx-5060ti-to-training-model-by-using-tensorflow/350054/4?u=pavansai

**Comment by arrunkumarr** [comment]
Any luck post above on conda?

python -c "import tensorflow as tf; print(tf.__version__); print(tf.config.list_physical_devices('GPU'))"
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1764022577.846089   33696 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1764022579.187975   33696 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2.21.0-dev20251124
[]

**Comment by aryalaadi** [comment]
> pre-compiled kernels for compute capability 12.0, eliminating JIT compilation failures.
> 
> `pip3 install tf-nightly`

tf-nightly[and_cuda] **

**Comment by Syraxius** [comment]
Hi guys :D

For convenience, you can download and install the pre-built and packaged .whl files here (TensorFlow 2.21 stable for Python 3.10, 3.11, 3.12 and 3.13)

https://github.com/Syraxius/TensorflowDockerBuilder/releases/tag/v2.21.0-sm120-cuda128-py310-py313

If needed, you can also build it yourself in Docker using this repository

Tested on my own RTX 5090 but since it targets sm_120 it could work for...
- GeForce RTX 5090
- GeForce RTX 5080
- GeForce RTX 5070 Ti
- GeForce RTX 5070
- GeForce RTX 5060 Ti
- GeForce RTX 5060
- GeForce RTX 5050
- NVIDIA RTX PRO 6000 Blackwell Server Edition
- NVIDIA RTX PRO 4500 Blackwell Server Edition
- NVIDIA RTX PRO 6000 Blackwell Workstation Edition
- NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
- NVIDIA RTX PRO 5000 Blackwell
- NVIDIA RTX PRO 4500 Blackwell
- NVIDIA RTX PRO 4000 Blackwell
- NVIDIA RTX PRO 4000 Blackwell SFF Edition
- NVIDIA RTX PRO 2000 Blackwell

**Comment by TonyEinstein** [comment]
> 在 Ubuntu 24.04 上使用“nvidia-smi”命令显示驱动程序版本：580.95.05 CUDA 版本：13.0 ...
> 
> 在 .venv 环境中运行 `pip3 install tf-nightly[and-cuda]` 时出现错误：
> 
> W0000 00:00:1763102316.477334 4144 cuda_executor.cc:1802] GPU互连信息不可用： 内部：NVML不支持提取结构信息，或者设备未使用NVLink。
> 
> W0000 00:00:1763102316.477348 4144 gpu_device.cc:2362] 无法打开某些 GPU 库。 如果您想使用 GPU，请确保已正确安装上述缺失的库。
> 
> 我需要将 CUDA 从 13.0 版本降级吗？……PyTorch 目前运行正常。

Hi, I was wondering what version of PyTorch works properly on RTX 50 series GPUs?

**Comment by MikeHallettUK** [comment]
PyTorch works properly on RTX 50 series GPU =

pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130

...

**Comment by mihaimaruseac** [comment]
Talking about pytorch here is a little bit spam.

**Comment by MikeHallettUK** [comment]
I was happily using Keras with tf, but then could not get tf working with new GPU: so now Keras works well on Pytorch... untill I can get tf back onto CUDA 13 ...

**Comment by TonyEinstein** [comment]
> I was happily using Keras with tf, but then could not get tf working with new GPU: so now Keras works well on Pytorch... untill I can get tf back onto CUDA 13 ...

After trying with my AI and making some experiments, I finally figured out that as long as you follow this installation command order and use a TensorFlow version 2.10 or later, it will definitely work with the latest 12.0 compute-optimized GPUs.
`
conda install -c conda-forge tensorflow-gpu

conda install -c nvidia cuda cudnn
`

If you're using an older version of TensorFlow, like 2.10, you can still install it on new GPUs with a computing power of 12.0 using the following command - it works for sure! Tested and verified.
`
pip install tensorflow-directml-plugin

pip install numpy==1.26.4
`

**Comment by Venkat6871** [comment]
Hi @MikeHallettUK , thank you for your patience.

Based on the discussion so far, it looks like support for Blackwell GPUs has improved in newer TensorFlow releases. Could you please verify whether this still occurs with the latest stable TensorFlow release? If it does, it would also e helpful to test with the latest tf-nightly in a clean environment.

If the issue is still reproducible, please share the updated logs and your current CUDA, driver, and TensorFlow versions so we can investigate further.

**Comment by MikeHallettUK** [comment]
Ok, will do: away for a few weeks = expect end August.

**Comment by MikeHallettUK** [comment]
pip3 install tensorflow[and-cuda]  => installed ok in fresh empty .venv

Running tftest.py as at top:

~/PycharmProjects/tflow/.venv/bin/python ~/PycharmProjects/tflow/tftest.py 
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787025495.820648   20902 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1787025495.844195   20902 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787025496.589299   20902 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Keras version:  3.15.1
W0000 00:00:1787025497.469518   20902 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15325367331280373782
xla_global_id: -1
]
Tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int64)
W0000 00:00:1787025497.547702   20902 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
dx (None, 8, 16)

Process finished with exit code 0

... so not finding my RTX5080 ...  pip installed CUDA 12.9  {e.g. nvidia-cuda-nvcc-cu12-12.9.86}

I have been running well with CUDA 13 for a year now ....

nvidia-smi
Tue Aug 18 14:04:27 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5080        Off |   00000000:01:00.0  On |                  N/A |
|  0%   32C    P5             25W /  360W |    1245MiB /  16303MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1755      G   /usr/lib/xorg/Xorg                      789MiB |
|    0   N/A  N/A            5992      G   .../8754/usr/lib/firefox/firefox        375MiB |
+-----------------------------------------------------------------------------------------+

**Comment by MikeHallettUK** [comment]
pip3 install tf-nightly[and-cuda] also still seems to be 12.9 ... not yet 13.0 ...

e.g. Collecting nvidia-cublas-cu12<13.0,>=12.5.3.2 (from tf-nightly[and-cuda])

**Comment by Venkat6871** [comment]
Hi @MikeHallettUK,

Thanks for testing this on a fresh environment and sharing the full output.

The latest result appears to be different from the original `CUDA_ERROR_INVALID_PTX` / `CUDA_ERROR_INVALID_HANDLE` failure. TensorFlow 2.21.0 imports successfully, but reports:

```text
Cannot dlopen some GPU libraries
Skipping registering GPU devices...
```

while `nvidia-smi` correctly detects your RTX 5080.

Could you try running the same test after adding the NVIDIA libraries installed inside the virtual environment to `LD_LIBRARY_PATH`?

```bash
export NVIDIA_DIR=$(python3 -c "import nvidia, os; print(os.path.dirname(nvidia.__file__))")
export LD_LIBRARY_PATH=$(echo $NVIDIA_DIR/*/lib | sed -e 's/ /:/g'):$LD_LIBRARY_PATH

python3 tftest.py
```

Then please let us know whether TensorFlow detects the RTX 5080.

The CUDA 13 version reported by `nvidia-smi` and the CUDA 12.x packages installed by TensorFlow's `[and-cuda]` extra are separate pieces, so I would like to verify the library-loading issue first before suggesting a CUDA version change.
Thanks!
