### ISSUE TITLE
tensorflow-gpu crashes without libcuda.so

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#9969]
I'm on a multi-machine cluster where not all the machines have gpus. Previously with 0.11 I could use one tensorflow-gpu installation (either from source or from the provided wheel) on all the machines. I've now upgraded to 1.1, and tensorflow crashes at import on the non-gpu machines:

    ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

My current workaround is to have different tensorflows (cpu or gpu) in different conda environments and load the conda environment based on whether I need to use a gpu or not.

**Comment by yaroslavvb** [comment]
TensorFlow GPU is statically linked against cuda, you need cuda drivers. Having CUDA does not require having a GPU, so a workaround is to install cuda on your non-GPU machines

**Comment by vladfi1** [comment]
So this is expected behavior and I was just lucky somehow with 0.11?

**Comment by yaroslavvb** [comment]
I think it was always this behavior. There was a bit of refactoring in how cuda paths are found, perhaps 0.11 managed to find the libcuda.so on the machine

**Comment by vladfi1** [comment]
According to `locate` the non-gpu machines (at least the ones I checked) don't have libcuda.so. Mystery unsolved I guess :)

**Comment by KashiErez** [comment]
I encountered a similar issue:
I am using nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04 docker image.

While trying to upgrade tensorflow from 0.12.1 to 1.1.0 , I get this error:
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by KashiErez** [comment]
I think it is a bug in tensorflow 1.1.0.
I downgraded to tensorflow 1.0.0, and it works.

Here are the lines from my Dockerfile:

FROM nvidia/cuda:8.0-devel-ubuntu16.04
RUN pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp27-none-linux_x86_64.whl
# RUN pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.1.0-cp27-none-linux_x86_64.whl

**Comment by Jonathan-LeRoux** [comment]
I'm not sure I understand why this issue was marked as Closed. 
We have exactly the same problem: we're on a multi-node slurm cluster where the head node does not have a GPU. In order to run tensorboard on the head node without having to use a separate tensorflow-cpu environment (which is fine too, but that's one more thing to keep track of), we need to have the NVIDIA driver libraries on the head node. 

Fortunately, copying the relevant libraries from one of the compute nodes to the head node does the trick. Unfortunately, there's a bunch of them, together with a host of symbolic links. 
Here's the simplest way I found to get everything in place (replace 384.90 by whatever driver version you have):
#### on a compute node
```
tar cvf /path/to/folder/accessible/from/head/node/libs_nvidia384-90.tar --files-from /dev/null  # create an empty tar file so that we can add files to it
pushd /usr/lib/x86_64-linux-gnu/
for i in `ls *384.90`; do j=`echo $i | sed 's|.384.90||'`; tar rvf /path/to/folder/accessible/from/head/node/libs_nvidia384-90.tar ${j}*; done  # add all relevant files to the .tar
```
#### on head node
```
pushd /usr/lib/x86_64-linux-gnu/
sudo tar xvf /path/to/folder/accessible/from/head/node/libs_nvidia384-90.tar
```
With this, we're now able to run tensorboard on the head node.

**Comment by yaroslavvb** [comment]
It was marked as closed because it was working as intended -- there are two versions of TensorFlow, one that requires cuda libraries, and the one that doesn't, so it's expected that the former will crash without cuda libraries present.

I agree see that it adds to management pain, if someone has an idea of a solution (ie, how to restructure tensorflow to remove static linking requirement) it could make to make a feature request with an overview of how to solve this.

**Comment by Jonathan-LeRoux** [comment]
I see, thanks. My comment is just a hack to work around the issue, hopefully it will be useful to someone in a similar situation.

**Comment by yaroslavvb** [comment]
The proper solution is to use official instructions to install CUDA. You do not need a GPU in order to install CUDA

**Comment by Jonathan-LeRoux** [comment]
We have the CUDA toolkit installed on the head node, but not the CUDA driver. I didn't know it was possible to install the driver without a GPU, but if that's the case, then indeed it sounds like the proper solution.

**Comment by mikeguidry** [comment]
I have setup a brand new gpu tensorflow directly from docker images for testing, and:
mike@i  ~/code/gpu-notebook  docker run -it \                                                                                                                                       ✔  7938  11:43:37
--rm \
--device /dev/nvidia0:/dev/nvidia0 \
--device /dev/nvidiactl:/dev/nvidiactl \
--device /dev/nvidia-uvm:/dev/nvidia-uvm \
-p 8888:8888 \
-v `pwd`:/home/user \
tensorflow/tensorflow:latest-gpu /bin/bash

________                               _______________                
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ / 
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u $(id -u):$(id -g) args...

root@80b83d7a7b89:/# cd /home/user
root@80b83d7a7b89:/home/user# ls
a.py  d  docker-compose.yml
root@80b83d7a7b89:/home/user# python a.py
Traceback (most recent call last):
  File "a.py", line 3, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
root@80b83d7a7b89:/home/user#


I believe this is official tensorflow docker images, and the python file I found for benchmarking doesn't seem to request cuda:
import sys
import numpy as np
import tensorflow as tf
from datetime import datetime

device_name = sys.argv[1]  # Choose device from cmd line. Options: gpu or cpu
shape = (int(sys.argv[2]), int(sys.argv[2]))
if device_name == "gpu":
    device_name = "/gpu:0"
else:
    device_name = "/cpu:0"

with tf.device(device_name):
    random_matrix = tf.random_uniform(shape=shape, minval=0, maxval=1)
    dot_operation = tf.matmul(random_matrix, tf.transpose(random_matrix))
    sum_operation = tf.reduce_sum(dot_operation)

startTime = datetime.now()
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as session:
        result = session.run(sum_operation)
        print(result)

# It can be hard to see the results on the terminal with lots of output -- add some newlines to improve readability.
print("\n" * 5)
print("Shape:", shape, "Device:", device_name)
print("Time taken:", str(datetime.now() - startTime))



I believe this if not a bug should never not be considered "how it is meant to be."  I think its amazing that I spent 4 days on a weird connection failing to pull various images, libraries with bazel, and such.  The docker image finally worked out fine through another solution.  If these other scenarios aren't an issue then I love the idea of "production levels" of "development stacks."

I'll obviously go and figure it out however it would be cooler if it just worked as people expect it.. ;)

**Comment by mikeguidry** [comment]
I had a similar issue, and it was solved using nvidia-docker instead of just docker.  It is just the difference between the forced runtime, and regular in my case.  The error message doesn't give information about the shared library failing to load during its initialization.  It seems to respond as if it is missing..
